# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

from scipy.special import expit

from sklearn.frozen import FrozenEstimator
from sklearn.metrics import roc_auc_score
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import StackingClassifier
from sklearn.calibration import CalibratedClassifierCV
from sklearn.inspection import permutation_importance
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, StratifiedKFold, train_test_split, cross_val_predict

from feature_engine.encoding import RareLabelEncoder
from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

In [3]:
def dump_pickle(file_obj, file_path):
    with open(file_path, 'bw') as file:
        pickle.dump(file_obj, file)


def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)


def voting_cross_val_predict(probas: list[np.ndarray], weights: np.ndarray[float]) -> np.ndarray[float]:
    weights /= weights.sum()
    return np.sum([proba * weight for proba, weight in zip(probas, weights)], axis=0)

# Loading Dataset

In [4]:
X_train_proba = pd.read_parquet('../data/processed/X_train_stacking.parquet')
X_test_proba = pd.read_parquet('../data/processed/X_test_stacking.parquet')

In [5]:
X_train = pd.read_parquet('../data/processed/X_train.parquet')
X_test = pd.read_parquet('../data/processed/X_test.parquet')

y_train = pd.read_parquet('../data/processed/y_train.parquet')

In [6]:
X_train_proba.head()

   lgbm_proba  cat_proba  xgb_proba  hist_proba  lg_proba  knn_proba
0    0.802607   0.891870   0.895659    0.883947  0.808497   0.887454
1    0.649405   0.831360   0.829854    0.779541  0.689888   0.519966
2    0.505904   0.851809   0.751522    0.758911  0.558520   0.209855
3    0.001713   0.005910   0.007057    0.007298  0.002275   0.000000
4    0.392205   0.565506   0.489033    0.482967  0.414144   0.297043

In [7]:
X_train.head()

,driver,compound,race,year,pitstop,lapnumber,stint,tyrelife,position,laptime_s,...,treeraceprogress,treeposition,treelaptime_s,treecumulative_degradation,treeraceprogress_position,treeraceprogress_laptime_s,treeraceprogress_cumulative_degradation,treeposition_laptime_s,treeposition_cumulative_degradation,treelaptime_s_cumulative_degradation
id,,,,,,,,,,,,,,,,,,,,,
0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,...,0.298107,0.207392,0.252153,0.279021,0.298107,0.298107,0.321361,0.252153,0.279021,0.253721
1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,...,0.298107,0.185508,0.252153,0.586119,0.298107,0.298107,0.610176,0.252153,0.544023,0.613159
2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,...,0.298107,0.207392,0.252153,0.207676,0.298107,0.298107,0.423519,0.252153,0.228194,0.231339
3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,...,0.102471,0.185508,0.178575,0.138352,0.102471,0.102471,0.043550,0.178575,0.138352,0.070991
4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,...,0.298107,0.185508,0.178575,0.138352,0.298107,0.298107,0.206543,0.178575,0.138352,0.153276

# Feature Engineering

## Ridge

In [8]:
ridge = load_pickle('../models/model_ridge.pkl')

In [9]:
X_train_proba['ridge_logit'] = cross_val_predict(ridge, X_train, y_train.PitNextLap,  cv=StratifiedKFold(shuffle=True), n_jobs=-1, method='decision_function')
X_test_proba['ridge_logit'] = ridge.decision_function(X_test)

## Voting Classifier

In [10]:
X_train_proba['voting_lgbm_cat_xgb_hist_proba'] = voting_cross_val_predict(
    [
        X_train_proba['lgbm_proba'],
        X_train_proba['cat_proba'],
        X_train_proba['xgb_proba'],
        X_train_proba['hist_proba']
    ], 
    weights=np.power([0.9484150827066593, 0.9481909576979181, 0.9477770044293032, 0.9485545192992528], 2)
)

In [11]:
X_train_proba['voting_lg_ridge_proba'] = voting_cross_val_predict(
    [
        X_train_proba['lg_proba'],
        X_train_proba['ridge_logit'].apply(expit),
    ],
    weights=np.power([0.8934924863693583, 0.8880861768599859], 2)
)

In [12]:
X_test_proba['voting_lgbm_cat_xgb_hist_proba'] = voting_cross_val_predict(
    [
        X_test_proba['lgbm_proba'],
        X_test_proba['cat_proba'],
        X_test_proba['xgb_proba'],
        X_test_proba['hist_proba']
    ], 
    weights=np.power([0.9484150827066593, 0.9481909576979181, 0.9477770044293032, 0.9485545192992528], 2)
)

In [14]:
X_test_proba['voting_lg_ridge_proba'] = voting_cross_val_predict(
    [
        X_test_proba['lg_proba'],
        X_test_proba['ridge_logit'],
    ], 
    weights=np.power([0.8934924863693583, 0.8880861768599859], 2)
)

# Machine Learning

######

In [15]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "objective": "binary",
        "n_estimators": trial.suggest_int("n_estimators", 30, 300),
        "learning_rate": trial.suggest_float("learning_rate", 0.003, 0.05, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 4),
        "num_leaves": trial.suggest_int("num_leaves", 2, 16),
        "min_child_samples": trial.suggest_int("min_child_samples", 20, 300),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-5, 100, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-5, 100, log=True),
        "verbosity": -1,
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LGBMClassifier(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

features_to_use = ['voting_lg_ridge_proba', 'knn_proba', 'voting_lgbm_cat_xgb_hist_proba']

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train_proba[features_to_use], y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-19 12:45:39,836] A new study created in memory with name: no-name-63a7376b-b1d7-4155-8b41-66465b223f0e
Best trial: 3. Best value: 0.946484:   0%|▏                                                                                                               | 1/500 [00:08<1:14:28,  8.95s/it]

[I 2026-05-19 12:45:48,768] Trial 3 finished with value: 0.9464844234063283 and parameters: {'n_estimators': 85, 'learning_rate': 0.04851550912367974, 'max_depth': 1, 'num_leaves': 3, 'min_child_samples': 63, 'subsample': 0.6292609612335408, 'colsample_bytree': 0.6727145721178005, 'reg_alpha': 4.9444203185243536e-05, 'reg_lambda': 4.463207248916472}. Best is trial 3 with value: 0.9464844234063283.

Best trial: 9. Best value: 0.946977:   1%|▉                                                                                                                 | 4/500 [00:09<12:40,  1.53s/it]

[I 2026-05-19 12:45:49,251] Trial 4 finished with value: 0.9408941025320459 and parameters: {'n_estimators': 96, 'learning_rate': 0.01730313599524915, 'max_depth': 1, 'num_leaves': 4, 'min_child_samples': 192, 'subsample': 0.9903163452610904, 'colsample_bytree': 0.6528573220582258, 'reg_alpha': 0.029972111060422007, 'reg_lambda': 0.15099048361604217}. Best is trial 3 with value: 0.9464844234063283.
[I 2026-05-19 12:45:49,348] Trial 0 finished with value: 0.9438135178695912 and parameters: {'n_estimators': 64, 'learning_rate': 0.012605723444627044, 'max_depth': 2, 'num_leaves': 16, 'min_child_samples': 151, 'subsample': 0.9376317719808214, 'colsample_bytree': 0.752366659695173, 'reg_alpha': 24.71610552599812, 'reg_lambda': 1.2588735460810603}. Best is trial 3 with value: 0.9464844234063283.
[I 2026-05-19 12:45:49,427] Trial 9 finished with value: 0.9469769567958007 and parameters: {'n_estimators': 56, 'learning_rate': 0.03305384650485767, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 60, 'subsample': 0.9797127344812876, 'colsample_bytree': 0.7087397738067126, 'reg_alpha': 12.97176353485007, 'reg_lambda': 3.51019582286509}. Best is trial 9 with value: 0.9469769567958007.

Best trial: 9. Best value: 0.946977:   1%|█▏                                                                                                                | 5/500 [00:11<13:13,  1.60s/it]

[I 2026-05-19 12:45:51,175] Trial 1 finished with value: 0.9320599811754964 and parameters: {'n_estimators': 119, 'learning_rate': 0.0071104875111449055, 'max_depth': 1, 'num_leaves': 14, 'min_child_samples': 35, 'subsample': 0.8578707806426599, 'colsample_bytree': 0.7525945571813585, 'reg_alpha': 9.569543047947356e-05, 'reg_lambda': 0.00040219535011857253}. Best is trial 9 with value: 0.9469769567958007.

Best trial: 9. Best value: 0.946977:   1%|█▎                                                                                                                | 6/500 [00:13<13:41,  1.66s/it]

[I 2026-05-19 12:45:52,974] Trial 8 pruned.

Best trial: 9. Best value: 0.946977:   2%|█▊                                                                                                                | 8/500 [00:15<10:03,  1.23s/it]

[I 2026-05-19 12:45:54,746] Trial 16 pruned.
[I 2026-05-19 12:45:54,891] Trial 10 pruned.

Best trial: 9. Best value: 0.946977:   2%|██                                                                                                                | 9/500 [00:16<09:31,  1.16s/it]

[I 2026-05-19 12:45:55,921] Trial 15 pruned.

Best trial: 6. Best value: 0.94707:   2%|██▎                                                                                                               | 10/500 [00:17<10:49,  1.32s/it]

[I 2026-05-19 12:45:57,615] Trial 6 finished with value: 0.9470695847519263 and parameters: {'n_estimators': 80, 'learning_rate': 0.0039715894511531905, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 221, 'subsample': 0.9235507175108151, 'colsample_bytree': 0.6450040865168669, 'reg_alpha': 0.05829977230674599, 'reg_lambda': 3.911147406643764e-05}. Best is trial 6 with value: 0.9470695847519263.

Best trial: 6. Best value: 0.94707:   2%|██▌                                                                                                               | 11/500 [00:18<09:54,  1.22s/it]

[I 2026-05-19 12:45:58,575] Trial 17 pruned.

Best trial: 7. Best value: 0.949429:   2%|██▋                                                                                                              | 12/500 [00:20<12:12,  1.50s/it]

[I 2026-05-19 12:46:00,732] Trial 7 finished with value: 0.9494287898236469 and parameters: {'n_estimators': 123, 'learning_rate': 0.016974479657413853, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 55, 'subsample': 0.603242147975055, 'colsample_bytree': 0.9151562466880895, 'reg_alpha': 0.00040677167697138287, 'reg_lambda': 2.8721332662918305e-05}. Best is trial 7 with value: 0.9494287898236469.

Best trial: 7. Best value: 0.949429:   3%|██▉                                                                                                              | 13/500 [00:23<14:29,  1.79s/it]

[I 2026-05-19 12:46:03,193] Trial 18 pruned.

Best trial: 2. Best value: 0.949492:   3%|███▏                                                                                                             | 14/500 [00:29<25:33,  3.16s/it]

[I 2026-05-19 12:46:09,529] Trial 2 finished with value: 0.9494922302225415 and parameters: {'n_estimators': 283, 'learning_rate': 0.015411247433592581, 'max_depth': 2, 'num_leaves': 3, 'min_child_samples': 239, 'subsample': 0.9769919572790409, 'colsample_bytree': 0.8896196323887355, 'reg_alpha': 0.3752078765456314, 'reg_lambda': 0.5249532378772284}. Best is trial 2 with value: 0.9494922302225415.

Best trial: 2. Best value: 0.949492:   3%|███▍                                                                                                             | 15/500 [00:30<20:00,  2.48s/it]

[I 2026-05-19 12:46:10,434] Trial 5 finished with value: 0.9468807739259217 and parameters: {'n_estimators': 283, 'learning_rate': 0.006860106513596281, 'max_depth': 4, 'num_leaves': 3, 'min_child_samples': 49, 'subsample': 0.7423362495171245, 'colsample_bytree': 0.8494848084519424, 'reg_alpha': 1.7510657299999802e-05, 'reg_lambda': 27.059472664419303}. Best is trial 2 with value: 0.9494922302225415.

Best trial: 2. Best value: 0.949492:   3%|███▌                                                                                                             | 16/500 [00:34<23:22,  2.90s/it]

[I 2026-05-19 12:46:14,314] Trial 12 finished with value: 0.9472089944738127 and parameters: {'n_estimators': 176, 'learning_rate': 0.014423361634722428, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 193, 'subsample': 0.8134109047420424, 'colsample_bytree': 0.7945084633735113, 'reg_alpha': 3.5667184747934857, 'reg_lambda': 1.8920181005957608}. Best is trial 2 with value: 0.9494922302225415.

Best trial: 14. Best value: 0.949592:   3%|███▊                                                                                                            | 17/500 [00:38<26:25,  3.28s/it]

[I 2026-05-19 12:46:18,482] Trial 14 finished with value: 0.9495915058237612 and parameters: {'n_estimators': 252, 'learning_rate': 0.021539503832538966, 'max_depth': 2, 'num_leaves': 5, 'min_child_samples': 277, 'subsample': 0.8803493843829138, 'colsample_bytree': 0.9095586102665238, 'reg_alpha': 4.804984069940626e-05, 'reg_lambda': 0.05296618943437208}. Best is trial 14 with value: 0.9495915058237612.

Best trial: 14. Best value: 0.949592:   4%|████                                                                                                            | 18/500 [00:39<20:27,  2.55s/it]

[I 2026-05-19 12:46:19,319] Trial 13 finished with value: 0.94827716494577 and parameters: {'n_estimators': 154, 'learning_rate': 0.0032096431757980574, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 98, 'subsample': 0.9990542306866546, 'colsample_bytree': 0.8453663150624002, 'reg_alpha': 0.04130345704830444, 'reg_lambda': 29.660911001394197}. Best is trial 14 with value: 0.9495915058237612.

Best trial: 20. Best value: 0.94969:   4%|████▎                                                                                                            | 19/500 [00:44<26:17,  3.28s/it]

[I 2026-05-19 12:46:24,306] Trial 20 finished with value: 0.94968965680042 and parameters: {'n_estimators': 215, 'learning_rate': 0.02713036748418551, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 213, 'subsample': 0.75335389717971, 'colsample_bytree': 0.947374394080218, 'reg_alpha': 0.010270008776983823, 'reg_lambda': 1.4143136628416229e-05}. Best is trial 20 with value: 0.94968965680042.

Best trial: 20. Best value: 0.94969:   4%|████▌                                                                                                            | 20/500 [00:44<18:58,  2.37s/it]

[I 2026-05-19 12:46:24,562] Trial 11 finished with value: 0.948642140248759 and parameters: {'n_estimators': 292, 'learning_rate': 0.016287729124711766, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 47, 'subsample': 0.8608122574871038, 'colsample_bytree': 0.7268810417260498, 'reg_alpha': 0.006944848105095275, 'reg_lambda': 1.6419006822456963e-05}. Best is trial 20 with value: 0.94968965680042.

Best trial: 20. Best value: 0.94969:   4%|████▋                                                                                                            | 21/500 [00:46<16:38,  2.09s/it]

[I 2026-05-19 12:46:25,980] Trial 22 finished with value: 0.9462110292875998 and parameters: {'n_estimators': 161, 'learning_rate': 0.00319599436976885, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 242, 'subsample': 0.9773507889629114, 'colsample_bytree': 0.6017549032877387, 'reg_alpha': 2.0060863666356377, 'reg_lambda': 0.006868013351179461}. Best is trial 20 with value: 0.94968965680042.

Best trial: 20. Best value: 0.94969:   4%|████▉                                                                                                            | 22/500 [00:47<14:04,  1.77s/it]

[I 2026-05-19 12:46:26,994] Trial 19 finished with value: 0.9491637756967254 and parameters: {'n_estimators': 214, 'learning_rate': 0.007138725967249065, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 190, 'subsample': 0.7471575115788378, 'colsample_bytree': 0.906371761676426, 'reg_alpha': 0.03349956735872868, 'reg_lambda': 0.04945496783177636}. Best is trial 20 with value: 0.94968965680042.

Best trial: 20. Best value: 0.94969:   5%|█████▏                                                                                                           | 23/500 [00:49<15:48,  1.99s/it]

[I 2026-05-19 12:46:29,499] Trial 21 finished with value: 0.9479162804960997 and parameters: {'n_estimators': 167, 'learning_rate': 0.003049439151547734, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 298, 'subsample': 0.8119019994874035, 'colsample_bytree': 0.8617895979650756, 'reg_alpha': 0.007628281290261393, 'reg_lambda': 0.0053463002328450705}. Best is trial 20 with value: 0.94968965680042.

Best trial: 20. Best value: 0.94969:   5%|█████▍                                                                                                           | 24/500 [00:51<14:41,  1.85s/it]

[I 2026-05-19 12:46:31,027] Trial 23 finished with value: 0.9479161686208718 and parameters: {'n_estimators': 156, 'learning_rate': 0.0033158461309962016, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 254, 'subsample': 0.7748115995668801, 'colsample_bytree': 0.9959317539429029, 'reg_alpha': 0.0011481994819278975, 'reg_lambda': 0.0013272782245358035}. Best is trial 20 with value: 0.94968965680042.

Best trial: 20. Best value: 0.94969:   5%|█████▋                                                                                                           | 25/500 [00:56<22:17,  2.82s/it]

[I 2026-05-19 12:46:36,088] Trial 24 finished with value: 0.9496826114775432 and parameters: {'n_estimators': 166, 'learning_rate': 0.02146499843876306, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 275, 'subsample': 0.7738741990721596, 'colsample_bytree': 0.9859854443353825, 'reg_alpha': 0.002397994316317127, 'reg_lambda': 0.001944687450274903}. Best is trial 20 with value: 0.94968965680042.

Best trial: 20. Best value: 0.94969:   5%|█████▉                                                                                                           | 26/500 [00:57<19:34,  2.48s/it]

[I 2026-05-19 12:46:37,796] Trial 26 finished with value: 0.9495791812594382 and parameters: {'n_estimators': 179, 'learning_rate': 0.02147858998717989, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 286, 'subsample': 0.8062194314524596, 'colsample_bytree': 0.9791115193549463, 'reg_alpha': 0.00431692561737888, 'reg_lambda': 0.004347595377241027}. Best is trial 20 with value: 0.94968965680042.

Best trial: 20. Best value: 0.94969:   5%|██████                                                                                                           | 27/500 [01:01<22:30,  2.86s/it]

[I 2026-05-19 12:46:41,532] Trial 27 finished with value: 0.9495826110601803 and parameters: {'n_estimators': 166, 'learning_rate': 0.02239358630031985, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 297, 'subsample': 0.6917336647348341, 'colsample_bytree': 0.9691491546509647, 'reg_alpha': 0.0009438337564598119, 'reg_lambda': 0.007412976510799847}. Best is trial 20 with value: 0.94968965680042.

Best trial: 25. Best value: 0.949701:   6%|██████▎                                                                                                         | 28/500 [01:12<40:37,  5.16s/it]

[I 2026-05-19 12:46:52,090] Trial 25 finished with value: 0.949700827489637 and parameters: {'n_estimators': 284, 'learning_rate': 0.021317016801310096, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 279, 'subsample': 0.781695264458046, 'colsample_bytree': 0.8783587442921513, 'reg_alpha': 0.0022013314917507226, 'reg_lambda': 0.015448175008530072}. Best is trial 25 with value: 0.949700827489637.

Best trial: 29. Best value: 0.949708:   6%|██████▍                                                                                                         | 29/500 [01:13<31:15,  3.98s/it]

[I 2026-05-19 12:46:53,309] Trial 29 finished with value: 0.949708383155607 and parameters: {'n_estimators': 295, 'learning_rate': 0.027081538485685907, 'max_depth': 2, 'num_leaves': 7, 'min_child_samples': 289, 'subsample': 0.9286065871818053, 'colsample_bytree': 0.9884027687626968, 'reg_alpha': 0.0032535389037995858, 'reg_lambda': 0.013677199888643639}. Best is trial 29 with value: 0.949708383155607.

Best trial: 29. Best value: 0.949708:   6%|██████▋                                                                                                         | 30/500 [01:13<22:42,  2.90s/it]

[I 2026-05-19 12:46:53,686] Trial 28 finished with value: 0.9496802289010431 and parameters: {'n_estimators': 300, 'learning_rate': 0.0232318920112744, 'max_depth': 2, 'num_leaves': 7, 'min_child_samples': 294, 'subsample': 0.9411848227799996, 'colsample_bytree': 0.9854229926613488, 'reg_alpha': 0.003148655286957224, 'reg_lambda': 0.012585626074413946}. Best is trial 29 with value: 0.949708383155607.

Best trial: 29. Best value: 0.949708:   6%|██████▉                                                                                                         | 31/500 [01:14<17:08,  2.19s/it]

[I 2026-05-19 12:46:54,213] Trial 32 finished with value: 0.9496022628196965 and parameters: {'n_estimators': 239, 'learning_rate': 0.023017155735753973, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 283, 'subsample': 0.8010686148382041, 'colsample_bytree': 0.9902500505546864, 'reg_alpha': 0.0010259595030850152, 'reg_lambda': 0.002332255314122336}. Best is trial 29 with value: 0.949708383155607.

Best trial: 29. Best value: 0.949708:   6%|███████▏                                                                                                        | 32/500 [01:16<17:21,  2.23s/it]

[I 2026-05-19 12:46:56,528] Trial 33 finished with value: 0.9496232901459145 and parameters: {'n_estimators': 254, 'learning_rate': 0.02273443761137643, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 279, 'subsample': 0.8040343404444156, 'colsample_bytree': 0.9973407003410767, 'reg_alpha': 0.0019020386753596295, 'reg_lambda': 0.0016192670602539509}. Best is trial 29 with value: 0.949708383155607.

Best trial: 29. Best value: 0.949708:   7%|███████▍                                                                                                        | 33/500 [01:18<15:54,  2.04s/it]

[I 2026-05-19 12:46:58,148] Trial 30 finished with value: 0.9496789183894407 and parameters: {'n_estimators': 228, 'learning_rate': 0.023412021378576207, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 290, 'subsample': 0.8004809891666332, 'colsample_bytree': 0.9973632092040048, 'reg_alpha': 0.0014023441486800397, 'reg_lambda': 0.0035693940959129374}. Best is trial 29 with value: 0.949708383155607.
[I 2026-05-19 12:46:58,157] Trial 31 finished with value: 0.949696088703899 and parameters: {'n_estimators': 233, 'learning_rate': 0.024244026406584247, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 280, 'subsample': 0.8074767985247371, 'colsample_bytree': 0.9792046320994289, 'reg_alpha': 0.0009679073117738277, 'reg_lambda': 0.006068923939029778}. Best is trial 29 with value: 0.949708383155607.

Best trial: 29. Best value: 0.949708:   7%|███████▊                                                                                                        | 35/500 [01:20<13:08,  1.70s/it]

[I 2026-05-19 12:47:00,726] Trial 34 finished with value: 0.9496508822106952 and parameters: {'n_estimators': 266, 'learning_rate': 0.02330109726512932, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 264, 'subsample': 0.9231955263835507, 'colsample_bytree': 0.9963757479054384, 'reg_alpha': 0.0009292895760352132, 'reg_lambda': 0.0013389706606211165}. Best is trial 29 with value: 0.949708383155607.

Best trial: 29. Best value: 0.949708:   7%|████████▎                                                                                                       | 37/500 [01:22<08:58,  1.16s/it]

[I 2026-05-19 12:47:01,717] Trial 35 finished with value: 0.9496241339411464 and parameters: {'n_estimators': 259, 'learning_rate': 0.02238835018338713, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 278, 'subsample': 0.9223136747708048, 'colsample_bytree': 0.995472508586938, 'reg_alpha': 0.5949407981928577, 'reg_lambda': 0.1412169219290104}. Best is trial 29 with value: 0.949708383155607.
[I 2026-05-19 12:47:01,864] Trial 36 finished with value: 0.9495854183230819 and parameters: {'n_estimators': 227, 'learning_rate': 0.02344628141936621, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 274, 'subsample': 0.6992837844993822, 'colsample_bytree': 0.9701832944895505, 'reg_alpha': 0.0015850756752880558, 'reg_lambda': 0.0002521158503246751}. Best is trial 29 with value: 0.949708383155607.

Best trial: 29. Best value: 0.949708:   8%|████████▌                                                                                                       | 38/500 [01:26<15:55,  2.07s/it]

[I 2026-05-19 12:47:06,353] Trial 37 finished with value: 0.9496237065910511 and parameters: {'n_estimators': 247, 'learning_rate': 0.023252126080037946, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 277, 'subsample': 0.7111953039226537, 'colsample_bytree': 0.9663301528100777, 'reg_alpha': 0.0013151059696784476, 'reg_lambda': 0.0002171174724289777}. Best is trial 29 with value: 0.949708383155607.

Best trial: 29. Best value: 0.949708:   8%|████████▋                                                                                                       | 39/500 [01:29<18:12,  2.37s/it]

[I 2026-05-19 12:47:09,494] Trial 38 finished with value: 0.9496912003175652 and parameters: {'n_estimators': 244, 'learning_rate': 0.02948653908524645, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 273, 'subsample': 0.6977648870682357, 'colsample_bytree': 0.9616158681075364, 'reg_alpha': 0.002323668087197872, 'reg_lambda': 0.00022805395157648615}. Best is trial 29 with value: 0.949708383155607.

[I 2026-05-19 12:47:22,296] Trial 40 finished with value: 0.949695339600658 and parameters: {'n_estimators': 251, 'learning_rate': 0.030160354977121884, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 253, 'subsample': 0.7055531385103806, 'colsample_bytree': 0.9502836989047309, 'reg_alpha': 0.013222952562051507, 'reg_lambda': 0.0001371307614476311}. Best is trial 29 with value: 0.949708383155607.

Best trial: 41. Best value: 0.949709:   8%|█████████▏                                                                                                      | 41/500 [01:42<29:30,  3.86s/it]

[I 2026-05-19 12:47:22,495] Trial 41 finished with value: 0.949709065150806 and parameters: {'n_estimators': 259, 'learning_rate': 0.03220346890099525, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 257, 'subsample': 0.7139095996117447, 'colsample_bytree': 0.9535306155113202, 'reg_alpha': 0.01598183576524627, 'reg_lambda': 0.00025126494177076804}. Best is trial 41 with value: 0.949709065150806.

Best trial: 41. Best value: 0.949709:   8%|█████████▍                                                                                                      | 42/500 [01:44<24:56,  3.27s/it]

[I 2026-05-19 12:47:24,345] Trial 39 finished with value: 0.949694930340295 and parameters: {'n_estimators': 207, 'learning_rate': 0.02863512893332934, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 268, 'subsample': 0.7020036685607581, 'colsample_bytree': 0.9534352579759582, 'reg_alpha': 0.002491584493248269, 'reg_lambda': 0.0004658040898667917}. Best is trial 41 with value: 0.949709065150806.

Best trial: 43. Best value: 0.949718:   9%|█████████▋                                                                                                      | 43/500 [01:51<32:40,  4.29s/it]

[I 2026-05-19 12:47:31,087] Trial 43 finished with value: 0.949717959584528 and parameters: {'n_estimators': 224, 'learning_rate': 0.031553697748399945, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 255, 'subsample': 0.7092089485931132, 'colsample_bytree': 0.9543586624793907, 'reg_alpha': 0.012527088514797712, 'reg_lambda': 0.00034500732088317435}. Best is trial 43 with value: 0.949717959584528.

Best trial: 43. Best value: 0.949718:   9%|█████████▊                                                                                                      | 44/500 [01:55<31:45,  4.18s/it]

[I 2026-05-19 12:47:34,983] Trial 47 finished with value: 0.949717433286858 and parameters: {'n_estimators': 273, 'learning_rate': 0.030363582704989355, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 217, 'subsample': 0.7079648903531341, 'colsample_bytree': 0.9521972811569235, 'reg_alpha': 0.01325694122142538, 'reg_lambda': 0.00018793272083130952}. Best is trial 43 with value: 0.949717959584528.

Best trial: 42. Best value: 0.949727:   9%|██████████                                                                                                      | 45/500 [01:55<23:56,  3.16s/it]

[I 2026-05-19 12:47:35,745] Trial 42 finished with value: 0.949727313111584 and parameters: {'n_estimators': 264, 'learning_rate': 0.03035484090721904, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 265, 'subsample': 0.7057402677559308, 'colsample_bytree': 0.955054084634444, 'reg_alpha': 0.01187644814667548, 'reg_lambda': 0.00018204775665428652}. Best is trial 42 with value: 0.949727313111584.

Best trial: 45. Best value: 0.949732:   9%|██████████▎                                                                                                     | 46/500 [01:59<24:18,  3.21s/it]

[I 2026-05-19 12:47:39,070] Trial 45 finished with value: 0.9497319513326035 and parameters: {'n_estimators': 269, 'learning_rate': 0.03123773873423486, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 259, 'subsample': 0.7191795509531937, 'colsample_bytree': 0.9501597134204319, 'reg_alpha': 0.00035190399767786397, 'reg_lambda': 0.0002172179406783379}. Best is trial 45 with value: 0.9497319513326035.

Best trial: 45. Best value: 0.949732:   9%|██████████▌                                                                                                     | 47/500 [01:59<17:46,  2.35s/it]

[I 2026-05-19 12:47:39,419] Trial 44 finished with value: 0.9497312565518736 and parameters: {'n_estimators': 275, 'learning_rate': 0.030779936816334074, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 260, 'subsample': 0.7094156276188486, 'colsample_bytree': 0.9522140049149641, 'reg_alpha': 0.013831326515440282, 'reg_lambda': 0.00018272461798390493}. Best is trial 45 with value: 0.9497319513326035.

Best trial: 45. Best value: 0.949732:  10%|██████████▊                                                                                                     | 48/500 [02:00<13:46,  1.83s/it]

[I 2026-05-19 12:47:40,013] Trial 49 finished with value: 0.9497197428499978 and parameters: {'n_estimators': 277, 'learning_rate': 0.031189964664887847, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 244, 'subsample': 0.8355438512099298, 'colsample_bytree': 0.9314394391067736, 'reg_alpha': 0.017127173732685397, 'reg_lambda': 0.14904079737350706}. Best is trial 45 with value: 0.9497319513326035.

Best trial: 46. Best value: 0.949733:  10%|██████████▉                                                                                                     | 49/500 [02:02<14:58,  1.99s/it]

[I 2026-05-19 12:47:42,385] Trial 46 finished with value: 0.9497329293927054 and parameters: {'n_estimators': 274, 'learning_rate': 0.03133760856940984, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 226, 'subsample': 0.7166310518423762, 'colsample_bytree': 0.9500676709091347, 'reg_alpha': 0.014401040965445623, 'reg_lambda': 0.00027174099320899863}. Best is trial 46 with value: 0.9497329293927054.

Best trial: 46. Best value: 0.949733:  10%|███████████▏                                                                                                    | 50/500 [02:04<14:19,  1.91s/it]

[I 2026-05-19 12:47:44,093] Trial 48 finished with value: 0.9497286687517779 and parameters: {'n_estimators': 273, 'learning_rate': 0.030055660946199513, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 227, 'subsample': 0.8389452010202179, 'colsample_bytree': 0.9400791928289515, 'reg_alpha': 0.0002762831127096467, 'reg_lambda': 0.00019338533724943613}. Best is trial 46 with value: 0.9497329293927054.

Best trial: 50. Best value: 0.949733:  10%|███████████▍                                                                                                    | 51/500 [02:09<22:03,  2.95s/it]

[I 2026-05-19 12:47:49,483] Trial 50 finished with value: 0.9497330180193911 and parameters: {'n_estimators': 271, 'learning_rate': 0.047919313034031366, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 240, 'subsample': 0.6592185289076148, 'colsample_bytree': 0.8822716455285876, 'reg_alpha': 0.00019580936952427142, 'reg_lambda': 0.0004164472512151424}. Best is trial 50 with value: 0.9497330180193911.

Best trial: 50. Best value: 0.949733:  10%|███████████▋                                                                                                    | 52/500 [02:23<46:04,  6.17s/it]

[I 2026-05-19 12:48:03,174] Trial 52 finished with value: 0.9497319516272643 and parameters: {'n_estimators': 275, 'learning_rate': 0.04290424671087653, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 249, 'subsample': 0.6653667359473956, 'colsample_bytree': 0.8917587086582764, 'reg_alpha': 0.014096096026411903, 'reg_lambda': 0.0006046662467507839}. Best is trial 50 with value: 0.9497330180193911.

Best trial: 50. Best value: 0.949733:  11%|███████████▊                                                                                                    | 53/500 [02:23<32:57,  4.42s/it]

[I 2026-05-19 12:48:03,531] Trial 53 finished with value: 0.9497317950027823 and parameters: {'n_estimators': 275, 'learning_rate': 0.04590177208768697, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 245, 'subsample': 0.6458816266245249, 'colsample_bytree': 0.8853151925810786, 'reg_alpha': 0.016536660468856924, 'reg_lambda': 8.829196564726888e-05}. Best is trial 50 with value: 0.9497330180193911.

Best trial: 50. Best value: 0.949733:  11%|████████████                                                                                                    | 54/500 [02:24<25:15,  3.40s/it]

[I 2026-05-19 12:48:04,539] Trial 51 finished with value: 0.9497309021728337 and parameters: {'n_estimators': 286, 'learning_rate': 0.04557255545083949, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 243, 'subsample': 0.6645108295513565, 'colsample_bytree': 0.8813152128255359, 'reg_alpha': 0.00019756418507683063, 'reg_lambda': 0.0006888608790406019}. Best is trial 50 with value: 0.9497330180193911.

Best trial: 54. Best value: 0.949733:  11%|████████████▎                                                                                                   | 55/500 [02:30<29:55,  4.03s/it]

[I 2026-05-19 12:48:10,042] Trial 54 finished with value: 0.9497331596126726 and parameters: {'n_estimators': 275, 'learning_rate': 0.045632622481985984, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 242, 'subsample': 0.6507803209460132, 'colsample_bytree': 0.8808755185294362, 'reg_alpha': 0.000321861519447395, 'reg_lambda': 0.0007242208794681986}. Best is trial 54 with value: 0.9497331596126726.

Best trial: 55. Best value: 0.949737:  11%|████████████▌                                                                                                   | 56/500 [02:35<32:33,  4.40s/it]

[I 2026-05-19 12:48:15,299] Trial 55 finished with value: 0.9497374666915765 and parameters: {'n_estimators': 277, 'learning_rate': 0.045351816197057915, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 238, 'subsample': 0.6609716708107947, 'colsample_bytree': 0.8862293415494368, 'reg_alpha': 0.0942506263232132, 'reg_lambda': 0.0006538352261808682}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  11%|████████████▊                                                                                                   | 57/500 [02:36<24:51,  3.37s/it]

[I 2026-05-19 12:48:16,253] Trial 56 finished with value: 0.949730591431798 and parameters: {'n_estimators': 270, 'learning_rate': 0.04735613537783183, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 236, 'subsample': 0.6534998554967302, 'colsample_bytree': 0.9273719166675655, 'reg_alpha': 0.01555465866265839, 'reg_lambda': 9.000019197091435e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  12%|█████████████▍                                                                                                  | 60/500 [02:39<13:35,  1.85s/it]

[I 2026-05-19 12:48:19,677] Trial 59 finished with value: 0.9497341182822246 and parameters: {'n_estimators': 270, 'learning_rate': 0.041739507169376716, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 235, 'subsample': 0.6647622025809984, 'colsample_bytree': 0.8925917060775982, 'reg_alpha': 0.07545976803606212, 'reg_lambda': 8.728422010707514e-05}. Best is trial 55 with value: 0.9497374666915765.
[I 2026-05-19 12:48:19,771] Trial 58 finished with value: 0.9497341696460169 and parameters: {'n_estimators': 272, 'learning_rate': 0.042916017325679436, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 244, 'subsample': 0.6584059274546189, 'colsample_bytree': 0.9192577021974982, 'reg_alpha': 0.13804900998144534, 'reg_lambda': 5.819762336973197e-05}. Best is trial 55 with value: 0.9497374666915765.
[I 2026-05-19 12:48:19,772] Trial 57 finished with value: 0.9497322718332034 and parameters: {'n_estimators': 271, 'learning_rate': 0.043385755926986715, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 236, 'subsample': 0.6646498484650388, 'colsample_bytree': 0.9307656732318079, 'reg_alpha': 0.07533155276036088, 'reg_lambda': 7.862505644939087e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  12%|█████████████▋                                                                                                  | 61/500 [02:43<15:40,  2.14s/it]

[I 2026-05-19 12:48:22,841] Trial 60 finished with value: 0.9497342816136216 and parameters: {'n_estimators': 277, 'learning_rate': 0.040553046122096544, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 234, 'subsample': 0.6625123998833873, 'colsample_bytree': 0.9217827749814065, 'reg_alpha': 0.09666294057068667, 'reg_lambda': 0.0006352600740463124}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  12%|█████████████▉                                                                                                  | 62/500 [02:43<12:42,  1.74s/it]

[I 2026-05-19 12:48:23,448] Trial 69 pruned.

Best trial: 55. Best value: 0.949737:  13%|██████████████                                                                                                  | 63/500 [02:45<13:44,  1.89s/it]

[I 2026-05-19 12:48:25,718] Trial 61 finished with value: 0.949733836541401 and parameters: {'n_estimators': 286, 'learning_rate': 0.04255791609998895, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 232, 'subsample': 0.6542777756559849, 'colsample_bytree': 0.9213107066729963, 'reg_alpha': 0.000239761774140776, 'reg_lambda': 0.0007777686537912869}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  13%|██████████████▎                                                                                                 | 64/500 [02:49<17:32,  2.41s/it]

[I 2026-05-19 12:48:29,483] Trial 62 finished with value: 0.949731610986057 and parameters: {'n_estimators': 283, 'learning_rate': 0.043991301123776264, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 233, 'subsample': 0.6565152421852999, 'colsample_bytree': 0.9183367794933838, 'reg_alpha': 0.00018007217402965563, 'reg_lambda': 7.822953208586441e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  13%|██████████████▌                                                                                                 | 65/500 [03:03<40:26,  5.58s/it]

[I 2026-05-19 12:48:42,966] Trial 63 finished with value: 0.9497268090411092 and parameters: {'n_estimators': 285, 'learning_rate': 0.04971852288464925, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 231, 'subsample': 0.6603408031803287, 'colsample_bytree': 0.8843853230419136, 'reg_alpha': 0.0002059885801226707, 'reg_lambda': 7.492446499726262e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  13%|██████████████▊                                                                                                 | 66/500 [03:06<34:58,  4.83s/it]

[I 2026-05-19 12:48:46,000] Trial 64 finished with value: 0.9496090093232888 and parameters: {'n_estimators': 285, 'learning_rate': 0.04438117978036887, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 230, 'subsample': 0.6570362272224122, 'colsample_bytree': 0.8210197751068181, 'reg_alpha': 0.06211858135021354, 'reg_lambda': 7.183644199012565e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  13%|███████████████                                                                                                 | 67/500 [03:08<29:34,  4.10s/it]

[I 2026-05-19 12:48:48,314] Trial 65 finished with value: 0.9495894130442718 and parameters: {'n_estimators': 289, 'learning_rate': 0.03967959794678066, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 230, 'subsample': 0.6548262902825139, 'colsample_bytree': 0.8167205686771117, 'reg_alpha': 0.0703585222402177, 'reg_lambda': 6.571350230531696e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  14%|███████████████▏                                                                                                | 68/500 [03:13<30:58,  4.30s/it]

[I 2026-05-19 12:48:53,103] Trial 66 finished with value: 0.9495939045061649 and parameters: {'n_estimators': 290, 'learning_rate': 0.04037868835226915, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 197, 'subsample': 0.654112244465471, 'colsample_bytree': 0.8325713142505907, 'reg_alpha': 1.1375535179964632e-05, 'reg_lambda': 8.190758711963359e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  14%|███████████████▍                                                                                                | 69/500 [03:18<32:00,  4.46s/it]

[I 2026-05-19 12:48:57,914] Trial 68 finished with value: 0.9497339017606109 and parameters: {'n_estimators': 288, 'learning_rate': 0.0387967807945628, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 205, 'subsample': 0.6750507641488339, 'colsample_bytree': 0.8340390828882351, 'reg_alpha': 8.478130653730368e-05, 'reg_lambda': 4.807195945428388e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  14%|███████████████▋                                                                                                | 70/500 [03:19<24:56,  3.48s/it]

[I 2026-05-19 12:48:59,098] Trial 67 finished with value: 0.9495799412653149 and parameters: {'n_estimators': 290, 'learning_rate': 0.03864114612844602, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 233, 'subsample': 0.6694655090083329, 'colsample_bytree': 0.8253052572987487, 'reg_alpha': 1.0386577484625906e-05, 'reg_lambda': 0.0007563341792810148}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  14%|███████████████▉                                                                                                | 71/500 [03:22<25:07,  3.51s/it]

[I 2026-05-19 12:49:02,696] Trial 71 finished with value: 0.9495701164535715 and parameters: {'n_estimators': 290, 'learning_rate': 0.03768419304571476, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 201, 'subsample': 0.6292326432147737, 'colsample_bytree': 0.822966776643265, 'reg_alpha': 0.1485258459868627, 'reg_lambda': 2.7061746728109072e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  14%|████████████████▏                                                                                               | 72/500 [03:23<19:54,  2.79s/it]

[I 2026-05-19 12:49:03,789] Trial 70 finished with value: 0.9495717341119334 and parameters: {'n_estimators': 289, 'learning_rate': 0.037980782413943266, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 204, 'subsample': 0.6298401688750419, 'colsample_bytree': 0.823368228126006, 'reg_alpha': 0.1583259686388889, 'reg_lambda': 4.0395615633105904e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  15%|████████████████▌                                                                                               | 74/500 [03:26<13:09,  1.85s/it]

[I 2026-05-19 12:49:05,856] Trial 73 finished with value: 0.9497363272155003 and parameters: {'n_estimators': 288, 'learning_rate': 0.037019702727514626, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 148, 'subsample': 0.628430672213748, 'colsample_bytree': 0.9126428527423306, 'reg_alpha': 0.2252862111315816, 'reg_lambda': 3.6391872591263966e-05}. Best is trial 55 with value: 0.9497374666915765.
[I 2026-05-19 12:49:05,996] Trial 72 finished with value: 0.9495592452998818 and parameters: {'n_estimators': 287, 'learning_rate': 0.03720356604488178, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 205, 'subsample': 0.6254506792697175, 'colsample_bytree': 0.8310868222681987, 'reg_alpha': 1.0386937871370382e-05, 'reg_lambda': 4.2645226427619515e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  15%|████████████████▊                                                                                               | 75/500 [03:27<11:46,  1.66s/it]

[I 2026-05-19 12:49:07,231] Trial 74 finished with value: 0.9497363234368199 and parameters: {'n_estimators': 289, 'learning_rate': 0.03753420752824654, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 183, 'subsample': 0.621326373735803, 'colsample_bytree': 0.9055678772355964, 'reg_alpha': 0.35199683198433246, 'reg_lambda': 4.085793168892248e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  15%|█████████████████                                                                                               | 76/500 [03:41<38:47,  5.49s/it]

[I 2026-05-19 12:49:21,660] Trial 75 finished with value: 0.9497200383162452 and parameters: {'n_estimators': 291, 'learning_rate': 0.036791101138746216, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 164, 'subsample': 0.625418695471251, 'colsample_bytree': 0.8986087850165004, 'reg_alpha': 7.805329883829126e-05, 'reg_lambda': 3.5193448749380415e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  15%|█████████████████▏                                                                                              | 77/500 [03:54<54:50,  7.78s/it]

[I 2026-05-19 12:49:34,787] Trial 86 finished with value: 0.9494605533070611 and parameters: {'n_estimators': 141, 'learning_rate': 0.010291256185347233, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 156, 'subsample': 0.682045250373208, 'colsample_bytree': 0.9089812781747355, 'reg_alpha': 0.969653338386265, 'reg_lambda': 2.175945290364094e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  16%|█████████████████▍                                                                                              | 78/500 [03:57<43:44,  6.22s/it]

[I 2026-05-19 12:49:37,367] Trial 76 finished with value: 0.9497203251130818 and parameters: {'n_estimators': 300, 'learning_rate': 0.0374148393040773, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 164, 'subsample': 0.6328567618391485, 'colsample_bytree': 0.8997195041414787, 'reg_alpha': 0.21287421350361255, 'reg_lambda': 3.3768886764459455e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  16%|█████████████████▋                                                                                              | 79/500 [03:58<32:49,  4.68s/it]

[I 2026-05-19 12:49:38,447] Trial 77 finished with value: 0.949722518273808 and parameters: {'n_estimators': 296, 'learning_rate': 0.03736241151133498, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 181, 'subsample': 0.6283372969883066, 'colsample_bytree': 0.9049598275793324, 'reg_alpha': 0.2560866473772122, 'reg_lambda': 2.1025776987125328e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  16%|█████████████████▉                                                                                              | 80/500 [04:00<26:06,  3.73s/it]

[I 2026-05-19 12:49:39,961] Trial 78 finished with value: 0.9497194888577971 and parameters: {'n_estimators': 299, 'learning_rate': 0.03587711184265902, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 179, 'subsample': 0.6279457314546881, 'colsample_bytree': 0.9013033741742251, 'reg_alpha': 1.1459554374078029e-05, 'reg_lambda': 2.627480351602762e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  16%|██████████████████▏                                                                                             | 81/500 [04:04<26:56,  3.86s/it]

[I 2026-05-19 12:49:44,127] Trial 79 finished with value: 0.9497234422575362 and parameters: {'n_estimators': 298, 'learning_rate': 0.03570375123973209, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 177, 'subsample': 0.6280727943813752, 'colsample_bytree': 0.9017959965377897, 'reg_alpha': 9.097501349648682e-05, 'reg_lambda': 3.699893423759189e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  16%|██████████████████▎                                                                                             | 82/500 [04:08<28:28,  4.09s/it]

[I 2026-05-19 12:49:48,757] Trial 80 finished with value: 0.9497203804234762 and parameters: {'n_estimators': 294, 'learning_rate': 0.03612670825957582, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 165, 'subsample': 0.626914479231598, 'colsample_bytree': 0.8652303155904655, 'reg_alpha': 8.899695840260256e-05, 'reg_lambda': 2.4794765432000958e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  17%|██████████████████▌                                                                                             | 83/500 [04:11<26:13,  3.77s/it]

[I 2026-05-19 12:49:51,796] Trial 81 finished with value: 0.9497204726186824 and parameters: {'n_estimators': 300, 'learning_rate': 0.03543331604330232, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 177, 'subsample': 0.626504122990715, 'colsample_bytree': 0.8668308438781986, 'reg_alpha': 0.27041253016411426, 'reg_lambda': 2.533134062236834e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  17%|███████████████████                                                                                             | 85/500 [04:12<13:27,  1.95s/it]

[I 2026-05-19 12:49:52,029] Trial 84 finished with value: 0.9497257976806341 and parameters: {'n_estimators': 261, 'learning_rate': 0.036032442902279346, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 147, 'subsample': 0.6802379554228641, 'colsample_bytree': 0.9008751919348585, 'reg_alpha': 7.945453649816508e-05, 'reg_lambda': 2.210658263887347e-05}. Best is trial 55 with value: 0.9497374666915765.
[I 2026-05-19 12:49:52,167] Trial 85 finished with value: 0.9497318592062213 and parameters: {'n_estimators': 260, 'learning_rate': 0.03524464630142618, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 148, 'subsample': 0.6832784141157744, 'colsample_bytree': 0.9001383579600993, 'reg_alpha': 5.524224901573674e-05, 'reg_lambda': 1.9709044284058185e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  17%|███████████████████▎                                                                                            | 86/500 [04:15<15:32,  2.25s/it]

[I 2026-05-19 12:49:55,143] Trial 82 finished with value: 0.9497233173483925 and parameters: {'n_estimators': 300, 'learning_rate': 0.03447290877962833, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 180, 'subsample': 0.6326172849911325, 'colsample_bytree': 0.8652228284611581, 'reg_alpha': 9.354489010272548e-05, 'reg_lambda': 3.9474240730536425e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  17%|███████████████████▍                                                                                            | 87/500 [04:17<14:20,  2.08s/it]

[I 2026-05-19 12:49:56,827] Trial 83 finished with value: 0.9497255662278855 and parameters: {'n_estimators': 300, 'learning_rate': 0.034987024452606354, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 176, 'subsample': 0.6831671517041847, 'colsample_bytree': 0.8669153235801316, 'reg_alpha': 7.003185847250946e-05, 'reg_lambda': 1.764022237099831e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  18%|███████████████████▉                                                                                            | 89/500 [04:35<33:20,  4.87s/it]

[I 2026-05-19 12:50:15,009] Trial 87 finished with value: 0.9497244462600982 and parameters: {'n_estimators': 296, 'learning_rate': 0.03494908327454213, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 148, 'subsample': 0.6837972121313227, 'colsample_bytree': 0.8629650757158173, 'reg_alpha': 0.47736607954299015, 'reg_lambda': 1.2292877053308084e-05}. Best is trial 55 with value: 0.9497374666915765.
[I 2026-05-19 12:50:15,116] Trial 89 finished with value: 0.9497344495540885 and parameters: {'n_estimators': 261, 'learning_rate': 0.03406074695339115, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 185, 'subsample': 0.6138160813284815, 'colsample_bytree': 0.8556816963316349, 'reg_alpha': 0.335365636525347, 'reg_lambda': 1.5627690071673064e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  18%|████████████████████▏                                                                                           | 90/500 [04:35<24:33,  3.59s/it]

[I 2026-05-19 12:50:15,731] Trial 91 finished with value: 0.9496605331486496 and parameters: {'n_estimators': 260, 'learning_rate': 0.034456371541807244, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 119, 'subsample': 0.6032299658235399, 'colsample_bytree': 0.8628522629114884, 'reg_alpha': 91.57934547050343, 'reg_lambda': 1.0413465141614192e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  18%|████████████████████▍                                                                                           | 91/500 [04:38<23:14,  3.41s/it]

[I 2026-05-19 12:50:18,717] Trial 90 finished with value: 0.949734999173622 and parameters: {'n_estimators': 258, 'learning_rate': 0.03441230173657445, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 137, 'subsample': 0.6015366602162596, 'colsample_bytree': 0.8691173779645825, 'reg_alpha': 0.7949829419741485, 'reg_lambda': 1.0576340564689786e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  18%|████████████████████▌                                                                                           | 92/500 [04:40<19:38,  2.89s/it]

[I 2026-05-19 12:50:20,375] Trial 88 finished with value: 0.9497334358737307 and parameters: {'n_estimators': 299, 'learning_rate': 0.03457019686540505, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 183, 'subsample': 0.6032843221594437, 'colsample_bytree': 0.857811556256648, 'reg_alpha': 0.3267229576227432, 'reg_lambda': 1.5779695571060784e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  19%|████████████████████▊                                                                                           | 93/500 [04:41<15:42,  2.32s/it]

[I 2026-05-19 12:50:21,366] Trial 92 finished with value: 0.9497368283533782 and parameters: {'n_estimators': 259, 'learning_rate': 0.0413191087019236, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 215, 'subsample': 0.6046014748114652, 'colsample_bytree': 0.8545992453745223, 'reg_alpha': 0.6019939970277196, 'reg_lambda': 1.1130792543875519e-05}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 55. Best value: 0.949737:  19%|█████████████████████                                                                                           | 94/500 [04:44<17:17,  2.55s/it]

[I 2026-05-19 12:50:24,472] Trial 97 finished with value: 0.949728517709634 and parameters: {'n_estimators': 191, 'learning_rate': 0.04189139156727212, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 130, 'subsample': 0.6054173463388425, 'colsample_bytree': 0.9171174748763887, 'reg_alpha': 0.5022540593053055, 'reg_lambda': 0.002448126767188655}. Best is trial 55 with value: 0.9497374666915765.

Best trial: 93. Best value: 0.949738:  19%|█████████████████████▎                                                                                          | 95/500 [04:45<13:11,  1.95s/it]

[I 2026-05-19 12:50:25,030] Trial 93 finished with value: 0.9497379986305402 and parameters: {'n_estimators': 263, 'learning_rate': 0.04187254683906004, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 215, 'subsample': 0.6027005703338907, 'colsample_bytree': 0.8699478707253528, 'reg_alpha': 3.55325003625267e-05, 'reg_lambda': 1.1538121485108786e-05}. Best is trial 93 with value: 0.9497379986305402.

Best trial: 93. Best value: 0.949738:  19%|█████████████████████▌                                                                                          | 96/500 [04:47<12:51,  1.91s/it]

[I 2026-05-19 12:50:26,816] Trial 98 finished with value: 0.949731394247183 and parameters: {'n_estimators': 194, 'learning_rate': 0.04166619582125725, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 140, 'subsample': 0.6429512612893136, 'colsample_bytree': 0.9208132533963727, 'reg_alpha': 0.03444175141648509, 'reg_lambda': 1.2798438546712533e-05}. Best is trial 93 with value: 0.9497379986305402.

Best trial: 93. Best value: 0.949738:  19%|█████████████████████▋                                                                                          | 97/500 [04:48<11:08,  1.66s/it]

[I 2026-05-19 12:50:27,901] Trial 96 finished with value: 0.9497373119372815 and parameters: {'n_estimators': 243, 'learning_rate': 0.04142161772539891, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 122, 'subsample': 0.6429218005189924, 'colsample_bytree': 0.9185627054204256, 'reg_alpha': 0.5371907704748943, 'reg_lambda': 1.3541926938166777e-05}. Best is trial 93 with value: 0.9497379986305402.

Best trial: 93. Best value: 0.949738:  20%|█████████████████████▉                                                                                          | 98/500 [04:50<12:25,  1.85s/it]

[I 2026-05-19 12:50:30,228] Trial 95 finished with value: 0.9497365614782624 and parameters: {'n_estimators': 256, 'learning_rate': 0.04145110557546226, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 214, 'subsample': 0.6117123738155976, 'colsample_bytree': 0.851135060989176, 'reg_alpha': 0.036004026645215625, 'reg_lambda': 0.0001225411377287248}. Best is trial 93 with value: 0.9497379986305402.

Best trial: 93. Best value: 0.949738:  20%|██████████████████████▏                                                                                         | 99/500 [04:52<12:57,  1.94s/it]

[I 2026-05-19 12:50:32,358] Trial 94 finished with value: 0.9497140097868613 and parameters: {'n_estimators': 262, 'learning_rate': 0.026605629875182172, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 113, 'subsample': 0.6002573397629083, 'colsample_bytree': 0.9218310845258035, 'reg_alpha': 0.5863778187269413, 'reg_lambda': 1.4910104221561551e-05}. Best is trial 93 with value: 0.9497379986305402.

Best trial: 93. Best value: 0.949738:  20%|██████████████████████▏                                                                                        | 100/500 [04:58<21:09,  3.17s/it]

[I 2026-05-19 12:50:38,390] Trial 101 pruned.

Best trial: 102. Best value: 0.949738:  20%|██████████████████████▏                                                                                       | 101/500 [05:15<48:09,  7.24s/it]

[I 2026-05-19 12:50:55,153] Trial 102 finished with value: 0.9497382947945143 and parameters: {'n_estimators': 239, 'learning_rate': 0.0418915352718444, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 132, 'subsample': 0.6150311543500246, 'colsample_bytree': 0.8476201558029031, 'reg_alpha': 1.0930434550778552, 'reg_lambda': 5.602920559283708e-05}. Best is trial 102 with value: 0.9497382947945143.

Best trial: 103. Best value: 0.949739:  20%|██████████████████████▍                                                                                       | 102/500 [05:17<38:56,  5.87s/it]

[I 2026-05-19 12:50:57,809] Trial 103 finished with value: 0.9497388522605303 and parameters: {'n_estimators': 244, 'learning_rate': 0.04112484189697074, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 138, 'subsample': 0.6429150143229768, 'colsample_bytree': 0.846580142769577, 'reg_alpha': 1.1558293383264155, 'reg_lambda': 0.00012702878888445521}. Best is trial 103 with value: 0.9497388522605303.

Best trial: 103. Best value: 0.949739:  21%|██████████████████████▋                                                                                       | 103/500 [05:18<28:05,  4.25s/it]

[I 2026-05-19 12:50:58,272] Trial 100 finished with value: 0.9497170112767815 and parameters: {'n_estimators': 280, 'learning_rate': 0.025803198786622152, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 140, 'subsample': 0.6002489188701975, 'colsample_bytree': 0.8495460961760558, 'reg_alpha': 1.0002967617212875, 'reg_lambda': 1.0712454376039434e-05}. Best is trial 103 with value: 0.9497388522605303.

Best trial: 104. Best value: 0.94974:  21%|███████████████████████                                                                                        | 104/500 [05:18<20:10,  3.06s/it]

[I 2026-05-19 12:50:58,540] Trial 104 finished with value: 0.9497398786711349 and parameters: {'n_estimators': 254, 'learning_rate': 0.040436814209079006, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 138, 'subsample': 0.614802197377626, 'colsample_bytree': 0.8491126635351887, 'reg_alpha': 1.026136246419354, 'reg_lambda': 0.000136626483572334}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  21%|███████████████████████▎                                                                                       | 105/500 [05:19<16:25,  2.49s/it]

[I 2026-05-19 12:50:59,721] Trial 99 finished with value: 0.9496828466167481 and parameters: {'n_estimators': 280, 'learning_rate': 0.01836945315630279, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 131, 'subsample': 0.7299143402328471, 'colsample_bytree': 0.920264877795795, 'reg_alpha': 0.039257001355404636, 'reg_lambda': 0.00013166312440028135}. Best is trial 104 with value: 0.9497398786711349.
[I 2026-05-19 12:50:59,791] Trial 105 finished with value: 0.9496840698052578 and parameters: {'n_estimators': 237, 'learning_rate': 0.026349058293219964, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 213, 'subsample': 0.6417996682618226, 'colsample_bytree': 0.8477404594461164, 'reg_alpha': 1.0667508811508992, 'reg_lambda': 56.26497804811037}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  21%|███████████████████████▊                                                                                       | 107/500 [05:23<13:39,  2.09s/it]

[I 2026-05-19 12:51:02,936] Trial 106 finished with value: 0.9490836932521505 and parameters: {'n_estimators': 241, 'learning_rate': 0.02568539308491064, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 214, 'subsample': 0.6174970530828322, 'colsample_bytree': 0.7891858360413099, 'reg_alpha': 0.9395234964975262, 'reg_lambda': 1.019189777334939e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  22%|███████████████████████▉                                                                                       | 108/500 [05:25<13:30,  2.07s/it]

[I 2026-05-19 12:51:04,952] Trial 108 finished with value: 0.9491421341471552 and parameters: {'n_estimators': 241, 'learning_rate': 0.026980839031251574, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 102, 'subsample': 0.6104689405082278, 'colsample_bytree': 0.7744605743165845, 'reg_alpha': 1.1174072671279438, 'reg_lambda': 0.00014057890299681175}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  22%|████████████████████████▏                                                                                      | 109/500 [05:25<10:48,  1.66s/it]

[I 2026-05-19 12:51:05,483] Trial 107 finished with value: 0.9491335310195916 and parameters: {'n_estimators': 247, 'learning_rate': 0.026426259655022828, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 216, 'subsample': 0.6139976142580562, 'colsample_bytree': 0.7643838369974894, 'reg_alpha': 1.2220617603096062, 'reg_lambda': 7.903946949306443}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  22%|████████████████████████▍                                                                                      | 110/500 [05:28<12:29,  1.92s/it]

[I 2026-05-19 12:51:08,087] Trial 109 finished with value: 0.9497027215378104 and parameters: {'n_estimators': 240, 'learning_rate': 0.02568653139915373, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 94, 'subsample': 0.6129965495748577, 'colsample_bytree': 0.849598223814031, 'reg_alpha': 1.311780743944376, 'reg_lambda': 0.00012324866344941643}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  22%|████████████████████████▋                                                                                      | 111/500 [05:30<13:18,  2.05s/it]

[I 2026-05-19 12:51:10,461] Trial 110 finished with value: 0.949660479402717 and parameters: {'n_estimators': 242, 'learning_rate': 0.019547418604290965, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 212, 'subsample': 0.6148148317074935, 'colsample_bytree': 0.8489292731036547, 'reg_alpha': 1.1001481972218625, 'reg_lambda': 0.00012813788906578666}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  22%|████████████████████████▊                                                                                      | 112/500 [05:37<22:20,  3.46s/it]

[I 2026-05-19 12:51:17,447] Trial 111 finished with value: 0.9495503495482127 and parameters: {'n_estimators': 246, 'learning_rate': 0.013017027756615202, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 213, 'subsample': 0.6145472034670043, 'colsample_bytree': 0.8494035363300367, 'reg_alpha': 2.060895326621806, 'reg_lambda': 1.0361283096558605e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  23%|█████████████████████████                                                                                      | 113/500 [05:52<44:21,  6.88s/it]

[I 2026-05-19 12:51:32,694] Trial 112 finished with value: 0.9497339598568502 and parameters: {'n_estimators': 249, 'learning_rate': 0.049615969227262705, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 214, 'subsample': 0.6164409956878605, 'colsample_bytree': 0.8746486773812313, 'reg_alpha': 5.707541580588557, 'reg_lambda': 1.0452072891926706e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  23%|█████████████████████████▎                                                                                     | 114/500 [05:54<34:17,  5.33s/it]

[I 2026-05-19 12:51:34,302] Trial 114 finished with value: 0.9497311836499739 and parameters: {'n_estimators': 248, 'learning_rate': 0.048229733811058786, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 102, 'subsample': 0.6163319723613568, 'colsample_bytree': 0.8458370313069135, 'reg_alpha': 7.253336413139662, 'reg_lambda': 0.00012719197666533234}. Best is trial 104 with value: 0.9497398786711349.
[I 2026-05-19 12:51:34,336] Trial 115 finished with value: 0.9497372199844104 and parameters: {'n_estimators': 247, 'learning_rate': 0.048760173409110645, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 108, 'subsample': 0.6438620565175381, 'colsample_bytree': 0.8443890137198753, 'reg_alpha': 3.0173126325664748, 'reg_lambda': 0.00011153073678659998}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  23%|█████████████████████████▊                                                                                     | 116/500 [05:55<19:55,  3.11s/it]

[I 2026-05-19 12:51:35,223] Trial 117 finished with value: 0.9497364452621389 and parameters: {'n_estimators': 244, 'learning_rate': 0.04823556816741067, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 103, 'subsample': 0.6162278132726435, 'colsample_bytree': 0.8751197145006023, 'reg_alpha': 3.926537565194227, 'reg_lambda': 0.00011317881848033531}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  23%|█████████████████████████▉                                                                                     | 117/500 [05:55<15:37,  2.45s/it]

[I 2026-05-19 12:51:35,623] Trial 113 finished with value: 0.9497353321280558 and parameters: {'n_estimators': 252, 'learning_rate': 0.0492329324358554, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 91, 'subsample': 0.616550311457269, 'colsample_bytree': 0.8448302947033051, 'reg_alpha': 3.5353198673282016, 'reg_lambda': 0.00011557133995332811}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  24%|██████████████████████████▏                                                                                    | 118/500 [05:57<14:12,  2.23s/it]

[I 2026-05-19 12:51:37,238] Trial 116 finished with value: 0.9497318275309452 and parameters: {'n_estimators': 246, 'learning_rate': 0.04956671950631272, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 108, 'subsample': 0.6154232584922954, 'colsample_bytree': 0.8742468953902277, 'reg_alpha': 2.2759186341402673, 'reg_lambda': 0.00011877484251317267}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  24%|██████████████████████████▍                                                                                    | 119/500 [06:01<17:30,  2.76s/it]

[I 2026-05-19 12:51:41,429] Trial 118 finished with value: 0.9496020995399373 and parameters: {'n_estimators': 249, 'learning_rate': 0.04961439896195822, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 96, 'subsample': 0.6394546907483998, 'colsample_bytree': 0.8085344743794016, 'reg_alpha': 2.260129294476385, 'reg_lambda': 5.616306134639095e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  24%|██████████████████████████▋                                                                                    | 120/500 [06:02<14:09,  2.24s/it]

[I 2026-05-19 12:51:42,305] Trial 121 finished with value: 0.9495490254355407 and parameters: {'n_estimators': 219, 'learning_rate': 0.049585178474773506, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 123, 'subsample': 0.6402631879651037, 'colsample_bytree': 0.8124486832831966, 'reg_alpha': 3.7106474543558057, 'reg_lambda': 5.812418426841574e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  24%|██████████████████████████▊                                                                                    | 121/500 [06:03<11:41,  1.85s/it]

[I 2026-05-19 12:51:43,201] Trial 119 finished with value: 0.9496080042076926 and parameters: {'n_estimators': 253, 'learning_rate': 0.04908374653403068, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 125, 'subsample': 0.6183341692870661, 'colsample_bytree': 0.8101842315236762, 'reg_alpha': 1.9146625128543722, 'reg_lambda': 4.964636270316839e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  24%|███████████████████████████                                                                                    | 122/500 [06:03<08:50,  1.40s/it]

[I 2026-05-19 12:51:43,484] Trial 120 finished with value: 0.9497349937092976 and parameters: {'n_estimators': 249, 'learning_rate': 0.0477413908543045, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 123, 'subsample': 0.6382405065309443, 'colsample_bytree': 0.8727677972337196, 'reg_alpha': 3.352590768724366, 'reg_lambda': 5.5665200536749997e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  25%|███████████████████████████▎                                                                                   | 123/500 [06:07<13:34,  2.16s/it]

[I 2026-05-19 12:51:47,481] Trial 122 finished with value: 0.949735379430725 and parameters: {'n_estimators': 255, 'learning_rate': 0.0490265733693154, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 122, 'subsample': 0.6371944196694209, 'colsample_bytree': 0.8740904842793352, 'reg_alpha': 3.9131705453938204, 'reg_lambda': 1.5176120731607376e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  25%|███████████████████████████▌                                                                                   | 124/500 [06:14<22:43,  3.63s/it]

[I 2026-05-19 12:51:54,621] Trial 123 finished with value: 0.9496073571471626 and parameters: {'n_estimators': 252, 'learning_rate': 0.04997201460449221, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 122, 'subsample': 0.6384155244054869, 'colsample_bytree': 0.8107323478483153, 'reg_alpha': 5.128614644627389, 'reg_lambda': 5.6269342140699086e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  25%|███████████████████████████▊                                                                                   | 125/500 [06:16<19:18,  3.09s/it]

[I 2026-05-19 12:51:56,436] Trial 130 finished with value: 0.9496006709391681 and parameters: {'n_estimators': 89, 'learning_rate': 0.04586176197340714, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 120, 'subsample': 0.6373178349349609, 'colsample_bytree': 0.8910952324287409, 'reg_alpha': 3.3587020436798283, 'reg_lambda': 0.0003077440595095254}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  25%|███████████████████████████▉                                                                                   | 126/500 [06:17<14:49,  2.38s/it]

[I 2026-05-19 12:51:57,136] Trial 126 pruned.

Best trial: 104. Best value: 0.94974:  25%|████████████████████████████▏                                                                                  | 127/500 [06:30<34:37,  5.57s/it]

[I 2026-05-19 12:52:10,190] Trial 124 finished with value: 0.9497390343885097 and parameters: {'n_estimators': 256, 'learning_rate': 0.04725293530952217, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 120, 'subsample': 0.6396356062508214, 'colsample_bytree': 0.8744386951769328, 'reg_alpha': 2.744611455798754, 'reg_lambda': 5.4556428244021134e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  26%|████████████████████████████▍                                                                                  | 128/500 [06:30<24:39,  3.98s/it]

[I 2026-05-19 12:52:10,461] Trial 127 finished with value: 0.9495449620991234 and parameters: {'n_estimators': 231, 'learning_rate': 0.0459264777473985, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 85, 'subsample': 0.6382459910069727, 'colsample_bytree': 0.8055175195005281, 'reg_alpha': 3.077426832248846, 'reg_lambda': 0.00034660964315089436}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  26%|████████████████████████████▋                                                                                  | 129/500 [06:30<17:39,  2.86s/it]

[I 2026-05-19 12:52:10,684] Trial 128 finished with value: 0.9495169662563112 and parameters: {'n_estimators': 220, 'learning_rate': 0.04572390340861816, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 79, 'subsample': 0.6422656082719252, 'colsample_bytree': 0.8152546884483425, 'reg_alpha': 2.002655999852948, 'reg_lambda': 6.0575418266731785e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  26%|████████████████████████████▊                                                                                  | 130/500 [06:32<15:58,  2.59s/it]

[I 2026-05-19 12:52:12,649] Trial 129 finished with value: 0.9495110841325906 and parameters: {'n_estimators': 218, 'learning_rate': 0.04590303054798724, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 125, 'subsample': 0.6389725584174468, 'colsample_bytree': 0.7992579101288286, 'reg_alpha': 3.1229896852267363, 'reg_lambda': 5.351975659213998e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  26%|█████████████████████████████                                                                                  | 131/500 [06:34<13:47,  2.24s/it]

[I 2026-05-19 12:52:14,093] Trial 125 finished with value: 0.9494044103861834 and parameters: {'n_estimators': 254, 'learning_rate': 0.032591474628224364, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 115, 'subsample': 0.6402871338818947, 'colsample_bytree': 0.8114873178768695, 'reg_alpha': 2.597428425436566, 'reg_lambda': 5.4043963632578745e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  26%|█████████████████████████████▎                                                                                 | 132/500 [06:38<17:13,  2.81s/it]

[I 2026-05-19 12:52:18,201] Trial 133 finished with value: 0.9497312398206571 and parameters: {'n_estimators': 230, 'learning_rate': 0.045352111394114866, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 87, 'subsample': 0.6461903725845555, 'colsample_bytree': 0.8400828978042229, 'reg_alpha': 10.525065317849817, 'reg_lambda': 0.00032157401393039366}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  27%|█████████████████████████████▌                                                                                 | 133/500 [06:40<15:50,  2.59s/it]

[I 2026-05-19 12:52:20,296] Trial 132 finished with value: 0.949737741636525 and parameters: {'n_estimators': 255, 'learning_rate': 0.046246473255438576, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 89, 'subsample': 0.6363005400206504, 'colsample_bytree': 0.838854597077784, 'reg_alpha': 3.614556457322548, 'reg_lambda': 3.07680646258931e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  27%|█████████████████████████████▋                                                                                 | 134/500 [06:40<11:50,  1.94s/it]

[I 2026-05-19 12:52:20,715] Trial 131 finished with value: 0.94973969875631 and parameters: {'n_estimators': 255, 'learning_rate': 0.04547492708393108, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 87, 'subsample': 0.6456098611725718, 'colsample_bytree': 0.8355256049817281, 'reg_alpha': 0.6921460184039064, 'reg_lambda': 0.0003992100620079321}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  27%|█████████████████████████████▉                                                                                 | 135/500 [06:42<11:08,  1.83s/it]

[I 2026-05-19 12:52:22,267] Trial 134 finished with value: 0.9497225012339798 and parameters: {'n_estimators': 233, 'learning_rate': 0.04533726213212329, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 112, 'subsample': 0.6445343197519154, 'colsample_bytree': 0.8862049791921978, 'reg_alpha': 15.236587163431615, 'reg_lambda': 0.00030047984752473527}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  27%|██████████████████████████████▏                                                                                | 136/500 [06:49<20:57,  3.45s/it]

[I 2026-05-19 12:52:29,547] Trial 136 finished with value: 0.949724656317106 and parameters: {'n_estimators': 231, 'learning_rate': 0.044522958478141424, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 88, 'subsample': 0.6484807797944688, 'colsample_bytree': 0.8841344514954247, 'reg_alpha': 15.392247172942055, 'reg_lambda': 0.00043858119194500216}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  27%|██████████████████████████████▍                                                                                | 137/500 [06:49<15:00,  2.48s/it]

[I 2026-05-19 12:52:29,749] Trial 135 finished with value: 0.9497278905380989 and parameters: {'n_estimators': 234, 'learning_rate': 0.04503545136076755, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 84, 'subsample': 0.6442689592908661, 'colsample_bytree': 0.8903458127774077, 'reg_alpha': 10.219049500698226, 'reg_lambda': 3.122302534575159e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  28%|██████████████████████████████▋                                                                                | 138/500 [06:50<12:23,  2.05s/it]

[I 2026-05-19 12:52:30,818] Trial 137 finished with value: 0.9494596003980114 and parameters: {'n_estimators': 230, 'learning_rate': 0.04465865271178779, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 154, 'subsample': 0.6484908477763484, 'colsample_bytree': 0.7137644744735201, 'reg_alpha': 27.949972460814156, 'reg_lambda': 0.34190659981883714}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  28%|██████████████████████████████▊                                                                                | 139/500 [07:04<32:27,  5.39s/it]

[I 2026-05-19 12:52:43,981] Trial 138 finished with value: 0.9497305986623467 and parameters: {'n_estimators': 230, 'learning_rate': 0.04368924155217598, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 78, 'subsample': 0.6460232235512469, 'colsample_bytree': 0.8383578748670202, 'reg_alpha': 9.369974391165156, 'reg_lambda': 3.0690397903694185e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  28%|███████████████████████████████                                                                                | 140/500 [07:09<32:17,  5.38s/it]

[I 2026-05-19 12:52:49,341] Trial 139 finished with value: 0.9497320332444257 and parameters: {'n_estimators': 265, 'learning_rate': 0.044438025692413285, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 154, 'subsample': 0.6206336385472593, 'colsample_bytree': 0.8401572967665247, 'reg_alpha': 10.252779260429723, 'reg_lambda': 3.184151105833249e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  28%|███████████████████████████████▎                                                                               | 141/500 [07:10<24:17,  4.06s/it]

[I 2026-05-19 12:52:50,318] Trial 140 finished with value: 0.9497238141957887 and parameters: {'n_estimators': 268, 'learning_rate': 0.0399296658285604, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 114, 'subsample': 0.623671170449051, 'colsample_bytree': 0.834780160989222, 'reg_alpha': 18.32679990149784, 'reg_lambda': 3.384354157713713e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  28%|███████████████████████████████▌                                                                               | 142/500 [07:12<20:14,  3.39s/it]

[I 2026-05-19 12:52:52,164] Trial 141 finished with value: 0.9497307599998166 and parameters: {'n_estimators': 266, 'learning_rate': 0.04057961886398919, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 113, 'subsample': 0.6223601626706525, 'colsample_bytree': 0.8358943655439689, 'reg_alpha': 12.296838621504508, 'reg_lambda': 3.073964765769674e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  29%|███████████████████████████████▋                                                                               | 143/500 [07:14<17:43,  2.98s/it]

[I 2026-05-19 12:52:54,151] Trial 142 finished with value: 0.9497293711455465 and parameters: {'n_estimators': 266, 'learning_rate': 0.040667246530494944, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 110, 'subsample': 0.6238906357056229, 'colsample_bytree': 0.8382484967199069, 'reg_alpha': 13.283292070421968, 'reg_lambda': 0.48570759979113015}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  29%|███████████████████████████████▉                                                                               | 144/500 [07:16<16:59,  2.86s/it]

[I 2026-05-19 12:52:56,766] Trial 143 finished with value: 0.9497370992524152 and parameters: {'n_estimators': 267, 'learning_rate': 0.03981244048086024, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 108, 'subsample': 0.6220044131954086, 'colsample_bytree': 0.8812435814599215, 'reg_alpha': 0.6229040457578071, 'reg_lambda': 3.384684171180575e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  29%|████████████████████████████████▍                                                                              | 146/500 [07:20<12:37,  2.14s/it]

[I 2026-05-19 12:53:00,019] Trial 144 finished with value: 0.9497280521679542 and parameters: {'n_estimators': 266, 'learning_rate': 0.040455292882220675, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 104, 'subsample': 0.6228585249616622, 'colsample_bytree': 0.8377266688963692, 'reg_alpha': 13.395309565567675, 'reg_lambda': 0.9813315007893646}. Best is trial 104 with value: 0.9497398786711349.
[I 2026-05-19 12:53:00,204] Trial 145 finished with value: 0.9497262886345265 and parameters: {'n_estimators': 265, 'learning_rate': 0.04046243536166924, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 73, 'subsample': 0.6502042951321232, 'colsample_bytree': 0.8403897433873363, 'reg_alpha': 17.19794683627127, 'reg_lambda': 0.0004964593654492831}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  29%|████████████████████████████████▋                                                                              | 147/500 [07:22<12:25,  2.11s/it]

[I 2026-05-19 12:53:02,230] Trial 146 finished with value: 0.9497387929381848 and parameters: {'n_estimators': 265, 'learning_rate': 0.03975407330869428, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 60, 'subsample': 0.6496588138522039, 'colsample_bytree': 0.8561788189603405, 'reg_alpha': 0.7030717439355907, 'reg_lambda': 0.0005081613772220655}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  30%|████████████████████████████████▊                                                                              | 148/500 [07:26<15:59,  2.73s/it]

[I 2026-05-19 12:53:06,402] Trial 150 finished with value: 0.9495591108411855 and parameters: {'n_estimators': 266, 'learning_rate': 0.03959688143226102, 'max_depth': 1, 'num_leaves': 16, 'min_child_samples': 105, 'subsample': 0.6224787312075611, 'colsample_bytree': 0.8565051556819653, 'reg_alpha': 0.20542281202623622, 'reg_lambda': 0.00017497786248973603}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  30%|█████████████████████████████████                                                                              | 149/500 [07:28<14:32,  2.49s/it]

[I 2026-05-19 12:53:08,332] Trial 147 finished with value: 0.9497364436004248 and parameters: {'n_estimators': 269, 'learning_rate': 0.040346176082462375, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 80, 'subsample': 0.8966723537223233, 'colsample_bytree': 0.8371034810739973, 'reg_alpha': 0.7219696839940001, 'reg_lambda': 0.00016838676454960066}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  30%|█████████████████████████████████▎                                                                             | 150/500 [07:29<11:33,  1.98s/it]

[I 2026-05-19 12:53:09,141] Trial 148 finished with value: 0.9497326056288141 and parameters: {'n_estimators': 267, 'learning_rate': 0.041809962359156745, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 106, 'subsample': 0.6224640989812577, 'colsample_bytree': 0.8351807687818137, 'reg_alpha': 0.7106169173050289, 'reg_lambda': 0.30511143993209133}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  30%|█████████████████████████████████▌                                                                             | 151/500 [07:30<09:39,  1.66s/it]

[I 2026-05-19 12:53:10,035] Trial 149 finished with value: 0.9497338160317431 and parameters: {'n_estimators': 267, 'learning_rate': 0.0402503630039289, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 66, 'subsample': 0.6214408760802812, 'colsample_bytree': 0.8366356556737962, 'reg_alpha': 0.7719779432071002, 'reg_lambda': 0.0011704349468992302}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  30%|█████████████████████████████████▋                                                                             | 152/500 [07:42<28:36,  4.93s/it]

[I 2026-05-19 12:53:22,610] Trial 157 finished with value: 0.9495647995760728 and parameters: {'n_estimators': 257, 'learning_rate': 0.042744854930885895, 'max_depth': 1, 'num_leaves': 14, 'min_child_samples': 141, 'subsample': 0.6076225007497472, 'colsample_bytree': 0.8585814625841602, 'reg_alpha': 0.6110983979786172, 'reg_lambda': 0.0001786613765236265}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  31%|█████████████████████████████████▉                                                                             | 153/500 [07:46<25:39,  4.44s/it]

[I 2026-05-19 12:53:25,886] Trial 160 finished with value: 0.9496474579709175 and parameters: {'n_estimators': 109, 'learning_rate': 0.042540800030366144, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 131, 'subsample': 0.6088113017197699, 'colsample_bytree': 0.8565665089401674, 'reg_alpha': 1.5695887556365016, 'reg_lambda': 8.069142367845399e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  31%|██████████████████████████████████▏                                                                            | 154/500 [07:47<21:05,  3.66s/it]

[I 2026-05-19 12:53:27,712] Trial 151 finished with value: 0.9497380712115133 and parameters: {'n_estimators': 267, 'learning_rate': 0.04043222764307697, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 104, 'subsample': 0.6723292275245789, 'colsample_bytree': 0.8549218681457948, 'reg_alpha': 0.674021539766566, 'reg_lambda': 0.0010612798408785376}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  31%|██████████████████████████████████▍                                                                            | 155/500 [07:50<18:44,  3.26s/it]

[I 2026-05-19 12:53:30,073] Trial 153 finished with value: 0.9497369958610911 and parameters: {'n_estimators': 258, 'learning_rate': 0.04074672964678194, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 222, 'subsample': 0.6070653096267367, 'colsample_bytree': 0.85620287791037, 'reg_alpha': 0.6841814416486847, 'reg_lambda': 0.02457467288654069}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  31%|██████████████████████████████████▋                                                                            | 156/500 [07:50<13:35,  2.37s/it]

[I 2026-05-19 12:53:30,355] Trial 152 finished with value: 0.9497346743134439 and parameters: {'n_estimators': 268, 'learning_rate': 0.040712398945468055, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 223, 'subsample': 0.6054473593548999, 'colsample_bytree': 0.8589738112447625, 'reg_alpha': 0.6871511726283445, 'reg_lambda': 0.00017568282349172991}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  31%|██████████████████████████████████▊                                                                            | 157/500 [07:55<17:27,  3.06s/it]

[I 2026-05-19 12:53:35,000] Trial 154 finished with value: 0.9497355895032052 and parameters: {'n_estimators': 280, 'learning_rate': 0.03904541459065547, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 65, 'subsample': 0.60722139064957, 'colsample_bytree': 0.8585700439471848, 'reg_alpha': 0.670296783725443, 'reg_lambda': 8.67346088084966e-05}. Best is trial 104 with value: 0.9497398786711349.
[I 2026-05-19 12:53:35,055] Trial 155 finished with value: 0.949737374174874 and parameters: {'n_estimators': 259, 'learning_rate': 0.04214665173406522, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 103, 'subsample': 0.6063393687187085, 'colsample_bytree': 0.8578208242570156, 'reg_alpha': 0.4552051397195919, 'reg_lambda': 8.941423005492926e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  32%|███████████████████████████████████▎                                                                           | 159/500 [07:57<11:57,  2.10s/it]

[I 2026-05-19 12:53:37,006] Trial 156 finished with value: 0.9497372493224457 and parameters: {'n_estimators': 257, 'learning_rate': 0.03928478694174772, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 67, 'subsample': 0.609683112404503, 'colsample_bytree': 0.8591947939558582, 'reg_alpha': 0.70854574971139, 'reg_lambda': 9.22414375025149e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  32%|███████████████████████████████████▌                                                                           | 160/500 [07:59<12:38,  2.23s/it]

[I 2026-05-19 12:53:39,608] Trial 158 finished with value: 0.9497352419903062 and parameters: {'n_estimators': 256, 'learning_rate': 0.04241406095232594, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 106, 'subsample': 0.6061705327429416, 'colsample_bytree': 0.8531231425701595, 'reg_alpha': 0.720781145456697, 'reg_lambda': 0.0002109368301689955}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  32%|███████████████████████████████████▋                                                                           | 161/500 [08:04<16:52,  2.99s/it]

[I 2026-05-19 12:53:44,730] Trial 159 finished with value: 0.9497350930536875 and parameters: {'n_estimators': 257, 'learning_rate': 0.04170851573384737, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 42, 'subsample': 0.607465199737092, 'colsample_bytree': 0.8566882024872617, 'reg_alpha': 0.6975253441334437, 'reg_lambda': 8.059317396767168e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  32%|███████████████████████████████████▉                                                                           | 162/500 [08:06<14:18,  2.54s/it]

[I 2026-05-19 12:53:46,077] Trial 161 finished with value: 0.9497350801728981 and parameters: {'n_estimators': 259, 'learning_rate': 0.042788393866819735, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 59, 'subsample': 0.6073634657591653, 'colsample_bytree': 0.8561139727077657, 'reg_alpha': 1.562158180340619, 'reg_lambda': 8.167364831210503e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  33%|████████████████████████████████████▏                                                                          | 163/500 [08:07<12:09,  2.16s/it]

[I 2026-05-19 12:53:47,283] Trial 164 pruned.

Best trial: 104. Best value: 0.94974:  33%|████████████████████████████████████▍                                                                          | 164/500 [08:07<09:06,  1.63s/it]

[I 2026-05-19 12:53:47,572] Trial 162 finished with value: 0.9497379955114212 and parameters: {'n_estimators': 257, 'learning_rate': 0.0425611932997654, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 222, 'subsample': 0.8951191052803039, 'colsample_bytree': 0.8581670311253303, 'reg_alpha': 1.5263006934463061, 'reg_lambda': 0.0001875287501699377}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  33%|████████████████████████████████████▋                                                                          | 165/500 [08:09<09:18,  1.67s/it]

[I 2026-05-19 12:53:49,331] Trial 168 pruned.

Best trial: 104. Best value: 0.94974:  33%|████████████████████████████████████▊                                                                          | 166/500 [08:13<12:32,  2.25s/it]

[I 2026-05-19 12:53:52,996] Trial 167 finished with value: 0.949558723213633 and parameters: {'n_estimators': 257, 'learning_rate': 0.03857635181834916, 'max_depth': 3, 'num_leaves': 2, 'min_child_samples': 50, 'subsample': 0.6711242905439774, 'colsample_bytree': 0.8557625971739097, 'reg_alpha': 0.47497289052191055, 'reg_lambda': 0.0010040707792953166}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  33%|█████████████████████████████████████                                                                          | 167/500 [08:22<24:18,  4.38s/it]

[I 2026-05-19 12:54:02,449] Trial 163 finished with value: 0.9495706981907223 and parameters: {'n_estimators': 258, 'learning_rate': 0.0426300161849048, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 39, 'subsample': 0.8949896027157452, 'colsample_bytree': 0.8272990658989018, 'reg_alpha': 1.3837509294818842, 'reg_lambda': 9.552038295109416e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  34%|█████████████████████████████████████▎                                                                         | 168/500 [08:25<21:37,  3.91s/it]

[I 2026-05-19 12:54:05,252] Trial 165 finished with value: 0.9497355046348733 and parameters: {'n_estimators': 257, 'learning_rate': 0.03851521610151588, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 25, 'subsample': 0.6657417230902289, 'colsample_bytree': 0.8776096867558543, 'reg_alpha': 0.022895268859179505, 'reg_lambda': 0.00022971102525637266}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  34%|█████████████████████████████████████▌                                                                         | 169/500 [08:30<24:14,  4.39s/it]

[I 2026-05-19 12:54:10,792] Trial 166 finished with value: 0.9494356065734824 and parameters: {'n_estimators': 258, 'learning_rate': 0.008297419829542794, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 41, 'subsample': 0.6637145683110981, 'colsample_bytree': 0.8559021394265482, 'reg_alpha': 0.4516297484075321, 'reg_lambda': 0.001067683699204441}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  34%|█████████████████████████████████████▋                                                                         | 170/500 [08:35<24:26,  4.44s/it]

[I 2026-05-19 12:54:15,345] Trial 169 finished with value: 0.9495227165512719 and parameters: {'n_estimators': 258, 'learning_rate': 0.038240489703078064, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 98, 'subsample': 0.6561292410284812, 'colsample_bytree': 0.8268600917819358, 'reg_alpha': 0.39539189175717526, 'reg_lambda': 0.06556709893947879}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  34%|█████████████████████████████████████▉                                                                         | 171/500 [08:38<22:26,  4.09s/it]

[I 2026-05-19 12:54:18,600] Trial 170 finished with value: 0.9494709151440169 and parameters: {'n_estimators': 276, 'learning_rate': 0.03270000429113018, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 57, 'subsample': 0.664953293017435, 'colsample_bytree': 0.8276262054050292, 'reg_alpha': 1.5076989987789302, 'reg_lambda': 0.026232814776966974}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  34%|██████████████████████████████████████▏                                                                        | 172/500 [08:41<20:11,  3.69s/it]

[I 2026-05-19 12:54:21,383] Trial 171 finished with value: 0.9494313789882675 and parameters: {'n_estimators': 275, 'learning_rate': 0.007730267506785387, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 47, 'subsample': 0.6635632722811803, 'colsample_bytree': 0.8674684128666237, 'reg_alpha': 1.383793167282373, 'reg_lambda': 0.08999225609602436}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  35%|██████████████████████████████████████▍                                                                        | 173/500 [08:45<20:33,  3.77s/it]

[I 2026-05-19 12:54:25,331] Trial 172 finished with value: 0.9495173016369174 and parameters: {'n_estimators': 261, 'learning_rate': 0.03706428050750745, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 97, 'subsample': 0.6752391761414196, 'colsample_bytree': 0.8275836358672075, 'reg_alpha': 0.3491162884015392, 'reg_lambda': 0.02460748392777646}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  35%|██████████████████████████████████████▋                                                                        | 174/500 [08:48<18:43,  3.45s/it]

[I 2026-05-19 12:54:28,010] Trial 174 finished with value: 0.9497394810865725 and parameters: {'n_estimators': 275, 'learning_rate': 0.03811114399931053, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 71, 'subsample': 0.6651948777291494, 'colsample_bytree': 0.8807451901666438, 'reg_alpha': 0.41541179928834027, 'reg_lambda': 0.0029751601665207704}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  35%|██████████████████████████████████████▊                                                                        | 175/500 [08:49<14:46,  2.73s/it]

[I 2026-05-19 12:54:29,075] Trial 173 finished with value: 0.9495534275991057 and parameters: {'n_estimators': 276, 'learning_rate': 0.0380757545366487, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 98, 'subsample': 0.6334728489342195, 'colsample_bytree': 0.8271126135165322, 'reg_alpha': 0.4344481247886943, 'reg_lambda': 0.010399941413933859}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  35%|███████████████████████████████████████                                                                        | 176/500 [08:49<10:46,  2.00s/it]

[I 2026-05-19 12:54:29,367] Trial 175 finished with value: 0.9497379371854564 and parameters: {'n_estimators': 276, 'learning_rate': 0.037847728997147015, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 97, 'subsample': 0.6699618802588786, 'colsample_bytree': 0.8680584536181873, 'reg_alpha': 0.3299438006465639, 'reg_lambda': 0.0003739869979142516}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  35%|███████████████████████████████████████▎                                                                       | 177/500 [08:51<10:07,  1.88s/it]

[I 2026-05-19 12:54:30,971] Trial 176 finished with value: 0.9497334778131196 and parameters: {'n_estimators': 275, 'learning_rate': 0.03765589490648403, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 97, 'subsample': 0.8967829296160508, 'colsample_bytree': 0.867969007172017, 'reg_alpha': 0.0006147205287938327, 'reg_lambda': 0.0005029931304789098}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  36%|███████████████████████████████████████▌                                                                       | 178/500 [08:55<14:49,  2.76s/it]

[I 2026-05-19 12:54:35,785] Trial 177 finished with value: 0.9497365385541163 and parameters: {'n_estimators': 276, 'learning_rate': 0.037950807637675325, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 97, 'subsample': 0.972325529538023, 'colsample_bytree': 0.8689791337636916, 'reg_alpha': 0.3639852756640022, 'reg_lambda': 0.0005440046687701128}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  36%|███████████████████████████████████████▋                                                                       | 179/500 [09:01<19:13,  3.59s/it]

[I 2026-05-19 12:54:41,309] Trial 178 finished with value: 0.9494089344306443 and parameters: {'n_estimators': 250, 'learning_rate': 0.00821945560366645, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 93, 'subsample': 0.8499304185320153, 'colsample_bytree': 0.8791085977676149, 'reg_alpha': 0.3253956903536544, 'reg_lambda': 0.0014903258610442262}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  36%|███████████████████████████████████████▉                                                                       | 180/500 [09:06<21:45,  4.08s/it]

[I 2026-05-19 12:54:46,540] Trial 179 finished with value: 0.9495153112851975 and parameters: {'n_estimators': 273, 'learning_rate': 0.009384802543596093, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 96, 'subsample': 0.6580919578433041, 'colsample_bytree': 0.8713640507675376, 'reg_alpha': 3.127967745708801e-05, 'reg_lambda': 0.0004523936112121173}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  36%|████████████████████████████████████████▏                                                                      | 181/500 [09:12<25:05,  4.72s/it]

[I 2026-05-19 12:54:52,748] Trial 180 finished with value: 0.9497365192190902 and parameters: {'n_estimators': 276, 'learning_rate': 0.032373805565824136, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 97, 'subsample': 0.9518028257738637, 'colsample_bytree': 0.8682104040940524, 'reg_alpha': 0.29830359474716445, 'reg_lambda': 0.020898024809050255}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  36%|████████████████████████████████████████▍                                                                      | 182/500 [09:14<20:41,  3.91s/it]

[I 2026-05-19 12:54:54,754] Trial 182 finished with value: 0.9497389111193237 and parameters: {'n_estimators': 249, 'learning_rate': 0.04637382749507515, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 97, 'subsample': 0.7913552176029606, 'colsample_bytree': 0.8635067090987362, 'reg_alpha': 0.9679534562499569, 'reg_lambda': 1.888694450441298e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  37%|████████████████████████████████████████▋                                                                      | 183/500 [09:17<19:02,  3.60s/it]

[I 2026-05-19 12:54:57,657] Trial 181 finished with value: 0.9497343036382115 and parameters: {'n_estimators': 277, 'learning_rate': 0.03254065991782149, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 98, 'subsample': 0.631699709606202, 'colsample_bytree': 0.8666983551672247, 'reg_alpha': 1.7762592718952581, 'reg_lambda': 0.010386873110005052}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  37%|████████████████████████████████████████▊                                                                      | 184/500 [09:19<16:24,  3.12s/it]

[I 2026-05-19 12:54:59,629] Trial 183 finished with value: 0.9495775399174959 and parameters: {'n_estimators': 246, 'learning_rate': 0.04672897346805001, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 100, 'subsample': 0.7891974148597104, 'colsample_bytree': 0.6729882514421205, 'reg_alpha': 0.3001664658290692, 'reg_lambda': 0.0004925795066141991}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  37%|█████████████████████████████████████████▎                                                                     | 186/500 [09:23<12:18,  2.35s/it]

[I 2026-05-19 12:55:03,352] Trial 184 finished with value: 0.9497344064581785 and parameters: {'n_estimators': 249, 'learning_rate': 0.04633633055468497, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 67, 'subsample': 0.944663171595638, 'colsample_bytree': 0.8650026853270208, 'reg_alpha': 0.27949263620651377, 'reg_lambda': 0.0004975931082482471}. Best is trial 104 with value: 0.9497398786711349.
[I 2026-05-19 12:55:03,494] Trial 185 finished with value: 0.9497363209532155 and parameters: {'n_estimators': 251, 'learning_rate': 0.04669742459470229, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 72, 'subsample': 0.9666588489112289, 'colsample_bytree': 0.8705836984929183, 'reg_alpha': 2.648100685366979e-05, 'reg_lambda': 0.010712327598491196}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  37%|█████████████████████████████████████████▌                                                                     | 187/500 [09:25<12:09,  2.33s/it]

[I 2026-05-19 12:55:05,784] Trial 187 finished with value: 0.9497383337677352 and parameters: {'n_estimators': 251, 'learning_rate': 0.04753601838320311, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 72, 'subsample': 0.6918502823413635, 'colsample_bytree': 0.8699683480691562, 'reg_alpha': 0.1068016996202564, 'reg_lambda': 0.00048691931213848687}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  38%|█████████████████████████████████████████▋                                                                     | 188/500 [09:27<10:08,  1.95s/it]

[I 2026-05-19 12:55:06,839] Trial 186 finished with value: 0.9497382634860294 and parameters: {'n_estimators': 250, 'learning_rate': 0.04683158050722454, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 70, 'subsample': 0.9686054224836268, 'colsample_bytree': 0.8712246905869596, 'reg_alpha': 0.11140815597920388, 'reg_lambda': 0.000494152660319557}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  38%|█████████████████████████████████████████▉                                                                     | 189/500 [09:28<09:29,  1.83s/it]

[I 2026-05-19 12:55:08,405] Trial 188 finished with value: 0.9497346812091291 and parameters: {'n_estimators': 249, 'learning_rate': 0.0465762485192729, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 71, 'subsample': 0.6549178507178723, 'colsample_bytree': 0.8804905318166348, 'reg_alpha': 0.11069908742051264, 'reg_lambda': 0.0016449384599756993}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  38%|██████████████████████████████████████████▏                                                                    | 190/500 [09:34<15:54,  3.08s/it]

[I 2026-05-19 12:55:14,384] Trial 189 finished with value: 0.9497356730898247 and parameters: {'n_estimators': 250, 'learning_rate': 0.04693658957036978, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 71, 'subsample': 0.6533004301333691, 'colsample_bytree': 0.8812982064608291, 'reg_alpha': 0.13292707573958068, 'reg_lambda': 0.00034786482305130525}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  38%|██████████████████████████████████████████▍                                                                    | 191/500 [09:36<13:31,  2.62s/it]

[I 2026-05-19 12:55:15,953] Trial 190 finished with value: 0.9497349963946439 and parameters: {'n_estimators': 239, 'learning_rate': 0.047011081411740194, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 69, 'subsample': 0.7600073112283054, 'colsample_bytree': 0.8810635168669968, 'reg_alpha': 2.842255395354933e-05, 'reg_lambda': 0.00040033525947809096}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  38%|██████████████████████████████████████████▌                                                                    | 192/500 [09:49<29:20,  5.72s/it]

[I 2026-05-19 12:55:28,879] Trial 191 finished with value: 0.9496171967419945 and parameters: {'n_estimators': 283, 'learning_rate': 0.04574263361011282, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 117, 'subsample': 0.6541103311152177, 'colsample_bytree': 0.6717922724751272, 'reg_alpha': 0.13960284568136755, 'reg_lambda': 0.002246367965196419}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  39%|██████████████████████████████████████████▊                                                                    | 193/500 [09:50<23:23,  4.57s/it]

[I 2026-05-19 12:55:30,750] Trial 192 finished with value: 0.9497379817558249 and parameters: {'n_estimators': 251, 'learning_rate': 0.047022622558027145, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 69, 'subsample': 0.6316769828766142, 'colsample_bytree': 0.8455839608395446, 'reg_alpha': 0.9628953085230676, 'reg_lambda': 0.000332668323779685}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  39%|███████████████████████████████████████████                                                                    | 194/500 [09:53<19:45,  3.87s/it]

[I 2026-05-19 12:55:33,033] Trial 193 finished with value: 0.9495488246077091 and parameters: {'n_estimators': 238, 'learning_rate': 0.04537679455889184, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 77, 'subsample': 0.6932117137521154, 'colsample_bytree': 0.6212249510784557, 'reg_alpha': 1.1149825021257225, 'reg_lambda': 0.0008094494900402822}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  39%|███████████████████████████████████████████▌                                                                   | 196/500 [09:55<12:27,  2.46s/it]

[I 2026-05-19 12:55:35,456] Trial 195 finished with value: 0.9497370051605969 and parameters: {'n_estimators': 238, 'learning_rate': 0.04632360296217259, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 73, 'subsample': 0.6520935706109562, 'colsample_bytree': 0.88171162926746, 'reg_alpha': 0.18160213549733228, 'reg_lambda': 1.787338424774133e-05}. Best is trial 104 with value: 0.9497398786711349.
[I 2026-05-19 12:55:35,633] Trial 194 finished with value: 0.9497346551655722 and parameters: {'n_estimators': 244, 'learning_rate': 0.04664297645595596, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 71, 'subsample': 0.6915111639784816, 'colsample_bytree': 0.8458098791601965, 'reg_alpha': 0.12718610845219427, 'reg_lambda': 1.9225493225812328e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  39%|███████████████████████████████████████████▋                                                                   | 197/500 [09:59<14:12,  2.81s/it]

[I 2026-05-19 12:55:39,259] Trial 197 finished with value: 0.9497365424561865 and parameters: {'n_estimators': 241, 'learning_rate': 0.043308596644427724, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 75, 'subsample': 0.7687468199694948, 'colsample_bytree': 0.8931557134538548, 'reg_alpha': 0.11981272982329272, 'reg_lambda': 2.015613249913124e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  40%|███████████████████████████████████████████▉                                                                   | 198/500 [10:00<11:38,  2.31s/it]

[I 2026-05-19 12:55:40,386] Trial 196 finished with value: 0.9497342007691036 and parameters: {'n_estimators': 243, 'learning_rate': 0.04653292550140283, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 89, 'subsample': 0.8682439787076235, 'colsample_bytree': 0.882908109768529, 'reg_alpha': 0.11690919210873735, 'reg_lambda': 1.6661469654588818e-05}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  40%|████████████████████████████████████████████▏                                                                  | 199/500 [10:03<11:54,  2.37s/it]

[I 2026-05-19 12:55:42,914] Trial 198 finished with value: 0.9497307767741979 and parameters: {'n_estimators': 241, 'learning_rate': 0.04450939444850241, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 73, 'subsample': 0.7362999699679665, 'colsample_bytree': 0.8462931254569794, 'reg_alpha': 0.10594808557862763, 'reg_lambda': 0.0009415586316518265}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  40%|████████████████████████████████████████████▍                                                                  | 200/500 [10:05<11:46,  2.36s/it]

[I 2026-05-19 12:55:45,249] Trial 199 finished with value: 0.9497367713980364 and parameters: {'n_estimators': 238, 'learning_rate': 0.044322966052565076, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 73, 'subsample': 0.9979918445121345, 'colsample_bytree': 0.8952686939457921, 'reg_alpha': 0.12457685582065678, 'reg_lambda': 0.0008278145375465308}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  40%|████████████████████████████████████████████▌                                                                  | 201/500 [10:05<08:35,  1.73s/it]

[I 2026-05-19 12:55:45,498] Trial 200 finished with value: 0.949735250119279 and parameters: {'n_estimators': 237, 'learning_rate': 0.043942666948523154, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 75, 'subsample': 0.6938932165836592, 'colsample_bytree': 0.8936386885726642, 'reg_alpha': 0.05742417011390911, 'reg_lambda': 0.0008271447402406598}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  40%|████████████████████████████████████████████▊                                                                  | 202/500 [10:12<16:35,  3.34s/it]

[I 2026-05-19 12:55:52,599] Trial 201 finished with value: 0.9497386251190573 and parameters: {'n_estimators': 238, 'learning_rate': 0.04409112839677448, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 54, 'subsample': 0.6880256178552482, 'colsample_bytree': 0.8935239084366527, 'reg_alpha': 0.9299128481671121, 'reg_lambda': 0.0007956253516172574}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 104. Best value: 0.94974:  41%|█████████████████████████████████████████████                                                                  | 203/500 [10:14<14:36,  2.95s/it]

[I 2026-05-19 12:55:54,633] Trial 202 finished with value: 0.9497320019190466 and parameters: {'n_estimators': 242, 'learning_rate': 0.04434742805882121, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 60, 'subsample': 0.6875351418525308, 'colsample_bytree': 0.8936360089955333, 'reg_alpha': 0.16993299629668573, 'reg_lambda': 0.0007221654301909148}. Best is trial 104 with value: 0.9497398786711349.

Best trial: 203. Best value: 0.949741:  41%|████████████████████████████████████████████▉                                                                 | 204/500 [10:25<25:22,  5.14s/it]

[I 2026-05-19 12:56:04,903] Trial 203 finished with value: 0.9497414732293162 and parameters: {'n_estimators': 238, 'learning_rate': 0.04454377519390935, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 77, 'subsample': 0.6866612328934097, 'colsample_bytree': 0.8452348684504442, 'reg_alpha': 0.18040627170637957, 'reg_lambda': 0.0006509382870876687}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  41%|█████████████████████████████████████████████                                                                 | 205/500 [10:26<20:00,  4.07s/it]

[I 2026-05-19 12:56:06,478] Trial 204 finished with value: 0.9497365246610677 and parameters: {'n_estimators': 236, 'learning_rate': 0.04362793619712632, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 77, 'subsample': 0.7323301966240857, 'colsample_bytree': 0.8937942372686372, 'reg_alpha': 0.04706432495557622, 'reg_lambda': 0.0002639889814071724}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  41%|█████████████████████████████████████████████▎                                                                | 206/500 [10:32<21:52,  4.46s/it]

[I 2026-05-19 12:56:11,855] Trial 205 finished with value: 0.9497373734499458 and parameters: {'n_estimators': 263, 'learning_rate': 0.043748706795233426, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 83, 'subsample': 0.6888241637316703, 'colsample_bytree': 0.8477097523004787, 'reg_alpha': 0.9280912333703712, 'reg_lambda': 0.0007713063708379455}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  41%|█████████████████████████████████████████████▌                                                                | 207/500 [10:33<17:24,  3.56s/it]

[I 2026-05-19 12:56:13,327] Trial 207 finished with value: 0.9497368232889276 and parameters: {'n_estimators': 253, 'learning_rate': 0.04388073755606893, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 84, 'subsample': 0.9169430157533156, 'colsample_bytree': 0.846672035839499, 'reg_alpha': 0.9481695456537524, 'reg_lambda': 0.0006647368962493491}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  42%|█████████████████████████████████████████████▊                                                                | 208/500 [10:36<16:10,  3.32s/it]

[I 2026-05-19 12:56:16,082] Trial 206 finished with value: 0.9497349252612481 and parameters: {'n_estimators': 262, 'learning_rate': 0.04352754186397253, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 63, 'subsample': 0.998431567074024, 'colsample_bytree': 0.8452832376547058, 'reg_alpha': 0.9760505148379633, 'reg_lambda': 0.0007304102439439211}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  42%|█████████████████████████████████████████████▉                                                                | 209/500 [10:36<12:07,  2.50s/it]

[I 2026-05-19 12:56:16,648] Trial 208 finished with value: 0.9497367541660907 and parameters: {'n_estimators': 262, 'learning_rate': 0.043517905197327414, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 56, 'subsample': 0.7365531958334044, 'colsample_bytree': 0.8476442739299471, 'reg_alpha': 0.06329061252422848, 'reg_lambda': 0.0007732608780016432}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  42%|██████████████████████████████████████████████▏                                                               | 210/500 [10:40<13:09,  2.72s/it]

[I 2026-05-19 12:56:19,893] Trial 209 finished with value: 0.9497378067395473 and parameters: {'n_estimators': 262, 'learning_rate': 0.043342437318069596, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 59, 'subsample': 0.9921156489589518, 'colsample_bytree': 0.8478082469404247, 'reg_alpha': 1.0102841952136716, 'reg_lambda': 0.0006393475399702407}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  42%|██████████████████████████████████████████████▍                                                               | 211/500 [10:41<11:24,  2.37s/it]

[I 2026-05-19 12:56:21,458] Trial 210 finished with value: 0.9497328103340704 and parameters: {'n_estimators': 262, 'learning_rate': 0.04356744967502626, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 62, 'subsample': 0.9973172612691997, 'colsample_bytree': 0.8624926498647495, 'reg_alpha': 0.9344821204524887, 'reg_lambda': 0.0006723224100556491}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  42%|██████████████████████████████████████████████▋                                                               | 212/500 [10:44<11:29,  2.39s/it]

[I 2026-05-19 12:56:23,902] Trial 212 finished with value: 0.9497387938712174 and parameters: {'n_estimators': 253, 'learning_rate': 0.04966792896636589, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 54, 'subsample': 0.6751159383858761, 'colsample_bytree': 0.8476459539949215, 'reg_alpha': 0.8480818137735687, 'reg_lambda': 0.0002905486287756668}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  43%|██████████████████████████████████████████████▊                                                               | 213/500 [10:44<08:21,  1.75s/it]

[I 2026-05-19 12:56:24,129] Trial 211 finished with value: 0.9497352363910878 and parameters: {'n_estimators': 262, 'learning_rate': 0.04311264962657808, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 61, 'subsample': 0.6754080995913945, 'colsample_bytree': 0.8464143603216521, 'reg_alpha': 0.9240674201173968, 'reg_lambda': 0.00028757828377632566}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  43%|███████████████████████████████████████████████                                                               | 214/500 [10:48<11:34,  2.43s/it]

[I 2026-05-19 12:56:28,154] Trial 213 finished with value: 0.9497302455141037 and parameters: {'n_estimators': 225, 'learning_rate': 0.04289751570705403, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 60, 'subsample': 0.684368641752714, 'colsample_bytree': 0.8615682608997958, 'reg_alpha': 0.9165826290593653, 'reg_lambda': 0.00028196257522477343}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  43%|███████████████████████████████████████████████▎                                                              | 215/500 [10:54<17:29,  3.68s/it]

[I 2026-05-19 12:56:34,762] Trial 214 finished with value: 0.9497368144515326 and parameters: {'n_estimators': 264, 'learning_rate': 0.04245418454770696, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 55, 'subsample': 0.6714402259177664, 'colsample_bytree': 0.8642792372626709, 'reg_alpha': 0.806432256957632, 'reg_lambda': 0.0002679263345268385}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  43%|███████████████████████████████████████████████▌                                                              | 216/500 [11:04<25:31,  5.39s/it]

[I 2026-05-19 12:56:44,149] Trial 215 finished with value: 0.9497375667383429 and parameters: {'n_estimators': 262, 'learning_rate': 0.042398991150422484, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 53, 'subsample': 0.6770408564044048, 'colsample_bytree': 0.8492222042636891, 'reg_alpha': 0.9774173032645349, 'reg_lambda': 0.000290279460853882}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  43%|███████████████████████████████████████████████▋                                                              | 217/500 [11:07<22:23,  4.75s/it]

[I 2026-05-19 12:56:47,370] Trial 216 finished with value: 0.9497376230903549 and parameters: {'n_estimators': 263, 'learning_rate': 0.04184557750412528, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 53, 'subsample': 0.6767833451862696, 'colsample_bytree': 0.8490837010069088, 'reg_alpha': 0.9225338596209599, 'reg_lambda': 0.0006087148897897412}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  44%|███████████████████████████████████████████████▉                                                              | 218/500 [11:09<18:10,  3.87s/it]

[I 2026-05-19 12:56:49,186] Trial 219 finished with value: 0.9497328200364796 and parameters: {'n_estimators': 225, 'learning_rate': 0.04879103695734837, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 55, 'subsample': 0.6761848605950559, 'colsample_bytree': 0.8631280411145108, 'reg_alpha': 0.20326592827971735, 'reg_lambda': 0.00028287555849451515}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  44%|████████████████████████████████████████████████▏                                                             | 219/500 [11:12<16:43,  3.57s/it]

[I 2026-05-19 12:56:52,060] Trial 218 finished with value: 0.9497311803263203 and parameters: {'n_estimators': 263, 'learning_rate': 0.049714564002801095, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 83, 'subsample': 0.6753500107813953, 'colsample_bytree': 0.8630270147195116, 'reg_alpha': 0.964082323087128, 'reg_lambda': 0.0003189210606305451}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  44%|████████████████████████████████████████████████▍                                                             | 220/500 [11:14<14:40,  3.15s/it]

[I 2026-05-19 12:56:54,213] Trial 220 finished with value: 0.9497351415375572 and parameters: {'n_estimators': 263, 'learning_rate': 0.04971611763363181, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 84, 'subsample': 0.6763801287063894, 'colsample_bytree': 0.8627899959054192, 'reg_alpha': 0.9447366002796697, 'reg_lambda': 0.0003324815241779727}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  44%|████████████████████████████████████████████████▌                                                             | 221/500 [11:14<10:40,  2.29s/it]

[I 2026-05-19 12:56:54,554] Trial 221 finished with value: 0.9497354843171463 and parameters: {'n_estimators': 224, 'learning_rate': 0.04965913254996673, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 57, 'subsample': 0.6824713030764965, 'colsample_bytree': 0.8739589397257935, 'reg_alpha': 0.19435004248548782, 'reg_lambda': 0.00033916031099549414}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  44%|████████████████████████████████████████████████▊                                                             | 222/500 [11:16<09:23,  2.03s/it]

[I 2026-05-19 12:56:55,938] Trial 217 finished with value: 0.949631097234781 and parameters: {'n_estimators': 263, 'learning_rate': 0.016001921652837252, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 53, 'subsample': 0.6770253028223588, 'colsample_bytree': 0.8456931637080172, 'reg_alpha': 0.9199682817618741, 'reg_lambda': 0.0006573801901495508}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  45%|█████████████████████████████████████████████████                                                             | 223/500 [11:19<11:40,  2.53s/it]

[I 2026-05-19 12:56:59,631] Trial 222 finished with value: 0.9497303694462265 and parameters: {'n_estimators': 271, 'learning_rate': 0.049679540301986624, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 51, 'subsample': 0.9832403188503747, 'colsample_bytree': 0.8637274885828932, 'reg_alpha': 0.22399609485935756, 'reg_lambda': 0.0012413268091371816}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  45%|█████████████████████████████████████████████████▎                                                            | 224/500 [11:22<12:05,  2.63s/it]

[I 2026-05-19 12:57:02,486] Trial 224 finished with value: 0.9497351515825697 and parameters: {'n_estimators': 252, 'learning_rate': 0.04986621543658822, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 57, 'subsample': 0.9818690356945048, 'colsample_bytree': 0.8720126980738447, 'reg_alpha': 1.982258303669995, 'reg_lambda': 0.00037773742732171925}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  45%|█████████████████████████████████████████████████▌                                                            | 225/500 [11:23<08:59,  1.96s/it]

[I 2026-05-19 12:57:02,915] Trial 223 finished with value: 0.9497404221271613 and parameters: {'n_estimators': 253, 'learning_rate': 0.049627933981356245, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 57, 'subsample': 0.6789748640410215, 'colsample_bytree': 0.87271268914354, 'reg_alpha': 1.9155745873060315, 'reg_lambda': 0.0003289083288388937}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  45%|█████████████████████████████████████████████████▋                                                            | 226/500 [11:28<13:10,  2.88s/it]

[I 2026-05-19 12:57:07,953] Trial 225 finished with value: 0.9492848362032482 and parameters: {'n_estimators': 252, 'learning_rate': 0.006309097296444549, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 54, 'subsample': 0.7015793376473055, 'colsample_bytree': 0.873629904147246, 'reg_alpha': 1.6804348214813178, 'reg_lambda': 0.0003693915722719421}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  45%|█████████████████████████████████████████████████▉                                                            | 227/500 [11:30<12:58,  2.85s/it]

[I 2026-05-19 12:57:10,718] Trial 226 finished with value: 0.9497335801804884 and parameters: {'n_estimators': 251, 'learning_rate': 0.048423992143052666, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 49, 'subsample': 0.9898821531866967, 'colsample_bytree': 0.873974664437808, 'reg_alpha': 0.21557660682774557, 'reg_lambda': 0.00038033283394421836}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  46%|██████████████████████████████████████████████████▏                                                           | 228/500 [11:42<24:44,  5.46s/it]

[I 2026-05-19 12:57:22,276] Trial 227 finished with value: 0.9497354126504313 and parameters: {'n_estimators': 251, 'learning_rate': 0.04897108043743172, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 47, 'subsample': 0.7002358507995415, 'colsample_bytree': 0.872729221619992, 'reg_alpha': 1.470099429216535, 'reg_lambda': 0.00033596092767368136}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  46%|██████████████████████████████████████████████████▌                                                           | 230/500 [11:49<19:08,  4.25s/it]

[I 2026-05-19 12:57:29,610] Trial 229 finished with value: 0.9486281609423255 and parameters: {'n_estimators': 252, 'learning_rate': 0.005407610652811666, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 44, 'subsample': 0.6791726882506969, 'colsample_bytree': 0.8523491039238509, 'reg_alpha': 1.774270230885155, 'reg_lambda': 0.0003670821986386576}. Best is trial 203 with value: 0.9497414732293162.
[I 2026-05-19 12:57:29,726] Trial 228 finished with value: 0.949736912553754 and parameters: {'n_estimators': 254, 'learning_rate': 0.04944648897241807, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 52, 'subsample': 0.6979900105385339, 'colsample_bytree': 0.8514622258056844, 'reg_alpha': 1.8948251440369983, 'reg_lambda': 0.00035005381956416254}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  46%|██████████████████████████████████████████████████▊                                                           | 231/500 [11:51<15:44,  3.51s/it]

[I 2026-05-19 12:57:31,498] Trial 230 finished with value: 0.9497330780338613 and parameters: {'n_estimators': 253, 'learning_rate': 0.04985272831587653, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 50, 'subsample': 0.8221807544098817, 'colsample_bytree': 0.8512580379433694, 'reg_alpha': 1.5515120093116137, 'reg_lambda': 0.0003957005842490651}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  46%|███████████████████████████████████████████████████                                                           | 232/500 [11:52<11:38,  2.61s/it]

[I 2026-05-19 12:57:32,024] Trial 231 finished with value: 0.9497390645609223 and parameters: {'n_estimators': 251, 'learning_rate': 0.03966161874162343, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 54, 'subsample': 0.6796179387736724, 'colsample_bytree': 0.8528906598434567, 'reg_alpha': 1.7829683263383838, 'reg_lambda': 0.0011592245375119062}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  47%|███████████████████████████████████████████████████▎                                                          | 233/500 [11:53<09:44,  2.19s/it]

[I 2026-05-19 12:57:33,222] Trial 233 finished with value: 0.9497396620024423 and parameters: {'n_estimators': 252, 'learning_rate': 0.03648317717726115, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 51, 'subsample': 0.8308259444747471, 'colsample_bytree': 0.8503628702313568, 'reg_alpha': 1.7968797824532037, 'reg_lambda': 0.0013298256908118962}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  47%|███████████████████████████████████████████████████▍                                                          | 234/500 [11:54<08:24,  1.90s/it]

[I 2026-05-19 12:57:34,439] Trial 239 finished with value: 0.9495165558036229 and parameters: {'n_estimators': 69, 'learning_rate': 0.03974039455520021, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 65, 'subsample': 0.6678850059534267, 'colsample_bytree': 0.8519119546606685, 'reg_alpha': 1.3191807900707715, 'reg_lambda': 0.0004969442710556508}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  47%|███████████████████████████████████████████████████▋                                                          | 235/500 [11:58<10:37,  2.40s/it]

[I 2026-05-19 12:57:38,022] Trial 234 finished with value: 0.9497407708031386 and parameters: {'n_estimators': 252, 'learning_rate': 0.040114421337934525, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 47, 'subsample': 0.7051540828605218, 'colsample_bytree': 0.8533554375747546, 'reg_alpha': 1.810119149360147, 'reg_lambda': 0.00047160508420483743}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  47%|███████████████████████████████████████████████████▉                                                          | 236/500 [11:58<08:22,  1.90s/it]

[I 2026-05-19 12:57:38,753] Trial 232 finished with value: 0.9491325344739794 and parameters: {'n_estimators': 253, 'learning_rate': 0.005412031218909552, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 50, 'subsample': 0.702229848970733, 'colsample_bytree': 0.8513035592170131, 'reg_alpha': 1.9422659761363066, 'reg_lambda': 0.001313742383636421}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  47%|████████████████████████████████████████████████████▏                                                         | 237/500 [12:01<09:08,  2.08s/it]

[I 2026-05-19 12:57:41,257] Trial 236 finished with value: 0.9497365398283597 and parameters: {'n_estimators': 253, 'learning_rate': 0.04095269099126506, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 45, 'subsample': 0.7219595934490556, 'colsample_bytree': 0.8533425272426352, 'reg_alpha': 1.4887084492163052, 'reg_lambda': 0.0004909740642690038}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  48%|████████████████████████████████████████████████████▎                                                         | 238/500 [12:02<07:23,  1.69s/it]

[I 2026-05-19 12:57:42,055] Trial 237 finished with value: 0.9497336335633454 and parameters: {'n_estimators': 207, 'learning_rate': 0.040143425081209876, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 45, 'subsample': 0.695717712298648, 'colsample_bytree': 0.8515397040883652, 'reg_alpha': 1.3920627426640868, 'reg_lambda': 0.0012301648975740383}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  48%|████████████████████████████████████████████████████▌                                                         | 239/500 [12:03<06:20,  1.46s/it]

[I 2026-05-19 12:57:42,960] Trial 235 finished with value: 0.9497355843600561 and parameters: {'n_estimators': 253, 'learning_rate': 0.039374310169610134, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 43, 'subsample': 0.6995994874860085, 'colsample_bytree': 0.8509634464487162, 'reg_alpha': 1.4491072821848088, 'reg_lambda': 0.0005108329707379672}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  48%|████████████████████████████████████████████████████▊                                                         | 240/500 [12:11<15:32,  3.59s/it]

[I 2026-05-19 12:57:51,499] Trial 238 finished with value: 0.9497388676854346 and parameters: {'n_estimators': 247, 'learning_rate': 0.04066849632784741, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 143, 'subsample': 0.6987606490957069, 'colsample_bytree': 0.8524801106655264, 'reg_alpha': 1.3718527494736181, 'reg_lambda': 0.0005175954489871303}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  48%|█████████████████████████████████████████████████████                                                         | 241/500 [12:12<12:19,  2.86s/it]

[I 2026-05-19 12:57:52,654] Trial 240 finished with value: 0.9496854499231999 and parameters: {'n_estimators': 142, 'learning_rate': 0.04076041793271792, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 143, 'subsample': 0.6682920279789714, 'colsample_bytree': 0.8349502749890694, 'reg_alpha': 4.991499846018364, 'reg_lambda': 0.0005432441363575415}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  48%|█████████████████████████████████████████████████████▏                                                        | 242/500 [12:28<29:12,  6.79s/it]

[I 2026-05-19 12:58:08,617] Trial 241 finished with value: 0.9497413564003262 and parameters: {'n_estimators': 246, 'learning_rate': 0.040971857285867344, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 64, 'subsample': 0.9638444647363971, 'colsample_bytree': 0.8352551907561565, 'reg_alpha': 1.3373466930034907, 'reg_lambda': 0.0004826700156471217}. Best is trial 203 with value: 0.9497414732293162.

[I 2026-05-19 12:58:09,357] Trial 243 finished with value: 0.949739985404826 and parameters: {'n_estimators': 245, 'learning_rate': 0.04028319078651908, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 91, 'subsample': 0.6686698788150615, 'colsample_bytree': 0.8524219984589417, 'reg_alpha': 2.6260206197718694, 'reg_lambda': 0.0005384521603742943}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  49%|█████████████████████████████████████████████████████▋                                                        | 244/500 [12:29<15:06,  3.54s/it]

[I 2026-05-19 12:58:09,557] Trial 244 finished with value: 0.9497312303039308 and parameters: {'n_estimators': 246, 'learning_rate': 0.03617015191768374, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 36, 'subsample': 0.8373854396908595, 'colsample_bytree': 0.8396298796791135, 'reg_alpha': 2.904758473679518, 'reg_lambda': 0.0011881660410054955}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  49%|█████████████████████████████████████████████████████▉                                                        | 245/500 [12:31<13:04,  3.07s/it]

[I 2026-05-19 12:58:11,554] Trial 245 finished with value: 0.9497350354379195 and parameters: {'n_estimators': 246, 'learning_rate': 0.03578826526107414, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 38, 'subsample': 0.6877054788867133, 'colsample_bytree': 0.8390488755836415, 'reg_alpha': 1.310315130679364, 'reg_lambda': 0.0017280550233244637}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  49%|██████████████████████████████████████████████████████                                                        | 246/500 [12:33<11:43,  2.77s/it]

[I 2026-05-19 12:58:13,624] Trial 246 finished with value: 0.9497345701209967 and parameters: {'n_estimators': 245, 'learning_rate': 0.03598909329071138, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 143, 'subsample': 0.832783133891052, 'colsample_bytree': 0.8409170219410327, 'reg_alpha': 2.963021701708617, 'reg_lambda': 0.0016884361873119287}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  49%|██████████████████████████████████████████████████████▎                                                       | 247/500 [12:34<08:48,  2.09s/it]

[I 2026-05-19 12:58:14,122] Trial 242 finished with value: 0.9497365721257383 and parameters: {'n_estimators': 271, 'learning_rate': 0.039636838976534076, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 134, 'subsample': 0.6695805688520772, 'colsample_bytree': 0.8398221864359188, 'reg_alpha': 0.5674177003011707, 'reg_lambda': 0.0005456917232742028}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  50%|██████████████████████████████████████████████████████▌                                                       | 248/500 [12:36<08:14,  1.96s/it]

[I 2026-05-19 12:58:15,728] Trial 248 finished with value: 0.9497283766421795 and parameters: {'n_estimators': 244, 'learning_rate': 0.03593282645750095, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 140, 'subsample': 0.9314019691085332, 'colsample_bytree': 0.8369478247041188, 'reg_alpha': 4.877436756113806, 'reg_lambda': 0.0011605843571662622}. Best is trial 203 with value: 0.9497414732293162.
[I 2026-05-19 12:58:15,874] Trial 247 finished with value: 0.9497400459737737 and parameters: {'n_estimators': 246, 'learning_rate': 0.036267163355875556, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 137, 'subsample': 0.8324697197196121, 'colsample_bytree': 0.8389438637961708, 'reg_alpha': 2.4164275625932694, 'reg_lambda': 0.0017026434303694543}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  50%|███████████████████████████████████████████████████████                                                       | 250/500 [12:39<08:13,  1.97s/it]

[I 2026-05-19 12:58:19,751] Trial 249 finished with value: 0.9497298496274414 and parameters: {'n_estimators': 244, 'learning_rate': 0.03608616796038688, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 33, 'subsample': 0.9608778874667924, 'colsample_bytree': 0.8357305920466376, 'reg_alpha': 5.766466234336471, 'reg_lambda': 0.0017156058325231791}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  50%|███████████████████████████████████████████████████████▏                                                      | 251/500 [12:42<08:17,  2.00s/it]

[I 2026-05-19 12:58:21,825] Trial 250 finished with value: 0.9497332265876185 and parameters: {'n_estimators': 246, 'learning_rate': 0.036878347437112345, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 37, 'subsample': 0.8456847658861675, 'colsample_bytree': 0.8398823576951989, 'reg_alpha': 5.959181716340639, 'reg_lambda': 0.0015226685171214158}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  50%|███████████████████████████████████████████████████████▍                                                      | 252/500 [12:50<15:06,  3.66s/it]

[I 2026-05-19 12:58:30,181] Trial 252 finished with value: 0.9497352171319406 and parameters: {'n_estimators': 246, 'learning_rate': 0.03753489752232401, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 138, 'subsample': 0.8322889099968195, 'colsample_bytree': 0.8398263916681102, 'reg_alpha': 2.6635694724207797, 'reg_lambda': 0.002089688381230336}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  51%|███████████████████████████████████████████████████████▋                                                      | 253/500 [12:50<11:25,  2.77s/it]

[I 2026-05-19 12:58:30,584] Trial 251 finished with value: 0.9497342831470224 and parameters: {'n_estimators': 245, 'learning_rate': 0.03647349025624049, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 35, 'subsample': 0.7905823043306239, 'colsample_bytree': 0.8388175908753724, 'reg_alpha': 2.3018863586197877, 'reg_lambda': 0.003558889233521819}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  51%|███████████████████████████████████████████████████████▉                                                      | 254/500 [13:08<28:17,  6.90s/it]

[I 2026-05-19 12:58:48,111] Trial 253 finished with value: 0.9497350206250059 and parameters: {'n_estimators': 247, 'learning_rate': 0.035807380926037684, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 134, 'subsample': 0.9677470300897416, 'colsample_bytree': 0.8344228602047734, 'reg_alpha': 2.760651540076784, 'reg_lambda': 0.000979443259688102}. Best is trial 203 with value: 0.9497414732293162.
[I 2026-05-19 12:58:48,300] Trial 255 finished with value: 0.9497361713574533 and parameters: {'n_estimators': 246, 'learning_rate': 0.0378279943953262, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 136, 'subsample': 0.6888649796283235, 'colsample_bytree': 0.8415153182332957, 'reg_alpha': 0.5716003663534597, 'reg_lambda': 0.00017275353759503638}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  51%|████████████████████████████████████████████████████████▎                                                     | 256/500 [13:09<15:46,  3.88s/it]

[I 2026-05-19 12:58:49,472] Trial 254 finished with value: 0.9497363138047191 and parameters: {'n_estimators': 249, 'learning_rate': 0.03653086061327337, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 91, 'subsample': 0.6877480478171183, 'colsample_bytree': 0.8377685141753934, 'reg_alpha': 2.6077058227697956, 'reg_lambda': 0.002187357415368348}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  51%|████████████████████████████████████████████████████████▌                                                     | 257/500 [13:11<12:49,  3.17s/it]

[I 2026-05-19 12:58:50,914] Trial 256 finished with value: 0.9497354192159913 and parameters: {'n_estimators': 244, 'learning_rate': 0.036651986030739596, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 130, 'subsample': 0.7099697837447778, 'colsample_bytree': 0.8618468544304156, 'reg_alpha': 2.375040494078199, 'reg_lambda': 0.00017659984610895454}. Best is trial 203 with value: 0.9497414732293162.
[I 2026-05-19 12:58:50,987] Trial 257 finished with value: 0.9497351892186268 and parameters: {'n_estimators': 246, 'learning_rate': 0.03800163092114294, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 80, 'subsample': 0.9576885975309615, 'colsample_bytree': 0.8605468815852131, 'reg_alpha': 2.2596185732233414, 'reg_lambda': 0.00018777265042059784}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  52%|█████████████████████████████████████████████████████████▏                                                    | 260/500 [13:12<06:12,  1.55s/it]

[I 2026-05-19 12:58:52,116] Trial 258 finished with value: 0.9497358590827268 and parameters: {'n_estimators': 245, 'learning_rate': 0.03768088826077881, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 137, 'subsample': 0.9639667059489208, 'colsample_bytree': 0.8610752583111057, 'reg_alpha': 2.286356331907084, 'reg_lambda': 0.00019778313103657936}. Best is trial 203 with value: 0.9497414732293162.
[I 2026-05-19 12:58:52,299] Trial 259 finished with value: 0.9497372267038158 and parameters: {'n_estimators': 246, 'learning_rate': 0.037718641080359404, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 68, 'subsample': 0.7102095293203473, 'colsample_bytree': 0.8596392977733849, 'reg_alpha': 2.757466842665643, 'reg_lambda': 0.004075042479893243}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  52%|█████████████████████████████████████████████████████████▍                                                    | 261/500 [13:14<06:50,  1.72s/it]

[I 2026-05-19 12:58:54,486] Trial 260 finished with value: 0.9497356855096131 and parameters: {'n_estimators': 246, 'learning_rate': 0.03745016619281139, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 131, 'subsample': 0.9617731569246397, 'colsample_bytree': 0.8603167140861259, 'reg_alpha': 1.9351440026466893, 'reg_lambda': 0.003138799723582864}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  52%|█████████████████████████████████████████████████████████▋                                                    | 262/500 [13:15<06:02,  1.52s/it]

[I 2026-05-19 12:58:55,479] Trial 261 finished with value: 0.9497338842182664 and parameters: {'n_estimators': 233, 'learning_rate': 0.03845345491727397, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 63, 'subsample': 0.8859983188683754, 'colsample_bytree': 0.8607653849629682, 'reg_alpha': 2.160036473815352, 'reg_lambda': 0.0022431696804977087}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  53%|█████████████████████████████████████████████████████████▊                                                    | 263/500 [13:18<07:11,  1.82s/it]

[I 2026-05-19 12:58:58,074] Trial 262 finished with value: 0.949737859757678 and parameters: {'n_estimators': 235, 'learning_rate': 0.03905724528921305, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 137, 'subsample': 0.7944422807207809, 'colsample_bytree': 0.8634897430014026, 'reg_alpha': 2.184262983311331, 'reg_lambda': 0.00021062518714101371}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  53%|██████████████████████████████████████████████████████████                                                    | 264/500 [13:26<13:53,  3.53s/it]

[I 2026-05-19 12:59:05,913] Trial 263 finished with value: 0.9497351266903244 and parameters: {'n_estimators': 237, 'learning_rate': 0.03922284986683562, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 128, 'subsample': 0.7846764295212059, 'colsample_bytree': 0.8604104367686154, 'reg_alpha': 1.8975065437001397, 'reg_lambda': 0.00019419098683646685}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  53%|██████████████████████████████████████████████████████████▎                                                   | 265/500 [13:27<11:53,  3.04s/it]

[I 2026-05-19 12:59:07,722] Trial 265 pruned.

Best trial: 203. Best value: 0.949741:  53%|██████████████████████████████████████████████████████████▌                                                   | 266/500 [13:28<08:39,  2.22s/it]

[I 2026-05-19 12:59:07,967] Trial 264 finished with value: 0.9495154482546131 and parameters: {'n_estimators': 232, 'learning_rate': 0.01130056130286518, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 67, 'subsample': 0.8576056911692373, 'colsample_bytree': 0.8614166980586138, 'reg_alpha': 2.10096330266222, 'reg_lambda': 0.00021386116512748602}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  53%|██████████████████████████████████████████████████████████▋                                                   | 267/500 [13:44<25:17,  6.51s/it]

[I 2026-05-19 12:59:24,753] Trial 267 finished with value: 0.9497348277215304 and parameters: {'n_estimators': 237, 'learning_rate': 0.04646474190649427, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 67, 'subsample': 0.7105106308232207, 'colsample_bytree': 0.8595666737112012, 'reg_alpha': 0.004754262746493925, 'reg_lambda': 0.0001921042078903403}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  54%|███████████████████████████████████████████████████████████▏                                                  | 269/500 [13:45<13:00,  3.38s/it]

[I 2026-05-19 12:59:25,362] Trial 266 finished with value: 0.9497385272526534 and parameters: {'n_estimators': 233, 'learning_rate': 0.04574588269473639, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 66, 'subsample': 0.8600951357200477, 'colsample_bytree': 0.8589640427626808, 'reg_alpha': 1.9464485468582662, 'reg_lambda': 0.0025724661108094187}. Best is trial 203 with value: 0.9497414732293162.
[I 2026-05-19 12:59:25,452] Trial 271 finished with value: 0.9494982402953773 and parameters: {'n_estimators': 236, 'learning_rate': 0.04635071923250281, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 148, 'subsample': 0.8254666403606247, 'colsample_bytree': 0.8199370977526372, 'reg_alpha': 1.300286011213604, 'reg_lambda': 0.0010103382181515656}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 203. Best value: 0.949741:  54%|███████████████████████████████████████████████████████████▍                                                  | 270/500 [13:45<09:16,  2.42s/it]

[I 2026-05-19 12:59:25,630] Trial 269 finished with value: 0.9495305131331294 and parameters: {'n_estimators': 235, 'learning_rate': 0.0461156985452725, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 66, 'subsample': 0.8538870068327864, 'colsample_bytree': 0.8195247547559065, 'reg_alpha': 0.004950519573886847, 'reg_lambda': 0.0009434179933846503}. Best is trial 203 with value: 0.9497414732293162.
[I 2026-05-19 12:59:25,691] Trial 270 finished with value: 0.9497377725468411 and parameters: {'n_estimators': 234, 'learning_rate': 0.04628085059383155, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 67, 'subsample': 0.8093078222835765, 'colsample_bytree': 0.8861237382711695, 'reg_alpha': 1.2586947319964208, 'reg_lambda': 0.005305718112681869}. Best is trial 203 with value: 0.9497414732293162.

Best trial: 273. Best value: 0.949742:  54%|███████████████████████████████████████████████████████████▊                                                  | 272/500 [13:47<06:29,  1.71s/it]

[I 2026-05-19 12:59:27,370] Trial 273 finished with value: 0.9497415897463499 and parameters: {'n_estimators': 238, 'learning_rate': 0.04612320144105945, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 148, 'subsample': 0.8692067131368955, 'colsample_bytree': 0.8769160303244248, 'reg_alpha': 1.2759521410212589, 'reg_lambda': 0.000899844856078035}. Best is trial 273 with value: 0.9497415897463499.

Best trial: 273. Best value: 0.949742:  55%|████████████████████████████████████████████████████████████                                                  | 273/500 [13:48<05:56,  1.57s/it]

[I 2026-05-19 12:59:28,541] Trial 268 finished with value: 0.9497381385194315 and parameters: {'n_estimators': 235, 'learning_rate': 0.04602962367397562, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 66, 'subsample': 0.8860797764063584, 'colsample_bytree': 0.8588485682064512, 'reg_alpha': 2.0686425752492172, 'reg_lambda': 0.001041646946336856}. Best is trial 273 with value: 0.9497415897463499.

Best trial: 273. Best value: 0.949742:  55%|████████████████████████████████████████████████████████████▎                                                 | 274/500 [13:53<08:35,  2.28s/it]

[I 2026-05-19 12:59:32,812] Trial 272 finished with value: 0.9495618842829151 and parameters: {'n_estimators': 239, 'learning_rate': 0.046263671010878825, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 149, 'subsample': 0.7213323768112057, 'colsample_bytree': 0.8204346678484596, 'reg_alpha': 1.2252732240887925, 'reg_lambda': 0.0009418409568077199}. Best is trial 273 with value: 0.9497415897463499.
[I 2026-05-19 12:59:32,859] Trial 274 finished with value: 0.9492971568004089 and parameters: {'n_estimators': 235, 'learning_rate': 0.01154754137210415, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 152, 'subsample': 0.9127333151212339, 'colsample_bytree': 0.8884831340280693, 'reg_alpha': 1.2836216967522909, 'reg_lambda': 0.0008945367428222688}. Best is trial 273 with value: 0.9497415897463499.

Best trial: 275. Best value: 0.949742:  55%|████████████████████████████████████████████████████████████▋                                                 | 276/500 [14:02<12:10,  3.26s/it]

[I 2026-05-19 12:59:41,968] Trial 275 finished with value: 0.9497418267693526 and parameters: {'n_estimators': 256, 'learning_rate': 0.045683802820823675, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 65, 'subsample': 0.8538565893655636, 'colsample_bytree': 0.888071388582886, 'reg_alpha': 1.25313048839443, 'reg_lambda': 0.0009565697964740664}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  55%|████████████████████████████████████████████████████████████▉                                                 | 277/500 [14:07<13:36,  3.66s/it]

[I 2026-05-19 12:59:46,963] Trial 276 finished with value: 0.9497343982043469 and parameters: {'n_estimators': 256, 'learning_rate': 0.04555914252586062, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 64, 'subsample': 0.9117621723245045, 'colsample_bytree': 0.8849397683588784, 'reg_alpha': 1.2865938721510748, 'reg_lambda': 0.0010004352192387763}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  56%|█████████████████████████████████████████████████████████████▏                                                | 278/500 [14:08<11:44,  3.17s/it]

[I 2026-05-19 12:59:48,662] Trial 277 finished with value: 0.9497368222045022 and parameters: {'n_estimators': 255, 'learning_rate': 0.04587993157983177, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 145, 'subsample': 0.7469706185736572, 'colsample_bytree': 0.8878701867348662, 'reg_alpha': 1.272866337535303, 'reg_lambda': 0.0009562765399177919}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  56%|█████████████████████████████████████████████████████████████▍                                                | 279/500 [14:23<22:33,  6.13s/it]

[I 2026-05-19 13:00:03,030] Trial 284 finished with value: 0.9494763713103934 and parameters: {'n_estimators': 229, 'learning_rate': 0.013620346570041911, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 158, 'subsample': 0.8655176056864096, 'colsample_bytree': 0.876824139651933, 'reg_alpha': 4.442877963152855, 'reg_lambda': 0.000975278356839486}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  56%|█████████████████████████████████████████████████████████████▊                                                | 281/500 [14:23<12:12,  3.34s/it]

[I 2026-05-19 13:00:03,564] Trial 279 finished with value: 0.949550103555748 and parameters: {'n_estimators': 256, 'learning_rate': 0.041739072392641616, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 147, 'subsample': 0.9103761689046488, 'colsample_bytree': 0.8193624302380946, 'reg_alpha': 1.2681780970859875, 'reg_lambda': 0.0009612620121023374}. Best is trial 275 with value: 0.9497418267693526.
[I 2026-05-19 13:00:03,687] Trial 278 finished with value: 0.9497373764515833 and parameters: {'n_estimators': 255, 'learning_rate': 0.04561876216064914, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 62, 'subsample': 0.8060060891021643, 'colsample_bytree': 0.8770159448835587, 'reg_alpha': 1.2653739090495382, 'reg_lambda': 0.000970957220089445}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  56%|██████████████████████████████████████████████████████████████                                                | 282/500 [14:24<08:54,  2.45s/it]

[I 2026-05-19 13:00:03,922] Trial 280 finished with value: 0.9497392207194414 and parameters: {'n_estimators': 255, 'learning_rate': 0.0412038773190491, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 170, 'subsample': 0.8066045076976134, 'colsample_bytree': 0.8788331377736687, 'reg_alpha': 1.2447230287823192, 'reg_lambda': 0.0009498775441000842}. Best is trial 275 with value: 0.9497418267693526.
[I 2026-05-19 13:00:04,008] Trial 281 finished with value: 0.9497354308912833 and parameters: {'n_estimators': 255, 'learning_rate': 0.04129863507263459, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 159, 'subsample': 0.9076311240606706, 'colsample_bytree': 0.8761271740239378, 'reg_alpha': 0.637753616217479, 'reg_lambda': 0.0006093253831682303}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  57%|██████████████████████████████████████████████████████████████▍                                               | 284/500 [14:26<06:24,  1.78s/it]

[I 2026-05-19 13:00:05,861] Trial 283 finished with value: 0.9497383968321482 and parameters: {'n_estimators': 240, 'learning_rate': 0.04145012729028412, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 148, 'subsample': 0.878111164742976, 'colsample_bytree': 0.8761276550201152, 'reg_alpha': 0.5945598694737693, 'reg_lambda': 0.0009114817891649671}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  57%|██████████████████████████████████████████████████████████████▋                                               | 285/500 [14:26<05:16,  1.47s/it]

[I 2026-05-19 13:00:06,378] Trial 282 finished with value: 0.949738845633631 and parameters: {'n_estimators': 256, 'learning_rate': 0.040884549025259315, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 79, 'subsample': 0.684196647521198, 'colsample_bytree': 0.87679084750594, 'reg_alpha': 4.108160450145639, 'reg_lambda': 0.0005387546268609939}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  57%|██████████████████████████████████████████████████████████████▉                                               | 286/500 [14:29<06:49,  1.91s/it]

[I 2026-05-19 13:00:09,535] Trial 286 finished with value: 0.9497373413760808 and parameters: {'n_estimators': 228, 'learning_rate': 0.0417291640598241, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 145, 'subsample': 0.8613350942734344, 'colsample_bytree': 0.8694444218293583, 'reg_alpha': 3.733747441631258, 'reg_lambda': 0.0005952934384818374}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  57%|███████████████████████████████████████████████████████████████▏                                              | 287/500 [14:31<06:13,  1.75s/it]

[I 2026-05-19 13:00:10,854] Trial 285 finished with value: 0.9497353319577689 and parameters: {'n_estimators': 239, 'learning_rate': 0.04136629839082713, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 146, 'subsample': 0.6847407337961859, 'colsample_bytree': 0.8778851255008631, 'reg_alpha': 4.037107004762487, 'reg_lambda': 0.0006281309042412749}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  58%|███████████████████████████████████████████████████████████████▎                                              | 288/500 [14:37<10:22,  2.94s/it]

[I 2026-05-19 13:00:16,900] Trial 288 finished with value: 0.9494598215373683 and parameters: {'n_estimators': 178, 'learning_rate': 0.014570960445807118, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 145, 'subsample': 0.8659449612052365, 'colsample_bytree': 0.8760478991135084, 'reg_alpha': 3.5371761933801147, 'reg_lambda': 0.00065058582569142}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  58%|███████████████████████████████████████████████████████████████▌                                              | 289/500 [14:38<08:52,  2.53s/it]

[I 2026-05-19 13:00:18,373] Trial 287 finished with value: 0.9497372846457445 and parameters: {'n_estimators': 228, 'learning_rate': 0.04469107372902336, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 160, 'subsample': 0.8692032837799167, 'colsample_bytree': 0.8777427245681536, 'reg_alpha': 3.3763296842964565, 'reg_lambda': 0.0006671532297202408}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  58%|███████████████████████████████████████████████████████████████▊                                              | 290/500 [14:45<12:49,  3.66s/it]

[I 2026-05-19 13:00:24,844] Trial 289 finished with value: 0.9497397365441081 and parameters: {'n_estimators': 226, 'learning_rate': 0.04215073909619954, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 61, 'subsample': 0.8617596791363584, 'colsample_bytree': 0.8752640328336796, 'reg_alpha': 3.248745380352306, 'reg_lambda': 0.0006171534664594072}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  58%|████████████████████████████████████████████████████████████████                                              | 291/500 [14:52<16:25,  4.71s/it]

[I 2026-05-19 13:00:32,104] Trial 290 finished with value: 0.9497190609312224 and parameters: {'n_estimators': 181, 'learning_rate': 0.042246923714907646, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 79, 'subsample': 0.8434587332020735, 'colsample_bytree': 0.869824451359793, 'reg_alpha': 3.8423585952398756, 'reg_lambda': 0.0006373202612247219}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  59%|████████████████████████████████████████████████████████████████▍                                             | 293/500 [14:54<09:56,  2.88s/it]

[I 2026-05-19 13:00:34,518] Trial 291 finished with value: 0.9497338991795805 and parameters: {'n_estimators': 196, 'learning_rate': 0.04393616304938851, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 60, 'subsample': 0.8792434472775275, 'colsample_bytree': 0.8769117344076202, 'reg_alpha': 3.4383255891082363, 'reg_lambda': 0.0006274405735227015}. Best is trial 275 with value: 0.9497418267693526.
[I 2026-05-19 13:00:34,630] Trial 294 finished with value: 0.9497358186514031 and parameters: {'n_estimators': 240, 'learning_rate': 0.04129873189548635, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 59, 'subsample': 0.8426745665182859, 'colsample_bytree': 0.9022987553803975, 'reg_alpha': 3.623166428607923, 'reg_lambda': 0.0006026601546124202}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  59%|████████████████████████████████████████████████████████████████▋                                             | 294/500 [14:57<09:43,  2.83s/it]

[I 2026-05-19 13:00:37,375] Trial 298 finished with value: 0.9497315397063414 and parameters: {'n_estimators': 198, 'learning_rate': 0.044122500666994115, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 77, 'subsample': 0.8732815109126859, 'colsample_bytree': 0.8817136159888534, 'reg_alpha': 0.6975473989907712, 'reg_lambda': 0.001578744314012962}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  59%|████████████████████████████████████████████████████████████████▉                                             | 295/500 [15:02<12:01,  3.52s/it]

[I 2026-05-19 13:00:42,491] Trial 293 finished with value: 0.9497340519276923 and parameters: {'n_estimators': 250, 'learning_rate': 0.03374834485000768, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 170, 'subsample': 0.8266371632772378, 'colsample_bytree': 0.8760562453168163, 'reg_alpha': 0.7255783097199148, 'reg_lambda': 0.0005060280498528485}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  59%|█████████████████████████████████████████████████████████████████                                             | 296/500 [15:02<08:37,  2.54s/it]

[I 2026-05-19 13:00:42,707] Trial 292 finished with value: 0.949735668726872 and parameters: {'n_estimators': 240, 'learning_rate': 0.04128654224506761, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 79, 'subsample': 0.8752349332866979, 'colsample_bytree': 0.9019765357285661, 'reg_alpha': 3.7945298508599405, 'reg_lambda': 0.0006005518785166092}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  59%|█████████████████████████████████████████████████████████████████▎                                            | 297/500 [15:04<08:03,  2.38s/it]

[I 2026-05-19 13:00:44,752] Trial 296 finished with value: 0.9497272254648841 and parameters: {'n_estimators': 240, 'learning_rate': 0.03402328408425004, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 170, 'subsample': 0.8442030545201419, 'colsample_bytree': 0.9033016855485172, 'reg_alpha': 3.8952638201866976, 'reg_lambda': 0.0005957839862548401}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  60%|█████████████████████████████████████████████████████████████████▌                                            | 298/500 [15:05<05:53,  1.75s/it]

[I 2026-05-19 13:00:45,024] Trial 295 finished with value: 0.9497283971627398 and parameters: {'n_estimators': 240, 'learning_rate': 0.033963231448943906, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 168, 'subsample': 0.8408617192067175, 'colsample_bytree': 0.8987170619619618, 'reg_alpha': 0.7819150582593378, 'reg_lambda': 0.0014528878621592495}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  60%|█████████████████████████████████████████████████████████████████▊                                            | 299/500 [15:07<06:07,  1.83s/it]

[I 2026-05-19 13:00:46,982] Trial 297 finished with value: 0.9497289326167049 and parameters: {'n_estimators': 240, 'learning_rate': 0.0340256155895233, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 169, 'subsample': 0.847053775389408, 'colsample_bytree': 0.8965018564308304, 'reg_alpha': 0.6988334831030595, 'reg_lambda': 0.0015259256185234525}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  60%|██████████████████████████████████████████████████████████████████                                            | 300/500 [15:10<07:28,  2.24s/it]

[I 2026-05-19 13:00:50,250] Trial 299 finished with value: 0.9497272647794099 and parameters: {'n_estimators': 241, 'learning_rate': 0.03313593448325722, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 162, 'subsample': 0.8172996569361396, 'colsample_bytree': 0.9087363702056208, 'reg_alpha': 0.5821187875134295, 'reg_lambda': 0.0017454163684422527}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  60%|██████████████████████████████████████████████████████████████████▏                                           | 301/500 [15:19<14:20,  4.32s/it]

[I 2026-05-19 13:00:59,443] Trial 300 finished with value: 0.9497395163124758 and parameters: {'n_estimators': 252, 'learning_rate': 0.040426705703241514, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 78, 'subsample': 0.8418510241126589, 'colsample_bytree': 0.8938768281006111, 'reg_alpha': 0.5268954275516594, 'reg_lambda': 0.0014829457492992113}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  60%|██████████████████████████████████████████████████████████████████▍                                           | 302/500 [15:22<12:28,  3.78s/it]

[I 2026-05-19 13:01:01,945] Trial 301 finished with value: 0.9497306308939948 and parameters: {'n_estimators': 240, 'learning_rate': 0.03351597869056485, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 153, 'subsample': 0.843428962972418, 'colsample_bytree': 0.9028867237264573, 'reg_alpha': 0.6840458044119792, 'reg_lambda': 0.001418586238800673}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  61%|██████████████████████████████████████████████████████████████████▋                                           | 303/500 [15:25<12:16,  3.74s/it]

[I 2026-05-19 13:01:05,599] Trial 302 finished with value: 0.949738043468613 and parameters: {'n_estimators': 212, 'learning_rate': 0.04040497266373626, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 171, 'subsample': 0.8503062150064667, 'colsample_bytree': 0.9088627704028356, 'reg_alpha': 0.7204389661188877, 'reg_lambda': 0.0013184024485384494}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  61%|██████████████████████████████████████████████████████████████████▉                                           | 304/500 [15:30<13:33,  4.15s/it]

[I 2026-05-19 13:01:10,708] Trial 303 finished with value: 0.9497346613941277 and parameters: {'n_estimators': 240, 'learning_rate': 0.04001772796202927, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 57, 'subsample': 0.8513301372999073, 'colsample_bytree': 0.9062243407377936, 'reg_alpha': 0.7349066112263497, 'reg_lambda': 0.0012891665994253611}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  61%|███████████████████████████████████████████████████████████████████                                           | 305/500 [15:31<10:25,  3.21s/it]

[I 2026-05-19 13:01:11,709] Trial 308 finished with value: 0.949709039629379 and parameters: {'n_estimators': 220, 'learning_rate': 0.039734832808561, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 55, 'subsample': 0.8590266416118869, 'colsample_bytree': 0.8950130935919755, 'reg_alpha': 6.502916760645798, 'reg_lambda': 0.0016435188055549121}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  61%|███████████████████████████████████████████████████████████████████▎                                          | 306/500 [15:32<07:56,  2.46s/it]

[I 2026-05-19 13:01:12,366] Trial 304 finished with value: 0.9497357449753421 and parameters: {'n_estimators': 240, 'learning_rate': 0.04015237216062709, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 153, 'subsample': 0.8552289042746044, 'colsample_bytree': 0.8966129408838759, 'reg_alpha': 0.6894035330602034, 'reg_lambda': 0.0015523063767679502}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  61%|███████████████████████████████████████████████████████████████████▌                                          | 307/500 [15:33<06:41,  2.08s/it]

[I 2026-05-19 13:01:13,606] Trial 305 finished with value: 0.9497373312753243 and parameters: {'n_estimators': 242, 'learning_rate': 0.039867037211611195, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 55, 'subsample': 0.8530324727209582, 'colsample_bytree': 0.8999543784531421, 'reg_alpha': 7.204304973046136, 'reg_lambda': 0.0014521076376308002}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  62%|███████████████████████████████████████████████████████████████████▊                                          | 308/500 [15:36<07:09,  2.24s/it]

[I 2026-05-19 13:01:16,229] Trial 309 finished with value: 0.9497170710130373 and parameters: {'n_estimators': 250, 'learning_rate': 0.039826735683705254, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 56, 'subsample': 0.8180276761474474, 'colsample_bytree': 0.8866539555422299, 'reg_alpha': 6.660865383406065, 'reg_lambda': 0.0014339104435902473}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  62%|████████████████████████████████████████████████████████████████████▏                                         | 310/500 [15:37<04:25,  1.40s/it]

[I 2026-05-19 13:01:17,386] Trial 310 finished with value: 0.9497110151721235 and parameters: {'n_estimators': 221, 'learning_rate': 0.0403380224015036, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 58, 'subsample': 0.8530113515131945, 'colsample_bytree': 0.885298525251194, 'reg_alpha': 6.576944331456435, 'reg_lambda': 0.0022907640400899264}. Best is trial 275 with value: 0.9497418267693526.
[I 2026-05-19 13:01:17,575] Trial 307 finished with value: 0.9497302440534229 and parameters: {'n_estimators': 213, 'learning_rate': 0.03963062397557727, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 56, 'subsample': 0.8522110261571275, 'colsample_bytree': 0.8884242303230813, 'reg_alpha': 1.626853751569954, 'reg_lambda': 0.00042840717856341525}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  62%|████████████████████████████████████████████████████████████████████▍                                         | 311/500 [15:41<06:52,  2.18s/it]

[I 2026-05-19 13:01:21,594] Trial 306 finished with value: 0.9497403109439853 and parameters: {'n_estimators': 242, 'learning_rate': 0.03981457305231338, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 167, 'subsample': 0.8539107878976933, 'colsample_bytree': 0.8905960828664131, 'reg_alpha': 1.6400737625064556, 'reg_lambda': 0.0014073402003110583}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  62%|████████████████████████████████████████████████████████████████████▋                                         | 312/500 [15:46<09:03,  2.89s/it]

[I 2026-05-19 13:01:26,148] Trial 311 finished with value: 0.9497400849202735 and parameters: {'n_estimators': 252, 'learning_rate': 0.039613884895768996, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 153, 'subsample': 0.8614110620638971, 'colsample_bytree': 0.8925174647673225, 'reg_alpha': 1.648062362105775, 'reg_lambda': 0.0023482226796953253}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  63%|████████████████████████████████████████████████████████████████████▊                                         | 313/500 [15:54<14:08,  4.54s/it]

[I 2026-05-19 13:01:34,525] Trial 312 finished with value: 0.949728382193751 and parameters: {'n_estimators': 213, 'learning_rate': 0.0396366357527665, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 91, 'subsample': 0.8558483855478723, 'colsample_bytree': 0.8819871304669877, 'reg_alpha': 1.0874644989702078, 'reg_lambda': 0.003095973774136574}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  63%|█████████████████████████████████████████████████████████████████████                                         | 314/500 [16:00<15:18,  4.94s/it]

[I 2026-05-19 13:01:40,399] Trial 313 finished with value: 0.9494782339171932 and parameters: {'n_estimators': 249, 'learning_rate': 0.03977090785655339, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 90, 'subsample': 0.8535584896263848, 'colsample_bytree': 0.8313275526092769, 'reg_alpha': 1.6539581403583505, 'reg_lambda': 0.0024577790960464293}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  63%|█████████████████████████████████████████████████████████████████████▎                                        | 315/500 [16:05<15:08,  4.91s/it]

[I 2026-05-19 13:01:45,245] Trial 315 finished with value: 0.9497233811625139 and parameters: {'n_estimators': 220, 'learning_rate': 0.03934189717577373, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 84, 'subsample': 0.8354979348657243, 'colsample_bytree': 0.8891740631472907, 'reg_alpha': 7.387039914302823, 'reg_lambda': 0.002296531352933232}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  63%|█████████████████████████████████████████████████████████████████████▌                                        | 316/500 [16:07<12:14,  3.99s/it]

[I 2026-05-19 13:01:47,014] Trial 314 finished with value: 0.9497378981188707 and parameters: {'n_estimators': 251, 'learning_rate': 0.039174473018435185, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 89, 'subsample': 0.8600410951145937, 'colsample_bytree': 0.8885644190746039, 'reg_alpha': 1.6782744899193793, 'reg_lambda': 0.002282724960862423}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  63%|█████████████████████████████████████████████████████████████████████▋                                        | 317/500 [16:13<14:16,  4.68s/it]

[I 2026-05-19 13:01:53,358] Trial 317 finished with value: 0.9497367963340977 and parameters: {'n_estimators': 249, 'learning_rate': 0.043753535382851885, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 87, 'subsample': 0.8364311535833223, 'colsample_bytree': 0.8851341016123941, 'reg_alpha': 1.6856570515915883, 'reg_lambda': 0.002245875117139434}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  64%|█████████████████████████████████████████████████████████████████████▉                                        | 318/500 [16:14<10:23,  3.43s/it]

[I 2026-05-19 13:01:53,884] Trial 316 finished with value: 0.9497341116839163 and parameters: {'n_estimators': 250, 'learning_rate': 0.04366148057367608, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 88, 'subsample': 0.8319923304591959, 'colsample_bytree': 0.8892740477680431, 'reg_alpha': 0.4547020909937156, 'reg_lambda': 0.002586185387068231}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  64%|██████████████████████████████████████████████████████████████████████▏                                       | 319/500 [16:15<08:16,  2.74s/it]

[I 2026-05-19 13:01:55,016] Trial 318 finished with value: 0.9497384036960981 and parameters: {'n_estimators': 249, 'learning_rate': 0.043783039041968654, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 85, 'subsample': 0.8271837348602795, 'colsample_bytree': 0.8829995655744168, 'reg_alpha': 1.7993843654336816, 'reg_lambda': 0.002418271052677167}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  64%|██████████████████████████████████████████████████████████████████████▍                                       | 320/500 [16:16<07:05,  2.36s/it]

[I 2026-05-19 13:01:56,506] Trial 319 finished with value: 0.9497386409532371 and parameters: {'n_estimators': 259, 'learning_rate': 0.04344563912451878, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 83, 'subsample': 0.7985603569475149, 'colsample_bytree': 0.8838230760523565, 'reg_alpha': 1.6447927049562054, 'reg_lambda': 0.002112829663569481}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  64%|██████████████████████████████████████████████████████████████████████▌                                       | 321/500 [16:19<07:11,  2.41s/it]

[I 2026-05-19 13:01:59,008] Trial 321 finished with value: 0.9495623185846458 and parameters: {'n_estimators': 250, 'learning_rate': 0.04375039006973208, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 82, 'subsample': 0.8315099662942754, 'colsample_bytree': 0.8315342266184336, 'reg_alpha': 1.633331428558498, 'reg_lambda': 0.0023137684746910186}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  64%|██████████████████████████████████████████████████████████████████████▊                                       | 322/500 [16:19<05:32,  1.87s/it]

[I 2026-05-19 13:01:59,621] Trial 320 finished with value: 0.9495656117203563 and parameters: {'n_estimators': 250, 'learning_rate': 0.044162500346454525, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 88, 'subsample': 0.7730709222487734, 'colsample_bytree': 0.8297001807877629, 'reg_alpha': 1.6929842920099878, 'reg_lambda': 0.00042703754342090947}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  65%|███████████████████████████████████████████████████████████████████████                                       | 323/500 [16:22<06:08,  2.08s/it]

[I 2026-05-19 13:02:02,183] Trial 322 finished with value: 0.9497379817044843 and parameters: {'n_estimators': 249, 'learning_rate': 0.04347922372160156, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 90, 'subsample': 0.8026021209212252, 'colsample_bytree': 0.8855423598288756, 'reg_alpha': 1.6890082750016275, 'reg_lambda': 0.00040104307402056714}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  65%|███████████████████████████████████████████████████████████████████████▎                                      | 324/500 [16:26<08:03,  2.75s/it]

[I 2026-05-19 13:02:06,516] Trial 323 finished with value: 0.94973901823254 and parameters: {'n_estimators': 258, 'learning_rate': 0.04316506044498307, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 90, 'subsample': 0.8332712159656166, 'colsample_bytree': 0.8855588075444129, 'reg_alpha': 1.7142875905960804, 'reg_lambda': 0.0031957538788449386}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  65%|███████████████████████████████████████████████████████████████████████▌                                      | 325/500 [16:29<08:19,  2.86s/it]

[I 2026-05-19 13:02:09,621] Trial 325 finished with value: 0.9497189824340125 and parameters: {'n_estimators': 259, 'learning_rate': 0.04296992506996323, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 177, 'subsample': 0.827667819684879, 'colsample_bytree': 0.8884602473106216, 'reg_alpha': 1.5890196884058898, 'reg_lambda': 0.0004084297386247383}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  65%|███████████████████████████████████████████████████████████████████████▋                                      | 326/500 [16:34<09:44,  3.36s/it]

[I 2026-05-19 13:02:14,155] Trial 324 finished with value: 0.949569804342841 and parameters: {'n_estimators': 258, 'learning_rate': 0.04352813157317718, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 85, 'subsample': 0.773998809305945, 'colsample_bytree': 0.8284913718299187, 'reg_alpha': 1.6987341318689215, 'reg_lambda': 0.0025770757359729383}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  65%|███████████████████████████████████████████████████████████████████████▉                                      | 327/500 [16:43<14:25,  5.01s/it]

[I 2026-05-19 13:02:23,008] Trial 326 finished with value: 0.9497406466349954 and parameters: {'n_estimators': 255, 'learning_rate': 0.04273807007212975, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 178, 'subsample': 0.8320918467511336, 'colsample_bytree': 0.8894161467387395, 'reg_alpha': 1.6521589846549365, 'reg_lambda': 0.0008080635321550532}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  66%|████████████████████████████████████████████████████████████████████████▏                                     | 328/500 [16:46<12:40,  4.42s/it]

[I 2026-05-19 13:02:26,058] Trial 327 finished with value: 0.9497349937843808 and parameters: {'n_estimators': 260, 'learning_rate': 0.043007643671684345, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 189, 'subsample': 0.6652385683600044, 'colsample_bytree': 0.8530510848747652, 'reg_alpha': 0.46238292188813074, 'reg_lambda': 0.005029647569870153}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  66%|████████████████████████████████████████████████████████████████████████▍                                     | 329/500 [16:51<13:35,  4.77s/it]

[I 2026-05-19 13:02:31,649] Trial 328 finished with value: 0.9495702357640825 and parameters: {'n_estimators': 258, 'learning_rate': 0.043826529081172426, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 155, 'subsample': 0.8002698785336817, 'colsample_bytree': 0.8302068407320938, 'reg_alpha': 2.778024040525172, 'reg_lambda': 0.00039205104362474827}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  66%|████████████████████████████████████████████████████████████████████████▌                                     | 330/500 [16:52<09:58,  3.52s/it]

[I 2026-05-19 13:02:32,256] Trial 329 finished with value: 0.9497396468659064 and parameters: {'n_estimators': 258, 'learning_rate': 0.03719940919868329, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 165, 'subsample': 0.6581819820341638, 'colsample_bytree': 0.8676355658699505, 'reg_alpha': 2.7054080847085453, 'reg_lambda': 0.00040628065188160855}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  66%|████████████████████████████████████████████████████████████████████████▊                                     | 331/500 [16:54<08:51,  3.15s/it]

[I 2026-05-19 13:02:34,511] Trial 330 finished with value: 0.9497372736615347 and parameters: {'n_estimators': 259, 'learning_rate': 0.03558351085302551, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 158, 'subsample': 0.6584192992622749, 'colsample_bytree': 0.8453670434421525, 'reg_alpha': 2.480532586519327, 'reg_lambda': 0.004959359709961935}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  67%|█████████████████████████████████████████████████████████████████████████▎                                    | 333/500 [16:57<06:09,  2.21s/it]

[I 2026-05-19 13:02:37,504] Trial 331 finished with value: 0.9494873622661497 and parameters: {'n_estimators': 258, 'learning_rate': 0.03714225210311931, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 163, 'subsample': 0.7784299788298434, 'colsample_bytree': 0.8299003845940583, 'reg_alpha': 2.676880339781058, 'reg_lambda': 0.007166308231323541}. Best is trial 275 with value: 0.9497418267693526.
[I 2026-05-19 13:02:37,627] Trial 332 finished with value: 0.9497323658113199 and parameters: {'n_estimators': 258, 'learning_rate': 0.03515870328349818, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 165, 'subsample': 0.7702253577008524, 'colsample_bytree': 0.8677694366714251, 'reg_alpha': 2.5045426913069115, 'reg_lambda': 0.0002839801066033326}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  67%|█████████████████████████████████████████████████████████████████████████▍                                    | 334/500 [17:02<07:48,  2.82s/it]

[I 2026-05-19 13:02:41,888] Trial 344 pruned.

Best trial: 275. Best value: 0.949742:  67%|█████████████████████████████████████████████████████████████████████████▋                                    | 335/500 [17:02<05:45,  2.09s/it]

[I 2026-05-19 13:02:42,293] Trial 333 finished with value: 0.9497373485848108 and parameters: {'n_estimators': 258, 'learning_rate': 0.03723607766456923, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 164, 'subsample': 0.6668130962233464, 'colsample_bytree': 0.8674663380025937, 'reg_alpha': 2.7123347792030374, 'reg_lambda': 0.00042409121501621585}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  67%|█████████████████████████████████████████████████████████████████████████▉                                    | 336/500 [17:03<04:36,  1.69s/it]

[I 2026-05-19 13:02:43,033] Trial 334 finished with value: 0.9497360535442809 and parameters: {'n_estimators': 260, 'learning_rate': 0.03506777773493398, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 156, 'subsample': 0.6595319830516255, 'colsample_bytree': 0.8688706451697367, 'reg_alpha': 2.5911328132598044, 'reg_lambda': 0.00027510303822498856}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  67%|██████████████████████████████████████████████████████████████████████████▏                                   | 337/500 [17:09<08:07,  2.99s/it]

[I 2026-05-19 13:02:49,063] Trial 336 finished with value: 0.9497357236688728 and parameters: {'n_estimators': 257, 'learning_rate': 0.03750111809366243, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 165, 'subsample': 0.7594046515980434, 'colsample_bytree': 0.8673906446224036, 'reg_alpha': 2.617410046854511, 'reg_lambda': 0.00591628343907046}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  68%|██████████████████████████████████████████████████████████████████████████▎                                   | 338/500 [17:09<05:58,  2.22s/it]

[I 2026-05-19 13:02:49,457] Trial 335 finished with value: 0.949737715249592 and parameters: {'n_estimators': 255, 'learning_rate': 0.04721255617890513, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 165, 'subsample': 0.6613740350318408, 'colsample_bytree': 0.8690133354559315, 'reg_alpha': 3.0798768052650787, 'reg_lambda': 0.005116250908013446}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  68%|██████████████████████████████████████████████████████████████████████████▌                                   | 339/500 [17:15<09:03,  3.37s/it]

[I 2026-05-19 13:02:55,544] Trial 337 finished with value: 0.949735575117707 and parameters: {'n_estimators': 259, 'learning_rate': 0.04769207623884557, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 165, 'subsample': 0.6612331244954076, 'colsample_bytree': 0.8693806919636334, 'reg_alpha': 2.6698518675555043, 'reg_lambda': 0.004168953180695369}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  68%|██████████████████████████████████████████████████████████████████████████▊                                   | 340/500 [17:23<12:32,  4.70s/it]

[I 2026-05-19 13:03:03,319] Trial 338 finished with value: 0.9497354769261117 and parameters: {'n_estimators': 256, 'learning_rate': 0.03748800330149727, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 190, 'subsample': 0.8192207576765719, 'colsample_bytree': 0.8708382510935403, 'reg_alpha': 2.7274479201774042, 'reg_lambda': 0.004114265811570987}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  68%|███████████████████████████████████████████████████████████████████████████                                   | 341/500 [17:26<10:43,  4.05s/it]

[I 2026-05-19 13:03:05,861] Trial 339 finished with value: 0.9497173567018574 and parameters: {'n_estimators': 256, 'learning_rate': 0.028450190146527075, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 156, 'subsample': 0.84303279351221, 'colsample_bytree': 0.9138107317624923, 'reg_alpha': 2.791104688442971, 'reg_lambda': 0.0008202095671356205}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  68%|███████████████████████████████████████████████████████████████████████████▏                                  | 342/500 [17:32<12:12,  4.64s/it]

[I 2026-05-19 13:03:11,878] Trial 342 finished with value: 0.9497355549308842 and parameters: {'n_estimators': 254, 'learning_rate': 0.03731920855310925, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 165, 'subsample': 0.8170890246635754, 'colsample_bytree': 0.8687584578270423, 'reg_alpha': 2.7748149661133112, 'reg_lambda': 0.03879387984705266}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  69%|███████████████████████████████████████████████████████████████████████████▋                                  | 344/500 [17:35<07:37,  2.93s/it]

[I 2026-05-19 13:03:14,814] Trial 340 finished with value: 0.949733787767886 and parameters: {'n_estimators': 255, 'learning_rate': 0.037411165569657734, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 185, 'subsample': 0.822754601814595, 'colsample_bytree': 0.9122881462935826, 'reg_alpha': 2.7223641759132726, 'reg_lambda': 0.004330927400880048}. Best is trial 275 with value: 0.9497418267693526.
[I 2026-05-19 13:03:14,972] Trial 341 finished with value: 0.9497319216443876 and parameters: {'n_estimators': 254, 'learning_rate': 0.03490919113517722, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 165, 'subsample': 0.8151785964567032, 'colsample_bytree': 0.8714926779258517, 'reg_alpha': 2.691689707467904, 'reg_lambda': 0.0007771406208302658}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  69%|███████████████████████████████████████████████████████████████████████████▉                                  | 345/500 [17:38<07:33,  2.92s/it]

[I 2026-05-19 13:03:17,866] Trial 343 finished with value: 0.9497397805176359 and parameters: {'n_estimators': 269, 'learning_rate': 0.03546847916581718, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 165, 'subsample': 0.8141653571876389, 'colsample_bytree': 0.8691074109032901, 'reg_alpha': 1.0752279949582422, 'reg_lambda': 3.0294598435689544}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  69%|████████████████████████████████████████████████████████████████████████████                                  | 346/500 [17:40<07:03,  2.75s/it]

[I 2026-05-19 13:03:20,204] Trial 350 finished with value: 0.9497125155500556 and parameters: {'n_estimators': 159, 'learning_rate': 0.04172579860095708, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 173, 'subsample': 0.8117519917719013, 'colsample_bytree': 0.8933995765719631, 'reg_alpha': 1.085471652564866, 'reg_lambda': 0.0011854055117637321}. Best is trial 275 with value: 0.9497418267693526.
[I 2026-05-19 13:03:20,296] Trial 346 finished with value: 0.9496157178866188 and parameters: {'n_estimators': 245, 'learning_rate': 0.01714949970668453, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 173, 'subsample': 0.8093120835469035, 'colsample_bytree': 0.8917791944974037, 'reg_alpha': 1.2458052935078525, 'reg_lambda': 0.0038845105745740852}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  70%|████████████████████████████████████████████████████████████████████████████▌                                 | 348/500 [17:41<04:16,  1.69s/it]

[I 2026-05-19 13:03:21,112] Trial 347 finished with value: 0.9497350482140435 and parameters: {'n_estimators': 245, 'learning_rate': 0.03800669984808194, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 183, 'subsample': 0.8159969517990455, 'colsample_bytree': 0.9111330064762757, 'reg_alpha': 1.1409961660792605, 'reg_lambda': 0.0011200098516860088}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  70%|████████████████████████████████████████████████████████████████████████████▊                                 | 349/500 [17:45<05:33,  2.21s/it]

[I 2026-05-19 13:03:24,887] Trial 345 finished with value: 0.9497365924144653 and parameters: {'n_estimators': 269, 'learning_rate': 0.03774353028934664, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 154, 'subsample': 0.8110790377195478, 'colsample_bytree': 0.9113239965579627, 'reg_alpha': 1.2244771850581109, 'reg_lambda': 0.00398122781742951}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  70%|█████████████████████████████████████████████████████████████████████████████                                 | 350/500 [17:46<05:03,  2.02s/it]

[I 2026-05-19 13:03:26,399] Trial 348 finished with value: 0.949720083343039 and parameters: {'n_estimators': 246, 'learning_rate': 0.02940947127426668, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 182, 'subsample': 0.8417035077825773, 'colsample_bytree': 0.911609967268337, 'reg_alpha': 1.2317730393936674, 'reg_lambda': 0.0011499106346284913}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  70%|█████████████████████████████████████████████████████████████████████████████▏                                | 351/500 [17:51<07:04,  2.85s/it]

[I 2026-05-19 13:03:31,462] Trial 349 finished with value: 0.9497385529944857 and parameters: {'n_estimators': 267, 'learning_rate': 0.04158615571084106, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 182, 'subsample': 0.8414135413232917, 'colsample_bytree': 0.8895205168082037, 'reg_alpha': 1.2008440765230077, 'reg_lambda': 0.0037405607774711478}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  70%|█████████████████████████████████████████████████████████████████████████████▍                                | 352/500 [17:55<08:00,  3.25s/it]

[I 2026-05-19 13:03:35,741] Trial 358 pruned.

Best trial: 275. Best value: 0.949742:  71%|█████████████████████████████████████████████████████████████████████████████▋                                | 353/500 [17:59<08:06,  3.31s/it]

[I 2026-05-19 13:03:39,173] Trial 351 finished with value: 0.9497356609411881 and parameters: {'n_estimators': 245, 'learning_rate': 0.0416047207417891, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 178, 'subsample': 0.8376623369240153, 'colsample_bytree': 0.9131485603952917, 'reg_alpha': 1.1835162557722658, 'reg_lambda': 0.0011842728660015074}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  71%|█████████████████████████████████████████████████████████████████████████████▉                                | 354/500 [18:06<10:30,  4.32s/it]

[I 2026-05-19 13:03:45,976] Trial 352 finished with value: 0.9497375439202447 and parameters: {'n_estimators': 269, 'learning_rate': 0.041399713192840686, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 178, 'subsample': 0.8091812663277514, 'colsample_bytree': 0.8987138419225845, 'reg_alpha': 1.058752098644784, 'reg_lambda': 0.0011938592564117415}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  71%|██████████████████████████████████████████████████████████████████████████████                                | 355/500 [18:07<08:18,  3.44s/it]

[I 2026-05-19 13:03:47,302] Trial 359 finished with value: 0.9495355377975798 and parameters: {'n_estimators': 270, 'learning_rate': 0.03259423973321368, 'max_depth': 1, 'num_leaves': 6, 'min_child_samples': 178, 'subsample': 0.8332298246009072, 'colsample_bytree': 0.8788432162734494, 'reg_alpha': 1.1483435370285382, 'reg_lambda': 0.0011981021440396593}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  71%|██████████████████████████████████████████████████████████████████████████████▎                               | 356/500 [18:09<06:56,  2.89s/it]

[I 2026-05-19 13:03:48,875] Trial 360 finished with value: 0.9495346271624389 and parameters: {'n_estimators': 263, 'learning_rate': 0.03265988448091583, 'max_depth': 1, 'num_leaves': 10, 'min_child_samples': 141, 'subsample': 0.8408404302101257, 'colsample_bytree': 0.8812722239713722, 'reg_alpha': 1.9347778610662953, 'reg_lambda': 4.265190307612544}. Best is trial 275 with value: 0.9497418267693526.
[I 2026-05-19 13:03:49,034] Trial 353 finished with value: 0.9497388717975624 and parameters: {'n_estimators': 245, 'learning_rate': 0.04147685254351151, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 181, 'subsample': 0.8308007907563095, 'colsample_bytree': 0.8951011128909694, 'reg_alpha': 1.2147975674719194, 'reg_lambda': 0.001180693722890151}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  72%|██████████████████████████████████████████████████████████████████████████████▊                               | 358/500 [18:09<03:59,  1.69s/it]

[I 2026-05-19 13:03:49,816] Trial 361 finished with value: 0.9495313155622558 and parameters: {'n_estimators': 271, 'learning_rate': 0.032148158725879894, 'max_depth': 1, 'num_leaves': 5, 'min_child_samples': 75, 'subsample': 0.8659670057392271, 'colsample_bytree': 0.8780127661962766, 'reg_alpha': 4.91982746212767, 'reg_lambda': 52.288119803613014}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  72%|██████████████████████████████████████████████████████████████████████████████▉                               | 359/500 [18:12<04:41,  1.99s/it]

[I 2026-05-19 13:03:52,523] Trial 354 finished with value: 0.9497387935473975 and parameters: {'n_estimators': 246, 'learning_rate': 0.04124209148096924, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 180, 'subsample': 0.8367926717648242, 'colsample_bytree': 0.8950429949797023, 'reg_alpha': 1.0688549671785283, 'reg_lambda': 4.430328771479769}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  72%|███████████████████████████████████████████████████████████████████████████████▏                              | 360/500 [18:16<05:56,  2.55s/it]

[I 2026-05-19 13:03:56,353] Trial 355 finished with value: 0.9497413644149914 and parameters: {'n_estimators': 267, 'learning_rate': 0.0411099533631647, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 181, 'subsample': 0.8623628925281358, 'colsample_bytree': 0.8789801840361959, 'reg_alpha': 1.192931150030557, 'reg_lambda': 0.0012060737280630935}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  72%|███████████████████████████████████████████████████████████████████████████████▍                              | 361/500 [18:17<04:35,  1.98s/it]

[I 2026-05-19 13:03:57,016] Trial 356 finished with value: 0.9497369750152311 and parameters: {'n_estimators': 269, 'learning_rate': 0.04168935154013225, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 175, 'subsample': 0.8358960806029728, 'colsample_bytree': 0.892320918732174, 'reg_alpha': 1.0763676252812946, 'reg_lambda': 0.0011226784230207731}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  72%|███████████████████████████████████████████████████████████████████████████████▋                              | 362/500 [18:21<06:27,  2.81s/it]

[I 2026-05-19 13:04:01,745] Trial 364 pruned.

Best trial: 275. Best value: 0.949742:  73%|███████████████████████████████████████████████████████████████████████████████▊                              | 363/500 [18:23<05:50,  2.56s/it]

[I 2026-05-19 13:04:03,749] Trial 357 finished with value: 0.9497123490754683 and parameters: {'n_estimators': 267, 'learning_rate': 0.030555496092815118, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 174, 'subsample': 0.8371168984718959, 'colsample_bytree': 0.8961754392049812, 'reg_alpha': 1.1735844264017303, 'reg_lambda': 98.60521718472197}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  73%|████████████████████████████████████████████████████████████████████████████████                              | 364/500 [18:31<09:32,  4.21s/it]

[I 2026-05-19 13:04:11,817] Trial 362 finished with value: 0.9494069592107099 and parameters: {'n_estimators': 269, 'learning_rate': 0.032853054333478286, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 174, 'subsample': 0.8331126266311422, 'colsample_bytree': 0.7439043030846032, 'reg_alpha': 1.9899186027922324, 'reg_lambda': 0.0008092615713016652}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  73%|████████████████████████████████████████████████████████████████████████████████▎                             | 365/500 [18:35<08:43,  3.88s/it]

[I 2026-05-19 13:04:14,915] Trial 368 finished with value: 0.9497159439091238 and parameters: {'n_estimators': 151, 'learning_rate': 0.047365685440036144, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 173, 'subsample': 0.8284944054255367, 'colsample_bytree': 0.8915832326917601, 'reg_alpha': 4.549509172779507, 'reg_lambda': 0.0016909161855024914}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  73%|████████████████████████████████████████████████████████████████████████████████▌                             | 366/500 [18:38<08:06,  3.63s/it]

[I 2026-05-19 13:04:17,969] Trial 363 finished with value: 0.9497336892729162 and parameters: {'n_estimators': 270, 'learning_rate': 0.03207614031496569, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 174, 'subsample': 0.833030127454528, 'colsample_bytree': 0.8810851562182421, 'reg_alpha': 1.7831188685562982, 'reg_lambda': 0.1617586072654019}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 275. Best value: 0.949742:  73%|████████████████████████████████████████████████████████████████████████████████▋                             | 367/500 [18:42<08:46,  3.96s/it]

[I 2026-05-19 13:04:22,687] Trial 367 finished with value: 0.9497090304108605 and parameters: {'n_estimators': 249, 'learning_rate': 0.0314303651635994, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 73, 'subsample': 0.8288660499079027, 'colsample_bytree': 0.8516427238346805, 'reg_alpha': 4.9674838778097765, 'reg_lambda': 32.798544691963144}. Best is trial 275 with value: 0.9497418267693526.

Best trial: 369. Best value: 0.949746:  74%|████████████████████████████████████████████████████████████████████████████████▉                             | 368/500 [18:45<07:48,  3.55s/it]

[I 2026-05-19 13:04:25,284] Trial 369 finished with value: 0.9497463981150632 and parameters: {'n_estimators': 263, 'learning_rate': 0.047418411814875695, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 192, 'subsample': 0.8319703101039705, 'colsample_bytree': 0.8932485427901515, 'reg_alpha': 1.934040912530523, 'reg_lambda': 26.810642869845147}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  74%|█████████████████████████████████████████████████████████████████████████████████▏                            | 369/500 [18:47<06:47,  3.11s/it]

[I 2026-05-19 13:04:27,390] Trial 365 finished with value: 0.9497374563444918 and parameters: {'n_estimators': 266, 'learning_rate': 0.03479975250423876, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 74, 'subsample': 0.8377700303620003, 'colsample_bytree': 0.8795320572371558, 'reg_alpha': 2.0261676870194427, 'reg_lambda': 0.0007133112326744336}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  74%|█████████████████████████████████████████████████████████████████████████████████▍                            | 370/500 [18:51<07:19,  3.38s/it]

[I 2026-05-19 13:04:31,400] Trial 370 finished with value: 0.9497379604288605 and parameters: {'n_estimators': 251, 'learning_rate': 0.04779381856399082, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 174, 'subsample': 0.8303570806272975, 'colsample_bytree': 0.8948977389746073, 'reg_alpha': 1.9725074168791061, 'reg_lambda': 1.4149330526666488}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  74%|█████████████████████████████████████████████████████████████████████████████████▌                            | 371/500 [18:52<05:48,  2.70s/it]

[I 2026-05-19 13:04:32,489] Trial 366 finished with value: 0.9497286386390913 and parameters: {'n_estimators': 265, 'learning_rate': 0.030577930227790342, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 171, 'subsample': 0.8348934029754698, 'colsample_bytree': 0.8807675686169091, 'reg_alpha': 2.0401639400090317, 'reg_lambda': 0.000783763895668519}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  74%|█████████████████████████████████████████████████████████████████████████████████▊                            | 372/500 [18:55<05:54,  2.77s/it]

[I 2026-05-19 13:04:35,399] Trial 372 finished with value: 0.9497415691883584 and parameters: {'n_estimators': 282, 'learning_rate': 0.04731125616459728, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 45, 'subsample': 0.8710249758946649, 'colsample_bytree': 0.8814863818135765, 'reg_alpha': 1.8878932883317325, 'reg_lambda': 2.050308733256118}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  75%|██████████████████████████████████████████████████████████████████████████████████                            | 373/500 [18:57<05:07,  2.42s/it]

[I 2026-05-19 13:04:37,024] Trial 371 finished with value: 0.9497420260459494 and parameters: {'n_estimators': 264, 'learning_rate': 0.04631557469422682, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 188, 'subsample': 0.861837747807253, 'colsample_bytree': 0.8800937296718875, 'reg_alpha': 1.852893958632058, 'reg_lambda': 11.681948307476098}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  75%|██████████████████████████████████████████████████████████████████████████████████▎                           | 374/500 [18:57<03:53,  1.86s/it]

[I 2026-05-19 13:04:37,560] Trial 373 finished with value: 0.9497372285212806 and parameters: {'n_estimators': 264, 'learning_rate': 0.03468984318712017, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 171, 'subsample': 0.8472974619558467, 'colsample_bytree': 0.8748315160931299, 'reg_alpha': 0.4881311264918377, 'reg_lambda': 0.0017252154811414127}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  75%|██████████████████████████████████████████████████████████████████████████████████▌                           | 375/500 [19:06<07:54,  3.80s/it]

[I 2026-05-19 13:04:45,890] Trial 374 finished with value: 0.9497372319466482 and parameters: {'n_estimators': 281, 'learning_rate': 0.03537548921146553, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 46, 'subsample': 0.8630885181133762, 'colsample_bytree': 0.8807988119481602, 'reg_alpha': 1.9448663806325717, 'reg_lambda': 0.0017282407080494258}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  75%|██████████████████████████████████████████████████████████████████████████████████▋                           | 376/500 [19:09<07:52,  3.81s/it]

[I 2026-05-19 13:04:49,728] Trial 381 finished with value: 0.9496822571531343 and parameters: {'n_estimators': 127, 'learning_rate': 0.04506866963033303, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 46, 'subsample': 0.8610441694231011, 'colsample_bytree': 0.9031928894419682, 'reg_alpha': 1.54186028701282, 'reg_lambda': 0.0018275284679888995}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  75%|██████████████████████████████████████████████████████████████████████████████████▉                           | 377/500 [19:11<06:30,  3.18s/it]

[I 2026-05-19 13:04:51,447] Trial 375 finished with value: 0.9497357882532524 and parameters: {'n_estimators': 251, 'learning_rate': 0.04640934352271997, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 47, 'subsample': 0.8638097127729392, 'colsample_bytree': 0.8775544866459924, 'reg_alpha': 1.9377709789749307, 'reg_lambda': 0.0017579624975553503}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  76%|███████████████████████████████████████████████████████████████████████████████████▏                          | 378/500 [19:13<05:43,  2.82s/it]

[I 2026-05-19 13:04:53,426] Trial 376 finished with value: 0.9497333905458835 and parameters: {'n_estimators': 263, 'learning_rate': 0.03499615349286776, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 74, 'subsample': 0.8482881386509774, 'colsample_bytree': 0.8840775278945191, 'reg_alpha': 0.506783417665893, 'reg_lambda': 0.0018496668946351511}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  76%|███████████████████████████████████████████████████████████████████████████████████▍                          | 379/500 [19:15<05:25,  2.69s/it]

[I 2026-05-19 13:04:55,811] Trial 377 finished with value: 0.9497333191840841 and parameters: {'n_estimators': 252, 'learning_rate': 0.03489197684512982, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 75, 'subsample': 0.8641613401950801, 'colsample_bytree': 0.8755525793991367, 'reg_alpha': 0.4885035578819502, 'reg_lambda': 0.0017493707475088834}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  76%|███████████████████████████████████████████████████████████████████████████████████▌                          | 380/500 [19:20<06:30,  3.26s/it]

[I 2026-05-19 13:05:00,370] Trial 379 finished with value: 0.9497354729715781 and parameters: {'n_estimators': 264, 'learning_rate': 0.035076444489293625, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 201, 'subsample': 0.8648766720607902, 'colsample_bytree': 0.9012571637715774, 'reg_alpha': 2.1019982645104616, 'reg_lambda': 0.9627145902907125}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  76%|███████████████████████████████████████████████████████████████████████████████████▊                          | 381/500 [19:24<06:39,  3.36s/it]

[I 2026-05-19 13:05:03,994] Trial 380 finished with value: 0.9497396718890773 and parameters: {'n_estimators': 279, 'learning_rate': 0.0473598540859068, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 197, 'subsample': 0.8626165547617404, 'colsample_bytree': 0.9043060317109357, 'reg_alpha': 2.045840665656488, 'reg_lambda': 19.370830174292188}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  76%|████████████████████████████████████████████████████████████████████████████████████                          | 382/500 [19:25<05:34,  2.84s/it]

[I 2026-05-19 13:05:05,615] Trial 378 finished with value: 0.9497344779458418 and parameters: {'n_estimators': 281, 'learning_rate': 0.04726237324649716, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 47, 'subsample': 0.8651090098649473, 'colsample_bytree': 0.8749026376386762, 'reg_alpha': 0.5188932193361478, 'reg_lambda': 0.0007970130580184138}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  77%|████████████████████████████████████████████████████████████████████████████████████▎                         | 383/500 [19:27<04:52,  2.50s/it]

[I 2026-05-19 13:05:07,321] Trial 382 finished with value: 0.9497417822609033 and parameters: {'n_estimators': 283, 'learning_rate': 0.0387770970994896, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 195, 'subsample': 0.8482495104690393, 'colsample_bytree': 0.9014519243441734, 'reg_alpha': 1.6085393724485988, 'reg_lambda': 0.0017235164802444662}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  77%|████████████████████████████████████████████████████████████████████████████████████▍                         | 384/500 [19:31<05:26,  2.81s/it]

[I 2026-05-19 13:05:10,867] Trial 383 finished with value: 0.9497423769945416 and parameters: {'n_estimators': 276, 'learning_rate': 0.04738057210962417, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 190, 'subsample': 0.8614230030133211, 'colsample_bytree': 0.905154890421978, 'reg_alpha': 0.4318292212632039, 'reg_lambda': 2.609396247302874}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  77%|████████████████████████████████████████████████████████████████████████████████████▋                         | 385/500 [19:36<06:38,  3.46s/it]

[I 2026-05-19 13:05:15,847] Trial 384 finished with value: 0.9497416022620003 and parameters: {'n_estimators': 281, 'learning_rate': 0.049980497278841206, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 200, 'subsample': 0.8687074155889632, 'colsample_bytree': 0.9046921789000695, 'reg_alpha': 0.47774107398156695, 'reg_lambda': 6.197823906735043}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  77%|████████████████████████████████████████████████████████████████████████████████████▉                         | 386/500 [19:36<04:54,  2.59s/it]

[I 2026-05-19 13:05:16,400] Trial 385 finished with value: 0.9497456939047568 and parameters: {'n_estimators': 282, 'learning_rate': 0.04558633677833131, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 196, 'subsample': 0.8664115784467163, 'colsample_bytree': 0.8865510179201407, 'reg_alpha': 0.8059217029682476, 'reg_lambda': 16.377183096639683}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  77%|█████████████████████████████████████████████████████████████████████████████████████▏                        | 387/500 [19:43<07:22,  3.91s/it]

[I 2026-05-19 13:05:23,399] Trial 386 finished with value: 0.9497463589826323 and parameters: {'n_estimators': 286, 'learning_rate': 0.04557757051287305, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 196, 'subsample': 0.8726414079369564, 'colsample_bytree': 0.8883894692785733, 'reg_alpha': 1.5888224617230642, 'reg_lambda': 16.349951978784496}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  78%|█████████████████████████████████████████████████████████████████████████████████████▎                        | 388/500 [19:46<06:28,  3.47s/it]

[I 2026-05-19 13:05:25,843] Trial 387 finished with value: 0.9497134150821503 and parameters: {'n_estimators': 282, 'learning_rate': 0.0477645410475744, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 194, 'subsample': 0.8754486074073077, 'colsample_bytree': 0.9025222523783054, 'reg_alpha': 50.24355742511447, 'reg_lambda': 2.1331234610784717}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  78%|█████████████████████████████████████████████████████████████████████████████████████▊                        | 390/500 [19:49<04:25,  2.41s/it]

[I 2026-05-19 13:05:29,088] Trial 388 finished with value: 0.9497424840181484 and parameters: {'n_estimators': 279, 'learning_rate': 0.03897760187811933, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 191, 'subsample': 0.8864893668163945, 'colsample_bytree': 0.8848712959926356, 'reg_alpha': 0.8828398183082604, 'reg_lambda': 7.20052532194682}. Best is trial 369 with value: 0.9497463981150632.
[I 2026-05-19 13:05:29,188] Trial 389 finished with value: 0.9497352370436956 and parameters: {'n_estimators': 283, 'learning_rate': 0.03884205300103507, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 187, 'subsample': 0.8886643604339863, 'colsample_bytree': 0.8993136925760581, 'reg_alpha': 1.4137308808719609, 'reg_lambda': 5.776027891161066}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  78%|██████████████████████████████████████████████████████████████████████████████████████                        | 391/500 [19:50<03:53,  2.14s/it]

[I 2026-05-19 13:05:30,700] Trial 390 finished with value: 0.9497371282835841 and parameters: {'n_estimators': 280, 'learning_rate': 0.03857377625915814, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 191, 'subsample': 0.8738743594421305, 'colsample_bytree': 0.9021801920101433, 'reg_alpha': 1.540843082140255, 'reg_lambda': 2.9133893753061653}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  78%|██████████████████████████████████████████████████████████████████████████████████████▏                       | 392/500 [19:54<04:44,  2.63s/it]

[I 2026-05-19 13:05:34,457] Trial 391 finished with value: 0.9497364772948433 and parameters: {'n_estimators': 281, 'learning_rate': 0.03896022666449702, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 197, 'subsample': 0.8786284571703519, 'colsample_bytree': 0.8889954738017608, 'reg_alpha': 0.8111497626835348, 'reg_lambda': 10.664322646365054}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  79%|██████████████████████████████████████████████████████████████████████████████████████▍                       | 393/500 [19:59<05:42,  3.20s/it]

[I 2026-05-19 13:05:39,022] Trial 393 finished with value: 0.9497434139883382 and parameters: {'n_estimators': 284, 'learning_rate': 0.04942952300415171, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 199, 'subsample': 0.8829255620692953, 'colsample_bytree': 0.9044657207817772, 'reg_alpha': 0.8875592470500675, 'reg_lambda': 8.997209040004007}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  79%|██████████████████████████████████████████████████████████████████████████████████████▋                       | 394/500 [19:59<04:16,  2.42s/it]

[I 2026-05-19 13:05:39,589] Trial 392 finished with value: 0.9497438037137943 and parameters: {'n_estimators': 284, 'learning_rate': 0.04961968845442644, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 197, 'subsample': 0.8761135198860363, 'colsample_bytree': 0.9029021241637696, 'reg_alpha': 0.9181879362835257, 'reg_lambda': 7.155311981861706}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  79%|██████████████████████████████████████████████████████████████████████████████████████▉                       | 395/500 [20:01<04:01,  2.30s/it]

[I 2026-05-19 13:05:41,627] Trial 394 finished with value: 0.9497434502352764 and parameters: {'n_estimators': 280, 'learning_rate': 0.04727420917889705, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 193, 'subsample': 0.8773171681871881, 'colsample_bytree': 0.9363117468135582, 'reg_alpha': 0.8341215457475659, 'reg_lambda': 6.2676775877397475}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  79%|███████████████████████████████████████████████████████████████████████████████████████                       | 396/500 [20:04<04:21,  2.51s/it]

[I 2026-05-19 13:05:44,606] Trial 395 finished with value: 0.9497402314366603 and parameters: {'n_estimators': 282, 'learning_rate': 0.04931521283774979, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 195, 'subsample': 0.8759998327398127, 'colsample_bytree': 0.919886021845998, 'reg_alpha': 0.7837328980303142, 'reg_lambda': 11.714536513683978}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  79%|███████████████████████████████████████████████████████████████████████████████████████▎                      | 397/500 [20:11<06:17,  3.66s/it]

[I 2026-05-19 13:05:50,970] Trial 397 finished with value: 0.9497442979714055 and parameters: {'n_estimators': 288, 'learning_rate': 0.048900631150512804, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 197, 'subsample': 0.8891343181567851, 'colsample_bytree': 0.9199106834068158, 'reg_alpha': 0.8275869934479841, 'reg_lambda': 11.133529691854898}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  80%|███████████████████████████████████████████████████████████████████████████████████████▌                      | 398/500 [20:12<05:01,  2.95s/it]

[I 2026-05-19 13:05:52,267] Trial 396 finished with value: 0.9497403667397887 and parameters: {'n_estimators': 286, 'learning_rate': 0.049440624056880315, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 195, 'subsample': 0.8803867643841449, 'colsample_bytree': 0.9034488304068617, 'reg_alpha': 0.7898948680959132, 'reg_lambda': 2.354879051240794}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  80%|███████████████████████████████████████████████████████████████████████████████████████▊                      | 399/500 [20:18<06:34,  3.91s/it]

[I 2026-05-19 13:05:58,404] Trial 398 finished with value: 0.9497402271350399 and parameters: {'n_estimators': 286, 'learning_rate': 0.04964328467304048, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 193, 'subsample': 0.8888170975853205, 'colsample_bytree': 0.9229425965010619, 'reg_alpha': 0.773479579865218, 'reg_lambda': 8.98811308883808}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  80%|████████████████████████████████████████████████████████████████████████████████████████                      | 400/500 [20:20<05:22,  3.22s/it]

[I 2026-05-19 13:06:00,015] Trial 399 finished with value: 0.9497443066694172 and parameters: {'n_estimators': 280, 'learning_rate': 0.04978102538110113, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 197, 'subsample': 0.8885556644320066, 'colsample_bytree': 0.9178806260192541, 'reg_alpha': 0.7792589680993127, 'reg_lambda': 8.182658807228515}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  80%|████████████████████████████████████████████████████████████████████████████████████████▏                     | 401/500 [20:24<05:54,  3.58s/it]

[I 2026-05-19 13:06:04,445] Trial 401 finished with value: 0.9497424627799738 and parameters: {'n_estimators': 291, 'learning_rate': 0.04989132922623684, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 208, 'subsample': 0.8786846184018288, 'colsample_bytree': 0.9041201237857663, 'reg_alpha': 0.7811693789897016, 'reg_lambda': 2.6947572508901643}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  80%|████████████████████████████████████████████████████████████████████████████████████████▍                     | 402/500 [20:25<04:33,  2.79s/it]

[I 2026-05-19 13:06:05,359] Trial 400 finished with value: 0.9497411827126282 and parameters: {'n_estimators': 292, 'learning_rate': 0.04951401065167172, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 200, 'subsample': 0.8908670177699279, 'colsample_bytree': 0.9043301438543726, 'reg_alpha': 0.7954660561590043, 'reg_lambda': 7.9131274904655715}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  81%|████████████████████████████████████████████████████████████████████████████████████████▋                     | 403/500 [20:26<03:23,  2.09s/it]

[I 2026-05-19 13:06:05,863] Trial 402 finished with value: 0.9497411095823332 and parameters: {'n_estimators': 290, 'learning_rate': 0.04968911006032243, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 196, 'subsample': 0.8807969084830527, 'colsample_bytree': 0.9225643568169655, 'reg_alpha': 0.8097256431478085, 'reg_lambda': 12.276409455629675}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  81%|████████████████████████████████████████████████████████████████████████████████████████▉                     | 404/500 [20:29<03:46,  2.36s/it]

[I 2026-05-19 13:06:08,825] Trial 404 finished with value: 0.9497305050322031 and parameters: {'n_estimators': 291, 'learning_rate': 0.049230891227273706, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 207, 'subsample': 0.8863266089446395, 'colsample_bytree': 0.9154751362099435, 'reg_alpha': 0.9366797807621214, 'reg_lambda': 9.32330644249635}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  81%|█████████████████████████████████████████████████████████████████████████████████████████                     | 405/500 [20:31<03:55,  2.48s/it]

[I 2026-05-19 13:06:11,594] Trial 403 finished with value: 0.949741263164387 and parameters: {'n_estimators': 294, 'learning_rate': 0.049766158869921806, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 209, 'subsample': 0.8862845288423262, 'colsample_bytree': 0.9254888770459619, 'reg_alpha': 0.9225112343316111, 'reg_lambda': 10.020586890027275}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  81%|█████████████████████████████████████████████████████████████████████████████████████████▎                    | 406/500 [20:32<02:50,  1.81s/it]

[I 2026-05-19 13:06:11,867] Trial 405 finished with value: 0.9497315600068145 and parameters: {'n_estimators': 288, 'learning_rate': 0.04941435185162022, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 205, 'subsample': 0.8787648575858867, 'colsample_bytree': 0.9247369903169945, 'reg_alpha': 0.8577883946042508, 'reg_lambda': 7.644310923411125}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  81%|█████████████████████████████████████████████████████████████████████████████████████████▌                    | 407/500 [20:38<04:45,  3.07s/it]

[I 2026-05-19 13:06:17,853] Trial 406 finished with value: 0.949738530199749 and parameters: {'n_estimators': 292, 'learning_rate': 0.04980960293189008, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 207, 'subsample': 0.8870916163512186, 'colsample_bytree': 0.9405764439783739, 'reg_alpha': 0.33965945121750074, 'reg_lambda': 8.910787867987414}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  82%|█████████████████████████████████████████████████████████████████████████████████████████▊                    | 408/500 [20:39<04:06,  2.68s/it]

[I 2026-05-19 13:06:19,596] Trial 407 finished with value: 0.9497430566785224 and parameters: {'n_estimators': 288, 'learning_rate': 0.04857072240793046, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 199, 'subsample': 0.883934904494092, 'colsample_bytree': 0.9362815757864609, 'reg_alpha': 0.3161382145163471, 'reg_lambda': 6.545711191105669}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  82%|█████████████████████████████████████████████████████████████████████████████████████████▉                    | 409/500 [20:45<05:26,  3.59s/it]

[I 2026-05-19 13:06:25,301] Trial 409 finished with value: 0.9497314936076788 and parameters: {'n_estimators': 289, 'learning_rate': 0.0494933544109627, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 206, 'subsample': 0.8882701546132212, 'colsample_bytree': 0.9367120101720996, 'reg_alpha': 0.3623677864812267, 'reg_lambda': 9.428917037982902}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  82%|██████████████████████████████████████████████████████████████████████████████████████████▏                   | 410/500 [20:48<05:06,  3.41s/it]

[I 2026-05-19 13:06:28,323] Trial 408 finished with value: 0.9497408991180845 and parameters: {'n_estimators': 291, 'learning_rate': 0.04941388031411671, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 205, 'subsample': 0.8843780257739777, 'colsample_bytree': 0.9398904596758189, 'reg_alpha': 0.8354027342297917, 'reg_lambda': 8.806681730176221}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  82%|██████████████████████████████████████████████████████████████████████████████████████████▍                   | 411/500 [20:50<04:38,  3.13s/it]

[I 2026-05-19 13:06:30,790] Trial 410 finished with value: 0.9497324219695585 and parameters: {'n_estimators': 292, 'learning_rate': 0.04996054166485591, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 203, 'subsample': 0.8897795943554142, 'colsample_bytree': 0.9208940533747505, 'reg_alpha': 0.2904695159991445, 'reg_lambda': 7.8098235310534845}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  82%|██████████████████████████████████████████████████████████████████████████████████████████▋                   | 412/500 [20:55<04:59,  3.40s/it]

[I 2026-05-19 13:06:34,850] Trial 411 finished with value: 0.9497299566757288 and parameters: {'n_estimators': 294, 'learning_rate': 0.04935612451129406, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 208, 'subsample': 0.8861986402850843, 'colsample_bytree': 0.935622950476979, 'reg_alpha': 0.33187563172496276, 'reg_lambda': 6.0731125282362015}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  83%|██████████████████████████████████████████████████████████████████████████████████████████▊                   | 413/500 [20:57<04:43,  3.26s/it]

[I 2026-05-19 13:06:37,752] Trial 412 finished with value: 0.9497329931436571 and parameters: {'n_estimators': 291, 'learning_rate': 0.04981855010967388, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 206, 'subsample': 0.8854150918698249, 'colsample_bytree': 0.9386513742375185, 'reg_alpha': 0.40284650779654463, 'reg_lambda': 7.125085728080869}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  83%|███████████████████████████████████████████████████████████████████████████████████████████                   | 414/500 [20:58<03:39,  2.55s/it]

[I 2026-05-19 13:06:38,671] Trial 413 finished with value: 0.9497284211828084 and parameters: {'n_estimators': 293, 'learning_rate': 0.04956009001692018, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 206, 'subsample': 0.8843260279295435, 'colsample_bytree': 0.9285398947249252, 'reg_alpha': 0.3943818726203019, 'reg_lambda': 5.661265748302605}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  83%|███████████████████████████████████████████████████████████████████████████████████████████▎                  | 415/500 [21:00<03:18,  2.34s/it]

[I 2026-05-19 13:06:40,498] Trial 414 finished with value: 0.9497302786960917 and parameters: {'n_estimators': 294, 'learning_rate': 0.049046055696563264, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 209, 'subsample': 0.8908425948187194, 'colsample_bytree': 0.9358846803766575, 'reg_alpha': 0.41278717933042525, 'reg_lambda': 7.663908863951058}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  83%|███████████████████████████████████████████████████████████████████████████████████████████▌                  | 416/500 [21:09<05:51,  4.19s/it]

[I 2026-05-19 13:06:49,002] Trial 415 finished with value: 0.9497398799568698 and parameters: {'n_estimators': 292, 'learning_rate': 0.04976844291465308, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 206, 'subsample': 0.9020632228495643, 'colsample_bytree': 0.9437319691576647, 'reg_alpha': 0.3453607522182242, 'reg_lambda': 6.860869089703842}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  83%|███████████████████████████████████████████████████████████████████████████████████████████▋                  | 417/500 [21:10<04:26,  3.21s/it]

[I 2026-05-19 13:06:49,892] Trial 416 finished with value: 0.9497408323621592 and parameters: {'n_estimators': 293, 'learning_rate': 0.04981960515251622, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 203, 'subsample': 0.8950919010728446, 'colsample_bytree': 0.9382851069932628, 'reg_alpha': 0.31008182998881645, 'reg_lambda': 6.4300446745937805}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  84%|███████████████████████████████████████████████████████████████████████████████████████████▉                  | 418/500 [21:13<04:36,  3.37s/it]

[I 2026-05-19 13:06:53,676] Trial 417 finished with value: 0.9497442906307393 and parameters: {'n_estimators': 294, 'learning_rate': 0.04951246785111025, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 208, 'subsample': 0.8957730977423131, 'colsample_bytree': 0.9389017370523055, 'reg_alpha': 0.38286410046934954, 'reg_lambda': 6.6536371117103865}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  84%|████████████████████████████████████████████████████████████████████████████████████████████▏                 | 419/500 [21:18<05:02,  3.73s/it]

[I 2026-05-19 13:06:58,256] Trial 419 finished with value: 0.9497423621245493 and parameters: {'n_estimators': 292, 'learning_rate': 0.049926759543714075, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 201, 'subsample': 0.8961224505935921, 'colsample_bytree': 0.9441142152506729, 'reg_alpha': 0.2909199005251051, 'reg_lambda': 6.001975060532438}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  84%|████████████████████████████████████████████████████████████████████████████████████████████▍                 | 420/500 [21:19<03:44,  2.81s/it]

[I 2026-05-19 13:06:58,891] Trial 418 finished with value: 0.9497408441908745 and parameters: {'n_estimators': 296, 'learning_rate': 0.04978598369178694, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 199, 'subsample': 0.8984262729237044, 'colsample_bytree': 0.933472308805818, 'reg_alpha': 0.3655337103431399, 'reg_lambda': 5.846876459798863}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  84%|████████████████████████████████████████████████████████████████████████████████████████████▌                 | 421/500 [21:26<05:26,  4.14s/it]

[I 2026-05-19 13:07:06,126] Trial 420 finished with value: 0.9497430336439535 and parameters: {'n_estimators': 297, 'learning_rate': 0.04986466411293444, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 201, 'subsample': 0.8994275352906216, 'colsample_bytree': 0.933709632887397, 'reg_alpha': 0.33637047934026604, 'reg_lambda': 5.578017940227592}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  85%|█████████████████████████████████████████████████████████████████████████████████████████████                 | 423/500 [21:28<03:15,  2.54s/it]

[I 2026-05-19 13:07:08,329] Trial 422 finished with value: 0.949738965858607 and parameters: {'n_estimators': 296, 'learning_rate': 0.04711441473748633, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 201, 'subsample': 0.8942735003498511, 'colsample_bytree': 0.9330709656662972, 'reg_alpha': 0.41441979073787205, 'reg_lambda': 23.292648096740393}. Best is trial 369 with value: 0.9497463981150632.
[I 2026-05-19 13:07:08,492] Trial 421 finished with value: 0.9497422502775832 and parameters: {'n_estimators': 294, 'learning_rate': 0.04973797481588031, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 202, 'subsample': 0.8995587632497788, 'colsample_bytree': 0.9386750306740813, 'reg_alpha': 0.2739239918913696, 'reg_lambda': 6.495716802502537}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▎                | 424/500 [21:35<04:47,  3.78s/it]

[I 2026-05-19 13:07:15,173] Trial 423 finished with value: 0.9497432955017466 and parameters: {'n_estimators': 294, 'learning_rate': 0.04695516261734644, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 202, 'subsample': 0.8967376892285354, 'colsample_bytree': 0.9444749554321479, 'reg_alpha': 0.5629021173847275, 'reg_lambda': 22.02237500158284}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▌                | 425/500 [21:38<04:22,  3.51s/it]

[I 2026-05-19 13:07:18,040] Trial 426 finished with value: 0.949741807276442 and parameters: {'n_estimators': 298, 'learning_rate': 0.04679805697865409, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 199, 'subsample': 0.9021034741723426, 'colsample_bytree': 0.9322328607110485, 'reg_alpha': 0.5687250879941657, 'reg_lambda': 20.91184852402757}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▋                | 426/500 [21:39<03:20,  2.71s/it]

[I 2026-05-19 13:07:18,892] Trial 425 finished with value: 0.9497450751222409 and parameters: {'n_estimators': 297, 'learning_rate': 0.046651548703910944, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 199, 'subsample': 0.8716241199912262, 'colsample_bytree': 0.9488372191811502, 'reg_alpha': 0.5136095707883215, 'reg_lambda': 21.309458469777525}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▉                | 427/500 [21:39<02:33,  2.11s/it]

[I 2026-05-19 13:07:19,610] Trial 424 finished with value: 0.9497389213426934 and parameters: {'n_estimators': 298, 'learning_rate': 0.0470419959396337, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 200, 'subsample': 0.9032286896512149, 'colsample_bytree': 0.9476858232734777, 'reg_alpha': 0.5550411266722215, 'reg_lambda': 23.114934723032036}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  86%|██████████████████████████████████████████████████████████████████████████████████████████████▍               | 429/500 [21:48<03:26,  2.91s/it]

[I 2026-05-19 13:07:28,403] Trial 427 finished with value: 0.9497408473487328 and parameters: {'n_estimators': 297, 'learning_rate': 0.04733291382162503, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 199, 'subsample': 0.8957836585554004, 'colsample_bytree': 0.9458984970941137, 'reg_alpha': 0.5866752181878436, 'reg_lambda': 22.311212965994454}. Best is trial 369 with value: 0.9497463981150632.
[I 2026-05-19 13:07:28,490] Trial 428 finished with value: 0.9497417884752025 and parameters: {'n_estimators': 298, 'learning_rate': 0.04650588652629619, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 199, 'subsample': 0.8981663416155792, 'colsample_bytree': 0.9268580790269891, 'reg_alpha': 0.6115981344296795, 'reg_lambda': 19.850548580237984}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  86%|██████████████████████████████████████████████████████████████████████████████████████████████▌               | 430/500 [21:53<04:06,  3.52s/it]

[I 2026-05-19 13:07:33,434] Trial 429 finished with value: 0.9497418818248704 and parameters: {'n_estimators': 297, 'learning_rate': 0.04663450585531199, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 199, 'subsample': 0.9018335627558799, 'colsample_bytree': 0.9283937237482386, 'reg_alpha': 0.24821247304490285, 'reg_lambda': 20.34728732976836}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  86%|██████████████████████████████████████████████████████████████████████████████████████████████▊               | 431/500 [21:57<04:10,  3.63s/it]

[I 2026-05-19 13:07:37,322] Trial 431 finished with value: 0.9497381041053222 and parameters: {'n_estimators': 300, 'learning_rate': 0.04628049114563055, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 188, 'subsample': 0.9047196756381515, 'colsample_bytree': 0.9563851659388416, 'reg_alpha': 0.538397113174093, 'reg_lambda': 19.220673450514653}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  86%|███████████████████████████████████████████████████████████████████████████████████████████████               | 432/500 [21:58<03:11,  2.81s/it]

[I 2026-05-19 13:07:38,238] Trial 430 finished with value: 0.9497416927566189 and parameters: {'n_estimators': 300, 'learning_rate': 0.04659498365577416, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 199, 'subsample': 0.9022718955339778, 'colsample_bytree': 0.9583076696290144, 'reg_alpha': 0.24534465249494022, 'reg_lambda': 20.923549171208062}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  87%|███████████████████████████████████████████████████████████████████████████████████████████████▍              | 434/500 [22:06<03:20,  3.03s/it]

[I 2026-05-19 13:07:45,956] Trial 434 finished with value: 0.9497387079526242 and parameters: {'n_estimators': 285, 'learning_rate': 0.04544490971874591, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 187, 'subsample': 0.9057299397555598, 'colsample_bytree': 0.9570369260369134, 'reg_alpha': 0.20663207385684534, 'reg_lambda': 4.137617196692855}. Best is trial 369 with value: 0.9497463981150632.
[I 2026-05-19 13:07:46,058] Trial 432 finished with value: 0.9497408982083038 and parameters: {'n_estimators': 300, 'learning_rate': 0.04666933551665766, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 190, 'subsample': 0.9024372171838271, 'colsample_bytree': 0.928315146602988, 'reg_alpha': 0.21659620568663054, 'reg_lambda': 19.48119632247849}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  87%|███████████████████████████████████████████████████████████████████████████████████████████████▋              | 435/500 [22:08<02:52,  2.66s/it]

[I 2026-05-19 13:07:47,832] Trial 433 finished with value: 0.9497410947423794 and parameters: {'n_estimators': 300, 'learning_rate': 0.04614548209058852, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 188, 'subsample': 0.9048140939161771, 'colsample_bytree': 0.9538309310872874, 'reg_alpha': 0.16369244453765583, 'reg_lambda': 14.798679527879202}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  87%|███████████████████████████████████████████████████████████████████████████████████████████████▉              | 436/500 [22:14<04:08,  3.88s/it]

[I 2026-05-19 13:07:54,571] Trial 435 finished with value: 0.9497440831924324 and parameters: {'n_estimators': 299, 'learning_rate': 0.046305954231123596, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 187, 'subsample': 0.8734058203255939, 'colsample_bytree': 0.9643511770405452, 'reg_alpha': 0.22526948708706795, 'reg_lambda': 15.013202026283194}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  87%|████████████████████████████████████████████████████████████████████████████████████████████████▏             | 437/500 [22:19<04:26,  4.22s/it]

[I 2026-05-19 13:07:59,611] Trial 437 finished with value: 0.9497409803334204 and parameters: {'n_estimators': 299, 'learning_rate': 0.04629143441987454, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 191, 'subsample': 0.9031128015637616, 'colsample_bytree': 0.9583794141242589, 'reg_alpha': 0.5262148434808769, 'reg_lambda': 16.14668675618479}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  88%|████████████████████████████████████████████████████████████████████████████████████████████████▎             | 438/500 [22:20<03:10,  3.07s/it]

[I 2026-05-19 13:07:59,993] Trial 438 finished with value: 0.9497387424707349 and parameters: {'n_estimators': 299, 'learning_rate': 0.046112101467094394, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 190, 'subsample': 0.9219002706792532, 'colsample_bytree': 0.9504342309335452, 'reg_alpha': 0.23136321644915342, 'reg_lambda': 18.099509860218262}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  88%|████████████████████████████████████████████████████████████████████████████████████████████████▌             | 439/500 [22:20<02:22,  2.33s/it]

[I 2026-05-19 13:08:00,578] Trial 436 finished with value: 0.9497423944714376 and parameters: {'n_estimators': 299, 'learning_rate': 0.046180813185544504, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 217, 'subsample': 0.9023924625727509, 'colsample_bytree': 0.9492406697167922, 'reg_alpha': 0.17170935318971908, 'reg_lambda': 16.111893394546136}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  88%|████████████████████████████████████████████████████████████████████████████████████████████████▊             | 440/500 [22:27<03:46,  3.77s/it]

[I 2026-05-19 13:08:07,697] Trial 439 finished with value: 0.9497421073936065 and parameters: {'n_estimators': 286, 'learning_rate': 0.04601993395611848, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 189, 'subsample': 0.9161543829985768, 'colsample_bytree': 0.9636716025680787, 'reg_alpha': 0.27360413787643045, 'reg_lambda': 15.003855291298533}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████             | 441/500 [22:28<02:41,  2.74s/it]

[I 2026-05-19 13:08:08,030] Trial 440 finished with value: 0.9497431101257027 and parameters: {'n_estimators': 300, 'learning_rate': 0.045888022473908704, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 189, 'subsample': 0.9177856419670503, 'colsample_bytree': 0.9550650283576637, 'reg_alpha': 0.27967790963605876, 'reg_lambda': 13.508517691416724}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████▏            | 442/500 [22:31<02:47,  2.89s/it]

[I 2026-05-19 13:08:11,259] Trial 441 finished with value: 0.949745243210463 and parameters: {'n_estimators': 287, 'learning_rate': 0.04586827028724289, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 190, 'subsample': 0.9037934357300165, 'colsample_bytree': 0.961141854149291, 'reg_alpha': 0.24821107526046673, 'reg_lambda': 15.77079466048734}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████▍            | 443/500 [22:36<03:22,  3.55s/it]

[I 2026-05-19 13:08:16,385] Trial 442 finished with value: 0.9497399025810334 and parameters: {'n_estimators': 285, 'learning_rate': 0.045907803821401125, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 192, 'subsample': 0.9159424655234366, 'colsample_bytree': 0.9613796867890698, 'reg_alpha': 0.2260291386580647, 'reg_lambda': 32.98959758899338}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████▋            | 444/500 [22:40<03:20,  3.58s/it]

[I 2026-05-19 13:08:20,028] Trial 443 finished with value: 0.9497396036201934 and parameters: {'n_estimators': 300, 'learning_rate': 0.04602489486427544, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 191, 'subsample': 0.9186236827242155, 'colsample_bytree': 0.9585586687758346, 'reg_alpha': 0.203103954359435, 'reg_lambda': 31.05459043533818}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████▉            | 445/500 [22:44<03:31,  3.84s/it]

[I 2026-05-19 13:08:24,486] Trial 445 finished with value: 0.9497441862894951 and parameters: {'n_estimators': 286, 'learning_rate': 0.04556674419456109, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 216, 'subsample': 0.9197241030617385, 'colsample_bytree': 0.9698584596112237, 'reg_alpha': 0.17419702549961188, 'reg_lambda': 31.245671389778153}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████▎           | 447/500 [22:46<02:04,  2.35s/it]

[I 2026-05-19 13:08:26,516] Trial 444 finished with value: 0.9497404412222613 and parameters: {'n_estimators': 299, 'learning_rate': 0.045849041376786456, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 219, 'subsample': 0.9213913885328946, 'colsample_bytree': 0.9596469576672634, 'reg_alpha': 0.2581369833901841, 'reg_lambda': 13.818849864722457}. Best is trial 369 with value: 0.9497463981150632.
[I 2026-05-19 13:08:26,645] Trial 446 finished with value: 0.949739193321409 and parameters: {'n_estimators': 286, 'learning_rate': 0.04563036426488009, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 214, 'subsample': 0.9154362752341927, 'colsample_bytree': 0.9703423831836884, 'reg_alpha': 0.2573841035950737, 'reg_lambda': 31.784477029859893}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  90%|██████████████████████████████████████████████████████████████████████████████████████████████████▌           | 448/500 [22:51<02:41,  3.11s/it]

[I 2026-05-19 13:08:31,514] Trial 447 finished with value: 0.9497382382701153 and parameters: {'n_estimators': 287, 'learning_rate': 0.045426439111636366, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 215, 'subsample': 0.9256098760232396, 'colsample_bytree': 0.9814630004611838, 'reg_alpha': 0.24400127142349695, 'reg_lambda': 32.28520668104164}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  90%|██████████████████████████████████████████████████████████████████████████████████████████████████▊           | 449/500 [22:55<02:43,  3.21s/it]

[I 2026-05-19 13:08:34,972] Trial 449 finished with value: 0.9497435177122323 and parameters: {'n_estimators': 287, 'learning_rate': 0.04525475365694211, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 218, 'subsample': 0.8975688911580896, 'colsample_bytree': 0.9853576032511351, 'reg_alpha': 0.3151319409392933, 'reg_lambda': 46.095225664837216}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████           | 450/500 [22:57<02:20,  2.80s/it]

[I 2026-05-19 13:08:36,835] Trial 450 finished with value: 0.9497415303776444 and parameters: {'n_estimators': 287, 'learning_rate': 0.045527427833677934, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 213, 'subsample': 0.9094356852918158, 'colsample_bytree': 0.9730463484492284, 'reg_alpha': 0.25735342966714536, 'reg_lambda': 31.56357514740165}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████▏          | 451/500 [22:58<02:00,  2.47s/it]

[I 2026-05-19 13:08:38,530] Trial 448 finished with value: 0.9497359698654236 and parameters: {'n_estimators': 286, 'learning_rate': 0.04570313855158017, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 194, 'subsample': 0.9243243962795625, 'colsample_bytree': 0.9739109653052385, 'reg_alpha': 0.2419783708549371, 'reg_lambda': 38.729124092152425}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  91%|███████████████████████████████████████████████████████████████████████████████████████████████████▋          | 453/500 [23:03<01:42,  2.17s/it]

[I 2026-05-19 13:08:42,858] Trial 451 finished with value: 0.9497372652556916 and parameters: {'n_estimators': 287, 'learning_rate': 0.04497854202462282, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 219, 'subsample': 0.915536265517666, 'colsample_bytree': 0.9753679836865682, 'reg_alpha': 0.26098889120408475, 'reg_lambda': 38.04394067114153}. Best is trial 369 with value: 0.9497463981150632.
[I 2026-05-19 13:08:43,006] Trial 452 finished with value: 0.9497401858699215 and parameters: {'n_estimators': 286, 'learning_rate': 0.045052245512403125, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 220, 'subsample': 0.9282940991901216, 'colsample_bytree': 0.9644121413134188, 'reg_alpha': 0.26668898616390496, 'reg_lambda': 39.056680238443285}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  91%|███████████████████████████████████████████████████████████████████████████████████████████████████▉          | 454/500 [23:08<02:24,  3.13s/it]

[I 2026-05-19 13:08:48,409] Trial 453 finished with value: 0.9497396986620359 and parameters: {'n_estimators': 287, 'learning_rate': 0.04539133698458629, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 220, 'subsample': 0.9178106751418602, 'colsample_bytree': 0.9687906684964964, 'reg_alpha': 0.25776701595624046, 'reg_lambda': 32.55156683504477}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████          | 455/500 [23:11<02:13,  2.96s/it]

[I 2026-05-19 13:08:50,959] Trial 454 finished with value: 0.9497382077856914 and parameters: {'n_estimators': 287, 'learning_rate': 0.045301471251915484, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 212, 'subsample': 0.923713001810826, 'colsample_bytree': 0.9781831256051522, 'reg_alpha': 0.2621421226417736, 'reg_lambda': 44.17448572333529}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 456/500 [23:15<02:33,  3.48s/it]

[I 2026-05-19 13:08:55,648] Trial 455 finished with value: 0.9497428741329379 and parameters: {'n_estimators': 284, 'learning_rate': 0.04522655413030964, 'max_depth': 4, 'num_leaves': 4, 'min_child_samples': 195, 'subsample': 0.9392887697005138, 'colsample_bytree': 0.9725300918196632, 'reg_alpha': 0.29221143947544725, 'reg_lambda': 14.144508449305492}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 457/500 [23:22<03:08,  4.38s/it]

[I 2026-05-19 13:09:02,110] Trial 456 finished with value: 0.9497424877842618 and parameters: {'n_estimators': 287, 'learning_rate': 0.04495061671928307, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 218, 'subsample': 0.9370050616260592, 'colsample_bytree': 0.9725102053484581, 'reg_alpha': 0.15483174596614457, 'reg_lambda': 41.42001003220485}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 458/500 [23:23<02:28,  3.54s/it]

[I 2026-05-19 13:09:03,718] Trial 457 finished with value: 0.9497425616290162 and parameters: {'n_estimators': 287, 'learning_rate': 0.04482941436006471, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 215, 'subsample': 0.9195712050630248, 'colsample_bytree': 0.9745603757241421, 'reg_alpha': 0.28546863283620444, 'reg_lambda': 12.976470093211063}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 459/500 [23:25<01:56,  2.84s/it]

[I 2026-05-19 13:09:04,907] Trial 458 finished with value: 0.9497437914970595 and parameters: {'n_estimators': 285, 'learning_rate': 0.04467987831832942, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 223, 'subsample': 0.9273975260165884, 'colsample_bytree': 0.9790555504789894, 'reg_alpha': 0.13688215050631722, 'reg_lambda': 40.89276807504972}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 460/500 [23:25<01:24,  2.10s/it]

[I 2026-05-19 13:09:05,296] Trial 460 finished with value: 0.9497140712063935 and parameters: {'n_estimators': 287, 'learning_rate': 0.04432640637546853, 'max_depth': 4, 'num_leaves': 3, 'min_child_samples': 225, 'subsample': 0.9109026275448763, 'colsample_bytree': 0.9712563602737838, 'reg_alpha': 0.1522867165710994, 'reg_lambda': 40.41663081946394}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 461/500 [23:27<01:15,  1.95s/it]

[I 2026-05-19 13:09:06,892] Trial 461 finished with value: 0.9497102926856631 and parameters: {'n_estimators': 289, 'learning_rate': 0.04442708732923766, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 225, 'subsample': 0.9389993744276892, 'colsample_bytree': 0.9623069497509685, 'reg_alpha': 0.16400236868780227, 'reg_lambda': 50.136290759181634}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 462/500 [23:28<01:11,  1.87s/it]

[I 2026-05-19 13:09:08,585] Trial 459 finished with value: 0.9497399448325841 and parameters: {'n_estimators': 287, 'learning_rate': 0.04457624810446778, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 227, 'subsample': 0.928515428955669, 'colsample_bytree': 0.9768091245880768, 'reg_alpha': 0.13006227887872265, 'reg_lambda': 51.4236888659361}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 463/500 [23:35<02:05,  3.38s/it]

[I 2026-05-19 13:09:15,417] Trial 462 finished with value: 0.9497395173644904 and parameters: {'n_estimators': 288, 'learning_rate': 0.04430162179359529, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 219, 'subsample': 0.910437760068753, 'colsample_bytree': 0.9701712858021871, 'reg_alpha': 0.08480062047168302, 'reg_lambda': 12.065544072464505}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████        | 464/500 [23:37<01:49,  3.03s/it]

[I 2026-05-19 13:09:17,667] Trial 463 finished with value: 0.9497436913463371 and parameters: {'n_estimators': 277, 'learning_rate': 0.044505684185479365, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 225, 'subsample': 0.9321007710911546, 'colsample_bytree': 0.9911609332821217, 'reg_alpha': 0.19192374966296008, 'reg_lambda': 51.84088479017898}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 465/500 [23:40<01:39,  2.84s/it]

[I 2026-05-19 13:09:20,070] Trial 464 finished with value: 0.9497449634981467 and parameters: {'n_estimators': 277, 'learning_rate': 0.04776202746263135, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 212, 'subsample': 0.8774120107970985, 'colsample_bytree': 0.9472332252188913, 'reg_alpha': 0.12151663558945913, 'reg_lambda': 3.911363336438779}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 369. Best value: 0.949746:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 466/500 [23:43<01:43,  3.06s/it]

[I 2026-05-19 13:09:23,667] Trial 465 finished with value: 0.9497412406476682 and parameters: {'n_estimators': 277, 'learning_rate': 0.047493386800060954, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 230, 'subsample': 0.8753685796916232, 'colsample_bytree': 0.9486052999055952, 'reg_alpha': 0.1689010090980784, 'reg_lambda': 13.547942578244305}. Best is trial 369 with value: 0.9497463981150632.

Best trial: 466. Best value: 0.949747:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 467/500 [23:50<02:17,  4.17s/it]

[I 2026-05-19 13:09:30,417] Trial 466 finished with value: 0.9497467182297676 and parameters: {'n_estimators': 292, 'learning_rate': 0.047727485249843014, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 195, 'subsample': 0.8940955907328312, 'colsample_bytree': 0.9880686112438711, 'reg_alpha': 0.07782365396103623, 'reg_lambda': 13.206952900093844}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 468/500 [23:51<01:46,  3.34s/it]

[I 2026-05-19 13:09:31,799] Trial 467 finished with value: 0.949741434034371 and parameters: {'n_estimators': 277, 'learning_rate': 0.04735959533984481, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 227, 'subsample': 0.9390280406996965, 'colsample_bytree': 0.9475541155884396, 'reg_alpha': 0.07954360612912192, 'reg_lambda': 75.73610068426831}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 469/500 [23:58<02:14,  4.33s/it]

[I 2026-05-19 13:09:38,488] Trial 470 finished with value: 0.9497212339921584 and parameters: {'n_estimators': 278, 'learning_rate': 0.04432811095679756, 'max_depth': 2, 'num_leaves': 5, 'min_child_samples': 228, 'subsample': 0.9440202074599311, 'colsample_bytree': 0.9900770301624956, 'reg_alpha': 0.14573014937093146, 'reg_lambda': 62.51066187026923}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 470/500 [23:59<01:37,  3.25s/it]

[I 2026-05-19 13:09:39,182] Trial 468 finished with value: 0.9497435187493014 and parameters: {'n_estimators': 277, 'learning_rate': 0.04773133882036164, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 213, 'subsample': 0.9371089290735313, 'colsample_bytree': 0.9485503589926143, 'reg_alpha': 0.08546665357970426, 'reg_lambda': 59.16377435554343}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 471/500 [24:02<01:32,  3.18s/it]

[I 2026-05-19 13:09:42,210] Trial 469 finished with value: 0.9497413279334616 and parameters: {'n_estimators': 278, 'learning_rate': 0.04387854176243519, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 228, 'subsample': 0.9383051256307033, 'colsample_bytree': 0.9867914433384101, 'reg_alpha': 0.11706469267436304, 'reg_lambda': 56.39318404283523}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 472/500 [24:02<01:04,  2.31s/it]

[I 2026-05-19 13:09:42,465] Trial 471 finished with value: 0.9497423779727603 and parameters: {'n_estimators': 278, 'learning_rate': 0.04403099259474776, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 228, 'subsample': 0.9296874380136555, 'colsample_bytree': 0.9913992210181836, 'reg_alpha': 0.14670228928650736, 'reg_lambda': 64.69002755963193}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████      | 473/500 [24:06<01:10,  2.62s/it]

[I 2026-05-19 13:09:45,861] Trial 473 finished with value: 0.9496261345004916 and parameters: {'n_estimators': 279, 'learning_rate': 0.01862343712094547, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 210, 'subsample': 0.9359341585405384, 'colsample_bytree': 0.9492362947177039, 'reg_alpha': 0.10275237498927467, 'reg_lambda': 86.75257453921697}. Best is trial 466 with value: 0.9497467182297676.
[I 2026-05-19 13:09:45,862] Trial 472 finished with value: 0.949742993033734 and parameters: {'n_estimators': 278, 'learning_rate': 0.04382793319468281, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 228, 'subsample': 0.9524517156608499, 'colsample_bytree': 0.9868557007573526, 'reg_alpha': 0.10502257425262315, 'reg_lambda': 63.419712330011414}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 475/500 [24:09<00:57,  2.31s/it]

[I 2026-05-19 13:09:49,750] Trial 475 finished with value: 0.9497267801404062 and parameters: {'n_estimators': 278, 'learning_rate': 0.04760504100697464, 'max_depth': 2, 'num_leaves': 5, 'min_child_samples': 232, 'subsample': 0.9401566889977646, 'colsample_bytree': 0.9902493715467614, 'reg_alpha': 0.08411086179895674, 'reg_lambda': 97.68337153116087}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 476/500 [24:15<01:12,  3.04s/it]

[I 2026-05-19 13:09:55,004] Trial 474 finished with value: 0.9497437728229455 and parameters: {'n_estimators': 282, 'learning_rate': 0.047885891612374706, 'max_depth': 3, 'num_leaves': 5, 'min_child_samples': 213, 'subsample': 0.9358683824162849, 'colsample_bytree': 0.949331982154103, 'reg_alpha': 0.15464272036317747, 'reg_lambda': 69.41791941520614}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 477/500 [24:18<01:11,  3.09s/it]

[I 2026-05-19 13:09:58,250] Trial 476 finished with value: 0.9496582806258351 and parameters: {'n_estimators': 277, 'learning_rate': 0.020120724248907606, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 228, 'subsample': 0.9362524279544404, 'colsample_bytree': 0.9906555611408024, 'reg_alpha': 0.08171952775655782, 'reg_lambda': 74.19154410572571}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 478/500 [24:23<01:19,  3.62s/it]

[I 2026-05-19 13:10:03,281] Trial 477 finished with value: 0.9497379477811283 and parameters: {'n_estimators': 278, 'learning_rate': 0.04396917740917964, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 236, 'subsample': 0.9458752365789472, 'colsample_bytree': 0.9874015493002078, 'reg_alpha': 0.094971570837192, 'reg_lambda': 80.91052871679058}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 479/500 [24:28<01:24,  4.03s/it]

[I 2026-05-19 13:10:08,368] Trial 479 finished with value: 0.9497394400557807 and parameters: {'n_estimators': 280, 'learning_rate': 0.043941726593334195, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 210, 'subsample': 0.9495768727975804, 'colsample_bytree': 0.9888300909294876, 'reg_alpha': 0.09012907546373619, 'reg_lambda': 61.21899991314097}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 480/500 [24:30<01:08,  3.44s/it]

[I 2026-05-19 13:10:10,347] Trial 478 finished with value: 0.9496431395790467 and parameters: {'n_estimators': 280, 'learning_rate': 0.018904324462681456, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 212, 'subsample': 0.9465910209283135, 'colsample_bytree': 0.9894264526865305, 'reg_alpha': 0.1095032171832393, 'reg_lambda': 89.34487856761874}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 481/500 [24:38<01:30,  4.75s/it]

[I 2026-05-19 13:10:18,261] Trial 480 finished with value: 0.9497390760813197 and parameters: {'n_estimators': 281, 'learning_rate': 0.04320794182483464, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 212, 'subsample': 0.9335102757656611, 'colsample_bytree': 0.9996362761061652, 'reg_alpha': 0.05493399680302171, 'reg_lambda': 65.55090700039605}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████    | 482/500 [24:39<01:05,  3.65s/it]

[I 2026-05-19 13:10:19,272] Trial 481 finished with value: 0.9497414221616036 and parameters: {'n_estimators': 280, 'learning_rate': 0.04766643845390277, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 214, 'subsample': 0.9336633896604902, 'colsample_bytree': 0.9973142971162585, 'reg_alpha': 0.07489788943053367, 'reg_lambda': 64.7616291026847}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 483/500 [24:41<00:55,  3.26s/it]

[I 2026-05-19 13:10:21,609] Trial 482 finished with value: 0.9497447370174614 and parameters: {'n_estimators': 281, 'learning_rate': 0.04803967438752981, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 210, 'subsample': 0.9444407754602757, 'colsample_bytree': 0.9879060273543735, 'reg_alpha': 0.04927496766666529, 'reg_lambda': 87.61160263497796}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 484/500 [24:42<00:38,  2.42s/it]

[I 2026-05-19 13:10:22,052] Trial 483 finished with value: 0.9496608079799831 and parameters: {'n_estimators': 281, 'learning_rate': 0.021460111197429764, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 211, 'subsample': 0.9372830948786935, 'colsample_bytree': 0.9931834306285822, 'reg_alpha': 0.05800612208002408, 'reg_lambda': 82.31273483939789}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 486/500 [24:45<00:25,  1.80s/it]

[I 2026-05-19 13:10:24,688] Trial 485 finished with value: 0.9497411923094813 and parameters: {'n_estimators': 282, 'learning_rate': 0.04765141200418035, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 211, 'subsample': 0.9468633738222887, 'colsample_bytree': 0.9993649615688985, 'reg_alpha': 0.05972993327008354, 'reg_lambda': 26.985873906476957}. Best is trial 466 with value: 0.9497467182297676.
[I 2026-05-19 13:10:24,828] Trial 484 finished with value: 0.949745331528883 and parameters: {'n_estimators': 282, 'learning_rate': 0.04806198167528676, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 211, 'subsample': 0.9462217392902398, 'colsample_bytree': 0.9966666327113061, 'reg_alpha': 0.03126784681300187, 'reg_lambda': 25.633089240012897}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 487/500 [24:46<00:23,  1.82s/it]

[I 2026-05-19 13:10:26,723] Trial 486 finished with value: 0.9497432186491439 and parameters: {'n_estimators': 282, 'learning_rate': 0.04780519256895375, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 240, 'subsample': 0.9519079465845043, 'colsample_bytree': 0.9818607173468552, 'reg_alpha': 0.07866079672546349, 'reg_lambda': 26.00088118102878}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 488/500 [24:56<00:49,  4.15s/it]

[I 2026-05-19 13:10:36,348] Trial 487 finished with value: 0.9496723507250933 and parameters: {'n_estimators': 293, 'learning_rate': 0.020782049894183963, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 236, 'subsample': 0.9522477428162797, 'colsample_bytree': 0.9976262444190184, 'reg_alpha': 0.04971099366457276, 'reg_lambda': 68.07402887831608}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 489/500 [24:57<00:35,  3.18s/it]

[I 2026-05-19 13:10:37,260] Trial 488 finished with value: 0.9497400143830493 and parameters: {'n_estimators': 293, 'learning_rate': 0.047704493833020806, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 237, 'subsample': 0.9493247044662938, 'colsample_bytree': 0.9822230787768443, 'reg_alpha': 0.12413706871100967, 'reg_lambda': 4.072054268136047}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 490/500 [25:03<00:41,  4.12s/it]

[I 2026-05-19 13:10:43,590] Trial 489 finished with value: 0.9497440421186969 and parameters: {'n_estimators': 293, 'learning_rate': 0.04781508797453741, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 211, 'subsample': 0.9464346227047715, 'colsample_bytree': 0.9830371109571822, 'reg_alpha': 0.07429658226908784, 'reg_lambda': 58.42688394173643}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 491/500 [25:06<00:34,  3.80s/it]

[I 2026-05-19 13:10:46,642] Trial 490 finished with value: 0.9497463269987089 and parameters: {'n_estimators': 294, 'learning_rate': 0.04750426553491352, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 212, 'subsample': 0.9530726271569965, 'colsample_bytree': 0.9832718575677379, 'reg_alpha': 0.08129001909489335, 'reg_lambda': 27.217931201187856}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 492/500 [25:09<00:26,  3.34s/it]

[I 2026-05-19 13:10:48,904] Trial 491 finished with value: 0.9493892510040348 and parameters: {'n_estimators': 293, 'learning_rate': 0.00992887848167478, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 203, 'subsample': 0.878875353234607, 'colsample_bytree': 0.9989582060022645, 'reg_alpha': 0.037763112429605325, 'reg_lambda': 29.784374947701025}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 493/500 [25:09<00:18,  2.58s/it]

[I 2026-05-19 13:10:49,732] Trial 494 finished with value: 0.9497249699681001 and parameters: {'n_estimators': 293, 'learning_rate': 0.04753812539640985, 'max_depth': 4, 'num_leaves': 3, 'min_child_samples': 204, 'subsample': 0.8915468801258397, 'colsample_bytree': 0.9793870057322008, 'reg_alpha': 0.06344366417684141, 'reg_lambda': 3.8943797294659603}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 494/500 [25:10<00:12,  2.11s/it]

[I 2026-05-19 13:10:50,721] Trial 495 finished with value: 0.9497253496937074 and parameters: {'n_estimators': 291, 'learning_rate': 0.04770609744017387, 'max_depth': 4, 'num_leaves': 3, 'min_child_samples': 202, 'subsample': 0.8922362207831661, 'colsample_bytree': 0.9542158254209654, 'reg_alpha': 0.022957227481675953, 'reg_lambda': 25.714342146458744}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 466. Best value: 0.949747:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 495/500 [25:12<00:09,  1.99s/it]

[I 2026-05-19 13:10:52,456] Trial 496 finished with value: 0.9497311665194653 and parameters: {'n_estimators': 294, 'learning_rate': 0.047572243440710336, 'max_depth': 4, 'num_leaves': 3, 'min_child_samples': 203, 'subsample': 0.8793401453416023, 'colsample_bytree': 0.9799125257584171, 'reg_alpha': 0.05637997984693592, 'reg_lambda': 3.780124410044026}. Best is trial 466 with value: 0.9497467182297676.

Best trial: 492. Best value: 0.949748:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 497/500 [25:13<00:03,  1.11s/it]

[I 2026-05-19 13:10:52,880] Trial 492 finished with value: 0.9497476583824082 and parameters: {'n_estimators': 293, 'learning_rate': 0.047663767796583004, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 196, 'subsample': 0.8952983695946886, 'colsample_bytree': 0.982244251020764, 'reg_alpha': 0.06333722350987524, 'reg_lambda': 24.555536711114392}. Best is trial 492 with value: 0.9497476583824082.
[I 2026-05-19 13:10:53,017] Trial 493 finished with value: 0.9497462849214097 and parameters: {'n_estimators': 293, 'learning_rate': 0.04813066555427673, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 205, 'subsample': 0.9530650014050607, 'colsample_bytree': 0.9534396312007958, 'reg_alpha': 0.026313305792090274, 'reg_lambda': 10.794856829728921}. Best is trial 492 with value: 0.9497476583824082.

Best trial: 492. Best value: 0.949748: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 498/500 [25:14<00:02,  1.19s/it]

[I 2026-05-19 13:10:54,400] Trial 498 finished with value: 0.9491925595290418 and parameters: {'n_estimators': 273, 'learning_rate': 0.00998917695223314, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 240, 'subsample': 0.8752383644154257, 'colsample_bytree': 0.9775455450251381, 'reg_alpha': 0.044277078837069606, 'reg_lambda': 25.292524583006696}. Best is trial 492 with value: 0.9497476583824082.

Best trial: 492. Best value: 0.949748: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 499/500 [25:15<00:01,  1.02s/it]

[I 2026-05-19 13:10:55,035] Trial 497 finished with value: 0.9494266381249286 and parameters: {'n_estimators': 292, 'learning_rate': 0.009803871954013351, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 204, 'subsample': 0.8790810759283725, 'colsample_bytree': 0.983425707353601, 'reg_alpha': 0.05341511231495445, 'reg_lambda': 3.6516958546913707}. Best is trial 492 with value: 0.9497476583824082.

Best trial: 492. Best value: 0.949748: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [25:15<00:00,  3.03s/it]

[I 2026-05-19 13:10:55,475] Trial 499 finished with value: 0.9497407813150088 and parameters: {'n_estimators': 274, 'learning_rate': 0.047734855947167094, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 220, 'subsample': 0.9277019288071781, 'colsample_bytree': 0.9786859166495131, 'reg_alpha': 0.042875462839447036, 'reg_lambda': 26.085384739854828}. Best is trial 492 with value: 0.9497476583824082.
Best trial score:
0.9497476583824082

Best params:
{'n_estimators': 293, 'learning_rate': 0.047663767796583004, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 196, 'subsample': 0.8952983695946886, 'colsample_bytree': 0.982244251020764, 'reg_alpha': 0.06333722350987524, 'reg_lambda': 24.555536711114392}

## Train Dataset

In [16]:
cv = StratifiedKFold(shuffle=True, random_state=42, n_splits=5)

stacking_proba = cross_val_predict(
    LGBMClassifier(**study.best_params), 
    X_train_proba[features_to_use], 
    y_train.PitNextLap,
    cv=cv, 
    n_jobs=-1, 
    method='predict_proba'
)[:, 1]

In [17]:
X_train_stacking = X_train_proba.copy()
X_train_stacking['stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba'] = stacking_proba

# Test Dataset

In [18]:
stacking = LGBMClassifier(**study.best_params).fit(X_train_proba[features_to_use], y_train.PitNextLap)

[LightGBM] [Info] Number of positive: 87381, number of negative: 351759
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001116 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 765
[LightGBM] [Info] Number of data points in the train set: 439140, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198982 -> initscore=-1.392668
[LightGBM] [Info] Start training from score -1.392668

In [19]:
X_test_stacking = X_test_proba.copy()
X_test_stacking['stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba'] = stacking.predict_proba(X_test_proba[features_to_use])[:, 1]

# Saving

In [20]:
X_test_stacking.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,ridge_logit,voting_lgbm_cat_xgb_hist_proba,voting_lg_ridge_proba,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,-1.272709,0.019849,-0.629264,0.006334
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,-0.626960,0.012173,-0.279447,0.003675
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,-1.335019,0.010304,-0.661186,0.003484
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.190133,0.444558,0.424415,0.238053
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.535153,0.939648,0.688728,0.895339

In [21]:
X_train_stacking.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,ridge_logit,voting_lgbm_cat_xgb_hist_proba,voting_lg_ridge_proba,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.500714,0.868510,0.716126,0.773266
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.335105,0.772514,0.636769,0.591885
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.136991,0.717012,0.546431,0.516648
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,-1.247050,0.005494,0.112073,0.001113
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,-0.094611,0.482416,0.445065,0.293469

In [22]:
X_train_stacking.to_parquet('../data/processed/X_train_stacking2.parquet')
X_test_stacking.to_parquet('../data/processed/X_test_stacking2.parquet')

[LightGBM] [Info] Number of positive: 69905, number of negative: 281407
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.060958 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 765
[LightGBM] [Info] Number of data points in the train set: 351312, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198983 -> initscore=-1.392665
[LightGBM] [Info] Start training from score -1.392665
[LightGBM] [Info] Number of positive: 69905, number of negative: 281407
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.062352 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 765
[LightGBM] [Info] Number of data points in the train set: 351312, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198983 -> initscore=-1.392665
[LightGBM] [Info] Start training from score -1.392665
[LightGBM] [Info] Number of positive: 69905, number of negative: 281407
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.076755 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 765
[LightGBM] [Info] Number of data points in the train set: 351312, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198983 -> initscore=-1.392665
[LightGBM] [Info] Start training from score -1.392665
[LightGBM] [Info] Number of positive: 69904, number of negative: 281408
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001051 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 765
[LightGBM] [Info] Number of data points in the train set: 351312, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198980 -> initscore=-1.392683
[LightGBM] [Info] Start training from score -1.392683
[LightGBM] [Info] Number of positive: 69905, number of negative: 281407
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.055037 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 765
[LightGBM] [Info] Number of data points in the train set: 351312, number of used features: 3
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198983 -> initscore=-1.392665
[LightGBM] [Info] Start training from score -1.392665