# Imports

In [44]:
import re
import torch
import optuna
import pickle

import numpy as np
import pandas as pd
import tensorflow as tf

from sklearn import set_config
from catboost import CatBoostClassifier
from category_encoders import CatBoostEncoder

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import StackingClassifier, VotingClassifier
from sklearn.preprocessing import TargetEncoder, StandardScaler, RobustScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures
from pytorch_tabnet.tab_model import TabNetClassifier

from tensorflow.keras import layers
from tensorflow.keras import callbacks
from tensorflow.keras import regularizers
from tensorflow.keras.models import Sequential

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1778800699.793923  184631 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

## Utils

In [31]:
set_config(enable_metadata_routing=True)

In [32]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

In [33]:
column_transformer = ColumnTransformer([
    (
        'target_encoder', 
        TargetEncoder(), 
        ['driver', 'compound', 'race']
    ),
    (
        'catboost_encoder', 
        CatBoostEncoder(), 
        ['driver', 'compound', 'race']
    ),
    (
        'standard_scaler', 
        StandardScaler(), 
        ['lapnumber', 'position', 'raceprogress', 'year', 'position_norm', 'race_progress_sin', 'position_vs_mean']
    ),
    (
        'robust_scaler', 
        RobustScaler(), 
        [
            'position_change', 'cumulative_degradation', 'laptime_delta', 'laptime_s', 'stint', 'driver_mean_lap', 'tyrelife', 'delta_x_tyre_life', 
            'compound_tyre_life', 'stint_progress', 'tyre_life_ratio', 'degradation_per_lap', 'position_change_cum', 'laps_since_pit', 'lap_time_inv',  
            'lap_time_vs_race_mean', 'lap_time_x_tyre', 'position_x_progress', 'degradation_x_progress', 'race_progress_squared', 'driver_avg_position' 
        ]
    ),
], remainder="passthrough")

# Loading Dataset

In [34]:
X_train = pd.read_parquet('../data/X_train.parquet')
X_test = pd.read_parquet('../data/X_test.parquet')

y_train = pd.read_parquet('../data/y_train.parquet')

In [35]:
X_train.head()

,driver,compound,race,year,pitstop,lapnumber,stint,tyrelife,position,laptime_s,...,treeraceprogress,treeposition,treelaptime_s,treecumulative_degradation,treeraceprogress_position,treeraceprogress_laptime_s,treeraceprogress_cumulative_degradation,treeposition_laptime_s,treeposition_cumulative_degradation,treelaptime_s_cumulative_degradation
id,,,,,,,,,,,,,,,,,,,,,
0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,...,0.298107,0.207392,0.252153,0.279021,0.298107,0.298107,0.321361,0.252153,0.279021,0.253721
1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,...,0.298107,0.185508,0.252153,0.586119,0.298107,0.298107,0.610176,0.252153,0.544023,0.613159
2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,...,0.298107,0.207392,0.252153,0.207676,0.298107,0.298107,0.423519,0.252153,0.228194,0.231339
3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,...,0.102471,0.185508,0.178575,0.138352,0.102471,0.102471,0.043550,0.178575,0.138352,0.070991
4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,...,0.298107,0.185508,0.178575,0.138352,0.298107,0.298107,0.206543,0.178575,0.138352,0.153276

In [36]:
X_test.head()

,driver,compound,race,year,pitstop,lapnumber,stint,tyrelife,position,laptime_s,...,treeraceprogress,treeposition,treelaptime_s,treecumulative_degradation,treeraceprogress_position,treeraceprogress_laptime_s,treeraceprogress_cumulative_degradation,treeposition_laptime_s,treeposition_cumulative_degradation,treelaptime_s_cumulative_degradation
id,,,,,,,,,,,,,,,,,,,,,
439140,D119,MEDIUM,British Grand Prix,2023,0,21,1,21.0,4,93.387,...,0.298107,0.185508,0.178575,0.138352,0.298107,0.298107,0.206543,0.178575,0.138352,0.070991
439141,VER,MEDIUM,Abu Dhabi Grand Prix,2023,0,24,1,24.0,1,90.867,...,0.298107,0.185508,0.178575,0.147360,0.298107,0.298107,0.321361,0.178575,0.147360,0.253721
439142,D270,MEDIUM,British Grand Prix,2023,0,24,1,24.0,11,92.871,...,0.298107,0.207392,0.178575,0.138352,0.298107,0.298107,0.206543,0.178575,0.138352,0.070991
439143,D112,SOFT,São Paulo Grand Prix,2024,0,6,2,4.0,15,94.967,...,0.102471,0.207392,0.178575,0.279021,0.102471,0.102471,0.071042,0.178575,0.279021,0.216120
439144,AND,HARD,United States Grand Prix,2024,0,52,2,29.0,12,99.112,...,0.298107,0.207392,0.178575,0.111582,0.298107,0.298107,0.206543,0.178575,0.111582,0.216120

## Creating Stacking Database

In [7]:
lgbm = load_pickle('../models/model_lightgbm.pkl')
cat = load_pickle('../models/model_pure_catboost.pkl')
catencoder_cat = load_pickle('../models/model_catboostencoder_catboost.pkl')
xgb = load_pickle('../models/model_xgboost.pkl')
hist = load_pickle('../models/model_histgradientboosting.pkl')
lg = load_pickle('../models/model_logistic_regression.pkl')
voting = load_pickle('../models/model_voting.pkl')

In [9]:
cv = StratifiedKFold(shuffle=True, random_state=42, n_splits=5)

lgbm_proba = cross_val_predict(lgbm, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba')[:, 1]
catencoder_cat_proba = cross_val_predict(catencoder_cat, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba')[:, 1]
xgb_proba = cross_val_predict(xgb, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba')[:, 1]
hist_proba = cross_val_predict(hist, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba')[:, 1]
lg_proba = cross_val_predict(lg, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba')[:, 1]
voting_proba = cross_val_predict(voting, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba',)[:, 1]

In [39]:
oof_preds = np.zeros(len(X_train))
test_preds = np.zeros(len(X_test))

for fold, (train_idx, valid_idx) in enumerate(cv.split(X_train, y_train)):

    print(f"\n======== Fold {fold + 1} ========")

    X_tr = X_train.iloc[train_idx, :]
    X_val = X_train.iloc[valid_idx, :]

    y_tr = y_train.iloc[train_idx, 0]
    y_val = y_train.iloc[valid_idx, 0]

    X_tr_transformed = column_transformer.fit_transform(X_tr, y_tr)
    X_val_transformed = column_transformer.transform(X_val)
    X_test_transformed = column_transformer.transform(X_test)

    tab_net = TabNetClassifier(
        n_d=32,
        n_a=32,
        n_steps=5,
        gamma=1.5,
        lambda_sparse=1e-4,
        optimizer_fn=torch.optim.Adam,
        optimizer_params=dict(lr=1e-2),
        scheduler_fn=torch.optim.lr_scheduler.StepLR,
        scheduler_params={"step_size": 20, "gamma": 0.9},
        mask_type="entmax",
        seed=42,
        verbose=1
    )

    tab_net.fit(
        X_train=X_tr_transformed,
        y_train=y_tr.values,
        eval_set=[(X_val_transformed, y_val.values)],
        eval_name=["valid"],
        eval_metric=["auc"],
        max_epochs=200,
        patience=20,
        batch_size=1024,
        virtual_batch_size=128,
        num_workers=11,
        drop_last=False
    )

    oof_preds[valid_idx] = tab_net.predict_proba(X_val_transformed)[:, 1]

fold_test_preds = tab_net.predict_proba(X_test_transformed)[:, 1]

======== Fold 1 ========

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.38938 | valid_auc: 0.87697 |  0:00:18s
epoch 1  | loss: 0.31181 | valid_auc: 0.90711 |  0:00:36s
epoch 2  | loss: 0.29353 | valid_auc: 0.91508 |  0:00:55s
epoch 3  | loss: 0.28634 | valid_auc: 0.91695 |  0:01:13s
epoch 4  | loss: 0.28057 | valid_auc: 0.92062 |  0:01:31s
epoch 5  | loss: 0.27775 | valid_auc: 0.92153 |  0:01:50s
epoch 6  | loss: 0.27262 | valid_auc: 0.92349 |  0:02:09s
epoch 7  | loss: 0.27408 | valid_auc: 0.92603 |  0:02:27s
epoch 8  | loss: 0.27558 | valid_auc: 0.91391 |  0:02:46s
epoch 9  | loss: 0.27669 | valid_auc: 0.92439 |  0:03:05s
epoch 10 | loss: 0.27044 | valid_auc: 0.9255  |  0:03:25s
epoch 11 | loss: 0.2665  | valid_auc: 0.92826 |  0:03:44s
epoch 12 | loss: 0.26389 | valid_auc: 0.9234  |  0:04:03s
epoch 13 | loss: 0.26803 | valid_auc: 0.92958 |  0:04:22s
epoch 14 | loss: 0.26174 | valid_auc: 0.92913 |  0:04:41s
epoch 15 | loss: 0.26173 | valid_auc: 0.93231 |  0:05:00s
epoch 16 | loss: 0.25639 | valid_auc: 0.9342  |  0:05:19s
epoch 17 | loss: 0.25391 | valid_auc: 0.9354  |  0:05:38s
epoch 18 | loss: 0.25301 | valid_auc: 0.93367 |  0:05:56s
epoch 19 | loss: 0.25149 | valid_auc: 0.93619 |  0:06:15s
epoch 20 | loss: 0.24895 | valid_auc: 0.93779 |  0:06:33s
epoch 21 | loss: 0.24712 | valid_auc: 0.93811 |  0:06:52s
epoch 22 | loss: 0.24568 | valid_auc: 0.93844 |  0:07:10s
epoch 23 | loss: 0.24594 | valid_auc: 0.93804 |  0:07:29s
epoch 24 | loss: 0.24788 | valid_auc: 0.9359  |  0:07:47s
epoch 25 | loss: 0.24995 | valid_auc: 0.93747 |  0:08:06s
epoch 26 | loss: 0.24627 | valid_auc: 0.93895 |  0:08:24s
epoch 27 | loss: 0.24346 | valid_auc: 0.93927 |  0:08:43s
epoch 28 | loss: 0.24813 | valid_auc: 0.93814 |  0:09:01s
epoch 29 | loss: 0.24566 | valid_auc: 0.93958 |  0:09:19s
epoch 30 | loss: 0.24379 | valid_auc: 0.93636 |  0:09:38s
epoch 31 | loss: 0.245   | valid_auc: 0.93946 |  0:09:56s
epoch 32 | loss: 0.24193 | valid_auc: 0.94105 |  0:10:15s
epoch 33 | loss: 0.23981 | valid_auc: 0.94153 |  0:10:33s
epoch 34 | loss: 0.23898 | valid_auc: 0.94146 |  0:10:52s
epoch 35 | loss: 0.2378  | valid_auc: 0.94196 |  0:11:10s
epoch 36 | loss: 0.23807 | valid_auc: 0.94137 |  0:11:29s
epoch 37 | loss: 0.23639 | valid_auc: 0.94226 |  0:11:48s
epoch 38 | loss: 0.23535 | valid_auc: 0.94177 |  0:12:08s
epoch 39 | loss: 0.23665 | valid_auc: 0.93999 |  0:12:27s
epoch 40 | loss: 0.23996 | valid_auc: 0.94215 |  0:12:45s
epoch 41 | loss: 0.23756 | valid_auc: 0.94056 |  0:13:03s
epoch 42 | loss: 0.23708 | valid_auc: 0.94195 |  0:13:22s
epoch 43 | loss: 0.23341 | valid_auc: 0.94184 |  0:13:40s
epoch 44 | loss: 0.23245 | valid_auc: 0.94232 |  0:13:59s
epoch 45 | loss: 0.23256 | valid_auc: 0.94248 |  0:14:17s
epoch 46 | loss: 0.23095 | valid_auc: 0.94309 |  0:14:37s
epoch 47 | loss: 0.22947 | valid_auc: 0.94359 |  0:14:55s
epoch 48 | loss: 0.22892 | valid_auc: 0.94333 |  0:15:14s
epoch 49 | loss: 0.2284  | valid_auc: 0.94236 |  0:15:34s
epoch 50 | loss: 0.22867 | valid_auc: 0.94154 |  0:15:52s
epoch 51 | loss: 0.22789 | valid_auc: 0.94078 |  0:16:11s
epoch 52 | loss: 0.22648 | valid_auc: 0.94185 |  0:16:30s
epoch 53 | loss: 0.22527 | valid_auc: 0.94043 |  0:16:48s
epoch 54 | loss: 0.22451 | valid_auc: 0.9427  |  0:17:06s
epoch 55 | loss: 0.22425 | valid_auc: 0.94247 |  0:17:24s
epoch 56 | loss: 0.22358 | valid_auc: 0.94242 |  0:17:41s
epoch 57 | loss: 0.22297 | valid_auc: 0.94309 |  0:17:59s
epoch 58 | loss: 0.22246 | valid_auc: 0.94322 |  0:18:17s
epoch 59 | loss: 0.22179 | valid_auc: 0.94223 |  0:18:35s
epoch 60 | loss: 0.22081 | valid_auc: 0.94215 |  0:18:53s
epoch 61 | loss: 0.21912 | valid_auc: 0.94218 |  0:19:11s
epoch 62 | loss: 0.21802 | valid_auc: 0.94038 |  0:19:29s
epoch 63 | loss: 0.21759 | valid_auc: 0.94165 |  0:19:48s
epoch 64 | loss: 0.21817 | valid_auc: 0.93922 |  0:20:07s
epoch 65 | loss: 0.21925 | valid_auc: 0.94227 |  0:20:25s
epoch 66 | loss: 0.2163  | valid_auc: 0.94017 |  0:20:43s
epoch 67 | loss: 0.21515 | valid_auc: 0.941   |  0:21:01s

Early stopping occurred at epoch 67 with best_epoch = 47 and best_valid_auc = 0.94359

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

======== Fold 2 ========

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.40031 | valid_auc: 0.87885 |  0:00:18s
epoch 1  | loss: 0.31507 | valid_auc: 0.90376 |  0:00:36s
epoch 2  | loss: 0.3018  | valid_auc: 0.90688 |  0:00:54s
epoch 3  | loss: 0.29502 | valid_auc: 0.90745 |  0:01:13s
epoch 4  | loss: 0.29097 | valid_auc: 0.91542 |  0:01:31s
epoch 5  | loss: 0.27766 | valid_auc: 0.92156 |  0:01:49s
epoch 6  | loss: 0.27288 | valid_auc: 0.92577 |  0:02:07s
epoch 7  | loss: 0.26842 | valid_auc: 0.92112 |  0:02:25s
epoch 8  | loss: 0.27309 | valid_auc: 0.92271 |  0:02:43s
epoch 9  | loss: 0.26883 | valid_auc: 0.92504 |  0:03:02s
epoch 10 | loss: 0.26934 | valid_auc: 0.92639 |  0:03:20s
epoch 11 | loss: 0.26708 | valid_auc: 0.92384 |  0:03:38s
epoch 12 | loss: 0.27629 | valid_auc: 0.9191  |  0:03:56s
epoch 13 | loss: 0.27221 | valid_auc: 0.92677 |  0:04:14s
epoch 14 | loss: 0.26327 | valid_auc: 0.9291  |  0:04:32s
epoch 15 | loss: 0.26062 | valid_auc: 0.9305  |  0:04:50s
epoch 16 | loss: 0.25933 | valid_auc: 0.93206 |  0:05:09s
epoch 17 | loss: 0.25882 | valid_auc: 0.931   |  0:05:27s
epoch 18 | loss: 0.25702 | valid_auc: 0.93249 |  0:05:45s
epoch 19 | loss: 0.25602 | valid_auc: 0.93276 |  0:06:03s
epoch 20 | loss: 0.25323 | valid_auc: 0.93425 |  0:06:21s
epoch 21 | loss: 0.25132 | valid_auc: 0.93527 |  0:06:39s
epoch 22 | loss: 0.24918 | valid_auc: 0.93545 |  0:07:00s
epoch 23 | loss: 0.24776 | valid_auc: 0.93695 |  0:07:21s
epoch 24 | loss: 0.24625 | valid_auc: 0.93786 |  0:07:41s
epoch 25 | loss: 0.24455 | valid_auc: 0.93762 |  0:08:03s
epoch 26 | loss: 0.24468 | valid_auc: 0.93756 |  0:08:23s
epoch 27 | loss: 0.24321 | valid_auc: 0.93907 |  0:08:41s
epoch 28 | loss: 0.24498 | valid_auc: 0.93511 |  0:08:59s
epoch 29 | loss: 0.24509 | valid_auc: 0.93617 |  0:09:18s
epoch 30 | loss: 0.24422 | valid_auc: 0.93623 |  0:09:36s
epoch 31 | loss: 0.24352 | valid_auc: 0.93726 |  0:09:55s
epoch 32 | loss: 0.24298 | valid_auc: 0.93703 |  0:10:13s
epoch 33 | loss: 0.24182 | valid_auc: 0.93606 |  0:10:31s
epoch 34 | loss: 0.2407  | valid_auc: 0.93811 |  0:10:49s
epoch 35 | loss: 0.24057 | valid_auc: 0.93808 |  0:11:08s
epoch 36 | loss: 0.2388  | valid_auc: 0.93604 |  0:11:26s
epoch 37 | loss: 0.23802 | valid_auc: 0.93864 |  0:11:44s
epoch 38 | loss: 0.23867 | valid_auc: 0.93851 |  0:12:02s
epoch 39 | loss: 0.2369  | valid_auc: 0.93792 |  0:12:20s
epoch 40 | loss: 0.23625 | valid_auc: 0.93957 |  0:12:38s
epoch 41 | loss: 0.23615 | valid_auc: 0.93967 |  0:12:56s
epoch 42 | loss: 0.23484 | valid_auc: 0.93993 |  0:13:14s
epoch 43 | loss: 0.23424 | valid_auc: 0.93958 |  0:13:32s
epoch 44 | loss: 0.23203 | valid_auc: 0.9399  |  0:13:50s
epoch 45 | loss: 0.23105 | valid_auc: 0.93927 |  0:14:08s
epoch 46 | loss: 0.23279 | valid_auc: 0.93924 |  0:14:26s
epoch 47 | loss: 0.23189 | valid_auc: 0.94058 |  0:14:44s
epoch 48 | loss: 0.22957 | valid_auc: 0.9407  |  0:15:02s
epoch 49 | loss: 0.22919 | valid_auc: 0.94088 |  0:15:20s
epoch 50 | loss: 0.22805 | valid_auc: 0.94089 |  0:15:38s
epoch 51 | loss: 0.22708 | valid_auc: 0.94069 |  0:15:56s
epoch 52 | loss: 0.22681 | valid_auc: 0.94144 |  0:16:14s
epoch 53 | loss: 0.22566 | valid_auc: 0.94095 |  0:16:33s
epoch 54 | loss: 0.22517 | valid_auc: 0.94125 |  0:16:51s
epoch 55 | loss: 0.2251  | valid_auc: 0.94141 |  0:17:09s
epoch 56 | loss: 0.22422 | valid_auc: 0.94079 |  0:17:27s
epoch 57 | loss: 0.22604 | valid_auc: 0.94052 |  0:17:45s
epoch 58 | loss: 0.22538 | valid_auc: 0.93795 |  0:18:03s
epoch 59 | loss: 0.2269  | valid_auc: 0.94141 |  0:18:21s
epoch 60 | loss: 0.22359 | valid_auc: 0.94104 |  0:18:39s
epoch 61 | loss: 0.22294 | valid_auc: 0.94083 |  0:18:57s
epoch 62 | loss: 0.22143 | valid_auc: 0.94135 |  0:19:15s
epoch 63 | loss: 0.22359 | valid_auc: 0.94183 |  0:19:33s
epoch 64 | loss: 0.22265 | valid_auc: 0.94019 |  0:19:51s
epoch 65 | loss: 0.22502 | valid_auc: 0.94134 |  0:20:10s
epoch 66 | loss: 0.22135 | valid_auc: 0.94133 |  0:20:28s
epoch 67 | loss: 0.23031 | valid_auc: 0.94063 |  0:20:46s
epoch 68 | loss: 0.22363 | valid_auc: 0.94152 |  0:21:04s
epoch 69 | loss: 0.22307 | valid_auc: 0.9417  |  0:21:22s
epoch 70 | loss: 0.22    | valid_auc: 0.94123 |  0:21:40s
epoch 71 | loss: 0.21901 | valid_auc: 0.94128 |  0:21:58s
epoch 72 | loss: 0.21745 | valid_auc: 0.94081 |  0:22:16s
epoch 73 | loss: 0.2169  | valid_auc: 0.94132 |  0:22:35s
epoch 74 | loss: 0.21694 | valid_auc: 0.9406  |  0:22:53s
epoch 75 | loss: 0.21556 | valid_auc: 0.94121 |  0:23:11s
epoch 76 | loss: 0.2156  | valid_auc: 0.94086 |  0:23:29s
epoch 77 | loss: 0.2149  | valid_auc: 0.9409  |  0:23:47s
epoch 78 | loss: 0.21468 | valid_auc: 0.94093 |  0:24:05s
epoch 79 | loss: 0.21388 | valid_auc: 0.94065 |  0:24:23s
epoch 80 | loss: 0.21314 | valid_auc: 0.94088 |  0:24:42s
epoch 81 | loss: 0.21672 | valid_auc: 0.94001 |  0:25:00s
epoch 82 | loss: 0.21561 | valid_auc: 0.94069 |  0:25:19s
epoch 83 | loss: 0.21277 | valid_auc: 0.94022 |  0:25:37s

Early stopping occurred at epoch 83 with best_epoch = 63 and best_valid_auc = 0.94183

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

======== Fold 3 ========

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.38878 | valid_auc: 0.88842 |  0:00:18s
epoch 1  | loss: 0.31388 | valid_auc: 0.90445 |  0:00:36s
epoch 2  | loss: 0.30597 | valid_auc: 0.89879 |  0:00:54s
epoch 3  | loss: 0.29984 | valid_auc: 0.90635 |  0:01:13s
epoch 4  | loss: 0.29632 | valid_auc: 0.90879 |  0:01:31s
epoch 5  | loss: 0.29181 | valid_auc: 0.91154 |  0:01:49s
epoch 6  | loss: 0.28858 | valid_auc: 0.91417 |  0:02:07s
epoch 7  | loss: 0.2846  | valid_auc: 0.91714 |  0:02:25s
epoch 8  | loss: 0.27764 | valid_auc: 0.9218  |  0:02:43s
epoch 9  | loss: 0.28051 | valid_auc: 0.92265 |  0:03:02s
epoch 10 | loss: 0.27353 | valid_auc: 0.92564 |  0:03:20s
epoch 11 | loss: 0.27219 | valid_auc: 0.92319 |  0:03:38s
epoch 12 | loss: 0.26944 | valid_auc: 0.92721 |  0:03:56s
epoch 13 | loss: 0.26484 | valid_auc: 0.92861 |  0:04:14s
epoch 14 | loss: 0.26236 | valid_auc: 0.93052 |  0:04:32s
epoch 15 | loss: 0.26089 | valid_auc: 0.93139 |  0:04:50s
epoch 16 | loss: 0.26242 | valid_auc: 0.93145 |  0:05:09s
epoch 17 | loss: 0.26383 | valid_auc: 0.93093 |  0:05:27s
epoch 18 | loss: 0.26153 | valid_auc: 0.92927 |  0:05:45s
epoch 19 | loss: 0.25996 | valid_auc: 0.93268 |  0:06:03s
epoch 20 | loss: 0.25597 | valid_auc: 0.9337  |  0:06:21s
epoch 21 | loss: 0.25662 | valid_auc: 0.93325 |  0:06:39s
epoch 22 | loss: 0.25919 | valid_auc: 0.93291 |  0:06:57s
epoch 23 | loss: 0.25762 | valid_auc: 0.93146 |  0:07:15s
epoch 24 | loss: 0.25425 | valid_auc: 0.93399 |  0:07:33s
epoch 25 | loss: 0.25237 | valid_auc: 0.93494 |  0:07:52s
epoch 26 | loss: 0.2529  | valid_auc: 0.93415 |  0:08:10s
epoch 27 | loss: 0.25225 | valid_auc: 0.93603 |  0:08:28s
epoch 28 | loss: 0.25481 | valid_auc: 0.93432 |  0:08:46s
epoch 29 | loss: 0.24929 | valid_auc: 0.93657 |  0:09:04s
epoch 30 | loss: 0.2502  | valid_auc: 0.93705 |  0:09:22s
epoch 31 | loss: 0.24617 | valid_auc: 0.93789 |  0:09:41s
epoch 32 | loss: 0.24415 | valid_auc: 0.93908 |  0:09:59s
epoch 33 | loss: 0.24401 | valid_auc: 0.93946 |  0:10:17s
epoch 34 | loss: 0.24186 | valid_auc: 0.93861 |  0:10:35s
epoch 35 | loss: 0.24144 | valid_auc: 0.93931 |  0:10:53s
epoch 36 | loss: 0.2402  | valid_auc: 0.93955 |  0:11:11s
epoch 37 | loss: 0.23965 | valid_auc: 0.93904 |  0:11:30s
epoch 38 | loss: 0.23854 | valid_auc: 0.93993 |  0:11:48s
epoch 39 | loss: 0.23918 | valid_auc: 0.9398  |  0:12:06s
epoch 40 | loss: 0.23797 | valid_auc: 0.94081 |  0:12:24s
epoch 41 | loss: 0.24059 | valid_auc: 0.93401 |  0:12:42s
epoch 42 | loss: 0.25073 | valid_auc: 0.93204 |  0:13:00s
epoch 43 | loss: 0.25416 | valid_auc: 0.93235 |  0:13:18s
epoch 44 | loss: 0.25156 | valid_auc: 0.93549 |  0:13:37s
epoch 45 | loss: 0.24509 | valid_auc: 0.93735 |  0:13:55s
epoch 46 | loss: 0.24223 | valid_auc: 0.93736 |  0:14:13s
epoch 47 | loss: 0.24233 | valid_auc: 0.93781 |  0:14:31s
epoch 48 | loss: 0.23971 | valid_auc: 0.93978 |  0:14:49s
epoch 49 | loss: 0.23946 | valid_auc: 0.93874 |  0:15:08s
epoch 50 | loss: 0.24133 | valid_auc: 0.93882 |  0:15:26s
epoch 51 | loss: 0.24007 | valid_auc: 0.93956 |  0:15:44s
epoch 52 | loss: 0.23887 | valid_auc: 0.93995 |  0:16:02s
epoch 53 | loss: 0.23601 | valid_auc: 0.94098 |  0:16:20s
epoch 54 | loss: 0.23483 | valid_auc: 0.94091 |  0:16:39s
epoch 55 | loss: 0.23857 | valid_auc: 0.93977 |  0:16:57s
epoch 56 | loss: 0.23845 | valid_auc: 0.94024 |  0:17:15s
epoch 57 | loss: 0.23623 | valid_auc: 0.94016 |  0:17:33s
epoch 58 | loss: 0.23753 | valid_auc: 0.93871 |  0:17:51s
epoch 59 | loss: 0.23715 | valid_auc: 0.9398  |  0:18:09s
epoch 60 | loss: 0.23856 | valid_auc: 0.94014 |  0:18:28s
epoch 61 | loss: 0.23867 | valid_auc: 0.94076 |  0:18:46s
epoch 62 | loss: 0.23415 | valid_auc: 0.94112 |  0:19:04s
epoch 63 | loss: 0.23384 | valid_auc: 0.94104 |  0:19:22s
epoch 64 | loss: 0.23301 | valid_auc: 0.9418  |  0:19:40s
epoch 65 | loss: 0.23167 | valid_auc: 0.94069 |  0:19:58s
epoch 66 | loss: 0.23372 | valid_auc: 0.9392  |  0:20:17s
epoch 67 | loss: 0.23402 | valid_auc: 0.94046 |  0:20:35s
epoch 68 | loss: 0.23101 | valid_auc: 0.94209 |  0:20:53s
epoch 69 | loss: 0.23034 | valid_auc: 0.94245 |  0:21:11s
epoch 70 | loss: 0.22917 | valid_auc: 0.9423  |  0:21:29s
epoch 71 | loss: 0.22928 | valid_auc: 0.94173 |  0:21:47s
epoch 72 | loss: 0.22819 | valid_auc: 0.943   |  0:22:05s
epoch 73 | loss: 0.22851 | valid_auc: 0.94239 |  0:22:23s
epoch 74 | loss: 0.22769 | valid_auc: 0.94133 |  0:22:42s
epoch 75 | loss: 0.22669 | valid_auc: 0.94272 |  0:23:00s
epoch 76 | loss: 0.22965 | valid_auc: 0.94134 |  0:23:18s
epoch 77 | loss: 0.22802 | valid_auc: 0.9416  |  0:23:36s
epoch 78 | loss: 0.22616 | valid_auc: 0.94216 |  0:23:54s
epoch 79 | loss: 0.22498 | valid_auc: 0.94123 |  0:24:12s
epoch 80 | loss: 0.22485 | valid_auc: 0.94298 |  0:24:30s
epoch 81 | loss: 0.22711 | valid_auc: 0.94263 |  0:24:48s
epoch 82 | loss: 0.22659 | valid_auc: 0.9425  |  0:25:06s
epoch 83 | loss: 0.22442 | valid_auc: 0.94263 |  0:25:24s
epoch 84 | loss: 0.22463 | valid_auc: 0.94306 |  0:25:42s
epoch 85 | loss: 0.22272 | valid_auc: 0.94308 |  0:26:00s
epoch 86 | loss: 0.22173 | valid_auc: 0.9426  |  0:26:18s
epoch 87 | loss: 0.22086 | valid_auc: 0.94285 |  0:26:36s
epoch 88 | loss: 0.22008 | valid_auc: 0.94292 |  0:26:54s
epoch 89 | loss: 0.22273 | valid_auc: 0.9428  |  0:27:13s
epoch 90 | loss: 0.22115 | valid_auc: 0.94267 |  0:27:31s
epoch 91 | loss: 0.21988 | valid_auc: 0.94284 |  0:27:49s
epoch 92 | loss: 0.21864 | valid_auc: 0.94222 |  0:28:07s
epoch 93 | loss: 0.21862 | valid_auc: 0.94293 |  0:28:25s
epoch 94 | loss: 0.21815 | valid_auc: 0.94262 |  0:28:43s
epoch 95 | loss: 0.21865 | valid_auc: 0.94236 |  0:29:01s
epoch 96 | loss: 0.21806 | valid_auc: 0.94253 |  0:29:19s
epoch 97 | loss: 0.21739 | valid_auc: 0.94184 |  0:29:37s
epoch 98 | loss: 0.21763 | valid_auc: 0.94262 |  0:29:55s
epoch 99 | loss: 0.21635 | valid_auc: 0.94258 |  0:30:13s
epoch 100| loss: 0.21497 | valid_auc: 0.94191 |  0:30:31s
epoch 101| loss: 0.21457 | valid_auc: 0.94218 |  0:30:50s
epoch 102| loss: 0.21386 | valid_auc: 0.94236 |  0:31:08s
epoch 103| loss: 0.21375 | valid_auc: 0.94201 |  0:31:26s
epoch 104| loss: 0.21323 | valid_auc: 0.94151 |  0:31:44s
epoch 105| loss: 0.21405 | valid_auc: 0.94193 |  0:32:02s

Early stopping occurred at epoch 105 with best_epoch = 85 and best_valid_auc = 0.94308

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

======== Fold 4 ========

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.3942  | valid_auc: 0.87716 |  0:00:18s
epoch 1  | loss: 0.32433 | valid_auc: 0.89208 |  0:00:36s
epoch 2  | loss: 0.30328 | valid_auc: 0.90596 |  0:00:55s
epoch 3  | loss: 0.29303 | valid_auc: 0.91385 |  0:01:13s
epoch 4  | loss: 0.28603 | valid_auc: 0.91558 |  0:01:31s
epoch 5  | loss: 0.27947 | valid_auc: 0.91868 |  0:01:49s
epoch 6  | loss: 0.27455 | valid_auc: 0.92065 |  0:02:08s
epoch 7  | loss: 0.27476 | valid_auc: 0.91975 |  0:02:26s
epoch 8  | loss: 0.27053 | valid_auc: 0.92542 |  0:02:44s
epoch 9  | loss: 0.26682 | valid_auc: 0.92701 |  0:03:02s
epoch 10 | loss: 0.26314 | valid_auc: 0.92881 |  0:03:21s
epoch 11 | loss: 0.25953 | valid_auc: 0.93065 |  0:03:39s
epoch 12 | loss: 0.25793 | valid_auc: 0.92828 |  0:03:57s
epoch 13 | loss: 0.25589 | valid_auc: 0.93078 |  0:04:15s
epoch 14 | loss: 0.25404 | valid_auc: 0.93284 |  0:04:34s
epoch 15 | loss: 0.25204 | valid_auc: 0.93338 |  0:04:52s
epoch 16 | loss: 0.25187 | valid_auc: 0.93434 |  0:05:10s
epoch 17 | loss: 0.24833 | valid_auc: 0.93539 |  0:05:28s
epoch 18 | loss: 0.24911 | valid_auc: 0.93411 |  0:05:47s
epoch 19 | loss: 0.24859 | valid_auc: 0.93557 |  0:06:05s
epoch 20 | loss: 0.2448  | valid_auc: 0.93584 |  0:06:23s
epoch 21 | loss: 0.24314 | valid_auc: 0.93819 |  0:06:41s
epoch 22 | loss: 0.2422  | valid_auc: 0.93817 |  0:06:59s
epoch 23 | loss: 0.24121 | valid_auc: 0.93778 |  0:07:17s
epoch 24 | loss: 0.23996 | valid_auc: 0.93738 |  0:07:35s
epoch 25 | loss: 0.23833 | valid_auc: 0.93964 |  0:07:54s
epoch 26 | loss: 0.23938 | valid_auc: 0.93759 |  0:08:12s
epoch 27 | loss: 0.23718 | valid_auc: 0.93955 |  0:08:30s
epoch 28 | loss: 0.23453 | valid_auc: 0.94009 |  0:08:48s
epoch 29 | loss: 0.23397 | valid_auc: 0.94009 |  0:09:06s
epoch 30 | loss: 0.23312 | valid_auc: 0.94003 |  0:09:24s
epoch 31 | loss: 0.23146 | valid_auc: 0.94036 |  0:09:43s
epoch 32 | loss: 0.23243 | valid_auc: 0.94025 |  0:10:01s
epoch 33 | loss: 0.23131 | valid_auc: 0.94093 |  0:10:19s
epoch 34 | loss: 0.23093 | valid_auc: 0.93965 |  0:10:38s
epoch 35 | loss: 0.2304  | valid_auc: 0.93992 |  0:10:58s
epoch 36 | loss: 0.22883 | valid_auc: 0.93908 |  0:11:17s
epoch 37 | loss: 0.22727 | valid_auc: 0.9416  |  0:11:36s
epoch 38 | loss: 0.22756 | valid_auc: 0.94113 |  0:11:54s
epoch 39 | loss: 0.22605 | valid_auc: 0.94018 |  0:12:13s
epoch 40 | loss: 0.22396 | valid_auc: 0.94114 |  0:12:32s
epoch 41 | loss: 0.22326 | valid_auc: 0.94133 |  0:12:51s
epoch 42 | loss: 0.22266 | valid_auc: 0.94162 |  0:13:09s
epoch 43 | loss: 0.22149 | valid_auc: 0.941   |  0:13:28s
epoch 44 | loss: 0.22095 | valid_auc: 0.94138 |  0:13:46s
epoch 45 | loss: 0.22052 | valid_auc: 0.93875 |  0:14:05s
epoch 46 | loss: 0.21955 | valid_auc: 0.9411  |  0:14:24s
epoch 47 | loss: 0.21938 | valid_auc: 0.94014 |  0:14:42s
epoch 48 | loss: 0.2189  | valid_auc: 0.93851 |  0:15:01s
epoch 49 | loss: 0.21732 | valid_auc: 0.94021 |  0:15:20s
epoch 50 | loss: 0.21832 | valid_auc: 0.93771 |  0:15:39s
epoch 51 | loss: 0.21686 | valid_auc: 0.93952 |  0:15:57s
epoch 52 | loss: 0.21569 | valid_auc: 0.93863 |  0:16:16s
epoch 53 | loss: 0.21865 | valid_auc: 0.93966 |  0:16:35s
epoch 54 | loss: 0.21448 | valid_auc: 0.93632 |  0:16:53s
epoch 55 | loss: 0.21359 | valid_auc: 0.93832 |  0:17:12s
epoch 56 | loss: 0.21357 | valid_auc: 0.9391  |  0:17:30s
epoch 57 | loss: 0.2129  | valid_auc: 0.9392  |  0:17:49s
epoch 58 | loss: 0.21194 | valid_auc: 0.93797 |  0:18:08s
epoch 59 | loss: 0.21137 | valid_auc: 0.93785 |  0:18:26s
epoch 60 | loss: 0.20967 | valid_auc: 0.93793 |  0:18:45s
epoch 61 | loss: 0.20909 | valid_auc: 0.93736 |  0:19:04s
epoch 62 | loss: 0.20791 | valid_auc: 0.93748 |  0:19:22s

Early stopping occurred at epoch 62 with best_epoch = 42 and best_valid_auc = 0.94162

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

======== Fold 5 ========

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/pytorch_tabnet/abstract_model.py:82: UserWarning: Device used : cpu
  warnings.warn(f"Device used : {self.device}")

epoch 0  | loss: 0.38905 | valid_auc: 0.87773 |  0:00:19s
epoch 1  | loss: 0.31637 | valid_auc: 0.90294 |  0:00:38s
epoch 2  | loss: 0.30915 | valid_auc: 0.90165 |  0:00:57s
epoch 3  | loss: 0.29954 | valid_auc: 0.91467 |  0:01:17s
epoch 4  | loss: 0.28454 | valid_auc: 0.91934 |  0:01:36s
epoch 5  | loss: 0.27706 | valid_auc: 0.92302 |  0:01:56s
epoch 6  | loss: 0.27446 | valid_auc: 0.92351 |  0:02:14s
epoch 7  | loss: 0.27053 | valid_auc: 0.92437 |  0:02:32s
epoch 8  | loss: 0.26812 | valid_auc: 0.92652 |  0:02:51s
epoch 9  | loss: 0.26637 | valid_auc: 0.9272  |  0:03:09s
epoch 10 | loss: 0.26574 | valid_auc: 0.93086 |  0:03:27s
epoch 11 | loss: 0.26164 | valid_auc: 0.9292  |  0:03:46s
epoch 12 | loss: 0.26071 | valid_auc: 0.93105 |  0:04:04s
epoch 13 | loss: 0.26344 | valid_auc: 0.93129 |  0:04:23s
epoch 14 | loss: 0.25836 | valid_auc: 0.9305  |  0:04:42s
epoch 15 | loss: 0.25614 | valid_auc: 0.93315 |  0:05:01s
epoch 16 | loss: 0.25292 | valid_auc: 0.93519 |  0:05:20s
epoch 17 | loss: 0.25056 | valid_auc: 0.93616 |  0:05:39s
epoch 18 | loss: 0.25053 | valid_auc: 0.93446 |  0:05:59s
epoch 19 | loss: 0.24923 | valid_auc: 0.93812 |  0:06:19s
epoch 20 | loss: 0.24797 | valid_auc: 0.9375  |  0:06:39s
epoch 21 | loss: 0.24492 | valid_auc: 0.93947 |  0:06:58s
epoch 22 | loss: 0.24497 | valid_auc: 0.93736 |  0:07:18s
epoch 23 | loss: 0.24467 | valid_auc: 0.93805 |  0:07:37s
epoch 24 | loss: 0.24264 | valid_auc: 0.93683 |  0:07:57s
epoch 25 | loss: 0.24138 | valid_auc: 0.9397  |  0:08:16s
epoch 26 | loss: 0.24047 | valid_auc: 0.939   |  0:08:35s
epoch 27 | loss: 0.23857 | valid_auc: 0.94129 |  0:08:55s
epoch 28 | loss: 0.23743 | valid_auc: 0.93145 |  0:09:14s
epoch 29 | loss: 0.23639 | valid_auc: 0.94114 |  0:09:33s
epoch 30 | loss: 0.23544 | valid_auc: 0.94166 |  0:09:52s
epoch 31 | loss: 0.2344  | valid_auc: 0.93988 |  0:10:12s
epoch 32 | loss: 0.23394 | valid_auc: 0.9415  |  0:10:31s
epoch 33 | loss: 0.23359 | valid_auc: 0.94134 |  0:10:51s
epoch 34 | loss: 0.23336 | valid_auc: 0.94042 |  0:11:10s
epoch 35 | loss: 0.23695 | valid_auc: 0.93807 |  0:11:29s
epoch 36 | loss: 0.23453 | valid_auc: 0.94046 |  0:11:48s
epoch 37 | loss: 0.2323  | valid_auc: 0.94147 |  0:12:07s
epoch 38 | loss: 0.23118 | valid_auc: 0.94066 |  0:12:26s
epoch 39 | loss: 0.22944 | valid_auc: 0.94118 |  0:12:44s
epoch 40 | loss: 0.22745 | valid_auc: 0.94156 |  0:13:03s
epoch 41 | loss: 0.22698 | valid_auc: 0.93984 |  0:13:23s
epoch 42 | loss: 0.22597 | valid_auc: 0.94024 |  0:13:42s
epoch 43 | loss: 0.2248  | valid_auc: 0.94131 |  0:14:01s
epoch 44 | loss: 0.22399 | valid_auc: 0.94142 |  0:14:19s
epoch 45 | loss: 0.22252 | valid_auc: 0.93983 |  0:14:38s
epoch 46 | loss: 0.222   | valid_auc: 0.93933 |  0:14:57s
epoch 47 | loss: 0.22078 | valid_auc: 0.94035 |  0:15:16s
epoch 48 | loss: 0.22017 | valid_auc: 0.94098 |  0:15:35s
epoch 49 | loss: 0.21921 | valid_auc: 0.9394  |  0:15:54s
epoch 50 | loss: 0.21792 | valid_auc: 0.93958 |  0:16:13s

Early stopping occurred at epoch 50 with best_epoch = 30 and best_valid_auc = 0.94166

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/pytorch_tabnet/callbacks.py:172: UserWarning: Best weights from best epoch are automatically used!
  warnings.warn(wrn_msg)

In [48]:
nn_oof_train = np.zeros(len(X_train))
nn_test_preds = np.zeros(len(X_test))

aucs = []

cv = StratifiedKFold(shuffle=True, random_state=42, n_splits=3)

for fold, (train_idx, valid_idx) in enumerate(cv.split(X_train, y_train)):
    print(f"\n======== Fold {fold + 1} ========")

    X_tr, X_val = X_train.iloc[train_idx, :], X_train.iloc[valid_idx, :]
    y_tr, y_val = y_train.iloc[train_idx, 0], y_train.iloc[valid_idx, 0]

    X_tr_tf = column_transformer.fit_transform(X_tr, y_tr).astype(np.float32)
    X_val_tf = column_transformer.transform(X_val).astype(np.float32)
    X_test_tf = column_transformer.transform(X_test).astype(np.float32)

    y_tr = y_tr.values.astype(np.float32)
    y_val = y_val.values.astype(np.float32)

    model = Sequential([
        layers.Input(shape=(X_tr_tf.shape[1],)),
        layers.Dense(512, activation="swish", kernel_regularizer=regularizers.l2(1e-4)),
        layers.BatchNormalization(),
        layers.Dropout(0.30),
        layers.Dense(256, activation="swish", kernel_regularizer=regularizers.l2(1e-4)),
        layers.BatchNormalization(),
        layers.Dropout(0.25),
        layers.Dense(128, activation="swish", kernel_regularizer=regularizers.l2(1e-4)),
        layers.BatchNormalization(),
        layers.Dropout(0.20),
        layers.Dense(1, activation="sigmoid")
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="binary_crossentropy",
        metrics=[tf.keras.metrics.AUC(name="auc")]
    )

    early_stopping = callbacks.EarlyStopping(monitor="val_auc", mode="max", patience=15, restore_best_weights=True)
    reduce_lr = callbacks.ReduceLROnPlateau(monitor="val_auc", mode="max", factor=0.5, patience=5, min_lr=1e-6)

    model.fit(
        X_tr_tf, y_tr,
        validation_data=(X_val_tf, y_val),
        epochs=200,
        batch_size=1024,
        callbacks=[early_stopping, reduce_lr],
        verbose=1
    )
    
    val_preds = model.predict(X_val_tf, verbose=0).ravel()
    nn_oof_train[valid_idx] = val_preds
    
    nn_test_preds += model.predict(X_test_tf, verbose=0).ravel() / cv.get_n_splits()

    auc = roc_auc_score(y_val, val_preds)
    aucs.append(auc)
    print(f"Fold AUC: {auc:.6f}")

print(f"\nMean AUC: {np.mean(aucs):.6f} (+/- {np.std(aucs):.6f})")

======== Fold 1 ========
Epoch 1/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - auc: 0.8563 - loss: 0.4502 - val_auc: 0.9075 - val_loss: 0.3819 - learning_rate: 0.0010
Epoch 2/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.9099 - loss: 0.3456 - val_auc: 0.9186 - val_loss: 0.3367 - learning_rate: 0.0010
Epoch 3/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.9194 - loss: 0.3215 - val_auc: 0.9248 - val_loss: 0.3161 - learning_rate: 0.0010
Epoch 4/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.9231 - loss: 0.3081 - val_auc: 0.9262 - val_loss: 0.3032 - learning_rate: 0.0010
Epoch 5/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.9254 - loss: 0.2982 - val_auc: 0.9288 - val_loss: 0.2940 - learning_rate: 0.0010
Epoch 6/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 11ms/step - auc: 0.9267 - loss: 0.2914 - val_auc: 0.9301 - val_loss: 0.2856 - learning_rate: 0.0010
Epoch 7/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9273 - loss: 0.2869 - val_auc: 0.9313 - val_loss: 0.2815 - learning_rate: 0.0010
Epoch 8/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9283 - loss: 0.2828 - val_auc: 0.9317 - val_loss: 0.2816 - learning_rate: 0.0010
Epoch 9/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9289 - loss: 0.2802 - val_auc: 0.9316 - val_loss: 0.2767 - learning_rate: 0.0010
Epoch 10/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - auc: 0.9292 - loss: 0.2784 - val_auc: 0.9334 - val_loss: 0.2736 - learning_rate: 0.0010
Epoch 11/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9298 - loss: 0.2764 - val_auc: 0.9319 - val_loss: 0.2768 - learning_rate: 0.0010
Epoch 12/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - auc: 0.9301 - loss: 0.2753 - val_auc: 0.9334 - val_loss: 0.2724 - learning_rate: 0.0010
Epoch 13/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9306 - loss: 0.2739 - val_auc: 0.9332 - val_loss: 0.2746 - learning_rate: 0.0010
Epoch 14/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9312 - loss: 0.2728 - val_auc: 0.9328 - val_loss: 0.2729 - learning_rate: 0.0010
Epoch 15/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9315 - loss: 0.2722 - val_auc: 0.9326 - val_loss: 0.2752 - learning_rate: 0.0010
Epoch 16/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9336 - loss: 0.2680 - val_auc: 0.9339 - val_loss: 0.2712 - learning_rate: 5.0000e-04
Epoch 17/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9341 - loss: 0.2663 - val_auc: 0.9358 - val_loss: 0.2669 - learning_rate: 5.0000e-04
Epoch 18/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9341 - loss: 0.2658 - val_auc: 0.9357 - val_loss: 0.2666 - learning_rate: 5.0000e-04
Epoch 19/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9341 - loss: 0.2654 - val_auc: 0.9354 - val_loss: 0.2671 - learning_rate: 5.0000e-04
Epoch 20/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9347 - loss: 0.2642 - val_auc: 0.9354 - val_loss: 0.2659 - learning_rate: 5.0000e-04
Epoch 21/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9348 - loss: 0.2639 - val_auc: 0.9360 - val_loss: 0.2636 - learning_rate: 5.0000e-04
Epoch 22/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9351 - loss: 0.2633 - val_auc: 0.9349 - val_loss: 0.2653 - learning_rate: 5.0000e-04
Epoch 23/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9351 - loss: 0.2632 - val_auc: 0.9366 - val_loss: 0.2626 - learning_rate: 5.0000e-04
Epoch 24/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9351 - loss: 0.2631 - val_auc: 0.9367 - val_loss: 0.2644 - learning_rate: 5.0000e-04
Epoch 25/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9355 - loss: 0.2624 - val_auc: 0.9363 - val_loss: 0.2649 - learning_rate: 5.0000e-04
Epoch 26/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9358 - loss: 0.2621 - val_auc: 0.9359 - val_loss: 0.2649 - learning_rate: 5.0000e-04
Epoch 27/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9356 - loss: 0.2623 - val_auc: 0.9350 - val_loss: 0.2664 - learning_rate: 5.0000e-04
Epoch 28/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9362 - loss: 0.2611 - val_auc: 0.9360 - val_loss: 0.2627 - learning_rate: 5.0000e-04
Epoch 29/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9360 - loss: 0.2615 - val_auc: 0.9357 - val_loss: 0.2641 - learning_rate: 5.0000e-04
Epoch 30/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9378 - loss: 0.2583 - val_auc: 0.9386 - val_loss: 0.2574 - learning_rate: 2.5000e-04
Epoch 31/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9382 - loss: 0.2572 - val_auc: 0.9389 - val_loss: 0.2565 - learning_rate: 2.5000e-04
Epoch 32/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9381 - loss: 0.2571 - val_auc: 0.9394 - val_loss: 0.2564 - learning_rate: 2.5000e-04
Epoch 33/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9385 - loss: 0.2561 - val_auc: 0.9387 - val_loss: 0.2571 - learning_rate: 2.5000e-04
Epoch 34/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9387 - loss: 0.2558 - val_auc: 0.9380 - val_loss: 0.2579 - learning_rate: 2.5000e-04
Epoch 35/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9385 - loss: 0.2557 - val_auc: 0.9388 - val_loss: 0.2566 - learning_rate: 2.5000e-04
Epoch 36/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9387 - loss: 0.2555 - val_auc: 0.9393 - val_loss: 0.2551 - learning_rate: 2.5000e-04
Epoch 37/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9390 - loss: 0.2550 - val_auc: 0.9396 - val_loss: 0.2552 - learning_rate: 2.5000e-04
Epoch 38/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9391 - loss: 0.2547 - val_auc: 0.9392 - val_loss: 0.2549 - learning_rate: 2.5000e-04
Epoch 39/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9389 - loss: 0.2550 - val_auc: 0.9393 - val_loss: 0.2559 - learning_rate: 2.5000e-04
Epoch 40/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9392 - loss: 0.2544 - val_auc: 0.9393 - val_loss: 0.2549 - learning_rate: 2.5000e-04
Epoch 41/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9394 - loss: 0.2539 - val_auc: 0.9396 - val_loss: 0.2538 - learning_rate: 2.5000e-04
Epoch 42/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - auc: 0.9394 - loss: 0.2540 - val_auc: 0.9394 - val_loss: 0.2551 - learning_rate: 2.5000e-04
Epoch 43/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9403 - loss: 0.2522 - val_auc: 0.9406 - val_loss: 0.2525 - learning_rate: 1.2500e-04
Epoch 44/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9406 - loss: 0.2516 - val_auc: 0.9406 - val_loss: 0.2519 - learning_rate: 1.2500e-04
Epoch 45/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9409 - loss: 0.2509 - val_auc: 0.9409 - val_loss: 0.2509 - learning_rate: 1.2500e-04
Epoch 46/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9408 - loss: 0.2509 - val_auc: 0.9407 - val_loss: 0.2517 - learning_rate: 1.2500e-04
Epoch 47/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9410 - loss: 0.2505 - val_auc: 0.9409 - val_loss: 0.2512 - learning_rate: 1.2500e-04
Epoch 48/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9407 - loss: 0.2511 - val_auc: 0.9412 - val_loss: 0.2509 - learning_rate: 1.2500e-04
Epoch 49/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9412 - loss: 0.2499 - val_auc: 0.9409 - val_loss: 0.2510 - learning_rate: 1.2500e-04
Epoch 50/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9410 - loss: 0.2502 - val_auc: 0.9407 - val_loss: 0.2517 - learning_rate: 1.2500e-04
Epoch 51/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9412 - loss: 0.2498 - val_auc: 0.9409 - val_loss: 0.2508 - learning_rate: 1.2500e-04
Epoch 52/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9412 - loss: 0.2498 - val_auc: 0.9415 - val_loss: 0.2497 - learning_rate: 1.2500e-04
Epoch 53/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9414 - loss: 0.2495 - val_auc: 0.9411 - val_loss: 0.2504 - learning_rate: 1.2500e-04
Epoch 54/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9415 - loss: 0.2493 - val_auc: 0.9412 - val_loss: 0.2499 - learning_rate: 1.2500e-04
Epoch 55/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9415 - loss: 0.2492 - val_auc: 0.9417 - val_loss: 0.2491 - learning_rate: 1.2500e-04
Epoch 56/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9416 - loss: 0.2489 - val_auc: 0.9410 - val_loss: 0.2508 - learning_rate: 1.2500e-04
Epoch 57/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9418 - loss: 0.2488 - val_auc: 0.9415 - val_loss: 0.2495 - learning_rate: 1.2500e-04
Epoch 58/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9418 - loss: 0.2486 - val_auc: 0.9410 - val_loss: 0.2506 - learning_rate: 1.2500e-04
Epoch 59/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9416 - loss: 0.2487 - val_auc: 0.9414 - val_loss: 0.2504 - learning_rate: 1.2500e-04
Epoch 60/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9418 - loss: 0.2486 - val_auc: 0.9418 - val_loss: 0.2495 - learning_rate: 1.2500e-04
Epoch 61/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9424 - loss: 0.2474 - val_auc: 0.9417 - val_loss: 0.2491 - learning_rate: 6.2500e-05
Epoch 62/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9426 - loss: 0.2469 - val_auc: 0.9416 - val_loss: 0.2494 - learning_rate: 6.2500e-05
Epoch 63/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9427 - loss: 0.2468 - val_auc: 0.9418 - val_loss: 0.2492 - learning_rate: 6.2500e-05
Epoch 64/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9427 - loss: 0.2468 - val_auc: 0.9423 - val_loss: 0.2481 - learning_rate: 6.2500e-05
Epoch 65/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9427 - loss: 0.2466 - val_auc: 0.9418 - val_loss: 0.2488 - learning_rate: 6.2500e-05
Epoch 66/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9428 - loss: 0.2466 - val_auc: 0.9420 - val_loss: 0.2484 - learning_rate: 6.2500e-05
Epoch 67/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9427 - loss: 0.2467 - val_auc: 0.9423 - val_loss: 0.2479 - learning_rate: 6.2500e-05
Epoch 68/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9429 - loss: 0.2462 - val_auc: 0.9420 - val_loss: 0.2483 - learning_rate: 6.2500e-05
Epoch 69/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9429 - loss: 0.2463 - val_auc: 0.9422 - val_loss: 0.2481 - learning_rate: 6.2500e-05
Epoch 70/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9429 - loss: 0.2461 - val_auc: 0.9423 - val_loss: 0.2478 - learning_rate: 3.1250e-05
Epoch 71/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9432 - loss: 0.2457 - val_auc: 0.9422 - val_loss: 0.2478 - learning_rate: 3.1250e-05
Epoch 72/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9434 - loss: 0.2451 - val_auc: 0.9423 - val_loss: 0.2478 - learning_rate: 3.1250e-05
Epoch 73/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9436 - loss: 0.2449 - val_auc: 0.9424 - val_loss: 0.2475 - learning_rate: 3.1250e-05
Epoch 74/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9438 - loss: 0.2444 - val_auc: 0.9428 - val_loss: 0.2468 - learning_rate: 3.1250e-05
Epoch 75/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9436 - loss: 0.2449 - val_auc: 0.9425 - val_loss: 0.2474 - learning_rate: 3.1250e-05
Epoch 76/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9435 - loss: 0.2448 - val_auc: 0.9426 - val_loss: 0.2468 - learning_rate: 3.1250e-05
Epoch 77/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9434 - loss: 0.2451 - val_auc: 0.9423 - val_loss: 0.2477 - learning_rate: 3.1250e-05
Epoch 78/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9434 - loss: 0.2450 - val_auc: 0.9424 - val_loss: 0.2475 - learning_rate: 3.1250e-05
Epoch 79/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9435 - loss: 0.2448 - val_auc: 0.9426 - val_loss: 0.2470 - learning_rate: 3.1250e-05
Epoch 80/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - auc: 0.9437 - loss: 0.2444 - val_auc: 0.9425 - val_loss: 0.2471 - learning_rate: 1.5625e-05
Epoch 81/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9439 - loss: 0.2440 - val_auc: 0.9426 - val_loss: 0.2470 - learning_rate: 1.5625e-05
Epoch 82/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9438 - loss: 0.2442 - val_auc: 0.9427 - val_loss: 0.2471 - learning_rate: 1.5625e-05
Epoch 83/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9438 - loss: 0.2442 - val_auc: 0.9427 - val_loss: 0.2469 - learning_rate: 1.5625e-05
Epoch 84/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9438 - loss: 0.2442 - val_auc: 0.9427 - val_loss: 0.2469 - learning_rate: 1.5625e-05
Epoch 85/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9438 - loss: 0.2443 - val_auc: 0.9422 - val_loss: 0.2478 - learning_rate: 7.8125e-06
Epoch 86/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9437 - loss: 0.2444 - val_auc: 0.9427 - val_loss: 0.2469 - learning_rate: 7.8125e-06
Epoch 87/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9438 - loss: 0.2441 - val_auc: 0.9424 - val_loss: 0.2474 - learning_rate: 7.8125e-06
Epoch 88/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9439 - loss: 0.2439 - val_auc: 0.9426 - val_loss: 0.2468 - learning_rate: 7.8125e-06
Epoch 89/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9439 - loss: 0.2440 - val_auc: 0.9429 - val_loss: 0.2464 - learning_rate: 7.8125e-06
Epoch 90/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9438 - loss: 0.2442 - val_auc: 0.9426 - val_loss: 0.2469 - learning_rate: 3.9063e-06
Epoch 91/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9440 - loss: 0.2437 - val_auc: 0.9427 - val_loss: 0.2468 - learning_rate: 3.9063e-06
Epoch 92/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9438 - loss: 0.2440 - val_auc: 0.9425 - val_loss: 0.2470 - learning_rate: 3.9063e-06
Epoch 93/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9440 - loss: 0.2439 - val_auc: 0.9426 - val_loss: 0.2469 - learning_rate: 3.9063e-06
Epoch 94/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9441 - loss: 0.2437 - val_auc: 0.9426 - val_loss: 0.2471 - learning_rate: 3.9063e-06
Epoch 95/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9441 - loss: 0.2437 - val_auc: 0.9428 - val_loss: 0.2466 - learning_rate: 1.9531e-06
Epoch 96/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9441 - loss: 0.2436 - val_auc: 0.9429 - val_loss: 0.2465 - learning_rate: 1.9531e-06
Epoch 97/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9441 - loss: 0.2437 - val_auc: 0.9422 - val_loss: 0.2477 - learning_rate: 1.9531e-06
Epoch 98/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9441 - loss: 0.2437 - val_auc: 0.9428 - val_loss: 0.2466 - learning_rate: 1.9531e-06
Epoch 99/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9442 - loss: 0.2434 - val_auc: 0.9427 - val_loss: 0.2467 - learning_rate: 1.9531e-06
Epoch 100/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9439 - loss: 0.2441 - val_auc: 0.9426 - val_loss: 0.2469 - learning_rate: 1.0000e-06
Epoch 101/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9441 - loss: 0.2434 - val_auc: 0.9424 - val_loss: 0.2474 - learning_rate: 1.0000e-06
Epoch 102/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9441 - loss: 0.2436 - val_auc: 0.9424 - val_loss: 0.2472 - learning_rate: 1.0000e-06
Epoch 103/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9441 - loss: 0.2435 - val_auc: 0.9426 - val_loss: 0.2469 - learning_rate: 1.0000e-06
Epoch 104/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9444 - loss: 0.2433 - val_auc: 0.9425 - val_loss: 0.2471 - learning_rate: 1.0000e-06
Fold AUC: 0.943222

======== Fold 2 ========
Epoch 1/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - auc: 0.8573 - loss: 0.4487 - val_auc: 0.9043 - val_loss: 0.3885 - learning_rate: 0.0010
Epoch 2/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9097 - loss: 0.3465 - val_auc: 0.9174 - val_loss: 0.3477 - learning_rate: 0.0010
Epoch 3/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9190 - loss: 0.3229 - val_auc: 0.9220 - val_loss: 0.3193 - learning_rate: 0.0010
Epoch 4/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9226 - loss: 0.3093 - val_auc: 0.9254 - val_loss: 0.3101 - learning_rate: 0.0010
Epoch 5/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9256 - loss: 0.2980 - val_auc: 0.9250 - val_loss: 0.3015 - learning_rate: 0.0010
Epoch 6/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9265 - loss: 0.2919 - val_auc: 0.9269 - val_loss: 0.2928 - learning_rate: 0.0010
Epoch 7/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9276 - loss: 0.2866 - val_auc: 0.9287 - val_loss: 0.2883 - learning_rate: 0.0010
Epoch 8/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9284 - loss: 0.2824 - val_auc: 0.9282 - val_loss: 0.2852 - learning_rate: 0.0010
Epoch 9/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9287 - loss: 0.2802 - val_auc: 0.9304 - val_loss: 0.2810 - learning_rate: 0.0010
Epoch 10/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9293 - loss: 0.2778 - val_auc: 0.9308 - val_loss: 0.2774 - learning_rate: 0.0010
Epoch 11/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9301 - loss: 0.2758 - val_auc: 0.9313 - val_loss: 0.2759 - learning_rate: 0.0010
Epoch 12/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9303 - loss: 0.2749 - val_auc: 0.9314 - val_loss: 0.2764 - learning_rate: 0.0010
Epoch 13/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9305 - loss: 0.2742 - val_auc: 0.9316 - val_loss: 0.2773 - learning_rate: 0.0010
Epoch 14/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9308 - loss: 0.2733 - val_auc: 0.9314 - val_loss: 0.2760 - learning_rate: 0.0010
Epoch 15/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9314 - loss: 0.2722 - val_auc: 0.9330 - val_loss: 0.2744 - learning_rate: 0.0010
Epoch 16/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9314 - loss: 0.2721 - val_auc: 0.9310 - val_loss: 0.2772 - learning_rate: 0.0010
Epoch 17/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9318 - loss: 0.2712 - val_auc: 0.9323 - val_loss: 0.2748 - learning_rate: 0.0010
Epoch 18/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9321 - loss: 0.2709 - val_auc: 0.9338 - val_loss: 0.2703 - learning_rate: 0.0010
Epoch 19/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9323 - loss: 0.2705 - val_auc: 0.9335 - val_loss: 0.2725 - learning_rate: 0.0010
Epoch 20/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9325 - loss: 0.2702 - val_auc: 0.9311 - val_loss: 0.2762 - learning_rate: 0.0010
Epoch 21/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - auc: 0.9327 - loss: 0.2701 - val_auc: 0.9344 - val_loss: 0.2690 - learning_rate: 0.0010
Epoch 22/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 4s 13ms/step - auc: 0.9331 - loss: 0.2692 - val_auc: 0.9340 - val_loss: 0.2704 - learning_rate: 0.0010
Epoch 23/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9333 - loss: 0.2687 - val_auc: 0.9313 - val_loss: 0.2735 - learning_rate: 0.0010
Epoch 24/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9333 - loss: 0.2688 - val_auc: 0.9318 - val_loss: 0.2729 - learning_rate: 0.0010
Epoch 25/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9337 - loss: 0.2684 - val_auc: 0.9344 - val_loss: 0.2708 - learning_rate: 0.0010
Epoch 26/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9334 - loss: 0.2688 - val_auc: 0.9336 - val_loss: 0.2695 - learning_rate: 0.0010
Epoch 27/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9360 - loss: 0.2639 - val_auc: 0.9351 - val_loss: 0.2680 - learning_rate: 5.0000e-04
Epoch 28/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9367 - loss: 0.2619 - val_auc: 0.9363 - val_loss: 0.2638 - learning_rate: 5.0000e-04
Epoch 29/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9364 - loss: 0.2620 - val_auc: 0.9369 - val_loss: 0.2622 - learning_rate: 5.0000e-04
Epoch 30/200
286/286 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - auc: 0.9369 - loss: 0.2608 - val_auc: 0.9369 - val_loss: 0.2624 - learning_rate: 5.0000e-04
Epoch 31/200

In [49]:
X_train_stacking = pd.DataFrame({
    'lgbm_proba': lgbm_proba,
    'catencoder_cat_proba': catencoder_cat_proba,
    'xgb_proba': xgb_proba,
    'hist_proba': hist_proba,
    'lg_proba': lg_proba,
    'voting_proba': voting_proba,
    'cat_proba': cat_proba,
    'tabnet_proba': oof_preds,
    'nn_proba': nn_oof_train
})

X_train_stacking.to_parquet('../data/X_train_4.1_stacking.parquet')

In [50]:
X_test_stacking = pd.DataFrame({
    'lgbm_proba': lgbm.predict_proba(X_test)[:, 1],
    'catencoder_cat_proba': catencoder_cat.predict_proba(X_test)[:, 1],
    'xgb_proba': xgb.predict_proba(X_test)[:, 1],
    'hist_proba': hist.predict_proba(X_test)[:, 1],
    'lg_proba': lg.predict_proba(X_test)[:, 1],
    'voting_proba': voting.predict_proba(X_test)[:, 1],
    'cat_proba': cat.predict_proba(X_test)[:, 1],
    'tabnet_proba': test_preds,
    'nn_proba': nn_test_preds
})

X_test_stacking.to_parquet('../data/X_test_4.1_stacking.parquet')

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

# Machine Learning

In [52]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "C": trial.suggest_float("C", 1e-5, 100, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
        "max_iter": trial.suggest_int("max_iter", 1000, 5000),
        "random_state": trial.suggest_int("random_state", 0, 1000)
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LogisticRegression(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)


study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train_stacking, y_train), n_trials=500, n_jobs=-1)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-14 21:28:55,483] A new study created in memory with name: no-name-d9cc86ca-fc4f-47a0-b0d2-e1560ae76168
[I 2026-05-14 21:29:04,675] Trial 1 finished with value: 0.9024483204954754 and parameters: {'solver': 'saga', 'C': 0.005941338610121171, 'l1_ratio': 0.40209120383159525, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.009705910923974045, 'max_iter': 4609, 'random_state': 6}. Best is trial 1 with value: 0.9024483204954754.
[I 2026-05-14 21:29:10,224] Trial 2 finished with value: 0.9491305441681325 and parameters: {'solver': 'saga', 'C': 6.057123968355615e-05, 'l1_ratio': 0.09860942745730295, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.000973816156801536, 'max_iter': 2339, 'random_state': 736}. Best is trial 2 with value: 0.9491305441681325.
[I 2026-05-14 21:29:12,107] Trial 9 finished with value: 0.9495357436760814 and parameters: {'solver': 'saga', 'C': 18.620516949192602, 'l1_ratio': 0.19156575734480408, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001609801746690628, 'max_iter': 2344, 'random_state': 766}. Best is trial 9 with value: 0.9495357436760814.
[I 2026-05-14 21:29:12,558] Trial 11 finished with value: 0.9497312171090739 and parameters: {'solver': 'saga', 'C': 0.003467597446770093, 'l1_ratio': 0.5236425047264587, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005228901369633789, 'max_iter': 3892, 'random_state': 832}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:14,756] Trial 6 finished with value: 0.9495364296489675 and parameters: {'solver': 'saga', 'C': 2.456564100774462, 'l1_ratio': 0.5994696113901736, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0005198900403847221, 'max_iter': 3773, 'random_state': 281}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:17,590] Trial 4 pruned.
[I 2026-05-14 21:29:18,409] Trial 10 finished with value: 0.9497182883824852 and parameters: {'solver': 'saga', 'C': 0.030244921553385665, 'l1_ratio': 0.727377994287419, 'class_weight': None, 'fit_intercept': True, 'tol': 3.385301448318306e-05, 'max_iter': 3880, 'random_state': 664}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:18,897] Trial 5 pruned.
[I 2026-05-14 21:29:19,162] Trial 8 finished with value: 0.9496890215878022 and parameters: {'solver': 'saga', 'C': 0.2222454074128249, 'l1_ratio': 0.30960355894007285, 'class_weight': None, 'fit_intercept': True, 'tol': 3.368247420494798e-05, 'max_iter': 3072, 'random_state': 746}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:20,052] Trial 13 pruned.
[I 2026-05-14 21:29:22,106] Trial 3 finished with value: 0.9497284064427195 and parameters: {'solver': 'saga', 'C': 0.0213743669619573, 'l1_ratio': 0.6090200228622477, 'class_weight': None, 'fit_intercept': True, 'tol': 4.09419674297566e-06, 'max_iter': 4413, 'random_state': 894}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:22,237] Trial 0 finished with value: 0.9496845447452487 and parameters: {'solver': 'saga', 'C': 49.128877086002056, 'l1_ratio': 0.46998165622729426, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1327119958210147e-05, 'max_iter': 1972, 'random_state': 704}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:23,087] Trial 12 pruned.
[I 2026-05-14 21:29:23,896] Trial 7 finished with value: 0.9497195816826874 and parameters: {'solver': 'saga', 'C': 0.0018360159988335897, 'l1_ratio': 0.6315357271201297, 'class_weight': None, 'fit_intercept': True, 'tol': 2.4011032242649227e-06, 'max_iter': 4591, 'random_state': 999}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:24,705] Trial 16 pruned.
[I 2026-05-14 21:29:26,806] Trial 18 pruned.
[I 2026-05-14 21:29:28,571] Trial 17 pruned.
[I 2026-05-14 21:29:30,509] Trial 20 finished with value: 0.9496890624361491 and parameters: {'solver': 'saga', 'C': 0.17493247818052102, 'l1_ratio': 0.7498386148137017, 'class_weight': None, 'fit_intercept': True, 'tol': 0.003312279403410079, 'max_iter': 4722, 'random_state': 731}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:32,382] Trial 15 finished with value: 0.9496410065537869 and parameters: {'solver': 'saga', 'C': 0.0023410375722613765, 'l1_ratio': 0.29369955468060405, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.104297020166666e-05, 'max_iter': 1080, 'random_state': 730}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:48,540] Trial 21 finished with value: 0.9496017884301784 and parameters: {'solver': 'saga', 'C': 0.0004913193697283802, 'l1_ratio': 0.535840283368233, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1214139458557432e-06, 'max_iter': 4933, 'random_state': 951}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:49,550] Trial 22 finished with value: 0.9495406715807899 and parameters: {'solver': 'saga', 'C': 0.00024832692984229885, 'l1_ratio': 0.5742731455803968, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3402873428174848e-06, 'max_iter': 4858, 'random_state': 993}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:51,164] Trial 23 finished with value: 0.9496826652524216 and parameters: {'solver': 'saga', 'C': 0.0007161717066278848, 'l1_ratio': 0.6148548967472125, 'class_weight': None, 'fit_intercept': True, 'tol': 1.193955323772825e-06, 'max_iter': 4869, 'random_state': 990}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:51,418] Trial 24 finished with value: 0.949686711825159 and parameters: {'solver': 'saga', 'C': 0.0008175310687847791, 'l1_ratio': 0.6075140436799166, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2150606992388515e-06, 'max_iter': 4991, 'random_state': 985}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:52,094] Trial 25 finished with value: 0.9495956847223329 and parameters: {'solver': 'saga', 'C': 0.0004199199446737195, 'l1_ratio': 0.5544143475226678, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3453604934472916e-06, 'max_iter': 3915, 'random_state': 867}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:52,449] Trial 26 finished with value: 0.9495566311364347 and parameters: {'solver': 'saga', 'C': 0.0003874557262643352, 'l1_ratio': 0.5377700589680511, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4954782587897202e-06, 'max_iter': 4243, 'random_state': 898}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:55,022] Trial 28 finished with value: 0.9496993901435669 and parameters: {'solver': 'saga', 'C': 0.001407821424474616, 'l1_ratio': 0.5290082862691432, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3234177877704984e-06, 'max_iter': 4935, 'random_state': 891}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:55,610] Trial 27 finished with value: 0.9496888737037585 and parameters: {'solver': 'saga', 'C': 0.0010289449245575088, 'l1_ratio': 0.548814969517844, 'class_weight': None, 'fit_intercept': True, 'tol': 1.108420444934244e-06, 'max_iter': 4878, 'random_state': 894}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:29:59,954] Trial 29 finished with value: 0.9497082745166031 and parameters: {'solver': 'saga', 'C': 0.0016523553824168838, 'l1_ratio': 0.5567038114258099, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0771182524924048e-06, 'max_iter': 4106, 'random_state': 888}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:30:00,281] Trial 30 finished with value: 0.9496830590732965 and parameters: {'solver': 'saga', 'C': 0.0008769129833525806, 'l1_ratio': 0.5521915051656174, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9328955063983187e-06, 'max_iter': 4198, 'random_state': 885}. Best is trial 11 with value: 0.9497312171090739.
[I 2026-05-14 21:30:06,095] Trial 31 finished with value: 0.9497489113207415 and parameters: {'solver': 'saga', 'C': 0.005728559511168816, 'l1_ratio': 0.5256171952508586, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00022223303071855003, 'max_iter': 4192, 'random_state': 888}. Best is trial 31 with value: 0.9497489113207415.
[I 2026-05-14 21:30:14,842] Trial 32 finished with value: 0.949739683556483 and parameters: {'solver': 'saga', 'C': 0.0037994536216875807, 'l1_ratio': 0.6233645751410937, 'class_weight': None, 'fit_intercept': True, 'tol': 3.696795529914513e-06, 'max_iter': 4276, 'random_state': 882}. Best is trial 31 with value: 0.9497489113207415.
[I 2026-05-14 21:30:15,279] Trial 34 finished with value: 0.9497431576641713 and parameters: {'solver': 'saga', 'C': 0.002264703214985896, 'l1_ratio': 0.823098187462878, 'class_weight': None, 'fit_intercept': True, 'tol': 7.81881846565488e-06, 'max_iter': 4231, 'random_state': 864}. Best is trial 31 with value: 0.9497489113207415.
[I 2026-05-14 21:30:18,571] Trial 33 finished with value: 0.9497539120494043 and parameters: {'solver': 'saga', 'C': 0.0058871925603182764, 'l1_ratio': 0.840060403693684, 'class_weight': None, 'fit_intercept': True, 'tol': 4.175007896582165e-06, 'max_iter': 4262, 'random_state': 870}. Best is trial 33 with value: 0.9497539120494043.
[I 2026-05-14 21:30:19,101] Trial 35 finished with value: 0.949753595962215 and parameters: {'solver': 'saga', 'C': 0.006161261800451793, 'l1_ratio': 0.4717482433939816, 'class_weight': None, 'fit_intercept': True, 'tol': 3.933389710115261e-06, 'max_iter': 4290, 'random_state': 879}. Best is trial 33 with value: 0.9497539120494043.
[I 2026-05-14 21:30:19,483] Trial 36 finished with value: 0.9497542040400445 and parameters: {'solver': 'saga', 'C': 0.006198393046216084, 'l1_ratio': 0.8400028766349391, 'class_weight': None, 'fit_intercept': True, 'tol': 3.4566220778616832e-06, 'max_iter': 4344, 'random_state': 609}. Best is trial 36 with value: 0.9497542040400445.
[I 2026-05-14 21:30:21,023] Trial 37 finished with value: 0.9497626445767722 and parameters: {'solver': 'saga', 'C': 0.010445349641535479, 'l1_ratio': 0.8489253377152188, 'class_weight': None, 'fit_intercept': True, 'tol': 4.580948122453351e-06, 'max_iter': 4403, 'random_state': 549}. Best is trial 37 with value: 0.9497626445767722.
[I 2026-05-14 21:30:22,050] Trial 38 finished with value: 0.949762977333991 and parameters: {'solver': 'saga', 'C': 0.007810713228272986, 'l1_ratio': 0.8331916979104241, 'class_weight': None, 'fit_intercept': True, 'tol': 4.164909121473366e-06, 'max_iter': 4334, 'random_state': 631}. Best is trial 38 with value: 0.949762977333991.
[I 2026-05-14 21:30:24,015] Trial 41 finished with value: 0.949742060135082 and parameters: {'solver': 'saga', 'C': 0.01218568724056231, 'l1_ratio': 0.45028330398513255, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00021942641164981433, 'max_iter': 4379, 'random_state': 585}. Best is trial 38 with value: 0.949762977333991.
[I 2026-05-14 21:30:25,566] Trial 40 finished with value: 0.949754804804601 and parameters: {'solver': 'saga', 'C': 0.008029371079006675, 'l1_ratio': 0.46410231361931453, 'class_weight': None, 'fit_intercept': True, 'tol': 9.513463922298315e-06, 'max_iter': 4489, 'random_state': 579}. Best is trial 38 with value: 0.949762977333991.
[I 2026-05-14 21:30:27,168] Trial 39 finished with value: 0.9497631415210972 and parameters: {'solver': 'saga', 'C': 0.0100638161240242, 'l1_ratio': 0.8253271334499692, 'class_weight': None, 'fit_intercept': True, 'tol': 3.696983508848458e-06, 'max_iter': 4377, 'random_state': 593}. Best is trial 39 with value: 0.9497631415210972.
[I 2026-05-14 21:30:38,169] Trial 42 finished with value: 0.9497512052655759 and parameters: {'solver': 'saga', 'C': 0.009660514530273076, 'l1_ratio': 0.46063710956652826, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5306188065017673e-05, 'max_iter': 4334, 'random_state': 641}. Best is trial 39 with value: 0.9497631415210972.
[I 2026-05-14 21:30:38,910] Trial 43 finished with value: 0.9497542178546026 and parameters: {'solver': 'saga', 'C': 0.007416119029340014, 'l1_ratio': 0.44756882544390286, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4253659328940768e-05, 'max_iter': 3360, 'random_state': 675}. Best is trial 39 with value: 0.9497631415210972.
[I 2026-05-14 21:30:42,367] Trial 44 finished with value: 0.9497647253951091 and parameters: {'solver': 'saga', 'C': 0.00822762861536955, 'l1_ratio': 0.8710983422258746, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2059064491639272e-05, 'max_iter': 3275, 'random_state': 599}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:30:42,576] Trial 45 finished with value: 0.9497624129389777 and parameters: {'solver': 'saga', 'C': 0.01062855066642526, 'l1_ratio': 0.8611460322211307, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3312420164195105e-05, 'max_iter': 3414, 'random_state': 613}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:30:43,849] Trial 46 finished with value: 0.9497498432357989 and parameters: {'solver': 'saga', 'C': 0.009826648900929207, 'l1_ratio': 0.4449521632393471, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4363477824449546e-05, 'max_iter': 3353, 'random_state': 585}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:30:45,722] Trial 47 finished with value: 0.9497618505994583 and parameters: {'solver': 'saga', 'C': 0.01072497014846557, 'l1_ratio': 0.8502019398774355, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3842810018242689e-05, 'max_iter': 4456, 'random_state': 586}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:30:45,994] Trial 48 finished with value: 0.9497589859965077 and parameters: {'solver': 'saga', 'C': 0.011879228034219848, 'l1_ratio': 0.8753993620890258, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4581966428332909e-05, 'max_iter': 4496, 'random_state': 569}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:30:47,935] Trial 49 finished with value: 0.949702161168781 and parameters: {'solver': 'saga', 'C': 0.06244660516851654, 'l1_ratio': 0.8883526653086363, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1350542163646068e-05, 'max_iter': 4588, 'random_state': 540}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:30:57,872] Trial 50 finished with value: 0.9495576882335852 and parameters: {'solver': 'saga', 'C': 0.0647117708984443, 'l1_ratio': 0.9128466719743581, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.416722230274094e-05, 'max_iter': 3395, 'random_state': 538}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:30:59,113] Trial 58 pruned.
[I 2026-05-14 21:31:00,502] Trial 59 pruned.
[I 2026-05-14 21:31:00,757] Trial 51 finished with value: 0.9495542967141063 and parameters: {'solver': 'saga', 'C': 0.080310828629289, 'l1_ratio': 0.9019885241708869, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.3783591393959816e-05, 'max_iter': 4590, 'random_state': 526}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:02,292] Trial 52 finished with value: 0.9497049528926542 and parameters: {'solver': 'saga', 'C': 0.05406132397278071, 'l1_ratio': 0.9077242846327833, 'class_weight': None, 'fit_intercept': True, 'tol': 1.414452368497944e-05, 'max_iter': 4590, 'random_state': 563}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:05,173] Trial 53 finished with value: 0.949702078041657 and parameters: {'solver': 'saga', 'C': 0.06332155540656731, 'l1_ratio': 0.9169236243322367, 'class_weight': None, 'fit_intercept': True, 'tol': 1.318949527304627e-05, 'max_iter': 4526, 'random_state': 535}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:10,272] Trial 55 finished with value: 0.9495589250126966 and parameters: {'solver': 'saga', 'C': 0.062247526479094456, 'l1_ratio': 0.8896787002145745, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.3809652985991872e-05, 'max_iter': 3044, 'random_state': 514}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:12,572] Trial 56 finished with value: 0.9495612351013598 and parameters: {'solver': 'saga', 'C': 0.054109906424138786, 'l1_ratio': 0.9096283984831975, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.7483755690291397e-05, 'max_iter': 3140, 'random_state': 499}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:12,965] Trial 60 pruned.
[I 2026-05-14 21:31:14,446] Trial 61 pruned.
[I 2026-05-14 21:31:17,886] Trial 57 finished with value: 0.9495575655794308 and parameters: {'solver': 'saga', 'C': 0.06508108967577486, 'l1_ratio': 0.9122479766157395, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.6537495481261384e-05, 'max_iter': 2661, 'random_state': 499}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:19,899] Trial 54 finished with value: 0.9495549421932857 and parameters: {'solver': 'saga', 'C': 0.07628116021675911, 'l1_ratio': 0.9096432457648136, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.37434926587677e-06, 'max_iter': 4584, 'random_state': 543}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:26,131] Trial 62 finished with value: 0.9497256054321938 and parameters: {'solver': 'saga', 'C': 0.023928067962578625, 'l1_ratio': 0.673343814619493, 'class_weight': None, 'fit_intercept': True, 'tol': 6.9503336810337465e-06, 'max_iter': 4010, 'random_state': 451}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:26,501] Trial 63 finished with value: 0.9497155846444467 and parameters: {'solver': 'saga', 'C': 0.03380960027542128, 'l1_ratio': 0.7819692989396112, 'class_weight': None, 'fit_intercept': True, 'tol': 5.789264646610377e-06, 'max_iter': 2686, 'random_state': 458}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:27,621] Trial 64 finished with value: 0.9497328881432912 and parameters: {'solver': 'saga', 'C': 0.019446570532330797, 'l1_ratio': 0.6683041581867235, 'class_weight': None, 'fit_intercept': True, 'tol': 6.259814278125772e-06, 'max_iter': 2530, 'random_state': 453}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:30,019] Trial 14 pruned.
[I 2026-05-14 21:31:36,993] Trial 67 finished with value: 0.949732754428607 and parameters: {'solver': 'saga', 'C': 0.019573312548750624, 'l1_ratio': 0.6719594167774315, 'class_weight': None, 'fit_intercept': True, 'tol': 5.927867244071874e-06, 'max_iter': 2626, 'random_state': 459}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:37,464] Trial 66 finished with value: 0.9497338538967789 and parameters: {'solver': 'saga', 'C': 0.020139290731859227, 'l1_ratio': 0.779578456742853, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5826898448397555e-06, 'max_iter': 2500, 'random_state': 472}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:39,476] Trial 68 finished with value: 0.9496865532355576 and parameters: {'solver': 'saga', 'C': 0.48462954299747485, 'l1_ratio': 0.0005788142525529061, 'class_weight': None, 'fit_intercept': True, 'tol': 2.649965954747113e-06, 'max_iter': 2622, 'random_state': 368}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:43,474] Trial 69 finished with value: 0.9496845501137166 and parameters: {'solver': 'saga', 'C': 92.811030430244, 'l1_ratio': 0.6587270654733266, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5321734619277864e-06, 'max_iter': 2592, 'random_state': 345}. Best is trial 44 with value: 0.9497647253951091.
[I 2026-05-14 21:31:45,935] Trial 71 finished with value: 0.9497302109287336 and parameters: {'solver': 'saga', 'C': 0.021120214000359423, 'l1_ratio': 0.6708397060947037, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6289792885732562e-06, 'max_iter': 4019, 'random_state': 380}. Best is trial 44 with value: 0.9497647253951091.

Best trial score:
0.9497659710345386

Best params:
{'solver': 'saga', 'C': 0.008630817906865327, 'l1_ratio': 0.8250356179011763, 'class_weight': None, 'fit_intercept': True, 'tol': 9.210749213449445e-06, 'max_iter': 4329, 'random_state': 736}

In [53]:
stacking_lg = LogisticRegression(**study.best_params).fit(X_train_stacking, y_train.PitNextLap)

# Submission

In [54]:
submission = pd.read_csv('../data/sample_submission.csv')

In [55]:
submission['PitNextLap'] = stacking_lg.predict_proba(X_test_stacking)[:, 1]

In [56]:
submission.to_csv('../data/submission.csv', index=False)