# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from lightgbm import LGBMClassifier

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import StackingClassifier, VotingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

# Loading Dataset

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_logit.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_logit.parquet')

In [4]:
X_train.head()

   lgbm_logit  ...  stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_logit
0    1.402666  ...                                           1.226844
1    0.616425  ...                                           0.371762
2    0.023615  ...                                           0.066618
3   -6.367775  ...                                          -6.799934
4   -0.438053  ...                                          -0.878595

[5 rows x 10 columns]

In [5]:
X_test.head()

   lgbm_logit  ...  stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_logit
0   -5.379032  ...                                          -5.055490
1   -5.795381  ...                                          -5.602505
2   -5.574937  ...                                          -5.656104
3   -1.635113  ...                                          -1.163384
4    1.920299  ...                                           2.146481

[5 rows x 10 columns]

# Machine Learning

In [8]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "alpha": trial.suggest_float("alpha", 1e-4, 100, log=True),
        "solver": trial.suggest_categorical("solver", ["auto", "svd", "cholesky", "lsqr", "sag", "sparse_cg"]),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = RidgeClassifier(**params)
        model.fit(X_train, y_train)

        scores = model.decision_function(X_valid)

        auc = roc_auc_score(y_valid, scores)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-19 17:05:37,698] A new study created in memory with name: no-name-76468938-6fa8-4e5c-b7b5-66563c10a04a
Best trial: 1. Best value: 0.946357:   0%|▍                                                                                                                 | 2/500 [00:04<15:49,  1.91s/it]

[I 2026-05-19 17:05:42,019] Trial 4 finished with value: 0.9455195507186627 and parameters: {'alpha': 0.000651770929950179, 'solver': 'auto', 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007736998869195268}. Best is trial 4 with value: 0.9455195507186627.
[I 2026-05-19 17:05:42,210] Trial 1 finished with value: 0.9463568010465278 and parameters: {'alpha': 38.82245847076902, 'solver': 'svd', 'class_weight': None, 'fit_intercept': False, 'tol': 2.1008787945233375e-05}. Best is trial 1 with value: 0.9463568010465278.

Best trial: 3. Best value: 0.94831:   1%|▋                                                                                                                  | 3/500 [00:04<09:23,  1.13s/it]

[I 2026-05-19 17:05:42,364] Trial 3 finished with value: 0.9483104189392433 and parameters: {'alpha': 0.06914292247230315, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00659654833575302}. Best is trial 3 with value: 0.9483104189392433.
[I 2026-05-19 17:05:42,379] Trial 7 finished with value: 0.948310410643038 and parameters: {'alpha': 0.05636761295240379, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 8.066442615031282e-05}. Best is trial 3 with value: 0.9483104189392433.

Best trial: 0. Best value: 0.949515:   1%|█▏                                                                                                                | 5/500 [00:05<05:06,  1.61it/s]

[I 2026-05-19 17:05:42,898] Trial 0 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.00017045593343705876, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005574382790258872}. Best is trial 0 with value: 0.9495149655028674.
[I 2026-05-19 17:05:42,960] Trial 9 finished with value: 0.949126085525481 and parameters: {'alpha': 11.512952435170808, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0062919855616281484}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   1%|█▌                                                                                                                | 7/500 [00:05<03:51,  2.13it/s]

[I 2026-05-19 17:05:43,437] Trial 2 finished with value: 0.9483114039060816 and parameters: {'alpha': 1.4137956621494618, 'solver': 'svd', 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00033624435573019696}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   2%|██                                                                                                                | 9/500 [00:06<03:01,  2.70it/s]

[I 2026-05-19 17:05:43,877] Trial 6 pruned.
[I 2026-05-19 17:05:44,000] Trial 8 finished with value: 0.9480579065203232 and parameters: {'alpha': 5.620476818823202, 'solver': 'svd', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0035834500818906186}. Best is trial 0 with value: 0.9495149655028674.
[I 2026-05-19 17:05:44,079] Trial 11 pruned.

Best trial: 0. Best value: 0.949515:   2%|██▍                                                                                                              | 11/500 [00:06<02:27,  3.32it/s]

[I 2026-05-19 17:05:44,419] Trial 12 pruned.

Best trial: 0. Best value: 0.949515:   2%|██▋                                                                                                              | 12/500 [00:07<03:28,  2.34it/s]

[I 2026-05-19 17:05:45,279] Trial 13 pruned.

Best trial: 0. Best value: 0.949515:   3%|██▉                                                                                                              | 13/500 [00:09<05:39,  1.43it/s]

[I 2026-05-19 17:05:46,775] Trial 18 pruned.

Best trial: 0. Best value: 0.949515:   3%|███▍                                                                                                             | 15/500 [00:10<04:53,  1.65it/s]

[I 2026-05-19 17:05:47,695] Trial 14 finished with value: 0.9480535014177128 and parameters: {'alpha': 0.16772498657730223, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.644110771926925e-05}. Best is trial 0 with value: 0.9495149655028674.
[I 2026-05-19 17:05:47,855] Trial 21 pruned.

Best trial: 0. Best value: 0.949515:   3%|███▌                                                                                                             | 16/500 [00:10<04:55,  1.64it/s]

[I 2026-05-19 17:05:48,432] Trial 17 pruned.

Best trial: 0. Best value: 0.949515:   4%|████                                                                                                             | 18/500 [00:11<03:29,  2.30it/s]

[I 2026-05-19 17:05:48,777] Trial 19 finished with value: 0.94805346172622 and parameters: {'alpha': 0.10792432294305558, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0004294230877753978}. Best is trial 0 with value: 0.9495149655028674.
[I 2026-05-19 17:05:49,028] Trial 16 finished with value: 0.9480534461098454 and parameters: {'alpha': 0.09378838991572669, 'solver': 'svd', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0006296283001319034}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   4%|████▎                                                                                                            | 19/500 [00:11<03:50,  2.08it/s]

[I 2026-05-19 17:05:49,612] Trial 20 finished with value: 0.948310496369975 and parameters: {'alpha': 0.17496342363978545, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.0690015283449585e-05}. Best is trial 0 with value: 0.9495149655028674.

[I 2026-05-19 17:05:50,930] Trial 22 finished with value: 0.948298692400415 and parameters: {'alpha': 0.0001230066367195926, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0016623295580129086}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   4%|████▋                                                                                                            | 21/500 [00:13<04:30,  1.77it/s]

[I 2026-05-19 17:05:51,128] Trial 26 pruned.

Best trial: 0. Best value: 0.949515:   4%|████▉                                                                                                            | 22/500 [00:14<04:28,  1.78it/s]

[I 2026-05-19 17:05:51,680] Trial 23 finished with value: 0.9491260788562007 and parameters: {'alpha': 0.859422322672472, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0024715835664889823}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   5%|█████▏                                                                                                           | 23/500 [00:14<04:22,  1.82it/s]

[I 2026-05-19 17:05:52,227] Trial 24 finished with value: 0.948298692400415 and parameters: {'alpha': 0.0001155712624445391, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0016226549133657486}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   5%|█████▍                                                                                                           | 24/500 [00:15<04:27,  1.78it/s]

[I 2026-05-19 17:05:52,824] Trial 25 finished with value: 0.948298692400415 and parameters: {'alpha': 0.00010376446611708642, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0016455925433168854}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   5%|█████▋                                                                                                           | 25/500 [00:18<11:55,  1.51s/it]

[I 2026-05-19 17:05:56,548] Trial 15 finished with value: 0.9482814773660386 and parameters: {'alpha': 0.00027980928798476343, 'solver': 'sag', 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.009463705603236101}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   5%|█████▉                                                                                                           | 26/500 [00:20<11:38,  1.47s/it]

[I 2026-05-19 17:05:57,951] Trial 5 pruned.
[I 2026-05-19 17:05:58,005] Trial 36 finished with value: 0.9491260772294854 and parameters: {'alpha': 0.5744320524830396, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003793160109187424}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   6%|██████▎                                                                                                          | 28/500 [00:22<09:29,  1.21s/it]

[I 2026-05-19 17:05:59,699] Trial 31 pruned.

Best trial: 0. Best value: 0.949515:   6%|██████▌                                                                                                          | 29/500 [00:22<08:25,  1.07s/it]

[I 2026-05-19 17:06:00,396] Trial 37 finished with value: 0.9491260783678644 and parameters: {'alpha': 15.48635643969314, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0034736877580567624}. Best is trial 0 with value: 0.9495149655028674.
[I 2026-05-19 17:06:00,401] Trial 38 finished with value: 0.9480715759988533 and parameters: {'alpha': 23.33738899289132, 'solver': 'cholesky', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003194369971729059}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   6%|███████                                                                                                          | 31/500 [00:23<05:52,  1.33it/s]

[I 2026-05-19 17:06:00,994] Trial 39 pruned.

Best trial: 0. Best value: 0.949515:   6%|███████▏                                                                                                         | 32/500 [00:24<06:52,  1.13it/s]

[I 2026-05-19 17:06:02,275] Trial 40 pruned.
[I 2026-05-19 17:06:02,325] Trial 41 pruned.

Best trial: 0. Best value: 0.949515:   7%|███████▋                                                                                                         | 34/500 [00:26<06:19,  1.23it/s]

[I 2026-05-19 17:06:03,733] Trial 42 finished with value: 0.9491260830854993 and parameters: {'alpha': 6.861251151715372, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005608833172111974}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   7%|███████▉                                                                                                         | 35/500 [00:26<06:31,  1.19it/s]

[I 2026-05-19 17:06:04,648] Trial 43 finished with value: 0.9491260819467987 and parameters: {'alpha': 9.794472026378164, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0036282401381040937}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   7%|████████▏                                                                                                        | 36/500 [00:27<05:22,  1.44it/s]

[I 2026-05-19 17:06:04,901] Trial 44 finished with value: 0.949126081458798 and parameters: {'alpha': 6.656113800878488, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005338114925134424}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   7%|████████▎                                                                                                        | 37/500 [00:27<05:28,  1.41it/s]

[I 2026-05-19 17:06:05,569] Trial 27 finished with value: 0.9480459632319127 and parameters: {'alpha': 0.011210759994906864, 'solver': 'sag', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002551239253012959}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   8%|████████▊                                                                                                        | 39/500 [00:28<04:20,  1.77it/s]

[I 2026-05-19 17:06:06,463] Trial 30 finished with value: 0.9480632988578757 and parameters: {'alpha': 0.01091411937582289, 'solver': 'sag', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002113518577752683}. Best is trial 0 with value: 0.9495149655028674.
[I 2026-05-19 17:06:06,570] Trial 45 finished with value: 0.9491260817841412 and parameters: {'alpha': 7.132856135659166, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00507788065795343}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   8%|█████████▎                                                                                                       | 41/500 [00:29<02:47,  2.73it/s]

[I 2026-05-19 17:06:06,818] Trial 29 finished with value: 0.9480327999556348 and parameters: {'alpha': 0.00927495917933034, 'solver': 'sag', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0025346341028729415}. Best is trial 0 with value: 0.9495149655028674.
[I 2026-05-19 17:06:06,885] Trial 28 finished with value: 0.9480437832705695 and parameters: {'alpha': 0.00840080990870584, 'solver': 'sag', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002551165428055195}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   8%|█████████▍                                                                                                       | 42/500 [00:30<03:34,  2.14it/s]

[I 2026-05-19 17:06:07,630] Trial 34 finished with value: 0.9480396683759414 and parameters: {'alpha': 18.209850837723582, 'solver': 'sag', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0031723112937532736}. Best is trial 0 with value: 0.9495149655028674.
[I 2026-05-19 17:06:07,698] Trial 32 finished with value: 0.9480518889451119 and parameters: {'alpha': 0.9798028932879281, 'solver': 'sag', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002662242491217705}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   9%|█████████▉                                                                                                       | 44/500 [00:30<02:23,  3.18it/s]

[I 2026-05-19 17:06:07,885] Trial 46 finished with value: 0.9491260795067819 and parameters: {'alpha': 4.96281252009126, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006777288484264484}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:   9%|██████████▌                                                                                                      | 47/500 [00:31<02:14,  3.37it/s]

[I 2026-05-19 17:06:08,789] Trial 33 finished with value: 0.9480721703140546 and parameters: {'alpha': 13.45088082386709, 'solver': 'sag', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002264132582745525}. Best is trial 0 with value: 0.9495149655028674.
[I 2026-05-19 17:06:08,830] Trial 47 finished with value: 0.9491261182208814 and parameters: {'alpha': 84.91436350154208, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0055919693876756065}. Best is trial 0 with value: 0.9495149655028674.
[I 2026-05-19 17:06:08,883] Trial 35 finished with value: 0.9480465110480069 and parameters: {'alpha': 0.6196309006060895, 'solver': 'sag', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0037059496629430356}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:  10%|██████████▊                                                                                                      | 48/500 [00:32<03:08,  2.39it/s]

[I 2026-05-19 17:06:09,693] Trial 48 finished with value: 0.9491260806454334 and parameters: {'alpha': 6.397966324180668, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004811164590255562}. Best is trial 0 with value: 0.9495149655028674.
[I 2026-05-19 17:06:09,815] Trial 50 finished with value: 0.9486953372394626 and parameters: {'alpha': 68.21742532323107, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0060456572485279485}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:  10%|███████████▎                                                                                                     | 50/500 [00:33<03:17,  2.28it/s]

[I 2026-05-19 17:06:10,586] Trial 51 finished with value: 0.9486953177190276 and parameters: {'alpha': 91.74447214372586, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005996953639772969}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:  10%|███████████▌                                                                                                     | 51/500 [00:33<02:59,  2.51it/s]

[I 2026-05-19 17:06:10,947] Trial 49 finished with value: 0.9491261065089311 and parameters: {'alpha': 68.4364200950187, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005674732666492905}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 0. Best value: 0.949515:  10%|███████████▊                                                                                                     | 52/500 [00:33<02:57,  2.52it/s]

[I 2026-05-19 17:06:11,271] Trial 52 finished with value: 0.9491260796695024 and parameters: {'alpha': 5.8179363900778895, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005650105612086938}. Best is trial 0 with value: 0.9495149655028674.

Best trial: 54. Best value: 0.949515:  11%|███████████▊                                                                                                    | 53/500 [00:34<02:57,  2.52it/s]

[I 2026-05-19 17:06:11,718] Trial 57 pruned.
[I 2026-05-19 17:06:11,722] Trial 54 finished with value: 0.9495151086530521 and parameters: {'alpha': 78.61279755188333, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005489248060430993}. Best is trial 54 with value: 0.9495151086530521.

[I 2026-05-19 17:06:11,933] Trial 55 finished with value: 0.9488727461431218 and parameters: {'alpha': 75.60620959791034, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00587983516517843}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  11%|████████████▊                                                                                                   | 57/500 [00:34<01:49,  4.03it/s]

[I 2026-05-19 17:06:12,233] Trial 53 finished with value: 0.949126115292892 and parameters: {'alpha': 89.00450655311947, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0056792082233718755}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:12,425] Trial 59 pruned.

Best trial: 54. Best value: 0.949515:  12%|█████████████▏                                                                                                  | 59/500 [00:35<01:40,  4.39it/s]

[I 2026-05-19 17:06:12,713] Trial 60 pruned.
[I 2026-05-19 17:06:12,822] Trial 56 finished with value: 0.9495150730280043 and parameters: {'alpha': 53.1206639145013, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005204732729516424}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  12%|█████████████▍                                                                                                  | 60/500 [00:35<02:38,  2.78it/s]

[I 2026-05-19 17:06:13,542] Trial 58 finished with value: 0.9486953156043609 and parameters: {'alpha': 98.90632784807869, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006146912539479269}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  12%|█████████████▋                                                                                                  | 61/500 [00:36<03:26,  2.13it/s]

[I 2026-05-19 17:06:14,296] Trial 61 pruned.

Best trial: 54. Best value: 0.949515:  12%|█████████████▉                                                                                                  | 62/500 [00:37<04:21,  1.68it/s]

[I 2026-05-19 17:06:15,230] Trial 65 pruned.

Best trial: 54. Best value: 0.949515:  13%|██████████████                                                                                                  | 63/500 [00:37<03:48,  1.91it/s]

[I 2026-05-19 17:06:15,569] Trial 66 pruned.

Best trial: 54. Best value: 0.949515:  13%|██████████████▊                                                                                                 | 66/500 [00:38<02:19,  3.11it/s]

[I 2026-05-19 17:06:16,063] Trial 68 pruned.
[I 2026-05-19 17:06:16,131] Trial 69 pruned.
[I 2026-05-19 17:06:16,210] Trial 70 pruned.

Best trial: 54. Best value: 0.949515:  13%|███████████████                                                                                                 | 67/500 [00:38<01:57,  3.68it/s]

[I 2026-05-19 17:06:16,245] Trial 67 pruned.
[I 2026-05-19 17:06:16,415] Trial 64 finished with value: 0.9490494011712618 and parameters: {'alpha': 30.79333158634685, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': True, 'tol': 0.008479920021939246}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  14%|███████████████▍                                                                                                | 69/500 [00:38<01:33,  4.60it/s]

[I 2026-05-19 17:06:16,557] Trial 62 finished with value: 0.9483011448188188 and parameters: {'alpha': 32.664920596720776, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0009902597867986196}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  14%|███████████████▋                                                                                                | 70/500 [00:39<02:17,  3.14it/s]

[I 2026-05-19 17:06:17,307] Trial 71 pruned.

Best trial: 54. Best value: 0.949515:  14%|███████████████▉                                                                                                | 71/500 [00:40<02:42,  2.64it/s]

[I 2026-05-19 17:06:17,869] Trial 72 pruned.
[I 2026-05-19 17:06:17,948] Trial 63 finished with value: 0.9481549670780808 and parameters: {'alpha': 40.082738048112525, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001516478042357971}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  15%|████████████████▎                                                                                               | 73/500 [00:40<01:58,  3.61it/s]

[I 2026-05-19 17:06:18,089] Trial 73 pruned.

Best trial: 54. Best value: 0.949515:  15%|████████████████▌                                                                                               | 74/500 [00:40<01:50,  3.85it/s]

[I 2026-05-19 17:06:18,314] Trial 76 pruned.
[I 2026-05-19 17:06:18,366] Trial 75 pruned.

Best trial: 54. Best value: 0.949515:  15%|█████████████████                                                                                               | 76/500 [00:41<01:40,  4.23it/s]

[I 2026-05-19 17:06:18,666] Trial 74 pruned.

Best trial: 54. Best value: 0.949515:  15%|█████████████████▏                                                                                              | 77/500 [00:42<02:46,  2.54it/s]

[I 2026-05-19 17:06:19,648] Trial 10 finished with value: 0.9480534713247977 and parameters: {'alpha': 0.16406481043862856, 'solver': 'sag', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 8.633165662288768e-06}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  16%|█████████████████▍                                                                                              | 78/500 [00:43<03:56,  1.78it/s]

[I 2026-05-19 17:06:20,774] Trial 77 finished with value: 0.9480728253031255 and parameters: {'alpha': 24.996159788030145, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.390709958181217e-05}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:20,899] Trial 79 finished with value: 0.9480533786019991 and parameters: {'alpha': 0.0008287374801471989, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.859262026887113e-05}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  16%|██████████████████▏                                                                                             | 81/500 [00:43<02:15,  3.10it/s]

[I 2026-05-19 17:06:21,050] Trial 78 finished with value: 0.9480533781139705 and parameters: {'alpha': 0.00041203620648589675, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 4.829182485971011e-05}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:21,283] Trial 80 finished with value: 0.9480533797406998 and parameters: {'alpha': 0.001473774987132607, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.007709263606080666}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  16%|██████████████████▎                                                                                             | 82/500 [00:44<02:58,  2.34it/s]

[I 2026-05-19 17:06:21,854] Trial 81 finished with value: 0.9480560175968098 and parameters: {'alpha': 3.3191295768308238, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 8.414129152339161e-05}. Best is trial 54 with value: 0.9495151086530521.

[I 2026-05-19 17:06:22,321] Trial 83 finished with value: 0.9480555598436228 and parameters: {'alpha': 2.72985048681182, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004642460046201249}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:22,514] Trial 82 finished with value: 0.9480560159701156 and parameters: {'alpha': 3.315600200318991, 'solver': 'auto', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 3.215519028567626e-05}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:22,550] Trial 84 finished with value: 0.9480558868103387 and parameters: {'alpha': 3.161508590727891, 'solver': 'cholesky', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004414912492428251}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  17%|███████████████████▎                                                                                            | 86/500 [00:45<01:36,  4.27it/s]

[I 2026-05-19 17:06:22,725] Trial 85 finished with value: 0.9480559430939766 and parameters: {'alpha': 3.224156614788751, 'solver': 'cholesky', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004366107914327636}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  17%|███████████████████▍                                                                                            | 87/500 [00:45<01:45,  3.92it/s]

[I 2026-05-19 17:06:23,032] Trial 86 finished with value: 0.948055937888544 and parameters: {'alpha': 3.2185061512334974, 'solver': 'cholesky', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 4.017423113678698e-05}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  18%|███████████████████▋                                                                                            | 88/500 [00:45<01:45,  3.91it/s]

[I 2026-05-19 17:06:23,343] Trial 87 finished with value: 0.9480533779513202 and parameters: {'alpha': 0.0005414964330993389, 'solver': 'cholesky', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00429532784868743}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  18%|████████████████████▏                                                                                           | 90/500 [00:47<03:25,  1.99it/s]

[I 2026-05-19 17:06:25,098] Trial 88 finished with value: 0.949126077717521 and parameters: {'alpha': 0.0004204245141979914, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0042665378564423085}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:25,144] Trial 89 finished with value: 0.9480551754541138 and parameters: {'alpha': 2.2413877339868606, 'solver': 'cholesky', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004371642584330524}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  18%|████████████████████▍                                                                                           | 91/500 [00:48<03:44,  1.82it/s]

[I 2026-05-19 17:06:25,856] Trial 90 finished with value: 0.9480558110062383 and parameters: {'alpha': 3.0699371494180774, 'solver': 'cholesky', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004370515495240014}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:26,004] Trial 92 finished with value: 0.9480613778965313 and parameters: {'alpha': 9.953871901069903, 'solver': 'cholesky', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004512962001314165}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  18%|████████████████████▌                                                                                           | 92/500 [00:48<03:12,  2.12it/s]

[I 2026-05-19 17:06:26,138] Trial 91 finished with value: 0.9480554015656866 and parameters: {'alpha': 2.5515563128862095, 'solver': 'cholesky', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004803307763394995}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  19%|█████████████████████                                                                                           | 94/500 [00:49<02:49,  2.39it/s]

[I 2026-05-19 17:06:26,858] Trial 93 finished with value: 0.9480608784994576 and parameters: {'alpha': 9.352394470193547, 'solver': 'cholesky', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0042868370366319465}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  19%|█████████████████████▎                                                                                          | 95/500 [00:49<03:22,  2.00it/s]

[I 2026-05-19 17:06:27,555] Trial 94 finished with value: 0.9480636861827334 and parameters: {'alpha': 12.977440919850434, 'solver': 'cholesky', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004411735471735793}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  19%|█████████████████████▌                                                                                          | 96/500 [00:50<03:33,  1.90it/s]

[I 2026-05-19 17:06:28,154] Trial 95 finished with value: 0.94912608552553 and parameters: {'alpha': 10.06524426661484, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0037352274275202746}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  19%|█████████████████████▋                                                                                          | 97/500 [00:50<03:10,  2.12it/s]

[I 2026-05-19 17:06:28,512] Trial 98 finished with value: 0.9491260791813128 and parameters: {'alpha': 14.193023356719943, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002906809831222109}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  20%|█████████████████████▉                                                                                          | 98/500 [00:51<02:58,  2.25it/s]

[I 2026-05-19 17:06:28,832] Trial 96 finished with value: 0.9491260832481216 and parameters: {'alpha': 12.062301765360228, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004083775820085264}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  20%|██████████████████████▏                                                                                         | 99/500 [00:51<02:41,  2.48it/s]

[I 2026-05-19 17:06:29,122] Trial 99 finished with value: 0.9491260842241089 and parameters: {'alpha': 11.777401882601946, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0028298062873731073}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  20%|██████████████████████▏                                                                                        | 100/500 [00:52<03:35,  1.86it/s]

[I 2026-05-19 17:06:30,049] Trial 97 finished with value: 0.9480630483546767 and parameters: {'alpha': 12.160172983202521, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 2.035886446273246e-06}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  20%|██████████████████████▍                                                                                        | 101/500 [00:53<04:27,  1.49it/s]

[I 2026-05-19 17:06:31,027] Trial 101 finished with value: 0.9491260793439844 and parameters: {'alpha': 14.002750670231881, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0029809841043953564}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  21%|██████████████████████▊                                                                                        | 103/500 [00:53<03:01,  2.19it/s]

[I 2026-05-19 17:06:31,422] Trial 100 finished with value: 0.9491260865015242 and parameters: {'alpha': 10.559643972151093, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002980188550676835}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:31,544] Trial 102 finished with value: 0.949126085850852 and parameters: {'alpha': 10.179907395642099, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0028702330240014625}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  21%|███████████████████████                                                                                        | 104/500 [00:54<02:57,  2.23it/s]

[I 2026-05-19 17:06:32,006] Trial 103 finished with value: 0.9491260848748648 and parameters: {'alpha': 10.01276647989609, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0028313420270124467}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  21%|███████████████████████▌                                                                                       | 106/500 [00:54<02:25,  2.71it/s]

[I 2026-05-19 17:06:32,476] Trial 104 finished with value: 0.9491260832481216 and parameters: {'alpha': 12.074026580250038, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003071026130045451}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:32,639] Trial 105 finished with value: 0.9491260863388595 and parameters: {'alpha': 11.049718652329055, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003024999894510229}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  21%|███████████████████████▊                                                                                       | 107/500 [00:55<02:43,  2.40it/s]

[I 2026-05-19 17:06:33,177] Trial 106 finished with value: 0.9491261071596382 and parameters: {'alpha': 53.86622753427126, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002743360214498322}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  22%|███████████████████████▉                                                                                       | 108/500 [00:56<04:02,  1.61it/s]

[I 2026-05-19 17:06:34,284] Trial 107 finished with value: 0.9491261024423181 and parameters: {'alpha': 51.87838488086335, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003202284307781492}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  22%|████████████████████████▏                                                                                      | 109/500 [00:57<03:36,  1.80it/s]

[I 2026-05-19 17:06:34,591] Trial 108 finished with value: 0.948303107923971 and parameters: {'alpha': 58.69832681023329, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0020445155433772683}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  22%|████████████████████████▍                                                                                      | 110/500 [00:58<05:04,  1.28it/s]

[I 2026-05-19 17:06:35,992] Trial 110 finished with value: 0.9482987185902353 and parameters: {'alpha': 0.2906212145700558, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0018068019124835822}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:36,017] Trial 109 finished with value: 0.9480935863824957 and parameters: {'alpha': 53.327327006086996, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 2.1169754089999562e-06}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  22%|████████████████████████▊                                                                                      | 112/500 [00:58<03:40,  1.76it/s]

[I 2026-05-19 17:06:36,618] Trial 111 finished with value: 0.949126091706348 and parameters: {'alpha': 49.40178332416892, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002081840564934401}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  23%|█████████████████████████                                                                                      | 113/500 [00:59<03:34,  1.81it/s]

[I 2026-05-19 17:06:37,117] Trial 112 finished with value: 0.9483024886382075 and parameters: {'alpha': 50.82777483667403, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0017428575400257667}. Best is trial 54 with value: 0.9495151086530521.

[I 2026-05-19 17:06:38,072] Trial 113 finished with value: 0.9491261063463226 and parameters: {'alpha': 60.18384012252426, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002036856810707505}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  23%|█████████████████████████▌                                                                                     | 115/500 [01:00<03:29,  1.84it/s]

[I 2026-05-19 17:06:38,261] Trial 114 finished with value: 0.9491261037435852 and parameters: {'alpha': 56.479045301403396, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0020043751086605732}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  23%|█████████████████████████▉                                                                                     | 117/500 [01:01<02:54,  2.20it/s]

[I 2026-05-19 17:06:39,015] Trial 116 finished with value: 0.9483027249973233 and parameters: {'alpha': 53.812009797934046, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0018695778193817312}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:39,153] Trial 117 finished with value: 0.9487398104623003 and parameters: {'alpha': 54.30844826579054, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0019551067237260564}. Best is trial 54 with value: 0.9495151086530521.

[I 2026-05-19 17:06:39,253] Trial 115 finished with value: 0.9483026682254054 and parameters: {'alpha': 53.12736922702286, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0018048231526969626}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  24%|██████████████████████████▍                                                                                    | 119/500 [01:01<02:08,  2.97it/s]

[I 2026-05-19 17:06:39,448] Trial 118 finished with value: 0.9491261037437322 and parameters: {'alpha': 51.3351965416341, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0021903564939841883}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  24%|██████████████████████████▋                                                                                    | 120/500 [01:03<03:49,  1.65it/s]

[I 2026-05-19 17:06:40,830] Trial 119 finished with value: 0.9483029145082185 and parameters: {'alpha': 56.34833883815365, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0013677279424389927}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  24%|██████████████████████████▊                                                                                    | 121/500 [01:03<04:10,  1.51it/s]

[I 2026-05-19 17:06:41,588] Trial 120 finished with value: 0.9483025185690735 and parameters: {'alpha': 51.295607748716314, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0014685905664502234}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:41,655] Trial 121 finished with value: 0.9491261079730448 and parameters: {'alpha': 70.84534536025858, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0069526763220338125}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  25%|███████████████████████████▎                                                                                   | 123/500 [01:04<02:57,  2.13it/s]

[I 2026-05-19 17:06:42,077] Trial 122 finished with value: 0.9491261094369975 and parameters: {'alpha': 73.0713932611464, 'solver': 'sparse_cg', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.007395755372473317}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  25%|███████████████████████████▊                                                                                   | 125/500 [01:04<02:10,  2.88it/s]

[I 2026-05-19 17:06:42,338] Trial 128 pruned.
[I 2026-05-19 17:06:42,503] Trial 130 pruned.

Best trial: 54. Best value: 0.949515:  25%|███████████████████████████▉                                                                                   | 126/500 [01:05<02:40,  2.33it/s]

[I 2026-05-19 17:06:43,120] Trial 123 finished with value: 0.9483040161112111 and parameters: {'alpha': 71.65272811887638, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0014383885267786399}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  26%|████████████████████████████▋                                                                                  | 129/500 [01:06<01:38,  3.78it/s]

[I 2026-05-19 17:06:43,570] Trial 127 finished with value: 0.9495151076769112 and parameters: {'alpha': 72.72006822573289, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006437702511487828}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:43,579] Trial 124 finished with value: 0.9482986933764093 and parameters: {'alpha': 0.03575380992915752, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001292463230560101}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:43,712] Trial 131 pruned.

Best trial: 54. Best value: 0.949515:  26%|█████████████████████████████▎                                                                                 | 132/500 [01:06<01:22,  4.46it/s]

[I 2026-05-19 17:06:44,195] Trial 129 finished with value: 0.9495149653401891 and parameters: {'alpha': 0.0455364909972359, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006485212254968899}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:44,261] Trial 132 pruned.
[I 2026-05-19 17:06:44,343] Trial 125 finished with value: 0.9491260705595337 and parameters: {'alpha': 19.812031919375293, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006664032695627795}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  27%|█████████████████████████████▌                                                                                 | 133/500 [01:06<01:19,  4.59it/s]

[I 2026-05-19 17:06:44,528] Trial 126 finished with value: 0.948304142180586 and parameters: {'alpha': 73.54323672338859, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001435937728220132}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 54. Best value: 0.949515:  27%|█████████████████████████████▋                                                                                 | 134/500 [01:08<02:43,  2.24it/s]

[I 2026-05-19 17:06:45,697] Trial 133 finished with value: 0.9495151065381965 and parameters: {'alpha': 74.766050189752, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007068487535379146}. Best is trial 54 with value: 0.9495151086530521.

Best trial: 135. Best value: 0.949515:  27%|█████████████████████████████▋                                                                                | 135/500 [01:08<02:48,  2.17it/s]

[I 2026-05-19 17:06:46,254] Trial 134 finished with value: 0.9495151042608372 and parameters: {'alpha': 70.4682082203967, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006991862594608763}. Best is trial 54 with value: 0.9495151086530521.
[I 2026-05-19 17:06:46,260] Trial 135 finished with value: 0.9495151198773586 and parameters: {'alpha': 82.1507432309152, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006869281314210918}. Best is trial 135 with value: 0.9495151198773586.

Best trial: 135. Best value: 0.949515:  27%|██████████████████████████████▏                                                                               | 137/500 [01:09<02:42,  2.23it/s]

[I 2026-05-19 17:06:47,086] Trial 136 finished with value: 0.9475529176091155 and parameters: {'alpha': 0.03510243237282203, 'solver': 'lsqr', 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.007167859195761728}. Best is trial 135 with value: 0.9495151198773586.

Best trial: 135. Best value: 0.949515:  28%|██████████████████████████████▌                                                                               | 139/500 [01:10<02:45,  2.19it/s]

[I 2026-05-19 17:06:47,525] Trial 137 finished with value: 0.9495149959224125 and parameters: {'alpha': 19.1750991452123, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006981620604344767}. Best is trial 135 with value: 0.9495151198773586.
[I 2026-05-19 17:06:47,657] Trial 138 finished with value: 0.9495149967357633 and parameters: {'alpha': 18.284618607992407, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007019191838948371}. Best is trial 135 with value: 0.9495151198773586.
[I 2026-05-19 17:06:47,737] Trial 139 finished with value: 0.9495149946210756 and parameters: {'alpha': 19.46811783584999, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007023795118010409}. Best is trial 135 with value: 0.9495151198773586.

Best trial: 135. Best value: 0.949515:  28%|███████████████████████████████▏                                                                              | 142/500 [01:10<01:43,  3.47it/s]

[I 2026-05-19 17:06:48,094] Trial 143 finished with value: 0.9486953160923687 and parameters: {'alpha': 96.84834022984757, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007261458820598429}. Best is trial 135 with value: 0.9495151198773586.
[I 2026-05-19 17:06:48,217] Trial 144 finished with value: 0.9486953152790252 and parameters: {'alpha': 98.19685516105473, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007530966060172663}. Best is trial 135 with value: 0.9495151198773586.

Best trial: 141. Best value: 0.949515:  29%|███████████████████████████████▉                                                                              | 145/500 [01:10<01:02,  5.70it/s]

[I 2026-05-19 17:06:48,310] Trial 141 finished with value: 0.9495151546886641 and parameters: {'alpha': 98.85788235242278, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0068156344795750135}. Best is trial 141 with value: 0.9495151546886641.
[I 2026-05-19 17:06:48,329] Trial 142 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.0033464260523151323, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006919363247426869}. Best is trial 141 with value: 0.9495151546886641.
[I 2026-05-19 17:06:48,346] Trial 140 finished with value: 0.9495149962477907 and parameters: {'alpha': 20.58866858334925, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0068160266862499755}. Best is trial 141 with value: 0.9495151546886641.

Best trial: 145. Best value: 0.949515:  29%|████████████████████████████████                                                                              | 146/500 [01:12<02:50,  2.07it/s]

[I 2026-05-19 17:06:49,938] Trial 145 finished with value: 0.949515155339336 and parameters: {'alpha': 98.90699188693296, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00680620171031613}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:49,987] Trial 146 finished with value: 0.9486953165803691 and parameters: {'alpha': 95.54998972196955, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0074776330290620184}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  30%|████████████████████████████████▊                                                                             | 149/500 [01:12<01:52,  3.11it/s]

[I 2026-05-19 17:06:50,365] Trial 147 finished with value: 0.949156215734965 and parameters: {'alpha': 0.004442650297427581, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007167891745279782}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:50,491] Trial 148 finished with value: 0.9486953154417035 and parameters: {'alpha': 97.80532788099754, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007106606248094353}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  30%|█████████████████████████████████                                                                             | 150/500 [01:13<02:28,  2.36it/s]

[I 2026-05-19 17:06:51,280] Trial 149 finished with value: 0.9486953169057122 and parameters: {'alpha': 95.66411515810667, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00744533016923699}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:51,372] Trial 151 finished with value: 0.9486953826243957 and parameters: {'alpha': 21.246962586249094, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007486842551970262}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  30%|█████████████████████████████████▍                                                                            | 152/500 [01:14<02:00,  2.89it/s]

[I 2026-05-19 17:06:51,693] Trial 150 finished with value: 0.9495149939703544 and parameters: {'alpha': 17.0819941951939, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006830149116069287}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  31%|█████████████████████████████████▉                                                                            | 154/500 [01:14<01:54,  3.03it/s]

[I 2026-05-19 17:06:52,234] Trial 152 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.002673629557487467, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006067305827372316}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:52,410] Trial 153 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.0030732461869238076, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005505572662581043}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:52,451] Trial 155 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.0030433157705382747, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005555780345146825}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  31%|██████████████████████████████████▎                                                                           | 156/500 [01:14<01:19,  4.31it/s]

[I 2026-05-19 17:06:52,551] Trial 156 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.005109294747276751, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005612804421881484}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:52,578] Trial 154 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.0021917606730602578, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0057026268306932994}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  32%|██████████████████████████████████▉                                                                           | 159/500 [01:16<01:45,  3.23it/s]

[I 2026-05-19 17:06:53,647] Trial 157 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.004458301546645223, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005439357398484641}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:53,818] Trial 158 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.006710528527448044, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005643292887373737}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  32%|███████████████████████████████████▏                                                                          | 160/500 [01:16<01:50,  3.07it/s]

[I 2026-05-19 17:06:54,253] Trial 159 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.0001552040108368197, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00533201236803043}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:54,270] Trial 160 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.00022306090419197322, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005599556283486456}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  33%|███████████████████████████████████▊                                                                          | 163/500 [01:17<01:54,  2.95it/s]

[I 2026-05-19 17:06:54,908] Trial 163 finished with value: 0.948695406374164 and parameters: {'alpha': 0.0001382732515499465, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00995019068586869}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:55,008] Trial 162 finished with value: 0.9486954062114925 and parameters: {'alpha': 0.006814825689065605, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009973516268446423}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:55,117] Trial 161 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.0002030049890935524, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005667296216303963}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  33%|████████████████████████████████████▎                                                                         | 165/500 [01:18<01:49,  3.06it/s]

[I 2026-05-19 17:06:55,726] Trial 165 finished with value: 0.9486953837631174 and parameters: {'alpha': 20.12143999036645, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009391565198157923}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  33%|████████████████████████████████████▋                                                                         | 167/500 [01:18<01:30,  3.67it/s]

[I 2026-05-19 17:06:56,037] Trial 164 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.003336464234639091, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005263148810486139}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:56,137] Trial 166 finished with value: 0.949514965340196 and parameters: {'alpha': 0.015932910994254822, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005161961374350342}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  34%|████████████████████████████████████▉                                                                         | 168/500 [01:18<01:20,  4.11it/s]

[I 2026-05-19 17:06:56,318] Trial 168 finished with value: 0.9486954062114925 and parameters: {'alpha': 0.01553966813056758, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009796491315196117}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  34%|█████████████████████████████████████▏                                                                        | 169/500 [01:18<01:20,  4.12it/s]

[I 2026-05-19 17:06:56,557] Trial 167 finished with value: 0.948695406374164 and parameters: {'alpha': 0.0002592644624825262, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009976477536783943}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  34%|█████████████████████████████████████▍                                                                        | 170/500 [01:19<02:19,  2.36it/s]

[I 2026-05-19 17:06:57,469] Trial 169 finished with value: 0.948695406374164 and parameters: {'alpha': 0.0002868303725363353, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009194577564295654}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:57,614] Trial 170 finished with value: 0.948695406374164 and parameters: {'alpha': 0.0001901500965816505, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00997249904440279}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  35%|██████████████████████████████████████                                                                        | 173/500 [01:20<01:17,  4.19it/s]

[I 2026-05-19 17:06:57,661] Trial 171 finished with value: 0.948695406374164 and parameters: {'alpha': 0.001212298663658388, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008410908246005626}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:57,795] Trial 172 finished with value: 0.948695406048828 and parameters: {'alpha': 0.08385238376547231, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009848568733924389}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  35%|██████████████████████████████████████▋                                                                       | 176/500 [01:21<01:24,  3.85it/s]

[I 2026-05-19 17:06:58,692] Trial 173 finished with value: 0.948695406374164 and parameters: {'alpha': 0.0014453727017738197, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009973385705944564}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:58,834] Trial 174 finished with value: 0.9486954062114925 and parameters: {'alpha': 0.019904175169746883, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008436395375378797}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:06:58,847] Trial 175 finished with value: 0.948695406374164 and parameters: {'alpha': 0.0018173533523614387, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009099588772834118}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  35%|██████████████████████████████████████▉                                                                       | 177/500 [01:21<01:44,  3.08it/s]

[I 2026-05-19 17:06:59,429] Trial 176 finished with value: 0.9486954062114925 and parameters: {'alpha': 0.016375785034128038, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008496498749118559}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  36%|███████████████████████████████████████▏                                                                      | 178/500 [01:22<02:07,  2.52it/s]

[I 2026-05-19 17:07:00,001] Trial 178 finished with value: 0.9482298848903021 and parameters: {'alpha': 0.0014242503500575242, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003657492485346134}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:00,144] Trial 177 finished with value: 0.9482298848903021 and parameters: {'alpha': 0.002127636883906985, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003650437378621941}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  36%|███████████████████████████████████████▊                                                                      | 181/500 [01:23<01:36,  3.31it/s]

[I 2026-05-19 17:07:00,580] Trial 179 finished with value: 0.9482304560256891 and parameters: {'alpha': 38.847725631333375, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0037005859604364675}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:00,701] Trial 180 finished with value: 0.948230152645888 and parameters: {'alpha': 17.65909692279347, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0037583835607916264}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  36%|████████████████████████████████████████                                                                      | 182/500 [01:23<01:59,  2.67it/s]

[I 2026-05-19 17:07:01,344] Trial 181 finished with value: 0.9482298848903021 and parameters: {'alpha': 0.001573707039623412, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003686245685006781}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  37%|████████████████████████████████████████▋                                                                     | 185/500 [01:24<01:09,  4.56it/s]

[I 2026-05-19 17:07:01,568] Trial 182 finished with value: 0.9482298848903021 and parameters: {'alpha': 0.001343552735010587, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003744390676514546}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:01,576] Trial 183 finished with value: 0.9482298848903021 and parameters: {'alpha': 0.002069728910009375, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00372209282084203}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:01,673] Trial 184 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.0015150556975239823, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006416985226366471}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  37%|████████████████████████████████████████▉                                                                     | 186/500 [01:24<01:22,  3.82it/s]

[I 2026-05-19 17:07:02,102] Trial 186 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.002346086663633716, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0063862048453229014}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  37%|█████████████████████████████████████████▏                                                                    | 187/500 [01:24<01:32,  3.40it/s]

[I 2026-05-19 17:07:02,485] Trial 187 finished with value: 0.9482298848903021 and parameters: {'alpha': 0.0019644596039916917, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003772210232608983}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  38%|█████████████████████████████████████████▎                                                                    | 188/500 [01:25<02:38,  1.97it/s]

[I 2026-05-19 17:07:03,595] Trial 196 pruned.

Best trial: 145. Best value: 0.949515:  38%|█████████████████████████████████████████▌                                                                    | 189/500 [01:26<02:59,  1.73it/s]

[I 2026-05-19 17:07:04,363] Trial 198 pruned.

Best trial: 145. Best value: 0.949515:  38%|█████████████████████████████████████████▊                                                                    | 190/500 [01:29<06:27,  1.25s/it]

[I 2026-05-19 17:07:07,331] Trial 191 pruned.

Best trial: 145. Best value: 0.949515:  38%|██████████████████████████████████████████                                                                    | 191/500 [01:29<04:54,  1.05it/s]

[I 2026-05-19 17:07:07,528] Trial 189 pruned.

[I 2026-05-19 17:07:08,351] Trial 190 pruned.
[I 2026-05-19 17:07:08,378] Trial 185 pruned.
[I 2026-05-19 17:07:08,492] Trial 194 pruned.

Best trial: 145. Best value: 0.949515:  39%|██████████████████████████████████████████▋                                                                   | 194/500 [01:30<02:45,  1.85it/s]

[I 2026-05-19 17:07:08,553] Trial 195 pruned.

Best trial: 145. Best value: 0.949515:  39%|███████████████████████████████████████████                                                                   | 196/500 [01:31<01:58,  2.57it/s]

[I 2026-05-19 17:07:08,850] Trial 192 pruned.

Best trial: 145. Best value: 0.949515:  39%|███████████████████████████████████████████▎                                                                  | 197/500 [01:31<01:50,  2.73it/s]

[I 2026-05-19 17:07:09,120] Trial 193 pruned.
[I 2026-05-19 17:07:09,205] Trial 188 pruned.

Best trial: 145. Best value: 0.949515:  40%|███████████████████████████████████████████▊                                                                  | 199/500 [01:31<01:34,  3.19it/s]

[I 2026-05-19 17:07:09,551] Trial 197 pruned.

Best trial: 145. Best value: 0.949515:  40%|████████████████████████████████████████████                                                                  | 200/500 [01:32<01:28,  3.39it/s]

[I 2026-05-19 17:07:09,770] Trial 201 finished with value: 0.9495150196723421 and parameters: {'alpha': 26.989981570774823, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004713484551915031}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:09,823] Trial 202 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.005036571496340907, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004975032801896775}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  40%|████████████████████████████████████████████▍                                                                 | 202/500 [01:32<01:38,  3.03it/s]

[I 2026-05-19 17:07:10,538] Trial 200 pruned.

Best trial: 145. Best value: 0.949515:  41%|████████████████████████████████████████████▋                                                                 | 203/500 [01:33<01:40,  2.96it/s]

[I 2026-05-19 17:07:10,837] Trial 199 pruned.

Best trial: 145. Best value: 0.949515:  41%|█████████████████████████████████████████████                                                                 | 205/500 [01:34<02:01,  2.43it/s]

[I 2026-05-19 17:07:11,972] Trial 203 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.004485063241413499, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004909532936454838}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:12,091] Trial 204 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.003482179441269447, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004918592039565154}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:12,109] Trial 205 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.004180033059754089, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005032404982978871}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  41%|█████████████████████████████████████████████▌                                                                | 207/500 [01:34<01:24,  3.46it/s]

[I 2026-05-19 17:07:12,294] Trial 206 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.00414114076927526, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004893379384777693}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  42%|█████████████████████████████████████████████▊                                                                | 208/500 [01:35<01:28,  3.31it/s]

[I 2026-05-19 17:07:12,701] Trial 207 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.0038747379486211066, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0049110194125156345}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  42%|█████████████████████████████████████████████▉                                                                | 209/500 [01:35<01:24,  3.45it/s]

[I 2026-05-19 17:07:12,940] Trial 208 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.004249492807544936, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004905690557855069}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  42%|██████████████████████████████████████████████▏                                                               | 210/500 [01:35<01:26,  3.35it/s]

[I 2026-05-19 17:07:13,275] Trial 209 finished with value: 0.9495149655028674 and parameters: {'alpha': 0.003833159190396876, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0051876404877155636}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  43%|██████████████████████████████████████████████▊                                                               | 213/500 [01:36<00:55,  5.15it/s]

[I 2026-05-19 17:07:13,534] Trial 210 finished with value: 0.9495150198350135 and parameters: {'alpha': 26.984251128510998, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005089710462875991}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:13,561] Trial 212 finished with value: 0.9495150110507307 and parameters: {'alpha': 24.04671599957775, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004872292560335883}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:13,709] Trial 211 finished with value: 0.949515019672272 and parameters: {'alpha': 30.425374429417207, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004742865703812419}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  43%|███████████████████████████████████████████████                                                               | 214/500 [01:36<01:23,  3.43it/s]

[I 2026-05-19 17:07:14,287] Trial 213 finished with value: 0.9495150208109937 and parameters: {'alpha': 27.280920910767406, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0048922317774504}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  43%|███████████████████████████████████████████████▎                                                              | 215/500 [01:37<02:00,  2.37it/s]

[I 2026-05-19 17:07:15,109] Trial 216 pruned.
[I 2026-05-19 17:07:15,173] Trial 214 finished with value: 0.949515019672335 and parameters: {'alpha': 26.63826290570228, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005207915482866865}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  44%|████████████████████████████████████████████████▏                                                             | 219/500 [01:38<01:21,  3.46it/s]

[I 2026-05-19 17:07:15,895] Trial 217 finished with value: 0.9486953761175281 and parameters: {'alpha': 27.90391395469223, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007912061911806214}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:15,919] Trial 215 finished with value: 0.9495150193469991 and parameters: {'alpha': 28.313986968423276, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005146035582447851}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:15,963] Trial 218 finished with value: 0.9486953712374036 and parameters: {'alpha': 33.68008023320152, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00804213727249501}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  44%|████████████████████████████████████████████████▍                                                             | 220/500 [01:38<01:21,  3.45it/s]

[I 2026-05-19 17:07:16,278] Trial 219 finished with value: 0.9486953738401338 and parameters: {'alpha': 30.099521859673324, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00790346141676474}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:16,430] Trial 222 pruned.

Best trial: 145. Best value: 0.949515:  44%|████████████████████████████████████████████████▊                                                             | 222/500 [01:38<01:05,  4.27it/s]

[I 2026-05-19 17:07:16,635] Trial 220 finished with value: 0.948695375466842 and parameters: {'alpha': 29.13938306088343, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008247664865432934}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  45%|█████████████████████████████████████████████████▎                                                            | 224/500 [01:39<01:20,  3.44it/s]

[I 2026-05-19 17:07:17,080] Trial 224 finished with value: 0.9486953792082937 and parameters: {'alpha': 24.740870070553612, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007801302783421126}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:17,144] Trial 221 finished with value: 0.9486953779069077 and parameters: {'alpha': 26.25520856071098, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008105377078403468}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:17,238] Trial 225 pruned.

Best trial: 145. Best value: 0.949515:  45%|█████████████████████████████████████████████████▋                                                            | 226/500 [01:39<00:53,  5.10it/s]

[I 2026-05-19 17:07:17,338] Trial 223 finished with value: 0.9486953808350158 and parameters: {'alpha': 22.472368921212325, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007780716997553339}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  46%|██████████████████████████████████████████████████▏                                                           | 228/500 [01:41<01:43,  2.64it/s]

[I 2026-05-19 17:07:18,895] Trial 226 finished with value: 0.9486953796963153 and parameters: {'alpha': 23.256657149160176, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007844955334079562}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:19,067] Trial 227 finished with value: 0.9486953798589937 and parameters: {'alpha': 22.783556281010814, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008194844464743412}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  46%|██████████████████████████████████████████████████▌                                                           | 230/500 [01:42<01:35,  2.82it/s]

[I 2026-05-19 17:07:19,725] Trial 230 finished with value: 0.9486953796963153 and parameters: {'alpha': 23.278984103924145, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007930191465301606}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:19,801] Trial 228 finished with value: 0.9486953853898182 and parameters: {'alpha': 17.78249344911691, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008135672059695127}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  46%|██████████████████████████████████████████████████▊                                                           | 231/500 [01:42<01:24,  3.17it/s]

[I 2026-05-19 17:07:20,016] Trial 229 finished with value: 0.9486953860404835 and parameters: {'alpha': 16.716078688562305, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007915490312252763}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  46%|███████████████████████████████████████████████████                                                           | 232/500 [01:42<01:24,  3.19it/s]

[I 2026-05-19 17:07:20,233] Trial 231 finished with value: 0.9486953865284979 and parameters: {'alpha': 16.359398869284558, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00753112653178891}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  47%|███████████████████████████████████████████████████▎                                                          | 233/500 [01:43<01:33,  2.85it/s]

[I 2026-05-19 17:07:20,771] Trial 232 finished with value: 0.9486953866911694 and parameters: {'alpha': 16.45274492610148, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007675735097094005}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  47%|███████████████████████████████████████████████████▍                                                          | 234/500 [01:43<01:32,  2.87it/s]

[I 2026-05-19 17:07:21,108] Trial 234 finished with value: 0.949514987788816 and parameters: {'alpha': 15.26081585831691, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0058890732859617715}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:21,127] Trial 233 finished with value: 0.9482302011214749 and parameters: {'alpha': 21.051920410453874, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004479786761187349}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  47%|████████████████████████████████████████████████████▏                                                         | 237/500 [01:43<01:18,  3.33it/s]

[I 2026-05-19 17:07:21,597] Trial 239 pruned.
[I 2026-05-19 17:07:21,630] Trial 237 finished with value: 0.9495149871381299 and parameters: {'alpha': 15.150106491344966, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006096466034267212}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:21,679] Trial 235 finished with value: 0.9482301367041494 and parameters: {'alpha': 16.377709101303537, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004429602543773174}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  48%|████████████████████████████████████████████████████▌                                                         | 239/500 [01:44<01:02,  4.17it/s]

[I 2026-05-19 17:07:22,113] Trial 236 finished with value: 0.9482301367041565 and parameters: {'alpha': 16.39515522449094, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0044393855568670825}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  48%|█████████████████████████████████████████████████████                                                         | 241/500 [01:45<01:21,  3.17it/s]

[I 2026-05-19 17:07:23,048] Trial 241 pruned.
[I 2026-05-19 17:07:23,131] Trial 243 pruned.

Best trial: 145. Best value: 0.949515:  48%|█████████████████████████████████████████████████████▏                                                        | 242/500 [01:45<01:26,  2.97it/s]

[I 2026-05-19 17:07:23,565] Trial 244 pruned.
[I 2026-05-19 17:07:23,579] Trial 238 finished with value: 0.9482301131169126 and parameters: {'alpha': 15.081128765017016, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004421542163303239}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  49%|█████████████████████████████████████████████████████▉                                                        | 245/500 [01:46<00:58,  4.39it/s]

[I 2026-05-19 17:07:23,864] Trial 240 finished with value: 0.948230143211003 and parameters: {'alpha': 16.981564467394165, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004489986010184864}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:23,935] Trial 245 pruned.

Best trial: 145. Best value: 0.949515:  49%|██████████████████████████████████████████████████████                                                        | 246/500 [01:46<01:25,  2.97it/s]

[I 2026-05-19 17:07:24,683] Trial 242 finished with value: 0.9495150494408096 and parameters: {'alpha': 40.845470451772165, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005824132669686674}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  49%|██████████████████████████████████████████████████████▎                                                       | 247/500 [01:47<01:38,  2.57it/s]

[I 2026-05-19 17:07:25,176] Trial 246 finished with value: 0.9495150522062252 and parameters: {'alpha': 42.80606356036136, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005828533702809155}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  50%|██████████████████████████████████████████████████████▌                                                       | 248/500 [01:48<02:17,  1.83it/s]

[I 2026-05-19 17:07:26,158] Trial 249 finished with value: 0.9495150570863636 and parameters: {'alpha': 45.980649953937366, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005841968723490854}. Best is trial 145 with value: 0.949515155339336.

[I 2026-05-19 17:07:26,477] Trial 247 finished with value: 0.9482304981572899 and parameters: {'alpha': 41.95948678737825, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004307239049368051}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:26,660] Trial 250 finished with value: 0.9495150473260449 and parameters: {'alpha': 39.87860781039294, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00585871430190876}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  50%|███████████████████████████████████████████████████████                                                       | 250/500 [01:49<01:36,  2.58it/s]

[I 2026-05-19 17:07:26,676] Trial 248 finished with value: 0.9482304521216566 and parameters: {'alpha': 38.536335390900454, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0044408696149229356}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  51%|███████████████████████████████████████████████████████▋                                                      | 253/500 [01:50<01:35,  2.59it/s]

[I 2026-05-19 17:07:27,723] Trial 251 finished with value: 0.9495150387045873 and parameters: {'alpha': 37.32518937244348, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005990854774101553}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:27,881] Trial 253 finished with value: 0.949515101332673 and parameters: {'alpha': 63.58455025098784, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0059677816527624475}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  51%|████████████████████████████████████████████████████████                                                      | 255/500 [01:50<01:13,  3.32it/s]

[I 2026-05-19 17:07:28,134] Trial 254 finished with value: 0.9495151008447353 and parameters: {'alpha': 64.81883960270144, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006144104937776674}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:28,285] Trial 252 finished with value: 0.9495151057248599 and parameters: {'alpha': 66.61581972068751, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006309226848190192}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  51%|████████████████████████████████████████████████████████▎                                                     | 256/500 [01:50<01:07,  3.60it/s]

[I 2026-05-19 17:07:28,511] Trial 256 pruned.
[I 2026-05-19 17:07:28,544] Trial 255 finished with value: 0.9495149664788896 and parameters: {'alpha': 0.29971428995581667, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005979160840952339}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  52%|████████████████████████████████████████████████████████▉                                                     | 259/500 [01:51<01:13,  3.30it/s]

[I 2026-05-19 17:07:29,373] Trial 257 finished with value: 0.9495151057248737 and parameters: {'alpha': 73.74509562169264, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0060370875094869405}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:29,534] Trial 258 finished with value: 0.9495151040982005 and parameters: {'alpha': 65.53329015977447, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0055796097842499195}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  52%|█████████████████████████████████████████████████████████▏                                                    | 260/500 [01:52<01:41,  2.37it/s]

[I 2026-05-19 17:07:30,334] Trial 259 finished with value: 0.949515104260858 and parameters: {'alpha': 65.43141523720405, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005830528521030963}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  52%|█████████████████████████████████████████████████████████▋                                                    | 262/500 [01:53<01:39,  2.39it/s]

[I 2026-05-19 17:07:31,121] Trial 261 finished with value: 0.9495150967778356 and parameters: {'alpha': 62.7450981964309, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005721076623840558}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:31,227] Trial 262 finished with value: 0.949515095964499 and parameters: {'alpha': 62.60168025329119, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005502840381451653}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  53%|█████████████████████████████████████████████████████████▊                                                    | 263/500 [01:54<01:37,  2.44it/s]

[I 2026-05-19 17:07:31,648] Trial 260 finished with value: 0.9495150964525136 and parameters: {'alpha': 62.61629591292505, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005673172113288741}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  53%|██████████████████████████████████████████████████████████                                                    | 264/500 [01:54<01:21,  2.89it/s]

[I 2026-05-19 17:07:31,887] Trial 263 pruned.

Best trial: 145. Best value: 0.949515:  53%|██████████████████████████████████████████████████████████▎                                                   | 265/500 [01:54<01:39,  2.37it/s]

[I 2026-05-19 17:07:32,484] Trial 264 finished with value: 0.9495150974285286 and parameters: {'alpha': 62.89566858363602, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005589672633733085}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  53%|██████████████████████████████████████████████████████████▋                                                   | 267/500 [01:55<01:27,  2.65it/s]

[I 2026-05-19 17:07:33,121] Trial 266 finished with value: 0.9495151029594651 and parameters: {'alpha': 70.2964343297209, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005378326625916331}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:33,135] Trial 265 finished with value: 0.949515101007407 and parameters: {'alpha': 64.77664386050827, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005238644448647231}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  54%|██████████████████████████████████████████████████████████▉                                                   | 268/500 [01:55<01:13,  3.17it/s]

[I 2026-05-19 17:07:33,274] Trial 268 finished with value: 0.9495151013327499 and parameters: {'alpha': 64.73685820192507, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005221253871102346}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:33,362] Trial 267 finished with value: 0.9495151053995239 and parameters: {'alpha': 66.49751243353525, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005624782287584315}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  54%|███████████████████████████████████████████████████████████▍                                                  | 270/500 [01:56<01:13,  3.12it/s]

[I 2026-05-19 17:07:34,070] Trial 269 finished with value: 0.9495151049115093 and parameters: {'alpha': 66.7783673305648, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004978329774937593}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  54%|███████████████████████████████████████████████████████████▌                                                  | 271/500 [01:56<01:11,  3.21it/s]

[I 2026-05-19 17:07:34,316] Trial 270 finished with value: 0.9495150979165432 and parameters: {'alpha': 62.94506046637983, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005534732686954026}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  55%|████████████████████████████████████████████████████████████                                                  | 273/500 [01:57<01:25,  2.65it/s]

[I 2026-05-19 17:07:35,198] Trial 276 pruned.
[I 2026-05-19 17:07:35,273] Trial 271 finished with value: 0.949515102634108 and parameters: {'alpha': 64.34006790464487, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005360078666142441}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  55%|████████████████████████████████████████████████████████████▋                                                 | 276/500 [01:58<01:08,  3.26it/s]

[I 2026-05-19 17:07:36,102] Trial 280 pruned.
[I 2026-05-19 17:07:36,142] Trial 277 pruned.
[I 2026-05-19 17:07:36,152] Trial 273 finished with value: 0.9495151042608512 and parameters: {'alpha': 65.44592807870862, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00584218247987428}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  56%|█████████████████████████████████████████████████████████████▍                                                | 279/500 [01:58<00:40,  5.46it/s]

[I 2026-05-19 17:07:36,155] Trial 272 finished with value: 0.9495151021461075 and parameters: {'alpha': 64.98284726290308, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005602107339983335}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:36,360] Trial 279 pruned.
[I 2026-05-19 17:07:36,513] Trial 274 finished with value: 0.9495151044235227 and parameters: {'alpha': 65.72191888560873, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005519628238110611}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  56%|█████████████████████████████████████████████████████████████▌                                                | 280/500 [01:59<00:48,  4.54it/s]

[I 2026-05-19 17:07:36,931] Trial 282 pruned.

Best trial: 145. Best value: 0.949515:  56%|█████████████████████████████████████████████████████████████▊                                                | 281/500 [01:59<00:49,  4.44it/s]

[I 2026-05-19 17:07:37,126] Trial 275 finished with value: 0.949515105724811 and parameters: {'alpha': 68.00359161718636, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005632820552782395}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  56%|██████████████████████████████████████████████████████████████                                                | 282/500 [02:01<02:04,  1.76it/s]

[I 2026-05-19 17:07:38,743] Trial 278 finished with value: 0.9495151058874614 and parameters: {'alpha': 67.78161008215564, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00584778608858979}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  57%|██████████████████████████████████████████████████████████████▎                                               | 283/500 [02:01<01:51,  1.94it/s]

[I 2026-05-19 17:07:38,997] Trial 281 finished with value: 0.9482309451753389 and parameters: {'alpha': 72.1020407182726, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003230769711373505}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  57%|██████████████████████████████████████████████████████████████▍                                               | 284/500 [02:02<02:05,  1.72it/s]

[I 2026-05-19 17:07:39,841] Trial 283 finished with value: 0.9482310531883854 and parameters: {'alpha': 80.50033396727534, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003464110269553787}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  57%|██████████████████████████████████████████████████████████████▋                                               | 285/500 [02:02<01:58,  1.82it/s]

[I 2026-05-19 17:07:40,296] Trial 284 finished with value: 0.9482310478202812 and parameters: {'alpha': 79.9008658988349, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003438600919687779}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  57%|███████████████████████████████████████████████████████████████▏                                              | 287/500 [02:03<01:56,  1.83it/s]

[I 2026-05-19 17:07:40,819] Trial 287 finished with value: 0.9482313430666955 and parameters: {'alpha': 98.90389905365853, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0038612323075781357}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:40,836] Trial 285 finished with value: 0.9482313433920107 and parameters: {'alpha': 98.80051375975147, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0032777474580354504}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:40,958] Trial 288 finished with value: 0.9482313303783384 and parameters: {'alpha': 98.12378562133189, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0037150052873353317}. Best is trial 145 with value: 0.949515155339336.

[I 2026-05-19 17:07:41,065] Trial 289 finished with value: 0.9482312282213476 and parameters: {'alpha': 91.76421936910937, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0037024151784499984}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:41,183] Trial 290 finished with value: 0.9482312139064781 and parameters: {'alpha': 90.61647959674256, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0038655503289136933}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  58%|████████████████████████████████████████████████████████████████                                              | 291/500 [02:03<00:45,  4.59it/s]

[I 2026-05-19 17:07:41,274] Trial 291 finished with value: 0.9482313430666955 and parameters: {'alpha': 98.90375368015783, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0037768922973272245}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:41,289] Trial 286 finished with value: 0.9482312903615024 and parameters: {'alpha': 95.7777920139451, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0032646361892024345}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  59%|████████████████████████████████████████████████████████████████▍                                             | 293/500 [02:04<00:58,  3.55it/s]

[I 2026-05-19 17:07:42,060] Trial 292 finished with value: 0.9482312836920125 and parameters: {'alpha': 95.37261965511054, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004026716422655341}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  59%|████████████████████████████████████████████████████████████████▋                                             | 294/500 [02:05<01:35,  2.16it/s]

[I 2026-05-19 17:07:43,157] Trial 294 finished with value: 0.9482312350535581 and parameters: {'alpha': 92.41161961114358, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0035901129215241455}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:43,199] Trial 293 finished with value: 0.9482312862947566 and parameters: {'alpha': 95.51065672555758, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003844214132240915}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  59%|█████████████████████████████████████████████████████████████████                                             | 296/500 [02:05<01:07,  3.03it/s]

[I 2026-05-19 17:07:43,422] Trial 296 pruned.

Best trial: 145. Best value: 0.949515:  60%|█████████████████████████████████████████████████████████████████▌                                            | 298/500 [02:06<01:12,  2.79it/s]

[I 2026-05-19 17:07:44,161] Trial 304 pruned.
[I 2026-05-19 17:07:44,299] Trial 295 finished with value: 0.9482311771430096 and parameters: {'alpha': 88.61201928369077, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003913876232398358}. Best is trial 145 with value: 0.949515155339336.

[I 2026-05-19 17:07:44,699] Trial 297 finished with value: 0.9495151517606256 and parameters: {'alpha': 96.79521488131064, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007032494877129416}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  60%|██████████████████████████████████████████████████████████████████▏                                           | 301/500 [02:07<01:05,  3.03it/s]

[I 2026-05-19 17:07:44,896] Trial 299 finished with value: 0.949515085878935 and parameters: {'alpha': 58.3890484625136, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00674135301475961}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:44,983] Trial 300 finished with value: 0.9486953463489346 and parameters: {'alpha': 55.156407031871325, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00760282110820648}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:45,150] Trial 303 finished with value: 0.9486953479756428 and parameters: {'alpha': 54.601248552938024, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007285508165728073}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  61%|██████████████████████████████████████████████████████████████████▉                                           | 304/500 [02:07<00:34,  5.76it/s]

[I 2026-05-19 17:07:45,190] Trial 298 finished with value: 0.9482306652197462 and parameters: {'alpha': 52.62909971655316, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004286161526208389}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:45,230] Trial 302 finished with value: 0.9495150801854809 and parameters: {'alpha': 54.67894518570568, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006987237931473566}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:45,357] Trial 306 pruned.

Best trial: 145. Best value: 0.949515:  61%|███████████████████████████████████████████████████████████████████▌                                          | 307/500 [02:07<00:27,  7.07it/s]

[I 2026-05-19 17:07:45,408] Trial 301 finished with value: 0.9495150717266672 and parameters: {'alpha': 52.6981950144853, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007055225414207077}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:45,620] Trial 307 pruned.

Best trial: 145. Best value: 0.949515:  62%|███████████████████████████████████████████████████████████████████▊                                          | 308/500 [02:09<01:38,  1.95it/s]

[I 2026-05-19 17:07:47,307] Trial 305 finished with value: 0.949515068798573 and parameters: {'alpha': 51.891922082040324, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00704849851829122}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  62%|████████████████████████████████████████████████████████████████████▏                                         | 310/500 [02:10<01:38,  1.93it/s]

[I 2026-05-19 17:07:48,493] Trial 309 finished with value: 0.9495150717266881 and parameters: {'alpha': 52.549994041184824, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006749127994219084}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:48,637] Trial 308 finished with value: 0.9495150674972356 and parameters: {'alpha': 51.0532921342233, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006934960843300163}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  62%|████████████████████████████████████████████████████████████████████▋                                         | 312/500 [02:11<01:04,  2.90it/s]

[I 2026-05-19 17:07:48,750] Trial 310 finished with value: 0.9495150608277386 and parameters: {'alpha': 48.83495640518356, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007042830941939759}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:48,847] Trial 312 finished with value: 0.9495150687985798 and parameters: {'alpha': 51.789102049187576, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007034638785206373}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  63%|█████████████████████████████████████████████████████████████████████▎                                        | 315/500 [02:11<00:43,  4.21it/s]

[I 2026-05-19 17:07:49,198] Trial 315 finished with value: 0.9486953339860953 and parameters: {'alpha': 70.88793974843867, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008686773745967744}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:49,214] Trial 311 finished with value: 0.9495150665212065 and parameters: {'alpha': 50.674473988320344, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006878750777949594}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:49,335] Trial 314 pruned.

Best trial: 145. Best value: 0.949515:  64%|█████████████████████████████████████████████████████████████████████▉                                        | 318/500 [02:11<00:29,  6.20it/s]

[I 2026-05-19 17:07:49,419] Trial 316 pruned.
[I 2026-05-19 17:07:49,484] Trial 317 finished with value: 0.9486953338234239 and parameters: {'alpha': 70.64834235692963, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009094075754094643}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:49,499] Trial 318 finished with value: 0.9486953333354023 and parameters: {'alpha': 72.98573902899933, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00869678559392964}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  64%|█████████████████████████████████████████████████████████████████████▉                                        | 318/500 [02:12<00:29,  6.20it/s]

[I 2026-05-19 17:07:49,659] Trial 313 pruned.

Best trial: 145. Best value: 0.949515:  64%|██████████████████████████████████████████████████████████████████████▍                                       | 320/500 [02:13<01:22,  2.17it/s]

[I 2026-05-19 17:07:51,609] Trial 319 finished with value: 0.9495151084903106 and parameters: {'alpha': 75.81466501064456, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0048332048829259405}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  64%|██████████████████████████████████████████████████████████████████████▊                                       | 322/500 [02:15<01:25,  2.09it/s]

[I 2026-05-19 17:07:52,693] Trial 322 finished with value: 0.9486953330100661 and parameters: {'alpha': 72.65346080455727, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00895778306831094}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:52,808] Trial 321 pruned.

[I 2026-05-19 17:07:53,037] Trial 320 pruned.
[I 2026-05-19 17:07:53,182] Trial 323 finished with value: 0.9495151057248808 and parameters: {'alpha': 73.81334335117104, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0049216507098968874}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  65%|███████████████████████████████████████████████████████████████████████▌                                      | 325/500 [02:15<00:51,  3.40it/s]

[I 2026-05-19 17:07:53,250] Trial 324 finished with value: 0.9490494083288505 and parameters: {'alpha': 69.72125105834337, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.0050408853691032195}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  65%|███████████████████████████████████████████████████████████████████████▉                                      | 327/500 [02:16<00:43,  3.96it/s]

[I 2026-05-19 17:07:53,591] Trial 325 finished with value: 0.9490494088168999 and parameters: {'alpha': 73.03962467085678, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.0047717910782479256}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:53,716] Trial 328 finished with value: 0.949049409467586 and parameters: {'alpha': 74.01581415353293, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.004496748645158676}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  66%|████████████████████████████████████████████████████████████████████████▌                                     | 330/500 [02:16<00:32,  5.25it/s]

[I 2026-05-19 17:07:54,024] Trial 326 finished with value: 0.9495151068635884 and parameters: {'alpha': 74.15382778571723, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0049600424724487785}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:54,048] Trial 330 finished with value: 0.949049408491557 and parameters: {'alpha': 72.9329221333515, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.005262288069272042}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:54,089] Trial 327 finished with value: 0.9490494089795645 and parameters: {'alpha': 72.46249566753639, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.0048073063736237915}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  66%|████████████████████████████████████████████████████████████████████████▊                                     | 331/500 [02:16<00:37,  4.53it/s]

[I 2026-05-19 17:07:54,505] Trial 329 finished with value: 0.9490494089795645 and parameters: {'alpha': 75.93760125343628, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.004987612811071399}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  66%|█████████████████████████████████████████████████████████████████████████                                     | 332/500 [02:18<01:33,  1.79it/s]

[I 2026-05-19 17:07:56,103] Trial 331 finished with value: 0.9495151102797672 and parameters: {'alpha': 79.61754109217735, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005029374843324657}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  67%|█████████████████████████████████████████████████████████████████████████▎                                    | 333/500 [02:18<01:30,  1.84it/s]

[I 2026-05-19 17:07:56,595] Trial 332 finished with value: 0.9490494099556006 and parameters: {'alpha': 76.41711810623738, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.004821466111967017}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  67%|█████████████████████████████████████████████████████████████████████████▍                                    | 334/500 [02:19<01:14,  2.23it/s]

[I 2026-05-19 17:07:56,813] Trial 333 finished with value: 0.9490494099555937 and parameters: {'alpha': 76.34503079963841, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.004955017402426129}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  67%|█████████████████████████████████████████████████████████████████████████▉                                    | 336/500 [02:19<01:04,  2.53it/s]

[I 2026-05-19 17:07:57,454] Trial 334 finished with value: 0.9490494110942873 and parameters: {'alpha': 77.66411037516835, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.005040428656632369}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:57,536] Trial 336 finished with value: 0.9491819474675876 and parameters: {'alpha': 38.775852796640116, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004664029074265275}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:57,587] Trial 335 finished with value: 0.9490494060514353 and parameters: {'alpha': 42.29836716740495, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.0048358649237640215}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  68%|██████████████████████████████████████████████████████████████████████████▌                                   | 339/500 [02:20<00:36,  4.46it/s]

[I 2026-05-19 17:07:57,727] Trial 337 finished with value: 0.9495150549716481 and parameters: {'alpha': 45.39636934405068, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0048365963543198585}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:57,828] Trial 338 finished with value: 0.9495150509048601 and parameters: {'alpha': 42.42163028860735, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00522875367431481}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  68%|██████████████████████████████████████████████████████████████████████████▊                                   | 340/500 [02:20<00:44,  3.61it/s]

[I 2026-05-19 17:07:58,262] Trial 341 finished with value: 0.9495150551342636 and parameters: {'alpha': 44.47717929453317, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0050875872708436454}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:07:58,320] Trial 339 finished with value: 0.9495151553393292 and parameters: {'alpha': 98.97540458795766, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004951239471582327}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  68%|███████████████████████████████████████████████████████████████████████████▏                                  | 342/500 [02:20<00:36,  4.38it/s]

[I 2026-05-19 17:07:58,607] Trial 342 pruned.

Best trial: 145. Best value: 0.949515:  69%|███████████████████████████████████████████████████████████████████████████▍                                  | 343/500 [02:21<00:39,  3.93it/s]

[I 2026-05-19 17:07:58,870] Trial 340 finished with value: 0.9495150526942189 and parameters: {'alpha': 43.407701829086115, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004907464941382041}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  69%|███████████████████████████████████████████████████████████████████████████▋                                  | 344/500 [02:23<01:39,  1.57it/s]

[I 2026-05-19 17:08:00,726] Trial 343 finished with value: 0.9482305009227124 and parameters: {'alpha': 42.11753632299424, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004426155717149382}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  69%|███████████████████████████████████████████████████████████████████████████▉                                  | 345/500 [02:23<01:27,  1.76it/s]

[I 2026-05-19 17:08:01,129] Trial 344 finished with value: 0.9482313590084062 and parameters: {'alpha': 99.82525819437213, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004262751884726163}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  69%|████████████████████████████████████████████████████████████████████████████▎                                 | 347/500 [02:24<01:06,  2.30it/s]

[I 2026-05-19 17:08:01,641] Trial 350 finished with value: 0.9486953152790252 and parameters: {'alpha': 98.20365254726049, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008499785883242062}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:08:01,762] Trial 345 finished with value: 0.9482305163763245 and parameters: {'alpha': 43.09463432381204, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004374940386616667}. Best is trial 145 with value: 0.949515155339336.

[I 2026-05-19 17:08:01,946] Trial 349 finished with value: 0.9486953156043609 and parameters: {'alpha': 98.90763180321363, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008631354448603093}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:08:02,038] Trial 348 finished with value: 0.9482305258111674 and parameters: {'alpha': 43.469131810923656, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.002692305013425853}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:08:02,188] Trial 351 finished with value: 0.9486953149537098 and parameters: {'alpha': 99.54485917849323, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008455981596363904}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  70%|█████████████████████████████████████████████████████████████████████████████▍                                | 352/500 [02:24<00:26,  5.62it/s]

[I 2026-05-19 17:08:02,216] Trial 346 finished with value: 0.9482313481094286 and parameters: {'alpha': 99.2370978281655, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004402636009087705}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:08:02,303] Trial 347 finished with value: 0.949515142651007 and parameters: {'alpha': 91.61476643510129, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005728143341136113}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  71%|█████████████████████████████████████████████████████████████████████████████▉                                | 354/500 [02:25<00:35,  4.15it/s]

[I 2026-05-19 17:08:02,952] Trial 354 finished with value: 0.9495151512726252 and parameters: {'alpha': 96.94786629916648, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006161281403320342}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:08:03,004] Trial 352 finished with value: 0.948231362424508 and parameters: {'alpha': 99.92403785731923, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.002760714541704919}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:08:03,040] Trial 353 finished with value: 0.9482313105326163 and parameters: {'alpha': 96.92975744126952, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0027812227605088402}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  71%|██████████████████████████████████████████████████████████████████████████████▎                               | 356/500 [02:26<01:03,  2.26it/s]

[I 2026-05-19 17:08:04,557] Trial 356 finished with value: 0.9486953160923756 and parameters: {'alpha': 97.28542850306945, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00899699258887613}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  71%|██████████████████████████████████████████████████████████████████████████████▌                               | 357/500 [02:27<01:10,  2.04it/s]

[I 2026-05-19 17:08:05,221] Trial 355 finished with value: 0.9486953165803691 and parameters: {'alpha': 95.50214928243916, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008529103134267567}. Best is trial 145 with value: 0.949515155339336.

Best trial: 145. Best value: 0.949515:  72%|██████████████████████████████████████████████████████████████████████████████▉                               | 359/500 [02:28<01:03,  2.22it/s]

[I 2026-05-19 17:08:06,061] Trial 365 pruned.
[I 2026-05-19 17:08:06,129] Trial 357 finished with value: 0.9482312038209212 and parameters: {'alpha': 89.89169788627422, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0029053937229297686}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:08:06,146] Trial 359 finished with value: 0.9495151499712602 and parameters: {'alpha': 95.09465849459914, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006291885427295061}. Best is trial 145 with value: 0.949515155339336.

[I 2026-05-19 17:08:06,196] Trial 358 finished with value: 0.948231228709376 and parameters: {'alpha': 91.9563006463914, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0027685091332713477}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:08:06,238] Trial 366 pruned.
[I 2026-05-19 17:08:06,251] Trial 362 finished with value: 0.9495150826254907 and parameters: {'alpha': 56.58085753886431, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006352094025463871}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:08:06,260] Trial 364 pruned.

Best trial: 145. Best value: 0.949515:  73%|████████████████████████████████████████████████████████████████████████████████▌                             | 366/500 [02:28<00:20,  6.60it/s]

[I 2026-05-19 17:08:06,288] Trial 360 finished with value: 0.9495151322401207 and parameters: {'alpha': 88.93210354328484, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006145899942315685}. Best is trial 145 with value: 0.949515155339336.
[I 2026-05-19 17:08:06,381] Trial 361 finished with value: 0.9495150831134913 and parameters: {'alpha': 57.14642129636823, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005905339454668971}. Best is trial 145 with value: 0.949515155339336.

Best trial: 363. Best value: 0.949515:  73%|████████████████████████████████████████████████████████████████████████████████▌                             | 366/500 [02:29<00:20,  6.60it/s]

[I 2026-05-19 17:08:06,941] Trial 363 finished with value: 0.9495151577793669 and parameters: {'alpha': 99.5343891626218, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0062609991161933125}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  74%|████████████████████████████████████████████████████████████████████████████████▉                             | 368/500 [02:29<00:31,  4.16it/s]

[I 2026-05-19 17:08:07,458] Trial 367 pruned.

Best trial: 363. Best value: 0.949515:  74%|█████████████████████████████████████████████████████████████████████████████████▏                            | 369/500 [02:31<01:07,  1.93it/s]

[I 2026-05-19 17:08:09,158] Trial 374 pruned.
[I 2026-05-19 17:08:09,172] Trial 371 pruned.

Best trial: 363. Best value: 0.949515:  74%|█████████████████████████████████████████████████████████████████████████████████▌                            | 371/500 [02:32<00:53,  2.39it/s]

[I 2026-05-19 17:08:09,637] Trial 368 finished with value: 0.9495150925484461 and parameters: {'alpha': 60.56287913351973, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006311197354018435}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  75%|██████████████████████████████████████████████████████████████████████████████████                            | 373/500 [02:32<00:41,  3.05it/s]

[I 2026-05-19 17:08:09,913] Trial 370 finished with value: 0.9486953461862703 and parameters: {'alpha': 56.03674848511475, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006310716898999433}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:10,044] Trial 372 finished with value: 0.9486953295940206 and parameters: {'alpha': 78.015373264663, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007723624948119058}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  75%|██████████████████████████████████████████████████████████████████████████████████▌                           | 375/500 [02:32<00:28,  4.32it/s]

[I 2026-05-19 17:08:10,114] Trial 375 finished with value: 0.9486953276419483 and parameters: {'alpha': 81.3906525810308, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007357424368305318}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:10,153] Trial 376 finished with value: 0.9486953300820209 and parameters: {'alpha': 78.78317628375672, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007711698131411628}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:10,249] Trial 373 finished with value: 0.9486953292686634 and parameters: {'alpha': 80.01029417884916, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007604847895196343}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  76%|███████████████████████████████████████████████████████████████████████████████████▏                          | 378/500 [02:33<00:24,  4.90it/s]

[I 2026-05-19 17:08:10,578] Trial 369 finished with value: 0.9495150847401714 and parameters: {'alpha': 57.25832004332091, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006233094095857157}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:10,634] Trial 377 finished with value: 0.948695329756678 and parameters: {'alpha': 79.53504808502971, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007420361162244417}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:10,697] Trial 378 finished with value: 0.948695406048828 and parameters: {'alpha': 0.1224514216133663, 'solver': 'sparse_cg', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007560577973949361}. Best is trial 363 with value: 0.9495151577793669.

[I 2026-05-19 17:08:11,551] Trial 381 pruned.
[I 2026-05-19 17:08:11,606] Trial 379 finished with value: 0.9486953266659262 and parameters: {'alpha': 82.72183387209276, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0075958754713838}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:11,654] Trial 380 pruned.

Best trial: 363. Best value: 0.949515:  77%|████████████████████████████████████████████████████████████████████████████████████▎                         | 383/500 [02:34<00:22,  5.14it/s]

[I 2026-05-19 17:08:11,668] Trial 382 pruned.

Best trial: 363. Best value: 0.949515:  77%|████████████████████████████████████████████████████████████████████████████████████▍                         | 384/500 [02:34<00:24,  4.68it/s]

[I 2026-05-19 17:08:12,150] Trial 383 pruned.

Best trial: 363. Best value: 0.949515:  77%|████████████████████████████████████████████████████████████████████████████████████▋                         | 385/500 [02:34<00:25,  4.49it/s]

[I 2026-05-19 17:08:12,394] Trial 387 pruned.

Best trial: 363. Best value: 0.949515:  77%|████████████████████████████████████████████████████████████████████████████████████▉                         | 386/500 [02:35<00:38,  2.99it/s]

[I 2026-05-19 17:08:13,015] Trial 389 pruned.
[I 2026-05-19 17:08:13,084] Trial 390 pruned.

Best trial: 363. Best value: 0.949515:  78%|█████████████████████████████████████████████████████████████████████████████████████▎                        | 388/500 [02:36<00:43,  2.56it/s]

[I 2026-05-19 17:08:13,985] Trial 388 finished with value: 0.9486953151163535 and parameters: {'alpha': 98.35795140981543, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009510962539729453}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:14,083] Trial 384 finished with value: 0.9486953273166051 and parameters: {'alpha': 81.5414953167001, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007687405949912306}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  78%|█████████████████████████████████████████████████████████████████████████████████████▊                        | 390/500 [02:36<00:33,  3.33it/s]

[I 2026-05-19 17:08:14,272] Trial 386 finished with value: 0.9482313178527926 and parameters: {'alpha': 97.43347348939318, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003979055540021406}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:14,341] Trial 385 finished with value: 0.9486953160923755 and parameters: {'alpha': 97.04956408757006, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007773500868877091}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  78%|██████████████████████████████████████████████████████████████████████████████████████▏                       | 392/500 [02:37<00:43,  2.48it/s]

[I 2026-05-19 17:08:15,510] Trial 392 finished with value: 0.9482304264198371 and parameters: {'alpha': 36.89109085038864, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0040931101784449}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  79%|██████████████████████████████████████████████████████████████████████████████████████▋                       | 394/500 [02:38<00:35,  2.98it/s]

[I 2026-05-19 17:08:15,807] Trial 393 finished with value: 0.9482304182863663 and parameters: {'alpha': 36.23325141589311, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0039323061117143236}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:15,875] Trial 396 finished with value: 0.948695369773388 and parameters: {'alpha': 34.184168460477586, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00986928131783797}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  79%|███████████████████████████████████████████████████████████████████████████████████████                       | 396/500 [02:38<00:30,  3.41it/s]

[I 2026-05-19 17:08:16,278] Trial 394 finished with value: 0.9482303880297094 and parameters: {'alpha': 34.61376781612817, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004098933940467964}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:16,427] Trial 395 finished with value: 0.9482304213770621 and parameters: {'alpha': 36.45155598061179, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004274786686593247}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  79%|███████████████████████████████████████████████████████████████████████████████████████▎                      | 397/500 [02:39<00:31,  3.28it/s]

[I 2026-05-19 17:08:16,723] Trial 391 finished with value: 0.9482304335773069 and parameters: {'alpha': 37.42548952922936, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004214441764210778}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  80%|███████████████████████████████████████████████████████████████████████████████████████▌                      | 398/500 [02:39<00:31,  3.23it/s]

[I 2026-05-19 17:08:17,121] Trial 397 finished with value: 0.9495150800227886 and parameters: {'alpha': 54.95413368132499, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00547071784384942}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  80%|███████████████████████████████████████████████████████████████████████████████████████▊                      | 399/500 [02:39<00:35,  2.88it/s]

[I 2026-05-19 17:08:17,547] Trial 398 finished with value: 0.9495150639184973 and parameters: {'alpha': 49.4878863919703, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0056628953148257334}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  80%|████████████████████████████████████████████████████████████████████████████████████████▏                     | 401/500 [02:40<00:49,  1.98it/s]

[I 2026-05-19 17:08:18,411] Trial 400 finished with value: 0.9495150650571771 and parameters: {'alpha': 49.722883327131136, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005562150063533013}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:18,452] Trial 401 finished with value: 0.9495150715640095 and parameters: {'alpha': 52.6416517437518, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005491678938771553}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:18,462] Trial 399 finished with value: 0.9495150746546704 and parameters: {'alpha': 53.62774441011694, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005654198893985424}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  81%|████████████████████████████████████████████████████████████████████████████████████████▋                     | 403/500 [02:41<00:26,  3.67it/s]

[I 2026-05-19 17:08:18,691] Trial 402 finished with value: 0.9495150614784317 and parameters: {'alpha': 48.759733633263494, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005635028872707561}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  81%|████████████████████████████████████████████████████████████████████████████████████████▉                     | 404/500 [02:41<00:38,  2.46it/s]

[I 2026-05-19 17:08:19,616] Trial 403 finished with value: 0.9495150655451706 and parameters: {'alpha': 49.78005176509164, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005224390573421093}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  81%|█████████████████████████████████████████████████████████████████████████████████████████                     | 405/500 [02:42<00:43,  2.21it/s]

[I 2026-05-19 17:08:20,182] Trial 404 finished with value: 0.9495150679852504 and parameters: {'alpha': 50.96865428251924, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005511388493290097}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:20,221] Trial 405 finished with value: 0.9495150686358944 and parameters: {'alpha': 51.96998771353167, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005568363684389624}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  82%|█████████████████████████████████████████████████████████████████████████████████████████▉                    | 409/500 [02:43<00:26,  3.46it/s]

[I 2026-05-19 17:08:20,841] Trial 406 finished with value: 0.9495150714013312 and parameters: {'alpha': 52.68159236680204, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005682929811286224}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:20,860] Trial 411 pruned.
[I 2026-05-19 17:08:20,878] Trial 408 finished with value: 0.9495150674972358 and parameters: {'alpha': 51.009336749439974, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005626568837451002}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:20,913] Trial 413 pruned.

Best trial: 363. Best value: 0.949515:  82%|██████████████████████████████████████████████████████████████████████████████████████████▍                   | 411/500 [02:43<00:19,  4.64it/s]

[I 2026-05-19 17:08:21,055] Trial 407 finished with value: 0.9495150717266672 and parameters: {'alpha': 52.69309705565598, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005541782048498909}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  82%|██████████████████████████████████████████████████████████████████████████████████████████▋                   | 412/500 [02:43<00:20,  4.23it/s]

[I 2026-05-19 17:08:21,523] Trial 409 finished with value: 0.9495150673345641 and parameters: {'alpha': 51.02338798170879, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00573333309532891}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  83%|███████████████████████████████████████████████████████████████████████████████████████████                   | 414/500 [02:44<00:19,  4.40it/s]

[I 2026-05-19 17:08:21,805] Trial 410 finished with value: 0.9495150951511624 and parameters: {'alpha': 61.22474069983556, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005178521205947076}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:21,978] Trial 415 pruned.

Best trial: 363. Best value: 0.949515:  83%|███████████████████████████████████████████████████████████████████████████████████████████▎                  | 415/500 [02:45<00:28,  2.94it/s]

[I 2026-05-19 17:08:22,646] Trial 416 pruned.
[I 2026-05-19 17:08:22,725] Trial 412 finished with value: 0.9495149661535465 and parameters: {'alpha': 0.42401515761983677, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0061196259425124345}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  83%|███████████████████████████████████████████████████████████████████████████████████████████▋                  | 417/500 [02:45<00:27,  3.06it/s]

[I 2026-05-19 17:08:23,268] Trial 414 finished with value: 0.9495151049114392 and parameters: {'alpha': 67.3433338286559, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006447962567120766}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  84%|███████████████████████████████████████████████████████████████████████████████████████████▉                  | 418/500 [02:46<00:45,  1.80it/s]

[I 2026-05-19 17:08:24,521] Trial 417 finished with value: 0.9495151060501259 and parameters: {'alpha': 67.75200042156725, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00650183249059996}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:24,638] Trial 421 pruned.

Best trial: 363. Best value: 0.949515:  84%|████████████████████████████████████████████████████████████████████████████████████████████▍                 | 420/500 [02:47<00:31,  2.51it/s]

[I 2026-05-19 17:08:24,905] Trial 422 pruned.

Best trial: 363. Best value: 0.949515:  84%|████████████████████████████████████████████████████████████████████████████████████████████▌                 | 421/500 [02:47<00:29,  2.63it/s]

[I 2026-05-19 17:08:25,153] Trial 420 pruned.

Best trial: 363. Best value: 0.949515:  84%|████████████████████████████████████████████████████████████████████████████████████████████▊                 | 422/500 [02:47<00:26,  2.91it/s]

[I 2026-05-19 17:08:25,442] Trial 418 finished with value: 0.9488953074068261 and parameters: {'alpha': 73.13651085033763, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004653797654131225}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:25,489] Trial 419 finished with value: 0.9482309539595798 and parameters: {'alpha': 73.22532436573681, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0032484820562526124}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▎                | 424/500 [02:48<00:23,  3.18it/s]

[I 2026-05-19 17:08:25,954] Trial 423 finished with value: 0.9482299618334462 and parameters: {'alpha': 5.013498688601914, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003365341031609628}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▋                | 426/500 [02:48<00:18,  3.90it/s]

[I 2026-05-19 17:08:26,199] Trial 424 finished with value: 0.9482298876557109 and parameters: {'alpha': 0.2900132178617748, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003334249847096869}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:26,333] Trial 426 pruned.

Best trial: 363. Best value: 0.949515:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▉                | 427/500 [02:48<00:18,  3.91it/s]

[I 2026-05-19 17:08:26,513] Trial 425 finished with value: 0.948230981125499 and parameters: {'alpha': 75.16342995044342, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003091037406269158}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  86%|██████████████████████████████████████████████████████████████████████████████████████████████▏               | 428/500 [02:49<00:19,  3.67it/s]

[I 2026-05-19 17:08:26,850] Trial 427 finished with value: 0.9482309443619954 and parameters: {'alpha': 72.12860412525043, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004407304984649865}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  86%|██████████████████████████████████████████████████████████████████████████████████████████████▍               | 429/500 [02:49<00:21,  3.24it/s]

[I 2026-05-19 17:08:27,352] Trial 428 finished with value: 0.948695314953703 and parameters: {'alpha': 99.71797611460859, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00992556932018664}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  86%|███████████████████████████████████████████████████████████████████████████████████████████████               | 432/500 [02:51<00:23,  2.88it/s]

[I 2026-05-19 17:08:28,487] Trial 429 finished with value: 0.9486953156043679 and parameters: {'alpha': 99.1847008963294, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009983959735728257}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:28,571] Trial 430 finished with value: 0.9486954058861563 and parameters: {'alpha': 0.940816628058585, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008769008596078277}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:28,642] Trial 431 finished with value: 0.9486953170683836 and parameters: {'alpha': 96.4446360303677, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009897507741605837}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  87%|███████████████████████████████████████████████████████████████████████████████████████████████▎              | 433/500 [02:51<00:23,  2.87it/s]

[I 2026-05-19 17:08:29,010] Trial 432 finished with value: 0.9486953159297039 and parameters: {'alpha': 97.24749000742146, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009957566925607836}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:29,183] Trial 434 finished with value: 0.9486953151163744 and parameters: {'alpha': 99.59703463777137, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008855318279570519}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  87%|███████████████████████████████████████████████████████████████████████████████████████████████▋              | 435/500 [02:51<00:20,  3.10it/s]

[I 2026-05-19 17:08:29,569] Trial 433 finished with value: 0.9482313251729059 and parameters: {'alpha': 97.87554090788386, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.003413942009427216}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  88%|████████████████████████████████████████████████████████████████████████████████████████████████▌             | 439/500 [02:52<00:11,  5.42it/s]

[I 2026-05-19 17:08:30,036] Trial 437 finished with value: 0.9486953164176907 and parameters: {'alpha': 94.88379777394981, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009259378998135365}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:30,080] Trial 438 finished with value: 0.9486953222738161 and parameters: {'alpha': 86.37350292452413, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008953912595795383}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:30,082] Trial 435 finished with value: 0.9486953154416964 and parameters: {'alpha': 99.0400611344332, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008431081497606163}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:30,118] Trial 436 finished with value: 0.9486953154416964 and parameters: {'alpha': 99.0619359706245, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.009014402225604788}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  88%|████████████████████████████████████████████████████████████████████████████████████████████████▊             | 440/500 [02:52<00:14,  4.27it/s]

[I 2026-05-19 17:08:30,607] Trial 439 finished with value: 0.9486954052354843 and parameters: {'alpha': 1.0687526671723613, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00849762799902638}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████             | 441/500 [02:53<00:17,  3.43it/s]

[I 2026-05-19 17:08:31,094] Trial 440 finished with value: 0.9486953164176907 and parameters: {'alpha': 95.29756812447154, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007966169918418054}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 363. Best value: 0.949515:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████▏            | 442/500 [02:54<00:27,  2.11it/s]

[I 2026-05-19 17:08:32,131] Trial 442 finished with value: 0.9495151545259786 and parameters: {'alpha': 98.49827059617651, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0070316407034663065}. Best is trial 363 with value: 0.9495151577793669.
[I 2026-05-19 17:08:32,150] Trial 443 finished with value: 0.9495151553393292 and parameters: {'alpha': 98.69850141557491, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006990624707948613}. Best is trial 363 with value: 0.9495151577793669.

Best trial: 444. Best value: 0.949515:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████▋            | 444/500 [02:54<00:19,  2.82it/s]

[I 2026-05-19 17:08:32,506] Trial 444 finished with value: 0.9495151579420383 and parameters: {'alpha': 99.36883070481686, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006964629514169135}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████▉            | 445/500 [02:55<00:20,  2.74it/s]

[I 2026-05-19 17:08:32,902] Trial 449 finished with value: 0.9495151013327149 and parameters: {'alpha': 63.95129291781983, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007047505194778951}. Best is trial 444 with value: 0.9495151579420383.
[I 2026-05-19 17:08:32,914] Trial 448 finished with value: 0.9495150876682936 and parameters: {'alpha': 58.830651411781126, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006986557669996036}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████▎           | 447/500 [02:56<00:23,  2.22it/s]

[I 2026-05-19 17:08:34,063] Trial 454 finished with value: 0.9486953390288354 and parameters: {'alpha': 64.05951502704535, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007245794408122806}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  90%|██████████████████████████████████████████████████████████████████████████████████████████████████▌           | 448/500 [02:57<00:26,  2.00it/s]

[I 2026-05-19 17:08:34,737] Trial 456 finished with value: 0.9495151081649815 and parameters: {'alpha': 77.57014811169458, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007106026310084758}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  90%|██████████████████████████████████████████████████████████████████████████████████████████████████▊           | 449/500 [02:58<00:32,  1.56it/s]

[I 2026-05-19 17:08:35,836] Trial 458 finished with value: 0.9495151084903176 and parameters: {'alpha': 77.5118115074634, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007045920564111001}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████           | 450/500 [02:58<00:26,  1.88it/s]

[I 2026-05-19 17:08:36,041] Trial 441 pruned.

Best trial: 444. Best value: 0.949515:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████▏          | 451/500 [02:59<00:27,  1.76it/s]

[I 2026-05-19 17:08:36,716] Trial 459 finished with value: 0.9495151065382176 and parameters: {'alpha': 75.36160088728083, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007102184496168145}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████▍          | 452/500 [02:59<00:28,  1.70it/s]

[I 2026-05-19 17:08:37,348] Trial 447 pruned.

Best trial: 444. Best value: 0.949515:  91%|███████████████████████████████████████████████████████████████████████████████████████████████████▋          | 453/500 [02:59<00:23,  1.97it/s]

[I 2026-05-19 17:08:37,658] Trial 461 finished with value: 0.9486953292686703 and parameters: {'alpha': 79.93276795934595, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0073667023156649865}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  91%|███████████████████████████████████████████████████████████████████████████████████████████████████▉          | 454/500 [03:00<00:20,  2.27it/s]

[I 2026-05-19 17:08:37,925] Trial 451 pruned.

Best trial: 444. Best value: 0.949515:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████          | 455/500 [03:00<00:22,  2.00it/s]

[I 2026-05-19 17:08:38,575] Trial 450 pruned.

[I 2026-05-19 17:08:38,913] Trial 462 finished with value: 0.9488727464684927 and parameters: {'alpha': 77.21667561896223, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00720324773492289}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 457/500 [03:01<00:16,  2.60it/s]

[I 2026-05-19 17:08:39,105] Trial 446 pruned.

Best trial: 444. Best value: 0.949515:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 459/500 [03:01<00:12,  3.26it/s]

[I 2026-05-19 17:08:39,549] Trial 452 pruned.
[I 2026-05-19 17:08:39,638] Trial 463 finished with value: 0.9486953302446924 and parameters: {'alpha': 78.50220070508293, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007668296272519004}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 460/500 [03:02<00:12,  3.21it/s]

[I 2026-05-19 17:08:39,959] Trial 457 pruned.
[I 2026-05-19 17:08:39,989] Trial 445 pruned.

Best trial: 444. Best value: 0.949515:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 462/500 [03:02<00:10,  3.69it/s]

[I 2026-05-19 17:08:40,410] Trial 465 finished with value: 0.9486953156043609 and parameters: {'alpha': 98.91193303405778, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007911822160357261}. Best is trial 444 with value: 0.9495151579420383.
[I 2026-05-19 17:08:40,430] Trial 464 pruned.

Best trial: 444. Best value: 0.949515:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 465/500 [03:03<00:07,  4.52it/s]

[I 2026-05-19 17:08:40,872] Trial 453 pruned.
[I 2026-05-19 17:08:40,909] Trial 455 pruned.

Best trial: 444. Best value: 0.949515:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 466/500 [03:04<00:11,  2.88it/s]

[I 2026-05-19 17:08:41,802] Trial 466 finished with value: 0.948695329431349 and parameters: {'alpha': 79.40862409661577, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007859468998907056}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 467/500 [03:04<00:12,  2.60it/s]

[I 2026-05-19 17:08:42,290] Trial 467 finished with value: 0.9486953152790459 and parameters: {'alpha': 99.41996758211805, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.007748840172752632}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 468/500 [03:05<00:13,  2.34it/s]

[I 2026-05-19 17:08:42,910] Trial 468 finished with value: 0.9486953278046197 and parameters: {'alpha': 81.31980235236087, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00792142528938713}. Best is trial 444 with value: 0.9495151579420383.

[I 2026-05-19 17:08:43,571] Trial 470 finished with value: 0.9482305014107201 and parameters: {'alpha': 42.15892918773567, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004559336410910883}. Best is trial 444 with value: 0.9495151579420383.
[I 2026-05-19 17:08:43,690] Trial 471 finished with value: 0.9491821101389208 and parameters: {'alpha': 80.08782420172228, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004686852922836194}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 470/500 [03:06<00:11,  2.51it/s]

[I 2026-05-19 17:08:43,779] Trial 469 pruned.

[I 2026-05-19 17:08:44,191] Trial 472 finished with value: 0.9491822152242646 and parameters: {'alpha': 98.52735340639059, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004656684264585371}. Best is trial 444 with value: 0.9495151579420383.
[I 2026-05-19 17:08:44,282] Trial 474 finished with value: 0.949181969102878 and parameters: {'alpha': 42.983110269543324, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00469178319980775}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 474/500 [03:06<00:06,  4.17it/s]

[I 2026-05-19 17:08:44,390] Trial 473 finished with value: 0.9495150556222782 and parameters: {'alpha': 44.45903086549057, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.0048682809842930256}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 475/500 [03:07<00:07,  3.54it/s]

[I 2026-05-19 17:08:44,834] Trial 475 pruned.

Best trial: 444. Best value: 0.949515:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 476/500 [03:07<00:08,  2.93it/s]

[I 2026-05-19 17:08:45,340] Trial 476 finished with value: 0.949515050579496 and parameters: {'alpha': 41.71022032538556, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004721808733384001}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 477/500 [03:07<00:07,  2.99it/s]

[I 2026-05-19 17:08:45,651] Trial 477 finished with value: 0.9491819645480966 and parameters: {'alpha': 42.323985192845896, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004692415267302474}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 478/500 [03:09<00:11,  1.94it/s]

[I 2026-05-19 17:08:46,583] Trial 481 pruned.
[I 2026-05-19 17:08:46,668] Trial 478 finished with value: 0.9482305079175107 and parameters: {'alpha': 42.43076374720668, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004545306108526205}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 480/500 [03:09<00:07,  2.80it/s]

[I 2026-05-19 17:08:46,936] Trial 483 pruned.

Best trial: 444. Best value: 0.949515:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████    | 482/500 [03:09<00:05,  3.25it/s]

[I 2026-05-19 17:08:47,393] Trial 485 pruned.
[I 2026-05-19 17:08:47,490] Trial 479 finished with value: 0.9482305274378756 and parameters: {'alpha': 43.5841315765709, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.004530827701135851}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 483/500 [03:10<00:04,  3.64it/s]

[I 2026-05-19 17:08:47,666] Trial 486 pruned.

[I 2026-05-19 17:08:47,909] Trial 480 finished with value: 0.9488947714050306 and parameters: {'alpha': 0.05413055279986983, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00460854060178766}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 485/500 [03:10<00:03,  3.88it/s]

[I 2026-05-19 17:08:48,110] Trial 482 finished with value: 0.9495150526942187 and parameters: {'alpha': 43.397274725175514, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.00485479594742045}. Best is trial 444 with value: 0.9495151579420383.

[I 2026-05-19 17:08:48,392] Trial 488 pruned.
[I 2026-05-19 17:08:48,402] Trial 487 pruned.

Best trial: 444. Best value: 0.949515:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 488/500 [03:10<00:02,  5.20it/s]

[I 2026-05-19 17:08:48,583] Trial 484 finished with value: 0.9495150517182107 and parameters: {'alpha': 42.73785058612044, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.005255793810834316}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 489/500 [03:12<00:05,  1.98it/s]

[I 2026-05-19 17:08:50,108] Trial 491 pruned.

Best trial: 444. Best value: 0.949515:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 491/500 [03:13<00:03,  2.28it/s]

[I 2026-05-19 17:08:50,767] Trial 490 finished with value: 0.9495151091409897 and parameters: {'alpha': 76.10746833532698, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006236258288020269}. Best is trial 444 with value: 0.9495151579420383.
[I 2026-05-19 17:08:50,954] Trial 489 finished with value: 0.9495151571287017 and parameters: {'alpha': 99.1930243508348, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006092999989998492}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 492/500 [03:13<00:03,  2.49it/s]

[I 2026-05-19 17:08:51,254] Trial 492 finished with value: 0.9486954062114925 and parameters: {'alpha': 0.07023789643962455, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008636614943181622}. Best is trial 444 with value: 0.9495151579420383.
[I 2026-05-19 17:08:51,305] Trial 493 finished with value: 0.9490494099556075 and parameters: {'alpha': 76.7804057016056, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.008841660802208115}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 494/500 [03:13<00:01,  3.53it/s]

[I 2026-05-19 17:08:51,519] Trial 495 pruned.
[I 2026-05-19 17:08:51,571] Trial 496 finished with value: 0.9490494171131403 and parameters: {'alpha': 99.33230567039884, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.006095921855944322}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 498/500 [03:14<00:00,  6.31it/s]

[I 2026-05-19 17:08:51,747] Trial 494 finished with value: 0.9490494167878112 and parameters: {'alpha': 99.12278857853536, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.008356714259022053}. Best is trial 444 with value: 0.9495151579420383.
[I 2026-05-19 17:08:51,760] Trial 497 finished with value: 0.9486953295940206 and parameters: {'alpha': 77.99050146057263, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.008623903246598915}. Best is trial 444 with value: 0.9495151579420383.
[I 2026-05-19 17:08:51,863] Trial 499 finished with value: 0.949049410118258 and parameters: {'alpha': 76.14842486963971, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.009762865078653421}. Best is trial 444 with value: 0.9495151579420383.
[I 2026-05-19 17:08:51,926] Trial 498 finished with value: 0.9490494093049145 and parameters: {'alpha': 74.35165459155428, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': True, 'tol': 0.00859977922115067}. Best is trial 444 with value: 0.9495151579420383.

Best trial: 444. Best value: 0.949515: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [03:18<00:00,  2.52it/s]

[I 2026-05-19 17:08:55,721] Trial 460 pruned.
Best trial score:
0.9495151579420383

Best params:
{'alpha': 99.36883070481686, 'solver': 'lsqr', 'class_weight': None, 'fit_intercept': False, 'tol': 0.006964629514169135}

In [9]:
stacking_ridge = RidgeClassifier(**study.best_params).fit(X_train, y_train.PitNextLap)

# Submission

In [10]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [13]:
submission['PitNextLap'] = stacking_ridge.decision_function(X_test)

In [14]:
submission.to_csv('../data/submission/submission.csv', index=False)

In [15]:
X_train.columns

Index(['lgbm_logit', 'cat_logit', 'xgb_logit', 'hist_logit', 'lg_logit',
       'knn_logit', 'ridge_logit', 'voting_lgbm_cat_xgb_hist_logit',
       'voting_lg_ridge_logit',
       'stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_logit'],
      dtype='str')