# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from lightgbm import LGBMClassifier

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import StackingClassifier, VotingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

# Loading Dataset

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking2.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking2.parquet')

In [4]:
X_train.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,ridge_proba,voting_lgbm_cat_xgb_hist_proba,voting_lg_ridge_proba,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.519677,0.868510,0.664963,0.772948
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.395214,0.772514,0.543445,0.595178
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.259447,0.717012,0.409891,0.515461
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,0.005106,0.005494,0.003682,0.001281
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,0.150282,0.482416,0.283014,0.293768

In [5]:
X_test.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,ridge_proba,voting_lgbm_cat_xgb_hist_proba,voting_lg_ridge_proba,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,0.004726,0.019849,0.005577,0.006190
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,0.033245,0.012173,0.048652,0.003070
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,0.003903,0.010304,0.004212,0.003695
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.296579,0.444558,0.477315,0.232534
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.548189,0.939648,0.695206,0.894775

# Machine Learning

In [6]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "objective": "binary",
        "n_estimators": trial.suggest_int("n_estimators", 30, 300),
        "learning_rate": trial.suggest_float("learning_rate", 0.003, 0.05, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 4),
        "num_leaves": trial.suggest_int("num_leaves", 2, 16),
        "min_child_samples": trial.suggest_int("min_child_samples", 20, 300),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-5, 100, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-5, 100, log=True),
        "verbosity": -1,
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LGBMClassifier(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)


study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-19 11:55:27,823] A new study created in memory with name: no-name-b1f1d6c3-5723-4bab-9318-1e486054d58a
Best trial: 7. Best value: 0.946324:   0%|▏                                                                                                               | 1/500 [00:10<1:24:23, 10.15s/it]

[I 2026-05-19 11:55:37,954] Trial 7 finished with value: 0.94632412344384 and parameters: {'n_estimators': 55, 'learning_rate': 0.01728958547161018, 'max_depth': 2, 'num_leaves': 16, 'min_child_samples': 87, 'subsample': 0.8637829805807256, 'colsample_bytree': 0.6992776552507046, 'reg_alpha': 3.7191745933425146e-05, 'reg_lambda': 0.00018940826559520394}. Best is trial 7 with value: 0.94632412344384.

Best trial: 6. Best value: 0.949667:   0%|▍                                                                                                                 | 2/500 [00:13<49:41,  5.99s/it]

[I 2026-05-19 11:55:41,036] Trial 6 finished with value: 0.9496667082764386 and parameters: {'n_estimators': 71, 'learning_rate': 0.044784103123623076, 'max_depth': 2, 'num_leaves': 15, 'min_child_samples': 71, 'subsample': 0.8426805756789664, 'colsample_bytree': 0.643698417386747, 'reg_alpha': 2.9804608740949465e-05, 'reg_lambda': 0.002221516692151999}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   1%|▋                                                                                                                 | 3/500 [00:15<37:14,  4.50s/it]

[I 2026-05-19 11:55:43,745] Trial 11 finished with value: 0.9385699760362807 and parameters: {'n_estimators': 125, 'learning_rate': 0.009530832957462983, 'max_depth': 1, 'num_leaves': 11, 'min_child_samples': 204, 'subsample': 0.9500789935629619, 'colsample_bytree': 0.7094218301117164, 'reg_alpha': 0.6468608630259145, 'reg_lambda': 25.410145533683778}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   1%|▉                                                                                                                 | 4/500 [00:18<31:40,  3.83s/it]

[I 2026-05-19 11:55:46,574] Trial 12 finished with value: 0.9069217705976126 and parameters: {'n_estimators': 63, 'learning_rate': 0.003311731595148475, 'max_depth': 1, 'num_leaves': 15, 'min_child_samples': 171, 'subsample': 0.9919070910567017, 'colsample_bytree': 0.6409444254473063, 'reg_alpha': 0.006048280175235138, 'reg_lambda': 0.00041304406580813726}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   1%|█▏                                                                                                                | 5/500 [00:19<21:40,  2.63s/it]

[I 2026-05-19 11:55:47,039] Trial 4 finished with value: 0.9493820227615455 and parameters: {'n_estimators': 157, 'learning_rate': 0.03299120792076453, 'max_depth': 1, 'num_leaves': 4, 'min_child_samples': 89, 'subsample': 0.9137046833373836, 'colsample_bytree': 0.7758367161785993, 'reg_alpha': 1.3624655347906683e-05, 'reg_lambda': 0.013164598068294085}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   1%|█▎                                                                                                                | 6/500 [00:19<16:21,  1.99s/it]

[I 2026-05-19 11:55:47,791] Trial 2 pruned.

Best trial: 6. Best value: 0.949667:   1%|█▌                                                                                                                | 7/500 [00:22<16:54,  2.06s/it]

[I 2026-05-19 11:55:49,999] Trial 8 finished with value: 0.9468069380174746 and parameters: {'n_estimators': 200, 'learning_rate': 0.012956540773187104, 'max_depth': 1, 'num_leaves': 14, 'min_child_samples': 140, 'subsample': 0.8631196279023817, 'colsample_bytree': 0.7723749117693472, 'reg_alpha': 0.045077551207763626, 'reg_lambda': 0.013041651933848146}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   2%|█▊                                                                                                                | 8/500 [00:23<13:53,  1.69s/it]

[I 2026-05-19 11:55:50,898] Trial 0 finished with value: 0.9485442621020503 and parameters: {'n_estimators': 218, 'learning_rate': 0.01858292740355286, 'max_depth': 1, 'num_leaves': 16, 'min_child_samples': 42, 'subsample': 0.6385864865824477, 'colsample_bytree': 0.8223381035536617, 'reg_alpha': 2.136225696782116, 'reg_lambda': 95.78191140297537}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   2%|██                                                                                                                | 9/500 [00:24<13:28,  1.65s/it]

[I 2026-05-19 11:55:52,455] Trial 9 finished with value: 0.9482407102241039 and parameters: {'n_estimators': 130, 'learning_rate': 0.011456853992318607, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 143, 'subsample': 0.7598670958917533, 'colsample_bytree': 0.8177453808923993, 'reg_alpha': 0.0015481822090050194, 'reg_lambda': 0.02099238061705109}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   2%|██▍                                                                                                              | 11/500 [00:33<21:36,  2.65s/it]

[I 2026-05-19 11:56:00,961] Trial 13 pruned.
[I 2026-05-19 11:56:01,095] Trial 10 finished with value: 0.9485339278174871 and parameters: {'n_estimators': 162, 'learning_rate': 0.005579089235013163, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 32, 'subsample': 0.6067316392954504, 'colsample_bytree': 0.8494282974849999, 'reg_alpha': 0.0005140430485383047, 'reg_lambda': 11.349699596943964}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   2%|██▋                                                                                                              | 12/500 [00:35<21:30,  2.64s/it]

[I 2026-05-19 11:56:03,710] Trial 14 finished with value: 0.948000165569973 and parameters: {'n_estimators': 87, 'learning_rate': 0.005717193261929238, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 256, 'subsample': 0.6787319286262252, 'colsample_bytree': 0.8812920024477156, 'reg_alpha': 3.751051036699256, 'reg_lambda': 7.664144329316719}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   3%|██▉                                                                                                              | 13/500 [00:36<16:01,  1.97s/it]

[I 2026-05-19 11:56:04,137] Trial 18 pruned.

Best trial: 6. Best value: 0.949667:   3%|███▏                                                                                                             | 14/500 [00:41<23:16,  2.87s/it]

[I 2026-05-19 11:56:09,094] Trial 16 finished with value: 0.9488457578448006 and parameters: {'n_estimators': 149, 'learning_rate': 0.020150343593678663, 'max_depth': 3, 'num_leaves': 3, 'min_child_samples': 284, 'subsample': 0.934562386696822, 'colsample_bytree': 0.8131406660427924, 'reg_alpha': 3.8437099823167424e-05, 'reg_lambda': 28.80278858660137}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   3%|███▍                                                                                                             | 15/500 [00:42<20:01,  2.48s/it]

[I 2026-05-19 11:56:10,669] Trial 23 finished with value: 0.9482862567299863 and parameters: {'n_estimators': 34, 'learning_rate': 0.04968756205153791, 'max_depth': 2, 'num_leaves': 7, 'min_child_samples': 97, 'subsample': 0.8082866580387065, 'colsample_bytree': 0.6108775754172491, 'reg_alpha': 1.3180702885483472e-05, 'reg_lambda': 0.33739487356188474}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   3%|███▌                                                                                                             | 16/500 [00:43<15:40,  1.94s/it]

[I 2026-05-19 11:56:11,344] Trial 21 finished with value: 0.9487559526301089 and parameters: {'n_estimators': 39, 'learning_rate': 0.049495234290745815, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 283, 'subsample': 0.7572267576938029, 'colsample_bytree': 0.6029130778470904, 'reg_alpha': 59.75187658337982, 'reg_lambda': 1.752167180049068e-05}. Best is trial 6 with value: 0.9496667082764386.

Best trial: 6. Best value: 0.949667:   3%|███▊                                                                                                             | 17/500 [00:45<15:37,  1.94s/it]

[I 2026-05-19 11:56:13,299] Trial 25 pruned.

Best trial: 3. Best value: 0.949742:   4%|████                                                                                                             | 18/500 [00:46<14:00,  1.74s/it]

[I 2026-05-19 11:56:14,580] Trial 3 finished with value: 0.949741705844164 and parameters: {'n_estimators': 180, 'learning_rate': 0.00912591226886342, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 86, 'subsample': 0.9897263390029388, 'colsample_bytree': 0.9200307258289407, 'reg_alpha': 0.5857215688427292, 'reg_lambda': 1.6563705663840824e-05}. Best is trial 3 with value: 0.949741705844164.

Best trial: 3. Best value: 0.949742:   4%|████▎                                                                                                            | 19/500 [00:48<13:55,  1.74s/it]

[I 2026-05-19 11:56:16,311] Trial 19 finished with value: 0.9490760851137201 and parameters: {'n_estimators': 88, 'learning_rate': 0.0032305530725160667, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 134, 'subsample': 0.8868169422824341, 'colsample_bytree': 0.8193275537776371, 'reg_alpha': 0.02542437461074979, 'reg_lambda': 1.9348012526939086e-05}. Best is trial 3 with value: 0.949741705844164.

Best trial: 22. Best value: 0.949764:   4%|████▍                                                                                                           | 20/500 [00:49<11:59,  1.50s/it]

[I 2026-05-19 11:56:17,254] Trial 22 finished with value: 0.9497640744468431 and parameters: {'n_estimators': 95, 'learning_rate': 0.047690823994187344, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 294, 'subsample': 0.7497696022703582, 'colsample_bytree': 0.6279724331774281, 'reg_alpha': 1.3747882192234027e-05, 'reg_lambda': 0.2454516845616343}. Best is trial 22 with value: 0.9497640744468431.

Best trial: 1. Best value: 0.949793:   4%|████▋                                                                                                            | 21/500 [00:50<10:58,  1.38s/it]

[I 2026-05-19 11:56:18,337] Trial 1 finished with value: 0.9497928574785097 and parameters: {'n_estimators': 250, 'learning_rate': 0.020130878081682516, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 206, 'subsample': 0.8311549542740104, 'colsample_bytree': 0.7928851807062598, 'reg_alpha': 0.0038528364875726924, 'reg_lambda': 0.00035087116541151814}. Best is trial 1 with value: 0.9497928574785097.

Best trial: 1. Best value: 0.949793:   4%|████▉                                                                                                            | 22/500 [01:01<34:14,  4.30s/it]

[I 2026-05-19 11:56:29,420] Trial 5 finished with value: 0.9488693497155769 and parameters: {'n_estimators': 277, 'learning_rate': 0.004082714886730278, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 140, 'subsample': 0.69196518059212, 'colsample_bytree': 0.6406122565451634, 'reg_alpha': 0.05010775705163281, 'reg_lambda': 60.47439673497181}. Best is trial 1 with value: 0.9497928574785097.

Best trial: 1. Best value: 0.949793:   5%|█████▏                                                                                                           | 23/500 [01:02<24:48,  3.12s/it]

[I 2026-05-19 11:56:29,778] Trial 28 finished with value: 0.9496495636624791 and parameters: {'n_estimators': 100, 'learning_rate': 0.030870079209651596, 'max_depth': 2, 'num_leaves': 4, 'min_child_samples': 116, 'subsample': 0.8986298471047325, 'colsample_bytree': 0.7525760005082992, 'reg_alpha': 0.0001760921495743547, 'reg_lambda': 0.003030290513800286}. Best is trial 1 with value: 0.9497928574785097.

Best trial: 1. Best value: 0.949793:   5%|█████▍                                                                                                           | 24/500 [01:09<36:16,  4.57s/it]

[I 2026-05-19 11:56:37,789] Trial 24 finished with value: 0.9497779182668573 and parameters: {'n_estimators': 220, 'learning_rate': 0.04973967875419435, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 99, 'subsample': 0.8116447378140957, 'colsample_bytree': 0.6301980278427516, 'reg_alpha': 89.13886517685907, 'reg_lambda': 1.1233889359440755e-05}. Best is trial 1 with value: 0.9497928574785097.

Best trial: 1. Best value: 0.949793:   5%|█████▋                                                                                                           | 25/500 [01:13<33:17,  4.21s/it]

[I 2026-05-19 11:56:41,127] Trial 26 finished with value: 0.9497711498632142 and parameters: {'n_estimators': 208, 'learning_rate': 0.04658952225929678, 'max_depth': 2, 'num_leaves': 5, 'min_child_samples': 86, 'subsample': 0.8175059973352163, 'colsample_bytree': 0.6619537191654788, 'reg_alpha': 99.407623409203, 'reg_lambda': 0.0025705850087979895}. Best is trial 1 with value: 0.9497928574785097.

Best trial: 27. Best value: 0.949794:   5%|█████▊                                                                                                          | 26/500 [01:14<27:11,  3.44s/it]

[I 2026-05-19 11:56:42,781] Trial 27 finished with value: 0.949793730217608 and parameters: {'n_estimators': 202, 'learning_rate': 0.031582273494047, 'max_depth': 2, 'num_leaves': 6, 'min_child_samples': 94, 'subsample': 0.823349287582101, 'colsample_bytree': 0.7515252959994522, 'reg_alpha': 0.0003409617566037945, 'reg_lambda': 0.0031624743189783704}. Best is trial 27 with value: 0.949793730217608.

Best trial: 27. Best value: 0.949794:   5%|██████                                                                                                          | 27/500 [01:16<23:34,  2.99s/it]

[I 2026-05-19 11:56:44,717] Trial 17 finished with value: 0.9497382887216826 and parameters: {'n_estimators': 294, 'learning_rate': 0.009100382275444109, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 86, 'subsample': 0.7202012886051259, 'colsample_bytree': 0.7764950331580984, 'reg_alpha': 0.00048405997887882376, 'reg_lambda': 0.00030220750262558354}. Best is trial 27 with value: 0.949793730217608.

Best trial: 27. Best value: 0.949794:   6%|██████▎                                                                                                         | 28/500 [01:24<34:28,  4.38s/it]

[I 2026-05-19 11:56:52,367] Trial 15 finished with value: 0.9496404613273075 and parameters: {'n_estimators': 280, 'learning_rate': 0.006700795013664757, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 107, 'subsample': 0.782539392623207, 'colsample_bytree': 0.820546167001561, 'reg_alpha': 1.4356092707772915e-05, 'reg_lambda': 0.8866315418042099}. Best is trial 27 with value: 0.949793730217608.

Best trial: 29. Best value: 0.949806:   6%|██████▍                                                                                                         | 29/500 [01:30<37:20,  4.76s/it]

[I 2026-05-19 11:56:57,999] Trial 29 finished with value: 0.94980619922106 and parameters: {'n_estimators': 215, 'learning_rate': 0.028535109880113773, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 121, 'subsample': 0.9980651288330816, 'colsample_bytree': 0.9223764586012144, 'reg_alpha': 0.04293100748625934, 'reg_lambda': 0.0025178137077217114}. Best is trial 29 with value: 0.94980619922106.
[I 2026-05-19 11:56:58,190] Trial 31 finished with value: 0.9497848358474213 and parameters: {'n_estimators': 200, 'learning_rate': 0.029008987784525087, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 251, 'subsample': 0.7029008356077673, 'colsample_bytree': 0.987620206582187, 'reg_alpha': 51.99805565646769, 'reg_lambda': 0.6984369975766416}. Best is trial 29 with value: 0.94980619922106.

Best trial: 29. Best value: 0.949806:   6%|██████▉                                                                                                         | 31/500 [01:36<33:59,  4.35s/it]

[I 2026-05-19 11:57:04,791] Trial 30 finished with value: 0.9497947565058554 and parameters: {'n_estimators': 239, 'learning_rate': 0.02816754404400437, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 65, 'subsample': 0.989019417587195, 'colsample_bytree': 0.9871782569004415, 'reg_alpha': 55.025210353505706, 'reg_lambda': 0.0015918696011746677}. Best is trial 29 with value: 0.94980619922106.

Best trial: 29. Best value: 0.949806:   6%|███████▏                                                                                                        | 32/500 [01:37<24:35,  3.15s/it]

[I 2026-05-19 11:57:05,122] Trial 20 finished with value: 0.949648176612723 and parameters: {'n_estimators': 283, 'learning_rate': 0.006018438108315271, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 232, 'subsample': 0.8870554765813405, 'colsample_bytree': 0.7760265887546406, 'reg_alpha': 0.01663081407574041, 'reg_lambda': 1.0087997099492494}. Best is trial 29 with value: 0.94980619922106.

Best trial: 32. Best value: 0.949816:   7%|███████▍                                                                                                        | 33/500 [01:41<26:27,  3.40s/it]

[I 2026-05-19 11:57:09,108] Trial 32 finished with value: 0.949815559115508 and parameters: {'n_estimators': 249, 'learning_rate': 0.027337856248203445, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 239, 'subsample': 0.7165416533027622, 'colsample_bytree': 0.9889703267471787, 'reg_alpha': 0.1289512935873026, 'reg_lambda': 0.42646989613454284}. Best is trial 32 with value: 0.949815559115508.

Best trial: 32. Best value: 0.949816:   7%|███████▌                                                                                                        | 34/500 [01:47<33:39,  4.33s/it]

[I 2026-05-19 11:57:15,638] Trial 33 finished with value: 0.9498068851610295 and parameters: {'n_estimators': 224, 'learning_rate': 0.029103665659826007, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 239, 'subsample': 0.7673679728702881, 'colsample_bytree': 0.9977994314758744, 'reg_alpha': 28.111895599530758, 'reg_lambda': 8.82714720422068e-05}. Best is trial 32 with value: 0.949815559115508.

Best trial: 32. Best value: 0.949816:   7%|███████▊                                                                                                        | 35/500 [01:49<28:09,  3.63s/it]

[I 2026-05-19 11:57:17,628] Trial 34 finished with value: 0.9497946608731986 and parameters: {'n_estimators': 228, 'learning_rate': 0.02624144023042733, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 237, 'subsample': 0.9737721108622663, 'colsample_bytree': 0.9875754062039298, 'reg_alpha': 42.808786234887584, 'reg_lambda': 0.36564002144552066}. Best is trial 32 with value: 0.949815559115508.

Best trial: 32. Best value: 0.949816:   7%|████████                                                                                                        | 36/500 [01:56<34:54,  4.51s/it]

[I 2026-05-19 11:57:24,179] Trial 35 finished with value: 0.9498116241202597 and parameters: {'n_estimators': 246, 'learning_rate': 0.029079152399446567, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 253, 'subsample': 0.7882642454552692, 'colsample_bytree': 0.686781099887778, 'reg_alpha': 0.006259839681686245, 'reg_lambda': 0.3701838027376907}. Best is trial 32 with value: 0.949815559115508.

Best trial: 32. Best value: 0.949816:   7%|████████▎                                                                                                       | 37/500 [02:03<40:54,  5.30s/it]

[I 2026-05-19 11:57:31,352] Trial 36 finished with value: 0.9498074531854039 and parameters: {'n_estimators': 247, 'learning_rate': 0.030686969379889243, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 232, 'subsample': 0.7827520231995377, 'colsample_bytree': 0.9863028238050613, 'reg_alpha': 51.13771186742148, 'reg_lambda': 7.128164685236365e-05}. Best is trial 32 with value: 0.949815559115508.

Best trial: 37. Best value: 0.949816:   8%|████████▌                                                                                                       | 38/500 [02:05<33:02,  4.29s/it]

[I 2026-05-19 11:57:33,259] Trial 37 finished with value: 0.9498164854344939 and parameters: {'n_estimators': 249, 'learning_rate': 0.027616028373538392, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 235, 'subsample': 0.7837390385486895, 'colsample_bytree': 0.9977526940726282, 'reg_alpha': 0.004096629505492698, 'reg_lambda': 0.00012694363996528207}. Best is trial 37 with value: 0.9498164854344939.

Best trial: 37. Best value: 0.949816:   8%|████████▋                                                                                                       | 39/500 [02:09<31:32,  4.11s/it]

[I 2026-05-19 11:57:36,947] Trial 38 finished with value: 0.9498151517961082 and parameters: {'n_estimators': 248, 'learning_rate': 0.027491541163871872, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 230, 'subsample': 0.7827116247854192, 'colsample_bytree': 0.9817815608669176, 'reg_alpha': 0.007730785824842646, 'reg_lambda': 0.00010466351964615834}. Best is trial 37 with value: 0.9498164854344939.

Best trial: 39. Best value: 0.949817:   8%|████████▉                                                                                                       | 40/500 [02:12<30:46,  4.01s/it]

[I 2026-05-19 11:57:40,744] Trial 39 finished with value: 0.949816708627672 and parameters: {'n_estimators': 233, 'learning_rate': 0.0293196220777451, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 225, 'subsample': 0.8405176651622067, 'colsample_bytree': 0.9860121017566486, 'reg_alpha': 0.0035207592535832673, 'reg_lambda': 8.755719615830252e-05}. Best is trial 39 with value: 0.949816708627672.

Best trial: 39. Best value: 0.949817:   8%|█████████▏                                                                                                      | 41/500 [02:22<43:44,  5.72s/it]

[I 2026-05-19 11:57:50,432] Trial 40 finished with value: 0.949806369965985 and parameters: {'n_estimators': 244, 'learning_rate': 0.025422253916044548, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 211, 'subsample': 0.9489885693646485, 'colsample_bytree': 0.8572785222888135, 'reg_alpha': 0.00875955723181569, 'reg_lambda': 9.488912938144621e-05}. Best is trial 39 with value: 0.949816708627672.

Best trial: 39. Best value: 0.949817:   8%|█████████▍                                                                                                      | 42/500 [02:24<34:13,  4.48s/it]

[I 2026-05-19 11:57:52,029] Trial 41 finished with value: 0.9497960806585661 and parameters: {'n_estimators': 241, 'learning_rate': 0.022707240769089972, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 206, 'subsample': 0.9614143569990858, 'colsample_bytree': 0.850202417236924, 'reg_alpha': 0.005690470549273388, 'reg_lambda': 0.00010010307617769393}. Best is trial 39 with value: 0.949816708627672.

Best trial: 39. Best value: 0.949817:   9%|█████████▋                                                                                                      | 43/500 [02:28<34:44,  4.56s/it]

[I 2026-05-19 11:57:56,780] Trial 43 finished with value: 0.9498029081922477 and parameters: {'n_estimators': 244, 'learning_rate': 0.023365085986420793, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 52, 'subsample': 0.9631142624619444, 'colsample_bytree': 0.9875745909084389, 'reg_alpha': 0.0026373011847681633, 'reg_lambda': 6.103021720900597e-05}. Best is trial 39 with value: 0.949816708627672.

Best trial: 39. Best value: 0.949817:   9%|█████████▊                                                                                                      | 44/500 [02:30<27:12,  3.58s/it]

[I 2026-05-19 11:57:58,073] Trial 42 finished with value: 0.9498006440757518 and parameters: {'n_estimators': 242, 'learning_rate': 0.023136825823848912, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 42, 'subsample': 0.9596504622585016, 'colsample_bytree': 0.9967648347413156, 'reg_alpha': 0.0043990614710184735, 'reg_lambda': 6.57124761682871e-05}. Best is trial 39 with value: 0.949816708627672.

Best trial: 39. Best value: 0.949817:   9%|██████████                                                                                                      | 45/500 [02:32<24:14,  3.20s/it]

[I 2026-05-19 11:58:00,371] Trial 44 finished with value: 0.9498031103789671 and parameters: {'n_estimators': 240, 'learning_rate': 0.024548452961380873, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 60, 'subsample': 0.9555249458951741, 'colsample_bytree': 0.9931807554875197, 'reg_alpha': 0.13448976567171578, 'reg_lambda': 0.0776683884573116}. Best is trial 39 with value: 0.949816708627672.

Best trial: 39. Best value: 0.949817:   9%|██████████▎                                                                                                     | 46/500 [02:38<30:58,  4.09s/it]

[I 2026-05-19 11:58:06,556] Trial 45 finished with value: 0.9498021277457882 and parameters: {'n_estimators': 240, 'learning_rate': 0.02388028188676832, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 222, 'subsample': 0.9609120993976409, 'colsample_bytree': 0.997456312334744, 'reg_alpha': 13.640559596068167, 'reg_lambda': 6.745718638614389e-05}. Best is trial 39 with value: 0.949816708627672.

Best trial: 39. Best value: 0.949817:   9%|██████████▌                                                                                                     | 47/500 [02:44<35:45,  4.74s/it]

[I 2026-05-19 11:58:12,782] Trial 47 finished with value: 0.9498050634192448 and parameters: {'n_estimators': 250, 'learning_rate': 0.02287726268238179, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 223, 'subsample': 0.7756354511740325, 'colsample_bytree': 0.961151711165727, 'reg_alpha': 0.16763299131145376, 'reg_lambda': 0.06878159344933359}. Best is trial 39 with value: 0.949816708627672.

Best trial: 39. Best value: 0.949817:  10%|██████████▊                                                                                                     | 48/500 [02:46<28:08,  3.74s/it]

[I 2026-05-19 11:58:14,204] Trial 46 finished with value: 0.9498036373235997 and parameters: {'n_estimators': 248, 'learning_rate': 0.0234741401795834, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 63, 'subsample': 0.9599486310379044, 'colsample_bytree': 0.9591028885913664, 'reg_alpha': 10.595326060073322, 'reg_lambda': 0.05404500016990949}. Best is trial 39 with value: 0.949816708627672.

Best trial: 48. Best value: 0.949835:  10%|██████████▉                                                                                                     | 49/500 [02:54<39:00,  5.19s/it]

[I 2026-05-19 11:58:22,785] Trial 48 finished with value: 0.949834923021227 and parameters: {'n_estimators': 258, 'learning_rate': 0.037750279702467686, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 220, 'subsample': 0.7854565594355911, 'colsample_bytree': 0.9656930175321053, 'reg_alpha': 12.022856192287152, 'reg_lambda': 0.08013548223115603}. Best is trial 48 with value: 0.949834923021227.

Best trial: 48. Best value: 0.949835:  10%|███████████▏                                                                                                    | 50/500 [02:58<35:44,  4.77s/it]

[I 2026-05-19 11:58:26,563] Trial 49 finished with value: 0.9497954145001144 and parameters: {'n_estimators': 255, 'learning_rate': 0.0205556699020927, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 218, 'subsample': 0.7874821239854379, 'colsample_bytree': 0.955583276323168, 'reg_alpha': 0.10525181230318269, 'reg_lambda': 6.118780580114077e-05}. Best is trial 48 with value: 0.949834923021227.

Best trial: 50. Best value: 0.949838:  10%|███████████▍                                                                                                    | 51/500 [02:59<27:14,  3.64s/it]

[I 2026-05-19 11:58:27,575] Trial 50 finished with value: 0.9498375281423888 and parameters: {'n_estimators': 262, 'learning_rate': 0.03826762815844372, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 216, 'subsample': 0.6695924477255478, 'colsample_bytree': 0.9533636917964373, 'reg_alpha': 0.13822987257410146, 'reg_lambda': 0.06271951687361824}. Best is trial 50 with value: 0.9498375281423888.

Best trial: 50. Best value: 0.949838:  10%|███████████▋                                                                                                    | 52/500 [03:07<35:56,  4.81s/it]

[I 2026-05-19 11:58:35,126] Trial 51 finished with value: 0.9498086339607127 and parameters: {'n_estimators': 266, 'learning_rate': 0.021951979682397628, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 218, 'subsample': 0.6661483264938848, 'colsample_bytree': 0.964727543101797, 'reg_alpha': 0.2098823559860711, 'reg_lambda': 4.273947084749302e-05}. Best is trial 50 with value: 0.9498375281423888.

Best trial: 50. Best value: 0.949838:  11%|███████████▊                                                                                                    | 53/500 [03:12<35:37,  4.78s/it]

[I 2026-05-19 11:58:39,841] Trial 52 finished with value: 0.9498359204062116 and parameters: {'n_estimators': 260, 'learning_rate': 0.037404900636820795, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 265, 'subsample': 0.8502176495101854, 'colsample_bytree': 0.9534602814989408, 'reg_alpha': 0.0021161731175187264, 'reg_lambda': 0.07868716244585147}. Best is trial 50 with value: 0.9498375281423888.

Best trial: 53. Best value: 0.949838:  11%|████████████                                                                                                    | 54/500 [03:14<31:17,  4.21s/it]

[I 2026-05-19 11:58:42,717] Trial 53 finished with value: 0.9498383006691616 and parameters: {'n_estimators': 261, 'learning_rate': 0.03799849145736934, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 261, 'subsample': 0.6662282738719436, 'colsample_bytree': 0.9611729792198948, 'reg_alpha': 0.10522186852228796, 'reg_lambda': 0.0710429563987613}. Best is trial 53 with value: 0.9498383006691616.

Best trial: 54. Best value: 0.949841:  11%|████████████▎                                                                                                   | 55/500 [03:19<31:01,  4.18s/it]

[I 2026-05-19 11:58:46,833] Trial 54 finished with value: 0.9498406008526 and parameters: {'n_estimators': 268, 'learning_rate': 0.037358918480808925, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 263, 'subsample': 0.8527043484495855, 'colsample_bytree': 0.9501331979623278, 'reg_alpha': 0.0929574667987703, 'reg_lambda': 0.09039238740438278}. Best is trial 54 with value: 0.9498406008526.

Best trial: 54. Best value: 0.949841:  11%|████████████▌                                                                                                   | 56/500 [03:21<28:03,  3.79s/it]

[I 2026-05-19 11:58:49,705] Trial 55 finished with value: 0.9498339503045647 and parameters: {'n_estimators': 264, 'learning_rate': 0.037097745563520995, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 264, 'subsample': 0.8364375246669876, 'colsample_bytree': 0.9510947222987407, 'reg_alpha': 0.10078220185590389, 'reg_lambda': 0.06614921260361992}. Best is trial 54 with value: 0.9498406008526.

Best trial: 54. Best value: 0.949841:  11%|████████████▊                                                                                                   | 57/500 [03:26<30:24,  4.12s/it]

[I 2026-05-19 11:58:54,578] Trial 56 finished with value: 0.949782869456883 and parameters: {'n_estimators': 262, 'learning_rate': 0.01597438447174145, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 273, 'subsample': 0.8389383290519811, 'colsample_bytree': 0.961735950517268, 'reg_alpha': 0.0014258971717754346, 'reg_lambda': 0.049384264361371326}. Best is trial 54 with value: 0.9498406008526.

Best trial: 54. Best value: 0.949841:  12%|████████████▉                                                                                                   | 58/500 [03:29<28:16,  3.84s/it]

[I 2026-05-19 11:58:57,775] Trial 57 finished with value: 0.94983958960282 and parameters: {'n_estimators': 262, 'learning_rate': 0.039046837594562366, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 189, 'subsample': 0.8448994326980488, 'colsample_bytree': 0.9597461238212555, 'reg_alpha': 0.09011117905708349, 'reg_lambda': 0.08138217998489007}. Best is trial 54 with value: 0.9498406008526.

Best trial: 54. Best value: 0.949841:  12%|█████████████▏                                                                                                  | 59/500 [03:34<28:52,  3.93s/it]

[I 2026-05-19 11:59:01,910] Trial 58 finished with value: 0.9498385007181518 and parameters: {'n_estimators': 264, 'learning_rate': 0.037731253158194436, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 266, 'subsample': 0.8425980426686343, 'colsample_bytree': 0.9545025983021888, 'reg_alpha': 0.0019564600621769174, 'reg_lambda': 0.1419383884631101}. Best is trial 54 with value: 0.9498406008526.

Best trial: 54. Best value: 0.949841:  12%|█████████████▍                                                                                                  | 60/500 [03:36<25:35,  3.49s/it]

[I 2026-05-19 11:59:04,358] Trial 59 finished with value: 0.9498336031801978 and parameters: {'n_estimators': 263, 'learning_rate': 0.036977373903298846, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 187, 'subsample': 0.8459410919861622, 'colsample_bytree': 0.9608001822355717, 'reg_alpha': 0.001747560276386084, 'reg_lambda': 0.11842980559285614}. Best is trial 54 with value: 0.9498406008526.

Best trial: 54. Best value: 0.949841:  12%|█████████████▋                                                                                                  | 61/500 [03:43<32:47,  4.48s/it]

[I 2026-05-19 11:59:11,158] Trial 61 finished with value: 0.9498326256941152 and parameters: {'n_estimators': 181, 'learning_rate': 0.037119779953110145, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 191, 'subsample': 0.843884564009291, 'colsample_bytree': 0.9020763970062262, 'reg_alpha': 0.0015727024679670159, 'reg_lambda': 0.015039880493293155}. Best is trial 54 with value: 0.9498406008526.

Best trial: 54. Best value: 0.949841:  12%|█████████████▉                                                                                                  | 62/500 [03:50<38:52,  5.33s/it]

[I 2026-05-19 11:59:18,464] Trial 62 finished with value: 0.9498343606536434 and parameters: {'n_estimators': 264, 'learning_rate': 0.0365749359589184, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 265, 'subsample': 0.6595570307152332, 'colsample_bytree': 0.8924193917461394, 'reg_alpha': 0.0015943172652961904, 'reg_lambda': 0.00697535891062253}. Best is trial 54 with value: 0.9498406008526.

Best trial: 64. Best value: 0.949841:  13%|██████████████                                                                                                  | 63/500 [03:55<37:42,  5.18s/it]

[I 2026-05-19 11:59:23,297] Trial 64 finished with value: 0.9498408306370484 and parameters: {'n_estimators': 180, 'learning_rate': 0.03800723902838996, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 193, 'subsample': 0.6300636986955686, 'colsample_bytree': 0.9030794170215132, 'reg_alpha': 2.608202263883268, 'reg_lambda': 0.12758152262808722}. Best is trial 64 with value: 0.9498408306370484.

Best trial: 60. Best value: 0.94985:  13%|██████████████▍                                                                                                  | 64/500 [03:56<29:34,  4.07s/it]

[I 2026-05-19 11:59:24,799] Trial 60 finished with value: 0.9498495947015613 and parameters: {'n_estimators': 271, 'learning_rate': 0.036736692083550584, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 186, 'subsample': 0.8475010424342048, 'colsample_bytree': 0.903025949563114, 'reg_alpha': 0.0014433673113329838, 'reg_lambda': 0.0006406294817747162}. Best is trial 60 with value: 0.9498495947015613.

Best trial: 60. Best value: 0.94985:  13%|██████████████▋                                                                                                  | 65/500 [04:01<29:25,  4.06s/it]

[I 2026-05-19 11:59:28,812] Trial 63 finished with value: 0.9498340177752418 and parameters: {'n_estimators': 267, 'learning_rate': 0.03790157364614373, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 191, 'subsample': 0.8393373562330932, 'colsample_bytree': 0.9094601845796934, 'reg_alpha': 0.0013009925121108346, 'reg_lambda': 0.000832386684755492}. Best is trial 60 with value: 0.9498495947015613.

Best trial: 60. Best value: 0.94985:  13%|███████████████▏                                                                                                 | 67/500 [04:15<35:53,  4.97s/it]

[I 2026-05-19 11:59:42,847] Trial 70 finished with value: 0.9498462875677562 and parameters: {'n_estimators': 181, 'learning_rate': 0.03963112620315666, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 189, 'subsample': 0.8579002009329788, 'colsample_bytree': 0.903807342731787, 'reg_alpha': 1.1117405531249955, 'reg_lambda': 0.14539723769107413}. Best is trial 60 with value: 0.9498495947015613.
[I 2026-05-19 11:59:42,980] Trial 65 finished with value: 0.9498465294084099 and parameters: {'n_estimators': 266, 'learning_rate': 0.03883385638710274, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 272, 'subsample': 0.8434064904938308, 'colsample_bytree': 0.9370054731371883, 'reg_alpha': 0.001058214504727223, 'reg_lambda': 0.14566619067504996}. Best is trial 60 with value: 0.9498495947015613.

Best trial: 66. Best value: 0.949856:  14%|███████████████▏                                                                                                | 68/500 [04:17<29:06,  4.04s/it]

[I 2026-05-19 11:59:44,852] Trial 66 finished with value: 0.9498560081759004 and parameters: {'n_estimators': 267, 'learning_rate': 0.03791874607921399, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 269, 'subsample': 0.8396560233801379, 'colsample_bytree': 0.9008506240922624, 'reg_alpha': 1.724362409048631, 'reg_lambda': 0.009194278961267408}. Best is trial 66 with value: 0.9498560081759004.

Best trial: 66. Best value: 0.949856:  14%|███████████████▍                                                                                                | 69/500 [04:17<21:36,  3.01s/it]

[I 2026-05-19 11:59:45,433] Trial 67 finished with value: 0.949842698937006 and parameters: {'n_estimators': 266, 'learning_rate': 0.0379364305748502, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 268, 'subsample': 0.6313452612420025, 'colsample_bytree': 0.8998208864547326, 'reg_alpha': 1.5913694294057505, 'reg_lambda': 0.16434804997954447}. Best is trial 66 with value: 0.9498560081759004.

Best trial: 66. Best value: 0.949856:  14%|███████████████▋                                                                                                | 70/500 [04:23<27:29,  3.84s/it]

[I 2026-05-19 11:59:51,207] Trial 69 finished with value: 0.9498484258990659 and parameters: {'n_estimators': 274, 'learning_rate': 0.038960116986462914, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 186, 'subsample': 0.6172122486732095, 'colsample_bytree': 0.8893973014102312, 'reg_alpha': 1.3570531406545812, 'reg_lambda': 0.14959405048342134}. Best is trial 66 with value: 0.9498560081759004.

Best trial: 66. Best value: 0.949856:  14%|███████████████▉                                                                                                | 71/500 [04:28<30:09,  4.22s/it]

[I 2026-05-19 11:59:56,314] Trial 68 finished with value: 0.9498526821157126 and parameters: {'n_estimators': 269, 'learning_rate': 0.03694098271135333, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 187, 'subsample': 0.86115166901403, 'colsample_bytree': 0.9016084481171991, 'reg_alpha': 1.1518677437313927, 'reg_lambda': 0.14055862344889156}. Best is trial 66 with value: 0.9498560081759004.

Best trial: 66. Best value: 0.949856:  14%|████████████████▏                                                                                               | 72/500 [04:32<30:28,  4.27s/it]

[I 2026-05-19 12:00:00,730] Trial 71 finished with value: 0.9498391973145732 and parameters: {'n_estimators': 275, 'learning_rate': 0.03878237701908308, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 296, 'subsample': 0.8618094771383221, 'colsample_bytree': 0.8892405581282771, 'reg_alpha': 0.3913194768003136, 'reg_lambda': 0.006974940376968473}. Best is trial 66 with value: 0.9498560081759004.

Best trial: 66. Best value: 0.949856:  15%|████████████████▎                                                                                               | 73/500 [04:38<33:24,  4.69s/it]

[I 2026-05-19 12:00:06,399] Trial 72 finished with value: 0.9498401179350264 and parameters: {'n_estimators': 273, 'learning_rate': 0.04138938263267117, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 269, 'subsample': 0.6200506004904857, 'colsample_bytree': 0.938091325562252, 'reg_alpha': 1.4349938724369284, 'reg_lambda': 0.02349546364607762}. Best is trial 66 with value: 0.9498560081759004.

Best trial: 66. Best value: 0.949856:  15%|████████████████▌                                                                                               | 74/500 [04:49<45:52,  6.46s/it]

[I 2026-05-19 12:00:16,988] Trial 73 finished with value: 0.9498529557440346 and parameters: {'n_estimators': 286, 'learning_rate': 0.039173687657211784, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 170, 'subsample': 0.61017811908868, 'colsample_bytree': 0.9352668524100586, 'reg_alpha': 1.1630809331807737, 'reg_lambda': 0.15572046856943839}. Best is trial 66 with value: 0.9498560081759004.

Best trial: 66. Best value: 0.949856:  15%|████████████████▊                                                                                               | 75/500 [04:51<36:01,  5.09s/it]

[I 2026-05-19 12:00:18,853] Trial 74 finished with value: 0.9498526595126251 and parameters: {'n_estimators': 276, 'learning_rate': 0.04143717587941413, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 152, 'subsample': 0.6136897858324519, 'colsample_bytree': 0.9371147949695735, 'reg_alpha': 1.4526281431983208, 'reg_lambda': 0.02933541535112129}. Best is trial 66 with value: 0.9498560081759004.

Best trial: 66. Best value: 0.949856:  15%|█████████████████                                                                                               | 76/500 [04:55<35:26,  5.02s/it]

[I 2026-05-19 12:00:23,716] Trial 76 finished with value: 0.9498489477968226 and parameters: {'n_estimators': 288, 'learning_rate': 0.040286517744415676, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 150, 'subsample': 0.6071532045918131, 'colsample_bytree': 0.9363210764467967, 'reg_alpha': 1.2000010776824024, 'reg_lambda': 0.16392106989118654}. Best is trial 66 with value: 0.9498560081759004.

Best trial: 66. Best value: 0.949856:  15%|█████████████████▏                                                                                              | 77/500 [04:56<26:36,  3.77s/it]

[I 2026-05-19 12:00:24,586] Trial 75 finished with value: 0.949849470867238 and parameters: {'n_estimators': 285, 'learning_rate': 0.04224418154623035, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 159, 'subsample': 0.6161773799885911, 'colsample_bytree': 0.9370974242506684, 'reg_alpha': 1.4564031696846869, 'reg_lambda': 0.027034160600378145}. Best is trial 66 with value: 0.9498560081759004.

Best trial: 77. Best value: 0.949857:  16%|█████████████████▍                                                                                              | 78/500 [05:13<52:50,  7.51s/it]

[I 2026-05-19 12:00:40,828] Trial 77 finished with value: 0.9498572242339147 and parameters: {'n_estimators': 287, 'learning_rate': 0.04123183085835536, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 156, 'subsample': 0.6001788389702288, 'colsample_bytree': 0.9279515107354128, 'reg_alpha': 1.035313379136549, 'reg_lambda': 0.02956591539811252}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  16%|█████████████████▋                                                                                              | 79/500 [05:14<39:12,  5.59s/it]

[I 2026-05-19 12:00:41,895] Trial 80 finished with value: 0.9498487869038197 and parameters: {'n_estimators': 288, 'learning_rate': 0.04188323754381262, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 293, 'subsample': 0.6160306253333445, 'colsample_bytree': 0.9343529277955835, 'reg_alpha': 1.9310575726210293, 'reg_lambda': 0.032021082664559344}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  16%|█████████████████▉                                                                                              | 80/500 [05:14<28:32,  4.08s/it]

[I 2026-05-19 12:00:42,474] Trial 78 finished with value: 0.9498492973186368 and parameters: {'n_estimators': 287, 'learning_rate': 0.04194190352716948, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 167, 'subsample': 0.8704892976243466, 'colsample_bytree': 0.8748915655037738, 'reg_alpha': 1.3352872199139483, 'reg_lambda': 0.15251148541652218}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  16%|██████████████████▏                                                                                             | 81/500 [05:19<30:18,  4.34s/it]

[I 2026-05-19 12:00:47,402] Trial 81 finished with value: 0.9498510991427993 and parameters: {'n_estimators': 289, 'learning_rate': 0.03360483552433568, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 155, 'subsample': 0.620047552932672, 'colsample_bytree': 0.8719605009893739, 'reg_alpha': 1.5311536303456619, 'reg_lambda': 0.02475326171959843}. Best is trial 77 with value: 0.9498572242339147.
[I 2026-05-19 12:00:47,448] Trial 79 finished with value: 0.9498489808062208 and parameters: {'n_estimators': 284, 'learning_rate': 0.04359936712178826, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 160, 'subsample': 0.8690643154318003, 'colsample_bytree': 0.9330801662233046, 'reg_alpha': 1.1742055118317551, 'reg_lambda': 0.029727917225411633}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  17%|██████████████████▊                                                                                             | 84/500 [05:28<22:25,  3.23s/it]

[I 2026-05-19 12:00:55,740] Trial 83 finished with value: 0.949844598418157 and parameters: {'n_estimators': 287, 'learning_rate': 0.04252705933509986, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 156, 'subsample': 0.6168046841236847, 'colsample_bytree': 0.8729552137389535, 'reg_alpha': 1.501958193853197, 'reg_lambda': 0.03224424777514146}. Best is trial 77 with value: 0.9498572242339147.
[I 2026-05-19 12:00:55,862] Trial 82 finished with value: 0.9498488880058696 and parameters: {'n_estimators': 287, 'learning_rate': 0.04193156591895203, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 160, 'subsample': 0.6127483786064961, 'colsample_bytree': 0.8738578278642837, 'reg_alpha': 1.7320762865135806, 'reg_lambda': 0.026882497642165475}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  17%|███████████████████                                                                                             | 85/500 [05:35<30:26,  4.40s/it]

[I 2026-05-19 12:01:03,576] Trial 84 finished with value: 0.949846991022428 and parameters: {'n_estimators': 293, 'learning_rate': 0.03340130715607396, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 154, 'subsample': 0.6000848821834679, 'colsample_bytree': 0.8673863945072031, 'reg_alpha': 2.399285514267021, 'reg_lambda': 1.1956574296951623}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  17%|███████████████████▎                                                                                            | 86/500 [05:43<36:05,  5.23s/it]

[I 2026-05-19 12:01:11,023] Trial 85 finished with value: 0.9498530751859159 and parameters: {'n_estimators': 289, 'learning_rate': 0.04438325649330381, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 158, 'subsample': 0.6077109128919075, 'colsample_bytree': 0.8702272234593975, 'reg_alpha': 1.4709662871818154, 'reg_lambda': 1.6167778462912605}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  17%|███████████████████▍                                                                                            | 87/500 [05:51<41:56,  6.09s/it]

[I 2026-05-19 12:01:19,323] Trial 88 finished with value: 0.9498415011722636 and parameters: {'n_estimators': 287, 'learning_rate': 0.03384014137289433, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 154, 'subsample': 0.615893800585519, 'colsample_bytree': 0.8700340600186708, 'reg_alpha': 5.484981256198771, 'reg_lambda': 1.4583570398099368}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  18%|███████████████████▋                                                                                            | 88/500 [05:52<31:07,  4.53s/it]

[I 2026-05-19 12:01:19,963] Trial 86 finished with value: 0.9498505274772985 and parameters: {'n_estimators': 292, 'learning_rate': 0.03358188982671058, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 158, 'subsample': 0.8750354706408985, 'colsample_bytree': 0.8748404128795778, 'reg_alpha': 0.8530613180734453, 'reg_lambda': 2.678362585392128}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  18%|███████████████████▉                                                                                            | 89/500 [05:55<27:44,  4.05s/it]

[I 2026-05-19 12:01:22,833] Trial 87 finished with value: 0.9498520508998783 and parameters: {'n_estimators': 286, 'learning_rate': 0.03340312655799489, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 150, 'subsample': 0.6019878301409637, 'colsample_bytree': 0.9212221445013191, 'reg_alpha': 4.7207760139019355, 'reg_lambda': 1.982116617131212}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  18%|████████████████████▏                                                                                           | 90/500 [06:10<50:14,  7.35s/it]

[I 2026-05-19 12:01:38,170] Trial 90 finished with value: 0.9498438283292148 and parameters: {'n_estimators': 298, 'learning_rate': 0.03340150074141417, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 155, 'subsample': 0.6005036384359379, 'colsample_bytree': 0.8711477410688001, 'reg_alpha': 4.333969593160378, 'reg_lambda': 0.005087297135707243}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  18%|████████████████████▍                                                                                           | 91/500 [06:10<36:12,  5.31s/it]

[I 2026-05-19 12:01:38,590] Trial 91 finished with value: 0.9498435902637585 and parameters: {'n_estimators': 284, 'learning_rate': 0.033792737879912424, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 167, 'subsample': 0.907624575763222, 'colsample_bytree': 0.9147813435942629, 'reg_alpha': 4.108491905885856, 'reg_lambda': 2.425234640245055}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  18%|████████████████████▌                                                                                           | 92/500 [06:15<34:04,  5.01s/it]

[I 2026-05-19 12:01:42,879] Trial 89 finished with value: 0.9498496829635126 and parameters: {'n_estimators': 290, 'learning_rate': 0.04252764143782733, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 157, 'subsample': 0.6042001840475005, 'colsample_bytree': 0.8718314993926557, 'reg_alpha': 4.257208300344852, 'reg_lambda': 0.03479883957680922}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  19%|████████████████████▊                                                                                           | 93/500 [06:17<29:27,  4.34s/it]

[I 2026-05-19 12:01:45,650] Trial 92 finished with value: 0.9498428053016459 and parameters: {'n_estimators': 297, 'learning_rate': 0.03406382551532755, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 165, 'subsample': 0.9144459435092347, 'colsample_bytree': 0.8723139873444204, 'reg_alpha': 4.992156273874763, 'reg_lambda': 0.006253867643908145}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  19%|█████████████████████                                                                                           | 94/500 [06:20<25:31,  3.77s/it]

[I 2026-05-19 12:01:48,087] Trial 93 finished with value: 0.9498496768695169 and parameters: {'n_estimators': 297, 'learning_rate': 0.033585443540703794, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 172, 'subsample': 0.6501173989750769, 'colsample_bytree': 0.8776066364776453, 'reg_alpha': 5.16275919643594, 'reg_lambda': 0.007420453378213823}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  19%|█████████████████████▎                                                                                          | 95/500 [06:23<24:36,  3.64s/it]

[I 2026-05-19 12:01:51,429] Trial 95 finished with value: 0.9498399717308532 and parameters: {'n_estimators': 280, 'learning_rate': 0.03303573732806074, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 170, 'subsample': 0.6428684103684915, 'colsample_bytree': 0.9171450717817672, 'reg_alpha': 5.048015809697717, 'reg_lambda': 0.00962733277501065}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  19%|█████████████████████▌                                                                                          | 96/500 [06:26<23:16,  3.46s/it]

[I 2026-05-19 12:01:54,442] Trial 94 finished with value: 0.9498457387656993 and parameters: {'n_estimators': 297, 'learning_rate': 0.03349421305635763, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 174, 'subsample': 0.6499985379504486, 'colsample_bytree': 0.9168967928933411, 'reg_alpha': 5.465797418623717, 'reg_lambda': 0.008967494921963649}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  19%|█████████████████████▋                                                                                          | 97/500 [06:32<28:22,  4.22s/it]

[I 2026-05-19 12:02:00,465] Trial 96 finished with value: 0.9498452456276787 and parameters: {'n_estimators': 300, 'learning_rate': 0.03445137564053961, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 171, 'subsample': 0.6432022506144265, 'colsample_bytree': 0.9156564044914398, 'reg_alpha': 4.623150421567011, 'reg_lambda': 0.008476176938571877}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  20%|█████████████████████▉                                                                                          | 98/500 [06:42<39:22,  5.88s/it]

[I 2026-05-19 12:02:10,209] Trial 97 finished with value: 0.9498446107122644 and parameters: {'n_estimators': 300, 'learning_rate': 0.03424568724422916, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 126, 'subsample': 0.6465579389263036, 'colsample_bytree': 0.9189008902484214, 'reg_alpha': 5.853417421290437, 'reg_lambda': 0.008024746089314066}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  20%|██████████████████████▏                                                                                         | 99/500 [06:46<35:07,  5.26s/it]

[I 2026-05-19 12:02:13,994] Trial 98 finished with value: 0.9498452776335551 and parameters: {'n_estimators': 298, 'learning_rate': 0.04696034700199459, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 135, 'subsample': 0.643992262684324, 'colsample_bytree': 0.9174908810541526, 'reg_alpha': 0.6377527495333947, 'reg_lambda': 0.005487505982628535}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  20%|██████████████████████▏                                                                                        | 100/500 [06:51<34:54,  5.24s/it]

[I 2026-05-19 12:02:19,196] Trial 99 finished with value: 0.9498407562513786 and parameters: {'n_estimators': 300, 'learning_rate': 0.033268552733121015, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 129, 'subsample': 0.6414696411263562, 'colsample_bytree': 0.9157089974157294, 'reg_alpha': 0.6451574562611552, 'reg_lambda': 8.38457650623908}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  20%|██████████████████████▍                                                                                        | 101/500 [06:52<26:36,  4.00s/it]

[I 2026-05-19 12:02:20,322] Trial 100 finished with value: 0.9498405188708657 and parameters: {'n_estimators': 300, 'learning_rate': 0.03326526022070593, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 134, 'subsample': 0.6473846199286536, 'colsample_bytree': 0.9200770492446171, 'reg_alpha': 0.6457280439628704, 'reg_lambda': 15.725662981881303}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  20%|██████████████████████▋                                                                                        | 102/500 [07:03<40:30,  6.11s/it]

[I 2026-05-19 12:02:31,333] Trial 101 finished with value: 0.9498502880579001 and parameters: {'n_estimators': 299, 'learning_rate': 0.045773379874282115, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 133, 'subsample': 0.9204184786805599, 'colsample_bytree': 0.8327816298711692, 'reg_alpha': 0.47203278558357287, 'reg_lambda': 4.674188723997853}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  21%|███████████████████████                                                                                        | 104/500 [07:10<29:45,  4.51s/it]

[I 2026-05-19 12:02:38,299] Trial 105 finished with value: 0.9498508558244276 and parameters: {'n_estimators': 277, 'learning_rate': 0.04590343013346809, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 135, 'subsample': 0.6401023017823652, 'colsample_bytree': 0.8393360382466937, 'reg_alpha': 0.6612323273704496, 'reg_lambda': 3.0190999965057}. Best is trial 77 with value: 0.9498572242339147.
[I 2026-05-19 12:02:38,489] Trial 102 finished with value: 0.9498499029403462 and parameters: {'n_estimators': 297, 'learning_rate': 0.04603551325786833, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 136, 'subsample': 0.647372845387765, 'colsample_bytree': 0.8332786517118096, 'reg_alpha': 0.6979478497668489, 'reg_lambda': 3.0366227755523756}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  21%|███████████████████████▎                                                                                       | 105/500 [07:13<25:44,  3.91s/it]

[I 2026-05-19 12:02:41,004] Trial 104 finished with value: 0.9498437825602878 and parameters: {'n_estimators': 278, 'learning_rate': 0.03136744378936456, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 134, 'subsample': 0.649636151459616, 'colsample_bytree': 0.8346504565981926, 'reg_alpha': 0.6663581266428333, 'reg_lambda': 5.064264365194693}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  21%|███████████████████████▌                                                                                       | 106/500 [07:13<19:25,  2.96s/it]

[I 2026-05-19 12:02:41,732] Trial 103 finished with value: 0.9498556016904789 and parameters: {'n_estimators': 296, 'learning_rate': 0.04594330370547795, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 129, 'subsample': 0.8820801137575461, 'colsample_bytree': 0.8335612058723488, 'reg_alpha': 0.6018237246991995, 'reg_lambda': 5.5339545161450285}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  21%|███████████████████████▊                                                                                       | 107/500 [07:15<16:30,  2.52s/it]

[I 2026-05-19 12:02:43,221] Trial 110 finished with value: 0.9497819220869868 and parameters: {'n_estimators': 277, 'learning_rate': 0.04805699707289155, 'max_depth': 1, 'num_leaves': 8, 'min_child_samples': 145, 'subsample': 0.6298135278304428, 'colsample_bytree': 0.8373775254311792, 'reg_alpha': 0.31004141712161504, 'reg_lambda': 9.64376545115914}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  22%|███████████████████████▉                                                                                       | 108/500 [07:18<18:03,  2.76s/it]

[I 2026-05-19 12:02:46,566] Trial 106 finished with value: 0.9498473362861727 and parameters: {'n_estimators': 277, 'learning_rate': 0.04587710075715781, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 135, 'subsample': 0.6302864978053623, 'colsample_bytree': 0.834407688000509, 'reg_alpha': 0.7301458945491675, 'reg_lambda': 5.968621056073225}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  22%|████████████████████████▏                                                                                      | 109/500 [07:21<17:18,  2.66s/it]

[I 2026-05-19 12:02:48,976] Trial 107 finished with value: 0.949853617729359 and parameters: {'n_estimators': 279, 'learning_rate': 0.04639934695512304, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 133, 'subsample': 0.6312061194400417, 'colsample_bytree': 0.8334873165595564, 'reg_alpha': 0.702536198017194, 'reg_lambda': 6.797938001061033}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  22%|████████████████████████▍                                                                                      | 110/500 [07:27<23:57,  3.69s/it]

[I 2026-05-19 12:02:55,053] Trial 108 finished with value: 0.9498497596605967 and parameters: {'n_estimators': 278, 'learning_rate': 0.046374242002169094, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 137, 'subsample': 0.633886108209508, 'colsample_bytree': 0.8434164653611076, 'reg_alpha': 0.6744621630585135, 'reg_lambda': 6.5842543581202415}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  22%|████████████████████████▋                                                                                      | 111/500 [07:41<44:17,  6.83s/it]

[I 2026-05-19 12:03:09,236] Trial 109 finished with value: 0.9498519566416699 and parameters: {'n_estimators': 278, 'learning_rate': 0.04582332263539889, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 142, 'subsample': 0.6296096606067699, 'colsample_bytree': 0.858115690443798, 'reg_alpha': 0.731216054447945, 'reg_lambda': 7.0118685667643605}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  22%|████████████████████████▊                                                                                      | 112/500 [07:45<38:41,  5.98s/it]

[I 2026-05-19 12:03:13,238] Trial 116 finished with value: 0.9497822195953869 and parameters: {'n_estimators': 277, 'learning_rate': 0.04520599473874751, 'max_depth': 1, 'num_leaves': 6, 'min_child_samples': 145, 'subsample': 0.628012115657612, 'colsample_bytree': 0.8572679246520812, 'reg_alpha': 0.31139662223379966, 'reg_lambda': 0.6196711564429251}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  23%|█████████████████████████▎                                                                                     | 114/500 [07:46<19:54,  3.09s/it]

[I 2026-05-19 12:03:13,744] Trial 117 finished with value: 0.9497867918577747 and parameters: {'n_estimators': 278, 'learning_rate': 0.04529875852369878, 'max_depth': 1, 'num_leaves': 8, 'min_child_samples': 144, 'subsample': 0.6281712879368513, 'colsample_bytree': 0.8603977213585182, 'reg_alpha': 0.2598977373929385, 'reg_lambda': 0.6117119959898083}. Best is trial 77 with value: 0.9498572242339147.
[I 2026-05-19 12:03:13,918] Trial 111 finished with value: 0.9498542856621729 and parameters: {'n_estimators': 277, 'learning_rate': 0.04584359821532682, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 145, 'subsample': 0.6270539492745317, 'colsample_bytree': 0.8342680024733049, 'reg_alpha': 0.355407183140022, 'reg_lambda': 4.518792402161453}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  23%|█████████████████████████▌                                                                                     | 115/500 [07:49<20:54,  3.26s/it]

[I 2026-05-19 12:03:17,575] Trial 112 finished with value: 0.9498470144943919 and parameters: {'n_estimators': 277, 'learning_rate': 0.04515432653320218, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 179, 'subsample': 0.6278891298287049, 'colsample_bytree': 0.8541176613081173, 'reg_alpha': 0.28077951685246477, 'reg_lambda': 3.864581029607589}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  23%|█████████████████████████▊                                                                                     | 116/500 [07:50<16:51,  2.63s/it]

[I 2026-05-19 12:03:18,745] Trial 119 finished with value: 0.9498229192834028 and parameters: {'n_estimators': 135, 'learning_rate': 0.049893801361705466, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 109, 'subsample': 0.880659356871687, 'colsample_bytree': 0.8019506225663054, 'reg_alpha': 0.2688292305503008, 'reg_lambda': 82.00222008260658}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  23%|█████████████████████████▉                                                                                     | 117/500 [07:59<29:04,  4.55s/it]

[I 2026-05-19 12:03:27,785] Trial 113 finished with value: 0.9498531063306377 and parameters: {'n_estimators': 280, 'learning_rate': 0.04542586167659443, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 147, 'subsample': 0.6346651091332985, 'colsample_bytree': 0.8383644928901928, 'reg_alpha': 0.3724042042726925, 'reg_lambda': 4.218678650566919}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  24%|██████████████████████████▏                                                                                    | 118/500 [08:04<29:27,  4.63s/it]

[I 2026-05-19 12:03:32,572] Trial 114 finished with value: 0.9498547816157465 and parameters: {'n_estimators': 276, 'learning_rate': 0.04677072382464166, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 144, 'subsample': 0.631523198747565, 'colsample_bytree': 0.83089113855011, 'reg_alpha': 0.3674849031815909, 'reg_lambda': 4.022491617277759}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  24%|██████████████████████████▍                                                                                    | 119/500 [08:06<24:38,  3.88s/it]

[I 2026-05-19 12:03:34,725] Trial 115 finished with value: 0.949851780769146 and parameters: {'n_estimators': 278, 'learning_rate': 0.04902766390888547, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 145, 'subsample': 0.9340512133607796, 'colsample_bytree': 0.8026643589994007, 'reg_alpha': 0.30237095466230923, 'reg_lambda': 4.013031653579274}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 77. Best value: 0.949857:  24%|██████████████████████████▋                                                                                    | 120/500 [08:10<24:25,  3.86s/it]

[I 2026-05-19 12:03:38,515] Trial 118 finished with value: 0.9498294775936682 and parameters: {'n_estimators': 255, 'learning_rate': 0.030371552799715044, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 113, 'subsample': 0.8795432594130245, 'colsample_bytree': 0.8622869328925257, 'reg_alpha': 2.858728464729611, 'reg_lambda': 67.89274957289707}. Best is trial 77 with value: 0.9498572242339147.

Best trial: 120. Best value: 0.949859:  24%|██████████████████████████▌                                                                                   | 121/500 [08:13<23:06,  3.66s/it]

[I 2026-05-19 12:03:41,694] Trial 120 finished with value: 0.9498586427315591 and parameters: {'n_estimators': 254, 'learning_rate': 0.04920765800680236, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 108, 'subsample': 0.6267189339262024, 'colsample_bytree': 0.8545656534290379, 'reg_alpha': 2.907780777969208, 'reg_lambda': 43.24248067157213}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  24%|██████████████████████████▊                                                                                   | 122/500 [08:14<17:43,  2.81s/it]

[I 2026-05-19 12:03:42,561] Trial 121 finished with value: 0.9498426945745677 and parameters: {'n_estimators': 254, 'learning_rate': 0.04956618629106006, 'max_depth': 4, 'num_leaves': 6, 'min_child_samples': 107, 'subsample': 0.6862900426940465, 'colsample_bytree': 0.8058414194660918, 'reg_alpha': 2.854059732324024, 'reg_lambda': 99.87102237005612}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  25%|███████████████████████████                                                                                   | 123/500 [08:19<20:54,  3.33s/it]

[I 2026-05-19 12:03:47,060] Trial 124 finished with value: 0.9498305557932001 and parameters: {'n_estimators': 145, 'learning_rate': 0.04815924594985065, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 113, 'subsample': 0.6070136069792409, 'colsample_bytree': 0.8096929475412323, 'reg_alpha': 2.7460684126306325, 'reg_lambda': 18.657777043315654}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  25%|███████████████████████████▎                                                                                  | 124/500 [08:21<19:18,  3.08s/it]

[I 2026-05-19 12:03:49,589] Trial 123 pruned.

Best trial: 120. Best value: 0.949859:  25%|███████████████████████████▌                                                                                  | 125/500 [08:36<40:15,  6.44s/it]

[I 2026-05-19 12:04:03,855] Trial 122 finished with value: 0.9498570751946007 and parameters: {'n_estimators': 272, 'learning_rate': 0.049795640968431754, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 144, 'subsample': 0.6848191091947242, 'colsample_bytree': 0.857781833092966, 'reg_alpha': 2.7056382073254746, 'reg_lambda': 0.6336822800637281}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  25%|███████████████████████████▋                                                                                  | 126/500 [08:37<29:57,  4.81s/it]

[I 2026-05-19 12:04:04,864] Trial 125 finished with value: 0.9498577801499526 and parameters: {'n_estimators': 253, 'learning_rate': 0.04915928324547566, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 111, 'subsample': 0.6850939754650706, 'colsample_bytree': 0.8029383975887988, 'reg_alpha': 3.2001482603196028, 'reg_lambda': 75.10058684657447}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  25%|███████████████████████████▉                                                                                  | 127/500 [08:46<38:39,  6.22s/it]

[I 2026-05-19 12:04:14,380] Trial 126 finished with value: 0.9495770888523992 and parameters: {'n_estimators': 255, 'learning_rate': 0.010909192623679643, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 150, 'subsample': 0.6811980642333992, 'colsample_bytree': 0.7974155577392329, 'reg_alpha': 3.0260368149602592, 'reg_lambda': 45.73896884053831}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  26%|████████████████████████████▏                                                                                 | 128/500 [08:47<28:10,  4.54s/it]

[I 2026-05-19 12:04:15,010] Trial 127 finished with value: 0.9497521511660189 and parameters: {'n_estimators': 255, 'learning_rate': 0.01441657524720466, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 115, 'subsample': 0.6106067581257194, 'colsample_bytree': 0.7975126073345982, 'reg_alpha': 3.168010824640083, 'reg_lambda': 16.53922084056761}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  26%|████████████████████████████▍                                                                                 | 129/500 [08:58<39:42,  6.42s/it]

[I 2026-05-19 12:04:25,827] Trial 128 finished with value: 0.9494101925434494 and parameters: {'n_estimators': 253, 'learning_rate': 0.007456511309927914, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 116, 'subsample': 0.6931844654183098, 'colsample_bytree': 0.7993616130530381, 'reg_alpha': 3.295108785715567, 'reg_lambda': 17.734377985956776}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  26%|████████████████████████████▌                                                                                 | 130/500 [09:01<33:26,  5.42s/it]

[I 2026-05-19 12:04:28,904] Trial 135 pruned.

Best trial: 120. Best value: 0.949859:  26%|████████████████████████████▊                                                                                 | 131/500 [09:03<28:28,  4.63s/it]

[I 2026-05-19 12:04:31,655] Trial 138 pruned.

Best trial: 120. Best value: 0.949859:  27%|█████████████████████████████▎                                                                                | 133/500 [09:07<17:59,  2.94s/it]

[I 2026-05-19 12:04:34,665] Trial 129 finished with value: 0.9496902079017419 and parameters: {'n_estimators': 269, 'learning_rate': 0.011001023329710603, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 120, 'subsample': 0.6083669673853572, 'colsample_bytree': 0.7914674819874821, 'reg_alpha': 3.191296013487966, 'reg_lambda': 14.301986974333559}. Best is trial 120 with value: 0.9498586427315591.
[I 2026-05-19 12:04:34,832] Trial 131 finished with value: 0.9498542300392054 and parameters: {'n_estimators': 256, 'learning_rate': 0.043407955068094584, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 179, 'subsample': 0.6858703506550529, 'colsample_bytree': 0.8141828896055415, 'reg_alpha': 0.46220767933443846, 'reg_lambda': 1.7189331015979696}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  27%|█████████████████████████████▍                                                                                | 134/500 [09:08<16:10,  2.65s/it]

[I 2026-05-19 12:04:36,799] Trial 130 finished with value: 0.9497322415926535 and parameters: {'n_estimators': 256, 'learning_rate': 0.012346314553406817, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 118, 'subsample': 0.6083237582903545, 'colsample_bytree': 0.8120445709871486, 'reg_alpha': 2.8237679367371613, 'reg_lambda': 17.64754461138718}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  27%|█████████████████████████████▋                                                                                | 135/500 [09:09<12:32,  2.06s/it]

[I 2026-05-19 12:04:37,486] Trial 132 finished with value: 0.9497067146475949 and parameters: {'n_estimators': 255, 'learning_rate': 0.011912700060521217, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 123, 'subsample': 0.8254590865550703, 'colsample_bytree': 0.8257022030478035, 'reg_alpha': 8.665486520822647, 'reg_lambda': 15.859509839162083}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  27%|█████████████████████████████▉                                                                                | 136/500 [09:14<17:13,  2.84s/it]

[I 2026-05-19 12:04:42,127] Trial 133 finished with value: 0.9497766038508539 and parameters: {'n_estimators': 271, 'learning_rate': 0.015016198813987011, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 122, 'subsample': 0.6087707853773784, 'colsample_bytree': 0.8211561877886521, 'reg_alpha': 0.43695050152080595, 'reg_lambda': 41.212565077021814}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 120. Best value: 0.949859:  27%|██████████████████████████████▏                                                                               | 137/500 [09:15<14:35,  2.41s/it]

[I 2026-05-19 12:04:43,531] Trial 136 pruned.

Best trial: 120. Best value: 0.949859:  28%|██████████████████████████████▎                                                                               | 138/500 [09:20<18:21,  3.04s/it]

[I 2026-05-19 12:04:48,049] Trial 134 finished with value: 0.9497393690417388 and parameters: {'n_estimators': 271, 'learning_rate': 0.013456864956261633, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 120, 'subsample': 0.6102220750498836, 'colsample_bytree': 0.818723686161737, 'reg_alpha': 7.844949583437062, 'reg_lambda': 47.96429810347773}. Best is trial 120 with value: 0.9498586427315591.

Best trial: 137. Best value: 0.949862:  28%|██████████████████████████████▌                                                                               | 139/500 [09:34<39:19,  6.54s/it]

[I 2026-05-19 12:05:02,746] Trial 137 finished with value: 0.9498624417023628 and parameters: {'n_estimators': 273, 'learning_rate': 0.043772478878793764, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 122, 'subsample': 0.7323307536530438, 'colsample_bytree': 0.8186863047766975, 'reg_alpha': 17.235281592306027, 'reg_lambda': 17.375586018227036}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  28%|██████████████████████████████▏                                                                             | 140/500 [09:56<1:05:34, 10.93s/it]

[I 2026-05-19 12:05:23,928] Trial 139 finished with value: 0.9493319141305765 and parameters: {'n_estimators': 272, 'learning_rate': 0.005209285336266819, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 121, 'subsample': 0.7057636373077507, 'colsample_bytree': 0.8249829539124882, 'reg_alpha': 0.9300644680625952, 'reg_lambda': 31.55781759253328}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  28%|███████████████████████████████                                                                               | 141/500 [09:58<49:31,  8.28s/it]

[I 2026-05-19 12:05:26,009] Trial 140 finished with value: 0.949849169871707 and parameters: {'n_estimators': 271, 'learning_rate': 0.043155064916442956, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 98, 'subsample': 0.7248392903959329, 'colsample_bytree': 0.7832769970694274, 'reg_alpha': 1.0224603847025484, 'reg_lambda': 44.061617453947676}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  28%|███████████████████████████████▏                                                                              | 142/500 [09:59<37:14,  6.24s/it]

[I 2026-05-19 12:05:27,500] Trial 141 finished with value: 0.9498509775586857 and parameters: {'n_estimators': 270, 'learning_rate': 0.04333210404997831, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 97, 'subsample': 0.6603335570824928, 'colsample_bytree': 0.8217330891657616, 'reg_alpha': 0.984664795617784, 'reg_lambda': 0.25381234750790305}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  29%|███████████████████████████████▍                                                                              | 143/500 [10:03<32:53,  5.53s/it]

[I 2026-05-19 12:05:31,368] Trial 146 finished with value: 0.9498517215213468 and parameters: {'n_estimators': 236, 'learning_rate': 0.044240504630930814, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 76, 'subsample': 0.753162324434168, 'colsample_bytree': 0.8202685884012262, 'reg_alpha': 1.1146486421642126, 'reg_lambda': 1.9171797401728146}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  29%|███████████████████████████████▋                                                                              | 144/500 [10:03<23:22,  3.94s/it]

[I 2026-05-19 12:05:31,609] Trial 142 finished with value: 0.9498479273507348 and parameters: {'n_estimators': 271, 'learning_rate': 0.04363382465965599, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 101, 'subsample': 0.6213383770186978, 'colsample_bytree': 0.8220076939894962, 'reg_alpha': 0.895892980475279, 'reg_lambda': 1.7816393901680063}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  29%|███████████████████████████████▉                                                                              | 145/500 [10:05<18:29,  3.13s/it]

[I 2026-05-19 12:05:32,843] Trial 145 finished with value: 0.9498522865622195 and parameters: {'n_estimators': 235, 'learning_rate': 0.04364460963638485, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 101, 'subsample': 0.7052277011711612, 'colsample_bytree': 0.8173469922206076, 'reg_alpha': 0.06827776991270963, 'reg_lambda': 1.5672709939159541}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  29%|████████████████████████████████                                                                              | 146/500 [10:05<14:20,  2.43s/it]

[I 2026-05-19 12:05:33,636] Trial 143 finished with value: 0.9498539789930855 and parameters: {'n_estimators': 271, 'learning_rate': 0.04110694562200607, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 127, 'subsample': 0.8927008458829117, 'colsample_bytree': 0.821403733181556, 'reg_alpha': 2.174317484517046, 'reg_lambda': 0.31150474694189784}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  29%|████████████████████████████████▎                                                                             | 147/500 [10:06<11:08,  1.90s/it]

[I 2026-05-19 12:05:34,280] Trial 144 finished with value: 0.9498506223838781 and parameters: {'n_estimators': 269, 'learning_rate': 0.04327555285075886, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 100, 'subsample': 0.7152857591333193, 'colsample_bytree': 0.8167545968213629, 'reg_alpha': 0.9521503417173915, 'reg_lambda': 1.3894914132482667}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  30%|████████████████████████████████▌                                                                             | 148/500 [10:09<13:14,  2.26s/it]

[I 2026-05-19 12:05:37,385] Trial 148 finished with value: 0.9498472824487655 and parameters: {'n_estimators': 237, 'learning_rate': 0.04356235726056727, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 197, 'subsample': 0.7043067105103821, 'colsample_bytree': 0.849034578420074, 'reg_alpha': 1.0009417434912127, 'reg_lambda': 1.8799290056253057}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  30%|████████████████████████████████▊                                                                             | 149/500 [10:12<13:53,  2.38s/it]

[I 2026-05-19 12:05:40,025] Trial 149 finished with value: 0.949849783613525 and parameters: {'n_estimators': 230, 'learning_rate': 0.04350020079111424, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 129, 'subsample': 0.7370502329290531, 'colsample_bytree': 0.8854123058842192, 'reg_alpha': 0.965277520808347, 'reg_lambda': 1.5844549193612947}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  30%|█████████████████████████████████                                                                             | 150/500 [10:16<16:32,  2.84s/it]

[I 2026-05-19 12:05:43,941] Trial 147 finished with value: 0.9498493840616484 and parameters: {'n_estimators': 271, 'learning_rate': 0.04331644770578087, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 77, 'subsample': 0.7474958764888457, 'colsample_bytree': 0.8488963492899184, 'reg_alpha': 0.20383156220270868, 'reg_lambda': 0.9407730504712942}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  30%|█████████████████████████████████▏                                                                            | 151/500 [10:28<32:53,  5.65s/it]

[I 2026-05-19 12:05:56,163] Trial 150 finished with value: 0.9498573175793034 and parameters: {'n_estimators': 231, 'learning_rate': 0.04348296706873285, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 77, 'subsample': 0.7305585252208694, 'colsample_bytree': 0.8467421260655327, 'reg_alpha': 19.052752688145784, 'reg_lambda': 1.74709474207037}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  30%|█████████████████████████████████▍                                                                            | 152/500 [10:41<45:22,  7.82s/it]

[I 2026-05-19 12:06:09,045] Trial 155 finished with value: 0.9498262838844305 and parameters: {'n_estimators': 171, 'learning_rate': 0.040387889974685454, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 164, 'subsample': 0.6712734135367732, 'colsample_bytree': 0.8482617568525692, 'reg_alpha': 0.19217954958836247, 'reg_lambda': 1.1499448927873803}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  31%|█████████████████████████████████▋                                                                            | 153/500 [10:44<37:50,  6.54s/it]

[I 2026-05-19 12:06:12,625] Trial 152 finished with value: 0.9498388647692613 and parameters: {'n_estimators': 235, 'learning_rate': 0.04037640242763399, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 199, 'subsample': 0.7038612425628502, 'colsample_bytree': 0.8465074310056647, 'reg_alpha': 0.060809878886643465, 'reg_lambda': 0.27411880757355434}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  31%|█████████████████████████████████▉                                                                            | 154/500 [10:47<30:30,  5.29s/it]

[I 2026-05-19 12:06:14,977] Trial 160 finished with value: 0.9498094571044797 and parameters: {'n_estimators': 114, 'learning_rate': 0.040435409119257464, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 141, 'subsample': 0.8955489157083938, 'colsample_bytree': 0.8447637279765826, 'reg_alpha': 2.195389600335678, 'reg_lambda': 0.7997690158813647}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  31%|██████████████████████████████████                                                                            | 155/500 [10:49<25:21,  4.41s/it]

[I 2026-05-19 12:06:17,337] Trial 157 finished with value: 0.9498379184855119 and parameters: {'n_estimators': 192, 'learning_rate': 0.0396257407028606, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 129, 'subsample': 0.7330268581811649, 'colsample_bytree': 0.8478799218699197, 'reg_alpha': 0.18043800033561125, 'reg_lambda': 0.7270497851712097}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  31%|██████████████████████████████████▎                                                                           | 156/500 [10:52<22:56,  4.00s/it]

[I 2026-05-19 12:06:20,395] Trial 153 finished with value: 0.9498435858913566 and parameters: {'n_estimators': 235, 'learning_rate': 0.04366427956732026, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 104, 'subsample': 0.6744511267763305, 'colsample_bytree': 0.8442893194633142, 'reg_alpha': 0.1703642080303167, 'reg_lambda': 1.510184054532061}. Best is trial 137 with value: 0.9498624417023628.
[I 2026-05-19 12:06:20,415] Trial 159 finished with value: 0.9498530757579925 and parameters: {'n_estimators': 171, 'learning_rate': 0.04984396423848216, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 128, 'subsample': 0.7446763465660634, 'colsample_bytree': 0.8459411382332712, 'reg_alpha': 2.0936555158351613, 'reg_lambda': 0.8859733294985342}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  32%|██████████████████████████████████▊                                                                           | 158/500 [10:56<17:48,  3.12s/it]

[I 2026-05-19 12:06:24,594] Trial 151 finished with value: 0.9498529295318832 and parameters: {'n_estimators': 292, 'learning_rate': 0.04345394399883468, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 102, 'subsample': 0.7419895297589182, 'colsample_bytree': 0.8460945090359725, 'reg_alpha': 1.036629961169196, 'reg_lambda': 0.879697996958676}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  32%|██████████████████████████████████▉                                                                           | 159/500 [10:59<17:33,  3.09s/it]

[I 2026-05-19 12:06:27,580] Trial 154 finished with value: 0.9498428220180006 and parameters: {'n_estimators': 291, 'learning_rate': 0.0406316985551093, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 104, 'subsample': 0.7132665040166466, 'colsample_bytree': 0.843823336354776, 'reg_alpha': 0.19205184378203383, 'reg_lambda': 1.2446329829441551}. Best is trial 137 with value: 0.9498624417023628.
[I 2026-05-19 12:06:27,615] Trial 161 finished with value: 0.9498454624945605 and parameters: {'n_estimators': 170, 'learning_rate': 0.03961552947243193, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 164, 'subsample': 0.6582307463167355, 'colsample_bytree': 0.8483515199624847, 'reg_alpha': 2.209718638539574, 'reg_lambda': 0.45038966757396964}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  32%|███████████████████████████████████▍                                                                          | 161/500 [11:03<14:09,  2.51s/it]

[I 2026-05-19 12:06:30,949] Trial 156 finished with value: 0.9498535727444709 and parameters: {'n_estimators': 291, 'learning_rate': 0.040754182944065666, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 130, 'subsample': 0.6731422308813926, 'colsample_bytree': 0.8463004986997946, 'reg_alpha': 1.9459885318198231, 'reg_lambda': 0.9211185127045446}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  32%|███████████████████████████████████▋                                                                          | 162/500 [11:07<16:10,  2.87s/it]

[I 2026-05-19 12:06:35,064] Trial 158 finished with value: 0.9498614848276343 and parameters: {'n_estimators': 292, 'learning_rate': 0.0397202138501295, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 140, 'subsample': 0.8910326630086566, 'colsample_bytree': 0.8461285631892935, 'reg_alpha': 14.950291973166824, 'reg_lambda': 0.9264076171057056}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  33%|███████████████████████████████████▊                                                                          | 163/500 [11:16<24:38,  4.39s/it]

[I 2026-05-19 12:06:44,071] Trial 172 finished with value: 0.9493731051290728 and parameters: {'n_estimators': 46, 'learning_rate': 0.04987014585131677, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 128, 'subsample': 0.6830377251255146, 'colsample_bytree': 0.8308304259351473, 'reg_alpha': 18.569165788319804, 'reg_lambda': 10.522854826225691}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  33%|████████████████████████████████████                                                                          | 164/500 [11:33<42:58,  7.67s/it]

[I 2026-05-19 12:07:01,094] Trial 162 finished with value: 0.9498553811497313 and parameters: {'n_estimators': 292, 'learning_rate': 0.03981559208492396, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 163, 'subsample': 0.8934085067542455, 'colsample_bytree': 0.8405150156090704, 'reg_alpha': 26.538227166282887, 'reg_lambda': 11.050861891052202}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  33%|████████████████████████████████████▎                                                                         | 165/500 [11:36<36:27,  6.53s/it]

[I 2026-05-19 12:07:04,548] Trial 174 finished with value: 0.9497219284159231 and parameters: {'n_estimators': 76, 'learning_rate': 0.04775890411963014, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 34, 'subsample': 0.7603815434548015, 'colsample_bytree': 0.8341549944668033, 'reg_alpha': 43.067521452499925, 'reg_lambda': 4.626912515441151}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  33%|████████████████████████████████████▌                                                                         | 166/500 [11:41<33:19,  5.99s/it]

[I 2026-05-19 12:07:09,130] Trial 168 finished with value: 0.9498503524566401 and parameters: {'n_estimators': 219, 'learning_rate': 0.04988494425201765, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 140, 'subsample': 0.7703457802766321, 'colsample_bytree': 0.8341297227219225, 'reg_alpha': 1.831147297246173, 'reg_lambda': 11.452280185026185}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  33%|████████████████████████████████████▋                                                                         | 167/500 [11:41<24:38,  4.44s/it]

[I 2026-05-19 12:07:09,680] Trial 164 finished with value: 0.9498612321157325 and parameters: {'n_estimators': 292, 'learning_rate': 0.04975985217033901, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 141, 'subsample': 0.8898208378491638, 'colsample_bytree': 0.8330859528006891, 'reg_alpha': 24.780106292765623, 'reg_lambda': 10.825895625171924}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  34%|████████████████████████████████████▉                                                                         | 168/500 [11:44<21:17,  3.85s/it]

[I 2026-05-19 12:07:12,083] Trial 169 finished with value: 0.9498602855179253 and parameters: {'n_estimators': 220, 'learning_rate': 0.04940287420335222, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 89, 'subsample': 0.7671334314781562, 'colsample_bytree': 0.8376145476782687, 'reg_alpha': 19.11873378036493, 'reg_lambda': 11.442104149400834}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  34%|█████████████████████████████████████▏                                                                        | 169/500 [11:46<17:54,  3.24s/it]

[I 2026-05-19 12:07:13,883] Trial 171 finished with value: 0.949860385889713 and parameters: {'n_estimators': 212, 'learning_rate': 0.04832173820375167, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 88, 'subsample': 0.7651406141356552, 'colsample_bytree': 0.767941900966796, 'reg_alpha': 17.591363924461657, 'reg_lambda': 10.429100500900715}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 137. Best value: 0.949862:  34%|█████████████████████████████████████▍                                                                        | 170/500 [11:47<14:38,  2.66s/it]

[I 2026-05-19 12:07:15,145] Trial 163 finished with value: 0.9498601939235314 and parameters: {'n_estimators': 292, 'learning_rate': 0.04905682511605383, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 140, 'subsample': 0.8929139998915351, 'colsample_bytree': 0.8444651168115122, 'reg_alpha': 34.122523849943654, 'reg_lambda': 0.4405499014715865}. Best is trial 137 with value: 0.9498624417023628.

Best trial: 167. Best value: 0.949866:  34%|█████████████████████████████████████▌                                                                        | 171/500 [11:51<16:39,  3.04s/it]

[I 2026-05-19 12:07:19,081] Trial 167 finished with value: 0.9498664695849518 and parameters: {'n_estimators': 292, 'learning_rate': 0.049739251629885274, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 245, 'subsample': 0.6566059016320229, 'colsample_bytree': 0.7567108320523559, 'reg_alpha': 16.34614975508886, 'reg_lambda': 0.4805652481356107}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  34%|█████████████████████████████████████▊                                                                        | 172/500 [11:52<13:00,  2.38s/it]

[I 2026-05-19 12:07:19,896] Trial 166 finished with value: 0.9498569762316322 and parameters: {'n_estimators': 293, 'learning_rate': 0.0478322016329945, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 88, 'subsample': 0.8026245054412889, 'colsample_bytree': 0.768131080840251, 'reg_alpha': 38.55983033036235, 'reg_lambda': 10.881739324745466}. Best is trial 167 with value: 0.9498664695849518.
[I 2026-05-19 12:07:19,958] Trial 165 finished with value: 0.9498601449446644 and parameters: {'n_estimators': 283, 'learning_rate': 0.04976207878367811, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 128, 'subsample': 0.7692411470316802, 'colsample_bytree': 0.8378643256659897, 'reg_alpha': 21.160836637811496, 'reg_lambda': 0.46093295503145243}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  35%|██████████████████████████████████████▎                                                                       | 174/500 [11:54<10:09,  1.87s/it]

[I 2026-05-19 12:07:22,419] Trial 170 finished with value: 0.9498631564822897 and parameters: {'n_estimators': 282, 'learning_rate': 0.04931799629499022, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 140, 'subsample': 0.7701636828310043, 'colsample_bytree': 0.8325191136431584, 'reg_alpha': 21.481301373270426, 'reg_lambda': 9.996368937483341}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  35%|██████████████████████████████████████▌                                                                       | 175/500 [12:02<18:12,  3.36s/it]

[I 2026-05-19 12:07:30,335] Trial 173 finished with value: 0.9498643340881989 and parameters: {'n_estimators': 260, 'learning_rate': 0.049925459230374905, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 140, 'subsample': 0.7968785003616223, 'colsample_bytree': 0.8390452808625186, 'reg_alpha': 18.820889735202883, 'reg_lambda': 0.015145524280131498}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  35%|██████████████████████████████████████▋                                                                       | 176/500 [12:31<54:14, 10.04s/it]

[I 2026-05-19 12:07:59,328] Trial 181 finished with value: 0.9498525908799085 and parameters: {'n_estimators': 213, 'learning_rate': 0.047469114535667455, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 90, 'subsample': 0.9021689301245359, 'colsample_bytree': 0.7286619318478142, 'reg_alpha': 27.148536263113147, 'reg_lambda': 0.016305369157855815}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  35%|██████████████████████████████████████▉                                                                       | 177/500 [12:35<45:05,  8.38s/it]

[I 2026-05-19 12:08:03,225] Trial 176 finished with value: 0.9498616592381092 and parameters: {'n_estimators': 281, 'learning_rate': 0.04705735833480258, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 148, 'subsample': 0.9024681274640438, 'colsample_bytree': 0.8647595526862075, 'reg_alpha': 7.538869073471426, 'reg_lambda': 2.932587787931844}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  36%|███████████████████████████████████████▏                                                                      | 178/500 [12:35<33:13,  6.19s/it]

[I 2026-05-19 12:08:03,785] Trial 182 finished with value: 0.9498556636777339 and parameters: {'n_estimators': 210, 'learning_rate': 0.0478227824357015, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 90, 'subsample': 0.88409924341764, 'colsample_bytree': 0.7470275344267028, 'reg_alpha': 17.18074697038799, 'reg_lambda': 10.575106137337011}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  36%|███████████████████████████████████████▍                                                                      | 179/500 [12:37<25:37,  4.79s/it]

[I 2026-05-19 12:08:05,055] Trial 179 finished with value: 0.9498620329410802 and parameters: {'n_estimators': 244, 'learning_rate': 0.04761022402112562, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 139, 'subsample': 0.8915136562079745, 'colsample_bytree': 0.8117035306777133, 'reg_alpha': 28.99456928933119, 'reg_lambda': 6.547403341856678}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  36%|███████████████████████████████████████▌                                                                      | 180/500 [12:37<18:37,  3.49s/it]

[I 2026-05-19 12:08:05,363] Trial 180 finished with value: 0.9498300611112043 and parameters: {'n_estimators': 204, 'learning_rate': 0.03560194697740243, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 93, 'subsample': 0.80078213935208, 'colsample_bytree': 0.7511394456072967, 'reg_alpha': 33.38554091263426, 'reg_lambda': 0.017804125993119913}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  36%|███████████████████████████████████████▊                                                                      | 181/500 [12:37<13:44,  2.58s/it]

[I 2026-05-19 12:08:05,764] Trial 175 finished with value: 0.9498576511815665 and parameters: {'n_estimators': 282, 'learning_rate': 0.03563252794344791, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 147, 'subsample': 0.9021491473422666, 'colsample_bytree': 0.8330218546790675, 'reg_alpha': 37.52946511977066, 'reg_lambda': 3.706109830243421}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  36%|████████████████████████████████████████                                                                      | 182/500 [12:38<10:14,  1.93s/it]

[I 2026-05-19 12:08:06,133] Trial 177 finished with value: 0.9498645528001788 and parameters: {'n_estimators': 261, 'learning_rate': 0.04728013205651064, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 148, 'subsample': 0.8882784732365893, 'colsample_bytree': 0.8592965305978799, 'reg_alpha': 24.591417163196347, 'reg_lambda': 3.2649557640848075}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  37%|████████████████████████████████████████▎                                                                     | 183/500 [12:40<10:13,  1.93s/it]

[I 2026-05-19 12:08:08,066] Trial 183 finished with value: 0.949843901697615 and parameters: {'n_estimators': 214, 'learning_rate': 0.04748298973490238, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 83, 'subsample': 0.8991174479266574, 'colsample_bytree': 0.763406784541812, 'reg_alpha': 33.03402446291381, 'reg_lambda': 0.015194750367711776}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  37%|████████████████████████████████████████▍                                                                     | 184/500 [12:41<09:38,  1.83s/it]

[I 2026-05-19 12:08:09,664] Trial 185 finished with value: 0.9498431800033084 and parameters: {'n_estimators': 211, 'learning_rate': 0.04789901100095443, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 90, 'subsample': 0.7946408508745506, 'colsample_bytree': 0.7553109651045055, 'reg_alpha': 33.60760192500173, 'reg_lambda': 22.753726911167018}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  37%|████████████████████████████████████████▋                                                                     | 185/500 [12:44<11:07,  2.12s/it]

[I 2026-05-19 12:08:12,435] Trial 186 finished with value: 0.9498545229747674 and parameters: {'n_estimators': 204, 'learning_rate': 0.047464023673142335, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 82, 'subsample': 0.7928934382111483, 'colsample_bytree': 0.7308087041546939, 'reg_alpha': 15.192982932915076, 'reg_lambda': 0.015242756536667339}. Best is trial 167 with value: 0.9498664695849518.
[I 2026-05-19 12:08:12,477] Trial 184 finished with value: 0.9498515308639528 and parameters: {'n_estimators': 224, 'learning_rate': 0.0477385590570698, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 88, 'subsample': 0.7979501577040031, 'colsample_bytree': 0.7512095351780854, 'reg_alpha': 30.91519731764476, 'reg_lambda': 0.46500794496945835}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  37%|█████████████████████████████████████████▏                                                                    | 187/500 [12:45<06:56,  1.33s/it]

[I 2026-05-19 12:08:13,281] Trial 178 finished with value: 0.9498553731925286 and parameters: {'n_estimators': 283, 'learning_rate': 0.047032955724182576, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 84, 'subsample': 0.9057496345703707, 'colsample_bytree': 0.8619249911265998, 'reg_alpha': 25.50780450480591, 'reg_lambda': 7.609156560436761}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  38%|█████████████████████████████████████████▎                                                                    | 188/500 [13:11<38:07,  7.33s/it]

[I 2026-05-19 12:08:38,829] Trial 193 pruned.

Best trial: 167. Best value: 0.949866:  38%|█████████████████████████████████████████▌                                                                    | 189/500 [13:22<44:03,  8.50s/it]

[I 2026-05-19 12:08:50,673] Trial 188 finished with value: 0.9498600399261121 and parameters: {'n_estimators': 226, 'learning_rate': 0.047729572500205486, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 81, 'subsample': 0.7992218762095842, 'colsample_bytree': 0.7669408730721552, 'reg_alpha': 14.445267555815347, 'reg_lambda': 0.44286190825723254}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  38%|█████████████████████████████████████████▊                                                                    | 190/500 [13:23<32:56,  6.38s/it]

[I 2026-05-19 12:08:51,351] Trial 189 finished with value: 0.9498279052568691 and parameters: {'n_estimators': 224, 'learning_rate': 0.04999949048318568, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 83, 'subsample': 0.7908909255199773, 'colsample_bytree': 0.769521624560782, 'reg_alpha': 74.33865549356635, 'reg_lambda': 0.015639317087810703}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  38%|██████████████████████████████████████████                                                                    | 191/500 [13:25<26:59,  5.24s/it]

[I 2026-05-19 12:08:53,678] Trial 187 finished with value: 0.9498573785984512 and parameters: {'n_estimators': 226, 'learning_rate': 0.0498655403548052, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 85, 'subsample': 0.7905851335248716, 'colsample_bytree': 0.760349633345798, 'reg_alpha': 14.50081869797188, 'reg_lambda': 22.18354498280298}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  38%|██████████████████████████████████████████▏                                                                   | 192/500 [13:26<19:52,  3.87s/it]

[I 2026-05-19 12:08:54,101] Trial 190 finished with value: 0.9498594657503421 and parameters: {'n_estimators': 221, 'learning_rate': 0.04966069337928029, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 77, 'subsample': 0.7967592834526571, 'colsample_bytree': 0.7636931623509382, 'reg_alpha': 13.23539903154129, 'reg_lambda': 26.34941480729642}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  39%|██████████████████████████████████████████▍                                                                   | 193/500 [13:29<18:52,  3.69s/it]

[I 2026-05-19 12:08:57,345] Trial 194 finished with value: 0.949864161859772 and parameters: {'n_estimators': 226, 'learning_rate': 0.04980899723587607, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 139, 'subsample': 0.7755063104337482, 'colsample_bytree': 0.8586446392756011, 'reg_alpha': 13.262882925062263, 'reg_lambda': 0.43894203709509444}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  39%|██████████████████████████████████████████▋                                                                   | 194/500 [13:33<18:49,  3.69s/it]

[I 2026-05-19 12:09:01,035] Trial 191 finished with value: 0.9498071517181913 and parameters: {'n_estimators': 244, 'learning_rate': 0.04970665732652959, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 83, 'subsample': 0.7750976475289226, 'colsample_bytree': 0.7684709436638192, 'reg_alpha': 78.99096294204962, 'reg_lambda': 23.238791810950275}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 167. Best value: 0.949866:  39%|██████████████████████████████████████████▉                                                                   | 195/500 [13:34<15:05,  2.97s/it]

[I 2026-05-19 12:09:02,270] Trial 196 finished with value: 0.9498285393424771 and parameters: {'n_estimators': 227, 'learning_rate': 0.04972188858587641, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 150, 'subsample': 0.7771653405249032, 'colsample_bytree': 0.8592470109185879, 'reg_alpha': 68.44919701250943, 'reg_lambda': 7.298733700249164}. Best is trial 167 with value: 0.9498664695849518.

Best trial: 192. Best value: 0.949868:  39%|███████████████████████████████████████████                                                                   | 196/500 [13:36<12:57,  2.56s/it]

[I 2026-05-19 12:09:03,870] Trial 192 finished with value: 0.9498676328276904 and parameters: {'n_estimators': 286, 'learning_rate': 0.04973686568587008, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 80, 'subsample': 0.7993272777381091, 'colsample_bytree': 0.7633267677312474, 'reg_alpha': 14.132698497982531, 'reg_lambda': 0.4644813699635641}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  39%|███████████████████████████████████████████▎                                                                  | 197/500 [13:37<11:48,  2.34s/it]

[I 2026-05-19 12:09:05,702] Trial 197 finished with value: 0.9498287829136668 and parameters: {'n_estimators': 245, 'learning_rate': 0.04994639423568979, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 140, 'subsample': 0.7744628559606697, 'colsample_bytree': 0.8621378897536868, 'reg_alpha': 66.16365246174408, 'reg_lambda': 2.54111282822381}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  40%|███████████████████████████████████████████▌                                                                  | 198/500 [13:38<09:55,  1.97s/it]

[I 2026-05-19 12:09:06,802] Trial 198 finished with value: 0.9498131095779035 and parameters: {'n_estimators': 244, 'learning_rate': 0.04867891977263801, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 69, 'subsample': 0.7769475437322334, 'colsample_bytree': 0.7836761252149781, 'reg_alpha': 80.83908219085106, 'reg_lambda': 3.055609287214032}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  40%|███████████████████████████████████████████▊                                                                  | 199/500 [13:44<14:47,  2.95s/it]

[I 2026-05-19 12:09:12,009] Trial 195 finished with value: 0.9498645399990793 and parameters: {'n_estimators': 283, 'learning_rate': 0.049514647844040145, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 69, 'subsample': 0.7631733717962134, 'colsample_bytree': 0.8606763106770374, 'reg_alpha': 13.786013470194892, 'reg_lambda': 2.8781143122251467}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  40%|████████████████████████████████████████████                                                                  | 200/500 [14:06<43:56,  8.79s/it]

[I 2026-05-19 12:09:34,500] Trial 199 finished with value: 0.9498651722249688 and parameters: {'n_estimators': 245, 'learning_rate': 0.049842757035628224, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 151, 'subsample': 0.7739753918325314, 'colsample_bytree': 0.97613249737161, 'reg_alpha': 12.35266888404806, 'reg_lambda': 0.04297918305750009}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  40%|████████████████████████████████████████████▏                                                                 | 201/500 [14:07<32:22,  6.50s/it]

[I 2026-05-19 12:09:35,643] Trial 206 finished with value: 0.9498304224025473 and parameters: {'n_estimators': 248, 'learning_rate': 0.045488615059425634, 'max_depth': 2, 'num_leaves': 15, 'min_child_samples': 109, 'subsample': 0.8134299177974585, 'colsample_bytree': 0.7825926632992222, 'reg_alpha': 11.787298610761242, 'reg_lambda': 0.4312072960129178}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  40%|████████████████████████████████████████████▍                                                                 | 202/500 [14:09<25:31,  5.14s/it]

[I 2026-05-19 12:09:37,625] Trial 207 finished with value: 0.9498202640294625 and parameters: {'n_estimators': 220, 'learning_rate': 0.045998524465974376, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 141, 'subsample': 0.7604802273217707, 'colsample_bytree': 0.7848001577268765, 'reg_alpha': 10.370469539737481, 'reg_lambda': 0.20918817892574945}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  41%|████████████████████████████████████████████▋                                                                 | 203/500 [14:17<28:50,  5.83s/it]

[I 2026-05-19 12:09:45,039] Trial 200 finished with value: 0.9498645539406787 and parameters: {'n_estimators': 246, 'learning_rate': 0.049618363833509004, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 62, 'subsample': 0.7759604174075435, 'colsample_bytree': 0.7609619836808014, 'reg_alpha': 11.381717685278698, 'reg_lambda': 0.5045178238014424}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  41%|████████████████████████████████████████████▉                                                                 | 204/500 [14:17<20:51,  4.23s/it]

[I 2026-05-19 12:09:45,529] Trial 202 finished with value: 0.9498641158719539 and parameters: {'n_estimators': 246, 'learning_rate': 0.0499086523985773, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 68, 'subsample': 0.8118449378839093, 'colsample_bytree': 0.7798183744174029, 'reg_alpha': 11.225125404492347, 'reg_lambda': 27.625760147770624}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  41%|█████████████████████████████████████████████                                                                 | 205/500 [14:18<15:34,  3.17s/it]

[I 2026-05-19 12:09:46,236] Trial 201 finished with value: 0.9498650806457498 and parameters: {'n_estimators': 244, 'learning_rate': 0.0497049638144871, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 71, 'subsample': 0.7776760735534756, 'colsample_bytree': 0.8090761788680711, 'reg_alpha': 9.231759374940054, 'reg_lambda': 0.04429213336663366}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  41%|█████████████████████████████████████████████▎                                                                | 206/500 [14:25<21:33,  4.40s/it]

[I 2026-05-19 12:09:53,495] Trial 203 finished with value: 0.9498605414942058 and parameters: {'n_estimators': 245, 'learning_rate': 0.04974017469913754, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 65, 'subsample': 0.7772951188347208, 'colsample_bytree': 0.7859534280797185, 'reg_alpha': 12.994381197419326, 'reg_lambda': 21.983995899770576}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  41%|█████████████████████████████████████████████▌                                                                | 207/500 [14:25<15:28,  3.17s/it]

[I 2026-05-19 12:09:53,797] Trial 208 finished with value: 0.9498573280882496 and parameters: {'n_estimators': 219, 'learning_rate': 0.045754845592974526, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 70, 'subsample': 0.8153090911198799, 'colsample_bytree': 0.7395264637183081, 'reg_alpha': 10.087284862042047, 'reg_lambda': 0.26226535282549707}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  42%|█████████████████████████████████████████████▊                                                                | 208/500 [14:26<11:51,  2.44s/it]

[I 2026-05-19 12:09:54,526] Trial 204 finished with value: 0.9498598784162645 and parameters: {'n_estimators': 243, 'learning_rate': 0.0493620751719699, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 65, 'subsample': 0.777006773671297, 'colsample_bytree': 0.7628145798941603, 'reg_alpha': 12.747965285451144, 'reg_lambda': 22.922044612016656}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  42%|█████████████████████████████████████████████▉                                                                | 209/500 [14:28<11:04,  2.28s/it]

[I 2026-05-19 12:09:56,442] Trial 205 finished with value: 0.9498541840384259 and parameters: {'n_estimators': 244, 'learning_rate': 0.04999225027003506, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 59, 'subsample': 0.8135136831289272, 'colsample_bytree': 0.7597269637481805, 'reg_alpha': 11.50156983831899, 'reg_lambda': 0.45186376465556494}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  42%|██████████████████████████████████████████████▏                                                               | 210/500 [14:31<11:09,  2.31s/it]

[I 2026-05-19 12:09:58,816] Trial 209 finished with value: 0.9498501199124473 and parameters: {'n_estimators': 219, 'learning_rate': 0.045882719300027804, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 137, 'subsample': 0.7600078532676994, 'colsample_bytree': 0.7804815663631736, 'reg_alpha': 10.411426978403123, 'reg_lambda': 0.5321040827363162}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  42%|██████████████████████████████████████████████▍                                                               | 211/500 [14:47<31:36,  6.56s/it]

[I 2026-05-19 12:10:15,315] Trial 210 finished with value: 0.9498539768302612 and parameters: {'n_estimators': 260, 'learning_rate': 0.04523650470117472, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 61, 'subsample': 0.8140177027056297, 'colsample_bytree': 0.7884147319787191, 'reg_alpha': 11.090391279204908, 'reg_lambda': 0.3365711013440347}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  42%|██████████████████████████████████████████████▋                                                               | 212/500 [14:50<26:41,  5.56s/it]

[I 2026-05-19 12:10:18,531] Trial 213 finished with value: 0.9498547149696968 and parameters: {'n_estimators': 195, 'learning_rate': 0.04691671859081749, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 63, 'subsample': 0.7658272183306869, 'colsample_bytree': 0.735750980357838, 'reg_alpha': 11.539261823358041, 'reg_lambda': 0.35584125271696304}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  43%|██████████████████████████████████████████████▊                                                               | 213/500 [14:55<25:36,  5.35s/it]

[I 2026-05-19 12:10:23,389] Trial 211 finished with value: 0.9498575933529594 and parameters: {'n_estimators': 220, 'learning_rate': 0.04548812491984327, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 66, 'subsample': 0.815140292549696, 'colsample_bytree': 0.7443896325484249, 'reg_alpha': 13.347520642493604, 'reg_lambda': 0.46159985416038235}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  43%|███████████████████████████████████████████████                                                               | 214/500 [15:10<39:51,  8.36s/it]

[I 2026-05-19 12:10:38,767] Trial 215 finished with value: 0.9498639461827105 and parameters: {'n_estimators': 240, 'learning_rate': 0.04588310199795378, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 58, 'subsample': 0.7677234751217011, 'colsample_bytree': 0.7758421349120357, 'reg_alpha': 12.802343465553998, 'reg_lambda': 0.4958268284238593}. Best is trial 192 with value: 0.9498676328276904.
[I 2026-05-19 12:10:38,780] Trial 216 finished with value: 0.9498626366510177 and parameters: {'n_estimators': 241, 'learning_rate': 0.045654800448271936, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 55, 'subsample': 0.7671037329860534, 'colsample_bytree': 0.7794490287638893, 'reg_alpha': 8.816152614851998, 'reg_lambda': 0.5072531974449999}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  43%|███████████████████████████████████████████████▌                                                              | 216/500 [15:12<23:07,  4.89s/it]

[I 2026-05-19 12:10:40,427] Trial 212 finished with value: 0.9498582795806975 and parameters: {'n_estimators': 283, 'learning_rate': 0.045752779899375824, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 66, 'subsample': 0.7626278411442681, 'colsample_bytree': 0.7591605697007971, 'reg_alpha': 9.93633498433794, 'reg_lambda': 0.35047921585952607}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  43%|███████████████████████████████████████████████▋                                                              | 217/500 [15:17<22:28,  4.77s/it]

[I 2026-05-19 12:10:44,841] Trial 217 finished with value: 0.9498635478400207 and parameters: {'n_estimators': 240, 'learning_rate': 0.04558239122220715, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 57, 'subsample': 0.7650231590937175, 'colsample_bytree': 0.7450125422997079, 'reg_alpha': 9.351735478953344, 'reg_lambda': 0.5844545334992391}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  44%|███████████████████████████████████████████████▉                                                              | 218/500 [15:17<17:04,  3.63s/it]

[I 2026-05-19 12:10:45,273] Trial 218 finished with value: 0.9498571970274471 and parameters: {'n_estimators': 240, 'learning_rate': 0.0453708111182931, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 54, 'subsample': 0.7641097805406154, 'colsample_bytree': 0.7781161667174945, 'reg_alpha': 7.080429101279136, 'reg_lambda': 0.05291087406353823}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  44%|████████████████████████████████████████████████▏                                                             | 219/500 [15:20<15:57,  3.41s/it]

[I 2026-05-19 12:10:48,087] Trial 214 finished with value: 0.9498580100368859 and parameters: {'n_estimators': 285, 'learning_rate': 0.04571693934737419, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 57, 'subsample': 0.8069745591508849, 'colsample_bytree': 0.7624103198947043, 'reg_alpha': 11.692793664046578, 'reg_lambda': 0.5032510505376658}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  44%|████████████████████████████████████████████████▍                                                             | 220/500 [15:22<14:04,  3.02s/it]

[I 2026-05-19 12:10:50,099] Trial 220 finished with value: 0.9498622985327424 and parameters: {'n_estimators': 250, 'learning_rate': 0.04585078435019672, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 56, 'subsample': 0.7642093969728091, 'colsample_bytree': 0.7426191967932924, 'reg_alpha': 19.91255989922833, 'reg_lambda': 13.03522251158571}. Best is trial 192 with value: 0.9498676328276904.
[I 2026-05-19 12:10:50,243] Trial 221 finished with value: 0.9498629509071203 and parameters: {'n_estimators': 248, 'learning_rate': 0.04541498405819887, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 50, 'subsample': 0.7642922573845504, 'colsample_bytree': 0.7433840519058232, 'reg_alpha': 7.113273585928224, 'reg_lambda': 0.05190827746230234}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  44%|████████████████████████████████████████████████▊                                                             | 222/500 [15:29<16:53,  3.65s/it]

[I 2026-05-19 12:10:57,459] Trial 219 finished with value: 0.9498539034957283 and parameters: {'n_estimators': 261, 'learning_rate': 0.045029388853873385, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 59, 'subsample': 0.7666018551509289, 'colsample_bytree': 0.9772965102120619, 'reg_alpha': 8.040742503307467, 'reg_lambda': 0.5537413450040837}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  45%|█████████████████████████████████████████████████                                                             | 223/500 [15:40<26:24,  5.72s/it]

[I 2026-05-19 12:11:08,178] Trial 222 finished with value: 0.9498592218561981 and parameters: {'n_estimators': 249, 'learning_rate': 0.04605063561397224, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 53, 'subsample': 0.7663493808056845, 'colsample_bytree': 0.775258803617091, 'reg_alpha': 19.861607898935546, 'reg_lambda': 0.3580749413010909}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  45%|█████████████████████████████████████████████████▎                                                            | 224/500 [15:46<26:20,  5.72s/it]

[I 2026-05-19 12:11:13,925] Trial 223 finished with value: 0.9497864336342179 and parameters: {'n_estimators': 232, 'learning_rate': 0.01858679002086478, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 52, 'subsample': 0.92107435619654, 'colsample_bytree': 0.74753605043583, 'reg_alpha': 21.069481221227864, 'reg_lambda': 0.04021323857585611}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  45%|█████████████████████████████████████████████████▌                                                            | 225/500 [15:47<19:50,  4.33s/it]

[I 2026-05-19 12:11:14,929] Trial 224 finished with value: 0.949861820029182 and parameters: {'n_estimators': 249, 'learning_rate': 0.046284745732431826, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 52, 'subsample': 0.7663871025289123, 'colsample_bytree': 0.7183307755611384, 'reg_alpha': 20.78118071130564, 'reg_lambda': 0.04794942964460483}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  45%|█████████████████████████████████████████████████▋                                                            | 226/500 [16:05<38:10,  8.36s/it]

[I 2026-05-19 12:11:32,808] Trial 225 finished with value: 0.9498593728467828 and parameters: {'n_estimators': 250, 'learning_rate': 0.04494512317066913, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 49, 'subsample': 0.7837199068328642, 'colsample_bytree': 0.7799487840044752, 'reg_alpha': 6.97189456625336, 'reg_lambda': 0.05008361424320837}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  45%|█████████████████████████████████████████████████▉                                                            | 227/500 [16:05<28:00,  6.16s/it]

[I 2026-05-19 12:11:33,786] Trial 227 finished with value: 0.9498571322470765 and parameters: {'n_estimators': 240, 'learning_rate': 0.0422683928604415, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 48, 'subsample': 0.7833241284585627, 'colsample_bytree': 0.7721367341072916, 'reg_alpha': 7.479683067505057, 'reg_lambda': 13.5856912257571}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  46%|██████████████████████████████████████████████████▏                                                           | 228/500 [16:07<21:42,  4.79s/it]

[I 2026-05-19 12:11:35,352] Trial 226 finished with value: 0.9498671858227752 and parameters: {'n_estimators': 250, 'learning_rate': 0.04501382013456509, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 53, 'subsample': 0.9150963673057565, 'colsample_bytree': 0.7739171380930154, 'reg_alpha': 7.830482413265366, 'reg_lambda': 15.14003944252463}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  46%|██████████████████████████████████████████████████▍                                                           | 229/500 [16:08<16:48,  3.72s/it]

[I 2026-05-19 12:11:36,555] Trial 228 finished with value: 0.9498542053219425 and parameters: {'n_estimators': 239, 'learning_rate': 0.04193657169202769, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 50, 'subsample': 0.7836616899539803, 'colsample_bytree': 0.777646276139297, 'reg_alpha': 21.029904677296148, 'reg_lambda': 0.7029527400786743}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  46%|██████████████████████████████████████████████████▌                                                           | 230/500 [16:10<14:36,  3.25s/it]

[I 2026-05-19 12:11:38,719] Trial 230 finished with value: 0.9498588155698183 and parameters: {'n_estimators': 238, 'learning_rate': 0.043289548016159765, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 46, 'subsample': 0.7537089121330066, 'colsample_bytree': 0.7187052362683466, 'reg_alpha': 20.633739412933842, 'reg_lambda': 13.113303951306683}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  46%|██████████████████████████████████████████████████▊                                                           | 231/500 [16:12<12:46,  2.85s/it]

[I 2026-05-19 12:11:40,635] Trial 229 finished with value: 0.9498542320028761 and parameters: {'n_estimators': 250, 'learning_rate': 0.042392242508453776, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 45, 'subsample': 0.7840514625012073, 'colsample_bytree': 0.7016638894836892, 'reg_alpha': 21.20267656670181, 'reg_lambda': 14.927207220406197}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  46%|███████████████████████████████████████████████████                                                           | 232/500 [16:17<14:47,  3.31s/it]

[I 2026-05-19 12:11:45,014] Trial 231 finished with value: 0.9498587637651266 and parameters: {'n_estimators': 249, 'learning_rate': 0.04222795750683574, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 54, 'subsample': 0.7533738581915428, 'colsample_bytree': 0.714206368963069, 'reg_alpha': 6.971165602585562, 'reg_lambda': 0.721271444649336}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  47%|███████████████████████████████████████████████████▎                                                          | 233/500 [16:19<12:49,  2.88s/it]

[I 2026-05-19 12:11:46,924] Trial 232 finished with value: 0.9497889756138542 and parameters: {'n_estimators': 251, 'learning_rate': 0.017928078569883, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 44, 'subsample': 0.7835548270551762, 'colsample_bytree': 0.715736716358252, 'reg_alpha': 21.864033665331622, 'reg_lambda': 0.044416023466061764}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  47%|███████████████████████████████████████████████████▍                                                          | 234/500 [16:25<17:48,  4.02s/it]

[I 2026-05-19 12:11:53,585] Trial 233 finished with value: 0.9498546207839424 and parameters: {'n_estimators': 249, 'learning_rate': 0.04201931894835065, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 48, 'subsample': 0.7834665735976668, 'colsample_bytree': 0.7754462745906222, 'reg_alpha': 22.436153990004907, 'reg_lambda': 15.71211318693384}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  47%|███████████████████████████████████████████████████▋                                                          | 235/500 [16:29<17:49,  4.03s/it]

[I 2026-05-19 12:11:57,649] Trial 234 finished with value: 0.9498595906189582 and parameters: {'n_estimators': 239, 'learning_rate': 0.04216744033428752, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 48, 'subsample': 0.7831476342081091, 'colsample_bytree': 0.7103069334768979, 'reg_alpha': 6.525651392164207, 'reg_lambda': 12.623233771901468}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  47%|███████████████████████████████████████████████████▉                                                          | 236/500 [16:36<21:27,  4.88s/it]

[I 2026-05-19 12:12:04,491] Trial 235 finished with value: 0.9498566987403365 and parameters: {'n_estimators': 249, 'learning_rate': 0.04191629042779044, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 47, 'subsample': 0.7529589200001713, 'colsample_bytree': 0.7369195033441283, 'reg_alpha': 17.07513199751132, 'reg_lambda': 14.450067114685643}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  47%|████████████████████████████████████████████████████▏                                                         | 237/500 [16:43<24:22,  5.56s/it]

[I 2026-05-19 12:12:11,651] Trial 236 finished with value: 0.9498586286209451 and parameters: {'n_estimators': 249, 'learning_rate': 0.042299439306344735, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 46, 'subsample': 0.7519967204342167, 'colsample_bytree': 0.7151706356661764, 'reg_alpha': 7.489103425420705, 'reg_lambda': 0.04596192955833977}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  48%|████████████████████████████████████████████████████▎                                                         | 238/500 [16:45<19:41,  4.51s/it]

[I 2026-05-19 12:12:13,706] Trial 238 finished with value: 0.9498273743369309 and parameters: {'n_estimators': 249, 'learning_rate': 0.041777036776997366, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 45, 'subsample': 0.747177419686436, 'colsample_bytree': 0.7098004712348585, 'reg_alpha': 24.981081574241294, 'reg_lambda': 6.674768466220318}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  48%|████████████████████████████████████████████████████▌                                                         | 239/500 [16:49<18:28,  4.25s/it]

[I 2026-05-19 12:12:17,343] Trial 242 finished with value: 0.949835854058404 and parameters: {'n_estimators': 247, 'learning_rate': 0.04693123238372561, 'max_depth': 4, 'num_leaves': 4, 'min_child_samples': 42, 'subsample': 0.7499337392953055, 'colsample_bytree': 0.7425231933625009, 'reg_alpha': 7.312441056209411, 'reg_lambda': 0.2178753159493209}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  48%|████████████████████████████████████████████████████▊                                                         | 240/500 [16:51<15:51,  3.66s/it]

[I 2026-05-19 12:12:19,634] Trial 237 finished with value: 0.949860525591775 and parameters: {'n_estimators': 239, 'learning_rate': 0.04222828857069913, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 44, 'subsample': 0.7533927345833619, 'colsample_bytree': 0.7138963783356086, 'reg_alpha': 6.985972961784969, 'reg_lambda': 0.09749956774688573}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  48%|█████████████████████████████████████████████████████                                                         | 241/500 [17:02<24:16,  5.62s/it]

[I 2026-05-19 12:12:29,813] Trial 240 finished with value: 0.9498573204290295 and parameters: {'n_estimators': 249, 'learning_rate': 0.042492993944852106, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 57, 'subsample': 0.7542088585878745, 'colsample_bytree': 0.713154109034537, 'reg_alpha': 26.471846648110393, 'reg_lambda': 0.06889593883401968}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  48%|█████████████████████████████████████████████████████▏                                                        | 242/500 [17:03<18:14,  4.24s/it]

[I 2026-05-19 12:12:30,853] Trial 239 finished with value: 0.9498582124762087 and parameters: {'n_estimators': 251, 'learning_rate': 0.04332991182818245, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 43, 'subsample': 0.7499492665902175, 'colsample_bytree': 0.7031686769246073, 'reg_alpha': 24.191211099096765, 'reg_lambda': 0.7560690220438896}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  49%|█████████████████████████████████████████████████████▍                                                        | 243/500 [17:03<13:00,  3.04s/it]

[I 2026-05-19 12:12:31,084] Trial 241 finished with value: 0.9498613044457794 and parameters: {'n_estimators': 250, 'learning_rate': 0.04227909056992116, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 40, 'subsample': 0.7532114947616539, 'colsample_bytree': 0.7393249514607397, 'reg_alpha': 7.41786863688622, 'reg_lambda': 0.038664918263299757}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  49%|█████████████████████████████████████████████████████▋                                                        | 244/500 [17:08<15:16,  3.58s/it]

[I 2026-05-19 12:12:35,939] Trial 244 finished with value: 0.9498586990764221 and parameters: {'n_estimators': 244, 'learning_rate': 0.04658113761806632, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 61, 'subsample': 0.9140101929856624, 'colsample_bytree': 0.6853155669288945, 'reg_alpha': 15.250849757349302, 'reg_lambda': 0.07032284862279521}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  49%|█████████████████████████████████████████████████████▉                                                        | 245/500 [17:10<13:30,  3.18s/it]

[I 2026-05-19 12:12:38,169] Trial 243 finished with value: 0.949865523771703 and parameters: {'n_estimators': 245, 'learning_rate': 0.046902888470480034, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 29, 'subsample': 0.9139424808088696, 'colsample_bytree': 0.8100948636362991, 'reg_alpha': 16.05604272588294, 'reg_lambda': 0.04428241138313222}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  49%|██████████████████████████████████████████████████████                                                        | 246/500 [17:18<19:12,  4.54s/it]

[I 2026-05-19 12:12:45,888] Trial 246 finished with value: 0.9498610482518375 and parameters: {'n_estimators': 244, 'learning_rate': 0.046661736265730946, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 38, 'subsample': 0.9313791353137033, 'colsample_bytree': 0.6851454015903453, 'reg_alpha': 8.653506159601816, 'reg_lambda': 7.882225729108007}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  49%|██████████████████████████████████████████████████████▎                                                       | 247/500 [17:19<14:48,  3.51s/it]

[I 2026-05-19 12:12:47,006] Trial 245 finished with value: 0.9498667067504296 and parameters: {'n_estimators': 245, 'learning_rate': 0.046950716034427964, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 40, 'subsample': 0.9186954959119188, 'colsample_bytree': 0.7350443375227629, 'reg_alpha': 13.709253373870753, 'reg_lambda': 0.06875519059114149}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  50%|██████████████████████████████████████████████████████▌                                                       | 248/500 [17:25<18:16,  4.35s/it]

[I 2026-05-19 12:12:53,306] Trial 248 finished with value: 0.9498075435050829 and parameters: {'n_estimators': 258, 'learning_rate': 0.04647507967957813, 'max_depth': 4, 'num_leaves': 4, 'min_child_samples': 36, 'subsample': 0.9135130006851353, 'colsample_bytree': 0.795407865260677, 'reg_alpha': 48.83824709556813, 'reg_lambda': 8.128460575743533}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  50%|██████████████████████████████████████████████████████▊                                                       | 249/500 [17:37<28:19,  6.77s/it]

[I 2026-05-19 12:13:05,727] Trial 247 finished with value: 0.9498562303772113 and parameters: {'n_estimators': 259, 'learning_rate': 0.047091458562821153, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 59, 'subsample': 0.9188196414499784, 'colsample_bytree': 0.6924899779443093, 'reg_alpha': 14.760210089832377, 'reg_lambda': 0.2214785353714691}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  50%|███████████████████████████████████████████████████████                                                       | 250/500 [17:43<26:24,  6.34s/it]

[I 2026-05-19 12:13:11,032] Trial 250 finished with value: 0.9498644167684794 and parameters: {'n_estimators': 243, 'learning_rate': 0.04682364633203297, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 71, 'subsample': 0.7732483924604934, 'colsample_bytree': 0.6808695811788383, 'reg_alpha': 16.322847835243394, 'reg_lambda': 0.09250936168523786}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  50%|███████████████████████████████████████████████████████▏                                                      | 251/500 [17:45<21:18,  5.13s/it]

[I 2026-05-19 12:13:13,380] Trial 249 finished with value: 0.9498481161798498 and parameters: {'n_estimators': 260, 'learning_rate': 0.04690838540374905, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 26, 'subsample': 0.9149756212203612, 'colsample_bytree': 0.7931350474992311, 'reg_alpha': 44.76180732316136, 'reg_lambda': 0.09767232130019769}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  50%|███████████████████████████████████████████████████████▍                                                      | 252/500 [17:49<19:47,  4.79s/it]

[I 2026-05-19 12:13:17,357] Trial 251 finished with value: 0.9498628275841071 and parameters: {'n_estimators': 261, 'learning_rate': 0.046955741893227494, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 21, 'subsample': 0.9129545675365971, 'colsample_bytree': 0.7940712574715835, 'reg_alpha': 14.977813643063676, 'reg_lambda': 32.01030170643164}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  51%|███████████████████████████████████████████████████████▋                                                      | 253/500 [18:00<26:44,  6.50s/it]

[I 2026-05-19 12:13:27,850] Trial 252 finished with value: 0.9498655326533051 and parameters: {'n_estimators': 261, 'learning_rate': 0.04730969272333788, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 37, 'subsample': 0.9281695361222274, 'colsample_bytree': 0.7228598973109305, 'reg_alpha': 14.870222810484838, 'reg_lambda': 0.035785719159230955}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  51%|███████████████████████████████████████████████████████▉                                                      | 254/500 [18:00<19:22,  4.72s/it]

[I 2026-05-19 12:13:28,433] Trial 253 finished with value: 0.9498593286397012 and parameters: {'n_estimators': 259, 'learning_rate': 0.04693950583595764, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 71, 'subsample': 0.9107675126722442, 'colsample_bytree': 0.6832333438579508, 'reg_alpha': 14.487541871015157, 'reg_lambda': 0.09773046721712017}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  51%|████████████████████████████████████████████████████████▎                                                     | 256/500 [18:02<10:42,  2.63s/it]

[I 2026-05-19 12:13:29,674] Trial 254 finished with value: 0.9498646285152468 and parameters: {'n_estimators': 259, 'learning_rate': 0.046980630933344425, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 37, 'subsample': 0.7711215793475744, 'colsample_bytree': 0.7315714588100445, 'reg_alpha': 14.737579463272388, 'reg_lambda': 0.026238263240106717}. Best is trial 192 with value: 0.9498676328276904.
[I 2026-05-19 12:13:29,840] Trial 255 finished with value: 0.9498583504714968 and parameters: {'n_estimators': 260, 'learning_rate': 0.04698551001768565, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 71, 'subsample': 0.7725625814434014, 'colsample_bytree': 0.7253198251842202, 'reg_alpha': 14.245795383653265, 'reg_lambda': 0.025555561264119925}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  51%|████████████████████████████████████████████████████████▌                                                     | 257/500 [18:05<11:39,  2.88s/it]

[I 2026-05-19 12:13:33,325] Trial 256 finished with value: 0.9498634590937745 and parameters: {'n_estimators': 258, 'learning_rate': 0.04686401947980984, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 34, 'subsample': 0.7686969217313112, 'colsample_bytree': 0.7249606120057913, 'reg_alpha': 15.33159773506321, 'reg_lambda': 0.02653300975455267}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  52%|████████████████████████████████████████████████████████▊                                                     | 258/500 [18:12<16:57,  4.21s/it]

[I 2026-05-19 12:13:40,612] Trial 257 finished with value: 0.9498639004290883 and parameters: {'n_estimators': 259, 'learning_rate': 0.04697052013149115, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 55, 'subsample': 0.9108275864749424, 'colsample_bytree': 0.8092118689982267, 'reg_alpha': 14.338507111338538, 'reg_lambda': 0.037389396805123536}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  52%|████████████████████████████████████████████████████████▉                                                     | 259/500 [18:13<12:55,  3.22s/it]

[I 2026-05-19 12:13:41,527] Trial 258 finished with value: 0.9498504891918153 and parameters: {'n_estimators': 257, 'learning_rate': 0.04495868384847734, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 29, 'subsample': 0.9150412090394336, 'colsample_bytree': 0.7238123615442765, 'reg_alpha': 48.94959332280459, 'reg_lambda': 0.023962413484758995}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  52%|█████████████████████████████████████████████████████████▏                                                    | 260/500 [18:22<19:46,  4.94s/it]

[I 2026-05-19 12:13:50,493] Trial 259 finished with value: 0.9498629648950025 and parameters: {'n_estimators': 259, 'learning_rate': 0.045108332437727085, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 21, 'subsample': 0.923308628519046, 'colsample_bytree': 0.7536633479373486, 'reg_alpha': 15.101869721093998, 'reg_lambda': 0.10706310579487921}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  52%|█████████████████████████████████████████████████████████▍                                                    | 261/500 [18:34<28:21,  7.12s/it]

[I 2026-05-19 12:14:02,695] Trial 260 finished with value: 0.9498612534856792 and parameters: {'n_estimators': 261, 'learning_rate': 0.04415203350655359, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 33, 'subsample': 0.9392969741834695, 'colsample_bytree': 0.7524502316568065, 'reg_alpha': 9.187049252758019, 'reg_lambda': 0.025356389551119244}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 192. Best value: 0.949868:  52%|█████████████████████████████████████████████████████████▋                                                    | 262/500 [18:37<22:42,  5.72s/it]

[I 2026-05-19 12:14:05,144] Trial 262 finished with value: 0.9498641172015267 and parameters: {'n_estimators': 241, 'learning_rate': 0.04460345358880641, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 67, 'subsample': 0.7733721476327977, 'colsample_bytree': 0.7516800882956834, 'reg_alpha': 15.736837473874305, 'reg_lambda': 0.05168246347843221}. Best is trial 192 with value: 0.9498676328276904.

Best trial: 261. Best value: 0.949869:  53%|█████████████████████████████████████████████████████████▊                                                    | 263/500 [18:38<16:57,  4.29s/it]

[I 2026-05-19 12:14:06,128] Trial 261 finished with value: 0.9498692400511732 and parameters: {'n_estimators': 262, 'learning_rate': 0.044869749336608866, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 69, 'subsample': 0.9310314984928566, 'colsample_bytree': 0.6495674872472957, 'reg_alpha': 15.319032809516834, 'reg_lambda': 0.030118029827057136}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  53%|██████████████████████████████████████████████████████████                                                    | 264/500 [18:44<19:15,  4.90s/it]

[I 2026-05-19 12:14:12,426] Trial 263 finished with value: 0.9498565475843239 and parameters: {'n_estimators': 236, 'learning_rate': 0.04458907257295002, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 22, 'subsample': 0.774590487094008, 'colsample_bytree': 0.6658713149508757, 'reg_alpha': 9.905136567419337, 'reg_lambda': 0.05362361628020906}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  53%|██████████████████████████████████████████████████████████▎                                                   | 265/500 [18:51<21:33,  5.51s/it]

[I 2026-05-19 12:14:19,347] Trial 266 finished with value: 0.9498273741287822 and parameters: {'n_estimators': 233, 'learning_rate': 0.044765410447600566, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 27, 'subsample': 0.9267922851074003, 'colsample_bytree': 0.726129950049585, 'reg_alpha': 0.021562230142054453, 'reg_lambda': 0.020099429140738943}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  53%|██████████████████████████████████████████████████████████▌                                                   | 266/500 [18:52<16:27,  4.22s/it]

[I 2026-05-19 12:14:20,562] Trial 265 finished with value: 0.9498667344236678 and parameters: {'n_estimators': 263, 'learning_rate': 0.04473999318310658, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 27, 'subsample': 0.928665823779164, 'colsample_bytree': 0.6440411422780816, 'reg_alpha': 10.096375481043978, 'reg_lambda': 0.034069846773106933}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  53%|██████████████████████████████████████████████████████████▋                                                   | 267/500 [18:53<12:38,  3.26s/it]

[I 2026-05-19 12:14:21,581] Trial 267 finished with value: 0.9498625997864425 and parameters: {'n_estimators': 234, 'learning_rate': 0.04515835050797687, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 25, 'subsample': 0.9251612217804535, 'colsample_bytree': 0.8089744418476005, 'reg_alpha': 10.085417824545125, 'reg_lambda': 0.022187603881868214}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  54%|██████████████████████████████████████████████████████████▉                                                   | 268/500 [18:54<09:33,  2.47s/it]

[I 2026-05-19 12:14:22,216] Trial 264 finished with value: 0.9498405048839178 and parameters: {'n_estimators': 264, 'learning_rate': 0.044665805004879926, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 25, 'subsample': 0.9466837438968688, 'colsample_bytree': 0.7272539645338655, 'reg_alpha': 0.0001192199673349886, 'reg_lambda': 0.023701308732383686}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  54%|███████████████████████████████████████████████████████████▏                                                  | 269/500 [19:03<17:23,  4.52s/it]

[I 2026-05-19 12:14:31,520] Trial 268 finished with value: 0.9498671115227003 and parameters: {'n_estimators': 264, 'learning_rate': 0.04406842745718632, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 32, 'subsample': 0.9292576275783885, 'colsample_bytree': 0.6473208850389207, 'reg_alpha': 9.751045320487496, 'reg_lambda': 0.02003886008431179}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  54%|███████████████████████████████████████████████████████████▍                                                  | 270/500 [19:07<16:21,  4.27s/it]

[I 2026-05-19 12:14:35,185] Trial 269 finished with value: 0.9498665374520838 and parameters: {'n_estimators': 262, 'learning_rate': 0.04475178316645299, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 27, 'subsample': 0.7735848724310065, 'colsample_bytree': 0.7315554629457006, 'reg_alpha': 9.657286670744654, 'reg_lambda': 0.023596277885066075}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  54%|███████████████████████████████████████████████████████████▌                                                  | 271/500 [19:10<14:36,  3.83s/it]

[I 2026-05-19 12:14:38,008] Trial 270 finished with value: 0.9498601752201689 and parameters: {'n_estimators': 264, 'learning_rate': 0.04440777025253845, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 24, 'subsample': 0.9277175762966705, 'colsample_bytree': 0.6551721701964278, 'reg_alpha': 9.592107877923882, 'reg_lambda': 0.02958332207478437}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  54%|███████████████████████████████████████████████████████████▊                                                  | 272/500 [19:21<22:32,  5.93s/it]

[I 2026-05-19 12:14:48,830] Trial 271 finished with value: 0.9498681581502988 and parameters: {'n_estimators': 265, 'learning_rate': 0.04485838924893759, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 22, 'subsample': 0.926452082359969, 'colsample_bytree': 0.6560550146934034, 'reg_alpha': 10.278954960154985, 'reg_lambda': 0.032887267148525044}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  55%|████████████████████████████████████████████████████████████                                                  | 273/500 [19:30<26:43,  7.07s/it]

[I 2026-05-19 12:14:58,559] Trial 272 finished with value: 0.94986734112256 and parameters: {'n_estimators': 264, 'learning_rate': 0.04987516061564344, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 21, 'subsample': 0.9307336534354695, 'colsample_bytree': 0.6615971335558168, 'reg_alpha': 10.63095940896277, 'reg_lambda': 0.03687414149908073}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  55%|████████████████████████████████████████████████████████████▎                                                 | 274/500 [19:32<20:40,  5.49s/it]

[I 2026-05-19 12:15:00,361] Trial 273 finished with value: 0.949863804989581 and parameters: {'n_estimators': 264, 'learning_rate': 0.0443403375069987, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.940564431119201, 'colsample_bytree': 0.6356709853932335, 'reg_alpha': 11.25013310341685, 'reg_lambda': 0.03571813987982498}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  55%|████████████████████████████████████████████████████████████▌                                                 | 275/500 [19:35<17:18,  4.62s/it]

[I 2026-05-19 12:15:02,932] Trial 275 finished with value: 0.9498691578696791 and parameters: {'n_estimators': 232, 'learning_rate': 0.04994873568288209, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 29, 'subsample': 0.9249745600543327, 'colsample_bytree': 0.6250674769083555, 'reg_alpha': 11.884115828853917, 'reg_lambda': 0.03877602314061188}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  55%|████████████████████████████████████████████████████████████▋                                                 | 276/500 [19:35<12:24,  3.33s/it]

[I 2026-05-19 12:15:03,262] Trial 274 finished with value: 0.949861011014046 and parameters: {'n_estimators': 265, 'learning_rate': 0.049712370489689114, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 21, 'subsample': 0.9331487805240901, 'colsample_bytree': 0.6544540924196967, 'reg_alpha': 10.553931045243793, 'reg_lambda': 0.03436443382897748}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 261. Best value: 0.949869:  56%|█████████████████████████████████████████████████████████████▏                                                | 278/500 [19:43<12:00,  3.25s/it]

[I 2026-05-19 12:15:10,717] Trial 276 finished with value: 0.9498614631214352 and parameters: {'n_estimators': 255, 'learning_rate': 0.049826255665411934, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 34, 'subsample': 0.9283840489450143, 'colsample_bytree': 0.731618056886564, 'reg_alpha': 11.248851876249324, 'reg_lambda': 0.029372407493985415}. Best is trial 261 with value: 0.9498692400511732.
[I 2026-05-19 12:15:10,862] Trial 277 finished with value: 0.9498673332798047 and parameters: {'n_estimators': 266, 'learning_rate': 0.049645306129059916, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 31, 'subsample': 0.9362905704070147, 'colsample_bytree': 0.6411087868286995, 'reg_alpha': 11.609695764183595, 'reg_lambda': 0.032596919448316296}. Best is trial 261 with value: 0.9498692400511732.

Best trial: 278. Best value: 0.94987:  56%|█████████████████████████████████████████████████████████████▉                                                 | 279/500 [19:48<14:12,  3.86s/it]

[I 2026-05-19 12:15:16,164] Trial 278 finished with value: 0.9498696453127563 and parameters: {'n_estimators': 263, 'learning_rate': 0.049551544146696415, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 29, 'subsample': 0.9316781089323378, 'colsample_bytree': 0.6437269691157212, 'reg_alpha': 11.699361366575193, 'reg_lambda': 0.012175431321308872}. Best is trial 278 with value: 0.9498696453127563.

Best trial: 278. Best value: 0.94987:  56%|██████████████████████████████████████████████████████████████▏                                                | 280/500 [19:56<19:18,  5.27s/it]

[I 2026-05-19 12:15:24,715] Trial 279 finished with value: 0.9496415893936746 and parameters: {'n_estimators': 266, 'learning_rate': 0.006363861516340445, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 31, 'subsample': 0.937675686552208, 'colsample_bytree': 0.635869719357159, 'reg_alpha': 12.04434868124898, 'reg_lambda': 0.03699359188177722}. Best is trial 278 with value: 0.9498696453127563.

Best trial: 278. Best value: 0.94987:  56%|██████████████████████████████████████████████████████████████▍                                                | 281/500 [19:58<15:00,  4.11s/it]

[I 2026-05-19 12:15:26,122] Trial 280 finished with value: 0.9498637164308624 and parameters: {'n_estimators': 267, 'learning_rate': 0.049740938207910604, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 34, 'subsample': 0.9351462563811326, 'colsample_bytree': 0.647803334069519, 'reg_alpha': 5.196197670156377, 'reg_lambda': 0.027722912189022734}. Best is trial 278 with value: 0.9498696453127563.

Best trial: 278. Best value: 0.94987:  56%|██████████████████████████████████████████████████████████████▌                                                | 282/500 [19:58<10:42,  2.95s/it]

[I 2026-05-19 12:15:26,357] Trial 281 finished with value: 0.9498666764646556 and parameters: {'n_estimators': 267, 'learning_rate': 0.04953593233533164, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 33, 'subsample': 0.9358133826444427, 'colsample_bytree': 0.6296623356464702, 'reg_alpha': 11.453136841592826, 'reg_lambda': 0.012809031398715727}. Best is trial 278 with value: 0.9498696453127563.

Best trial: 278. Best value: 0.94987:  57%|██████████████████████████████████████████████████████████████▊                                                | 283/500 [20:01<11:02,  3.05s/it]

[I 2026-05-19 12:15:29,660] Trial 282 finished with value: 0.9498682520783625 and parameters: {'n_estimators': 265, 'learning_rate': 0.04993671720602657, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 31, 'subsample': 0.9439605335877699, 'colsample_bytree': 0.6320788692294574, 'reg_alpha': 5.384762032596433, 'reg_lambda': 0.03581296595834834}. Best is trial 278 with value: 0.9498696453127563.

Best trial: 283. Best value: 0.949873:  57%|██████████████████████████████████████████████████████████████▍                                               | 284/500 [20:16<24:01,  6.67s/it]

[I 2026-05-19 12:15:44,795] Trial 283 finished with value: 0.9498732594942114 and parameters: {'n_estimators': 266, 'learning_rate': 0.04942916813691308, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 32, 'subsample': 0.9422295765850754, 'colsample_bytree': 0.6335149932265012, 'reg_alpha': 5.245105599327132, 'reg_lambda': 0.0345686655554487}. Best is trial 283 with value: 0.9498732594942114.

Best trial: 283. Best value: 0.949873:  57%|██████████████████████████████████████████████████████████████▋                                               | 285/500 [20:23<23:38,  6.60s/it]

[I 2026-05-19 12:15:51,206] Trial 284 finished with value: 0.9498723379599566 and parameters: {'n_estimators': 265, 'learning_rate': 0.0496668355055678, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 32, 'subsample': 0.9414580471376373, 'colsample_bytree': 0.6321111648516718, 'reg_alpha': 4.948294267530205, 'reg_lambda': 0.010555849193562885}. Best is trial 283 with value: 0.9498732594942114.

Best trial: 283. Best value: 0.949873:  57%|██████████████████████████████████████████████████████████████▉                                               | 286/500 [20:27<20:47,  5.83s/it]

[I 2026-05-19 12:15:55,227] Trial 285 finished with value: 0.9498593660731561 and parameters: {'n_estimators': 266, 'learning_rate': 0.04996670973014373, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 247, 'subsample': 0.9395829530167491, 'colsample_bytree': 0.657150942688917, 'reg_alpha': 5.3753561472840055, 'reg_lambda': 0.012663730375651454}. Best is trial 283 with value: 0.9498732594942114.

Best trial: 283. Best value: 0.949873:  57%|███████████████████████████████████████████████████████████████▏                                              | 287/500 [20:29<16:47,  4.73s/it]

[I 2026-05-19 12:15:57,395] Trial 287 finished with value: 0.9498646746927305 and parameters: {'n_estimators': 254, 'learning_rate': 0.04949898025917847, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 32, 'subsample': 0.9471914537291843, 'colsample_bytree': 0.6222811463979226, 'reg_alpha': 4.206786023092363, 'reg_lambda': 0.01827447987400323}. Best is trial 283 with value: 0.9498732594942114.

Best trial: 286. Best value: 0.949875:  58%|███████████████████████████████████████████████████████████████▎                                              | 288/500 [20:31<13:35,  3.85s/it]

[I 2026-05-19 12:15:59,194] Trial 286 finished with value: 0.9498753425732973 and parameters: {'n_estimators': 264, 'learning_rate': 0.04988723993993441, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 33, 'subsample': 0.9378306380798972, 'colsample_bytree': 0.6226095012834436, 'reg_alpha': 5.126147127831397, 'reg_lambda': 0.06618224883283678}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  58%|███████████████████████████████████████████████████████████████▌                                              | 289/500 [20:36<15:03,  4.28s/it]

[I 2026-05-19 12:16:04,482] Trial 288 finished with value: 0.9498666492472237 and parameters: {'n_estimators': 266, 'learning_rate': 0.04995287232035334, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.9409042125175339, 'colsample_bytree': 0.6722179605156968, 'reg_alpha': 5.450403589549113, 'reg_lambda': 0.010624047393232434}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  58%|███████████████████████████████████████████████████████████████▊                                              | 290/500 [20:38<12:08,  3.47s/it]

[I 2026-05-19 12:16:06,063] Trial 289 finished with value: 0.9498671705305621 and parameters: {'n_estimators': 265, 'learning_rate': 0.049856284020709817, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 31, 'subsample': 0.943800168288808, 'colsample_bytree': 0.6245371423565557, 'reg_alpha': 16.08246834022262, 'reg_lambda': 0.010846921647184293}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  58%|████████████████████████████████████████████████████████████████                                              | 291/500 [20:42<12:56,  3.71s/it]

[I 2026-05-19 12:16:10,340] Trial 290 finished with value: 0.9498705960511294 and parameters: {'n_estimators': 266, 'learning_rate': 0.04809264773681779, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 31, 'subsample': 0.942725413572529, 'colsample_bytree': 0.6216902819045795, 'reg_alpha': 5.62860858435446, 'reg_lambda': 0.012141874963936029}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  58%|████████████████████████████████████████████████████████████████▏                                             | 292/500 [20:50<17:43,  5.11s/it]

[I 2026-05-19 12:16:18,717] Trial 291 finished with value: 0.9498707127932564 and parameters: {'n_estimators': 266, 'learning_rate': 0.04986330674559437, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 38, 'subsample': 0.9432036267708468, 'colsample_bytree': 0.6509841448194486, 'reg_alpha': 5.784192314280828, 'reg_lambda': 0.011572116613582227}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  59%|████████████████████████████████████████████████████████████████▍                                             | 293/500 [20:52<14:10,  4.11s/it]

[I 2026-05-19 12:16:20,479] Trial 292 finished with value: 0.9498580937029242 and parameters: {'n_estimators': 266, 'learning_rate': 0.047985340406723795, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 38, 'subsample': 0.9379866047417756, 'colsample_bytree': 0.6668096318720896, 'reg_alpha': 5.758141136976569, 'reg_lambda': 0.014421885007791995}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  59%|████████████████████████████████████████████████████████████████▋                                             | 294/500 [20:54<11:31,  3.36s/it]

[I 2026-05-19 12:16:22,092] Trial 294 finished with value: 0.9498635204524207 and parameters: {'n_estimators': 267, 'learning_rate': 0.04808368519543179, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.9531273147109819, 'colsample_bytree': 0.6223633912622637, 'reg_alpha': 4.936715062734862, 'reg_lambda': 0.0181242338108944}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  59%|████████████████████████████████████████████████████████████████▉                                             | 295/500 [20:56<10:29,  3.07s/it]

[I 2026-05-19 12:16:24,486] Trial 293 finished with value: 0.9498610817604576 and parameters: {'n_estimators': 266, 'learning_rate': 0.0480628711068102, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 38, 'subsample': 0.9469793476010072, 'colsample_bytree': 0.6158131831264101, 'reg_alpha': 17.753897056568295, 'reg_lambda': 0.010433867201354021}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  59%|█████████████████████████████████████████████████████████████████                                             | 296/500 [21:09<20:37,  6.07s/it]

[I 2026-05-19 12:16:37,555] Trial 295 finished with value: 0.9498574979817338 and parameters: {'n_estimators': 271, 'learning_rate': 0.04988914818061903, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 38, 'subsample': 0.9509703200676163, 'colsample_bytree': 0.621874224432049, 'reg_alpha': 4.2473676205227004, 'reg_lambda': 0.0098419525379702}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  59%|█████████████████████████████████████████████████████████████████▎                                            | 297/500 [21:19<23:52,  7.06s/it]

[I 2026-05-19 12:16:46,919] Trial 297 finished with value: 0.9498611235029447 and parameters: {'n_estimators': 266, 'learning_rate': 0.047673975257748386, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 29, 'subsample': 0.9522308547839745, 'colsample_bytree': 0.6470537311546523, 'reg_alpha': 4.604887306188105, 'reg_lambda': 0.010460731405219727}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  60%|█████████████████████████████████████████████████████████████████▌                                            | 298/500 [21:20<17:58,  5.34s/it]

[I 2026-05-19 12:16:48,246] Trial 296 finished with value: 0.9498653441668733 and parameters: {'n_estimators': 271, 'learning_rate': 0.048066906733236096, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 39, 'subsample': 0.948294757201076, 'colsample_bytree': 0.6218408153663636, 'reg_alpha': 4.428428794664794, 'reg_lambda': 0.01248300844131054}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  60%|█████████████████████████████████████████████████████████████████▊                                            | 299/500 [21:24<16:06,  4.81s/it]

[I 2026-05-19 12:16:51,820] Trial 298 finished with value: 0.9498609749437479 and parameters: {'n_estimators': 268, 'learning_rate': 0.047383334751245676, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 38, 'subsample': 0.9497638867295948, 'colsample_bytree': 0.6167861939158082, 'reg_alpha': 4.565956352902393, 'reg_lambda': 0.01107079315654636}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  60%|██████████████████████████████████████████████████████████████████▏                                           | 301/500 [21:27<10:36,  3.20s/it]

[I 2026-05-19 12:16:55,595] Trial 300 finished with value: 0.9498669130577276 and parameters: {'n_estimators': 268, 'learning_rate': 0.0499678342804464, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.9525598009972074, 'colsample_bytree': 0.6226617896598448, 'reg_alpha': 4.448370084760907, 'reg_lambda': 0.013264637575848053}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:16:55,746] Trial 299 finished with value: 0.9498657231374412 and parameters: {'n_estimators': 267, 'learning_rate': 0.04990723366317934, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 29, 'subsample': 0.9688813530570953, 'colsample_bytree': 0.62047374410433, 'reg_alpha': 6.048468539069436, 'reg_lambda': 0.010514081007296186}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  60%|██████████████████████████████████████████████████████████████████▍                                           | 302/500 [21:33<12:35,  3.81s/it]

[I 2026-05-19 12:17:01,004] Trial 301 finished with value: 0.9498590009706508 and parameters: {'n_estimators': 268, 'learning_rate': 0.047809809573969374, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 29, 'subsample': 0.949752587256695, 'colsample_bytree': 0.6198335010480495, 'reg_alpha': 4.461452239731497, 'reg_lambda': 0.01135841575251116}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  61%|██████████████████████████████████████████████████████████████████▋                                           | 303/500 [21:38<14:03,  4.28s/it]

[I 2026-05-19 12:17:06,383] Trial 302 finished with value: 0.9498647402763135 and parameters: {'n_estimators': 267, 'learning_rate': 0.04792503052089455, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 28, 'subsample': 0.9713436626089658, 'colsample_bytree': 0.6203156546799535, 'reg_alpha': 4.6673018896978125, 'reg_lambda': 0.012522032886336241}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  61%|██████████████████████████████████████████████████████████████████▉                                           | 304/500 [21:45<16:34,  5.07s/it]

[I 2026-05-19 12:17:13,307] Trial 307 finished with value: 0.9498300157025087 and parameters: {'n_estimators': 274, 'learning_rate': 0.039923030341848124, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 27, 'subsample': 0.9595952373653662, 'colsample_bytree': 0.6046015167945361, 'reg_alpha': 4.218113170523776, 'reg_lambda': 0.011279927680629192}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  61%|███████████████████████████████████████████████████████████████████                                           | 305/500 [21:48<14:08,  4.35s/it]

[I 2026-05-19 12:17:15,978] Trial 304 finished with value: 0.9498650845203642 and parameters: {'n_estimators': 272, 'learning_rate': 0.04999672459198847, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 29, 'subsample': 0.9561421018109442, 'colsample_bytree': 0.6274508049932656, 'reg_alpha': 3.6503315990125813, 'reg_lambda': 0.011132826887135313}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  61%|███████████████████████████████████████████████████████████████████▎                                          | 306/500 [21:49<10:45,  3.33s/it]

[I 2026-05-19 12:17:16,911] Trial 303 finished with value: 0.9498579784499965 and parameters: {'n_estimators': 268, 'learning_rate': 0.0400109071720119, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 28, 'subsample': 0.9557864381763685, 'colsample_bytree': 0.6199168694673288, 'reg_alpha': 4.527150474021878, 'reg_lambda': 0.011052233038639787}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  61%|███████████████████████████████████████████████████████████████████▌                                          | 307/500 [21:49<07:45,  2.41s/it]

[I 2026-05-19 12:17:17,137] Trial 305 finished with value: 0.949871344670169 and parameters: {'n_estimators': 273, 'learning_rate': 0.049889205225015526, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 28, 'subsample': 0.946642194979061, 'colsample_bytree': 0.605279722880495, 'reg_alpha': 3.9291246896591443, 'reg_lambda': 0.010629267098238127}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  62%|███████████████████████████████████████████████████████████████████▊                                          | 308/500 [21:55<11:19,  3.54s/it]

[I 2026-05-19 12:17:23,363] Trial 308 finished with value: 0.9498323379728735 and parameters: {'n_estimators': 272, 'learning_rate': 0.04392296493749132, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 27, 'subsample': 0.982222921964506, 'colsample_bytree': 0.605645714793974, 'reg_alpha': 5.557266869564012, 'reg_lambda': 0.005760340117892669}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  62%|███████████████████████████████████████████████████████████████████▉                                          | 309/500 [21:56<08:35,  2.70s/it]

[I 2026-05-19 12:17:24,067] Trial 306 finished with value: 0.9498597005026971 and parameters: {'n_estimators': 274, 'learning_rate': 0.04370579845711691, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 28, 'subsample': 0.9808567552910122, 'colsample_bytree': 0.6025360110407112, 'reg_alpha': 5.248595073841563, 'reg_lambda': 0.003921872141505885}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  62%|████████████████████████████████████████████████████████████████████▏                                         | 310/500 [22:14<23:26,  7.40s/it]

[I 2026-05-19 12:17:42,463] Trial 309 finished with value: 0.9498526556963558 and parameters: {'n_estimators': 272, 'learning_rate': 0.03977697688235513, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 28, 'subsample': 0.9668856177564275, 'colsample_bytree': 0.6299638039941604, 'reg_alpha': 5.914369650927769, 'reg_lambda': 0.0032852568450743697}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  62%|████████████████████████████████████████████████████████████████████▍                                         | 311/500 [22:18<19:37,  6.23s/it]

[I 2026-05-19 12:17:45,982] Trial 317 finished with value: 0.9497583425688445 and parameters: {'n_estimators': 276, 'learning_rate': 0.04380971195894132, 'max_depth': 1, 'num_leaves': 12, 'min_child_samples': 21, 'subsample': 0.9408516130671883, 'colsample_bytree': 0.639799715135524, 'reg_alpha': 6.246373810896638, 'reg_lambda': 0.004155086210115071}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  62%|████████████████████████████████████████████████████████████████████▋                                         | 312/500 [22:22<17:40,  5.64s/it]

[I 2026-05-19 12:17:50,210] Trial 319 finished with value: 0.9497594850805615 and parameters: {'n_estimators': 274, 'learning_rate': 0.04377691778628589, 'max_depth': 1, 'num_leaves': 12, 'min_child_samples': 23, 'subsample': 0.9402134658215011, 'colsample_bytree': 0.6427772564529991, 'reg_alpha': 5.957442172959927, 'reg_lambda': 0.00823841073029167}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  63%|████████████████████████████████████████████████████████████████████▊                                         | 313/500 [22:23<13:24,  4.30s/it]

[I 2026-05-19 12:17:51,427] Trial 310 finished with value: 0.9498563382621377 and parameters: {'n_estimators': 266, 'learning_rate': 0.03950146364136243, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 25, 'subsample': 0.9423509604207849, 'colsample_bytree': 0.6311708177694823, 'reg_alpha': 5.892838819695067, 'reg_lambda': 0.005275793193858692}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  63%|█████████████████████████████████████████████████████████████████████                                         | 314/500 [22:25<10:51,  3.50s/it]

[I 2026-05-19 12:17:53,058] Trial 311 finished with value: 0.9498593231676915 and parameters: {'n_estimators': 276, 'learning_rate': 0.04380625171791725, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 27, 'subsample': 0.9619733031457744, 'colsample_bytree': 0.6041765682862426, 'reg_alpha': 3.7760005794580094, 'reg_lambda': 0.004264362403174782}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  63%|█████████████████████████████████████████████████████████████████████▌                                        | 316/500 [22:27<07:03,  2.30s/it]

[I 2026-05-19 12:17:55,680] Trial 313 finished with value: 0.9498606184443398 and parameters: {'n_estimators': 274, 'learning_rate': 0.03905300482567785, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 24, 'subsample': 0.966257169561292, 'colsample_bytree': 0.6089597368930804, 'reg_alpha': 5.770691455320705, 'reg_lambda': 0.004112367998920202}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:17:55,767] Trial 312 finished with value: 0.9498656916344761 and parameters: {'n_estimators': 275, 'learning_rate': 0.03939169864251424, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 27, 'subsample': 0.9626481206028118, 'colsample_bytree': 0.6050009424903675, 'reg_alpha': 6.107596874018976, 'reg_lambda': 0.006983495765995117}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  63%|█████████████████████████████████████████████████████████████████████▋                                        | 317/500 [22:33<09:56,  3.26s/it]

[I 2026-05-19 12:18:01,297] Trial 314 finished with value: 0.9498579846411511 and parameters: {'n_estimators': 275, 'learning_rate': 0.04051370243219123, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 24, 'subsample': 0.9614867581988363, 'colsample_bytree': 0.6396460225588665, 'reg_alpha': 3.6624893687012405, 'reg_lambda': 0.00669643096062354}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  64%|█████████████████████████████████████████████████████████████████████▉                                        | 318/500 [22:42<14:42,  4.85s/it]

[I 2026-05-19 12:18:09,834] Trial 315 finished with value: 0.9498622087905192 and parameters: {'n_estimators': 276, 'learning_rate': 0.043679386935104786, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 20, 'subsample': 0.9702953015158925, 'colsample_bytree': 0.6337050143796769, 'reg_alpha': 5.875948539076853, 'reg_lambda': 0.006604757669225268}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  64%|██████████████████████████████████████████████████████████████████████▏                                       | 319/500 [22:43<11:52,  3.93s/it]

[I 2026-05-19 12:18:11,643] Trial 316 finished with value: 0.9498599929057896 and parameters: {'n_estimators': 275, 'learning_rate': 0.0440332780987841, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 20, 'subsample': 0.9702061873846153, 'colsample_bytree': 0.6381793502930853, 'reg_alpha': 6.0793071388052375, 'reg_lambda': 0.006669196325208866}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  64%|██████████████████████████████████████████████████████████████████████▍                                       | 320/500 [22:44<08:28,  2.83s/it]

[I 2026-05-19 12:18:11,899] Trial 318 finished with value: 0.9498556646569565 and parameters: {'n_estimators': 274, 'learning_rate': 0.0435903236604803, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 20, 'subsample': 0.9650768701663852, 'colsample_bytree': 0.639204862052296, 'reg_alpha': 5.8647439558634575, 'reg_lambda': 0.0038848567290421677}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  64%|██████████████████████████████████████████████████████████████████████▌                                       | 321/500 [22:52<13:28,  4.52s/it]

[I 2026-05-19 12:18:20,356] Trial 320 finished with value: 0.9498654422106515 and parameters: {'n_estimators': 265, 'learning_rate': 0.043845063843902445, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 23, 'subsample': 0.9642460295832384, 'colsample_bytree': 0.6385152729089764, 'reg_alpha': 7.013331890417037, 'reg_lambda': 0.0058536923771213755}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  64%|██████████████████████████████████████████████████████████████████████▊                                       | 322/500 [23:14<28:44,  9.69s/it]

[I 2026-05-19 12:18:42,114] Trial 322 finished with value: 0.9498572726409567 and parameters: {'n_estimators': 263, 'learning_rate': 0.044189491377218046, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 21, 'subsample': 0.9422525406430501, 'colsample_bytree': 0.6463770199624596, 'reg_alpha': 3.272535122197906, 'reg_lambda': 0.007361996577909836}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  65%|███████████████████████████████████████████████████████████████████████                                       | 323/500 [23:15<21:08,  7.17s/it]

[I 2026-05-19 12:18:43,393] Trial 324 finished with value: 0.9498706993414183 and parameters: {'n_estimators': 263, 'learning_rate': 0.04731705839666915, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 20, 'subsample': 0.9322424876679841, 'colsample_bytree': 0.6427948337897211, 'reg_alpha': 3.4871224950466635, 'reg_lambda': 0.0070228914055834495}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  65%|███████████████████████████████████████████████████████████████████████▎                                      | 324/500 [23:16<15:29,  5.28s/it]

[I 2026-05-19 12:18:44,254] Trial 321 finished with value: 0.9498651960386454 and parameters: {'n_estimators': 277, 'learning_rate': 0.04386567086292892, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 20, 'subsample': 0.9419995235749873, 'colsample_bytree': 0.6406742022587749, 'reg_alpha': 6.507312531134307, 'reg_lambda': 0.006170785837845779}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  65%|███████████████████████████████████████████████████████████████████████▌                                      | 325/500 [23:16<11:11,  3.84s/it]

[I 2026-05-19 12:18:44,733] Trial 323 finished with value: 0.9498680523172105 and parameters: {'n_estimators': 263, 'learning_rate': 0.04986809342410787, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 20, 'subsample': 0.9334047670639493, 'colsample_bytree': 0.633504952175248, 'reg_alpha': 7.445810902258463, 'reg_lambda': 0.007501768707778274}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  65%|███████████████████████████████████████████████████████████████████████▋                                      | 326/500 [23:17<08:18,  2.87s/it]

[I 2026-05-19 12:18:45,331] Trial 325 finished with value: 0.9498660480971403 and parameters: {'n_estimators': 262, 'learning_rate': 0.04738149741226966, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 34, 'subsample': 0.9319241620229181, 'colsample_bytree': 0.6473091642147633, 'reg_alpha': 8.45875152004684, 'reg_lambda': 0.006382615443135353}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  65%|███████████████████████████████████████████████████████████████████████▉                                      | 327/500 [23:21<09:37,  3.34s/it]

[I 2026-05-19 12:18:49,781] Trial 327 finished with value: 0.9498641985767813 and parameters: {'n_estimators': 262, 'learning_rate': 0.04727262475911646, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 20, 'subsample': 0.9324862947815388, 'colsample_bytree': 0.6473297721768684, 'reg_alpha': 7.7710899981580575, 'reg_lambda': 0.01783030075668977}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  66%|████████████████████████████████████████████████████████████████████████▏                                     | 328/500 [23:22<06:55,  2.42s/it]

[I 2026-05-19 12:18:50,039] Trial 326 finished with value: 0.9498682406839132 and parameters: {'n_estimators': 264, 'learning_rate': 0.049773713006768396, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 34, 'subsample': 0.9346699971161929, 'colsample_bytree': 0.6428605850171736, 'reg_alpha': 7.171024617256795, 'reg_lambda': 0.007854111066978099}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  66%|████████████████████████████████████████████████████████████████████████▌                                     | 330/500 [23:36<12:03,  4.26s/it]

[I 2026-05-19 12:19:04,406] Trial 328 finished with value: 0.9497700327962573 and parameters: {'n_estimators': 263, 'learning_rate': 0.01013594232238773, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 20, 'subsample': 0.9326262430796836, 'colsample_bytree': 0.6498941743612465, 'reg_alpha': 8.69809059630011, 'reg_lambda': 0.018069608497775575}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:19:04,597] Trial 331 finished with value: 0.9498658338696206 and parameters: {'n_estimators': 263, 'learning_rate': 0.04978792728311616, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.9353614394530261, 'colsample_bytree': 0.668742744935193, 'reg_alpha': 8.346972496254772, 'reg_lambda': 0.021632551590935783}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  66%|████████████████████████████████████████████████████████████████████████▊                                     | 331/500 [23:37<09:15,  3.28s/it]

[I 2026-05-19 12:19:05,610] Trial 330 finished with value: 0.9498662311730621 and parameters: {'n_estimators': 265, 'learning_rate': 0.047814199756996724, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.9281036716071198, 'colsample_bytree': 0.6525371576387005, 'reg_alpha': 8.325773659523255, 'reg_lambda': 0.02153639335805483}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  66%|█████████████████████████████████████████████████████████████████████████                                     | 332/500 [23:38<06:56,  2.48s/it]

[I 2026-05-19 12:19:06,221] Trial 329 finished with value: 0.9498673178441994 and parameters: {'n_estimators': 264, 'learning_rate': 0.049875464549713554, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 34, 'subsample': 0.9328336225614544, 'colsample_bytree': 0.6489134546347171, 'reg_alpha': 7.993492233481961, 'reg_lambda': 0.02121126045244301}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  67%|█████████████████████████████████████████████████████████████████████████▎                                    | 333/500 [23:47<12:10,  4.37s/it]

[I 2026-05-19 12:19:14,997] Trial 332 finished with value: 0.9498653374527057 and parameters: {'n_estimators': 263, 'learning_rate': 0.04734441679741202, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.9328326852599036, 'colsample_bytree': 0.6494022385184283, 'reg_alpha': 9.016192062144334, 'reg_lambda': 0.0016650427892169104}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  67%|█████████████████████████████████████████████████████████████████████████▍                                    | 334/500 [24:08<26:06,  9.43s/it]

[I 2026-05-19 12:19:36,251] Trial 336 finished with value: 0.9498580667833169 and parameters: {'n_estimators': 255, 'learning_rate': 0.04753737190583191, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 34, 'subsample': 0.9335355554143548, 'colsample_bytree': 0.6703493354146179, 'reg_alpha': 9.276816353486064, 'reg_lambda': 0.019023681938104383}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  67%|█████████████████████████████████████████████████████████████████████████▋                                    | 335/500 [24:08<18:30,  6.73s/it]

[I 2026-05-19 12:19:36,668] Trial 335 finished with value: 0.9498589937636016 and parameters: {'n_estimators': 262, 'learning_rate': 0.04716977657747176, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 34, 'subsample': 0.9327286968521322, 'colsample_bytree': 0.6714064670447841, 'reg_alpha': 8.243939488617887, 'reg_lambda': 0.019024273379322314}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  67%|█████████████████████████████████████████████████████████████████████████▉                                    | 336/500 [24:09<13:08,  4.81s/it]

[I 2026-05-19 12:19:36,992] Trial 337 finished with value: 0.9498625117524547 and parameters: {'n_estimators': 257, 'learning_rate': 0.04701739244555022, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 34, 'subsample': 0.9235590994432934, 'colsample_bytree': 0.6738923333830388, 'reg_alpha': 8.349227120826948, 'reg_lambda': 0.020073193387211963}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:19:37,049] Trial 333 finished with value: 0.9498652126426576 and parameters: {'n_estimators': 255, 'learning_rate': 0.04751230981076295, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 34, 'subsample': 0.9328712816184502, 'colsample_bytree': 0.6620963270680101, 'reg_alpha': 8.864788223442815, 'reg_lambda': 0.0164666658182672}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  68%|██████████████████████████████████████████████████████████████████████████▎                                   | 338/500 [24:10<07:39,  2.84s/it]

[I 2026-05-19 12:19:38,069] Trial 334 finished with value: 0.9498626247186739 and parameters: {'n_estimators': 256, 'learning_rate': 0.04715715557370314, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.9326530635900754, 'colsample_bytree': 0.6695792890532465, 'reg_alpha': 8.49568742384664, 'reg_lambda': 0.019400553400536813}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  68%|██████████████████████████████████████████████████████████████████████████▌                                   | 339/500 [24:10<06:05,  2.27s/it]

[I 2026-05-19 12:19:38,609] Trial 338 finished with value: 0.9498534391631278 and parameters: {'n_estimators': 255, 'learning_rate': 0.04707532578543536, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.9221748190139194, 'colsample_bytree': 0.6746725015968997, 'reg_alpha': 2.5983773302561524, 'reg_lambda': 0.019011898184924214}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  68%|██████████████████████████████████████████████████████████████████████████▊                                   | 340/500 [24:15<07:38,  2.87s/it]

[I 2026-05-19 12:19:43,151] Trial 339 finished with value: 0.949864546637448 and parameters: {'n_estimators': 256, 'learning_rate': 0.0472920169084033, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 34, 'subsample': 0.9274279315713669, 'colsample_bytree': 0.6601661940469957, 'reg_alpha': 8.433730801020765, 'reg_lambda': 0.017963854380528572}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  68%|███████████████████████████████████████████████████████████████████████████                                   | 341/500 [24:32<17:40,  6.67s/it]

[I 2026-05-19 12:19:59,988] Trial 340 finished with value: 0.9498635558517549 and parameters: {'n_estimators': 255, 'learning_rate': 0.049818168857222594, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.9224943463372001, 'colsample_bytree': 0.671738848647736, 'reg_alpha': 8.673124670879798, 'reg_lambda': 0.015758148916852413}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  68%|███████████████████████████████████████████████████████████████████████████▏                                  | 342/500 [24:32<13:09,  5.00s/it]

[I 2026-05-19 12:20:00,703] Trial 342 finished with value: 0.9498595390012493 and parameters: {'n_estimators': 255, 'learning_rate': 0.04987616688655265, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.9238906400008691, 'colsample_bytree': 0.6627252534274473, 'reg_alpha': 3.5527440793223617, 'reg_lambda': 0.0017547003268321923}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  69%|███████████████████████████████████████████████████████████████████████████▍                                  | 343/500 [24:34<10:31,  4.02s/it]

[I 2026-05-19 12:20:02,275] Trial 341 finished with value: 0.949867542356999 and parameters: {'n_estimators': 255, 'learning_rate': 0.047070332807276564, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 41, 'subsample': 0.9234853337190425, 'colsample_bytree': 0.630655207156582, 'reg_alpha': 2.755023106212056, 'reg_lambda': 0.015727328534934207}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  69%|███████████████████████████████████████████████████████████████████████████▋                                  | 344/500 [24:36<09:16,  3.57s/it]

[I 2026-05-19 12:20:04,736] Trial 343 finished with value: 0.9498293716546564 and parameters: {'n_estimators': 255, 'learning_rate': 0.021231601026136505, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.9205179683272469, 'colsample_bytree': 0.6306831385418735, 'reg_alpha': 2.8642870580370223, 'reg_lambda': 0.015321577349428532}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  69%|███████████████████████████████████████████████████████████████████████████▉                                  | 345/500 [24:38<07:20,  2.84s/it]

[I 2026-05-19 12:20:05,798] Trial 344 finished with value: 0.9498630813410918 and parameters: {'n_estimators': 256, 'learning_rate': 0.046968739545605036, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 40, 'subsample': 0.9217573761803044, 'colsample_bytree': 0.628486291052297, 'reg_alpha': 3.0538271495424647, 'reg_lambda': 0.014508713709670412}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  69%|████████████████████████████████████████████████████████████████████████████                                  | 346/500 [24:59<21:26,  8.36s/it]

[I 2026-05-19 12:20:27,354] Trial 349 finished with value: 0.9498458476132342 and parameters: {'n_estimators': 255, 'learning_rate': 0.04980637031906392, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 41, 'subsample': 0.921629052097973, 'colsample_bytree': 0.6291671978330771, 'reg_alpha': 0.012052319713816257, 'reg_lambda': 0.008459904846671704}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  69%|████████████████████████████████████████████████████████████████████████████▎                                 | 347/500 [25:00<15:48,  6.20s/it]

[I 2026-05-19 12:20:28,432] Trial 345 finished with value: 0.9498691124493449 and parameters: {'n_estimators': 254, 'learning_rate': 0.04985637127078398, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.9203862646894131, 'colsample_bytree': 0.6599099310891772, 'reg_alpha': 8.490250658828108, 'reg_lambda': 0.06489300894670269}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  70%|████████████████████████████████████████████████████████████████████████████▌                                 | 348/500 [25:01<12:02,  4.75s/it]

[I 2026-05-19 12:20:29,782] Trial 347 finished with value: 0.9498643561472775 and parameters: {'n_estimators': 254, 'learning_rate': 0.04965016591797608, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 39, 'subsample': 0.9208017630839167, 'colsample_bytree': 0.6589591953922134, 'reg_alpha': 2.6338743814552803, 'reg_lambda': 0.015165244628535541}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  70%|████████████████████████████████████████████████████████████████████████████▊                                 | 349/500 [25:02<08:50,  3.52s/it]

[I 2026-05-19 12:20:30,376] Trial 348 finished with value: 0.9498622858683955 and parameters: {'n_estimators': 255, 'learning_rate': 0.045943911538937385, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 41, 'subsample': 0.9211187573602438, 'colsample_bytree': 0.6313870113815712, 'reg_alpha': 2.792754594338703, 'reg_lambda': 0.07144001064408168}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  70%|█████████████████████████████████████████████████████████████████████████████                                 | 350/500 [25:04<07:56,  3.17s/it]

[I 2026-05-19 12:20:32,723] Trial 346 finished with value: 0.9498595939417372 and parameters: {'n_estimators': 256, 'learning_rate': 0.04652750820751394, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 41, 'subsample': 0.9256520456064119, 'colsample_bytree': 0.6347445332360756, 'reg_alpha': 2.9126240726052215, 'reg_lambda': 0.015049203096811533}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  70%|█████████████████████████████████████████████████████████████████████████████▏                                | 351/500 [25:05<05:50,  2.35s/it]

[I 2026-05-19 12:20:33,196] Trial 351 finished with value: 0.949845358184173 and parameters: {'n_estimators': 268, 'learning_rate': 0.04984409083156549, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 39, 'subsample': 0.9470432821091184, 'colsample_bytree': 0.6307170640288443, 'reg_alpha': 0.00083139472867333, 'reg_lambda': 0.008788283212859965}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  70%|█████████████████████████████████████████████████████████████████████████████▍                                | 352/500 [25:11<08:21,  3.39s/it]

[I 2026-05-19 12:20:38,994] Trial 354 finished with value: 0.9498379080313981 and parameters: {'n_estimators': 150, 'learning_rate': 0.0417473686253336, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.9439719139414872, 'colsample_bytree': 0.629229717746368, 'reg_alpha': 2.954078400911204, 'reg_lambda': 0.07161167669615563}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  71%|█████████████████████████████████████████████████████████████████████████████▋                                | 353/500 [25:12<07:02,  2.88s/it]

[I 2026-05-19 12:20:40,674] Trial 350 finished with value: 0.9497619954683051 and parameters: {'n_estimators': 269, 'learning_rate': 0.008349168497461795, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.9215024451685399, 'colsample_bytree': 0.6302067602636907, 'reg_alpha': 0.000679625062309656, 'reg_lambda': 0.06703507854980016}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  71%|█████████████████████████████████████████████████████████████████████████████▉                                | 354/500 [25:31<18:46,  7.72s/it]

[I 2026-05-19 12:20:59,717] Trial 352 finished with value: 0.949845566379788 and parameters: {'n_estimators': 270, 'learning_rate': 0.025943645786941576, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 43, 'subsample': 0.9439046811249089, 'colsample_bytree': 0.6288762139945112, 'reg_alpha': 2.9565661126140528, 'reg_lambda': 0.07181172675230614}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  71%|██████████████████████████████████████████████████████████████████████████████                                | 355/500 [25:35<15:44,  6.51s/it]

[I 2026-05-19 12:21:03,389] Trial 355 finished with value: 0.9498530500913613 and parameters: {'n_estimators': 270, 'learning_rate': 0.04171134924681178, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 41, 'subsample': 0.9474248298453436, 'colsample_bytree': 0.6310371470966781, 'reg_alpha': 3.499546462375453e-05, 'reg_lambda': 0.008379914997353305}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  71%|██████████████████████████████████████████████████████████████████████████████▎                               | 356/500 [25:35<11:06,  4.63s/it]

[I 2026-05-19 12:21:03,647] Trial 353 finished with value: 0.9498723574314957 and parameters: {'n_estimators': 270, 'learning_rate': 0.045633533381091156, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.9516966932913846, 'colsample_bytree': 0.6298601915282948, 'reg_alpha': 2.725695033433635, 'reg_lambda': 0.06012647730257006}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  71%|██████████████████████████████████████████████████████████████████████████████▌                               | 357/500 [25:36<08:09,  3.43s/it]

[I 2026-05-19 12:21:04,252] Trial 356 finished with value: 0.9498153065409284 and parameters: {'n_estimators': 270, 'learning_rate': 0.01656318467295661, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.9459762244593402, 'colsample_bytree': 0.6129209360623196, 'reg_alpha': 2.436680046120627, 'reg_lambda': 0.008691846932475213}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  72%|██████████████████████████████████████████████████████████████████████████████▊                               | 358/500 [25:44<11:40,  4.93s/it]

[I 2026-05-19 12:21:12,691] Trial 362 finished with value: 0.9497967898300971 and parameters: {'n_estimators': 158, 'learning_rate': 0.025552258517744147, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 31, 'subsample': 0.9453823428825355, 'colsample_bytree': 0.6133985367638526, 'reg_alpha': 4.0293775287824865, 'reg_lambda': 0.03306445634269717}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  72%|██████████████████████████████████████████████████████████████████████████████▉                               | 359/500 [25:53<14:01,  5.97s/it]

[I 2026-05-19 12:21:21,093] Trial 358 finished with value: 0.9498615131428385 and parameters: {'n_estimators': 269, 'learning_rate': 0.041983709475212426, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.9446350039781717, 'colsample_bytree': 0.6107744910985332, 'reg_alpha': 3.6205379251055754, 'reg_lambda': 0.03374714743180868}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  72%|███████████████████████████████████████████████████████████████████████████████▏                              | 360/500 [25:56<11:49,  5.07s/it]

[I 2026-05-19 12:21:24,061] Trial 360 finished with value: 0.9498584638277923 and parameters: {'n_estimators': 271, 'learning_rate': 0.041309255072775955, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 31, 'subsample': 0.9466496644866078, 'colsample_bytree': 0.6143750887813211, 'reg_alpha': 3.522409756701317, 'reg_lambda': 0.008820382739631491}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  72%|███████████████████████████████████████████████████████████████████████████████▍                              | 361/500 [25:57<08:55,  3.85s/it]

[I 2026-05-19 12:21:25,065] Trial 357 finished with value: 0.9498584584913587 and parameters: {'n_estimators': 269, 'learning_rate': 0.04131081617085532, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 41, 'subsample': 0.9469295275321596, 'colsample_bytree': 0.614315791160688, 'reg_alpha': 3.487756660948185, 'reg_lambda': 0.0629803639134373}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  73%|███████████████████████████████████████████████████████████████████████████████▊                              | 363/500 [26:03<07:07,  3.12s/it]

[I 2026-05-19 12:21:30,781] Trial 359 finished with value: 0.9498652475812163 and parameters: {'n_estimators': 270, 'learning_rate': 0.042066279661564655, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.947969158814157, 'colsample_bytree': 0.6123626002495558, 'reg_alpha': 3.5930618627726583, 'reg_lambda': 0.06272200549160648}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:21:30,863] Trial 361 finished with value: 0.9498617865411637 and parameters: {'n_estimators': 270, 'learning_rate': 0.04224520952665983, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.9452953279101161, 'colsample_bytree': 0.6126832702601112, 'reg_alpha': 4.037689958478485, 'reg_lambda': 0.0337897262711369}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  73%|████████████████████████████████████████████████████████████████████████████████                              | 364/500 [26:04<06:02,  2.67s/it]

[I 2026-05-19 12:21:32,492] Trial 363 finished with value: 0.9498609086139824 and parameters: {'n_estimators': 270, 'learning_rate': 0.041491865242012295, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.9533733843152609, 'colsample_bytree': 0.611160263613344, 'reg_alpha': 4.636059661874347, 'reg_lambda': 0.0361581935784886}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  73%|████████████████████████████████████████████████████████████████████████████████▎                             | 365/500 [26:07<06:01,  2.68s/it]

[I 2026-05-19 12:21:35,217] Trial 364 finished with value: 0.9498577702474622 and parameters: {'n_estimators': 270, 'learning_rate': 0.04145713050236685, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.9523789103461121, 'colsample_bytree': 0.653455390921908, 'reg_alpha': 4.071731994628316, 'reg_lambda': 0.03283059374211018}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  73%|████████████████████████████████████████████████████████████████████████████████▌                             | 366/500 [26:29<18:48,  8.42s/it]

[I 2026-05-19 12:21:57,004] Trial 366 finished with value: 0.9498610635021285 and parameters: {'n_estimators': 261, 'learning_rate': 0.04546238691996484, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 31, 'subsample': 0.9541497704931904, 'colsample_bytree': 0.6128510661238143, 'reg_alpha': 3.83691030492589, 'reg_lambda': 0.04265834075780999}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  73%|████████████████████████████████████████████████████████████████████████████████▋                             | 367/500 [26:29<13:30,  6.09s/it]

[I 2026-05-19 12:21:57,697] Trial 365 finished with value: 0.9498647962925422 and parameters: {'n_estimators': 262, 'learning_rate': 0.0447636348154531, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 29, 'subsample': 0.9549374168677308, 'colsample_bytree': 0.6124010815113758, 'reg_alpha': 3.8490102827896866, 'reg_lambda': 0.03357629274188498}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  74%|████████████████████████████████████████████████████████████████████████████████▉                             | 368/500 [26:30<09:46,  4.44s/it]

[I 2026-05-19 12:21:58,278] Trial 368 finished with value: 0.9498617572438619 and parameters: {'n_estimators': 261, 'learning_rate': 0.045243373430361125, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 32, 'subsample': 0.9541167325091758, 'colsample_bytree': 0.6134138793541181, 'reg_alpha': 1.7767895199065504, 'reg_lambda': 0.002702441830344871}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  74%|█████████████████████████████████████████████████████████████████████████████████▏                            | 369/500 [26:34<09:06,  4.17s/it]

[I 2026-05-19 12:22:01,829] Trial 367 finished with value: 0.9498626963879774 and parameters: {'n_estimators': 281, 'learning_rate': 0.045768351368826045, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.9558903649165696, 'colsample_bytree': 0.6164114754772184, 'reg_alpha': 1.843939010982478, 'reg_lambda': 0.03217477629492857}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  74%|█████████████████████████████████████████████████████████████████████████████████▍                            | 370/500 [26:36<07:42,  3.56s/it]

[I 2026-05-19 12:22:03,950] Trial 369 finished with value: 0.9498568614598554 and parameters: {'n_estimators': 260, 'learning_rate': 0.04989786891778369, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.9547805905965616, 'colsample_bytree': 0.6415659357584161, 'reg_alpha': 3.966020255357227, 'reg_lambda': 0.03410768365363102}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  74%|█████████████████████████████████████████████████████████████████████████████████▊                            | 372/500 [26:51<10:40,  5.00s/it]

[I 2026-05-19 12:22:19,258] Trial 371 finished with value: 0.9498567840156689 and parameters: {'n_estimators': 279, 'learning_rate': 0.04494150849745994, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 26, 'subsample': 0.9547066530175375, 'colsample_bytree': 0.6532237048047493, 'reg_alpha': 4.573689549718427, 'reg_lambda': 0.05298737997378032}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:22:19,395] Trial 370 finished with value: 0.9498600880926601 and parameters: {'n_estimators': 279, 'learning_rate': 0.04507133460333231, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 29, 'subsample': 0.9579653551220244, 'colsample_bytree': 0.6543243617842532, 'reg_alpha': 4.505575531682342, 'reg_lambda': 0.00017962775038881732}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  75%|██████████████████████████████████████████████████████████████████████████████████                            | 373/500 [26:52<07:56,  3.75s/it]

[I 2026-05-19 12:22:20,228] Trial 372 finished with value: 0.9498565280784534 and parameters: {'n_estimators': 260, 'learning_rate': 0.045324040120436546, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 26, 'subsample': 0.9569238715453035, 'colsample_bytree': 0.6555794906039076, 'reg_alpha': 1.7809427632222183, 'reg_lambda': 0.002813493537539765}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  75%|██████████████████████████████████████████████████████████████████████████████████▎                           | 374/500 [26:59<09:41,  4.61s/it]

[I 2026-05-19 12:22:26,860] Trial 373 finished with value: 0.9498442074701046 and parameters: {'n_estimators': 282, 'learning_rate': 0.0452228874114215, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 26, 'subsample': 0.9569159960704591, 'colsample_bytree': 0.6541366949252472, 'reg_alpha': 0.035816197767118564, 'reg_lambda': 0.031147665243196124}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  75%|██████████████████████████████████████████████████████████████████████████████████▋                           | 376/500 [27:01<07:55,  3.83s/it]

[I 2026-05-19 12:22:28,857] Trial 375 finished with value: 0.9498562605626077 and parameters: {'n_estimators': 282, 'learning_rate': 0.045094209000292276, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 26, 'subsample': 0.9553685301398669, 'colsample_bytree': 0.6546063308139991, 'reg_alpha': 2.115484016231848, 'reg_lambda': 0.02749018425211723}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:22:28,872] Trial 376 finished with value: 0.9498665590719859 and parameters: {'n_estimators': 261, 'learning_rate': 0.04497897280104084, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 25, 'subsample': 0.9570440644205583, 'colsample_bytree': 0.6396547295523013, 'reg_alpha': 6.4383450873464945, 'reg_lambda': 0.02561726899045929}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:22:28,877] Trial 374 finished with value: 0.9498599264401661 and parameters: {'n_estimators': 282, 'learning_rate': 0.04539697170011522, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 25, 'subsample': 0.9568929475476715, 'colsample_bytree': 0.6536857833945029, 'reg_alpha': 5.17151913961261, 'reg_lambda': 0.027170330593597355}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  76%|███████████████████████████████████████████████████████████████████████████████████▏                          | 378/500 [27:20<10:46,  5.30s/it]

[I 2026-05-19 12:22:48,148] Trial 384 finished with value: 0.9498283429427035 and parameters: {'n_estimators': 112, 'learning_rate': 0.049856125278092425, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 23, 'subsample': 0.9357881932241665, 'colsample_bytree': 0.6426345287129569, 'reg_alpha': 7.463119791545635, 'reg_lambda': 0.013049927100153043}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  76%|███████████████████████████████████████████████████████████████████████████████████▍                          | 379/500 [27:24<10:05,  5.00s/it]

[I 2026-05-19 12:22:52,093] Trial 378 finished with value: 0.9498648577918294 and parameters: {'n_estimators': 280, 'learning_rate': 0.04981870918308637, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 26, 'subsample': 0.9390878576528341, 'colsample_bytree': 0.6424332121128671, 'reg_alpha': 5.717967538495533, 'reg_lambda': 0.023491548521461816}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  76%|███████████████████████████████████████████████████████████████████████████████████▌                          | 380/500 [27:25<08:27,  4.23s/it]

[I 2026-05-19 12:22:53,741] Trial 377 finished with value: 0.9498520481042227 and parameters: {'n_estimators': 261, 'learning_rate': 0.04544851796917172, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 25, 'subsample': 0.9072833209884358, 'colsample_bytree': 0.6443261428585564, 'reg_alpha': 1.765392733170335, 'reg_lambda': 0.002952394654788402}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  76%|███████████████████████████████████████████████████████████████████████████████████▊                          | 381/500 [27:27<06:58,  3.52s/it]

[I 2026-05-19 12:22:55,103] Trial 379 finished with value: 0.9498676609609611 and parameters: {'n_estimators': 280, 'learning_rate': 0.04992126700563911, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 24, 'subsample': 0.9374640774862528, 'colsample_bytree': 0.6415909638177913, 'reg_alpha': 6.273026809216719, 'reg_lambda': 2.353592717522414e-05}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  76%|████████████████████████████████████████████████████████████████████████████████████                          | 382/500 [27:28<05:32,  2.81s/it]

[I 2026-05-19 12:22:55,945] Trial 380 finished with value: 0.9498629839523574 and parameters: {'n_estimators': 280, 'learning_rate': 0.04961375433219629, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 24, 'subsample': 0.9078651675132227, 'colsample_bytree': 0.6435755116596433, 'reg_alpha': 5.808384279860542, 'reg_lambda': 0.011991510022879941}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  77%|████████████████████████████████████████████████████████████████████████████████████▎                         | 383/500 [27:34<07:13,  3.70s/it]

[I 2026-05-19 12:23:02,022] Trial 381 finished with value: 0.9498723878879985 and parameters: {'n_estimators': 281, 'learning_rate': 0.04544743925964646, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 25, 'subsample': 0.9368286875992402, 'colsample_bytree': 0.6456220299796093, 'reg_alpha': 6.431302569620184, 'reg_lambda': 0.025864963672308904}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  77%|████████████████████████████████████████████████████████████████████████████████████▍                         | 384/500 [27:37<06:48,  3.52s/it]

[I 2026-05-19 12:23:05,054] Trial 387 pruned.

Best trial: 286. Best value: 0.949875:  77%|████████████████████████████████████████████████████████████████████████████████████▋                         | 385/500 [27:49<11:16,  5.89s/it]

[I 2026-05-19 12:23:16,868] Trial 382 finished with value: 0.9498703113551373 and parameters: {'n_estimators': 280, 'learning_rate': 0.049751992730659, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 49, 'subsample': 0.936220607438063, 'colsample_bytree': 0.6437189846454813, 'reg_alpha': 6.900099660935423, 'reg_lambda': 0.011555857627136897}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  77%|████████████████████████████████████████████████████████████████████████████████████▉                         | 386/500 [27:50<08:38,  4.55s/it]

[I 2026-05-19 12:23:18,145] Trial 383 finished with value: 0.9498687070605868 and parameters: {'n_estimators': 263, 'learning_rate': 0.049675953362157126, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 47, 'subsample': 0.9363485950932008, 'colsample_bytree': 0.6425432790049952, 'reg_alpha': 6.212448109437654, 'reg_lambda': 0.013022254365522486}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  77%|█████████████████████████████████████████████████████████████████████████████████████▏                        | 387/500 [27:55<08:55,  4.74s/it]

[I 2026-05-19 12:23:23,332] Trial 388 finished with value: 0.9498745067722357 and parameters: {'n_estimators': 265, 'learning_rate': 0.049636124476311556, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 47, 'subsample': 0.9077599217288836, 'colsample_bytree': 0.6439566343823194, 'reg_alpha': 6.503824071724272, 'reg_lambda': 0.012603276549577049}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  78%|█████████████████████████████████████████████████████████████████████████████████████▌                        | 389/500 [27:58<05:20,  2.89s/it]

[I 2026-05-19 12:23:25,730] Trial 386 finished with value: 0.9498706730151293 and parameters: {'n_estimators': 264, 'learning_rate': 0.04769195296795087, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 46, 'subsample': 0.9376118214303477, 'colsample_bytree': 0.6415768673588499, 'reg_alpha': 6.49845507808407, 'reg_lambda': 0.0104989222017247}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:23:25,854] Trial 385 finished with value: 0.9498683543337114 and parameters: {'n_estimators': 265, 'learning_rate': 0.047713670759662784, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 49, 'subsample': 0.9381958883923385, 'colsample_bytree': 0.6446648551185326, 'reg_alpha': 6.398501171652537, 'reg_lambda': 0.012801484872750436}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  78%|█████████████████████████████████████████████████████████████████████████████████████▊                        | 390/500 [28:02<06:24,  3.49s/it]

[I 2026-05-19 12:23:30,794] Trial 390 pruned.

Best trial: 286. Best value: 0.949875:  78%|██████████████████████████████████████████████████████████████████████████████████████                        | 391/500 [28:12<09:45,  5.37s/it]

[I 2026-05-19 12:23:40,559] Trial 389 finished with value: 0.9498691533764954 and parameters: {'n_estimators': 265, 'learning_rate': 0.047487026433940024, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 47, 'subsample': 0.9378819621523014, 'colsample_bytree': 0.6236724875339061, 'reg_alpha': 7.514878525352309, 'reg_lambda': 0.005171410686180608}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  78%|██████████████████████████████████████████████████████████████████████████████████████▏                       | 392/500 [28:21<11:39,  6.48s/it]

[I 2026-05-19 12:23:49,645] Trial 393 finished with value: 0.9498635816923825 and parameters: {'n_estimators': 265, 'learning_rate': 0.04729186793297519, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 49, 'subsample': 0.9365871558461745, 'colsample_bytree': 0.6375792120486373, 'reg_alpha': 11.420890293323904, 'reg_lambda': 3.4669425362352305e-05}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  79%|██████████████████████████████████████████████████████████████████████████████████████▍                       | 393/500 [28:23<08:43,  4.89s/it]

[I 2026-05-19 12:23:50,821] Trial 392 finished with value: 0.9498675093940827 and parameters: {'n_estimators': 264, 'learning_rate': 0.04991041233128622, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 50, 'subsample': 0.929120619569276, 'colsample_bytree': 0.6385512798089987, 'reg_alpha': 11.044085226201622, 'reg_lambda': 3.101806176075622e-05}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  79%|██████████████████████████████████████████████████████████████████████████████████████▋                       | 394/500 [28:27<08:24,  4.76s/it]

[I 2026-05-19 12:23:55,274] Trial 391 finished with value: 0.9498215832570642 and parameters: {'n_estimators': 264, 'learning_rate': 0.019629763083520102, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 51, 'subsample': 0.9377395903980522, 'colsample_bytree': 0.624256592492683, 'reg_alpha': 11.37391135402408, 'reg_lambda': 0.00988122453391986}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  79%|██████████████████████████████████████████████████████████████████████████████████████▉                       | 395/500 [28:28<06:32,  3.73s/it]

[I 2026-05-19 12:23:56,605] Trial 394 finished with value: 0.9498638372288178 and parameters: {'n_estimators': 277, 'learning_rate': 0.04724222876287442, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 47, 'subsample': 0.9331813620083854, 'colsample_bytree': 0.6365689806212999, 'reg_alpha': 6.688204472626072, 'reg_lambda': 1.0340323128360506e-05}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  79%|███████████████████████████████████████████████████████████████████████████████████████                       | 396/500 [28:32<06:26,  3.72s/it]

[I 2026-05-19 12:24:00,289] Trial 395 finished with value: 0.9498668023020487 and parameters: {'n_estimators': 286, 'learning_rate': 0.04715028864499671, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 20, 'subsample': 0.9363791571441743, 'colsample_bytree': 0.6356799835574167, 'reg_alpha': 6.963223816241004, 'reg_lambda': 0.05483897309621801}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  79%|███████████████████████████████████████████████████████████████████████████████████████▎                      | 397/500 [28:44<10:24,  6.06s/it]

[I 2026-05-19 12:24:11,835] Trial 397 finished with value: 0.9498620932112424 and parameters: {'n_estimators': 284, 'learning_rate': 0.04746315414333764, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 49, 'subsample': 0.9371865466684436, 'colsample_bytree': 0.6372980610319384, 'reg_alpha': 6.790368611694413, 'reg_lambda': 5.1201505538480665e-05}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  80%|███████████████████████████████████████████████████████████████████████████████████████▌                      | 398/500 [28:51<10:46,  6.34s/it]

[I 2026-05-19 12:24:18,824] Trial 396 finished with value: 0.9498631894212624 and parameters: {'n_estimators': 287, 'learning_rate': 0.047578608554318724, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 48, 'subsample': 0.9348690127983188, 'colsample_bytree': 0.6363608860121319, 'reg_alpha': 6.9166508594690495, 'reg_lambda': 0.05115947176608347}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  80%|███████████████████████████████████████████████████████████████████████████████████████▊                      | 399/500 [28:56<10:19,  6.13s/it]

[I 2026-05-19 12:24:24,459] Trial 398 finished with value: 0.9498629313066997 and parameters: {'n_estimators': 289, 'learning_rate': 0.04715514244990306, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 49, 'subsample': 0.9363077206268329, 'colsample_bytree': 0.634967518701415, 'reg_alpha': 6.4011331513772705, 'reg_lambda': 0.00046583768630234214}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  80%|████████████████████████████████████████████████████████████████████████████████████████                      | 400/500 [28:59<08:34,  5.15s/it]

[I 2026-05-19 12:24:27,320] Trial 399 finished with value: 0.9498604799906207 and parameters: {'n_estimators': 288, 'learning_rate': 0.04755024072630226, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 51, 'subsample': 0.9374499085248795, 'colsample_bytree': 0.6612968518772422, 'reg_alpha': 6.000559672734438, 'reg_lambda': 0.00045244905491612016}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  80%|████████████████████████████████████████████████████████████████████████████████████████▍                     | 402/500 [29:00<04:27,  2.73s/it]

[I 2026-05-19 12:24:28,055] Trial 401 finished with value: 0.9498704409706491 and parameters: {'n_estimators': 276, 'learning_rate': 0.04711328123706285, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 49, 'subsample': 0.9386121893798908, 'colsample_bytree': 0.6466014541552246, 'reg_alpha': 5.554648624782192, 'reg_lambda': 1.0267339720550282e-05}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:24:28,241] Trial 400 finished with value: 0.9498599125270836 and parameters: {'n_estimators': 288, 'learning_rate': 0.04698975124452507, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 49, 'subsample': 0.9374417828907814, 'colsample_bytree': 0.6351760044575099, 'reg_alpha': 5.87973535944783, 'reg_lambda': 0.008329388030236471}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  81%|████████████████████████████████████████████████████████████████████████████████████████▋                     | 403/500 [29:16<10:42,  6.63s/it]

[I 2026-05-19 12:24:43,941] Trial 402 finished with value: 0.9498665144975073 and parameters: {'n_estimators': 287, 'learning_rate': 0.04791636922868164, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 51, 'subsample': 0.9373061608192801, 'colsample_bytree': 0.634260939032198, 'reg_alpha': 6.2478256299619614, 'reg_lambda': 0.007633105338552846}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  81%|████████████████████████████████████████████████████████████████████████████████████████▉                     | 404/500 [29:17<08:09,  5.10s/it]

[I 2026-05-19 12:24:45,479] Trial 403 finished with value: 0.9498672515780022 and parameters: {'n_estimators': 287, 'learning_rate': 0.04655881672691379, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 48, 'subsample': 0.9382601959044887, 'colsample_bytree': 0.6325300276631344, 'reg_alpha': 6.171704988334326, 'reg_lambda': 0.0005225208608734725}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  81%|█████████████████████████████████████████████████████████████████████████████████████████                     | 405/500 [29:24<08:59,  5.68s/it]

[I 2026-05-19 12:24:52,526] Trial 404 finished with value: 0.9498677006946619 and parameters: {'n_estimators': 289, 'learning_rate': 0.04710661375465651, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 48, 'subsample': 0.9393940025969179, 'colsample_bytree': 0.6349996783627628, 'reg_alpha': 6.342008768763801, 'reg_lambda': 0.007257418634505083}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  81%|█████████████████████████████████████████████████████████████████████████████████████████▎                    | 406/500 [29:27<07:19,  4.67s/it]

[I 2026-05-19 12:24:54,862] Trial 406 finished with value: 0.9498595281675668 and parameters: {'n_estimators': 275, 'learning_rate': 0.047238489267767136, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 48, 'subsample': 0.94062243482894, 'colsample_bytree': 0.6357568469220983, 'reg_alpha': 5.302696036790325, 'reg_lambda': 0.0051861502897815204}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  81%|█████████████████████████████████████████████████████████████████████████████████████████▌                    | 407/500 [29:28<05:46,  3.73s/it]

[I 2026-05-19 12:24:56,387] Trial 405 finished with value: 0.9498609169308787 and parameters: {'n_estimators': 287, 'learning_rate': 0.047306400687845127, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 47, 'subsample': 0.9371598575236885, 'colsample_bytree': 0.6342687486179402, 'reg_alpha': 6.192319620170728, 'reg_lambda': 0.0007705768749673283}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  82%|█████████████████████████████████████████████████████████████████████████████████████████▊                    | 408/500 [29:33<06:25,  4.19s/it]

[I 2026-05-19 12:25:01,612] Trial 407 finished with value: 0.9498631423871249 and parameters: {'n_estimators': 275, 'learning_rate': 0.04726482008674563, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 48, 'subsample': 0.937816370694842, 'colsample_bytree': 0.645148403368082, 'reg_alpha': 5.38380580478337, 'reg_lambda': 0.004685901728064449}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  82%|█████████████████████████████████████████████████████████████████████████████████████████▉                    | 409/500 [29:42<08:24,  5.55s/it]

[I 2026-05-19 12:25:10,368] Trial 408 finished with value: 0.9498624590472954 and parameters: {'n_estimators': 287, 'learning_rate': 0.04729509023079015, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 51, 'subsample': 0.941812719731217, 'colsample_bytree': 0.6460509249454872, 'reg_alpha': 5.688408242710661, 'reg_lambda': 0.007644788380243438}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  82%|██████████████████████████████████████████████████████████████████████████████████████████▏                   | 410/500 [29:52<10:14,  6.82s/it]

[I 2026-05-19 12:25:20,171] Trial 409 finished with value: 0.9498614063619357 and parameters: {'n_estimators': 276, 'learning_rate': 0.04701002601734975, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 46, 'subsample': 0.9417368133257771, 'colsample_bytree': 0.6498407205080661, 'reg_alpha': 5.1002586381205886, 'reg_lambda': 0.0004264403411482914}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  82%|██████████████████████████████████████████████████████████████████████████████████████████▍                   | 411/500 [29:55<08:34,  5.78s/it]

[I 2026-05-19 12:25:23,502] Trial 410 finished with value: 0.9498590866029533 and parameters: {'n_estimators': 276, 'learning_rate': 0.043335516593068425, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 53, 'subsample': 0.9404315286797627, 'colsample_bytree': 0.6482752830941181, 'reg_alpha': 5.820906383200748, 'reg_lambda': 0.007274305825023015}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  82%|██████████████████████████████████████████████████████████████████████████████████████████▋                   | 412/500 [29:58<07:04,  4.83s/it]

[I 2026-05-19 12:25:26,109] Trial 411 finished with value: 0.949860792076991 and parameters: {'n_estimators': 277, 'learning_rate': 0.04338506563983221, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 45, 'subsample': 0.9271152961546326, 'colsample_bytree': 0.6246399475516726, 'reg_alpha': 4.888810747686663, 'reg_lambda': 0.0009328875035479122}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  83%|██████████████████████████████████████████████████████████████████████████████████████████▊                   | 413/500 [29:58<05:06,  3.53s/it]

[I 2026-05-19 12:25:26,580] Trial 413 finished with value: 0.9498577074346919 and parameters: {'n_estimators': 278, 'learning_rate': 0.04298301886976838, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 46, 'subsample': 0.9282600632251958, 'colsample_bytree': 0.6482724683044605, 'reg_alpha': 5.467737329012897, 'reg_lambda': 0.0009036797691976556}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  83%|███████████████████████████████████████████████████████████████████████████████████████████                   | 414/500 [30:03<05:21,  3.74s/it]

[I 2026-05-19 12:25:30,837] Trial 412 finished with value: 0.9498634376559124 and parameters: {'n_estimators': 275, 'learning_rate': 0.04369258108966884, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 46, 'subsample': 0.9272205488344719, 'colsample_bytree': 0.6486238189284675, 'reg_alpha': 4.8365264701625925, 'reg_lambda': 0.0010943415059751545}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  83%|███████████████████████████████████████████████████████████████████████████████████████████▎                  | 415/500 [30:14<08:31,  6.02s/it]

[I 2026-05-19 12:25:42,166] Trial 414 finished with value: 0.9498679246909589 and parameters: {'n_estimators': 275, 'learning_rate': 0.04353516498322095, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 55, 'subsample': 0.9258817535115537, 'colsample_bytree': 0.6478179133762221, 'reg_alpha': 4.216866048158131, 'reg_lambda': 2.334262663723033e-05}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  83%|███████████████████████████████████████████████████████████████████████████████████████████▌                  | 416/500 [30:18<07:39,  5.47s/it]

[I 2026-05-19 12:25:46,353] Trial 415 finished with value: 0.9498628342102071 and parameters: {'n_estimators': 275, 'learning_rate': 0.043113956008543654, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 45, 'subsample': 0.9264916313929381, 'colsample_bytree': 0.648011024475581, 'reg_alpha': 4.699859959780967, 'reg_lambda': 1.1803777122337906e-05}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  83%|███████████████████████████████████████████████████████████████████████████████████████████▋                  | 417/500 [30:24<07:45,  5.60s/it]

[I 2026-05-19 12:25:52,264] Trial 418 finished with value: 0.9498558766811123 and parameters: {'n_estimators': 275, 'learning_rate': 0.03768822073478712, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 44, 'subsample': 0.9266890726071365, 'colsample_bytree': 0.6471704633456855, 'reg_alpha': 4.389741413304734, 'reg_lambda': 0.004845216244993909}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  84%|████████████████████████████████████████████████████████████████████████████████████████████▏                 | 419/500 [30:25<03:55,  2.91s/it]

[I 2026-05-19 12:25:52,846] Trial 417 finished with value: 0.9498599058224755 and parameters: {'n_estimators': 276, 'learning_rate': 0.04319542191072, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 57, 'subsample': 0.9280687084324869, 'colsample_bytree': 0.6490441435785994, 'reg_alpha': 4.476703294377175, 'reg_lambda': 0.00477139451623649}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:25:52,995] Trial 416 finished with value: 0.9498600248929847 and parameters: {'n_estimators': 274, 'learning_rate': 0.04408054811100544, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 55, 'subsample': 0.9273453726139309, 'colsample_bytree': 0.6485369051640756, 'reg_alpha': 4.29172865608549, 'reg_lambda': 0.004867812209170265}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  84%|████████████████████████████████████████████████████████████████████████████████████████████▍                 | 420/500 [30:32<05:46,  4.33s/it]

[I 2026-05-19 12:26:00,652] Trial 419 finished with value: 0.9498690984990008 and parameters: {'n_estimators': 270, 'learning_rate': 0.042176512534651586, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 56, 'subsample': 0.9276379982791381, 'colsample_bytree': 0.6495395229916014, 'reg_alpha': 4.240743770699647, 'reg_lambda': 0.0010975969606627394}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  84%|████████████████████████████████████████████████████████████████████████████████████████████▌                 | 421/500 [30:37<05:47,  4.39s/it]

[I 2026-05-19 12:26:05,183] Trial 420 finished with value: 0.9498640733270811 and parameters: {'n_estimators': 274, 'learning_rate': 0.04290922646475833, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 55, 'subsample': 0.9268877192409402, 'colsample_bytree': 0.6496110360019391, 'reg_alpha': 4.249804794296813, 'reg_lambda': 0.006535838729608808}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  84%|████████████████████████████████████████████████████████████████████████████████████████████▊                 | 422/500 [30:43<06:17,  4.84s/it]

[I 2026-05-19 12:26:11,063] Trial 424 finished with value: 0.9498450968787479 and parameters: {'n_estimators': 186, 'learning_rate': 0.036705208488634365, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 57, 'subsample': 0.9143411564544727, 'colsample_bytree': 0.6255631206464947, 'reg_alpha': 4.207981848779238, 'reg_lambda': 0.00022459128746250492}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  85%|█████████████████████████████████████████████████████████████████████████████████████████████                 | 423/500 [30:50<07:13,  5.64s/it]

[I 2026-05-19 12:26:18,552] Trial 421 finished with value: 0.9498620547528865 and parameters: {'n_estimators': 273, 'learning_rate': 0.04341011059095769, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 38, 'subsample': 0.9258767209065223, 'colsample_bytree': 0.6230144437417536, 'reg_alpha': 3.986248724291996, 'reg_lambda': 0.005897846090209922}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▎                | 424/500 [30:56<07:03,  5.58s/it]

[I 2026-05-19 12:26:23,998] Trial 423 finished with value: 0.9498548153198036 and parameters: {'n_estimators': 270, 'learning_rate': 0.03686471676073113, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 56, 'subsample': 0.9166332478895833, 'colsample_bytree': 0.6626915491870512, 'reg_alpha': 3.5524695919988916, 'reg_lambda': 0.005833083350414046}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▌                | 425/500 [30:56<05:00,  4.01s/it]

[I 2026-05-19 12:26:24,362] Trial 431 finished with value: 0.9497765510870669 and parameters: {'n_estimators': 86, 'learning_rate': 0.04044812079104911, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 60, 'subsample': 0.9134623676023785, 'colsample_bytree': 0.6633669716044801, 'reg_alpha': 2.2557885403564932, 'reg_lambda': 0.009825335995187819}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▋                | 426/500 [30:57<03:41,  3.00s/it]

[I 2026-05-19 12:26:24,992] Trial 422 finished with value: 0.9497347540538902 and parameters: {'n_estimators': 273, 'learning_rate': 0.0070203956792741305, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 37, 'subsample': 0.924104962246647, 'colsample_bytree': 0.6258433397091917, 'reg_alpha': 3.7673226663108763, 'reg_lambda': 0.00940653124472396}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▉                | 427/500 [31:01<04:14,  3.48s/it]

[I 2026-05-19 12:26:29,575] Trial 429 finished with value: 0.9498270444071515 and parameters: {'n_estimators': 270, 'learning_rate': 0.040501922386716474, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 38, 'subsample': 0.9155727560424644, 'colsample_bytree': 0.6614384823373729, 'reg_alpha': 2.770755606657016, 'reg_lambda': 1.883479611365776e-05}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  86%|██████████████████████████████████████████████████████████████████████████████████████████████▏               | 428/500 [31:02<03:09,  2.63s/it]

[I 2026-05-19 12:26:30,233] Trial 425 finished with value: 0.9498343900982593 and parameters: {'n_estimators': 272, 'learning_rate': 0.037969674155075725, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 56, 'subsample': 0.9146249971992831, 'colsample_bytree': 0.6602760775102859, 'reg_alpha': 0.0028596758898871287, 'reg_lambda': 0.008836158682480088}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  86%|██████████████████████████████████████████████████████████████████████████████████████████████▍               | 429/500 [31:13<06:02,  5.11s/it]

[I 2026-05-19 12:26:41,137] Trial 426 finished with value: 0.9498531581379825 and parameters: {'n_estimators': 271, 'learning_rate': 0.03752611952837035, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 39, 'subsample': 0.9184238573423972, 'colsample_bytree': 0.6592653140269367, 'reg_alpha': 2.3752931350828987, 'reg_lambda': 0.10113022743250381}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  86%|██████████████████████████████████████████████████████████████████████████████████████████████▌               | 430/500 [31:14<04:42,  4.03s/it]

[I 2026-05-19 12:26:42,659] Trial 432 finished with value: 0.9498334698818226 and parameters: {'n_estimators': 270, 'learning_rate': 0.04470510916771974, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 39, 'subsample': 0.9192100601355402, 'colsample_bytree': 0.6611289081227308, 'reg_alpha': 2.5756438731261304, 'reg_lambda': 0.11394302084923859}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  86%|██████████████████████████████████████████████████████████████████████████████████████████████▊               | 431/500 [31:15<03:32,  3.09s/it]

[I 2026-05-19 12:26:43,541] Trial 427 finished with value: 0.9498632135042102 and parameters: {'n_estimators': 272, 'learning_rate': 0.043202358010189575, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 57, 'subsample': 0.9135901134599541, 'colsample_bytree': 0.6248959333574368, 'reg_alpha': 2.2606931828758565, 'reg_lambda': 0.00023313986912182783}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  86%|███████████████████████████████████████████████████████████████████████████████████████████████               | 432/500 [31:17<02:58,  2.63s/it]

[I 2026-05-19 12:26:45,090] Trial 433 finished with value: 0.9498173198198374 and parameters: {'n_estimators': 269, 'learning_rate': 0.04087081654222184, 'max_depth': 4, 'num_leaves': 3, 'min_child_samples': 36, 'subsample': 0.9126345625089209, 'colsample_bytree': 0.6608733598193223, 'reg_alpha': 2.851660355712106, 'reg_lambda': 0.11901874088648602}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  87%|███████████████████████████████████████████████████████████████████████████████████████████████▎              | 433/500 [31:24<04:19,  3.87s/it]

[I 2026-05-19 12:26:51,846] Trial 428 finished with value: 0.9498588612882808 and parameters: {'n_estimators': 271, 'learning_rate': 0.04301273643559199, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 61, 'subsample': 0.9141233171959091, 'colsample_bytree': 0.6623730753229807, 'reg_alpha': 3.299601657908829, 'reg_lambda': 1.8954998110604043e-05}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  87%|███████████████████████████████████████████████████████████████████████████████████████████████▍              | 434/500 [31:28<04:26,  4.03s/it]

[I 2026-05-19 12:26:56,274] Trial 430 finished with value: 0.9498576601315399 and parameters: {'n_estimators': 271, 'learning_rate': 0.03991897755340317, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 37, 'subsample': 0.9179156161180655, 'colsample_bytree': 0.6599271252889065, 'reg_alpha': 2.301793586337428, 'reg_lambda': 1.6503808130896014e-05}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  87%|███████████████████████████████████████████████████████████████████████████████████████████████▋              | 435/500 [31:31<03:53,  3.60s/it]

[I 2026-05-19 12:26:58,856] Trial 434 finished with value: 0.9498251129073252 and parameters: {'n_estimators': 269, 'learning_rate': 0.03841176608848857, 'max_depth': 2, 'num_leaves': 12, 'min_child_samples': 36, 'subsample': 0.91535069005905, 'colsample_bytree': 0.6622466440486822, 'reg_alpha': 8.74852485103817, 'reg_lambda': 0.1405912747555172}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  87%|███████████████████████████████████████████████████████████████████████████████████████████████▉              | 436/500 [31:40<05:47,  5.43s/it]

[I 2026-05-19 12:27:08,552] Trial 436 finished with value: 0.9498373366589423 and parameters: {'n_estimators': 260, 'learning_rate': 0.049973105356352805, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 35, 'subsample': 0.9481287524807613, 'colsample_bytree': 0.6585602928476015, 'reg_alpha': 1.0738949834706934e-05, 'reg_lambda': 0.0862545481105309}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  87%|████████████████████████████████████████████████████████████████████████████████████████████████▏             | 437/500 [31:49<06:46,  6.45s/it]

[I 2026-05-19 12:27:17,400] Trial 438 finished with value: 0.9498418160879647 and parameters: {'n_estimators': 258, 'learning_rate': 0.04555032722388432, 'max_depth': 3, 'num_leaves': 12, 'min_child_samples': 37, 'subsample': 0.9172371959358955, 'colsample_bytree': 0.655150889739826, 'reg_alpha': 9.100720441385143, 'reg_lambda': 0.09950116741472186}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  88%|████████████████████████████████████████████████████████████████████████████████████████████████▎             | 438/500 [31:51<05:09,  5.00s/it]

[I 2026-05-19 12:27:18,995] Trial 435 finished with value: 0.9498542243091593 and parameters: {'n_estimators': 259, 'learning_rate': 0.03980628638956163, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 37, 'subsample': 0.9142519470614912, 'colsample_bytree': 0.6018094373658723, 'reg_alpha': 2.3319479519142092, 'reg_lambda': 0.010026503273120085}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  88%|████████████████████████████████████████████████████████████████████████████████████████████████▌             | 439/500 [31:55<04:53,  4.82s/it]

[I 2026-05-19 12:27:23,400] Trial 437 finished with value: 0.9498622608935555 and parameters: {'n_estimators': 267, 'learning_rate': 0.04525947028705201, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 38, 'subsample': 0.9479147993837267, 'colsample_bytree': 0.6593313935456107, 'reg_alpha': 2.5204318998214523, 'reg_lambda': 0.09371984837843719}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  88%|████████████████████████████████████████████████████████████████████████████████████████████████▊             | 440/500 [31:58<04:07,  4.12s/it]

[I 2026-05-19 12:27:25,887] Trial 440 finished with value: 0.949853060377792 and parameters: {'n_estimators': 258, 'learning_rate': 0.049957641660691325, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 37, 'subsample': 0.9487534614639459, 'colsample_bytree': 0.6201597135320317, 'reg_alpha': 9.810256884057928, 'reg_lambda': 0.0001234147692934648}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████             | 441/500 [32:01<03:58,  4.04s/it]

[I 2026-05-19 12:27:29,755] Trial 441 finished with value: 0.9498569727182605 and parameters: {'n_estimators': 258, 'learning_rate': 0.04996931186054969, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.9480157377478783, 'colsample_bytree': 0.6206298155759633, 'reg_alpha': 8.762615036991608, 'reg_lambda': 0.013171631899495958}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████▏            | 442/500 [32:04<03:21,  3.47s/it]

[I 2026-05-19 12:27:31,896] Trial 439 finished with value: 0.9497842378477557 and parameters: {'n_estimators': 258, 'learning_rate': 0.01296111802093999, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 36, 'subsample': 0.9982316446639874, 'colsample_bytree': 0.624468049350164, 'reg_alpha': 2.4416641689461613, 'reg_lambda': 0.0929334170055585}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:27:31,911] Trial 443 finished with value: 0.9497652717937886 and parameters: {'n_estimators': 258, 'learning_rate': 0.014326464389666291, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 37, 'subsample': 0.9490551327400313, 'colsample_bytree': 0.6250972373192013, 'reg_alpha': 9.132149573818072, 'reg_lambda': 0.0139482239431299}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████▋            | 444/500 [32:07<02:22,  2.55s/it]

[I 2026-05-19 12:27:34,841] Trial 442 finished with value: 0.9498665458320523 and parameters: {'n_estimators': 259, 'learning_rate': 0.0499144545678217, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 35, 'subsample': 0.9479539970145149, 'colsample_bytree': 0.6195790033485662, 'reg_alpha': 9.027770136266312, 'reg_lambda': 0.01297444264390873}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  89%|█████████████████████████████████████████████████████████████████████████████████████████████████▉            | 445/500 [32:16<03:50,  4.19s/it]

[I 2026-05-19 12:27:44,016] Trial 444 finished with value: 0.9498674087770411 and parameters: {'n_estimators': 258, 'learning_rate': 0.04992700419015267, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 36, 'subsample': 0.9458378667636141, 'colsample_bytree': 0.6197335485472005, 'reg_alpha': 9.68613521201259, 'reg_lambda': 0.013278129497976554}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████            | 446/500 [32:17<02:59,  3.32s/it]

[I 2026-05-19 12:27:44,875] Trial 445 finished with value: 0.9498273210459118 and parameters: {'n_estimators': 257, 'learning_rate': 0.04991977585669032, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 36, 'subsample': 0.9449950018674301, 'colsample_bytree': 0.619875366669654, 'reg_alpha': 2.400434605448074e-05, 'reg_lambda': 0.0001208826848185906}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████▎           | 447/500 [32:19<02:42,  3.06s/it]

[I 2026-05-19 12:27:47,239] Trial 446 finished with value: 0.9498539359274588 and parameters: {'n_estimators': 259, 'learning_rate': 0.049834034623254815, 'max_depth': 3, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.9444280331312098, 'colsample_bytree': 0.61951315578067, 'reg_alpha': 9.513382078460024, 'reg_lambda': 0.013411146310331842}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  90%|██████████████████████████████████████████████████████████████████████████████████████████████████▌           | 448/500 [32:28<04:13,  4.88s/it]

[I 2026-05-19 12:27:56,791] Trial 451 finished with value: 0.9498328152590103 and parameters: {'n_estimators': 131, 'learning_rate': 0.0458594649633231, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 20, 'subsample': 0.9457292194321599, 'colsample_bytree': 0.6423200032026686, 'reg_alpha': 9.054447205545936, 'reg_lambda': 0.013173043498707513}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  90%|██████████████████████████████████████████████████████████████████████████████████████████████████▊           | 449/500 [32:33<04:07,  4.86s/it]

[I 2026-05-19 12:28:01,587] Trial 447 finished with value: 0.9498641779697244 and parameters: {'n_estimators': 259, 'learning_rate': 0.0457512200845179, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.9454348190049396, 'colsample_bytree': 0.6201292995355496, 'reg_alpha': 9.234228925917783, 'reg_lambda': 0.01415763394182728}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████           | 450/500 [32:43<05:13,  6.26s/it]

[I 2026-05-19 12:28:11,321] Trial 448 finished with value: 0.9498633289326864 and parameters: {'n_estimators': 259, 'learning_rate': 0.049972767647109395, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 20, 'subsample': 0.9463868980179849, 'colsample_bytree': 0.6253266694210758, 'reg_alpha': 8.983094779895119, 'reg_lambda': 0.013757281823831909}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████▏          | 451/500 [32:45<03:58,  4.87s/it]

[I 2026-05-19 12:28:12,813] Trial 449 finished with value: 0.949859964840565 and parameters: {'n_estimators': 258, 'learning_rate': 0.045808136829413204, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 20, 'subsample': 0.9466665542601567, 'colsample_bytree': 0.6200396524191503, 'reg_alpha': 10.683193473307803, 'reg_lambda': 0.00013536491600860703}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████▍          | 452/500 [32:48<03:31,  4.41s/it]

[I 2026-05-19 12:28:16,111] Trial 450 finished with value: 0.9498723658829586 and parameters: {'n_estimators': 259, 'learning_rate': 0.04997340016110198, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 42, 'subsample': 0.9465183141277537, 'colsample_bytree': 0.6185130004853906, 'reg_alpha': 9.345566119006914, 'reg_lambda': 0.012977499834146006}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  91%|███████████████████████████████████████████████████████████████████████████████████████████████████▋          | 453/500 [32:57<04:27,  5.70s/it]

[I 2026-05-19 12:28:24,878] Trial 452 finished with value: 0.9498651548936982 and parameters: {'n_estimators': 264, 'learning_rate': 0.0457224492878282, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 20, 'subsample': 0.9443830383762942, 'colsample_bytree': 0.6399067301792069, 'reg_alpha': 8.283034718485116, 'reg_lambda': 0.014177976216081278}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:28:24,925] Trial 454 finished with value: 0.9498643093026893 and parameters: {'n_estimators': 266, 'learning_rate': 0.04576327205602743, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 43, 'subsample': 0.943687160158283, 'colsample_bytree': 0.63969018162896, 'reg_alpha': 8.171541783693641, 'reg_lambda': 0.013927464067420684}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████          | 455/500 [32:57<02:23,  3.20s/it]

[I 2026-05-19 12:28:25,369] Trial 453 finished with value: 0.9498577506322758 and parameters: {'n_estimators': 264, 'learning_rate': 0.04998728220280491, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 283, 'subsample': 0.9312642371226727, 'colsample_bytree': 0.6418913722855082, 'reg_alpha': 7.917829554431253, 'reg_lambda': 0.013004633570899754}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████▎         | 456/500 [33:00<02:16,  3.11s/it]

[I 2026-05-19 12:28:28,217] Trial 455 finished with value: 0.9498666965631168 and parameters: {'n_estimators': 265, 'learning_rate': 0.04590591849687154, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 44, 'subsample': 0.9323844246319368, 'colsample_bytree': 0.600297445034562, 'reg_alpha': 12.05624118457657, 'reg_lambda': 0.0479016157905806}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████▌         | 457/500 [33:08<03:09,  4.42s/it]

[I 2026-05-19 12:28:36,344] Trial 456 finished with value: 0.949871206450748 and parameters: {'n_estimators': 266, 'learning_rate': 0.046101280170606954, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 21, 'subsample': 0.9317161399082261, 'colsample_bytree': 0.6405284949891907, 'reg_alpha': 11.827418743788474, 'reg_lambda': 0.048042141174832804}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████▊         | 458/500 [33:11<02:45,  3.95s/it]

[I 2026-05-19 12:28:39,037] Trial 457 finished with value: 0.9498628151553016 and parameters: {'n_estimators': 263, 'learning_rate': 0.046223488483056276, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 20, 'subsample': 0.9316304592033081, 'colsample_bytree': 0.6410816976718797, 'reg_alpha': 8.069307918653633, 'reg_lambda': 0.021011465370866567}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  92%|████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 459/500 [33:15<02:43,  3.99s/it]

[I 2026-05-19 12:28:43,143] Trial 458 finished with value: 0.9498616125167931 and parameters: {'n_estimators': 265, 'learning_rate': 0.04579112598559686, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 20, 'subsample': 0.9317714729721824, 'colsample_bytree': 0.6408500717083145, 'reg_alpha': 12.142461128864895, 'reg_lambda': 0.047978956630652075}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 460/500 [33:21<02:58,  4.47s/it]

[I 2026-05-19 12:28:48,820] Trial 459 finished with value: 0.949848998119123 and parameters: {'n_estimators': 264, 'learning_rate': 0.04641467713776491, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 44, 'subsample': 0.9337281001693769, 'colsample_bytree': 0.6398279412386674, 'reg_alpha': 0.00032659268430386195, 'reg_lambda': 0.05119871684861865}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍        | 461/500 [33:26<03:03,  4.71s/it]

[I 2026-05-19 12:28:54,098] Trial 460 finished with value: 0.949863319562068 and parameters: {'n_estimators': 265, 'learning_rate': 0.045984644094308434, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 44, 'subsample': 0.9335740119639612, 'colsample_bytree': 0.6414359064693207, 'reg_alpha': 12.849587054160478, 'reg_lambda': 0.051853060237136546}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 462/500 [33:38<04:23,  6.93s/it]

[I 2026-05-19 12:29:06,402] Trial 461 finished with value: 0.9498643507434356 and parameters: {'n_estimators': 265, 'learning_rate': 0.0461302260402845, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 43, 'subsample': 0.9310928097756522, 'colsample_bytree': 0.639958977696127, 'reg_alpha': 13.025259881260277, 'reg_lambda': 0.04710238140692428}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  93%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 463/500 [33:38<03:03,  4.95s/it]

[I 2026-05-19 12:29:06,627] Trial 462 finished with value: 0.9498433558564823 and parameters: {'n_estimators': 265, 'learning_rate': 0.04696523167394856, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.9758630823713422, 'colsample_bytree': 0.6419577049004969, 'reg_alpha': 0.005149030162953224, 'reg_lambda': 0.05077553093008015}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████        | 464/500 [33:41<02:33,  4.26s/it]

[I 2026-05-19 12:29:09,230] Trial 463 finished with value: 0.9498658089906622 and parameters: {'n_estimators': 265, 'learning_rate': 0.04653873668333618, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 45, 'subsample': 0.9639831361151884, 'colsample_bytree': 0.6058259918429371, 'reg_alpha': 6.902932512883684, 'reg_lambda': 0.023174643447523225}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎       | 465/500 [33:47<02:48,  4.82s/it]

[I 2026-05-19 12:29:15,386] Trial 464 finished with value: 0.9498646473472874 and parameters: {'n_estimators': 252, 'learning_rate': 0.046740352019592014, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 45, 'subsample': 0.9758829898062843, 'colsample_bytree': 0.6041410698967578, 'reg_alpha': 12.295618154095756, 'reg_lambda': 0.0491835575196569}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌       | 466/500 [33:50<02:26,  4.30s/it]

[I 2026-05-19 12:29:18,474] Trial 465 finished with value: 0.9498716786545748 and parameters: {'n_estimators': 251, 'learning_rate': 0.047038640924922034, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 30, 'subsample': 0.9750042632376219, 'colsample_bytree': 0.6313092602416049, 'reg_alpha': 13.08182083549768, 'reg_lambda': 0.02111443725857588}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 467/500 [33:51<01:43,  3.13s/it]

[I 2026-05-19 12:29:18,844] Trial 466 finished with value: 0.9498686877399505 and parameters: {'n_estimators': 253, 'learning_rate': 0.047155486661842626, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 43, 'subsample': 0.980286738016867, 'colsample_bytree': 0.6012001694980806, 'reg_alpha': 12.344934473367502, 'reg_lambda': 0.020289914845906587}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  94%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 468/500 [33:53<01:36,  3.01s/it]

[I 2026-05-19 12:29:21,589] Trial 467 finished with value: 0.9498668482549713 and parameters: {'n_estimators': 252, 'learning_rate': 0.04719558110672007, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 52, 'subsample': 0.964225584919561, 'colsample_bytree': 0.6318244720824243, 'reg_alpha': 3.398938970608968, 'reg_lambda': 0.024596191574654976}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 469/500 [34:01<02:18,  4.47s/it]

[I 2026-05-19 12:29:29,468] Trial 469 finished with value: 0.9498651722974236 and parameters: {'n_estimators': 251, 'learning_rate': 0.047319942905167126, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 52, 'subsample': 0.9631744093321235, 'colsample_bytree': 0.6330494795775681, 'reg_alpha': 13.275084296347044, 'reg_lambda': 0.002169335142775457}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 470/500 [34:02<01:38,  3.29s/it]

[I 2026-05-19 12:29:29,998] Trial 468 finished with value: 0.949858431033667 and parameters: {'n_estimators': 251, 'learning_rate': 0.04726221815493774, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 44, 'subsample': 0.9600491820180576, 'colsample_bytree': 0.6333651234447838, 'reg_alpha': 15.05395156851931, 'reg_lambda': 0.021665098234045884}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 471/500 [34:04<01:28,  3.07s/it]

[I 2026-05-19 12:29:32,537] Trial 478 finished with value: 0.9497122128429674 and parameters: {'n_estimators': 53, 'learning_rate': 0.0417540985958141, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 53, 'subsample': 0.9890981993847092, 'colsample_bytree': 0.6082052742474363, 'reg_alpha': 16.785447683423175, 'reg_lambda': 0.022204212028259167}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 472/500 [34:06<01:11,  2.56s/it]

[I 2026-05-19 12:29:33,915] Trial 470 finished with value: 0.9498455359745452 and parameters: {'n_estimators': 252, 'learning_rate': 0.04726127755766399, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 53, 'subsample': 0.9637111640512622, 'colsample_bytree': 0.6309263903947998, 'reg_alpha': 0.004930977661887389, 'reg_lambda': 0.02322420045063404}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████      | 473/500 [34:17<02:23,  5.32s/it]

[I 2026-05-19 12:29:45,679] Trial 471 finished with value: 0.9498618790788609 and parameters: {'n_estimators': 281, 'learning_rate': 0.04753626365443948, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 53, 'subsample': 0.9589612873894153, 'colsample_bytree': 0.6309091810170637, 'reg_alpha': 3.37463589437231, 'reg_lambda': 0.024837935545156075}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 474/500 [34:18<01:38,  3.80s/it]

[I 2026-05-19 12:29:45,950] Trial 472 finished with value: 0.9498604809868165 and parameters: {'n_estimators': 252, 'learning_rate': 0.04753391193205899, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 64, 'subsample': 0.9640987390049794, 'colsample_bytree': 0.6294332170753216, 'reg_alpha': 3.3663287054827116, 'reg_lambda': 0.02270923207064892}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 475/500 [34:29<02:31,  6.06s/it]

[I 2026-05-19 12:29:57,279] Trial 473 finished with value: 0.9498614196198236 and parameters: {'n_estimators': 251, 'learning_rate': 0.042322537422507495, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 52, 'subsample': 0.9622970006126087, 'colsample_bytree': 0.6305018765306822, 'reg_alpha': 3.56357078100893, 'reg_lambda': 0.022626416203279723}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 476/500 [34:32<02:04,  5.20s/it]

[I 2026-05-19 12:30:00,489] Trial 474 finished with value: 0.9498682834266052 and parameters: {'n_estimators': 252, 'learning_rate': 0.04744220351871825, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 62, 'subsample': 0.9612297344204827, 'colsample_bytree': 0.6336732818999095, 'reg_alpha': 3.3259298854827177, 'reg_lambda': 0.025131151343092607}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 477/500 [34:39<02:08,  5.60s/it]

[I 2026-05-19 12:30:07,011] Trial 475 finished with value: 0.9498635396194484 and parameters: {'n_estimators': 281, 'learning_rate': 0.04211014729657142, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 53, 'subsample': 0.9562589176882496, 'colsample_bytree': 0.6309948905796054, 'reg_alpha': 3.532739757969726, 'reg_lambda': 0.0020739402308674014}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 478/500 [34:40<01:31,  4.17s/it]

[I 2026-05-19 12:30:07,853] Trial 476 finished with value: 0.9498552833272772 and parameters: {'n_estimators': 252, 'learning_rate': 0.042638931516652996, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 63, 'subsample': 0.9605840138944552, 'colsample_bytree': 0.6313580503442824, 'reg_alpha': 3.3920484043177757, 'reg_lambda': 0.020654643771922842}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 479/500 [34:44<01:27,  4.15s/it]

[I 2026-05-19 12:30:11,942] Trial 479 finished with value: 0.9498558267709647 and parameters: {'n_estimators': 252, 'learning_rate': 0.0429100375645891, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 29, 'subsample': 0.9810168867984296, 'colsample_bytree': 0.6124862021277107, 'reg_alpha': 19.21208393128195, 'reg_lambda': 0.020151636217493066}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 480/500 [34:49<01:29,  4.48s/it]

[I 2026-05-19 12:30:17,182] Trial 477 finished with value: 0.9498567127255522 and parameters: {'n_estimators': 281, 'learning_rate': 0.0422656579634549, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 53, 'subsample': 0.9841019438375241, 'colsample_bytree': 0.6276886432049936, 'reg_alpha': 18.47930858968582, 'reg_lambda': 0.021153630939695967}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 481/500 [34:55<01:31,  4.84s/it]

[I 2026-05-19 12:30:22,858] Trial 480 finished with value: 0.9498561127083113 and parameters: {'n_estimators': 251, 'learning_rate': 0.04246939710218841, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 65, 'subsample': 0.9609843651204577, 'colsample_bytree': 0.6087338400342794, 'reg_alpha': 18.919593377858828, 'reg_lambda': 0.019840880306829588}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████    | 482/500 [35:03<01:45,  5.87s/it]

[I 2026-05-19 12:30:31,153] Trial 481 finished with value: 0.9498545631897775 and parameters: {'n_estimators': 281, 'learning_rate': 0.04232557322740809, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 62, 'subsample': 0.9848969132940214, 'colsample_bytree': 0.60079695010655, 'reg_alpha': 20.097318435753376, 'reg_lambda': 0.020622979243480322}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 483/500 [35:03<01:11,  4.19s/it]

[I 2026-05-19 12:30:31,399] Trial 483 finished with value: 0.9498561763012938 and parameters: {'n_estimators': 280, 'learning_rate': 0.042034758083514485, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 61, 'subsample': 0.983166082373261, 'colsample_bytree': 0.6064139285002769, 'reg_alpha': 31.993530917693686, 'reg_lambda': 0.01861359826017027}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 484/500 [35:04<00:49,  3.08s/it]

[I 2026-05-19 12:30:31,904] Trial 482 finished with value: 0.949857911557707 and parameters: {'n_estimators': 281, 'learning_rate': 0.042120622509556976, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 53, 'subsample': 0.9815900388327439, 'colsample_bytree': 0.6082577518920134, 'reg_alpha': 27.26487224105715, 'reg_lambda': 0.017210359505587056}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 485/500 [35:08<00:52,  3.53s/it]

[I 2026-05-19 12:30:36,481] Trial 489 finished with value: 0.9497594829971 and parameters: {'n_estimators': 279, 'learning_rate': 0.043646192668524125, 'max_depth': 1, 'num_leaves': 12, 'min_child_samples': 29, 'subsample': 0.9866358404583692, 'colsample_bytree': 0.6117146277494224, 'reg_alpha': 26.21338580889061, 'reg_lambda': 0.009818982536869605}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 486/500 [35:09<00:37,  2.66s/it]

[I 2026-05-19 12:30:37,086] Trial 488 finished with value: 0.9497697337298622 and parameters: {'n_estimators': 281, 'learning_rate': 0.04236799419154502, 'max_depth': 1, 'num_leaves': 12, 'min_child_samples': 30, 'subsample': 0.9810226139908973, 'colsample_bytree': 0.6112068438868671, 'reg_alpha': 18.740006658912865, 'reg_lambda': 0.01755557505923717}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 487/500 [35:12<00:36,  2.80s/it]

[I 2026-05-19 12:30:40,236] Trial 485 finished with value: 0.9498543512489199 and parameters: {'n_estimators': 253, 'learning_rate': 0.042170384491325465, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 29, 'subsample': 0.9785816478513835, 'colsample_bytree': 0.6120775263917598, 'reg_alpha': 20.96318340889551, 'reg_lambda': 0.009887864405192574}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:30:40,421] Trial 492 pruned.

Best trial: 286. Best value: 0.949875:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 489/500 [35:19<00:38,  3.49s/it]

[I 2026-05-19 12:30:47,372] Trial 484 finished with value: 0.949853575422887 and parameters: {'n_estimators': 252, 'learning_rate': 0.042218126351886806, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 61, 'subsample': 0.9719988681499168, 'colsample_bytree': 0.6120464247472426, 'reg_alpha': 31.687046388925122, 'reg_lambda': 0.009836430793456245}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  98%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 490/500 [35:27<00:49,  4.94s/it]

[I 2026-05-19 12:30:55,678] Trial 486 finished with value: 0.9498604488679886 and parameters: {'n_estimators': 280, 'learning_rate': 0.04458588014767399, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 28, 'subsample': 0.9841128864631926, 'colsample_bytree': 0.6098575174657797, 'reg_alpha': 23.985472913491986, 'reg_lambda': 0.009426491123555593}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 491/500 [35:30<00:37,  4.21s/it]

[I 2026-05-19 12:30:58,201] Trial 487 finished with value: 0.9498572001103607 and parameters: {'n_estimators': 279, 'learning_rate': 0.042529794271924694, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 29, 'subsample': 0.9883516228698638, 'colsample_bytree': 0.6010331159778108, 'reg_alpha': 29.787638136529747, 'reg_lambda': 0.009872725633531169}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 492/500 [35:38<00:43,  5.47s/it]

[I 2026-05-19 12:31:06,617] Trial 490 finished with value: 0.9498656653083912 and parameters: {'n_estimators': 280, 'learning_rate': 0.043951543524022085, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 206, 'subsample': 0.9981487853852716, 'colsample_bytree': 0.60748599823305, 'reg_alpha': 25.052550278704626, 'reg_lambda': 0.016513307393826136}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 493/500 [35:40<00:29,  4.24s/it]

[I 2026-05-19 12:31:07,981] Trial 491 finished with value: 0.9498638942130692 and parameters: {'n_estimators': 272, 'learning_rate': 0.044398590680573224, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 30, 'subsample': 0.983908162943303, 'colsample_bytree': 0.6066265283992689, 'reg_alpha': 27.89720043551773, 'reg_lambda': 0.009328892862919528}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  99%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 494/500 [35:49<00:34,  5.74s/it]

[I 2026-05-19 12:31:17,223] Trial 495 finished with value: 0.9498575980676035 and parameters: {'n_estimators': 270, 'learning_rate': 0.04524522025455935, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 29, 'subsample': 0.9735049383880789, 'colsample_bytree': 0.6512974372994902, 'reg_alpha': 5.50945416196891, 'reg_lambda': 0.010085238821130129}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 496/500 [35:49<00:11,  2.91s/it]

[I 2026-05-19 12:31:17,516] Trial 493 finished with value: 0.949854576321423 and parameters: {'n_estimators': 270, 'learning_rate': 0.04384265482931108, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 41, 'subsample': 0.9928417151272527, 'colsample_bytree': 0.613871514625698, 'reg_alpha': 32.353587792335404, 'reg_lambda': 0.008332295020735767}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:31:17,632] Trial 494 finished with value: 0.9498646487816439 and parameters: {'n_estimators': 271, 'learning_rate': 0.044351479392672644, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 32, 'subsample': 0.993145128850272, 'colsample_bytree': 0.6524687661803421, 'reg_alpha': 27.34886407822162, 'reg_lambda': 0.008914000617185782}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 497/500 [35:50<00:06,  2.30s/it]

[I 2026-05-19 12:31:18,506] Trial 496 finished with value: 0.9498587792768755 and parameters: {'n_estimators': 269, 'learning_rate': 0.04494063170965147, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 300, 'subsample': 0.9237020748038881, 'colsample_bytree': 0.6499276222856707, 'reg_alpha': 5.186829751801562, 'reg_lambda': 0.009387345721878142}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 498/500 [35:50<00:03,  1.68s/it]

[I 2026-05-19 12:31:18,748] Trial 497 finished with value: 0.9498660440640055 and parameters: {'n_estimators': 270, 'learning_rate': 0.04457799568816225, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 43, 'subsample': 0.9404941248844878, 'colsample_bytree': 0.6523962186108764, 'reg_alpha': 5.313988226694605, 'reg_lambda': 0.009470118202303361}. Best is trial 286 with value: 0.9498753425732973.

Best trial: 286. Best value: 0.949875: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [35:51<00:00,  4.30s/it]

[I 2026-05-19 12:31:18,979] Trial 498 finished with value: 0.9498628628231216 and parameters: {'n_estimators': 271, 'learning_rate': 0.04471282068563977, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 41, 'subsample': 0.9968985715282146, 'colsample_bytree': 0.6482620052770925, 'reg_alpha': 5.017336723017805, 'reg_lambda': 0.07115848738449355}. Best is trial 286 with value: 0.9498753425732973.
[I 2026-05-19 12:31:19,170] Trial 499 finished with value: 0.9498645082322421 and parameters: {'n_estimators': 273, 'learning_rate': 0.044543423434898574, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 41, 'subsample': 0.9957323589250318, 'colsample_bytree': 0.6508950729547044, 'reg_alpha': 5.380106408071916, 'reg_lambda': 0.07114107261577225}. Best is trial 286 with value: 0.9498753425732973.
Best trial score:
0.9498753425732973

Best params:
{'n_estimators': 264, 'learning_rate': 0.04988723993993441, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 33, 'subsample': 0.9378306380798972, 'colsample_bytree': 0.6226095012834436, 'reg_alpha': 5.126147127831397, 'reg_lambda': 0.06618224883283678}

In [12]:
stacking_lgbm = LGBMClassifier(**study.best_params).fit(X_train, y_train.PitNextLap)

[LightGBM] [Info] Number of positive: 87381, number of negative: 351759
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001243 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 439140, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198982 -> initscore=-1.392668
[LightGBM] [Info] Start training from score -1.392668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

# Submission

In [13]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [14]:
submission['PitNextLap'] = stacking_lgbm.predict_proba(X_test)[:, 1]

In [15]:
submission.to_csv('../data/submission/submission.csv', index=False)

In [16]:
X_train.columns

Index(['lgbm_proba', 'cat_proba', 'xgb_proba', 'hist_proba', 'lg_proba',
       'knn_proba', 'ridge_proba', 'voting_lgbm_cat_xgb_hist_proba',
       'voting_lg_ridge_proba',
       'stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba'],
      dtype='str')