# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from catboost import CatBoostClassifier

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import StackingClassifier, VotingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

# Loading Dataset

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking2.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking2.parquet')

In [4]:
X_train.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,ridge_proba,voting_lgbm_cat_xgb_hist_proba,voting_lg_ridge_proba,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.519677,0.868510,0.664963,0.772948
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.395214,0.772514,0.543445,0.595178
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.259447,0.717012,0.409891,0.515461
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,0.005106,0.005494,0.003682,0.001281
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,0.150282,0.482416,0.283014,0.293768

In [5]:
X_test.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,ridge_proba,voting_lgbm_cat_xgb_hist_proba,voting_lg_ridge_proba,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,0.004726,0.019849,0.005577,0.006190
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,0.033245,0.012173,0.048652,0.003070
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,0.003903,0.010304,0.004212,0.003695
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.296579,0.444558,0.477315,0.232534
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.548189,0.939648,0.695206,0.894775

# Machine Learning

In [6]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "C": trial.suggest_float("C", 1e-5, 100, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
        "max_iter": trial.suggest_int("max_iter", 1000, 5000)
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LogisticRegression(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-19 11:37:32,165] A new study created in memory with name: no-name-848536ac-2236-4bbd-94a8-b1aa1993c2bf
Best trial: 10. Best value: 0.5:   0%|▏                                                                                                                     | 1/500 [00:06<57:15,  6.88s/it]

[I 2026-05-19 11:37:39,049] Trial 10 finished with value: 0.5 and parameters: {'solver': 'saga', 'C': 1.2905632598245504e-05, 'l1_ratio': 0.8220212359286581, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.6115877313136515e-06, 'max_iter': 1273}. Best is trial 10 with value: 0.5.

Best trial: 8. Best value: 0.805073:   0%|▍                                                                                                                 | 2/500 [00:09<36:25,  4.39s/it]

[I 2026-05-19 11:37:41,679] Trial 8 finished with value: 0.8050733585051886 and parameters: {'solver': 'saga', 'C': 0.0002033376587658991, 'l1_ratio': 0.9496843244387186, 'class_weight': None, 'fit_intercept': False, 'tol': 0.004601133976411335, 'max_iter': 1773}. Best is trial 8 with value: 0.8050733585051886.

Best trial: 5. Best value: 0.910234:   1%|▋                                                                                                                 | 3/500 [00:10<21:50,  2.64s/it]

[I 2026-05-19 11:37:42,240] Trial 5 finished with value: 0.9102341356874815 and parameters: {'solver': 'saga', 'C': 0.002894938401265087, 'l1_ratio': 0.07975429140051449, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006917889597280668, 'max_iter': 1218}. Best is trial 5 with value: 0.9102341356874815.

Best trial: 5. Best value: 0.910234:   1%|▉                                                                                                                 | 4/500 [00:12<21:15,  2.57s/it]

[I 2026-05-19 11:37:44,708] Trial 3 finished with value: 0.8167412553048674 and parameters: {'solver': 'saga', 'C': 16.136110676048776, 'l1_ratio': 0.7874214926584022, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0015878610005688948, 'max_iter': 4497}. Best is trial 5 with value: 0.9102341356874815.

Best trial: 2. Best value: 0.949573:   1%|█▏                                                                                                                | 5/500 [00:14<20:12,  2.45s/it]

[I 2026-05-19 11:37:46,943] Trial 2 finished with value: 0.9495730183262004 and parameters: {'solver': 'saga', 'C': 2.214748958452084e-05, 'l1_ratio': 0.2007117899853178, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0022998692350038093, 'max_iter': 4180}. Best is trial 2 with value: 0.9495730183262004.

Best trial: 2. Best value: 0.949573:   1%|█▎                                                                                                                | 6/500 [00:16<17:56,  2.18s/it]

[I 2026-05-19 11:37:48,594] Trial 14 pruned.

Best trial: 2. Best value: 0.949573:   1%|█▌                                                                                                                | 7/500 [00:21<25:45,  3.14s/it]

[I 2026-05-19 11:37:53,698] Trial 1 finished with value: 0.9486632456963957 and parameters: {'solver': 'saga', 'C': 5.6352879856096996e-05, 'l1_ratio': 0.38176693771699977, 'class_weight': None, 'fit_intercept': True, 'tol': 3.322406607368051e-05, 'max_iter': 2067}. Best is trial 2 with value: 0.9495730183262004.

Best trial: 2. Best value: 0.949573:   2%|█▊                                                                                                                | 8/500 [00:23<22:04,  2.69s/it]

[I 2026-05-19 11:37:55,443] Trial 11 finished with value: 0.9029866240168166 and parameters: {'solver': 'saga', 'C': 0.022959535302834854, 'l1_ratio': 0.946541384737992, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 9.08782477075731e-06, 'max_iter': 4784}. Best is trial 2 with value: 0.9495730183262004.

Best trial: 2. Best value: 0.949573:   2%|██                                                                                                                | 9/500 [00:23<16:49,  2.06s/it]

[I 2026-05-19 11:37:56,095] Trial 6 pruned.

Best trial: 2. Best value: 0.949573:   2%|██▎                                                                                                              | 10/500 [00:26<18:15,  2.23s/it]

[I 2026-05-19 11:37:58,721] Trial 0 pruned.

Best trial: 2. Best value: 0.949573:   2%|██▍                                                                                                              | 11/500 [00:26<13:31,  1.66s/it]

[I 2026-05-19 11:37:59,090] Trial 4 finished with value: 0.9030885224518788 and parameters: {'solver': 'saga', 'C': 0.04384217495882906, 'l1_ratio': 0.6276756223692993, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 2.0685128467372134e-06, 'max_iter': 1572}. Best is trial 2 with value: 0.9495730183262004.

Best trial: 2. Best value: 0.949573:   2%|██▋                                                                                                              | 12/500 [00:29<16:57,  2.08s/it]

[I 2026-05-19 11:38:02,152] Trial 13 finished with value: 0.9475906715988422 and parameters: {'solver': 'saga', 'C': 3.969441860950811e-05, 'l1_ratio': 0.2319009782733923, 'class_weight': None, 'fit_intercept': True, 'tol': 4.13709409120289e-05, 'max_iter': 1752}. Best is trial 2 with value: 0.9495730183262004.

Best trial: 2. Best value: 0.949573:   3%|██▉                                                                                                              | 13/500 [00:34<24:03,  2.96s/it]

[I 2026-05-19 11:38:07,134] Trial 12 finished with value: 0.9494936191413462 and parameters: {'solver': 'saga', 'C': 1.0430703942368962e-05, 'l1_ratio': 0.37957942309084625, 'class_weight': None, 'fit_intercept': True, 'tol': 7.832672022330078e-06, 'max_iter': 1022}. Best is trial 2 with value: 0.9495730183262004.

Best trial: 2. Best value: 0.949573:   3%|███▏                                                                                                             | 14/500 [00:36<20:28,  2.53s/it]

[I 2026-05-19 11:38:08,662] Trial 16 pruned.

Best trial: 18. Best value: 0.949657:   3%|███▎                                                                                                            | 15/500 [00:36<15:00,  1.86s/it]

[I 2026-05-19 11:38:08,959] Trial 18 finished with value: 0.9496565668957343 and parameters: {'solver': 'saga', 'C': 9.35045639739935e-05, 'l1_ratio': 0.7027268707360511, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0006234227483634785, 'max_iter': 4539}. Best is trial 18 with value: 0.9496565668957343.

Best trial: 17. Best value: 0.949671:   3%|███▌                                                                                                            | 16/500 [00:38<15:33,  1.93s/it]

[I 2026-05-19 11:38:11,055] Trial 17 finished with value: 0.9496713045367272 and parameters: {'solver': 'saga', 'C': 0.00017701495900707755, 'l1_ratio': 0.8593803210751783, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8476637509359414e-05, 'max_iter': 4301}. Best is trial 17 with value: 0.9496713045367272.

Best trial: 17. Best value: 0.949671:   3%|███▊                                                                                                            | 17/500 [00:39<12:10,  1.51s/it]

[I 2026-05-19 11:38:11,596] Trial 15 finished with value: 0.9492614750884997 and parameters: {'solver': 'saga', 'C': 4.6269850417432696e-05, 'l1_ratio': 0.0735662705147, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 4.173271396641621e-06, 'max_iter': 1957}. Best is trial 17 with value: 0.9496713045367272.

Best trial: 17. Best value: 0.949671:   4%|████▎                                                                                                           | 19/500 [00:45<15:49,  1.97s/it]

[I 2026-05-19 11:38:17,252] Trial 21 finished with value: 0.9489774775119566 and parameters: {'solver': 'saga', 'C': 0.11565290688121219, 'l1_ratio': 0.004397733493563621, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0002693962530688517, 'max_iter': 3569}. Best is trial 17 with value: 0.9496713045367272.
[I 2026-05-19 11:38:17,401] Trial 22 finished with value: 0.9495940348036577 and parameters: {'solver': 'saga', 'C': 1.0678756825828268e-05, 'l1_ratio': 0.24224898008166235, 'class_weight': None, 'fit_intercept': True, 'tol': 9.255259476637317e-05, 'max_iter': 3242}. Best is trial 17 with value: 0.9496713045367272.

Best trial: 17. Best value: 0.949671:   4%|████▍                                                                                                           | 20/500 [00:50<24:21,  3.04s/it]

[I 2026-05-19 11:38:22,922] Trial 23 finished with value: 0.949493753517847 and parameters: {'solver': 'saga', 'C': 1.1184024180909316e-05, 'l1_ratio': 0.32728929079413394, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.000232599439925758, 'max_iter': 3404}. Best is trial 17 with value: 0.9496713045367272.

Best trial: 17. Best value: 0.949671:   4%|████▋                                                                                                           | 21/500 [00:53<22:47,  2.85s/it]

[I 2026-05-19 11:38:25,354] Trial 25 finished with value: 0.94964701579968 and parameters: {'solver': 'saga', 'C': 1.0846549458413583e-05, 'l1_ratio': 0.29291397524409635, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003288850412344941, 'max_iter': 3576}. Best is trial 17 with value: 0.9496713045367272.

Best trial: 17. Best value: 0.949671:   4%|████▉                                                                                                           | 22/500 [00:53<17:00,  2.14s/it]

[I 2026-05-19 11:38:25,811] Trial 26 pruned.

Best trial: 17. Best value: 0.949671:   5%|█████▏                                                                                                          | 23/500 [00:55<15:54,  2.00s/it]

[I 2026-05-19 11:38:27,498] Trial 24 finished with value: 0.948954375501421 and parameters: {'solver': 'saga', 'C': 1.069245571753863e-05, 'l1_ratio': 0.26143276212918903, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0003126289102349128, 'max_iter': 3556}. Best is trial 17 with value: 0.9496713045367272.

Best trial: 30. Best value: 0.949686:   5%|█████▍                                                                                                          | 24/500 [01:00<22:32,  2.84s/it]

[I 2026-05-19 11:38:32,304] Trial 30 finished with value: 0.9496864775412 and parameters: {'solver': 'saga', 'C': 0.0002660971875020496, 'l1_ratio': 0.7968584963471345, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00039729839547459505, 'max_iter': 2693}. Best is trial 30 with value: 0.9496864775412.

Best trial: 29. Best value: 0.949689:   5%|█████▌                                                                                                          | 25/500 [01:02<21:27,  2.71s/it]

[I 2026-05-19 11:38:34,710] Trial 29 finished with value: 0.949688670183275 and parameters: {'solver': 'saga', 'C': 0.0003227740567459819, 'l1_ratio': 0.8219657588216132, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00036956186796259277, 'max_iter': 4980}. Best is trial 29 with value: 0.949688670183275.

Best trial: 29. Best value: 0.949689:   5%|█████▊                                                                                                          | 26/500 [01:06<24:21,  3.08s/it]

[I 2026-05-19 11:38:38,657] Trial 31 finished with value: 0.949419765000402 and parameters: {'solver': 'saga', 'C': 0.0002732802775295812, 'l1_ratio': 0.547760381409135, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005328389459392104, 'max_iter': 2598}. Best is trial 29 with value: 0.949688670183275.

Best trial: 29. Best value: 0.949689:   5%|██████                                                                                                          | 27/500 [01:07<20:05,  2.55s/it]

[I 2026-05-19 11:38:39,964] Trial 33 finished with value: 0.9494085008966369 and parameters: {'solver': 'saga', 'C': 0.00025123180590385654, 'l1_ratio': 0.5471571206591752, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005678360914705547, 'max_iter': 2677}. Best is trial 29 with value: 0.949688670183275.

Best trial: 29. Best value: 0.949689:   6%|██████▎                                                                                                         | 28/500 [01:08<14:53,  1.89s/it]

[I 2026-05-19 11:38:40,325] Trial 32 finished with value: 0.9494072284903723 and parameters: {'solver': 'saga', 'C': 0.0002669169633254789, 'l1_ratio': 0.5430296022055798, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005834355958829101, 'max_iter': 3872}. Best is trial 29 with value: 0.949688670183275.

Best trial: 29. Best value: 0.949689:   6%|██████▍                                                                                                         | 29/500 [01:10<15:22,  1.96s/it]

[I 2026-05-19 11:38:42,442] Trial 34 finished with value: 0.9493251879611766 and parameters: {'solver': 'saga', 'C': 0.00022498153334684994, 'l1_ratio': 0.521400892863426, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007929621015716339, 'max_iter': 2513}. Best is trial 29 with value: 0.949688670183275.

Best trial: 29. Best value: 0.949689:   6%|██████▋                                                                                                         | 30/500 [01:11<14:47,  1.89s/it]

[I 2026-05-19 11:38:44,155] Trial 28 finished with value: 0.9494243067182246 and parameters: {'solver': 'saga', 'C': 0.27067407877285926, 'l1_ratio': 0.8142090916565248, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00040140689418225936, 'max_iter': 3531}. Best is trial 29 with value: 0.949688670183275.

Best trial: 29. Best value: 0.949689:   6%|██████▉                                                                                                         | 31/500 [01:12<11:41,  1.49s/it]

[I 2026-05-19 11:38:44,738] Trial 19 pruned.

Best trial: 35. Best value: 0.949689:   6%|███████▏                                                                                                        | 32/500 [01:14<13:49,  1.77s/it]

[I 2026-05-19 11:38:47,144] Trial 35 finished with value: 0.9496892426270925 and parameters: {'solver': 'saga', 'C': 0.00034832194775802437, 'l1_ratio': 0.841101789809332, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009981488506403092, 'max_iter': 2610}. Best is trial 35 with value: 0.9496892426270925.

Best trial: 35. Best value: 0.949689:   7%|███████▍                                                                                                        | 33/500 [01:17<15:15,  1.96s/it]

[I 2026-05-19 11:38:49,548] Trial 27 finished with value: 0.9494183113455994 and parameters: {'solver': 'saga', 'C': 0.3490997796123636, 'l1_ratio': 0.7910730393258883, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002483234680371367, 'max_iter': 3493}. Best is trial 35 with value: 0.9496892426270925.

Best trial: 35. Best value: 0.949689:   7%|███████▌                                                                                                        | 34/500 [01:20<16:49,  2.17s/it]

[I 2026-05-19 11:38:52,205] Trial 7 finished with value: 0.948897629461476 and parameters: {'solver': 'saga', 'C': 14.774437993515944, 'l1_ratio': 0.38385071340106336, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.391106332126993e-05, 'max_iter': 1559}. Best is trial 35 with value: 0.9496892426270925.

Best trial: 36. Best value: 0.949711:   7%|███████▊                                                                                                        | 35/500 [01:20<13:22,  1.73s/it]

[I 2026-05-19 11:38:52,905] Trial 36 finished with value: 0.949710592417303 and parameters: {'solver': 'saga', 'C': 0.0056544971234325815, 'l1_ratio': 0.8571272782630726, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010939290635449974, 'max_iter': 2670}. Best is trial 36 with value: 0.949710592417303.

Best trial: 37. Best value: 0.949714:   7%|████████                                                                                                        | 36/500 [01:26<22:49,  2.95s/it]

[I 2026-05-19 11:38:58,714] Trial 37 finished with value: 0.9497141816432014 and parameters: {'solver': 'saga', 'C': 0.00212255368757902, 'l1_ratio': 0.8483851022973911, 'class_weight': None, 'fit_intercept': True, 'tol': 8.526497708445396e-05, 'max_iter': 4980}. Best is trial 37 with value: 0.9497141816432014.

Best trial: 37. Best value: 0.949714:   7%|████████▎                                                                                                       | 37/500 [01:26<16:31,  2.14s/it]

[I 2026-05-19 11:38:58,961] Trial 38 finished with value: 0.9497115833485754 and parameters: {'solver': 'saga', 'C': 0.003640836543526127, 'l1_ratio': 0.8275488638389598, 'class_weight': None, 'fit_intercept': True, 'tol': 8.052400507881876e-05, 'max_iter': 4818}. Best is trial 37 with value: 0.9497141816432014.

Best trial: 37. Best value: 0.949714:   8%|████████▌                                                                                                       | 38/500 [01:27<13:27,  1.75s/it]

[I 2026-05-19 11:38:59,780] Trial 39 finished with value: 0.9497066695861299 and parameters: {'solver': 'saga', 'C': 0.008311582881333398, 'l1_ratio': 0.8648407464799512, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001240951482286704, 'max_iter': 4984}. Best is trial 37 with value: 0.9497141816432014.

Best trial: 40. Best value: 0.949715:   8%|████████▋                                                                                                       | 39/500 [01:28<12:14,  1.59s/it]

[I 2026-05-19 11:39:01,028] Trial 40 finished with value: 0.9497150883983189 and parameters: {'solver': 'saga', 'C': 0.002567946048216557, 'l1_ratio': 0.8785572436836986, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011952332710433978, 'max_iter': 4980}. Best is trial 40 with value: 0.9497150883983189.

Best trial: 42. Best value: 0.949716:   8%|████████▉                                                                                                       | 40/500 [01:30<12:48,  1.67s/it]

[I 2026-05-19 11:39:02,878] Trial 42 finished with value: 0.9497163933256789 and parameters: {'solver': 'saga', 'C': 0.0020394969935398095, 'l1_ratio': 0.8867120948564617, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014778650881997794, 'max_iter': 4890}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:   8%|█████████▏                                                                                                      | 41/500 [01:31<11:07,  1.45s/it]

[I 2026-05-19 11:39:03,824] Trial 41 finished with value: 0.9497139581679587 and parameters: {'solver': 'saga', 'C': 0.0029158445786303757, 'l1_ratio': 0.8688336583510513, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011823238202133823, 'max_iter': 4929}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:   8%|█████████▍                                                                                                      | 42/500 [01:33<12:45,  1.67s/it]

[I 2026-05-19 11:39:06,007] Trial 43 finished with value: 0.9497157927381152 and parameters: {'solver': 'saga', 'C': 0.0018447838625343569, 'l1_ratio': 0.8760174034532023, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012479232561671692, 'max_iter': 2433}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:   9%|█████████▋                                                                                                      | 43/500 [01:36<15:07,  1.99s/it]

[I 2026-05-19 11:39:08,728] Trial 44 finished with value: 0.9497161961776663 and parameters: {'solver': 'saga', 'C': 0.002254481587078336, 'l1_ratio': 0.8853623027413383, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010745637729695347, 'max_iter': 2234}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:   9%|█████████▊                                                                                                      | 44/500 [01:38<15:22,  2.02s/it]

[I 2026-05-19 11:39:10,838] Trial 45 finished with value: 0.9497132746354742 and parameters: {'solver': 'saga', 'C': 0.0031585724920262866, 'l1_ratio': 0.8689864695849748, 'class_weight': None, 'fit_intercept': True, 'tol': 8.509763755909963e-05, 'max_iter': 4968}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:   9%|██████████                                                                                                      | 45/500 [01:39<12:04,  1.59s/it]

[I 2026-05-19 11:39:11,413] Trial 46 finished with value: 0.9497110834884962 and parameters: {'solver': 'saga', 'C': 0.003880283362372162, 'l1_ratio': 0.863750081751711, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001238519285664596, 'max_iter': 2289}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:   9%|██████████▎                                                                                                     | 46/500 [01:45<22:28,  2.97s/it]

[I 2026-05-19 11:39:17,606] Trial 47 finished with value: 0.949710410052545 and parameters: {'solver': 'saga', 'C': 0.003978540085283576, 'l1_ratio': 0.8891205931784609, 'class_weight': None, 'fit_intercept': True, 'tol': 9.503104282019163e-05, 'max_iter': 4902}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:   9%|██████████▌                                                                                                     | 47/500 [01:46<17:57,  2.38s/it]

[I 2026-05-19 11:39:18,605] Trial 48 finished with value: 0.9497077042178464 and parameters: {'solver': 'saga', 'C': 0.005095383089266083, 'l1_ratio': 0.8797019302871038, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011015981878740573, 'max_iter': 2241}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  10%|██████████▊                                                                                                     | 48/500 [01:47<15:27,  2.05s/it]

[I 2026-05-19 11:39:19,896] Trial 49 finished with value: 0.9497087134149401 and parameters: {'solver': 'saga', 'C': 0.004664021649244175, 'l1_ratio': 0.8802084788169671, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010466032554023215, 'max_iter': 2253}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  10%|██████████▉                                                                                                     | 49/500 [01:48<11:38,  1.55s/it]

[I 2026-05-19 11:39:20,275] Trial 50 finished with value: 0.9497075301670133 and parameters: {'solver': 'saga', 'C': 0.004504454022784654, 'l1_ratio': 0.9071465279293758, 'class_weight': None, 'fit_intercept': True, 'tol': 7.345187084085979e-05, 'max_iter': 2269}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  10%|███████████▏                                                                                                    | 50/500 [01:51<15:10,  2.02s/it]

[I 2026-05-19 11:39:23,406] Trial 51 finished with value: 0.9497017343891013 and parameters: {'solver': 'saga', 'C': 0.0014488519173435786, 'l1_ratio': 0.7420566223216186, 'class_weight': None, 'fit_intercept': True, 'tol': 6.0956841859370176e-05, 'max_iter': 4654}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  10%|███████████▍                                                                                                    | 51/500 [01:52<12:30,  1.67s/it]

[I 2026-05-19 11:39:24,253] Trial 52 finished with value: 0.949714196956234 and parameters: {'solver': 'saga', 'C': 0.0013898260125525396, 'l1_ratio': 0.9161485624991599, 'class_weight': None, 'fit_intercept': True, 'tol': 6.241172812647832e-05, 'max_iter': 4675}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  10%|███████████▋                                                                                                    | 52/500 [01:53<12:08,  1.63s/it]

[I 2026-05-19 11:39:25,770] Trial 53 finished with value: 0.9497145875296391 and parameters: {'solver': 'saga', 'C': 0.0014390616259830982, 'l1_ratio': 0.9154962780087207, 'class_weight': None, 'fit_intercept': True, 'tol': 5.581615308465468e-05, 'max_iter': 4622}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  11%|███████████▊                                                                                                    | 53/500 [01:56<14:56,  2.01s/it]

[I 2026-05-19 11:39:28,668] Trial 54 finished with value: 0.9497120386368902 and parameters: {'solver': 'saga', 'C': 0.0011700194403735124, 'l1_ratio': 0.9070974611919393, 'class_weight': None, 'fit_intercept': True, 'tol': 5.83643961216172e-05, 'max_iter': 2196}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  11%|████████████                                                                                                    | 54/500 [01:57<12:19,  1.66s/it]

[I 2026-05-19 11:39:29,506] Trial 55 finished with value: 0.9496976996561894 and parameters: {'solver': 'saga', 'C': 0.00097709273132818, 'l1_ratio': 0.7319989919206019, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001667204956384582, 'max_iter': 2364}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  11%|████████████▎                                                                                                   | 55/500 [01:58<12:13,  1.65s/it]

[I 2026-05-19 11:39:31,135] Trial 60 pruned.

Best trial: 42. Best value: 0.949716:  11%|████████████▌                                                                                                   | 56/500 [01:59<09:52,  1.33s/it]

[I 2026-05-19 11:39:31,742] Trial 56 finished with value: 0.9497104301615241 and parameters: {'solver': 'saga', 'C': 0.0009918727258328925, 'l1_ratio': 0.9215420356420336, 'class_weight': None, 'fit_intercept': True, 'tol': 5.566101085756455e-05, 'max_iter': 4587}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  11%|████████████▊                                                                                                   | 57/500 [02:02<12:27,  1.69s/it]

[I 2026-05-19 11:39:34,247] Trial 61 pruned.

Best trial: 42. Best value: 0.949716:  12%|████████████▉                                                                                                   | 58/500 [02:04<13:44,  1.86s/it]

[I 2026-05-19 11:39:36,527] Trial 63 pruned.

Best trial: 42. Best value: 0.949716:  12%|█████████████▏                                                                                                  | 59/500 [02:06<13:11,  1.79s/it]

[I 2026-05-19 11:39:38,159] Trial 57 finished with value: 0.9496997689894856 and parameters: {'solver': 'saga', 'C': 0.001122130362110993, 'l1_ratio': 0.7417244470220759, 'class_weight': None, 'fit_intercept': True, 'tol': 4.7225734915253066e-05, 'max_iter': 4619}. Best is trial 42 with value: 0.9497163933256789.
[I 2026-05-19 11:39:38,175] Trial 58 finished with value: 0.9497001833106093 and parameters: {'solver': 'saga', 'C': 0.0011083676447767557, 'l1_ratio': 0.7466476943443687, 'class_weight': None, 'fit_intercept': True, 'tol': 4.427850974728869e-05, 'max_iter': 4425}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  12%|█████████████▋                                                                                                  | 61/500 [02:07<09:13,  1.26s/it]

[I 2026-05-19 11:39:39,431] Trial 64 pruned.

Best trial: 42. Best value: 0.949716:  12%|█████████████▉                                                                                                  | 62/500 [02:08<08:22,  1.15s/it]

[I 2026-05-19 11:39:40,240] Trial 59 finished with value: 0.9497006253256716 and parameters: {'solver': 'saga', 'C': 0.0010515152019033198, 'l1_ratio': 0.9909865608962982, 'class_weight': None, 'fit_intercept': True, 'tol': 4.036609096091437e-05, 'max_iter': 4650}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  13%|██████████████                                                                                                  | 63/500 [02:08<06:35,  1.11it/s]

[I 2026-05-19 11:39:40,452] Trial 65 pruned.

Best trial: 42. Best value: 0.949716:  13%|██████████████▎                                                                                                 | 64/500 [02:12<13:42,  1.89s/it]

[I 2026-05-19 11:39:44,968] Trial 62 finished with value: 0.9497109983796458 and parameters: {'solver': 'saga', 'C': 0.0010126948693369242, 'l1_ratio': 0.9322996519557298, 'class_weight': None, 'fit_intercept': True, 'tol': 4.521484224806737e-05, 'max_iter': 4368}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  13%|██████████████▊                                                                                                 | 66/500 [02:26<27:22,  3.79s/it]

[I 2026-05-19 11:39:58,848] Trial 66 finished with value: 0.9495701139457902 and parameters: {'solver': 'saga', 'C': 0.03657098355077148, 'l1_ratio': 0.9375978938425156, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000181230699236628, 'max_iter': 4357}. Best is trial 42 with value: 0.9497163933256789.
[I 2026-05-19 11:39:58,985] Trial 74 finished with value: 0.9496427485671599 and parameters: {'solver': 'saga', 'C': 0.022353957625010076, 'l1_ratio': 0.92884549653569, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016928446981483183, 'max_iter': 4780}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  13%|███████████████                                                                                                 | 67/500 [02:33<34:02,  4.72s/it]

[I 2026-05-19 11:40:05,988] Trial 72 finished with value: 0.9495781103298151 and parameters: {'solver': 'saga', 'C': 0.034535743957406606, 'l1_ratio': 0.9307796739229633, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016612772898257398, 'max_iter': 4734}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  14%|███████████████▏                                                                                                | 68/500 [02:37<30:56,  4.30s/it]

[I 2026-05-19 11:40:09,274] Trial 75 finished with value: 0.9496143892494244 and parameters: {'solver': 'saga', 'C': 0.02700344712163047, 'l1_ratio': 0.9412950293866513, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016777858067777213, 'max_iter': 4753}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  14%|███████████████▍                                                                                                | 69/500 [02:43<35:38,  4.96s/it]

[I 2026-05-19 11:40:15,820] Trial 69 finished with value: 0.9496096744145829 and parameters: {'solver': 'saga', 'C': 0.02790656714851918, 'l1_ratio': 0.9492312894589758, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1969376075456217e-05, 'max_iter': 4353}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  14%|███████████████▋                                                                                                | 70/500 [02:44<27:06,  3.78s/it]

[I 2026-05-19 11:40:16,811] Trial 73 finished with value: 0.9495702043955389 and parameters: {'solver': 'saga', 'C': 0.03656207570945564, 'l1_ratio': 0.9544163561686112, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018652295027758552, 'max_iter': 4744}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  14%|███████████████▉                                                                                                | 71/500 [02:46<23:12,  3.25s/it]

[I 2026-05-19 11:40:18,790] Trial 78 pruned.

Best trial: 42. Best value: 0.949716:  14%|████████████████▏                                                                                               | 72/500 [02:48<20:30,  2.88s/it]

[I 2026-05-19 11:40:20,793] Trial 77 finished with value: 0.9496497330250865 and parameters: {'solver': 'saga', 'C': 0.00958277400366248, 'l1_ratio': 0.15687656034661301, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6140350293321463e-05, 'max_iter': 4142}. Best is trial 42 with value: 0.9497163933256789.
[I 2026-05-19 11:40:20,818] Trial 76 finished with value: 0.9496645777547492 and parameters: {'solver': 'saga', 'C': 0.018008779323233706, 'l1_ratio': 0.7684988385935639, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8830449398149957e-05, 'max_iter': 4791}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  15%|████████████████▌                                                                                               | 74/500 [02:49<11:57,  1.68s/it]

[I 2026-05-19 11:40:21,366] Trial 68 finished with value: 0.949542582640358 and parameters: {'solver': 'saga', 'C': 0.044968235522559984, 'l1_ratio': 0.9460842633512118, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5447067363104412e-05, 'max_iter': 4371}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  15%|████████████████▊                                                                                               | 75/500 [02:51<12:08,  1.71s/it]

[I 2026-05-19 11:40:23,168] Trial 71 finished with value: 0.94956487905255 and parameters: {'solver': 'saga', 'C': 0.038004500442208024, 'l1_ratio': 0.9427241801484957, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5260651480595472e-05, 'max_iter': 2988}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  15%|█████████████████                                                                                               | 76/500 [02:52<10:59,  1.56s/it]

[I 2026-05-19 11:40:24,275] Trial 70 finished with value: 0.9495683504398251 and parameters: {'solver': 'saga', 'C': 0.03704813063281644, 'l1_ratio': 0.9481543594071146, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6755634085075787e-05, 'max_iter': 4389}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  15%|█████████████████▏                                                                                              | 77/500 [02:53<11:18,  1.60s/it]

[I 2026-05-19 11:40:26,013] Trial 81 finished with value: 0.9496446845971516 and parameters: {'solver': 'saga', 'C': 0.00010418493803654552, 'l1_ratio': 0.7764902682913897, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00873436888883176, 'max_iter': 2928}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  16%|█████████████████▍                                                                                              | 78/500 [02:54<09:31,  1.35s/it]

[I 2026-05-19 11:40:26,714] Trial 67 finished with value: 0.9496703919785524 and parameters: {'solver': 'saga', 'C': 0.01318427688864638, 'l1_ratio': 0.986733836689816, 'class_weight': None, 'fit_intercept': True, 'tol': 2.4946148254081474e-05, 'max_iter': 4088}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  16%|█████████████████▋                                                                                              | 79/500 [02:58<15:39,  2.23s/it]

[I 2026-05-19 11:40:31,149] Trial 79 finished with value: 0.9497028712059512 and parameters: {'solver': 'saga', 'C': 0.008912964971255894, 'l1_ratio': 0.7783734138378364, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6312955664771546e-05, 'max_iter': 2970}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  16%|█████████████████▉                                                                                              | 80/500 [03:05<23:40,  3.38s/it]

[I 2026-05-19 11:40:37,355] Trial 82 finished with value: 0.949709068243239 and parameters: {'solver': 'saga', 'C': 0.0021092835796477014, 'l1_ratio': 0.7894883149971732, 'class_weight': None, 'fit_intercept': True, 'tol': 6.796764149675919e-05, 'max_iter': 2012}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  16%|██████████████████▏                                                                                             | 81/500 [03:08<23:05,  3.31s/it]

[I 2026-05-19 11:40:40,475] Trial 83 finished with value: 0.9496913998509499 and parameters: {'solver': 'saga', 'C': 0.010592557206515767, 'l1_ratio': 0.8335752683845521, 'class_weight': None, 'fit_intercept': True, 'tol': 7.128750360171733e-05, 'max_iter': 2060}. Best is trial 42 with value: 0.9497163933256789.
[I 2026-05-19 11:40:40,508] Trial 80 finished with value: 0.9494254309625099 and parameters: {'solver': 'saga', 'C': 0.00012169724328514149, 'l1_ratio': 0.6088635260089971, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.3802511361093443e-05, 'max_iter': 1525}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  17%|██████████████████▌                                                                                             | 83/500 [03:08<13:23,  1.93s/it]

[I 2026-05-19 11:40:41,027] Trial 84 finished with value: 0.9496133474237107 and parameters: {'solver': 'saga', 'C': 0.000539593125578906, 'l1_ratio': 0.689165475987278, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.932890622598311e-05, 'max_iter': 1854}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  17%|██████████████████▊                                                                                             | 84/500 [03:09<11:18,  1.63s/it]

[I 2026-05-19 11:40:41,749] Trial 85 finished with value: 0.949323355570046 and parameters: {'solver': 'saga', 'C': 0.0005044330367070023, 'l1_ratio': 0.4522224077118174, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.740855658436169e-05, 'max_iter': 1979}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  17%|███████████████████                                                                                             | 85/500 [03:12<12:44,  1.84s/it]

[I 2026-05-19 11:40:44,183] Trial 89 finished with value: 0.9496132068113005 and parameters: {'solver': 'saga', 'C': 0.0021313419491122546, 'l1_ratio': 0.6786971205508603, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0002125500795964632, 'max_iter': 1727}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  17%|███████████████████▎                                                                                            | 86/500 [03:12<10:13,  1.48s/it]

[I 2026-05-19 11:40:44,693] Trial 87 finished with value: 0.9496159298441489 and parameters: {'solver': 'saga', 'C': 0.0015839010135537024, 'l1_ratio': 0.8000119576370128, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 7.033334302919918e-05, 'max_iter': 1644}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  17%|███████████████████▍                                                                                            | 87/500 [03:15<13:13,  1.92s/it]

[I 2026-05-19 11:40:47,769] Trial 86 finished with value: 0.9497102381742983 and parameters: {'solver': 'saga', 'C': 0.0022058244120368125, 'l1_ratio': 0.8023208785321596, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1927449215504458e-05, 'max_iter': 1677}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  18%|███████████████████▋                                                                                            | 88/500 [03:17<14:04,  2.05s/it]

[I 2026-05-19 11:40:50,143] Trial 88 finished with value: 0.949695964823469 and parameters: {'solver': 'saga', 'C': 0.0018897849023297834, 'l1_ratio': 0.6661553412370552, 'class_weight': None, 'fit_intercept': True, 'tol': 1.25660796063029e-05, 'max_iter': 1551}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  18%|███████████████████▉                                                                                            | 89/500 [03:19<13:03,  1.91s/it]

[I 2026-05-19 11:40:51,658] Trial 90 finished with value: 0.9496103662776758 and parameters: {'solver': 'saga', 'C': 0.0023621695024980583, 'l1_ratio': 0.666480682961401, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 7.294308929928628e-05, 'max_iter': 1888}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 42. Best value: 0.949716:  18%|████████████████████▏                                                                                           | 90/500 [03:22<15:34,  2.28s/it]

[I 2026-05-19 11:40:54,874] Trial 91 finished with value: 0.94962377505608 and parameters: {'solver': 'saga', 'C': 0.00045081437712530615, 'l1_ratio': 0.8374146302630907, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00024276632552671558, 'max_iter': 1796}. Best is trial 42 with value: 0.9497163933256789.

Best trial: 93. Best value: 0.949717:  18%|████████████████████▍                                                                                           | 91/500 [03:26<19:28,  2.86s/it]

[I 2026-05-19 11:40:59,110] Trial 93 finished with value: 0.94971693243582 and parameters: {'solver': 'saga', 'C': 0.002193203638990036, 'l1_ratio': 0.89839712471031, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001350258081959178, 'max_iter': 4918}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  18%|████████████████████▌                                                                                           | 92/500 [03:27<14:22,  2.11s/it]

[I 2026-05-19 11:40:59,445] Trial 92 finished with value: 0.9497161869205076 and parameters: {'solver': 'saga', 'C': 0.002381337399798716, 'l1_ratio': 0.8947562403312379, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013731172631847345, 'max_iter': 4904}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  19%|████████████████████▊                                                                                           | 93/500 [03:28<11:30,  1.70s/it]

[I 2026-05-19 11:41:00,168] Trial 94 finished with value: 0.9496686497326149 and parameters: {'solver': 'saga', 'C': 0.0021663695368070866, 'l1_ratio': 0.45740942051273187, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013936741908003703, 'max_iter': 4895}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  19%|█████████████████████                                                                                           | 94/500 [03:29<10:12,  1.51s/it]

[I 2026-05-19 11:41:01,233] Trial 95 finished with value: 0.9497138063679772 and parameters: {'solver': 'saga', 'C': 0.0023393399939986128, 'l1_ratio': 0.8457041918738565, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012653114654304377, 'max_iter': 4911}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  19%|█████████████████████▌                                                                                          | 96/500 [03:30<07:27,  1.11s/it]

[I 2026-05-19 11:41:02,839] Trial 96 finished with value: 0.9497159404771848 and parameters: {'solver': 'saga', 'C': 0.0024865571330867525, 'l1_ratio': 0.8950564381378489, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014062046101804, 'max_iter': 4900}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:41:02,944] Trial 97 finished with value: 0.9497167058285024 and parameters: {'solver': 'saga', 'C': 0.002113988420865207, 'l1_ratio': 0.8945072597557386, 'class_weight': None, 'fit_intercept': True, 'tol': 9.085196554698101e-05, 'max_iter': 4876}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  19%|█████████████████████▋                                                                                          | 97/500 [03:35<14:30,  2.16s/it]

[I 2026-05-19 11:41:07,560] Trial 98 finished with value: 0.9497087843885428 and parameters: {'solver': 'saga', 'C': 0.00625877472356436, 'l1_ratio': 0.8972110267326902, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012387094069563387, 'max_iter': 4934}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  20%|█████████████████████▉                                                                                          | 98/500 [03:41<21:52,  3.26s/it]

[I 2026-05-19 11:41:13,409] Trial 101 finished with value: 0.9497138296860527 and parameters: {'solver': 'saga', 'C': 0.0029443880180082377, 'l1_ratio': 0.8988194476085055, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013507240429899383, 'max_iter': 4936}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  20%|██████████████████████▏                                                                                         | 99/500 [03:45<23:24,  3.50s/it]

[I 2026-05-19 11:41:17,466] Trial 103 finished with value: 0.9497105457900966 and parameters: {'solver': 'saga', 'C': 0.006471704260863365, 'l1_ratio': 0.8855044828686393, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013724503067027375, 'max_iter': 4906}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  20%|██████████████████████▏                                                                                        | 100/500 [03:45<17:11,  2.58s/it]

[I 2026-05-19 11:41:17,895] Trial 102 finished with value: 0.9497126051097184 and parameters: {'solver': 'saga', 'C': 0.003313213858255169, 'l1_ratio': 0.8895647912716744, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001308795727157885, 'max_iter': 4930}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  20%|██████████████████████▍                                                                                        | 101/500 [03:46<13:52,  2.09s/it]

[I 2026-05-19 11:41:18,827] Trial 104 finished with value: 0.9497048837015767 and parameters: {'solver': 'saga', 'C': 0.005554931311975164, 'l1_ratio': 0.8992590961245647, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013057147458170608, 'max_iter': 4906}. Best is trial 93 with value: 0.94971693243582.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 93. Best value: 0.949717:  20%|██████████████████████▋                                                                                        | 102/500 [03:51<18:50,  2.84s/it]

[I 2026-05-19 11:41:23,426] Trial 105 finished with value: 0.9497093850075796 and parameters: {'solver': 'saga', 'C': 0.0068337452232512174, 'l1_ratio': 0.8993384839590725, 'class_weight': None, 'fit_intercept': True, 'tol': 3.4618795805486646e-05, 'max_iter': 4848}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  21%|██████████████████████▊                                                                                        | 103/500 [03:51<14:00,  2.12s/it]

[I 2026-05-19 11:41:23,852] Trial 106 finished with value: 0.9497057894428605 and parameters: {'solver': 'saga', 'C': 0.0053032708759404995, 'l1_ratio': 0.8972581178221946, 'class_weight': None, 'fit_intercept': True, 'tol': 3.555643895453464e-05, 'max_iter': 4508}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  21%|███████████████████████                                                                                        | 104/500 [03:52<11:54,  1.80s/it]

[I 2026-05-19 11:41:24,925] Trial 107 finished with value: 0.9497098051883828 and parameters: {'solver': 'saga', 'C': 0.006885927379124954, 'l1_ratio': 0.8968461313867294, 'class_weight': None, 'fit_intercept': True, 'tol': 3.4810843119882795e-05, 'max_iter': 4851}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  21%|███████████████████████▎                                                                                       | 105/500 [03:57<16:40,  2.53s/it]

[I 2026-05-19 11:41:29,153] Trial 110 finished with value: 0.9496846594494016 and parameters: {'solver': 'saga', 'C': 0.0003549491748446027, 'l1_ratio': 0.9080114387436039, 'class_weight': None, 'fit_intercept': True, 'tol': 0.003716004849372117, 'max_iter': 4508}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  21%|███████████████████████▌                                                                                       | 106/500 [03:57<12:22,  1.89s/it]

[I 2026-05-19 11:41:29,536] Trial 108 finished with value: 0.9497076814170733 and parameters: {'solver': 'saga', 'C': 0.0073461000980887025, 'l1_ratio': 0.9103617058999133, 'class_weight': None, 'fit_intercept': True, 'tol': 3.46241221431957e-05, 'max_iter': 4532}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  21%|███████████████████████▊                                                                                       | 107/500 [04:00<15:19,  2.34s/it]

[I 2026-05-19 11:41:32,934] Trial 109 finished with value: 0.9497077499098749 and parameters: {'solver': 'saga', 'C': 0.007422329651856006, 'l1_ratio': 0.908673029964802, 'class_weight': None, 'fit_intercept': True, 'tol': 9.795515986629099e-05, 'max_iter': 4850}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  22%|███████████████████████▉                                                                                       | 108/500 [04:03<16:45,  2.57s/it]

[I 2026-05-19 11:41:36,032] Trial 111 finished with value: 0.9497018403415218 and parameters: {'solver': 'saga', 'C': 0.0006538164356203253, 'l1_ratio': 0.9122127933649001, 'class_weight': None, 'fit_intercept': True, 'tol': 9.46752525668453e-05, 'max_iter': 4483}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  22%|████████████████████████▏                                                                                      | 109/500 [04:06<16:23,  2.51s/it]

[I 2026-05-19 11:41:38,423] Trial 116 pruned.

Best trial: 93. Best value: 0.949717:  22%|████████████████████████▍                                                                                      | 110/500 [04:07<13:40,  2.10s/it]

[I 2026-05-19 11:41:39,553] Trial 117 pruned.

Best trial: 93. Best value: 0.949717:  22%|████████████████████████▋                                                                                      | 111/500 [04:09<13:43,  2.12s/it]

[I 2026-05-19 11:41:41,717] Trial 113 finished with value: 0.9497017077237118 and parameters: {'solver': 'saga', 'C': 0.0007095450667670076, 'l1_ratio': 0.8531150646996085, 'class_weight': None, 'fit_intercept': True, 'tol': 9.215980848638503e-05, 'max_iter': 4519}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  22%|████████████████████████▊                                                                                      | 112/500 [04:10<10:55,  1.69s/it]

[I 2026-05-19 11:41:42,405] Trial 114 finished with value: 0.9497130997128564 and parameters: {'solver': 'saga', 'C': 0.0014880117859501826, 'l1_ratio': 0.8591358560911077, 'class_weight': None, 'fit_intercept': True, 'tol': 8.643532489882572e-05, 'max_iter': 4690}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  23%|█████████████████████████                                                                                      | 113/500 [04:11<09:06,  1.41s/it]

[I 2026-05-19 11:41:43,168] Trial 115 finished with value: 0.9497134128531866 and parameters: {'solver': 'saga', 'C': 0.0015356269351393178, 'l1_ratio': 0.8580902733993129, 'class_weight': None, 'fit_intercept': True, 'tol': 9.538591343031135e-05, 'max_iter': 4668}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  23%|█████████████████████████▎                                                                                     | 114/500 [04:11<06:45,  1.05s/it]

[I 2026-05-19 11:41:43,380] Trial 99 finished with value: 0.9493967656763983 and parameters: {'solver': 'saga', 'C': 51.21965959853352, 'l1_ratio': 0.8956955958114224, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000127052610219445, 'max_iter': 4895}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  23%|█████████████████████████▌                                                                                     | 115/500 [04:11<05:40,  1.13it/s]

[I 2026-05-19 11:41:43,877] Trial 119 pruned.

Best trial: 93. Best value: 0.949717:  23%|█████████████████████████▊                                                                                     | 116/500 [04:17<14:47,  2.31s/it]

[I 2026-05-19 11:41:49,517] Trial 118 finished with value: 0.9497001421840064 and parameters: {'solver': 'saga', 'C': 0.0006554561475250541, 'l1_ratio': 0.849753833795364, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020891300324481888, 'max_iter': 4694}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  23%|█████████████████████████▉                                                                                     | 117/500 [04:21<18:13,  2.85s/it]

[I 2026-05-19 11:41:53,627] Trial 100 finished with value: 0.9493967383477028 and parameters: {'solver': 'saga', 'C': 60.51191922253817, 'l1_ratio': 0.8976987167620505, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012768339305575495, 'max_iter': 4899}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  24%|██████████████████████████▏                                                                                    | 118/500 [04:24<17:48,  2.80s/it]

[I 2026-05-19 11:41:56,302] Trial 20 pruned.

Best trial: 93. Best value: 0.949717:  24%|██████████████████████████▋                                                                                    | 120/500 [04:24<09:38,  1.52s/it]

[I 2026-05-19 11:41:56,792] Trial 121 finished with value: 0.9497095708805354 and parameters: {'solver': 'saga', 'C': 0.001511251161476286, 'l1_ratio': 0.8105964578531331, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00022792455704311862, 'max_iter': 4683}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:41:56,944] Trial 120 finished with value: 0.9493981667535089 and parameters: {'solver': 'saga', 'C': 4.343002167657703, 'l1_ratio': 0.9631737424104687, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002987177098205815, 'max_iter': 4719}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  24%|██████████████████████████▊                                                                                    | 121/500 [04:26<09:31,  1.51s/it]

[I 2026-05-19 11:41:58,433] Trial 123 finished with value: 0.9497111373105985 and parameters: {'solver': 'saga', 'C': 0.003786215735680211, 'l1_ratio': 0.8205670447504513, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003134472194390652, 'max_iter': 2810}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  24%|███████████████████████████                                                                                    | 122/500 [04:28<10:03,  1.60s/it]

[I 2026-05-19 11:42:00,231] Trial 124 finished with value: 0.9497132996904414 and parameters: {'solver': 'saga', 'C': 0.003161320929287752, 'l1_ratio': 0.8750314171543955, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00029977546376259095, 'max_iter': 4997}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  25%|███████████████████████████▎                                                                                   | 123/500 [04:28<07:41,  1.22s/it]

[I 2026-05-19 11:42:00,588] Trial 125 finished with value: 0.9497124843978355 and parameters: {'solver': 'saga', 'C': 0.003409549569321296, 'l1_ratio': 0.8757601059871085, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00028825882594721037, 'max_iter': 4974}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  25%|███████████████████████████▌                                                                                   | 124/500 [04:32<13:31,  2.16s/it]

[I 2026-05-19 11:42:04,922] Trial 126 finished with value: 0.9497112445092452 and parameters: {'solver': 'saga', 'C': 0.003791940898533706, 'l1_ratio': 0.8223772104034461, 'class_weight': None, 'fit_intercept': True, 'tol': 5.601993175520144e-05, 'max_iter': 2792}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  25%|███████████████████████████▊                                                                                   | 125/500 [04:37<18:11,  2.91s/it]

[I 2026-05-19 11:42:09,591] Trial 128 finished with value: 0.9497103792786948 and parameters: {'solver': 'saga', 'C': 0.004332173243217618, 'l1_ratio': 0.8130077910285953, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004586301416223063, 'max_iter': 4995}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  25%|███████████████████████████▉                                                                                   | 126/500 [04:38<14:40,  2.35s/it]

[I 2026-05-19 11:42:10,641] Trial 127 finished with value: 0.9497110445903955 and parameters: {'solver': 'saga', 'C': 0.003996253843840208, 'l1_ratio': 0.8200780643215155, 'class_weight': None, 'fit_intercept': True, 'tol': 5.425603328078747e-05, 'max_iter': 4991}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  25%|████████████████████████████▏                                                                                  | 127/500 [04:40<13:52,  2.23s/it]

[I 2026-05-19 11:42:12,586] Trial 129 finished with value: 0.9497115817117516 and parameters: {'solver': 'saga', 'C': 0.0034938874354118973, 'l1_ratio': 0.8165017367920026, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00047171974192712634, 'max_iter': 4996}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  26%|████████████████████████████▍                                                                                  | 128/500 [04:44<17:48,  2.87s/it]

[I 2026-05-19 11:42:16,953] Trial 131 finished with value: 0.9497117327081899 and parameters: {'solver': 'saga', 'C': 0.003629752296378727, 'l1_ratio': 0.8789947879276008, 'class_weight': None, 'fit_intercept': True, 'tol': 5.6319049297253577e-05, 'max_iter': 2758}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  26%|████████████████████████████▋                                                                                  | 129/500 [04:45<13:47,  2.23s/it]

[I 2026-05-19 11:42:17,694] Trial 130 finished with value: 0.9497022265033944 and parameters: {'solver': 'saga', 'C': 0.0037014142220841715, 'l1_ratio': 0.9667949749365163, 'class_weight': None, 'fit_intercept': True, 'tol': 5.648226026176696e-05, 'max_iter': 4237}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  26%|████████████████████████████▊                                                                                  | 130/500 [04:46<10:31,  1.71s/it]

[I 2026-05-19 11:42:18,176] Trial 132 finished with value: 0.9497143667974329 and parameters: {'solver': 'saga', 'C': 0.0028300603480787044, 'l1_ratio': 0.8753232248952093, 'class_weight': None, 'fit_intercept': True, 'tol': 5.2436372847492664e-05, 'max_iter': 4987}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  26%|█████████████████████████████                                                                                  | 131/500 [04:47<09:14,  1.50s/it]

[I 2026-05-19 11:42:19,206] Trial 133 finished with value: 0.9497124985878866 and parameters: {'solver': 'saga', 'C': 0.0030979343782209057, 'l1_ratio': 0.9225673535096761, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015562485796413644, 'max_iter': 4990}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  26%|█████████████████████████████▎                                                                                 | 132/500 [04:49<10:54,  1.78s/it]

[I 2026-05-19 11:42:21,623] Trial 134 finished with value: 0.949712598798199 and parameters: {'solver': 'saga', 'C': 0.002999756520639014, 'l1_ratio': 0.9285067835794789, 'class_weight': None, 'fit_intercept': True, 'tol': 5.702274841372223e-05, 'max_iter': 4800}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  27%|█████████████████████████████▌                                                                                 | 133/500 [04:50<09:22,  1.53s/it]

[I 2026-05-19 11:42:22,572] Trial 135 finished with value: 0.9497149208972715 and parameters: {'solver': 'saga', 'C': 0.0025630367265691237, 'l1_ratio': 0.9262586901477794, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015554790519418975, 'max_iter': 4806}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  27%|█████████████████████████████▋                                                                                 | 134/500 [04:56<16:46,  2.75s/it]

[I 2026-05-19 11:42:28,163] Trial 136 finished with value: 0.9497142110127854 and parameters: {'solver': 'saga', 'C': 0.0026802755134383545, 'l1_ratio': 0.9277994930351063, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015776607611045604, 'max_iter': 4761}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:42:28,219] Trial 137 finished with value: 0.9497138495612821 and parameters: {'solver': 'saga', 'C': 0.002743319302702104, 'l1_ratio': 0.9284082794669754, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001524596533533462, 'max_iter': 2158}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  27%|██████████████████████████████▏                                                                                | 136/500 [04:58<12:27,  2.05s/it]

[I 2026-05-19 11:42:30,658] Trial 138 finished with value: 0.9497101700034228 and parameters: {'solver': 'saga', 'C': 0.0027029114218183868, 'l1_ratio': 0.9561363974524608, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015181875137111123, 'max_iter': 4801}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  27%|██████████████████████████████▍                                                                                | 137/500 [04:59<10:18,  1.70s/it]

[I 2026-05-19 11:42:31,289] Trial 112 finished with value: 0.9493967175259097 and parameters: {'solver': 'saga', 'C': 73.85288176244288, 'l1_ratio': 0.9129797800153077, 'class_weight': None, 'fit_intercept': True, 'tol': 9.21983223720014e-05, 'max_iter': 4495}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  28%|██████████████████████████████▋                                                                                | 138/500 [05:03<14:03,  2.33s/it]

[I 2026-05-19 11:42:35,391] Trial 139 finished with value: 0.9497147624617848 and parameters: {'solver': 'saga', 'C': 0.0025629796126187456, 'l1_ratio': 0.9295612733778098, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001579528534067512, 'max_iter': 4804}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  28%|██████████████████████████████▊                                                                                | 139/500 [05:03<10:48,  1.80s/it]

[I 2026-05-19 11:42:35,757] Trial 140 finished with value: 0.9497155915798114 and parameters: {'solver': 'saga', 'C': 0.0023647878953433335, 'l1_ratio': 0.9267858482778413, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014702029570243334, 'max_iter': 4796}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  28%|███████████████████████████████                                                                                | 140/500 [05:05<10:53,  1.81s/it]

[I 2026-05-19 11:42:37,618] Trial 141 finished with value: 0.9497149534348275 and parameters: {'solver': 'saga', 'C': 0.002540886670311538, 'l1_ratio': 0.9281150799177699, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010820118429306799, 'max_iter': 4768}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  28%|███████████████████████████████▎                                                                               | 141/500 [05:07<11:00,  1.84s/it]

[I 2026-05-19 11:42:39,526] Trial 142 finished with value: 0.9496760203659397 and parameters: {'solver': 'saga', 'C': 0.012798027808309536, 'l1_ratio': 0.927531645370256, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010864938621439553, 'max_iter': 4812}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  28%|███████████████████████████████▌                                                                               | 142/500 [05:08<10:30,  1.76s/it]

[I 2026-05-19 11:42:41,090] Trial 122 finished with value: 0.9493967547774836 and parameters: {'solver': 'saga', 'C': 52.69704115341523, 'l1_ratio': 0.819781619607863, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00033168596982828237, 'max_iter': 4990}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  29%|███████████████████████████████▋                                                                               | 143/500 [05:09<07:59,  1.34s/it]

[I 2026-05-19 11:42:41,412] Trial 144 finished with value: 0.949685607558302 and parameters: {'solver': 'saga', 'C': 0.011433770194669018, 'l1_ratio': 0.8689618450746632, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019663051267582678, 'max_iter': 4774}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:42:41,513] Trial 143 finished with value: 0.949678904720064 and parameters: {'solver': 'saga', 'C': 0.012900170086838721, 'l1_ratio': 0.8744221171758526, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001118838110636495, 'max_iter': 4777}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  29%|████████████████████████████████▏                                                                              | 145/500 [05:13<10:02,  1.70s/it]

[I 2026-05-19 11:42:45,661] Trial 146 finished with value: 0.9497126671267271 and parameters: {'solver': 'saga', 'C': 0.0019720709930256815, 'l1_ratio': 0.9551880015192501, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020269181761363168, 'max_iter': 4802}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  29%|████████████████████████████████▍                                                                              | 146/500 [05:14<08:38,  1.47s/it]

[I 2026-05-19 11:42:46,419] Trial 145 finished with value: 0.949675090765424 and parameters: {'solver': 'saga', 'C': 0.013343099363905516, 'l1_ratio': 0.9234499329986058, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020073482816754435, 'max_iter': 4788}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  29%|████████████████████████████████▋                                                                              | 147/500 [05:16<09:04,  1.54s/it]

[I 2026-05-19 11:42:48,184] Trial 147 finished with value: 0.9496824736043907 and parameters: {'solver': 'saga', 'C': 0.011911365000335733, 'l1_ratio': 0.8715923255666567, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000208998606318983, 'max_iter': 4778}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  30%|████████████████████████████████▊                                                                              | 148/500 [05:25<21:38,  3.69s/it]

[I 2026-05-19 11:42:57,655] Trial 152 finished with value: 0.9497141574878967 and parameters: {'solver': 'saga', 'C': 0.0018771201945195254, 'l1_ratio': 0.9464468742556585, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002048067687907547, 'max_iter': 4771}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:42:57,696] Trial 148 finished with value: 0.9497088989681881 and parameters: {'solver': 'saga', 'C': 0.0008837576200936431, 'l1_ratio': 0.9452385376765791, 'class_weight': None, 'fit_intercept': True, 'tol': 2.202648812346816e-06, 'max_iter': 4793}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  30%|█████████████████████████████████▎                                                                             | 150/500 [05:26<13:11,  2.26s/it]

[I 2026-05-19 11:42:58,464] Trial 154 finished with value: 0.9497099038730272 and parameters: {'solver': 'saga', 'C': 0.0018858719497140402, 'l1_ratio': 0.9672847215924085, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018997514633694885, 'max_iter': 4602}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  30%|█████████████████████████████████▌                                                                             | 151/500 [05:26<10:30,  1.81s/it]

[I 2026-05-19 11:42:58,829] Trial 153 finished with value: 0.9497111923719563 and parameters: {'solver': 'saga', 'C': 0.0018290152132831481, 'l1_ratio': 0.9633667060897202, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018040429611701196, 'max_iter': 4760}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  31%|█████████████████████████████████▉                                                                             | 153/500 [05:27<06:09,  1.07s/it]

[I 2026-05-19 11:42:59,071] Trial 155 finished with value: 0.9497100061124222 and parameters: {'solver': 'saga', 'C': 0.0009504531292185008, 'l1_ratio': 0.9503284011420466, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019967028584449832, 'max_iter': 4614}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:42:59,179] Trial 150 finished with value: 0.9496757652329875 and parameters: {'solver': 'saga', 'C': 0.012403424996108628, 'l1_ratio': 0.9710259585190203, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002077048137387765, 'max_iter': 4795}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  31%|██████████████████████████████████▏                                                                            | 154/500 [05:28<07:16,  1.26s/it]

[I 2026-05-19 11:43:00,960] Trial 149 finished with value: 0.9496682761437428 and parameters: {'solver': 'saga', 'C': 0.01513049335282253, 'l1_ratio': 0.9680572999038537, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002152782154801423, 'max_iter': 4778}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  31%|██████████████████████████████████▍                                                                            | 155/500 [05:31<10:03,  1.75s/it]

[I 2026-05-19 11:43:03,929] Trial 151 finished with value: 0.9496693307024323 and parameters: {'solver': 'saga', 'C': 0.01600418267690372, 'l1_ratio': 0.9663496816132768, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019290624953243723, 'max_iter': 4838}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  31%|██████████████████████████████████▋                                                                            | 156/500 [05:32<07:32,  1.31s/it]

[I 2026-05-19 11:43:04,188] Trial 165 pruned.

Best trial: 93. Best value: 0.949717:  31%|██████████████████████████████████▊                                                                            | 157/500 [05:32<06:19,  1.11s/it]

[I 2026-05-19 11:43:04,778] Trial 157 finished with value: 0.9497115758666022 and parameters: {'solver': 'saga', 'C': 0.0010343842081845646, 'l1_ratio': 0.9405200656563478, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001732325961411289, 'max_iter': 4845}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  32%|███████████████████████████████████                                                                            | 158/500 [05:42<20:16,  3.56s/it]

[I 2026-05-19 11:43:14,232] Trial 156 finished with value: 0.9497058481631502 and parameters: {'solver': 'saga', 'C': 0.0009901318692483213, 'l1_ratio': 0.9788118670998542, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7847545350952823e-06, 'max_iter': 4599}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  32%|███████████████████████████████████▎                                                                           | 159/500 [05:42<15:26,  2.72s/it]

[I 2026-05-19 11:43:14,951] Trial 159 finished with value: 0.9497045358994821 and parameters: {'solver': 'saga', 'C': 0.0009747631395852326, 'l1_ratio': 0.9823135274262824, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016544218919191836, 'max_iter': 4604}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  32%|███████████████████████████████████▌                                                                           | 160/500 [05:44<13:00,  2.30s/it]

[I 2026-05-19 11:43:16,251] Trial 160 finished with value: 0.949705267591906 and parameters: {'solver': 'saga', 'C': 0.0009300612778555593, 'l1_ratio': 0.9789046217590254, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001685915598890541, 'max_iter': 2492}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  32%|███████████████████████████████████▋                                                                           | 161/500 [05:44<09:29,  1.68s/it]

[I 2026-05-19 11:43:16,467] Trial 158 finished with value: 0.9497082935789628 and parameters: {'solver': 'saga', 'C': 0.0010459215036308837, 'l1_ratio': 0.9711250797754855, 'class_weight': None, 'fit_intercept': True, 'tol': 1.566092270765804e-06, 'max_iter': 4594}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  32%|███████████████████████████████████▉                                                                           | 162/500 [05:44<06:59,  1.24s/it]

[I 2026-05-19 11:43:16,688] Trial 162 finished with value: 0.9497107136932387 and parameters: {'solver': 'saga', 'C': 0.0010182871211531195, 'l1_ratio': 0.916818431321932, 'class_weight': None, 'fit_intercept': True, 'tol': 7.680205040546224e-05, 'max_iter': 4621}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  33%|████████████████████████████████████▏                                                                          | 163/500 [05:45<06:30,  1.16s/it]

[I 2026-05-19 11:43:17,657] Trial 161 finished with value: 0.9497054958213008 and parameters: {'solver': 'saga', 'C': 0.00105017974019332, 'l1_ratio': 0.9806881248214342, 'class_weight': None, 'fit_intercept': True, 'tol': 7.974867781329198e-05, 'max_iter': 3248}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  33%|████████████████████████████████████▍                                                                          | 164/500 [05:46<05:51,  1.05s/it]

[I 2026-05-19 11:43:18,443] Trial 164 finished with value: 0.9497134481906674 and parameters: {'solver': 'saga', 'C': 0.001249255716773041, 'l1_ratio': 0.9258803248680852, 'class_weight': None, 'fit_intercept': True, 'tol': 7.989290025296827e-05, 'max_iter': 4888}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  33%|████████████████████████████████████▋                                                                          | 165/500 [05:49<09:05,  1.63s/it]

[I 2026-05-19 11:43:21,406] Trial 167 finished with value: 0.9497092397059204 and parameters: {'solver': 'saga', 'C': 0.0010461659555984731, 'l1_ratio': 0.8821724804353327, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011539282184808307, 'max_iter': 2489}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  33%|████████████████████████████████████▊                                                                          | 166/500 [05:50<08:22,  1.51s/it]

[I 2026-05-19 11:43:22,642] Trial 168 finished with value: 0.9497131356790364 and parameters: {'solver': 'saga', 'C': 0.0013554269638001977, 'l1_ratio': 0.8905973226981231, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010980611425732485, 'max_iter': 2449}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  33%|█████████████████████████████████████                                                                          | 167/500 [05:54<12:46,  2.30s/it]

[I 2026-05-19 11:43:26,814] Trial 163 finished with value: 0.9496886528972965 and parameters: {'solver': 'saga', 'C': 0.0012347952506631084, 'l1_ratio': 0.9994933476797475, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011213555699685074, 'max_iter': 4860}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  34%|█████████████████████████████████████▎                                                                         | 168/500 [05:59<16:22,  2.96s/it]

[I 2026-05-19 11:43:31,306] Trial 166 finished with value: 0.9496891413977785 and parameters: {'solver': 'saga', 'C': 0.0012074471439639147, 'l1_ratio': 0.9993060417333555, 'class_weight': None, 'fit_intercept': True, 'tol': 7.579929326113643e-05, 'max_iter': 2391}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  34%|█████████████████████████████████████▌                                                                         | 169/500 [06:01<14:45,  2.68s/it]

[I 2026-05-19 11:43:33,320] Trial 169 finished with value: 0.9496916942540002 and parameters: {'solver': 'saga', 'C': 0.00042634213364718557, 'l1_ratio': 0.8856618994161887, 'class_weight': None, 'fit_intercept': True, 'tol': 7.981123582822602e-05, 'max_iter': 2472}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  34%|█████████████████████████████████████▋                                                                         | 170/500 [06:02<11:49,  2.15s/it]

[I 2026-05-19 11:43:34,226] Trial 170 finished with value: 0.9497128505137231 and parameters: {'solver': 'saga', 'C': 0.0013511165136610992, 'l1_ratio': 0.8836244575825793, 'class_weight': None, 'fit_intercept': True, 'tol': 8.276063923527586e-05, 'max_iter': 4897}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  34%|█████████████████████████████████████▉                                                                         | 171/500 [06:03<10:17,  1.88s/it]

[I 2026-05-19 11:43:35,468] Trial 172 finished with value: 0.9497158505134221 and parameters: {'solver': 'saga', 'C': 0.0024767451996756287, 'l1_ratio': 0.8903123284113449, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011019065012039933, 'max_iter': 4897}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  34%|██████████████████████████████████████▏                                                                        | 172/500 [06:03<07:38,  1.40s/it]

[I 2026-05-19 11:43:35,758] Trial 171 finished with value: 0.949706957404303 and parameters: {'solver': 'saga', 'C': 0.005243464631878438, 'l1_ratio': 0.8843858799411091, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011586751100829173, 'max_iter': 4880}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  35%|██████████████████████████████████████▍                                                                        | 173/500 [06:04<06:30,  1.19s/it]

[I 2026-05-19 11:43:36,473] Trial 173 finished with value: 0.9497132679239895 and parameters: {'solver': 'saga', 'C': 0.00234197559872051, 'l1_ratio': 0.8355442119728971, 'class_weight': None, 'fit_intercept': True, 'tol': 8.088390532864081e-05, 'max_iter': 4893}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  35%|██████████████████████████████████████▋                                                                        | 174/500 [06:05<06:20,  1.17s/it]

[I 2026-05-19 11:43:37,578] Trial 175 finished with value: 0.9497153774674688 and parameters: {'solver': 'saga', 'C': 0.0025864544088312156, 'l1_ratio': 0.8854222451537247, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010952458213824985, 'max_iter': 4889}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  35%|██████████████████████████████████████▊                                                                        | 175/500 [06:06<05:42,  1.05s/it]

[I 2026-05-19 11:43:38,370] Trial 174 finished with value: 0.9497092044996348 and parameters: {'solver': 'saga', 'C': 0.004932958404173684, 'l1_ratio': 0.83654391639047, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010712467314791083, 'max_iter': 4880}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  35%|███████████████████████████████████████                                                                        | 176/500 [06:08<08:16,  1.53s/it]

[I 2026-05-19 11:43:41,015] Trial 176 finished with value: 0.9497086283314976 and parameters: {'solver': 'saga', 'C': 0.005158834214409276, 'l1_ratio': 0.8458058298350966, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001012040948550636, 'max_iter': 4890}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  35%|███████████████████████████████████████▎                                                                       | 177/500 [06:09<06:48,  1.26s/it]

[I 2026-05-19 11:43:41,647] Trial 177 finished with value: 0.9497140705457691 and parameters: {'solver': 'saga', 'C': 0.0023964013195715895, 'l1_ratio': 0.8522770362360181, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014126849841930952, 'max_iter': 4882}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  36%|███████████████████████████████████████▌                                                                       | 178/500 [06:09<05:31,  1.03s/it]

[I 2026-05-19 11:43:42,142] Trial 180 pruned.

Best trial: 93. Best value: 0.949717:  36%|███████████████████████████████████████▋                                                                       | 179/500 [06:12<07:51,  1.47s/it]

[I 2026-05-19 11:43:44,631] Trial 178 finished with value: 0.9497085494363795 and parameters: {'solver': 'saga', 'C': 0.005246765945225754, 'l1_ratio': 0.8480002912651197, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001381566822751879, 'max_iter': 4914}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  36%|███████████████████████████████████████▉                                                                       | 180/500 [06:15<10:01,  1.88s/it]

[I 2026-05-19 11:43:47,470] Trial 186 pruned.

Best trial: 93. Best value: 0.949717:  36%|████████████████████████████████████████▏                                                                      | 181/500 [06:17<10:55,  2.05s/it]

[I 2026-05-19 11:43:49,933] Trial 187 pruned.
[I 2026-05-19 11:43:49,967] Trial 179 finished with value: 0.9497135919688023 and parameters: {'solver': 'saga', 'C': 0.0023516191087776094, 'l1_ratio': 0.8418162559606414, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014328144501717815, 'max_iter': 4888}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  37%|████████████████████████████████████████▋                                                                      | 183/500 [06:19<07:58,  1.51s/it]

[I 2026-05-19 11:43:51,678] Trial 188 pruned.

Best trial: 93. Best value: 0.949717:  37%|████████████████████████████████████████▊                                                                      | 184/500 [06:21<08:23,  1.59s/it]

[I 2026-05-19 11:43:53,511] Trial 181 finished with value: 0.9497093702623353 and parameters: {'solver': 'saga', 'C': 0.004817250633501217, 'l1_ratio': 0.845322887775105, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014283955155989202, 'max_iter': 3822}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  37%|█████████████████████████████████████████▎                                                                     | 186/500 [06:23<06:17,  1.20s/it]

[I 2026-05-19 11:43:55,171] Trial 183 finished with value: 0.9497133813067071 and parameters: {'solver': 'saga', 'C': 0.0022560604117113562, 'l1_ratio': 0.8385466209240593, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014259785446212186, 'max_iter': 4691}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:43:55,295] Trial 184 finished with value: 0.949714110075465 and parameters: {'solver': 'saga', 'C': 0.002335368001881414, 'l1_ratio': 0.8526802939946105, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014170298997218518, 'max_iter': 4716}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  37%|█████████████████████████████████████████▌                                                                     | 187/500 [06:23<04:46,  1.09it/s]

[I 2026-05-19 11:43:55,453] Trial 182 finished with value: 0.9497137564278433 and parameters: {'solver': 'saga', 'C': 0.0023486538779772534, 'l1_ratio': 0.845637625177846, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001437134442588977, 'max_iter': 4900}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:43:55,501] Trial 185 finished with value: 0.9497158687499458 and parameters: {'solver': 'saga', 'C': 0.0025186951174605526, 'l1_ratio': 0.9060381193870388, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001491775010735627, 'max_iter': 4706}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  38%|█████████████████████████████████████████▉                                                                     | 189/500 [06:28<09:04,  1.75s/it]

[I 2026-05-19 11:44:01,053] Trial 189 finished with value: 0.9497158349194403 and parameters: {'solver': 'saga', 'C': 0.0025198933236441, 'l1_ratio': 0.9096393764775363, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013872142653966144, 'max_iter': 4715}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  38%|██████████████████████████████████████████▏                                                                    | 190/500 [06:33<12:08,  2.35s/it]

[I 2026-05-19 11:44:05,294] Trial 190 finished with value: 0.9497163216198464 and parameters: {'solver': 'saga', 'C': 0.0023910533406055986, 'l1_ratio': 0.9052274423867339, 'class_weight': None, 'fit_intercept': True, 'tol': 6.535375817195018e-05, 'max_iter': 4734}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  38%|██████████████████████████████████████████▍                                                                    | 191/500 [06:37<14:06,  2.74s/it]

[I 2026-05-19 11:44:09,174] Trial 191 finished with value: 0.9497159151164135 and parameters: {'solver': 'saga', 'C': 0.0024886676851157085, 'l1_ratio': 0.9109107286563056, 'class_weight': None, 'fit_intercept': True, 'tol': 4.169777683844339e-05, 'max_iter': 3682}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  38%|██████████████████████████████████████████▌                                                                    | 192/500 [06:38<11:40,  2.27s/it]

[I 2026-05-19 11:44:10,162] Trial 193 finished with value: 0.9497148824859541 and parameters: {'solver': 'saga', 'C': 0.002704462638566175, 'l1_ratio': 0.9051446238731199, 'class_weight': None, 'fit_intercept': True, 'tol': 9.950261563699738e-05, 'max_iter': 4701}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  39%|██████████████████████████████████████████▊                                                                    | 193/500 [06:38<09:14,  1.81s/it]

[I 2026-05-19 11:44:10,743] Trial 192 finished with value: 0.9497156946617984 and parameters: {'solver': 'saga', 'C': 0.001709748073550678, 'l1_ratio': 0.9058515604319577, 'class_weight': None, 'fit_intercept': True, 'tol': 6.600400473861458e-05, 'max_iter': 2140}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  39%|███████████████████████████████████████████                                                                    | 194/500 [06:39<08:04,  1.58s/it]

[I 2026-05-19 11:44:11,777] Trial 194 finished with value: 0.9497154203792608 and parameters: {'solver': 'saga', 'C': 0.001987686906602906, 'l1_ratio': 0.865369567555368, 'class_weight': None, 'fit_intercept': True, 'tol': 6.402107704998002e-05, 'max_iter': 4705}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  39%|███████████████████████████████████████████▎                                                                   | 195/500 [06:40<07:23,  1.45s/it]

[I 2026-05-19 11:44:12,908] Trial 195 finished with value: 0.9497150631565384 and parameters: {'solver': 'saga', 'C': 0.0017497956061990293, 'l1_ratio': 0.8671581388698981, 'class_weight': None, 'fit_intercept': True, 'tol': 9.745697953551272e-05, 'max_iter': 4686}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  39%|███████████████████████████████████████████▌                                                                   | 196/500 [06:41<06:58,  1.38s/it]

[I 2026-05-19 11:44:14,101] Trial 197 finished with value: 0.9497153758668752 and parameters: {'solver': 'saga', 'C': 0.0018061466840501865, 'l1_ratio': 0.9359811129914863, 'class_weight': None, 'fit_intercept': True, 'tol': 6.700550005561885e-05, 'max_iter': 2137}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  39%|███████████████████████████████████████████▋                                                                   | 197/500 [06:42<05:48,  1.15s/it]

[I 2026-05-19 11:44:14,703] Trial 198 finished with value: 0.9497150767186392 and parameters: {'solver': 'saga', 'C': 0.0016511488538942572, 'l1_ratio': 0.9391317419079039, 'class_weight': None, 'fit_intercept': True, 'tol': 6.302763212165543e-05, 'max_iter': 2127}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  40%|███████████████████████████████████████████▉                                                                   | 198/500 [06:43<05:23,  1.07s/it]

[I 2026-05-19 11:44:15,590] Trial 196 finished with value: 0.9497154814282851 and parameters: {'solver': 'saga', 'C': 0.0016304974756916732, 'l1_ratio': 0.9314247500040387, 'class_weight': None, 'fit_intercept': True, 'tol': 6.219257356256085e-05, 'max_iter': 5000}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  40%|████████████████████████████████████████████▏                                                                  | 199/500 [06:46<08:02,  1.60s/it]

[I 2026-05-19 11:44:18,452] Trial 200 finished with value: 0.9497154056287179 and parameters: {'solver': 'saga', 'C': 0.0016600196246875421, 'l1_ratio': 0.9332636084173831, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002453749348325651, 'max_iter': 2150}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  40%|████████████████████████████████████████████▍                                                                  | 200/500 [06:52<14:54,  2.98s/it]

[I 2026-05-19 11:44:24,659] Trial 201 finished with value: 0.9497142685096716 and parameters: {'solver': 'saga', 'C': 0.0016168556200159552, 'l1_ratio': 0.8685175003092436, 'class_weight': None, 'fit_intercept': True, 'tol': 9.814298584003368e-05, 'max_iter': 3663}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  40%|████████████████████████████████████████████▌                                                                  | 201/500 [06:56<16:23,  3.29s/it]

[I 2026-05-19 11:44:28,697] Trial 202 finished with value: 0.9497160535135165 and parameters: {'solver': 'saga', 'C': 0.0018381829310000065, 'l1_ratio': 0.9011358615487618, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001014573309594825, 'max_iter': 3413}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  40%|████████████████████████████████████████████▊                                                                  | 202/500 [06:57<12:37,  2.54s/it]

[I 2026-05-19 11:44:29,484] Trial 203 finished with value: 0.9497152096193151 and parameters: {'solver': 'saga', 'C': 0.0016943502070253325, 'l1_ratio': 0.9378012336204028, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010162960882191786, 'max_iter': 3425}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  41%|█████████████████████████████████████████████                                                                  | 203/500 [06:57<09:14,  1.87s/it]

[I 2026-05-19 11:44:29,767] Trial 204 finished with value: 0.9497157214992406 and parameters: {'solver': 'saga', 'C': 0.0017101035818471702, 'l1_ratio': 0.9037474993347127, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010239141195897715, 'max_iter': 2124}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  41%|█████████████████████████████████████████████▎                                                                 | 204/500 [06:59<08:29,  1.72s/it]

[I 2026-05-19 11:44:31,137] Trial 206 finished with value: 0.9497155591513406 and parameters: {'solver': 'saga', 'C': 0.0017134613464400985, 'l1_ratio': 0.8966006139373296, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001099945754755761, 'max_iter': 2255}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:44:31,166] Trial 205 finished with value: 0.9497154726103046 and parameters: {'solver': 'saga', 'C': 0.0016915306298742705, 'l1_ratio': 0.8972436154813717, 'class_weight': None, 'fit_intercept': True, 'tol': 6.584796902082291e-05, 'max_iter': 2093}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  41%|█████████████████████████████████████████████▋                                                                 | 206/500 [07:01<07:41,  1.57s/it]

[I 2026-05-19 11:44:33,936] Trial 207 finished with value: 0.9497154538930488 and parameters: {'solver': 'saga', 'C': 0.0017896882968054622, 'l1_ratio': 0.8711491301005423, 'class_weight': None, 'fit_intercept': True, 'tol': 6.435553370324168e-05, 'max_iter': 2066}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  41%|█████████████████████████████████████████████▉                                                                 | 207/500 [07:03<07:48,  1.60s/it]

[I 2026-05-19 11:44:35,621] Trial 199 finished with value: 0.9495136590424613 and parameters: {'solver': 'saga', 'C': 0.057902773007786186, 'l1_ratio': 0.9305853143811261, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010118489006274294, 'max_iter': 4717}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  42%|██████████████████████████████████████████████▏                                                                | 208/500 [07:04<07:29,  1.54s/it]

[I 2026-05-19 11:44:36,995] Trial 208 finished with value: 0.9497151889123648 and parameters: {'solver': 'saga', 'C': 0.0016330536613113037, 'l1_ratio': 0.8972933841012101, 'class_weight': None, 'fit_intercept': True, 'tol': 4.320621041350858e-05, 'max_iter': 3659}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:44:37,050] Trial 209 finished with value: 0.9496811063690631 and parameters: {'solver': 'saga', 'C': 0.0015900500930330522, 'l1_ratio': 0.5786383735215495, 'class_weight': None, 'fit_intercept': True, 'tol': 4.366003895023685e-05, 'max_iter': 2140}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  42%|██████████████████████████████████████████████▌                                                                | 210/500 [07:07<07:02,  1.46s/it]

[I 2026-05-19 11:44:39,684] Trial 210 finished with value: 0.9496036248153701 and parameters: {'solver': 'saga', 'C': 0.0016672671015869292, 'l1_ratio': 0.8967652618123455, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.2594936391619205e-05, 'max_iter': 2316}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  42%|██████████████████████████████████████████████▊                                                                | 211/500 [07:14<12:58,  2.69s/it]

[I 2026-05-19 11:44:46,433] Trial 211 finished with value: 0.9495899392371939 and parameters: {'solver': 'saga', 'C': 0.003742441559887158, 'l1_ratio': 0.8936201187435675, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.103829843548165e-05, 'max_iter': 2292}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  42%|███████████████████████████████████████████████                                                                | 212/500 [07:16<12:45,  2.66s/it]

[I 2026-05-19 11:44:48,986] Trial 212 finished with value: 0.9497149839480397 and parameters: {'solver': 'saga', 'C': 0.0015990261062332504, 'l1_ratio': 0.8963872609900345, 'class_weight': None, 'fit_intercept': True, 'tol': 4.3741175320378644e-05, 'max_iter': 2043}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  43%|███████████████████████████████████████████████▎                                                               | 213/500 [07:17<10:13,  2.14s/it]

[I 2026-05-19 11:44:49,664] Trial 214 finished with value: 0.9497120481342527 and parameters: {'solver': 'saga', 'C': 0.0034321923047969873, 'l1_ratio': 0.8977694448364073, 'class_weight': None, 'fit_intercept': True, 'tol': 4.014066222833827e-05, 'max_iter': 2306}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  43%|███████████████████████████████████████████████▌                                                               | 214/500 [07:18<08:58,  1.88s/it]

[I 2026-05-19 11:44:50,869] Trial 215 pruned.

Best trial: 93. Best value: 0.949717:  43%|███████████████████████████████████████████████▋                                                               | 215/500 [07:20<09:21,  1.97s/it]

[I 2026-05-19 11:44:53,058] Trial 217 finished with value: 0.9496019115447313 and parameters: {'solver': 'saga', 'C': 0.0006116360856671659, 'l1_ratio': 0.8980247560376826, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.968835912541466e-05, 'max_iter': 2015}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  43%|███████████████████████████████████████████████▉                                                               | 216/500 [07:24<11:29,  2.43s/it]

[I 2026-05-19 11:44:56,635] Trial 218 finished with value: 0.9496031909439123 and parameters: {'solver': 'saga', 'C': 0.0007355044809112707, 'l1_ratio': 0.8949191971848729, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.083854169537818e-05, 'max_iter': 2014}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  43%|████████████████████████████████████████████████▏                                                              | 217/500 [07:24<08:47,  1.86s/it]

[I 2026-05-19 11:44:57,109] Trial 219 finished with value: 0.9496020476991311 and parameters: {'solver': 'saga', 'C': 0.0006283648141345132, 'l1_ratio': 0.8990477242300823, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.7780732863181335e-05, 'max_iter': 2220}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  44%|████████████████████████████████████████████████▍                                                              | 218/500 [07:27<09:24,  2.00s/it]

[I 2026-05-19 11:44:59,454] Trial 220 finished with value: 0.9496026067973087 and parameters: {'solver': 'saga', 'C': 0.0006962778931064713, 'l1_ratio': 0.9004913301255155, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.899836819694694e-05, 'max_iter': 2267}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  44%|████████████████████████████████████████████████▊                                                              | 220/500 [07:28<05:40,  1.21s/it]

[I 2026-05-19 11:45:00,248] Trial 221 finished with value: 0.9497015851057176 and parameters: {'solver': 'saga', 'C': 0.0006529744590838235, 'l1_ratio': 0.9057638804607425, 'class_weight': None, 'fit_intercept': True, 'tol': 6.2973604441992e-05, 'max_iter': 2214}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:45:00,431] Trial 216 pruned.

Best trial: 93. Best value: 0.949717:  44%|█████████████████████████████████████████████████                                                              | 221/500 [07:33<11:39,  2.51s/it]

[I 2026-05-19 11:45:05,993] Trial 222 finished with value: 0.9497036939644212 and parameters: {'solver': 'saga', 'C': 0.000721229765168618, 'l1_ratio': 0.9050647895627215, 'class_weight': None, 'fit_intercept': True, 'tol': 6.798541034587903e-05, 'max_iter': 2058}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  44%|█████████████████████████████████████████████████▎                                                             | 222/500 [07:36<11:56,  2.58s/it]

[I 2026-05-19 11:45:08,734] Trial 223 finished with value: 0.949702557716628 and parameters: {'solver': 'saga', 'C': 0.000676641783693035, 'l1_ratio': 0.9109926338712292, 'class_weight': None, 'fit_intercept': True, 'tol': 6.651753298525558e-05, 'max_iter': 1890}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  45%|█████████████████████████████████████████████████▋                                                             | 224/500 [07:36<06:11,  1.35s/it]

[I 2026-05-19 11:45:08,941] Trial 225 finished with value: 0.9496985727851948 and parameters: {'solver': 'saga', 'C': 0.0005707910633308989, 'l1_ratio': 0.9131861350277096, 'class_weight': None, 'fit_intercept': True, 'tol': 6.168128038593454e-05, 'max_iter': 1865}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:45:09,068] Trial 213 finished with value: 0.9494942305160597 and parameters: {'solver': 'saga', 'C': 0.07098541741399733, 'l1_ratio': 0.8978656202391896, 'class_weight': None, 'fit_intercept': True, 'tol': 6.701190361618943e-05, 'max_iter': 3466}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  45%|█████████████████████████████████████████████████▉                                                             | 225/500 [07:37<05:48,  1.27s/it]

[I 2026-05-19 11:45:10,146] Trial 224 finished with value: 0.9497041684772304 and parameters: {'solver': 'saga', 'C': 0.0007275748959499136, 'l1_ratio': 0.9102698503556423, 'class_weight': None, 'fit_intercept': True, 'tol': 6.83344549792663e-05, 'max_iter': 1915}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  45%|██████████████████████████████████████████████████▏                                                            | 226/500 [07:40<07:05,  1.55s/it]

[I 2026-05-19 11:45:12,372] Trial 226 finished with value: 0.9497039402203782 and parameters: {'solver': 'saga', 'C': 0.0007875817679530797, 'l1_ratio': 0.8680826215553753, 'class_weight': None, 'fit_intercept': True, 'tol': 6.367042746954859e-05, 'max_iter': 2190}. Best is trial 93 with value: 0.94971693243582.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 93. Best value: 0.949717:  45%|██████████████████████████████████████████████████▍                                                            | 227/500 [07:44<11:18,  2.48s/it]

[I 2026-05-19 11:45:17,015] Trial 227 finished with value: 0.9497122789445376 and parameters: {'solver': 'saga', 'C': 0.0034944030402205514, 'l1_ratio': 0.8694553219441706, 'class_weight': None, 'fit_intercept': True, 'tol': 5.821374247726407e-05, 'max_iter': 1918}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:45:17,065] Trial 228 finished with value: 0.9497116011874496 and parameters: {'solver': 'saga', 'C': 0.0012947562407552653, 'l1_ratio': 0.8648023867581968, 'class_weight': None, 'fit_intercept': True, 'tol': 6.27397474692348e-05, 'max_iter': 1933}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  46%|██████████████████████████████████████████████████▊                                                            | 229/500 [07:47<08:55,  1.97s/it]

[I 2026-05-19 11:45:19,783] Trial 229 finished with value: 0.9497120476246499 and parameters: {'solver': 'saga', 'C': 0.003569638058663186, 'l1_ratio': 0.8631188126273267, 'class_weight': None, 'fit_intercept': True, 'tol': 6.43071982340056e-05, 'max_iter': 2123}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  46%|███████████████████████████████████████████████████                                                            | 230/500 [07:48<07:10,  1.59s/it]

[I 2026-05-19 11:45:20,223] Trial 231 finished with value: 0.9497112840631526 and parameters: {'solver': 'saga', 'C': 0.0038194617871427786, 'l1_ratio': 0.867819028057551, 'class_weight': None, 'fit_intercept': True, 'tol': 6.450066104532043e-05, 'max_iter': 2089}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  46%|███████████████████████████████████████████████████▎                                                           | 231/500 [07:52<10:51,  2.42s/it]

[I 2026-05-19 11:45:24,974] Trial 232 finished with value: 0.9497136632150435 and parameters: {'solver': 'saga', 'C': 0.0014677869528160153, 'l1_ratio': 0.8808538288803105, 'class_weight': None, 'fit_intercept': True, 'tol': 8.421416140926695e-05, 'max_iter': 2110}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  46%|███████████████████████████████████████████████████▌                                                           | 232/500 [07:54<10:06,  2.26s/it]

[I 2026-05-19 11:45:26,817] Trial 234 finished with value: 0.9497124045257508 and parameters: {'solver': 'saga', 'C': 0.003435085033226227, 'l1_ratio': 0.8736405184172795, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011947000027421952, 'max_iter': 2149}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  47%|███████████████████████████████████████████████████▉                                                           | 234/500 [07:55<06:09,  1.39s/it]

[I 2026-05-19 11:45:27,754] Trial 235 finished with value: 0.949712333926936 and parameters: {'solver': 'saga', 'C': 0.0034759881693351476, 'l1_ratio': 0.8701419568127744, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011778145859589462, 'max_iter': 2119}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:45:27,891] Trial 233 finished with value: 0.9497118752882876 and parameters: {'solver': 'saga', 'C': 0.0013303543566861823, 'l1_ratio': 0.8644289341514473, 'class_weight': None, 'fit_intercept': True, 'tol': 8.571346225375108e-05, 'max_iter': 3932}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  47%|████████████████████████████████████████████████████▏                                                          | 235/500 [07:57<06:21,  1.44s/it]

[I 2026-05-19 11:45:29,460] Trial 236 finished with value: 0.9497113720656302 and parameters: {'solver': 'saga', 'C': 0.0037878734412676402, 'l1_ratio': 0.8659443768112612, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011545684718382377, 'max_iter': 2166}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  47%|████████████████████████████████████████████████████▍                                                          | 236/500 [07:59<07:27,  1.69s/it]

[I 2026-05-19 11:45:31,766] Trial 237 finished with value: 0.9497117274965945 and parameters: {'solver': 'saga', 'C': 0.0036860613190359734, 'l1_ratio': 0.8667919454342051, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012097020053723524, 'max_iter': 2123}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  47%|████████████████████████████████████████████████████▌                                                          | 237/500 [08:04<11:51,  2.71s/it]

[I 2026-05-19 11:45:36,893] Trial 239 finished with value: 0.9497102527470982 and parameters: {'solver': 'saga', 'C': 0.004081234098548328, 'l1_ratio': 0.8825045129949309, 'class_weight': None, 'fit_intercept': True, 'tol': 8.562712259427349e-05, 'max_iter': 3892}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  48%|████████████████████████████████████████████████████▊                                                          | 238/500 [08:05<09:04,  2.08s/it]

[I 2026-05-19 11:45:37,483] Trial 238 finished with value: 0.9497116140481392 and parameters: {'solver': 'saga', 'C': 0.0012626518270268277, 'l1_ratio': 0.8752178843410912, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012192538610503048, 'max_iter': 2147}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  48%|█████████████████████████████████████████████████████                                                          | 239/500 [08:08<10:09,  2.34s/it]

[I 2026-05-19 11:45:40,420] Trial 240 finished with value: 0.9496683037232019 and parameters: {'solver': 'saga', 'C': 0.0019207082688141189, 'l1_ratio': 0.4874509522017115, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011887637714784154, 'max_iter': 1068}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:45:40,464] Trial 241 finished with value: 0.9497160391913578 and parameters: {'solver': 'saga', 'C': 0.002074384056979584, 'l1_ratio': 0.8810652578376691, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011735815651734384, 'max_iter': 3326}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  48%|█████████████████████████████████████████████████████▌                                                         | 241/500 [08:12<09:12,  2.14s/it]

[I 2026-05-19 11:45:44,210] Trial 242 finished with value: 0.9497138739580917 and parameters: {'solver': 'saga', 'C': 0.0019368675904840405, 'l1_ratio': 0.9472213184405608, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000119472813335742, 'max_iter': 2174}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  48%|█████████████████████████████████████████████████████▋                                                         | 242/500 [08:14<09:58,  2.32s/it]

[I 2026-05-19 11:45:47,104] Trial 243 finished with value: 0.9497148550097745 and parameters: {'solver': 'saga', 'C': 0.001956730791129232, 'l1_ratio': 0.9402936938160233, 'class_weight': None, 'fit_intercept': True, 'tol': 8.447090857659349e-05, 'max_iter': 2167}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  49%|██████████████████████████████████████████████████████▏                                                        | 244/500 [08:16<06:27,  1.51s/it]

[I 2026-05-19 11:45:48,326] Trial 245 finished with value: 0.9497144953492178 and parameters: {'solver': 'saga', 'C': 0.0018242658618040277, 'l1_ratio': 0.9446337507624631, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011656284819054475, 'max_iter': 1175}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:45:48,442] Trial 246 finished with value: 0.949713623780075 and parameters: {'solver': 'saga', 'C': 0.0020316187551723394, 'l1_ratio': 0.9484275055057214, 'class_weight': None, 'fit_intercept': True, 'tol': 8.70082250681981e-05, 'max_iter': 2202}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  49%|██████████████████████████████████████████████████████▍                                                        | 245/500 [08:18<07:34,  1.78s/it]

[I 2026-05-19 11:45:50,921] Trial 247 finished with value: 0.9497147103979737 and parameters: {'solver': 'saga', 'C': 0.002002278064639585, 'l1_ratio': 0.940772263942096, 'class_weight': None, 'fit_intercept': True, 'tol': 8.14949434495116e-05, 'max_iter': 3354}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  49%|██████████████████████████████████████████████████████▊                                                        | 247/500 [08:24<08:58,  2.13s/it]

[I 2026-05-19 11:45:56,797] Trial 249 finished with value: 0.9497146285776994 and parameters: {'solver': 'saga', 'C': 0.0019910197910979737, 'l1_ratio': 0.9423641428674783, 'class_weight': None, 'fit_intercept': True, 'tol': 9.426285426915909e-05, 'max_iter': 2597}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:45:56,911] Trial 248 finished with value: 0.9497141278858013 and parameters: {'solver': 'saga', 'C': 0.0020035303008553826, 'l1_ratio': 0.9453284747708277, 'class_weight': None, 'fit_intercept': True, 'tol': 9.258650066773688e-05, 'max_iter': 1177}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  50%|███████████████████████████████████████████████████████                                                        | 248/500 [08:27<09:55,  2.36s/it]

[I 2026-05-19 11:45:59,839] Trial 251 finished with value: 0.949716251674572 and parameters: {'solver': 'saga', 'C': 0.0020197145946003426, 'l1_ratio': 0.9247941292261636, 'class_weight': None, 'fit_intercept': True, 'tol': 8.670609051090886e-05, 'max_iter': 3176}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:45:59,851] Trial 250 finished with value: 0.9497148050705008 and parameters: {'solver': 'saga', 'C': 0.0019914079112398134, 'l1_ratio': 0.9401790679599362, 'class_weight': None, 'fit_intercept': True, 'tol': 9.238700915621486e-05, 'max_iter': 2219}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  50%|███████████████████████████████████████████████████████▌                                                       | 250/500 [08:30<08:20,  2.00s/it]

[I 2026-05-19 11:46:02,971] Trial 252 finished with value: 0.9497153727825314 and parameters: {'solver': 'saga', 'C': 0.001957958056775269, 'l1_ratio': 0.9355823772638349, 'class_weight': None, 'fit_intercept': True, 'tol': 8.622105116594252e-05, 'max_iter': 1428}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  50%|███████████████████████████████████████████████████████▋                                                       | 251/500 [08:34<09:52,  2.38s/it]

[I 2026-05-19 11:46:06,518] Trial 254 finished with value: 0.9497146720087694 and parameters: {'solver': 'saga', 'C': 0.0026556619391845623, 'l1_ratio': 0.9229526835222551, 'class_weight': None, 'fit_intercept': True, 'tol': 9.334689165828082e-05, 'max_iter': 3308}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  50%|███████████████████████████████████████████████████████▉                                                       | 252/500 [08:34<07:48,  1.89s/it]

[I 2026-05-19 11:46:07,004] Trial 253 finished with value: 0.9497155258530061 and parameters: {'solver': 'saga', 'C': 0.001990527696314827, 'l1_ratio': 0.9332616007001463, 'class_weight': None, 'fit_intercept': True, 'tol': 9.25946549079589e-05, 'max_iter': 3358}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:46:07,031] Trial 255 finished with value: 0.9497147949801796 and parameters: {'solver': 'saga', 'C': 0.0026625431048730996, 'l1_ratio': 0.9174162540690773, 'class_weight': None, 'fit_intercept': True, 'tol': 9.299960459903263e-05, 'max_iter': 2346}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  51%|████████████████████████████████████████████████████████▍                                                      | 254/500 [08:42<11:04,  2.70s/it]

[I 2026-05-19 11:46:14,603] Trial 257 finished with value: 0.9497149822184724 and parameters: {'solver': 'saga', 'C': 0.0025853906838972937, 'l1_ratio': 0.922865856910069, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001729837160302869, 'max_iter': 1977}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  51%|████████████████████████████████████████████████████████▌                                                      | 255/500 [08:42<08:48,  2.16s/it]

[I 2026-05-19 11:46:14,971] Trial 258 finished with value: 0.9497150152364806 and parameters: {'solver': 'saga', 'C': 0.0025966492455739023, 'l1_ratio': 0.9201780539065623, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016750887562753358, 'max_iter': 3170}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  51%|████████████████████████████████████████████████████████▊                                                      | 256/500 [08:45<09:03,  2.23s/it]

[I 2026-05-19 11:46:17,397] Trial 260 finished with value: 0.9497147469992463 and parameters: {'solver': 'saga', 'C': 0.002658639153985393, 'l1_ratio': 0.9214558134926923, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016094842681227812, 'max_iter': 3066}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  51%|█████████████████████████████████████████████████████████                                                      | 257/500 [08:48<10:04,  2.49s/it]

[I 2026-05-19 11:46:20,628] Trial 261 finished with value: 0.9497138806211879 and parameters: {'solver': 'saga', 'C': 0.0028503570227955194, 'l1_ratio': 0.9184530929421757, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016890061020885712, 'max_iter': 3092}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  52%|█████████████████████████████████████████████████████████▎                                                     | 258/500 [08:52<11:42,  2.90s/it]

[I 2026-05-19 11:46:24,630] Trial 264 finished with value: 0.9497138644617366 and parameters: {'solver': 'saga', 'C': 0.0013195168605369407, 'l1_ratio': 0.9211551166762347, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017830525413230875, 'max_iter': 3099}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  52%|█████████████████████████████████████████████████████████▋                                                     | 260/500 [08:53<06:43,  1.68s/it]

[I 2026-05-19 11:46:25,368] Trial 230 finished with value: 0.9494128020310748 and parameters: {'solver': 'saga', 'C': 0.46170508740962823, 'l1_ratio': 0.8701147855410645, 'class_weight': None, 'fit_intercept': True, 'tol': 6.862755547018431e-05, 'max_iter': 1904}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:46:25,519] Trial 263 finished with value: 0.9497131805960883 and parameters: {'solver': 'saga', 'C': 0.0012386597392687378, 'l1_ratio': 0.9217119991646786, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017258411751251788, 'max_iter': 3341}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  52%|█████████████████████████████████████████████████████████▉                                                     | 261/500 [08:53<05:22,  1.35s/it]

[I 2026-05-19 11:46:26,053] Trial 262 finished with value: 0.9497144968078051 and parameters: {'solver': 'saga', 'C': 0.002720045757277278, 'l1_ratio': 0.9169277405399346, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001665960651796325, 'max_iter': 3138}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  52%|██████████████████████████████████████████████████████████▏                                                    | 262/500 [08:59<09:58,  2.52s/it]

[I 2026-05-19 11:46:31,387] Trial 265 finished with value: 0.9497139732827821 and parameters: {'solver': 'saga', 'C': 0.00136440316809837, 'l1_ratio': 0.9130533040270349, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024260609362265108, 'max_iter': 3083}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  53%|██████████████████████████████████████████████████████████▍                                                    | 263/500 [09:00<08:04,  2.05s/it]

[I 2026-05-19 11:46:32,306] Trial 266 finished with value: 0.9497132219076854 and parameters: {'solver': 'saga', 'C': 0.0012474352870103173, 'l1_ratio': 0.9130714265533835, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002444841520824767, 'max_iter': 3520}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  53%|██████████████████████████████████████████████████████████▌                                                    | 264/500 [09:07<13:46,  3.50s/it]

[I 2026-05-19 11:46:39,253] Trial 272 finished with value: 0.9497130388903454 and parameters: {'solver': 'saga', 'C': 0.0013436656525237585, 'l1_ratio': 0.8897617451337515, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0012007463393242444, 'max_iter': 3527}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  53%|██████████████████████████████████████████████████████████▊                                                    | 265/500 [09:09<12:14,  3.13s/it]

[I 2026-05-19 11:46:41,506] Trial 268 finished with value: 0.949711869937113 and parameters: {'solver': 'saga', 'C': 0.001221954867486006, 'l1_ratio': 0.8892759431377981, 'class_weight': None, 'fit_intercept': True, 'tol': 5.33287026010524e-05, 'max_iter': 3521}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  53%|███████████████████████████████████████████████████████████                                                    | 266/500 [09:11<10:31,  2.70s/it]

[I 2026-05-19 11:46:43,198] Trial 270 finished with value: 0.9497127155009757 and parameters: {'solver': 'saga', 'C': 0.0012846193276811765, 'l1_ratio': 0.8919686062766818, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001316968405135929, 'max_iter': 3366}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  53%|███████████████████████████████████████████████████████████▎                                                   | 267/500 [09:12<09:13,  2.38s/it]

[I 2026-05-19 11:46:44,816] Trial 269 finished with value: 0.9497132189642148 and parameters: {'solver': 'saga', 'C': 0.0013840366774065798, 'l1_ratio': 0.8860893540538766, 'class_weight': None, 'fit_intercept': True, 'tol': 5.3086858552299214e-05, 'max_iter': 3559}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  54%|███████████████████████████████████████████████████████████▍                                                   | 268/500 [09:13<07:55,  2.05s/it]

[I 2026-05-19 11:46:46,101] Trial 271 finished with value: 0.9497133271377292 and parameters: {'solver': 'saga', 'C': 0.0014158966815196552, 'l1_ratio': 0.8822932099140066, 'class_weight': None, 'fit_intercept': True, 'tol': 5.200353433496193e-05, 'max_iter': 3475}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  54%|███████████████████████████████████████████████████████████▋                                                   | 269/500 [09:16<08:57,  2.33s/it]

[I 2026-05-19 11:46:49,074] Trial 273 finished with value: 0.9497127603952638 and parameters: {'solver': 'saga', 'C': 0.001318269843906769, 'l1_ratio': 0.8870846265853792, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012779000230020427, 'max_iter': 3534}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  54%|███████████████████████████████████████████████████████████▉                                                   | 270/500 [09:19<08:43,  2.28s/it]

[I 2026-05-19 11:46:51,234] Trial 274 finished with value: 0.9497145357855535 and parameters: {'solver': 'saga', 'C': 0.0015312887735507773, 'l1_ratio': 0.8893603156261847, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013291133276647495, 'max_iter': 3232}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  54%|████████████████████████████████████████████████████████████▏                                                  | 271/500 [09:26<14:55,  3.91s/it]

[I 2026-05-19 11:46:58,957] Trial 275 finished with value: 0.9497149351414855 and parameters: {'solver': 'saga', 'C': 0.0015992373802526203, 'l1_ratio': 0.8862682017107576, 'class_weight': None, 'fit_intercept': True, 'tol': 5.276913558848356e-05, 'max_iter': 3225}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  54%|████████████████████████████████████████████████████████████▍                                                  | 272/500 [09:27<11:23,  3.00s/it]

[I 2026-05-19 11:46:59,835] Trial 276 finished with value: 0.9497150220094385 and parameters: {'solver': 'saga', 'C': 0.0016017781475677999, 'l1_ratio': 0.8909862788056744, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013149667060230488, 'max_iter': 3410}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  55%|████████████████████████████████████████████████████████████▌                                                  | 273/500 [09:30<11:35,  3.06s/it]

[I 2026-05-19 11:47:03,045] Trial 277 finished with value: 0.9497150540520615 and parameters: {'solver': 'saga', 'C': 0.0016618348101314464, 'l1_ratio': 0.8799722570479993, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010793542118269673, 'max_iter': 3292}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  55%|████████████████████████████████████████████████████████████▊                                                  | 274/500 [09:33<10:51,  2.88s/it]

[I 2026-05-19 11:47:05,504] Trial 278 finished with value: 0.9497007528488025 and parameters: {'solver': 'saga', 'C': 0.001706449786512715, 'l1_ratio': 0.7193167158780663, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010866750471769215, 'max_iter': 3285}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  55%|█████████████████████████████████████████████████████████████                                                  | 275/500 [09:33<08:06,  2.16s/it]

[I 2026-05-19 11:47:05,979] Trial 279 finished with value: 0.9495308262985421 and parameters: {'solver': 'saga', 'C': 0.0018196649574797326, 'l1_ratio': 0.21327672507099293, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012466882248879623, 'max_iter': 3255}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  55%|█████████████████████████████████████████████████████████████▎                                                 | 276/500 [09:35<07:41,  2.06s/it]

[I 2026-05-19 11:47:07,802] Trial 280 finished with value: 0.9496982568744444 and parameters: {'solver': 'saga', 'C': 0.005252968196506332, 'l1_ratio': 0.9572778246144886, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010479527555484331, 'max_iter': 4989}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  55%|█████████████████████████████████████████████████████████████▍                                                 | 277/500 [09:38<09:05,  2.45s/it]

[I 2026-05-19 11:47:11,157] Trial 281 finished with value: 0.9496040555739409 and parameters: {'solver': 'saga', 'C': 0.003035252666508798, 'l1_ratio': 0.08193822786522692, 'class_weight': None, 'fit_intercept': True, 'tol': 7.595745127351327e-05, 'max_iter': 3247}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  56%|█████████████████████████████████████████████████████████████▋                                                 | 278/500 [09:46<14:17,  3.86s/it]

[I 2026-05-19 11:47:18,322] Trial 282 finished with value: 0.9496981509759177 and parameters: {'solver': 'saga', 'C': 0.005048601127824173, 'l1_ratio': 0.9616438720057527, 'class_weight': None, 'fit_intercept': True, 'tol': 7.546282846489981e-05, 'max_iter': 3281}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  56%|█████████████████████████████████████████████████████████████▉                                                 | 279/500 [09:46<10:31,  2.86s/it]

[I 2026-05-19 11:47:18,828] Trial 283 finished with value: 0.9496980008308998 and parameters: {'solver': 'saga', 'C': 0.005006413489721609, 'l1_ratio': 0.96281845479688, 'class_weight': None, 'fit_intercept': True, 'tol': 7.799192440555543e-05, 'max_iter': 4969}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  56%|██████████████████████████████████████████████████████████████▍                                                | 281/500 [09:50<08:03,  2.21s/it]

[I 2026-05-19 11:47:22,523] Trial 288 pruned.
[I 2026-05-19 11:47:22,628] Trial 284 finished with value: 0.9496956653824095 and parameters: {'solver': 'saga', 'C': 0.005752079846146823, 'l1_ratio': 0.9636220936175028, 'class_weight': None, 'fit_intercept': True, 'tol': 7.542315933042086e-05, 'max_iter': 4969}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  56%|██████████████████████████████████████████████████████████████▌                                                | 282/500 [09:53<08:59,  2.47s/it]

[I 2026-05-19 11:47:25,725] Trial 285 finished with value: 0.9496970614144576 and parameters: {'solver': 'saga', 'C': 0.0055882288841703764, 'l1_ratio': 0.9583021296907324, 'class_weight': None, 'fit_intercept': True, 'tol': 7.957795397801049e-05, 'max_iter': 2879}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  57%|██████████████████████████████████████████████████████████████▊                                                | 283/500 [09:54<07:42,  2.13s/it]

[I 2026-05-19 11:47:27,058] Trial 259 finished with value: 0.9494097971882303 and parameters: {'solver': 'saga', 'C': 0.5644165771696961, 'l1_ratio': 0.9121688738323562, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016772179873935365, 'max_iter': 3161}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  57%|███████████████████████████████████████████████████████████████                                                | 284/500 [09:55<05:53,  1.64s/it]

[I 2026-05-19 11:47:27,537] Trial 287 finished with value: 0.9497136261985173 and parameters: {'solver': 'saga', 'C': 0.0029762362566076897, 'l1_ratio': 0.9092802735953992, 'class_weight': None, 'fit_intercept': True, 'tol': 7.763609397067735e-05, 'max_iter': 2930}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  57%|███████████████████████████████████████████████████████████████▎                                               | 285/500 [09:55<04:24,  1.23s/it]

[I 2026-05-19 11:47:27,814] Trial 286 finished with value: 0.9496875578080928 and parameters: {'solver': 'saga', 'C': 0.004434976651657679, 'l1_ratio': 0.28429607157941905, 'class_weight': None, 'fit_intercept': True, 'tol': 8.164896816258704e-05, 'max_iter': 2851}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  57%|███████████████████████████████████████████████████████████████▋                                               | 287/500 [09:56<02:41,  1.32it/s]

[I 2026-05-19 11:47:28,332] Trial 290 pruned.
[I 2026-05-19 11:47:28,496] Trial 289 pruned.

Best trial: 93. Best value: 0.949717:  58%|███████████████████████████████████████████████████████████████▉                                               | 288/500 [10:08<14:48,  4.19s/it]

[I 2026-05-19 11:47:40,692] Trial 267 finished with value: 0.9494077072007583 and parameters: {'solver': 'saga', 'C': 0.6699001714164848, 'l1_ratio': 0.8856285208384532, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001281550395940047, 'max_iter': 4992}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  58%|████████████████████████████████████████████████████████████████▍                                              | 290/500 [10:09<07:50,  2.24s/it]

[I 2026-05-19 11:47:41,347] Trial 292 finished with value: 0.9497060967351618 and parameters: {'solver': 'saga', 'C': 0.000918367064024898, 'l1_ratio': 0.8579037930686758, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010594681488887698, 'max_iter': 2936}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:47:41,504] Trial 291 finished with value: 0.9497057639091091 and parameters: {'solver': 'saga', 'C': 0.0009170670996449382, 'l1_ratio': 0.8519555908488553, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010261115375418039, 'max_iter': 4840}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  58%|████████████████████████████████████████████████████████████████▌                                              | 291/500 [10:11<08:09,  2.34s/it]

[I 2026-05-19 11:47:44,091] Trial 293 finished with value: 0.9497126737114586 and parameters: {'solver': 'saga', 'C': 0.0030393442579300495, 'l1_ratio': 0.8429438673237024, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010733904827268092, 'max_iter': 4832}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  58%|████████████████████████████████████████████████████████████████▊                                              | 292/500 [10:13<07:15,  2.09s/it]

[I 2026-05-19 11:47:45,608] Trial 294 finished with value: 0.9497125660116807 and parameters: {'solver': 'saga', 'C': 0.00292826425927249, 'l1_ratio': 0.8324363871308306, 'class_weight': None, 'fit_intercept': True, 'tol': 9.82071790070674e-05, 'max_iter': 4826}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  59%|█████████████████████████████████████████████████████████████████                                              | 293/500 [10:13<05:29,  1.59s/it]

[I 2026-05-19 11:47:46,012] Trial 296 finished with value: 0.9497135496746283 and parameters: {'solver': 'saga', 'C': 0.002395557340699227, 'l1_ratio': 0.8420239118439163, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010311668024896053, 'max_iter': 4810}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  59%|█████████████████████████████████████████████████████████████████▎                                             | 294/500 [10:14<04:10,  1.22s/it]

[I 2026-05-19 11:47:46,367] Trial 295 finished with value: 0.9497051721082277 and parameters: {'solver': 'saga', 'C': 0.0009267667956393751, 'l1_ratio': 0.8329599825939875, 'class_weight': None, 'fit_intercept': True, 'tol': 9.953550294597896e-05, 'max_iter': 4837}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  59%|█████████████████████████████████████████████████████████████████▍                                             | 295/500 [10:14<03:41,  1.08s/it]

[I 2026-05-19 11:47:47,134] Trial 297 finished with value: 0.949714117557984 and parameters: {'solver': 'saga', 'C': 0.0023940912294877713, 'l1_ratio': 0.8532364815561109, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001007547029519347, 'max_iter': 4027}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  59%|█████████████████████████████████████████████████████████████████▋                                             | 296/500 [10:15<03:07,  1.09it/s]

[I 2026-05-19 11:47:47,679] Trial 298 finished with value: 0.949713785221233 and parameters: {'solver': 'saga', 'C': 0.0023765450914587996, 'l1_ratio': 0.846752628206031, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010443530141361673, 'max_iter': 4839}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  59%|█████████████████████████████████████████████████████████████████▉                                             | 297/500 [10:26<13:08,  3.88s/it]

[I 2026-05-19 11:47:58,470] Trial 256 finished with value: 0.9494062774913555 and parameters: {'solver': 'saga', 'C': 0.7629454232165447, 'l1_ratio': 0.9185038215051164, 'class_weight': None, 'fit_intercept': True, 'tol': 9.732805028294655e-05, 'max_iter': 3071}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  60%|██████████████████████████████████████████████████████████████████▏                                            | 298/500 [10:28<11:03,  3.28s/it]

[I 2026-05-19 11:48:00,355] Trial 300 finished with value: 0.9497142608702944 and parameters: {'solver': 'saga', 'C': 0.0022565923407482716, 'l1_ratio': 0.8522455080589136, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010240506249988814, 'max_iter': 4828}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  60%|██████████████████████████████████████████████████████████████████▍                                            | 299/500 [10:28<08:23,  2.50s/it]

[I 2026-05-19 11:48:01,041] Trial 299 finished with value: 0.9497137004708149 and parameters: {'solver': 'saga', 'C': 0.002415624304400495, 'l1_ratio': 0.8463915458039624, 'class_weight': None, 'fit_intercept': True, 'tol': 9.679137281777789e-05, 'max_iter': 3634}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  60%|██████████████████████████████████████████████████████████████████▌                                            | 300/500 [10:30<06:58,  2.09s/it]

[I 2026-05-19 11:48:02,171] Trial 301 finished with value: 0.9497158196395391 and parameters: {'solver': 'saga', 'C': 0.0023450982244107386, 'l1_ratio': 0.9251346283670503, 'class_weight': None, 'fit_intercept': True, 'tol': 9.763381582217832e-05, 'max_iter': 2039}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  60%|███████████████████████████████████████████████████████████████████                                            | 302/500 [10:30<04:03,  1.23s/it]

[I 2026-05-19 11:48:02,916] Trial 303 finished with value: 0.9497154632285024 and parameters: {'solver': 'saga', 'C': 0.002115307893011075, 'l1_ratio': 0.9326904228676369, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003679999379178294, 'max_iter': 2267}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:48:03,073] Trial 302 finished with value: 0.9497151185424766 and parameters: {'solver': 'saga', 'C': 0.0023462529522480643, 'l1_ratio': 0.9339037771585539, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014053682148128425, 'max_iter': 3688}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  61%|███████████████████████████████████████████████████████████████████▎                                           | 303/500 [10:32<04:45,  1.45s/it]

[I 2026-05-19 11:48:05,039] Trial 305 finished with value: 0.9497152968221394 and parameters: {'solver': 'saga', 'C': 0.002225388699933108, 'l1_ratio': 0.933000405912795, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014785396900010323, 'max_iter': 3684}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  61%|███████████████████████████████████████████████████████████████████▍                                           | 304/500 [10:33<03:47,  1.16s/it]

[I 2026-05-19 11:48:05,531] Trial 304 finished with value: 0.9497155060112507 and parameters: {'solver': 'saga', 'C': 0.0022021663710561296, 'l1_ratio': 0.9313626398268613, 'class_weight': None, 'fit_intercept': True, 'tol': 5.512577017385672e-05, 'max_iter': 2034}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  61%|███████████████████████████████████████████████████████████████████▋                                           | 305/500 [10:33<02:50,  1.14it/s]

[I 2026-05-19 11:48:05,741] Trial 307 finished with value: 0.9497154435502718 and parameters: {'solver': 'saga', 'C': 0.0022817662908714395, 'l1_ratio': 0.9311286257395369, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014495316768182642, 'max_iter': 2027}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  61%|███████████████████████████████████████████████████████████████████▉                                           | 306/500 [10:34<02:31,  1.28it/s]

[I 2026-05-19 11:48:06,301] Trial 306 finished with value: 0.9497159362672782 and parameters: {'solver': 'saga', 'C': 0.002120042393743383, 'l1_ratio': 0.927841038716097, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001249875073744353, 'max_iter': 2243}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  61%|████████████████████████████████████████████████████████████████████▏                                          | 307/500 [10:38<05:34,  1.73s/it]

[I 2026-05-19 11:48:10,251] Trial 244 finished with value: 0.9494048041871059 and parameters: {'solver': 'saga', 'C': 0.8982958260401629, 'l1_ratio': 0.9447540594819406, 'class_weight': None, 'fit_intercept': True, 'tol': 8.494762740031486e-05, 'max_iter': 3343}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  62%|████████████████████████████████████████████████████████████████████▍                                          | 308/500 [10:44<10:25,  3.26s/it]

[I 2026-05-19 11:48:17,072] Trial 308 finished with value: 0.9497152439499656 and parameters: {'solver': 'saga', 'C': 0.002008068997752447, 'l1_ratio': 0.9359019478680045, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001419031134464555, 'max_iter': 2033}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  62%|████████████████████████████████████████████████████████████████████▌                                          | 309/500 [10:46<08:39,  2.72s/it]

[I 2026-05-19 11:48:18,532] Trial 309 finished with value: 0.9497154326446695 and parameters: {'solver': 'saga', 'C': 0.001960326074031168, 'l1_ratio': 0.934825464913754, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001384573373346328, 'max_iter': 2261}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  62%|████████████████████████████████████████████████████████████████████▊                                          | 310/500 [10:47<07:18,  2.31s/it]

[I 2026-05-19 11:48:19,880] Trial 310 finished with value: 0.9497049040073418 and parameters: {'solver': 'saga', 'C': 0.007515215251907886, 'l1_ratio': 0.9284639909160595, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014089075039270952, 'max_iter': 2064}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  62%|█████████████████████████████████████████████████████████████████████▎                                         | 312/500 [10:49<04:26,  1.42s/it]

[I 2026-05-19 11:48:21,032] Trial 311 finished with value: 0.9497039662152991 and parameters: {'solver': 'saga', 'C': 0.007532633850423267, 'l1_ratio': 0.9338607814707932, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013413222118226366, 'max_iter': 2042}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:48:21,174] Trial 316 finished with value: 0.9497006973875198 and parameters: {'solver': 'saga', 'C': 0.007837080692880445, 'l1_ratio': 0.9507228158825904, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005719058465870481, 'max_iter': 1796}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  62%|█████████████████████████████████████████████████████████████████████▎                                         | 312/500 [10:49<04:26,  1.42s/it]

[I 2026-05-19 11:48:21,259] Trial 313 finished with value: 0.9497104818198967 and parameters: {'solver': 'saga', 'C': 0.0033523157348124876, 'l1_ratio': 0.9309120318591374, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013858223479157924, 'max_iter': 2003}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  63%|█████████████████████████████████████████████████████████████████████▋                                         | 314/500 [10:50<03:31,  1.14s/it]

[I 2026-05-19 11:48:22,795] Trial 312 finished with value: 0.9497110101693662 and parameters: {'solver': 'saga', 'C': 0.003243301323129187, 'l1_ratio': 0.9309693705873255, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014173542484919433, 'max_iter': 2038}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  63%|█████████████████████████████████████████████████████████████████████▉                                         | 315/500 [10:52<04:16,  1.38s/it]

[I 2026-05-19 11:48:24,941] Trial 315 finished with value: 0.9497039273413611 and parameters: {'solver': 'saga', 'C': 0.007576656671680959, 'l1_ratio': 0.9338290585188771, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013176899836711477, 'max_iter': 1784}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  63%|██████████████████████████████████████████████████████████████████████▏                                        | 316/500 [10:53<03:55,  1.28s/it]

[I 2026-05-19 11:48:25,921] Trial 317 finished with value: 0.9497083211892899 and parameters: {'solver': 'saga', 'C': 0.007270541326463857, 'l1_ratio': 0.9074228691933317, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012954806061903147, 'max_iter': 2352}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  64%|██████████████████████████████████████████████████████████████████████▌                                        | 318/500 [10:56<05:10,  1.70s/it]

[I 2026-05-19 11:48:29,096] Trial 314 finished with value: 0.9496122228408446 and parameters: {'solver': 'saga', 'C': 0.0001412503952456956, 'l1_ratio': 0.9287581834883671, 'class_weight': None, 'fit_intercept': True, 'tol': 7.015888363362276e-06, 'max_iter': 2041}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:48:29,098] Trial 318 finished with value: 0.9497111399590942 and parameters: {'solver': 'saga', 'C': 0.0036053711196549036, 'l1_ratio': 0.9055013477501878, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013033526325117436, 'max_iter': 1971}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  64%|██████████████████████████████████████████████████████████████████████▊                                        | 319/500 [11:04<09:21,  3.10s/it]

[I 2026-05-19 11:48:36,672] Trial 319 finished with value: 0.9497124694537563 and parameters: {'solver': 'saga', 'C': 0.003251015881385721, 'l1_ratio': 0.9045904909352289, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012600565234213585, 'max_iter': 2267}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  64%|███████████████████████████████████████████████████████████████████████                                        | 320/500 [11:05<08:02,  2.68s/it]

[I 2026-05-19 11:48:38,112] Trial 324 finished with value: 0.9497112424409734 and parameters: {'solver': 'saga', 'C': 0.003567111239002348, 'l1_ratio': 0.9058934368027957, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020036569877719, 'max_iter': 4928}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  64%|███████████████████████████████████████████████████████████████████████▎                                       | 321/500 [11:06<06:07,  2.05s/it]

[I 2026-05-19 11:48:38,432] Trial 321 finished with value: 0.9497106752071074 and parameters: {'solver': 'saga', 'C': 0.0038162168416209156, 'l1_ratio': 0.8978747549750751, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000194146089918814, 'max_iter': 2385}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  65%|███████████████████████████████████████████████████████████████████████▋                                       | 323/500 [11:07<03:56,  1.34s/it]

[I 2026-05-19 11:48:39,612] Trial 323 finished with value: 0.9497105675222652 and parameters: {'solver': 'saga', 'C': 0.003791914558758065, 'l1_ratio': 0.9016574516517704, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012267164292457822, 'max_iter': 4925}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:48:39,726] Trial 322 finished with value: 0.949710504730214 and parameters: {'solver': 'saga', 'C': 0.003837138940328871, 'l1_ratio': 0.8994794718356223, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019654310530776894, 'max_iter': 2297}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  65%|███████████████████████████████████████████████████████████████████████▉                                       | 324/500 [11:08<03:23,  1.15s/it]

[I 2026-05-19 11:48:40,442] Trial 325 finished with value: 0.9497075768532766 and parameters: {'solver': 'saga', 'C': 0.004485468453578726, 'l1_ratio': 0.9079759080510813, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002054170293039373, 'max_iter': 2359}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  65%|████████████████████████████████████████████████████████████████████████▏                                      | 325/500 [11:10<04:08,  1.42s/it]

[I 2026-05-19 11:48:42,511] Trial 320 finished with value: 0.9497143417722114 and parameters: {'solver': 'saga', 'C': 0.0028163153465870423, 'l1_ratio': 0.9033494172714263, 'class_weight': None, 'fit_intercept': True, 'tol': 8.283063157428177e-06, 'max_iter': 2068}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  65%|████████████████████████████████████████████████████████████████████████▎                                      | 326/500 [11:10<03:08,  1.09s/it]

[I 2026-05-19 11:48:42,791] Trial 326 finished with value: 0.9497013544562295 and parameters: {'solver': 'saga', 'C': 0.003977187725885944, 'l1_ratio': 0.6287117266968321, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001921137175937721, 'max_iter': 2391}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  65%|████████████████████████████████████████████████████████████████████████▌                                      | 327/500 [11:11<02:58,  1.03s/it]

[I 2026-05-19 11:48:43,691] Trial 327 finished with value: 0.949710080165192 and parameters: {'solver': 'saga', 'C': 0.003932864864633423, 'l1_ratio': 0.9012029436285489, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001859580094613885, 'max_iter': 2265}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  66%|████████████████████████████████████████████████████████████████████████▊                                      | 328/500 [11:13<03:45,  1.31s/it]

[I 2026-05-19 11:48:45,679] Trial 329 finished with value: 0.9497105235953107 and parameters: {'solver': 'saga', 'C': 0.0039342952713087385, 'l1_ratio': 0.8875301725820006, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020033168653635637, 'max_iter': 4916}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  66%|█████████████████████████████████████████████████████████████████████████                                      | 329/500 [11:15<04:30,  1.58s/it]

[I 2026-05-19 11:48:47,888] Trial 328 finished with value: 0.9497100856958905 and parameters: {'solver': 'saga', 'C': 0.003946343679004373, 'l1_ratio': 0.9004590784455658, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018392683013201776, 'max_iter': 2235}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  66%|█████████████████████████████████████████████████████████████████████████▎                                     | 330/500 [11:22<08:37,  3.04s/it]

[I 2026-05-19 11:48:54,361] Trial 330 finished with value: 0.9497118574147294 and parameters: {'solver': 'saga', 'C': 0.0012031955068169619, 'l1_ratio': 0.8933023045903596, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019009765019680267, 'max_iter': 4924}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  66%|█████████████████████████████████████████████████████████████████████████▍                                     | 331/500 [11:25<09:06,  3.23s/it]

[I 2026-05-19 11:48:58,049] Trial 331 finished with value: 0.9497105008959654 and parameters: {'solver': 'saga', 'C': 0.0011232861883309448, 'l1_ratio': 0.885612101830975, 'class_weight': None, 'fit_intercept': True, 'tol': 5.4448552423308464e-05, 'max_iter': 3430}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  66%|█████████████████████████████████████████████████████████████████████████▋                                     | 332/500 [11:26<06:51,  2.45s/it]

[I 2026-05-19 11:48:58,645] Trial 332 finished with value: 0.9497110453546579 and parameters: {'solver': 'saga', 'C': 0.0011754376237145228, 'l1_ratio': 0.8843737640380842, 'class_weight': None, 'fit_intercept': True, 'tol': 6.093011296278783e-05, 'max_iter': 3781}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  67%|█████████████████████████████████████████████████████████████████████████▉                                     | 333/500 [11:27<05:43,  2.05s/it]

[I 2026-05-19 11:48:59,794] Trial 335 finished with value: 0.9497123080029543 and parameters: {'solver': 'saga', 'C': 0.0013038395856123412, 'l1_ratio': 0.8799068501554421, 'class_weight': None, 'fit_intercept': True, 'tol': 5.574536601110781e-05, 'max_iter': 2216}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  67%|██████████████████████████████████████████████████████████████████████████▏                                    | 334/500 [11:28<04:29,  1.62s/it]

[I 2026-05-19 11:49:00,395] Trial 333 finished with value: 0.9496828670925568 and parameters: {'solver': 'saga', 'C': 0.001155892906552121, 'l1_ratio': 0.6261665029558127, 'class_weight': None, 'fit_intercept': True, 'tol': 5.576871417771375e-05, 'max_iter': 3406}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  67%|██████████████████████████████████████████████████████████████████████████▎                                    | 335/500 [11:28<03:22,  1.22s/it]

[I 2026-05-19 11:49:00,693] Trial 334 finished with value: 0.9497112429957918 and parameters: {'solver': 'saga', 'C': 0.0012118164973695458, 'l1_ratio': 0.8789504136891387, 'class_weight': None, 'fit_intercept': True, 'tol': 5.4362204074487376e-05, 'max_iter': 2723}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  67%|██████████████████████████████████████████████████████████████████████████▌                                    | 336/500 [11:30<04:16,  1.57s/it]

[I 2026-05-19 11:49:03,050] Trial 337 finished with value: 0.9497101217077055 and parameters: {'solver': 'saga', 'C': 0.001111165125045076, 'l1_ratio': 0.8812955656135045, 'class_weight': None, 'fit_intercept': True, 'tol': 5.4653305449405766e-05, 'max_iter': 2219}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  67%|██████████████████████████████████████████████████████████████████████████▊                                    | 337/500 [11:31<03:09,  1.16s/it]

[I 2026-05-19 11:49:03,289] Trial 336 finished with value: 0.9497121332962166 and parameters: {'solver': 'saga', 'C': 0.0012807984931753618, 'l1_ratio': 0.8816051967611088, 'class_weight': None, 'fit_intercept': True, 'tol': 5.4570193567247884e-05, 'max_iter': 4723}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  68%|███████████████████████████████████████████████████████████████████████████                                    | 338/500 [11:34<04:34,  1.69s/it]

[I 2026-05-19 11:49:06,213] Trial 338 finished with value: 0.9493976771178871 and parameters: {'solver': 'saga', 'C': 7.3142027665310545, 'l1_ratio': 0.8823000383268346, 'class_weight': None, 'fit_intercept': True, 'tol': 5.4666444612769265e-05, 'max_iter': 3422}. Best is trial 93 with value: 0.94971693243582.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 93. Best value: 0.949717:  68%|███████████████████████████████████████████████████████████████████████████▎                                   | 339/500 [11:35<04:30,  1.68s/it]

[I 2026-05-19 11:49:07,864] Trial 9 pruned.

Best trial: 93. Best value: 0.949717:  68%|███████████████████████████████████████████████████████████████████████████▋                                   | 341/500 [11:36<02:38,  1.00it/s]

[I 2026-05-19 11:49:08,500] Trial 339 finished with value: 0.9497074278591807 and parameters: {'solver': 'saga', 'C': 0.001133864538606347, 'l1_ratio': 0.976433395867239, 'class_weight': None, 'fit_intercept': True, 'tol': 3.0571802368868804e-05, 'max_iter': 3417}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:49:08,621] Trial 347 pruned.

Best trial: 93. Best value: 0.949717:  69%|████████████████████████████████████████████████████████████████████████████▏                                  | 343/500 [11:36<01:36,  1.63it/s]

[I 2026-05-19 11:49:08,998] Trial 348 pruned.
[I 2026-05-19 11:49:09,161] Trial 340 finished with value: 0.949706321551054 and parameters: {'solver': 'saga', 'C': 0.0015162629890991218, 'l1_ratio': 0.9798561862093141, 'class_weight': None, 'fit_intercept': True, 'tol': 5.2502487159870705e-05, 'max_iter': 3379}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  69%|████████████████████████████████████████████████████████████████████████████▎                                  | 344/500 [11:38<02:03,  1.26it/s]

[I 2026-05-19 11:49:10,363] Trial 346 pruned.

Best trial: 93. Best value: 0.949717:  69%|████████████████████████████████████████████████████████████████████████████▌                                  | 345/500 [11:41<03:54,  1.51s/it]

[I 2026-05-19 11:49:13,555] Trial 344 pruned.

Best trial: 93. Best value: 0.949717:  69%|████████████████████████████████████████████████████████████████████████████▊                                  | 346/500 [11:43<04:08,  1.61s/it]

[I 2026-05-19 11:49:15,412] Trial 349 pruned.

Best trial: 93. Best value: 0.949717:  69%|█████████████████████████████████████████████████████████████████████████████                                  | 347/500 [11:44<03:32,  1.39s/it]

[I 2026-05-19 11:49:16,272] Trial 341 finished with value: 0.9497075386498013 and parameters: {'solver': 'saga', 'C': 0.0017848678912313661, 'l1_ratio': 0.9752010046976594, 'class_weight': None, 'fit_intercept': True, 'tol': 3.289645111650971e-05, 'max_iter': 4776}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  70%|█████████████████████████████████████████████████████████████████████████████▎                                 | 348/500 [11:46<03:59,  1.57s/it]

[I 2026-05-19 11:49:18,275] Trial 342 finished with value: 0.9497069011431283 and parameters: {'solver': 'saga', 'C': 0.0015378962933511903, 'l1_ratio': 0.9783798237928936, 'class_weight': None, 'fit_intercept': True, 'tol': 7.113903939822207e-05, 'max_iter': 4722}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  70%|█████████████████████████████████████████████████████████████████████████████▍                                 | 349/500 [11:47<03:52,  1.54s/it]

[I 2026-05-19 11:49:19,741] Trial 343 finished with value: 0.949704982779946 and parameters: {'solver': 'saga', 'C': 0.0016976252280575268, 'l1_ratio': 0.9820299905869815, 'class_weight': None, 'fit_intercept': True, 'tol': 7.062198260756488e-05, 'max_iter': 4742}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  70%|█████████████████████████████████████████████████████████████████████████████▋                                 | 350/500 [11:55<08:56,  3.58s/it]

[I 2026-05-19 11:49:28,070] Trial 350 finished with value: 0.9497131751357513 and parameters: {'solver': 'saga', 'C': 0.0018034202306943033, 'l1_ratio': 0.9538996067886356, 'class_weight': None, 'fit_intercept': True, 'tol': 7.456692246092498e-05, 'max_iter': 4561}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:49:28,105] Trial 352 finished with value: 0.949624996873629 and parameters: {'solver': 'saga', 'C': 0.0017171745480451899, 'l1_ratio': 0.40917468405019664, 'class_weight': None, 'fit_intercept': True, 'tol': 7.932321403657227e-05, 'max_iter': 4991}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  70%|██████████████████████████████████████████████████████████████████████████████▏                                | 352/500 [11:56<05:09,  2.09s/it]

[I 2026-05-19 11:49:28,777] Trial 354 finished with value: 0.9497160857431137 and parameters: {'solver': 'saga', 'C': 0.0017826468160281128, 'l1_ratio': 0.9232436810985576, 'class_weight': None, 'fit_intercept': True, 'tol': 7.45390060664588e-05, 'max_iter': 5000}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:49:28,805] Trial 351 finished with value: 0.9497114044930166 and parameters: {'solver': 'saga', 'C': 0.0021010038811120828, 'l1_ratio': 0.9599188379280732, 'class_weight': None, 'fit_intercept': True, 'tol': 8.446304869461307e-05, 'max_iter': 4639}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  71%|██████████████████████████████████████████████████████████████████████████████▌                                | 354/500 [11:57<03:16,  1.34s/it]

[I 2026-05-19 11:49:29,205] Trial 353 finished with value: 0.9497137849731914 and parameters: {'solver': 'saga', 'C': 0.0016873822351857384, 'l1_ratio': 0.9504922155308785, 'class_weight': None, 'fit_intercept': True, 'tol': 7.127232556575386e-05, 'max_iter': 4939}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  71%|██████████████████████████████████████████████████████████████████████████████▊                                | 355/500 [11:57<02:42,  1.12s/it]

[I 2026-05-19 11:49:29,528] Trial 355 finished with value: 0.9497147561022963 and parameters: {'solver': 'saga', 'C': 0.0026714056301064605, 'l1_ratio': 0.917058175468892, 'class_weight': None, 'fit_intercept': True, 'tol': 8.742191703572091e-05, 'max_iter': 4993}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  71%|███████████████████████████████████████████████████████████████████████████████                                | 356/500 [11:59<03:24,  1.42s/it]

[I 2026-05-19 11:49:31,889] Trial 345 pruned.

Best trial: 93. Best value: 0.949717:  71%|███████████████████████████████████████████████████████████████████████████████▎                               | 357/500 [11:59<02:40,  1.12s/it]

[I 2026-05-19 11:49:32,141] Trial 356 finished with value: 0.9495698606535852 and parameters: {'solver': 'saga', 'C': 4.3060006701989344e-05, 'l1_ratio': 0.9208511024570712, 'class_weight': None, 'fit_intercept': True, 'tol': 8.933036482231472e-05, 'max_iter': 1940}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  72%|███████████████████████████████████████████████████████████████████████████████▍                               | 358/500 [12:03<04:16,  1.80s/it]

[I 2026-05-19 11:49:35,830] Trial 357 finished with value: 0.9497145239778517 and parameters: {'solver': 'saga', 'C': 0.00270611975334206, 'l1_ratio': 0.9193516586107774, 'class_weight': None, 'fit_intercept': True, 'tol': 8.694719968566666e-05, 'max_iter': 2605}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  72%|███████████████████████████████████████████████████████████████████████████████▋                               | 359/500 [12:03<03:13,  1.37s/it]

[I 2026-05-19 11:49:36,068] Trial 358 finished with value: 0.9497143354413138 and parameters: {'solver': 'saga', 'C': 0.0027606957008003393, 'l1_ratio': 0.9166848833065565, 'class_weight': None, 'fit_intercept': True, 'tol': 8.770832881352018e-05, 'max_iter': 4990}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  72%|███████████████████████████████████████████████████████████████████████████████▉                               | 360/500 [12:05<03:38,  1.56s/it]

[I 2026-05-19 11:49:38,119] Trial 359 finished with value: 0.9497145311354332 and parameters: {'solver': 'saga', 'C': 0.0026886823316815646, 'l1_ratio': 0.9208732144156682, 'class_weight': None, 'fit_intercept': True, 'tol': 8.305078101066445e-05, 'max_iter': 4966}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  72%|████████████████████████████████████████████████████████████████████████████████▏                              | 361/500 [12:06<03:09,  1.36s/it]

[I 2026-05-19 11:49:38,972] Trial 360 finished with value: 0.9495924251752621 and parameters: {'solver': 'saga', 'C': 0.0026815283941099316, 'l1_ratio': 0.9199123318092667, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 8.762147778157382e-05, 'max_iter': 4451}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  73%|████████████████████████████████████████████████████████████████████████████████▊                              | 364/500 [12:15<04:31,  2.00s/it]

[I 2026-05-19 11:49:47,947] Trial 366 finished with value: 0.9495931742673192 and parameters: {'solver': 'saga', 'C': 0.0026566867017973803, 'l1_ratio': 0.9156612924140534, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011377692772633941, 'max_iter': 4885}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:49:47,957] Trial 364 finished with value: 0.9495909866914263 and parameters: {'solver': 'saga', 'C': 0.0028238995720616636, 'l1_ratio': 0.92172523597706, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011273846823384379, 'max_iter': 4939}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:49:48,116] Trial 361 finished with value: 0.9495944260060398 and parameters: {'solver': 'saga', 'C': 0.0024840839711554995, 'l1_ratio': 0.9162359434223573, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.088401965409089e-05, 'max_iter': 4944}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  73%|████████████████████████████████████████████████████████████████████████████████▊                              | 364/500 [12:16<04:31,  2.00s/it]

[I 2026-05-19 11:49:48,174] Trial 362 finished with value: 0.9495928425837586 and parameters: {'solver': 'saga', 'C': 0.002673993326612728, 'l1_ratio': 0.9170518824198751, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 8.741281352146337e-05, 'max_iter': 4994}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  73%|█████████████████████████████████████████████████████████████████████████████████▎                             | 366/500 [12:16<02:54,  1.30s/it]

[I 2026-05-19 11:49:48,614] Trial 363 finished with value: 0.9497140935572567 and parameters: {'solver': 'saga', 'C': 0.002784065255834978, 'l1_ratio': 0.9202683465993401, 'class_weight': None, 'fit_intercept': True, 'tol': 9.247484523830656e-05, 'max_iter': 4870}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:49:48,661] Trial 365 finished with value: 0.949591707154094 and parameters: {'solver': 'saga', 'C': 0.002788633466112769, 'l1_ratio': 0.9185994034197941, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011476580098463161, 'max_iter': 4885}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  74%|█████████████████████████████████████████████████████████████████████████████████▋                             | 368/500 [12:19<02:52,  1.31s/it]

[I 2026-05-19 11:49:51,233] Trial 368 finished with value: 0.9495917513984866 and parameters: {'solver': 'saga', 'C': 0.002689066527016926, 'l1_ratio': 0.9241350503292147, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011442615874293554, 'max_iter': 4869}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  74%|█████████████████████████████████████████████████████████████████████████████████▉                             | 369/500 [12:20<02:55,  1.34s/it]

[I 2026-05-19 11:49:52,688] Trial 367 finished with value: 0.94959191472003 and parameters: {'solver': 'saga', 'C': 0.0027551230428445868, 'l1_ratio': 0.9190326685171503, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011596024176504346, 'max_iter': 4882}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  74%|██████████████████████████████████████████████████████████████████████████████████▏                            | 370/500 [12:23<03:52,  1.79s/it]

[I 2026-05-19 11:49:56,018] Trial 370 finished with value: 0.9495974202971393 and parameters: {'solver': 'saga', 'C': 0.002936035019780128, 'l1_ratio': 0.8648324697704671, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001150845086627358, 'max_iter': 4850}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  74%|██████████████████████████████████████████████████████████████████████████████████▎                            | 371/500 [12:24<03:15,  1.52s/it]

[I 2026-05-19 11:49:56,696] Trial 369 finished with value: 0.94958983938658 and parameters: {'solver': 'saga', 'C': 0.0029361046465240393, 'l1_ratio': 0.9246586152569135, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011696558302766716, 'max_iter': 4895}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  74%|██████████████████████████████████████████████████████████████████████████████████▌                            | 372/500 [12:25<02:48,  1.32s/it]

[I 2026-05-19 11:49:57,464] Trial 371 finished with value: 0.9495984911509275 and parameters: {'solver': 'saga', 'C': 0.002789554081539946, 'l1_ratio': 0.8667649964793817, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00011136190156575416, 'max_iter': 4902}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  75%|██████████████████████████████████████████████████████████████████████████████████▊                            | 373/500 [12:26<02:34,  1.22s/it]

[I 2026-05-19 11:49:58,401] Trial 372 finished with value: 0.9497049232383968 and parameters: {'solver': 'saga', 'C': 0.0008267284536784262, 'l1_ratio': 0.8730200200900153, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011608747482424815, 'max_iter': 4867}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  75%|███████████████████████████████████████████████████████████████████████████████████▎                           | 375/500 [12:33<04:26,  2.13s/it]

[I 2026-05-19 11:50:05,753] Trial 376 finished with value: 0.949694695022383 and parameters: {'solver': 'saga', 'C': 0.0004801508239870278, 'l1_ratio': 0.8716731589427368, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016380570907327532, 'max_iter': 4836}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:50:05,890] Trial 374 finished with value: 0.9497073176396714 and parameters: {'solver': 'saga', 'C': 0.0008147191626890467, 'l1_ratio': 0.9381193440884997, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015405658206141831, 'max_iter': 4855}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  75%|███████████████████████████████████████████████████████████████████████████████████▍                           | 376/500 [12:34<03:18,  1.60s/it]

[I 2026-05-19 11:50:06,194] Trial 375 finished with value: 0.9497037490802427 and parameters: {'solver': 'saga', 'C': 0.0007874924296924555, 'l1_ratio': 0.8613762234956965, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001646109889239511, 'max_iter': 4863}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:50:06,264] Trial 378 finished with value: 0.9496947685470744 and parameters: {'solver': 'saga', 'C': 0.00048129245925451536, 'l1_ratio': 0.8652926683683511, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016692168507030056, 'max_iter': 4852}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  76%|████████████████████████████████████████████████████████████████████████████████████▏                          | 379/500 [12:35<01:48,  1.11it/s]

[I 2026-05-19 11:50:07,368] Trial 373 finished with value: 0.9497148713722717 and parameters: {'solver': 'saga', 'C': 0.0022264746750740422, 'l1_ratio': 0.8619803144928417, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011485454963048935, 'max_iter': 4840}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:50:07,481] Trial 377 finished with value: 0.9497050821664382 and parameters: {'solver': 'saga', 'C': 0.0008355792537287826, 'l1_ratio': 0.8723681834227675, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015473735158116162, 'max_iter': 4851}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  76%|████████████████████████████████████████████████████████████████████████████████████▎                          | 380/500 [12:38<02:55,  1.46s/it]

[I 2026-05-19 11:50:10,573] Trial 379 finished with value: 0.9495013819136998 and parameters: {'solver': 'saga', 'C': 0.0003540420070114388, 'l1_ratio': 0.5717643711949452, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001147256148361212, 'max_iter': 4824}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  76%|████████████████████████████████████████████████████████████████████████████████████▌                          | 381/500 [12:38<02:21,  1.19s/it]

[I 2026-05-19 11:50:11,041] Trial 380 finished with value: 0.949707107894709 and parameters: {'solver': 'saga', 'C': 0.0009683511465195715, 'l1_ratio': 0.8607590434118108, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015903450462676275, 'max_iter': 3031}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  76%|████████████████████████████████████████████████████████████████████████████████████▊                          | 382/500 [12:42<03:45,  1.91s/it]

[I 2026-05-19 11:50:14,832] Trial 381 finished with value: 0.9496818843473344 and parameters: {'solver': 'saga', 'C': 0.0003883910949706592, 'l1_ratio': 0.9444785162658194, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015315210158864802, 'max_iter': 4089}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:50:14,834] Trial 382 finished with value: 0.949705854193563 and parameters: {'solver': 'saga', 'C': 0.0009036089549589702, 'l1_ratio': 0.8578763503743694, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015901516881118238, 'max_iter': 3171}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  77%|█████████████████████████████████████████████████████████████████████████████████████▏                         | 384/500 [12:43<02:24,  1.25s/it]

[I 2026-05-19 11:50:15,644] Trial 383 finished with value: 0.9497096202524264 and parameters: {'solver': 'saga', 'C': 0.0009224764257895691, 'l1_ratio': 0.9471043128543152, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015248232259198135, 'max_iter': 4788}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:50:15,728] Trial 384 finished with value: 0.9497100932875997 and parameters: {'solver': 'saga', 'C': 0.0009418969579864394, 'l1_ratio': 0.9411969474906179, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001527104310219825, 'max_iter': 3202}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  77%|█████████████████████████████████████████████████████████████████████████████████████▉                         | 387/500 [12:52<03:40,  1.95s/it]

[I 2026-05-19 11:50:24,344] Trial 385 finished with value: 0.9497078270813007 and parameters: {'solver': 'saga', 'C': 0.0009171300811598682, 'l1_ratio': 0.8950806817713022, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001636604788066001, 'max_iter': 3216}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:50:24,483] Trial 386 finished with value: 0.9497164037410771 and parameters: {'solver': 'saga', 'C': 0.0019824300022262434, 'l1_ratio': 0.8933195542032795, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014154490835582907, 'max_iter': 3176}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  78%|██████████████████████████████████████████████████████████████████████████████████████▏                        | 388/500 [12:52<03:00,  1.61s/it]

[I 2026-05-19 11:50:25,007] Trial 388 finished with value: 0.9497073102338941 and parameters: {'solver': 'saga', 'C': 0.004873276450975143, 'l1_ratio': 0.8950645518391215, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014525947523635666, 'max_iter': 4678}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  78%|██████████████████████████████████████████████████████████████████████████████████████▎                        | 389/500 [12:53<02:35,  1.40s/it]

[I 2026-05-19 11:50:25,797] Trial 387 finished with value: 0.9497081021273497 and parameters: {'solver': 'saga', 'C': 0.005979665818407944, 'l1_ratio': 0.8941447960545388, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014626820581059672, 'max_iter': 3192}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  78%|██████████████████████████████████████████████████████████████████████████████████████▌                        | 390/500 [12:54<02:08,  1.16s/it]

[I 2026-05-19 11:50:26,303] Trial 389 finished with value: 0.9497058117281867 and parameters: {'solver': 'saga', 'C': 0.005342957421195073, 'l1_ratio': 0.8963491528621402, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013570165416165362, 'max_iter': 4712}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  78%|██████████████████████████████████████████████████████████████████████████████████████▊                        | 391/500 [12:54<01:44,  1.05it/s]

[I 2026-05-19 11:50:26,705] Trial 390 finished with value: 0.9497084311875568 and parameters: {'solver': 'saga', 'C': 0.004565208384731002, 'l1_ratio': 0.8935419309065001, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015014565595289524, 'max_iter': 3163}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  78%|███████████████████████████████████████████████████████████████████████████████████████                        | 392/500 [12:56<02:19,  1.29s/it]

[I 2026-05-19 11:50:28,857] Trial 392 finished with value: 0.9497141280267585 and parameters: {'solver': 'saga', 'C': 0.0014230136208689685, 'l1_ratio': 0.945574324239266, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002709954961182269, 'max_iter': 2497}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  79%|███████████████████████████████████████████████████████████████████████████████████████▏                       | 393/500 [12:57<01:48,  1.01s/it]

[I 2026-05-19 11:50:29,174] Trial 391 finished with value: 0.9497029608012559 and parameters: {'solver': 'saga', 'C': 0.004417861567796062, 'l1_ratio': 0.9453574580604392, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014703098469473998, 'max_iter': 3198}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  79%|███████████████████████████████████████████████████████████████████████████████████████▍                       | 394/500 [12:59<02:46,  1.57s/it]

[I 2026-05-19 11:50:32,097] Trial 396 finished with value: 0.9497066509363453 and parameters: {'solver': 'saga', 'C': 0.0051474253682988825, 'l1_ratio': 0.8928999872133254, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024110697482418702, 'max_iter': 4701}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  79%|███████████████████████████████████████████████████████████████████████████████████████▋                       | 395/500 [13:02<03:05,  1.77s/it]

[I 2026-05-19 11:50:34,349] Trial 398 pruned.

Best trial: 93. Best value: 0.949717:  79%|███████████████████████████████████████████████████████████████████████████████████████▉                       | 396/500 [13:02<02:23,  1.38s/it]

[I 2026-05-19 11:50:34,793] Trial 394 finished with value: 0.9497074943777202 and parameters: {'solver': 'saga', 'C': 0.004663276751366297, 'l1_ratio': 0.9016389875248931, 'class_weight': None, 'fit_intercept': True, 'tol': 4.487500336274498e-05, 'max_iter': 2534}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  79%|████████████████████████████████████████████████████████████████████████████████████████▏                      | 397/500 [13:04<02:35,  1.51s/it]

[I 2026-05-19 11:50:36,594] Trial 393 finished with value: 0.9497061577262876 and parameters: {'solver': 'saga', 'C': 0.00522485242561264, 'l1_ratio': 0.8968001252206393, 'class_weight': None, 'fit_intercept': True, 'tol': 4.656610691162205e-05, 'max_iter': 4698}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  80%|████████████████████████████████████████████████████████████████████████████████████████▎                      | 398/500 [13:05<02:24,  1.41s/it]

[I 2026-05-19 11:50:37,792] Trial 395 finished with value: 0.9497067107976092 and parameters: {'solver': 'saga', 'C': 0.005107034225119341, 'l1_ratio': 0.8932617033069273, 'class_weight': None, 'fit_intercept': True, 'tol': 4.6359347175691097e-05, 'max_iter': 2480}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  80%|████████████████████████████████████████████████████████████████████████████████████████▌                      | 399/500 [13:11<04:35,  2.73s/it]

[I 2026-05-19 11:50:43,603] Trial 399 finished with value: 0.9497038832019433 and parameters: {'solver': 'saga', 'C': 0.004458762340101322, 'l1_ratio': 0.5251955620341515, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002224337661134533, 'max_iter': 3018}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:50:43,683] Trial 397 finished with value: 0.9497075023455952 and parameters: {'solver': 'saga', 'C': 0.004955523555404157, 'l1_ratio': 0.8892133419863288, 'class_weight': None, 'fit_intercept': True, 'tol': 9.68723808639629e-05, 'max_iter': 4659}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  80%|█████████████████████████████████████████████████████████████████████████████████████████                      | 401/500 [13:11<02:30,  1.52s/it]

[I 2026-05-19 11:50:43,831] Trial 400 finished with value: 0.9497110305342569 and parameters: {'solver': 'saga', 'C': 0.0019008489011621303, 'l1_ratio': 0.8132984196679603, 'class_weight': None, 'fit_intercept': True, 'tol': 9.908257177469042e-05, 'max_iter': 2516}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  80%|█████████████████████████████████████████████████████████████████████████████████████████▏                     | 402/500 [13:12<02:04,  1.27s/it]

[I 2026-05-19 11:50:44,323] Trial 402 finished with value: 0.9497160195054741 and parameters: {'solver': 'saga', 'C': 0.001893591351535012, 'l1_ratio': 0.8836242102465794, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00023855551985002717, 'max_iter': 3021}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  81%|█████████████████████████████████████████████████████████████████████████████████████████▍                     | 403/500 [13:13<02:06,  1.30s/it]

[I 2026-05-19 11:50:45,721] Trial 401 finished with value: 0.9497137565909763 and parameters: {'solver': 'saga', 'C': 0.0014492045933946732, 'l1_ratio': 0.8870290602848264, 'class_weight': None, 'fit_intercept': True, 'tol': 9.822396259453405e-05, 'max_iter': 2990}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  81%|█████████████████████████████████████████████████████████████████████████████████████████▋                     | 404/500 [13:15<02:30,  1.57s/it]

[I 2026-05-19 11:50:48,006] Trial 403 finished with value: 0.9497120392598248 and parameters: {'solver': 'saga', 'C': 0.001959868779203693, 'l1_ratio': 0.8244541025001781, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010166806031258791, 'max_iter': 3305}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  81%|█████████████████████████████████████████████████████████████████████████████████████████▉                     | 405/500 [13:16<02:08,  1.35s/it]

[I 2026-05-19 11:50:48,795] Trial 404 finished with value: 0.9497124423589154 and parameters: {'solver': 'saga', 'C': 0.0019534697667635517, 'l1_ratio': 0.829362912104066, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010249072741726439, 'max_iter': 2974}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  81%|██████████████████████████████████████████████████████████████████████████████████████████▎                    | 407/500 [13:19<01:58,  1.28s/it]

[I 2026-05-19 11:50:51,472] Trial 415 pruned.
[I 2026-05-19 11:50:51,627] Trial 405 finished with value: 0.9496756860404252 and parameters: {'solver': 'saga', 'C': 0.0018604443878288404, 'l1_ratio': 0.5258683491020385, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010078914572211906, 'max_iter': 2119}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  82%|██████████████████████████████████████████████████████████████████████████████████████████▌                    | 408/500 [13:21<02:27,  1.60s/it]

[I 2026-05-19 11:50:54,026] Trial 406 finished with value: 0.9497161932386661 and parameters: {'solver': 'saga', 'C': 0.0019409899598554, 'l1_ratio': 0.883927446648255, 'class_weight': None, 'fit_intercept': True, 'tol': 9.86550041099895e-05, 'max_iter': 2199}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  82%|██████████████████████████████████████████████████████████████████████████████████████████▊                    | 409/500 [13:22<01:48,  1.19s/it]

[I 2026-05-19 11:50:54,228] Trial 407 finished with value: 0.9497117443377041 and parameters: {'solver': 'saga', 'C': 0.0019718633545151017, 'l1_ratio': 0.8212671989519142, 'class_weight': None, 'fit_intercept': True, 'tol': 9.824920932758535e-05, 'max_iter': 3316}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  82%|███████████████████████████████████████████████████████████████████████████████████████████                    | 410/500 [13:25<02:35,  1.73s/it]

[I 2026-05-19 11:50:57,254] Trial 409 finished with value: 0.9496739658025788 and parameters: {'solver': 'saga', 'C': 0.001969223904775089, 'l1_ratio': 0.5054986508359465, 'class_weight': None, 'fit_intercept': True, 'tol': 9.800451360678132e-05, 'max_iter': 2127}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  82%|███████████████████████████████████████████████████████████████████████████████████████████▏                   | 411/500 [13:30<04:00,  2.70s/it]

[I 2026-05-19 11:51:02,229] Trial 414 finished with value: 0.9497085254009502 and parameters: {'solver': 'saga', 'C': 0.0017362976178605855, 'l1_ratio': 0.795198124705095, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003775610341938112, 'max_iter': 3112}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  82%|███████████████████████████████████████████████████████████████████████████████████████████▍                   | 412/500 [13:30<03:03,  2.08s/it]

[I 2026-05-19 11:51:02,869] Trial 411 finished with value: 0.9497111281435879 and parameters: {'solver': 'saga', 'C': 0.0020859456613279326, 'l1_ratio': 0.8127354593603214, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001263865670657583, 'max_iter': 3284}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  83%|███████████████████████████████████████████████████████████████████████████████████████████▋                   | 413/500 [13:31<02:32,  1.75s/it]

[I 2026-05-19 11:51:03,825] Trial 413 finished with value: 0.9497110516756567 and parameters: {'solver': 'saga', 'C': 0.0014622691910644594, 'l1_ratio': 0.8273616218180533, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011989902026921873, 'max_iter': 3035}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:51:03,879] Trial 412 finished with value: 0.9494997092476967 and parameters: {'solver': 'saga', 'C': 0.0020192842794969582, 'l1_ratio': 0.054106374826182635, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001232181019437835, 'max_iter': 3302}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  83%|████████████████████████████████████████████████████████████████████████████████████████████▏                  | 415/500 [13:31<01:24,  1.00it/s]

[I 2026-05-19 11:51:04,054] Trial 410 finished with value: 0.9497116958578641 and parameters: {'solver': 'saga', 'C': 0.0018504730410810763, 'l1_ratio': 0.8208215283277391, 'class_weight': None, 'fit_intercept': True, 'tol': 9.986002581224799e-05, 'max_iter': 2121}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  83%|████████████████████████████████████████████████████████████████████████████████████████████▎                  | 416/500 [13:35<02:18,  1.64s/it]

[I 2026-05-19 11:51:07,675] Trial 419 finished with value: 0.94971115757475 and parameters: {'solver': 'saga', 'C': 0.001331723837325469, 'l1_ratio': 0.847711688403413, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007778213837855173, 'max_iter': 2316}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  83%|████████████████████████████████████████████████████████████████████████████████████████████▌                  | 417/500 [13:36<01:58,  1.43s/it]

[I 2026-05-19 11:51:08,482] Trial 418 finished with value: 0.9497084733446662 and parameters: {'solver': 'saga', 'C': 0.0016134030255062029, 'l1_ratio': 0.7985658424544021, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003937212505186649, 'max_iter': 2191}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  84%|████████████████████████████████████████████████████████████████████████████████████████████▊                  | 418/500 [13:38<02:05,  1.52s/it]

[I 2026-05-19 11:51:10,273] Trial 417 finished with value: 0.9497128472546894 and parameters: {'solver': 'saga', 'C': 0.001375666544413915, 'l1_ratio': 0.8756734063791667, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012696584214283248, 'max_iter': 3302}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  84%|█████████████████████████████████████████████████████████████████████████████████████████████                  | 419/500 [13:41<02:48,  2.08s/it]

[I 2026-05-19 11:51:13,794] Trial 421 finished with value: 0.9497118593370212 and parameters: {'solver': 'saga', 'C': 0.0013754278224541836, 'l1_ratio': 0.849188399027184, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00037516412812676483, 'max_iter': 2206}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  84%|█████████████████████████████████████████████████████████████████████████████████████████████▏                 | 420/500 [13:43<02:40,  2.01s/it]

[I 2026-05-19 11:51:15,613] Trial 416 finished with value: 0.9493971110257512 and parameters: {'solver': 'saga', 'C': 15.911953721140444, 'l1_ratio': 0.8743628496667006, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8639625086877786e-05, 'max_iter': 3113}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  84%|█████████████████████████████████████████████████████████████████████████████████████████████▍                 | 421/500 [13:47<03:34,  2.72s/it]

[I 2026-05-19 11:51:20,079] Trial 423 finished with value: 0.9497103699234927 and parameters: {'solver': 'saga', 'C': 0.0012848852334169285, 'l1_ratio': 0.8440932988044113, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002189739619246045, 'max_iter': 4288}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  84%|█████████████████████████████████████████████████████████████████████████████████████████████▋                 | 422/500 [13:48<02:46,  2.13s/it]

[I 2026-05-19 11:51:20,795] Trial 426 finished with value: 0.9497108660717535 and parameters: {'solver': 'saga', 'C': 0.0012562648630022426, 'l1_ratio': 0.8551182053753608, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00022567858392906161, 'max_iter': 2273}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▉                 | 423/500 [13:48<02:01,  1.58s/it]

[I 2026-05-19 11:51:21,060] Trial 424 finished with value: 0.949711674236173 and parameters: {'solver': 'saga', 'C': 0.00126645182986831, 'l1_ratio': 0.875997899200878, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024471441900664886, 'max_iter': 4301}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  85%|██████████████████████████████████████████████████████████████████████████████████████████████▏                | 424/500 [13:49<01:38,  1.30s/it]

[I 2026-05-19 11:51:21,685] Trial 425 finished with value: 0.9497121817571547 and parameters: {'solver': 'saga', 'C': 0.001382993936429292, 'l1_ratio': 0.8582722595906772, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002299383991671939, 'max_iter': 2187}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  85%|██████████████████████████████████████████████████████████████████████████████████████████████▎                | 425/500 [13:51<01:57,  1.56s/it]

[I 2026-05-19 11:51:23,854] Trial 422 finished with value: 0.9497122004763204 and parameters: {'solver': 'saga', 'C': 0.0013183814013862938, 'l1_ratio': 0.874787986681168, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0721683237024147e-05, 'max_iter': 2166}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  85%|██████████████████████████████████████████████████████████████████████████████████████████████▌                | 426/500 [13:55<02:49,  2.29s/it]

[I 2026-05-19 11:51:27,857] Trial 429 finished with value: 0.9497119516440978 and parameters: {'solver': 'saga', 'C': 0.0036180645061699938, 'l1_ratio': 0.8553002569706202, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00022632959152768298, 'max_iter': 2208}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  85%|██████████████████████████████████████████████████████████████████████████████████████████████▊                | 427/500 [13:58<02:52,  2.36s/it]

[I 2026-05-19 11:51:30,408] Trial 420 finished with value: 0.9493968808470405 and parameters: {'solver': 'saga', 'C': 29.22802121648443, 'l1_ratio': 0.791249310155111, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003365186808560995, 'max_iter': 2183}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  86%|███████████████████████████████████████████████████████████████████████████████████████████████                | 428/500 [13:58<02:12,  1.84s/it]

[I 2026-05-19 11:51:31,031] Trial 427 finished with value: 0.9497124573932727 and parameters: {'solver': 'saga', 'C': 0.0034206534594583286, 'l1_ratio': 0.874536661169149, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0380063979561708e-05, 'max_iter': 2347}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  86%|███████████████████████████████████████████████████████████████████████████████████████████████▏               | 429/500 [14:00<02:01,  1.71s/it]

[I 2026-05-19 11:51:32,428] Trial 428 finished with value: 0.9497126125778405 and parameters: {'solver': 'saga', 'C': 0.0033638387018628756, 'l1_ratio': 0.8740277655793953, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7301971399319882e-05, 'max_iter': 2823}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  86%|███████████████████████████████████████████████████████████████████████████████████████████████▍               | 430/500 [14:00<01:35,  1.36s/it]

[I 2026-05-19 11:51:32,976] Trial 408 finished with value: 0.9494304743609424 and parameters: {'solver': 'saga', 'C': 0.2171261225093048, 'l1_ratio': 0.8798244142521194, 'class_weight': None, 'fit_intercept': True, 'tol': 9.791989231997856e-05, 'max_iter': 2129}. Best is trial 93 with value: 0.94971693243582.

[I 2026-05-19 11:51:37,042] Trial 430 finished with value: 0.9497118407164236 and parameters: {'solver': 'saga', 'C': 0.003633791868032118, 'l1_ratio': 0.8704047801989477, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2933032195428885e-05, 'max_iter': 2769}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  87%|████████████████████████████████████████████████████████████████████████████████████████████████▏              | 433/500 [14:05<01:16,  1.14s/it]

[I 2026-05-19 11:51:37,239] Trial 432 finished with value: 0.9497133114280094 and parameters: {'solver': 'saga', 'C': 0.0030836903849473045, 'l1_ratio': 0.9029330180879191, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001886120223458851, 'max_iter': 2388}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:51:37,370] Trial 433 finished with value: 0.9497120190260763 and parameters: {'solver': 'saga', 'C': 0.0033486229400742293, 'l1_ratio': 0.9079259659737762, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018927620914682691, 'max_iter': 2325}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  87%|████████████████████████████████████████████████████████████████████████████████████████████████▎              | 434/500 [14:07<01:42,  1.56s/it]

[I 2026-05-19 11:51:39,906] Trial 435 finished with value: 0.9497119993357505 and parameters: {'solver': 'saga', 'C': 0.0033990201951909793, 'l1_ratio': 0.9010582001760513, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018020556751951043, 'max_iter': 4528}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  87%|████████████████████████████████████████████████████████████████████████████████████████████████▌              | 435/500 [14:11<02:17,  2.11s/it]

[I 2026-05-19 11:51:43,296] Trial 436 finished with value: 0.9497107033609341 and parameters: {'solver': 'saga', 'C': 0.0036335113632713833, 'l1_ratio': 0.9130469614726425, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017732374584442085, 'max_iter': 2384}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  87%|████████████████████████████████████████████████████████████████████████████████████████████████▊              | 436/500 [14:16<03:17,  3.09s/it]

[I 2026-05-19 11:51:48,675] Trial 438 finished with value: 0.9497114016919094 and parameters: {'solver': 'saga', 'C': 0.0035418419696573587, 'l1_ratio': 0.9039666605238998, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001816484668058556, 'max_iter': 2800}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  87%|█████████████████████████████████████████████████████████████████████████████████████████████████              | 437/500 [14:17<02:32,  2.42s/it]

[I 2026-05-19 11:51:49,529] Trial 439 finished with value: 0.9496773703461674 and parameters: {'solver': 'saga', 'C': 0.003284839658117167, 'l1_ratio': 0.3383582986858792, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001783027268408807, 'max_iter': 3983}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████▏             | 438/500 [14:19<02:33,  2.48s/it]

[I 2026-05-19 11:51:52,163] Trial 441 finished with value: 0.9497124245619517 and parameters: {'solver': 'saga', 'C': 0.0032242520504077985, 'l1_ratio': 0.9121377844885787, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012942102603469773, 'max_iter': 4558}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████▋             | 440/500 [14:23<01:53,  1.89s/it]

[I 2026-05-19 11:51:55,138] Trial 444 finished with value: 0.9496594971838009 and parameters: {'solver': 'saga', 'C': 0.00019730524503409194, 'l1_ratio': 0.9056024618870642, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013113698557801155, 'max_iter': 4775}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:51:55,274] Trial 434 finished with value: 0.9493968427821858 and parameters: {'solver': 'saga', 'C': 34.00193089360209, 'l1_ratio': 0.9072992643596304, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018155563673154893, 'max_iter': 2790}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████▋             | 440/500 [14:23<01:53,  1.89s/it]

[I 2026-05-19 11:51:55,346] Trial 443 finished with value: 0.9497167756336662 and parameters: {'solver': 'saga', 'C': 0.00230077935949576, 'l1_ratio': 0.908086186119085, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018469496699696964, 'max_iter': 4744}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████             | 442/500 [14:24<01:11,  1.24s/it]

[I 2026-05-19 11:51:56,245] Trial 442 finished with value: 0.9496807569864101 and parameters: {'solver': 'saga', 'C': 0.0031182198917554583, 'l1_ratio': 0.4317307963532969, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019076819347674527, 'max_iter': 4738}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:51:56,343] Trial 440 finished with value: 0.9494515437266535 and parameters: {'solver': 'saga', 'C': 0.13265523305067534, 'l1_ratio': 0.7647433899598527, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017171685461681312, 'max_iter': 4773}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████▌            | 444/500 [14:25<00:57,  1.03s/it]

[I 2026-05-19 11:51:57,700] Trial 445 finished with value: 0.9497168681928068 and parameters: {'solver': 'saga', 'C': 0.0022426179686406435, 'l1_ratio': 0.9122405695811162, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012755734675381448, 'max_iter': 1956}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████▊            | 445/500 [14:28<01:18,  1.42s/it]

[I 2026-05-19 11:52:00,495] Trial 446 finished with value: 0.9497162739648297 and parameters: {'solver': 'saga', 'C': 0.0024199895136802984, 'l1_ratio': 0.9106702004964381, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013449332910490624, 'max_iter': 4725}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████            | 446/500 [14:32<01:49,  2.03s/it]

[I 2026-05-19 11:52:04,453] Trial 453 pruned.

Best trial: 93. Best value: 0.949717:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████▏           | 447/500 [14:34<01:48,  2.04s/it]

[I 2026-05-19 11:52:06,527] Trial 455 pruned.

Best trial: 93. Best value: 0.949717:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████▍           | 448/500 [14:36<01:53,  2.19s/it]

[I 2026-05-19 11:52:09,112] Trial 456 pruned.

Best trial: 93. Best value: 0.949717:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████▋           | 449/500 [14:37<01:26,  1.70s/it]

[I 2026-05-19 11:52:09,539] Trial 448 finished with value: 0.949705752204609 and parameters: {'solver': 'saga', 'C': 0.002077346374369231, 'l1_ratio': 0.7531214426763462, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013339776463377825, 'max_iter': 4782}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████▉           | 450/500 [14:37<01:04,  1.30s/it]

[I 2026-05-19 11:52:09,816] Trial 447 finished with value: 0.949716747818789 and parameters: {'solver': 'saga', 'C': 0.002301732022709319, 'l1_ratio': 0.9096067979705644, 'class_weight': None, 'fit_intercept': True, 'tol': 7.492168950643171e-05, 'max_iter': 3938}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:52:09,863] Trial 431 finished with value: 0.9494302222238229 and parameters: {'solver': 'saga', 'C': 0.21786866610532432, 'l1_ratio': 0.9077984810561017, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00023095862036585845, 'max_iter': 2340}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 452/500 [14:40<01:08,  1.42s/it]

[I 2026-05-19 11:52:12,975] Trial 452 finished with value: 0.9497155188632096 and parameters: {'solver': 'saga', 'C': 0.002223962595408369, 'l1_ratio': 0.931320404106656, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00028004161778681576, 'max_iter': 4785}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 453/500 [14:41<00:54,  1.17s/it]

[I 2026-05-19 11:52:13,339] Trial 449 finished with value: 0.9497166921863551 and parameters: {'solver': 'saga', 'C': 0.0023123918747497306, 'l1_ratio': 0.9102139591664534, 'class_weight': None, 'fit_intercept': True, 'tol': 7.244313700337385e-05, 'max_iter': 4998}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 454/500 [14:42<00:54,  1.19s/it]

[I 2026-05-19 11:52:14,579] Trial 451 finished with value: 0.9497153630298378 and parameters: {'solver': 'saga', 'C': 0.0022827719710427196, 'l1_ratio': 0.9324886531865298, 'class_weight': None, 'fit_intercept': True, 'tol': 7.369747916680981e-05, 'max_iter': 1414}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████          | 455/500 [14:42<00:42,  1.05it/s]

[I 2026-05-19 11:52:14,899] Trial 454 finished with value: 0.9497153026795452 and parameters: {'solver': 'saga', 'C': 0.002240565300376843, 'l1_ratio': 0.9334161156443492, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013242880055931678, 'max_iter': 4632}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 456/500 [14:43<00:36,  1.21it/s]

[I 2026-05-19 11:52:15,405] Trial 450 finished with value: 0.9497163969213747 and parameters: {'solver': 'saga', 'C': 0.0022961081722259343, 'l1_ratio': 0.8905913055353935, 'class_weight': None, 'fit_intercept': True, 'tol': 7.757744150113537e-05, 'max_iter': 4783}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 457/500 [14:51<02:01,  2.83s/it]

[I 2026-05-19 11:52:23,288] Trial 457 finished with value: 0.9497157770219736 and parameters: {'solver': 'saga', 'C': 0.002371600193841917, 'l1_ratio': 0.9241661103503862, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013442117705679397, 'max_iter': 4647}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋         | 458/500 [14:52<01:42,  2.44s/it]

[I 2026-05-19 11:52:24,770] Trial 458 finished with value: 0.9497162388337916 and parameters: {'solver': 'saga', 'C': 0.0022889262762223225, 'l1_ratio': 0.9214647726533796, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001359637032159559, 'max_iter': 1661}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 459/500 [14:55<01:40,  2.45s/it]

[I 2026-05-19 11:52:27,245] Trial 459 finished with value: 0.949715985849015 and parameters: {'solver': 'saga', 'C': 0.002309418114799283, 'l1_ratio': 0.8870392135155024, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013049695944215132, 'max_iter': 4683}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████         | 460/500 [14:57<01:32,  2.30s/it]

[I 2026-05-19 11:52:29,194] Trial 460 finished with value: 0.9497156832808435 and parameters: {'solver': 'saga', 'C': 0.0023981645855640516, 'l1_ratio': 0.8836037646018975, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015084870404547424, 'max_iter': 1696}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 461/500 [14:58<01:15,  1.93s/it]

[I 2026-05-19 11:52:30,249] Trial 461 finished with value: 0.9497162160260538 and parameters: {'solver': 'saga', 'C': 0.0022688106481884847, 'l1_ratio': 0.8870470362208688, 'class_weight': None, 'fit_intercept': True, 'tol': 7.607113515459932e-05, 'max_iter': 3856}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 463/500 [14:59<00:44,  1.20s/it]

[I 2026-05-19 11:52:31,148] Trial 462 finished with value: 0.9497151279351641 and parameters: {'solver': 'saga', 'C': 0.0026611492069608415, 'l1_ratio': 0.8863008837828308, 'class_weight': None, 'fit_intercept': True, 'tol': 8.094374177957525e-05, 'max_iter': 4399}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:52:31,323] Trial 437 finished with value: 0.9494239451062606 and parameters: {'solver': 'saga', 'C': 0.27019003143445963, 'l1_ratio': 0.9078279471591262, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001830093554575853, 'max_iter': 2839}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████        | 464/500 [15:01<00:54,  1.50s/it]

[I 2026-05-19 11:52:33,548] Trial 463 finished with value: 0.9496338854443641 and parameters: {'solver': 'saga', 'C': 0.02353717170670069, 'l1_ratio': 0.885174642742818, 'class_weight': None, 'fit_intercept': True, 'tol': 7.79215894329271e-05, 'max_iter': 3875}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 465/500 [15:02<00:49,  1.42s/it]

[I 2026-05-19 11:52:34,765] Trial 464 finished with value: 0.9496982900630991 and parameters: {'solver': 'saga', 'C': 0.0061017740954182375, 'l1_ratio': 0.9522144676195906, 'class_weight': None, 'fit_intercept': True, 'tol': 6.486103722022792e-05, 'max_iter': 3862}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 466/500 [15:03<00:40,  1.19s/it]

[I 2026-05-19 11:52:35,407] Trial 465 finished with value: 0.9497004939866907 and parameters: {'solver': 'saga', 'C': 0.007275054730822723, 'l1_ratio': 0.9557916463163489, 'class_weight': None, 'fit_intercept': True, 'tol': 7.510053009868547e-05, 'max_iter': 3608}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 468/500 [15:04<00:25,  1.24it/s]

[I 2026-05-19 11:52:36,208] Trial 467 finished with value: 0.9497062871158629 and parameters: {'solver': 'saga', 'C': 0.008161608325220133, 'l1_ratio': 0.8821516830953168, 'class_weight': None, 'fit_intercept': True, 'tol': 6.799265962174482e-05, 'max_iter': 3873}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:52:36,396] Trial 466 finished with value: 0.9497011394242675 and parameters: {'solver': 'saga', 'C': 0.006731121198617448, 'l1_ratio': 0.9508056392126976, 'class_weight': None, 'fit_intercept': True, 'tol': 7.962159747367374e-05, 'max_iter': 4992}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████       | 469/500 [15:11<01:28,  2.84s/it]

[I 2026-05-19 11:52:43,998] Trial 469 finished with value: 0.9497101499457592 and parameters: {'solver': 'saga', 'C': 0.004077196883778461, 'l1_ratio': 0.8877096362393554, 'class_weight': None, 'fit_intercept': True, 'tol': 6.854087356477381e-05, 'max_iter': 3609}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 470/500 [15:12<01:05,  2.20s/it]

[I 2026-05-19 11:52:44,695] Trial 468 finished with value: 0.9497010268185735 and parameters: {'solver': 'saga', 'C': 0.009175304160016325, 'l1_ratio': 0.8852562053759144, 'class_weight': None, 'fit_intercept': True, 'tol': 7.361198699521705e-05, 'max_iter': 3639}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 471/500 [15:15<01:07,  2.33s/it]

[I 2026-05-19 11:52:47,322] Trial 470 finished with value: 0.9496946255156523 and parameters: {'solver': 'saga', 'C': 0.010085949335143648, 'l1_ratio': 0.8865805514372714, 'class_weight': None, 'fit_intercept': True, 'tol': 6.636930172659881e-05, 'max_iter': 1458}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 472/500 [15:16<00:59,  2.12s/it]

[I 2026-05-19 11:52:48,945] Trial 471 finished with value: 0.9496983014930522 and parameters: {'solver': 'saga', 'C': 0.009596294087814036, 'l1_ratio': 0.8824201507788403, 'class_weight': None, 'fit_intercept': True, 'tol': 7.328270272526488e-05, 'max_iter': 1767}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████      | 473/500 [15:18<00:57,  2.11s/it]

[I 2026-05-19 11:52:51,050] Trial 472 finished with value: 0.9497114152685707 and parameters: {'solver': 'saga', 'C': 0.0012058953721141206, 'l1_ratio': 0.8835975999759922, 'class_weight': None, 'fit_intercept': True, 'tol': 6.363046528242733e-05, 'max_iter': 3756}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 474/500 [15:19<00:44,  1.73s/it]

[I 2026-05-19 11:52:51,883] Trial 473 finished with value: 0.9497107535737875 and parameters: {'solver': 'saga', 'C': 0.00704211469375117, 'l1_ratio': 0.8878377383620432, 'class_weight': None, 'fit_intercept': True, 'tol': 7.270977655669243e-05, 'max_iter': 1333}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 475/500 [15:20<00:36,  1.45s/it]

[I 2026-05-19 11:52:52,685] Trial 474 finished with value: 0.9497047340404962 and parameters: {'solver': 'saga', 'C': 0.008749974072737024, 'l1_ratio': 0.8515738507667743, 'class_weight': None, 'fit_intercept': True, 'tol': 6.625531929068219e-05, 'max_iter': 3864}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 476/500 [15:22<00:39,  1.64s/it]

[I 2026-05-19 11:52:54,761] Trial 475 finished with value: 0.9497132531091401 and parameters: {'solver': 'saga', 'C': 0.0064842462061116685, 'l1_ratio': 0.854611988030988, 'class_weight': None, 'fit_intercept': True, 'tol': 6.444398086438298e-05, 'max_iter': 1439}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 477/500 [15:22<00:28,  1.24s/it]

[I 2026-05-19 11:52:55,051] Trial 476 finished with value: 0.949702030511202 and parameters: {'solver': 'saga', 'C': 0.00916938739423061, 'l1_ratio': 0.8534560879748514, 'class_weight': None, 'fit_intercept': True, 'tol': 6.414737139643664e-05, 'max_iter': 3740}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████     | 478/500 [15:23<00:20,  1.07it/s]

[I 2026-05-19 11:52:55,288] Trial 477 finished with value: 0.949707806889319 and parameters: {'solver': 'saga', 'C': 0.0010240637228033072, 'l1_ratio': 0.8582348343125056, 'class_weight': None, 'fit_intercept': True, 'tol': 6.32041421244409e-05, 'max_iter': 1673}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 479/500 [15:24<00:19,  1.07it/s]

[I 2026-05-19 11:52:56,231] Trial 479 finished with value: 0.9497096252177674 and parameters: {'solver': 'saga', 'C': 0.0011928535797550678, 'l1_ratio': 0.8481766192301835, 'class_weight': None, 'fit_intercept': True, 'tol': 6.509111722403861e-05, 'max_iter': 4122}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 480/500 [15:24<00:15,  1.28it/s]

[I 2026-05-19 11:52:56,634] Trial 478 finished with value: 0.9497077172533966 and parameters: {'solver': 'saga', 'C': 0.001042718781303496, 'l1_ratio': 0.8505038233487142, 'class_weight': None, 'fit_intercept': True, 'tol': 8.240049155448677e-05, 'max_iter': 4139}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 481/500 [15:31<00:47,  2.51s/it]

[I 2026-05-19 11:53:03,185] Trial 480 finished with value: 0.9497092707637347 and parameters: {'solver': 'saga', 'C': 0.0011230614371857488, 'l1_ratio': 0.8595940145922591, 'class_weight': None, 'fit_intercept': True, 'tol': 8.730757603038878e-05, 'max_iter': 3730}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████    | 482/500 [15:31<00:34,  1.94s/it]

[I 2026-05-19 11:53:03,796] Trial 481 finished with value: 0.9497131620103385 and parameters: {'solver': 'saga', 'C': 0.0015282047897724532, 'l1_ratio': 0.8518542672178026, 'class_weight': None, 'fit_intercept': True, 'tol': 8.576722285203317e-05, 'max_iter': 3745}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 483/500 [15:34<00:37,  2.18s/it]

[I 2026-05-19 11:53:06,535] Trial 482 finished with value: 0.9496933897229212 and parameters: {'solver': 'saga', 'C': 0.0010834018848398584, 'l1_ratio': 0.6928405000796419, 'class_weight': None, 'fit_intercept': True, 'tol': 8.612830766582543e-05, 'max_iter': 3745}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 484/500 [15:38<00:44,  2.77s/it]

[I 2026-05-19 11:53:10,685] Trial 484 finished with value: 0.9497142559822158 and parameters: {'solver': 'saga', 'C': 0.0016278287213118536, 'l1_ratio': 0.8654943032737206, 'class_weight': None, 'fit_intercept': True, 'tol': 9.059018341577733e-05, 'max_iter': 3797}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 485/500 [15:39<00:32,  2.14s/it]

[I 2026-05-19 11:53:11,344] Trial 485 finished with value: 0.9497137585277073 and parameters: {'solver': 'saga', 'C': 0.0016122489853257773, 'l1_ratio': 0.8531871055629949, 'class_weight': None, 'fit_intercept': True, 'tol': 9.027065708394097e-05, 'max_iter': 1547}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 486/500 [15:39<00:24,  1.74s/it]

[I 2026-05-19 11:53:12,153] Trial 486 finished with value: 0.9491620967242248 and parameters: {'solver': 'saga', 'C': 0.001068429933910873, 'l1_ratio': 0.016164545773421857, 'class_weight': None, 'fit_intercept': True, 'tol': 9.124801385486131e-05, 'max_iter': 1640}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 487/500 [15:42<00:23,  1.84s/it]

[I 2026-05-19 11:53:14,224] Trial 488 finished with value: 0.9497153172694104 and parameters: {'solver': 'saga', 'C': 0.001565740899130264, 'l1_ratio': 0.9150479096063515, 'class_weight': None, 'fit_intercept': True, 'tol': 8.97489989038044e-05, 'max_iter': 3957}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 489/500 [15:42<00:11,  1.08s/it]

[I 2026-05-19 11:53:14,811] Trial 487 finished with value: 0.9497151018902118 and parameters: {'solver': 'saga', 'C': 0.0015593728360107134, 'l1_ratio': 0.9094142983127907, 'class_weight': None, 'fit_intercept': True, 'tol': 9.030100726491743e-05, 'max_iter': 4001}. Best is trial 93 with value: 0.94971693243582.
[I 2026-05-19 11:53:14,991] Trial 489 finished with value: 0.9497154107999629 and parameters: {'solver': 'saga', 'C': 0.0016309475589853216, 'l1_ratio': 0.9068160623438767, 'class_weight': None, 'fit_intercept': True, 'tol': 9.841724106928203e-05, 'max_iter': 4106}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 490/500 [15:43<00:08,  1.21it/s]

[I 2026-05-19 11:53:15,242] Trial 490 finished with value: 0.9497153733902504 and parameters: {'solver': 'saga', 'C': 0.001593121284100337, 'l1_ratio': 0.9134117305839503, 'class_weight': None, 'fit_intercept': True, 'tol': 9.312712696188075e-05, 'max_iter': 1558}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 491/500 [15:44<00:09,  1.02s/it]

[I 2026-05-19 11:53:16,696] Trial 491 finished with value: 0.9497150498398602 and parameters: {'solver': 'saga', 'C': 0.0015080736748877164, 'l1_ratio': 0.9178951895368622, 'class_weight': None, 'fit_intercept': True, 'tol': 9.099086979544156e-05, 'max_iter': 4930}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 492/500 [15:46<00:09,  1.22s/it]

[I 2026-05-19 11:53:18,373] Trial 483 finished with value: 0.9497127574502822 and parameters: {'solver': 'saga', 'C': 0.001457458313179109, 'l1_ratio': 0.8562906736992413, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0851685278631798e-06, 'max_iter': 4118}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 493/500 [15:49<00:12,  1.74s/it]

[I 2026-05-19 11:53:21,350] Trial 493 finished with value: 0.9494191781189464 and parameters: {'solver': 'saga', 'C': 0.0017311810173241174, 'l1_ratio': 0.00810241274326956, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011274500300841927, 'max_iter': 3990}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 494/500 [15:49<00:08,  1.38s/it]

[I 2026-05-19 11:53:21,888] Trial 492 finished with value: 0.9497154423660088 and parameters: {'solver': 'saga', 'C': 0.0016243695896569932, 'l1_ratio': 0.9136522581013594, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011068437463982104, 'max_iter': 4924}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 495/500 [15:51<00:07,  1.40s/it]

[I 2026-05-19 11:53:23,345] Trial 494 finished with value: 0.9497155751054056 and parameters: {'solver': 'saga', 'C': 0.0016735016892789512, 'l1_ratio': 0.9120385866055187, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001175142572865618, 'max_iter': 1601}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 496/500 [15:54<00:08,  2.03s/it]

[I 2026-05-19 11:53:26,823] Trial 495 finished with value: 0.9497086641377901 and parameters: {'solver': 'saga', 'C': 0.0040381817694368095, 'l1_ratio': 0.9138759796175588, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001107533663304094, 'max_iter': 1543}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 497/500 [15:55<00:05,  1.70s/it]

[I 2026-05-19 11:53:27,776] Trial 497 finished with value: 0.9497120079684848 and parameters: {'solver': 'saga', 'C': 0.0033112105832856244, 'l1_ratio': 0.9124499124363306, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011521287458885457, 'max_iter': 3487}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 498/500 [15:56<00:02,  1.39s/it]

[I 2026-05-19 11:53:28,438] Trial 498 finished with value: 0.9497127015867639 and parameters: {'solver': 'saga', 'C': 0.0031551653601360656, 'l1_ratio': 0.9114924197926617, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011112079250789059, 'max_iter': 1821}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 499/500 [15:57<00:01,  1.20s/it]

[I 2026-05-19 11:53:29,186] Trial 496 finished with value: 0.9497127811322603 and parameters: {'solver': 'saga', 'C': 0.0031325468395663613, 'l1_ratio': 0.9110802428832693, 'class_weight': None, 'fit_intercept': True, 'tol': 3.5517986947942004e-05, 'max_iter': 1596}. Best is trial 93 with value: 0.94971693243582.

Best trial: 93. Best value: 0.949717: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [15:58<00:00,  1.92s/it]

[I 2026-05-19 11:53:30,380] Trial 499 finished with value: 0.9497131510453405 and parameters: {'solver': 'saga', 'C': 0.0030465541891385064, 'l1_ratio': 0.9139785509303224, 'class_weight': None, 'fit_intercept': True, 'tol': 3.598636390590139e-05, 'max_iter': 4935}. Best is trial 93 with value: 0.94971693243582.
Best trial score:
0.94971693243582

Best params:
{'solver': 'saga', 'C': 0.002193203638990036, 'l1_ratio': 0.89839712471031, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001350258081959178, 'max_iter': 4918}

In [7]:
stacking_lg = LogisticRegression(**study.best_params).fit(X_train, y_train.PitNextLap)

# Submission

In [8]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [9]:
submission['PitNextLap'] = stacking_lg.predict_proba(X_test)[:, 1]

In [10]:
submission.to_csv('../data/submission/submission.csv', index=False)

In [11]:
X_train.columns.tolist()

['lgbm_proba',
 'cat_proba',
 'xgb_proba',
 'hist_proba',
 'lg_proba',
 'knn_proba',
 'ridge_proba',
 'voting_lgbm_cat_xgb_hist_proba',
 'voting_lg_ridge_proba',
 'stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba']