# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

# Loading Dataset

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_stacking2.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking2.parquet')

In [4]:
X_train.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,voting_lgbm_cat_xgb_hist_proba,stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.868510,0.826590
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.772514,0.801335
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.717012,0.782757
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,0.005494,0.502476
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,0.482416,0.703165

In [6]:
X_test.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,voting_lgbm_cat_xgb_hist_proba,stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,0.019849,0.509303
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,0.012173,0.505573
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,0.010304,0.504827
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.444558,0.696136
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.939648,0.852833

# Machine Learning

In [7]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "max_iter": trial.suggest_int("max_iter", 10, 100),
        "learning_rate": trial.suggest_float("learning_rate", 0.001, 0.05, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 3),
        "max_leaf_nodes": trial.suggest_int("max_leaf_nodes", 2, 8),
        "l2_regularization": trial.suggest_float("l2_regularization", 0.1, 100.0, log=True),
        "min_samples_leaf": trial.suggest_int("min_samples_leaf", 50, 500),
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = HistGradientBoostingClassifier(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)


study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-18 15:55:01,051] A new study created in memory with name: no-name-094d8629-a8cb-4ad3-8149-0fae11d0eebb
Best trial: 10. Best value: 0.91625:   0%|          | 1/500 [00:07<1:05:29,  7.88s/it]

[I 2026-05-18 15:55:08,896] Trial 10 finished with value: 0.9162497731563265 and parameters: {'max_iter': 16, 'learning_rate': 0.023267473164318105, 'max_depth': 1, 'max_leaf_nodes': 8, 'l2_regularization': 34.294753403338376, 'min_samples_leaf': 367}. Best is trial 10 with value: 0.9162497731563265.

Best trial: 2. Best value: 0.934534:   0%|          | 2/500 [00:09<36:18,  4.38s/it]

[I 2026-05-18 15:55:10,817] Trial 2 finished with value: 0.9345344306232238 and parameters: {'max_iter': 13, 'learning_rate': 0.002156777686842487, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.6086362382567709, 'min_samples_leaf': 53}. Best is trial 2 with value: 0.9345344306232238.

Best trial: 0. Best value: 0.939494:   1%|          | 3/500 [00:10<21:55,  2.65s/it]

[I 2026-05-18 15:55:11,403] Trial 0 finished with value: 0.9394936572445027 and parameters: {'max_iter': 20, 'learning_rate': 0.011777367498933596, 'max_depth': 2, 'max_leaf_nodes': 8, 'l2_regularization': 33.59239814817942, 'min_samples_leaf': 384}. Best is trial 0 with value: 0.9394936572445027.

Best trial: 0. Best value: 0.939494:   1%|          | 4/500 [00:10<14:41,  1.78s/it]

[I 2026-05-18 15:55:11,857] Trial 5 finished with value: 0.8968309387558697 and parameters: {'max_iter': 30, 'learning_rate': 0.0046798495739177855, 'max_depth': 1, 'max_leaf_nodes': 6, 'l2_regularization': 76.52153126409397, 'min_samples_leaf': 358}. Best is trial 0 with value: 0.9394936572445027.

Best trial: 3. Best value: 0.941391:   1%|          | 5/500 [00:11<10:03,  1.22s/it]

[I 2026-05-18 15:55:12,096] Trial 3 finished with value: 0.9413908813857352 and parameters: {'max_iter': 17, 'learning_rate': 0.014040461399912014, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 16.214544355286954, 'min_samples_leaf': 394}. Best is trial 3 with value: 0.9413908813857352.

Best trial: 8. Best value: 0.943379:   1%|          | 6/500 [00:11<07:29,  1.10it/s]

[I 2026-05-18 15:55:12,399] Trial 8 finished with value: 0.9433786574653888 and parameters: {'max_iter': 24, 'learning_rate': 0.02185577397164707, 'max_depth': 2, 'max_leaf_nodes': 5, 'l2_regularization': 11.139903225606977, 'min_samples_leaf': 147}. Best is trial 8 with value: 0.9433786574653888.

Best trial: 8. Best value: 0.943379:   1%|▏         | 7/500 [00:12<07:03,  1.16it/s]

[I 2026-05-18 15:55:13,161] Trial 11 pruned.

Best trial: 8. Best value: 0.943379:   2%|▏         | 8/500 [00:13<08:54,  1.09s/it]

[I 2026-05-18 15:55:14,672] Trial 1 pruned.

Best trial: 8. Best value: 0.943379:   2%|▏         | 9/500 [00:14<09:16,  1.13s/it]

[I 2026-05-18 15:55:15,962] Trial 16 pruned.

Best trial: 8. Best value: 0.943379:   2%|▏         | 10/500 [00:15<08:02,  1.02it/s]

[I 2026-05-18 15:55:16,625] Trial 17 pruned.

Best trial: 8. Best value: 0.943379:   2%|▏         | 11/500 [00:16<07:54,  1.03it/s]

[I 2026-05-18 15:55:17,561] Trial 4 finished with value: 0.937549536085216 and parameters: {'max_iter': 29, 'learning_rate': 0.001049647096302806, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.5181992107011618, 'min_samples_leaf': 469}. Best is trial 8 with value: 0.9433786574653888.

Best trial: 8. Best value: 0.943379:   2%|▏         | 12/500 [00:16<06:09,  1.32it/s]

[I 2026-05-18 15:55:17,791] Trial 12 finished with value: 0.9379314808567172 and parameters: {'max_iter': 28, 'learning_rate': 0.04289372138560998, 'max_depth': 1, 'max_leaf_nodes': 7, 'l2_regularization': 5.59690502287776, 'min_samples_leaf': 115}. Best is trial 8 with value: 0.9433786574653888.

Best trial: 8. Best value: 0.943379:   3%|▎         | 13/500 [00:17<06:12,  1.31it/s]

[I 2026-05-18 15:55:18,613] Trial 15 pruned.

Best trial: 9. Best value: 0.94893:   3%|▎         | 14/500 [00:28<30:26,  3.76s/it]

[I 2026-05-18 15:55:29,230] Trial 9 finished with value: 0.9489301395399213 and parameters: {'max_iter': 89, 'learning_rate': 0.024207664484452534, 'max_depth': 2, 'max_leaf_nodes': 6, 'l2_regularization': 26.918028322127615, 'min_samples_leaf': 112}. Best is trial 9 with value: 0.9489301395399213.

Best trial: 9. Best value: 0.94893:   3%|▎         | 15/500 [00:29<23:03,  2.85s/it]

[I 2026-05-18 15:55:30,050] Trial 21 finished with value: 0.9474282288747812 and parameters: {'max_iter': 45, 'learning_rate': 0.04984643070237049, 'max_depth': 2, 'max_leaf_nodes': 3, 'l2_regularization': 6.540742500358971, 'min_samples_leaf': 172}. Best is trial 9 with value: 0.9489301395399213.

Best trial: 9. Best value: 0.94893:   3%|▎         | 16/500 [00:29<17:35,  2.18s/it]

[I 2026-05-18 15:55:30,662] Trial 7 finished with value: 0.948200377781664 and parameters: {'max_iter': 95, 'learning_rate': 0.019398138164084058, 'max_depth': 2, 'max_leaf_nodes': 4, 'l2_regularization': 4.226852301169703, 'min_samples_leaf': 238}. Best is trial 9 with value: 0.9489301395399213.

Best trial: 9. Best value: 0.94893:   3%|▎         | 17/500 [00:30<14:09,  1.76s/it]

[I 2026-05-18 15:55:31,438] Trial 22 finished with value: 0.9471671246504318 and parameters: {'max_iter': 47, 'learning_rate': 0.04370791524652987, 'max_depth': 2, 'max_leaf_nodes': 3, 'l2_regularization': 7.15728752436915, 'min_samples_leaf': 178}. Best is trial 9 with value: 0.9489301395399213.

Best trial: 18. Best value: 0.949457:   4%|▍         | 19/500 [00:31<08:02,  1.00s/it]

[I 2026-05-18 15:55:31,872] Trial 23 pruned.
[I 2026-05-18 15:55:32,034] Trial 18 finished with value: 0.9494571240370974 and parameters: {'max_iter': 40, 'learning_rate': 0.04542651086095354, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 21.658132909135443, 'min_samples_leaf': 150}. Best is trial 18 with value: 0.9494571240370974.

Best trial: 18. Best value: 0.949457:   4%|▍         | 20/500 [00:31<06:47,  1.18it/s]

[I 2026-05-18 15:55:32,535] Trial 6 finished with value: 0.9465396234283088 and parameters: {'max_iter': 68, 'learning_rate': 0.0025408466202254485, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.9478705568588017, 'min_samples_leaf': 383}. Best is trial 18 with value: 0.9494571240370974.

[I 2026-05-18 15:55:34,871] Trial 14 pruned.

Best trial: 18. Best value: 0.949457:   4%|▍         | 22/500 [00:34<07:44,  1.03it/s]

[I 2026-05-18 15:55:35,073] Trial 13 finished with value: 0.9443721290699294 and parameters: {'max_iter': 84, 'learning_rate': 0.007662201243390325, 'max_depth': 2, 'max_leaf_nodes': 8, 'l2_regularization': 1.989080869535811, 'min_samples_leaf': 471}. Best is trial 18 with value: 0.9494571240370974.

Best trial: 18. Best value: 0.949457:   5%|▍         | 23/500 [00:34<06:57,  1.14it/s]

[I 2026-05-18 15:55:35,744] Trial 20 pruned.

Best trial: 18. Best value: 0.949457:   5%|▍         | 24/500 [00:38<13:01,  1.64s/it]

[I 2026-05-18 15:55:39,111] Trial 24 finished with value: 0.94830486236289 and parameters: {'max_iter': 78, 'learning_rate': 0.03343240934969481, 'max_depth': 3, 'max_leaf_nodes': 3, 'l2_regularization': 0.12532718582153976, 'min_samples_leaf': 209}. Best is trial 18 with value: 0.9494571240370974.

Best trial: 18. Best value: 0.949457:   5%|▌         | 25/500 [00:44<24:27,  3.09s/it]

[I 2026-05-18 15:55:45,635] Trial 19 finished with value: 0.9457239561185391 and parameters: {'max_iter': 76, 'learning_rate': 0.0013695568056407475, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 63.47703139324289, 'min_samples_leaf': 425}. Best is trial 18 with value: 0.9494571240370974.

Best trial: 18. Best value: 0.949457:   5%|▌         | 26/500 [00:50<30:03,  3.81s/it]

[I 2026-05-18 15:55:51,105] Trial 31 finished with value: 0.9484279558312233 and parameters: {'max_iter': 68, 'learning_rate': 0.03077374969847074, 'max_depth': 2, 'max_leaf_nodes': 7, 'l2_regularization': 83.85050771006817, 'min_samples_leaf': 287}. Best is trial 18 with value: 0.9494571240370974.

Best trial: 26. Best value: 0.949551:   5%|▌         | 27/500 [00:50<22:09,  2.81s/it]

[I 2026-05-18 15:55:51,605] Trial 26 finished with value: 0.9495507575510889 and parameters: {'max_iter': 85, 'learning_rate': 0.04704915236519753, 'max_depth': 2, 'max_leaf_nodes': 3, 'l2_regularization': 0.15958172494282463, 'min_samples_leaf': 195}. Best is trial 26 with value: 0.9495507575510889.

Best trial: 25. Best value: 0.949617:   6%|▌         | 28/500 [00:51<17:22,  2.21s/it]

[I 2026-05-18 15:55:52,405] Trial 25 finished with value: 0.9496168019727872 and parameters: {'max_iter': 91, 'learning_rate': 0.04770585580513428, 'max_depth': 2, 'max_leaf_nodes': 3, 'l2_regularization': 0.1020535368560719, 'min_samples_leaf': 180}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 25. Best value: 0.949617:   6%|▌         | 29/500 [00:54<18:27,  2.35s/it]

[I 2026-05-18 15:55:55,083] Trial 27 finished with value: 0.9481641102939496 and parameters: {'max_iter': 98, 'learning_rate': 0.025629602004625, 'max_depth': 2, 'max_leaf_nodes': 3, 'l2_regularization': 0.1661012107882939, 'min_samples_leaf': 267}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 25. Best value: 0.949617:   6%|▌         | 30/500 [00:56<18:37,  2.38s/it]

[I 2026-05-18 15:55:57,528] Trial 28 finished with value: 0.9491289803261926 and parameters: {'max_iter': 99, 'learning_rate': 0.024660876476992256, 'max_depth': 2, 'max_leaf_nodes': 4, 'l2_regularization': 2.453021392556633, 'min_samples_leaf': 284}. Best is trial 25 with value: 0.9496168019727872.
[I 2026-05-18 15:55:57,548] Trial 29 finished with value: 0.94925870543106 and parameters: {'max_iter': 98, 'learning_rate': 0.02567012263502981, 'max_depth': 2, 'max_leaf_nodes': 4, 'l2_regularization': 0.12340956803454567, 'min_samples_leaf': 261}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 25. Best value: 0.949617:   6%|▋         | 32/500 [00:56<10:53,  1.40s/it]

[I 2026-05-18 15:55:57,832] Trial 30 finished with value: 0.9494944976529329 and parameters: {'max_iter': 67, 'learning_rate': 0.03091060400482448, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.11252335786092495, 'min_samples_leaf': 298}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 25. Best value: 0.949617:   7%|▋         | 33/500 [00:58<11:40,  1.50s/it]

[I 2026-05-18 15:55:59,835] Trial 32 finished with value: 0.9492145863641547 and parameters: {'max_iter': 95, 'learning_rate': 0.027281817804747945, 'max_depth': 2, 'max_leaf_nodes': 4, 'l2_regularization': 24.352308412732366, 'min_samples_leaf': 278}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 25. Best value: 0.949617:   7%|▋         | 34/500 [01:00<11:34,  1.49s/it]

[I 2026-05-18 15:56:01,300] Trial 33 finished with value: 0.9493168529793115 and parameters: {'max_iter': 97, 'learning_rate': 0.027614546040368594, 'max_depth': 2, 'max_leaf_nodes': 4, 'l2_regularization': 21.97547047474209, 'min_samples_leaf': 291}. Best is trial 25 with value: 0.9496168019727872.
[I 2026-05-18 15:56:01,492] Trial 34 finished with value: 0.9491834924338323 and parameters: {'max_iter': 98, 'learning_rate': 0.02840067964843997, 'max_depth': 2, 'max_leaf_nodes': 4, 'l2_regularization': 99.131743958033, 'min_samples_leaf': 282}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 25. Best value: 0.949617:   7%|▋         | 36/500 [01:02<10:25,  1.35s/it]

[I 2026-05-18 15:56:03,384] Trial 40 pruned.

Best trial: 25. Best value: 0.949617:   7%|▋         | 37/500 [01:04<12:24,  1.61s/it]

[I 2026-05-18 15:56:05,640] Trial 35 finished with value: 0.9495049308351817 and parameters: {'max_iter': 67, 'learning_rate': 0.030920606705477787, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.1956905201628266, 'min_samples_leaf': 282}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 25. Best value: 0.949617:   8%|▊         | 38/500 [01:07<14:54,  1.94s/it]

[I 2026-05-18 15:56:08,387] Trial 44 pruned.

Best trial: 25. Best value: 0.949617:   8%|▊         | 39/500 [01:08<12:24,  1.61s/it]

[I 2026-05-18 15:56:09,228] Trial 37 finished with value: 0.9481683881053364 and parameters: {'max_iter': 61, 'learning_rate': 0.03024882451062371, 'max_depth': 2, 'max_leaf_nodes': 7, 'l2_regularization': 29.859700190242034, 'min_samples_leaf': 289}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 25. Best value: 0.949617:   8%|▊         | 40/500 [01:08<10:01,  1.31s/it]

[I 2026-05-18 15:56:09,780] Trial 43 pruned.

Best trial: 25. Best value: 0.949617:   8%|▊         | 42/500 [01:09<05:48,  1.31it/s]

[I 2026-05-18 15:56:10,137] Trial 45 pruned.
[I 2026-05-18 15:56:10,278] Trial 46 pruned.

Best trial: 25. Best value: 0.949617:   9%|▊         | 43/500 [01:11<09:41,  1.27s/it]

[I 2026-05-18 15:56:12,750] Trial 39 finished with value: 0.9475254118768162 and parameters: {'max_iter': 99, 'learning_rate': 0.03171104444287342, 'max_depth': 3, 'max_leaf_nodes': 2, 'l2_regularization': 0.10279142976250613, 'min_samples_leaf': 273}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 25. Best value: 0.949617:   9%|▉         | 44/500 [01:15<14:47,  1.95s/it]

[I 2026-05-18 15:56:16,284] Trial 41 finished with value: 0.9476399914101747 and parameters: {'max_iter': 89, 'learning_rate': 0.0354843375724367, 'max_depth': 2, 'max_leaf_nodes': 2, 'l2_regularization': 0.26791387023724494, 'min_samples_leaf': 179}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 25. Best value: 0.949617:   9%|▉         | 45/500 [01:15<11:30,  1.52s/it]

[I 2026-05-18 15:56:16,795] Trial 42 finished with value: 0.94783341193565 and parameters: {'max_iter': 92, 'learning_rate': 0.03488563317558256, 'max_depth': 2, 'max_leaf_nodes': 2, 'l2_regularization': 0.24776837225517342, 'min_samples_leaf': 321}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 25. Best value: 0.949617:   9%|▉         | 47/500 [01:17<09:08,  1.21s/it]

[I 2026-05-18 15:56:18,858] Trial 53 pruned.
[I 2026-05-18 15:56:18,962] Trial 38 finished with value: 0.9495339942344355 and parameters: {'max_iter': 100, 'learning_rate': 0.030852208022914798, 'max_depth': 2, 'max_leaf_nodes': 6, 'l2_regularization': 22.62497999220928, 'min_samples_leaf': 282}. Best is trial 25 with value: 0.9496168019727872.

Best trial: 36. Best value: 0.94965:  10%|▉         | 48/500 [01:22<16:29,  2.19s/it]

[I 2026-05-18 15:56:23,440] Trial 36 finished with value: 0.9496498573612469 and parameters: {'max_iter': 99, 'learning_rate': 0.03216065165247843, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.11663666407394038, 'min_samples_leaf': 299}. Best is trial 36 with value: 0.9496498573612469.

Best trial: 36. Best value: 0.94965:  10%|▉         | 49/500 [01:23<13:08,  1.75s/it]

[I 2026-05-18 15:56:24,168] Trial 51 pruned.

Best trial: 36. Best value: 0.94965:  10%|█         | 50/500 [01:25<14:08,  1.89s/it]

[I 2026-05-18 15:56:26,375] Trial 47 finished with value: 0.949519089349262 and parameters: {'max_iter': 60, 'learning_rate': 0.03903350606943108, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.2548473263771339, 'min_samples_leaf': 59}. Best is trial 36 with value: 0.9496498573612469.

Best trial: 36. Best value: 0.94965:  10%|█         | 52/500 [01:27<10:56,  1.47s/it]

[I 2026-05-18 15:56:28,693] Trial 58 pruned.
[I 2026-05-18 15:56:28,872] Trial 48 finished with value: 0.9483230041255396 and parameters: {'max_iter': 62, 'learning_rate': 0.01797225131621274, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.2891103187575933, 'min_samples_leaf': 337}. Best is trial 36 with value: 0.9496498573612469.

Best trial: 36. Best value: 0.94965:  11%|█         | 53/500 [01:32<17:42,  2.38s/it]

[I 2026-05-18 15:56:33,382] Trial 59 pruned.

Best trial: 36. Best value: 0.94965:  11%|█         | 54/500 [01:32<13:19,  1.79s/it]

[I 2026-05-18 15:56:33,807] Trial 60 pruned.

Best trial: 36. Best value: 0.94965:  11%|█         | 55/500 [01:33<11:33,  1.56s/it]

[I 2026-05-18 15:56:34,822] Trial 49 finished with value: 0.9478275360647166 and parameters: {'max_iter': 74, 'learning_rate': 0.017754098172855587, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.3389095962831346, 'min_samples_leaf': 322}. Best is trial 36 with value: 0.9496498573612469.

Best trial: 36. Best value: 0.94965:  11%|█         | 56/500 [01:35<11:03,  1.49s/it]

[I 2026-05-18 15:56:36,163] Trial 52 finished with value: 0.9490040350686595 and parameters: {'max_iter': 73, 'learning_rate': 0.01969422380691104, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.3999734392472838, 'min_samples_leaf': 84}. Best is trial 36 with value: 0.9496498573612469.

Best trial: 36. Best value: 0.94965:  11%|█▏        | 57/500 [01:35<08:18,  1.13s/it]

[I 2026-05-18 15:56:36,412] Trial 61 pruned.

Best trial: 54. Best value: 0.949657:  12%|█▏        | 58/500 [01:37<11:19,  1.54s/it]

[I 2026-05-18 15:56:38,925] Trial 54 finished with value: 0.9496572780132787 and parameters: {'max_iter': 75, 'learning_rate': 0.04898656793393028, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.42174211703159314, 'min_samples_leaf': 244}. Best is trial 54 with value: 0.9496572780132787.

Best trial: 54. Best value: 0.949657:  12%|█▏        | 59/500 [01:38<09:52,  1.34s/it]

[I 2026-05-18 15:56:39,821] Trial 50 finished with value: 0.9484139827049877 and parameters: {'max_iter': 90, 'learning_rate': 0.018813950773857113, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.3443654701305407, 'min_samples_leaf': 67}. Best is trial 54 with value: 0.9496572780132787.

Best trial: 54. Best value: 0.949657:  12%|█▏        | 60/500 [01:41<13:07,  1.79s/it]

[I 2026-05-18 15:56:42,648] Trial 55 finished with value: 0.9481876919021826 and parameters: {'max_iter': 73, 'learning_rate': 0.01728191244495979, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.4402090455233093, 'min_samples_leaf': 240}. Best is trial 54 with value: 0.9496572780132787.

Best trial: 54. Best value: 0.949657:  12%|█▏        | 61/500 [01:42<11:19,  1.55s/it]

[I 2026-05-18 15:56:43,642] Trial 56 finished with value: 0.9491268800470744 and parameters: {'max_iter': 75, 'learning_rate': 0.01996902381351514, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.4050528016622155, 'min_samples_leaf': 94}. Best is trial 54 with value: 0.9496572780132787.

Best trial: 54. Best value: 0.949657:  12%|█▏        | 62/500 [01:43<09:55,  1.36s/it]

[I 2026-05-18 15:56:44,559] Trial 57 finished with value: 0.949654811195064 and parameters: {'max_iter': 73, 'learning_rate': 0.04644563370881008, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.4216419959894611, 'min_samples_leaf': 154}. Best is trial 54 with value: 0.9496572780132787.

Best trial: 62. Best value: 0.949698:  13%|█▎        | 63/500 [01:58<39:13,  5.39s/it]

[I 2026-05-18 15:56:59,329] Trial 62 finished with value: 0.9496979664369123 and parameters: {'max_iter': 92, 'learning_rate': 0.04695160788911216, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.18020068058400918, 'min_samples_leaf': 94}. Best is trial 62 with value: 0.9496979664369123.

Best trial: 62. Best value: 0.949698:  13%|█▎        | 64/500 [01:58<28:15,  3.89s/it]

[I 2026-05-18 15:56:59,732] Trial 69 finished with value: 0.9496590653809681 and parameters: {'max_iter': 81, 'learning_rate': 0.04921437321312719, 'max_depth': 2, 'max_leaf_nodes': 5, 'l2_regularization': 0.16587208553245134, 'min_samples_leaf': 196}. Best is trial 62 with value: 0.9496979664369123.

Best trial: 62. Best value: 0.949698:  13%|█▎        | 66/500 [01:59<14:51,  2.05s/it]

[I 2026-05-18 15:57:00,191] Trial 70 finished with value: 0.9496246007627359 and parameters: {'max_iter': 78, 'learning_rate': 0.049322281524730824, 'max_depth': 2, 'max_leaf_nodes': 5, 'l2_regularization': 0.15987775802731874, 'min_samples_leaf': 103}. Best is trial 62 with value: 0.9496979664369123.
[I 2026-05-18 15:57:00,368] Trial 63 finished with value: 0.9496856404524754 and parameters: {'max_iter': 93, 'learning_rate': 0.04573988182851893, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.17246799925478795, 'min_samples_leaf': 74}. Best is trial 62 with value: 0.9496979664369123.

Best trial: 62. Best value: 0.949698:  13%|█▎        | 67/500 [02:00<12:37,  1.75s/it]

[I 2026-05-18 15:57:01,399] Trial 68 finished with value: 0.9496343740945251 and parameters: {'max_iter': 80, 'learning_rate': 0.04988988077732519, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.17261790258389362, 'min_samples_leaf': 357}. Best is trial 62 with value: 0.9496979664369123.

Best trial: 62. Best value: 0.949698:  14%|█▎        | 68/500 [02:02<14:03,  1.95s/it]

[I 2026-05-18 15:57:03,820] Trial 67 finished with value: 0.9496879958130453 and parameters: {'max_iter': 92, 'learning_rate': 0.04922591940936971, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.16189406173288287, 'min_samples_leaf': 357}. Best is trial 62 with value: 0.9496979664369123.

Best trial: 64. Best value: 0.94971:  14%|█▍        | 69/500 [02:03<11:23,  1.59s/it]

[I 2026-05-18 15:57:04,559] Trial 64 finished with value: 0.9497097098347099 and parameters: {'max_iter': 93, 'learning_rate': 0.047668579766598176, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.17091991611541424, 'min_samples_leaf': 92}. Best is trial 64 with value: 0.9497097098347099.

Best trial: 65. Best value: 0.94971:  14%|█▍        | 71/500 [02:03<06:16,  1.14it/s]

[I 2026-05-18 15:57:04,840] Trial 65 finished with value: 0.9497102649268083 and parameters: {'max_iter': 93, 'learning_rate': 0.04896659896690711, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.17499663420203682, 'min_samples_leaf': 90}. Best is trial 65 with value: 0.9497102649268083.
[I 2026-05-18 15:57:04,930] Trial 73 finished with value: 0.9496254773757515 and parameters: {'max_iter': 79, 'learning_rate': 0.04653976069405995, 'max_depth': 2, 'max_leaf_nodes': 5, 'l2_regularization': 0.15103448277842452, 'min_samples_leaf': 194}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  15%|█▍        | 73/500 [02:05<05:33,  1.28it/s]

[I 2026-05-18 15:57:06,443] Trial 66 finished with value: 0.9496974939666284 and parameters: {'max_iter': 93, 'learning_rate': 0.04883814844783879, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.6094150454984342, 'min_samples_leaf': 82}. Best is trial 65 with value: 0.9497102649268083.
[I 2026-05-18 15:57:06,604] Trial 71 finished with value: 0.94966278791582 and parameters: {'max_iter': 94, 'learning_rate': 0.04943979409559311, 'max_depth': 2, 'max_leaf_nodes': 5, 'l2_regularization': 0.17052550773943537, 'min_samples_leaf': 350}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  15%|█▍        | 74/500 [02:08<09:23,  1.32s/it]

[I 2026-05-18 15:57:09,176] Trial 72 finished with value: 0.9496642165832447 and parameters: {'max_iter': 81, 'learning_rate': 0.0476945806363512, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.17343407252479157, 'min_samples_leaf': 347}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  15%|█▌        | 75/500 [02:19<30:54,  4.36s/it]

[I 2026-05-18 15:57:20,627] Trial 75 finished with value: 0.9496274768593501 and parameters: {'max_iter': 80, 'learning_rate': 0.04762342572456061, 'max_depth': 2, 'max_leaf_nodes': 5, 'l2_regularization': 0.15273410462882464, 'min_samples_leaf': 153}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  15%|█▌        | 76/500 [02:22<27:18,  3.86s/it]

[I 2026-05-18 15:57:23,343] Trial 74 finished with value: 0.9496516154510403 and parameters: {'max_iter': 94, 'learning_rate': 0.0476375772611031, 'max_depth': 2, 'max_leaf_nodes': 5, 'l2_regularization': 0.16497273027599657, 'min_samples_leaf': 156}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  15%|█▌        | 77/500 [02:24<23:21,  3.31s/it]

[I 2026-05-18 15:57:25,370] Trial 76 finished with value: 0.9496563470777296 and parameters: {'max_iter': 80, 'learning_rate': 0.04713995525726036, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.7178304957749012, 'min_samples_leaf': 149}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  16%|█▌        | 78/500 [02:24<17:04,  2.43s/it]

[I 2026-05-18 15:57:25,730] Trial 77 finished with value: 0.94961831922095 and parameters: {'max_iter': 80, 'learning_rate': 0.04296554186500959, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.16358914562695814, 'min_samples_leaf': 136}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  16%|█▌        | 79/500 [02:25<13:33,  1.93s/it]

[I 2026-05-18 15:57:26,499] Trial 78 finished with value: 0.9496276180027058 and parameters: {'max_iter': 80, 'learning_rate': 0.04282708239430866, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.8235696843511168, 'min_samples_leaf': 131}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  16%|█▌        | 80/500 [02:31<21:54,  3.13s/it]

[I 2026-05-18 15:57:32,418] Trial 80 finished with value: 0.949653366086884 and parameters: {'max_iter': 93, 'learning_rate': 0.04315860075047759, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.7187987850199332, 'min_samples_leaf': 131}. Best is trial 65 with value: 0.9497102649268083.
[I 2026-05-18 15:57:32,500] Trial 79 finished with value: 0.949651920957184 and parameters: {'max_iter': 94, 'learning_rate': 0.04288811921699337, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.20120185547512268, 'min_samples_leaf': 137}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  16%|█▋        | 82/500 [02:32<13:26,  1.93s/it]

[I 2026-05-18 15:57:33,483] Trial 81 finished with value: 0.9496525370220483 and parameters: {'max_iter': 94, 'learning_rate': 0.04168876044082766, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.8050783993329499, 'min_samples_leaf': 127}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  17%|█▋        | 83/500 [02:32<10:40,  1.53s/it]

[I 2026-05-18 15:57:33,767] Trial 82 finished with value: 0.9496675826502896 and parameters: {'max_iter': 94, 'learning_rate': 0.04325632285586558, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.2002685671964428, 'min_samples_leaf': 152}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  17%|█▋        | 84/500 [02:33<09:37,  1.39s/it]

[I 2026-05-18 15:57:34,795] Trial 83 finished with value: 0.9496494460311021 and parameters: {'max_iter': 93, 'learning_rate': 0.04228442093295438, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.19815652856345975, 'min_samples_leaf': 108}. Best is trial 65 with value: 0.9497102649268083.
[I 2026-05-18 15:57:34,867] Trial 84 finished with value: 0.9496624964501358 and parameters: {'max_iter': 94, 'learning_rate': 0.042063485715571586, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.20360834404593794, 'min_samples_leaf': 126}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  17%|█▋        | 86/500 [02:36<09:23,  1.36s/it]

[I 2026-05-18 15:57:37,447] Trial 85 finished with value: 0.9496624403440668 and parameters: {'max_iter': 94, 'learning_rate': 0.0420591301256053, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.6397400534777733, 'min_samples_leaf': 123}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  17%|█▋        | 87/500 [02:43<19:19,  2.81s/it]

[I 2026-05-18 15:57:44,985] Trial 90 pruned.

Best trial: 65. Best value: 0.94971:  18%|█▊        | 88/500 [02:47<20:40,  3.01s/it]

[I 2026-05-18 15:57:48,606] Trial 86 finished with value: 0.9496550474435311 and parameters: {'max_iter': 93, 'learning_rate': 0.04138858950360891, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.7165902294644836, 'min_samples_leaf': 126}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  18%|█▊        | 89/500 [02:49<18:29,  2.70s/it]

[I 2026-05-18 15:57:50,428] Trial 92 pruned.

Best trial: 65. Best value: 0.94971:  18%|█▊        | 90/500 [02:50<14:57,  2.19s/it]

[I 2026-05-18 15:57:51,272] Trial 94 pruned.

Best trial: 65. Best value: 0.94971:  18%|█▊        | 91/500 [02:51<12:33,  1.84s/it]

[I 2026-05-18 15:57:52,230] Trial 95 pruned.

Best trial: 65. Best value: 0.94971:  18%|█▊        | 92/500 [02:53<12:33,  1.85s/it]

[I 2026-05-18 15:57:54,088] Trial 87 finished with value: 0.9496565356397404 and parameters: {'max_iter': 93, 'learning_rate': 0.041611119254207074, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.6092367552876602, 'min_samples_leaf': 121}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  19%|█▊        | 93/500 [02:55<12:59,  1.92s/it]

[I 2026-05-18 15:57:56,165] Trial 88 finished with value: 0.949664928798643 and parameters: {'max_iter': 93, 'learning_rate': 0.04000043233176575, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.19355385721009633, 'min_samples_leaf': 131}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  19%|█▉        | 94/500 [02:55<10:14,  1.51s/it]

[I 2026-05-18 15:57:56,683] Trial 89 finished with value: 0.9496606139519562 and parameters: {'max_iter': 93, 'learning_rate': 0.04103890757515201, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.20216140507165817, 'min_samples_leaf': 420}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  19%|█▉        | 95/500 [03:00<16:37,  2.46s/it]

[I 2026-05-18 15:58:01,435] Trial 91 finished with value: 0.9496656831203723 and parameters: {'max_iter': 88, 'learning_rate': 0.04140389301630144, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.21807705006120232, 'min_samples_leaf': 444}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  19%|█▉        | 96/500 [03:01<13:08,  1.95s/it]

[I 2026-05-18 15:58:02,167] Trial 93 finished with value: 0.9496573129868869 and parameters: {'max_iter': 87, 'learning_rate': 0.040254646146953836, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.19868064084238088, 'min_samples_leaf': 412}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  19%|█▉        | 97/500 [03:03<14:01,  2.09s/it]

[I 2026-05-18 15:58:04,587] Trial 96 finished with value: 0.9496535692450958 and parameters: {'max_iter': 89, 'learning_rate': 0.03873369286552224, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.13412905791940832, 'min_samples_leaf': 411}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  20%|█▉        | 98/500 [03:05<13:46,  2.06s/it]

[I 2026-05-18 15:58:06,570] Trial 97 finished with value: 0.9496446106225702 and parameters: {'max_iter': 88, 'learning_rate': 0.03815057648530506, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.12653810644929572, 'min_samples_leaf': 391}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  20%|█▉        | 99/500 [03:06<12:26,  1.86s/it]

[I 2026-05-18 15:58:07,957] Trial 100 pruned.

Best trial: 65. Best value: 0.94971:  20%|██        | 100/500 [03:12<19:42,  2.96s/it]

[I 2026-05-18 15:58:13,505] Trial 98 finished with value: 0.9496406518253622 and parameters: {'max_iter': 89, 'learning_rate': 0.03824268425798737, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.1277685417484621, 'min_samples_leaf': 451}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  20%|██        | 101/500 [03:17<23:06,  3.47s/it]

[I 2026-05-18 15:58:18,175] Trial 99 finished with value: 0.9496343954006955 and parameters: {'max_iter': 89, 'learning_rate': 0.037734872088753896, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.23589556475683388, 'min_samples_leaf': 351}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  20%|██        | 102/500 [03:19<20:36,  3.11s/it]

[I 2026-05-18 15:58:20,429] Trial 101 finished with value: 0.9496207455519976 and parameters: {'max_iter': 88, 'learning_rate': 0.0374166441753322, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 1.233702318546032, 'min_samples_leaf': 351}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  21%|██        | 103/500 [03:22<21:25,  3.24s/it]

[I 2026-05-18 15:58:23,979] Trial 102 finished with value: 0.949655114373447 and parameters: {'max_iter': 96, 'learning_rate': 0.038510980814155646, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.21993685425605758, 'min_samples_leaf': 93}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  21%|██        | 104/500 [03:25<19:44,  2.99s/it]

[I 2026-05-18 15:58:26,395] Trial 103 finished with value: 0.94967372640377 and parameters: {'max_iter': 97, 'learning_rate': 0.037773288460049875, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 1.24972735663244, 'min_samples_leaf': 93}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  21%|██        | 105/500 [03:27<17:05,  2.60s/it]

[I 2026-05-18 15:58:28,066] Trial 104 finished with value: 0.9496615443405375 and parameters: {'max_iter': 97, 'learning_rate': 0.03764212140784026, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.1379503590453732, 'min_samples_leaf': 89}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  21%|██        | 106/500 [03:28<13:51,  2.11s/it]

[I 2026-05-18 15:58:29,043] Trial 105 finished with value: 0.9496671429549455 and parameters: {'max_iter': 97, 'learning_rate': 0.03743108164920028, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.13196111248737535, 'min_samples_leaf': 94}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  21%|██▏       | 107/500 [03:29<13:30,  2.06s/it]

[I 2026-05-18 15:58:30,989] Trial 106 finished with value: 0.9496431666206945 and parameters: {'max_iter': 90, 'learning_rate': 0.03691525918182495, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 1.2470484097051484, 'min_samples_leaf': 447}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  22%|██▏       | 108/500 [03:33<16:03,  2.46s/it]

[I 2026-05-18 15:58:34,373] Trial 107 finished with value: 0.9496555791195973 and parameters: {'max_iter': 97, 'learning_rate': 0.03711897442624025, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 1.2797536047328988, 'min_samples_leaf': 87}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  22%|██▏       | 109/500 [03:34<13:02,  2.00s/it]

[I 2026-05-18 15:58:35,308] Trial 110 finished with value: 0.9495369911168062 and parameters: {'max_iter': 83, 'learning_rate': 0.033341327071708456, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.3327271789281097, 'min_samples_leaf': 97}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  22%|██▏       | 110/500 [03:35<11:59,  1.84s/it]

[I 2026-05-18 15:58:36,787] Trial 108 finished with value: 0.9496452606092107 and parameters: {'max_iter': 97, 'learning_rate': 0.03396124245496666, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.3481553593351195, 'min_samples_leaf': 500}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  22%|██▏       | 111/500 [03:37<11:13,  1.73s/it]

[I 2026-05-18 15:58:38,253] Trial 109 finished with value: 0.9496297230935703 and parameters: {'max_iter': 97, 'learning_rate': 0.03321181140419761, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.3317554916003192, 'min_samples_leaf': 93}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  22%|██▏       | 112/500 [03:45<23:08,  3.58s/it]

[I 2026-05-18 15:58:46,154] Trial 111 finished with value: 0.94963556476327 and parameters: {'max_iter': 100, 'learning_rate': 0.03376746440811449, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 3.8745616607632862, 'min_samples_leaf': 91}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  23%|██▎       | 113/500 [03:45<17:04,  2.65s/it]

[I 2026-05-18 15:58:46,615] Trial 113 finished with value: 0.9490675490854737 and parameters: {'max_iter': 97, 'learning_rate': 0.032485526082033256, 'max_depth': 3, 'max_leaf_nodes': 4, 'l2_regularization': 0.23775685543790898, 'min_samples_leaf': 91}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  23%|██▎       | 114/500 [03:48<17:07,  2.66s/it]

[I 2026-05-18 15:58:49,320] Trial 112 finished with value: 0.9496365292799107 and parameters: {'max_iter': 97, 'learning_rate': 0.034774687214017524, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.3186932943643345, 'min_samples_leaf': 370}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  23%|██▎       | 115/500 [03:49<14:38,  2.28s/it]

[I 2026-05-18 15:58:50,692] Trial 114 finished with value: 0.9492464224377282 and parameters: {'max_iter': 97, 'learning_rate': 0.0355110057432569, 'max_depth': 3, 'max_leaf_nodes': 4, 'l2_regularization': 0.28847396290676874, 'min_samples_leaf': 498}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  23%|██▎       | 116/500 [03:54<19:23,  3.03s/it]

[I 2026-05-18 15:58:55,486] Trial 116 finished with value: 0.9491952774845591 and parameters: {'max_iter': 83, 'learning_rate': 0.028241205623055366, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 2.967730643239693, 'min_samples_leaf': 499}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  23%|██▎       | 117/500 [03:56<16:49,  2.64s/it]

[I 2026-05-18 15:58:57,115] Trial 115 finished with value: 0.9496313205249821 and parameters: {'max_iter': 97, 'learning_rate': 0.03407564930516714, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 1.4142383054360605, 'min_samples_leaf': 496}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  24%|██▎       | 118/500 [03:57<14:33,  2.29s/it]

[I 2026-05-18 15:58:58,678] Trial 117 finished with value: 0.949616329172378 and parameters: {'max_iter': 91, 'learning_rate': 0.03434279519353418, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 3.000332200171559, 'min_samples_leaf': 76}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  24%|██▍       | 119/500 [04:01<18:27,  2.91s/it]

[I 2026-05-18 15:59:03,014] Trial 118 finished with value: 0.9496305799631276 and parameters: {'max_iter': 100, 'learning_rate': 0.03385760389206729, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 1.646956366343901, 'min_samples_leaf': 498}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  24%|██▍       | 120/500 [04:02<14:02,  2.22s/it]

[I 2026-05-18 15:59:03,639] Trial 119 finished with value: 0.9496012564543026 and parameters: {'max_iter': 91, 'learning_rate': 0.03466383410130613, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 2.7407076379425486, 'min_samples_leaf': 68}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  24%|██▍       | 121/500 [04:03<11:44,  1.86s/it]

[I 2026-05-18 15:59:04,656] Trial 120 finished with value: 0.9494828578853085 and parameters: {'max_iter': 91, 'learning_rate': 0.029461936764967417, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 3.7439831132640546, 'min_samples_leaf': 73}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  24%|██▍       | 122/500 [04:05<11:21,  1.80s/it]

[I 2026-05-18 15:59:06,316] Trial 121 finished with value: 0.9493848697522358 and parameters: {'max_iter': 91, 'learning_rate': 0.028232952480297665, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 1.7139220396389547, 'min_samples_leaf': 76}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  25%|██▍       | 123/500 [04:08<14:49,  2.36s/it]

[I 2026-05-18 15:59:09,988] Trial 122 finished with value: 0.9495505561340407 and parameters: {'max_iter': 100, 'learning_rate': 0.02878455339968169, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.11088452050522819, 'min_samples_leaf': 66}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  25%|██▍       | 124/500 [04:12<16:33,  2.64s/it]

[I 2026-05-18 15:59:13,284] Trial 124 finished with value: 0.949132063736187 and parameters: {'max_iter': 83, 'learning_rate': 0.026629617641490314, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.5254414420637195, 'min_samples_leaf': 77}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  25%|██▌       | 125/500 [04:17<20:33,  3.29s/it]

[I 2026-05-18 15:59:18,075] Trial 123 finished with value: 0.9495204104465174 and parameters: {'max_iter': 100, 'learning_rate': 0.026300099500658845, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.11132241531384426, 'min_samples_leaf': 75}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  25%|██▌       | 126/500 [04:18<16:12,  2.60s/it]

[I 2026-05-18 15:59:19,080] Trial 125 finished with value: 0.9494629430608674 and parameters: {'max_iter': 92, 'learning_rate': 0.02824313546817721, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 9.553670033782215, 'min_samples_leaf': 74}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  25%|██▌       | 127/500 [04:19<14:14,  2.29s/it]

[I 2026-05-18 15:59:20,650] Trial 126 finished with value: 0.94952279242317 and parameters: {'max_iter': 91, 'learning_rate': 0.02898150498648134, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.5066819288063805, 'min_samples_leaf': 68}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  26%|██▌       | 128/500 [04:22<15:53,  2.56s/it]

[I 2026-05-18 15:59:23,830] Trial 128 finished with value: 0.9496748177444376 and parameters: {'max_iter': 91, 'learning_rate': 0.044489204122805534, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.49960877709696827, 'min_samples_leaf': 72}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  26%|██▌       | 129/500 [04:24<14:28,  2.34s/it]

[I 2026-05-18 15:59:25,672] Trial 127 finished with value: 0.9496897678232067 and parameters: {'max_iter': 91, 'learning_rate': 0.045471169400730184, 'max_depth': 3, 'max_leaf_nodes': 6, 'l2_regularization': 0.5012437732792915, 'min_samples_leaf': 65}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  26%|██▌       | 130/500 [04:25<10:57,  1.78s/it]

[I 2026-05-18 15:59:26,131] Trial 129 finished with value: 0.9496565301620308 and parameters: {'max_iter': 91, 'learning_rate': 0.04461934367246064, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.48803749236981564, 'min_samples_leaf': 111}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  26%|██▌       | 131/500 [04:27<12:59,  2.11s/it]

[I 2026-05-18 15:59:29,024] Trial 130 finished with value: 0.9496423921410866 and parameters: {'max_iter': 86, 'learning_rate': 0.04574721309718111, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.5263099383016794, 'min_samples_leaf': 72}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  26%|██▋       | 132/500 [04:28<10:48,  1.76s/it]

[I 2026-05-18 15:59:29,972] Trial 131 finished with value: 0.9491383595544045 and parameters: {'max_iter': 86, 'learning_rate': 0.026368972978900895, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.5171529971941967, 'min_samples_leaf': 114}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  27%|██▋       | 133/500 [04:32<13:27,  2.20s/it]

[I 2026-05-18 15:59:33,199] Trial 132 finished with value: 0.9496757353898115 and parameters: {'max_iter': 95, 'learning_rate': 0.04516139448331211, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.1146275067679896, 'min_samples_leaf': 106}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  27%|██▋       | 134/500 [04:33<12:34,  2.06s/it]

[I 2026-05-18 15:59:34,929] Trial 133 finished with value: 0.9496611485691947 and parameters: {'max_iter': 95, 'learning_rate': 0.04515848119761477, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.1839438221082628, 'min_samples_leaf': 107}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  27%|██▋       | 135/500 [04:34<10:09,  1.67s/it]

[I 2026-05-18 15:59:35,695] Trial 134 finished with value: 0.9496566699398814 and parameters: {'max_iter': 86, 'learning_rate': 0.04639001515483856, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.4942558222452829, 'min_samples_leaf': 111}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  27%|██▋       | 136/500 [04:40<17:20,  2.86s/it]

[I 2026-05-18 15:59:41,325] Trial 135 finished with value: 0.949670766174141 and parameters: {'max_iter': 95, 'learning_rate': 0.045251969014131074, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.18299341195091615, 'min_samples_leaf': 114}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  27%|██▋       | 137/500 [04:45<20:46,  3.43s/it]

[I 2026-05-18 15:59:46,087] Trial 136 finished with value: 0.9496372461203848 and parameters: {'max_iter': 92, 'learning_rate': 0.045516636009947105, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.17993737438634547, 'min_samples_leaf': 112}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  28%|██▊       | 138/500 [04:46<17:26,  2.89s/it]

[I 2026-05-18 15:59:47,721] Trial 137 finished with value: 0.9496741206700305 and parameters: {'max_iter': 95, 'learning_rate': 0.04555738018416505, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.18170344341198477, 'min_samples_leaf': 112}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  28%|██▊       | 139/500 [04:48<15:48,  2.63s/it]

[I 2026-05-18 15:59:49,731] Trial 138 finished with value: 0.9496698558206674 and parameters: {'max_iter': 95, 'learning_rate': 0.04530351676530606, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.17773366877192553, 'min_samples_leaf': 112}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  28%|██▊       | 140/500 [04:49<12:14,  2.04s/it]

[I 2026-05-18 15:59:50,398] Trial 139 finished with value: 0.9496531520101609 and parameters: {'max_iter': 86, 'learning_rate': 0.04482974226558115, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.17768063046069807, 'min_samples_leaf': 108}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  28%|██▊       | 141/500 [04:50<09:57,  1.66s/it]

[I 2026-05-18 15:59:51,181] Trial 147 pruned.

Best trial: 65. Best value: 0.94971:  28%|██▊       | 142/500 [04:51<08:38,  1.45s/it]

[I 2026-05-18 15:59:52,126] Trial 140 finished with value: 0.9496618176496607 and parameters: {'max_iter': 86, 'learning_rate': 0.04522722701562531, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.14610134043021866, 'min_samples_leaf': 109}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  29%|██▊       | 143/500 [04:53<10:42,  1.80s/it]

[I 2026-05-18 15:59:54,740] Trial 146 pruned.

Best trial: 65. Best value: 0.94971:  29%|██▉       | 144/500 [04:56<12:51,  2.17s/it]

[I 2026-05-18 15:59:57,776] Trial 142 finished with value: 0.9496716755530656 and parameters: {'max_iter': 95, 'learning_rate': 0.04578518823984648, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.17907459145309582, 'min_samples_leaf': 54}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  29%|██▉       | 145/500 [04:57<10:28,  1.77s/it]

[I 2026-05-18 15:59:58,619] Trial 143 finished with value: 0.9496742653170219 and parameters: {'max_iter': 95, 'learning_rate': 0.04519932461723653, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.9617215149900417, 'min_samples_leaf': 103}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  29%|██▉       | 146/500 [04:57<07:42,  1.31s/it]

[I 2026-05-18 15:59:58,842] Trial 141 finished with value: 0.9496980716833827 and parameters: {'max_iter': 95, 'learning_rate': 0.04444505070835788, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.9117237065530273, 'min_samples_leaf': 52}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 65. Best value: 0.94971:  29%|██▉       | 147/500 [05:01<11:39,  1.98s/it]

[I 2026-05-18 16:00:02,397] Trial 148 pruned.

Best trial: 65. Best value: 0.94971:  30%|██▉       | 148/500 [05:02<10:50,  1.85s/it]

[I 2026-05-18 16:00:03,930] Trial 155 pruned.

Best trial: 65. Best value: 0.94971:  30%|██▉       | 149/500 [05:04<11:04,  1.89s/it]

[I 2026-05-18 16:00:05,937] Trial 150 pruned.

Best trial: 65. Best value: 0.94971:  30%|███       | 151/500 [05:05<06:25,  1.10s/it]

[I 2026-05-18 16:00:06,539] Trial 158 pruned.
[I 2026-05-18 16:00:06,699] Trial 144 finished with value: 0.9497070030415472 and parameters: {'max_iter': 96, 'learning_rate': 0.04563048075560233, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.9466709139164046, 'min_samples_leaf': 103}. Best is trial 65 with value: 0.9497102649268083.

Best trial: 145. Best value: 0.949725:  30%|███       | 152/500 [05:07<07:57,  1.37s/it]

[I 2026-05-18 16:00:08,701] Trial 145 finished with value: 0.9497246446755614 and parameters: {'max_iter': 96, 'learning_rate': 0.04548101210948218, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.2691509658666732, 'min_samples_leaf': 56}. Best is trial 145 with value: 0.9497246446755614.

Best trial: 145. Best value: 0.949725:  31%|███       | 153/500 [05:12<13:34,  2.35s/it]

[I 2026-05-18 16:00:13,312] Trial 154 pruned.

Best trial: 145. Best value: 0.949725:  31%|███       | 154/500 [05:15<14:18,  2.48s/it]

[I 2026-05-18 16:00:16,102] Trial 149 finished with value: 0.9496933253344159 and parameters: {'max_iter': 95, 'learning_rate': 0.04967274502534246, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.1513912799221005, 'min_samples_leaf': 104}. Best is trial 145 with value: 0.9497246446755614.

Best trial: 145. Best value: 0.949725:  31%|███       | 155/500 [05:16<11:56,  2.08s/it]

[I 2026-05-18 16:00:17,242] Trial 151 finished with value: 0.9496698058170547 and parameters: {'max_iter': 95, 'learning_rate': 0.04999531567870321, 'max_depth': 3, 'max_leaf_nodes': 4, 'l2_regularization': 0.9035020051068665, 'min_samples_leaf': 53}. Best is trial 145 with value: 0.9497246446755614.

Best trial: 145. Best value: 0.949725:  31%|███       | 156/500 [05:18<12:56,  2.26s/it]

[I 2026-05-18 16:00:19,921] Trial 152 finished with value: 0.9497030607430842 and parameters: {'max_iter': 95, 'learning_rate': 0.04889146841808176, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 1.0145502990665254, 'min_samples_leaf': 55}. Best is trial 145 with value: 0.9497246446755614.

Best trial: 145. Best value: 0.949725:  31%|███▏      | 157/500 [05:20<11:24,  1.99s/it]

[I 2026-05-18 16:00:21,315] Trial 153 finished with value: 0.9497041045404778 and parameters: {'max_iter': 96, 'learning_rate': 0.04996909072778015, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.1502585152168566, 'min_samples_leaf': 55}. Best is trial 145 with value: 0.9497246446755614.

Best trial: 145. Best value: 0.949725:  32%|███▏      | 158/500 [05:21<10:03,  1.77s/it]

[I 2026-05-18 16:00:22,540] Trial 159 pruned.

Best trial: 145. Best value: 0.949725:  32%|███▏      | 159/500 [05:26<15:11,  2.67s/it]

[I 2026-05-18 16:00:27,326] Trial 156 finished with value: 0.9497072526443204 and parameters: {'max_iter': 96, 'learning_rate': 0.049278344767663386, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.25513872100830876, 'min_samples_leaf': 58}. Best is trial 145 with value: 0.9497246446755614.

Best trial: 145. Best value: 0.949725:  32%|███▏      | 160/500 [05:31<18:59,  3.35s/it]

[I 2026-05-18 16:00:32,267] Trial 164 pruned.

Best trial: 157. Best value: 0.949728:  32%|███▏      | 161/500 [05:32<15:13,  2.69s/it]

[I 2026-05-18 16:00:33,423] Trial 157 finished with value: 0.9497282174651112 and parameters: {'max_iter': 99, 'learning_rate': 0.049800452248380575, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9622746308720239, 'min_samples_leaf': 59}. Best is trial 157 with value: 0.9497282174651112.

Best trial: 157. Best value: 0.949728:  32%|███▏      | 162/500 [05:33<12:02,  2.14s/it]

[I 2026-05-18 16:00:34,255] Trial 160 finished with value: 0.9496938093433874 and parameters: {'max_iter': 98, 'learning_rate': 0.048451893263755715, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 2.093986584682625, 'min_samples_leaf': 58}. Best is trial 157 with value: 0.9497282174651112.

Best trial: 157. Best value: 0.949728:  33%|███▎      | 164/500 [05:34<07:20,  1.31s/it]

[I 2026-05-18 16:00:35,339] Trial 169 finished with value: 0.9489130504294014 and parameters: {'max_iter': 34, 'learning_rate': 0.040650135811067904, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.6527767852986441, 'min_samples_leaf': 82}. Best is trial 157 with value: 0.9497282174651112.
[I 2026-05-18 16:00:35,459] Trial 161 finished with value: 0.9496641682598087 and parameters: {'max_iter': 99, 'learning_rate': 0.04048674087052228, 'max_depth': 3, 'max_leaf_nodes': 5, 'l2_regularization': 0.669860083378299, 'min_samples_leaf': 61}. Best is trial 157 with value: 0.9497282174651112.

Best trial: 157. Best value: 0.949728:  33%|███▎      | 165/500 [05:38<11:45,  2.11s/it]

[I 2026-05-18 16:00:39,427] Trial 162 finished with value: 0.9496846814452237 and parameters: {'max_iter': 99, 'learning_rate': 0.039741510683383316, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.9574975378933142, 'min_samples_leaf': 82}. Best is trial 157 with value: 0.9497282174651112.

Best trial: 157. Best value: 0.949728:  33%|███▎      | 166/500 [05:39<09:15,  1.66s/it]

[I 2026-05-18 16:00:40,044] Trial 168 pruned.

Best trial: 157. Best value: 0.949728:  33%|███▎      | 167/500 [05:39<07:49,  1.41s/it]

[I 2026-05-18 16:00:40,858] Trial 171 pruned.

Best trial: 163. Best value: 0.949741:  34%|███▎      | 168/500 [05:40<06:37,  1.20s/it]

[I 2026-05-18 16:00:41,582] Trial 163 finished with value: 0.9497414494911413 and parameters: {'max_iter': 98, 'learning_rate': 0.04938222999664412, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.9772720146033429, 'min_samples_leaf': 82}. Best is trial 163 with value: 0.9497414494911413.

Best trial: 163. Best value: 0.949741:  34%|███▍      | 169/500 [05:47<16:43,  3.03s/it]

[I 2026-05-18 16:00:48,892] Trial 165 finished with value: 0.949736489751753 and parameters: {'max_iter': 99, 'learning_rate': 0.04965102059610043, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.6337813567648003, 'min_samples_leaf': 83}. Best is trial 163 with value: 0.9497414494911413.

Best trial: 163. Best value: 0.949741:  34%|███▍      | 170/500 [05:48<13:23,  2.43s/it]

[I 2026-05-18 16:00:49,924] Trial 166 finished with value: 0.9496906940859645 and parameters: {'max_iter': 98, 'learning_rate': 0.04053372915351488, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.6812950030374588, 'min_samples_leaf': 84}. Best is trial 163 with value: 0.9497414494911413.

Best trial: 163. Best value: 0.949741:  34%|███▍      | 171/500 [05:51<13:03,  2.38s/it]

[I 2026-05-18 16:00:52,189] Trial 167 finished with value: 0.9496743807012006 and parameters: {'max_iter': 99, 'learning_rate': 0.04072479078061357, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.6760060474873073, 'min_samples_leaf': 83}. Best is trial 163 with value: 0.9497414494911413.

Best trial: 163. Best value: 0.949741:  34%|███▍      | 172/500 [05:57<20:09,  3.69s/it]

[I 2026-05-18 16:00:58,927] Trial 170 finished with value: 0.9497173230081326 and parameters: {'max_iter': 99, 'learning_rate': 0.0497021905342585, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.6321791421348664, 'min_samples_leaf': 84}. Best is trial 163 with value: 0.9497414494911413.

Best trial: 163. Best value: 0.949741:  35%|███▍      | 173/500 [06:04<25:02,  4.60s/it]

[I 2026-05-18 16:01:05,643] Trial 172 finished with value: 0.9497337323124366 and parameters: {'max_iter': 98, 'learning_rate': 0.04955447054457347, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6228780348499415, 'min_samples_leaf': 82}. Best is trial 163 with value: 0.9497414494911413.
[I 2026-05-18 16:01:05,655] Trial 175 finished with value: 0.9497187915484915 and parameters: {'max_iter': 92, 'learning_rate': 0.04952774629659426, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8246020841769325, 'min_samples_leaf': 83}. Best is trial 163 with value: 0.9497414494911413.

Best trial: 163. Best value: 0.949741:  35%|███▌      | 175/500 [06:05<14:31,  2.68s/it]

[I 2026-05-18 16:01:06,528] Trial 173 finished with value: 0.9497244561585884 and parameters: {'max_iter': 98, 'learning_rate': 0.04958418781579525, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6351658069530454, 'min_samples_leaf': 84}. Best is trial 163 with value: 0.9497414494911413.

Best trial: 174. Best value: 0.94975:  35%|███▌      | 176/500 [06:06<11:44,  2.17s/it]

[I 2026-05-18 16:01:07,152] Trial 174 finished with value: 0.9497504301117491 and parameters: {'max_iter': 99, 'learning_rate': 0.04988905023070226, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.7849780191890819, 'min_samples_leaf': 63}. Best is trial 174 with value: 0.9497504301117491.

Best trial: 174. Best value: 0.94975:  35%|███▌      | 177/500 [06:10<14:45,  2.74s/it]

[I 2026-05-18 16:01:11,512] Trial 176 finished with value: 0.9497244695208191 and parameters: {'max_iter': 98, 'learning_rate': 0.04922641768065664, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.4626175656266729, 'min_samples_leaf': 82}. Best is trial 174 with value: 0.9497504301117491.

Best trial: 174. Best value: 0.94975:  36%|███▌      | 178/500 [06:10<11:18,  2.11s/it]

[I 2026-05-18 16:01:11,919] Trial 179 finished with value: 0.94971692453508 and parameters: {'max_iter': 92, 'learning_rate': 0.04996292443911664, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 2.0382391109730675, 'min_samples_leaf': 63}. Best is trial 174 with value: 0.9497504301117491.

Best trial: 174. Best value: 0.94975:  36%|███▌      | 179/500 [06:12<09:52,  1.84s/it]

[I 2026-05-18 16:01:13,093] Trial 177 finished with value: 0.9497315130464508 and parameters: {'max_iter': 98, 'learning_rate': 0.04921797873350099, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.4267794424138054, 'min_samples_leaf': 65}. Best is trial 174 with value: 0.9497504301117491.

Best trial: 178. Best value: 0.949751:  36%|███▌      | 180/500 [06:12<07:23,  1.39s/it]

[I 2026-05-18 16:01:13,310] Trial 178 finished with value: 0.9497506340929821 and parameters: {'max_iter': 98, 'learning_rate': 0.049607672750611474, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.444157518938507, 'min_samples_leaf': 64}. Best is trial 178 with value: 0.9497506340929821.

Best trial: 178. Best value: 0.949751:  36%|███▌      | 181/500 [06:19<16:45,  3.15s/it]

[I 2026-05-18 16:01:20,814] Trial 180 finished with value: 0.9497333465622028 and parameters: {'max_iter': 98, 'learning_rate': 0.049264272043181366, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.7967531533893847, 'min_samples_leaf': 66}. Best is trial 178 with value: 0.9497506340929821.

Best trial: 178. Best value: 0.949751:  36%|███▋      | 182/500 [06:20<13:20,  2.52s/it]

[I 2026-05-18 16:01:21,791] Trial 184 finished with value: 0.949537143342406 and parameters: {'max_iter': 43, 'learning_rate': 0.049788627333110055, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7858239678034424, 'min_samples_leaf': 62}. Best is trial 178 with value: 0.9497506340929821.

Best trial: 178. Best value: 0.949751:  37%|███▋      | 183/500 [06:21<11:18,  2.14s/it]

[I 2026-05-18 16:01:23,033] Trial 181 finished with value: 0.9497236482601048 and parameters: {'max_iter': 98, 'learning_rate': 0.04886019133426321, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7435337024321347, 'min_samples_leaf': 63}. Best is trial 178 with value: 0.9497506340929821.

Best trial: 178. Best value: 0.949751:  37%|███▋      | 184/500 [06:23<10:45,  2.04s/it]

[I 2026-05-18 16:01:24,841] Trial 182 finished with value: 0.9497426963132366 and parameters: {'max_iter': 98, 'learning_rate': 0.0499074896313462, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8001636099970351, 'min_samples_leaf': 50}. Best is trial 178 with value: 0.9497506340929821.

Best trial: 178. Best value: 0.949751:  37%|███▋      | 185/500 [06:30<17:32,  3.34s/it]

[I 2026-05-18 16:01:31,259] Trial 183 finished with value: 0.9497496572989105 and parameters: {'max_iter': 98, 'learning_rate': 0.04962952392321985, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7803934225925735, 'min_samples_leaf': 63}. Best is trial 178 with value: 0.9497506340929821.

Best trial: 178. Best value: 0.949751:  37%|███▋      | 186/500 [06:37<23:43,  4.53s/it]

[I 2026-05-18 16:01:38,598] Trial 185 finished with value: 0.9497448556354222 and parameters: {'max_iter': 98, 'learning_rate': 0.04940758310024907, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7939513187419097, 'min_samples_leaf': 62}. Best is trial 178 with value: 0.9497506340929821.

Best trial: 178. Best value: 0.949751:  37%|███▋      | 187/500 [06:37<17:08,  3.29s/it]

[I 2026-05-18 16:01:38,954] Trial 186 finished with value: 0.9497403674223024 and parameters: {'max_iter': 98, 'learning_rate': 0.04864785773943398, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8001778473439325, 'min_samples_leaf': 63}. Best is trial 178 with value: 0.9497506340929821.

Best trial: 178. Best value: 0.949751:  38%|███▊      | 188/500 [06:38<13:39,  2.63s/it]

[I 2026-05-18 16:01:40,033] Trial 187 finished with value: 0.949744603999296 and parameters: {'max_iter': 100, 'learning_rate': 0.04927736124202308, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.795810961277754, 'min_samples_leaf': 66}. Best is trial 178 with value: 0.9497506340929821.

Best trial: 188. Best value: 0.949757:  38%|███▊      | 189/500 [06:43<16:37,  3.21s/it]

[I 2026-05-18 16:01:44,597] Trial 188 finished with value: 0.9497571771545005 and parameters: {'max_iter': 100, 'learning_rate': 0.049279424968777505, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7407240315476109, 'min_samples_leaf': 65}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:01:44,726] Trial 189 finished with value: 0.9497415070695074 and parameters: {'max_iter': 100, 'learning_rate': 0.04949079916430491, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8061919253694143, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  38%|███▊      | 191/500 [06:44<09:21,  1.82s/it]

[I 2026-05-18 16:01:45,476] Trial 191 finished with value: 0.9497303068822063 and parameters: {'max_iter': 98, 'learning_rate': 0.04991175139548274, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.553827448139457, 'min_samples_leaf': 66}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  38%|███▊      | 192/500 [06:45<08:11,  1.60s/it]

[I 2026-05-18 16:01:46,547] Trial 190 finished with value: 0.9497465245472452 and parameters: {'max_iter': 100, 'learning_rate': 0.0494178824057043, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.4471526342195882, 'min_samples_leaf': 66}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  39%|███▊      | 193/500 [06:52<17:02,  3.33s/it]

[I 2026-05-18 16:01:53,932] Trial 192 finished with value: 0.9497358098801982 and parameters: {'max_iter': 100, 'learning_rate': 0.04869164007661803, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.6334230706874846, 'min_samples_leaf': 68}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  39%|███▉      | 194/500 [06:53<13:26,  2.64s/it]

[I 2026-05-18 16:01:54,948] Trial 193 finished with value: 0.9497334127931474 and parameters: {'max_iter': 100, 'learning_rate': 0.049217823407454106, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.5235868066489833, 'min_samples_leaf': 69}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  39%|███▉      | 195/500 [06:55<11:24,  2.24s/it]

[I 2026-05-18 16:01:56,267] Trial 194 finished with value: 0.9496999046343731 and parameters: {'max_iter': 100, 'learning_rate': 0.042521602606609275, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.3811017342941994, 'min_samples_leaf': 68}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  39%|███▉      | 196/500 [06:56<09:48,  1.94s/it]

[I 2026-05-18 16:01:57,488] Trial 195 finished with value: 0.9497534737869175 and parameters: {'max_iter': 100, 'learning_rate': 0.04971881956062539, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.4488797652425223, 'min_samples_leaf': 68}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  39%|███▉      | 197/500 [07:02<16:36,  3.29s/it]

[I 2026-05-18 16:02:03,941] Trial 200 pruned.
[I 2026-05-18 16:02:03,956] Trial 196 finished with value: 0.9497053347843 and parameters: {'max_iter': 100, 'learning_rate': 0.04189317960007275, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.3767166274176204, 'min_samples_leaf': 72}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  40%|███▉      | 199/500 [07:10<17:22,  3.47s/it]

[I 2026-05-18 16:02:11,215] Trial 197 finished with value: 0.9497343955237394 and parameters: {'max_iter': 100, 'learning_rate': 0.04999302907042596, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.6222586977129045, 'min_samples_leaf': 68}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  40%|████      | 200/500 [07:10<13:57,  2.79s/it]

[I 2026-05-18 16:02:12,033] Trial 198 finished with value: 0.9497084932363871 and parameters: {'max_iter': 100, 'learning_rate': 0.042408608739011526, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.4574598781988133, 'min_samples_leaf': 68}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  40%|████      | 201/500 [07:11<11:20,  2.28s/it]

[I 2026-05-18 16:02:12,854] Trial 199 finished with value: 0.9497097997285084 and parameters: {'max_iter': 100, 'learning_rate': 0.04271761134357144, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7828938349623074, 'min_samples_leaf': 69}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  40%|████      | 202/500 [07:16<14:40,  2.95s/it]

[I 2026-05-18 16:02:17,611] Trial 201 finished with value: 0.9496913706917581 and parameters: {'max_iter': 100, 'learning_rate': 0.04204104149455833, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.4848617260729022, 'min_samples_leaf': 68}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  41%|████      | 203/500 [07:17<11:15,  2.27s/it]

[I 2026-05-18 16:02:18,141] Trial 202 finished with value: 0.9497022851522452 and parameters: {'max_iter': 100, 'learning_rate': 0.042269221208693135, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.499425720134111, 'min_samples_leaf': 67}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  41%|████      | 204/500 [07:18<10:31,  2.13s/it]

[I 2026-05-18 16:02:19,918] Trial 203 finished with value: 0.9497094521335547 and parameters: {'max_iter': 100, 'learning_rate': 0.04274092563175067, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.4918305830629137, 'min_samples_leaf': 70}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  41%|████      | 205/500 [07:25<17:00,  3.46s/it]

[I 2026-05-18 16:02:26,636] Trial 204 finished with value: 0.9497091802114095 and parameters: {'max_iter': 100, 'learning_rate': 0.042234073307976315, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.5609060111712216, 'min_samples_leaf': 68}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  41%|████      | 206/500 [07:27<14:16,  2.91s/it]

[I 2026-05-18 16:02:28,222] Trial 205 finished with value: 0.9496985074658694 and parameters: {'max_iter': 100, 'learning_rate': 0.04217350481998115, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.4941139290335474, 'min_samples_leaf': 69}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  41%|████▏     | 207/500 [07:28<11:39,  2.39s/it]

[I 2026-05-18 16:02:29,354] Trial 206 finished with value: 0.9497008176053103 and parameters: {'max_iter': 100, 'learning_rate': 0.04142098081203014, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.6982435006582817, 'min_samples_leaf': 69}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  42%|████▏     | 208/500 [07:29<09:14,  1.90s/it]

[I 2026-05-18 16:02:30,080] Trial 207 finished with value: 0.9497116734970076 and parameters: {'max_iter': 100, 'learning_rate': 0.042847816957142765, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.6308766012292986, 'min_samples_leaf': 70}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  42%|████▏     | 209/500 [07:35<15:51,  3.27s/it]

[I 2026-05-18 16:02:36,598] Trial 208 finished with value: 0.9497121959998381 and parameters: {'max_iter': 100, 'learning_rate': 0.04294579758948498, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.6586584706359602, 'min_samples_leaf': 70}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  42%|████▏     | 210/500 [07:35<11:40,  2.42s/it]

[I 2026-05-18 16:02:37,011] Trial 209 finished with value: 0.9497060177681018 and parameters: {'max_iter': 100, 'learning_rate': 0.04376678285279144, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1754557102282268, 'min_samples_leaf': 70}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  42%|████▏     | 211/500 [07:43<18:36,  3.86s/it]

[I 2026-05-18 16:02:44,267] Trial 210 finished with value: 0.9497202664262563 and parameters: {'max_iter': 100, 'learning_rate': 0.04289281315168893, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.749032195982052, 'min_samples_leaf': 70}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  43%|████▎     | 213/500 [07:44<10:09,  2.12s/it]

[I 2026-05-18 16:02:45,150] Trial 211 finished with value: 0.9497231312996192 and parameters: {'max_iter': 100, 'learning_rate': 0.04302270955848464, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.7889320249384792, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:02:45,289] Trial 212 finished with value: 0.9496886669105589 and parameters: {'max_iter': 98, 'learning_rate': 0.04327774428953875, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.6527276970516198, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  43%|████▎     | 214/500 [07:48<13:40,  2.87s/it]

[I 2026-05-18 16:02:49,898] Trial 213 finished with value: 0.9497128008141139 and parameters: {'max_iter': 98, 'learning_rate': 0.045405698328521656, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.70355064810704, 'min_samples_leaf': 74}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  43%|████▎     | 215/500 [07:49<09:53,  2.08s/it]

[I 2026-05-18 16:02:50,127] Trial 214 finished with value: 0.949715759380901 and parameters: {'max_iter': 98, 'learning_rate': 0.04598894669497459, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.7786177618003345, 'min_samples_leaf': 52}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  43%|████▎     | 216/500 [07:51<09:54,  2.09s/it]

[I 2026-05-18 16:02:52,262] Trial 215 finished with value: 0.9497091253710501 and parameters: {'max_iter': 98, 'learning_rate': 0.04595005336609434, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.8346616876206756, 'min_samples_leaf': 52}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  43%|████▎     | 217/500 [07:58<16:59,  3.60s/it]

[I 2026-05-18 16:02:59,389] Trial 216 finished with value: 0.9497193541185671 and parameters: {'max_iter': 98, 'learning_rate': 0.04601553242824054, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 2.2973961712976223, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  44%|████▎     | 218/500 [07:59<14:06,  3.00s/it]

[I 2026-05-18 16:03:00,994] Trial 217 finished with value: 0.9497099929514394 and parameters: {'max_iter': 98, 'learning_rate': 0.045792689121439016, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 2.449545099388935, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  44%|████▍     | 219/500 [08:00<10:49,  2.31s/it]

[I 2026-05-18 16:03:01,692] Trial 218 finished with value: 0.9497248026843186 and parameters: {'max_iter': 97, 'learning_rate': 0.046179047617943905, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 2.3924590829038097, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  44%|████▍     | 220/500 [08:01<08:08,  1.74s/it]

[I 2026-05-18 16:03:02,108] Trial 219 finished with value: 0.9497164256692854 and parameters: {'max_iter': 97, 'learning_rate': 0.046480919264790976, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1884132907774039, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  44%|████▍     | 221/500 [08:07<14:35,  3.14s/it]

[I 2026-05-18 16:03:08,500] Trial 220 finished with value: 0.9497078695298017 and parameters: {'max_iter': 97, 'learning_rate': 0.04592056158120465, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1479598575923344, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  44%|████▍     | 222/500 [08:07<10:40,  2.30s/it]

[I 2026-05-18 16:03:08,795] Trial 221 finished with value: 0.949716441749765 and parameters: {'max_iter': 97, 'learning_rate': 0.04600903825789985, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 2.554285968126189, 'min_samples_leaf': 51}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  45%|████▍     | 223/500 [08:15<18:08,  3.93s/it]

[I 2026-05-18 16:03:16,578] Trial 222 finished with value: 0.9497192043616961 and parameters: {'max_iter': 97, 'learning_rate': 0.0463348062960032, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.175509142956702, 'min_samples_leaf': 52}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  45%|████▍     | 224/500 [08:16<13:37,  2.96s/it]

[I 2026-05-18 16:03:17,277] Trial 223 finished with value: 0.9497182006340357 and parameters: {'max_iter': 97, 'learning_rate': 0.0463260699488231, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1356840050450674, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  45%|████▌     | 225/500 [08:16<10:02,  2.19s/it]

[I 2026-05-18 16:03:17,680] Trial 224 finished with value: 0.949718820517368 and parameters: {'max_iter': 97, 'learning_rate': 0.046215912998147146, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.138573685500564, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  45%|████▌     | 226/500 [08:20<12:22,  2.71s/it]

[I 2026-05-18 16:03:21,602] Trial 225 finished with value: 0.949724949061048 and parameters: {'max_iter': 97, 'learning_rate': 0.04649599619606231, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1529891711570524, 'min_samples_leaf': 59}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  45%|████▌     | 227/500 [08:20<09:01,  1.98s/it]

[I 2026-05-18 16:03:21,867] Trial 226 finished with value: 0.9497180699563582 and parameters: {'max_iter': 97, 'learning_rate': 0.04684884079914127, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 2.53483328196169, 'min_samples_leaf': 59}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  46%|████▌     | 228/500 [08:23<10:12,  2.25s/it]

[I 2026-05-18 16:03:24,764] Trial 227 finished with value: 0.94972545530233 and parameters: {'max_iter': 97, 'learning_rate': 0.04687953176354843, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1876721038189313, 'min_samples_leaf': 59}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  46%|████▌     | 229/500 [08:30<16:28,  3.65s/it]

[I 2026-05-18 16:03:31,610] Trial 228 finished with value: 0.9497178579605612 and parameters: {'max_iter': 97, 'learning_rate': 0.0465473539711232, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1484644813095557, 'min_samples_leaf': 59}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  46%|████▌     | 230/500 [08:32<13:40,  3.04s/it]

[I 2026-05-18 16:03:33,287] Trial 229 finished with value: 0.9497401232759086 and parameters: {'max_iter': 97, 'learning_rate': 0.049564353993316615, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0735098471269087, 'min_samples_leaf': 60}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  46%|████▌     | 231/500 [08:32<10:22,  2.32s/it]

[I 2026-05-18 16:03:33,909] Trial 230 finished with value: 0.9497251308709351 and parameters: {'max_iter': 97, 'learning_rate': 0.04673953287179294, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0997317334581378, 'min_samples_leaf': 61}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  46%|████▋     | 232/500 [08:33<07:49,  1.75s/it]

[I 2026-05-18 16:03:34,341] Trial 231 finished with value: 0.9497311164996566 and parameters: {'max_iter': 97, 'learning_rate': 0.0472625447604078, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1052386836877315, 'min_samples_leaf': 60}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  47%|████▋     | 233/500 [08:39<13:32,  3.04s/it]

[I 2026-05-18 16:03:40,399] Trial 232 finished with value: 0.9497265169649921 and parameters: {'max_iter': 97, 'learning_rate': 0.04869259893346864, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8393986047035439, 'min_samples_leaf': 60}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  47%|████▋     | 234/500 [08:39<10:14,  2.31s/it]

[I 2026-05-18 16:03:41,006] Trial 233 finished with value: 0.949741764705746 and parameters: {'max_iter': 97, 'learning_rate': 0.048917331732908735, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8359945701101933, 'min_samples_leaf': 62}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  47%|████▋     | 236/500 [08:48<13:13,  3.01s/it]

[I 2026-05-18 16:03:49,692] Trial 234 finished with value: 0.9497333850718837 and parameters: {'max_iter': 97, 'learning_rate': 0.04960066060585099, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7864984136970813, 'min_samples_leaf': 61}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:03:49,847] Trial 235 finished with value: 0.9497375830239886 and parameters: {'max_iter': 97, 'learning_rate': 0.04956269919468815, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.825144112876356, 'min_samples_leaf': 59}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  47%|████▋     | 237/500 [08:49<09:47,  2.23s/it]

[I 2026-05-18 16:03:50,296] Trial 236 finished with value: 0.9497321296262566 and parameters: {'max_iter': 96, 'learning_rate': 0.049764853953214526, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8777570964899487, 'min_samples_leaf': 61}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  48%|████▊     | 238/500 [08:49<07:37,  1.75s/it]

[I 2026-05-18 16:03:50,906] Trial 241 finished with value: 0.9490896708049004 and parameters: {'max_iter': 98, 'learning_rate': 0.0493498315258847, 'max_depth': 1, 'max_leaf_nodes': 8, 'l2_regularization': 0.8050324310987226, 'min_samples_leaf': 79}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  48%|████▊     | 239/500 [08:53<10:08,  2.33s/it]

[I 2026-05-18 16:03:54,583] Trial 237 finished with value: 0.949733081988985 and parameters: {'max_iter': 97, 'learning_rate': 0.04988177057210368, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8321279292333011, 'min_samples_leaf': 61}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  48%|████▊     | 240/500 [08:54<08:03,  1.86s/it]

[I 2026-05-18 16:03:55,354] Trial 238 finished with value: 0.9497341455844955 and parameters: {'max_iter': 98, 'learning_rate': 0.04931410455093413, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8085562818969312, 'min_samples_leaf': 63}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  48%|████▊     | 241/500 [08:55<07:26,  1.73s/it]

[I 2026-05-18 16:03:56,756] Trial 242 finished with value: 0.9496746362757692 and parameters: {'max_iter': 63, 'learning_rate': 0.04997976089992187, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7579045257959783, 'min_samples_leaf': 77}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  48%|████▊     | 242/500 [08:56<06:40,  1.55s/it]

[I 2026-05-18 16:03:57,919] Trial 248 pruned.

Best trial: 188. Best value: 0.949757:  49%|████▊     | 243/500 [08:57<05:48,  1.35s/it]

[I 2026-05-18 16:03:58,806] Trial 239 finished with value: 0.9497396509098619 and parameters: {'max_iter': 98, 'learning_rate': 0.049999943249044325, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8144491300845577, 'min_samples_leaf': 78}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  49%|████▉     | 244/500 [09:04<12:18,  2.89s/it]

[I 2026-05-18 16:04:05,272] Trial 240 finished with value: 0.949733488029717 and parameters: {'max_iter': 98, 'learning_rate': 0.04989130825841027, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8095448444302827, 'min_samples_leaf': 78}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  49%|████▉     | 245/500 [09:06<11:45,  2.77s/it]

[I 2026-05-18 16:04:07,758] Trial 243 finished with value: 0.9497338091527261 and parameters: {'max_iter': 98, 'learning_rate': 0.048370961716435186, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8344632840201222, 'min_samples_leaf': 76}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  49%|████▉     | 247/500 [09:12<11:04,  2.63s/it]

[I 2026-05-18 16:04:13,638] Trial 244 finished with value: 0.9497378015981426 and parameters: {'max_iter': 98, 'learning_rate': 0.04985961776609858, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7935230189725505, 'min_samples_leaf': 78}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:04:13,749] Trial 245 finished with value: 0.9497407444885433 and parameters: {'max_iter': 98, 'learning_rate': 0.04987427474325734, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8022063265404689, 'min_samples_leaf': 77}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  50%|████▉     | 248/500 [09:20<17:57,  4.28s/it]

[I 2026-05-18 16:04:21,874] Trial 247 finished with value: 0.9497287147095552 and parameters: {'max_iter': 96, 'learning_rate': 0.04948772803650499, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7567539586382545, 'min_samples_leaf': 78}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  50%|████▉     | 249/500 [09:21<13:10,  3.15s/it]

[I 2026-05-18 16:04:22,405] Trial 249 finished with value: 0.9497260817241502 and parameters: {'max_iter': 94, 'learning_rate': 0.04933814529910666, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7388236034019784, 'min_samples_leaf': 75}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  50%|█████     | 250/500 [09:21<09:40,  2.32s/it]

[I 2026-05-18 16:04:22,803] Trial 246 finished with value: 0.9497313719326013 and parameters: {'max_iter': 98, 'learning_rate': 0.04900195814461345, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7098448335735612, 'min_samples_leaf': 78}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  50%|█████     | 251/500 [09:25<10:57,  2.64s/it]

[I 2026-05-18 16:04:26,173] Trial 250 finished with value: 0.9497363782079761 and parameters: {'max_iter': 94, 'learning_rate': 0.04968825273673534, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.726910225260736, 'min_samples_leaf': 77}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  50%|█████     | 252/500 [09:25<08:02,  1.95s/it]

[I 2026-05-18 16:04:26,499] Trial 251 finished with value: 0.9496853763600338 and parameters: {'max_iter': 94, 'learning_rate': 0.03887770002845061, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5693956970759058, 'min_samples_leaf': 77}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  51%|█████     | 253/500 [09:27<07:43,  1.88s/it]

[I 2026-05-18 16:04:28,226] Trial 252 finished with value: 0.9496821037699684 and parameters: {'max_iter': 95, 'learning_rate': 0.038811986080035214, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5656023290724763, 'min_samples_leaf': 78}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  51%|█████     | 254/500 [09:28<06:54,  1.68s/it]

[I 2026-05-18 16:04:29,450] Trial 253 finished with value: 0.9497334846362036 and parameters: {'max_iter': 95, 'learning_rate': 0.04945722354609032, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5680186954531357, 'min_samples_leaf': 76}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  51%|█████     | 255/500 [09:30<07:52,  1.93s/it]

[I 2026-05-18 16:04:31,947] Trial 254 finished with value: 0.949687482756773 and parameters: {'max_iter': 99, 'learning_rate': 0.038778039131660606, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5716924366084946, 'min_samples_leaf': 78}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  51%|█████     | 256/500 [09:36<12:46,  3.14s/it]

[I 2026-05-18 16:04:37,921] Trial 255 finished with value: 0.9496997154766861 and parameters: {'max_iter': 99, 'learning_rate': 0.039677798740212725, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7173324366116341, 'min_samples_leaf': 78}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  51%|█████▏    | 257/500 [09:37<09:45,  2.41s/it]

[I 2026-05-18 16:04:38,630] Trial 256 finished with value: 0.9497012258944524 and parameters: {'max_iter': 94, 'learning_rate': 0.04426759266306446, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5593518023350953, 'min_samples_leaf': 87}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  52%|█████▏    | 258/500 [09:43<14:00,  3.47s/it]

[I 2026-05-18 16:04:44,582] Trial 258 finished with value: 0.9496775652987118 and parameters: {'max_iter': 94, 'learning_rate': 0.038197167615105235, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5780421007587764, 'min_samples_leaf': 78}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  52%|█████▏    | 259/500 [09:45<12:19,  3.07s/it]

[I 2026-05-18 16:04:46,715] Trial 257 finished with value: 0.9496962421585724 and parameters: {'max_iter': 99, 'learning_rate': 0.03827039692134412, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6069600689403848, 'min_samples_leaf': 77}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  52%|█████▏    | 260/500 [09:50<14:10,  3.54s/it]

[I 2026-05-18 16:04:51,358] Trial 266 pruned.

Best trial: 188. Best value: 0.949757:  52%|█████▏    | 261/500 [09:52<12:13,  3.07s/it]

[I 2026-05-18 16:04:53,264] Trial 259 finished with value: 0.9496717925824946 and parameters: {'max_iter': 94, 'learning_rate': 0.03841862864821272, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5777540069107016, 'min_samples_leaf': 90}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  53%|█████▎    | 263/500 [09:54<07:52,  1.99s/it]

[I 2026-05-18 16:04:55,392] Trial 260 finished with value: 0.9496941259652782 and parameters: {'max_iter': 99, 'learning_rate': 0.03973366610244714, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5751219039774262, 'min_samples_leaf': 91}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:04:55,581] Trial 261 finished with value: 0.9496991462620696 and parameters: {'max_iter': 99, 'learning_rate': 0.03957821039557039, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5761047922732327, 'min_samples_leaf': 93}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  53%|█████▎    | 264/500 [09:56<07:59,  2.03s/it]

[I 2026-05-18 16:04:57,691] Trial 262 finished with value: 0.9496858690383082 and parameters: {'max_iter': 95, 'learning_rate': 0.03969963296359744, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.574408522028808, 'min_samples_leaf': 77}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  53%|█████▎    | 265/500 [09:58<07:50,  2.00s/it]

[I 2026-05-18 16:04:59,630] Trial 263 finished with value: 0.949691975885585 and parameters: {'max_iter': 99, 'learning_rate': 0.03838542850972505, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5792817245949176, 'min_samples_leaf': 89}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  53%|█████▎    | 266/500 [10:00<07:34,  1.94s/it]

[I 2026-05-18 16:05:01,429] Trial 264 finished with value: 0.9497144332000808 and parameters: {'max_iter': 99, 'learning_rate': 0.04391450202976331, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5708065290452924, 'min_samples_leaf': 93}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  53%|█████▎    | 267/500 [10:01<06:24,  1.65s/it]

[I 2026-05-18 16:05:02,390] Trial 265 finished with value: 0.9497027581726323 and parameters: {'max_iter': 100, 'learning_rate': 0.04401177085821838, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 42.75806999688888, 'min_samples_leaf': 90}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  54%|█████▎    | 268/500 [10:03<06:38,  1.72s/it]

[I 2026-05-18 16:05:04,275] Trial 269 pruned.

Best trial: 188. Best value: 0.949757:  54%|█████▍    | 269/500 [10:10<12:34,  3.27s/it]

[I 2026-05-18 16:05:11,151] Trial 267 finished with value: 0.9497112364116186 and parameters: {'max_iter': 100, 'learning_rate': 0.043179943047315116, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9439667338480376, 'min_samples_leaf': 90}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  54%|█████▍    | 270/500 [10:11<09:47,  2.55s/it]

[I 2026-05-18 16:05:12,043] Trial 268 finished with value: 0.949715254284175 and parameters: {'max_iter': 100, 'learning_rate': 0.04418708270038331, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9538064332644531, 'min_samples_leaf': 91}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  54%|█████▍    | 271/500 [10:12<08:25,  2.21s/it]

[I 2026-05-18 16:05:13,439] Trial 273 finished with value: 0.9495622278921113 and parameters: {'max_iter': 49, 'learning_rate': 0.04378210355997485, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9233726875075363, 'min_samples_leaf': 64}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  54%|█████▍    | 272/500 [10:19<14:14,  3.75s/it]

[I 2026-05-18 16:05:20,790] Trial 270 finished with value: 0.9497056447192096 and parameters: {'max_iter': 100, 'learning_rate': 0.04403288473068911, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8614773196877117, 'min_samples_leaf': 92}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  55%|█████▍    | 273/500 [10:23<13:55,  3.68s/it]

[I 2026-05-18 16:05:24,314] Trial 271 finished with value: 0.9497243219703588 and parameters: {'max_iter': 100, 'learning_rate': 0.04382411546700278, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8968405009413779, 'min_samples_leaf': 92}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  55%|█████▍    | 274/500 [10:25<12:16,  3.26s/it]

[I 2026-05-18 16:05:26,597] Trial 272 finished with value: 0.9497208084416524 and parameters: {'max_iter': 100, 'learning_rate': 0.0438834514928595, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9727573188254905, 'min_samples_leaf': 92}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  55%|█████▌    | 275/500 [10:26<10:01,  2.67s/it]

[I 2026-05-18 16:05:27,907] Trial 274 finished with value: 0.9496994757682842 and parameters: {'max_iter': 96, 'learning_rate': 0.04429378633812783, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9208235097351751, 'min_samples_leaf': 64}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  55%|█████▌    | 276/500 [10:30<11:02,  2.96s/it]

[I 2026-05-18 16:05:31,518] Trial 275 finished with value: 0.9497081327755182 and parameters: {'max_iter': 100, 'learning_rate': 0.0439784939398041, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8952245070522635, 'min_samples_leaf': 68}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  55%|█████▌    | 277/500 [10:30<08:12,  2.21s/it]

[I 2026-05-18 16:05:31,980] Trial 276 finished with value: 0.9497065305005551 and parameters: {'max_iter': 96, 'learning_rate': 0.04406403385961628, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8999977007247086, 'min_samples_leaf': 65}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  56%|█████▌    | 278/500 [10:32<07:43,  2.09s/it]

[I 2026-05-18 16:05:33,786] Trial 277 finished with value: 0.9497083789388043 and parameters: {'max_iter': 96, 'learning_rate': 0.043951649968901677, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9053548651232258, 'min_samples_leaf': 64}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  56%|█████▌    | 279/500 [10:34<07:10,  1.95s/it]

[I 2026-05-18 16:05:35,410] Trial 278 finished with value: 0.9497213025307726 and parameters: {'max_iter': 96, 'learning_rate': 0.04353738397819506, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9089720091196161, 'min_samples_leaf': 61}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  56%|█████▌    | 280/500 [10:35<06:23,  1.74s/it]

[I 2026-05-18 16:05:36,679] Trial 279 finished with value: 0.9497054523452535 and parameters: {'max_iter': 96, 'learning_rate': 0.04422308468816618, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9833312219099937, 'min_samples_leaf': 64}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  56%|█████▌    | 281/500 [10:42<11:27,  3.14s/it]

[I 2026-05-18 16:05:43,072] Trial 280 finished with value: 0.9497163574375597 and parameters: {'max_iter': 96, 'learning_rate': 0.04440030163785464, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6887108725362765, 'min_samples_leaf': 217}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  56%|█████▋    | 282/500 [10:43<09:18,  2.56s/it]

[I 2026-05-18 16:05:44,282] Trial 281 finished with value: 0.9497163629872218 and parameters: {'max_iter': 96, 'learning_rate': 0.04518658850475589, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7171962247616366, 'min_samples_leaf': 67}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  57%|█████▋    | 283/500 [10:44<08:05,  2.24s/it]

[I 2026-05-18 16:05:45,760] Trial 282 finished with value: 0.9497114175554708 and parameters: {'max_iter': 96, 'learning_rate': 0.04476272419482489, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6870559289595729, 'min_samples_leaf': 66}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  57%|█████▋    | 284/500 [10:45<06:39,  1.85s/it]

[I 2026-05-18 16:05:46,699] Trial 286 pruned.

Best trial: 188. Best value: 0.949757:  57%|█████▋    | 285/500 [10:51<11:00,  3.07s/it]

[I 2026-05-18 16:05:52,623] Trial 283 finished with value: 0.9497242777137999 and parameters: {'max_iter': 96, 'learning_rate': 0.04586395046502093, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6869069068565193, 'min_samples_leaf': 66}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:05:52,679] Trial 289 pruned.

Best trial: 188. Best value: 0.949757:  57%|█████▋    | 287/500 [10:54<08:36,  2.43s/it]

[I 2026-05-18 16:05:55,974] Trial 284 finished with value: 0.9497139419059811 and parameters: {'max_iter': 96, 'learning_rate': 0.04604029112064982, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6832964973501396, 'min_samples_leaf': 64}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  58%|█████▊    | 288/500 [10:57<08:45,  2.48s/it]

[I 2026-05-18 16:05:58,613] Trial 285 finished with value: 0.9497280723145692 and parameters: {'max_iter': 96, 'learning_rate': 0.04615672300455616, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6814743356393888, 'min_samples_leaf': 65}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  58%|█████▊    | 289/500 [11:02<10:53,  3.10s/it]

[I 2026-05-18 16:06:03,458] Trial 287 finished with value: 0.9492340322619723 and parameters: {'max_iter': 96, 'learning_rate': 0.015974022420304757, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6880503719375596, 'min_samples_leaf': 67}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  58%|█████▊    | 290/500 [11:02<08:17,  2.37s/it]

[I 2026-05-18 16:06:03,820] Trial 288 finished with value: 0.9497161282301427 and parameters: {'max_iter': 96, 'learning_rate': 0.04626651963461449, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6825688662179318, 'min_samples_leaf': 229}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  58%|█████▊    | 291/500 [11:03<06:48,  1.95s/it]

[I 2026-05-18 16:06:04,767] Trial 294 pruned.

Best trial: 188. Best value: 0.949757:  58%|█████▊    | 292/500 [11:06<07:46,  2.24s/it]

[I 2026-05-18 16:06:07,730] Trial 290 finished with value: 0.9497318105975345 and parameters: {'max_iter': 98, 'learning_rate': 0.04673947159987888, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6900438032602431, 'min_samples_leaf': 70}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  59%|█████▊    | 293/500 [11:07<06:35,  1.91s/it]

[I 2026-05-18 16:06:08,829] Trial 291 finished with value: 0.9497524945321946 and parameters: {'max_iter': 98, 'learning_rate': 0.049906552618958315, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6948708536757235, 'min_samples_leaf': 72}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  59%|█████▉    | 294/500 [11:14<11:26,  3.33s/it]

[I 2026-05-18 16:06:15,592] Trial 292 finished with value: 0.9497329181437546 and parameters: {'max_iter': 98, 'learning_rate': 0.047012922676392774, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.692816148261719, 'min_samples_leaf': 72}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  59%|█████▉    | 295/500 [11:15<08:47,  2.58s/it]

[I 2026-05-18 16:06:16,364] Trial 293 finished with value: 0.9497260075790475 and parameters: {'max_iter': 98, 'learning_rate': 0.04652306231925635, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7152920366584146, 'min_samples_leaf': 73}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  59%|█████▉    | 296/500 [11:17<08:43,  2.57s/it]

[I 2026-05-18 16:06:18,907] Trial 295 finished with value: 0.9497367811000608 and parameters: {'max_iter': 98, 'learning_rate': 0.04999225999734595, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7721445592129559, 'min_samples_leaf': 73}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  59%|█████▉    | 297/500 [11:23<11:47,  3.49s/it]

[I 2026-05-18 16:06:24,569] Trial 297 finished with value: 0.949722509312598 and parameters: {'max_iter': 98, 'learning_rate': 0.047362289844368216, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7896060217662286, 'min_samples_leaf': 58}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  60%|█████▉    | 298/500 [11:24<08:42,  2.59s/it]

[I 2026-05-18 16:06:25,022] Trial 296 finished with value: 0.9497399193200653 and parameters: {'max_iter': 98, 'learning_rate': 0.049860561000781414, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7990699603185765, 'min_samples_leaf': 75}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  60%|█████▉    | 299/500 [11:27<09:26,  2.82s/it]

[I 2026-05-18 16:06:28,408] Trial 298 finished with value: 0.9497264118164311 and parameters: {'max_iter': 98, 'learning_rate': 0.04994929122350135, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8013853306445949, 'min_samples_leaf': 74}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  60%|██████    | 300/500 [11:30<09:27,  2.84s/it]

[I 2026-05-18 16:06:31,270] Trial 299 finished with value: 0.9497306549422723 and parameters: {'max_iter': 98, 'learning_rate': 0.04938287012963022, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7907553176864826, 'min_samples_leaf': 74}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  60%|██████    | 302/500 [11:35<08:04,  2.45s/it]

[I 2026-05-18 16:06:36,120] Trial 300 finished with value: 0.9497352015381771 and parameters: {'max_iter': 98, 'learning_rate': 0.04996757330700786, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.4527897482904353, 'min_samples_leaf': 75}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:06:36,254] Trial 301 finished with value: 0.9497430320066167 and parameters: {'max_iter': 98, 'learning_rate': 0.04981583014178697, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7982158794602507, 'min_samples_leaf': 75}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  61%|██████    | 303/500 [11:36<06:28,  1.97s/it]

[I 2026-05-18 16:06:37,124] Trial 302 finished with value: 0.9497434806831357 and parameters: {'max_iter': 98, 'learning_rate': 0.04987104004688089, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8121572244878986, 'min_samples_leaf': 82}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  61%|██████    | 304/500 [11:38<07:19,  2.24s/it]

[I 2026-05-18 16:06:39,989] Trial 304 finished with value: 0.9497499311330302 and parameters: {'max_iter': 93, 'learning_rate': 0.04994447720501901, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.815981689480568, 'min_samples_leaf': 59}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  61%|██████    | 305/500 [11:39<05:50,  1.80s/it]

[I 2026-05-18 16:06:40,756] Trial 303 finished with value: 0.9497281943901168 and parameters: {'max_iter': 98, 'learning_rate': 0.049861254068579344, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8490335517481152, 'min_samples_leaf': 82}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  61%|██████    | 306/500 [11:45<10:08,  3.14s/it]

[I 2026-05-18 16:06:47,011] Trial 306 finished with value: 0.9497152027739837 and parameters: {'max_iter': 93, 'learning_rate': 0.049763056155375525, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8069972200395036, 'min_samples_leaf': 57}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  61%|██████▏   | 307/500 [11:47<08:20,  2.59s/it]

[I 2026-05-18 16:06:48,332] Trial 305 finished with value: 0.9497402347844763 and parameters: {'max_iter': 98, 'learning_rate': 0.04993883073696988, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0478019026871865, 'min_samples_leaf': 263}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  62%|██████▏   | 308/500 [11:47<06:06,  1.91s/it]

[I 2026-05-18 16:06:48,582] Trial 307 finished with value: 0.949715590247561 and parameters: {'max_iter': 93, 'learning_rate': 0.04908796715058192, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 1.0692003339428486, 'min_samples_leaf': 56}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  62%|██████▏   | 309/500 [11:54<11:03,  3.47s/it]

[I 2026-05-18 16:06:55,751] Trial 308 finished with value: 0.9497138353993746 and parameters: {'max_iter': 93, 'learning_rate': 0.04941347062975592, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.2644591927613973, 'min_samples_leaf': 170}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  62%|██████▏   | 310/500 [11:55<08:04,  2.55s/it]

[I 2026-05-18 16:06:56,170] Trial 309 finished with value: 0.9497059971112843 and parameters: {'max_iter': 94, 'learning_rate': 0.04989931948131806, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 1.2814859342163238, 'min_samples_leaf': 261}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  62%|██████▏   | 311/500 [12:00<10:34,  3.36s/it]

[I 2026-05-18 16:07:01,334] Trial 311 finished with value: 0.9497200414805388 and parameters: {'max_iter': 93, 'learning_rate': 0.04956812093788396, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.4675080078542932, 'min_samples_leaf': 58}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  62%|██████▏   | 312/500 [12:00<07:56,  2.54s/it]

[I 2026-05-18 16:07:02,039] Trial 310 finished with value: 0.9497512118074795 and parameters: {'max_iter': 100, 'learning_rate': 0.049970492750959904, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0612449631492744, 'min_samples_leaf': 57}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  63%|██████▎   | 314/500 [12:05<06:53,  2.22s/it]

[I 2026-05-18 16:07:06,441] Trial 313 finished with value: 0.94968425700439 and parameters: {'max_iter': 93, 'learning_rate': 0.040960978907942654, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 1.2443858327788906, 'min_samples_leaf': 83}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:07:06,620] Trial 312 finished with value: 0.9496680379671905 and parameters: {'max_iter': 93, 'learning_rate': 0.041029880899212806, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.44473269892423917, 'min_samples_leaf': 56}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  63%|██████▎   | 315/500 [12:05<04:59,  1.62s/it]

[I 2026-05-18 16:07:06,833] Trial 314 finished with value: 0.949677530350294 and parameters: {'max_iter': 93, 'learning_rate': 0.040900480731500995, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 1.065814332861366, 'min_samples_leaf': 171}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  63%|██████▎   | 316/500 [12:09<06:48,  2.22s/it]

[I 2026-05-18 16:07:10,456] Trial 315 finished with value: 0.949679856184269 and parameters: {'max_iter': 93, 'learning_rate': 0.04123259948376301, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 1.0396059694376851, 'min_samples_leaf': 57}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  63%|██████▎   | 317/500 [12:10<05:29,  1.80s/it]

[I 2026-05-18 16:07:11,269] Trial 316 finished with value: 0.9496644208762453 and parameters: {'max_iter': 93, 'learning_rate': 0.04093628785543507, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 1.0819627652125756, 'min_samples_leaf': 57}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  64%|██████▎   | 318/500 [12:16<09:22,  3.09s/it]

[I 2026-05-18 16:07:17,366] Trial 317 finished with value: 0.9496736843293899 and parameters: {'max_iter': 94, 'learning_rate': 0.041740308040185345, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 1.0690714192323503, 'min_samples_leaf': 54}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  64%|██████▍   | 319/500 [12:18<08:27,  2.80s/it]

[I 2026-05-18 16:07:19,512] Trial 319 finished with value: 0.949688489086521 and parameters: {'max_iter': 93, 'learning_rate': 0.04127226114879144, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0672771674086208, 'min_samples_leaf': 57}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  64%|██████▍   | 320/500 [12:18<06:16,  2.09s/it]

[I 2026-05-18 16:07:19,936] Trial 318 finished with value: 0.9496794025936 and parameters: {'max_iter': 94, 'learning_rate': 0.04071199239129242, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.241093934498778, 'min_samples_leaf': 55}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  64%|██████▍   | 321/500 [12:26<10:41,  3.58s/it]

[I 2026-05-18 16:07:26,991] Trial 320 finished with value: 0.9496788295197074 and parameters: {'max_iter': 94, 'learning_rate': 0.04094834524602597, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 4.693064524794303, 'min_samples_leaf': 57}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:07:27,187] Trial 321 finished with value: 0.949698618835255 and parameters: {'max_iter': 94, 'learning_rate': 0.04038276464879767, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0722642123042483, 'min_samples_leaf': 57}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  65%|██████▍   | 323/500 [12:31<09:52,  3.35s/it]

[I 2026-05-18 16:07:32,363] Trial 322 finished with value: 0.9496909295866617 and parameters: {'max_iter': 94, 'learning_rate': 0.04115200460020159, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0489391405618933, 'min_samples_leaf': 100}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  65%|██████▍   | 324/500 [12:34<09:42,  3.31s/it]

[I 2026-05-18 16:07:35,586] Trial 323 finished with value: 0.9496977933903897 and parameters: {'max_iter': 100, 'learning_rate': 0.04084300476733899, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.005720922712928, 'min_samples_leaf': 55}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  65%|██████▌   | 326/500 [12:38<06:59,  2.41s/it]

[I 2026-05-18 16:07:39,097] Trial 331 finished with value: 0.9496300323383728 and parameters: {'max_iter': 54, 'learning_rate': 0.045984399653848644, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.002448490588675, 'min_samples_leaf': 101}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:07:39,269] Trial 324 finished with value: 0.9497084815697543 and parameters: {'max_iter': 100, 'learning_rate': 0.041301634934687845, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0482333509859731, 'min_samples_leaf': 56}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  65%|██████▌   | 327/500 [12:38<05:22,  1.87s/it]

[I 2026-05-18 16:07:39,869] Trial 325 finished with value: 0.9497080506987962 and parameters: {'max_iter': 100, 'learning_rate': 0.041405351123407284, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.006407080647957, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  66%|██████▌   | 328/500 [12:39<04:22,  1.52s/it]

[I 2026-05-18 16:07:40,582] Trial 326 finished with value: 0.9497085084084885 and parameters: {'max_iter': 100, 'learning_rate': 0.042108157170824605, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0524546691810854, 'min_samples_leaf': 297}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  66%|██████▌   | 329/500 [12:42<05:53,  2.07s/it]

[I 2026-05-18 16:07:43,934] Trial 327 finished with value: 0.9497205859642875 and parameters: {'max_iter': 100, 'learning_rate': 0.045638645741544484, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0414875718027066, 'min_samples_leaf': 294}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  66%|██████▌   | 330/500 [12:43<04:47,  1.69s/it]

[I 2026-05-18 16:07:44,740] Trial 328 finished with value: 0.9497136451772927 and parameters: {'max_iter': 100, 'learning_rate': 0.04581776120717344, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9825861005912965, 'min_samples_leaf': 51}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  66%|██████▌   | 331/500 [12:49<08:22,  2.97s/it]

[I 2026-05-18 16:07:50,702] Trial 329 finished with value: 0.9497327818421697 and parameters: {'max_iter': 100, 'learning_rate': 0.04613419453175299, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0767657684890282, 'min_samples_leaf': 101}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  66%|██████▋   | 332/500 [12:52<07:56,  2.83s/it]

[I 2026-05-18 16:07:53,218] Trial 330 finished with value: 0.9497281506925273 and parameters: {'max_iter': 100, 'learning_rate': 0.04607648188601965, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8451837140716144, 'min_samples_leaf': 197}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  67%|██████▋   | 333/500 [12:54<07:08,  2.57s/it]

[I 2026-05-18 16:07:55,164] Trial 335 finished with value: 0.9496340774863619 and parameters: {'max_iter': 54, 'learning_rate': 0.045764615120987534, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8222501070486469, 'min_samples_leaf': 82}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  67%|██████▋   | 334/500 [12:56<06:58,  2.52s/it]

[I 2026-05-18 16:07:57,580] Trial 334 finished with value: 0.9496743882422471 and parameters: {'max_iter': 71, 'learning_rate': 0.0460231215378007, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8464591798341697, 'min_samples_leaf': 462}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  67%|██████▋   | 335/500 [12:57<05:56,  2.16s/it]

[I 2026-05-18 16:07:58,881] Trial 343 pruned.

Best trial: 188. Best value: 0.949757:  67%|██████▋   | 336/500 [12:58<04:37,  1.69s/it]

[I 2026-05-18 16:07:59,489] Trial 344 pruned.

Best trial: 188. Best value: 0.949757:  67%|██████▋   | 337/500 [13:00<04:40,  1.72s/it]

[I 2026-05-18 16:08:01,284] Trial 332 finished with value: 0.9497403138345198 and parameters: {'max_iter': 100, 'learning_rate': 0.04584873067302795, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0234269219596706, 'min_samples_leaf': 60}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  68%|██████▊   | 338/500 [13:00<03:38,  1.35s/it]

[I 2026-05-18 16:08:01,750] Trial 333 finished with value: 0.9497072405559557 and parameters: {'max_iter': 100, 'learning_rate': 0.04586735745726171, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8459036313848873, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  68%|██████▊   | 339/500 [13:06<07:06,  2.65s/it]

[I 2026-05-18 16:08:07,437] Trial 340 finished with value: 0.9496699260069148 and parameters: {'max_iter': 98, 'learning_rate': 0.046067630566283206, 'max_depth': 2, 'max_leaf_nodes': 8, 'l2_regularization': 0.8434629220837885, 'min_samples_leaf': 82}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  68%|██████▊   | 341/500 [13:12<06:53,  2.60s/it]

[I 2026-05-18 16:08:13,391] Trial 336 finished with value: 0.9497152243830478 and parameters: {'max_iter': 98, 'learning_rate': 0.04557546544273324, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8143369587938907, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:08:13,556] Trial 337 finished with value: 0.9497102247392638 and parameters: {'max_iter': 98, 'learning_rate': 0.04587691938259695, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8398069566665889, 'min_samples_leaf': 307}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  69%|██████▊   | 343/500 [13:13<03:44,  1.43s/it]

[I 2026-05-18 16:08:14,072] Trial 339 finished with value: 0.9497326812878961 and parameters: {'max_iter': 98, 'learning_rate': 0.04680727894807679, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8507276923921958, 'min_samples_leaf': 382}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:08:14,227] Trial 338 finished with value: 0.9497213784551484 and parameters: {'max_iter': 98, 'learning_rate': 0.04588447646186048, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8514110295658839, 'min_samples_leaf': 83}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  69%|██████▉   | 344/500 [13:17<06:01,  2.32s/it]

[I 2026-05-18 16:08:18,614] Trial 354 pruned.

Best trial: 188. Best value: 0.949757:  69%|██████▉   | 345/500 [13:17<04:30,  1.74s/it]

[I 2026-05-18 16:08:19,028] Trial 341 finished with value: 0.9497083174436411 and parameters: {'max_iter': 98, 'learning_rate': 0.0461811139002877, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8269378858593422, 'min_samples_leaf': 86}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  69%|██████▉   | 346/500 [13:20<05:04,  1.98s/it]

[I 2026-05-18 16:08:21,550] Trial 345 finished with value: 0.9496170588512969 and parameters: {'max_iter': 98, 'learning_rate': 0.03571325150520479, 'max_depth': 2, 'max_leaf_nodes': 8, 'l2_regularization': 0.8133094285998078, 'min_samples_leaf': 82}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:08:21,568] Trial 349 pruned.

Best trial: 188. Best value: 0.949757:  70%|██████▉   | 348/500 [13:21<03:01,  1.20s/it]

[I 2026-05-18 16:08:22,109] Trial 347 finished with value: 0.9491897108465654 and parameters: {'max_iter': 97, 'learning_rate': 0.03590671981762263, 'max_depth': 3, 'max_leaf_nodes': 3, 'l2_regularization': 0.7681528402631991, 'min_samples_leaf': 71}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  70%|██████▉   | 349/500 [13:23<04:01,  1.60s/it]

[I 2026-05-18 16:08:24,948] Trial 342 finished with value: 0.9497128289648191 and parameters: {'max_iter': 98, 'learning_rate': 0.04555842071770978, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 12.852194324890858, 'min_samples_leaf': 83}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  70%|███████   | 350/500 [13:31<07:53,  3.16s/it]

[I 2026-05-18 16:08:32,485] Trial 346 finished with value: 0.9497360284238333 and parameters: {'max_iter': 97, 'learning_rate': 0.049853034614405635, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.791894368318817, 'min_samples_leaf': 83}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  70%|███████   | 351/500 [13:33<07:23,  2.98s/it]

[I 2026-05-18 16:08:34,997] Trial 348 finished with value: 0.949711716366048 and parameters: {'max_iter': 98, 'learning_rate': 0.04642452328347216, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.3236776835239867, 'min_samples_leaf': 72}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  70%|███████   | 352/500 [13:39<09:05,  3.69s/it]

[I 2026-05-18 16:08:40,501] Trial 350 finished with value: 0.9495160014965233 and parameters: {'max_iter': 98, 'learning_rate': 0.021129835370628503, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.2472587115576512, 'min_samples_leaf': 71}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  71%|███████   | 353/500 [13:45<10:22,  4.24s/it]

[I 2026-05-18 16:08:46,110] Trial 351 finished with value: 0.9496745535555128 and parameters: {'max_iter': 97, 'learning_rate': 0.0369064535702934, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6337283152445742, 'min_samples_leaf': 71}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  71%|███████   | 354/500 [13:45<07:28,  3.07s/it]

[I 2026-05-18 16:08:46,325] Trial 352 finished with value: 0.9490503588330587 and parameters: {'max_iter': 97, 'learning_rate': 0.012073491450302135, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.3034065350225714, 'min_samples_leaf': 71}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:08:46,360] Trial 353 finished with value: 0.9496779579063224 and parameters: {'max_iter': 96, 'learning_rate': 0.0359960684717283, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.359561246045365, 'min_samples_leaf': 71}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  71%|███████   | 356/500 [13:50<06:38,  2.77s/it]

[I 2026-05-18 16:08:51,146] Trial 355 finished with value: 0.9497428509533732 and parameters: {'max_iter': 96, 'learning_rate': 0.049995272208784886, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.2510070988481568, 'min_samples_leaf': 70}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  71%|███████▏  | 357/500 [13:50<05:12,  2.18s/it]

[I 2026-05-18 16:08:51,515] Trial 356 finished with value: 0.9497181973856852 and parameters: {'max_iter': 96, 'learning_rate': 0.04951507420711379, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 19.08993872909437, 'min_samples_leaf': 72}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  72%|███████▏  | 358/500 [13:52<05:01,  2.12s/it]

[I 2026-05-18 16:08:53,449] Trial 358 finished with value: 0.9497263982895536 and parameters: {'max_iter': 96, 'learning_rate': 0.049786941896236836, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.2750662992784962, 'min_samples_leaf': 64}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  72%|███████▏  | 359/500 [13:53<04:04,  1.73s/it]

[I 2026-05-18 16:08:54,135] Trial 357 finished with value: 0.9497248798390652 and parameters: {'max_iter': 96, 'learning_rate': 0.0494349249814909, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.34937118044757, 'min_samples_leaf': 72}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  72%|███████▏  | 360/500 [13:53<03:16,  1.40s/it]

[I 2026-05-18 16:08:54,675] Trial 359 finished with value: 0.9497074315352639 and parameters: {'max_iter': 96, 'learning_rate': 0.043196462793005194, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.3184463503885508, 'min_samples_leaf': 67}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  72%|███████▏  | 361/500 [13:55<03:43,  1.61s/it]

[I 2026-05-18 16:08:56,797] Trial 360 finished with value: 0.9497244174195976 and parameters: {'max_iter': 96, 'learning_rate': 0.049047953276486624, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 7.1303112694354756, 'min_samples_leaf': 64}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  73%|███████▎  | 363/500 [14:04<05:46,  2.53s/it]

[I 2026-05-18 16:09:05,040] Trial 361 finished with value: 0.9497325218311163 and parameters: {'max_iter': 96, 'learning_rate': 0.04993865977523311, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.3257539938748164, 'min_samples_leaf': 274}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:09:05,141] Trial 372 pruned.

Best trial: 188. Best value: 0.949757:  73%|███████▎  | 364/500 [14:06<05:38,  2.49s/it]

[I 2026-05-18 16:09:07,544] Trial 362 finished with value: 0.9497322347420608 and parameters: {'max_iter': 96, 'learning_rate': 0.0498832416975172, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6290165438977899, 'min_samples_leaf': 63}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  73%|███████▎  | 365/500 [14:11<07:22,  3.28s/it]

[I 2026-05-18 16:09:12,712] Trial 363 finished with value: 0.94973741377857 and parameters: {'max_iter': 96, 'learning_rate': 0.04966959314941565, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6253176254977845, 'min_samples_leaf': 63}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  73%|███████▎  | 367/500 [14:17<06:05,  2.75s/it]

[I 2026-05-18 16:09:17,883] Trial 367 finished with value: 0.949677253446964 and parameters: {'max_iter': 77, 'learning_rate': 0.04344732732093651, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9557786971944302, 'min_samples_leaf': 63}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:09:18,059] Trial 364 finished with value: 0.9497318293248531 and parameters: {'max_iter': 96, 'learning_rate': 0.049466611993076164, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9269377281089327, 'min_samples_leaf': 63}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  74%|███████▎  | 368/500 [14:17<04:24,  2.00s/it]

[I 2026-05-18 16:09:18,292] Trial 365 finished with value: 0.9497174651622764 and parameters: {'max_iter': 96, 'learning_rate': 0.04312874970498453, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6161066879079989, 'min_samples_leaf': 61}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:09:18,306] Trial 366 finished with value: 0.9497185035268595 and parameters: {'max_iter': 95, 'learning_rate': 0.04973232715492789, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6104463400256891, 'min_samples_leaf': 63}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  74%|███████▍  | 370/500 [14:22<05:10,  2.39s/it]

[I 2026-05-18 16:09:23,973] Trial 368 finished with value: 0.9497002246094164 and parameters: {'max_iter': 95, 'learning_rate': 0.0433926948394227, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9634256791146395, 'min_samples_leaf': 61}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  74%|███████▍  | 371/500 [14:24<04:36,  2.14s/it]

[I 2026-05-18 16:09:25,356] Trial 369 finished with value: 0.9496954368817516 and parameters: {'max_iter': 95, 'learning_rate': 0.043038433338362186, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6310645324211509, 'min_samples_leaf': 62}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  74%|███████▍  | 372/500 [14:25<03:44,  1.76s/it]

[I 2026-05-18 16:09:26,056] Trial 370 finished with value: 0.9496904127710953 and parameters: {'max_iter': 95, 'learning_rate': 0.04315376333398598, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9399429956766573, 'min_samples_leaf': 62}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  75%|███████▍  | 373/500 [14:26<03:25,  1.62s/it]

[I 2026-05-18 16:09:27,297] Trial 371 finished with value: 0.9497265733570288 and parameters: {'max_iter': 95, 'learning_rate': 0.049921311295999415, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9550990979127084, 'min_samples_leaf': 61}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  75%|███████▌  | 375/500 [14:37<06:18,  3.03s/it]

[I 2026-05-18 16:09:38,015] Trial 373 finished with value: 0.9496958362371639 and parameters: {'max_iter': 100, 'learning_rate': 0.04310164845323658, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.9714160560733363, 'min_samples_leaf': 61}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:09:38,177] Trial 374 finished with value: 0.9497130352193132 and parameters: {'max_iter': 100, 'learning_rate': 0.04311335271762819, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6557806445352538, 'min_samples_leaf': 63}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  75%|███████▌  | 376/500 [14:40<06:09,  2.98s/it]

[I 2026-05-18 16:09:41,056] Trial 375 finished with value: 0.9497127921608923 and parameters: {'max_iter': 100, 'learning_rate': 0.043439365090819915, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9641688231830319, 'min_samples_leaf': 60}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  75%|███████▌  | 377/500 [14:44<07:17,  3.55s/it]

[I 2026-05-18 16:09:45,997] Trial 376 finished with value: 0.9497330943101607 and parameters: {'max_iter': 100, 'learning_rate': 0.04324039371583025, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9664546714737349, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  76%|███████▌  | 378/500 [14:49<08:00,  3.94s/it]

[I 2026-05-18 16:09:50,863] Trial 378 finished with value: 0.9497033980080187 and parameters: {'max_iter': 100, 'learning_rate': 0.04332189574942943, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1644310238120956, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:09:50,878] Trial 377 finished with value: 0.9497091903878709 and parameters: {'max_iter': 100, 'learning_rate': 0.04358585835597289, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.937572789447936, 'min_samples_leaf': 60}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  76%|███████▌  | 380/500 [14:50<04:24,  2.21s/it]

[I 2026-05-18 16:09:51,160] Trial 379 finished with value: 0.9497108573564059 and parameters: {'max_iter': 100, 'learning_rate': 0.04334684123116422, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1494315106313748, 'min_samples_leaf': 77}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  76%|███████▌  | 381/500 [14:50<03:26,  1.74s/it]

[I 2026-05-18 16:09:51,402] Trial 380 finished with value: 0.949709315286885 and parameters: {'max_iter': 100, 'learning_rate': 0.043228090353067995, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 2.09939255478399, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  76%|███████▋  | 382/500 [14:56<05:29,  2.79s/it]

[I 2026-05-18 16:09:57,265] Trial 381 finished with value: 0.9497030545941005 and parameters: {'max_iter': 100, 'learning_rate': 0.043299095665526685, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.163515042146812, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  77%|███████▋  | 383/500 [14:57<04:41,  2.40s/it]

[I 2026-05-18 16:09:58,616] Trial 382 finished with value: 0.9497155026836183 and parameters: {'max_iter': 100, 'learning_rate': 0.04344377466187817, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.158552565929182, 'min_samples_leaf': 51}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  77%|███████▋  | 384/500 [14:58<03:40,  1.90s/it]

[I 2026-05-18 16:09:59,187] Trial 383 finished with value: 0.9497149030629586 and parameters: {'max_iter': 100, 'learning_rate': 0.04573532985258391, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.9770261369698772, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  77%|███████▋  | 385/500 [14:59<03:21,  1.75s/it]

[I 2026-05-18 16:10:00,577] Trial 384 finished with value: 0.9497080510406206 and parameters: {'max_iter': 100, 'learning_rate': 0.04387978544278222, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1549286776003942, 'min_samples_leaf': 51}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  77%|███████▋  | 386/500 [15:09<07:34,  3.99s/it]

[I 2026-05-18 16:10:10,065] Trial 391 pruned.

Best trial: 188. Best value: 0.949757:  77%|███████▋  | 387/500 [15:09<05:31,  2.94s/it]

[I 2026-05-18 16:10:10,445] Trial 386 finished with value: 0.9497388877806076 and parameters: {'max_iter': 100, 'learning_rate': 0.045416476269894125, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7217753665524269, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  78%|███████▊  | 388/500 [15:10<04:16,  2.29s/it]

[I 2026-05-18 16:10:11,214] Trial 385 finished with value: 0.9497474553163384 and parameters: {'max_iter': 100, 'learning_rate': 0.04583692305569651, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7231171466583113, 'min_samples_leaf': 331}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  78%|███████▊  | 389/500 [15:13<04:34,  2.47s/it]

[I 2026-05-18 16:10:14,116] Trial 387 finished with value: 0.9497312596969062 and parameters: {'max_iter': 99, 'learning_rate': 0.045688102999584354, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1179566670974768, 'min_samples_leaf': 77}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  78%|███████▊  | 390/500 [15:15<04:35,  2.50s/it]

[I 2026-05-18 16:10:16,681] Trial 394 pruned.

Best trial: 188. Best value: 0.949757:  78%|███████▊  | 391/500 [15:17<04:12,  2.31s/it]

[I 2026-05-18 16:10:18,490] Trial 396 pruned.

Best trial: 188. Best value: 0.949757:  78%|███████▊  | 392/500 [15:18<03:23,  1.89s/it]

[I 2026-05-18 16:10:19,441] Trial 388 finished with value: 0.9497283137436436 and parameters: {'max_iter': 99, 'learning_rate': 0.045797500606087706, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1470382775555479, 'min_samples_leaf': 50}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  79%|███████▊  | 393/500 [15:22<04:29,  2.52s/it]

[I 2026-05-18 16:10:23,424] Trial 389 finished with value: 0.9497219089324795 and parameters: {'max_iter': 98, 'learning_rate': 0.046430105617205605, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7130101357205875, 'min_samples_leaf': 77}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  79%|███████▉  | 394/500 [15:22<03:15,  1.84s/it]

[I 2026-05-18 16:10:23,699] Trial 390 finished with value: 0.9497105399759607 and parameters: {'max_iter': 98, 'learning_rate': 0.04607901934870959, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1550013566666428, 'min_samples_leaf': 76}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  79%|███████▉  | 395/500 [15:23<02:50,  1.62s/it]

[I 2026-05-18 16:10:24,809] Trial 392 finished with value: 0.9497121137198059 and parameters: {'max_iter': 98, 'learning_rate': 0.04620789775197132, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7357950540571071, 'min_samples_leaf': 77}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  79%|███████▉  | 396/500 [15:29<04:52,  2.81s/it]

[I 2026-05-18 16:10:30,329] Trial 393 finished with value: 0.9497368162276147 and parameters: {'max_iter': 98, 'learning_rate': 0.04632327920935213, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.4940616137665102, 'min_samples_leaf': 97}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  79%|███████▉  | 397/500 [15:30<03:59,  2.32s/it]

[I 2026-05-18 16:10:31,596] Trial 395 finished with value: 0.9497167006174603 and parameters: {'max_iter': 98, 'learning_rate': 0.046616396763352205, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7447772050037194, 'min_samples_leaf': 184}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  80%|███████▉  | 399/500 [15:39<05:16,  3.13s/it]

[I 2026-05-18 16:10:40,822] Trial 397 finished with value: 0.9496879425644451 and parameters: {'max_iter': 91, 'learning_rate': 0.039283072028253985, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7376255306076658, 'min_samples_leaf': 251}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:10:41,010] Trial 398 finished with value: 0.9496753273866492 and parameters: {'max_iter': 91, 'learning_rate': 0.038493323349834886, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7466189304675888, 'min_samples_leaf': 97}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  80%|████████  | 400/500 [15:42<05:01,  3.02s/it]

[I 2026-05-18 16:10:43,752] Trial 399 finished with value: 0.9496902342482082 and parameters: {'max_iter': 98, 'learning_rate': 0.038454197861226856, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5095146467846633, 'min_samples_leaf': 399}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  80%|████████  | 401/500 [15:43<03:55,  2.37s/it]

[I 2026-05-18 16:10:44,638] Trial 400 finished with value: 0.9496811274970194 and parameters: {'max_iter': 91, 'learning_rate': 0.03850097851382351, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7285709470471688, 'min_samples_leaf': 320}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  80%|████████  | 402/500 [15:48<05:00,  3.07s/it]

[I 2026-05-18 16:10:49,312] Trial 401 finished with value: 0.9496943028399896 and parameters: {'max_iter': 98, 'learning_rate': 0.03842259463699331, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.48220283947559583, 'min_samples_leaf': 258}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  81%|████████  | 403/500 [15:49<04:05,  2.53s/it]

[I 2026-05-18 16:10:50,519] Trial 410 pruned.

Best trial: 188. Best value: 0.949757:  81%|████████  | 404/500 [15:49<03:00,  1.88s/it]

[I 2026-05-18 16:10:50,948] Trial 402 finished with value: 0.949696012111407 and parameters: {'max_iter': 98, 'learning_rate': 0.03965171879973788, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5043495362778364, 'min_samples_leaf': 254}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  81%|████████  | 405/500 [15:51<02:53,  1.83s/it]

[I 2026-05-18 16:10:52,661] Trial 403 finished with value: 0.9496960979398175 and parameters: {'max_iter': 98, 'learning_rate': 0.03946154289867338, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5450560304397795, 'min_samples_leaf': 398}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  81%|████████  | 406/500 [15:52<02:21,  1.50s/it]

[I 2026-05-18 16:10:53,391] Trial 407 finished with value: 0.9496658122894232 and parameters: {'max_iter': 66, 'learning_rate': 0.038218697247812836, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8995350398985729, 'min_samples_leaf': 264}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  81%|████████▏ | 407/500 [15:55<03:00,  1.94s/it]

[I 2026-05-18 16:10:56,365] Trial 404 finished with value: 0.9496788921639459 and parameters: {'max_iter': 98, 'learning_rate': 0.03851623890800969, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 3.4156938826099026, 'min_samples_leaf': 254}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  82%|████████▏ | 408/500 [15:55<02:19,  1.51s/it]

[I 2026-05-18 16:10:56,883] Trial 405 finished with value: 0.9496908425892716 and parameters: {'max_iter': 98, 'learning_rate': 0.03784135141730706, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.504938306204804, 'min_samples_leaf': 183}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  82%|████████▏ | 409/500 [15:57<02:14,  1.47s/it]

[I 2026-05-18 16:10:58,256] Trial 406 finished with value: 0.9496846898246005 and parameters: {'max_iter': 98, 'learning_rate': 0.03870254113498148, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5165596320967875, 'min_samples_leaf': 258}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  82%|████████▏ | 410/500 [16:01<03:38,  2.43s/it]

[I 2026-05-18 16:11:02,904] Trial 411 pruned.

Best trial: 188. Best value: 0.949757:  82%|████████▏ | 411/500 [16:03<03:07,  2.10s/it]

[I 2026-05-18 16:11:04,264] Trial 408 finished with value: 0.949686235212481 and parameters: {'max_iter': 97, 'learning_rate': 0.03879435325965902, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9090515263511363, 'min_samples_leaf': 87}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  82%|████████▏ | 412/500 [16:12<06:10,  4.21s/it]

[I 2026-05-18 16:11:13,390] Trial 409 finished with value: 0.9496861751286388 and parameters: {'max_iter': 97, 'learning_rate': 0.03868049088673003, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5191784691524645, 'min_samples_leaf': 397}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  83%|████████▎ | 413/500 [16:16<06:09,  4.25s/it]

[I 2026-05-18 16:11:17,737] Trial 412 finished with value: 0.9497263026392142 and parameters: {'max_iter': 97, 'learning_rate': 0.04722026646689822, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9218490911006227, 'min_samples_leaf': 362}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  83%|████████▎ | 414/500 [16:18<05:00,  3.50s/it]

[I 2026-05-18 16:11:19,461] Trial 420 finished with value: 0.9496516954702731 and parameters: {'max_iter': 95, 'learning_rate': 0.04976591833859246, 'max_depth': 3, 'max_leaf_nodes': 3, 'l2_regularization': 1.4651653435039746, 'min_samples_leaf': 87}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  83%|████████▎ | 415/500 [16:20<04:31,  3.19s/it]

[I 2026-05-18 16:11:21,961] Trial 413 finished with value: 0.9497243961938855 and parameters: {'max_iter': 95, 'learning_rate': 0.047483425881376565, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9240599552165616, 'min_samples_leaf': 86}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  83%|████████▎ | 416/500 [16:21<03:21,  2.40s/it]

[I 2026-05-18 16:11:22,516] Trial 414 finished with value: 0.9497318982852505 and parameters: {'max_iter': 95, 'learning_rate': 0.04985575921446261, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9105093964754399, 'min_samples_leaf': 72}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  83%|████████▎ | 417/500 [16:22<02:45,  2.00s/it]

[I 2026-05-18 16:11:23,572] Trial 415 finished with value: 0.9497196515879057 and parameters: {'max_iter': 95, 'learning_rate': 0.04719222459495768, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.418371857276514, 'min_samples_leaf': 87}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  84%|████████▎ | 418/500 [16:24<02:35,  1.90s/it]

[I 2026-05-18 16:11:25,243] Trial 416 finished with value: 0.9497178082333184 and parameters: {'max_iter': 96, 'learning_rate': 0.046970884086297, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.4716437147288415, 'min_samples_leaf': 70}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  84%|████████▍ | 419/500 [16:24<02:02,  1.51s/it]

[I 2026-05-18 16:11:25,850] Trial 417 finished with value: 0.9497102858634415 and parameters: {'max_iter': 95, 'learning_rate': 0.04681849540076134, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.4678634020893682, 'min_samples_leaf': 284}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  84%|████████▍ | 420/500 [16:27<02:24,  1.81s/it]

[I 2026-05-18 16:11:28,333] Trial 418 finished with value: 0.949190976081972 and parameters: {'max_iter': 95, 'learning_rate': 0.014638869904277412, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.483542997914635, 'min_samples_leaf': 287}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  84%|████████▍ | 421/500 [16:28<02:10,  1.65s/it]

[I 2026-05-18 16:11:29,617] Trial 419 finished with value: 0.9497167959886212 and parameters: {'max_iter': 95, 'learning_rate': 0.04701546532946756, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.5370694868235213, 'min_samples_leaf': 426}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  84%|████████▍ | 422/500 [16:33<03:35,  2.77s/it]

[I 2026-05-18 16:11:34,993] Trial 423 finished with value: 0.9496187397644762 and parameters: {'max_iter': 95, 'learning_rate': 0.046947555282170976, 'max_depth': 3, 'max_leaf_nodes': 3, 'l2_regularization': 1.489851833921041, 'min_samples_leaf': 69}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  85%|████████▍ | 423/500 [16:34<02:42,  2.12s/it]

[I 2026-05-18 16:11:35,597] Trial 421 finished with value: 0.9497150710076042 and parameters: {'max_iter': 95, 'learning_rate': 0.0470419397093052, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.4159448649270436, 'min_samples_leaf': 87}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  85%|████████▍ | 424/500 [16:34<01:59,  1.57s/it]

[I 2026-05-18 16:11:35,824] Trial 432 pruned.

Best trial: 188. Best value: 0.949757:  85%|████████▌ | 425/500 [16:35<01:43,  1.38s/it]

[I 2026-05-18 16:11:36,815] Trial 431 pruned.

Best trial: 188. Best value: 0.949757:  85%|████████▌ | 426/500 [16:36<01:27,  1.18s/it]

[I 2026-05-18 16:11:37,537] Trial 422 finished with value: 0.9497315824933498 and parameters: {'max_iter': 95, 'learning_rate': 0.04983038156003078, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.427119328024442, 'min_samples_leaf': 441}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  85%|████████▌ | 427/500 [16:37<01:29,  1.23s/it]

[I 2026-05-18 16:11:38,862] Trial 430 finished with value: 0.949217341562893 and parameters: {'max_iter': 30, 'learning_rate': 0.049589377346061114, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6586116134607124, 'min_samples_leaf': 68}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  86%|████████▌ | 428/500 [16:40<02:10,  1.81s/it]

[I 2026-05-18 16:11:42,030] Trial 427 pruned.

Best trial: 188. Best value: 0.949757:  86%|████████▌ | 429/500 [16:43<02:17,  1.94s/it]

[I 2026-05-18 16:11:44,294] Trial 428 pruned.

Best trial: 188. Best value: 0.949757:  86%|████████▌ | 430/500 [16:49<03:48,  3.26s/it]

[I 2026-05-18 16:11:50,636] Trial 424 finished with value: 0.9497280588259374 and parameters: {'max_iter': 95, 'learning_rate': 0.049963950127790833, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.432165069355869, 'min_samples_leaf': 69}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  86%|████████▌ | 431/500 [16:50<03:02,  2.64s/it]

[I 2026-05-18 16:11:51,821] Trial 425 finished with value: 0.9492507278868517 and parameters: {'max_iter': 95, 'learning_rate': 0.015516271576746368, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6380016566287173, 'min_samples_leaf': 369}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  86%|████████▋ | 432/500 [16:53<03:06,  2.74s/it]

[I 2026-05-18 16:11:54,798] Trial 426 finished with value: 0.9497274190013419 and parameters: {'max_iter': 95, 'learning_rate': 0.049644492382970265, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6358526547638382, 'min_samples_leaf': 144}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  87%|████████▋ | 433/500 [16:54<02:27,  2.20s/it]

[I 2026-05-18 16:11:55,737] Trial 435 pruned.

Best trial: 188. Best value: 0.949757:  87%|████████▋ | 434/500 [16:59<03:10,  2.89s/it]

[I 2026-05-18 16:12:00,228] Trial 429 finished with value: 0.9497442305623917 and parameters: {'max_iter': 100, 'learning_rate': 0.04977979277844109, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6363306754183907, 'min_samples_leaf': 69}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  87%|████████▋ | 435/500 [17:01<02:54,  2.68s/it]

[I 2026-05-18 16:12:02,406] Trial 442 pruned.

Best trial: 188. Best value: 0.949757:  87%|████████▋ | 436/500 [17:05<03:10,  2.97s/it]

[I 2026-05-18 16:12:06,087] Trial 443 pruned.

Best trial: 188. Best value: 0.949757:  87%|████████▋ | 437/500 [17:07<03:00,  2.86s/it]

[I 2026-05-18 16:12:08,678] Trial 433 finished with value: 0.949738553691765 and parameters: {'max_iter': 100, 'learning_rate': 0.049796722713054416, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6347996679843179, 'min_samples_leaf': 371}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  88%|████████▊ | 438/500 [17:08<02:21,  2.28s/it]

[I 2026-05-18 16:12:09,603] Trial 434 finished with value: 0.9497351126323318 and parameters: {'max_iter': 100, 'learning_rate': 0.04978595157173117, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.052689823129822, 'min_samples_leaf': 229}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  88%|████████▊ | 439/500 [17:10<02:05,  2.05s/it]

[I 2026-05-18 16:12:11,119] Trial 436 finished with value: 0.9497066852095607 and parameters: {'max_iter': 100, 'learning_rate': 0.04179499364662973, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6019475353784592, 'min_samples_leaf': 438}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  88%|████████▊ | 440/500 [17:10<01:30,  1.52s/it]

[I 2026-05-18 16:12:11,382] Trial 445 pruned.

Best trial: 188. Best value: 0.949757:  88%|████████▊ | 441/500 [17:10<01:07,  1.15s/it]

[I 2026-05-18 16:12:11,670] Trial 437 finished with value: 0.9497063216074985 and parameters: {'max_iter': 100, 'learning_rate': 0.041705870238845894, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6168909069535912, 'min_samples_leaf': 60}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  88%|████████▊ | 442/500 [17:12<01:15,  1.31s/it]

[I 2026-05-18 16:12:13,365] Trial 438 finished with value: 0.9497139892365363 and parameters: {'max_iter': 100, 'learning_rate': 0.041823627579789864, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0127804397249593, 'min_samples_leaf': 163}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  89%|████████▊ | 443/500 [17:15<01:38,  1.74s/it]

[I 2026-05-18 16:12:16,099] Trial 439 finished with value: 0.9497202535787374 and parameters: {'max_iter': 100, 'learning_rate': 0.042085971711957104, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.0650491991460818, 'min_samples_leaf': 57}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  89%|████████▉ | 444/500 [17:17<01:55,  2.05s/it]

[I 2026-05-18 16:12:18,896] Trial 440 finished with value: 0.9496982001174812 and parameters: {'max_iter': 100, 'learning_rate': 0.04148045433871808, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7959666587336955, 'min_samples_leaf': 59}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  89%|████████▉ | 445/500 [17:19<01:46,  1.94s/it]

[I 2026-05-18 16:12:20,564] Trial 446 finished with value: 0.9495266869210729 and parameters: {'max_iter': 48, 'learning_rate': 0.04227291752947084, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8165061252533379, 'min_samples_leaf': 58}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  89%|████████▉ | 446/500 [17:23<02:21,  2.61s/it]

[I 2026-05-18 16:12:24,693] Trial 441 finished with value: 0.9497145645119284 and parameters: {'max_iter': 100, 'learning_rate': 0.04159821257778957, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8106434535337674, 'min_samples_leaf': 235}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  90%|████████▉ | 448/500 [17:28<02:00,  2.31s/it]

[I 2026-05-18 16:12:29,435] Trial 448 finished with value: 0.9496432533236681 and parameters: {'max_iter': 58, 'learning_rate': 0.04278040048139971, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8085665072403279, 'min_samples_leaf': 307}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:12:29,580] Trial 444 finished with value: 0.9497022282919121 and parameters: {'max_iter': 99, 'learning_rate': 0.041598055108392186, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.823265170538663, 'min_samples_leaf': 58}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  90%|████████▉ | 449/500 [17:38<03:54,  4.61s/it]

[I 2026-05-18 16:12:39,554] Trial 447 finished with value: 0.949713953897119 and parameters: {'max_iter': 99, 'learning_rate': 0.04244435425010504, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8120629379893977, 'min_samples_leaf': 59}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  90%|█████████ | 450/500 [17:41<03:22,  4.04s/it]

[I 2026-05-18 16:12:42,281] Trial 449 finished with value: 0.9496748802715478 and parameters: {'max_iter': 98, 'learning_rate': 0.04243289430203746, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 37.23982496409336, 'min_samples_leaf': 58}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  90%|█████████ | 451/500 [17:42<02:41,  3.29s/it]

[I 2026-05-18 16:12:43,825] Trial 450 finished with value: 0.9497166626563007 and parameters: {'max_iter': 98, 'learning_rate': 0.044725765347980014, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8139758489939324, 'min_samples_leaf': 58}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  90%|█████████ | 452/500 [17:43<01:56,  2.42s/it]

[I 2026-05-18 16:12:44,213] Trial 451 finished with value: 0.9497034304309068 and parameters: {'max_iter': 97, 'learning_rate': 0.04474044010834397, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8237038774538286, 'min_samples_leaf': 58}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  91%|█████████ | 453/500 [17:43<01:23,  1.77s/it]

[I 2026-05-18 16:12:44,481] Trial 452 finished with value: 0.9497083047218331 and parameters: {'max_iter': 97, 'learning_rate': 0.04523217498249457, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.82619683890589, 'min_samples_leaf': 59}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  91%|█████████ | 454/500 [17:44<01:18,  1.70s/it]

[I 2026-05-18 16:12:45,998] Trial 453 finished with value: 0.9497151080899991 and parameters: {'max_iter': 97, 'learning_rate': 0.04509383773325083, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8396541204694137, 'min_samples_leaf': 59}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  91%|█████████ | 455/500 [17:47<01:32,  2.06s/it]

[I 2026-05-18 16:12:48,900] Trial 454 finished with value: 0.9497256885318774 and parameters: {'max_iter': 97, 'learning_rate': 0.04567172056806806, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8274783125398313, 'min_samples_leaf': 59}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  91%|█████████ | 456/500 [17:50<01:38,  2.24s/it]

[I 2026-05-18 16:12:51,552] Trial 455 finished with value: 0.9497169427266394 and parameters: {'max_iter': 97, 'learning_rate': 0.045505871224885294, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8255581840145293, 'min_samples_leaf': 74}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  91%|█████████▏| 457/500 [17:52<01:39,  2.31s/it]

[I 2026-05-18 16:12:54,018] Trial 456 finished with value: 0.9497159787017578 and parameters: {'max_iter': 97, 'learning_rate': 0.045661686113768, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8669809553568054, 'min_samples_leaf': 75}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  92%|█████████▏| 459/500 [17:54<00:56,  1.37s/it]

[I 2026-05-18 16:12:54,985] Trial 464 pruned.
[I 2026-05-18 16:12:55,105] Trial 463 pruned.

Best trial: 188. Best value: 0.949757:  92%|█████████▏| 460/500 [17:56<01:12,  1.81s/it]

[I 2026-05-18 16:12:57,942] Trial 457 finished with value: 0.9497217836417657 and parameters: {'max_iter': 97, 'learning_rate': 0.04545172401295169, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.3700075028345246, 'min_samples_leaf': 76}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  92%|█████████▏| 461/500 [18:01<01:41,  2.61s/it]

[I 2026-05-18 16:13:02,422] Trial 459 finished with value: 0.9497216527373495 and parameters: {'max_iter': 97, 'learning_rate': 0.04573713033062905, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.8999065367009756, 'min_samples_leaf': 75}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:13:02,446] Trial 458 finished with value: 0.9497157469996583 and parameters: {'max_iter': 97, 'learning_rate': 0.04565505322770444, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.3767973199205262, 'min_samples_leaf': 78}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  93%|█████████▎| 463/500 [18:11<02:19,  3.77s/it]

[I 2026-05-18 16:13:12,680] Trial 460 finished with value: 0.9497222809979128 and parameters: {'max_iter': 97, 'learning_rate': 0.04585988787856158, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.1791841499455515, 'min_samples_leaf': 74}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  93%|█████████▎| 464/500 [18:14<02:11,  3.65s/it]

[I 2026-05-18 16:13:15,955] Trial 461 finished with value: 0.9497229427762107 and parameters: {'max_iter': 97, 'learning_rate': 0.0459061524664546, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.2169366120598355, 'min_samples_leaf': 74}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  93%|█████████▎| 465/500 [18:16<01:47,  3.08s/it]

[I 2026-05-18 16:13:17,448] Trial 462 finished with value: 0.9497186805376391 and parameters: {'max_iter': 97, 'learning_rate': 0.045864224212305474, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.223329305407778, 'min_samples_leaf': 74}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  93%|█████████▎| 466/500 [18:17<01:25,  2.51s/it]

[I 2026-05-18 16:13:18,428] Trial 465 finished with value: 0.9497287330958676 and parameters: {'max_iter': 97, 'learning_rate': 0.049933821005891395, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 1.2370705718208783, 'min_samples_leaf': 75}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  93%|█████████▎| 467/500 [18:20<01:27,  2.66s/it]

[I 2026-05-18 16:13:21,454] Trial 466 finished with value: 0.9497178997166185 and parameters: {'max_iter': 97, 'learning_rate': 0.04691402928858347, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.2425998658214525, 'min_samples_leaf': 76}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  94%|█████████▎| 468/500 [18:21<01:06,  2.08s/it]

[I 2026-05-18 16:13:22,113] Trial 467 finished with value: 0.9497242504833577 and parameters: {'max_iter': 93, 'learning_rate': 0.049786168102298606, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 1.239214487997695, 'min_samples_leaf': 76}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  94%|█████████▍| 469/500 [18:23<01:05,  2.13s/it]

[I 2026-05-18 16:13:24,345] Trial 468 finished with value: 0.9497069927451502 and parameters: {'max_iter': 93, 'learning_rate': 0.04680882658699592, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 1.2220074742841989, 'min_samples_leaf': 79}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  94%|█████████▍| 470/500 [18:24<00:55,  1.85s/it]

[I 2026-05-18 16:13:25,502] Trial 469 finished with value: 0.9497120345007215 and parameters: {'max_iter': 93, 'learning_rate': 0.04995199904853928, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 85.1370035561333, 'min_samples_leaf': 215}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  94%|█████████▍| 471/500 [18:25<00:44,  1.53s/it]

[I 2026-05-18 16:13:26,292] Trial 470 finished with value: 0.9497249810399315 and parameters: {'max_iter': 93, 'learning_rate': 0.04973406206305143, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 1.1985188739772163, 'min_samples_leaf': 96}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  94%|█████████▍| 472/500 [18:28<00:59,  2.13s/it]

[I 2026-05-18 16:13:29,822] Trial 471 finished with value: 0.9497156774236452 and parameters: {'max_iter': 92, 'learning_rate': 0.049970443467133724, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.204011480127195, 'min_samples_leaf': 68}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  95%|█████████▍| 473/500 [18:33<01:20,  3.00s/it]

[I 2026-05-18 16:13:34,878] Trial 473 finished with value: 0.9497326133684891 and parameters: {'max_iter': 98, 'learning_rate': 0.049729205398661123, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7183678333078662, 'min_samples_leaf': 68}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  95%|█████████▍| 474/500 [18:34<01:00,  2.31s/it]

[I 2026-05-18 16:13:35,574] Trial 472 finished with value: 0.9497408975367104 and parameters: {'max_iter': 98, 'learning_rate': 0.04671006435662378, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.2363320201153494, 'min_samples_leaf': 330}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  95%|█████████▌| 475/500 [18:41<01:31,  3.68s/it]

[I 2026-05-18 16:13:42,461] Trial 484 pruned.

Best trial: 188. Best value: 0.949757:  95%|█████████▌| 476/500 [18:43<01:13,  3.07s/it]

[I 2026-05-18 16:13:44,094] Trial 474 finished with value: 0.9497056927325083 and parameters: {'max_iter': 92, 'learning_rate': 0.04975193301868273, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7179328325805628, 'min_samples_leaf': 84}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  95%|█████████▌| 477/500 [18:46<01:13,  3.18s/it]

[I 2026-05-18 16:13:47,549] Trial 475 finished with value: 0.9497183430101375 and parameters: {'max_iter': 93, 'learning_rate': 0.049099720678936865, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7157386667023103, 'min_samples_leaf': 96}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  96%|█████████▌| 478/500 [18:46<00:51,  2.35s/it]

[I 2026-05-18 16:13:47,925] Trial 476 finished with value: 0.9497308108041779 and parameters: {'max_iter': 93, 'learning_rate': 0.049493559059121395, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.7004206427398236, 'min_samples_leaf': 99}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  96%|█████████▌| 479/500 [18:48<00:43,  2.09s/it]

[I 2026-05-18 16:13:49,420] Trial 477 finished with value: 0.9497255414544608 and parameters: {'max_iter': 93, 'learning_rate': 0.04962557733582158, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.7118231568137778, 'min_samples_leaf': 88}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  96%|█████████▌| 480/500 [18:51<00:45,  2.28s/it]

[I 2026-05-18 16:13:52,137] Trial 478 finished with value: 0.949711380122797 and parameters: {'max_iter': 92, 'learning_rate': 0.04965580254009975, 'max_depth': 3, 'max_leaf_nodes': 7, 'l2_regularization': 0.703118885761645, 'min_samples_leaf': 207}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  96%|█████████▌| 481/500 [18:52<00:40,  2.12s/it]

[I 2026-05-18 16:13:53,911] Trial 479 finished with value: 0.9497258568355038 and parameters: {'max_iter': 93, 'learning_rate': 0.0495976174297585, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5689527772272801, 'min_samples_leaf': 94}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  96%|█████████▋| 482/500 [18:56<00:46,  2.57s/it]

[I 2026-05-18 16:13:57,520] Trial 480 finished with value: 0.9491817211673294 and parameters: {'max_iter': 99, 'learning_rate': 0.01295041495746036, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5812312655392857, 'min_samples_leaf': 97}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  97%|█████████▋| 483/500 [18:57<00:37,  2.22s/it]

[I 2026-05-18 16:13:58,921] Trial 481 finished with value: 0.9497393879866038 and parameters: {'max_iter': 99, 'learning_rate': 0.04946430351315498, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.5735855347189709, 'min_samples_leaf': 91}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  97%|█████████▋| 484/500 [18:58<00:28,  1.78s/it]

[I 2026-05-18 16:13:59,668] Trial 482 finished with value: 0.9497361991930715 and parameters: {'max_iter': 99, 'learning_rate': 0.049777286627493, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.6904435213581935, 'min_samples_leaf': 65}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  97%|█████████▋| 486/500 [19:02<00:24,  1.73s/it]

[I 2026-05-18 16:14:03,538] Trial 487 pruned.
[I 2026-05-18 16:14:03,707] Trial 483 finished with value: 0.9497320647384482 and parameters: {'max_iter': 99, 'learning_rate': 0.04969873698730666, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 8.740890436575409, 'min_samples_leaf': 329}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  97%|█████████▋| 487/500 [19:07<00:33,  2.61s/it]

[I 2026-05-18 16:14:08,354] Trial 485 finished with value: 0.9496764502511297 and parameters: {'max_iter': 99, 'learning_rate': 0.0346457551077839, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7028962257690531, 'min_samples_leaf': 337}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  98%|█████████▊| 488/500 [19:14<00:46,  3.87s/it]

[I 2026-05-18 16:14:15,159] Trial 486 finished with value: 0.9497055399217806 and parameters: {'max_iter': 99, 'learning_rate': 0.040510441655191826, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.7335680347977387, 'min_samples_leaf': 343}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  98%|█████████▊| 489/500 [19:19<00:47,  4.34s/it]

[I 2026-05-18 16:14:20,575] Trial 488 finished with value: 0.9496690752732796 and parameters: {'max_iter': 99, 'learning_rate': 0.032857281060753335, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.8129430524365207, 'min_samples_leaf': 340}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  98%|█████████▊| 490/500 [19:20<00:31,  3.18s/it]

[I 2026-05-18 16:14:21,082] Trial 489 finished with value: 0.9497098082163443 and parameters: {'max_iter': 99, 'learning_rate': 0.043544544221311196, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9440808141645657, 'min_samples_leaf': 355}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  98%|█████████▊| 491/500 [19:21<00:23,  2.56s/it]

[I 2026-05-18 16:14:22,189] Trial 490 finished with value: 0.9496677244560366 and parameters: {'max_iter': 99, 'learning_rate': 0.03495966536944231, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9540099590338715, 'min_samples_leaf': 359}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  98%|█████████▊| 492/500 [19:22<00:18,  2.27s/it]

[I 2026-05-18 16:14:23,769] Trial 491 finished with value: 0.9496734121417593 and parameters: {'max_iter': 99, 'learning_rate': 0.03133265153592536, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9574637631362934, 'min_samples_leaf': 66}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  99%|█████████▊| 493/500 [19:24<00:13,  1.99s/it]

[I 2026-05-18 16:14:25,093] Trial 492 finished with value: 0.9496656332162718 and parameters: {'max_iter': 99, 'learning_rate': 0.03534303733714764, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.817755133785129, 'min_samples_leaf': 310}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  99%|█████████▉| 494/500 [19:26<00:11,  2.00s/it]

[I 2026-05-18 16:14:27,142] Trial 493 finished with value: 0.9496757370054052 and parameters: {'max_iter': 99, 'learning_rate': 0.032243688633251895, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.7406071298082324, 'min_samples_leaf': 334}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  99%|█████████▉| 495/500 [19:26<00:08,  1.63s/it]

[I 2026-05-18 16:14:27,915] Trial 494 finished with value: 0.9496974696433453 and parameters: {'max_iter': 99, 'learning_rate': 0.0399013990242706, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9526005951685931, 'min_samples_leaf': 332}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757:  99%|█████████▉| 496/500 [19:27<00:04,  1.23s/it]

[I 2026-05-18 16:14:28,190] Trial 495 finished with value: 0.949692150953332 and parameters: {'max_iter': 99, 'learning_rate': 0.03637616563429741, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9761081218938257, 'min_samples_leaf': 335}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757: 100%|█████████▉| 498/500 [19:28<00:01,  1.15it/s]

[I 2026-05-18 16:14:29,328] Trial 496 finished with value: 0.9496881636314093 and parameters: {'max_iter': 99, 'learning_rate': 0.03476794654505241, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.962265477942625, 'min_samples_leaf': 336}. Best is trial 188 with value: 0.9497571771545005.
[I 2026-05-18 16:14:29,431] Trial 497 finished with value: 0.9496916741164512 and parameters: {'max_iter': 99, 'learning_rate': 0.035967002811773174, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9584148324083663, 'min_samples_leaf': 344}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757: 100%|█████████▉| 499/500 [19:29<00:00,  1.10it/s]

[I 2026-05-18 16:14:30,425] Trial 498 finished with value: 0.9496899307081058 and parameters: {'max_iter': 99, 'learning_rate': 0.0406260443954582, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 1.6974328330950201, 'min_samples_leaf': 67}. Best is trial 188 with value: 0.9497571771545005.

Best trial: 188. Best value: 0.949757: 100%|██████████| 500/500 [19:29<00:00,  2.34s/it]

[I 2026-05-18 16:14:30,917] Trial 499 finished with value: 0.9497146325270144 and parameters: {'max_iter': 100, 'learning_rate': 0.043586054597267186, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.9412982490993115, 'min_samples_leaf': 330}. Best is trial 188 with value: 0.9497571771545005.
Best trial score:
0.9497571771545005

Best params:
{'max_iter': 100, 'learning_rate': 0.049279424968777505, 'max_depth': 3, 'max_leaf_nodes': 8, 'l2_regularization': 0.7407240315476109, 'min_samples_leaf': 65}

In [8]:
stacking_lgbm = HistGradientBoostingClassifier(**study.best_params).fit(X_train, y_train.PitNextLap)

# Submission

In [9]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [10]:
submission['PitNextLap'] = stacking_lgbm.predict_proba(X_test)[:, 1]

In [11]:
submission.to_csv('../data/submission/submission.csv', index=False)

In [12]:
X_train.columns

Index(['lgbm_proba', 'cat_proba', 'xgb_proba', 'hist_proba', 'lg_proba',
       'knn_proba', 'voting_lgbm_cat_xgb_hist_proba',
       'stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba'],
      dtype='str')