# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from catboost import CatBoostClassifier

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import StackingClassifier, VotingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

# Loading Dataset

In [4]:
X_train = pd.read_parquet('../data/processed/X_train_stacking2.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking2.parquet')

In [5]:
X_train.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,voting_lgbm_cat_xgb_hist_proba,stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.868510,0.826590
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.772514,0.801335
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.717012,0.782757
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,0.005494,0.502476
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,0.482416,0.703165

In [6]:
X_test.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,voting_lgbm_cat_xgb_hist_proba,stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,0.019849,0.509303
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,0.012173,0.505573
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,0.010304,0.504827
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.444558,0.696136
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.939648,0.852833

# Machine Learning

In [7]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "C": trial.suggest_float("C", 1e-5, 100, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
        "max_iter": trial.suggest_int("max_iter", 1000, 5000)
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LogisticRegression(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-18 14:58:23,093] A new study created in memory with name: no-name-08c819e9-8a9c-4889-abf8-a79f9842db1b
Best trial: 5. Best value: 0.949618:   0%|          | 1/500 [00:15<2:05:42, 15.12s/it]

[I 2026-05-18 14:58:38,206] Trial 5 finished with value: 0.9496179463819487 and parameters: {'solver': 'saga', 'C': 0.000571582059976165, 'l1_ratio': 0.7144304416479819, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0011410774867599521, 'max_iter': 2003}. Best is trial 5 with value: 0.9496179463819487.
[I 2026-05-18 14:58:38,217] Trial 6 finished with value: 0.9494281854547953 and parameters: {'solver': 'saga', 'C': 0.19816457741260096, 'l1_ratio': 0.032121095903444696, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005588455800719528, 'max_iter': 4360}. Best is trial 5 with value: 0.9496179463819487.

Best trial: 5. Best value: 0.949618:   1%|          | 3/500 [00:15<33:56,  4.10s/it]

[I 2026-05-18 14:58:38,690] Trial 4 finished with value: 0.9492946526973484 and parameters: {'solver': 'saga', 'C': 0.0002936101707099479, 'l1_ratio': 0.22501943435526905, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005089049028739349, 'max_iter': 3023}. Best is trial 5 with value: 0.9496179463819487.

Best trial: 5. Best value: 0.949618:   1%|          | 4/500 [00:16<24:26,  2.96s/it]

[I 2026-05-18 14:58:39,481] Trial 11 finished with value: 0.9495118415112904 and parameters: {'solver': 'saga', 'C': 0.01470034572994281, 'l1_ratio': 0.4210679908759072, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002591840202992654, 'max_iter': 1832}. Best is trial 5 with value: 0.9496179463819487.

Best trial: 10. Best value: 0.949652:   1%|          | 5/500 [00:18<20:57,  2.54s/it]

[I 2026-05-18 14:58:41,188] Trial 10 finished with value: 0.9496515590164046 and parameters: {'solver': 'saga', 'C': 0.0018000459734629365, 'l1_ratio': 0.6491038520128132, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024400750691001393, 'max_iter': 1799}. Best is trial 10 with value: 0.9496515590164046.

Best trial: 10. Best value: 0.949652:   1%|          | 6/500 [00:19<17:13,  2.09s/it]

[I 2026-05-18 14:58:42,331] Trial 2 finished with value: 0.949539024101065 and parameters: {'solver': 'saga', 'C': 0.00018903340092223111, 'l1_ratio': 0.498913839600337, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 8.134245339582149e-05, 'max_iter': 1750}. Best is trial 10 with value: 0.9496515590164046.

Best trial: 10. Best value: 0.949652:   1%|▏         | 7/500 [00:20<15:21,  1.87s/it]

[I 2026-05-18 14:58:43,716] Trial 1 finished with value: 0.949568407583769 and parameters: {'solver': 'saga', 'C': 0.031119678219225812, 'l1_ratio': 0.9111484535179438, 'class_weight': None, 'fit_intercept': False, 'tol': 3.718324692966648e-05, 'max_iter': 3703}. Best is trial 10 with value: 0.9496515590164046.

Best trial: 10. Best value: 0.949652:   2%|▏         | 8/500 [00:23<19:01,  2.32s/it]

[I 2026-05-18 14:58:47,043] Trial 9 finished with value: 0.9494329053150696 and parameters: {'solver': 'saga', 'C': 0.15355216998919757, 'l1_ratio': 0.28871679070761835, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.7593286958827805e-06, 'max_iter': 4352}. Best is trial 10 with value: 0.9496515590164046.

Best trial: 10. Best value: 0.949652:   2%|▏         | 9/500 [00:25<18:06,  2.21s/it]

[I 2026-05-18 14:58:49,008] Trial 14 finished with value: 0.9494250758297526 and parameters: {'solver': 'saga', 'C': 0.191103062124699, 'l1_ratio': 0.3098884084212824, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0038336851250641325, 'max_iter': 4921}. Best is trial 10 with value: 0.9496515590164046.

Best trial: 10. Best value: 0.949652:   2%|▏         | 10/500 [00:27<15:51,  1.94s/it]

[I 2026-05-18 14:58:50,324] Trial 3 finished with value: 0.9495113994408658 and parameters: {'solver': 'saga', 'C': 0.014055526321354823, 'l1_ratio': 0.1980719860096558, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 2.626064004659461e-06, 'max_iter': 2060}. Best is trial 10 with value: 0.9496515590164046.

Best trial: 12. Best value: 0.949698:   2%|▏         | 11/500 [00:28<13:32,  1.66s/it]

[I 2026-05-18 14:58:51,351] Trial 12 finished with value: 0.9496982455322259 and parameters: {'solver': 'saga', 'C': 0.001795637700635626, 'l1_ratio': 0.8263124556924696, 'class_weight': None, 'fit_intercept': False, 'tol': 0.000767716740324803, 'max_iter': 4158}. Best is trial 12 with value: 0.9496982455322259.

Best trial: 12. Best value: 0.949698:   2%|▏         | 12/500 [00:30<14:20,  1.76s/it]

[I 2026-05-18 14:58:53,346] Trial 0 finished with value: 0.949555582752472 and parameters: {'solver': 'saga', 'C': 0.06733467093106413, 'l1_ratio': 0.3428321985039474, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.534015783857778e-06, 'max_iter': 2907}. Best is trial 12 with value: 0.9496982455322259.

Best trial: 12. Best value: 0.949698:   3%|▎         | 13/500 [00:33<17:35,  2.17s/it]

[I 2026-05-18 14:58:56,448] Trial 16 finished with value: 0.9494505458789193 and parameters: {'solver': 'saga', 'C': 0.06431125958425543, 'l1_ratio': 0.08730141683448467, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00046587039739105475, 'max_iter': 2959}. Best is trial 12 with value: 0.9496982455322259.

Best trial: 12. Best value: 0.949698:   3%|▎         | 14/500 [00:34<14:59,  1.85s/it]

[I 2026-05-18 14:58:57,561] Trial 7 finished with value: 0.9495541202470319 and parameters: {'solver': 'saga', 'C': 5.907924116972542, 'l1_ratio': 0.3234312555525529, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.003443090840877145, 'max_iter': 2354}. Best is trial 12 with value: 0.9496982455322259.

Best trial: 12. Best value: 0.949698:   3%|▎         | 15/500 [00:34<11:12,  1.39s/it]

[I 2026-05-18 14:58:57,844] Trial 23 pruned.

Best trial: 12. Best value: 0.949698:   3%|▎         | 16/500 [00:35<09:49,  1.22s/it]

[I 2026-05-18 14:58:58,693] Trial 25 pruned.

Best trial: 12. Best value: 0.949698:   4%|▎         | 18/500 [00:39<12:00,  1.50s/it]

[I 2026-05-18 14:59:02,783] Trial 15 finished with value: 0.9494449282830992 and parameters: {'solver': 'saga', 'C': 0.04676222082412107, 'l1_ratio': 0.9089638689521605, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 3.5486538013908e-05, 'max_iter': 2449}. Best is trial 12 with value: 0.9496982455322259.
[I 2026-05-18 14:59:02,919] Trial 13 finished with value: 0.9494714834559417 and parameters: {'solver': 'saga', 'C': 0.030272698531062882, 'l1_ratio': 0.5558098195141465, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.4869682855996218e-05, 'max_iter': 3326}. Best is trial 12 with value: 0.9496982455322259.

Best trial: 12. Best value: 0.949698:   4%|▍         | 19/500 [00:45<22:29,  2.81s/it]

[I 2026-05-18 14:59:08,777] Trial 20 finished with value: 0.9490057938519392 and parameters: {'solver': 'saga', 'C': 0.00013498148121570436, 'l1_ratio': 0.0258226522788485, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.795453568007416e-05, 'max_iter': 1668}. Best is trial 12 with value: 0.9496982455322259.

Best trial: 12. Best value: 0.949698:   4%|▍         | 20/500 [00:46<16:48,  2.10s/it]

[I 2026-05-18 14:59:09,229] Trial 18 finished with value: 0.9495186134324316 and parameters: {'solver': 'saga', 'C': 3.6194568055060197, 'l1_ratio': 0.2158554955245957, 'class_weight': None, 'fit_intercept': False, 'tol': 8.174945881369339e-06, 'max_iter': 3700}. Best is trial 12 with value: 0.9496982455322259.

Best trial: 12. Best value: 0.949698:   4%|▍         | 21/500 [00:51<25:21,  3.18s/it]

[I 2026-05-18 14:59:14,919] Trial 19 finished with value: 0.9494195395656717 and parameters: {'solver': 'saga', 'C': 0.6173415891131101, 'l1_ratio': 0.25248667308793893, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.81969373194771e-05, 'max_iter': 1897}. Best is trial 12 with value: 0.9496982455322259.

Best trial: 27. Best value: 0.949705:   4%|▍         | 22/500 [00:53<22:20,  2.80s/it]

[I 2026-05-18 14:59:16,856] Trial 27 finished with value: 0.9497048983330643 and parameters: {'solver': 'saga', 'C': 0.002379328372569686, 'l1_ratio': 0.9661947638478516, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012067036417865098, 'max_iter': 3675}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   5%|▍         | 23/500 [00:56<21:23,  2.69s/it]

[I 2026-05-18 14:59:19,288] Trial 26 finished with value: 0.9496716428982033 and parameters: {'solver': 'saga', 'C': 0.0023650278225336332, 'l1_ratio': 0.7258872229186595, 'class_weight': None, 'fit_intercept': True, 'tol': 4.099853222866639e-05, 'max_iter': 1126}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   5%|▍         | 24/500 [00:57<16:55,  2.13s/it]

[I 2026-05-18 14:59:20,120] Trial 8 finished with value: 0.9494947830584873 and parameters: {'solver': 'saga', 'C': 35.31952229179773, 'l1_ratio': 0.1135710901479996, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00040721147143292367, 'max_iter': 2803}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   5%|▌         | 25/500 [00:57<13:38,  1.72s/it]

[I 2026-05-18 14:59:20,879] Trial 28 finished with value: 0.9496831669227521 and parameters: {'solver': 'saga', 'C': 0.002164675393226087, 'l1_ratio': 0.8024454016116439, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016527236773633693, 'max_iter': 3614}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   5%|▌         | 26/500 [00:59<13:27,  1.70s/it]

[I 2026-05-18 14:59:22,545] Trial 21 finished with value: 0.9495324089809454 and parameters: {'solver': 'saga', 'C': 41.88281739149299, 'l1_ratio': 0.707937135578129, 'class_weight': None, 'fit_intercept': True, 'tol': 0.009552092347260897, 'max_iter': 1017}. Best is trial 27 with value: 0.9497048983330643.
[I 2026-05-18 14:59:22,572] Trial 30 finished with value: 0.9496864261742907 and parameters: {'solver': 'saga', 'C': 0.002123567748099844, 'l1_ratio': 0.824651668377242, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001637800377630457, 'max_iter': 4034}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   6%|▌         | 28/500 [01:01<11:13,  1.43s/it]

[I 2026-05-18 14:59:24,728] Trial 29 finished with value: 0.9496872222829067 and parameters: {'solver': 'saga', 'C': 0.0023347424014555137, 'l1_ratio': 0.822541617795381, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000128017771851119, 'max_iter': 3828}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   6%|▌         | 29/500 [01:02<09:32,  1.22s/it]

[I 2026-05-18 14:59:25,325] Trial 31 finished with value: 0.9497009195666809 and parameters: {'solver': 'saga', 'C': 0.002283614238996966, 'l1_ratio': 0.9935222193400116, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0014618494814575673, 'max_iter': 4923}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   6%|▌         | 30/500 [01:03<08:58,  1.15s/it]

[I 2026-05-18 14:59:26,275] Trial 22 finished with value: 0.949529659029667 and parameters: {'solver': 'saga', 'C': 62.93685445458847, 'l1_ratio': 0.7442807901889641, 'class_weight': None, 'fit_intercept': True, 'tol': 0.007571217073662684, 'max_iter': 2846}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   6%|▌         | 31/500 [01:03<07:40,  1.02it/s]

[I 2026-05-18 14:59:26,824] Trial 24 finished with value: 0.9495432363552684 and parameters: {'solver': 'saga', 'C': 6.086701940028479, 'l1_ratio': 0.6594703393959346, 'class_weight': None, 'fit_intercept': True, 'tol': 0.009142857283609267, 'max_iter': 1064}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   6%|▋         | 32/500 [01:05<08:33,  1.10s/it]

[I 2026-05-18 14:59:28,206] Trial 32 finished with value: 0.9496703207121605 and parameters: {'solver': 'saga', 'C': 0.0016339684209817392, 'l1_ratio': 0.7514541600961415, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0017410919795069991, 'max_iter': 1106}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   7%|▋         | 33/500 [01:12<21:52,  2.81s/it]

[I 2026-05-18 14:59:35,314] Trial 33 finished with value: 0.949685622098492 and parameters: {'solver': 'saga', 'C': 0.0021836514336956727, 'l1_ratio': 0.8179420553314494, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019662721384026345, 'max_iter': 4150}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   7%|▋         | 34/500 [01:13<18:05,  2.33s/it]

[I 2026-05-18 14:59:36,462] Trial 36 finished with value: 0.9497012758161727 and parameters: {'solver': 'saga', 'C': 0.003088921256874275, 'l1_ratio': 0.9758194772119595, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0013960929912462227, 'max_iter': 4046}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   7%|▋         | 35/500 [01:14<15:21,  1.98s/it]

[I 2026-05-18 14:59:37,600] Trial 34 finished with value: 0.9496901763731623 and parameters: {'solver': 'saga', 'C': 0.0031344196468716095, 'l1_ratio': 0.8230995550763944, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001822791259102583, 'max_iter': 4021}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   7%|▋         | 36/500 [01:15<13:06,  1.70s/it]

[I 2026-05-18 14:59:38,602] Trial 38 finished with value: 0.94955486904023 and parameters: {'solver': 'saga', 'C': 5.0892516910144754e-05, 'l1_ratio': 0.9863959198522205, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0013928176673875675, 'max_iter': 4161}. Best is trial 27 with value: 0.9497048983330643.
[I 2026-05-18 14:59:38,614] Trial 40 finished with value: 0.9495567579998336 and parameters: {'solver': 'saga', 'C': 7.216012432453754e-05, 'l1_ratio': 0.9828742802170163, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0015461061452747523, 'max_iter': 4903}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   8%|▊         | 38/500 [01:16<08:17,  1.08s/it]

[I 2026-05-18 14:59:39,299] Trial 39 finished with value: 0.9495539292467792 and parameters: {'solver': 'saga', 'C': 4.69237883151378e-05, 'l1_ratio': 0.9481936878238987, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0013723326509338368, 'max_iter': 4688}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   8%|▊         | 39/500 [01:18<10:18,  1.34s/it]

[I 2026-05-18 14:59:41,452] Trial 35 finished with value: 0.9496982721025493 and parameters: {'solver': 'saga', 'C': 0.0030314612362385925, 'l1_ratio': 0.9945501012382749, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0013827520245250587, 'max_iter': 4128}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   8%|▊         | 40/500 [01:24<18:58,  2.48s/it]

[I 2026-05-18 14:59:47,148] Trial 43 finished with value: 0.9496884575657386 and parameters: {'solver': 'saga', 'C': 0.0066132371964218424, 'l1_ratio': 0.9881902237284812, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010020691540810053, 'max_iter': 4697}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   8%|▊         | 41/500 [01:29<24:52,  3.25s/it]

[I 2026-05-18 14:59:52,478] Trial 46 finished with value: 0.9495579741718846 and parameters: {'solver': 'saga', 'C': 7.85096388925985e-05, 'l1_ratio': 0.9726368147387522, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009231953195005476, 'max_iter': 4951}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   8%|▊         | 42/500 [01:30<19:25,  2.54s/it]

[I 2026-05-18 14:59:53,207] Trial 50 finished with value: 0.9496757051348854 and parameters: {'solver': 'saga', 'C': 0.0005200169820323407, 'l1_ratio': 0.9021638932080374, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0026215798162128124, 'max_iter': 4571}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   9%|▉         | 44/500 [01:31<12:13,  1.61s/it]

[I 2026-05-18 14:59:54,517] Trial 37 finished with value: 0.9496987165171827 and parameters: {'solver': 'saga', 'C': 0.002766257923352969, 'l1_ratio': 0.9953058420439861, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016586883243424928, 'max_iter': 4095}. Best is trial 27 with value: 0.9497048983330643.
[I 2026-05-18 14:59:54,682] Trial 48 finished with value: 0.9496929059642261 and parameters: {'solver': 'saga', 'C': 0.007246532464831639, 'l1_ratio': 0.9004654686353986, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007509385219909295, 'max_iter': 4646}. Best is trial 27 with value: 0.9497048983330643.
[I 2026-05-18 14:59:54,695] Trial 41 finished with value: 0.9496882574776766 and parameters: {'solver': 'saga', 'C': 0.006305009194460116, 'l1_ratio': 0.9931181286727185, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0012340878249668653, 'max_iter': 4994}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   9%|▉         | 46/500 [01:31<07:09,  1.06it/s]

[I 2026-05-18 14:59:54,982] Trial 47 finished with value: 0.9496801888055639 and parameters: {'solver': 'saga', 'C': 0.0005996808152770168, 'l1_ratio': 0.9084766058149385, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007272021081240948, 'max_iter': 4677}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:   9%|▉         | 47/500 [01:33<07:46,  1.03s/it]

[I 2026-05-18 14:59:56,268] Trial 49 finished with value: 0.9496907320294102 and parameters: {'solver': 'saga', 'C': 0.009213116568904538, 'l1_ratio': 0.907549782535124, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007451556833503926, 'max_iter': 4593}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  10%|▉         | 48/500 [01:36<12:20,  1.64s/it]

[I 2026-05-18 14:59:59,652] Trial 51 finished with value: 0.9496584548314102 and parameters: {'solver': 'saga', 'C': 0.00028085863716599687, 'l1_ratio': 0.9000090955089747, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002646617998228314, 'max_iter': 3427}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  10%|▉         | 49/500 [01:37<10:27,  1.39s/it]

[I 2026-05-18 15:00:00,366] Trial 45 finished with value: 0.9496867498566278 and parameters: {'solver': 'saga', 'C': 0.008042935545008054, 'l1_ratio': 0.9875453948077488, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000869581621281278, 'max_iter': 4825}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  10%|█         | 50/500 [01:38<09:46,  1.30s/it]

[I 2026-05-18 15:00:01,450] Trial 44 finished with value: 0.9496860368759752 and parameters: {'solver': 'saga', 'C': 0.008600069352454706, 'l1_ratio': 0.9884675593203663, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009575012687825332, 'max_iter': 5000}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  10%|█         | 51/500 [01:41<13:37,  1.82s/it]

[I 2026-05-18 15:00:04,576] Trial 52 finished with value: 0.9496801272959129 and parameters: {'solver': 'saga', 'C': 0.000704571433169723, 'l1_ratio': 0.8876942846654914, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0027670017233970136, 'max_iter': 3325}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  10%|█         | 52/500 [01:46<19:53,  2.67s/it]

[I 2026-05-18 15:00:09,306] Trial 17 finished with value: 0.9495764245310536 and parameters: {'solver': 'saga', 'C': 0.6610799253268047, 'l1_ratio': 0.7187441467643333, 'class_weight': None, 'fit_intercept': True, 'tol': 3.19135996542443e-06, 'max_iter': 1064}. Best is trial 27 with value: 0.9497048983330643.
[I 2026-05-18 15:00:09,357] Trial 53 finished with value: 0.9496711396349224 and parameters: {'solver': 'saga', 'C': 0.000471542259599909, 'l1_ratio': 0.8874324391478841, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006156131065428883, 'max_iter': 3394}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  11%|█         | 54/500 [01:48<15:12,  2.05s/it]

[I 2026-05-18 15:00:11,912] Trial 57 finished with value: 0.9496622658850159 and parameters: {'solver': 'saga', 'C': 0.017994879318332362, 'l1_ratio': 0.9354119747447469, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003340547434133156, 'max_iter': 3403}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  11%|█         | 55/500 [01:49<12:44,  1.72s/it]

[I 2026-05-18 15:00:12,609] Trial 55 finished with value: 0.9496851956376077 and parameters: {'solver': 'saga', 'C': 0.0006141813438189568, 'l1_ratio': 0.9293420878595694, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002934298910234521, 'max_iter': 3400}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  11%|█         | 56/500 [01:50<11:50,  1.60s/it]

[I 2026-05-18 15:00:13,875] Trial 58 finished with value: 0.9495942271363246 and parameters: {'solver': 'saga', 'C': 0.0008215126914924276, 'l1_ratio': 0.5934841462453435, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003260480740057633, 'max_iter': 3366}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  11%|█▏        | 57/500 [01:53<13:59,  1.89s/it]

[I 2026-05-18 15:00:16,565] Trial 60 finished with value: 0.9496965260812347 and parameters: {'solver': 'saga', 'C': 0.0008622166819168579, 'l1_ratio': 0.9428631909543772, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00031019742444728327, 'max_iter': 4395}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  12%|█▏        | 59/500 [01:55<09:37,  1.31s/it]

[I 2026-05-18 15:00:18,038] Trial 63 finished with value: 0.9495741270114009 and parameters: {'solver': 'saga', 'C': 0.026885438863770084, 'l1_ratio': 0.8674887285557632, 'class_weight': None, 'fit_intercept': False, 'tol': 0.004762292701521457, 'max_iter': 4360}. Best is trial 27 with value: 0.9497048983330643.
[I 2026-05-18 15:00:18,167] Trial 59 finished with value: 0.9496571517358874 and parameters: {'solver': 'saga', 'C': 0.019451062258018653, 'l1_ratio': 0.94508646861279, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00036207119423863516, 'max_iter': 4369}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  12%|█▏        | 60/500 [01:55<07:55,  1.08s/it]

[I 2026-05-18 15:00:18,693] Trial 61 finished with value: 0.9496852635916208 and parameters: {'solver': 'saga', 'C': 0.0010181201415420734, 'l1_ratio': 0.8724371913442748, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00032047845059568497, 'max_iter': 4366}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  12%|█▏        | 62/500 [01:57<06:54,  1.06it/s]

[I 2026-05-18 15:00:20,497] Trial 66 finished with value: 0.9497022666949361 and parameters: {'solver': 'saga', 'C': 0.0011646546680736901, 'l1_ratio': 0.8717712375739024, 'class_weight': None, 'fit_intercept': False, 'tol': 0.004669300617178861, 'max_iter': 4398}. Best is trial 27 with value: 0.9497048983330643.
[I 2026-05-18 15:00:20,606] Trial 65 finished with value: 0.9496948651751286 and parameters: {'solver': 'saga', 'C': 0.0010305174171507093, 'l1_ratio': 0.8548550762076185, 'class_weight': None, 'fit_intercept': False, 'tol': 0.005117468270415208, 'max_iter': 4407}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  13%|█▎        | 63/500 [01:59<09:03,  1.24s/it]

[I 2026-05-18 15:00:22,554] Trial 67 finished with value: 0.949565784273337 and parameters: {'solver': 'saga', 'C': 0.027263776114002738, 'l1_ratio': 0.8558535122886939, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00380123331715821, 'max_iter': 4380}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  13%|█▎        | 64/500 [01:59<07:22,  1.01s/it]

[I 2026-05-18 15:00:23,032] Trial 54 finished with value: 0.9496803387737511 and parameters: {'solver': 'saga', 'C': 0.0006794685021785857, 'l1_ratio': 0.8936103539982723, 'class_weight': None, 'fit_intercept': True, 'tol': 1.191541117492931e-06, 'max_iter': 3399}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  13%|█▎        | 65/500 [02:00<07:11,  1.01it/s]

[I 2026-05-18 15:00:23,949] Trial 64 finished with value: 0.9495998718499477 and parameters: {'solver': 'saga', 'C': 0.018236565885962307, 'l1_ratio': 0.9412533565705641, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0003013669592301809, 'max_iter': 3825}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  13%|█▎        | 66/500 [02:01<06:37,  1.09it/s]

[I 2026-05-18 15:00:24,707] Trial 56 finished with value: 0.9496890247186485 and parameters: {'solver': 'saga', 'C': 0.000715180493209694, 'l1_ratio': 0.9293623624188485, 'class_weight': None, 'fit_intercept': True, 'tol': 1.577049000055692e-06, 'max_iter': 3423}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  13%|█▎        | 67/500 [02:02<07:30,  1.04s/it]

[I 2026-05-18 15:00:26,039] Trial 68 finished with value: 0.9495709909368555 and parameters: {'solver': 'saga', 'C': 0.02952995305691003, 'l1_ratio': 0.8669054334417362, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0047332470638648495, 'max_iter': 4320}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  14%|█▎        | 68/500 [02:06<13:47,  1.91s/it]

[I 2026-05-18 15:00:29,999] Trial 72 finished with value: 0.9494510781144232 and parameters: {'solver': 'saga', 'C': 0.0038205389910119744, 'l1_ratio': 0.38255223719988163, 'class_weight': None, 'fit_intercept': False, 'tol': 0.005047417389020959, 'max_iter': 3898}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  14%|█▍        | 69/500 [02:09<14:14,  1.98s/it]

[I 2026-05-18 15:00:32,141] Trial 62 finished with value: 0.9496037331610612 and parameters: {'solver': 'saga', 'C': 0.016417018681607318, 'l1_ratio': 0.8606265803311998, 'class_weight': None, 'fit_intercept': False, 'tol': 1.136858055165756e-06, 'max_iter': 4375}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  14%|█▍        | 70/500 [02:12<16:24,  2.29s/it]

[I 2026-05-18 15:00:35,151] Trial 69 finished with value: 0.9496888164911692 and parameters: {'solver': 'saga', 'C': 0.00448600103887569, 'l1_ratio': 0.847371166003569, 'class_weight': None, 'fit_intercept': False, 'tol': 9.669747181984166e-05, 'max_iter': 3909}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  14%|█▍        | 71/500 [02:12<12:36,  1.76s/it]

[I 2026-05-18 15:00:35,676] Trial 73 finished with value: 0.9496907800302321 and parameters: {'solver': 'saga', 'C': 0.003978570199917226, 'l1_ratio': 0.772633481099464, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00010337446766076096, 'max_iter': 3831}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  14%|█▍        | 72/500 [02:13<11:15,  1.58s/it]

[I 2026-05-18 15:00:36,818] Trial 70 finished with value: 0.9495841082902949 and parameters: {'solver': 'saga', 'C': 0.0046156337987942045, 'l1_ratio': 0.425729041157006, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00011062163402803455, 'max_iter': 3858}. Best is trial 27 with value: 0.9497048983330643.
[I 2026-05-18 15:00:36,910] Trial 42 finished with value: 0.9496858540277427 and parameters: {'solver': 'saga', 'C': 0.00752784783735167, 'l1_ratio': 0.9980594676360255, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011069516992677048, 'max_iter': 4975}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  15%|█▍        | 74/500 [02:14<07:55,  1.12s/it]

[I 2026-05-18 15:00:37,990] Trial 71 finished with value: 0.9494380884423352 and parameters: {'solver': 'saga', 'C': 0.11564841270234447, 'l1_ratio': 0.4206659193778124, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00010077422307108658, 'max_iter': 3791}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  15%|█▌        | 75/500 [02:17<10:05,  1.43s/it]

[I 2026-05-18 15:00:40,350] Trial 75 finished with value: 0.949690748140543 and parameters: {'solver': 'saga', 'C': 0.003862564179040211, 'l1_ratio': 0.7696579451808768, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00010041980256600294, 'max_iter': 3945}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  15%|█▌        | 76/500 [02:18<08:50,  1.25s/it]

[I 2026-05-18 15:00:41,108] Trial 74 finished with value: 0.949577222674035 and parameters: {'solver': 'saga', 'C': 0.004492361848307013, 'l1_ratio': 0.3756906231351339, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 8.678464900103746e-05, 'max_iter': 3952}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  15%|█▌        | 77/500 [02:19<10:04,  1.43s/it]

[I 2026-05-18 15:00:43,013] Trial 76 finished with value: 0.9495888464878254 and parameters: {'solver': 'saga', 'C': 0.0036165510132884974, 'l1_ratio': 0.39737448928166497, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 8.976403499748507e-05, 'max_iter': 4135}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  16%|█▌        | 78/500 [02:20<07:39,  1.09s/it]

[I 2026-05-18 15:00:43,221] Trial 77 finished with value: 0.9494507191361624 and parameters: {'solver': 'saga', 'C': 0.00019592678326093286, 'l1_ratio': 0.4183908447111011, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00010615100208118877, 'max_iter': 4187}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  16%|█▌        | 79/500 [02:20<06:08,  1.14it/s]

[I 2026-05-18 15:00:43,569] Trial 78 finished with value: 0.949585633624363 and parameters: {'solver': 'saga', 'C': 0.003976087022841097, 'l1_ratio': 0.7741891265744495, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00011664252013735013, 'max_iter': 3961}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  16%|█▌        | 80/500 [02:25<14:23,  2.06s/it]

[I 2026-05-18 15:00:48,525] Trial 81 finished with value: 0.949527532820914 and parameters: {'solver': 'saga', 'C': 0.0002452424128359982, 'l1_ratio': 0.49202863244467815, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002140805569255502, 'max_iter': 4174}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  16%|█▌        | 81/500 [02:25<10:53,  1.56s/it]

[I 2026-05-18 15:00:48,879] Trial 79 finished with value: 0.9496643727933461 and parameters: {'solver': 'saga', 'C': 0.00024151728067150073, 'l1_ratio': 0.9487034103684414, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00010049720520865683, 'max_iter': 4145}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  16%|█▋        | 82/500 [02:26<09:38,  1.38s/it]

[I 2026-05-18 15:00:49,843] Trial 80 finished with value: 0.9496666259341662 and parameters: {'solver': 'saga', 'C': 0.00023981450390555856, 'l1_ratio': 0.7799658745326743, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 9.10347252762755e-05, 'max_iter': 3606}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  17%|█▋        | 83/500 [02:27<07:49,  1.13s/it]

[I 2026-05-18 15:00:50,356] Trial 84 finished with value: 0.9496613778698609 and parameters: {'solver': 'saga', 'C': 0.0002194092092381792, 'l1_ratio': 0.9520324048001161, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0019711198165709015, 'max_iter': 4197}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  17%|█▋        | 85/500 [02:27<04:56,  1.40it/s]

[I 2026-05-18 15:00:50,932] Trial 85 finished with value: 0.9496112022222706 and parameters: {'solver': 'saga', 'C': 0.00018773438059165647, 'l1_ratio': 0.9666396959255399, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0019129011060486523, 'max_iter': 4167}. Best is trial 27 with value: 0.9497048983330643.
[I 2026-05-18 15:00:51,060] Trial 82 finished with value: 0.9496604824034094 and parameters: {'solver': 'saga', 'C': 0.00027809047161461893, 'l1_ratio': 0.955064100342724, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005670757245058094, 'max_iter': 4185}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 27. Best value: 0.949705:  17%|█▋        | 86/500 [02:31<10:53,  1.58s/it]

[I 2026-05-18 15:00:54,674] Trial 83 finished with value: 0.9495906022849668 and parameters: {'solver': 'saga', 'C': 0.0013986922358243362, 'l1_ratio': 0.9609382202486265, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0004955838199398182, 'max_iter': 4180}. Best is trial 27 with value: 0.9497048983330643.

Best trial: 86. Best value: 0.949706:  17%|█▋        | 87/500 [02:32<09:06,  1.32s/it]

[I 2026-05-18 15:00:55,397] Trial 86 finished with value: 0.9497062740636186 and parameters: {'solver': 'saga', 'C': 0.001318618100222441, 'l1_ratio': 0.9718182522597476, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005085956232810981, 'max_iter': 4167}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  18%|█▊        | 88/500 [02:33<08:02,  1.17s/it]

[I 2026-05-18 15:00:56,206] Trial 90 finished with value: 0.9497055851452965 and parameters: {'solver': 'saga', 'C': 0.0016803101296242202, 'l1_ratio': 0.958269711662204, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0020467456193246133, 'max_iter': 3680}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  18%|█▊        | 89/500 [02:35<09:52,  1.44s/it]

[I 2026-05-18 15:00:58,283] Trial 87 finished with value: 0.9497050413474056 and parameters: {'solver': 'saga', 'C': 0.0013128132690156636, 'l1_ratio': 0.9580442526989253, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004926524910779636, 'max_iter': 4183}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  18%|█▊        | 90/500 [02:35<08:24,  1.23s/it]

[I 2026-05-18 15:00:59,028] Trial 88 finished with value: 0.9497059005657909 and parameters: {'solver': 'saga', 'C': 0.0015274921429192748, 'l1_ratio': 0.9613532811257134, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000494992965508612, 'max_iter': 3629}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  18%|█▊        | 91/500 [02:38<10:29,  1.54s/it]

[I 2026-05-18 15:01:01,289] Trial 89 finished with value: 0.9496563112381358 and parameters: {'solver': 'saga', 'C': 0.0003059324929498232, 'l1_ratio': 0.9511286789646953, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004741523686606637, 'max_iter': 3570}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  18%|█▊        | 92/500 [02:41<14:10,  2.08s/it]

[I 2026-05-18 15:01:04,643] Trial 91 finished with value: 0.9497059155320319 and parameters: {'solver': 'saga', 'C': 0.0016515141851512541, 'l1_ratio': 0.963209516723116, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004852061323817764, 'max_iter': 3569}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  19%|█▊        | 93/500 [02:43<13:12,  1.95s/it]

[I 2026-05-18 15:01:06,273] Trial 92 finished with value: 0.9497047195862549 and parameters: {'solver': 'saga', 'C': 0.0013147530197115483, 'l1_ratio': 0.956373291302632, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00048295461886118155, 'max_iter': 4502}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  19%|█▉        | 94/500 [02:43<10:12,  1.51s/it]

[I 2026-05-18 15:01:06,755] Trial 93 finished with value: 0.9497058325725043 and parameters: {'solver': 'saga', 'C': 0.0014642266986557046, 'l1_ratio': 0.9620166192646585, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00043939748151224653, 'max_iter': 4776}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  19%|█▉        | 95/500 [02:44<08:05,  1.20s/it]

[I 2026-05-18 15:01:07,235] Trial 94 finished with value: 0.9497055654730542 and parameters: {'solver': 'saga', 'C': 0.0013466038666295232, 'l1_ratio': 0.9626283683173702, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004295985539043177, 'max_iter': 4493}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  19%|█▉        | 96/500 [02:44<06:41,  1.01it/s]

[I 2026-05-18 15:01:07,720] Trial 95 finished with value: 0.9497056150879223 and parameters: {'solver': 'saga', 'C': 0.001251374884687683, 'l1_ratio': 0.9660039445345142, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00047287025076575876, 'max_iter': 4520}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  19%|█▉        | 97/500 [02:45<05:28,  1.23it/s]

[I 2026-05-18 15:01:08,101] Trial 96 finished with value: 0.9496858731006256 and parameters: {'solver': 'saga', 'C': 0.0014785725201972226, 'l1_ratio': 0.8416217208302632, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00045977958885209784, 'max_iter': 4500}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  20%|█▉        | 98/500 [02:49<12:18,  1.84s/it]

[I 2026-05-18 15:01:12,368] Trial 97 finished with value: 0.9496837000023157 and parameters: {'solver': 'saga', 'C': 0.0012030385871780245, 'l1_ratio': 0.840242472634456, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002126729007494768, 'max_iter': 4524}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  20%|█▉        | 99/500 [02:52<15:01,  2.25s/it]

[I 2026-05-18 15:01:15,573] Trial 101 finished with value: 0.9496989962004798 and parameters: {'solver': 'saga', 'C': 0.0013738158178919352, 'l1_ratio': 0.9182034598354144, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004269543708878577, 'max_iter': 3565}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  20%|██        | 100/500 [02:55<17:26,  2.62s/it]

[I 2026-05-18 15:01:19,042] Trial 100 finished with value: 0.94970029299956 and parameters: {'solver': 'saga', 'C': 0.001499652547001412, 'l1_ratio': 0.9190092807599947, 'class_weight': None, 'fit_intercept': True, 'tol': 5.347266174323309e-05, 'max_iter': 4505}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  20%|██        | 101/500 [02:57<15:39,  2.35s/it]

[I 2026-05-18 15:01:20,794] Trial 102 finished with value: 0.9496983881399114 and parameters: {'solver': 'saga', 'C': 0.001355998718568908, 'l1_ratio': 0.9163697871815425, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00022957860638839105, 'max_iter': 3168}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  20%|██        | 102/500 [02:59<13:43,  2.07s/it]

[I 2026-05-18 15:01:22,197] Trial 103 finished with value: 0.9497059656448062 and parameters: {'solver': 'saga', 'C': 0.0012792708832060288, 'l1_ratio': 0.9684638269194884, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002268657263420237, 'max_iter': 3171}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  21%|██        | 103/500 [03:01<13:29,  2.04s/it]

[I 2026-05-18 15:01:24,170] Trial 104 finished with value: 0.9497009571815912 and parameters: {'solver': 'saga', 'C': 0.0015761926530827562, 'l1_ratio': 0.9201215295605516, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004284408289167043, 'max_iter': 3139}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  21%|██        | 106/500 [03:02<06:22,  1.03it/s]

[I 2026-05-18 15:01:25,155] Trial 105 finished with value: 0.9496998835625131 and parameters: {'solver': 'saga', 'C': 0.0014052940608024354, 'l1_ratio': 0.9217798945328, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00041386394507979686, 'max_iter': 3200}. Best is trial 86 with value: 0.9497062740636186.
[I 2026-05-18 15:01:25,173] Trial 108 finished with value: 0.9496724769820716 and parameters: {'solver': 'saga', 'C': 0.00042045344263118094, 'l1_ratio': 0.9229548616678932, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006371311566989057, 'max_iter': 3528}. Best is trial 86 with value: 0.9497062740636186.
[I 2026-05-18 15:01:25,342] Trial 106 finished with value: 0.9496998214235195 and parameters: {'solver': 'saga', 'C': 0.001408222169609449, 'l1_ratio': 0.9207555718724936, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00022461395256419037, 'max_iter': 4785}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  21%|██▏       | 107/500 [03:03<07:10,  1.09s/it]

[I 2026-05-18 15:01:26,811] Trial 107 finished with value: 0.9497011969569348 and parameters: {'solver': 'saga', 'C': 0.0015671476116616264, 'l1_ratio': 0.9224789727879181, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00021440401774085305, 'max_iter': 3039}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  22%|██▏       | 108/500 [03:03<05:40,  1.15it/s]

[I 2026-05-18 15:01:27,042] Trial 98 finished with value: 0.9497018554238398 and parameters: {'solver': 'saga', 'C': 0.0015524321163088843, 'l1_ratio': 0.9973632184233245, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018577378869959738, 'max_iter': 4542}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  22%|██▏       | 109/500 [03:06<09:06,  1.40s/it]

[I 2026-05-18 15:01:29,838] Trial 109 finished with value: 0.9496740693551405 and parameters: {'solver': 'saga', 'C': 0.00044174603859217153, 'l1_ratio': 0.9237177446173769, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00023444162166018218, 'max_iter': 3112}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  22%|██▏       | 110/500 [03:09<10:46,  1.66s/it]

[I 2026-05-18 15:01:32,184] Trial 112 pruned.

Best trial: 86. Best value: 0.949706:  22%|██▏       | 111/500 [03:10<10:40,  1.65s/it]

[I 2026-05-18 15:01:33,801] Trial 110 finished with value: 0.9497013174928899 and parameters: {'solver': 'saga', 'C': 0.0016941725218692048, 'l1_ratio': 0.9169596100237748, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00022965774347231198, 'max_iter': 3040}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  22%|██▏       | 112/500 [03:14<15:02,  2.33s/it]

[I 2026-05-18 15:01:37,792] Trial 111 finished with value: 0.9496755140889528 and parameters: {'solver': 'saga', 'C': 0.0004128950804959592, 'l1_ratio': 0.9688596333511758, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001456873374727262, 'max_iter': 3156}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  23%|██▎       | 113/500 [03:15<12:02,  1.87s/it]

[I 2026-05-18 15:01:38,550] Trial 114 finished with value: 0.9496875789783383 and parameters: {'solver': 'saga', 'C': 0.0005023864331708535, 'l1_ratio': 0.9729180930482131, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000619877091442237, 'max_iter': 2697}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  23%|██▎       | 114/500 [03:17<13:05,  2.04s/it]

[I 2026-05-18 15:01:40,984] Trial 113 finished with value: 0.9496762752269847 and parameters: {'solver': 'saga', 'C': 0.00041734065981388244, 'l1_ratio': 0.9741325621226207, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001522889023410932, 'max_iter': 2639}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  23%|██▎       | 115/500 [03:18<10:48,  1.68s/it]

[I 2026-05-18 15:01:41,836] Trial 115 finished with value: 0.9496670508761627 and parameters: {'solver': 'saga', 'C': 0.00036894767695080705, 'l1_ratio': 0.9694591495874171, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006269886482263102, 'max_iter': 2551}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  23%|██▎       | 116/500 [03:19<08:51,  1.39s/it]

[I 2026-05-18 15:01:42,504] Trial 118 finished with value: 0.9496760671696765 and parameters: {'solver': 'saga', 'C': 0.00041671176498764983, 'l1_ratio': 0.9731973843147589, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006455042331844273, 'max_iter': 3703}. Best is trial 86 with value: 0.9497062740636186.
[I 2026-05-18 15:01:42,544] Trial 99 finished with value: 0.9497024648001844 and parameters: {'solver': 'saga', 'C': 0.0011746012116750073, 'l1_ratio': 0.9989521642295974, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002202744625794039, 'max_iter': 4498}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  24%|██▎       | 118/500 [03:20<06:03,  1.05it/s]

[I 2026-05-18 15:01:43,383] Trial 116 finished with value: 0.9496766791260784 and parameters: {'solver': 'saga', 'C': 0.00042057201037424554, 'l1_ratio': 0.9662363411012741, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002705371211915014, 'max_iter': 2613}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  24%|██▍       | 120/500 [03:21<05:00,  1.26it/s]

[I 2026-05-18 15:01:44,602] Trial 117 finished with value: 0.9497049528291971 and parameters: {'solver': 'saga', 'C': 0.0023467198927514406, 'l1_ratio': 0.9648888897916246, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013599231573778388, 'max_iter': 2757}. Best is trial 86 with value: 0.9497062740636186.
[I 2026-05-18 15:01:44,761] Trial 119 finished with value: 0.9497034645480034 and parameters: {'solver': 'saga', 'C': 0.002365179785270833, 'l1_ratio': 0.9794726482080356, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002574432242542422, 'max_iter': 2354}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  24%|██▍       | 121/500 [03:26<11:10,  1.77s/it]

[I 2026-05-18 15:01:49,162] Trial 120 finished with value: 0.9496830769560557 and parameters: {'solver': 'saga', 'C': 0.011766769998462571, 'l1_ratio': 0.882301262822822, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014049369414177905, 'max_iter': 2503}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  24%|██▍       | 122/500 [03:27<10:02,  1.60s/it]

[I 2026-05-18 15:01:50,302] Trial 121 finished with value: 0.9496816062008939 and parameters: {'solver': 'saga', 'C': 0.01175508095991997, 'l1_ratio': 0.9710135879919637, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006628122204858645, 'max_iter': 3759}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  25%|██▍       | 123/500 [03:27<07:36,  1.21s/it]

[I 2026-05-18 15:01:50,559] Trial 122 finished with value: 0.9497044789622681 and parameters: {'solver': 'saga', 'C': 0.0023683845248650055, 'l1_ratio': 0.9711141282899676, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005283039932984493, 'max_iter': 3709}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  25%|██▍       | 124/500 [03:31<13:32,  2.16s/it]

[I 2026-05-18 15:01:55,047] Trial 123 finished with value: 0.9497043026271992 and parameters: {'solver': 'saga', 'C': 0.0025495176378669236, 'l1_ratio': 0.9682886336272927, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006343450846669718, 'max_iter': 3687}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  25%|██▌       | 125/500 [03:32<10:54,  1.75s/it]

[I 2026-05-18 15:01:55,791] Trial 124 finished with value: 0.949698024877615 and parameters: {'solver': 'saga', 'C': 0.002359079602565785, 'l1_ratio': 0.8857975231152442, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003677440160482579, 'max_iter': 3706}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  25%|██▌       | 126/500 [03:33<09:25,  1.51s/it]

[I 2026-05-18 15:01:56,742] Trial 125 finished with value: 0.9496966503129464 and parameters: {'solver': 'saga', 'C': 0.0024936099988526104, 'l1_ratio': 0.8775045162983641, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008567735567478633, 'max_iter': 4289}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  25%|██▌       | 127/500 [03:34<08:20,  1.34s/it]

[I 2026-05-18 15:01:57,679] Trial 127 finished with value: 0.9496967295311689 and parameters: {'solver': 'saga', 'C': 0.002336677112953201, 'l1_ratio': 0.879030996708323, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008513764889640428, 'max_iter': 4279}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  26%|██▌       | 128/500 [03:35<06:57,  1.12s/it]

[I 2026-05-18 15:01:58,284] Trial 129 finished with value: 0.9496982316317604 and parameters: {'solver': 'saga', 'C': 0.002348998424913587, 'l1_ratio': 0.8868160683583223, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008219075613790936, 'max_iter': 3718}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  26%|██▌       | 130/500 [03:36<05:41,  1.08it/s]

[I 2026-05-18 15:01:59,787] Trial 128 finished with value: 0.949697495219638 and parameters: {'solver': 'saga', 'C': 0.0027428752662508457, 'l1_ratio': 0.8825506808714114, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002672697651277854, 'max_iter': 3716}. Best is trial 86 with value: 0.9497062740636186.
[I 2026-05-18 15:01:59,978] Trial 126 finished with value: 0.949699297770929 and parameters: {'solver': 'saga', 'C': 0.0023212720845596823, 'l1_ratio': 0.8935427055389005, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00036294541813076145, 'max_iter': 3693}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  26%|██▌       | 131/500 [03:42<13:57,  2.27s/it]

[I 2026-05-18 15:02:05,399] Trial 131 finished with value: 0.9496835357208682 and parameters: {'solver': 'saga', 'C': 0.0008329722594913796, 'l1_ratio': 0.8863289521593075, 'class_weight': None, 'fit_intercept': True, 'tol': 7.109069939674303e-05, 'max_iter': 3286}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  26%|██▋       | 132/500 [03:43<11:05,  1.81s/it]

[I 2026-05-18 15:02:06,129] Trial 130 finished with value: 0.9496825938301556 and parameters: {'solver': 'saga', 'C': 0.011869937895232352, 'l1_ratio': 0.8866257132631856, 'class_weight': None, 'fit_intercept': True, 'tol': 6.843796062793623e-05, 'max_iter': 2268}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  27%|██▋       | 133/500 [03:43<08:59,  1.47s/it]

[I 2026-05-18 15:02:06,809] Trial 133 finished with value: 0.9496980946627437 and parameters: {'solver': 'saga', 'C': 0.0024113169074869187, 'l1_ratio': 0.8865252865539588, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003594034997896397, 'max_iter': 2368}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  27%|██▋       | 134/500 [03:44<06:59,  1.15s/it]

[I 2026-05-18 15:02:07,183] Trial 132 finished with value: 0.9497050553189815 and parameters: {'solver': 'saga', 'C': 0.0024490005124577626, 'l1_ratio': 0.9477892159759013, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003721079125257261, 'max_iter': 2076}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  27%|██▋       | 135/500 [03:44<06:01,  1.01it/s]

[I 2026-05-18 15:02:07,824] Trial 134 finished with value: 0.9496953464025817 and parameters: {'solver': 'saga', 'C': 0.0008160864878814564, 'l1_ratio': 0.9426650813646259, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00037007676745848386, 'max_iter': 2898}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  27%|██▋       | 136/500 [03:47<08:40,  1.43s/it]

[I 2026-05-18 15:02:10,275] Trial 135 finished with value: 0.9496947460852215 and parameters: {'solver': 'saga', 'C': 0.005479136811860621, 'l1_ratio': 0.9403843198723815, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000808904004451919, 'max_iter': 2880}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  27%|██▋       | 137/500 [03:48<09:15,  1.53s/it]

[I 2026-05-18 15:02:12,046] Trial 136 finished with value: 0.9496955017535285 and parameters: {'solver': 'saga', 'C': 0.0008091894340883746, 'l1_ratio': 0.9438667489091347, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008899424428362348, 'max_iter': 4737}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  28%|██▊       | 138/500 [03:49<06:52,  1.14s/it]

[I 2026-05-18 15:02:12,265] Trial 137 finished with value: 0.9496947397400601 and parameters: {'solver': 'saga', 'C': 0.005464566200969924, 'l1_ratio': 0.9408161242695713, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010845036332699435, 'max_iter': 2880}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  28%|██▊       | 139/500 [03:49<06:04,  1.01s/it]

[I 2026-05-18 15:02:12,977] Trial 138 finished with value: 0.9496937440988203 and parameters: {'solver': 'saga', 'C': 0.0008064693402320879, 'l1_ratio': 0.9369297002871158, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011284066179164467, 'max_iter': 4734}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  28%|██▊       | 140/500 [03:50<05:58,  1.00it/s]

[I 2026-05-18 15:02:13,947] Trial 140 finished with value: 0.9496942104123299 and parameters: {'solver': 'saga', 'C': 0.0057983867381136015, 'l1_ratio': 0.9403497080619068, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010625953368506727, 'max_iter': 2892}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  28%|██▊       | 141/500 [03:57<15:14,  2.55s/it]

[I 2026-05-18 15:02:20,099] Trial 139 finished with value: 0.949697304132683 and parameters: {'solver': 'saga', 'C': 0.0008671101396317387, 'l1_ratio': 0.9453215634775849, 'class_weight': None, 'fit_intercept': True, 'tol': 6.189683731268421e-05, 'max_iter': 3497}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  28%|██▊       | 142/500 [03:57<11:01,  1.85s/it]

[I 2026-05-18 15:02:20,316] Trial 141 finished with value: 0.9496958337571991 and parameters: {'solver': 'saga', 'C': 0.0008557746619418062, 'l1_ratio': 0.9401085712243178, 'class_weight': None, 'fit_intercept': True, 'tol': 6.154368352655068e-05, 'max_iter': 2875}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  29%|██▊       | 143/500 [03:58<10:44,  1.80s/it]

[I 2026-05-18 15:02:22,028] Trial 142 finished with value: 0.9496943361583625 and parameters: {'solver': 'saga', 'C': 0.005599525046463564, 'l1_ratio': 0.9443622932911432, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00048701320208852805, 'max_iter': 2874}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  29%|██▉       | 144/500 [03:59<08:56,  1.51s/it]

[I 2026-05-18 15:02:22,832] Trial 145 finished with value: 0.9496948518206361 and parameters: {'solver': 'saga', 'C': 0.005361106107542889, 'l1_ratio': 0.943248233765328, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005201467164891588, 'max_iter': 1947}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  29%|██▉       | 145/500 [04:00<06:49,  1.15s/it]

[I 2026-05-18 15:02:23,165] Trial 144 finished with value: 0.9496939029682316 and parameters: {'solver': 'saga', 'C': 0.005912051438535157, 'l1_ratio': 0.9425188459687348, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005797441338055656, 'max_iter': 2843}. Best is trial 86 with value: 0.9497062740636186.
[I 2026-05-18 15:02:23,215] Trial 143 finished with value: 0.9496964301040547 and parameters: {'solver': 'saga', 'C': 0.0008770547429688118, 'l1_ratio': 0.9412517836307244, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005465783670326911, 'max_iter': 2874}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  29%|██▉       | 147/500 [04:02<07:15,  1.23s/it]

[I 2026-05-18 15:02:25,816] Trial 146 finished with value: 0.9496932397590463 and parameters: {'solver': 'saga', 'C': 0.005962294038246804, 'l1_ratio': 0.9472408907170978, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005102858295860804, 'max_iter': 2213}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  30%|██▉       | 148/500 [04:03<06:47,  1.16s/it]

[I 2026-05-18 15:02:26,743] Trial 147 finished with value: 0.9496999105921832 and parameters: {'solver': 'saga', 'C': 0.0009516474507868316, 'l1_ratio': 0.9487159360619122, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005522385249883919, 'max_iter': 2047}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  30%|██▉       | 149/500 [04:06<09:45,  1.67s/it]

[I 2026-05-18 15:02:29,832] Trial 150 finished with value: 0.9497038193708566 and parameters: {'solver': 'saga', 'C': 0.0010204836741705187, 'l1_ratio': 0.9968160160039597, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000540707007208077, 'max_iter': 1367}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  30%|███       | 150/500 [04:09<11:38,  2.00s/it]

[I 2026-05-18 15:02:32,729] Trial 148 finished with value: 0.949703384878591 and parameters: {'solver': 'saga', 'C': 0.0010237109955284944, 'l1_ratio': 0.9976174927188334, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005184451281190059, 'max_iter': 3478}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  30%|███       | 151/500 [04:13<14:09,  2.43s/it]

[I 2026-05-18 15:02:36,283] Trial 152 finished with value: 0.9496983596230283 and parameters: {'solver': 'saga', 'C': 0.0034603859821483248, 'l1_ratio': 0.9846693636527408, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00048595452675066417, 'max_iter': 4633}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  30%|███       | 152/500 [04:13<10:44,  1.85s/it]

[I 2026-05-18 15:02:36,681] Trial 153 finished with value: 0.9496999630621185 and parameters: {'solver': 'saga', 'C': 0.0031885934345155715, 'l1_ratio': 0.982234406061145, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005099332484296832, 'max_iter': 1592}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  31%|███       | 153/500 [04:16<12:17,  2.13s/it]

[I 2026-05-18 15:02:39,482] Trial 156 finished with value: 0.9497054812146238 and parameters: {'solver': 'saga', 'C': 0.0010892251045627691, 'l1_ratio': 0.9900948246146771, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005030617920392676, 'max_iter': 1529}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  31%|███       | 155/500 [04:16<06:50,  1.19s/it]

[I 2026-05-18 15:02:39,891] Trial 155 finished with value: 0.9496990037957568 and parameters: {'solver': 'saga', 'C': 0.003092895537681018, 'l1_ratio': 0.9910536966527995, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005303554387966442, 'max_iter': 4053}. Best is trial 86 with value: 0.9497062740636186.
[I 2026-05-18 15:02:40,039] Trial 149 finished with value: 0.9497030416508446 and parameters: {'solver': 'saga', 'C': 0.0009643284240126418, 'l1_ratio': 0.9985227089983295, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005056879253113684, 'max_iter': 3491}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  31%|███       | 156/500 [04:19<09:14,  1.61s/it]

[I 2026-05-18 15:02:42,647] Trial 158 finished with value: 0.9497033763871775 and parameters: {'solver': 'saga', 'C': 0.0018100262798418686, 'l1_ratio': 0.9897705870219334, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00029017201203104017, 'max_iter': 1628}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  31%|███▏      | 157/500 [04:25<16:38,  2.91s/it]

[I 2026-05-18 15:02:48,617] Trial 160 finished with value: 0.9496980783659307 and parameters: {'solver': 'saga', 'C': 0.0033019445495955442, 'l1_ratio': 0.9900860041891814, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002986763537238924, 'max_iter': 3467}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  32%|███▏      | 158/500 [04:26<12:41,  2.23s/it]

[I 2026-05-18 15:02:49,255] Trial 151 finished with value: 0.949702599831386 and parameters: {'solver': 'saga', 'C': 0.0010342648757080627, 'l1_ratio': 0.9988961682754848, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000524791649796019, 'max_iter': 3518}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  32%|███▏      | 159/500 [04:27<10:20,  1.82s/it]

[I 2026-05-18 15:02:50,120] Trial 161 finished with value: 0.9496989494633169 and parameters: {'solver': 'saga', 'C': 0.003423409785147606, 'l1_ratio': 0.981424587676026, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00030686470319811314, 'max_iter': 4657}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  32%|███▏      | 160/500 [04:29<11:10,  1.97s/it]

[I 2026-05-18 15:02:52,446] Trial 162 finished with value: 0.9496953007327612 and parameters: {'solver': 'saga', 'C': 0.0005935141049531073, 'l1_ratio': 0.9974175745724644, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003174446541401773, 'max_iter': 4055}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  32%|███▏      | 161/500 [04:33<14:41,  2.60s/it]

[I 2026-05-18 15:02:56,512] Trial 166 finished with value: 0.9496938331214968 and parameters: {'solver': 'saga', 'C': 0.000609629607183919, 'l1_ratio': 0.9657371724890271, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003233243612953262, 'max_iter': 1245}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  32%|███▏      | 162/500 [04:33<10:41,  1.90s/it]

[I 2026-05-18 15:02:56,762] Trial 164 finished with value: 0.9496919824273353 and parameters: {'solver': 'saga', 'C': 0.0005819108094758617, 'l1_ratio': 0.964785234052225, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00030690952504894205, 'max_iter': 3624}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  33%|███▎      | 163/500 [04:34<08:05,  1.44s/it]

[I 2026-05-18 15:02:57,138] Trial 165 finished with value: 0.9497055516281787 and parameters: {'solver': 'saga', 'C': 0.001953575090739308, 'l1_ratio': 0.9649639216007885, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003068323709149648, 'max_iter': 1736}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  33%|███▎      | 164/500 [04:35<08:14,  1.47s/it]

[I 2026-05-18 15:02:58,680] Trial 157 finished with value: 0.9496958998818388 and parameters: {'solver': 'saga', 'C': 0.0035504058134468394, 'l1_ratio': 0.9948539093613561, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001729498168045422, 'max_iter': 3638}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  33%|███▎      | 165/500 [04:36<07:33,  1.35s/it]

[I 2026-05-18 15:02:59,749] Trial 167 finished with value: 0.9496931650367693 and parameters: {'solver': 'saga', 'C': 0.0005991903513253861, 'l1_ratio': 0.9655417819398214, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00042276192568492055, 'max_iter': 3609}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  33%|███▎      | 166/500 [04:41<14:00,  2.52s/it]

[I 2026-05-18 15:03:05,001] Trial 169 finished with value: 0.9497058751816819 and parameters: {'solver': 'saga', 'C': 0.0017643736090233134, 'l1_ratio': 0.9671729674100279, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006991999806438023, 'max_iter': 4867}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  33%|███▎      | 167/500 [04:44<13:56,  2.51s/it]

[I 2026-05-18 15:03:07,494] Trial 170 finished with value: 0.9497056519978676 and parameters: {'solver': 'saga', 'C': 0.001904743548805029, 'l1_ratio': 0.9629446295146904, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00038726567969499416, 'max_iter': 3653}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  34%|███▎      | 168/500 [04:44<10:04,  1.82s/it]

[I 2026-05-18 15:03:07,706] Trial 168 finished with value: 0.9497057849013067 and parameters: {'solver': 'saga', 'C': 0.0018529660610940597, 'l1_ratio': 0.9621686930331542, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018104375094062086, 'max_iter': 1209}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  34%|███▍      | 169/500 [04:44<07:27,  1.35s/it]

[I 2026-05-18 15:03:07,957] Trial 163 finished with value: 0.9497008562912814 and parameters: {'solver': 'saga', 'C': 0.0018448463585940926, 'l1_ratio': 0.9974542643152188, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003000997562919375, 'max_iter': 3625}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  34%|███▍      | 170/500 [04:46<08:39,  1.57s/it]

[I 2026-05-18 15:03:10,054] Trial 171 finished with value: 0.9497058556619887 and parameters: {'solver': 'saga', 'C': 0.0018169142347282076, 'l1_ratio': 0.9619464535816378, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00041544669560858346, 'max_iter': 1218}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  34%|███▍      | 171/500 [04:49<09:49,  1.79s/it]

[I 2026-05-18 15:03:12,340] Trial 172 finished with value: 0.9497055831832626 and parameters: {'solver': 'saga', 'C': 0.001930126406845784, 'l1_ratio': 0.9674769138385784, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00040205851358967985, 'max_iter': 1395}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  34%|███▍      | 172/500 [04:49<07:35,  1.39s/it]

[I 2026-05-18 15:03:12,800] Trial 173 finished with value: 0.9497056186494375 and parameters: {'solver': 'saga', 'C': 0.001909395921552586, 'l1_ratio': 0.9654578539625032, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000400963873116477, 'max_iter': 1347}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  35%|███▍      | 173/500 [04:51<08:21,  1.53s/it]

[I 2026-05-18 15:03:14,665] Trial 176 finished with value: 0.9497013235085389 and parameters: {'solver': 'saga', 'C': 0.0019673052902171428, 'l1_ratio': 0.9067751968736155, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007135623603391767, 'max_iter': 1517}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  35%|███▍      | 174/500 [04:52<06:50,  1.26s/it]

[I 2026-05-18 15:03:15,286] Trial 174 finished with value: 0.9496454087877095 and parameters: {'solver': 'saga', 'C': 0.0017185666648706526, 'l1_ratio': 0.6258665929889465, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017542025664736826, 'max_iter': 1788}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  35%|███▌      | 175/500 [04:52<05:32,  1.02s/it]

[I 2026-05-18 15:03:15,757] Trial 175 finished with value: 0.949700856809083 and parameters: {'solver': 'saga', 'C': 0.0018443475998597154, 'l1_ratio': 0.9073792669448463, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004372620352304125, 'max_iter': 4446}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  35%|███▌      | 176/500 [04:58<12:34,  2.33s/it]

[I 2026-05-18 15:03:21,135] Trial 177 finished with value: 0.9497014829248538 and parameters: {'solver': 'saga', 'C': 0.0019440344552963296, 'l1_ratio': 0.9079271074754633, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004016172222940627, 'max_iter': 1513}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  35%|███▌      | 177/500 [05:02<16:17,  3.03s/it]

[I 2026-05-18 15:03:25,791] Trial 181 finished with value: 0.9497011393674478 and parameters: {'solver': 'saga', 'C': 0.001797315000833023, 'l1_ratio': 0.9113567846992633, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004133294417127955, 'max_iter': 1726}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  36%|███▌      | 179/500 [05:04<09:53,  1.85s/it]

[I 2026-05-18 15:03:27,327] Trial 179 finished with value: 0.9497008268776292 and parameters: {'solver': 'saga', 'C': 0.0017453878169821023, 'l1_ratio': 0.9116065876834005, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018421706697447507, 'max_iter': 1747}. Best is trial 86 with value: 0.9497062740636186.
[I 2026-05-18 15:03:27,468] Trial 180 finished with value: 0.9497006890960105 and parameters: {'solver': 'saga', 'C': 0.0018315626398630693, 'l1_ratio': 0.9061085057496281, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017690358230769722, 'max_iter': 1702}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  36%|███▌      | 180/500 [05:05<09:06,  1.71s/it]

[I 2026-05-18 15:03:28,843] Trial 183 finished with value: 0.9497013962248955 and parameters: {'solver': 'saga', 'C': 0.0017163466466650476, 'l1_ratio': 0.916725719031401, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004027783068349984, 'max_iter': 1499}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  36%|███▌      | 181/500 [05:06<06:57,  1.31s/it]

[I 2026-05-18 15:03:29,226] Trial 182 finished with value: 0.9497004065390586 and parameters: {'solver': 'saga', 'C': 0.0017929828617920796, 'l1_ratio': 0.9055285842397437, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003947800365106365, 'max_iter': 1219}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  36%|███▋      | 182/500 [05:09<09:28,  1.79s/it]

[I 2026-05-18 15:03:32,137] Trial 186 finished with value: 0.949705050295892 and parameters: {'solver': 'saga', 'C': 0.0012535465473037454, 'l1_ratio': 0.9609624545629822, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004017526267924638, 'max_iter': 1266}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  37%|███▋      | 183/500 [05:09<07:39,  1.45s/it]

[I 2026-05-18 15:03:32,801] Trial 185 finished with value: 0.9496986544290961 and parameters: {'solver': 'saga', 'C': 0.0014016940242887854, 'l1_ratio': 0.9151859176111201, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00037506997882214596, 'max_iter': 1310}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  37%|███▋      | 184/500 [05:10<05:52,  1.12s/it]

[I 2026-05-18 15:03:33,134] Trial 184 finished with value: 0.9497008314329005 and parameters: {'solver': 'saga', 'C': 0.0018454741312291729, 'l1_ratio': 0.9069493720619761, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00040277920460610043, 'max_iter': 1245}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  37%|███▋      | 185/500 [05:13<09:40,  1.84s/it]

[I 2026-05-18 15:03:36,678] Trial 159 finished with value: 0.9496968075828833 and parameters: {'solver': 'saga', 'C': 0.0031045476061033203, 'l1_ratio': 0.9984629318900191, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001844921665236362, 'max_iter': 1754}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  37%|███▋      | 186/500 [05:16<10:40,  2.04s/it]

[I 2026-05-18 15:03:39,173] Trial 187 finished with value: 0.9497049915738536 and parameters: {'solver': 'saga', 'C': 0.0012231998303107356, 'l1_ratio': 0.9615479697652466, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00038691273877564623, 'max_iter': 1185}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  37%|███▋      | 187/500 [05:20<14:30,  2.78s/it]

[I 2026-05-18 15:03:43,686] Trial 188 finished with value: 0.9493240922160131 and parameters: {'solver': 'saga', 'C': 0.0010658564818548798, 'l1_ratio': 0.27435374260402745, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003553894416125571, 'max_iter': 1331}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  38%|███▊      | 188/500 [05:21<10:52,  2.09s/it]

[I 2026-05-18 15:03:44,165] Trial 189 finished with value: 0.9497044907202914 and parameters: {'solver': 'saga', 'C': 0.001112524668370784, 'l1_ratio': 0.9626718173086717, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004002221196986844, 'max_iter': 1339}. Best is trial 86 with value: 0.9497062740636186.
[I 2026-05-18 15:03:44,246] Trial 190 finished with value: 0.949704740412931 and parameters: {'solver': 'saga', 'C': 0.0012128736129359383, 'l1_ratio': 0.9601499719069727, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003538091921630439, 'max_iter': 1287}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  38%|███▊      | 190/500 [05:23<08:55,  1.73s/it]

[I 2026-05-18 15:03:46,777] Trial 191 finished with value: 0.9495608928864832 and parameters: {'solver': 'saga', 'C': 0.0009611942586367904, 'l1_ratio': 0.5338040351004718, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00038585507902405336, 'max_iter': 1185}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  38%|███▊      | 191/500 [05:25<09:21,  1.82s/it]

[I 2026-05-18 15:03:48,863] Trial 194 finished with value: 0.949705721630818 and parameters: {'solver': 'saga', 'C': 0.0014573114218416857, 'l1_ratio': 0.960868730156794, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000735196761298809, 'max_iter': 1147}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  38%|███▊      | 192/500 [05:27<08:52,  1.73s/it]

[I 2026-05-18 15:03:50,350] Trial 195 finished with value: 0.9497036503629737 and parameters: {'solver': 'saga', 'C': 0.0011304066963901975, 'l1_ratio': 0.956939005489586, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024352329428558092, 'max_iter': 1146}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  39%|███▊      | 193/500 [05:28<08:24,  1.64s/it]

[I 2026-05-18 15:03:51,760] Trial 196 finished with value: 0.9497049933631703 and parameters: {'solver': 'saga', 'C': 0.0012223182337421238, 'l1_ratio': 0.9614492892334484, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007302022408191925, 'max_iter': 1166}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  39%|███▉      | 194/500 [05:33<12:25,  2.44s/it]

[I 2026-05-18 15:03:56,238] Trial 197 finished with value: 0.9497046232936934 and parameters: {'solver': 'saga', 'C': 0.0011642027829910282, 'l1_ratio': 0.9620242198032359, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002488574851784127, 'max_iter': 1403}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  39%|███▉      | 195/500 [05:35<12:10,  2.39s/it]

[I 2026-05-18 15:03:58,518] Trial 200 finished with value: 0.9491790991680198 and parameters: {'solver': 'saga', 'C': 0.0011863346183548817, 'l1_ratio': 0.05996416740955102, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007626215588786362, 'max_iter': 4871}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 86. Best value: 0.949706:  39%|███▉      | 196/500 [05:39<13:51,  2.74s/it]

[I 2026-05-18 15:04:02,101] Trial 198 finished with value: 0.9497054403794778 and parameters: {'solver': 'saga', 'C': 0.0012837233787006722, 'l1_ratio': 0.9637786479848585, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002572820610166247, 'max_iter': 1128}. Best is trial 86 with value: 0.9497062740636186.

Best trial: 203. Best value: 0.949706:  39%|███▉      | 197/500 [05:41<12:51,  2.55s/it]

[I 2026-05-18 15:04:04,180] Trial 203 finished with value: 0.9497063363639058 and parameters: {'solver': 'saga', 'C': 0.0013039679830571897, 'l1_ratio': 0.9765640882460679, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006811211237551064, 'max_iter': 1016}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  40%|███▉      | 198/500 [05:44<14:17,  2.84s/it]

[I 2026-05-18 15:04:07,737] Trial 204 finished with value: 0.9496896918260879 and parameters: {'solver': 'saga', 'C': 0.0007379651955454377, 'l1_ratio': 0.9292412097857334, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007044946000815184, 'max_iter': 1025}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  40%|███▉      | 199/500 [05:46<12:04,  2.41s/it]

[I 2026-05-18 15:04:09,086] Trial 178 finished with value: 0.9495640092613868 and parameters: {'solver': 'saga', 'C': 0.4311418526044033, 'l1_ratio': 0.9603598635798758, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00037334914206247797, 'max_iter': 1404}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  40%|████      | 200/500 [05:47<10:23,  2.08s/it]

[I 2026-05-18 15:04:10,415] Trial 205 pruned.

Best trial: 203. Best value: 0.949706:  40%|████      | 201/500 [05:51<13:10,  2.64s/it]

[I 2026-05-18 15:04:14,378] Trial 206 finished with value: 0.9497027777662019 and parameters: {'solver': 'saga', 'C': 0.002726914038631558, 'l1_ratio': 0.9304804770405508, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006496510196946581, 'max_iter': 1029}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  40%|████      | 202/500 [06:00<22:33,  4.54s/it]

[I 2026-05-18 15:04:23,386] Trial 209 finished with value: 0.949702570022547 and parameters: {'solver': 'saga', 'C': 0.00277800644735617, 'l1_ratio': 0.9776564270142537, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006385686275079783, 'max_iter': 4901}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  41%|████      | 203/500 [06:02<18:23,  3.72s/it]

[I 2026-05-18 15:04:25,170] Trial 211 finished with value: 0.9497030416032954 and parameters: {'solver': 'saga', 'C': 0.0026267189886370838, 'l1_ratio': 0.9776223297590544, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000627142530942254, 'max_iter': 1068}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:04:25,256] Trial 207 finished with value: 0.9497000394684576 and parameters: {'solver': 'saga', 'C': 0.0006673847238483885, 'l1_ratio': 0.9817437948878934, 'class_weight': None, 'fit_intercept': True, 'tol': 1.206601129811704e-05, 'max_iter': 1024}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  41%|████      | 205/500 [06:09<18:16,  3.72s/it]

[I 2026-05-18 15:04:32,598] Trial 210 finished with value: 0.9497037202665896 and parameters: {'solver': 'saga', 'C': 0.0023600289079051214, 'l1_ratio': 0.9770608136232158, 'class_weight': None, 'fit_intercept': True, 'tol': 5.2688275615895576e-06, 'max_iter': 1048}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  41%|████      | 206/500 [06:14<20:05,  4.10s/it]

[I 2026-05-18 15:04:37,870] Trial 192 finished with value: 0.9495431402064345 and parameters: {'solver': 'saga', 'C': 0.9994284152488864, 'l1_ratio': 0.959179156538792, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024756438591156207, 'max_iter': 1296}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  41%|████▏     | 207/500 [06:18<19:18,  3.95s/it]

[I 2026-05-18 15:04:41,408] Trial 193 finished with value: 0.9495213828209821 and parameters: {'solver': 'saga', 'C': 10.975719111193738, 'l1_ratio': 0.96742494294693, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00025269845849126013, 'max_iter': 1352}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  42%|████▏     | 208/500 [06:19<15:50,  3.26s/it]

[I 2026-05-18 15:04:42,797] Trial 215 finished with value: 0.9497012153444965 and parameters: {'solver': 'saga', 'C': 0.001363910055435087, 'l1_ratio': 0.9313792933272029, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000274475407744277, 'max_iter': 1472}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  42%|████▏     | 209/500 [06:20<12:22,  2.55s/it]

[I 2026-05-18 15:04:43,527] Trial 202 finished with value: 0.9495501591268752 and parameters: {'solver': 'saga', 'C': 0.7375469863885955, 'l1_ratio': 0.9593322520566622, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006465777824145751, 'max_iter': 1381}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  42%|████▏     | 210/500 [06:20<09:15,  1.92s/it]

[I 2026-05-18 15:04:43,861] Trial 199 finished with value: 0.9495767839968569 and parameters: {'solver': 'saga', 'C': 0.2817347007542206, 'l1_ratio': 0.9618409217012277, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002635657876065294, 'max_iter': 1415}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  42%|████▏     | 211/500 [06:25<13:37,  2.83s/it]

[I 2026-05-18 15:04:48,927] Trial 216 finished with value: 0.9497024926243378 and parameters: {'solver': 'saga', 'C': 0.0015024235693469272, 'l1_ratio': 0.9329575962554286, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00028452749805077447, 'max_iter': 1268}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  42%|████▏     | 212/500 [06:30<16:18,  3.40s/it]

[I 2026-05-18 15:04:53,694] Trial 218 finished with value: 0.9497030574154796 and parameters: {'solver': 'saga', 'C': 0.0015087209039248454, 'l1_ratio': 0.9375290557828104, 'class_weight': None, 'fit_intercept': True, 'tol': 0.003136529665463171, 'max_iter': 1134}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  43%|████▎     | 213/500 [06:31<13:08,  2.75s/it]

[I 2026-05-18 15:04:54,898] Trial 201 finished with value: 0.9495271695128114 and parameters: {'solver': 'saga', 'C': 3.6701476570531555, 'l1_ratio': 0.9590731956422577, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024831080710188864, 'max_iter': 1019}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  43%|████▎     | 214/500 [06:32<10:27,  2.19s/it]

[I 2026-05-18 15:04:55,767] Trial 217 finished with value: 0.9497023702957363 and parameters: {'solver': 'saga', 'C': 0.0014720998771369845, 'l1_ratio': 0.9337354090305607, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002920626787718189, 'max_iter': 1484}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  43%|████▎     | 215/500 [06:34<10:20,  2.18s/it]

[I 2026-05-18 15:04:57,909] Trial 221 finished with value: 0.949702639513281 and parameters: {'solver': 'saga', 'C': 0.0015084341364825593, 'l1_ratio': 0.9342171417478969, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009688742278747193, 'max_iter': 1129}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  43%|████▎     | 216/500 [06:35<08:41,  1.83s/it]

[I 2026-05-18 15:04:58,938] Trial 219 finished with value: 0.9496981154659982 and parameters: {'solver': 'saga', 'C': 0.004194990167203943, 'l1_ratio': 0.9432575827119807, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004488963452362256, 'max_iter': 1126}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  43%|████▎     | 217/500 [06:37<08:25,  1.79s/it]

[I 2026-05-18 15:05:00,611] Trial 220 finished with value: 0.9496982306421249 and parameters: {'solver': 'saga', 'C': 0.004150071243554383, 'l1_ratio': 0.930463842662503, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004511684416017321, 'max_iter': 1131}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  44%|████▎     | 218/500 [06:41<11:29,  2.45s/it]

[I 2026-05-18 15:05:04,592] Trial 222 finished with value: 0.9497041495809434 and parameters: {'solver': 'saga', 'C': 0.001618094173246312, 'l1_ratio': 0.942585684540063, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005026580975080657, 'max_iter': 1155}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  44%|████▍     | 219/500 [06:47<15:57,  3.41s/it]

[I 2026-05-18 15:05:10,264] Trial 223 finished with value: 0.9497063031779721 and parameters: {'solver': 'saga', 'C': 0.0013624143423261136, 'l1_ratio': 0.9767401986288762, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004618078349482223, 'max_iter': 1122}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  44%|████▍     | 221/500 [06:48<08:55,  1.92s/it]

[I 2026-05-18 15:05:11,188] Trial 225 finished with value: 0.9496963078642301 and parameters: {'solver': 'saga', 'C': 0.0041220468257799365, 'l1_ratio': 0.9773298673535263, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000465783977175164, 'max_iter': 1163}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:05:11,375] Trial 224 finished with value: 0.9496960845187445 and parameters: {'solver': 'saga', 'C': 0.004186207241219929, 'l1_ratio': 0.9775037049910591, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004584657304357029, 'max_iter': 1210}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  44%|████▍     | 222/500 [06:50<09:05,  1.96s/it]

[I 2026-05-18 15:05:13,433] Trial 227 finished with value: 0.9497031946018177 and parameters: {'solver': 'saga', 'C': 0.0007760672641119343, 'l1_ratio': 0.9800398356823669, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00046888597552847196, 'max_iter': 4824}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  45%|████▍     | 223/500 [06:53<10:24,  2.26s/it]

[I 2026-05-18 15:05:16,374] Trial 228 finished with value: 0.9497018587633018 and parameters: {'solver': 'saga', 'C': 0.00073065039083363, 'l1_ratio': 0.9791770399969468, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004670505484298616, 'max_iter': 1556}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  45%|████▍     | 224/500 [06:57<12:51,  2.80s/it]

[I 2026-05-18 15:05:20,434] Trial 230 finished with value: 0.9497037855764134 and parameters: {'solver': 'saga', 'C': 0.0007875369019086021, 'l1_ratio': 0.9855679974792082, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0068338016708213364, 'max_iter': 3275}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  45%|████▌     | 225/500 [06:58<09:52,  2.16s/it]

[I 2026-05-18 15:05:21,088] Trial 229 finished with value: 0.949704409085893 and parameters: {'solver': 'saga', 'C': 0.0008555382330663701, 'l1_ratio': 0.979095811339549, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00045047210738100106, 'max_iter': 1240}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  45%|████▌     | 226/500 [06:59<08:52,  1.94s/it]

[I 2026-05-18 15:05:22,546] Trial 214 finished with value: 0.9496079804553167 and parameters: {'solver': 'saga', 'C': 0.05174687713242266, 'l1_ratio': 0.9766299481380561, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00025427155586909135, 'max_iter': 1128}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  45%|████▌     | 227/500 [07:01<08:21,  1.84s/it]

[I 2026-05-18 15:05:24,131] Trial 212 finished with value: 0.9495210540631094 and parameters: {'solver': 'saga', 'C': 11.371882056514764, 'l1_ratio': 0.9769602023100182, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002620299143300467, 'max_iter': 1460}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  46%|████▌     | 228/500 [07:03<09:02,  1.99s/it]

[I 2026-05-18 15:05:26,490] Trial 154 finished with value: 0.9496955704747142 and parameters: {'solver': 'saga', 'C': 0.003302295011693618, 'l1_ratio': 0.9997605575388795, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005286794906105523, 'max_iter': 1477}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  46%|████▌     | 229/500 [07:05<08:46,  1.94s/it]

[I 2026-05-18 15:05:28,313] Trial 231 finished with value: 0.9497036037118283 and parameters: {'solver': 'saga', 'C': 0.0008188781904397842, 'l1_ratio': 0.976614806680832, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003337177699895524, 'max_iter': 1222}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  46%|████▌     | 230/500 [07:05<06:31,  1.45s/it]

[I 2026-05-18 15:05:28,615] Trial 232 finished with value: 0.9497038752950475 and parameters: {'solver': 'saga', 'C': 0.0021188656088523545, 'l1_ratio': 0.9809066009661505, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00034771265411251325, 'max_iter': 1603}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  46%|████▌     | 231/500 [07:06<05:41,  1.27s/it]

[I 2026-05-18 15:05:29,467] Trial 233 finished with value: 0.9497030921947941 and parameters: {'solver': 'saga', 'C': 0.002392999421736563, 'l1_ratio': 0.9814381794019768, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00034473202358047605, 'max_iter': 1253}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  46%|████▋     | 232/500 [07:10<09:10,  2.05s/it]

[I 2026-05-18 15:05:33,341] Trial 234 finished with value: 0.9497053655312729 and parameters: {'solver': 'saga', 'C': 0.002271242793362366, 'l1_ratio': 0.9541449756880753, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003348992146288378, 'max_iter': 3287}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  47%|████▋     | 233/500 [07:12<09:32,  2.14s/it]

[I 2026-05-18 15:05:35,686] Trial 213 finished with value: 0.9495206060676249 and parameters: {'solver': 'saga', 'C': 14.144954864652194, 'l1_ratio': 0.9723020524377995, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024599336095336953, 'max_iter': 1457}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  47%|████▋     | 234/500 [07:14<08:56,  2.02s/it]

[I 2026-05-18 15:05:37,422] Trial 236 finished with value: 0.9497053430824709 and parameters: {'solver': 'saga', 'C': 0.002259568700847816, 'l1_ratio': 0.9545467849246271, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000349270860453914, 'max_iter': 3800}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  47%|████▋     | 235/500 [07:17<09:57,  2.25s/it]

[I 2026-05-18 15:05:40,232] Trial 208 finished with value: 0.9495342058434906 and parameters: {'solver': 'saga', 'C': 2.2304278602401477, 'l1_ratio': 0.9315657212683243, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7682687766733177e-05, 'max_iter': 1008}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  47%|████▋     | 236/500 [07:17<07:34,  1.72s/it]

[I 2026-05-18 15:05:40,708] Trial 237 finished with value: 0.9497053434078699 and parameters: {'solver': 'saga', 'C': 0.0022827967488346693, 'l1_ratio': 0.9536671328816659, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003411923907059479, 'max_iter': 1277}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  47%|████▋     | 237/500 [07:19<07:08,  1.63s/it]

[I 2026-05-18 15:05:42,124] Trial 238 finished with value: 0.9497054057117458 and parameters: {'solver': 'saga', 'C': 0.0021495876820877098, 'l1_ratio': 0.9526113598928093, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003621538710012286, 'max_iter': 3795}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  48%|████▊     | 240/500 [07:21<04:26,  1.02s/it]

[I 2026-05-18 15:05:44,497] Trial 242 finished with value: 0.9497036490568516 and parameters: {'solver': 'saga', 'C': 0.0011833211735524341, 'l1_ratio': 0.9539479111412936, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007425254182805945, 'max_iter': 1302}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:05:44,562] Trial 239 finished with value: 0.9497056321532437 and parameters: {'solver': 'saga', 'C': 0.001908690494358638, 'l1_ratio': 0.9557216268877784, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003330120157468551, 'max_iter': 1915}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:05:44,589] Trial 241 finished with value: 0.9497053884699153 and parameters: {'solver': 'saga', 'C': 0.002157151818268548, 'l1_ratio': 0.951529749686809, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005951271820223082, 'max_iter': 3807}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  48%|████▊     | 241/500 [07:21<03:35,  1.20it/s]

[I 2026-05-18 15:05:44,844] Trial 240 finished with value: 0.9497054507737841 and parameters: {'solver': 'saga', 'C': 0.0019665146644376797, 'l1_ratio': 0.9509332182929436, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005934018420275218, 'max_iter': 3797}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  48%|████▊     | 242/500 [07:25<07:06,  1.65s/it]

[I 2026-05-18 15:05:48,821] Trial 243 finished with value: 0.9497031424981526 and parameters: {'solver': 'saga', 'C': 0.001220410941286976, 'l1_ratio': 0.9492006525597498, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005678801404479332, 'max_iter': 3198}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  49%|████▊     | 243/500 [07:28<08:41,  2.03s/it]

[I 2026-05-18 15:05:51,853] Trial 244 finished with value: 0.9497038489716157 and parameters: {'solver': 'saga', 'C': 0.0013104212782735411, 'l1_ratio': 0.9505448776527445, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005936099872001672, 'max_iter': 3008}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  49%|████▉     | 244/500 [07:32<10:11,  2.39s/it]

[I 2026-05-18 15:05:55,169] Trial 245 finished with value: 0.9497054372712508 and parameters: {'solver': 'saga', 'C': 0.0019971278118970305, 'l1_ratio': 0.9502273981349668, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003410574367783748, 'max_iter': 3821}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  49%|████▉     | 246/500 [07:33<06:34,  1.55s/it]

[I 2026-05-18 15:05:56,637] Trial 247 finished with value: 0.9497053985554513 and parameters: {'solver': 'saga', 'C': 0.002001808909314802, 'l1_ratio': 0.9501957907004792, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005760448914279491, 'max_iter': 1898}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:05:56,788] Trial 246 finished with value: 0.9497055387771498 and parameters: {'solver': 'saga', 'C': 0.0019832812775961114, 'l1_ratio': 0.9524351703681418, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006146637456551073, 'max_iter': 3218}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  49%|████▉     | 247/500 [07:35<06:31,  1.55s/it]

[I 2026-05-18 15:05:58,329] Trial 248 finished with value: 0.9497054876982383 and parameters: {'solver': 'saga', 'C': 0.002009792075955105, 'l1_ratio': 0.9516760285629411, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005688756757502138, 'max_iter': 3212}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:05:58,335] Trial 226 finished with value: 0.949603730398066 and parameters: {'solver': 'saga', 'C': 0.0603374031850701, 'l1_ratio': 0.9764148561553192, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004421654647890848, 'max_iter': 1131}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  50%|████▉     | 249/500 [07:37<05:39,  1.35s/it]

[I 2026-05-18 15:06:00,565] Trial 235 finished with value: 0.9496048238609003 and parameters: {'solver': 'saga', 'C': 0.05788055152508819, 'l1_ratio': 0.951991986079293, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003322877984328283, 'max_iter': 1245}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  50%|█████     | 250/500 [07:38<04:46,  1.14s/it]

[I 2026-05-18 15:06:01,063] Trial 250 finished with value: 0.9494834052061798 and parameters: {'solver': 'saga', 'C': 0.0019596283285209706, 'l1_ratio': 0.17588286904797168, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005715505790618298, 'max_iter': 2992}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:06:01,126] Trial 252 finished with value: 0.9497053936776704 and parameters: {'solver': 'saga', 'C': 0.0019156180576579678, 'l1_ratio': 0.950742617761791, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006057991259542011, 'max_iter': 3892}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  50%|█████     | 252/500 [07:38<03:04,  1.35it/s]

[I 2026-05-18 15:06:01,401] Trial 251 finished with value: 0.9497050154714278 and parameters: {'solver': 'saga', 'C': 0.0018112881194368492, 'l1_ratio': 0.9455360536373332, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006000429985981606, 'max_iter': 3002}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  51%|█████     | 253/500 [07:39<03:33,  1.16it/s]

[I 2026-05-18 15:06:02,693] Trial 249 finished with value: 0.9497054624836986 and parameters: {'solver': 'saga', 'C': 0.002019453700949278, 'l1_ratio': 0.9509239189147164, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020462451605837055, 'max_iter': 3936}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  51%|█████     | 254/500 [07:41<04:48,  1.17s/it]

[I 2026-05-18 15:06:04,805] Trial 253 finished with value: 0.9496607266048016 and parameters: {'solver': 'saga', 'C': 0.0019130151853172215, 'l1_ratio': 0.6872793845336373, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006052654357682502, 'max_iter': 3841}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  51%|█████     | 255/500 [07:45<07:41,  1.88s/it]

[I 2026-05-18 15:06:08,721] Trial 254 finished with value: 0.9497055765163678 and parameters: {'solver': 'saga', 'C': 0.001951769036744271, 'l1_ratio': 0.9531227258919153, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008588910220560909, 'max_iter': 3888}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  51%|█████     | 256/500 [07:49<09:38,  2.37s/it]

[I 2026-05-18 15:06:12,409] Trial 257 finished with value: 0.9497029352435893 and parameters: {'solver': 'saga', 'C': 0.0016723011934962032, 'l1_ratio': 0.929846673083714, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008899977909868113, 'max_iter': 3841}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  51%|█████▏    | 257/500 [07:50<07:43,  1.91s/it]

[I 2026-05-18 15:06:13,114] Trial 256 finished with value: 0.9494313542704125 and parameters: {'solver': 'saga', 'C': 0.001763294619541996, 'l1_ratio': 0.15286597727540557, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000843422451970671, 'max_iter': 3904}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  52%|█████▏    | 258/500 [07:51<07:16,  1.80s/it]

[I 2026-05-18 15:06:14,645] Trial 259 finished with value: 0.9495456156101344 and parameters: {'solver': 'saga', 'C': 0.0016355520867919109, 'l1_ratio': 0.9978145743569347, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007231103989823855, 'max_iter': 3963}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  52%|█████▏    | 260/500 [07:53<05:00,  1.25s/it]

[I 2026-05-18 15:06:16,162] Trial 258 finished with value: 0.9495527101932106 and parameters: {'solver': 'saga', 'C': 3.310085087184682e-05, 'l1_ratio': 0.9274438259313519, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008046946701118846, 'max_iter': 4611}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:06:16,271] Trial 262 finished with value: 0.9497009282038855 and parameters: {'solver': 'saga', 'C': 0.0030667821330022903, 'l1_ratio': 0.9217145675270864, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000947825188651309, 'max_iter': 3942}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  53%|█████▎    | 263/500 [07:55<03:08,  1.26it/s]

[I 2026-05-18 15:06:17,981] Trial 263 finished with value: 0.9495448715416004 and parameters: {'solver': 'saga', 'C': 0.0010347634646961533, 'l1_ratio': 0.9992943210242229, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.000796984453008964, 'max_iter': 3384}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:06:17,987] Trial 264 finished with value: 0.9495883521026188 and parameters: {'solver': 'saga', 'C': 0.0030132841649266493, 'l1_ratio': 0.9303904959655795, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007735723707519697, 'max_iter': 3955}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:06:18,164] Trial 260 finished with value: 0.9495438862527074 and parameters: {'solver': 'saga', 'C': 0.0016355241946465272, 'l1_ratio': 0.9997382095881832, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008414402057782222, 'max_iter': 3928}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  53%|█████▎    | 264/500 [07:55<03:01,  1.30it/s]

[I 2026-05-18 15:06:18,867] Trial 261 finished with value: 0.9495482408718828 and parameters: {'solver': 'saga', 'C': 2.4914868068601043e-05, 'l1_ratio': 0.9274399233815774, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008508803689202132, 'max_iter': 3951}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  53%|█████▎    | 265/500 [07:57<04:27,  1.14s/it]

[I 2026-05-18 15:06:21,039] Trial 265 finished with value: 0.949697353242992 and parameters: {'solver': 'saga', 'C': 0.0011018603598657011, 'l1_ratio': 0.9266525351741508, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008238256113727915, 'max_iter': 3089}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  53%|█████▎    | 266/500 [08:01<06:29,  1.66s/it]

[I 2026-05-18 15:06:24,122] Trial 266 finished with value: 0.9495888340895174 and parameters: {'solver': 'saga', 'C': 0.0030904059983177033, 'l1_ratio': 0.9227449372269854, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002162559610026742, 'max_iter': 3981}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  53%|█████▎    | 267/500 [08:06<10:09,  2.61s/it]

[I 2026-05-18 15:06:29,195] Trial 269 finished with value: 0.9497006778553413 and parameters: {'solver': 'saga', 'C': 0.0031741526512555894, 'l1_ratio': 0.9196075177801953, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0012595354924402656, 'max_iter': 3978}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  54%|█████▎    | 268/500 [08:07<08:33,  2.22s/it]

[I 2026-05-18 15:06:30,414] Trial 268 finished with value: 0.9495884158392401 and parameters: {'solver': 'saga', 'C': 0.0030521055363250953, 'l1_ratio': 0.46762330630801574, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007475696063564422, 'max_iter': 4017}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  54%|█████▍    | 270/500 [08:08<05:06,  1.33s/it]

[I 2026-05-18 15:06:31,309] Trial 270 finished with value: 0.949701524553469 and parameters: {'solver': 'saga', 'C': 0.00307440869401359, 'l1_ratio': 0.9289170462893978, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0012647823309917716, 'max_iter': 3971}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:06:31,431] Trial 267 finished with value: 0.9495536078600498 and parameters: {'solver': 'saga', 'C': 0.0032902269178855634, 'l1_ratio': 0.9991029099338232, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008056979798315959, 'max_iter': 4020}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  54%|█████▍    | 271/500 [08:08<03:56,  1.03s/it]

[I 2026-05-18 15:06:31,746] Trial 255 finished with value: 0.9497008185550925 and parameters: {'solver': 'saga', 'C': 0.0017407011005128234, 'l1_ratio': 0.9982090284011025, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006037023615874214, 'max_iter': 3791}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  54%|█████▍    | 272/500 [08:09<03:42,  1.03it/s]

[I 2026-05-18 15:06:32,580] Trial 275 finished with value: 0.9497016156327911 and parameters: {'solver': 'saga', 'C': 0.003118837946346876, 'l1_ratio': 0.9682264283393728, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001593727480590821, 'max_iter': 3597}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  55%|█████▍    | 273/500 [08:10<03:33,  1.06it/s]

[I 2026-05-18 15:06:33,439] Trial 273 finished with value: 0.9497053296107184 and parameters: {'solver': 'saga', 'C': 0.0010787414632614514, 'l1_ratio': 0.9711506638974438, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00045685979441895813, 'max_iter': 3529}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  55%|█████▍    | 274/500 [08:10<02:46,  1.36it/s]

[I 2026-05-18 15:06:33,691] Trial 274 finished with value: 0.9497017846475858 and parameters: {'solver': 'saga', 'C': 0.003095702108031615, 'l1_ratio': 0.9691697630669429, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0012772002965703363, 'max_iter': 3575}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  55%|█████▌    | 276/500 [08:12<02:42,  1.38it/s]

[I 2026-05-18 15:06:35,217] Trial 272 finished with value: 0.9497018207606759 and parameters: {'solver': 'saga', 'C': 0.0030757319370048088, 'l1_ratio': 0.9693792024708647, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004850740823807709, 'max_iter': 3226}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:06:35,353] Trial 276 finished with value: 0.9497018765586358 and parameters: {'solver': 'saga', 'C': 0.003107099327053231, 'l1_ratio': 0.9665521651792982, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0017057360912609003, 'max_iter': 3223}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  55%|█████▌    | 277/500 [08:20<10:53,  2.93s/it]

[I 2026-05-18 15:06:43,463] Trial 277 finished with value: 0.9497045588880928 and parameters: {'solver': 'saga', 'C': 0.0009936091987148225, 'l1_ratio': 0.9698396160263983, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019860770498000588, 'max_iter': 4986}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  56%|█████▌    | 278/500 [08:24<12:29,  3.38s/it]

[I 2026-05-18 15:06:47,861] Trial 279 finished with value: 0.9497042839766253 and parameters: {'solver': 'saga', 'C': 0.0009823036318305613, 'l1_ratio': 0.968799244279197, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004516434341201274, 'max_iter': 4266}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 203. Best value: 0.949706:  56%|█████▌    | 279/500 [08:25<09:08,  2.48s/it]

[I 2026-05-18 15:06:48,272] Trial 278 finished with value: 0.9497048954469648 and parameters: {'solver': 'saga', 'C': 0.0010598420336490719, 'l1_ratio': 0.9683754300106905, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020336670417654215, 'max_iter': 4984}. Best is trial 203 with value: 0.9497063363639058.

Best trial: 284. Best value: 0.949706:  56%|█████▌    | 281/500 [08:26<05:24,  1.48s/it]

[I 2026-05-18 15:06:49,361] Trial 282 finished with value: 0.9497037579010803 and parameters: {'solver': 'saga', 'C': 0.0009646701343966847, 'l1_ratio': 0.9671278427340375, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020625586912907844, 'max_iter': 3244}. Best is trial 203 with value: 0.9497063363639058.
[I 2026-05-18 15:06:49,473] Trial 284 finished with value: 0.9497063435229075 and parameters: {'solver': 'saga', 'C': 0.001280609777973732, 'l1_ratio': 0.9762768685333756, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00047673769369941033, 'max_iter': 4961}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  56%|█████▋    | 282/500 [08:27<04:43,  1.30s/it]

[I 2026-05-18 15:06:50,349] Trial 281 finished with value: 0.9497049917501107 and parameters: {'solver': 'saga', 'C': 0.0010314699202011097, 'l1_ratio': 0.9711901490013327, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001984448247763713, 'max_iter': 3605}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  57%|█████▋    | 283/500 [08:27<03:44,  1.03s/it]

[I 2026-05-18 15:06:50,755] Trial 283 finished with value: 0.9494078568385312 and parameters: {'solver': 'saga', 'C': 0.001108191350448595, 'l1_ratio': 0.34386095423665514, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004339855323356485, 'max_iter': 4753}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  57%|█████▋    | 284/500 [08:28<02:56,  1.23it/s]

[I 2026-05-18 15:06:51,076] Trial 271 finished with value: 0.9496974444356174 and parameters: {'solver': 'saga', 'C': 0.002977348519634906, 'l1_ratio': 0.9975701914969537, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011699648055673254, 'max_iter': 4754}. Best is trial 284 with value: 0.9497063435229075.
[I 2026-05-18 15:06:51,101] Trial 280 finished with value: 0.949703669893538 and parameters: {'solver': 'saga', 'C': 0.0009878758571148117, 'l1_ratio': 0.9653188202016696, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001948291262892774, 'max_iter': 4760}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  57%|█████▋    | 286/500 [08:28<02:09,  1.65it/s]

[I 2026-05-18 15:06:51,784] Trial 286 finished with value: 0.9497062956995317 and parameters: {'solver': 'saga', 'C': 0.001274627970244524, 'l1_ratio': 0.9800514036633696, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004229780596226926, 'max_iter': 4985}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  57%|█████▋    | 287/500 [08:28<01:51,  1.92it/s]

[I 2026-05-18 15:06:52,060] Trial 285 finished with value: 0.9497059999643964 and parameters: {'solver': 'saga', 'C': 0.001339579291716989, 'l1_ratio': 0.968193608252523, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020947335957101275, 'max_iter': 4270}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  58%|█████▊    | 288/500 [08:31<04:02,  1.14s/it]

[I 2026-05-18 15:06:54,942] Trial 287 finished with value: 0.9497062395734869 and parameters: {'solver': 'saga', 'C': 0.0013861882419793283, 'l1_ratio': 0.9766271132301704, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002163598329838415, 'max_iter': 4762}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  58%|█████▊    | 289/500 [08:36<07:46,  2.21s/it]

[I 2026-05-18 15:07:00,028] Trial 288 finished with value: 0.9497060573843001 and parameters: {'solver': 'saga', 'C': 0.0013430964385662636, 'l1_ratio': 0.981885152008638, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004259055050784668, 'max_iter': 4728}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  58%|█████▊    | 290/500 [08:40<09:28,  2.71s/it]

[I 2026-05-18 15:07:04,014] Trial 289 finished with value: 0.9495067056114254 and parameters: {'solver': 'saga', 'C': 0.0015210932192800313, 'l1_ratio': 0.336273848945984, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005215523272865804, 'max_iter': 3658}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  58%|█████▊    | 291/500 [08:41<07:32,  2.17s/it]

[I 2026-05-18 15:07:04,830] Trial 290 finished with value: 0.9495016571330744 and parameters: {'solver': 'saga', 'C': 0.0014685035342770231, 'l1_ratio': 0.34325566402181396, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005200623737848821, 'max_iter': 3730}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  58%|█████▊    | 292/500 [08:43<06:40,  1.92s/it]

[I 2026-05-18 15:07:06,159] Trial 296 finished with value: 0.9496881564029639 and parameters: {'solver': 'saga', 'C': 0.0006191464591100516, 'l1_ratio': 0.9417429571693336, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005172234791624373, 'max_iter': 4903}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  59%|█████▉    | 294/500 [08:44<04:01,  1.17s/it]

[I 2026-05-18 15:07:07,033] Trial 292 finished with value: 0.9496972306598357 and parameters: {'solver': 'saga', 'C': 0.0006013380756680758, 'l1_ratio': 0.9853190787923645, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004004278012531537, 'max_iter': 4881}. Best is trial 284 with value: 0.9497063435229075.
[I 2026-05-18 15:07:07,136] Trial 291 finished with value: 0.9497032669358104 and parameters: {'solver': 'saga', 'C': 0.0013944348106556153, 'l1_ratio': 0.9423708109183115, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00041040496652810273, 'max_iter': 4749}. Best is trial 284 with value: 0.9497063435229075.
[I 2026-05-18 15:07:07,188] Trial 294 finished with value: 0.9496900318820704 and parameters: {'solver': 'saga', 'C': 0.0005130839104061498, 'l1_ratio': 0.9841518419260891, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005297162218403269, 'max_iter': 4882}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  59%|█████▉    | 297/500 [08:44<02:07,  1.59it/s]

[I 2026-05-18 15:07:07,745] Trial 295 finished with value: 0.9496976934534752 and parameters: {'solver': 'saga', 'C': 0.0006119261162676455, 'l1_ratio': 0.9840647688257376, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005139305535430023, 'max_iter': 4937}. Best is trial 284 with value: 0.9497063435229075.
[I 2026-05-18 15:07:07,935] Trial 293 finished with value: 0.949691325755057 and parameters: {'solver': 'saga', 'C': 0.0005261587131734728, 'l1_ratio': 0.9846603255073478, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00041672955751676535, 'max_iter': 4864}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  60%|█████▉    | 298/500 [08:45<02:06,  1.60it/s]

[I 2026-05-18 15:07:08,555] Trial 297 finished with value: 0.9494036916735444 and parameters: {'solver': 'saga', 'C': 0.0014224154282835239, 'l1_ratio': 0.23005910971693277, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005168568749128183, 'max_iter': 4852}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  60%|█████▉    | 299/500 [08:46<02:42,  1.23it/s]

[I 2026-05-18 15:07:09,853] Trial 298 finished with value: 0.9495621110188484 and parameters: {'solver': 'saga', 'C': 0.00011120307260039302, 'l1_ratio': 0.9812518982439031, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00039368045858403174, 'max_iter': 4422}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  60%|██████    | 300/500 [08:51<06:14,  1.87s/it]

[I 2026-05-18 15:07:14,459] Trial 299 finished with value: 0.9496952034703545 and parameters: {'solver': 'saga', 'C': 0.0005705055713789087, 'l1_ratio': 0.9860846523198079, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012334114982364528, 'max_iter': 4874}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  60%|██████    | 301/500 [08:53<06:28,  1.95s/it]

[I 2026-05-18 15:07:16,631] Trial 300 finished with value: 0.9496950575537749 and parameters: {'solver': 'saga', 'C': 0.0005721375882459584, 'l1_ratio': 0.9828824572895555, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00028762314659978904, 'max_iter': 4903}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  60%|██████    | 302/500 [08:57<08:01,  2.43s/it]

[I 2026-05-18 15:07:20,238] Trial 301 finished with value: 0.949702514969756 and parameters: {'solver': 'saga', 'C': 0.0007369492693132214, 'l1_ratio': 0.9823490672343147, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002946058082937895, 'max_iter': 4871}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  61%|██████    | 303/500 [09:00<08:58,  2.74s/it]

[I 2026-05-18 15:07:23,703] Trial 308 finished with value: 0.94957131683729 and parameters: {'solver': 'saga', 'C': 0.00013308944618279937, 'l1_ratio': 0.9834940143277876, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002846131101469016, 'max_iter': 4819}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  61%|██████    | 304/500 [09:00<06:30,  1.99s/it]

[I 2026-05-18 15:07:23,919] Trial 302 finished with value: 0.9496988939516969 and parameters: {'solver': 'saga', 'C': 0.0006398086303024048, 'l1_ratio': 0.9817513107434663, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015407006255190614, 'max_iter': 4856}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  61%|██████    | 305/500 [09:01<05:22,  1.66s/it]

[I 2026-05-18 15:07:24,772] Trial 305 finished with value: 0.949705715284796 and parameters: {'solver': 'saga', 'C': 0.001395341285530788, 'l1_ratio': 0.9845779260434536, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003063189305407235, 'max_iter': 4650}. Best is trial 284 with value: 0.9497063435229075.
[I 2026-05-18 15:07:24,789] Trial 303 finished with value: 0.9496962315418072 and parameters: {'solver': 'saga', 'C': 0.000584670639796704, 'l1_ratio': 0.9867373639576649, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00029456369254455324, 'max_iter': 4840}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  62%|██████▏   | 309/500 [09:02<02:11,  1.45it/s]

[I 2026-05-18 15:07:25,575] Trial 306 finished with value: 0.9497060985389062 and parameters: {'solver': 'saga', 'C': 0.0013468817872512, 'l1_ratio': 0.9823578588150227, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012877895524728776, 'max_iter': 4624}. Best is trial 284 with value: 0.9497063435229075.
[I 2026-05-18 15:07:25,596] Trial 307 finished with value: 0.9497058480271727 and parameters: {'solver': 'saga', 'C': 0.001323179063880949, 'l1_ratio': 0.9858256837056262, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015396188362648628, 'max_iter': 4679}. Best is trial 284 with value: 0.9497063435229075.
[I 2026-05-18 15:07:25,761] Trial 304 finished with value: 0.9497030477132172 and parameters: {'solver': 'saga', 'C': 0.0007529491903908441, 'l1_ratio': 0.9833861229206639, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013668166799636112, 'max_iter': 4861}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  62%|██████▏   | 310/500 [09:05<03:47,  1.20s/it]

[I 2026-05-18 15:07:28,761] Trial 310 finished with value: 0.9496308939071142 and parameters: {'solver': 'saga', 'C': 0.0013588363573304718, 'l1_ratio': 0.597751687821816, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001359023623233797, 'max_iter': 4662}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 284. Best value: 0.949706:  62%|██████▏   | 311/500 [09:07<04:24,  1.40s/it]

[I 2026-05-18 15:07:30,803] Trial 311 finished with value: 0.9496963803017296 and parameters: {'solver': 'saga', 'C': 0.0013784362943766923, 'l1_ratio': 0.9036673204131234, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002909607697430487, 'max_iter': 4689}. Best is trial 284 with value: 0.9497063435229075.

Best trial: 312. Best value: 0.949708:  62%|██████▏   | 312/500 [09:08<04:15,  1.36s/it]

[I 2026-05-18 15:07:32,028] Trial 312 finished with value: 0.9497076473716899 and parameters: {'solver': 'saga', 'C': 0.0014009873904905663, 'l1_ratio': 0.9001784283881352, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00014681402326795437, 'max_iter': 4665}. Best is trial 312 with value: 0.9497076473716899.

Best trial: 312. Best value: 0.949708:  63%|██████▎   | 313/500 [09:11<05:17,  1.70s/it]

[I 2026-05-18 15:07:34,663] Trial 313 finished with value: 0.9496508552921512 and parameters: {'solver': 'saga', 'C': 0.0014264389238700247, 'l1_ratio': 0.6465652824066559, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00032917031116383336, 'max_iter': 4675}. Best is trial 312 with value: 0.9497076473716899.

Best trial: 316. Best value: 0.949708:  63%|██████▎   | 314/500 [09:14<06:35,  2.12s/it]

[I 2026-05-18 15:07:37,900] Trial 316 finished with value: 0.9497077059345547 and parameters: {'solver': 'saga', 'C': 0.001424524535355597, 'l1_ratio': 0.8997183742627815, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0003374773629657047, 'max_iter': 4657}. Best is trial 316 with value: 0.9497077059345547.

Best trial: 314. Best value: 0.949712:  63%|██████▎   | 315/500 [09:15<04:53,  1.59s/it]

[I 2026-05-18 15:07:38,135] Trial 314 finished with value: 0.9497124134579081 and parameters: {'solver': 'saga', 'C': 0.0013587830713062798, 'l1_ratio': 0.9380658383866162, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0003034256866351547, 'max_iter': 4573}. Best is trial 314 with value: 0.9497124134579081.

Best trial: 317. Best value: 0.949713:  63%|██████▎   | 316/500 [09:15<03:44,  1.22s/it]

[I 2026-05-18 15:07:38,443] Trial 317 finished with value: 0.9497125419735118 and parameters: {'solver': 'saga', 'C': 0.001386722254897465, 'l1_ratio': 0.9423297191842144, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00035558447857240793, 'max_iter': 4576}. Best is trial 317 with value: 0.9497125419735118.

Best trial: 317. Best value: 0.949713:  63%|██████▎   | 317/500 [09:16<03:56,  1.29s/it]

[I 2026-05-18 15:07:39,901] Trial 315 finished with value: 0.9497028786414434 and parameters: {'solver': 'saga', 'C': 0.0014017776008394037, 'l1_ratio': 0.9392428609131553, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00032365827485834723, 'max_iter': 4670}. Best is trial 317 with value: 0.9497125419735118.

Best trial: 317. Best value: 0.949713:  64%|██████▎   | 318/500 [09:20<05:40,  1.87s/it]

[I 2026-05-18 15:07:43,171] Trial 320 finished with value: 0.9497011913474939 and parameters: {'solver': 'saga', 'C': 0.0013463637835915612, 'l1_ratio': 0.9978246476312461, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00015553788869283677, 'max_iter': 4590}. Best is trial 317 with value: 0.9497125419735118.

Best trial: 317. Best value: 0.949713:  64%|██████▍   | 319/500 [09:24<08:03,  2.67s/it]

[I 2026-05-18 15:07:47,749] Trial 319 finished with value: 0.9496999989765589 and parameters: {'solver': 'saga', 'C': 0.0013531778632566525, 'l1_ratio': 0.9989705472728552, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00013181831117590285, 'max_iter': 4588}. Best is trial 317 with value: 0.9497125419735118.

Best trial: 317. Best value: 0.949713:  64%|██████▍   | 320/500 [09:26<07:30,  2.50s/it]

[I 2026-05-18 15:07:49,855] Trial 323 finished with value: 0.9496964720725988 and parameters: {'solver': 'saga', 'C': 0.0008834743703363972, 'l1_ratio': 0.9407825567206535, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014406481102379894, 'max_iter': 4661}. Best is trial 317 with value: 0.9497125419735118.

Best trial: 317. Best value: 0.949713:  64%|██████▍   | 321/500 [09:29<08:05,  2.71s/it]

[I 2026-05-18 15:07:53,056] Trial 327 finished with value: 0.9497022533234192 and parameters: {'solver': 'saga', 'C': 0.0008984148590275481, 'l1_ratio': 0.8956611847826199, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001804577753288983, 'max_iter': 4594}. Best is trial 317 with value: 0.9497125419735118.

Best trial: 325. Best value: 0.949713:  64%|██████▍   | 322/500 [09:30<05:50,  1.97s/it]

[I 2026-05-18 15:07:53,292] Trial 325 finished with value: 0.9497129522133878 and parameters: {'solver': 'saga', 'C': 0.0012923036951043689, 'l1_ratio': 0.9386759982718541, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001222538987988676, 'max_iter': 4655}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  65%|██████▍   | 323/500 [09:31<05:09,  1.75s/it]

[I 2026-05-18 15:07:54,511] Trial 326 finished with value: 0.9497021213906436 and parameters: {'solver': 'saga', 'C': 0.000846587136134298, 'l1_ratio': 0.9000082403983326, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00010863361183466624, 'max_iter': 4590}. Best is trial 325 with value: 0.9497129522133878.
[I 2026-05-18 15:07:54,532] Trial 328 finished with value: 0.9497053037028783 and parameters: {'solver': 'saga', 'C': 0.0008166901087817846, 'l1_ratio': 0.9137701404463727, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001094412171939741, 'max_iter': 4564}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  65%|██████▌   | 325/500 [09:32<03:39,  1.26s/it]

[I 2026-05-18 15:07:55,856] Trial 324 finished with value: 0.949707586329857 and parameters: {'solver': 'saga', 'C': 0.0009506829883072647, 'l1_ratio': 0.9988320445094903, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00011994697523304933, 'max_iter': 4559}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  65%|██████▌   | 326/500 [09:35<04:27,  1.54s/it]

[I 2026-05-18 15:07:58,256] Trial 335 pruned.

Best trial: 325. Best value: 0.949713:  65%|██████▌   | 327/500 [09:36<04:10,  1.45s/it]

[I 2026-05-18 15:07:59,464] Trial 329 finished with value: 0.9497047680437681 and parameters: {'solver': 'saga', 'C': 0.0009071178969503391, 'l1_ratio': 0.9045015106880946, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00011499662713284599, 'max_iter': 4579}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  66%|██████▌   | 328/500 [09:38<04:57,  1.73s/it]

[I 2026-05-18 15:08:01,945] Trial 330 finished with value: 0.9497007382073154 and parameters: {'solver': 'saga', 'C': 0.0008610301141693779, 'l1_ratio': 0.8937759183919106, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00021371695939602565, 'max_iter': 4610}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  66%|██████▌   | 329/500 [09:41<05:15,  1.85s/it]

[I 2026-05-18 15:08:04,086] Trial 331 finished with value: 0.9497025797999239 and parameters: {'solver': 'saga', 'C': 0.0008697249973091611, 'l1_ratio': 0.8995390728716653, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00017864949221271564, 'max_iter': 4530}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  66%|██████▌   | 330/500 [09:45<07:09,  2.53s/it]

[I 2026-05-18 15:08:08,319] Trial 332 finished with value: 0.9497063609094127 and parameters: {'solver': 'saga', 'C': 0.0008993450465002464, 'l1_ratio': 0.9115303406672732, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00016387247171558512, 'max_iter': 4512}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  66%|██████▋   | 332/500 [09:46<04:17,  1.53s/it]

[I 2026-05-18 15:08:09,424] Trial 333 finished with value: 0.9497072617801562 and parameters: {'solver': 'saga', 'C': 0.0009020028057236512, 'l1_ratio': 0.9151086080046196, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00011228398866027898, 'max_iter': 4556}. Best is trial 325 with value: 0.9497129522133878.
[I 2026-05-18 15:08:09,537] Trial 334 finished with value: 0.9496737743365256 and parameters: {'solver': 'saga', 'C': 0.0011336798789419026, 'l1_ratio': 0.7485837813512388, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00015591848374610142, 'max_iter': 4503}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  67%|██████▋   | 333/500 [09:49<05:20,  1.92s/it]

[I 2026-05-18 15:08:12,399] Trial 337 finished with value: 0.9496970470697328 and parameters: {'solver': 'saga', 'C': 0.0009795780622869552, 'l1_ratio': 0.8671821863989911, 'class_weight': None, 'fit_intercept': False, 'tol': 7.462432972327147e-05, 'max_iter': 4517}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  67%|██████▋   | 334/500 [09:50<04:36,  1.67s/it]

[I 2026-05-18 15:08:13,464] Trial 336 finished with value: 0.9496466999156083 and parameters: {'solver': 'saga', 'C': 0.0003516828453145256, 'l1_ratio': 0.7277820691123047, 'class_weight': None, 'fit_intercept': False, 'tol': 7.728849004379319e-05, 'max_iter': 4500}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  67%|██████▋   | 335/500 [09:51<04:12,  1.53s/it]

[I 2026-05-18 15:08:14,657] Trial 318 finished with value: 0.949699930488689 and parameters: {'solver': 'saga', 'C': 0.001326434167127683, 'l1_ratio': 0.9996232544629564, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00014024601931844627, 'max_iter': 4562}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  67%|██████▋   | 336/500 [09:52<03:24,  1.25s/it]

[I 2026-05-18 15:08:15,249] Trial 338 finished with value: 0.9497122439224366 and parameters: {'solver': 'saga', 'C': 0.0011190647795257377, 'l1_ratio': 0.9314225390469759, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001199803433375101, 'max_iter': 4736}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  67%|██████▋   | 337/500 [09:53<03:42,  1.36s/it]

[I 2026-05-18 15:08:16,890] Trial 339 finished with value: 0.9496632447517376 and parameters: {'solver': 'saga', 'C': 0.0002993220769624319, 'l1_ratio': 0.8627875366561191, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00016044044018428537, 'max_iter': 4717}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  68%|██████▊   | 338/500 [09:56<04:38,  1.72s/it]

[I 2026-05-18 15:08:19,425] Trial 340 finished with value: 0.9496652410362193 and parameters: {'solver': 'saga', 'C': 0.0003034303396505514, 'l1_ratio': 0.8705346337941829, 'class_weight': None, 'fit_intercept': False, 'tol': 8.711636869604299e-05, 'max_iter': 4767}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  68%|██████▊   | 339/500 [09:59<06:02,  2.25s/it]

[I 2026-05-18 15:08:22,941] Trial 341 finished with value: 0.9497009467799493 and parameters: {'solver': 'saga', 'C': 0.0011022037588623126, 'l1_ratio': 0.8736781350466372, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00016847992942253882, 'max_iter': 4754}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  68%|██████▊   | 340/500 [10:01<05:11,  1.95s/it]

[I 2026-05-18 15:08:24,174] Trial 322 finished with value: 0.949701912041481 and parameters: {'solver': 'saga', 'C': 0.0013168965683227612, 'l1_ratio': 0.9990055049729711, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017165585487128392, 'max_iter': 4582}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  68%|██████▊   | 341/500 [10:03<05:26,  2.05s/it]

[I 2026-05-18 15:08:26,482] Trial 342 finished with value: 0.9496742336340894 and parameters: {'solver': 'saga', 'C': 0.0004359376348814228, 'l1_ratio': 0.8665587147149851, 'class_weight': None, 'fit_intercept': False, 'tol': 7.967647953805137e-05, 'max_iter': 4495}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  68%|██████▊   | 342/500 [10:04<04:19,  1.65s/it]

[I 2026-05-18 15:08:27,172] Trial 343 finished with value: 0.9496941803423005 and parameters: {'solver': 'saga', 'C': 0.0011068292183499355, 'l1_ratio': 0.8399893804830454, 'class_weight': None, 'fit_intercept': False, 'tol': 7.366155712447376e-05, 'max_iter': 4705}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  69%|██████▊   | 343/500 [10:05<04:02,  1.54s/it]

[I 2026-05-18 15:08:28,470] Trial 344 finished with value: 0.9496767533992353 and parameters: {'solver': 'saga', 'C': 0.0004817795694616872, 'l1_ratio': 0.8649690064529547, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00012434683668850822, 'max_iter': 4767}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  69%|██████▉   | 344/500 [10:06<03:22,  1.30s/it]

[I 2026-05-18 15:08:29,199] Trial 345 finished with value: 0.9497037179757946 and parameters: {'solver': 'saga', 'C': 0.0006972163033744699, 'l1_ratio': 0.9192094566478096, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00013120797066449474, 'max_iter': 4757}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  69%|██████▉   | 345/500 [10:07<03:38,  1.41s/it]

[I 2026-05-18 15:08:30,863] Trial 347 finished with value: 0.9496863068926373 and parameters: {'solver': 'saga', 'C': 0.0007036070650144734, 'l1_ratio': 0.8590607325868943, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00011021488347314508, 'max_iter': 4739}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  69%|██████▉   | 346/500 [10:08<02:43,  1.06s/it]

[I 2026-05-18 15:08:31,130] Trial 346 finished with value: 0.949692388097976 and parameters: {'solver': 'saga', 'C': 0.0004205964856855604, 'l1_ratio': 0.9280801337579592, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00011612367636141265, 'max_iter': 4728}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  69%|██████▉   | 347/500 [10:10<03:38,  1.43s/it]

[I 2026-05-18 15:08:33,397] Trial 348 finished with value: 0.9497042191729512 and parameters: {'solver': 'saga', 'C': 0.0007400914548368426, 'l1_ratio': 0.916450237237719, 'class_weight': None, 'fit_intercept': False, 'tol': 9.83374448598294e-05, 'max_iter': 4718}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  70%|██████▉   | 348/500 [10:11<03:14,  1.28s/it]

[I 2026-05-18 15:08:34,327] Trial 349 finished with value: 0.9496770647890319 and parameters: {'solver': 'saga', 'C': 0.0007542219579294663, 'l1_ratio': 0.8045027229669617, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00011866507650491242, 'max_iter': 4400}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  70%|██████▉   | 349/500 [10:15<05:07,  2.04s/it]

[I 2026-05-18 15:08:38,137] Trial 350 finished with value: 0.9496906177711051 and parameters: {'solver': 'saga', 'C': 0.0004535193638101218, 'l1_ratio': 0.9167375790211512, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00011494508054555226, 'max_iter': 4341}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  70%|███████   | 350/500 [10:18<06:11,  2.47s/it]

[I 2026-05-18 15:08:41,635] Trial 352 finished with value: 0.9497022916835988 and parameters: {'solver': 'saga', 'C': 0.0007073076624692616, 'l1_ratio': 0.9137918265696364, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00011902071893564898, 'max_iter': 4379}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  70%|███████   | 351/500 [10:19<04:56,  1.99s/it]

[I 2026-05-18 15:08:42,497] Trial 351 finished with value: 0.949518364709385 and parameters: {'solver': 'saga', 'C': 70.06271294593569, 'l1_ratio': 0.9212520683412726, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00011948458953405358, 'max_iter': 4368}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  70%|███████   | 352/500 [10:21<04:38,  1.88s/it]

[I 2026-05-18 15:08:44,120] Trial 353 finished with value: 0.9497032434639298 and parameters: {'solver': 'saga', 'C': 0.00068736360133167, 'l1_ratio': 0.9186316754234624, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00011799265082377492, 'max_iter': 4350}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  71%|███████   | 353/500 [10:21<03:51,  1.58s/it]

[I 2026-05-18 15:08:44,981] Trial 354 finished with value: 0.9497029522894034 and parameters: {'solver': 'saga', 'C': 0.0007104155748507943, 'l1_ratio': 0.9154869784919917, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00010730108098614388, 'max_iter': 4358}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  71%|███████   | 354/500 [10:22<03:16,  1.35s/it]

[I 2026-05-18 15:08:45,799] Trial 355 finished with value: 0.9497066371033849 and parameters: {'solver': 'saga', 'C': 0.0007512889272101914, 'l1_ratio': 0.9229912350095394, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00010269312588985652, 'max_iter': 4423}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  71%|███████   | 355/500 [10:23<02:56,  1.22s/it]

[I 2026-05-18 15:08:46,719] Trial 356 finished with value: 0.9497052098359717 and parameters: {'solver': 'saga', 'C': 0.0007468421057544638, 'l1_ratio': 0.9187664203458434, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00012078966390257293, 'max_iter': 4378}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  71%|███████   | 356/500 [10:24<02:23,  1.00it/s]

[I 2026-05-18 15:08:47,197] Trial 357 finished with value: 0.9496814611291506 and parameters: {'solver': 'saga', 'C': 0.0008447629763995726, 'l1_ratio': 0.8106197271424844, 'class_weight': None, 'fit_intercept': False, 'tol': 9.75157981163012e-05, 'max_iter': 4441}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 325. Best value: 0.949713:  71%|███████▏  | 357/500 [10:24<01:54,  1.25it/s]

[I 2026-05-18 15:08:47,548] Trial 358 finished with value: 0.9497126940093903 and parameters: {'solver': 'saga', 'C': 0.0009841817890294177, 'l1_ratio': 0.9340927482415996, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00012476090356948637, 'max_iter': 4392}. Best is trial 325 with value: 0.9497129522133878.

Best trial: 359. Best value: 0.949714:  72%|███████▏  | 358/500 [10:27<03:38,  1.54s/it]

[I 2026-05-18 15:08:50,795] Trial 359 finished with value: 0.9497139698538071 and parameters: {'solver': 'saga', 'C': 0.0011259990309810352, 'l1_ratio': 0.9405287263360853, 'class_weight': None, 'fit_intercept': False, 'tol': 9.229861898129603e-05, 'max_iter': 4302}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  72%|███████▏  | 359/500 [10:31<04:56,  2.10s/it]

[I 2026-05-18 15:08:54,228] Trial 360 finished with value: 0.9497129100497684 and parameters: {'solver': 'saga', 'C': 0.001061834950198374, 'l1_ratio': 0.9348364228916699, 'class_weight': None, 'fit_intercept': False, 'tol': 9.503812659583646e-05, 'max_iter': 4422}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  72%|███████▏  | 360/500 [10:33<05:21,  2.29s/it]

[I 2026-05-18 15:08:56,963] Trial 361 finished with value: 0.9497122250455803 and parameters: {'solver': 'saga', 'C': 0.0010639907432422905, 'l1_ratio': 0.9309569557356764, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00022175265574192005, 'max_iter': 4657}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  72%|███████▏  | 361/500 [10:36<05:18,  2.29s/it]

[I 2026-05-18 15:08:59,243] Trial 364 finished with value: 0.9497139457668942 and parameters: {'solver': 'saga', 'C': 0.0010601771148539337, 'l1_ratio': 0.9396406668196164, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00022361297808137749, 'max_iter': 4943}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  72%|███████▏  | 362/500 [10:36<03:56,  1.72s/it]

[I 2026-05-18 15:08:59,617] Trial 362 finished with value: 0.9497133238832063 and parameters: {'solver': 'saga', 'C': 0.0010845266365801143, 'l1_ratio': 0.9371782757347981, 'class_weight': None, 'fit_intercept': False, 'tol': 9.26350724630959e-05, 'max_iter': 4972}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  73%|███████▎  | 363/500 [10:37<03:28,  1.52s/it]

[I 2026-05-18 15:09:00,681] Trial 365 finished with value: 0.9497035283472588 and parameters: {'solver': 'saga', 'C': 0.0009892327885701628, 'l1_ratio': 0.894420951349472, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00014996357775733506, 'max_iter': 4262}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  73%|███████▎  | 364/500 [10:37<02:36,  1.15s/it]

[I 2026-05-18 15:09:00,968] Trial 363 finished with value: 0.9497135346991937 and parameters: {'solver': 'saga', 'C': 0.001033323257604024, 'l1_ratio': 0.9380333206510545, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00014909434887781518, 'max_iter': 4269}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  73%|███████▎  | 365/500 [10:39<02:56,  1.31s/it]

[I 2026-05-18 15:09:02,654] Trial 366 finished with value: 0.9497034798690278 and parameters: {'solver': 'saga', 'C': 0.0009697982944108533, 'l1_ratio': 0.8955152084843184, 'class_weight': None, 'fit_intercept': False, 'tol': 9.154886245906183e-05, 'max_iter': 4955}. Best is trial 359 with value: 0.9497139698538071.
[I 2026-05-18 15:09:02,664] Trial 367 finished with value: 0.9497040399576031 and parameters: {'solver': 'saga', 'C': 0.001082633712528839, 'l1_ratio': 0.8909179791545588, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001496622565257242, 'max_iter': 4638}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  73%|███████▎  | 367/500 [10:42<03:00,  1.36s/it]

[I 2026-05-18 15:09:05,470] Trial 368 finished with value: 0.9497039322772383 and parameters: {'solver': 'saga', 'C': 0.0011456040879295575, 'l1_ratio': 0.886748874227179, 'class_weight': None, 'fit_intercept': False, 'tol': 6.083199010271441e-05, 'max_iter': 4284}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  74%|███████▎  | 368/500 [10:46<04:14,  1.93s/it]

[I 2026-05-18 15:09:09,112] Trial 321 finished with value: 0.9497014482661251 and parameters: {'solver': 'saga', 'C': 0.0013496870918021549, 'l1_ratio': 0.9995996378875136, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014532397069404236, 'max_iter': 4573}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  74%|███████▍  | 369/500 [10:46<03:19,  1.52s/it]

[I 2026-05-18 15:09:09,509] Trial 369 finished with value: 0.9497053772699704 and parameters: {'solver': 'saga', 'C': 0.001057155633358145, 'l1_ratio': 0.8986759770997992, 'class_weight': None, 'fit_intercept': False, 'tol': 4.146183710256909e-05, 'max_iter': 4272}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  74%|███████▍  | 370/500 [10:48<03:46,  1.74s/it]

[I 2026-05-18 15:09:11,829] Trial 370 finished with value: 0.9497044502058669 and parameters: {'solver': 'saga', 'C': 0.001013980814594416, 'l1_ratio': 0.8963499483505487, 'class_weight': None, 'fit_intercept': False, 'tol': 8.567029566063813e-05, 'max_iter': 4200}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  74%|███████▍  | 371/500 [10:49<03:21,  1.56s/it]

[I 2026-05-18 15:09:12,942] Trial 371 finished with value: 0.9497043771789487 and parameters: {'solver': 'saga', 'C': 0.00112588342710901, 'l1_ratio': 0.8900639604667561, 'class_weight': None, 'fit_intercept': False, 'tol': 8.83068385699918e-05, 'max_iter': 4223}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  74%|███████▍  | 372/500 [10:52<03:50,  1.80s/it]

[I 2026-05-18 15:09:15,325] Trial 373 finished with value: 0.9496879142136398 and parameters: {'solver': 'saga', 'C': 0.0005702013884973333, 'l1_ratio': 0.887624585062705, 'class_weight': None, 'fit_intercept': False, 'tol': 9.214753798618962e-05, 'max_iter': 4275}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  75%|███████▍  | 373/500 [10:52<03:07,  1.48s/it]

[I 2026-05-18 15:09:16,024] Trial 372 finished with value: 0.9496822435164644 and parameters: {'solver': 'saga', 'C': 0.00048544527973536344, 'l1_ratio': 0.884645769735132, 'class_weight': None, 'fit_intercept': False, 'tol': 8.940681760074392e-05, 'max_iter': 4300}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  75%|███████▍  | 374/500 [10:53<02:40,  1.27s/it]

[I 2026-05-18 15:09:16,798] Trial 374 finished with value: 0.9496862811475081 and parameters: {'solver': 'saga', 'C': 0.0004559319640316, 'l1_ratio': 0.9040202968118398, 'class_weight': None, 'fit_intercept': False, 'tol': 5.871503793413435e-05, 'max_iter': 4975}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  75%|███████▌  | 375/500 [10:55<02:53,  1.39s/it]

[I 2026-05-18 15:09:18,471] Trial 377 finished with value: 0.9496875444548014 and parameters: {'solver': 'saga', 'C': 0.0005106558198300983, 'l1_ratio': 0.8972458601295119, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00010635319705267057, 'max_iter': 4975}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  75%|███████▌  | 376/500 [10:55<02:20,  1.13s/it]

[I 2026-05-18 15:09:18,988] Trial 375 finished with value: 0.9496848994239775 and parameters: {'solver': 'saga', 'C': 0.00044093554661465365, 'l1_ratio': 0.9031945781434803, 'class_weight': None, 'fit_intercept': False, 'tol': 6.480670131761839e-05, 'max_iter': 4950}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  75%|███████▌  | 377/500 [10:57<02:21,  1.15s/it]

[I 2026-05-18 15:09:20,175] Trial 376 finished with value: 0.9496802821953192 and parameters: {'solver': 'saga', 'C': 0.00045427418559603757, 'l1_ratio': 0.8846936502299986, 'class_weight': None, 'fit_intercept': False, 'tol': 8.42627313548174e-05, 'max_iter': 4989}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  76%|███████▌  | 378/500 [10:58<02:25,  1.19s/it]

[I 2026-05-18 15:09:21,469] Trial 378 finished with value: 0.9497016926902978 and parameters: {'solver': 'saga', 'C': 0.0005122178908765176, 'l1_ratio': 0.9349810959425875, 'class_weight': None, 'fit_intercept': False, 'tol': 9.412869814023633e-05, 'max_iter': 4986}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  76%|███████▌  | 379/500 [11:02<04:25,  2.19s/it]

[I 2026-05-18 15:09:26,004] Trial 379 finished with value: 0.9496980887248003 and parameters: {'solver': 'saga', 'C': 0.0004833819985984205, 'l1_ratio': 0.9304262043481528, 'class_weight': None, 'fit_intercept': False, 'tol': 8.544019045074575e-05, 'max_iter': 4462}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  76%|███████▌  | 380/500 [11:03<03:24,  1.70s/it]

[I 2026-05-18 15:09:26,552] Trial 380 finished with value: 0.9497000399571915 and parameters: {'solver': 'saga', 'C': 0.0004951532051930058, 'l1_ratio': 0.9334795593995782, 'class_weight': None, 'fit_intercept': False, 'tol': 5.285442100617071e-05, 'max_iter': 4437}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  76%|███████▌  | 381/500 [11:05<03:42,  1.87s/it]

[I 2026-05-18 15:09:28,814] Trial 381 finished with value: 0.9497002159656999 and parameters: {'solver': 'saga', 'C': 0.0004939345265232779, 'l1_ratio': 0.9342159698644585, 'class_weight': None, 'fit_intercept': False, 'tol': 9.271714947299307e-05, 'max_iter': 4987}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  76%|███████▋  | 382/500 [11:07<03:50,  1.95s/it]

[I 2026-05-18 15:09:30,973] Trial 382 finished with value: 0.9497018844867787 and parameters: {'solver': 'saga', 'C': 0.000534331671794051, 'l1_ratio': 0.9320811020697625, 'class_weight': None, 'fit_intercept': False, 'tol': 5.818983630893028e-05, 'max_iter': 4991}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  77%|███████▋  | 383/500 [11:09<03:23,  1.74s/it]

[I 2026-05-18 15:09:32,202] Trial 383 finished with value: 0.9497021454074746 and parameters: {'solver': 'saga', 'C': 0.0005310731092382998, 'l1_ratio': 0.933210980314164, 'class_weight': None, 'fit_intercept': False, 'tol': 9.812175269112336e-05, 'max_iter': 4475}. Best is trial 359 with value: 0.9497139698538071.
[I 2026-05-18 15:09:32,403] Trial 384 finished with value: 0.9497020543151269 and parameters: {'solver': 'saga', 'C': 0.0005422746666123364, 'l1_ratio': 0.9313100984465943, 'class_weight': None, 'fit_intercept': False, 'tol': 9.371010666939159e-05, 'max_iter': 4498}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  77%|███████▋  | 385/500 [11:10<02:13,  1.16s/it]

[I 2026-05-18 15:09:33,303] Trial 385 finished with value: 0.9496874201389888 and parameters: {'solver': 'saga', 'C': 0.00035633481114655355, 'l1_ratio': 0.930050615452692, 'class_weight': None, 'fit_intercept': False, 'tol': 9.346625916337612e-05, 'max_iter': 4447}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  77%|███████▋  | 387/500 [11:12<02:08,  1.14s/it]

[I 2026-05-18 15:09:35,793] Trial 387 finished with value: 0.9497070162675243 and parameters: {'solver': 'saga', 'C': 0.0006473125249757714, 'l1_ratio': 0.933242170293296, 'class_weight': None, 'fit_intercept': False, 'tol': 7.527578777427367e-05, 'max_iter': 4463}. Best is trial 359 with value: 0.9497139698538071.
[I 2026-05-18 15:09:35,943] Trial 386 finished with value: 0.9497039692855583 and parameters: {'solver': 'saga', 'C': 0.0006042176963444903, 'l1_ratio': 0.9292344504447635, 'class_weight': None, 'fit_intercept': False, 'tol': 4.597946328449109e-05, 'max_iter': 4451}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  78%|███████▊  | 388/500 [11:15<03:06,  1.66s/it]

[I 2026-05-18 15:09:38,835] Trial 388 finished with value: 0.9497090724265613 and parameters: {'solver': 'saga', 'C': 0.0006802540026932323, 'l1_ratio': 0.9363285042752463, 'class_weight': None, 'fit_intercept': False, 'tol': 5.054725609739057e-05, 'max_iter': 4434}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  78%|███████▊  | 389/500 [11:16<02:19,  1.25s/it]

[I 2026-05-18 15:09:39,128] Trial 389 finished with value: 0.9497093211545116 and parameters: {'solver': 'saga', 'C': 0.000708983708862835, 'l1_ratio': 0.9349140620376386, 'class_weight': None, 'fit_intercept': False, 'tol': 7.040739998920626e-05, 'max_iter': 4440}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  78%|███████▊  | 390/500 [11:18<02:52,  1.57s/it]

[I 2026-05-18 15:09:41,440] Trial 391 finished with value: 0.9497121867731494 and parameters: {'solver': 'saga', 'C': 0.0008045029355400736, 'l1_ratio': 0.9379550003663333, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00013588789668457493, 'max_iter': 4440}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  78%|███████▊  | 391/500 [11:19<02:40,  1.47s/it]

[I 2026-05-18 15:09:42,684] Trial 390 finished with value: 0.9495332398824541 and parameters: {'solver': 'saga', 'C': 0.11264884180743627, 'l1_ratio': 0.942674000802696, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00013681402428429029, 'max_iter': 4485}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 359. Best value: 0.949714:  78%|███████▊  | 392/500 [11:22<03:12,  1.79s/it]

[I 2026-05-18 15:09:45,203] Trial 397 pruned.

Best trial: 359. Best value: 0.949714:  79%|███████▉  | 394/500 [11:22<01:49,  1.03s/it]

[I 2026-05-18 15:09:45,753] Trial 392 finished with value: 0.9497117311298512 and parameters: {'solver': 'saga', 'C': 0.0007764583847653117, 'l1_ratio': 0.9375310758093868, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00013966862851196406, 'max_iter': 4447}. Best is trial 359 with value: 0.9497139698538071.
[I 2026-05-18 15:09:45,875] Trial 393 finished with value: 0.9497132644664376 and parameters: {'solver': 'saga', 'C': 0.0008156872498650553, 'l1_ratio': 0.940912677580895, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00014000551798677564, 'max_iter': 4455}. Best is trial 359 with value: 0.9497139698538071.

Best trial: 394. Best value: 0.949714:  79%|███████▉  | 395/500 [11:24<02:08,  1.22s/it]

[I 2026-05-18 15:09:47,562] Trial 394 finished with value: 0.9497141760657432 and parameters: {'solver': 'saga', 'C': 0.0008036146388656254, 'l1_ratio': 0.944587711912231, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00014690966579133298, 'max_iter': 4648}. Best is trial 394 with value: 0.9497141760657432.

Best trial: 394. Best value: 0.949714:  79%|███████▉  | 396/500 [11:24<01:45,  1.01s/it]

[I 2026-05-18 15:09:48,073] Trial 395 finished with value: 0.9497134311980178 and parameters: {'solver': 'saga', 'C': 0.0007830651143124291, 'l1_ratio': 0.9432418411881145, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00013674215304047182, 'max_iter': 4626}. Best is trial 394 with value: 0.9497141760657432.

Best trial: 394. Best value: 0.949714:  79%|███████▉  | 397/500 [11:26<02:06,  1.23s/it]

[I 2026-05-18 15:09:49,799] Trial 396 finished with value: 0.9497136418535582 and parameters: {'solver': 'saga', 'C': 0.0007690111530194061, 'l1_ratio': 0.9446288082415334, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001396572867865685, 'max_iter': 4634}. Best is trial 394 with value: 0.9497141760657432.

Best trial: 398. Best value: 0.949715:  80%|███████▉  | 398/500 [11:28<02:22,  1.40s/it]

[I 2026-05-18 15:09:51,596] Trial 398 finished with value: 0.9497146086068529 and parameters: {'solver': 'saga', 'C': 0.0008053604578252677, 'l1_ratio': 0.9457890093180699, 'class_weight': None, 'fit_intercept': False, 'tol': 7.64761017445739e-05, 'max_iter': 4611}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  80%|███████▉  | 399/500 [11:35<04:56,  2.93s/it]

[I 2026-05-18 15:09:58,113] Trial 399 finished with value: 0.9496648383296374 and parameters: {'solver': 'saga', 'C': 0.00020166531603367703, 'l1_ratio': 0.9441100538611372, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.429733075525867e-05, 'max_iter': 4522}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  80%|████████  | 400/500 [11:35<03:52,  2.32s/it]

[I 2026-05-18 15:09:59,005] Trial 400 finished with value: 0.9496739520512373 and parameters: {'solver': 'saga', 'C': 0.0002923721260361931, 'l1_ratio': 0.9120858216196299, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 4.8697188958008947e-05, 'max_iter': 4105}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  80%|████████  | 401/500 [11:36<02:56,  1.78s/it]

[I 2026-05-18 15:09:59,540] Trial 402 finished with value: 0.9496725294508724 and parameters: {'solver': 'saga', 'C': 0.0002616858509873962, 'l1_ratio': 0.9156378760611452, 'class_weight': None, 'fit_intercept': False, 'tol': 7.19487165082491e-05, 'max_iter': 4408}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  80%|████████  | 402/500 [11:38<03:07,  1.91s/it]

[I 2026-05-18 15:10:01,756] Trial 401 finished with value: 0.9496729783233896 and parameters: {'solver': 'saga', 'C': 0.00034534002361063615, 'l1_ratio': 0.9079520797497436, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.13450656252314e-05, 'max_iter': 4549}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  81%|████████  | 403/500 [11:41<03:24,  2.11s/it]

[I 2026-05-18 15:10:04,323] Trial 405 finished with value: 0.9496744789126265 and parameters: {'solver': 'saga', 'C': 0.00022243541257051166, 'l1_ratio': 0.9096729375764891, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.584852899933717e-05, 'max_iter': 4410}. Best is trial 398 with value: 0.9497146086068529.
[I 2026-05-18 15:10:04,397] Trial 404 finished with value: 0.9497037163559631 and parameters: {'solver': 'saga', 'C': 0.0007325553779888588, 'l1_ratio': 0.915666705558001, 'class_weight': None, 'fit_intercept': False, 'tol': 4.950161357005691e-05, 'max_iter': 4400}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  81%|████████  | 405/500 [11:41<02:03,  1.30s/it]

[I 2026-05-18 15:10:05,031] Trial 403 finished with value: 0.9496726479356468 and parameters: {'solver': 'saga', 'C': 0.00027002116653933626, 'l1_ratio': 0.9239814811684126, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.19080454326445e-05, 'max_iter': 4391}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  81%|████████  | 406/500 [11:43<01:56,  1.24s/it]

[I 2026-05-18 15:10:06,095] Trial 406 finished with value: 0.9496686676595724 and parameters: {'solver': 'saga', 'C': 0.0002408540701309513, 'l1_ratio': 0.909544816745842, 'class_weight': None, 'fit_intercept': False, 'tol': 3.23572042076905e-05, 'max_iter': 4377}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  81%|████████▏ | 407/500 [11:43<01:41,  1.09s/it]

[I 2026-05-18 15:10:06,769] Trial 408 finished with value: 0.9496730705534656 and parameters: {'solver': 'saga', 'C': 0.00033309910450992643, 'l1_ratio': 0.909384778759907, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.708776529398221e-05, 'max_iter': 4574}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  82%|████████▏ | 408/500 [11:43<01:19,  1.16it/s]

[I 2026-05-18 15:10:07,026] Trial 407 finished with value: 0.9496708459469183 and parameters: {'solver': 'saga', 'C': 0.00022164696161004602, 'l1_ratio': 0.8349015484111288, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.207753952442508e-05, 'max_iter': 4393}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  82%|████████▏ | 409/500 [11:46<01:52,  1.24s/it]

[I 2026-05-18 15:10:09,222] Trial 409 finished with value: 0.9496747193378374 and parameters: {'solver': 'saga', 'C': 0.0002265164069073616, 'l1_ratio': 0.9061624093372793, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.580324018711898e-05, 'max_iter': 4576}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  82%|████████▏ | 410/500 [11:52<03:50,  2.57s/it]

[I 2026-05-18 15:10:15,089] Trial 410 finished with value: 0.9496995493808266 and parameters: {'solver': 'saga', 'C': 0.0006688518742630649, 'l1_ratio': 0.9099301716342333, 'class_weight': None, 'fit_intercept': False, 'tol': 6.87693788637495e-05, 'max_iter': 4607}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  82%|████████▏ | 411/500 [11:53<03:33,  2.40s/it]

[I 2026-05-18 15:10:17,091] Trial 411 finished with value: 0.9496820671577855 and parameters: {'solver': 'saga', 'C': 0.0003734931246488475, 'l1_ratio': 0.9109367130998207, 'class_weight': None, 'fit_intercept': False, 'tol': 3.715273659333356e-05, 'max_iter': 4595}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  82%|████████▏ | 412/500 [11:54<02:52,  1.96s/it]

[I 2026-05-18 15:10:17,997] Trial 309 finished with value: 0.9497013217084979 and parameters: {'solver': 'saga', 'C': 0.0013552670826167802, 'l1_ratio': 0.9998794230269072, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003136121024108304, 'max_iter': 4586}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  83%|████████▎ | 413/500 [11:55<02:19,  1.61s/it]

[I 2026-05-18 15:10:18,765] Trial 412 finished with value: 0.9496603428835995 and parameters: {'solver': 'saga', 'C': 0.00030576280667763827, 'l1_ratio': 0.8457163416264772, 'class_weight': None, 'fit_intercept': False, 'tol': 3.7940584984842426e-05, 'max_iter': 4609}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  83%|████████▎ | 414/500 [11:56<01:54,  1.33s/it]

[I 2026-05-18 15:10:19,433] Trial 413 finished with value: 0.949678580148721 and parameters: {'solver': 'saga', 'C': 0.00033759120401556615, 'l1_ratio': 0.9100326042194175, 'class_weight': None, 'fit_intercept': False, 'tol': 7.239192158508836e-05, 'max_iter': 4630}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  83%|████████▎ | 415/500 [11:57<01:52,  1.32s/it]

[I 2026-05-18 15:10:20,733] Trial 418 finished with value: 0.9496806044851637 and parameters: {'solver': 'saga', 'C': 0.0006888742955009416, 'l1_ratio': 0.836322684281348, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001678359098832841, 'max_iter': 4656}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  83%|████████▎ | 416/500 [11:58<01:34,  1.13s/it]

[I 2026-05-18 15:10:21,395] Trial 416 finished with value: 0.949712414824979 and parameters: {'solver': 'saga', 'C': 0.000741126303669852, 'l1_ratio': 0.9418379680635091, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001774650873439969, 'max_iter': 4619}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  83%|████████▎ | 417/500 [11:58<01:21,  1.02it/s]

[I 2026-05-18 15:10:22,044] Trial 414 finished with value: 0.9496905448626182 and parameters: {'solver': 'saga', 'C': 0.00035381929581390967, 'l1_ratio': 0.9391175028158435, 'class_weight': None, 'fit_intercept': False, 'tol': 7.066568361310567e-05, 'max_iter': 4621}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  84%|████████▎ | 418/500 [11:59<01:11,  1.15it/s]

[I 2026-05-18 15:10:22,659] Trial 415 finished with value: 0.9496800141528661 and parameters: {'solver': 'saga', 'C': 0.0006830305418825846, 'l1_ratio': 0.8346553890736605, 'class_weight': None, 'fit_intercept': False, 'tol': 3.6961358393332156e-05, 'max_iter': 4646}. Best is trial 398 with value: 0.9497146086068529.
[I 2026-05-18 15:10:22,665] Trial 419 finished with value: 0.9497098405515283 and parameters: {'solver': 'saga', 'C': 0.0006584727111603413, 'l1_ratio': 0.9401517963779625, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001366711425086555, 'max_iter': 4613}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  84%|████████▍ | 420/500 [12:01<01:19,  1.01it/s]

[I 2026-05-18 15:10:24,922] Trial 420 finished with value: 0.9497118509981067 and parameters: {'solver': 'saga', 'C': 0.0006756848195087047, 'l1_ratio': 0.9441465265162033, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00016304832790174008, 'max_iter': 4656}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  84%|████████▍ | 421/500 [12:02<01:12,  1.10it/s]

[I 2026-05-18 15:10:25,588] Trial 417 finished with value: 0.9496909949745953 and parameters: {'solver': 'saga', 'C': 0.00036310053909285785, 'l1_ratio': 0.9379399848697055, 'class_weight': None, 'fit_intercept': False, 'tol': 3.580470606668974e-05, 'max_iter': 4625}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  84%|████████▍ | 422/500 [12:09<03:05,  2.38s/it]

[I 2026-05-18 15:10:32,122] Trial 422 finished with value: 0.9497110979953923 and parameters: {'solver': 'saga', 'C': 0.0006712116207948604, 'l1_ratio': 0.9424866044989184, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00017567683439527037, 'max_iter': 4656}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  85%|████████▍ | 423/500 [12:09<02:21,  1.83s/it]

[I 2026-05-18 15:10:32,488] Trial 423 finished with value: 0.9497121252642607 and parameters: {'solver': 'saga', 'C': 0.0007039884527871687, 'l1_ratio': 0.9430380086530061, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00015675999627804384, 'max_iter': 4657}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  85%|████████▌ | 425/500 [12:11<01:40,  1.34s/it]

[I 2026-05-18 15:10:34,296] Trial 424 finished with value: 0.9495591981135405 and parameters: {'solver': 'saga', 'C': 0.0006549311474622387, 'l1_ratio': 0.5520401450178578, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00017047774629857273, 'max_iter': 4669}. Best is trial 398 with value: 0.9497146086068529.
[I 2026-05-18 15:10:34,422] Trial 421 finished with value: 0.9497109232957832 and parameters: {'solver': 'saga', 'C': 0.0007112865116393655, 'l1_ratio': 0.9391000680563658, 'class_weight': None, 'fit_intercept': False, 'tol': 3.8842231574875356e-05, 'max_iter': 4653}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  85%|████████▌ | 426/500 [12:11<01:14,  1.01s/it]

[I 2026-05-18 15:10:34,610] Trial 425 finished with value: 0.9497108541606412 and parameters: {'solver': 'saga', 'C': 0.0007112773107466362, 'l1_ratio': 0.938897840051549, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00016520895142368153, 'max_iter': 4673}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  85%|████████▌ | 427/500 [12:12<01:13,  1.00s/it]

[I 2026-05-18 15:10:35,598] Trial 427 finished with value: 0.9497127323561315 and parameters: {'solver': 'saga', 'C': 0.0007305361043741644, 'l1_ratio': 0.9434225460878688, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001826454974378333, 'max_iter': 4689}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  86%|████████▌ | 429/500 [12:14<01:06,  1.07it/s]

[I 2026-05-18 15:10:37,481] Trial 426 finished with value: 0.9497121597405205 and parameters: {'solver': 'saga', 'C': 0.0006527460703741921, 'l1_ratio': 0.9467644655645866, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00013131863763403396, 'max_iter': 4673}. Best is trial 398 with value: 0.9497146086068529.
[I 2026-05-18 15:10:37,655] Trial 428 finished with value: 0.9497118731328706 and parameters: {'solver': 'saga', 'C': 0.0007431931872031131, 'l1_ratio': 0.9400774721261864, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00017226231308233755, 'max_iter': 4675}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  86%|████████▌ | 430/500 [12:15<01:06,  1.06it/s]

[I 2026-05-18 15:10:38,622] Trial 429 finished with value: 0.9497143530536667 and parameters: {'solver': 'saga', 'C': 0.0008155630868979722, 'l1_ratio': 0.9445912689573631, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00017369543396988853, 'max_iter': 4691}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  86%|████████▌ | 431/500 [12:16<00:58,  1.18it/s]

[I 2026-05-18 15:10:39,242] Trial 430 finished with value: 0.9497138813135486 and parameters: {'solver': 'saga', 'C': 0.0008317466109661715, 'l1_ratio': 0.9426434642318771, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001792427145571694, 'max_iter': 4686}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  86%|████████▋ | 432/500 [12:16<00:48,  1.41it/s]

[I 2026-05-18 15:10:39,627] Trial 431 finished with value: 0.9497106768355452 and parameters: {'solver': 'saga', 'C': 0.0006391139887428185, 'l1_ratio': 0.9439814350393044, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00018244471639913392, 'max_iter': 4689}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  87%|████████▋ | 433/500 [12:17<00:43,  1.53it/s]

[I 2026-05-18 15:10:40,144] Trial 432 finished with value: 0.949710023222741 and parameters: {'solver': 'saga', 'C': 0.0006246098752665926, 'l1_ratio': 0.9433017961751143, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001799933804408449, 'max_iter': 4817}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  87%|████████▋ | 434/500 [12:24<02:52,  2.62s/it]

[I 2026-05-18 15:10:47,360] Trial 433 finished with value: 0.9497091456147168 and parameters: {'solver': 'saga', 'C': 0.0006193611929231499, 'l1_ratio': 0.941683255825721, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00018156661224303652, 'max_iter': 4817}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  87%|████████▋ | 435/500 [12:24<02:03,  1.90s/it]

[I 2026-05-18 15:10:47,572] Trial 434 finished with value: 0.9497096057965736 and parameters: {'solver': 'saga', 'C': 0.0005656696757221729, 'l1_ratio': 0.9485539974904266, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001856791690207063, 'max_iter': 4712}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  87%|████████▋ | 436/500 [12:26<02:08,  2.01s/it]

[I 2026-05-18 15:10:49,846] Trial 435 finished with value: 0.9497094323934328 and parameters: {'solver': 'saga', 'C': 0.0005805104956748017, 'l1_ratio': 0.9462801859633848, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00019068209042161325, 'max_iter': 4709}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  88%|████████▊ | 438/500 [12:27<01:15,  1.22s/it]

[I 2026-05-18 15:10:50,747] Trial 437 finished with value: 0.9497063725520645 and parameters: {'solver': 'saga', 'C': 0.000527441972330173, 'l1_ratio': 0.9448682189072849, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00019378400795408882, 'max_iter': 4798}. Best is trial 398 with value: 0.9497146086068529.
[I 2026-05-18 15:10:50,890] Trial 438 finished with value: 0.9496986344738051 and parameters: {'solver': 'saga', 'C': 0.00044747485799382346, 'l1_ratio': 0.937951354191217, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00017842544514760347, 'max_iter': 4801}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  88%|████████▊ | 439/500 [12:27<00:53,  1.13it/s]

[I 2026-05-18 15:10:50,992] Trial 436 finished with value: 0.94971107845367 and parameters: {'solver': 'saga', 'C': 0.0005828366514067178, 'l1_ratio': 0.9505018934648702, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00018893263665304837, 'max_iter': 4780}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  88%|████████▊ | 441/500 [12:30<00:55,  1.06it/s]

[I 2026-05-18 15:10:53,188] Trial 443 finished with value: 0.9497050296952174 and parameters: {'solver': 'saga', 'C': 0.0004732970801048972, 'l1_ratio': 0.9497648110326117, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002092205552217635, 'max_iter': 4804}. Best is trial 398 with value: 0.9497146086068529.
[I 2026-05-18 15:10:53,361] Trial 440 finished with value: 0.9496980124057594 and parameters: {'solver': 'saga', 'C': 0.00040063879120180154, 'l1_ratio': 0.9466873088953149, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00021280668367609952, 'max_iter': 4813}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  88%|████████▊ | 442/500 [12:30<00:42,  1.35it/s]

[I 2026-05-18 15:10:53,618] Trial 441 finished with value: 0.9497030838276984 and parameters: {'solver': 'saga', 'C': 0.00045042884425796346, 'l1_ratio': 0.9488040838549395, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00019571163508809954, 'max_iter': 4762}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  89%|████████▊ | 443/500 [12:31<00:40,  1.39it/s]

[I 2026-05-18 15:10:54,291] Trial 439 finished with value: 0.9496999932450377 and parameters: {'solver': 'saga', 'C': 0.00041414274798957495, 'l1_ratio': 0.948159976957984, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00020118800239992074, 'max_iter': 4783}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  89%|████████▉ | 444/500 [12:31<00:39,  1.41it/s]

[I 2026-05-18 15:10:54,971] Trial 442 finished with value: 0.9497063998614663 and parameters: {'solver': 'saga', 'C': 0.00045982818423943904, 'l1_ratio': 0.9553427288919777, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00021844096469223357, 'max_iter': 4739}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  89%|████████▉ | 445/500 [12:33<00:58,  1.06s/it]

[I 2026-05-18 15:10:56,828] Trial 444 finished with value: 0.9497068411929313 and parameters: {'solver': 'saga', 'C': 0.0004786023768038336, 'l1_ratio': 0.9530467514137959, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00021369489857621843, 'max_iter': 4805}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  89%|████████▉ | 446/500 [12:37<01:37,  1.80s/it]

[I 2026-05-18 15:11:00,391] Trial 445 finished with value: 0.9496985069155313 and parameters: {'solver': 'saga', 'C': 0.00039140104269349234, 'l1_ratio': 0.9498294686724721, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00021660321709088636, 'max_iter': 4793}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  89%|████████▉ | 447/500 [12:39<01:48,  2.04s/it]

[I 2026-05-18 15:11:02,982] Trial 446 finished with value: 0.9497031431915035 and parameters: {'solver': 'saga', 'C': 0.00042734691090830896, 'l1_ratio': 0.9538733150459996, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00022519496107768983, 'max_iter': 4802}. Best is trial 398 with value: 0.9497146086068529.

Best trial: 398. Best value: 0.949715:  90%|████████▉ | 448/500 [12:41<01:32,  1.79s/it]

[I 2026-05-18 15:11:04,155] Trial 452 pruned.

Best trial: 447. Best value: 0.949717:  90%|████████▉ | 449/500 [12:41<01:09,  1.37s/it]

[I 2026-05-18 15:11:04,582] Trial 447 finished with value: 0.9497172440546713 and parameters: {'solver': 'saga', 'C': 0.0009340014135193548, 'l1_ratio': 0.9549729935003911, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00023025834343593578, 'max_iter': 4828}. Best is trial 447 with value: 0.9497172440546713.

Best trial: 449. Best value: 0.949718:  90%|█████████ | 450/500 [12:42<01:07,  1.35s/it]

[I 2026-05-18 15:11:05,864] Trial 449 finished with value: 0.9497176611404201 and parameters: {'solver': 'saga', 'C': 0.0009284772726825259, 'l1_ratio': 0.9569068811377953, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00023038949336779107, 'max_iter': 4765}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  90%|█████████ | 451/500 [12:43<00:52,  1.06s/it]

[I 2026-05-18 15:11:06,274] Trial 448 finished with value: 0.9497169419682393 and parameters: {'solver': 'saga', 'C': 0.0008971459036371872, 'l1_ratio': 0.9538904092508155, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00014606179230766716, 'max_iter': 4793}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  90%|█████████ | 452/500 [12:43<00:40,  1.18it/s]

[I 2026-05-18 15:11:06,613] Trial 450 finished with value: 0.9497171491999199 and parameters: {'solver': 'saga', 'C': 0.0008351885516456195, 'l1_ratio': 0.9554019904091235, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00022218825188636296, 'max_iter': 4530}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  91%|█████████ | 453/500 [12:45<00:53,  1.13s/it]

[I 2026-05-18 15:11:08,380] Trial 451 finished with value: 0.9497174561682181 and parameters: {'solver': 'saga', 'C': 0.0008916189594332115, 'l1_ratio': 0.9558771006402923, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00023557303931208092, 'max_iter': 4530}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  91%|█████████ | 454/500 [12:46<00:46,  1.00s/it]

[I 2026-05-18 15:11:09,102] Trial 453 finished with value: 0.9497096154647295 and parameters: {'solver': 'saga', 'C': 0.0009254572710459074, 'l1_ratio': 0.9229152875191539, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001432137528827678, 'max_iter': 4534}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  91%|█████████ | 455/500 [12:47<00:50,  1.12s/it]

[I 2026-05-18 15:11:10,492] Trial 454 finished with value: 0.9497097433231833 and parameters: {'solver': 'saga', 'C': 0.0009203459069952704, 'l1_ratio': 0.9237326028693158, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00014730808868899795, 'max_iter': 4704}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  91%|█████████ | 456/500 [12:48<00:45,  1.04s/it]

[I 2026-05-18 15:11:11,366] Trial 455 finished with value: 0.9497089735603922 and parameters: {'solver': 'saga', 'C': 0.0008848528435215907, 'l1_ratio': 0.922338934426757, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001440476444576735, 'max_iter': 4550}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  91%|█████████▏| 457/500 [12:50<01:00,  1.41s/it]

[I 2026-05-18 15:11:13,613] Trial 456 finished with value: 0.9497095303879611 and parameters: {'solver': 'saga', 'C': 0.0009301076496878141, 'l1_ratio': 0.9223080661212003, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00014625582674882318, 'max_iter': 4536}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  92%|█████████▏| 458/500 [12:53<01:15,  1.80s/it]

[I 2026-05-18 15:11:16,330] Trial 457 finished with value: 0.9497081701291303 and parameters: {'solver': 'saga', 'C': 0.0008841020779581235, 'l1_ratio': 0.9193068697232926, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00013275184391276762, 'max_iter': 4576}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  92%|█████████▏| 459/500 [12:56<01:36,  2.35s/it]

[I 2026-05-18 15:11:19,983] Trial 459 finished with value: 0.9495417173068621 and parameters: {'solver': 'saga', 'C': 0.0009256593940977471, 'l1_ratio': 0.4891326393870351, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00014685370734177382, 'max_iter': 4510}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  92%|█████████▏| 460/500 [12:57<01:15,  1.89s/it]

[I 2026-05-18 15:11:20,793] Trial 460 finished with value: 0.9497093306268928 and parameters: {'solver': 'saga', 'C': 0.0009194550490567179, 'l1_ratio': 0.9221732412158389, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00013850405260469527, 'max_iter': 4527}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  92%|█████████▏| 461/500 [12:58<00:55,  1.42s/it]

[I 2026-05-18 15:11:21,101] Trial 461 finished with value: 0.94970922293523 and parameters: {'solver': 'saga', 'C': 0.0008901679375526062, 'l1_ratio': 0.923072300577291, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001380348432011298, 'max_iter': 4534}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  92%|█████████▏| 462/500 [12:58<00:44,  1.17s/it]

[I 2026-05-18 15:11:21,683] Trial 464 finished with value: 0.949709452635517 and parameters: {'solver': 'saga', 'C': 0.0009478039862403474, 'l1_ratio': 0.9214871356585924, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002492321889158505, 'max_iter': 4530}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  93%|█████████▎| 463/500 [12:58<00:33,  1.12it/s]

[I 2026-05-18 15:11:21,947] Trial 463 finished with value: 0.9497090796249621 and parameters: {'solver': 'saga', 'C': 0.0009050962718402378, 'l1_ratio': 0.9219355862386921, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00024208761623767462, 'max_iter': 4909}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  93%|█████████▎| 464/500 [12:59<00:31,  1.15it/s]

[I 2026-05-18 15:11:22,727] Trial 465 finished with value: 0.9497095395096544 and parameters: {'solver': 'saga', 'C': 0.0010018636123210244, 'l1_ratio': 0.9201949126473806, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002493643438621642, 'max_iter': 4892}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  93%|█████████▎| 466/500 [13:02<00:32,  1.05it/s]

[I 2026-05-18 15:11:25,065] Trial 466 finished with value: 0.9497006310235208 and parameters: {'solver': 'saga', 'C': 0.0009909472411771363, 'l1_ratio': 0.8813606636146099, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00025209460530912, 'max_iter': 4899}. Best is trial 449 with value: 0.9497176611404201.
[I 2026-05-18 15:11:25,208] Trial 467 finished with value: 0.9497006082537828 and parameters: {'solver': 'saga', 'C': 0.0010343986194974405, 'l1_ratio': 0.8778135587954035, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002636098854186393, 'max_iter': 4919}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  93%|█████████▎| 467/500 [13:04<00:41,  1.27s/it]

[I 2026-05-18 15:11:27,219] Trial 458 finished with value: 0.9497104086543036 and parameters: {'solver': 'saga', 'C': 0.0009836251250662851, 'l1_ratio': 0.9239003862255393, 'class_weight': None, 'fit_intercept': False, 'tol': 2.1292441408028728e-06, 'max_iter': 4537}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  94%|█████████▎| 468/500 [13:05<00:43,  1.36s/it]

[I 2026-05-18 15:11:28,802] Trial 468 finished with value: 0.9497176079685911 and parameters: {'solver': 'saga', 'C': 0.0010207813936587294, 'l1_ratio': 0.9649840525830198, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002468833173099201, 'max_iter': 4856}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  94%|█████████▍| 469/500 [13:07<00:50,  1.64s/it]

[I 2026-05-18 15:11:31,075] Trial 469 finished with value: 0.9497168596963558 and parameters: {'solver': 'saga', 'C': 0.0010721996404265608, 'l1_ratio': 0.9630750032615422, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00025187505564409614, 'max_iter': 4822}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  94%|█████████▍| 470/500 [13:08<00:40,  1.34s/it]

[I 2026-05-18 15:11:31,706] Trial 462 finished with value: 0.9497097015245229 and parameters: {'solver': 'saga', 'C': 0.0009695478416548348, 'l1_ratio': 0.9219084089366509, 'class_weight': None, 'fit_intercept': False, 'tol': 2.575282497001831e-06, 'max_iter': 4860}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  94%|█████████▍| 471/500 [13:12<01:03,  2.19s/it]

[I 2026-05-18 15:11:35,885] Trial 470 finished with value: 0.9494667688318463 and parameters: {'solver': 'saga', 'C': 0.0010498113450933134, 'l1_ratio': 0.44393566311785204, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002552553661048475, 'max_iter': 4885}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  94%|█████████▍| 472/500 [13:13<00:44,  1.60s/it]

[I 2026-05-18 15:11:36,105] Trial 471 finished with value: 0.9497169564854033 and parameters: {'solver': 'saga', 'C': 0.0010742134272454591, 'l1_ratio': 0.9648639251524368, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00024145414053876581, 'max_iter': 4882}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  95%|█████████▍| 474/500 [13:13<00:23,  1.12it/s]

[I 2026-05-18 15:11:36,417] Trial 474 finished with value: 0.9497168120358822 and parameters: {'solver': 'saga', 'C': 0.0010871312644598204, 'l1_ratio': 0.9632711347907644, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00023383380110810528, 'max_iter': 4845}. Best is trial 449 with value: 0.9497176611404201.
[I 2026-05-18 15:11:36,558] Trial 473 finished with value: 0.9497168904403417 and parameters: {'solver': 'saga', 'C': 0.0010693547506645125, 'l1_ratio': 0.9629725549730218, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002545941350783741, 'max_iter': 4918}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  95%|█████████▌| 475/500 [13:14<00:25,  1.04s/it]

[I 2026-05-18 15:11:37,949] Trial 475 finished with value: 0.9497160081296527 and parameters: {'solver': 'saga', 'C': 0.0011406917667979518, 'l1_ratio': 0.9606692732003677, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002593874884775311, 'max_iter': 4882}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  95%|█████████▌| 476/500 [13:18<00:46,  1.95s/it]

[I 2026-05-18 15:11:42,036] Trial 476 finished with value: 0.9497161172789095 and parameters: {'solver': 'saga', 'C': 0.001124694097354575, 'l1_ratio': 0.9594564461758982, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00010582531286022221, 'max_iter': 4871}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  95%|█████████▌| 477/500 [13:20<00:41,  1.81s/it]

[I 2026-05-18 15:11:43,519] Trial 478 finished with value: 0.9497063003615164 and parameters: {'solver': 'saga', 'C': 0.0017570907075196182, 'l1_ratio': 0.9629632715772158, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00010373305699461274, 'max_iter': 4729}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  96%|█████████▌| 478/500 [13:21<00:36,  1.65s/it]

[I 2026-05-18 15:11:44,775] Trial 480 finished with value: 0.9497099189373623 and parameters: {'solver': 'saga', 'C': 0.001545610619728885, 'l1_ratio': 0.9621787005775868, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002516489080836486, 'max_iter': 4852}. Best is trial 449 with value: 0.9497176611404201.
[I 2026-05-18 15:11:44,805] Trial 472 finished with value: 0.949714756226302 and parameters: {'solver': 'saga', 'C': 0.0012161284413670789, 'l1_ratio': 0.9610508894356057, 'class_weight': None, 'fit_intercept': False, 'tol': 2.0299196426864462e-06, 'max_iter': 4901}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  96%|█████████▌| 480/500 [13:22<00:19,  1.02it/s]

[I 2026-05-18 15:11:45,175] Trial 479 finished with value: 0.9495806280760538 and parameters: {'solver': 'saga', 'C': 0.02523609900916116, 'l1_ratio': 0.9617359736431098, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00011370972518570195, 'max_iter': 4875}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  96%|█████████▌| 481/500 [13:22<00:17,  1.06it/s]

[I 2026-05-18 15:11:45,999] Trial 481 finished with value: 0.9497073489244313 and parameters: {'solver': 'saga', 'C': 0.001652075879274615, 'l1_ratio': 0.9670273937150544, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00025885459443599304, 'max_iter': 4854}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  96%|█████████▋| 482/500 [13:27<00:35,  1.97s/it]

[I 2026-05-18 15:11:50,854] Trial 482 finished with value: 0.9497087023328697 and parameters: {'solver': 'saga', 'C': 0.001588709905830726, 'l1_ratio': 0.9654340128745024, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002401374531238019, 'max_iter': 4831}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  97%|█████████▋| 483/500 [13:28<00:25,  1.49s/it]

[I 2026-05-18 15:11:51,088] Trial 483 finished with value: 0.9497108742901565 and parameters: {'solver': 'saga', 'C': 0.0014768712236726364, 'l1_ratio': 0.9640640218785137, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00021954558503076558, 'max_iter': 4866}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  97%|█████████▋| 484/500 [13:28<00:19,  1.22s/it]

[I 2026-05-18 15:11:51,602] Trial 484 finished with value: 0.9497081432374136 and parameters: {'solver': 'saga', 'C': 0.0016012370094056552, 'l1_ratio': 0.9670011176742702, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002468062788009526, 'max_iter': 4844}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  97%|█████████▋| 485/500 [13:29<00:16,  1.09s/it]

[I 2026-05-18 15:11:52,379] Trial 486 finished with value: 0.9497087976603084 and parameters: {'solver': 'saga', 'C': 0.0016576441214453843, 'l1_ratio': 0.9575764244601503, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00024200635377376713, 'max_iter': 4867}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  97%|█████████▋| 486/500 [13:29<00:12,  1.08it/s]

[I 2026-05-18 15:11:52,882] Trial 485 finished with value: 0.9497057134472936 and parameters: {'solver': 'saga', 'C': 0.0017525833448597111, 'l1_ratio': 0.967313852682889, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002529535901951852, 'max_iter': 4877}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  97%|█████████▋| 487/500 [13:30<00:11,  1.17it/s]

[I 2026-05-18 15:11:53,574] Trial 477 finished with value: 0.9495183577159789 and parameters: {'solver': 'saga', 'C': 23.33344682544333, 'l1_ratio': 0.289744147054658, 'class_weight': None, 'fit_intercept': False, 'tol': 1.49706078462029e-06, 'max_iter': 4713}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  98%|█████████▊| 488/500 [13:32<00:14,  1.18s/it]

[I 2026-05-18 15:11:55,541] Trial 487 finished with value: 0.9497084214084814 and parameters: {'solver': 'saga', 'C': 0.0016737768043343414, 'l1_ratio': 0.9587809537868578, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00024466267528516143, 'max_iter': 4874}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  98%|█████████▊| 489/500 [13:35<00:20,  1.86s/it]

[I 2026-05-18 15:11:59,011] Trial 491 finished with value: 0.9497053288968059 and parameters: {'solver': 'saga', 'C': 0.0017979774875653538, 'l1_ratio': 0.9650264404128712, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00023457751824894896, 'max_iter': 4914}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  98%|█████████▊| 490/500 [13:36<00:15,  1.51s/it]

[I 2026-05-18 15:11:59,704] Trial 488 finished with value: 0.949706081730217 and parameters: {'solver': 'saga', 'C': 0.0017324392694347676, 'l1_ratio': 0.9668175784765121, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002633657464340333, 'max_iter': 4925}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  98%|█████████▊| 491/500 [13:38<00:14,  1.60s/it]

[I 2026-05-18 15:12:01,520] Trial 489 finished with value: 0.9495187142769412 and parameters: {'solver': 'saga', 'C': 39.50843515027274, 'l1_ratio': 0.9660312608177232, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002341414481087858, 'max_iter': 4929}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  98%|█████████▊| 492/500 [13:42<00:18,  2.26s/it]

[I 2026-05-18 15:12:05,310] Trial 492 finished with value: 0.9497073194810552 and parameters: {'solver': 'saga', 'C': 0.0016558151895431068, 'l1_ratio': 0.966698809774653, 'class_weight': None, 'fit_intercept': False, 'tol': 1.0987211253831958e-05, 'max_iter': 4913}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  99%|█████████▉| 494/500 [13:42<00:07,  1.23s/it]

[I 2026-05-18 15:12:05,680] Trial 497 finished with value: 0.9497137775999664 and parameters: {'solver': 'saga', 'C': 0.0012265902643832326, 'l1_ratio': 0.9723967874231457, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00021079631558001296, 'max_iter': 4917}. Best is trial 449 with value: 0.9497176611404201.
[I 2026-05-18 15:12:05,816] Trial 495 finished with value: 0.9496987819525108 and parameters: {'solver': 'saga', 'C': 0.0021906729446096104, 'l1_ratio': 0.9683905577763648, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002201669243597407, 'max_iter': 4993}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  99%|█████████▉| 495/500 [13:43<00:06,  1.20s/it]

[I 2026-05-18 15:12:06,960] Trial 490 finished with value: 0.9497061209331775 and parameters: {'solver': 'saga', 'C': 0.0016870218960709962, 'l1_ratio': 0.9704381470856072, 'class_weight': None, 'fit_intercept': False, 'tol': 5.344687449180067e-06, 'max_iter': 4906}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  99%|█████████▉| 496/500 [13:46<00:05,  1.49s/it]

[I 2026-05-18 15:12:09,124] Trial 496 finished with value: 0.9497145245760276 and parameters: {'solver': 'saga', 'C': 0.0011811787959902823, 'l1_ratio': 0.9736915187134245, 'class_weight': None, 'fit_intercept': False, 'tol': 2.2704183821008946e-05, 'max_iter': 4934}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718:  99%|█████████▉| 497/500 [13:46<00:03,  1.13s/it]

[I 2026-05-18 15:12:09,397] Trial 493 finished with value: 0.9497145699697749 and parameters: {'solver': 'saga', 'C': 0.0012198782215660268, 'l1_ratio': 0.9654200273828324, 'class_weight': None, 'fit_intercept': False, 'tol': 8.957187040053117e-06, 'max_iter': 4890}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718: 100%|█████████▉| 498/500 [13:46<00:01,  1.04it/s]

[I 2026-05-18 15:12:09,983] Trial 499 finished with value: 0.9497147277499796 and parameters: {'solver': 'saga', 'C': 0.001181422874897922, 'l1_ratio': 0.9719070637595604, 'class_weight': None, 'fit_intercept': False, 'tol': 2.4026630220742177e-05, 'max_iter': 4926}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718: 100%|█████████▉| 499/500 [13:47<00:00,  1.16it/s]

[I 2026-05-18 15:12:10,607] Trial 494 finished with value: 0.9497159612755766 and parameters: {'solver': 'saga', 'C': 0.0011274317422515713, 'l1_ratio': 0.970201738692388, 'class_weight': None, 'fit_intercept': False, 'tol': 4.596547579317832e-06, 'max_iter': 4986}. Best is trial 449 with value: 0.9497176611404201.

Best trial: 449. Best value: 0.949718: 100%|██████████| 500/500 [13:47<00:00,  1.66s/it]

[I 2026-05-18 15:12:11,039] Trial 498 finished with value: 0.9497161670492785 and parameters: {'solver': 'saga', 'C': 0.001107002946324631, 'l1_ratio': 0.9723273495761446, 'class_weight': None, 'fit_intercept': False, 'tol': 7.926487046216622e-06, 'max_iter': 4989}. Best is trial 449 with value: 0.9497176611404201.
Best trial score:
0.9497176611404201

Best params:
{'solver': 'saga', 'C': 0.0009284772726825259, 'l1_ratio': 0.9569068811377953, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00023038949336779107, 'max_iter': 4765}

In [8]:
stacking_lg = LogisticRegression(**study.best_params).fit(X_train, y_train.PitNextLap)

# Submission

In [9]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [10]:
submission['PitNextLap'] = stacking_lg.predict_proba(X_test)[:, 1]

In [11]:
submission.to_csv('../data/submission/submission.csv', index=False)