# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from lightgbm import LGBMClassifier

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import StackingClassifier, VotingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

# Loading Dataset

In [4]:
X_train = pd.read_parquet('../data/processed/X_train_logit.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_logit.parquet')

In [5]:
X_train.head()

,lgbm_logit,cat_logit,xgb_logit,hist_logit,lg_logit,knn_logit,ridge_logit,voting_lgbm_cat_xgb_hist_logit,voting_lg_ridge_logit,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_logit
0,1.402666,2.109990,2.149899,2.030346,1.440273,2.064999,0.500714,1.887848,0.925326,1.226844
1,0.616425,1.595299,1.584592,1.262993,0.799597,0.079907,0.335105,1.222563,0.561368,0.371762
2,0.023615,1.748857,1.106745,1.146720,0.235157,-1.325798,0.136991,0.929687,0.186260,0.066618
3,-6.367775,-5.125195,-4.946636,-4.912857,-6.083520,-34.538776,-1.247050,-5.198584,-2.069743,-6.799934
4,-0.438053,0.263538,-0.043875,-0.068158,-0.346862,-0.861416,-0.094611,-0.070366,-0.220629,-0.878595

In [6]:
X_test.head()

,lgbm_logit,cat_logit,xgb_logit,hist_logit,lg_logit,knn_logit,ridge_logit,voting_lgbm_cat_xgb_hist_logit,voting_lg_ridge_logit,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_logit
0,-5.379032,-3.409957,-3.759100,-3.888929,-5.042109,-34.538776,-1.272709,-3.899528,-34.538776,-5.055490
1,-5.795381,-4.426299,-4.187473,-3.950213,-2.684867,-2.019087,-0.626960,-4.396275,-34.538776,-5.602505
2,-5.574937,-4.441487,-4.232580,-4.454119,-5.395432,-34.538776,-1.335019,-4.564839,-34.538776,-5.656104
3,-1.635113,0.176618,0.347033,-0.058463,0.644945,-2.198160,0.190133,-0.222683,-0.304675,-1.163384
4,1.920299,3.398116,3.163860,3.161400,1.661579,34.539576,0.535153,2.745303,0.794179,2.146481

# Machine Learning

In [8]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "objective": "binary",
        "n_estimators": trial.suggest_int("n_estimators", 30, 300),
        "learning_rate": trial.suggest_float("learning_rate", 0.003, 0.05, log=True),
        "max_depth": trial.suggest_int("max_depth", 1, 4),
        "num_leaves": trial.suggest_int("num_leaves", 2, 16),
        "min_child_samples": trial.suggest_int("min_child_samples", 20, 300),
        "subsample": trial.suggest_float("subsample", 0.6, 1.0),
        "colsample_bytree": trial.suggest_float("colsample_bytree", 0.6, 1.0),
        "reg_alpha": trial.suggest_float("reg_alpha", 1e-5, 100, log=True),
        "reg_lambda": trial.suggest_float("reg_lambda", 1e-5, 100, log=True),
        "verbosity": -1,
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LGBMClassifier(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)


study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=1000, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-19 13:54:51,966] A new study created in memory with name: no-name-b42b9c26-1eb4-48c4-8cdb-7b17f12642f7
  0%|                                                                                                                                                              | 0/1000 [00:18<?, ?it/s]

[I 2026-05-19 13:55:10,293] Trial 170 finished with value: 0.9498463750301551 and parameters: {'n_estimators': 288, 'learning_rate': 0.03893186343430399, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 67, 'subsample': 0.7250795253582988, 'colsample_bytree': 0.6106818690522473, 'reg_alpha': 0.005432377538186629, 'reg_lambda': 0.008549304693634598}. Best is trial 155 with value: 0.9498604985212739.

Best trial: 0. Best value: 0.909042:   0%|                                                                                                               | 1/1000 [00:19<5:17:31, 19.07s/it]

[I 2026-05-19 13:55:11,010] Trial 0 finished with value: 0.9090419474642738 and parameters: {'n_estimators': 63, 'learning_rate': 0.003980527600692953, 'max_depth': 1, 'num_leaves': 2, 'min_child_samples': 163, 'subsample': 0.7925605842818102, 'colsample_bytree': 0.752455029983794, 'reg_alpha': 0.0440275925989403, 'reg_lambda': 0.4028640886469403}. Best is trial 0 with value: 0.9090419474642738.

Best trial: 0. Best value: 0.909042:   0%|                                                                                                               | 1/1000 [00:20<5:17:31, 19.07s/it]

[I 2026-05-19 13:55:12,260] Trial 171 finished with value: 0.9498557478009223 and parameters: {'n_estimators': 288, 'learning_rate': 0.038809004136354144, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 136, 'subsample': 0.7237450496748378, 'colsample_bytree': 0.6116789332704029, 'reg_alpha': 0.005262289811608899, 'reg_lambda': 0.021835437039415814}. Best is trial 155 with value: 0.9498604985212739.

Best trial: 2. Best value: 0.944659:   0%|▏                                                                                                              | 2/1000 [00:20<2:27:19,  8.86s/it]

[I 2026-05-19 13:55:12,684] Trial 2 finished with value: 0.9446588443851844 and parameters: {'n_estimators': 60, 'learning_rate': 0.010539230706711375, 'max_depth': 2, 'num_leaves': 16, 'min_child_samples': 170, 'subsample': 0.7902779147641913, 'colsample_bytree': 0.7723081408650121, 'reg_alpha': 12.74153415384267, 'reg_lambda': 0.0016558042810794215}. Best is trial 2 with value: 0.9446588443851844.

Best trial: 11. Best value: 0.949204:   0%|▎                                                                                                             | 3/1000 [00:21<1:23:55,  5.05s/it]

[I 2026-05-19 13:55:13,199] Trial 11 finished with value: 0.9492044008337184 and parameters: {'n_estimators': 52, 'learning_rate': 0.022742982323412833, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 55, 'subsample': 0.8435097086890404, 'colsample_bytree': 0.8539062361307879, 'reg_alpha': 1.8525910420118399, 'reg_lambda': 1.6618031202254062}. Best is trial 11 with value: 0.9492044008337184.

Best trial: 11. Best value: 0.949204:   0%|▍                                                                                                             | 4/1000 [00:23<1:07:51,  4.09s/it]

[I 2026-05-19 13:55:15,797] Trial 10 finished with value: 0.9461924237261605 and parameters: {'n_estimators': 72, 'learning_rate': 0.010790270582105323, 'max_depth': 2, 'num_leaves': 16, 'min_child_samples': 214, 'subsample': 0.8422793139823488, 'colsample_bytree': 0.6271211724064994, 'reg_alpha': 4.9223990264226135e-05, 'reg_lambda': 0.18515184647391464}. Best is trial 11 with value: 0.9492044008337184.

Best trial: 11. Best value: 0.949204:   0%|▌                                                                                                               | 5/1000 [00:25<54:07,  3.26s/it]

[I 2026-05-19 13:55:17,656] Trial 8 finished with value: 0.9447162088718128 and parameters: {'n_estimators': 84, 'learning_rate': 0.007532638375401952, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 85, 'subsample': 0.8026941455234432, 'colsample_bytree': 0.8454031382749557, 'reg_alpha': 0.5080689533739527, 'reg_lambda': 0.09633869325386468}. Best is trial 11 with value: 0.9492044008337184.

Best trial: 11. Best value: 0.949204:   0%|▌                                                                                                               | 5/1000 [00:29<54:07,  3.26s/it]

[I 2026-05-19 13:55:21,126] Trial 169 finished with value: 0.9494545104464723 and parameters: {'n_estimators': 295, 'learning_rate': 0.0045540603551767435, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 152, 'subsample': 0.7764277579150545, 'colsample_bytree': 0.6498453279486085, 'reg_alpha': 0.3829670331329028, 'reg_lambda': 0.004097925786401258}. Best is trial 155 with value: 0.9498604985212739.

Best trial: 11. Best value: 0.949204:   0%|▌                                                                                                               | 5/1000 [00:32<54:07,  3.26s/it]

[I 2026-05-19 13:55:23,984] Trial 172 finished with value: 0.9498584068532543 and parameters: {'n_estimators': 293, 'learning_rate': 0.03932817874975696, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 153, 'subsample': 0.7222909235453491, 'colsample_bytree': 0.6110670582445893, 'reg_alpha': 0.005985580028117584, 'reg_lambda': 0.023775821675010116}. Best is trial 155 with value: 0.9498604985212739.

Best trial: 7. Best value: 0.949758:   1%|▋                                                                                                              | 6/1000 [00:34<1:27:46,  5.30s/it]

[I 2026-05-19 13:55:26,885] Trial 7 finished with value: 0.9497579278472138 and parameters: {'n_estimators': 112, 'learning_rate': 0.040216123888843894, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 185, 'subsample': 0.9576708535189471, 'colsample_bytree': 0.9552419055341498, 'reg_alpha': 0.0011295108699031268, 'reg_lambda': 16.344326453144518}. Best is trial 7 with value: 0.9497579278472138.

Best trial: 7. Best value: 0.949758:   1%|▋                                                                                                              | 6/1000 [00:36<1:27:46,  5.30s/it]

[I 2026-05-19 13:55:28,691] Trial 174 finished with value: 0.9498440288512751 and parameters: {'n_estimators': 287, 'learning_rate': 0.039344770115708826, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 290, 'subsample': 0.7305990015329621, 'colsample_bytree': 0.650019910233958, 'reg_alpha': 0.00017995262680460064, 'reg_lambda': 0.01811531348784347}. Best is trial 155 with value: 0.9498604985212739.

Best trial: 7. Best value: 0.949758:   1%|▋                                                                                                              | 6/1000 [00:37<1:27:46,  5.30s/it]

[I 2026-05-19 13:55:29,176] Trial 173 finished with value: 0.9498490834847406 and parameters: {'n_estimators': 290, 'learning_rate': 0.03922888532596453, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 281, 'subsample': 0.7335013156870919, 'colsample_bytree': 0.6493758284084502, 'reg_alpha': 0.005959690266643438, 'reg_lambda': 0.0204837797481238}. Best is trial 155 with value: 0.9498604985212739.

Best trial: 7. Best value: 0.949758:   1%|▊                                                                                                              | 7/1000 [00:37<1:12:29,  4.38s/it]

[I 2026-05-19 13:55:29,399] Trial 5 finished with value: 0.9451691445218234 and parameters: {'n_estimators': 105, 'learning_rate': 0.004928400453739497, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 128, 'subsample': 0.733107748702093, 'colsample_bytree': 0.6993499288554378, 'reg_alpha': 0.000736086916686814, 'reg_lambda': 0.0015277747263085961}. Best is trial 7 with value: 0.9497579278472138.

Best trial: 7. Best value: 0.949758:   1%|▉                                                                                                                | 8/1000 [00:38<54:01,  3.27s/it]

[I 2026-05-19 13:55:30,286] Trial 14 pruned.

Best trial: 7. Best value: 0.949758:   1%|▉                                                                                                                | 8/1000 [00:44<54:01,  3.27s/it]

[I 2026-05-19 13:55:36,275] Trial 175 finished with value: 0.9498585262652177 and parameters: {'n_estimators': 290, 'learning_rate': 0.03948077220579859, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 151, 'subsample': 0.6563375304105402, 'colsample_bytree': 0.6100207083556614, 'reg_alpha': 1.1252202288418278, 'reg_lambda': 0.0047911555727948784}. Best is trial 155 with value: 0.9498604985212739.

Best trial: 7. Best value: 0.949758:   1%|▉                                                                                                              | 9/1000 [00:49<1:36:21,  5.83s/it]

[I 2026-05-19 13:55:41,769] Trial 13 finished with value: 0.949719541402715 and parameters: {'n_estimators': 176, 'learning_rate': 0.04496985756917322, 'max_depth': 1, 'num_leaves': 14, 'min_child_samples': 21, 'subsample': 0.8660021372982727, 'colsample_bytree': 0.7141163766243057, 'reg_alpha': 5.2857023136419706e-05, 'reg_lambda': 0.00036567538151366716}. Best is trial 7 with value: 0.9497579278472138.

Best trial: 7. Best value: 0.949758:   1%|█                                                                                                             | 10/1000 [00:50<1:09:58,  4.24s/it]

[I 2026-05-19 13:55:42,387] Trial 19 pruned.

Best trial: 7. Best value: 0.949758:   1%|█▏                                                                                                              | 11/1000 [00:50<49:46,  3.02s/it]

[I 2026-05-19 13:55:42,632] Trial 3 finished with value: 0.9482579578164895 and parameters: {'n_estimators': 227, 'learning_rate': 0.006666284429990146, 'max_depth': 2, 'num_leaves': 11, 'min_child_samples': 205, 'subsample': 0.7458124627759746, 'colsample_bytree': 0.6943232266601356, 'reg_alpha': 0.005866336720204294, 'reg_lambda': 0.07410259520444062}. Best is trial 7 with value: 0.9497579278472138.

Best trial: 7. Best value: 0.949758:   1%|█▏                                                                                                              | 11/1000 [00:51<49:46,  3.02s/it]

[I 2026-05-19 13:55:43,490] Trial 176 finished with value: 0.9498480504782881 and parameters: {'n_estimators': 291, 'learning_rate': 0.03926722890518867, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 151, 'subsample': 0.792803635798989, 'colsample_bytree': 0.6092280524686955, 'reg_alpha': 0.0016580830761186629, 'reg_lambda': 0.0152396033018757}. Best is trial 155 with value: 0.9498604985212739.

Best trial: 7. Best value: 0.949758:   1%|█▎                                                                                                              | 12/1000 [00:52<44:35,  2.71s/it]

[I 2026-05-19 13:55:44,658] Trial 15 finished with value: 0.9492670605274288 and parameters: {'n_estimators': 186, 'learning_rate': 0.026387663867576808, 'max_depth': 1, 'num_leaves': 6, 'min_child_samples': 267, 'subsample': 0.9356759391688039, 'colsample_bytree': 0.8391111467981376, 'reg_alpha': 3.584587722871814, 'reg_lambda': 6.800315111248129}. Best is trial 7 with value: 0.9497579278472138.

Best trial: 7. Best value: 0.949758:   1%|█▍                                                                                                            | 13/1000 [00:59<1:04:41,  3.93s/it]

[I 2026-05-19 13:55:51,436] Trial 6 finished with value: 0.949693236304966 and parameters: {'n_estimators': 248, 'learning_rate': 0.016343908393468918, 'max_depth': 4, 'num_leaves': 4, 'min_child_samples': 80, 'subsample': 0.7371876307473644, 'colsample_bytree': 0.7608041622924058, 'reg_alpha': 0.06347638019577906, 'reg_lambda': 0.0003245562707214201}. Best is trial 7 with value: 0.9497579278472138.

Best trial: 7. Best value: 0.949758:   1%|█▍                                                                                                            | 13/1000 [01:01<1:04:41,  3.93s/it]

[I 2026-05-19 13:55:53,845] Trial 177 finished with value: 0.9494936014572224 and parameters: {'n_estimators': 293, 'learning_rate': 0.004966963387792131, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 293, 'subsample': 0.7769880300729967, 'colsample_bytree': 0.6019473130633998, 'reg_alpha': 0.012936657306676478, 'reg_lambda': 0.005200958646048577}. Best is trial 155 with value: 0.9498604985212739.

Best trial: 7. Best value: 0.949758:   1%|█▍                                                                                                            | 13/1000 [01:07<1:04:41,  3.93s/it]

[I 2026-05-19 13:55:59,446] Trial 178 finished with value: 0.9496897566100866 and parameters: {'n_estimators': 290, 'learning_rate': 0.0059153407187559305, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 290, 'subsample': 0.6549226465889938, 'colsample_bytree': 0.6089031361860602, 'reg_alpha': 0.0015903338321084943, 'reg_lambda': 0.012041046558087146}. Best is trial 155 with value: 0.9498604985212739.

Best trial: 7. Best value: 0.949758:   1%|█▌                                                                                                            | 14/1000 [01:09<1:32:55,  5.65s/it]

[I 2026-05-19 13:56:01,080] Trial 12 finished with value: 0.9497523508298341 and parameters: {'n_estimators': 250, 'learning_rate': 0.01605365265029872, 'max_depth': 2, 'num_leaves': 5, 'min_child_samples': 137, 'subsample': 0.6396231794728681, 'colsample_bytree': 0.9902060107120694, 'reg_alpha': 0.0010317314955720887, 'reg_lambda': 0.042054252803311376}. Best is trial 7 with value: 0.9497579278472138.

Best trial: 1. Best value: 0.949814:   2%|█▊                                                                                                              | 16/1000 [01:10<50:19,  3.07s/it]

[I 2026-05-19 13:56:02,288] Trial 1 finished with value: 0.9498139202413707 and parameters: {'n_estimators': 213, 'learning_rate': 0.025697630690089887, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 224, 'subsample': 0.6518294782597682, 'colsample_bytree': 0.6664259522248277, 'reg_alpha': 0.003803289566047681, 'reg_lambda': 9.42881725586382}. Best is trial 1 with value: 0.9498139202413707.
[I 2026-05-19 13:56:02,441] Trial 17 finished with value: 0.9498055863183769 and parameters: {'n_estimators': 202, 'learning_rate': 0.03684454404701242, 'max_depth': 2, 'num_leaves': 4, 'min_child_samples': 73, 'subsample': 0.7266089097941127, 'colsample_bytree': 0.8703715903584235, 'reg_alpha': 1.2549164562041072e-05, 'reg_lambda': 0.00012375453605876157}. Best is trial 1 with value: 0.9498139202413707.

[I 2026-05-19 13:56:03,994] Trial 20 pruned.

Best trial: 1. Best value: 0.949814:   2%|██                                                                                                              | 18/1000 [01:12<30:55,  1.89s/it]

[I 2026-05-19 13:56:04,196] Trial 16 finished with value: 0.9486252075362286 and parameters: {'n_estimators': 199, 'learning_rate': 0.007783449463847945, 'max_depth': 3, 'num_leaves': 6, 'min_child_samples': 208, 'subsample': 0.6144802098616502, 'colsample_bytree': 0.6703406494427201, 'reg_alpha': 0.04424567966206229, 'reg_lambda': 1.0355705804860205e-05}. Best is trial 1 with value: 0.9498139202413707.

Best trial: 1. Best value: 0.949814:   2%|██▏                                                                                                             | 19/1000 [01:15<37:19,  2.28s/it]

[I 2026-05-19 13:56:07,371] Trial 22 finished with value: 0.949741950412921 and parameters: {'n_estimators': 190, 'learning_rate': 0.047009136698312574, 'max_depth': 1, 'num_leaves': 13, 'min_child_samples': 294, 'subsample': 0.9718719169352085, 'colsample_bytree': 0.9954129050575498, 'reg_alpha': 0.0007716914347270136, 'reg_lambda': 1.3465404637906341e-05}. Best is trial 1 with value: 0.9498139202413707.

Best trial: 1. Best value: 0.949814:   2%|██▏                                                                                                             | 20/1000 [01:17<37:14,  2.28s/it]

[I 2026-05-19 13:56:09,688] Trial 18 finished with value: 0.9497630353705186 and parameters: {'n_estimators': 211, 'learning_rate': 0.025767049584758624, 'max_depth': 3, 'num_leaves': 4, 'min_child_samples': 85, 'subsample': 0.726215466867666, 'colsample_bytree': 0.8979409350267107, 'reg_alpha': 1.2843804642468004e-05, 'reg_lambda': 2.0259948159252206}. Best is trial 1 with value: 0.9498139202413707.

Best trial: 1. Best value: 0.949814:   2%|██▎                                                                                                             | 21/1000 [01:18<30:48,  1.89s/it]

[I 2026-05-19 13:56:10,665] Trial 4 finished with value: 0.9497651596561111 and parameters: {'n_estimators': 236, 'learning_rate': 0.017398199677449162, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 106, 'subsample': 0.7586949705499662, 'colsample_bytree': 0.6528001928691746, 'reg_alpha': 0.3388962609802158, 'reg_lambda': 68.3913924332865}. Best is trial 1 with value: 0.9498139202413707.

Best trial: 1. Best value: 0.949814:   2%|██▍                                                                                                             | 22/1000 [01:25<56:55,  3.49s/it]

[I 2026-05-19 13:56:17,891] Trial 9 finished with value: 0.9497259895049041 and parameters: {'n_estimators': 242, 'learning_rate': 0.009660663191324892, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 182, 'subsample': 0.7484716864632404, 'colsample_bytree': 0.9779715940889696, 'reg_alpha': 0.12832939259610598, 'reg_lambda': 0.009030833072367125}. Best is trial 1 with value: 0.9498139202413707.

Best trial: 1. Best value: 0.949814:   2%|██▌                                                                                                             | 23/1000 [01:26<41:07,  2.53s/it]

[I 2026-05-19 13:56:18,170] Trial 23 finished with value: 0.9497721687656826 and parameters: {'n_estimators': 286, 'learning_rate': 0.047782882489489836, 'max_depth': 1, 'num_leaves': 13, 'min_child_samples': 36, 'subsample': 0.9933023330603552, 'colsample_bytree': 0.9839238397194174, 'reg_alpha': 0.0008509918376928725, 'reg_lambda': 1.0433172073737696e-05}. Best is trial 1 with value: 0.9498139202413707.

Best trial: 1. Best value: 0.949814:   2%|██▋                                                                                                           | 24/1000 [01:33<1:03:00,  3.87s/it]

[I 2026-05-19 13:56:25,162] Trial 24 finished with value: 0.9497749574452843 and parameters: {'n_estimators': 299, 'learning_rate': 0.04760733850466909, 'max_depth': 1, 'num_leaves': 13, 'min_child_samples': 296, 'subsample': 0.9867219538281355, 'colsample_bytree': 0.9909825787751161, 'reg_alpha': 0.0006406144420676965, 'reg_lambda': 3.0496196427665214e-05}. Best is trial 1 with value: 0.9498139202413707.

Best trial: 26. Best value: 0.949817:   2%|██▊                                                                                                            | 25/1000 [01:35<56:29,  3.48s/it]

[I 2026-05-19 13:56:27,729] Trial 26 finished with value: 0.9498169490428404 and parameters: {'n_estimators': 143, 'learning_rate': 0.04927794680998797, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 295, 'subsample': 0.9515838589128087, 'colsample_bytree': 0.6341919843364854, 'reg_alpha': 0.0031791541550186524, 'reg_lambda': 89.31213539291922}. Best is trial 26 with value: 0.9498169490428404.

Best trial: 21. Best value: 0.94985:   3%|██▊                                                                                                           | 26/1000 [01:56<2:20:23,  8.65s/it]

[I 2026-05-19 13:56:48,443] Trial 21 finished with value: 0.9498498912237208 and parameters: {'n_estimators': 279, 'learning_rate': 0.04939257857944967, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 286, 'subsample': 0.9726844928337286, 'colsample_bytree': 0.9996522134829409, 'reg_alpha': 0.0030567196145590446, 'reg_lambda': 3.242490475106221e-05}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   3%|██▉                                                                                                           | 27/1000 [02:02<2:06:28,  7.80s/it]

[I 2026-05-19 13:56:54,263] Trial 36 finished with value: 0.9497642476378676 and parameters: {'n_estimators': 146, 'learning_rate': 0.033841430513255916, 'max_depth': 3, 'num_leaves': 7, 'min_child_samples': 247, 'subsample': 0.6871261465523659, 'colsample_bytree': 0.6134943843298052, 'reg_alpha': 0.0064939315713909256, 'reg_lambda': 88.11523851976006}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   3%|███                                                                                                           | 28/1000 [02:02<1:29:30,  5.53s/it]

[I 2026-05-19 13:56:54,485] Trial 27 finished with value: 0.9498189797440848 and parameters: {'n_estimators': 299, 'learning_rate': 0.030443751906828548, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 268, 'subsample': 0.6853860236979973, 'colsample_bytree': 0.6082675607813082, 'reg_alpha': 49.92840993527662, 'reg_lambda': 1.0902408300429965e-05}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   3%|███▏                                                                                                          | 29/1000 [02:04<1:13:39,  4.55s/it]

[I 2026-05-19 13:56:56,768] Trial 25 finished with value: 0.9498391789055353 and parameters: {'n_estimators': 289, 'learning_rate': 0.04273229377636415, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 128, 'subsample': 0.9899821788839257, 'colsample_bytree': 0.9868390893448646, 'reg_alpha': 0.0016253870575164663, 'reg_lambda': 0.010102107355173843}. Best is trial 21 with value: 0.9498498912237208.

[I 2026-05-19 13:56:58,811] Trial 39 pruned.
[I 2026-05-19 13:56:58,964] Trial 28 finished with value: 0.9498158540642706 and parameters: {'n_estimators': 299, 'learning_rate': 0.032158436818193345, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 273, 'subsample': 0.6918842164884957, 'colsample_bytree': 0.6005676136445102, 'reg_alpha': 67.87034946965012, 'reg_lambda': 4.737881255441083e-05}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   3%|███▍                                                                                                            | 31/1000 [02:07<43:47,  2.71s/it]

[I 2026-05-19 13:56:59,010] Trial 29 finished with value: 0.9498404165710024 and parameters: {'n_estimators': 287, 'learning_rate': 0.03254943192269533, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 290, 'subsample': 0.6782455468664705, 'colsample_bytree': 0.6008620721592133, 'reg_alpha': 0.008347887124299746, 'reg_lambda': 0.006648123390918593}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   3%|███▋                                                                                                            | 33/1000 [02:08<28:48,  1.79s/it]

[I 2026-05-19 13:57:00,407] Trial 30 finished with value: 0.9498350219440124 and parameters: {'n_estimators': 280, 'learning_rate': 0.03199631753045846, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 245, 'subsample': 0.6904376871142277, 'colsample_bytree': 0.608059344312131, 'reg_alpha': 0.006234375074426633, 'reg_lambda': 0.008027345168954828}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   3%|███▊                                                                                                            | 34/1000 [02:11<33:18,  2.07s/it]

[I 2026-05-19 13:57:03,306] Trial 31 finished with value: 0.9498247473278856 and parameters: {'n_estimators': 288, 'learning_rate': 0.03337281244929994, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 241, 'subsample': 0.6765979948086829, 'colsample_bytree': 0.6216325016510971, 'reg_alpha': 61.82428869801436, 'reg_lambda': 0.007137944241923195}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   4%|███▉                                                                                                            | 35/1000 [02:17<50:24,  3.13s/it]

[I 2026-05-19 13:57:09,453] Trial 32 finished with value: 0.9498041883088565 and parameters: {'n_estimators': 296, 'learning_rate': 0.032095883124411945, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 105, 'subsample': 0.680244462674345, 'colsample_bytree': 0.6094266591986559, 'reg_alpha': 85.26148387668614, 'reg_lambda': 82.0671442546014}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   4%|████                                                                                                            | 36/1000 [02:19<46:09,  2.87s/it]

[I 2026-05-19 13:57:11,638] Trial 34 finished with value: 0.949838269430316 and parameters: {'n_estimators': 293, 'learning_rate': 0.03479072234516512, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 33, 'subsample': 0.6781875683084716, 'colsample_bytree': 0.8050574575016518, 'reg_alpha': 0.006879310030166017, 'reg_lambda': 4.46925862662291e-05}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   4%|████▏                                                                                                           | 37/1000 [02:22<44:54,  2.80s/it]

[I 2026-05-19 13:57:14,240] Trial 33 finished with value: 0.949820412825608 and parameters: {'n_estimators': 285, 'learning_rate': 0.036145924234612124, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 108, 'subsample': 0.6906567816378627, 'colsample_bytree': 0.6120465748049103, 'reg_alpha': 79.93063596598586, 'reg_lambda': 95.5785738874985}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   4%|████▎                                                                                                           | 38/1000 [02:27<55:56,  3.49s/it]

[I 2026-05-19 13:57:19,436] Trial 35 finished with value: 0.9498337807937371 and parameters: {'n_estimators': 294, 'learning_rate': 0.03461758274132896, 'max_depth': 3, 'num_leaves': 8, 'min_child_samples': 300, 'subsample': 0.6863283859972649, 'colsample_bytree': 0.9329293300747195, 'reg_alpha': 0.005602336109810178, 'reg_lambda': 6.983159539531447e-05}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   4%|████▎                                                                                                           | 39/1000 [02:31<57:59,  3.62s/it]

[I 2026-05-19 13:57:23,396] Trial 37 finished with value: 0.9498114155341589 and parameters: {'n_estimators': 150, 'learning_rate': 0.032797360766341474, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 256, 'subsample': 0.8988328680100962, 'colsample_bytree': 0.6188772679089996, 'reg_alpha': 0.004260737021198956, 'reg_lambda': 0.011042732486963023}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   4%|████▍                                                                                                         | 40/1000 [02:46<1:49:58,  6.87s/it]

[I 2026-05-19 13:57:38,141] Trial 44 pruned.

Best trial: 21. Best value: 0.94985:   4%|████▌                                                                                                         | 41/1000 [02:47<1:25:25,  5.34s/it]

[I 2026-05-19 13:57:39,833] Trial 41 pruned.

Best trial: 21. Best value: 0.94985:   4%|████▌                                                                                                         | 42/1000 [02:55<1:38:31,  6.17s/it]

[I 2026-05-19 13:57:47,960] Trial 38 finished with value: 0.949843795345385 and parameters: {'n_estimators': 269, 'learning_rate': 0.03336655099643925, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 272, 'subsample': 0.90467261563174, 'colsample_bytree': 0.6008749922470193, 'reg_alpha': 0.009332573685018225, 'reg_lambda': 15.954975897342921}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   4%|████▋                                                                                                         | 43/1000 [02:59<1:27:02,  5.46s/it]

[I 2026-05-19 13:57:51,735] Trial 42 finished with value: 0.9498372557169461 and parameters: {'n_estimators': 277, 'learning_rate': 0.0384242967862247, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 253, 'subsample': 0.9298403691773908, 'colsample_bytree': 0.9548794011713061, 'reg_alpha': 0.009942791907151019, 'reg_lambda': 0.003977864135542408}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   4%|████▊                                                                                                         | 44/1000 [03:04<1:24:04,  5.28s/it]

[I 2026-05-19 13:57:56,587] Trial 40 finished with value: 0.9498402239642336 and parameters: {'n_estimators': 271, 'learning_rate': 0.03307235102263585, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 268, 'subsample': 0.9114677564123034, 'colsample_bytree': 0.8139674098388119, 'reg_alpha': 0.012175091112259312, 'reg_lambda': 0.010343760555460307}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   4%|████▉                                                                                                         | 45/1000 [03:06<1:06:38,  4.19s/it]

[I 2026-05-19 13:57:58,171] Trial 43 finished with value: 0.9498389922930273 and parameters: {'n_estimators': 273, 'learning_rate': 0.029623555939641347, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 246, 'subsample': 0.9262592887975608, 'colsample_bytree': 0.9309809266138984, 'reg_alpha': 0.0163379444507259, 'reg_lambda': 0.009830261437002807}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   5%|█████                                                                                                         | 46/1000 [03:14<1:27:46,  5.52s/it]

[I 2026-05-19 13:58:06,851] Trial 45 finished with value: 0.9498175707981247 and parameters: {'n_estimators': 266, 'learning_rate': 0.020159258209713198, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 148, 'subsample': 0.8953162810730018, 'colsample_bytree': 0.9441380330678473, 'reg_alpha': 0.02311631856147249, 'reg_lambda': 0.008718061661009184}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   5%|█████▏                                                                                                        | 47/1000 [03:21<1:33:26,  5.88s/it]

[I 2026-05-19 13:58:13,579] Trial 47 finished with value: 0.9498247419242227 and parameters: {'n_estimators': 266, 'learning_rate': 0.021781535503344118, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 151, 'subsample': 0.9113333776826662, 'colsample_bytree': 0.9362205987889696, 'reg_alpha': 0.023976444233186706, 'reg_lambda': 0.0012699068710329787}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   5%|█████▎                                                                                                        | 48/1000 [03:24<1:20:57,  5.10s/it]

[I 2026-05-19 13:58:16,855] Trial 46 finished with value: 0.9498215392361574 and parameters: {'n_estimators': 268, 'learning_rate': 0.020828997055839567, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 159, 'subsample': 0.917391283308202, 'colsample_bytree': 0.9541815346162756, 'reg_alpha': 0.014283916859918642, 'reg_lambda': 0.011684027554056111}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   5%|█████▍                                                                                                          | 49/1000 [03:25<59:20,  3.74s/it]

[I 2026-05-19 13:58:17,440] Trial 50 finished with value: 0.9498475621518043 and parameters: {'n_estimators': 265, 'learning_rate': 0.040540589546847784, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 149, 'subsample': 0.7822667885041019, 'colsample_bytree': 0.7283294514764831, 'reg_alpha': 0.01716252387854177, 'reg_lambda': 0.0015956078152355182}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   5%|█████▌                                                                                                          | 50/1000 [03:26<47:47,  3.02s/it]

[I 2026-05-19 13:58:18,692] Trial 48 finished with value: 0.949821141411124 and parameters: {'n_estimators': 261, 'learning_rate': 0.020826247605737057, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 190, 'subsample': 0.9147547630288122, 'colsample_bytree': 0.9419009339373343, 'reg_alpha': 0.015510008377184133, 'reg_lambda': 0.001686176822845421}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   5%|█████▋                                                                                                          | 51/1000 [03:29<46:32,  2.94s/it]

[I 2026-05-19 13:58:21,526] Trial 49 finished with value: 0.9498215978438515 and parameters: {'n_estimators': 263, 'learning_rate': 0.020582159210175664, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 150, 'subsample': 0.9267338984287482, 'colsample_bytree': 0.727321550957926, 'reg_alpha': 0.024531444819669807, 'reg_lambda': 0.0014407206105896144}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   5%|█████▋                                                                                                        | 52/1000 [03:47<1:58:04,  7.47s/it]

[I 2026-05-19 13:58:39,526] Trial 51 finished with value: 0.949827626992761 and parameters: {'n_estimators': 263, 'learning_rate': 0.02168017835041217, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 161, 'subsample': 0.7765523481039384, 'colsample_bytree': 0.7356913024154039, 'reg_alpha': 0.01777943530103249, 'reg_lambda': 0.001428559070619962}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   5%|█████▊                                                                                                        | 53/1000 [03:53<1:51:01,  7.03s/it]

[I 2026-05-19 13:58:45,566] Trial 53 finished with value: 0.9498448873847781 and parameters: {'n_estimators': 267, 'learning_rate': 0.04075388006220575, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 225, 'subsample': 0.8011160211443626, 'colsample_bytree': 0.7848488496427451, 'reg_alpha': 0.021420483773609833, 'reg_lambda': 0.0015269963332055908}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 21. Best value: 0.94985:   5%|█████▉                                                                                                        | 54/1000 [03:53<1:19:23,  5.04s/it]

[I 2026-05-19 13:58:45,960] Trial 52 finished with value: 0.9498193268105597 and parameters: {'n_estimators': 266, 'learning_rate': 0.020667090219113098, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 224, 'subsample': 0.7956314408722429, 'colsample_bytree': 0.7953348402454087, 'reg_alpha': 0.00023619627799449742, 'reg_lambda': 0.002032904554752708}. Best is trial 21 with value: 0.9498498912237208.

Best trial: 54. Best value: 0.949851:   6%|██████                                                                                                         | 55/1000 [03:54<57:38,  3.66s/it]

[I 2026-05-19 13:58:46,397] Trial 54 finished with value: 0.9498509635591781 and parameters: {'n_estimators': 257, 'learning_rate': 0.041446913452756834, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 225, 'subsample': 0.7845040378501429, 'colsample_bytree': 0.7326220772646026, 'reg_alpha': 0.023246164878869862, 'reg_lambda': 0.0008838695334416097}. Best is trial 54 with value: 0.9498509635591781.

Best trial: 54. Best value: 0.949851:   6%|██████                                                                                                       | 56/1000 [04:04<1:26:05,  5.47s/it]

[I 2026-05-19 13:58:56,099] Trial 55 finished with value: 0.9498229904384576 and parameters: {'n_estimators': 259, 'learning_rate': 0.02137671815720004, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 226, 'subsample': 0.8760051459497388, 'colsample_bytree': 0.7203633719605206, 'reg_alpha': 0.024414973203738297, 'reg_lambda': 0.00112284912574821}. Best is trial 54 with value: 0.9498509635591781.

Best trial: 54. Best value: 0.949851:   6%|██████▏                                                                                                      | 57/1000 [04:07<1:17:25,  4.93s/it]

[I 2026-05-19 13:58:59,752] Trial 56 finished with value: 0.9498234895208565 and parameters: {'n_estimators': 260, 'learning_rate': 0.021206562312198186, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 283, 'subsample': 0.8827984486954524, 'colsample_bytree': 0.747660523658362, 'reg_alpha': 0.0021123085380544376, 'reg_lambda': 0.0012727233369421128}. Best is trial 54 with value: 0.9498509635591781.

Best trial: 54. Best value: 0.949851:   6%|██████▎                                                                                                      | 58/1000 [04:11<1:13:12,  4.66s/it]

[I 2026-05-19 13:59:03,804] Trial 57 finished with value: 0.9498450118683339 and parameters: {'n_estimators': 255, 'learning_rate': 0.041244365594129695, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 281, 'subsample': 0.8008481181128067, 'colsample_bytree': 0.7358455620454141, 'reg_alpha': 0.09474009177713, 'reg_lambda': 0.0018726422323128084}. Best is trial 54 with value: 0.9498509635591781.

Best trial: 54. Best value: 0.949851:   6%|██████▍                                                                                                      | 59/1000 [04:18<1:19:25,  5.06s/it]

[I 2026-05-19 13:59:09,784] Trial 58 finished with value: 0.9497639068979783 and parameters: {'n_estimators': 226, 'learning_rate': 0.014225292399701963, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 224, 'subsample': 0.7858070089533594, 'colsample_bytree': 0.7341412104757159, 'reg_alpha': 0.002068917234606575, 'reg_lambda': 0.40374584662548846}. Best is trial 54 with value: 0.9498509635591781.
[I 2026-05-19 13:59:09,957] Trial 60 finished with value: 0.949763354051804 and parameters: {'n_estimators': 230, 'learning_rate': 0.014481263795803659, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 224, 'subsample': 0.8017521296736286, 'colsample_bytree': 0.7264423459447762, 'reg_alpha': 0.11729029672026468, 'reg_lambda': 0.00045547751231048443}. Best is trial 54 with value: 0.9498509635591781.

Best trial: 54. Best value: 0.949851:   6%|██████▊                                                                                                        | 61/1000 [04:20<49:58,  3.19s/it]

[I 2026-05-19 13:59:12,232] Trial 59 finished with value: 0.9497640702950966 and parameters: {'n_estimators': 232, 'learning_rate': 0.013854426305848475, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 225, 'subsample': 0.8059796214639265, 'colsample_bytree': 0.727075040232979, 'reg_alpha': 0.1166145928092578, 'reg_lambda': 0.21873357670274216}. Best is trial 54 with value: 0.9498509635591781.

Best trial: 54. Best value: 0.949851:   6%|██████▉                                                                                                        | 62/1000 [04:22<43:27,  2.78s/it]

[I 2026-05-19 13:59:14,047] Trial 62 finished with value: 0.9498407485415672 and parameters: {'n_estimators': 226, 'learning_rate': 0.03995163806398885, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 224, 'subsample': 0.7962736310336657, 'colsample_bytree': 0.7789945286404037, 'reg_alpha': 0.002594593394650326, 'reg_lambda': 0.06893231353324267}. Best is trial 54 with value: 0.9498509635591781.

Best trial: 54. Best value: 0.949851:   6%|██████▉                                                                                                        | 63/1000 [04:22<34:01,  2.18s/it]

[I 2026-05-19 13:59:14,824] Trial 61 finished with value: 0.9497665507552668 and parameters: {'n_estimators': 229, 'learning_rate': 0.014327362209770917, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 222, 'subsample': 0.866816760044286, 'colsample_bytree': 0.7308236092263627, 'reg_alpha': 0.09827614109536667, 'reg_lambda': 0.2474008250789864}. Best is trial 54 with value: 0.9498509635591781.

Best trial: 54. Best value: 0.949851:   6%|██████▉                                                                                                      | 64/1000 [04:39<1:41:54,  6.53s/it]

[I 2026-05-19 13:59:31,520] Trial 63 finished with value: 0.9498425768409515 and parameters: {'n_estimators': 229, 'learning_rate': 0.04199397501427866, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 285, 'subsample': 0.8723181819092316, 'colsample_bytree': 0.7782191576310742, 'reg_alpha': 0.14661414305113668, 'reg_lambda': 0.03191618042284481}. Best is trial 54 with value: 0.9498509635591781.

Best trial: 54. Best value: 0.949851:   6%|███████                                                                                                      | 65/1000 [04:42<1:22:55,  5.32s/it]

[I 2026-05-19 13:59:33,998] Trial 64 finished with value: 0.9498428303818631 and parameters: {'n_estimators': 224, 'learning_rate': 0.04108344899499407, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 226, 'subsample': 0.8138682886433674, 'colsample_bytree': 0.7817652041873941, 'reg_alpha': 0.14739154310886404, 'reg_lambda': 0.030494392582750687}. Best is trial 54 with value: 0.9498509635591781.

Best trial: 65. Best value: 0.949855:   7%|███████▏                                                                                                     | 66/1000 [04:44<1:09:41,  4.48s/it]

[I 2026-05-19 13:59:36,523] Trial 65 finished with value: 0.949854886618712 and parameters: {'n_estimators': 229, 'learning_rate': 0.04126305058095294, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 283, 'subsample': 0.8141201276555892, 'colsample_bytree': 0.6791481619828064, 'reg_alpha': 0.12800930531575969, 'reg_lambda': 0.0003606423296924578}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   7%|███████▍                                                                                                       | 67/1000 [04:44<50:28,  3.25s/it]

[I 2026-05-19 13:59:36,900] Trial 66 finished with value: 0.9498459248023206 and parameters: {'n_estimators': 226, 'learning_rate': 0.041292780115613666, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 284, 'subsample': 0.806623227662286, 'colsample_bytree': 0.6773727424029597, 'reg_alpha': 0.12198893279090617, 'reg_lambda': 0.0004109945805303551}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   7%|███████▍                                                                                                     | 68/1000 [04:54<1:21:25,  5.24s/it]

[I 2026-05-19 13:59:46,785] Trial 67 finished with value: 0.9498393529877951 and parameters: {'n_estimators': 238, 'learning_rate': 0.04182278710648144, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 282, 'subsample': 0.8179616886337092, 'colsample_bytree': 0.6710867068310578, 'reg_alpha': 0.10941570323535621, 'reg_lambda': 0.00040149849838624007}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   7%|███████▌                                                                                                     | 69/1000 [04:59<1:16:59,  4.96s/it]

[I 2026-05-19 13:59:51,098] Trial 68 finished with value: 0.9498482925128624 and parameters: {'n_estimators': 238, 'learning_rate': 0.040643488700546376, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 194, 'subsample': 0.8297379807335303, 'colsample_bytree': 0.681540055360547, 'reg_alpha': 0.11424026631002852, 'reg_lambda': 0.0003861760074605294}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   7%|███████▋                                                                                                     | 70/1000 [05:03<1:14:49,  4.83s/it]

[I 2026-05-19 13:59:55,613] Trial 69 finished with value: 0.9498391730532832 and parameters: {'n_estimators': 232, 'learning_rate': 0.04104651081587903, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 178, 'subsample': 0.817573429257177, 'colsample_bytree': 0.6909347915031537, 'reg_alpha': 0.11819586036565886, 'reg_lambda': 0.0004148160141433268}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   7%|███████▋                                                                                                     | 71/1000 [05:06<1:07:29,  4.36s/it]

[I 2026-05-19 13:59:58,862] Trial 70 finished with value: 0.9498461172870607 and parameters: {'n_estimators': 234, 'learning_rate': 0.04083633031687401, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 193, 'subsample': 0.8220089743192758, 'colsample_bytree': 0.6917195762445114, 'reg_alpha': 0.11394202538198864, 'reg_lambda': 0.00041854416912653333}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   7%|███████▊                                                                                                     | 72/1000 [05:11<1:06:57,  4.33s/it]

[I 2026-05-19 14:00:03,137] Trial 71 finished with value: 0.9498471891033361 and parameters: {'n_estimators': 246, 'learning_rate': 0.04268704574212439, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 191, 'subsample': 0.8191078666147608, 'colsample_bytree': 0.6929916752758589, 'reg_alpha': 0.28430289380120827, 'reg_lambda': 0.00018346783438115302}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   7%|███████▉                                                                                                     | 73/1000 [05:16<1:11:24,  4.62s/it]

[I 2026-05-19 14:00:08,403] Trial 72 finished with value: 0.9498457690964642 and parameters: {'n_estimators': 249, 'learning_rate': 0.0415963729184225, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 285, 'subsample': 0.8212886284978291, 'colsample_bytree': 0.683109073089987, 'reg_alpha': 0.36150604211695814, 'reg_lambda': 0.0005821173360412769}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   7%|████████                                                                                                     | 74/1000 [05:19<1:02:18,  4.04s/it]

[I 2026-05-19 14:00:11,116] Trial 73 finished with value: 0.9498436855319234 and parameters: {'n_estimators': 249, 'learning_rate': 0.042177177836746106, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 194, 'subsample': 0.8215171823670394, 'colsample_bytree': 0.7723925634023219, 'reg_alpha': 0.055781398311411975, 'reg_lambda': 0.00019775376583112977}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   8%|████████▎                                                                                                      | 75/1000 [05:19<46:46,  3.03s/it]

[I 2026-05-19 14:00:11,808] Trial 74 finished with value: 0.9498520427327521 and parameters: {'n_estimators': 249, 'learning_rate': 0.041722295180930756, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 199, 'subsample': 0.8217506144434945, 'colsample_bytree': 0.7857213846626211, 'reg_alpha': 0.3429422516815739, 'reg_lambda': 0.027557245384439235}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   8%|████████▎                                                                                                    | 76/1000 [05:31<1:27:51,  5.71s/it]

[I 2026-05-19 14:00:23,750] Trial 75 finished with value: 0.9498450777489907 and parameters: {'n_estimators': 251, 'learning_rate': 0.04286907716177366, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 284, 'subsample': 0.8180266328388317, 'colsample_bytree': 0.693095091931029, 'reg_alpha': 0.27153969313944004, 'reg_lambda': 0.0002356721801507469}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   8%|████████▍                                                                                                    | 77/1000 [05:40<1:41:01,  6.57s/it]

[I 2026-05-19 14:00:32,331] Trial 77 finished with value: 0.949852437267861 and parameters: {'n_estimators': 246, 'learning_rate': 0.044042834093476944, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 177, 'subsample': 0.8300071952064436, 'colsample_bytree': 0.6896362891288936, 'reg_alpha': 0.414233515494379, 'reg_lambda': 0.00019525554115613244}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   8%|████████▌                                                                                                    | 78/1000 [05:42<1:20:44,  5.25s/it]

[I 2026-05-19 14:00:34,505] Trial 76 finished with value: 0.9498361624086378 and parameters: {'n_estimators': 244, 'learning_rate': 0.028264154700647196, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 198, 'subsample': 0.8296319555801593, 'colsample_bytree': 0.6919716318602623, 'reg_alpha': 0.34216274242033845, 'reg_lambda': 0.0001998760521080276}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   8%|████████▌                                                                                                    | 79/1000 [05:47<1:20:45,  5.26s/it]

[I 2026-05-19 14:00:39,790] Trial 78 finished with value: 0.9498318684497706 and parameters: {'n_estimators': 247, 'learning_rate': 0.02674840244415768, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 177, 'subsample': 0.827888476387006, 'colsample_bytree': 0.6882833757190888, 'reg_alpha': 0.5255567761556471, 'reg_lambda': 0.0002161870860909804}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   8%|████████▋                                                                                                    | 80/1000 [05:49<1:04:43,  4.22s/it]

[I 2026-05-19 14:00:41,595] Trial 79 finished with value: 0.9498403157727126 and parameters: {'n_estimators': 248, 'learning_rate': 0.04447137559802656, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 189, 'subsample': 0.8271865320691334, 'colsample_bytree': 0.6942828654713856, 'reg_alpha': 0.34992625252873405, 'reg_lambda': 0.00016241363902985665}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   8%|████████▊                                                                                                    | 81/1000 [05:58<1:24:15,  5.50s/it]

[I 2026-05-19 14:00:50,089] Trial 80 finished with value: 0.9498356513525584 and parameters: {'n_estimators': 249, 'learning_rate': 0.028071749724519653, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 173, 'subsample': 0.7654662920799391, 'colsample_bytree': 0.6974979999117974, 'reg_alpha': 0.5744276799930531, 'reg_lambda': 0.0001425821887521388}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   8%|████████▉                                                                                                    | 82/1000 [06:02<1:16:55,  5.03s/it]

[I 2026-05-19 14:00:54,008] Trial 81 finished with value: 0.9498496707717432 and parameters: {'n_estimators': 252, 'learning_rate': 0.04998513245820184, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 202, 'subsample': 0.7569425845894718, 'colsample_bytree': 0.7017261581310597, 'reg_alpha': 0.719694576461636, 'reg_lambda': 0.0001982213972665801}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   8%|█████████                                                                                                    | 83/1000 [06:03<1:00:15,  3.94s/it]

[I 2026-05-19 14:00:55,415] Trial 82 finished with value: 0.9498462807336381 and parameters: {'n_estimators': 250, 'learning_rate': 0.04524960876612264, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 207, 'subsample': 0.7626654694697879, 'colsample_bytree': 0.7064583595552205, 'reg_alpha': 0.4409171314656838, 'reg_lambda': 0.00017924643161748815}. Best is trial 65 with value: 0.949854886618712.

Best trial: 65. Best value: 0.949855:   8%|█████████▎                                                                                                     | 84/1000 [06:06<57:31,  3.77s/it]

[I 2026-05-19 14:00:58,767] Trial 84 finished with value: 0.9498498738461079 and parameters: {'n_estimators': 215, 'learning_rate': 0.04967340787501222, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 193, 'subsample': 0.7650500536944955, 'colsample_bytree': 0.6538400770884171, 'reg_alpha': 0.8208256369483168, 'reg_lambda': 0.00019275721870335469}. Best is trial 65 with value: 0.949854886618712.

Best trial: 86. Best value: 0.949856:   8%|█████████▍                                                                                                     | 85/1000 [06:08<45:59,  3.02s/it]

[I 2026-05-19 14:01:00,027] Trial 86 finished with value: 0.9498560002780241 and parameters: {'n_estimators': 216, 'learning_rate': 0.04898596316773458, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 210, 'subsample': 0.7666639065171194, 'colsample_bytree': 0.642379239714998, 'reg_alpha': 1.564062520422161, 'reg_lambda': 0.00018554895089859557}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 86. Best value: 0.949856:   9%|█████████▌                                                                                                     | 86/1000 [06:09<36:55,  2.42s/it]

[I 2026-05-19 14:01:01,070] Trial 83 finished with value: 0.9498311461888372 and parameters: {'n_estimators': 245, 'learning_rate': 0.027558852240927478, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 197, 'subsample': 0.7630877613182419, 'colsample_bytree': 0.7032281171225274, 'reg_alpha': 0.4256831921200492, 'reg_lambda': 0.00018189329415508086}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 86. Best value: 0.949856:   9%|█████████▋                                                                                                     | 87/1000 [06:10<31:12,  2.05s/it]

[I 2026-05-19 14:01:02,238] Trial 85 finished with value: 0.9498387842564326 and parameters: {'n_estimators': 214, 'learning_rate': 0.02686913071417072, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 204, 'subsample': 0.7624914104038846, 'colsample_bytree': 0.6477330732109658, 'reg_alpha': 1.229327375615681, 'reg_lambda': 0.00016991037380408873}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 86. Best value: 0.949856:   9%|█████████▌                                                                                                   | 88/1000 [06:26<1:35:59,  6.32s/it]

[I 2026-05-19 14:01:18,512] Trial 91 finished with value: 0.9498502848074148 and parameters: {'n_estimators': 213, 'learning_rate': 0.049944701066403745, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 210, 'subsample': 0.7614019105976485, 'colsample_bytree': 0.6514647262703985, 'reg_alpha': 1.1911153820056195, 'reg_lambda': 0.00011850143674131746}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 86. Best value: 0.949856:   9%|█████████▋                                                                                                   | 89/1000 [06:31<1:30:24,  5.95s/it]

[I 2026-05-19 14:01:23,634] Trial 87 finished with value: 0.9498321687949176 and parameters: {'n_estimators': 243, 'learning_rate': 0.028027196912148902, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 184, 'subsample': 0.7623221637180122, 'colsample_bytree': 0.7061923236233665, 'reg_alpha': 0.958034991638318, 'reg_lambda': 0.00013057993603613063}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 86. Best value: 0.949856:   9%|█████████▊                                                                                                   | 90/1000 [06:32<1:07:54,  4.48s/it]

[I 2026-05-19 14:01:24,672] Trial 89 finished with value: 0.9498500319747507 and parameters: {'n_estimators': 216, 'learning_rate': 0.04925796963252145, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 174, 'subsample': 0.7645271677783657, 'colsample_bytree': 0.7063832356839057, 'reg_alpha': 1.1980386467280963, 'reg_lambda': 0.00010102281899986307}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 86. Best value: 0.949856:   9%|█████████▉                                                                                                   | 91/1000 [06:36<1:06:42,  4.40s/it]

[I 2026-05-19 14:01:28,892] Trial 96 finished with value: 0.9498276589243593 and parameters: {'n_estimators': 209, 'learning_rate': 0.04998138955940464, 'max_depth': 2, 'num_leaves': 15, 'min_child_samples': 203, 'subsample': 0.7145224814286937, 'colsample_bytree': 0.6384039148266647, 'reg_alpha': 1.2321959252675643, 'reg_lambda': 8.852912770989365e-05}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 86. Best value: 0.949856:   9%|██████████▏                                                                                                    | 92/1000 [06:38<52:44,  3.49s/it]

[I 2026-05-19 14:01:30,239] Trial 90 finished with value: 0.9498522268682532 and parameters: {'n_estimators': 218, 'learning_rate': 0.04985114952119515, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 208, 'subsample': 0.7644325674697787, 'colsample_bytree': 0.6519997057145582, 'reg_alpha': 0.8218128881489517, 'reg_lambda': 1.9359558214671964e-05}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 86. Best value: 0.949856:   9%|██████████▎                                                                                                    | 93/1000 [06:38<37:56,  2.51s/it]

[I 2026-05-19 14:01:30,478] Trial 88 finished with value: 0.9498343619604939 and parameters: {'n_estimators': 243, 'learning_rate': 0.027251926293866018, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 174, 'subsample': 0.7633209101985146, 'colsample_bytree': 0.7112202002629596, 'reg_alpha': 1.0677466459569362, 'reg_lambda': 0.00010348641317956072}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 86. Best value: 0.949856:   9%|██████████▍                                                                                                    | 94/1000 [06:44<54:38,  3.62s/it]

[I 2026-05-19 14:01:36,681] Trial 97 finished with value: 0.9498477994035828 and parameters: {'n_estimators': 204, 'learning_rate': 0.049413060786864325, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 216, 'subsample': 0.743034267194234, 'colsample_bytree': 0.6436489877522549, 'reg_alpha': 1.075508317317999, 'reg_lambda': 9.3949825521922e-05}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 86. Best value: 0.949856:  10%|██████████▌                                                                                                    | 95/1000 [06:49<58:27,  3.88s/it]

[I 2026-05-19 14:01:41,162] Trial 92 finished with value: 0.9498472781483237 and parameters: {'n_estimators': 210, 'learning_rate': 0.048462578146341216, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 207, 'subsample': 0.857558265855562, 'colsample_bytree': 0.7101907200078206, 'reg_alpha': 0.8448952112370536, 'reg_lambda': 0.0007333699561959272}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 86. Best value: 0.949856:  10%|██████████▋                                                                                                    | 96/1000 [06:51<50:46,  3.37s/it]

[I 2026-05-19 14:01:43,327] Trial 98 finished with value: 0.949851810389909 and parameters: {'n_estimators': 218, 'learning_rate': 0.04957575195523823, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 235, 'subsample': 0.7387021256900708, 'colsample_bytree': 0.6565501984642108, 'reg_alpha': 2.750969004627929, 'reg_lambda': 9.158578732134962e-05}. Best is trial 86 with value: 0.9498560002780241.
[I 2026-05-19 14:01:43,387] Trial 93 finished with value: 0.9498496602458992 and parameters: {'n_estimators': 216, 'learning_rate': 0.049816684404968094, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 208, 'subsample': 0.7478435245235527, 'colsample_bytree': 0.6529910639809848, 'reg_alpha': 1.2058437623528626, 'reg_lambda': 2.202369338786949e-05}. Best is trial 86 with value: 0.9498560002780241.

Best trial: 94. Best value: 0.949859:  10%|██████████▉                                                                                                    | 98/1000 [06:54<37:32,  2.50s/it]

[I 2026-05-19 14:01:46,308] Trial 94 finished with value: 0.9498591181656394 and parameters: {'n_estimators': 213, 'learning_rate': 0.04861708986558595, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 214, 'subsample': 0.8519433561722802, 'colsample_bytree': 0.6543713936896085, 'reg_alpha': 3.0184963474658413, 'reg_lambda': 0.0007661624892830454}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  10%|██████████▉                                                                                                    | 99/1000 [06:55<31:09,  2.08s/it]

[I 2026-05-19 14:01:47,103] Trial 100 finished with value: 0.9498051668310655 and parameters: {'n_estimators': 159, 'learning_rate': 0.04893722422683352, 'max_depth': 2, 'num_leaves': 15, 'min_child_samples': 211, 'subsample': 0.7460788915267735, 'colsample_bytree': 0.6573309818251374, 'reg_alpha': 3.8987509900469006, 'reg_lambda': 2.1635309830390834e-05}. Best is trial 94 with value: 0.9498591181656394.
[I 2026-05-19 14:01:47,179] Trial 95 finished with value: 0.9498495523168238 and parameters: {'n_estimators': 206, 'learning_rate': 0.04833429104929207, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 202, 'subsample': 0.710078811462699, 'colsample_bytree': 0.6477693680130627, 'reg_alpha': 1.1710319665291382, 'reg_lambda': 9.57073500688686e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  10%|███████████                                                                                                   | 101/1000 [06:56<22:28,  1.50s/it]

[I 2026-05-19 14:01:48,471] Trial 99 finished with value: 0.9498246571370974 and parameters: {'n_estimators': 208, 'learning_rate': 0.049989001637258175, 'max_depth': 2, 'num_leaves': 15, 'min_child_samples': 212, 'subsample': 0.7133694880689017, 'colsample_bytree': 0.6522563081081696, 'reg_alpha': 7.390453932146932, 'reg_lambda': 2.2373690370271723e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  10%|███████████▏                                                                                                  | 102/1000 [07:04<43:00,  2.87s/it]

[I 2026-05-19 14:01:55,989] Trial 101 finished with value: 0.9498278020835977 and parameters: {'n_estimators': 215, 'learning_rate': 0.046843902281075024, 'max_depth': 2, 'num_leaves': 15, 'min_child_samples': 167, 'subsample': 0.7171562209361945, 'colsample_bytree': 0.6535340640703634, 'reg_alpha': 4.009882090470489, 'reg_lambda': 9.689827108533101e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  10%|███████████                                                                                                 | 103/1000 [07:12<1:04:48,  4.33s/it]

[I 2026-05-19 14:02:04,786] Trial 105 finished with value: 0.9498031153364218 and parameters: {'n_estimators': 189, 'learning_rate': 0.03745445225634463, 'max_depth': 2, 'num_leaves': 13, 'min_child_samples': 212, 'subsample': 0.728549806602898, 'colsample_bytree': 0.662245375938779, 'reg_alpha': 3.0683590615495135, 'reg_lambda': 1.995582891675067e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  10%|███████████▍                                                                                                  | 104/1000 [07:14<55:58,  3.75s/it]

[I 2026-05-19 14:02:06,878] Trial 102 finished with value: 0.9498138712016864 and parameters: {'n_estimators': 190, 'learning_rate': 0.03777338643551931, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 213, 'subsample': 0.7518912783920926, 'colsample_bytree': 0.6561472249234349, 'reg_alpha': 6.761763346083628, 'reg_lambda': 2.8150328938753107e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  10%|███████████▌                                                                                                  | 105/1000 [07:16<46:37,  3.13s/it]

[I 2026-05-19 14:02:08,306] Trial 103 finished with value: 0.9498156975180521 and parameters: {'n_estimators': 193, 'learning_rate': 0.03696540940018648, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 180, 'subsample': 0.7368984846182691, 'colsample_bytree': 0.6581774043788531, 'reg_alpha': 6.901685849233524, 'reg_lambda': 2.0244466499558727e-05}. Best is trial 94 with value: 0.9498591181656394.
[I 2026-05-19 14:02:08,336] Trial 106 finished with value: 0.9497978656465236 and parameters: {'n_estimators': 190, 'learning_rate': 0.036868082107721585, 'max_depth': 2, 'num_leaves': 13, 'min_child_samples': 213, 'subsample': 0.7773632292480067, 'colsample_bytree': 0.6582357489900966, 'reg_alpha': 6.366763783496392, 'reg_lambda': 2.36305095923208e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  11%|███████████▊                                                                                                  | 107/1000 [07:20<38:47,  2.61s/it]

[I 2026-05-19 14:02:12,196] Trial 104 finished with value: 0.9498294131288609 and parameters: {'n_estimators': 217, 'learning_rate': 0.03712875458836122, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 218, 'subsample': 0.7415973663567196, 'colsample_bytree': 0.6539039646462966, 'reg_alpha': 3.1762932220918207, 'reg_lambda': 2.1005229359333354e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  11%|███████████▋                                                                                                | 108/1000 [07:29<1:00:37,  4.08s/it]

[I 2026-05-19 14:02:20,987] Trial 108 finished with value: 0.9498192574806193 and parameters: {'n_estimators': 191, 'learning_rate': 0.03781531240772202, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 234, 'subsample': 0.7335215322310135, 'colsample_bytree': 0.6609407720926677, 'reg_alpha': 3.9956900634815193, 'reg_lambda': 2.019270988923491e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  11%|███████████▉                                                                                                  | 109/1000 [07:30<51:59,  3.50s/it]

[I 2026-05-19 14:02:22,787] Trial 107 finished with value: 0.9498270983850873 and parameters: {'n_estimators': 195, 'learning_rate': 0.036724576712203194, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 233, 'subsample': 0.7209111489108083, 'colsample_bytree': 0.6571087610908758, 'reg_alpha': 3.102308786954788, 'reg_lambda': 2.9182235632466256e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  11%|████████████                                                                                                  | 110/1000 [07:32<42:47,  2.89s/it]

[I 2026-05-19 14:02:23,963] Trial 110 finished with value: 0.9498203173804118 and parameters: {'n_estimators': 192, 'learning_rate': 0.037449996054604265, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 237, 'subsample': 0.8415415407846107, 'colsample_bytree': 0.6607415828008019, 'reg_alpha': 3.522520022520925, 'reg_lambda': 6.072823562070124e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  11%|████████████▏                                                                                                 | 111/1000 [07:32<33:41,  2.27s/it]

[I 2026-05-19 14:02:24,647] Trial 112 finished with value: 0.949820853387328 and parameters: {'n_estimators': 192, 'learning_rate': 0.03691474882811162, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 234, 'subsample': 0.7751537294792727, 'colsample_bytree': 0.6626077292543999, 'reg_alpha': 2.422489542007665, 'reg_lambda': 3.727473078691616e-05}. Best is trial 94 with value: 0.9498591181656394.
[I 2026-05-19 14:02:24,734] Trial 109 finished with value: 0.9498205358450701 and parameters: {'n_estimators': 192, 'learning_rate': 0.03708031440589814, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 262, 'subsample': 0.7134671663561264, 'colsample_bytree': 0.6593268334268902, 'reg_alpha': 3.7425779992931854, 'reg_lambda': 2.2949229922456416e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  11%|████████████▍                                                                                                 | 113/1000 [07:33<22:28,  1.52s/it]

[I 2026-05-19 14:02:25,756] Trial 111 finished with value: 0.949817994511753 and parameters: {'n_estimators': 194, 'learning_rate': 0.037004692423914166, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 168, 'subsample': 0.776673967442791, 'colsample_bytree': 0.6699897591123105, 'reg_alpha': 4.061463401916817, 'reg_lambda': 4.382163168765408e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  11%|████████████▌                                                                                                 | 114/1000 [07:40<41:48,  2.83s/it]

[I 2026-05-19 14:02:32,763] Trial 113 finished with value: 0.9498245016661924 and parameters: {'n_estimators': 192, 'learning_rate': 0.03718325218153067, 'max_depth': 3, 'num_leaves': 13, 'min_child_samples': 233, 'subsample': 0.7360703696277103, 'colsample_bytree': 0.6283305160066507, 'reg_alpha': 2.104831049826532, 'reg_lambda': 3.7167424081714154e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  12%|████████████▍                                                                                               | 115/1000 [07:49<1:04:26,  4.37s/it]

[I 2026-05-19 14:02:41,635] Trial 114 finished with value: 0.9498397221504014 and parameters: {'n_estimators': 197, 'learning_rate': 0.04533752035622757, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 251, 'subsample': 0.7744023156272691, 'colsample_bytree': 0.6302060831063231, 'reg_alpha': 1.965164275522324, 'reg_lambda': 4.450587493698681e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  12%|████████████▌                                                                                               | 116/1000 [07:56<1:13:11,  4.97s/it]

[I 2026-05-19 14:02:48,252] Trial 117 finished with value: 0.9498362080100776 and parameters: {'n_estimators': 222, 'learning_rate': 0.04437232767519824, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 231, 'subsample': 0.8439215084956102, 'colsample_bytree': 0.670261926711403, 'reg_alpha': 2.4036748625141384, 'reg_lambda': 4.72104706034994e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  12%|████████████▋                                                                                               | 117/1000 [07:58<1:01:51,  4.20s/it]

[I 2026-05-19 14:02:50,441] Trial 116 finished with value: 0.9498423650775344 and parameters: {'n_estimators': 221, 'learning_rate': 0.04517357856543352, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 256, 'subsample': 0.7736779356576393, 'colsample_bytree': 0.6343265207742923, 'reg_alpha': 1.8774226691588862, 'reg_lambda': 4.8970807197217535e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  12%|████████████▉                                                                                                 | 118/1000 [07:59<48:55,  3.33s/it]

[I 2026-05-19 14:02:51,533] Trial 115 finished with value: 0.9498312762149492 and parameters: {'n_estimators': 221, 'learning_rate': 0.0357355091896525, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 256, 'subsample': 0.77797145025822, 'colsample_bytree': 0.6302605520390253, 'reg_alpha': 2.0530131773509144, 'reg_lambda': 4.876411563240219e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  12%|█████████████                                                                                                 | 119/1000 [08:04<54:26,  3.71s/it]

[I 2026-05-19 14:02:56,210] Trial 119 finished with value: 0.9498262279458446 and parameters: {'n_estimators': 181, 'learning_rate': 0.0447785606479763, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 260, 'subsample': 0.771806831305118, 'colsample_bytree': 0.6279911142193947, 'reg_alpha': 21.298560631533345, 'reg_lambda': 5.510378140471092e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  12%|█████████████▏                                                                                                | 120/1000 [08:06<46:26,  3.17s/it]

[I 2026-05-19 14:02:58,053] Trial 118 finished with value: 0.9498460365289001 and parameters: {'n_estimators': 237, 'learning_rate': 0.045269814324799054, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 233, 'subsample': 0.8432824153916387, 'colsample_bytree': 0.6328180606793462, 'reg_alpha': 2.1857646998468394, 'reg_lambda': 4.271045477609573e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  12%|█████████████                                                                                               | 121/1000 [08:14<1:07:44,  4.62s/it]

[I 2026-05-19 14:03:06,182] Trial 122 finished with value: 0.94985073227962 and parameters: {'n_estimators': 180, 'learning_rate': 0.044976107592978265, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 252, 'subsample': 0.7699885425714621, 'colsample_bytree': 0.630261969152174, 'reg_alpha': 1.863984854422228, 'reg_lambda': 0.00028495115605493945}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  12%|█████████████▍                                                                                                | 122/1000 [08:14<49:59,  3.42s/it]

[I 2026-05-19 14:03:06,709] Trial 120 finished with value: 0.9498459929422032 and parameters: {'n_estimators': 176, 'learning_rate': 0.04463797964053725, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 260, 'subsample': 0.8440968764671148, 'colsample_bytree': 0.6283970854392117, 'reg_alpha': 1.695602337164896, 'reg_lambda': 5.233277734347325e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  12%|█████████████▌                                                                                                | 123/1000 [08:17<48:30,  3.32s/it]

[I 2026-05-19 14:03:09,796] Trial 124 finished with value: 0.949849468526018 and parameters: {'n_estimators': 179, 'learning_rate': 0.045234664558139535, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 255, 'subsample': 0.9541700278231107, 'colsample_bytree': 0.6272653644889735, 'reg_alpha': 1.968895003413167, 'reg_lambda': 5.516007621156021e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  12%|█████████████▋                                                                                                | 124/1000 [08:21<47:36,  3.26s/it]

[I 2026-05-19 14:03:12,923] Trial 123 finished with value: 0.9498564076208389 and parameters: {'n_estimators': 221, 'learning_rate': 0.04535445300756865, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 186, 'subsample': 0.7845445515187306, 'colsample_bytree': 0.6303349293663485, 'reg_alpha': 24.068447255232012, 'reg_lambda': 0.0008714318364227936}. Best is trial 94 with value: 0.9498591181656394.
[I 2026-05-19 14:03:13,126] Trial 121 finished with value: 0.9498474743796717 and parameters: {'n_estimators': 220, 'learning_rate': 0.04520458075222081, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 252, 'subsample': 0.789543509799653, 'colsample_bytree': 0.6283533676707646, 'reg_alpha': 1.7403938269562857, 'reg_lambda': 4.124644795919283e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  13%|█████████████▊                                                                                                | 126/1000 [08:22<29:42,  2.04s/it]

[I 2026-05-19 14:03:14,337] Trial 125 finished with value: 0.9498517204734555 and parameters: {'n_estimators': 181, 'learning_rate': 0.0447069424267516, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 185, 'subsample': 0.7851386053194719, 'colsample_bytree': 0.6287581645253407, 'reg_alpha': 12.472357093828903, 'reg_lambda': 0.000291171855624049}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  13%|█████████████▋                                                                                              | 127/1000 [08:35<1:16:19,  5.25s/it]

[I 2026-05-19 14:03:27,208] Trial 128 finished with value: 0.9498499713716868 and parameters: {'n_estimators': 178, 'learning_rate': 0.04625673273545129, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 185, 'subsample': 0.7872874109896614, 'colsample_bytree': 0.6212033842257267, 'reg_alpha': 14.5508213949439, 'reg_lambda': 0.0003040203338881312}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  13%|█████████████▊                                                                                              | 128/1000 [08:37<1:01:59,  4.27s/it]

[I 2026-05-19 14:03:29,168] Trial 127 finished with value: 0.9498387483295841 and parameters: {'n_estimators': 177, 'learning_rate': 0.04622244772725554, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 186, 'subsample': 0.7924936249867791, 'colsample_bytree': 0.7566837599511969, 'reg_alpha': 13.198784989659487, 'reg_lambda': 0.0002872291917782988}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  13%|█████████████▉                                                                                              | 129/1000 [08:45<1:19:43,  5.49s/it]

[I 2026-05-19 14:03:37,538] Trial 126 finished with value: 0.9498427264531969 and parameters: {'n_estimators': 220, 'learning_rate': 0.04409052567310219, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 184, 'subsample': 0.7896380809174157, 'colsample_bytree': 0.7592578990588398, 'reg_alpha': 0.2238051839142878, 'reg_lambda': 0.0002936264968469012}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  13%|██████████████                                                                                              | 130/1000 [08:49<1:14:55,  5.17s/it]

[I 2026-05-19 14:03:41,943] Trial 129 finished with value: 0.9498473335336388 and parameters: {'n_estimators': 236, 'learning_rate': 0.0456130245558947, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 184, 'subsample': 0.9393691731886062, 'colsample_bytree': 0.7545486369937737, 'reg_alpha': 0.21477264227797863, 'reg_lambda': 0.0032331929786639604}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  13%|██████████████▍                                                                                               | 131/1000 [08:50<55:43,  3.85s/it]

[I 2026-05-19 14:03:42,688] Trial 136 finished with value: 0.9498194310187392 and parameters: {'n_estimators': 133, 'learning_rate': 0.04687127153070414, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 219, 'subsample': 0.7871914889794188, 'colsample_bytree': 0.7518382148793896, 'reg_alpha': 40.37103050143448, 'reg_lambda': 0.002584629020332263}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  13%|██████████████▌                                                                                               | 132/1000 [08:53<51:56,  3.59s/it]

[I 2026-05-19 14:03:45,691] Trial 132 finished with value: 0.9498429594761248 and parameters: {'n_estimators': 171, 'learning_rate': 0.04690568390456187, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 186, 'subsample': 0.7907875953083646, 'colsample_bytree': 0.7558832982577599, 'reg_alpha': 0.20267274068603008, 'reg_lambda': 0.00028249282229380853}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  13%|██████████████▎                                                                                             | 133/1000 [08:59<1:00:05,  4.16s/it]

[I 2026-05-19 14:03:51,188] Trial 140 pruned.

Best trial: 94. Best value: 0.949859:  13%|██████████████▋                                                                                               | 134/1000 [09:02<55:56,  3.88s/it]

[I 2026-05-19 14:03:54,383] Trial 133 finished with value: 0.9498420981013972 and parameters: {'n_estimators': 202, 'learning_rate': 0.04606107936610849, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 185, 'subsample': 0.7880605358368117, 'colsample_bytree': 0.9013250072936624, 'reg_alpha': 0.03893295592775489, 'reg_lambda': 0.0003055839252184742}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  14%|██████████████▉                                                                                               | 136/1000 [09:02<29:06,  2.02s/it]

[I 2026-05-19 14:03:54,727] Trial 130 finished with value: 0.9496839281798458 and parameters: {'n_estimators': 238, 'learning_rate': 0.00857014464932218, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 188, 'subsample': 0.78838893104543, 'colsample_bytree': 0.8364261691229563, 'reg_alpha': 0.17578272808333786, 'reg_lambda': 0.0006935917604778273}. Best is trial 94 with value: 0.9498591181656394.
[I 2026-05-19 14:03:54,893] Trial 137 finished with value: 0.9498291422803442 and parameters: {'n_estimators': 166, 'learning_rate': 0.039661656550433994, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 186, 'subsample': 0.7885804426622545, 'colsample_bytree': 0.7459892528020698, 'reg_alpha': 0.21470239499060229, 'reg_lambda': 0.0002928002822917914}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  14%|███████████████                                                                                               | 137/1000 [09:10<53:07,  3.69s/it]

[I 2026-05-19 14:04:02,492] Trial 131 finished with value: 0.9497425323459243 and parameters: {'n_estimators': 279, 'learning_rate': 0.010438336090836253, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 184, 'subsample': 0.9579140261151612, 'colsample_bytree': 0.7471380172448897, 'reg_alpha': 0.2245734823863554, 'reg_lambda': 0.003467394176224714}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  14%|███████████████▏                                                                                              | 138/1000 [09:14<54:54,  3.82s/it]

[I 2026-05-19 14:04:06,624] Trial 134 finished with value: 0.949754534573308 and parameters: {'n_estimators': 218, 'learning_rate': 0.011234934601425692, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 198, 'subsample': 0.788751618208834, 'colsample_bytree': 0.836348852630331, 'reg_alpha': 0.23625833364120913, 'reg_lambda': 0.0006832895262390744}. Best is trial 94 with value: 0.9498591181656394.
[I 2026-05-19 14:04:06,654] Trial 139 finished with value: 0.9495065053692027 and parameters: {'n_estimators': 164, 'learning_rate': 0.010425977988974117, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 219, 'subsample': 0.8091640855044355, 'colsample_bytree': 0.640224323279931, 'reg_alpha': 22.253266136982795, 'reg_lambda': 0.0006227685484598583}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  14%|███████████████▍                                                                                              | 140/1000 [09:15<33:46,  2.36s/it]

[I 2026-05-19 14:04:07,887] Trial 138 finished with value: 0.949816823101448 and parameters: {'n_estimators': 169, 'learning_rate': 0.039667566103178134, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 186, 'subsample': 0.8113032489121138, 'colsample_bytree': 0.7506156741268644, 'reg_alpha': 43.12275761423041, 'reg_lambda': 0.000825512392114716}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  14%|███████████████▌                                                                                              | 141/1000 [09:19<38:12,  2.67s/it]

[I 2026-05-19 14:04:11,532] Trial 135 finished with value: 0.9498426918285029 and parameters: {'n_estimators': 279, 'learning_rate': 0.04670755374020355, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 188, 'subsample': 0.7867095477290593, 'colsample_bytree': 0.7609419826828044, 'reg_alpha': 36.19378555185371, 'reg_lambda': 0.0005991689480671171}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  14%|███████████████▎                                                                                            | 142/1000 [09:29<1:06:54,  4.68s/it]

[I 2026-05-19 14:04:21,863] Trial 143 finished with value: 0.9498235265280617 and parameters: {'n_estimators': 162, 'learning_rate': 0.03917961957434346, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 158, 'subsample': 0.7548216729144961, 'colsample_bytree': 0.6149012763879032, 'reg_alpha': 26.809125340618028, 'reg_lambda': 0.0007944097037746648}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  14%|███████████████▋                                                                                              | 143/1000 [09:30<50:11,  3.51s/it]

[I 2026-05-19 14:04:22,272] Trial 141 finished with value: 0.9497131429099624 and parameters: {'n_estimators': 163, 'learning_rate': 0.008568146106773549, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 218, 'subsample': 0.8078431986469116, 'colsample_bytree': 0.6776228214537626, 'reg_alpha': 0.6224579843444616, 'reg_lambda': 0.0008211426934567004}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  14%|███████████████▊                                                                                              | 144/1000 [09:36<59:07,  4.14s/it]

[I 2026-05-19 14:04:28,042] Trial 144 finished with value: 0.9494031108932337 and parameters: {'n_estimators': 161, 'learning_rate': 0.007957854991742903, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 198, 'subsample': 0.8555233237886467, 'colsample_bytree': 0.6180150958667334, 'reg_alpha': 14.669259612313367, 'reg_lambda': 0.0006294042282010185}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  14%|███████████████▉                                                                                              | 145/1000 [09:38<52:47,  3.71s/it]

[I 2026-05-19 14:04:30,646] Trial 142 finished with value: 0.9497926659315192 and parameters: {'n_estimators': 202, 'learning_rate': 0.02395087274335959, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 199, 'subsample': 0.8098886495399447, 'colsample_bytree': 0.6151393114747602, 'reg_alpha': 23.85405351517893, 'reg_lambda': 0.0007770860565880605}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  15%|████████████████                                                                                              | 146/1000 [09:40<46:13,  3.25s/it]

[I 2026-05-19 14:04:32,757] Trial 146 finished with value: 0.9498349811704901 and parameters: {'n_estimators': 160, 'learning_rate': 0.0394432590195373, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 199, 'subsample': 0.7527876052104392, 'colsample_bytree': 0.6166288537755391, 'reg_alpha': 20.2010785693255, 'reg_lambda': 0.0010563668917594458}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  15%|████████████████▏                                                                                             | 147/1000 [09:41<35:07,  2.47s/it]

[I 2026-05-19 14:04:33,370] Trial 145 finished with value: 0.9498257641230075 and parameters: {'n_estimators': 164, 'learning_rate': 0.03941898128158411, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 198, 'subsample': 0.7551932877227623, 'colsample_bytree': 0.6177802531281216, 'reg_alpha': 28.41919973086441, 'reg_lambda': 0.0007964808061599654}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  15%|████████████████▎                                                                                             | 148/1000 [09:46<46:18,  3.26s/it]

[I 2026-05-19 14:04:38,524] Trial 148 finished with value: 0.9498360027396732 and parameters: {'n_estimators': 156, 'learning_rate': 0.03945159797645422, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 175, 'subsample': 0.7980578347342435, 'colsample_bytree': 0.6147717551158083, 'reg_alpha': 10.670333419958588, 'reg_lambda': 0.0009122071492869203}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  15%|████████████████▍                                                                                             | 149/1000 [09:47<37:35,  2.65s/it]

[I 2026-05-19 14:04:39,724] Trial 147 finished with value: 0.9498454355172925 and parameters: {'n_estimators': 204, 'learning_rate': 0.03920768260989878, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 199, 'subsample': 0.8560972539680218, 'colsample_bytree': 0.6201036541915504, 'reg_alpha': 21.606056557759633, 'reg_lambda': 0.0008903479202619565}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  15%|████████████████▏                                                                                           | 150/1000 [10:05<1:41:40,  7.18s/it]

[I 2026-05-19 14:04:57,597] Trial 150 finished with value: 0.9494945502243872 and parameters: {'n_estimators': 200, 'learning_rate': 0.006453167005703626, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 171, 'subsample': 0.7987115652162247, 'colsample_bytree': 0.6750838568957094, 'reg_alpha': 11.445148197241181, 'reg_lambda': 0.00012472487422220826}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  15%|████████████████▎                                                                                           | 151/1000 [10:06<1:13:14,  5.18s/it]

[I 2026-05-19 14:04:58,030] Trial 152 finished with value: 0.9493853283255869 and parameters: {'n_estimators': 183, 'learning_rate': 0.0045612869677750635, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 274, 'subsample': 0.8349235154514885, 'colsample_bytree': 0.6772810059982004, 'reg_alpha': 11.296613158561875, 'reg_lambda': 0.00011488479487930415}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  15%|████████████████▍                                                                                           | 152/1000 [10:11<1:14:32,  5.27s/it]

[I 2026-05-19 14:05:03,549] Trial 149 finished with value: 0.9498573506939237 and parameters: {'n_estimators': 257, 'learning_rate': 0.04248155647960117, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 166, 'subsample': 0.7544422767053043, 'colsample_bytree': 0.6197768220658967, 'reg_alpha': 11.456365341848526, 'reg_lambda': 0.0010973141974579424}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  15%|████████████████▌                                                                                           | 153/1000 [10:15<1:07:47,  4.80s/it]

[I 2026-05-19 14:05:07,251] Trial 151 finished with value: 0.9498591013231584 and parameters: {'n_estimators': 256, 'learning_rate': 0.04232398881284771, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 177, 'subsample': 0.7570359161082528, 'colsample_bytree': 0.618079337976548, 'reg_alpha': 13.681838490095009, 'reg_lambda': 0.0009676371814803025}. Best is trial 94 with value: 0.9498591181656394.
[I 2026-05-19 14:05:07,270] Trial 154 finished with value: 0.9498480026595806 and parameters: {'n_estimators': 182, 'learning_rate': 0.04225931438135924, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 294, 'subsample': 0.7536945677979564, 'colsample_bytree': 0.6188561799156899, 'reg_alpha': 11.816971863627526, 'reg_lambda': 1.2908132614004343e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  16%|█████████████████                                                                                             | 155/1000 [10:16<39:42,  2.82s/it]

[I 2026-05-19 14:05:08,264] Trial 159 finished with value: 0.9497928732104789 and parameters: {'n_estimators': 208, 'learning_rate': 0.04245839064017794, 'max_depth': 4, 'num_leaves': 3, 'min_child_samples': 272, 'subsample': 0.8360042020361254, 'colsample_bytree': 0.9667526827484273, 'reg_alpha': 9.29044370756969, 'reg_lambda': 0.00012315221373480773}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 94. Best value: 0.949859:  16%|█████████████████▎                                                                                            | 157/1000 [10:22<37:45,  2.69s/it]

[I 2026-05-19 14:05:14,156] Trial 158 finished with value: 0.9498466723186813 and parameters: {'n_estimators': 185, 'learning_rate': 0.04222500995168437, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 299, 'subsample': 0.7725185472186693, 'colsample_bytree': 0.6051347215033985, 'reg_alpha': 9.73307428817381, 'reg_lambda': 0.00011758229211390834}. Best is trial 94 with value: 0.9498591181656394.
[I 2026-05-19 14:05:14,288] Trial 156 finished with value: 0.9498418971947287 and parameters: {'n_estimators': 182, 'learning_rate': 0.0428785781998673, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 291, 'subsample': 0.7535095441884606, 'colsample_bytree': 0.6065548978955402, 'reg_alpha': 0.6266571110898007, 'reg_lambda': 1.3807381760736957e-05}. Best is trial 94 with value: 0.9498591181656394.

Best trial: 153. Best value: 0.949868:  16%|█████████████████▏                                                                                           | 158/1000 [10:24<37:22,  2.66s/it]

[I 2026-05-19 14:05:16,923] Trial 153 finished with value: 0.9498675399289287 and parameters: {'n_estimators': 256, 'learning_rate': 0.04289601413002519, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 292, 'subsample': 0.7992575729984042, 'colsample_bytree': 0.6081352001125518, 'reg_alpha': 10.406161854166653, 'reg_lambda': 0.00012068679537262603}. Best is trial 153 with value: 0.9498675399289287.

Best trial: 155. Best value: 0.949868:  16%|█████████████████▎                                                                                           | 159/1000 [10:31<51:58,  3.71s/it]

[I 2026-05-19 14:05:23,309] Trial 155 finished with value: 0.9498680443602749 and parameters: {'n_estimators': 257, 'learning_rate': 0.04322718260242102, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 275, 'subsample': 0.753446648059474, 'colsample_bytree': 0.6199907342034939, 'reg_alpha': 9.64510422630006, 'reg_lambda': 1.4636309628929767e-05}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  16%|█████████████████▍                                                                                           | 160/1000 [10:36<56:16,  4.02s/it]

[I 2026-05-19 14:05:28,119] Trial 160 finished with value: 0.9498365994449873 and parameters: {'n_estimators': 183, 'learning_rate': 0.04177657797834033, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 167, 'subsample': 0.8330384897123972, 'colsample_bytree': 0.6761298742955794, 'reg_alpha': 0.0722640524215401, 'reg_lambda': 0.00012010913997996814}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  16%|█████████████████▌                                                                                           | 161/1000 [10:39<54:00,  3.86s/it]

[I 2026-05-19 14:05:31,590] Trial 157 finished with value: 0.9498518770570504 and parameters: {'n_estimators': 257, 'learning_rate': 0.042413246017196614, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 290, 'subsample': 0.9989144161498267, 'colsample_bytree': 0.6054987212962324, 'reg_alpha': 0.0001759851741490458, 'reg_lambda': 7.145275763816239e-05}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  16%|█████████████████▎                                                                                         | 162/1000 [10:45<1:01:32,  4.41s/it]

[I 2026-05-19 14:05:37,315] Trial 164 finished with value: 0.9497929889506651 and parameters: {'n_estimators': 210, 'learning_rate': 0.04311691174994459, 'max_depth': 4, 'num_leaves': 3, 'min_child_samples': 168, 'subsample': 0.7678072071537895, 'colsample_bytree': 0.602103135032494, 'reg_alpha': 5.600496211359755, 'reg_lambda': 0.0004989093274388587}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  16%|█████████████████▍                                                                                         | 163/1000 [10:55<1:26:52,  6.23s/it]

[I 2026-05-19 14:05:47,875] Trial 162 finished with value: 0.9498493228167799 and parameters: {'n_estimators': 214, 'learning_rate': 0.042854056808850266, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 165, 'subsample': 0.7727829100699021, 'colsample_bytree': 0.6451654413657234, 'reg_alpha': 0.7210821999898618, 'reg_lambda': 0.00048382409446490063}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  16%|█████████████████▌                                                                                         | 164/1000 [10:57<1:07:35,  4.85s/it]

[I 2026-05-19 14:05:49,487] Trial 170 finished with value: 0.9497413709200655 and parameters: {'n_estimators': 256, 'learning_rate': 0.030545304229236868, 'max_depth': 1, 'num_leaves': 16, 'min_child_samples': 164, 'subsample': 0.7438466699961208, 'colsample_bytree': 0.6448934818794544, 'reg_alpha': 5.2925564102591665, 'reg_lambda': 0.0004754212331735795}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  17%|██████████████████                                                                                           | 166/1000 [11:01<45:41,  3.29s/it]

[I 2026-05-19 14:05:53,618] Trial 163 finished with value: 0.9498589899717675 and parameters: {'n_estimators': 228, 'learning_rate': 0.04350973412822554, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 291, 'subsample': 0.6245314541822053, 'colsample_bytree': 0.6050399074517545, 'reg_alpha': 5.379550138395595, 'reg_lambda': 0.00044096890529888644}. Best is trial 155 with value: 0.9498680443602749.
[I 2026-05-19 14:05:53,713] Trial 161 finished with value: 0.9498522015432347 and parameters: {'n_estimators': 256, 'learning_rate': 0.04220552003838406, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 292, 'subsample': 0.833413137641622, 'colsample_bytree': 0.6443679478901728, 'reg_alpha': 0.6414940446096584, 'reg_lambda': 1.3433698091265943e-05}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  17%|█████████████████▊                                                                                         | 167/1000 [11:13<1:18:49,  5.68s/it]

[I 2026-05-19 14:06:04,999] Trial 166 finished with value: 0.9498600908096879 and parameters: {'n_estimators': 256, 'learning_rate': 0.04240469903962907, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 178, 'subsample': 0.7683784270788173, 'colsample_bytree': 0.6027221403112013, 'reg_alpha': 1.511663737170734, 'reg_lambda': 0.00046672272636451745}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  17%|█████████████████▉                                                                                         | 168/1000 [11:14<1:02:21,  4.50s/it]

[I 2026-05-19 14:06:06,739] Trial 165 finished with value: 0.9498513709842268 and parameters: {'n_estimators': 258, 'learning_rate': 0.04179786682323457, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 162, 'subsample': 0.7679200990165487, 'colsample_bytree': 0.6002419736547442, 'reg_alpha': 0.7374647700082818, 'reg_lambda': 0.00045065988998701243}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  17%|██████████████████▍                                                                                          | 169/1000 [11:15<47:32,  3.43s/it]

[I 2026-05-19 14:06:07,685] Trial 168 finished with value: 0.9498471144259323 and parameters: {'n_estimators': 227, 'learning_rate': 0.0499264108783708, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 143, 'subsample': 0.7661018311038776, 'colsample_bytree': 0.6429733820388718, 'reg_alpha': 0.06538941299184803, 'reg_lambda': 0.0004208022490332276}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  17%|██████████████████▌                                                                                          | 170/1000 [11:17<40:28,  2.93s/it]

[I 2026-05-19 14:06:09,413] Trial 169 finished with value: 0.949853357725571 and parameters: {'n_estimators': 258, 'learning_rate': 0.04999584562041663, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 177, 'subsample': 0.7643001692724992, 'colsample_bytree': 0.6363733634182394, 'reg_alpha': 1.3229369774282485, 'reg_lambda': 0.004910361040740133}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  17%|██████████████████▋                                                                                          | 171/1000 [11:18<30:36,  2.22s/it]

[I 2026-05-19 14:06:09,972] Trial 167 finished with value: 0.9498370058000912 and parameters: {'n_estimators': 259, 'learning_rate': 0.04774492191387622, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 166, 'subsample': 0.7444536867930578, 'colsample_bytree': 0.6434399046204292, 'reg_alpha': 0.07482470182048563, 'reg_lambda': 0.005279648312908009}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  17%|██████████████████▋                                                                                          | 172/1000 [11:22<41:49,  3.03s/it]

[I 2026-05-19 14:06:14,927] Trial 174 finished with value: 0.9497380068331299 and parameters: {'n_estimators': 257, 'learning_rate': 0.031163723879708498, 'max_depth': 1, 'num_leaves': 16, 'min_child_samples': 291, 'subsample': 0.9798296293093391, 'colsample_bytree': 0.6383182955275734, 'reg_alpha': 8.141547857993885, 'reg_lambda': 7.29318032162417e-05}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 155. Best value: 0.949868:  17%|██████████████████▌                                                                                        | 173/1000 [11:33<1:14:52,  5.43s/it]

[I 2026-05-19 14:06:25,951] Trial 171 finished with value: 0.9498549981223092 and parameters: {'n_estimators': 259, 'learning_rate': 0.03047712442810243, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 209, 'subsample': 0.7420656021154332, 'colsample_bytree': 0.6393544056959382, 'reg_alpha': 5.576316389619875, 'reg_lambda': 0.0004552582064476244}. Best is trial 155 with value: 0.9498680443602749.

Best trial: 172. Best value: 0.949875:  17%|██████████████████▌                                                                                        | 174/1000 [11:39<1:13:16,  5.32s/it]

[I 2026-05-19 14:06:31,027] Trial 172 finished with value: 0.9498753676200742 and parameters: {'n_estimators': 261, 'learning_rate': 0.043409831057139844, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 278, 'subsample': 0.997422250643965, 'colsample_bytree': 0.6383931352776453, 'reg_alpha': 6.148061479403091, 'reg_lambda': 0.0004492936861663783}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  18%|██████████████████▋                                                                                        | 175/1000 [11:44<1:15:23,  5.48s/it]

[I 2026-05-19 14:06:36,876] Trial 173 finished with value: 0.9498400853633298 and parameters: {'n_estimators': 256, 'learning_rate': 0.030807256687143, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 278, 'subsample': 0.7425847826471345, 'colsample_bytree': 0.6386531728212614, 'reg_alpha': 2.2348065674856256e-05, 'reg_lambda': 0.0024457367798006585}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  18%|██████████████████▊                                                                                        | 176/1000 [11:55<1:37:59,  7.14s/it]

[I 2026-05-19 14:06:47,857] Trial 175 finished with value: 0.9498469677705325 and parameters: {'n_estimators': 257, 'learning_rate': 0.047874826142457465, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 289, 'subsample': 0.7287062231685668, 'colsample_bytree': 0.6356968652788283, 'reg_alpha': 2.1043562040217764e-05, 'reg_lambda': 6.865080626233697e-05}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  18%|██████████████████▉                                                                                        | 177/1000 [11:57<1:15:02,  5.47s/it]

[I 2026-05-19 14:06:49,447] Trial 177 finished with value: 0.9498412823264075 and parameters: {'n_estimators': 254, 'learning_rate': 0.04739144560748245, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 279, 'subsample': 0.9821087820785994, 'colsample_bytree': 0.6089316414126008, 'reg_alpha': 0.0002986398211449567, 'reg_lambda': 1.000750094800019e-05}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  18%|███████████████████                                                                                        | 178/1000 [12:01<1:07:21,  4.92s/it]

[I 2026-05-19 14:06:53,076] Trial 176 finished with value: 0.9498533773824669 and parameters: {'n_estimators': 259, 'learning_rate': 0.03526028503216632, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 289, 'subsample': 0.7813039453464824, 'colsample_bytree': 0.6374926340272311, 'reg_alpha': 5.099053699349425, 'reg_lambda': 7.547434013611509e-05}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  18%|███████████████████▏                                                                                       | 179/1000 [12:12<1:32:36,  6.77s/it]

[I 2026-05-19 14:07:04,155] Trial 182 finished with value: 0.9498470252414796 and parameters: {'n_estimators': 255, 'learning_rate': 0.04733123473810354, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 288, 'subsample': 0.970888878132978, 'colsample_bytree': 0.6126295404190122, 'reg_alpha': 6.45474369771655e-05, 'reg_lambda': 0.05798368283840246}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  18%|███████████████████▎                                                                                       | 180/1000 [12:13<1:10:12,  5.14s/it]

[I 2026-05-19 14:07:05,509] Trial 178 finished with value: 0.949848189078146 and parameters: {'n_estimators': 255, 'learning_rate': 0.03494180277661008, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 279, 'subsample': 0.6085684469500116, 'colsample_bytree': 0.6012106546204672, 'reg_alpha': 2.1883159289501305e-05, 'reg_lambda': 0.9341276570568641}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  18%|███████████████████▊                                                                                         | 182/1000 [12:14<37:11,  2.73s/it]

[I 2026-05-19 14:07:06,258] Trial 179 finished with value: 0.9498590806844451 and parameters: {'n_estimators': 261, 'learning_rate': 0.03499912630340338, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 289, 'subsample': 0.8910835106395726, 'colsample_bytree': 0.6101670898818898, 'reg_alpha': 8.336462712524817, 'reg_lambda': 0.005582320107804958}. Best is trial 172 with value: 0.9498753676200742.
[I 2026-05-19 14:07:06,433] Trial 180 finished with value: 0.9498426677977599 and parameters: {'n_estimators': 260, 'learning_rate': 0.034326898358368906, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 300, 'subsample': 0.6645978925584324, 'colsample_bytree': 0.6098041732791388, 'reg_alpha': 2.7913968823842418e-05, 'reg_lambda': 1.4163475049559599e-05}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  18%|███████████████████▉                                                                                         | 183/1000 [12:14<27:55,  2.05s/it]

[I 2026-05-19 14:07:06,894] Trial 181 finished with value: 0.9498454554912158 and parameters: {'n_estimators': 255, 'learning_rate': 0.035394164224728616, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 288, 'subsample': 0.9982405776449266, 'colsample_bytree': 0.6379107728618686, 'reg_alpha': 0.00041910022269427626, 'reg_lambda': 0.06354782591322831}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  18%|████████████████████                                                                                         | 184/1000 [12:19<39:49,  2.93s/it]

[I 2026-05-19 14:07:11,871] Trial 183 finished with value: 0.9498513739236121 and parameters: {'n_estimators': 253, 'learning_rate': 0.04752017287882434, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 295, 'subsample': 0.6692515942353766, 'colsample_bytree': 0.6088602819440748, 'reg_alpha': 16.85767327385638, 'reg_lambda': 1.5891742595604895e-05}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  18%|███████████████████▊                                                                                       | 185/1000 [12:33<1:24:18,  6.21s/it]

[I 2026-05-19 14:07:25,742] Trial 184 finished with value: 0.9498156248662916 and parameters: {'n_estimators': 253, 'learning_rate': 0.017069974254806587, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 280, 'subsample': 0.7229151240221693, 'colsample_bytree': 0.6119238334555848, 'reg_alpha': 0.0004818646505113195, 'reg_lambda': 0.014762054269931133}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  19%|███████████████████▉                                                                                       | 186/1000 [12:40<1:26:40,  6.39s/it]

[I 2026-05-19 14:07:32,533] Trial 185 finished with value: 0.9498617704101395 and parameters: {'n_estimators': 263, 'learning_rate': 0.035437840832121655, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 280, 'subsample': 0.6249345247877593, 'colsample_bytree': 0.6052032335624191, 'reg_alpha': 5.110516865929989, 'reg_lambda': 0.10097956278921719}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  19%|████████████████████                                                                                       | 187/1000 [12:48<1:33:30,  6.90s/it]

[I 2026-05-19 14:07:40,640] Trial 186 finished with value: 0.9498480178207707 and parameters: {'n_estimators': 272, 'learning_rate': 0.03539203773971066, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 289, 'subsample': 0.6256616588686746, 'colsample_bytree': 0.6058817441661051, 'reg_alpha': 0.0001857034500803845, 'reg_lambda': 0.028457340673842056}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  19%|████████████████████                                                                                       | 188/1000 [12:57<1:41:38,  7.51s/it]

[I 2026-05-19 14:07:49,577] Trial 187 finished with value: 0.9498460401066835 and parameters: {'n_estimators': 272, 'learning_rate': 0.03474654948219399, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 297, 'subsample': 0.6262964682203522, 'colsample_bytree': 0.6106287180761979, 'reg_alpha': 0.44066697252127934, 'reg_lambda': 0.0015169907447058948}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  19%|████████████████████▏                                                                                      | 189/1000 [12:59<1:19:03,  5.85s/it]

[I 2026-05-19 14:07:51,553] Trial 188 finished with value: 0.9498468986574287 and parameters: {'n_estimators': 264, 'learning_rate': 0.03443707461950667, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 300, 'subsample': 0.8247366802792779, 'colsample_bytree': 0.6066160637650015, 'reg_alpha': 0.43842688970140475, 'reg_lambda': 0.001687165203300236}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  19%|████████████████████▎                                                                                      | 190/1000 [13:04<1:15:50,  5.62s/it]

[I 2026-05-19 14:07:56,635] Trial 189 finished with value: 0.9498645494266416 and parameters: {'n_estimators': 274, 'learning_rate': 0.03422807508915805, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 296, 'subsample': 0.6182965354907811, 'colsample_bytree': 0.6106735615255635, 'reg_alpha': 4.945418897907318, 'reg_lambda': 0.0012728251698758794}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  19%|████████████████████▍                                                                                      | 191/1000 [13:10<1:18:00,  5.79s/it]

[I 2026-05-19 14:08:02,806] Trial 193 finished with value: 0.9498703585268038 and parameters: {'n_estimators': 265, 'learning_rate': 0.03972252555331695, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 296, 'subsample': 0.8244867058844799, 'colsample_bytree': 0.6246979012788076, 'reg_alpha': 5.686120360436536, 'reg_lambda': 0.0016747046996539636}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  19%|████████████████████▌                                                                                      | 192/1000 [13:13<1:05:12,  4.84s/it]

[I 2026-05-19 14:08:05,444] Trial 194 finished with value: 0.9498668860075611 and parameters: {'n_estimators': 273, 'learning_rate': 0.03972858800908921, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 267, 'subsample': 0.6310238147727016, 'colsample_bytree': 0.6251449025425092, 'reg_alpha': 5.366174471030027, 'reg_lambda': 0.0012924900514677646}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  19%|█████████████████████                                                                                        | 193/1000 [13:14<48:13,  3.59s/it]

[I 2026-05-19 14:08:06,107] Trial 192 finished with value: 0.9498603749379978 and parameters: {'n_estimators': 271, 'learning_rate': 0.03261168883985514, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 297, 'subsample': 0.6565194441739045, 'colsample_bytree': 0.6240544233740946, 'reg_alpha': 5.050338794000798, 'reg_lambda': 0.021378114446633872}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  19%|█████████████████████▏                                                                                       | 194/1000 [13:14<35:54,  2.67s/it]

[I 2026-05-19 14:08:06,650] Trial 190 finished with value: 0.9498501984580401 and parameters: {'n_estimators': 272, 'learning_rate': 0.0351128777944637, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 268, 'subsample': 0.7792839532730386, 'colsample_bytree': 0.6249305624787154, 'reg_alpha': 0.4787311763596387, 'reg_lambda': 0.0013024654263681802}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  20%|█████████████████████▎                                                                                       | 195/1000 [13:18<41:17,  3.08s/it]

[I 2026-05-19 14:08:10,661] Trial 191 finished with value: 0.9498615991942042 and parameters: {'n_estimators': 271, 'learning_rate': 0.03468167883705734, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 295, 'subsample': 0.662101553476139, 'colsample_bytree': 0.6232656458753415, 'reg_alpha': 4.641315634145171, 'reg_lambda': 0.01619200132362455}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  20%|█████████████████████▎                                                                                       | 196/1000 [13:22<43:04,  3.21s/it]

[I 2026-05-19 14:08:14,186] Trial 195 finished with value: 0.9498619871027649 and parameters: {'n_estimators': 272, 'learning_rate': 0.034215785190451486, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 268, 'subsample': 0.8940355980211954, 'colsample_bytree': 0.6196620522187953, 'reg_alpha': 5.52420111353847, 'reg_lambda': 0.01861369517890349}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  20%|█████████████████████                                                                                      | 197/1000 [13:30<1:01:29,  4.59s/it]

[I 2026-05-19 14:08:22,010] Trial 196 finished with value: 0.9498696764839594 and parameters: {'n_estimators': 268, 'learning_rate': 0.039938569914606745, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 268, 'subsample': 0.6155769705379538, 'colsample_bytree': 0.6225684160740667, 'reg_alpha': 5.4150854624356795, 'reg_lambda': 0.0013357107918869138}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  20%|█████████████████████▏                                                                                     | 198/1000 [13:43<1:37:43,  7.31s/it]

[I 2026-05-19 14:08:35,662] Trial 197 finished with value: 0.9498609045598636 and parameters: {'n_estimators': 272, 'learning_rate': 0.03326818383122322, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 274, 'subsample': 0.6341495773017487, 'colsample_bytree': 0.6235479455839523, 'reg_alpha': 5.405423436678415, 'reg_lambda': 0.0014503268704697616}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  20%|█████████████████████▎                                                                                     | 199/1000 [13:48<1:26:56,  6.51s/it]

[I 2026-05-19 14:08:40,313] Trial 198 finished with value: 0.9498628403784967 and parameters: {'n_estimators': 242, 'learning_rate': 0.03924069514693895, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 274, 'subsample': 0.6137207481179862, 'colsample_bytree': 0.6248631790906904, 'reg_alpha': 5.078734744349482, 'reg_lambda': 0.0013325823430868555}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  20%|█████████████████████▍                                                                                     | 200/1000 [13:57<1:38:09,  7.36s/it]

[I 2026-05-19 14:08:49,659] Trial 199 finished with value: 0.9498567097110573 and parameters: {'n_estimators': 265, 'learning_rate': 0.03278341108264962, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 270, 'subsample': 0.8846580792263109, 'colsample_bytree': 0.6238404052589722, 'reg_alpha': 5.0242440803138795, 'reg_lambda': 0.01631355991654346}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  20%|█████████████████████▌                                                                                     | 201/1000 [13:58<1:11:16,  5.35s/it]

[I 2026-05-19 14:08:50,328] Trial 200 finished with value: 0.9498582125475743 and parameters: {'n_estimators': 265, 'learning_rate': 0.03270809788805089, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 271, 'subsample': 0.6217420782824236, 'colsample_bytree': 0.6239741220922761, 'reg_alpha': 4.402956927956249, 'reg_lambda': 0.0012528819817439877}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  20%|█████████████████████▌                                                                                     | 202/1000 [14:02<1:06:23,  4.99s/it]

[I 2026-05-19 14:08:54,474] Trial 201 finished with value: 0.9498659333691728 and parameters: {'n_estimators': 264, 'learning_rate': 0.03869820469384801, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 270, 'subsample': 0.6156006017817156, 'colsample_bytree': 0.6193577622890399, 'reg_alpha': 5.603952238288676, 'reg_lambda': 0.0012486469464576982}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  20%|█████████████████████▋                                                                                     | 203/1000 [14:10<1:19:29,  5.98s/it]

[I 2026-05-19 14:09:02,776] Trial 203 finished with value: 0.9498577334720016 and parameters: {'n_estimators': 267, 'learning_rate': 0.032232636193000916, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 267, 'subsample': 0.6190530148873694, 'colsample_bytree': 0.6242226847351275, 'reg_alpha': 5.131576912057172, 'reg_lambda': 0.0012256148274178448}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  20%|█████████████████████▊                                                                                     | 204/1000 [14:15<1:15:11,  5.67s/it]

[I 2026-05-19 14:09:07,701] Trial 204 finished with value: 0.9498563829647768 and parameters: {'n_estimators': 276, 'learning_rate': 0.032882151841763, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 266, 'subsample': 0.6208919379744829, 'colsample_bytree': 0.6232889778535297, 'reg_alpha': 5.250647773309318, 'reg_lambda': 0.005485209898997586}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  20%|██████████████████████▎                                                                                      | 205/1000 [14:16<54:15,  4.09s/it]

[I 2026-05-19 14:09:08,124] Trial 202 finished with value: 0.9498259868346434 and parameters: {'n_estimators': 264, 'learning_rate': 0.019059299555892584, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 267, 'subsample': 0.619483282055629, 'colsample_bytree': 0.6227320807400228, 'reg_alpha': 5.007611563688197, 'reg_lambda': 0.001995662294387656}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  21%|██████████████████████▍                                                                                      | 206/1000 [14:18<45:58,  3.47s/it]

[I 2026-05-19 14:09:10,148] Trial 205 finished with value: 0.9498503988911062 and parameters: {'n_estimators': 267, 'learning_rate': 0.029794717574963017, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 274, 'subsample': 0.6214380888001793, 'colsample_bytree': 0.6201215036316908, 'reg_alpha': 5.273378422289067, 'reg_lambda': 0.11286027074042662}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  21%|██████████████████████▌                                                                                      | 207/1000 [14:18<33:21,  2.52s/it]

[I 2026-05-19 14:09:10,438] Trial 206 finished with value: 0.9498580807723437 and parameters: {'n_estimators': 267, 'learning_rate': 0.03247576336681331, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 272, 'subsample': 0.6494553270199594, 'colsample_bytree': 0.6229532862395393, 'reg_alpha': 5.1667874253140775, 'reg_lambda': 0.1161910758109398}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  21%|██████████████████████▋                                                                                      | 208/1000 [14:27<57:30,  4.36s/it]

[I 2026-05-19 14:09:19,074] Trial 207 finished with value: 0.9498628872553277 and parameters: {'n_estimators': 285, 'learning_rate': 0.03221286414085476, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 267, 'subsample': 0.6381308255635338, 'colsample_bytree': 0.6234700187962875, 'reg_alpha': 5.286889599412681, 'reg_lambda': 0.0021051406289176165}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  21%|██████████████████████▎                                                                                    | 209/1000 [14:33<1:06:01,  5.01s/it]

[I 2026-05-19 14:09:25,604] Trial 208 finished with value: 0.9498540713878301 and parameters: {'n_estimators': 266, 'learning_rate': 0.03239386242513043, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 272, 'subsample': 0.6392309857162266, 'colsample_bytree': 0.6226141803061989, 'reg_alpha': 5.051495687826188, 'reg_lambda': 0.01677493845190021}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  21%|██████████████████████▍                                                                                    | 210/1000 [14:49<1:50:33,  8.40s/it]

[I 2026-05-19 14:09:41,913] Trial 209 finished with value: 0.9498563785627157 and parameters: {'n_estimators': 283, 'learning_rate': 0.03202943499702017, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 264, 'subsample': 0.6415640834300079, 'colsample_bytree': 0.6229968819548264, 'reg_alpha': 7.226091520046374, 'reg_lambda': 0.017365457366608834}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  21%|██████████████████████▌                                                                                    | 211/1000 [14:53<1:32:07,  7.01s/it]

[I 2026-05-19 14:09:45,685] Trial 210 finished with value: 0.949859141547541 and parameters: {'n_estimators': 284, 'learning_rate': 0.03285833448561739, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 264, 'subsample': 0.6440152249187753, 'colsample_bytree': 0.6225261816672341, 'reg_alpha': 7.1603679592748515, 'reg_lambda': 0.01824176733239894}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  21%|██████████████████████▋                                                                                    | 212/1000 [14:57<1:20:18,  6.11s/it]

[I 2026-05-19 14:09:49,717] Trial 211 finished with value: 0.9498581762834055 and parameters: {'n_estimators': 267, 'learning_rate': 0.032727122803608004, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 270, 'subsample': 0.6409527844403631, 'colsample_bytree': 0.6224954504386787, 'reg_alpha': 7.444596723028717, 'reg_lambda': 0.01620294987460946}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  21%|██████████████████████▊                                                                                    | 213/1000 [14:59<1:02:16,  4.75s/it]

[I 2026-05-19 14:09:51,238] Trial 212 finished with value: 0.9498611635901794 and parameters: {'n_estimators': 283, 'learning_rate': 0.031943699367113214, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 268, 'subsample': 0.648974721333439, 'colsample_bytree': 0.6234081407725768, 'reg_alpha': 7.141839813575714, 'reg_lambda': 0.02022818355122055}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  21%|██████████████████████▉                                                                                    | 214/1000 [15:05<1:05:55,  5.03s/it]

[I 2026-05-19 14:09:56,950] Trial 213 finished with value: 0.9498592523086977 and parameters: {'n_estimators': 284, 'learning_rate': 0.03246755620380755, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 265, 'subsample': 0.644028398866142, 'colsample_bytree': 0.6206355720369436, 'reg_alpha': 7.4240352327823, 'reg_lambda': 0.01872944406200667}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  22%|███████████████████████                                                                                    | 215/1000 [15:13<1:19:27,  6.07s/it]

[I 2026-05-19 14:10:05,465] Trial 214 finished with value: 0.9498610851271236 and parameters: {'n_estimators': 284, 'learning_rate': 0.03190339720684279, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 265, 'subsample': 0.6421393313839996, 'colsample_bytree': 0.6233532516720816, 'reg_alpha': 6.8252913842849745, 'reg_lambda': 0.13013459526843896}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  22%|███████████████████████                                                                                    | 216/1000 [15:18<1:15:52,  5.81s/it]

[I 2026-05-19 14:10:10,649] Trial 215 finished with value: 0.9498617370368262 and parameters: {'n_estimators': 283, 'learning_rate': 0.032310432043746264, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 263, 'subsample': 0.6346061197231008, 'colsample_bytree': 0.6231663846836387, 'reg_alpha': 7.675912513240357, 'reg_lambda': 0.0022808818453566933}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  22%|███████████████████████▏                                                                                   | 217/1000 [15:21<1:04:33,  4.95s/it]

[I 2026-05-19 14:10:13,604] Trial 216 finished with value: 0.9498628272893208 and parameters: {'n_estimators': 284, 'learning_rate': 0.032830509366691324, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 274, 'subsample': 0.6418871928856685, 'colsample_bytree': 0.621006240077248, 'reg_alpha': 7.433955657647247, 'reg_lambda': 0.002748413572898627}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  22%|███████████████████████▊                                                                                     | 218/1000 [15:22<47:09,  3.62s/it]

[I 2026-05-19 14:10:14,111] Trial 218 finished with value: 0.9498609899210825 and parameters: {'n_estimators': 286, 'learning_rate': 0.0328935385782274, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 275, 'subsample': 0.6377887086723876, 'colsample_bytree': 0.6135261999126269, 'reg_alpha': 7.1721399847907, 'reg_lambda': 0.10961003202310277}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  22%|███████████████████████▊                                                                                     | 219/1000 [15:23<39:43,  3.05s/it]

[I 2026-05-19 14:10:15,852] Trial 217 finished with value: 0.9498571786812546 and parameters: {'n_estimators': 282, 'learning_rate': 0.03225876487744713, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 265, 'subsample': 0.6025426310893824, 'colsample_bytree': 0.6135745563684862, 'reg_alpha': 7.681736908565132, 'reg_lambda': 0.0193705382605801}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  22%|███████████████████████▉                                                                                     | 220/1000 [15:31<57:39,  4.44s/it]

[I 2026-05-19 14:10:23,510] Trial 219 finished with value: 0.9498552652042636 and parameters: {'n_estimators': 284, 'learning_rate': 0.02869396299001456, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 262, 'subsample': 0.6384025331781679, 'colsample_bytree': 0.6005763158701685, 'reg_alpha': 8.164081673841476, 'reg_lambda': 0.0025653276673744726}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  22%|███████████████████████▋                                                                                   | 221/1000 [15:39<1:10:51,  5.46s/it]

[I 2026-05-19 14:10:31,355] Trial 220 finished with value: 0.9498719575617605 and parameters: {'n_estimators': 281, 'learning_rate': 0.038342590195361896, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 283, 'subsample': 0.6008005751219491, 'colsample_bytree': 0.6006075101728928, 'reg_alpha': 7.606423617918437, 'reg_lambda': 0.0026100224300318305}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  22%|███████████████████████▊                                                                                   | 222/1000 [15:53<1:42:27,  7.90s/it]

[I 2026-05-19 14:10:44,960] Trial 221 finished with value: 0.9498671717327248 and parameters: {'n_estimators': 286, 'learning_rate': 0.038351903108577626, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 283, 'subsample': 0.6009036615927772, 'colsample_bytree': 0.614144921628646, 'reg_alpha': 8.25619522784573, 'reg_lambda': 0.0023803911958608}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  22%|███████████████████████▊                                                                                   | 223/1000 [15:59<1:37:55,  7.56s/it]

[I 2026-05-19 14:10:51,728] Trial 224 finished with value: 0.9498593053240671 and parameters: {'n_estimators': 288, 'learning_rate': 0.029037608991595583, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 282, 'subsample': 0.6002379551730291, 'colsample_bytree': 0.6034561877681069, 'reg_alpha': 7.724390333270345, 'reg_lambda': 0.0026479633311439314}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  22%|███████████████████████▉                                                                                   | 224/1000 [16:00<1:09:29,  5.37s/it]

[I 2026-05-19 14:10:52,000] Trial 222 finished with value: 0.9498561063948288 and parameters: {'n_estimators': 287, 'learning_rate': 0.028558669878929115, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 283, 'subsample': 0.6363891135025381, 'colsample_bytree': 0.6133891319759129, 'reg_alpha': 7.847778180208363, 'reg_lambda': 0.0028261556890711056}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  22%|████████████████████████▌                                                                                    | 225/1000 [16:01<52:38,  4.08s/it]

[I 2026-05-19 14:10:53,050] Trial 223 finished with value: 0.9498704429507875 and parameters: {'n_estimators': 287, 'learning_rate': 0.0378975602098075, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 283, 'subsample': 0.6309217987499754, 'colsample_bytree': 0.6130054571195087, 'reg_alpha': 3.134092510147392, 'reg_lambda': 0.0024705681634856853}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  23%|████████████████████████▏                                                                                  | 226/1000 [16:07<1:02:13,  4.82s/it]

[I 2026-05-19 14:10:59,608] Trial 225 finished with value: 0.9498708719418145 and parameters: {'n_estimators': 291, 'learning_rate': 0.03836923268723451, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 282, 'subsample': 0.6530861468162716, 'colsample_bytree': 0.6136484144953548, 'reg_alpha': 8.475144211408319, 'reg_lambda': 0.023382982815394675}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  23%|████████████████████████▎                                                                                  | 227/1000 [16:20<1:32:46,  7.20s/it]

[I 2026-05-19 14:11:12,354] Trial 226 finished with value: 0.9498514935703266 and parameters: {'n_estimators': 293, 'learning_rate': 0.02883230337965838, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 261, 'subsample': 0.6018832097996397, 'colsample_bytree': 0.6150703266482995, 'reg_alpha': 3.4185269914620235, 'reg_lambda': 0.02597097390602343}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  23%|████████████████████████▍                                                                                  | 228/1000 [16:22<1:11:23,  5.55s/it]

[I 2026-05-19 14:11:14,048] Trial 229 finished with value: 0.9498575602852387 and parameters: {'n_estimators': 290, 'learning_rate': 0.029333536218681504, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 260, 'subsample': 0.6318262796363402, 'colsample_bytree': 0.6312920326734851, 'reg_alpha': 8.423130096545652, 'reg_lambda': 0.039126661363929165}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  23%|████████████████████████▌                                                                                  | 229/1000 [16:28<1:16:20,  5.94s/it]

[I 2026-05-19 14:11:20,917] Trial 230 finished with value: 0.9498532974985807 and parameters: {'n_estimators': 289, 'learning_rate': 0.02868725171846682, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 278, 'subsample': 0.6347615863391963, 'colsample_bytree': 0.6312718838085465, 'reg_alpha': 2.960143408974671, 'reg_lambda': 0.0024316839811006343}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  23%|█████████████████████████                                                                                    | 230/1000 [16:29<54:13,  4.23s/it]

[I 2026-05-19 14:11:21,130] Trial 228 finished with value: 0.9498590395695649 and parameters: {'n_estimators': 291, 'learning_rate': 0.029191664625323792, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 261, 'subsample': 0.6328234199767456, 'colsample_bytree': 0.6144331456318387, 'reg_alpha': 3.1453609380310104, 'reg_lambda': 0.1619123703671815}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  23%|█████████████████████████▏                                                                                   | 231/1000 [16:29<39:28,  3.08s/it]

[I 2026-05-19 14:11:21,533] Trial 227 finished with value: 0.9498526890383969 and parameters: {'n_estimators': 292, 'learning_rate': 0.028476014165156147, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 261, 'subsample': 0.6022996921357437, 'colsample_bytree': 0.631982031336854, 'reg_alpha': 3.0956321669366336, 'reg_lambda': 0.023942461624087877}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  23%|█████████████████████████▎                                                                                   | 232/1000 [16:37<57:13,  4.47s/it]

[I 2026-05-19 14:11:29,220] Trial 231 finished with value: 0.9498512173353865 and parameters: {'n_estimators': 292, 'learning_rate': 0.02942721852871651, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 281, 'subsample': 0.6335488768536763, 'colsample_bytree': 0.6327129203007025, 'reg_alpha': 3.4520141806082982, 'reg_lambda': 0.03689005245542006}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  23%|█████████████████████████▍                                                                                   | 233/1000 [16:42<59:17,  4.64s/it]

[I 2026-05-19 14:11:34,288] Trial 232 finished with value: 0.9498536576410201 and parameters: {'n_estimators': 277, 'learning_rate': 0.02989521737997873, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 277, 'subsample': 0.6567777759448266, 'colsample_bytree': 0.6311724048093031, 'reg_alpha': 3.1307886174495745, 'reg_lambda': 0.2855915074229882}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  23%|█████████████████████████                                                                                  | 234/1000 [16:54<1:29:51,  7.04s/it]

[I 2026-05-19 14:11:46,922] Trial 233 finished with value: 0.9498748187135824 and parameters: {'n_estimators': 290, 'learning_rate': 0.03814327489978068, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 282, 'subsample': 0.6329440577890272, 'colsample_bytree': 0.6125815389444795, 'reg_alpha': 3.1383007483860887, 'reg_lambda': 0.041622374504476915}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  24%|█████████████████████████▏                                                                                 | 235/1000 [17:00<1:25:26,  6.70s/it]

[I 2026-05-19 14:11:52,830] Trial 236 finished with value: 0.9498609789954482 and parameters: {'n_estimators': 274, 'learning_rate': 0.03787519841450967, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 278, 'subsample': 0.6317355104414855, 'colsample_bytree': 0.632023883964247, 'reg_alpha': 3.4042404463294016, 'reg_lambda': 0.2707381337698895}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  24%|█████████████████████████▎                                                                                 | 236/1000 [17:01<1:01:35,  4.84s/it]

[I 2026-05-19 14:11:53,325] Trial 234 finished with value: 0.9498661870433498 and parameters: {'n_estimators': 293, 'learning_rate': 0.038582134943254486, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 278, 'subsample': 0.6325178199616448, 'colsample_bytree': 0.6138301891694063, 'reg_alpha': 3.491555120439188, 'reg_lambda': 0.28635839511279626}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  24%|█████████████████████████▊                                                                                   | 237/1000 [17:04<56:46,  4.46s/it]

[I 2026-05-19 14:11:56,871] Trial 235 finished with value: 0.9498680040189704 and parameters: {'n_estimators': 293, 'learning_rate': 0.037875568787967086, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 277, 'subsample': 0.6301643003510937, 'colsample_bytree': 0.6298284471562715, 'reg_alpha': 2.996420795250411, 'reg_lambda': 0.04259827175533706}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  24%|█████████████████████████▍                                                                                 | 238/1000 [17:12<1:07:40,  5.33s/it]

[I 2026-05-19 14:12:04,275] Trial 237 finished with value: 0.9498702223702804 and parameters: {'n_estimators': 291, 'learning_rate': 0.038259281218088956, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 276, 'subsample': 0.6324281333532792, 'colsample_bytree': 0.6320585523749579, 'reg_alpha': 3.1340809224067745, 'reg_lambda': 0.1781297393502182}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  24%|█████████████████████████▌                                                                                 | 239/1000 [17:22<1:27:06,  6.87s/it]

[I 2026-05-19 14:12:14,714] Trial 238 finished with value: 0.9498646785540723 and parameters: {'n_estimators': 293, 'learning_rate': 0.03785072729517487, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 277, 'subsample': 0.6325212791905964, 'colsample_bytree': 0.6329992224724816, 'reg_alpha': 3.069306096933769, 'reg_lambda': 0.04181830839359256}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  24%|█████████████████████████▋                                                                                 | 240/1000 [17:24<1:08:12,  5.39s/it]

[I 2026-05-19 14:12:16,652] Trial 239 finished with value: 0.9498654728179071 and parameters: {'n_estimators': 298, 'learning_rate': 0.038040656381934754, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 277, 'subsample': 0.611446863935384, 'colsample_bytree': 0.633168128131492, 'reg_alpha': 3.254012261169041, 'reg_lambda': 0.0038961852015394626}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  24%|██████████████████████████▎                                                                                  | 241/1000 [17:27<59:33,  4.71s/it]

[I 2026-05-19 14:12:19,770] Trial 240 finished with value: 0.9498590652405149 and parameters: {'n_estimators': 278, 'learning_rate': 0.03777858087639756, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 278, 'subsample': 0.6097005488889736, 'colsample_bytree': 0.6143239732525347, 'reg_alpha': 16.392122105935403, 'reg_lambda': 0.003668755475762538}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  24%|██████████████████████████▍                                                                                  | 242/1000 [17:30<51:53,  4.11s/it]

[I 2026-05-19 14:12:22,485] Trial 241 finished with value: 0.949863931410756 and parameters: {'n_estimators': 277, 'learning_rate': 0.037803150941200445, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 276, 'subsample': 0.6112969852024165, 'colsample_bytree': 0.6111621669615339, 'reg_alpha': 10.177603163353721, 'reg_lambda': 0.001785319711275409}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  24%|██████████████████████████▍                                                                                  | 243/1000 [17:31<41:45,  3.31s/it]

[I 2026-05-19 14:12:23,947] Trial 242 finished with value: 0.9498635534814982 and parameters: {'n_estimators': 279, 'learning_rate': 0.03826233794605821, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 276, 'subsample': 0.6600909441904804, 'colsample_bytree': 0.6139694820616072, 'reg_alpha': 4.021175214379548, 'reg_lambda': 0.0468966223105874}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  24%|██████████████████████████▌                                                                                  | 244/1000 [17:38<54:05,  4.29s/it]

[I 2026-05-19 14:12:30,515] Trial 243 finished with value: 0.9498602877702964 and parameters: {'n_estimators': 276, 'learning_rate': 0.03661563879648865, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 275, 'subsample': 0.6560901868398313, 'colsample_bytree': 0.6112537053582652, 'reg_alpha': 9.864137516370729, 'reg_lambda': 0.3493399446348621}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  24%|██████████████████████████▋                                                                                  | 245/1000 [17:42<53:29,  4.25s/it]

[I 2026-05-19 14:12:34,664] Trial 244 finished with value: 0.9498672479607672 and parameters: {'n_estimators': 277, 'learning_rate': 0.03913127004869353, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 276, 'subsample': 0.6114209833803517, 'colsample_bytree': 0.613592732231811, 'reg_alpha': 10.206221852309824, 'reg_lambda': 0.0019763136169652046}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  25%|██████████████████████████▎                                                                                | 246/1000 [17:53<1:19:38,  6.34s/it]

[I 2026-05-19 14:12:45,877] Trial 245 finished with value: 0.9498630874002814 and parameters: {'n_estimators': 276, 'learning_rate': 0.03877492838915527, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 276, 'subsample': 0.6492286068104792, 'colsample_bytree': 0.614092150670074, 'reg_alpha': 10.380579647099623, 'reg_lambda': 0.0038883358308818413}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  25%|██████████████████████████▍                                                                                | 247/1000 [18:01<1:23:42,  6.67s/it]

[I 2026-05-19 14:12:53,319] Trial 247 finished with value: 0.94986646690235 and parameters: {'n_estimators': 300, 'learning_rate': 0.03843915497031222, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 283, 'subsample': 0.6134739234415129, 'colsample_bytree': 0.6142150187344017, 'reg_alpha': 10.46042145061615, 'reg_lambda': 0.48155003682614983}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  25%|██████████████████████████▌                                                                                | 248/1000 [18:03<1:05:21,  5.22s/it]

[I 2026-05-19 14:12:55,153] Trial 246 finished with value: 0.949857843140793 and parameters: {'n_estimators': 300, 'learning_rate': 0.03759514168110019, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 285, 'subsample': 0.6103796978508339, 'colsample_bytree': 0.6119450094448835, 'reg_alpha': 16.17755773125625, 'reg_lambda': 0.003922232679480912}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  25%|██████████████████████████▋                                                                                | 249/1000 [18:10<1:12:34,  5.80s/it]

[I 2026-05-19 14:13:02,302] Trial 248 finished with value: 0.9498630128062695 and parameters: {'n_estimators': 299, 'learning_rate': 0.03818378394962185, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 285, 'subsample': 0.6114936386608361, 'colsample_bytree': 0.615249034532015, 'reg_alpha': 10.58183839022094, 'reg_lambda': 0.05268231425415291}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  25%|██████████████████████████▊                                                                                | 250/1000 [18:15<1:08:41,  5.49s/it]

[I 2026-05-19 14:13:07,091] Trial 249 finished with value: 0.9498676346779742 and parameters: {'n_estimators': 300, 'learning_rate': 0.03842833385740356, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 284, 'subsample': 0.6073165384463323, 'colsample_bytree': 0.6101058628254314, 'reg_alpha': 11.302514742286549, 'reg_lambda': 0.08191111485364926}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  25%|██████████████████████████▊                                                                                | 251/1000 [18:25<1:26:33,  6.93s/it]

[I 2026-05-19 14:13:17,382] Trial 250 finished with value: 0.9498629991519758 and parameters: {'n_estimators': 296, 'learning_rate': 0.03830823390125094, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 284, 'subsample': 0.6126861577886275, 'colsample_bytree': 0.6130686838619098, 'reg_alpha': 10.372389525164683, 'reg_lambda': 0.003783625735595585}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  25%|██████████████████████████▉                                                                                | 252/1000 [18:28<1:10:17,  5.64s/it]

[I 2026-05-19 14:13:19,998] Trial 251 finished with value: 0.9498633283374476 and parameters: {'n_estimators': 296, 'learning_rate': 0.03917562439023353, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 284, 'subsample': 0.6096935567091165, 'colsample_bytree': 0.6115782787341811, 'reg_alpha': 2.2811164142531983, 'reg_lambda': 0.391926871190772}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  25%|███████████████████████████                                                                                | 253/1000 [18:32<1:04:18,  5.17s/it]

[I 2026-05-19 14:13:24,059] Trial 255 finished with value: 0.9498566814751458 and parameters: {'n_estimators': 294, 'learning_rate': 0.03907144413575302, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 285, 'subsample': 0.6137477545988229, 'colsample_bytree': 0.6005788391902716, 'reg_alpha': 2.3251929226565076, 'reg_lambda': 0.05029847493837437}. Best is trial 172 with value: 0.9498753676200742.
[I 2026-05-19 14:13:24,098] Trial 252 finished with value: 0.9498665448828023 and parameters: {'n_estimators': 294, 'learning_rate': 0.03849995867903309, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 284, 'subsample': 0.6115034950047417, 'colsample_bytree': 0.6118058527564771, 'reg_alpha': 2.3069173339496385, 'reg_lambda': 0.05547885907374767}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  26%|███████████████████████████▊                                                                                 | 255/1000 [18:35<44:28,  3.58s/it]

[I 2026-05-19 14:13:27,526] Trial 253 finished with value: 0.9498627978365844 and parameters: {'n_estimators': 300, 'learning_rate': 0.03901402469419798, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 285, 'subsample': 0.6129587389569894, 'colsample_bytree': 0.6089176014761548, 'reg_alpha': 11.740442819167598, 'reg_lambda': 0.0019328691667180452}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  26%|███████████████████████████▉                                                                                 | 256/1000 [18:37<39:38,  3.20s/it]

[I 2026-05-19 14:13:29,552] Trial 254 finished with value: 0.949868565902508 and parameters: {'n_estimators': 298, 'learning_rate': 0.03942187753679693, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 284, 'subsample': 0.6142186189343549, 'colsample_bytree': 0.6085527280836311, 'reg_alpha': 2.3798171699787116, 'reg_lambda': 0.047757342677840146}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  26%|███████████████████████████▍                                                                               | 257/1000 [18:48<1:06:07,  5.34s/it]

[I 2026-05-19 14:13:40,957] Trial 256 finished with value: 0.9498697182756471 and parameters: {'n_estimators': 300, 'learning_rate': 0.03904619061283762, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 283, 'subsample': 0.6114907555266257, 'colsample_bytree': 0.6123160560958607, 'reg_alpha': 2.449646712712703, 'reg_lambda': 0.0017597029837152897}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  26%|███████████████████████████▌                                                                               | 258/1000 [18:59<1:24:30,  6.83s/it]

[I 2026-05-19 14:13:51,786] Trial 257 finished with value: 0.949864372968291 and parameters: {'n_estimators': 297, 'learning_rate': 0.03891778464045056, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 286, 'subsample': 0.6157472871215756, 'colsample_bytree': 0.6113465460190823, 'reg_alpha': 2.4559824283800316, 'reg_lambda': 0.5132503369399132}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  26%|███████████████████████████▋                                                                               | 259/1000 [19:04<1:17:18,  6.26s/it]

[I 2026-05-19 14:13:56,555] Trial 259 finished with value: 0.9498691432258429 and parameters: {'n_estimators': 298, 'learning_rate': 0.0391329890219609, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 283, 'subsample': 0.6157202095321281, 'colsample_bytree': 0.6001811206084139, 'reg_alpha': 10.648702132347516, 'reg_lambda': 0.8474921875309928}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  26%|███████████████████████████▊                                                                               | 260/1000 [19:08<1:07:58,  5.51s/it]

[I 2026-05-19 14:14:00,196] Trial 258 finished with value: 0.9498698011842766 and parameters: {'n_estimators': 299, 'learning_rate': 0.03909047527141257, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 285, 'subsample': 0.6128149333672259, 'colsample_bytree': 0.6099105372378506, 'reg_alpha': 2.4584083857302996, 'reg_lambda': 0.7296510216783534}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  26%|███████████████████████████▉                                                                               | 261/1000 [19:12<1:02:37,  5.08s/it]

[I 2026-05-19 14:14:04,233] Trial 263 finished with value: 0.9498467094534184 and parameters: {'n_estimators': 297, 'learning_rate': 0.039644528739163215, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 284, 'subsample': 0.6143149835224961, 'colsample_bytree': 0.6060540766721825, 'reg_alpha': 2.7101600675784603, 'reg_lambda': 0.9556051348004948}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  26%|████████████████████████████                                                                               | 262/1000 [19:17<1:02:08,  5.05s/it]

[I 2026-05-19 14:14:09,216] Trial 260 finished with value: 0.9498650553621697 and parameters: {'n_estimators': 297, 'learning_rate': 0.039468999384486406, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 284, 'subsample': 0.6147610636266312, 'colsample_bytree': 0.6085265405074292, 'reg_alpha': 11.867939219824493, 'reg_lambda': 0.04570020306893019}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  26%|████████████████████████████▋                                                                                | 263/1000 [19:21<59:12,  4.82s/it]

[I 2026-05-19 14:14:13,480] Trial 261 finished with value: 0.9498706244657257 and parameters: {'n_estimators': 297, 'learning_rate': 0.04009147678590376, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 285, 'subsample': 0.6126831958602205, 'colsample_bytree': 0.6093287480830758, 'reg_alpha': 12.031566603459636, 'reg_lambda': 0.5557966995317678}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  26%|████████████████████████████▏                                                                              | 264/1000 [19:30<1:15:16,  6.14s/it]

[I 2026-05-19 14:14:22,682] Trial 262 finished with value: 0.94986464186067 and parameters: {'n_estimators': 299, 'learning_rate': 0.03948326681291776, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 286, 'subsample': 0.6164217772067894, 'colsample_bytree': 0.6016294379528131, 'reg_alpha': 13.693957288192632, 'reg_lambda': 0.5887419121578918}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  26%|████████████████████████████▎                                                                              | 265/1000 [19:36<1:14:00,  6.04s/it]

[I 2026-05-19 14:14:28,542] Trial 266 finished with value: 0.9498647746559049 and parameters: {'n_estimators': 296, 'learning_rate': 0.04014191862899683, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 282, 'subsample': 0.6970656665469182, 'colsample_bytree': 0.6019858945777985, 'reg_alpha': 2.225408542009538, 'reg_lambda': 0.45020993316986724}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  27%|████████████████████████████▉                                                                                | 266/1000 [19:37<55:12,  4.51s/it]

[I 2026-05-19 14:14:29,465] Trial 264 finished with value: 0.9498620687814595 and parameters: {'n_estimators': 295, 'learning_rate': 0.039813505161320595, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 284, 'subsample': 0.6071970489542904, 'colsample_bytree': 0.6087822051234789, 'reg_alpha': 14.963095901914748, 'reg_lambda': 0.5033547786763373}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  27%|█████████████████████████████                                                                                | 267/1000 [19:38<40:26,  3.31s/it]

[I 2026-05-19 14:14:29,955] Trial 265 finished with value: 0.9498656198594781 and parameters: {'n_estimators': 297, 'learning_rate': 0.04010201430211164, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 284, 'subsample': 0.6080098454395925, 'colsample_bytree': 0.6071307196366249, 'reg_alpha': 2.707418850656422, 'reg_lambda': 0.5115348858322248}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  27%|█████████████████████████████▏                                                                               | 268/1000 [19:44<50:20,  4.13s/it]

[I 2026-05-19 14:14:36,003] Trial 267 finished with value: 0.9498641155561577 and parameters: {'n_estimators': 294, 'learning_rate': 0.0403588080076186, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 292, 'subsample': 0.6185253973202419, 'colsample_bytree': 0.601658915693375, 'reg_alpha': 2.500528558245211, 'reg_lambda': 0.06399085001095477}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  27%|█████████████████████████████▎                                                                               | 269/1000 [19:50<57:40,  4.73s/it]

[I 2026-05-19 14:14:42,151] Trial 268 finished with value: 0.9498609249531601 and parameters: {'n_estimators': 296, 'learning_rate': 0.04052412711069734, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 282, 'subsample': 0.6042359744658746, 'colsample_bytree': 0.6011901847865003, 'reg_alpha': 2.3843251435174997, 'reg_lambda': 0.07772770390484429}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  27%|████████████████████████████▉                                                                              | 270/1000 [20:03<1:29:59,  7.40s/it]

[I 2026-05-19 14:14:55,790] Trial 269 finished with value: 0.949866788200799 and parameters: {'n_estimators': 292, 'learning_rate': 0.04032691562958406, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 293, 'subsample': 0.6258365466286147, 'colsample_bytree': 0.6011801121577871, 'reg_alpha': 1.9854379700813385, 'reg_lambda': 0.949879536347721}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  27%|████████████████████████████▉                                                                              | 271/1000 [20:06<1:13:25,  6.04s/it]

[I 2026-05-19 14:14:58,640] Trial 270 finished with value: 0.9498661353675747 and parameters: {'n_estimators': 294, 'learning_rate': 0.039871366973737506, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 293, 'subsample': 0.6228347891123591, 'colsample_bytree': 0.6003813666444334, 'reg_alpha': 2.5242019638738094, 'reg_lambda': 0.17535677246420353}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  27%|█████████████████████████████                                                                              | 272/1000 [20:12<1:13:19,  6.04s/it]

[I 2026-05-19 14:15:04,702] Trial 271 finished with value: 0.9498632018441647 and parameters: {'n_estimators': 300, 'learning_rate': 0.040470902574146206, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 281, 'subsample': 0.7019605838775026, 'colsample_bytree': 0.6057008041536587, 'reg_alpha': 2.5904492025082644, 'reg_lambda': 0.586131164704972}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  27%|█████████████████████████████▊                                                                               | 273/1000 [20:14<57:14,  4.72s/it]

[I 2026-05-19 14:15:06,350] Trial 272 finished with value: 0.9498674341768283 and parameters: {'n_estimators': 300, 'learning_rate': 0.04091612905124244, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 292, 'subsample': 0.6046280335777169, 'colsample_bytree': 0.6000946522454143, 'reg_alpha': 1.7047604798620457, 'reg_lambda': 0.07641819584525794}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  27%|█████████████████████████████▎                                                                             | 274/1000 [20:22<1:09:53,  5.78s/it]

[I 2026-05-19 14:15:14,572] Trial 273 finished with value: 0.949858156294052 and parameters: {'n_estimators': 299, 'learning_rate': 0.04145850045929273, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 293, 'subsample': 0.6035035472920851, 'colsample_bytree': 0.6027448792344727, 'reg_alpha': 16.362628112968086, 'reg_lambda': 0.6763728906218476}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  28%|█████████████████████████████▍                                                                             | 275/1000 [20:27<1:05:34,  5.43s/it]

[I 2026-05-19 14:15:19,180] Trial 274 finished with value: 0.9498628170708937 and parameters: {'n_estimators': 300, 'learning_rate': 0.04093200988389883, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 292, 'subsample': 0.6039615437275451, 'colsample_bytree': 0.6055326834078434, 'reg_alpha': 1.866197539371768, 'reg_lambda': 0.5252323990934586}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  28%|██████████████████████████████                                                                               | 276/1000 [20:31<59:38,  4.94s/it]

[I 2026-05-19 14:15:23,001] Trial 275 finished with value: 0.9498592440001541 and parameters: {'n_estimators': 290, 'learning_rate': 0.04106090203656359, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 292, 'subsample': 0.7034820471891856, 'colsample_bytree': 0.6005262062132666, 'reg_alpha': 16.808736107863712, 'reg_lambda': 0.6597595372688532}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  28%|█████████████████████████████▋                                                                             | 277/1000 [20:37<1:04:43,  5.37s/it]

[I 2026-05-19 14:15:29,382] Trial 276 finished with value: 0.9498558538290454 and parameters: {'n_estimators': 290, 'learning_rate': 0.04098118947822941, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 292, 'subsample': 0.6047060982446679, 'colsample_bytree': 0.6007562225054766, 'reg_alpha': 17.36933923634651, 'reg_lambda': 0.8015744887199546}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  28%|█████████████████████████████▋                                                                             | 278/1000 [20:41<1:01:43,  5.13s/it]

[I 2026-05-19 14:15:33,936] Trial 277 finished with value: 0.9498646369322146 and parameters: {'n_estimators': 291, 'learning_rate': 0.04084843724634354, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 293, 'subsample': 0.6252451118526687, 'colsample_bytree': 0.6005591565163079, 'reg_alpha': 1.522245246681004, 'reg_lambda': 1.5369590450468056}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  28%|██████████████████████████████▍                                                                              | 279/1000 [20:42<45:07,  3.76s/it]

[I 2026-05-19 14:15:34,498] Trial 278 finished with value: 0.949862619043242 and parameters: {'n_estimators': 290, 'learning_rate': 0.04101340813281957, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 294, 'subsample': 0.625513091145488, 'colsample_bytree': 0.6013507157994643, 'reg_alpha': 1.4677500209100298, 'reg_lambda': 2.047975474639476}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  28%|█████████████████████████████▉                                                                             | 280/1000 [20:50<1:00:26,  5.04s/it]

[I 2026-05-19 14:15:42,515] Trial 279 finished with value: 0.9498582841192276 and parameters: {'n_estimators': 290, 'learning_rate': 0.036220228898572876, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 116, 'subsample': 0.6264606343959184, 'colsample_bytree': 0.6018672197970618, 'reg_alpha': 1.668540324019862, 'reg_lambda': 0.7161355016721124}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  28%|██████████████████████████████▋                                                                              | 281/1000 [20:54<54:37,  4.56s/it]

[I 2026-05-19 14:15:45,906] Trial 280 finished with value: 0.9498643678721667 and parameters: {'n_estimators': 289, 'learning_rate': 0.03573329320668821, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 292, 'subsample': 0.6258235634025298, 'colsample_bytree': 0.6001383405947655, 'reg_alpha': 3.6316832962168424, 'reg_lambda': 2.5094049249448127}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  28%|██████████████████████████████▏                                                                            | 282/1000 [21:07<1:25:20,  7.13s/it]

[I 2026-05-19 14:15:59,104] Trial 281 finished with value: 0.9498586400599928 and parameters: {'n_estimators': 291, 'learning_rate': 0.03658825968591834, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 293, 'subsample': 0.6250568381140789, 'colsample_bytree': 0.6016825360378011, 'reg_alpha': 1.3807257265066522, 'reg_lambda': 0.697083251408827}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  28%|██████████████████████████████▎                                                                            | 283/1000 [21:09<1:09:01,  5.78s/it]

[I 2026-05-19 14:16:01,712] Trial 282 finished with value: 0.9498623397907092 and parameters: {'n_estimators': 289, 'learning_rate': 0.036069961471961176, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 291, 'subsample': 0.6227786939880997, 'colsample_bytree': 0.6012153765538806, 'reg_alpha': 1.3462738657856004, 'reg_lambda': 2.5325142345170057}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  28%|██████████████████████████████▍                                                                            | 284/1000 [21:16<1:13:14,  6.14s/it]

[I 2026-05-19 14:16:08,665] Trial 283 finished with value: 0.9498670094912113 and parameters: {'n_estimators': 288, 'learning_rate': 0.03611093176716749, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 293, 'subsample': 0.6265546071717983, 'colsample_bytree': 0.6016269377564907, 'reg_alpha': 1.7895613573311928, 'reg_lambda': 2.324672024538557}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  28%|██████████████████████████████▍                                                                            | 285/1000 [21:19<1:00:17,  5.06s/it]

[I 2026-05-19 14:16:11,233] Trial 284 finished with value: 0.949862011022795 and parameters: {'n_estimators': 290, 'learning_rate': 0.0364717251595411, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 295, 'subsample': 0.62592820938883, 'colsample_bytree': 0.600268622831294, 'reg_alpha': 1.4990341697309062, 'reg_lambda': 0.08197575637009245}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  29%|███████████████████████████████▏                                                                             | 286/1000 [21:23<56:21,  4.74s/it]

[I 2026-05-19 14:16:15,193] Trial 293 finished with value: 0.9497294386479693 and parameters: {'n_estimators': 55, 'learning_rate': 0.043769315832841896, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 288, 'subsample': 0.6009121875355079, 'colsample_bytree': 0.61720458892371, 'reg_alpha': 9.561101958965061, 'reg_lambda': 1.4346918177069883}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  29%|██████████████████████████████▋                                                                            | 287/1000 [21:29<1:00:51,  5.12s/it]

[I 2026-05-19 14:16:21,237] Trial 285 finished with value: 0.9498666486520448 and parameters: {'n_estimators': 290, 'learning_rate': 0.03621865765373257, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 292, 'subsample': 0.6268004290044258, 'colsample_bytree': 0.600279860899179, 'reg_alpha': 1.5152565222137064, 'reg_lambda': 1.6396584411684403}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  29%|███████████████████████████████▍                                                                             | 288/1000 [21:29<44:09,  3.72s/it]

[I 2026-05-19 14:16:21,689] Trial 286 finished with value: 0.949860970720492 and parameters: {'n_estimators': 289, 'learning_rate': 0.036003169716461954, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 299, 'subsample': 0.6282743162862552, 'colsample_bytree': 0.6162134015720111, 'reg_alpha': 1.6892439505177297, 'reg_lambda': 1.5629589410534295}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  29%|███████████████████████████████▌                                                                             | 289/1000 [21:30<34:00,  2.87s/it]

[I 2026-05-19 14:16:22,571] Trial 287 finished with value: 0.9498639475471761 and parameters: {'n_estimators': 290, 'learning_rate': 0.043789894562762825, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 289, 'subsample': 0.6254865738749336, 'colsample_bytree': 0.614626406884257, 'reg_alpha': 1.4472861651857671, 'reg_lambda': 1.42761530019437}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  29%|███████████████████████████████                                                                            | 290/1000 [21:41<1:01:00,  5.16s/it]

[I 2026-05-19 14:16:33,057] Trial 288 finished with value: 0.9498652222745401 and parameters: {'n_estimators': 289, 'learning_rate': 0.03546170851596931, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 300, 'subsample': 0.6273616326530548, 'colsample_bytree': 0.6164964654836081, 'reg_alpha': 3.8795309298672764, 'reg_lambda': 2.1710023201265973}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  29%|███████████████████████████████▏                                                                           | 291/1000 [21:46<1:01:34,  5.21s/it]

[I 2026-05-19 14:16:38,397] Trial 289 finished with value: 0.9498637495157822 and parameters: {'n_estimators': 288, 'learning_rate': 0.03651321146415052, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 288, 'subsample': 0.6294659967598524, 'colsample_bytree': 0.6166609091711786, 'reg_alpha': 1.6979351978741142, 'reg_lambda': 1.8706366502780432}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  29%|███████████████████████████████▊                                                                             | 292/1000 [21:46<44:40,  3.79s/it]

[I 2026-05-19 14:16:38,868] Trial 290 finished with value: 0.9498674518375309 and parameters: {'n_estimators': 289, 'learning_rate': 0.036708466719788335, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 97, 'subsample': 0.6280423973036473, 'colsample_bytree': 0.615931678462812, 'reg_alpha': 3.773023480533233, 'reg_lambda': 0.08424588506645747}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  29%|███████████████████████████████▉                                                                             | 293/1000 [21:54<57:55,  4.92s/it]

[I 2026-05-19 14:16:46,415] Trial 291 finished with value: 0.9498659211074664 and parameters: {'n_estimators': 288, 'learning_rate': 0.036858799011086775, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 300, 'subsample': 0.6286399400595039, 'colsample_bytree': 0.6167074870229364, 'reg_alpha': 3.5197457056270918, 'reg_lambda': 1.575682052724668}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  29%|████████████████████████████████                                                                             | 294/1000 [21:54<42:16,  3.59s/it]

[I 2026-05-19 14:16:46,902] Trial 292 finished with value: 0.9498622011517451 and parameters: {'n_estimators': 287, 'learning_rate': 0.03638382300767269, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 300, 'subsample': 0.600120713439766, 'colsample_bytree': 0.6171555308089086, 'reg_alpha': 4.143619455737789, 'reg_lambda': 0.07079083144427069}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  30%|███████████████████████████████▌                                                                           | 295/1000 [22:10<1:22:47,  7.05s/it]

[I 2026-05-19 14:17:02,010] Trial 294 finished with value: 0.9498687283639313 and parameters: {'n_estimators': 286, 'learning_rate': 0.043746782760276666, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 299, 'subsample': 0.6008429814497661, 'colsample_bytree': 0.6155481339637211, 'reg_alpha': 3.983979148663368, 'reg_lambda': 1.2832473204297514}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  30%|███████████████████████████████▋                                                                           | 296/1000 [22:18<1:27:01,  7.42s/it]

[I 2026-05-19 14:17:10,309] Trial 295 finished with value: 0.9498685708170449 and parameters: {'n_estimators': 286, 'learning_rate': 0.04349318462749051, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 299, 'subsample': 0.6041703306916445, 'colsample_bytree': 0.6170803134935887, 'reg_alpha': 3.9934495520984323, 'reg_lambda': 1.0356872830417803}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  30%|███████████████████████████████▊                                                                           | 297/1000 [22:19<1:03:19,  5.41s/it]

[I 2026-05-19 14:17:11,008] Trial 296 finished with value: 0.9498734768995802 and parameters: {'n_estimators': 281, 'learning_rate': 0.043942730006816554, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 300, 'subsample': 0.6020262139208228, 'colsample_bytree': 0.6179868265494846, 'reg_alpha': 4.035865158722256, 'reg_lambda': 4.858386315708121}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  30%|███████████████████████████████▉                                                                           | 298/1000 [22:29<1:19:38,  6.81s/it]

[I 2026-05-19 14:17:21,093] Trial 299 finished with value: 0.9498625662724566 and parameters: {'n_estimators': 281, 'learning_rate': 0.043999130457453385, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 300, 'subsample': 0.6186024116445312, 'colsample_bytree': 0.6174840761890269, 'reg_alpha': 3.747423067696195, 'reg_lambda': 0.06336449409395074}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  30%|███████████████████████████████▉                                                                           | 299/1000 [22:31<1:04:38,  5.53s/it]

[I 2026-05-19 14:17:23,634] Trial 298 finished with value: 0.9498668257266802 and parameters: {'n_estimators': 281, 'learning_rate': 0.04343389028127465, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 299, 'subsample': 0.6196750839625561, 'colsample_bytree': 0.6136317530978356, 'reg_alpha': 0.9704727119255504, 'reg_lambda': 1.8348309291683336}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  30%|████████████████████████████████▋                                                                            | 300/1000 [22:32<47:47,  4.10s/it]

[I 2026-05-19 14:17:24,408] Trial 297 finished with value: 0.949861862602021 and parameters: {'n_estimators': 281, 'learning_rate': 0.03621085414312138, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 300, 'subsample': 0.6002428699889569, 'colsample_bytree': 0.8238570680977984, 'reg_alpha': 3.921385622651664, 'reg_lambda': 1.1112836060727131}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  30%|████████████████████████████████▊                                                                            | 301/1000 [22:35<45:05,  3.87s/it]

[I 2026-05-19 14:17:27,742] Trial 300 finished with value: 0.9498606287589524 and parameters: {'n_estimators': 281, 'learning_rate': 0.044191150791732865, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 298, 'subsample': 0.6190638448294555, 'colsample_bytree': 0.8771161891223022, 'reg_alpha': 4.17827753331844, 'reg_lambda': 0.08004492129969215}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  30%|████████████████████████████████▉                                                                            | 302/1000 [22:40<47:32,  4.09s/it]

[I 2026-05-19 14:17:32,330] Trial 301 finished with value: 0.9498692695143556 and parameters: {'n_estimators': 280, 'learning_rate': 0.04223639990791272, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 288, 'subsample': 0.6171227759810286, 'colsample_bytree': 0.6109159462525025, 'reg_alpha': 4.182353027091242, 'reg_lambda': 0.07257143537084942}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 172. Best value: 0.949875:  30%|█████████████████████████████████                                                                            | 303/1000 [22:41<38:44,  3.33s/it]

[I 2026-05-19 14:17:33,915] Trial 310 finished with value: 0.9495838336560988 and parameters: {'n_estimators': 32, 'learning_rate': 0.043670056568680234, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 97, 'subsample': 0.6013632809289953, 'colsample_bytree': 0.629109657291707, 'reg_alpha': 6.44802112107896, 'reg_lambda': 4.049418604804817}. Best is trial 172 with value: 0.9498753676200742.

Best trial: 302. Best value: 0.949877:  30%|█████████████████████████████████▏                                                                           | 304/1000 [22:45<37:57,  3.27s/it]

[I 2026-05-19 14:17:37,040] Trial 302 finished with value: 0.9498769329196636 and parameters: {'n_estimators': 280, 'learning_rate': 0.0436190427503173, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 300, 'subsample': 0.6015010476152154, 'colsample_bytree': 0.6093796204770228, 'reg_alpha': 4.351861617290465, 'reg_lambda': 5.268292035197034}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  30%|█████████████████████████████████▏                                                                           | 305/1000 [22:49<41:11,  3.56s/it]

[I 2026-05-19 14:17:41,267] Trial 303 finished with value: 0.9498574206309625 and parameters: {'n_estimators': 281, 'learning_rate': 0.04337974075555267, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 280, 'subsample': 0.6002116568764803, 'colsample_bytree': 0.6094286996591879, 'reg_alpha': 1.027969013505415, 'reg_lambda': 0.08517494096399518}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  31%|█████████████████████████████████▎                                                                           | 306/1000 [22:51<34:41,  3.00s/it]

[I 2026-05-19 14:17:42,953] Trial 313 finished with value: 0.9494491781222969 and parameters: {'n_estimators': 38, 'learning_rate': 0.04483602397919872, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 279, 'subsample': 0.6077938676986071, 'colsample_bytree': 0.6311694674894712, 'reg_alpha': 6.7283932088237695, 'reg_lambda': 24.4398785143898}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  31%|█████████████████████████████████▍                                                                           | 307/1000 [22:54<37:22,  3.24s/it]

[I 2026-05-19 14:17:46,715] Trial 305 finished with value: 0.9498696033092688 and parameters: {'n_estimators': 282, 'learning_rate': 0.043884590590175264, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 279, 'subsample': 0.6201049063691545, 'colsample_bytree': 0.6277716755546477, 'reg_alpha': 0.9241618987494941, 'reg_lambda': 5.100123346286204}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  31%|█████████████████████████████████▌                                                                           | 308/1000 [22:55<26:54,  2.33s/it]

[I 2026-05-19 14:17:46,969] Trial 304 finished with value: 0.9498684442911287 and parameters: {'n_estimators': 281, 'learning_rate': 0.043856823832950885, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 103, 'subsample': 0.6007679862502653, 'colsample_bytree': 0.6276837360168471, 'reg_alpha': 0.9292960050622793, 'reg_lambda': 3.9215900391643204}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  31%|█████████████████████████████████                                                                          | 309/1000 [23:13<1:21:34,  7.08s/it]

[I 2026-05-19 14:18:05,140] Trial 306 finished with value: 0.9498743252661367 and parameters: {'n_estimators': 281, 'learning_rate': 0.041947508193941406, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 57, 'subsample': 0.618368399109734, 'colsample_bytree': 0.6274831723137271, 'reg_alpha': 6.4926847378308725, 'reg_lambda': 0.1767558174615252}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  31%|█████████████████████████████████▏                                                                         | 310/1000 [23:14<1:02:19,  5.42s/it]

[I 2026-05-19 14:18:06,658] Trial 307 finished with value: 0.9498744611379536 and parameters: {'n_estimators': 280, 'learning_rate': 0.043441635247207316, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 75, 'subsample': 0.6005483758298767, 'colsample_bytree': 0.6291882076471249, 'reg_alpha': 6.872173253598429, 'reg_lambda': 4.4768513529626315}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  31%|█████████████████████████████████▉                                                                           | 311/1000 [23:19<59:07,  5.15s/it]

[I 2026-05-19 14:18:11,179] Trial 308 finished with value: 0.9498719072431967 and parameters: {'n_estimators': 281, 'learning_rate': 0.043450900121514084, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 82, 'subsample': 0.6077564559964838, 'colsample_bytree': 0.6315520217636784, 'reg_alpha': 4.0979008249912905, 'reg_lambda': 6.827808550779637}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  31%|█████████████████████████████████▍                                                                         | 312/1000 [23:27<1:11:16,  6.22s/it]

[I 2026-05-19 14:18:19,894] Trial 309 finished with value: 0.9498689295419037 and parameters: {'n_estimators': 281, 'learning_rate': 0.04309744039286032, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 288, 'subsample': 0.6008435369778532, 'colsample_bytree': 0.6293025921101184, 'reg_alpha': 6.478308718720135, 'reg_lambda': 3.619957666981593}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  31%|█████████████████████████████████▍                                                                         | 313/1000 [23:35<1:15:10,  6.57s/it]

[I 2026-05-19 14:18:27,174] Trial 312 finished with value: 0.9498691894824501 and parameters: {'n_estimators': 284, 'learning_rate': 0.04191403265612181, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 288, 'subsample': 0.6080827990107174, 'colsample_bytree': 0.6324805743845119, 'reg_alpha': 6.415659602072865, 'reg_lambda': 5.93313685169238}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  31%|█████████████████████████████████▌                                                                         | 314/1000 [23:38<1:03:48,  5.58s/it]

[I 2026-05-19 14:18:30,553] Trial 311 finished with value: 0.9498656134375694 and parameters: {'n_estimators': 281, 'learning_rate': 0.04444095707239745, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 86, 'subsample': 0.6088177883460919, 'colsample_bytree': 0.8771559118825535, 'reg_alpha': 6.281766250609229, 'reg_lambda': 0.16400497892993585}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  32%|██████████████████████████████████▎                                                                          | 315/1000 [23:42<58:44,  5.15s/it]

[I 2026-05-19 14:18:34,693] Trial 314 finished with value: 0.9498655378177888 and parameters: {'n_estimators': 278, 'learning_rate': 0.04278867901384182, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 134, 'subsample': 0.6073876230981865, 'colsample_bytree': 0.6294368076515731, 'reg_alpha': 6.361242227898425, 'reg_lambda': 0.12301778226382902}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  32%|██████████████████████████████████▍                                                                          | 316/1000 [23:45<51:14,  4.50s/it]

[I 2026-05-19 14:18:37,680] Trial 316 finished with value: 0.9498588553251105 and parameters: {'n_estimators': 278, 'learning_rate': 0.045807494979123245, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 57, 'subsample': 0.6097066042613862, 'colsample_bytree': 0.6280721667475878, 'reg_alpha': 4.169066498015258, 'reg_lambda': 29.10248067440763}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  32%|██████████████████████████████████▌                                                                          | 317/1000 [23:47<40:54,  3.59s/it]

[I 2026-05-19 14:18:39,156] Trial 315 finished with value: 0.9497640502294405 and parameters: {'n_estimators': 278, 'learning_rate': 0.012798989090574416, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 76, 'subsample': 0.6084507624475434, 'colsample_bytree': 0.6288212083650462, 'reg_alpha': 6.3678079614528835, 'reg_lambda': 13.284296545078234}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  32%|██████████████████████████████████▋                                                                          | 318/1000 [23:50<40:39,  3.58s/it]

[I 2026-05-19 14:18:42,700] Trial 317 finished with value: 0.9498706331125938 and parameters: {'n_estimators': 277, 'learning_rate': 0.042435311482089115, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 57, 'subsample': 0.6102419110381841, 'colsample_bytree': 0.6273770778862409, 'reg_alpha': 4.19776413708343, 'reg_lambda': 5.244429742507751}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  32%|██████████████████████████████████▊                                                                          | 319/1000 [23:51<32:03,  2.82s/it]

[I 2026-05-19 14:18:43,762] Trial 318 finished with value: 0.9498691988099877 and parameters: {'n_estimators': 283, 'learning_rate': 0.04602069363967952, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 125, 'subsample': 0.6092307050669756, 'colsample_bytree': 0.6263338289865179, 'reg_alpha': 3.9285978253762748, 'reg_lambda': 7.061207986943163}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  32%|██████████████████████████████████▉                                                                          | 320/1000 [23:55<36:04,  3.18s/it]

[I 2026-05-19 14:18:47,769] Trial 319 finished with value: 0.9498659506813274 and parameters: {'n_estimators': 282, 'learning_rate': 0.04668335242413428, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 86, 'subsample': 0.6096866258412397, 'colsample_bytree': 0.6334141935698525, 'reg_alpha': 4.2532769485097255, 'reg_lambda': 5.70258219940488}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  32%|██████████████████████████████████▎                                                                        | 321/1000 [24:11<1:17:16,  6.83s/it]

[I 2026-05-19 14:19:03,120] Trial 320 finished with value: 0.9498692972083699 and parameters: {'n_estimators': 280, 'learning_rate': 0.04303038858868981, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 63, 'subsample': 0.6093182351604305, 'colsample_bytree': 0.6352751138833062, 'reg_alpha': 6.130490532857759, 'reg_lambda': 8.212326389987844}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  32%|██████████████████████████████████▍                                                                        | 322/1000 [24:13<1:03:25,  5.61s/it]

[I 2026-05-19 14:19:05,900] Trial 321 finished with value: 0.9498712691281902 and parameters: {'n_estimators': 278, 'learning_rate': 0.045872682681986576, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 79, 'subsample': 0.609420789803247, 'colsample_bytree': 0.6424793807947696, 'reg_alpha': 5.9614243622833385, 'reg_lambda': 4.610906474580896}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  32%|██████████████████████████████████▌                                                                        | 323/1000 [24:18<1:00:28,  5.36s/it]

[I 2026-05-19 14:19:10,666] Trial 322 finished with value: 0.9498616188043375 and parameters: {'n_estimators': 278, 'learning_rate': 0.04615397786697167, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 52, 'subsample': 0.6099812629801323, 'colsample_bytree': 0.6432980286791511, 'reg_alpha': 6.181632970142126, 'reg_lambda': 6.136234656918001}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  32%|██████████████████████████████████▋                                                                        | 324/1000 [24:27<1:13:06,  6.49s/it]

[I 2026-05-19 14:19:19,790] Trial 323 finished with value: 0.9498700935194421 and parameters: {'n_estimators': 279, 'learning_rate': 0.045035616880239694, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 108, 'subsample': 0.6089713302149109, 'colsample_bytree': 0.6360769209599657, 'reg_alpha': 6.071501828037019, 'reg_lambda': 9.918156078291737}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  32%|██████████████████████████████████▊                                                                        | 325/1000 [24:37<1:22:22,  7.32s/it]

[I 2026-05-19 14:19:29,060] Trial 324 finished with value: 0.9498708824227176 and parameters: {'n_estimators': 281, 'learning_rate': 0.0453664649863236, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 48, 'subsample': 0.6090219947564559, 'colsample_bytree': 0.6401997599246759, 'reg_alpha': 6.610317021199291, 'reg_lambda': 7.09209142784208}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  33%|██████████████████████████████████▉                                                                        | 326/1000 [24:39<1:05:59,  5.87s/it]

[I 2026-05-19 14:19:31,551] Trial 325 finished with value: 0.949875889730124 and parameters: {'n_estimators': 277, 'learning_rate': 0.04459025922561295, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 57, 'subsample': 0.6087988578747805, 'colsample_bytree': 0.642224327555819, 'reg_alpha': 4.364723795546364, 'reg_lambda': 6.423948199919474}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  33%|███████████████████████████████████▋                                                                         | 327/1000 [24:41<53:54,  4.81s/it]

[I 2026-05-19 14:19:33,868] Trial 326 finished with value: 0.9498715141292781 and parameters: {'n_estimators': 276, 'learning_rate': 0.045857964156637065, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 59, 'subsample': 0.6165002104527052, 'colsample_bytree': 0.6393440001298012, 'reg_alpha': 4.396302638941678, 'reg_lambda': 10.014340402186273}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  33%|███████████████████████████████████▊                                                                         | 328/1000 [24:43<43:12,  3.86s/it]

[I 2026-05-19 14:19:35,514] Trial 328 finished with value: 0.9498722526160945 and parameters: {'n_estimators': 274, 'learning_rate': 0.04609909039362511, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 67, 'subsample': 0.6135877533968059, 'colsample_bytree': 0.64192264838429, 'reg_alpha': 4.267800844938465, 'reg_lambda': 6.6347123027495885}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  33%|███████████████████████████████████▊                                                                         | 329/1000 [24:46<40:04,  3.58s/it]

[I 2026-05-19 14:19:38,441] Trial 327 finished with value: 0.9498704298408365 and parameters: {'n_estimators': 284, 'learning_rate': 0.04621692946927688, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 69, 'subsample': 0.6166479377305806, 'colsample_bytree': 0.6399519505969304, 'reg_alpha': 4.624994401779377, 'reg_lambda': 8.272120842889574}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  33%|███████████████████████████████████▉                                                                         | 330/1000 [24:48<33:08,  2.97s/it]

[I 2026-05-19 14:19:39,989] Trial 329 finished with value: 0.9498714488827572 and parameters: {'n_estimators': 273, 'learning_rate': 0.04637274576489025, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 57, 'subsample': 0.6166173128637212, 'colsample_bytree': 0.6415419366349379, 'reg_alpha': 4.650600890342297, 'reg_lambda': 6.651613654838503}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  33%|████████████████████████████████████                                                                         | 331/1000 [24:50<32:44,  2.94s/it]

[I 2026-05-19 14:19:42,848] Trial 330 finished with value: 0.9498662784397272 and parameters: {'n_estimators': 274, 'learning_rate': 0.04660329004313064, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 56, 'subsample': 0.6169203124067025, 'colsample_bytree': 0.6407240336146478, 'reg_alpha': 4.539555038198157, 'reg_lambda': 7.365532678395426}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  33%|████████████████████████████████████▏                                                                        | 332/1000 [24:52<27:10,  2.44s/it]

[I 2026-05-19 14:19:44,134] Trial 331 finished with value: 0.949865094879156 and parameters: {'n_estimators': 273, 'learning_rate': 0.04734637330139691, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 61, 'subsample': 0.6168619148113466, 'colsample_bytree': 0.6419684994208892, 'reg_alpha': 4.431013692897457, 'reg_lambda': 6.776025007842509}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  33%|███████████████████████████████████▋                                                                       | 333/1000 [25:09<1:16:50,  6.91s/it]

[I 2026-05-19 14:20:01,478] Trial 332 finished with value: 0.9496219594898916 and parameters: {'n_estimators': 273, 'learning_rate': 0.005923411209898243, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 67, 'subsample': 0.6175962349017037, 'colsample_bytree': 0.6458926412090368, 'reg_alpha': 6.203257376822647, 'reg_lambda': 8.165554935206192}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:20:01,498] Trial 333 finished with value: 0.9498667529880299 and parameters: {'n_estimators': 271, 'learning_rate': 0.04682424437886875, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 63, 'subsample': 0.6166533555591063, 'colsample_bytree': 0.6402746841828623, 'reg_alpha': 6.515785833084896, 'reg_lambda': 8.141382518758808}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  34%|████████████████████████████████████▌                                                                        | 335/1000 [25:16<58:06,  5.24s/it]

[I 2026-05-19 14:20:08,066] Trial 334 finished with value: 0.9498699987847343 and parameters: {'n_estimators': 270, 'learning_rate': 0.046621961442562816, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 65, 'subsample': 0.6173629789402838, 'colsample_bytree': 0.6411357236785764, 'reg_alpha': 5.77641340960613, 'reg_lambda': 9.461247964524345}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  34%|███████████████████████████████████▉                                                                       | 336/1000 [25:26<1:12:47,  6.58s/it]

[I 2026-05-19 14:20:18,697] Trial 335 finished with value: 0.9498672610624208 and parameters: {'n_estimators': 274, 'learning_rate': 0.04655041670437149, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 71, 'subsample': 0.6195402095611304, 'colsample_bytree': 0.6487020895508241, 'reg_alpha': 5.074558165687522, 'reg_lambda': 8.580384000349964}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  34%|████████████████████████████████████▋                                                                        | 337/1000 [25:27<54:33,  4.94s/it]

[I 2026-05-19 14:20:18,972] Trial 342 finished with value: 0.9498294152994149 and parameters: {'n_estimators': 270, 'learning_rate': 0.04773031883578396, 'max_depth': 2, 'num_leaves': 14, 'min_child_samples': 42, 'subsample': 0.6184929306616005, 'colsample_bytree': 0.6494778898264545, 'reg_alpha': 2.960848860540424, 'reg_lambda': 13.309485431090863}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  34%|████████████████████████████████████▊                                                                        | 338/1000 [25:29<46:45,  4.24s/it]

[I 2026-05-19 14:20:21,359] Trial 343 finished with value: 0.9498329515264924 and parameters: {'n_estimators': 269, 'learning_rate': 0.04644423047828838, 'max_depth': 2, 'num_leaves': 14, 'min_child_samples': 48, 'subsample': 0.6185215192693142, 'colsample_bytree': 0.6490654475655427, 'reg_alpha': 8.194184461230357, 'reg_lambda': 3.439054770162598}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  34%|████████████████████████████████████▉                                                                        | 339/1000 [25:33<47:26,  4.31s/it]

[I 2026-05-19 14:20:25,830] Trial 336 finished with value: 0.9498699558021455 and parameters: {'n_estimators': 272, 'learning_rate': 0.047739297760592096, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 56, 'subsample': 0.6174968343104177, 'colsample_bytree': 0.6479063469604595, 'reg_alpha': 4.866771499262602, 'reg_lambda': 8.662802455628722}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  34%|█████████████████████████████████████                                                                        | 340/1000 [25:37<44:29,  4.04s/it]

[I 2026-05-19 14:20:29,241] Trial 337 finished with value: 0.9498698615359125 and parameters: {'n_estimators': 272, 'learning_rate': 0.046436228107643425, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 64, 'subsample': 0.6178130244470013, 'colsample_bytree': 0.6489192420518011, 'reg_alpha': 4.755834655160261, 'reg_lambda': 10.00169262994262}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  34%|█████████████████████████████████████▏                                                                       | 341/1000 [25:40<42:09,  3.84s/it]

[I 2026-05-19 14:20:32,584] Trial 338 finished with value: 0.9498622996063559 and parameters: {'n_estimators': 275, 'learning_rate': 0.047224512404544436, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 60, 'subsample': 0.6178878456315704, 'colsample_bytree': 0.6461611138741753, 'reg_alpha': 4.83354209331401, 'reg_lambda': 10.543592689617293}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  34%|█████████████████████████████████████▎                                                                       | 342/1000 [25:40<30:43,  2.80s/it]

[I 2026-05-19 14:20:32,858] Trial 339 finished with value: 0.9498632264087219 and parameters: {'n_estimators': 273, 'learning_rate': 0.04695798198827963, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 66, 'subsample': 0.6181286161972286, 'colsample_bytree': 0.6439894774347478, 'reg_alpha': 5.040383606639788, 'reg_lambda': 9.279267948485906}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  34%|█████████████████████████████████████▍                                                                       | 343/1000 [25:44<33:17,  3.04s/it]

[I 2026-05-19 14:20:36,487] Trial 340 finished with value: 0.9498661167200664 and parameters: {'n_estimators': 271, 'learning_rate': 0.04744268461915298, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 45, 'subsample': 0.6174708781617113, 'colsample_bytree': 0.6497265322241944, 'reg_alpha': 4.855216563155948, 'reg_lambda': 11.275677807926222}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  34%|█████████████████████████████████████▍                                                                       | 344/1000 [25:46<29:01,  2.65s/it]

[I 2026-05-19 14:20:38,214] Trial 341 finished with value: 0.9498624317331764 and parameters: {'n_estimators': 271, 'learning_rate': 0.047327186896245835, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 39, 'subsample': 0.618510455316367, 'colsample_bytree': 0.6510426838581368, 'reg_alpha': 4.520619843093496, 'reg_lambda': 11.414538029244646}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  34%|█████████████████████████████████████▌                                                                       | 345/1000 [25:50<33:52,  3.10s/it]

[I 2026-05-19 14:20:42,365] Trial 348 finished with value: 0.9498048275302915 and parameters: {'n_estimators': 121, 'learning_rate': 0.049073158347027045, 'max_depth': 4, 'num_leaves': 6, 'min_child_samples': 41, 'subsample': 0.6126223544731241, 'colsample_bytree': 0.6516869379866933, 'reg_alpha': 8.02603029621575, 'reg_lambda': 10.33231573732951}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  35%|█████████████████████████████████████▋                                                                       | 346/1000 [25:52<29:19,  2.69s/it]

[I 2026-05-19 14:20:44,107] Trial 350 finished with value: 0.94973162866302 and parameters: {'n_estimators': 69, 'learning_rate': 0.049995168275092754, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 79, 'subsample': 0.6102359565931716, 'colsample_bytree': 0.6541126421626163, 'reg_alpha': 8.15801966315254, 'reg_lambda': 13.11508366735493}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  35%|█████████████████████████████████████▊                                                                       | 347/1000 [25:52<21:30,  1.98s/it]

[I 2026-05-19 14:20:44,390] Trial 349 finished with value: 0.9497772743268067 and parameters: {'n_estimators': 79, 'learning_rate': 0.04952620476986478, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 77, 'subsample': 0.6102410286305143, 'colsample_bytree': 0.6649949340192296, 'reg_alpha': 2.9513283532705556, 'reg_lambda': 15.208505501719033}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  35%|█████████████████████████████████████▉                                                                       | 348/1000 [26:03<52:15,  4.81s/it]

[I 2026-05-19 14:20:55,852] Trial 344 finished with value: 0.9498611368365826 and parameters: {'n_estimators': 270, 'learning_rate': 0.04843091807849831, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 51, 'subsample': 0.6190760987492598, 'colsample_bytree': 0.6482845025700449, 'reg_alpha': 2.9059076344737793, 'reg_lambda': 13.627244051315369}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  35%|██████████████████████████████████████                                                                       | 349/1000 [26:06<44:42,  4.12s/it]

[I 2026-05-19 14:20:58,361] Trial 345 finished with value: 0.9498643731403142 and parameters: {'n_estimators': 271, 'learning_rate': 0.04783006429370685, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 55, 'subsample': 0.6178648559149196, 'colsample_bytree': 0.6523913541685284, 'reg_alpha': 2.9825822214078386, 'reg_lambda': 12.239508169429293}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  35%|██████████████████████████████████████▏                                                                      | 350/1000 [26:09<42:52,  3.96s/it]

[I 2026-05-19 14:21:01,922] Trial 352 finished with value: 0.9498225158895496 and parameters: {'n_estimators': 114, 'learning_rate': 0.04919901845046176, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 78, 'subsample': 0.6486573055663262, 'colsample_bytree': 0.6547128554480238, 'reg_alpha': 8.632748859335578, 'reg_lambda': 18.156063160789806}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  35%|██████████████████████████████████████▎                                                                      | 351/1000 [26:13<41:10,  3.81s/it]

[I 2026-05-19 14:21:05,378] Trial 346 finished with value: 0.949860158990858 and parameters: {'n_estimators': 270, 'learning_rate': 0.04821217901143165, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 45, 'subsample': 0.6185789564831707, 'colsample_bytree': 0.6468506942173802, 'reg_alpha': 2.974540274228743, 'reg_lambda': 12.507493974865591}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  35%|██████████████████████████████████████▎                                                                      | 352/1000 [26:17<41:06,  3.81s/it]

[I 2026-05-19 14:21:09,163] Trial 355 pruned.

Best trial: 302. Best value: 0.949877:  35%|██████████████████████████████████████▍                                                                      | 353/1000 [26:19<35:22,  3.28s/it]

[I 2026-05-19 14:21:11,258] Trial 357 finished with value: 0.9497493274253163 and parameters: {'n_estimators': 268, 'learning_rate': 0.04511452621525963, 'max_depth': 1, 'num_leaves': 15, 'min_child_samples': 31, 'subsample': 0.6003334140048412, 'colsample_bytree': 0.6620199715039736, 'reg_alpha': 8.536808391022689, 'reg_lambda': 17.567634679941825}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  35%|██████████████████████████████████████▌                                                                      | 354/1000 [26:24<41:20,  3.84s/it]

[I 2026-05-19 14:21:16,397] Trial 347 finished with value: 0.949865067059959 and parameters: {'n_estimators': 269, 'learning_rate': 0.048620365199643086, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 46, 'subsample': 0.6183081436861962, 'colsample_bytree': 0.6517582727078843, 'reg_alpha': 2.8365210199441546, 'reg_lambda': 16.892754874364968}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  36%|█████████████████████████████████████▉                                                                     | 355/1000 [26:36<1:08:28,  6.37s/it]

[I 2026-05-19 14:21:28,671] Trial 351 finished with value: 0.9498598774624598 and parameters: {'n_estimators': 268, 'learning_rate': 0.04924163246355411, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 50, 'subsample': 0.6474359173985165, 'colsample_bytree': 0.6633457311288448, 'reg_alpha': 7.738830461926628, 'reg_lambda': 12.757625203562272}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  36%|██████████████████████████████████████▊                                                                      | 356/1000 [26:38<54:11,  5.05s/it]

[I 2026-05-19 14:21:30,631] Trial 353 finished with value: 0.9498613421079675 and parameters: {'n_estimators': 271, 'learning_rate': 0.04996016085956964, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 77, 'subsample': 0.6356883478743426, 'colsample_bytree': 0.6671319888777608, 'reg_alpha': 8.54072385484346, 'reg_lambda': 15.127505975786846}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  36%|██████████████████████████████████████▉                                                                      | 357/1000 [26:41<47:49,  4.46s/it]

[I 2026-05-19 14:21:33,730] Trial 354 finished with value: 0.9498541371878787 and parameters: {'n_estimators': 268, 'learning_rate': 0.049683027163378725, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 28, 'subsample': 0.9352513812586607, 'colsample_bytree': 0.6617746560313472, 'reg_alpha': 8.844065336305562, 'reg_lambda': 22.31036441986901}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  36%|███████████████████████████████████████                                                                      | 358/1000 [26:48<54:14,  5.07s/it]

[I 2026-05-19 14:21:40,221] Trial 356 finished with value: 0.9498600166961284 and parameters: {'n_estimators': 264, 'learning_rate': 0.049395225520008176, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 77, 'subsample': 0.6340279107956882, 'colsample_bytree': 0.6652445668898049, 'reg_alpha': 8.465133524897013, 'reg_lambda': 15.500356456244889}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  36%|███████████████████████████████████████▏                                                                     | 359/1000 [26:50<45:35,  4.27s/it]

[I 2026-05-19 14:21:42,614] Trial 358 finished with value: 0.9498644837069363 and parameters: {'n_estimators': 267, 'learning_rate': 0.0452846906949011, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 49, 'subsample': 0.6361258833186415, 'colsample_bytree': 0.6393886281544923, 'reg_alpha': 9.165183333098458, 'reg_lambda': 4.8477838824128545}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  36%|███████████████████████████████████████▎                                                                     | 361/1000 [27:05<56:32,  5.31s/it]

[I 2026-05-19 14:21:57,667] Trial 360 finished with value: 0.9498682400377799 and parameters: {'n_estimators': 277, 'learning_rate': 0.04555485088971826, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 70, 'subsample': 0.6359056396189006, 'colsample_bytree': 0.6384259629894236, 'reg_alpha': 7.4446537089662055, 'reg_lambda': 4.627877535776635}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:21:57,854] Trial 359 finished with value: 0.9498410482690565 and parameters: {'n_estimators': 265, 'learning_rate': 0.02425013168232394, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 55, 'subsample': 0.6454158222790302, 'colsample_bytree': 0.6385282822617806, 'reg_alpha': 9.027321248985785, 'reg_lambda': 4.3631933971604955}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  36%|███████████████████████████████████████▍                                                                     | 362/1000 [27:10<53:07,  5.00s/it]

[I 2026-05-19 14:22:02,115] Trial 362 finished with value: 0.9498689481718952 and parameters: {'n_estimators': 276, 'learning_rate': 0.044987197817020416, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 71, 'subsample': 0.6382949295596987, 'colsample_bytree': 0.6397155797256573, 'reg_alpha': 8.513694058724866, 'reg_lambda': 4.6955711144409085}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  36%|███████████████████████████████████████▌                                                                     | 363/1000 [27:12<43:04,  4.06s/it]

[I 2026-05-19 14:22:03,992] Trial 361 finished with value: 0.9498682888825714 and parameters: {'n_estimators': 276, 'learning_rate': 0.04495947327907786, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 70, 'subsample': 0.6005206023540166, 'colsample_bytree': 0.6368536935522924, 'reg_alpha': 9.175061474512665, 'reg_lambda': 4.97558835493759}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  36%|███████████████████████████████████████▋                                                                     | 364/1000 [27:13<34:24,  3.25s/it]

[I 2026-05-19 14:22:05,339] Trial 364 finished with value: 0.9497969522093925 and parameters: {'n_estimators': 278, 'learning_rate': 0.04507141624817756, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 70, 'subsample': 0.6322252724622324, 'colsample_bytree': 0.6383862651574609, 'reg_alpha': 99.34818812084877, 'reg_lambda': 4.665227660639734}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  36%|███████████████████████████████████████▊                                                                     | 365/1000 [27:16<32:29,  3.07s/it]

[I 2026-05-19 14:22:07,990] Trial 363 finished with value: 0.9498615846654953 and parameters: {'n_estimators': 276, 'learning_rate': 0.04496922750395674, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 70, 'subsample': 0.6357736839664055, 'colsample_bytree': 0.6353017099237201, 'reg_alpha': 13.216222251322268, 'reg_lambda': 3.802195643487031}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  37%|███████████████████████████████████████▉                                                                     | 366/1000 [27:20<37:34,  3.56s/it]

[I 2026-05-19 14:22:12,690] Trial 365 finished with value: 0.9498645366885947 and parameters: {'n_estimators': 275, 'learning_rate': 0.044226125408401755, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 70, 'subsample': 0.6350167325678211, 'colsample_bytree': 0.6381826997139411, 'reg_alpha': 12.245178906266817, 'reg_lambda': 4.5354608339487665}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  37%|███████████████████████████████████████▎                                                                   | 367/1000 [27:37<1:18:13,  7.41s/it]

[I 2026-05-19 14:22:29,102] Trial 366 finished with value: 0.9498739661481842 and parameters: {'n_estimators': 277, 'learning_rate': 0.04491826696229473, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 72, 'subsample': 0.633709715534554, 'colsample_bytree': 0.6385778610964672, 'reg_alpha': 5.434725935720696, 'reg_lambda': 3.865098512612891}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:22:29,164] Trial 367 finished with value: 0.9498663106415236 and parameters: {'n_estimators': 277, 'learning_rate': 0.04513710236659358, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 69, 'subsample': 0.963077819924411, 'colsample_bytree': 0.6372795760035783, 'reg_alpha': 13.826456618364281, 'reg_lambda': 4.651001196548941}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  37%|████████████████████████████████████████▏                                                                    | 369/1000 [27:42<54:02,  5.14s/it]

[I 2026-05-19 14:22:34,071] Trial 368 finished with value: 0.9498631082596576 and parameters: {'n_estimators': 277, 'learning_rate': 0.04506101575861095, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 71, 'subsample': 0.6394789899882859, 'colsample_bytree': 0.6389174710495783, 'reg_alpha': 13.96607387012913, 'reg_lambda': 4.6659015949316185}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  37%|████████████████████████████████████████▎                                                                    | 370/1000 [27:43<45:08,  4.30s/it]

[I 2026-05-19 14:22:35,840] Trial 369 finished with value: 0.9498624337649909 and parameters: {'n_estimators': 276, 'learning_rate': 0.044647406624152376, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 72, 'subsample': 0.607061632964305, 'colsample_bytree': 0.6342517921038443, 'reg_alpha': 12.954338563134263, 'reg_lambda': 4.571021528838416}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  37%|████████████████████████████████████████▍                                                                    | 371/1000 [27:51<54:29,  5.20s/it]

[I 2026-05-19 14:22:43,560] Trial 370 finished with value: 0.9498670818682864 and parameters: {'n_estimators': 277, 'learning_rate': 0.045248657769202554, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 67, 'subsample': 0.9634445739365528, 'colsample_bytree': 0.6378045806458873, 'reg_alpha': 5.793818218665182, 'reg_lambda': 4.987530439678633}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  37%|███████████████████████████████████████▊                                                                   | 372/1000 [28:01<1:07:41,  6.47s/it]

[I 2026-05-19 14:22:53,432] Trial 378 finished with value: 0.9497855626906029 and parameters: {'n_estimators': 94, 'learning_rate': 0.0421765625919336, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 60, 'subsample': 0.6063706094242006, 'colsample_bytree': 0.6423337568519675, 'reg_alpha': 5.713137817597671, 'reg_lambda': 6.058844059374173}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  37%|████████████████████████████████████████▋                                                                    | 373/1000 [28:03<53:39,  5.14s/it]

[I 2026-05-19 14:22:55,121] Trial 372 finished with value: 0.9498640925447297 and parameters: {'n_estimators': 277, 'learning_rate': 0.044562735856589104, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 68, 'subsample': 0.6006201824802206, 'colsample_bytree': 0.6375081195166746, 'reg_alpha': 13.182810015256397, 'reg_lambda': 2.9873009349190007}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  37%|████████████████████████████████████████▊                                                                    | 374/1000 [28:04<41:53,  4.01s/it]

[I 2026-05-19 14:22:56,345] Trial 371 finished with value: 0.9498746597573866 and parameters: {'n_estimators': 277, 'learning_rate': 0.04474957940840991, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 66, 'subsample': 0.606643822171757, 'colsample_bytree': 0.6378327042294734, 'reg_alpha': 5.3021530371353744, 'reg_lambda': 5.332026108785849}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  38%|████████████████████████████████████████▉                                                                    | 375/1000 [28:09<46:10,  4.43s/it]

[I 2026-05-19 14:23:01,788] Trial 373 finished with value: 0.9498600969350489 and parameters: {'n_estimators': 276, 'learning_rate': 0.04206704822830893, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 66, 'subsample': 0.6005142487859252, 'colsample_bytree': 0.6379347838311304, 'reg_alpha': 14.403109952393084, 'reg_lambda': 3.429266922275617}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  38%|████████████████████████████████████████▉                                                                    | 376/1000 [28:13<43:35,  4.19s/it]

[I 2026-05-19 14:23:05,405] Trial 376 finished with value: 0.9498766148513189 and parameters: {'n_estimators': 284, 'learning_rate': 0.042767956493561445, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 61, 'subsample': 0.6057283388684014, 'colsample_bytree': 0.6408017236326212, 'reg_alpha': 5.1079679717711395, 'reg_lambda': 2.855013880977681}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  38%|█████████████████████████████████████████                                                                    | 377/1000 [28:13<31:29,  3.03s/it]

[I 2026-05-19 14:23:05,678] Trial 375 finished with value: 0.9498626706104325 and parameters: {'n_estimators': 285, 'learning_rate': 0.04287796201726023, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 62, 'subsample': 0.675796081022468, 'colsample_bytree': 0.6372244667987589, 'reg_alpha': 13.374083400580341, 'reg_lambda': 3.135965953040402}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  38%|█████████████████████████████████████████▏                                                                   | 378/1000 [28:14<24:04,  2.32s/it]

[I 2026-05-19 14:23:06,324] Trial 374 finished with value: 0.9498754269036978 and parameters: {'n_estimators': 277, 'learning_rate': 0.042033856436186394, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 62, 'subsample': 0.6065497634356852, 'colsample_bytree': 0.6385136617645233, 'reg_alpha': 5.705224591511206, 'reg_lambda': 3.4805668311120628}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  38%|█████████████████████████████████████████▎                                                                   | 379/1000 [28:22<41:42,  4.03s/it]

[I 2026-05-19 14:23:14,364] Trial 377 finished with value: 0.949872275048298 and parameters: {'n_estimators': 285, 'learning_rate': 0.041381791653905126, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 65, 'subsample': 0.6000254040790391, 'colsample_bytree': 0.6408681021467275, 'reg_alpha': 5.527561877318664, 'reg_lambda': 7.426977703613785}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  38%|████████████████████████████████████████▋                                                                  | 380/1000 [28:42<1:31:09,  8.82s/it]

[I 2026-05-19 14:23:34,463] Trial 379 finished with value: 0.9498650154905135 and parameters: {'n_estimators': 284, 'learning_rate': 0.042264742345844576, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 59, 'subsample': 0.9446664088614714, 'colsample_bytree': 0.7986118186223672, 'reg_alpha': 5.71488869096241, 'reg_lambda': 6.708181211319663}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  38%|████████████████████████████████████████▊                                                                  | 381/1000 [28:43<1:05:28,  6.35s/it]

[I 2026-05-19 14:23:34,990] Trial 381 finished with value: 0.9498700005705043 and parameters: {'n_estimators': 284, 'learning_rate': 0.04153525930282023, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 60, 'subsample': 0.9433383119351594, 'colsample_bytree': 0.6410783153966502, 'reg_alpha': 5.697420926271723, 'reg_lambda': 7.614870268579981}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  38%|████████████████████████████████████████▊                                                                  | 382/1000 [28:47<1:00:09,  5.84s/it]

[I 2026-05-19 14:23:39,651] Trial 380 finished with value: 0.949863770735511 and parameters: {'n_estimators': 285, 'learning_rate': 0.041671817046800036, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 86, 'subsample': 0.9471801847346438, 'colsample_bytree': 0.8549377065565302, 'reg_alpha': 5.636160523893312, 'reg_lambda': 6.55581790781523}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  38%|█████████████████████████████████████████▋                                                                   | 383/1000 [28:53<58:41,  5.71s/it]

[I 2026-05-19 14:23:45,055] Trial 382 finished with value: 0.949874152733895 and parameters: {'n_estimators': 285, 'learning_rate': 0.04177114922804073, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 62, 'subsample': 0.6819042222830516, 'colsample_bytree': 0.6463591051971364, 'reg_alpha': 3.7814557582830344, 'reg_lambda': 6.766298935505866}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  38%|█████████████████████████████████████████                                                                  | 384/1000 [29:01<1:08:03,  6.63s/it]

[I 2026-05-19 14:23:53,826] Trial 384 finished with value: 0.9498734419425571 and parameters: {'n_estimators': 284, 'learning_rate': 0.0418960404670759, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 88, 'subsample': 0.6754728439833524, 'colsample_bytree': 0.629389695102673, 'reg_alpha': 4.04203073338873, 'reg_lambda': 7.240323093906535}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  38%|█████████████████████████████████████████▉                                                                   | 385/1000 [29:02<48:09,  4.70s/it]

[I 2026-05-19 14:23:54,038] Trial 385 finished with value: 0.9498734473150563 and parameters: {'n_estimators': 284, 'learning_rate': 0.04180503118289211, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 81, 'subsample': 0.9471593076492566, 'colsample_bytree': 0.6302326149931788, 'reg_alpha': 3.6096674993778897, 'reg_lambda': 3.0415541747043515}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  39%|██████████████████████████████████████████                                                                   | 386/1000 [29:03<37:23,  3.65s/it]

[I 2026-05-19 14:23:55,246] Trial 383 finished with value: 0.9498714337405201 and parameters: {'n_estimators': 285, 'learning_rate': 0.04206473002725085, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 85, 'subsample': 0.6242084344648446, 'colsample_bytree': 0.6445721043208104, 'reg_alpha': 3.859662362963739, 'reg_lambda': 7.457201034182253}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  39%|██████████████████████████████████████████▏                                                                  | 387/1000 [29:10<48:35,  4.76s/it]

[I 2026-05-19 14:24:02,575] Trial 386 finished with value: 0.9498657283252218 and parameters: {'n_estimators': 283, 'learning_rate': 0.04238781548724639, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 83, 'subsample': 0.6246882023448767, 'colsample_bytree': 0.6309777015115561, 'reg_alpha': 3.5718792036380687, 'reg_lambda': 0.008134451519985653}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  39%|██████████████████████████████████████████▎                                                                  | 388/1000 [29:11<35:31,  3.48s/it]

[I 2026-05-19 14:24:03,083] Trial 387 finished with value: 0.9498743666163826 and parameters: {'n_estimators': 284, 'learning_rate': 0.04251853522642481, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 88, 'subsample': 0.6081792694665705, 'colsample_bytree': 0.6319310848455827, 'reg_alpha': 3.6847067335981727, 'reg_lambda': 6.807058044658883}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  39%|██████████████████████████████████████████▌                                                                  | 390/1000 [29:17<31:50,  3.13s/it]

[I 2026-05-19 14:24:09,644] Trial 389 finished with value: 0.9498739296180286 and parameters: {'n_estimators': 286, 'learning_rate': 0.0416766690007956, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 84, 'subsample': 0.9195328971599434, 'colsample_bytree': 0.6258577577556602, 'reg_alpha': 3.8665173893561957, 'reg_lambda': 2.6902319200028515}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:24:09,805] Trial 388 finished with value: 0.9498695518482357 and parameters: {'n_estimators': 284, 'learning_rate': 0.0415226647087492, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 89, 'subsample': 0.9191373154124232, 'colsample_bytree': 0.8491503153755758, 'reg_alpha': 3.514608108859846, 'reg_lambda': 6.68735860206399}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  39%|██████████████████████████████████████████▌                                                                  | 391/1000 [29:18<25:26,  2.51s/it]

[I 2026-05-19 14:24:10,845] Trial 390 finished with value: 0.9498724486837439 and parameters: {'n_estimators': 283, 'learning_rate': 0.04184598939726617, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 82, 'subsample': 0.6078003048320779, 'colsample_bytree': 0.6282462459206721, 'reg_alpha': 3.816131553340248, 'reg_lambda': 7.826365958414601}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  39%|█████████████████████████████████████████▉                                                                 | 392/1000 [29:44<1:36:23,  9.51s/it]

[I 2026-05-19 14:24:36,722] Trial 393 finished with value: 0.9498634052878334 and parameters: {'n_estimators': 284, 'learning_rate': 0.04145891218776182, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 83, 'subsample': 0.6007472194291309, 'colsample_bytree': 0.6254263972618915, 'reg_alpha': 0.001259275323344129, 'reg_lambda': 2.8925239266271245}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  39%|██████████████████████████████████████████                                                                 | 393/1000 [29:45<1:08:55,  6.81s/it]

[I 2026-05-19 14:24:37,224] Trial 392 finished with value: 0.9498707440289282 and parameters: {'n_estimators': 284, 'learning_rate': 0.04146075101500238, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 82, 'subsample': 0.6068580840440196, 'colsample_bytree': 0.6285554013344005, 'reg_alpha': 3.6251158101121788, 'reg_lambda': 2.7567995495224875}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  39%|██████████████████████████████████████████▉                                                                  | 394/1000 [29:48<57:01,  5.65s/it]

[I 2026-05-19 14:24:40,110] Trial 391 finished with value: 0.9498596422629397 and parameters: {'n_estimators': 283, 'learning_rate': 0.0424181142857908, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 55, 'subsample': 0.8697142763118259, 'colsample_bytree': 0.9204619574189847, 'reg_alpha': 3.5661277869448806, 'reg_lambda': 2.9927665405545403}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  40%|██████████████████████████████████████████▎                                                                | 395/1000 [30:00<1:17:20,  7.67s/it]

[I 2026-05-19 14:24:52,547] Trial 394 finished with value: 0.9498600202712641 and parameters: {'n_estimators': 284, 'learning_rate': 0.04186786093536057, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 81, 'subsample': 0.6078704377767349, 'colsample_bytree': 0.9090264598198307, 'reg_alpha': 3.771134325692971, 'reg_lambda': 2.9221734095159397}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  40%|███████████████████████████████████████████▏                                                                 | 396/1000 [30:00<55:06,  5.47s/it]

[I 2026-05-19 14:24:52,895] Trial 396 finished with value: 0.9498698205106594 and parameters: {'n_estimators': 284, 'learning_rate': 0.042428647064470804, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 83, 'subsample': 0.6718535069675503, 'colsample_bytree': 0.6470682761668902, 'reg_alpha': 3.548494811136943, 'reg_lambda': 2.2987287865368042}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  40%|███████████████████████████████████████████▎                                                                 | 397/1000 [30:01<39:24,  3.92s/it]

[I 2026-05-19 14:24:53,189] Trial 395 finished with value: 0.9498743974527958 and parameters: {'n_estimators': 285, 'learning_rate': 0.04138045530509926, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 83, 'subsample': 0.6713913423960355, 'colsample_bytree': 0.6274571786406021, 'reg_alpha': 3.8850848471043427, 'reg_lambda': 2.531876585988638}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  40%|███████████████████████████████████████████▍                                                                 | 398/1000 [30:06<44:27,  4.43s/it]

[I 2026-05-19 14:24:58,760] Trial 397 finished with value: 0.9498701766922537 and parameters: {'n_estimators': 283, 'learning_rate': 0.04230691415076844, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 84, 'subsample': 0.9852933117192246, 'colsample_bytree': 0.6588680691506844, 'reg_alpha': 3.7144433287067096, 'reg_lambda': 2.8172070358505197}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  40%|███████████████████████████████████████████▍                                                                 | 399/1000 [30:11<43:40,  4.36s/it]

[I 2026-05-19 14:25:03,011] Trial 398 finished with value: 0.949875449616373 and parameters: {'n_estimators': 281, 'learning_rate': 0.04170387349423174, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 92, 'subsample': 0.6006640985925613, 'colsample_bytree': 0.6470877601369446, 'reg_alpha': 3.9154210445500284, 'reg_lambda': 6.243304529980444}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  40%|███████████████████████████████████████████▌                                                                 | 400/1000 [30:14<39:36,  3.96s/it]

[I 2026-05-19 14:25:06,035] Trial 399 finished with value: 0.9498652293750158 and parameters: {'n_estimators': 284, 'learning_rate': 0.04172265721624321, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 91, 'subsample': 0.9875155419215229, 'colsample_bytree': 0.6552835258832417, 'reg_alpha': 3.552449337026766, 'reg_lambda': 2.811457724705791}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  40%|███████████████████████████████████████████▋                                                                 | 401/1000 [30:16<36:23,  3.65s/it]

[I 2026-05-19 14:25:08,947] Trial 401 finished with value: 0.9498724467622411 and parameters: {'n_estimators': 283, 'learning_rate': 0.041864533315643944, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 90, 'subsample': 0.6006756929463782, 'colsample_bytree': 0.6469276462809854, 'reg_alpha': 3.798922018333246, 'reg_lambda': 2.5197568352899262}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  40%|███████████████████████████████████████████▊                                                                 | 402/1000 [30:22<40:35,  4.07s/it]

[I 2026-05-19 14:25:14,009] Trial 400 finished with value: 0.9498677222257635 and parameters: {'n_estimators': 284, 'learning_rate': 0.04214165381206727, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 90, 'subsample': 0.9318062243936329, 'colsample_bytree': 0.6564370285227449, 'reg_alpha': 3.6997494628359657, 'reg_lambda': 2.9543168657484906}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  40%|███████████████████████████████████████████▉                                                                 | 403/1000 [30:24<35:02,  3.52s/it]

[I 2026-05-19 14:25:16,250] Trial 402 finished with value: 0.9498655052666365 and parameters: {'n_estimators': 285, 'learning_rate': 0.041485923652408906, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 81, 'subsample': 0.9074516436815094, 'colsample_bytree': 0.9146547582068334, 'reg_alpha': 3.5506614176008706, 'reg_lambda': 3.2904170902722996}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  40%|███████████████████████████████████████████▏                                                               | 404/1000 [30:41<1:16:40,  7.72s/it]

[I 2026-05-19 14:25:33,752] Trial 404 finished with value: 0.9498746175103886 and parameters: {'n_estimators': 281, 'learning_rate': 0.042394141287666984, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 96, 'subsample': 0.6939904707714717, 'colsample_bytree': 0.6484604878672185, 'reg_alpha': 2.402000852030547, 'reg_lambda': 3.2102890022557014}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  40%|███████████████████████████████████████████▎                                                               | 405/1000 [30:45<1:04:45,  6.53s/it]

[I 2026-05-19 14:25:37,519] Trial 403 finished with value: 0.949869044828754 and parameters: {'n_estimators': 285, 'learning_rate': 0.041852013914750186, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 92, 'subsample': 0.9956488415892534, 'colsample_bytree': 0.6479308586566408, 'reg_alpha': 3.6431414398005537, 'reg_lambda': 2.972411768479}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  41%|████████████████████████████████████████████▎                                                                | 406/1000 [30:46<49:11,  4.97s/it]

[I 2026-05-19 14:25:38,852] Trial 405 finished with value: 0.9498532091012851 and parameters: {'n_estimators': 286, 'learning_rate': 0.042608114460958024, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 79, 'subsample': 0.9040062090893196, 'colsample_bytree': 0.6570044994120388, 'reg_alpha': 2.2259733982518717, 'reg_lambda': 36.39828659260258}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  41%|████████████████████████████████████████████▍                                                                | 408/1000 [31:01<54:40,  5.54s/it]

[I 2026-05-19 14:25:53,470] Trial 407 finished with value: 0.9498691962597242 and parameters: {'n_estimators': 287, 'learning_rate': 0.04326741994594537, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 92, 'subsample': 0.9279323345031305, 'colsample_bytree': 0.6546211008142757, 'reg_alpha': 2.4724219025436533, 'reg_lambda': 6.3702141524986615}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:25:53,559] Trial 406 finished with value: 0.9498743963388204 and parameters: {'n_estimators': 281, 'learning_rate': 0.043103582626160826, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 75, 'subsample': 0.977216187815626, 'colsample_bytree': 0.6476448303952417, 'reg_alpha': 2.806932807114876, 'reg_lambda': 5.9699567497383}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  41%|████████████████████████████████████████████▌                                                                | 409/1000 [31:06<51:36,  5.24s/it]

[I 2026-05-19 14:25:58,119] Trial 409 finished with value: 0.9498586507321981 and parameters: {'n_estimators': 285, 'learning_rate': 0.0406315737391194, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 94, 'subsample': 0.9038817003107004, 'colsample_bytree': 0.6472372541378231, 'reg_alpha': 2.0951350738722416, 'reg_lambda': 48.49813080166087}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  41%|████████████████████████████████████████████▋                                                                | 410/1000 [31:06<38:04,  3.87s/it]

[I 2026-05-19 14:25:58,788] Trial 408 finished with value: 0.9494096317196206 and parameters: {'n_estimators': 287, 'learning_rate': 0.004557973856310546, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 93, 'subsample': 0.9307159762449685, 'colsample_bytree': 0.654108000976385, 'reg_alpha': 2.1563968709409003, 'reg_lambda': 3.363046284067661}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  41%|████████████████████████████████████████████▊                                                                | 411/1000 [31:09<34:09,  3.48s/it]

[I 2026-05-19 14:26:01,360] Trial 410 finished with value: 0.9498725726148756 and parameters: {'n_estimators': 287, 'learning_rate': 0.04060004497950888, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 91, 'subsample': 0.6840774681408751, 'colsample_bytree': 0.6314001210410701, 'reg_alpha': 2.2359834854586627, 'reg_lambda': 3.5499846354444538}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  41%|████████████████████████████████████████████▉                                                                | 412/1000 [31:14<40:15,  4.11s/it]

[I 2026-05-19 14:26:06,949] Trial 412 finished with value: 0.9498542606738243 and parameters: {'n_estimators': 289, 'learning_rate': 0.04085853447167875, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 96, 'subsample': 0.6634029826753237, 'colsample_bytree': 0.6319892393603256, 'reg_alpha': 2.299631773247017, 'reg_lambda': 39.73502391324852}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  41%|█████████████████████████████████████████████                                                                | 413/1000 [31:19<41:13,  4.21s/it]

[I 2026-05-19 14:26:11,402] Trial 411 finished with value: 0.9495755562416066 and parameters: {'n_estimators': 288, 'learning_rate': 0.004577975852805493, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 91, 'subsample': 0.6803484929147794, 'colsample_bytree': 0.630374716115638, 'reg_alpha': 2.333207838740669, 'reg_lambda': 6.032896248415478}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  41%|█████████████████████████████████████████████▏                                                               | 414/1000 [31:25<45:16,  4.63s/it]

[I 2026-05-19 14:26:17,036] Trial 414 finished with value: 0.9498620133004113 and parameters: {'n_estimators': 289, 'learning_rate': 0.0403964660015337, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 95, 'subsample': 0.6879879118430693, 'colsample_bytree': 0.6264460821041506, 'reg_alpha': 2.16966945419865, 'reg_lambda': 33.66321567417596}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  42%|█████████████████████████████████████████████▏                                                               | 415/1000 [31:26<34:25,  3.53s/it]

[I 2026-05-19 14:26:17,970] Trial 413 finished with value: 0.9498657411540815 and parameters: {'n_estimators': 290, 'learning_rate': 0.04038388044824525, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 96, 'subsample': 0.6821531685955486, 'colsample_bytree': 0.6320926197980066, 'reg_alpha': 2.2212438181282246, 'reg_lambda': 3.8848037194468743}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  42%|████████████████████████████████████████████▌                                                              | 416/1000 [31:42<1:12:11,  7.42s/it]

[I 2026-05-19 14:26:34,449] Trial 415 finished with value: 0.9498655703370618 and parameters: {'n_estimators': 291, 'learning_rate': 0.04016424911566432, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 95, 'subsample': 0.6904262304734446, 'colsample_bytree': 0.6302067493121737, 'reg_alpha': 2.02366835809456, 'reg_lambda': 2.2896509491496477}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  42%|█████████████████████████████████████████████▍                                                               | 417/1000 [31:44<56:39,  5.83s/it]

[I 2026-05-19 14:26:36,601] Trial 416 finished with value: 0.9498543547343525 and parameters: {'n_estimators': 289, 'learning_rate': 0.04019680101919831, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 97, 'subsample': 0.6869050019084831, 'colsample_bytree': 0.6318093563273945, 'reg_alpha': 2.240399035910535, 'reg_lambda': 58.59359665195029}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  42%|█████████████████████████████████████████████▌                                                               | 418/1000 [31:47<47:22,  4.88s/it]

[I 2026-05-19 14:26:39,263] Trial 417 finished with value: 0.9498640672951192 and parameters: {'n_estimators': 291, 'learning_rate': 0.04022829355590127, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 98, 'subsample': 0.6910005496557743, 'colsample_bytree': 0.6281135928365295, 'reg_alpha': 2.301701514288464, 'reg_lambda': 3.964295808051949}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  42%|████████████████████████████████████████████▊                                                              | 419/1000 [32:01<1:15:20,  7.78s/it]

[I 2026-05-19 14:26:53,816] Trial 418 finished with value: 0.9498659567394864 and parameters: {'n_estimators': 292, 'learning_rate': 0.04023694767854778, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 99, 'subsample': 0.6829364716260528, 'colsample_bytree': 0.6289648057982307, 'reg_alpha': 2.304423159601006, 'reg_lambda': 3.7289199734731215}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  42%|████████████████████████████████████████████▉                                                              | 420/1000 [32:07<1:08:11,  7.05s/it]

[I 2026-05-19 14:26:59,161] Trial 421 finished with value: 0.9498597453904141 and parameters: {'n_estimators': 290, 'learning_rate': 0.040083946406960703, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 100, 'subsample': 0.6807149634562902, 'colsample_bytree': 0.6717146668268025, 'reg_alpha': 2.4555531225383436, 'reg_lambda': 2.0567444188125776}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  42%|█████████████████████████████████████████████▉                                                               | 421/1000 [32:07<49:37,  5.14s/it]

[I 2026-05-19 14:26:59,852] Trial 420 finished with value: 0.94986336052641 and parameters: {'n_estimators': 289, 'learning_rate': 0.04013940368055415, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 99, 'subsample': 0.6795150171333323, 'colsample_bytree': 0.6726230590416133, 'reg_alpha': 2.3717230510688943, 'reg_lambda': 2.0256787822901856}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  42%|█████████████████████████████████████████████▉                                                               | 422/1000 [32:08<36:35,  3.80s/it]

[I 2026-05-19 14:27:00,521] Trial 422 finished with value: 0.9498717719568696 and parameters: {'n_estimators': 291, 'learning_rate': 0.04012672640717384, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 99, 'subsample': 0.9781959156869492, 'colsample_bytree': 0.6331780186172836, 'reg_alpha': 2.412254045009775, 'reg_lambda': 1.8332005180629094}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  42%|██████████████████████████████████████████████                                                               | 423/1000 [32:11<33:18,  3.46s/it]

[I 2026-05-19 14:27:03,189] Trial 419 finished with value: 0.9498039549199563 and parameters: {'n_estimators': 280, 'learning_rate': 0.01620164179795346, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 96, 'subsample': 0.6910781386795547, 'colsample_bytree': 0.6711784285180641, 'reg_alpha': 2.0361990025995524, 'reg_lambda': 3.850271923442412}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  42%|██████████████████████████████████████████████▏                                                              | 424/1000 [32:14<32:29,  3.38s/it]

[I 2026-05-19 14:27:06,383] Trial 423 finished with value: 0.9498657344497113 and parameters: {'n_estimators': 292, 'learning_rate': 0.040451333104483754, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 76, 'subsample': 0.6896202868450632, 'colsample_bytree': 0.6286327306113444, 'reg_alpha': 2.3715441115694906, 'reg_lambda': 2.042778587311632}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  42%|██████████████████████████████████████████████▎                                                              | 425/1000 [32:24<52:28,  5.48s/it]

[I 2026-05-19 14:27:16,741] Trial 424 finished with value: 0.9498747772270064 and parameters: {'n_estimators': 292, 'learning_rate': 0.04041757141695658, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 98, 'subsample': 0.9700128433133856, 'colsample_bytree': 0.6292549805119706, 'reg_alpha': 2.551147464151233, 'reg_lambda': 2.095618581459461}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  43%|██████████████████████████████████████████████▍                                                              | 426/1000 [32:29<50:34,  5.29s/it]

[I 2026-05-19 14:27:21,608] Trial 425 finished with value: 0.949868029737939 and parameters: {'n_estimators': 293, 'learning_rate': 0.040021236466685275, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 76, 'subsample': 0.686041478687056, 'colsample_bytree': 0.6449640623952834, 'reg_alpha': 2.5703901746261684, 'reg_lambda': 3.857282214488844}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  43%|██████████████████████████████████████████████▌                                                              | 427/1000 [32:29<36:08,  3.78s/it]

[I 2026-05-19 14:27:21,877] Trial 426 finished with value: 0.9498640448886286 and parameters: {'n_estimators': 278, 'learning_rate': 0.03987990566365285, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 99, 'subsample': 0.976821215409944, 'colsample_bytree': 0.6720804452213439, 'reg_alpha': 2.7911632141381295, 'reg_lambda': 2.1379154583360127}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  43%|██████████████████████████████████████████████▋                                                              | 428/1000 [32:34<38:32,  4.04s/it]

[I 2026-05-19 14:27:26,519] Trial 430 finished with value: 0.9497736795015606 and parameters: {'n_estimators': 146, 'learning_rate': 0.018657165408549177, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 114, 'subsample': 0.6741605685108396, 'colsample_bytree': 0.6490708727299411, 'reg_alpha': 2.98900047283371, 'reg_lambda': 1.809458312944609}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  43%|██████████████████████████████████████████████▊                                                              | 429/1000 [32:41<47:51,  5.03s/it]

[I 2026-05-19 14:27:33,840] Trial 428 finished with value: 0.9498629750906593 and parameters: {'n_estimators': 279, 'learning_rate': 0.044004831487276456, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 114, 'subsample': 0.6705097044050508, 'colsample_bytree': 0.6465882444648393, 'reg_alpha': 2.791568114316072, 'reg_lambda': 2.179340059370877}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  43%|██████████████████████████████████████████████▊                                                              | 430/1000 [32:43<38:27,  4.05s/it]

[I 2026-05-19 14:27:35,614] Trial 427 finished with value: 0.9498765011024746 and parameters: {'n_estimators': 294, 'learning_rate': 0.043951255451000336, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 106, 'subsample': 0.6732218005119136, 'colsample_bytree': 0.6474405637874909, 'reg_alpha': 2.7871926390607418, 'reg_lambda': 1.9638618259472467}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  43%|██████████████████████████████████████████████▉                                                              | 431/1000 [32:52<53:03,  5.60s/it]

[I 2026-05-19 14:27:44,820] Trial 429 finished with value: 0.9498226169855728 and parameters: {'n_estimators': 279, 'learning_rate': 0.01881809538204486, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 102, 'subsample': 0.6692520477727489, 'colsample_bytree': 0.718922798400837, 'reg_alpha': 2.8929431607587586, 'reg_lambda': 1.7871663545537038}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  43%|██████████████████████████████████████████████▏                                                            | 432/1000 [33:05<1:14:15,  7.84s/it]

[I 2026-05-19 14:27:57,898] Trial 432 finished with value: 0.9498762282261689 and parameters: {'n_estimators': 278, 'learning_rate': 0.04498458876261468, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 87, 'subsample': 0.6681954479457746, 'colsample_bytree': 0.6462465401394252, 'reg_alpha': 3.1032024920980485, 'reg_lambda': 5.410411459000861}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  43%|███████████████████████████████████████████████▏                                                             | 433/1000 [33:07<56:06,  5.94s/it]

[I 2026-05-19 14:27:59,396] Trial 433 finished with value: 0.9498658547773919 and parameters: {'n_estimators': 280, 'learning_rate': 0.04416392370094633, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 75, 'subsample': 0.6670951159494644, 'colsample_bytree': 0.6456777139827589, 'reg_alpha': 3.149747670794832, 'reg_lambda': 5.418106150276935}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  43%|███████████████████████████████████████████████▎                                                             | 434/1000 [33:09<44:11,  4.68s/it]

[I 2026-05-19 14:28:01,162] Trial 431 finished with value: 0.9498085742193838 and parameters: {'n_estimators': 280, 'learning_rate': 0.016179686427502626, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 75, 'subsample': 0.6703667282198721, 'colsample_bytree': 0.6459320377409632, 'reg_alpha': 3.1038603144270596, 'reg_lambda': 4.3056536234683005}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  44%|███████████████████████████████████████████████▍                                                             | 435/1000 [33:09<32:10,  3.42s/it]

[I 2026-05-19 14:28:01,624] Trial 438 finished with value: 0.9495200855415025 and parameters: {'n_estimators': 279, 'learning_rate': 0.0092488822555483, 'max_depth': 2, 'num_leaves': 13, 'min_child_samples': 105, 'subsample': 0.9910129980775518, 'colsample_bytree': 0.6220966376836349, 'reg_alpha': 3.114473856278134, 'reg_lambda': 5.092328888439512}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  44%|███████████████████████████████████████████████▋                                                             | 437/1000 [33:12<22:17,  2.38s/it]

[I 2026-05-19 14:28:04,698] Trial 435 finished with value: 0.9498735643485665 and parameters: {'n_estimators': 279, 'learning_rate': 0.04379224443373862, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 75, 'subsample': 0.6729609349685616, 'colsample_bytree': 0.6467749877814313, 'reg_alpha': 3.0994560589832205, 'reg_lambda': 5.509835450828484}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:28:04,840] Trial 434 finished with value: 0.9498749407709353 and parameters: {'n_estimators': 280, 'learning_rate': 0.04399723683896518, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 111, 'subsample': 0.669905089726876, 'colsample_bytree': 0.6461606677800432, 'reg_alpha': 3.0824372793759087, 'reg_lambda': 5.137234673639647}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  44%|███████████████████████████████████████████████▋                                                             | 438/1000 [33:15<22:05,  2.36s/it]

[I 2026-05-19 14:28:07,194] Trial 440 finished with value: 0.9498320787951554 and parameters: {'n_estimators': 139, 'learning_rate': 0.04399576986961571, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 106, 'subsample': 0.9707477269887297, 'colsample_bytree': 0.6229960631782109, 'reg_alpha': 1.5803126819333373, 'reg_lambda': 5.615497404895597}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  44%|███████████████████████████████████████████████▊                                                             | 439/1000 [33:20<28:52,  3.09s/it]

[I 2026-05-19 14:28:11,983] Trial 441 finished with value: 0.9498320103450011 and parameters: {'n_estimators': 280, 'learning_rate': 0.04382231632752086, 'max_depth': 2, 'num_leaves': 13, 'min_child_samples': 89, 'subsample': 0.6693196973658131, 'colsample_bytree': 0.6245078071699285, 'reg_alpha': 1.2945745597427643, 'reg_lambda': 5.037061937493671}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  44%|███████████████████████████████████████████████▉                                                             | 440/1000 [33:24<32:21,  3.47s/it]

[I 2026-05-19 14:28:16,315] Trial 436 finished with value: 0.9498724458825134 and parameters: {'n_estimators': 278, 'learning_rate': 0.04404781296302915, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 88, 'subsample': 0.6742132658255677, 'colsample_bytree': 0.6466218056407406, 'reg_alpha': 2.861749990526739, 'reg_lambda': 5.694571895626572}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  44%|████████████████████████████████████████████████                                                             | 441/1000 [33:28<32:51,  3.53s/it]

[I 2026-05-19 14:28:19,981] Trial 437 finished with value: 0.9498674386377708 and parameters: {'n_estimators': 280, 'learning_rate': 0.04373871246516701, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 87, 'subsample': 0.9629267886472404, 'colsample_bytree': 0.647671260406667, 'reg_alpha': 3.0267109518700064, 'reg_lambda': 5.348076269768541}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  44%|████████████████████████████████████████████████▏                                                            | 442/1000 [33:33<37:26,  4.03s/it]

[I 2026-05-19 14:28:25,197] Trial 442 finished with value: 0.9498319893817605 and parameters: {'n_estimators': 293, 'learning_rate': 0.04396343359599333, 'max_depth': 2, 'num_leaves': 13, 'min_child_samples': 75, 'subsample': 0.9713894481040287, 'colsample_bytree': 0.6219509983415634, 'reg_alpha': 1.2183366809227345, 'reg_lambda': 5.142970470648105}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  44%|████████████████████████████████████████████████▎                                                            | 443/1000 [33:36<35:00,  3.77s/it]

[I 2026-05-19 14:28:28,359] Trial 439 finished with value: 0.9498688390881274 and parameters: {'n_estimators': 280, 'learning_rate': 0.04344080183424109, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 87, 'subsample': 0.9647117457057269, 'colsample_bytree': 0.6228612251530378, 'reg_alpha': 4.564066507238122, 'reg_lambda': 5.642522153550254}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  44%|████████████████████████████████████████████████▍                                                            | 444/1000 [33:47<54:50,  5.92s/it]

[I 2026-05-19 14:28:39,299] Trial 444 finished with value: 0.9498339842088569 and parameters: {'n_estimators': 295, 'learning_rate': 0.04408959425971858, 'max_depth': 2, 'num_leaves': 13, 'min_child_samples': 107, 'subsample': 0.9584798473449962, 'colsample_bytree': 0.6612725191697625, 'reg_alpha': 1.2711464605907539, 'reg_lambda': 5.3103365657745485}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  44%|███████████████████████████████████████████████▌                                                           | 445/1000 [34:07<1:34:16, 10.19s/it]

[I 2026-05-19 14:28:59,441] Trial 443 finished with value: 0.9498617324910434 and parameters: {'n_estimators': 280, 'learning_rate': 0.04396739217994682, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 105, 'subsample': 0.9648491452658755, 'colsample_bytree': 0.7684807607980851, 'reg_alpha': 4.5318018388049754, 'reg_lambda': 5.442591501133291}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  45%|████████████████████████████████████████████████▋                                                            | 447/1000 [34:09<50:31,  5.48s/it]

[I 2026-05-19 14:29:01,511] Trial 448 finished with value: 0.9498642986684833 and parameters: {'n_estimators': 295, 'learning_rate': 0.04409782514653102, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 87, 'subsample': 0.9670449368364551, 'colsample_bytree': 0.658402640364925, 'reg_alpha': 1.429680441371099, 'reg_lambda': 5.1624168016567085}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:29:01,683] Trial 446 finished with value: 0.9498656441467492 and parameters: {'n_estimators': 295, 'learning_rate': 0.044322922702437734, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 88, 'subsample': 0.6569733866273865, 'colsample_bytree': 0.6219319784046106, 'reg_alpha': 1.5283147303857034, 'reg_lambda': 3.727190272669946}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  45%|████████████████████████████████████████████████▊                                                            | 448/1000 [34:11<39:29,  4.29s/it]

[I 2026-05-19 14:29:03,200] Trial 451 finished with value: 0.9498606074475318 and parameters: {'n_estimators': 273, 'learning_rate': 0.04455358262944257, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 106, 'subsample': 0.9663895165699485, 'colsample_bytree': 0.663192235679469, 'reg_alpha': 1.6577361561830666, 'reg_lambda': 3.4820733775826027}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  45%|████████████████████████████████████████████████▉                                                            | 449/1000 [34:12<29:48,  3.25s/it]

[I 2026-05-19 14:29:04,018] Trial 445 finished with value: 0.9498602129603535 and parameters: {'n_estimators': 295, 'learning_rate': 0.04361603924346943, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 106, 'subsample': 0.6595003362569973, 'colsample_bytree': 0.7679965049553217, 'reg_alpha': 1.275036438141221, 'reg_lambda': 1.2377503058009607}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  45%|█████████████████████████████████████████████████                                                            | 450/1000 [34:13<23:31,  2.57s/it]

[I 2026-05-19 14:29:05,001] Trial 447 finished with value: 0.9498622326346708 and parameters: {'n_estimators': 274, 'learning_rate': 0.04433840334694217, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 88, 'subsample': 0.9556816746444236, 'colsample_bytree': 0.6539050043168132, 'reg_alpha': 1.2419950596258111, 'reg_lambda': 3.937700250250488}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  45%|█████████████████████████████████████████████████▏                                                           | 451/1000 [34:18<31:35,  3.45s/it]

[I 2026-05-19 14:29:10,515] Trial 449 finished with value: 0.949857386521386 and parameters: {'n_estimators': 295, 'learning_rate': 0.04450461073515382, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 110, 'subsample': 0.6605087166297121, 'colsample_bytree': 0.6615871169119836, 'reg_alpha': 1.4260385561067386, 'reg_lambda': 1.2967104532331644}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  45%|█████████████████████████████████████████████████▎                                                           | 452/1000 [34:20<26:42,  2.92s/it]

[I 2026-05-19 14:29:12,222] Trial 450 finished with value: 0.9498624015906725 and parameters: {'n_estimators': 295, 'learning_rate': 0.044183868377576666, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 86, 'subsample': 0.6581301538493842, 'colsample_bytree': 0.6579284337539526, 'reg_alpha': 1.7132791656262014, 'reg_lambda': 1.23748507595455}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  45%|█████████████████████████████████████████████████▍                                                           | 453/1000 [34:28<42:16,  4.64s/it]

[I 2026-05-19 14:29:20,825] Trial 453 finished with value: 0.9498649655064023 and parameters: {'n_estimators': 276, 'learning_rate': 0.04560257975540262, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 110, 'subsample': 0.6602540557260047, 'colsample_bytree': 0.6667454361448533, 'reg_alpha': 1.7477141535662675, 'reg_lambda': 3.250271361973545}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:29:20,862] Trial 454 finished with value: 0.9498646424445546 and parameters: {'n_estimators': 274, 'learning_rate': 0.04634309787134809, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 106, 'subsample': 0.6618283418662132, 'colsample_bytree': 0.662348447709175, 'reg_alpha': 1.6544651346833426, 'reg_lambda': 3.28989087209831}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  46%|█████████████████████████████████████████████████▌                                                           | 455/1000 [34:30<26:25,  2.91s/it]

[I 2026-05-19 14:29:22,635] Trial 452 finished with value: 0.9498607808843236 and parameters: {'n_estimators': 294, 'learning_rate': 0.04638536861945279, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 76, 'subsample': 0.9543040479954021, 'colsample_bytree': 0.6662228888378302, 'reg_alpha': 4.797900167602944, 'reg_lambda': 3.1761492642830533}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  46%|█████████████████████████████████████████████████▋                                                           | 456/1000 [34:38<36:36,  4.04s/it]

[I 2026-05-19 14:29:30,102] Trial 455 finished with value: 0.9498667741531601 and parameters: {'n_estimators': 273, 'learning_rate': 0.047160163410169605, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 111, 'subsample': 0.6994992274759849, 'colsample_bytree': 0.6564597779407024, 'reg_alpha': 1.7223439328963617, 'reg_lambda': 2.952605363714482}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  46%|████████████████████████████████████████████████▉                                                          | 457/1000 [34:55<1:08:25,  7.56s/it]

[I 2026-05-19 14:29:47,616] Trial 465 finished with value: 0.9497624059766722 and parameters: {'n_estimators': 263, 'learning_rate': 0.047302262531881904, 'max_depth': 1, 'num_leaves': 14, 'min_child_samples': 119, 'subsample': 0.6963110904972947, 'colsample_bytree': 0.6372404789467662, 'reg_alpha': 5.3239398569956204, 'reg_lambda': 9.96824209265733}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  46%|█████████████████████████████████████████████████▉                                                           | 458/1000 [34:57<53:39,  5.94s/it]

[I 2026-05-19 14:29:49,206] Trial 463 finished with value: 0.9498281088238372 and parameters: {'n_estimators': 273, 'learning_rate': 0.046767306860755496, 'max_depth': 4, 'num_leaves': 4, 'min_child_samples': 75, 'subsample': 0.6990064089421809, 'colsample_bytree': 0.6372134292747134, 'reg_alpha': 4.659412297858255, 'reg_lambda': 2.5946385887891688}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  46%|██████████████████████████████████████████████████                                                           | 459/1000 [35:00<47:25,  5.26s/it]

[I 2026-05-19 14:29:52,719] Trial 456 finished with value: 0.9498554411877482 and parameters: {'n_estimators': 274, 'learning_rate': 0.04689345698814606, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 115, 'subsample': 0.7013464172614136, 'colsample_bytree': 0.6620708468897828, 'reg_alpha': 4.841884126669093, 'reg_lambda': 1.3128044136580466}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  46%|██████████████████████████████████████████████████▏                                                          | 460/1000 [35:08<53:57,  6.00s/it]

[I 2026-05-19 14:30:00,553] Trial 466 finished with value: 0.9498272930430943 and parameters: {'n_estimators': 265, 'learning_rate': 0.03839389195763494, 'max_depth': 4, 'num_leaves': 4, 'min_child_samples': 73, 'subsample': 0.7012909598948667, 'colsample_bytree': 0.6390021565481164, 'reg_alpha': 5.810150182408166, 'reg_lambda': 9.397091529063227}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  46%|██████████████████████████████████████████████████▏                                                          | 461/1000 [35:09<40:43,  4.53s/it]

[I 2026-05-19 14:30:01,493] Trial 458 finished with value: 0.9498584787496966 and parameters: {'n_estimators': 273, 'learning_rate': 0.04610486103795836, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 110, 'subsample': 0.9862146544309303, 'colsample_bytree': 0.6552332331980525, 'reg_alpha': 8.270162756288772e-05, 'reg_lambda': 1.2028894190344295}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  46%|██████████████████████████████████████████████████▍                                                          | 463/1000 [35:10<22:00,  2.46s/it]

[I 2026-05-19 14:30:02,285] Trial 457 finished with value: 0.9498597385095982 and parameters: {'n_estimators': 274, 'learning_rate': 0.04602482421645464, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 74, 'subsample': 0.6651351954497254, 'colsample_bytree': 0.6619336738315026, 'reg_alpha': 5.000272296238355, 'reg_lambda': 1.2259848495226728}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:30:02,409] Trial 459 finished with value: 0.9498675278066668 and parameters: {'n_estimators': 275, 'learning_rate': 0.04690745062982145, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 119, 'subsample': 0.6977857611899617, 'colsample_bytree': 0.6631590636254762, 'reg_alpha': 4.949737034663347, 'reg_lambda': 1.4213429834521656}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  46%|██████████████████████████████████████████████████▌                                                          | 464/1000 [35:11<18:29,  2.07s/it]

[I 2026-05-19 14:30:03,551] Trial 460 finished with value: 0.9498668944875479 and parameters: {'n_estimators': 275, 'learning_rate': 0.04776989204672153, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 116, 'subsample': 0.9994944817831439, 'colsample_bytree': 0.6589536930352609, 'reg_alpha': 4.71161466289746, 'reg_lambda': 2.705534248543683}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:30:03,597] Trial 461 finished with value: 0.9498661269041545 and parameters: {'n_estimators': 275, 'learning_rate': 0.04675010918642375, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 118, 'subsample': 0.6969928809999826, 'colsample_bytree': 0.6611717182012707, 'reg_alpha': 4.991954678803909, 'reg_lambda': 2.860292919355826}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  47%|██████████████████████████████████████████████████▊                                                          | 466/1000 [35:17<21:06,  2.37s/it]

[I 2026-05-19 14:30:09,031] Trial 462 finished with value: 0.9498658890795622 and parameters: {'n_estimators': 264, 'learning_rate': 0.04727889607664828, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 73, 'subsample': 0.7068367754578245, 'colsample_bytree': 0.6538015882081086, 'reg_alpha': 5.122303980393372, 'reg_lambda': 2.8043961499383574}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  47%|██████████████████████████████████████████████████▉                                                          | 467/1000 [35:31<46:35,  5.24s/it]

[I 2026-05-19 14:30:23,024] Trial 464 finished with value: 0.9498688149994449 and parameters: {'n_estimators': 287, 'learning_rate': 0.04664707336808163, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 74, 'subsample': 0.6972850361705911, 'colsample_bytree': 0.6376326102900252, 'reg_alpha': 5.020236538546908, 'reg_lambda': 8.894853883781522}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  47%|███████████████████████████████████████████████████                                                          | 468/1000 [35:37<49:20,  5.56s/it]

[I 2026-05-19 14:30:29,512] Trial 467 finished with value: 0.9498606198305595 and parameters: {'n_estimators': 286, 'learning_rate': 0.03878500055898079, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 62, 'subsample': 0.9890031655334831, 'colsample_bytree': 0.6367685747149752, 'reg_alpha': 5.297142058075207, 'reg_lambda': 10.08156172154812}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  47%|██████████████████████████████████████████████████▏                                                        | 469/1000 [35:55<1:18:09,  8.83s/it]

[I 2026-05-19 14:30:47,092] Trial 468 finished with value: 0.9498640655298924 and parameters: {'n_estimators': 287, 'learning_rate': 0.03811060662734885, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 64, 'subsample': 0.9833658185003709, 'colsample_bytree': 0.6370147277259229, 'reg_alpha': 6.079919685739568, 'reg_lambda': 8.862530316942886}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  47%|██████████████████████████████████████████████████▎                                                        | 470/1000 [36:01<1:11:08,  8.05s/it]

[I 2026-05-19 14:30:53,155] Trial 470 finished with value: 0.9498623277403467 and parameters: {'n_estimators': 286, 'learning_rate': 0.0377028317905715, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 61, 'subsample': 0.9868499963763364, 'colsample_bytree': 0.6413657704951047, 'reg_alpha': 6.767652752305326, 'reg_lambda': 8.274769962329632}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  47%|███████████████████████████████████████████████████▎                                                         | 471/1000 [36:01<52:02,  5.90s/it]

[I 2026-05-19 14:30:53,656] Trial 469 finished with value: 0.9497673263115491 and parameters: {'n_estimators': 287, 'learning_rate': 0.01248919670049654, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 81, 'subsample': 0.6734027055355298, 'colsample_bytree': 0.6841850786675969, 'reg_alpha': 6.105260341643539, 'reg_lambda': 8.707506600988737}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  47%|██████████████████████████████████████████████████▌                                                        | 472/1000 [36:11<1:01:02,  6.94s/it]

[I 2026-05-19 14:31:03,115] Trial 476 finished with value: 0.9498636959937251 and parameters: {'n_estimators': 285, 'learning_rate': 0.03854029737140334, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 81, 'subsample': 0.68169755085505, 'colsample_bytree': 0.6480812219402169, 'reg_alpha': 6.68410851624865, 'reg_lambda': 8.129353038367457}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  47%|███████████████████████████████████████████████████▌                                                         | 473/1000 [36:11<44:23,  5.05s/it]

[I 2026-05-19 14:31:03,596] Trial 472 finished with value: 0.9498674216857198 and parameters: {'n_estimators': 287, 'learning_rate': 0.042083693666909505, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 65, 'subsample': 0.6705439455053853, 'colsample_bytree': 0.6501418448577521, 'reg_alpha': 3.4796033202366905, 'reg_lambda': 8.161162841630293}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  47%|███████████████████████████████████████████████████▋                                                         | 474/1000 [36:12<33:25,  3.81s/it]

[I 2026-05-19 14:31:04,485] Trial 474 finished with value: 0.9498551687275413 and parameters: {'n_estimators': 287, 'learning_rate': 0.03804104950359582, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 63, 'subsample': 0.9988860777314551, 'colsample_bytree': 0.6857774703658711, 'reg_alpha': 0.004592750521581663, 'reg_lambda': 8.31053219664264}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  48%|███████████████████████████████████████████████████▊                                                         | 475/1000 [36:16<33:34,  3.84s/it]

[I 2026-05-19 14:31:08,374] Trial 473 finished with value: 0.9497406738299257 and parameters: {'n_estimators': 286, 'learning_rate': 0.007311172589092199, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 64, 'subsample': 0.9970119013126058, 'colsample_bytree': 0.648941330684685, 'reg_alpha': 6.611334614295319, 'reg_lambda': 8.119298122042235}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  48%|███████████████████████████████████████████████████▉                                                         | 476/1000 [36:16<24:37,  2.82s/it]

[I 2026-05-19 14:31:08,800] Trial 475 finished with value: 0.9497724343725281 and parameters: {'n_estimators': 287, 'learning_rate': 0.012626169460475211, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 63, 'subsample': 0.6728455287060385, 'colsample_bytree': 0.6507339312898742, 'reg_alpha': 3.3264013043177716, 'reg_lambda': 8.476621710176902}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  48%|███████████████████████████████████████████████████▉                                                         | 477/1000 [36:19<24:14,  2.78s/it]

[I 2026-05-19 14:31:11,484] Trial 471 finished with value: 0.9496829945760407 and parameters: {'n_estimators': 287, 'learning_rate': 0.006793470218416193, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 63, 'subsample': 0.6723299975649716, 'colsample_bytree': 0.6511662783861277, 'reg_alpha': 6.251049279424559, 'reg_lambda': 8.31269573257297}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  48%|████████████████████████████████████████████████████                                                         | 478/1000 [36:23<26:39,  3.07s/it]

[I 2026-05-19 14:31:15,210] Trial 477 finished with value: 0.9498680104585804 and parameters: {'n_estimators': 287, 'learning_rate': 0.04244207059053067, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 62, 'subsample': 0.6793571036223995, 'colsample_bytree': 0.8083512914712317, 'reg_alpha': 3.2418669443717625, 'reg_lambda': 9.223075760250495}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  48%|████████████████████████████████████████████████████▏                                                        | 479/1000 [36:33<45:53,  5.29s/it]

[I 2026-05-19 14:31:25,705] Trial 478 finished with value: 0.9498452193264303 and parameters: {'n_estimators': 287, 'learning_rate': 0.03826851406748082, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 81, 'subsample': 0.6767529689301186, 'colsample_bytree': 0.6840504035337591, 'reg_alpha': 54.864194776800424, 'reg_lambda': 7.456380388171957}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  48%|████████████████████████████████████████████████████▎                                                        | 480/1000 [36:36<38:42,  4.47s/it]

[I 2026-05-19 14:31:28,252] Trial 479 finished with value: 0.9498659753999773 and parameters: {'n_estimators': 287, 'learning_rate': 0.037656801336655346, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 65, 'subsample': 0.6734290889408974, 'colsample_bytree': 0.6456333011637458, 'reg_alpha': 3.425574391381708, 'reg_lambda': 8.284614196895065}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  48%|████████████████████████████████████████████████████▍                                                        | 481/1000 [36:41<40:24,  4.67s/it]

[I 2026-05-19 14:31:33,406] Trial 484 finished with value: 0.949772288937677 and parameters: {'n_estimators': 280, 'learning_rate': 0.04208116029619799, 'max_depth': 4, 'num_leaves': 2, 'min_child_samples': 131, 'subsample': 0.6781102397122772, 'colsample_bytree': 0.6347321051562397, 'reg_alpha': 3.1519397866565724, 'reg_lambda': 4.3030655105057}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  48%|████████████████████████████████████████████████████▌                                                        | 482/1000 [36:42<30:14,  3.50s/it]

[I 2026-05-19 14:31:34,184] Trial 485 finished with value: 0.9497794911582798 and parameters: {'n_estimators': 280, 'learning_rate': 0.042432237531395404, 'max_depth': 4, 'num_leaves': 2, 'min_child_samples': 52, 'subsample': 0.6792885069411234, 'colsample_bytree': 0.6320069634672671, 'reg_alpha': 3.24098694565345, 'reg_lambda': 4.036560047958217}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  48%|████████████████████████████████████████████████████▋                                                        | 483/1000 [36:55<56:10,  6.52s/it]

[I 2026-05-19 14:31:47,742] Trial 482 finished with value: 0.9498699582894478 and parameters: {'n_estimators': 281, 'learning_rate': 0.042447241077042, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 138, 'subsample': 0.678392902884152, 'colsample_bytree': 0.6487260968069495, 'reg_alpha': 3.226245864934292, 'reg_lambda': 3.8886473139910516}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  48%|████████████████████████████████████████████████████▊                                                        | 484/1000 [36:57<43:54,  5.11s/it]

[I 2026-05-19 14:31:49,556] Trial 480 finished with value: 0.9497297358327155 and parameters: {'n_estimators': 283, 'learning_rate': 0.006977753103568986, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 83, 'subsample': 0.6768361528912512, 'colsample_bytree': 0.6473320226464374, 'reg_alpha': 3.20868764178504, 'reg_lambda': 4.3160118592675545}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  48%|████████████████████████████████████████████████████▊                                                        | 485/1000 [37:05<51:03,  5.95s/it]

[I 2026-05-19 14:31:57,459] Trial 481 finished with value: 0.949862043828638 and parameters: {'n_estimators': 280, 'learning_rate': 0.04231790805661943, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 82, 'subsample': 0.6734225857249083, 'colsample_bytree': 0.6501122205131202, 'reg_alpha': 3.355358974620444, 'reg_lambda': 6.825352255339857}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  49%|████████████████████████████████████████████████████▉                                                        | 486/1000 [37:08<43:11,  5.04s/it]

[I 2026-05-19 14:32:00,390] Trial 486 finished with value: 0.9498619754071942 and parameters: {'n_estimators': 280, 'learning_rate': 0.04222388054294291, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 91, 'subsample': 0.9744470834829908, 'colsample_bytree': 0.6324487333005743, 'reg_alpha': 3.086637619404456, 'reg_lambda': 2.2150582645995875}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  49%|█████████████████████████████████████████████████████                                                        | 487/1000 [37:13<43:35,  5.10s/it]

[I 2026-05-19 14:32:05,604] Trial 483 finished with value: 0.9498677711542015 and parameters: {'n_estimators': 280, 'learning_rate': 0.04202883466924106, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 143, 'subsample': 0.6723788717744686, 'colsample_bytree': 0.6488395103044745, 'reg_alpha': 3.062998991361123, 'reg_lambda': 4.10002732623135}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  49%|█████████████████████████████████████████████████████▏                                                       | 488/1000 [37:14<33:18,  3.90s/it]

[I 2026-05-19 14:32:06,735] Trial 487 finished with value: 0.9498419487388018 and parameters: {'n_estimators': 280, 'learning_rate': 0.04167302800758584, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 53, 'subsample': 0.6771270439405812, 'colsample_bytree': 0.6331553313727408, 'reg_alpha': 57.76703646399002, 'reg_lambda': 3.9969688040657965}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  49%|█████████████████████████████████████████████████████▎                                                       | 489/1000 [37:18<31:29,  3.70s/it]

[I 2026-05-19 14:32:09,954] Trial 489 finished with value: 0.9498752348287338 and parameters: {'n_estimators': 280, 'learning_rate': 0.04216328066008641, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 82, 'subsample': 0.9756138076700942, 'colsample_bytree': 0.6248031819701195, 'reg_alpha': 3.0085027179128776, 'reg_lambda': 4.3815795788045415}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  49%|█████████████████████████████████████████████████████▍                                                       | 490/1000 [37:19<25:33,  3.01s/it]

[I 2026-05-19 14:32:11,339] Trial 488 finished with value: 0.9498760390399006 and parameters: {'n_estimators': 280, 'learning_rate': 0.041268749939414345, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 81, 'subsample': 0.6833719937198659, 'colsample_bytree': 0.6339858579642966, 'reg_alpha': 3.2895110943741215, 'reg_lambda': 4.229250190728979}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  49%|████████████████████████████████████████████████████▌                                                      | 491/1000 [37:40<1:12:07,  8.50s/it]

[I 2026-05-19 14:32:32,679] Trial 492 finished with value: 0.9498702891253149 and parameters: {'n_estimators': 281, 'learning_rate': 0.041778591529935745, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 139, 'subsample': 0.6535726972152813, 'colsample_bytree': 0.6241150559797001, 'reg_alpha': 2.9152831088617566, 'reg_lambda': 1.903658325031264}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  49%|█████████████████████████████████████████████████████▋                                                       | 492/1000 [37:41<52:26,  6.19s/it]

[I 2026-05-19 14:32:33,499] Trial 490 finished with value: 0.9497809783711396 and parameters: {'n_estimators': 281, 'learning_rate': 0.011499557698277797, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 81, 'subsample': 0.6522261606342535, 'colsample_bytree': 0.6327029855948071, 'reg_alpha': 2.994792677620157, 'reg_lambda': 4.217254159274526}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  49%|█████████████████████████████████████████████████████▋                                                       | 493/1000 [37:42<39:25,  4.67s/it]

[I 2026-05-19 14:32:34,571] Trial 491 finished with value: 0.9497838807281754 and parameters: {'n_estimators': 281, 'learning_rate': 0.01147425018822518, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 50, 'subsample': 0.9490978421348689, 'colsample_bytree': 0.6327143081790421, 'reg_alpha': 2.9224545335211336, 'reg_lambda': 4.113320915340264}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  49%|█████████████████████████████████████████████████████▊                                                       | 494/1000 [37:43<30:00,  3.56s/it]

[I 2026-05-19 14:32:35,565] Trial 493 finished with value: 0.9497727351811667 and parameters: {'n_estimators': 280, 'learning_rate': 0.011113920297489132, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 54, 'subsample': 0.9492831068967994, 'colsample_bytree': 0.6242629975559542, 'reg_alpha': 2.8254834697055053, 'reg_lambda': 2.404721097478636}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  50%|█████████████████████████████████████████████████████▉                                                       | 495/1000 [37:54<49:22,  5.87s/it]

[I 2026-05-19 14:32:46,789] Trial 495 finished with value: 0.9498663885213776 and parameters: {'n_estimators': 268, 'learning_rate': 0.04102458153635837, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 92, 'subsample': 0.9779872575781655, 'colsample_bytree': 0.6220316550209389, 'reg_alpha': 1.9522601405461804, 'reg_lambda': 2.1717402249060878}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  50%|██████████████████████████████████████████████████████                                                       | 496/1000 [37:55<35:13,  4.19s/it]

[I 2026-05-19 14:32:47,067] Trial 494 finished with value: 0.9498685056370645 and parameters: {'n_estimators': 268, 'learning_rate': 0.04073836730135239, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 81, 'subsample': 0.971045821135866, 'colsample_bytree': 0.6247219302171662, 'reg_alpha': 3.885327864087413, 'reg_lambda': 1.780081768434279}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  50%|██████████████████████████████████████████████████████▏                                                      | 497/1000 [38:04<48:56,  5.84s/it]

[I 2026-05-19 14:32:56,774] Trial 496 finished with value: 0.9498654161329332 and parameters: {'n_estimators': 268, 'learning_rate': 0.04119076460503157, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 93, 'subsample': 0.6638300170679933, 'colsample_bytree': 0.9710893649885529, 'reg_alpha': 2.3030049483108854, 'reg_lambda': 1.9556880558247973}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  50%|██████████████████████████████████████████████████████▎                                                      | 498/1000 [38:12<52:54,  6.32s/it]

[I 2026-05-19 14:33:04,228] Trial 499 finished with value: 0.9498682936444407 and parameters: {'n_estimators': 268, 'learning_rate': 0.04027543558039254, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 93, 'subsample': 0.6644770947007896, 'colsample_bytree': 0.6208515180819804, 'reg_alpha': 2.095606980672412, 'reg_lambda': 2.2199991999245157}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  50%|██████████████████████████████████████████████████████▍                                                      | 499/1000 [38:12<38:06,  4.56s/it]

[I 2026-05-19 14:33:04,700] Trial 497 finished with value: 0.9498670639993115 and parameters: {'n_estimators': 292, 'learning_rate': 0.04084062747237974, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 55, 'subsample': 0.9515265873604614, 'colsample_bytree': 0.6242206869709128, 'reg_alpha': 2.0536307990940563, 'reg_lambda': 2.200216390043919}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  50%|██████████████████████████████████████████████████████▌                                                      | 500/1000 [38:15<34:24,  4.13s/it]

[I 2026-05-19 14:33:07,797] Trial 501 finished with value: 0.9498628665009695 and parameters: {'n_estimators': 268, 'learning_rate': 0.04972441785313607, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 70, 'subsample': 0.9750358021759964, 'colsample_bytree': 0.6207066199891415, 'reg_alpha': 2.0584346382775056, 'reg_lambda': 2.1927355263000785}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  50%|██████████████████████████████████████████████████████▌                                                      | 501/1000 [38:18<31:19,  3.77s/it]

[I 2026-05-19 14:33:10,720] Trial 498 finished with value: 0.949843015423709 and parameters: {'n_estimators': 268, 'learning_rate': 0.04050947546683895, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 55, 'subsample': 0.665746773953967, 'colsample_bytree': 0.976620729679638, 'reg_alpha': 0.047890344644153135, 'reg_lambda': 2.25916864809113}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  50%|██████████████████████████████████████████████████████▋                                                      | 502/1000 [38:24<36:13,  4.36s/it]

[I 2026-05-19 14:33:16,494] Trial 500 finished with value: 0.9497704308913665 and parameters: {'n_estimators': 265, 'learning_rate': 0.0135868578426063, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 78, 'subsample': 0.9476528089733071, 'colsample_bytree': 0.8251795523953818, 'reg_alpha': 2.1541430854139834, 'reg_lambda': 2.5835771099831004}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  50%|█████████████████████████████████████████████████████▊                                                     | 503/1000 [38:38<1:00:15,  7.27s/it]

[I 2026-05-19 14:33:30,535] Trial 503 finished with value: 0.9498551914958885 and parameters: {'n_estimators': 268, 'learning_rate': 0.039584602846822574, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 72, 'subsample': 0.8849131105772069, 'colsample_bytree': 0.6221361231458438, 'reg_alpha': 1.9609842918395062, 'reg_lambda': 2.315390465438611}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  50%|██████████████████████████████████████████████████████▉                                                      | 504/1000 [38:39<44:48,  5.42s/it]

[I 2026-05-19 14:33:31,651] Trial 505 finished with value: 0.9498662047036956 and parameters: {'n_estimators': 270, 'learning_rate': 0.03986003695187188, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 71, 'subsample': 0.9794178283458027, 'colsample_bytree': 0.6215890041918446, 'reg_alpha': 1.9402091678608882, 'reg_lambda': 5.905448235198338}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  50%|███████████████████████████████████████████████████████                                                      | 505/1000 [38:42<38:30,  4.67s/it]

[I 2026-05-19 14:33:34,543] Trial 504 finished with value: 0.9497893193088867 and parameters: {'n_estimators': 267, 'learning_rate': 0.01491740179287906, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 70, 'subsample': 0.663811729180157, 'colsample_bytree': 0.6237633990738869, 'reg_alpha': 2.059636980262871, 'reg_lambda': 5.586932260641322}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  51%|███████████████████████████████████████████████████████▏                                                     | 506/1000 [38:45<34:55,  4.24s/it]

[I 2026-05-19 14:33:37,798] Trial 502 finished with value: 0.9498558711890063 and parameters: {'n_estimators': 269, 'learning_rate': 0.04016318604992834, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 71, 'subsample': 0.9766814097542074, 'colsample_bytree': 0.7892421345249475, 'reg_alpha': 0.008352780159716734, 'reg_lambda': 2.4283906023082347}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  51%|███████████████████████████████████████████████████████▎                                                     | 507/1000 [38:55<47:41,  5.80s/it]

[I 2026-05-19 14:33:47,246] Trial 506 finished with value: 0.9498613197440026 and parameters: {'n_estimators': 270, 'learning_rate': 0.03980971619286636, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 69, 'subsample': 0.6652131949301324, 'colsample_bytree': 0.64061379517947, 'reg_alpha': 1.8609759319009918, 'reg_lambda': 5.831708156221944}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:33:47,263] Trial 507 finished with value: 0.9498591639249924 and parameters: {'n_estimators': 269, 'learning_rate': 0.049184655800440055, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 71, 'subsample': 0.978405971873534, 'colsample_bytree': 0.9712339129240233, 'reg_alpha': 2.0608299472020626, 'reg_lambda': 5.562655432100142}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  51%|███████████████████████████████████████████████████████▍                                                     | 509/1000 [39:05<44:16,  5.41s/it]

[I 2026-05-19 14:33:57,100] Trial 508 finished with value: 0.9498573132475434 and parameters: {'n_estimators': 292, 'learning_rate': 0.04990971959559224, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 71, 'subsample': 0.8781703374110559, 'colsample_bytree': 0.6411573644854343, 'reg_alpha': 0.0328199934192818, 'reg_lambda': 6.171771199124881}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  51%|███████████████████████████████████████████████████████▌                                                     | 510/1000 [39:08<39:17,  4.81s/it]

[I 2026-05-19 14:34:00,147] Trial 510 finished with value: 0.9498655014120054 and parameters: {'n_estimators': 263, 'learning_rate': 0.04969037044077394, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 71, 'subsample': 0.6888606330861229, 'colsample_bytree': 0.6417425521504866, 'reg_alpha': 6.945893758078776, 'reg_lambda': 5.727998584687172}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  51%|███████████████████████████████████████████████████████▋                                                     | 511/1000 [39:14<43:02,  5.28s/it]

[I 2026-05-19 14:34:06,764] Trial 511 finished with value: 0.9498595399761985 and parameters: {'n_estimators': 293, 'learning_rate': 0.044479030446718575, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 72, 'subsample': 0.6860334814665238, 'colsample_bytree': 0.6423685947865868, 'reg_alpha': 0.008194250273677187, 'reg_lambda': 5.902888625776528}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  51%|███████████████████████████████████████████████████████▊                                                     | 512/1000 [39:15<31:44,  3.90s/it]

[I 2026-05-19 14:34:06,972] Trial 509 finished with value: 0.9498373464797003 and parameters: {'n_estimators': 292, 'learning_rate': 0.022490489110772564, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 69, 'subsample': 0.9749011334612699, 'colsample_bytree': 0.6424657051831961, 'reg_alpha': 7.334324576506735, 'reg_lambda': 5.678240059177828}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  51%|███████████████████████████████████████████████████████▉                                                     | 513/1000 [39:18<30:42,  3.78s/it]

[I 2026-05-19 14:34:10,457] Trial 512 finished with value: 0.9498673368923438 and parameters: {'n_estimators': 293, 'learning_rate': 0.04449580523773349, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 73, 'subsample': 0.9801258511841644, 'colsample_bytree': 0.6431675507032018, 'reg_alpha': 7.591735693391844, 'reg_lambda': 5.585637115786096}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  51%|████████████████████████████████████████████████████████                                                     | 514/1000 [39:22<32:17,  3.99s/it]

[I 2026-05-19 14:34:14,943] Trial 513 finished with value: 0.9498723686815209 and parameters: {'n_estimators': 275, 'learning_rate': 0.04391791585850071, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 72, 'subsample': 0.6879584271947765, 'colsample_bytree': 0.6414575620783644, 'reg_alpha': 7.739827731869698, 'reg_lambda': 5.91017057095549}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  52%|████████████████████████████████████████████████████████▏                                                    | 515/1000 [39:37<57:43,  7.14s/it]

[I 2026-05-19 14:34:29,818] Trial 514 finished with value: 0.9498597310594514 and parameters: {'n_estimators': 293, 'learning_rate': 0.0442975511121628, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 70, 'subsample': 0.6873231717205189, 'colsample_bytree': 0.6432326183376289, 'reg_alpha': 7.1086438184854295, 'reg_lambda': 5.342880386303767}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  52%|████████████████████████████████████████████████████████▏                                                    | 516/1000 [39:39<43:58,  5.45s/it]

[I 2026-05-19 14:34:31,166] Trial 516 finished with value: 0.949865111749576 and parameters: {'n_estimators': 275, 'learning_rate': 0.044417735368222126, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 75, 'subsample': 0.6887420078701028, 'colsample_bytree': 0.6403527064946649, 'reg_alpha': 7.627044526844359, 'reg_lambda': 5.626706862158039}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  52%|████████████████████████████████████████████████████████▎                                                    | 517/1000 [39:42<37:45,  4.69s/it]

[I 2026-05-19 14:34:34,042] Trial 515 finished with value: 0.9498573174858842 and parameters: {'n_estimators': 275, 'learning_rate': 0.04439740729073257, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 101, 'subsample': 0.9900339176545334, 'colsample_bytree': 0.9998248328039809, 'reg_alpha': 0.009498964960433717, 'reg_lambda': 5.904435720382755}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  52%|████████████████████████████████████████████████████████▍                                                    | 518/1000 [39:49<43:29,  5.41s/it]

[I 2026-05-19 14:34:41,172] Trial 517 finished with value: 0.9498600300148949 and parameters: {'n_estimators': 294, 'learning_rate': 0.0447124314815126, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 77, 'subsample': 0.6878227270934708, 'colsample_bytree': 0.6418699264812109, 'reg_alpha': 7.383219180710257, 'reg_lambda': 6.068026530232651}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  52%|████████████████████████████████████████████████████████▌                                                    | 519/1000 [39:55<45:23,  5.66s/it]

[I 2026-05-19 14:34:47,427] Trial 519 finished with value: 0.9498603130655052 and parameters: {'n_estimators': 293, 'learning_rate': 0.0445259279464467, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 153, 'subsample': 0.9872143831684155, 'colsample_bytree': 0.6420455286402255, 'reg_alpha': 7.5433222503177255, 'reg_lambda': 3.397608261074044}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  52%|████████████████████████████████████████████████████████▋                                                    | 520/1000 [40:01<44:55,  5.62s/it]

[I 2026-05-19 14:34:52,946] Trial 520 finished with value: 0.9498619235490272 and parameters: {'n_estimators': 276, 'learning_rate': 0.04425815670028961, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 101, 'subsample': 0.6920138961153097, 'colsample_bytree': 0.6412750926316424, 'reg_alpha': 7.081395462706661, 'reg_lambda': 3.586748866164847}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:34:53,134] Trial 518 finished with value: 0.9498381743912901 and parameters: {'n_estimators': 292, 'learning_rate': 0.02216619292295163, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 101, 'subsample': 0.6519491972189303, 'colsample_bytree': 0.6418622788289586, 'reg_alpha': 4.296084314491235, 'reg_lambda': 3.385128861915988}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  52%|████████████████████████████████████████████████████████▉                                                    | 522/1000 [40:06<34:55,  4.38s/it]

[I 2026-05-19 14:34:58,419] Trial 521 finished with value: 0.9498693584738046 and parameters: {'n_estimators': 276, 'learning_rate': 0.04468819636536231, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 101, 'subsample': 0.6487000414755385, 'colsample_bytree': 0.6427426497902496, 'reg_alpha': 4.483917916637153, 'reg_lambda': 3.2857531642592246}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  52%|█████████████████████████████████████████████████████████                                                    | 523/1000 [40:11<35:26,  4.46s/it]

[I 2026-05-19 14:35:03,053] Trial 522 finished with value: 0.9498718607198919 and parameters: {'n_estimators': 278, 'learning_rate': 0.04415533099554714, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 86, 'subsample': 0.6518305910721084, 'colsample_bytree': 0.6364040505319135, 'reg_alpha': 4.411458375924224, 'reg_lambda': 3.3678832715891946}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  52%|█████████████████████████████████████████████████████████                                                    | 524/1000 [40:14<33:00,  4.16s/it]

[I 2026-05-19 14:35:06,533] Trial 523 finished with value: 0.9498609349931758 and parameters: {'n_estimators': 277, 'learning_rate': 0.03667913592765869, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 247, 'subsample': 0.6508088471489494, 'colsample_bytree': 0.6343615813365321, 'reg_alpha': 1.00110526587183e-05, 'reg_lambda': 3.5299303675121037}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  52%|█████████████████████████████████████████████████████████▏                                                   | 525/1000 [40:19<34:40,  4.38s/it]

[I 2026-05-19 14:35:11,407] Trial 525 finished with value: 0.9498621788283506 and parameters: {'n_estimators': 276, 'learning_rate': 0.04519852225013966, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 102, 'subsample': 0.7086524109280108, 'colsample_bytree': 0.6359502728498211, 'reg_alpha': 3.9377060161546678, 'reg_lambda': 3.016175423366317}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  53%|█████████████████████████████████████████████████████████▎                                                   | 526/1000 [40:20<25:36,  3.24s/it]

[I 2026-05-19 14:35:11,999] Trial 524 finished with value: 0.9498603956659253 and parameters: {'n_estimators': 278, 'learning_rate': 0.03732015590274672, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 100, 'subsample': 0.9919845002502622, 'colsample_bytree': 0.6349815828265862, 'reg_alpha': 4.221769563805311, 'reg_lambda': 3.4356368993465085}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  53%|█████████████████████████████████████████████████████████▍                                                   | 527/1000 [40:23<26:12,  3.33s/it]

[I 2026-05-19 14:35:15,515] Trial 527 finished with value: 0.949836636389074 and parameters: {'n_estimators': 276, 'learning_rate': 0.03590471831857773, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 86, 'subsample': 0.9935206794059772, 'colsample_bytree': 0.6326236226407826, 'reg_alpha': 4.2743362739445905, 'reg_lambda': 3.3725518332031115}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  53%|█████████████████████████████████████████████████████████▌                                                   | 528/1000 [40:34<44:39,  5.68s/it]

[I 2026-05-19 14:35:26,692] Trial 528 finished with value: 0.9498428564666084 and parameters: {'n_estimators': 276, 'learning_rate': 0.03666520338770315, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 83, 'subsample': 0.7197481377457556, 'colsample_bytree': 0.6334826527452445, 'reg_alpha': 4.171937712594098, 'reg_lambda': 3.688163556639734}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  53%|█████████████████████████████████████████████████████████▋                                                   | 529/1000 [40:36<34:24,  4.38s/it]

[I 2026-05-19 14:35:28,056] Trial 526 finished with value: 0.9498593045104929 and parameters: {'n_estimators': 275, 'learning_rate': 0.037259266758091665, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 101, 'subsample': 0.6031017155227556, 'colsample_bytree': 0.6336816059500855, 'reg_alpha': 4.410901111594267, 'reg_lambda': 3.181526458589185}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  53%|█████████████████████████████████████████████████████████▊                                                   | 530/1000 [40:40<33:19,  4.26s/it]

[I 2026-05-19 14:35:32,005] Trial 529 finished with value: 0.9498439999458359 and parameters: {'n_estimators': 277, 'learning_rate': 0.03672215904918967, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 85, 'subsample': 0.6020711902998674, 'colsample_bytree': 0.632300424612647, 'reg_alpha': 4.3371239518844344, 'reg_lambda': 3.4166637781908404}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  53%|█████████████████████████████████████████████████████████▉                                                   | 531/1000 [40:43<32:13,  4.12s/it]

[I 2026-05-19 14:35:35,825] Trial 530 finished with value: 0.9498459508110446 and parameters: {'n_estimators': 278, 'learning_rate': 0.036638631784607606, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 85, 'subsample': 0.7100845988922035, 'colsample_bytree': 0.6334027878256511, 'reg_alpha': 4.342710875602368, 'reg_lambda': 3.7577437293018927}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  53%|█████████████████████████████████████████████████████████▉                                                   | 532/1000 [40:50<36:58,  4.74s/it]

[I 2026-05-19 14:35:41,999] Trial 531 finished with value: 0.9498429284966073 and parameters: {'n_estimators': 277, 'learning_rate': 0.03714908840042463, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 86, 'subsample': 0.6499342433498312, 'colsample_bytree': 0.6321894871929667, 'reg_alpha': 4.21848991395121, 'reg_lambda': 11.780586153297}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  53%|██████████████████████████████████████████████████████████                                                   | 533/1000 [40:55<38:19,  4.92s/it]

[I 2026-05-19 14:35:47,357] Trial 533 finished with value: 0.9498483932190258 and parameters: {'n_estimators': 279, 'learning_rate': 0.03689102429887018, 'max_depth': 3, 'num_leaves': 10, 'min_child_samples': 85, 'subsample': 0.6062286816312574, 'colsample_bytree': 0.6327974818233, 'reg_alpha': 4.244639884526665, 'reg_lambda': 3.828208028365889}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  53%|██████████████████████████████████████████████████████████▏                                                  | 534/1000 [41:07<54:19,  6.99s/it]

[I 2026-05-19 14:35:59,190] Trial 532 finished with value: 0.9498607738379594 and parameters: {'n_estimators': 277, 'learning_rate': 0.037050706431322716, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 86, 'subsample': 0.6010451730523668, 'colsample_bytree': 0.8907673558896538, 'reg_alpha': 4.5130645049895, 'reg_lambda': 12.212509324480589}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  54%|██████████████████████████████████████████████████████████▎                                                  | 535/1000 [41:12<49:18,  6.36s/it]

[I 2026-05-19 14:36:04,062] Trial 535 finished with value: 0.9498665520061504 and parameters: {'n_estimators': 284, 'learning_rate': 0.036915799210668745, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 85, 'subsample': 0.7100830298399321, 'colsample_bytree': 0.6550836042366507, 'reg_alpha': 4.122679210388201, 'reg_lambda': 0.01059076390039561}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  54%|██████████████████████████████████████████████████████████▍                                                  | 536/1000 [41:12<36:15,  4.69s/it]

[I 2026-05-19 14:36:04,842] Trial 536 finished with value: 0.9498420733802988 and parameters: {'n_estimators': 282, 'learning_rate': 0.03779465039402979, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 87, 'subsample': 0.7198791680313847, 'colsample_bytree': 0.6548429277362576, 'reg_alpha': 4.4174141034092775, 'reg_lambda': 14.201046561927823}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  54%|██████████████████████████████████████████████████████████▌                                                  | 537/1000 [41:15<31:11,  4.04s/it]

[I 2026-05-19 14:36:07,396] Trial 534 finished with value: 0.9498609508534965 and parameters: {'n_estimators': 282, 'learning_rate': 0.036778679177140484, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 86, 'subsample': 0.6094037834494661, 'colsample_bytree': 0.6544305777596956, 'reg_alpha': 4.231862568251593, 'reg_lambda': 11.155610601322277}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  54%|██████████████████████████████████████████████████████████▋                                                  | 538/1000 [41:21<35:03,  4.55s/it]

[I 2026-05-19 14:36:13,133] Trial 537 finished with value: 0.9498588154900707 and parameters: {'n_estimators': 283, 'learning_rate': 0.03691810753613458, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 84, 'subsample': 0.60248090031856, 'colsample_bytree': 0.6521146308405168, 'reg_alpha': 4.434522751672215, 'reg_lambda': 13.223311677763055}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  54%|██████████████████████████████████████████████████████████▊                                                  | 539/1000 [41:30<46:46,  6.09s/it]

[I 2026-05-19 14:36:22,799] Trial 538 finished with value: 0.9498660525383951 and parameters: {'n_estimators': 300, 'learning_rate': 0.03800927006716162, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 84, 'subsample': 0.60178825964242, 'colsample_bytree': 0.6559564715339746, 'reg_alpha': 4.459145536343675, 'reg_lambda': 11.264801405969743}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  54%|██████████████████████████████████████████████████████████▊                                                  | 540/1000 [41:35<43:53,  5.73s/it]

[I 2026-05-19 14:36:27,685] Trial 539 finished with value: 0.949863017786325 and parameters: {'n_estimators': 283, 'learning_rate': 0.04716764904872053, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 60, 'subsample': 0.605636770963146, 'colsample_bytree': 0.6558146765628353, 'reg_alpha': 10.378534014576971, 'reg_lambda': 11.18581744912857}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  54%|██████████████████████████████████████████████████████████▉                                                  | 541/1000 [41:36<31:47,  4.16s/it]

[I 2026-05-19 14:36:28,151] Trial 540 finished with value: 0.9490623678846168 and parameters: {'n_estimators': 261, 'learning_rate': 0.0038217548586348946, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 91, 'subsample': 0.6076756291217016, 'colsample_bytree': 0.6545051106472919, 'reg_alpha': 10.269199907378754, 'reg_lambda': 13.092304482583721}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  54%|███████████████████████████████████████████████████████████                                                  | 542/1000 [41:39<29:57,  3.93s/it]

[I 2026-05-19 14:36:31,571] Trial 542 finished with value: 0.9498681115500824 and parameters: {'n_estimators': 283, 'learning_rate': 0.046956673736183625, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 59, 'subsample': 0.605518781793972, 'colsample_bytree': 0.654606619552656, 'reg_alpha': 2.5429288734064426, 'reg_lambda': 12.021408210543596}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  54%|███████████████████████████████████████████████████████████▏                                                 | 543/1000 [41:43<28:58,  3.80s/it]

[I 2026-05-19 14:36:35,081] Trial 541 finished with value: 0.9498677486652343 and parameters: {'n_estimators': 283, 'learning_rate': 0.0474986085853661, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 78, 'subsample': 0.6063689762399247, 'colsample_bytree': 0.6187170705257239, 'reg_alpha': 10.412596474394169, 'reg_lambda': 10.816952670275949}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  54%|███████████████████████████████████████████████████████████▎                                                 | 544/1000 [41:46<27:23,  3.60s/it]

[I 2026-05-19 14:36:38,165] Trial 545 finished with value: 0.9498156567513355 and parameters: {'n_estimators': 300, 'learning_rate': 0.04682689591661722, 'max_depth': 4, 'num_leaves': 3, 'min_child_samples': 58, 'subsample': 0.609896340890035, 'colsample_bytree': 0.6556124057982243, 'reg_alpha': 10.127540256175664, 'reg_lambda': 1.626339595585266}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  55%|███████████████████████████████████████████████████████████▍                                                 | 545/1000 [41:50<28:41,  3.78s/it]

[I 2026-05-19 14:36:42,390] Trial 543 finished with value: 0.9498557695267301 and parameters: {'n_estimators': 284, 'learning_rate': 0.04733148703231384, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 56, 'subsample': 0.6099439419443996, 'colsample_bytree': 0.6533994280389669, 'reg_alpha': 10.580397567793336, 'reg_lambda': 12.636691954470585}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  55%|███████████████████████████████████████████████████████████▌                                                 | 546/1000 [41:54<29:27,  3.89s/it]

[I 2026-05-19 14:36:46,582] Trial 552 pruned.

Best trial: 302. Best value: 0.949877:  55%|███████████████████████████████████████████████████████████▌                                                 | 547/1000 [41:57<28:00,  3.71s/it]

[I 2026-05-19 14:36:49,838] Trial 544 finished with value: 0.9498600447589849 and parameters: {'n_estimators': 284, 'learning_rate': 0.04709149924134839, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 58, 'subsample': 0.6074777833901329, 'colsample_bytree': 0.654491761202034, 'reg_alpha': 10.652060060476495, 'reg_lambda': 11.705162168028656}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  55%|███████████████████████████████████████████████████████████▋                                                 | 548/1000 [42:15<59:16,  7.87s/it]

[I 2026-05-19 14:37:07,427] Trial 547 finished with value: 0.9498603575670383 and parameters: {'n_estimators': 288, 'learning_rate': 0.04665547930946622, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 57, 'subsample': 0.6000219379305833, 'colsample_bytree': 0.6251946852074501, 'reg_alpha': 10.014641656519855, 'reg_lambda': 4.552700412214378}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  55%|███████████████████████████████████████████████████████████▊                                                 | 549/1000 [42:17<46:37,  6.20s/it]

[I 2026-05-19 14:37:09,745] Trial 556 finished with value: 0.9497749239099816 and parameters: {'n_estimators': 288, 'learning_rate': 0.04243597471821484, 'max_depth': 1, 'num_leaves': 14, 'min_child_samples': 45, 'subsample': 0.625325510573041, 'colsample_bytree': 0.6201899217698793, 'reg_alpha': 1.0091483893936333, 'reg_lambda': 20.424232408219755}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  55%|███████████████████████████████████████████████████████████▉                                                 | 550/1000 [42:19<36:40,  4.89s/it]

[I 2026-05-19 14:37:11,564] Trial 548 finished with value: 0.9496265819274698 and parameters: {'n_estimators': 260, 'learning_rate': 0.005587462335587011, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 58, 'subsample': 0.6045064164235294, 'colsample_bytree': 0.6225553745053286, 'reg_alpha': 9.406517134312926, 'reg_lambda': 1.5488871870051761}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:37:11,665] Trial 546 finished with value: 0.9498570684991835 and parameters: {'n_estimators': 300, 'learning_rate': 0.0393354024991904, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 60, 'subsample': 0.6073493073555466, 'colsample_bytree': 0.6556877878322117, 'reg_alpha': 0.8236875915782451, 'reg_lambda': 0.21297558270468667}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  55%|████████████████████████████████████████████████████████████▏                                                | 552/1000 [42:20<20:59,  2.81s/it]

[I 2026-05-19 14:37:12,327] Trial 549 finished with value: 0.9498677660756305 and parameters: {'n_estimators': 287, 'learning_rate': 0.04738601903096731, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 60, 'subsample': 0.62507041186811, 'colsample_bytree': 0.6191504522652955, 'reg_alpha': 0.894968213052412, 'reg_lambda': 22.933143453240067}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  55%|████████████████████████████████████████████████████████████▎                                                | 553/1000 [42:24<23:02,  3.09s/it]

[I 2026-05-19 14:37:16,288] Trial 550 finished with value: 0.9498685316445933 and parameters: {'n_estimators': 262, 'learning_rate': 0.047265068498215886, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 58, 'subsample': 0.6240353905550593, 'colsample_bytree': 0.6178110614346084, 'reg_alpha': 2.4925893448866407, 'reg_lambda': 1.6799012330083765}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  55%|████████████████████████████████████████████████████████████▍                                                | 554/1000 [42:28<25:55,  3.49s/it]

[I 2026-05-19 14:37:20,890] Trial 551 finished with value: 0.949870918913166 and parameters: {'n_estimators': 261, 'learning_rate': 0.04738087888351836, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 94, 'subsample': 0.6251939387148684, 'colsample_bytree': 0.6185214374043817, 'reg_alpha': 2.5306165576185666, 'reg_lambda': 1.549404082262201}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  56%|████████████████████████████████████████████████████████████▍                                                | 555/1000 [42:38<37:42,  5.08s/it]

[I 2026-05-19 14:37:30,252] Trial 553 finished with value: 0.9498682630982582 and parameters: {'n_estimators': 288, 'learning_rate': 0.04233226787512213, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 77, 'subsample': 0.6154806449506155, 'colsample_bytree': 0.618934525814956, 'reg_alpha': 2.928661327843198, 'reg_lambda': 1.491728220691123}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  56%|████████████████████████████████████████████████████████████▌                                                | 556/1000 [42:44<40:44,  5.50s/it]

[I 2026-05-19 14:37:36,834] Trial 554 finished with value: 0.9498630574538789 and parameters: {'n_estimators': 288, 'learning_rate': 0.042147576778883554, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 77, 'subsample': 0.6233087657793914, 'colsample_bytree': 0.6175329222198169, 'reg_alpha': 1.0505239900606724, 'reg_lambda': 4.512696854576414}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  56%|████████████████████████████████████████████████████████████▋                                                | 557/1000 [42:45<29:37,  4.01s/it]

[I 2026-05-19 14:37:37,111] Trial 555 finished with value: 0.9498737592693953 and parameters: {'n_estimators': 289, 'learning_rate': 0.04245284575409605, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 93, 'subsample': 0.6270890458224712, 'colsample_bytree': 0.616539572869101, 'reg_alpha': 2.891306326836825, 'reg_lambda': 4.978604159342146}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  56%|████████████████████████████████████████████████████████████▊                                                | 558/1000 [42:52<37:32,  5.10s/it]

[I 2026-05-19 14:37:44,857] Trial 557 finished with value: 0.949857863743269 and parameters: {'n_estimators': 290, 'learning_rate': 0.04213963360436137, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 93, 'subsample': 0.6222266682145207, 'colsample_bytree': 0.6269689236290084, 'reg_alpha': 0.7995070616737926, 'reg_lambda': 4.8551687132076555}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  56%|████████████████████████████████████████████████████████████▉                                                | 559/1000 [42:57<36:35,  4.98s/it]

[I 2026-05-19 14:37:49,563] Trial 558 finished with value: 0.9498588068378098 and parameters: {'n_estimators': 290, 'learning_rate': 0.04253363496767483, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 94, 'subsample': 0.6233852907939491, 'colsample_bytree': 0.6182707749976006, 'reg_alpha': 28.065904334632823, 'reg_lambda': 4.184489107670144}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  56%|███████████████████████████████████████████████████████████▉                                               | 560/1000 [43:15<1:03:51,  8.71s/it]

[I 2026-05-19 14:38:07,192] Trial 566 finished with value: 0.9498430636126433 and parameters: {'n_estimators': 152, 'learning_rate': 0.04204935114307162, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 66, 'subsample': 0.6449757878077804, 'colsample_bytree': 0.669569567607487, 'reg_alpha': 5.9982181970195265, 'reg_lambda': 4.337728027441051}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  56%|█████████████████████████████████████████████████████████████▏                                               | 561/1000 [43:17<48:53,  6.68s/it]

[I 2026-05-19 14:38:09,044] Trial 559 finished with value: 0.9498766510349087 and parameters: {'n_estimators': 290, 'learning_rate': 0.041511293332980835, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 95, 'subsample': 0.6594744089213719, 'colsample_bytree': 0.6257150102168253, 'reg_alpha': 2.5433748569264725, 'reg_lambda': 4.419884975299939}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  56%|█████████████████████████████████████████████████████████████▎                                               | 562/1000 [43:20<40:47,  5.59s/it]

[I 2026-05-19 14:38:12,061] Trial 560 finished with value: 0.9498736136199538 and parameters: {'n_estimators': 290, 'learning_rate': 0.04175788033027643, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 79, 'subsample': 0.6432286765611396, 'colsample_bytree': 0.6179704120420355, 'reg_alpha': 2.781212771396132, 'reg_lambda': 4.666006801017719}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  56%|█████████████████████████████████████████████████████████████▎                                               | 563/1000 [43:20<29:55,  4.11s/it]

[I 2026-05-19 14:38:12,688] Trial 562 finished with value: 0.9498663299981516 and parameters: {'n_estimators': 291, 'learning_rate': 0.04293358061295096, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 94, 'subsample': 0.9999415796741963, 'colsample_bytree': 0.6260763984733975, 'reg_alpha': 2.820119207867282, 'reg_lambda': 4.21606260988197}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  56%|█████████████████████████████████████████████████████████████▍                                               | 564/1000 [43:21<21:41,  2.99s/it]

[I 2026-05-19 14:38:13,040] Trial 563 finished with value: 0.9498717596049596 and parameters: {'n_estimators': 292, 'learning_rate': 0.04268506428094989, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 95, 'subsample': 0.6657919205883395, 'colsample_bytree': 0.6280570507137798, 'reg_alpha': 2.8321254722274047, 'reg_lambda': 4.624071366724582}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  56%|█████████████████████████████████████████████████████████████▌                                               | 565/1000 [43:22<18:54,  2.61s/it]

[I 2026-05-19 14:38:14,775] Trial 567 finished with value: 0.9498411428460944 and parameters: {'n_estimators': 152, 'learning_rate': 0.04273709842499741, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 95, 'subsample': 0.6636134984951153, 'colsample_bytree': 0.6692323933720147, 'reg_alpha': 5.985743803186853, 'reg_lambda': 4.829741230531445}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  57%|█████████████████████████████████████████████████████████████▋                                               | 566/1000 [43:24<17:19,  2.39s/it]

[I 2026-05-19 14:38:16,659] Trial 561 finished with value: 0.9498682790040011 and parameters: {'n_estimators': 290, 'learning_rate': 0.04254983073810581, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 92, 'subsample': 0.660307717323302, 'colsample_bytree': 0.6714194436163979, 'reg_alpha': 2.579920196542661, 'reg_lambda': 4.644632080305604}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  57%|█████████████████████████████████████████████████████████████▊                                               | 567/1000 [43:27<17:40,  2.45s/it]

[I 2026-05-19 14:38:19,222] Trial 564 finished with value: 0.9498682284237882 and parameters: {'n_estimators': 291, 'learning_rate': 0.04254447405946394, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 95, 'subsample': 0.9199091624180444, 'colsample_bytree': 0.6275836640861032, 'reg_alpha': 2.9542096066431376, 'reg_lambda': 4.602008838196569}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  57%|█████████████████████████████████████████████████████████████▉                                               | 568/1000 [43:28<15:54,  2.21s/it]

[I 2026-05-19 14:38:20,872] Trial 565 finished with value: 0.9498662630404547 and parameters: {'n_estimators': 272, 'learning_rate': 0.04206421037371664, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 66, 'subsample': 0.6634641093007965, 'colsample_bytree': 0.6695672745196976, 'reg_alpha': 2.835428722009581, 'reg_lambda': 4.510178421184574}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  57%|████████████████████████████████████████████████████████████▉                                              | 569/1000 [43:52<1:01:58,  8.63s/it]

[I 2026-05-19 14:38:44,500] Trial 568 finished with value: 0.9498426715809675 and parameters: {'n_estimators': 295, 'learning_rate': 0.02430272439112688, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 94, 'subsample': 0.6400029190260148, 'colsample_bytree': 0.6695229024240632, 'reg_alpha': 1.4752761751701413, 'reg_lambda': 6.942776533503224}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  57%|██████████████████████████████████████████████████████████████▏                                              | 570/1000 [43:56<52:31,  7.33s/it]

[I 2026-05-19 14:38:48,792] Trial 569 finished with value: 0.9498589857350307 and parameters: {'n_estimators': 293, 'learning_rate': 0.039827231194632676, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 95, 'subsample': 0.6643775367437864, 'colsample_bytree': 0.6687380978157417, 'reg_alpha': 1.593719707326384, 'reg_lambda': 4.606674312241169}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  57%|██████████████████████████████████████████████████████████████▏                                              | 571/1000 [44:02<49:26,  6.92s/it]

[I 2026-05-19 14:38:54,743] Trial 570 finished with value: 0.9498627721590112 and parameters: {'n_estimators': 295, 'learning_rate': 0.039669234642003476, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 94, 'subsample': 0.6663735215023858, 'colsample_bytree': 0.6470913467951801, 'reg_alpha': 1.581879740623186, 'reg_lambda': 7.068157387901781}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  57%|█████████████████████████████████████████████████████████████▏                                             | 572/1000 [44:16<1:03:54,  8.96s/it]

[I 2026-05-19 14:39:08,474] Trial 575 finished with value: 0.9498629064139508 and parameters: {'n_estimators': 272, 'learning_rate': 0.03929607316811207, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 95, 'subsample': 0.6580388697310826, 'colsample_bytree': 0.6310030458764806, 'reg_alpha': 1.8130257972861248, 'reg_lambda': 2.208994105408485}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  57%|██████████████████████████████████████████████████████████████▍                                              | 573/1000 [44:17<46:24,  6.52s/it]

[I 2026-05-19 14:39:09,303] Trial 571 finished with value: 0.9498654257778671 and parameters: {'n_estimators': 296, 'learning_rate': 0.03925187791745873, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 93, 'subsample': 0.6431313477261321, 'colsample_bytree': 0.6447694651718211, 'reg_alpha': 1.5948874415955234, 'reg_lambda': 6.781604769675584}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  57%|██████████████████████████████████████████████████████████████▌                                              | 574/1000 [44:21<42:09,  5.94s/it]

[I 2026-05-19 14:39:13,881] Trial 576 finished with value: 0.949864629270418 and parameters: {'n_estimators': 293, 'learning_rate': 0.039699695060899584, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 91, 'subsample': 0.6412011561135366, 'colsample_bytree': 0.6297587533046786, 'reg_alpha': 1.5333134032366558, 'reg_lambda': 2.6352061534993934}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  57%|██████████████████████████████████████████████████████████████▋                                              | 575/1000 [44:22<30:17,  4.28s/it]

[I 2026-05-19 14:39:14,276] Trial 573 finished with value: 0.9498616936074136 and parameters: {'n_estimators': 296, 'learning_rate': 0.03997212849461203, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 240, 'subsample': 0.6623452053782809, 'colsample_bytree': 0.6292365319392496, 'reg_alpha': 1.6883184712316417, 'reg_lambda': 7.745523490002223}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  58%|██████████████████████████████████████████████████████████████▊                                              | 576/1000 [44:24<25:04,  3.55s/it]

[I 2026-05-19 14:39:16,137] Trial 574 finished with value: 0.9498619315539939 and parameters: {'n_estimators': 296, 'learning_rate': 0.039666461944320906, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 92, 'subsample': 0.6581059873482861, 'colsample_bytree': 0.6265419342286527, 'reg_alpha': 1.6193505594280535, 'reg_lambda': 2.646743515068551}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  58%|██████████████████████████████████████████████████████████████▉                                              | 577/1000 [44:26<21:43,  3.08s/it]

[I 2026-05-19 14:39:18,127] Trial 572 finished with value: 0.9498521200534027 and parameters: {'n_estimators': 295, 'learning_rate': 0.025091894259732496, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 94, 'subsample': 0.6586093318141821, 'colsample_bytree': 0.6277000025980372, 'reg_alpha': 1.600019750180752, 'reg_lambda': 2.559445997499353}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  58%|███████████████████████████████████████████████████████████████                                              | 578/1000 [44:30<24:38,  3.50s/it]

[I 2026-05-19 14:39:22,615] Trial 577 finished with value: 0.9498614815614645 and parameters: {'n_estimators': 296, 'learning_rate': 0.03435341900837391, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 97, 'subsample': 0.6368044130100952, 'colsample_bytree': 0.6304832907093452, 'reg_alpha': 1.5843679559619337, 'reg_lambda': 2.501637979488682}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  58%|███████████████████████████████████████████████████████████████                                              | 579/1000 [44:31<18:11,  2.59s/it]

[I 2026-05-19 14:39:23,090] Trial 579 finished with value: 0.9498674865552477 and parameters: {'n_estimators': 299, 'learning_rate': 0.03955425014789711, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 108, 'subsample': 0.6425765592039101, 'colsample_bytree': 0.627686771387063, 'reg_alpha': 5.453599493044062, 'reg_lambda': 2.548555968491076}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:39:23,105] Trial 578 finished with value: 0.949848660365755 and parameters: {'n_estimators': 295, 'learning_rate': 0.025362958548245034, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 38, 'subsample': 0.6439003588604452, 'colsample_bytree': 0.6301617890957818, 'reg_alpha': 1.5537725287193767, 'reg_lambda': 2.6065302610675154}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  58%|███████████████████████████████████████████████████████████████▎                                             | 581/1000 [44:52<43:39,  6.25s/it]

[I 2026-05-19 14:39:44,111] Trial 586 finished with value: 0.9498111269281113 and parameters: {'n_estimators': 121, 'learning_rate': 0.03922950795007132, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 50, 'subsample': 0.6814790213919771, 'colsample_bytree': 0.6098996126866632, 'reg_alpha': 6.15769823983893, 'reg_lambda': 2.6062490934286298}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  58%|███████████████████████████████████████████████████████████████▍                                             | 582/1000 [44:55<38:49,  5.57s/it]

[I 2026-05-19 14:39:47,624] Trial 580 finished with value: 0.949863213572819 and parameters: {'n_estimators': 295, 'learning_rate': 0.03916124212460403, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 37, 'subsample': 0.9596672638463035, 'colsample_bytree': 0.6280213967961356, 'reg_alpha': 1.6680160962296051, 'reg_lambda': 2.6179874855749437}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  58%|███████████████████████████████████████████████████████████████▌                                             | 583/1000 [44:59<35:20,  5.08s/it]

[I 2026-05-19 14:39:51,339] Trial 581 finished with value: 0.9498676179653339 and parameters: {'n_estimators': 297, 'learning_rate': 0.03914787666369076, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 105, 'subsample': 0.6813145493811725, 'colsample_bytree': 0.6294688965832066, 'reg_alpha': 1.6337885810641388, 'reg_lambda': 2.6439113389906805}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  58%|███████████████████████████████████████████████████████████████▋                                             | 584/1000 [45:06<39:51,  5.75s/it]

[I 2026-05-19 14:39:58,865] Trial 582 finished with value: 0.9498678236380755 and parameters: {'n_estimators': 295, 'learning_rate': 0.034641012062243653, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 124, 'subsample': 0.6315220093161362, 'colsample_bytree': 0.629006581883052, 'reg_alpha': 6.121344952815776, 'reg_lambda': 2.801551860099957}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  58%|███████████████████████████████████████████████████████████████▊                                             | 585/1000 [45:16<47:45,  6.91s/it]

[I 2026-05-19 14:40:08,763] Trial 585 finished with value: 0.9498536748470781 and parameters: {'n_estimators': 298, 'learning_rate': 0.03511349594011596, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 106, 'subsample': 0.6821154892310227, 'colsample_bytree': 0.6358144304894122, 'reg_alpha': 7.206883417979665, 'reg_lambda': 2.5467533797556823}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  59%|███████████████████████████████████████████████████████████████▊                                             | 586/1000 [45:21<43:58,  6.37s/it]

[I 2026-05-19 14:40:13,790] Trial 583 finished with value: 0.9498722014276805 and parameters: {'n_estimators': 298, 'learning_rate': 0.03927569192854831, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 107, 'subsample': 0.6818229788234359, 'colsample_bytree': 0.6103142483281271, 'reg_alpha': 5.989780515577856, 'reg_lambda': 2.629497668089901}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  59%|███████████████████████████████████████████████████████████████▉                                             | 587/1000 [45:23<34:23,  5.00s/it]

[I 2026-05-19 14:40:15,415] Trial 584 finished with value: 0.9498701012098969 and parameters: {'n_estimators': 296, 'learning_rate': 0.040385626256507746, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 125, 'subsample': 0.6818358118345293, 'colsample_bytree': 0.6101097842841292, 'reg_alpha': 6.03232790505262, 'reg_lambda': 2.7538786108761477}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  59%|████████████████████████████████████████████████████████████████                                             | 588/1000 [45:25<27:42,  4.04s/it]

[I 2026-05-19 14:40:17,135] Trial 587 finished with value: 0.9498658591061698 and parameters: {'n_estimators': 284, 'learning_rate': 0.045208848438705325, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 127, 'subsample': 0.9582642385238619, 'colsample_bytree': 0.637158734693005, 'reg_alpha': 6.414080056054782, 'reg_lambda': 2.4873247798703804}. Best is trial 302 with value: 0.9498769329196636.

[I 2026-05-19 14:40:22,323] Trial 590 finished with value: 0.9498715589260985 and parameters: {'n_estimators': 284, 'learning_rate': 0.04504723245380627, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 106, 'subsample': 0.9585349558240471, 'colsample_bytree': 0.6124639856019916, 'reg_alpha': 6.223533254687092, 'reg_lambda': 6.967024361993443}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  59%|████████████████████████████████████████████████████████████████▎                                            | 590/1000 [45:30<21:29,  3.14s/it]

[I 2026-05-19 14:40:22,532] Trial 595 finished with value: 0.9497813840651625 and parameters: {'n_estimators': 88, 'learning_rate': 0.04551778289003128, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 103, 'subsample': 0.9829245903164173, 'colsample_bytree': 0.6387965693602405, 'reg_alpha': 3.3743314770657036, 'reg_lambda': 6.798861375866817}. Best is trial 302 with value: 0.9498769329196636.
[I 2026-05-19 14:40:22,614] Trial 591 finished with value: 0.9498645519744124 and parameters: {'n_estimators': 285, 'learning_rate': 0.034485217993702785, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 50, 'subsample': 0.9846903671508381, 'colsample_bytree': 0.6115040494840084, 'reg_alpha': 6.141104154836099, 'reg_lambda': 1.0130724449907318}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  59%|████████████████████████████████████████████████████████████████▌                                            | 592/1000 [45:33<16:21,  2.41s/it]

[I 2026-05-19 14:40:25,611] Trial 588 finished with value: 0.9498545531075389 and parameters: {'n_estimators': 283, 'learning_rate': 0.04518946011796724, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 22, 'subsample': 0.6799346429118285, 'colsample_bytree': 0.9512420590376898, 'reg_alpha': 6.163368255730415, 'reg_lambda': 2.7061040129947407}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  59%|████████████████████████████████████████████████████████████████▋                                            | 593/1000 [45:38<19:52,  2.93s/it]

[I 2026-05-19 14:40:30,145] Trial 599 finished with value: 0.9497157617283609 and parameters: {'n_estimators': 46, 'learning_rate': 0.04522724450010224, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 82, 'subsample': 0.614531229408087, 'colsample_bytree': 0.645102273710926, 'reg_alpha': 2.816722010589621, 'reg_lambda': 7.002713224053878}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  59%|████████████████████████████████████████████████████████████████▋                                            | 594/1000 [45:40<18:52,  2.79s/it]

[I 2026-05-19 14:40:32,513] Trial 589 finished with value: 0.9498510650196668 and parameters: {'n_estimators': 283, 'learning_rate': 0.03475886932782941, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 105, 'subsample': 0.6814809161283999, 'colsample_bytree': 0.9523207910347087, 'reg_alpha': 5.887152288230441, 'reg_lambda': 0.033811568688843406}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  60%|████████████████████████████████████████████████████████████████▊                                            | 595/1000 [45:44<20:09,  2.99s/it]

[I 2026-05-19 14:40:36,045] Trial 602 finished with value: 0.9496934593065184 and parameters: {'n_estimators': 43, 'learning_rate': 0.04407491048682793, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 82, 'subsample': 0.6144195953030552, 'colsample_bytree': 0.6461902433663665, 'reg_alpha': 2.5821160129889202, 'reg_lambda': 6.857334387378295}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  60%|████████████████████████████████████████████████████████████████▉                                            | 596/1000 [45:44<15:48,  2.35s/it]

[I 2026-05-19 14:40:36,752] Trial 597 finished with value: 0.9498048099426125 and parameters: {'n_estimators': 90, 'learning_rate': 0.04509690261494644, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 48, 'subsample': 0.9838159610700937, 'colsample_bytree': 0.6386127216626162, 'reg_alpha': 3.6210457845676327, 'reg_lambda': 0.33869073417680784}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  60%|█████████████████████████████████████████████████████████████████                                            | 597/1000 [45:58<38:19,  5.70s/it]

[I 2026-05-19 14:40:50,855] Trial 592 finished with value: 0.949865125622629 and parameters: {'n_estimators': 283, 'learning_rate': 0.03443818640321719, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 80, 'subsample': 0.9624818866150843, 'colsample_bytree': 0.8617751968151407, 'reg_alpha': 5.514161776788627, 'reg_lambda': 0.9520142188133843}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  60%|█████████████████████████████████████████████████████████████████▏                                           | 598/1000 [45:59<28:11,  4.21s/it]

[I 2026-05-19 14:40:51,399] Trial 594 finished with value: 0.9498610368876749 and parameters: {'n_estimators': 283, 'learning_rate': 0.04995081429527682, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 80, 'subsample': 0.6152832453512036, 'colsample_bytree': 0.6386829349222855, 'reg_alpha': 5.987127663145996, 'reg_lambda': 0.967136924735217}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  60%|█████████████████████████████████████████████████████████████████▎                                           | 599/1000 [46:10<41:44,  6.25s/it]

[I 2026-05-19 14:41:02,578] Trial 593 finished with value: 0.9498057984188806 and parameters: {'n_estimators': 283, 'learning_rate': 0.017605343735000896, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 79, 'subsample': 0.6152321378935502, 'colsample_bytree': 0.9560110569002253, 'reg_alpha': 5.839090398233067, 'reg_lambda': 6.8528487308347845}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  60%|█████████████████████████████████████████████████████████████████▍                                           | 600/1000 [46:15<39:16,  5.89s/it]

[I 2026-05-19 14:41:07,590] Trial 596 finished with value: 0.9498578956946979 and parameters: {'n_estimators': 285, 'learning_rate': 0.04992964469955721, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 81, 'subsample': 0.8592545006207796, 'colsample_bytree': 0.6438481346673571, 'reg_alpha': 5.943746212417489, 'reg_lambda': 7.327642792565551}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  60%|█████████████████████████████████████████████████████████████████▌                                           | 601/1000 [46:23<43:10,  6.49s/it]

[I 2026-05-19 14:41:15,524] Trial 598 finished with value: 0.9498592324215778 and parameters: {'n_estimators': 284, 'learning_rate': 0.04507955220671133, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 79, 'subsample': 0.6135131297754371, 'colsample_bytree': 0.6386528962200692, 'reg_alpha': 19.115538551996607, 'reg_lambda': 6.461355306542393}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 302. Best value: 0.949877:  60%|█████████████████████████████████████████████████████████████████▌                                           | 602/1000 [46:28<39:17,  5.92s/it]

[I 2026-05-19 14:41:20,119] Trial 601 finished with value: 0.9498686125395546 and parameters: {'n_estimators': 272, 'learning_rate': 0.04492497210268473, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 80, 'subsample': 0.611977808196488, 'colsample_bytree': 0.6451040114552933, 'reg_alpha': 3.3072640438621836, 'reg_lambda': 6.74935540294787}. Best is trial 302 with value: 0.9498769329196636.

Best trial: 603. Best value: 0.949882:  60%|█████████████████████████████████████████████████████████████████▋                                           | 603/1000 [46:30<31:07,  4.70s/it]

[I 2026-05-19 14:41:21,961] Trial 603 finished with value: 0.9498815886860695 and parameters: {'n_estimators': 272, 'learning_rate': 0.04331743813378749, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 79, 'subsample': 0.849554199458748, 'colsample_bytree': 0.6452730806890068, 'reg_alpha': 3.4284318632046933, 'reg_lambda': 6.744375246788695}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:41:22,156] Trial 600 finished with value: 0.949869427445768 and parameters: {'n_estimators': 282, 'learning_rate': 0.04490072273544141, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 77, 'subsample': 0.9842190771510378, 'colsample_bytree': 0.6455275685615258, 'reg_alpha': 3.3017137131967895, 'reg_lambda': 6.791955163554226}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  60%|█████████████████████████████████████████████████████████████████▉                                           | 605/1000 [46:34<24:43,  3.76s/it]

[I 2026-05-19 14:41:26,827] Trial 604 finished with value: 0.9498554653679964 and parameters: {'n_estimators': 271, 'learning_rate': 0.04333124124800269, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 65, 'subsample': 0.6303127136053702, 'colsample_bytree': 0.6457027679325403, 'reg_alpha': 18.782127537966275, 'reg_lambda': 0.03156172303794836}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  61%|██████████████████████████████████████████████████████████████████                                           | 606/1000 [46:36<20:39,  3.15s/it]

[I 2026-05-19 14:41:28,552] Trial 610 finished with value: 0.9497984498810486 and parameters: {'n_estimators': 102, 'learning_rate': 0.04151845543051272, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 90, 'subsample': 0.8494649977182814, 'colsample_bytree': 0.644475675802042, 'reg_alpha': 3.403166867358853, 'reg_lambda': 0.008015901583020766}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  61%|██████████████████████████████████████████████████████████████████▏                                          | 607/1000 [46:39<20:25,  3.12s/it]

[I 2026-05-19 14:41:31,609] Trial 605 finished with value: 0.9498656774675867 and parameters: {'n_estimators': 274, 'learning_rate': 0.043148132065926256, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 65, 'subsample': 0.6138468955917101, 'colsample_bytree': 0.6459923789596571, 'reg_alpha': 3.330880039200206, 'reg_lambda': 0.006577467455003483}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  61%|██████████████████████████████████████████████████████████████████▎                                          | 608/1000 [46:41<18:09,  2.78s/it]

[I 2026-05-19 14:41:33,595] Trial 606 finished with value: 0.949871454224434 and parameters: {'n_estimators': 272, 'learning_rate': 0.04123289789869604, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 78, 'subsample': 0.8957302812408228, 'colsample_bytree': 0.6379605725330749, 'reg_alpha': 3.567943312855758, 'reg_lambda': 3.75286791735013}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  61%|██████████████████████████████████████████████████████████████████▍                                          | 609/1000 [46:42<14:26,  2.22s/it]

[I 2026-05-19 14:41:34,502] Trial 607 finished with value: 0.9498619607753647 and parameters: {'n_estimators': 274, 'learning_rate': 0.041222392061070624, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 66, 'subsample': 0.6139691647563446, 'colsample_bytree': 0.6384008398359041, 'reg_alpha': 0.0008076803207794787, 'reg_lambda': 3.521376889430495}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  61%|██████████████████████████████████████████████████████████████████▍                                          | 610/1000 [46:54<33:12,  5.11s/it]

[I 2026-05-19 14:41:46,365] Trial 609 finished with value: 0.9498548484428865 and parameters: {'n_estimators': 271, 'learning_rate': 0.041253139286668496, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 66, 'subsample': 0.85988923530521, 'colsample_bytree': 0.6478492643090189, 'reg_alpha': 17.77305384301843, 'reg_lambda': 0.006492882104597568}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  61%|██████████████████████████████████████████████████████████████████▌                                          | 611/1000 [46:56<27:43,  4.28s/it]

[I 2026-05-19 14:41:48,689] Trial 608 finished with value: 0.9498672123401624 and parameters: {'n_estimators': 272, 'learning_rate': 0.04994774932775998, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 88, 'subsample': 0.8558123576526817, 'colsample_bytree': 0.6430214464950968, 'reg_alpha': 3.3434000290512067, 'reg_lambda': 3.9039578814757037}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  61%|██████████████████████████████████████████████████████████████████▋                                          | 612/1000 [47:11<47:52,  7.40s/it]

[I 2026-05-19 14:42:03,396] Trial 611 finished with value: 0.9498696801537363 and parameters: {'n_estimators': 270, 'learning_rate': 0.04152581733686838, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 66, 'subsample': 0.6308278497070116, 'colsample_bytree': 0.6485101787182049, 'reg_alpha': 3.764978435056223, 'reg_lambda': 0.006860479139928455}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  61%|██████████████████████████████████████████████████████████████████▊                                          | 613/1000 [47:18<46:45,  7.25s/it]

[I 2026-05-19 14:42:10,250] Trial 612 finished with value: 0.9498745528187651 and parameters: {'n_estimators': 275, 'learning_rate': 0.041278860164028555, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 66, 'subsample': 0.8940490574235045, 'colsample_bytree': 0.6462101568132286, 'reg_alpha': 3.4693382518304308, 'reg_lambda': 0.007970224660253343}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  61%|██████████████████████████████████████████████████████████████████▉                                          | 614/1000 [47:24<45:22,  7.05s/it]

[I 2026-05-19 14:42:16,883] Trial 613 finished with value: 0.9498757773236622 and parameters: {'n_estimators': 273, 'learning_rate': 0.04170140352184426, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 67, 'subsample': 0.6301741355792564, 'colsample_bytree': 0.6184496806336812, 'reg_alpha': 3.4512521225008794, 'reg_lambda': 3.7786593857221926}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  62%|███████████████████████████████████████████████████████████████████                                          | 615/1000 [47:27<36:32,  5.69s/it]

[I 2026-05-19 14:42:19,401] Trial 615 finished with value: 0.9498675629458516 and parameters: {'n_estimators': 272, 'learning_rate': 0.0417345599424071, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 65, 'subsample': 0.896138023424405, 'colsample_bytree': 0.6481130025591116, 'reg_alpha': 3.714969410258743, 'reg_lambda': 1.756090773773487}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  62%|███████████████████████████████████████████████████████████████████▏                                         | 616/1000 [47:31<32:35,  5.09s/it]

[I 2026-05-19 14:42:23,089] Trial 614 finished with value: 0.9498667880091187 and parameters: {'n_estimators': 272, 'learning_rate': 0.041236109390108085, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 66, 'subsample': 0.8965250389547079, 'colsample_bytree': 0.7390408407455599, 'reg_alpha': 3.691998961975476, 'reg_lambda': 3.7859112359416187}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  62%|███████████████████████████████████████████████████████████████████▎                                         | 617/1000 [47:34<29:37,  4.64s/it]

[I 2026-05-19 14:42:26,687] Trial 616 finished with value: 0.949870335618835 and parameters: {'n_estimators': 274, 'learning_rate': 0.041307731804059306, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 66, 'subsample': 0.9126750393250196, 'colsample_bytree': 0.6498129675975977, 'reg_alpha': 3.803917518399513, 'reg_lambda': 9.296772009991745}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  62%|███████████████████████████████████████████████████████████████████▎                                         | 618/1000 [47:37<26:29,  4.16s/it]

[I 2026-05-19 14:42:29,715] Trial 617 finished with value: 0.9498626067001876 and parameters: {'n_estimators': 271, 'learning_rate': 0.0412185238083903, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 67, 'subsample': 0.8789670440122397, 'colsample_bytree': 0.6606399700573712, 'reg_alpha': 2.1376942280494187, 'reg_lambda': 9.67178811494196}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  62%|███████████████████████████████████████████████████████████████████▍                                         | 619/1000 [47:40<24:22,  3.84s/it]

[I 2026-05-19 14:42:32,804] Trial 620 finished with value: 0.9498612338802618 and parameters: {'n_estimators': 265, 'learning_rate': 0.0478014925614597, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 67, 'subsample': 0.865433627537785, 'colsample_bytree': 0.7358524854878349, 'reg_alpha': 2.2761202843966344, 'reg_lambda': 10.181762456616557}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  62%|███████████████████████████████████████████████████████████████████▌                                         | 620/1000 [47:41<17:45,  2.80s/it]

[I 2026-05-19 14:42:33,200] Trial 618 finished with value: 0.9498450934309896 and parameters: {'n_estimators': 272, 'learning_rate': 0.04097777362003733, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 74, 'subsample': 0.9396175152575242, 'colsample_bytree': 0.6505755763215959, 'reg_alpha': 0.00010334694090974237, 'reg_lambda': 0.013085682325272513}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  62%|███████████████████████████████████████████████████████████████████▋                                         | 621/1000 [47:43<15:46,  2.50s/it]

[I 2026-05-19 14:42:34,969] Trial 619 finished with value: 0.9498480740497202 and parameters: {'n_estimators': 273, 'learning_rate': 0.04101401638779833, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 69, 'subsample': 0.8865693655936203, 'colsample_bytree': 0.6508042382463557, 'reg_alpha': 0.003140340656997712, 'reg_lambda': 1.744989306509627}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  62%|███████████████████████████████████████████████████████████████████▊                                         | 622/1000 [47:52<29:44,  4.72s/it]

[I 2026-05-19 14:42:44,890] Trial 621 finished with value: 0.9498647825529407 and parameters: {'n_estimators': 264, 'learning_rate': 0.048086809049839765, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 87, 'subsample': 0.8707664878344081, 'colsample_bytree': 0.6567787639283837, 'reg_alpha': 2.356321336402563, 'reg_lambda': 1.7016482350741278}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  62%|███████████████████████████████████████████████████████████████████▉                                         | 623/1000 [47:55<25:47,  4.10s/it]

[I 2026-05-19 14:42:47,559] Trial 622 finished with value: 0.9498674020496217 and parameters: {'n_estimators': 264, 'learning_rate': 0.04734483539306415, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 74, 'subsample': 0.9723614844519366, 'colsample_bytree': 0.6606185874177375, 'reg_alpha': 2.376114039775765, 'reg_lambda': 9.266443194574014}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  62%|████████████████████████████████████████████████████████████████████                                         | 624/1000 [48:09<43:14,  6.90s/it]

[I 2026-05-19 14:43:00,964] Trial 623 finished with value: 0.9498687070311208 and parameters: {'n_estimators': 264, 'learning_rate': 0.047510903411590366, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 74, 'subsample': 0.6000182291609013, 'colsample_bytree': 0.6625775620745133, 'reg_alpha': 2.280748340756051, 'reg_lambda': 8.567599887612902}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  62%|████████████████████████████████████████████████████████████████████▏                                        | 625/1000 [48:16<44:31,  7.13s/it]

[I 2026-05-19 14:43:08,634] Trial 624 finished with value: 0.9498628521914216 and parameters: {'n_estimators': 277, 'learning_rate': 0.047220130658675384, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 74, 'subsample': 0.8790044418318662, 'colsample_bytree': 0.6593081961032805, 'reg_alpha': 2.152667090300783, 'reg_lambda': 0.1505567030125913}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  63%|████████████████████████████████████████████████████████████████████▏                                        | 626/1000 [48:21<40:21,  6.48s/it]

[I 2026-05-19 14:43:13,597] Trial 632 finished with value: 0.9498367264100084 and parameters: {'n_estimators': 171, 'learning_rate': 0.0436860282816886, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 59, 'subsample': 0.8738647789842031, 'colsample_bytree': 0.6628875147704236, 'reg_alpha': 1.9604480110911908, 'reg_lambda': 0.1509580756899663}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  63%|████████████████████████████████████████████████████████████████████▎                                        | 627/1000 [48:23<31:05,  5.00s/it]

[I 2026-05-19 14:43:15,153] Trial 626 finished with value: 0.9498615890570944 and parameters: {'n_estimators': 266, 'learning_rate': 0.03834795683468343, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 54, 'subsample': 0.8416176478502568, 'colsample_bytree': 0.6604500400520058, 'reg_alpha': 2.2604130194351515, 'reg_lambda': 9.049224150040375}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  63%|████████████████████████████████████████████████████████████████████▍                                        | 628/1000 [48:25<25:04,  4.04s/it]

[I 2026-05-19 14:43:16,941] Trial 625 finished with value: 0.9498604727584491 and parameters: {'n_estimators': 262, 'learning_rate': 0.0388857039828805, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 61, 'subsample': 0.8343336275089096, 'colsample_bytree': 0.6605498690503165, 'reg_alpha': 1.9714962623580201, 'reg_lambda': 9.43037598801406}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  63%|████████████████████████████████████████████████████████████████████▌                                        | 629/1000 [48:29<26:08,  4.23s/it]

[I 2026-05-19 14:43:21,615] Trial 627 finished with value: 0.9498551103752924 and parameters: {'n_estimators': 264, 'learning_rate': 0.038085913085568114, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 61, 'subsample': 0.6715030696536815, 'colsample_bytree': 0.6596274921616836, 'reg_alpha': 2.2301567193374012, 'reg_lambda': 8.928551121769305}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  63%|████████████████████████████████████████████████████████████████████▋                                        | 630/1000 [48:32<24:24,  3.96s/it]

[I 2026-05-19 14:43:24,936] Trial 628 finished with value: 0.9498621183494935 and parameters: {'n_estimators': 264, 'learning_rate': 0.038777381365133756, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 53, 'subsample': 0.8787985327593653, 'colsample_bytree': 0.6630511604157652, 'reg_alpha': 2.1916048308167477, 'reg_lambda': 10.633864763440798}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  63%|████████████████████████████████████████████████████████████████████▊                                        | 631/1000 [48:34<20:44,  3.37s/it]

[I 2026-05-19 14:43:26,955] Trial 629 finished with value: 0.9498582710008859 and parameters: {'n_estimators': 262, 'learning_rate': 0.03819560799043239, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 54, 'subsample': 0.816955015800576, 'colsample_bytree': 0.6581160556641342, 'reg_alpha': 2.432973981786387, 'reg_lambda': 0.1433145582498082}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  63%|████████████████████████████████████████████████████████████████████▉                                        | 632/1000 [48:37<19:06,  3.12s/it]

[I 2026-05-19 14:43:29,462] Trial 631 finished with value: 0.9498594460013925 and parameters: {'n_estimators': 263, 'learning_rate': 0.03933786928844035, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 55, 'subsample': 0.6701531458920782, 'colsample_bytree': 0.6347621683947027, 'reg_alpha': 2.2830503967236995, 'reg_lambda': 4.965911620887881}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  63%|████████████████████████████████████████████████████████████████████▉                                        | 633/1000 [48:38<15:46,  2.58s/it]

[I 2026-05-19 14:43:30,788] Trial 630 finished with value: 0.9498575836819084 and parameters: {'n_estimators': 265, 'learning_rate': 0.03867343543482576, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 56, 'subsample': 0.8332864577478006, 'colsample_bytree': 0.6642507714585982, 'reg_alpha': 1.1781901524825484, 'reg_lambda': 5.692793450254852}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  63%|█████████████████████████████████████████████████████████████████████                                        | 634/1000 [48:53<37:05,  6.08s/it]

[I 2026-05-19 14:43:45,034] Trial 633 finished with value: 0.949856664752717 and parameters: {'n_estimators': 263, 'learning_rate': 0.038262373162081115, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 56, 'subsample': 0.6945257852130243, 'colsample_bytree': 0.6642691532992998, 'reg_alpha': 2.335215894684673, 'reg_lambda': 4.999803230963302}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  64%|█████████████████████████████████████████████████████████████████████▏                                       | 635/1000 [48:55<30:21,  4.99s/it]

[I 2026-05-19 14:43:47,495] Trial 636 finished with value: 0.9498387157673477 and parameters: {'n_estimators': 171, 'learning_rate': 0.03884659750219562, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 54, 'subsample': 0.6944531741023973, 'colsample_bytree': 0.6356130244155879, 'reg_alpha': 1.1825092707737805, 'reg_lambda': 5.1081026727398795}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  64%|█████████████████████████████████████████████████████████████████████▎                                       | 636/1000 [49:03<34:52,  5.75s/it]

[I 2026-05-19 14:43:55,012] Trial 634 finished with value: 0.9497621798004026 and parameters: {'n_estimators': 278, 'learning_rate': 0.008453127420377515, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 57, 'subsample': 0.8146742770600459, 'colsample_bytree': 0.635163517409274, 'reg_alpha': 1.1355937935894715, 'reg_lambda': 5.374578861155517}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  64%|█████████████████████████████████████████████████████████████████████▍                                       | 637/1000 [49:07<32:11,  5.32s/it]

[I 2026-05-19 14:43:59,328] Trial 640 pruned.
[I 2026-05-19 14:43:59,345] Trial 635 finished with value: 0.9498559237360995 and parameters: {'n_estimators': 277, 'learning_rate': 0.038383960454453026, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 53, 'subsample': 0.6001854944966761, 'colsample_bytree': 0.6375870606040517, 'reg_alpha': 2.66829592268605, 'reg_lambda': 16.68283883361132}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  64%|█████████████████████████████████████████████████████████████████████▋                                       | 639/1000 [49:20<35:08,  5.84s/it]

[I 2026-05-19 14:44:12,226] Trial 637 finished with value: 0.9498589369990604 and parameters: {'n_estimators': 280, 'learning_rate': 0.038117702869192284, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 54, 'subsample': 0.6726154744259808, 'colsample_bytree': 0.6356551411099352, 'reg_alpha': 2.662912927389663, 'reg_lambda': 15.566108101560857}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  64%|█████████████████████████████████████████████████████████████████████▊                                       | 640/1000 [49:22<29:04,  4.84s/it]

[I 2026-05-19 14:44:14,042] Trial 638 finished with value: 0.9498565852539601 and parameters: {'n_estimators': 278, 'learning_rate': 0.038401758815537264, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 52, 'subsample': 0.6697550112269779, 'colsample_bytree': 0.6367264476597899, 'reg_alpha': 1.1651751387624565, 'reg_lambda': 18.681898427233595}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  64%|█████████████████████████████████████████████████████████████████████▊                                       | 641/1000 [49:23<22:59,  3.84s/it]

[I 2026-05-19 14:44:15,049] Trial 639 finished with value: 0.9498565711168002 and parameters: {'n_estimators': 279, 'learning_rate': 0.03825834879749138, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 53, 'subsample': 0.9917005445109354, 'colsample_bytree': 0.6351008135384659, 'reg_alpha': 1.1270140357337552, 'reg_lambda': 5.094337261876117}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  64%|█████████████████████████████████████████████████████████████████████▉                                       | 642/1000 [49:26<22:08,  3.71s/it]

[I 2026-05-19 14:44:18,423] Trial 641 finished with value: 0.9498603503099172 and parameters: {'n_estimators': 279, 'learning_rate': 0.04310261263598855, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 52, 'subsample': 0.8126379801066723, 'colsample_bytree': 0.6350161316011552, 'reg_alpha': 1.0220676281992769, 'reg_lambda': 5.008985269496416}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  64%|██████████████████████████████████████████████████████████████████████                                       | 643/1000 [49:32<26:39,  4.48s/it]

[I 2026-05-19 14:44:24,876] Trial 642 finished with value: 0.9498494272886197 and parameters: {'n_estimators': 280, 'learning_rate': 0.04362931052698293, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 44, 'subsample': 0.6715373092685237, 'colsample_bytree': 0.6351698396960768, 'reg_alpha': 0.001982978661354212, 'reg_lambda': 0.24451214599820803}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  64%|██████████████████████████████████████████████████████████████████████▎                                      | 645/1000 [49:37<18:32,  3.13s/it]

[I 2026-05-19 14:44:28,860] Trial 650 finished with value: 0.9497452670970246 and parameters: {'n_estimators': 64, 'learning_rate': 0.04377548703226395, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 48, 'subsample': 0.8013972285489291, 'colsample_bytree': 0.6206058847582336, 'reg_alpha': 8.409388352404296, 'reg_lambda': 0.2337437696850188}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:44:29,035] Trial 644 finished with value: 0.9498627421165284 and parameters: {'n_estimators': 279, 'learning_rate': 0.04343215923533787, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 47, 'subsample': 0.9692008914192904, 'colsample_bytree': 0.6211615969010738, 'reg_alpha': 1.16969160066343, 'reg_lambda': 19.57560197283515}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  65%|██████████████████████████████████████████████████████████████████████▍                                      | 646/1000 [49:39<17:10,  2.91s/it]

[I 2026-05-19 14:44:31,393] Trial 643 finished with value: 0.9498677450667223 and parameters: {'n_estimators': 279, 'learning_rate': 0.04345636333185608, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 49, 'subsample': 0.6903743577218602, 'colsample_bytree': 0.6207044263804086, 'reg_alpha': 1.1418939011120213, 'reg_lambda': 5.086043994383959}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  65%|██████████████████████████████████████████████████████████████████████▌                                      | 647/1000 [49:49<29:09,  4.96s/it]

[I 2026-05-19 14:44:41,272] Trial 645 finished with value: 0.9498647184533178 and parameters: {'n_estimators': 278, 'learning_rate': 0.043447937200051294, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 44, 'subsample': 0.6709961828272283, 'colsample_bytree': 0.6208619297394673, 'reg_alpha': 4.703967596500945, 'reg_lambda': 15.995142567470207}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  65%|██████████████████████████████████████████████████████████████████████▋                                      | 648/1000 [49:54<29:09,  4.97s/it]

[I 2026-05-19 14:44:46,266] Trial 646 finished with value: 0.9498625650889911 and parameters: {'n_estimators': 279, 'learning_rate': 0.04270808010959243, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 44, 'subsample': 0.60113299081228, 'colsample_bytree': 0.620666213916324, 'reg_alpha': 4.647480825537845, 'reg_lambda': 18.037998342719874}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  65%|██████████████████████████████████████████████████████████████████████▋                                      | 649/1000 [49:56<23:30,  4.02s/it]

[I 2026-05-19 14:44:48,029] Trial 647 finished with value: 0.9498560667972672 and parameters: {'n_estimators': 278, 'learning_rate': 0.04363786022933592, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 44, 'subsample': 0.6531488391905663, 'colsample_bytree': 0.6364602464910083, 'reg_alpha': 8.515628958598024, 'reg_lambda': 18.309316214701894}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  65%|██████████████████████████████████████████████████████████████████████▉                                      | 651/1000 [50:04<21:49,  3.75s/it]

[I 2026-05-19 14:44:56,368] Trial 649 finished with value: 0.9498658379000574 and parameters: {'n_estimators': 279, 'learning_rate': 0.043727238140769537, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 111, 'subsample': 0.9905028188683457, 'colsample_bytree': 0.6192214631242434, 'reg_alpha': 8.932995366976808, 'reg_lambda': 3.7770387351177224}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:44:56,457] Trial 652 finished with value: 0.9498298417057468 and parameters: {'n_estimators': 288, 'learning_rate': 0.04342690527531707, 'max_depth': 2, 'num_leaves': 14, 'min_child_samples': 100, 'subsample': 0.6000713750059287, 'colsample_bytree': 0.6215613278917721, 'reg_alpha': 4.752824431198718, 'reg_lambda': 3.600822198627535}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:44:56,508] Trial 653 finished with value: 0.9498362875106405 and parameters: {'n_estimators': 288, 'learning_rate': 0.04367826041366604, 'max_depth': 2, 'num_leaves': 8, 'min_child_samples': 98, 'subsample': 0.6001140662707902, 'colsample_bytree': 0.6780599122221629, 'reg_alpha': 8.308531377109077, 'reg_lambda': 3.428324921559364}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  65%|███████████████████████████████████████████████████████████████████████▏                                     | 653/1000 [50:06<14:09,  2.45s/it]

[I 2026-05-19 14:44:58,313] Trial 648 finished with value: 0.9498640609668871 and parameters: {'n_estimators': 280, 'learning_rate': 0.04356509416308886, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 100, 'subsample': 0.9684291399696221, 'colsample_bytree': 0.6786854461641321, 'reg_alpha': 8.944286214533387, 'reg_lambda': 3.3687733935091515}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  65%|███████████████████████████████████████████████████████████████████████▎                                     | 654/1000 [50:11<18:14,  3.16s/it]

[I 2026-05-19 14:45:03,657] Trial 654 finished with value: 0.9498311326896408 and parameters: {'n_estimators': 288, 'learning_rate': 0.043651361836657174, 'max_depth': 2, 'num_leaves': 14, 'min_child_samples': 113, 'subsample': 0.652571737527665, 'colsample_bytree': 0.619272399709532, 'reg_alpha': 4.705962965939407, 'reg_lambda': 3.5449220862002497}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  66%|███████████████████████████████████████████████████████████████████████▍                                     | 655/1000 [50:15<19:19,  3.36s/it]

[I 2026-05-19 14:45:07,574] Trial 655 finished with value: 0.9498338766565387 and parameters: {'n_estimators': 285, 'learning_rate': 0.04371658748847418, 'max_depth': 2, 'num_leaves': 14, 'min_child_samples': 88, 'subsample': 0.9688354914759129, 'colsample_bytree': 0.6220490124848438, 'reg_alpha': 4.757516628057574, 'reg_lambda': 3.6034827000656615}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  66%|███████████████████████████████████████████████████████████████████████▌                                     | 656/1000 [50:20<21:08,  3.69s/it]

[I 2026-05-19 14:45:12,128] Trial 651 finished with value: 0.9497562619845146 and parameters: {'n_estimators': 280, 'learning_rate': 0.009595263868264297, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 99, 'subsample': 0.6197749998387878, 'colsample_bytree': 0.6171493959641374, 'reg_alpha': 8.123322181059788, 'reg_lambda': 3.635085301736109}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  66%|███████████████████████████████████████████████████████████████████████▌                                     | 657/1000 [50:36<41:35,  7.28s/it]

[I 2026-05-19 14:45:28,624] Trial 656 finished with value: 0.9498568552925313 and parameters: {'n_estimators': 289, 'learning_rate': 0.045416831558285, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 100, 'subsample': 0.6205120422165975, 'colsample_bytree': 0.6224870669007521, 'reg_alpha': 0.021014400312696663, 'reg_lambda': 3.62758054393604}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  66%|███████████████████████████████████████████████████████████████████████▋                                     | 658/1000 [50:38<33:19,  5.85s/it]

[I 2026-05-19 14:45:30,925] Trial 657 finished with value: 0.949871081435527 and parameters: {'n_estimators': 289, 'learning_rate': 0.04508190291739945, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 100, 'subsample': 0.6211792396614773, 'colsample_bytree': 0.6250120959326316, 'reg_alpha': 4.234622768336143, 'reg_lambda': 0.025067248169250655}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  66%|███████████████████████████████████████████████████████████████████████▊                                     | 659/1000 [50:50<42:08,  7.41s/it]

[I 2026-05-19 14:45:42,180] Trial 658 finished with value: 0.9498646876595916 and parameters: {'n_estimators': 289, 'learning_rate': 0.04565294383852556, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 100, 'subsample': 0.6201339422425396, 'colsample_bytree': 0.6107298510241194, 'reg_alpha': 8.608790774286229, 'reg_lambda': 3.749586822019711}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  66%|███████████████████████████████████████████████████████████████████████▉                                     | 660/1000 [50:53<35:43,  6.31s/it]

[I 2026-05-19 14:45:45,817] Trial 659 finished with value: 0.9498773527723463 and parameters: {'n_estimators': 287, 'learning_rate': 0.04561571067291351, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 102, 'subsample': 0.6220110382923315, 'colsample_bytree': 0.6121078434911056, 'reg_alpha': 3.93490585815421, 'reg_lambda': 3.6517975817766497}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  66%|████████████████████████████████████████████████████████████████████████                                     | 661/1000 [50:58<32:43,  5.79s/it]

[I 2026-05-19 14:45:50,384] Trial 660 finished with value: 0.9498651924434199 and parameters: {'n_estimators': 289, 'learning_rate': 0.04621200327264837, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 101, 'subsample': 0.6225212077724142, 'colsample_bytree': 0.6509881344077985, 'reg_alpha': 4.593756568054983, 'reg_lambda': 6.850640029641506}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  66%|████████████████████████████████████████████████████████████████████████▏                                    | 662/1000 [51:06<36:29,  6.48s/it]

[I 2026-05-19 14:45:58,473] Trial 663 finished with value: 0.9498703590982766 and parameters: {'n_estimators': 289, 'learning_rate': 0.046328397906355345, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 74, 'subsample': 0.6207827978719773, 'colsample_bytree': 0.6087168788699032, 'reg_alpha': 3.4442383933979013, 'reg_lambda': 7.202071137027158}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  66%|████████████████████████████████████████████████████████████████████████▎                                    | 663/1000 [51:06<25:58,  4.62s/it]

[I 2026-05-19 14:45:58,712] Trial 661 finished with value: 0.9498644414358651 and parameters: {'n_estimators': 289, 'learning_rate': 0.046150934740847575, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 89, 'subsample': 0.6219500234362486, 'colsample_bytree': 0.6802882802784842, 'reg_alpha': 4.277082020285313, 'reg_lambda': 3.541133168801446}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  66%|████████████████████████████████████████████████████████████████████████▍                                    | 664/1000 [51:09<22:11,  3.96s/it]

[I 2026-05-19 14:46:01,122] Trial 664 finished with value: 0.9497728416959681 and parameters: {'n_estimators': 288, 'learning_rate': 0.009836899956131665, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 72, 'subsample': 0.6206667480378812, 'colsample_bytree': 0.6097593397127274, 'reg_alpha': 3.513319425759181, 'reg_lambda': 5.815277266493548}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  66%|████████████████████████████████████████████████████████████████████████▍                                    | 665/1000 [51:10<17:50,  3.19s/it]

[I 2026-05-19 14:46:02,515] Trial 662 finished with value: 0.9498649353516271 and parameters: {'n_estimators': 288, 'learning_rate': 0.04537212530115984, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 88, 'subsample': 0.6191796958877211, 'colsample_bytree': 0.6510029926633559, 'reg_alpha': 3.659742598248286, 'reg_lambda': 3.295760698893232}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  67%|████████████████████████████████████████████████████████████████████████▌                                    | 666/1000 [51:12<16:27,  2.96s/it]

[I 2026-05-19 14:46:04,928] Trial 665 finished with value: 0.9498595290778737 and parameters: {'n_estimators': 289, 'learning_rate': 0.04695748860014103, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 89, 'subsample': 0.6212196601020191, 'colsample_bytree': 0.7018267306680799, 'reg_alpha': 3.188741578442694, 'reg_lambda': 6.554378917568777}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  67%|████████████████████████████████████████████████████████████████████████▋                                    | 667/1000 [51:13<13:09,  2.37s/it]

[I 2026-05-19 14:46:05,922] Trial 666 finished with value: 0.9498700327737554 and parameters: {'n_estimators': 270, 'learning_rate': 0.046520211158663886, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 255, 'subsample': 0.9999931414039477, 'colsample_bytree': 0.6485183176783933, 'reg_alpha': 3.417617266945696, 'reg_lambda': 0.026929153590830514}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  67%|████████████████████████████████████████████████████████████████████████▊                                    | 668/1000 [51:23<24:09,  4.37s/it]

[I 2026-05-19 14:46:14,941] Trial 667 finished with value: 0.9498551565466962 and parameters: {'n_estimators': 289, 'learning_rate': 0.04643367006845469, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 63, 'subsample': 0.6205684085830295, 'colsample_bytree': 0.6511281292061258, 'reg_alpha': 3.3635395310205705, 'reg_lambda': 96.1537385897941}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  67%|████████████████████████████████████████████████████████████████████████▉                                    | 669/1000 [51:34<35:12,  6.38s/it]

[I 2026-05-19 14:46:26,040] Trial 668 finished with value: 0.9498689315561594 and parameters: {'n_estimators': 270, 'learning_rate': 0.04594709253320979, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 74, 'subsample': 0.6114011096277587, 'colsample_bytree': 0.6521851170623976, 'reg_alpha': 3.376867986437744, 'reg_lambda': 7.60763764438797}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  67%|█████████████████████████████████████████████████████████████████████████                                    | 670/1000 [51:35<26:39,  4.85s/it]

[I 2026-05-19 14:46:27,298] Trial 669 finished with value: 0.9498676964517159 and parameters: {'n_estimators': 270, 'learning_rate': 0.04053126251418944, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 74, 'subsample': 0.6099847633575564, 'colsample_bytree': 0.6494244767958698, 'reg_alpha': 3.6838986678338665, 'reg_lambda': 0.011097046516123948}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  67%|█████████████████████████████████████████████████████████████████████████▏                                   | 671/1000 [51:46<36:57,  6.74s/it]

[I 2026-05-19 14:46:38,485] Trial 670 finished with value: 0.9498706415066493 and parameters: {'n_estimators': 270, 'learning_rate': 0.040687447833251476, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 75, 'subsample': 0.8463788462836166, 'colsample_bytree': 0.6478307266552108, 'reg_alpha': 3.102569485290923, 'reg_lambda': 6.549567619052073}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  67%|█████████████████████████████████████████████████████████████████████████▏                                   | 672/1000 [51:47<27:30,  5.03s/it]

[I 2026-05-19 14:46:39,509] Trial 671 finished with value: 0.9498651994930014 and parameters: {'n_estimators': 271, 'learning_rate': 0.04998081429888837, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 87, 'subsample': 0.6127025385806564, 'colsample_bytree': 0.6101583204001724, 'reg_alpha': 3.2209154844829113, 'reg_lambda': 1.9700746347033082}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  67%|█████████████████████████████████████████████████████████████████████████▎                                   | 673/1000 [51:48<21:07,  3.88s/it]

[I 2026-05-19 14:46:40,704] Trial 672 finished with value: 0.9498673964398401 and parameters: {'n_estimators': 250, 'learning_rate': 0.04813954501494285, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 112, 'subsample': 0.6089401250347307, 'colsample_bytree': 0.6124598516036496, 'reg_alpha': 3.0795285793643616, 'reg_lambda': 0.010205946096367298}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  67%|█████████████████████████████████████████████████████████████████████████▍                                   | 674/1000 [51:59<32:23,  5.96s/it]

[I 2026-05-19 14:46:51,444] Trial 673 finished with value: 0.9498780799276327 and parameters: {'n_estimators': 270, 'learning_rate': 0.049839388903712194, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 88, 'subsample': 0.612278743612365, 'colsample_bytree': 0.6087654355442668, 'reg_alpha': 3.807411021944289, 'reg_lambda': 1.8193945776185552}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  68%|█████████████████████████████████████████████████████████████████████████▌                                   | 675/1000 [52:03<29:18,  5.41s/it]

[I 2026-05-19 14:46:55,648] Trial 675 finished with value: 0.949853874293332 and parameters: {'n_estimators': 273, 'learning_rate': 0.048807650318028646, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 116, 'subsample': 0.6118334018083282, 'colsample_bytree': 0.6111003398569572, 'reg_alpha': 3.112863067301966, 'reg_lambda': 97.38690559687439}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  68%|█████████████████████████████████████████████████████████████████████████▋                                   | 676/1000 [52:04<21:02,  3.90s/it]

[I 2026-05-19 14:46:55,987] Trial 674 finished with value: 0.949863701188254 and parameters: {'n_estimators': 269, 'learning_rate': 0.04923688912944366, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 113, 'subsample': 0.6088795731965938, 'colsample_bytree': 0.6112654867873287, 'reg_alpha': 3.118800119354565, 'reg_lambda': 1.7543387842952192}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  68%|█████████████████████████████████████████████████████████████████████████▊                                   | 677/1000 [52:07<19:57,  3.71s/it]

[I 2026-05-19 14:46:59,289] Trial 676 finished with value: 0.9498781355625555 and parameters: {'n_estimators': 269, 'learning_rate': 0.04993720081066874, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 112, 'subsample': 0.609753192390386, 'colsample_bytree': 0.6088680382082666, 'reg_alpha': 2.9109221110386123, 'reg_lambda': 1.9178950615964865}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  68%|█████████████████████████████████████████████████████████████████████████▉                                   | 678/1000 [52:08<16:22,  3.05s/it]

[I 2026-05-19 14:47:00,788] Trial 678 finished with value: 0.9498669768486276 and parameters: {'n_estimators': 270, 'learning_rate': 0.049282706159554324, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 110, 'subsample': 0.6093618235388124, 'colsample_bytree': 0.6150934306190978, 'reg_alpha': 5.802833585633367, 'reg_lambda': 1.9642950420375196}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  68%|██████████████████████████████████████████████████████████████████████████                                   | 679/1000 [52:16<24:19,  4.55s/it]

[I 2026-05-19 14:47:08,813] Trial 677 finished with value: 0.9498255564155771 and parameters: {'n_estimators': 269, 'learning_rate': 0.019821075932077614, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 111, 'subsample': 0.6100398196730805, 'colsample_bytree': 0.6082150321243026, 'reg_alpha': 2.7344211523927617, 'reg_lambda': 1.5337890718235008}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  68%|██████████████████████████████████████████████████████████████████████████                                   | 680/1000 [52:20<22:34,  4.23s/it]

[I 2026-05-19 14:47:12,316] Trial 679 finished with value: 0.9498618250993547 and parameters: {'n_estimators': 272, 'learning_rate': 0.049206829607856085, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 108, 'subsample': 0.6083143517461704, 'colsample_bytree': 0.6106630596657191, 'reg_alpha': 5.647716249352731, 'reg_lambda': 1.923392717017471}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  68%|██████████████████████████████████████████████████████████████████████████▏                                  | 681/1000 [52:23<21:23,  4.02s/it]

[I 2026-05-19 14:47:15,874] Trial 680 finished with value: 0.949865830302446 and parameters: {'n_estimators': 251, 'learning_rate': 0.04964275390208964, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 112, 'subsample': 0.610010458444892, 'colsample_bytree': 0.6129068363419551, 'reg_alpha': 5.89029600606394, 'reg_lambda': 1.974273672579111}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  68%|██████████████████████████████████████████████████████████████████████████▎                                  | 682/1000 [52:26<19:31,  3.68s/it]

[I 2026-05-19 14:47:18,761] Trial 681 finished with value: 0.9498641752621758 and parameters: {'n_estimators': 248, 'learning_rate': 0.048667176237747606, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 112, 'subsample': 0.6320384420066107, 'colsample_bytree': 0.6095585238151955, 'reg_alpha': 5.579398829078046, 'reg_lambda': 1.7286411452314063}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  68%|██████████████████████████████████████████████████████████████████████████▍                                  | 683/1000 [52:47<45:52,  8.68s/it]

[I 2026-05-19 14:47:39,099] Trial 683 finished with value: 0.9498616779876217 and parameters: {'n_estimators': 275, 'learning_rate': 0.035866257848852015, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 113, 'subsample': 0.6120836867128508, 'colsample_bytree': 0.6091680601735552, 'reg_alpha': 5.572544436332139, 'reg_lambda': 1.3205312452725504}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  68%|██████████████████████████████████████████████████████████████████████████▌                                  | 684/1000 [52:49<34:58,  6.64s/it]

[I 2026-05-19 14:47:40,981] Trial 682 finished with value: 0.9498306746685911 and parameters: {'n_estimators': 274, 'learning_rate': 0.020159178691774506, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 118, 'subsample': 0.6105586937428423, 'colsample_bytree': 0.6093389094907982, 'reg_alpha': 5.389593977321043, 'reg_lambda': 1.3230889425522163}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  68%|██████████████████████████████████████████████████████████████████████████▋                                  | 685/1000 [52:49<25:08,  4.79s/it]

[I 2026-05-19 14:47:41,454] Trial 684 finished with value: 0.9498640460143054 and parameters: {'n_estimators': 273, 'learning_rate': 0.03533425881253281, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 82, 'subsample': 0.6061223330381247, 'colsample_bytree': 0.6278011515209688, 'reg_alpha': 5.276732966332997, 'reg_lambda': 4.801055612126576}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  69%|██████████████████████████████████████████████████████████████████████████▊                                  | 686/1000 [52:50<19:01,  3.63s/it]

[I 2026-05-19 14:47:42,391] Trial 685 finished with value: 0.9498666091783937 and parameters: {'n_estimators': 255, 'learning_rate': 0.049389369707431685, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 82, 'subsample': 0.6085848065438855, 'colsample_bytree': 0.6108131818457904, 'reg_alpha': 5.33646157239631, 'reg_lambda': 1.2740506975772592}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  69%|██████████████████████████████████████████████████████████████████████████▉                                  | 687/1000 [53:00<28:37,  5.49s/it]

[I 2026-05-19 14:47:52,204] Trial 688 finished with value: 0.9498541953050902 and parameters: {'n_estimators': 255, 'learning_rate': 0.04858160202198459, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 118, 'subsample': 0.6317247139399644, 'colsample_bytree': 0.6058190954804784, 'reg_alpha': 1.7763266325015306, 'reg_lambda': 1.2244774304419743}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  69%|██████████████████████████████████████████████████████████████████████████▉                                  | 688/1000 [53:01<21:15,  4.09s/it]

[I 2026-05-19 14:47:53,012] Trial 686 finished with value: 0.9498703126752831 and parameters: {'n_estimators': 274, 'learning_rate': 0.04900760461204746, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 82, 'subsample': 0.6063042384845952, 'colsample_bytree': 0.6076163650096527, 'reg_alpha': 5.6943551062870155, 'reg_lambda': 0.9869290357920223}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  69%|███████████████████████████████████████████████████████████████████████████                                  | 689/1000 [53:01<15:48,  3.05s/it]

[I 2026-05-19 14:47:53,623] Trial 689 finished with value: 0.9498429012603011 and parameters: {'n_estimators': 259, 'learning_rate': 0.04863882294254458, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 118, 'subsample': 0.6294045213539531, 'colsample_bytree': 0.6075750170221456, 'reg_alpha': 0.012698142074002683, 'reg_lambda': 1.1674995140481583}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  69%|███████████████████████████████████████████████████████████████████████████▏                                 | 690/1000 [53:04<14:57,  2.89s/it]

[I 2026-05-19 14:47:56,176] Trial 687 finished with value: 0.9498587654555765 and parameters: {'n_estimators': 257, 'learning_rate': 0.048817604651382976, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 82, 'subsample': 0.6088995540233529, 'colsample_bytree': 0.9887133022319534, 'reg_alpha': 5.35732237626531, 'reg_lambda': 2.2758797086345064}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  69%|███████████████████████████████████████████████████████████████████████████▎                                 | 691/1000 [53:10<19:39,  3.82s/it]

[I 2026-05-19 14:48:02,151] Trial 691 finished with value: 0.9498514479064939 and parameters: {'n_estimators': 250, 'learning_rate': 0.04879333057657545, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 123, 'subsample': 0.6314128592177516, 'colsample_bytree': 0.6047918819678573, 'reg_alpha': 1.7278980396448664, 'reg_lambda': 1.082449403538841}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  69%|███████████████████████████████████████████████████████████████████████████▍                                 | 692/1000 [53:13<18:12,  3.55s/it]

[I 2026-05-19 14:48:05,076] Trial 690 finished with value: 0.9498571877328088 and parameters: {'n_estimators': 261, 'learning_rate': 0.04998949452347558, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 120, 'subsample': 0.6012273317729674, 'colsample_bytree': 0.6082516979041553, 'reg_alpha': 0.5456819421512599, 'reg_lambda': 1.1507954185635938}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  69%|███████████████████████████████████████████████████████████████████████████▌                                 | 693/1000 [53:16<18:11,  3.56s/it]

[I 2026-05-19 14:48:08,630] Trial 692 finished with value: 0.9498649855715721 and parameters: {'n_estimators': 257, 'learning_rate': 0.04932384324178671, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 106, 'subsample': 0.6262999274405937, 'colsample_bytree': 0.6038576970086535, 'reg_alpha': 1.7834993533505201, 'reg_lambda': 1.4778071049485995}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  69%|███████████████████████████████████████████████████████████████████████████▋                                 | 694/1000 [53:23<22:33,  4.42s/it]

[I 2026-05-19 14:48:15,077] Trial 693 finished with value: 0.949857976088625 and parameters: {'n_estimators': 259, 'learning_rate': 0.04718199498458742, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 120, 'subsample': 0.6014422175051004, 'colsample_bytree': 0.6067161121175823, 'reg_alpha': 0.014572492925334218, 'reg_lambda': 1.147012718183584}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  70%|███████████████████████████████████████████████████████████████████████████▊                                 | 695/1000 [53:40<42:28,  8.36s/it]

[I 2026-05-19 14:48:32,617] Trial 695 finished with value: 0.9498667432190274 and parameters: {'n_estimators': 264, 'learning_rate': 0.04995993904704966, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 105, 'subsample': 0.6307113269769518, 'colsample_bytree': 0.6048258141121903, 'reg_alpha': 1.874425069123561, 'reg_lambda': 0.9255552234525914}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  70%|███████████████████████████████████████████████████████████████████████████▊                                 | 696/1000 [53:43<33:20,  6.58s/it]

[I 2026-05-19 14:48:35,062] Trial 694 finished with value: 0.9498556568051306 and parameters: {'n_estimators': 261, 'learning_rate': 0.047058351952861635, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 82, 'subsample': 0.6000957743264339, 'colsample_bytree': 0.604488959560083, 'reg_alpha': 0.16253942692208265, 'reg_lambda': 1.1314773528225983}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:48:35,254] Trial 696 finished with value: 0.9498657372691905 and parameters: {'n_estimators': 267, 'learning_rate': 0.049597116608536634, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 120, 'subsample': 0.732133720359298, 'colsample_bytree': 0.600633569418898, 'reg_alpha': 1.8804555592688883, 'reg_lambda': 0.7767046606069712}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  70%|████████████████████████████████████████████████████████████████████████████                                 | 698/1000 [53:44<18:01,  3.58s/it]

[I 2026-05-19 14:48:36,297] Trial 697 finished with value: 0.9498560169047915 and parameters: {'n_estimators': 259, 'learning_rate': 0.049629917372525846, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 121, 'subsample': 0.6284645680282361, 'colsample_bytree': 0.6165191320969959, 'reg_alpha': 1.6546998292714377, 'reg_lambda': 0.816439132883958}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  70%|████████████████████████████████████████████████████████████████████████████▏                                | 699/1000 [53:53<26:58,  5.38s/it]

[I 2026-05-19 14:48:45,871] Trial 698 finished with value: 0.949853489041676 and parameters: {'n_estimators': 259, 'learning_rate': 0.04708769692114981, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 106, 'subsample': 0.6279997140491659, 'colsample_bytree': 0.604044301607045, 'reg_alpha': 0.01347871615003686, 'reg_lambda': 2.1957324851309377}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  70%|████████████████████████████████████████████████████████████████████████████▎                                | 700/1000 [53:54<19:21,  3.87s/it]

[I 2026-05-19 14:48:46,236] Trial 700 finished with value: 0.9498670043355852 and parameters: {'n_estimators': 259, 'learning_rate': 0.047010345782510295, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 103, 'subsample': 0.9791240455504735, 'colsample_bytree': 0.6001005535332985, 'reg_alpha': 1.8204753519182244, 'reg_lambda': 0.8025775287362467}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  70%|████████████████████████████████████████████████████████████████████████████▍                                | 701/1000 [54:00<22:06,  4.44s/it]

[I 2026-05-19 14:48:51,985] Trial 699 finished with value: 0.9498630227101138 and parameters: {'n_estimators': 261, 'learning_rate': 0.046693657892177894, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 106, 'subsample': 0.6272862961250915, 'colsample_bytree': 0.626095230947758, 'reg_alpha': 1.880363778893519, 'reg_lambda': 2.2524485852473153}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  70%|████████████████████████████████████████████████████████████████████████████▌                                | 702/1000 [54:00<16:10,  3.26s/it]

[I 2026-05-19 14:48:52,492] Trial 701 finished with value: 0.9498648969271042 and parameters: {'n_estimators': 267, 'learning_rate': 0.04639541369112441, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 121, 'subsample': 0.6001544262609076, 'colsample_bytree': 0.6207377701651949, 'reg_alpha': 1.803373754023184, 'reg_lambda': 2.181341014685197}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  70%|████████████████████████████████████████████████████████████████████████████▋                                | 703/1000 [54:06<20:27,  4.13s/it]

[I 2026-05-19 14:48:58,673] Trial 703 finished with value: 0.9498720407229573 and parameters: {'n_estimators': 267, 'learning_rate': 0.04598989646053482, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 105, 'subsample': 0.9767042173767387, 'colsample_bytree': 0.6174684714304616, 'reg_alpha': 2.0902213364142104, 'reg_lambda': 2.4827261198040116}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  70%|████████████████████████████████████████████████████████████████████████████▋                                | 704/1000 [54:09<18:59,  3.85s/it]

[I 2026-05-19 14:49:01,827] Trial 702 finished with value: 0.9498576090565661 and parameters: {'n_estimators': 268, 'learning_rate': 0.04578101756938289, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 101, 'subsample': 0.9279164206099684, 'colsample_bytree': 0.826313402854228, 'reg_alpha': 2.01550837824734, 'reg_lambda': 2.984867587896774}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  70%|████████████████████████████████████████████████████████████████████████████▊                                | 705/1000 [54:10<13:32,  2.75s/it]

[I 2026-05-19 14:49:02,053] Trial 704 finished with value: 0.9498635904545797 and parameters: {'n_estimators': 264, 'learning_rate': 0.04597351371110614, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 104, 'subsample': 0.6576804640481017, 'colsample_bytree': 0.6166142983396694, 'reg_alpha': 2.4973639223826005, 'reg_lambda': 0.807008466977741}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  71%|████████████████████████████████████████████████████████████████████████████▉                                | 706/1000 [54:18<21:53,  4.47s/it]

[I 2026-05-19 14:49:10,527] Trial 705 finished with value: 0.9498645665900612 and parameters: {'n_estimators': 268, 'learning_rate': 0.04578228291212401, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 104, 'subsample': 0.6553010431789424, 'colsample_bytree': 0.6171198201251643, 'reg_alpha': 2.488215404260825, 'reg_lambda': 2.267205160925156}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  71%|█████████████████████████████████████████████████████████████████████████████                                | 707/1000 [54:27<27:47,  5.69s/it]

[I 2026-05-19 14:49:19,029] Trial 709 finished with value: 0.9498445985430027 and parameters: {'n_estimators': 275, 'learning_rate': 0.04572979474434089, 'max_depth': 4, 'num_leaves': 5, 'min_child_samples': 102, 'subsample': 0.9351965936688631, 'colsample_bytree': 0.6268121520040262, 'reg_alpha': 2.5287739828220914, 'reg_lambda': 2.5156097370892527}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  71%|█████████████████████████████████████████████████████████████████████████████▏                               | 708/1000 [54:38<35:11,  7.23s/it]

[I 2026-05-19 14:49:29,894] Trial 708 finished with value: 0.9498632797602022 and parameters: {'n_estimators': 267, 'learning_rate': 0.045209491045863796, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 149, 'subsample': 0.6543030567851835, 'colsample_bytree': 0.6259500294448325, 'reg_alpha': 2.73088509765416, 'reg_lambda': 2.5703873924450376}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:49:30,101] Trial 715 finished with value: 0.9497635889232556 and parameters: {'n_estimators': 276, 'learning_rate': 0.040206911904454044, 'max_depth': 1, 'num_leaves': 12, 'min_child_samples': 89, 'subsample': 0.826147449146035, 'colsample_bytree': 0.6263404229688436, 'reg_alpha': 2.651846702780141, 'reg_lambda': 3.021021306955655}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  71%|█████████████████████████████████████████████████████████████████████████████▍                               | 710/1000 [54:38<18:32,  3.84s/it]

[I 2026-05-19 14:49:30,937] Trial 706 finished with value: 0.949868743955862 and parameters: {'n_estimators': 267, 'learning_rate': 0.04588530835345725, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 98, 'subsample': 0.6557333675601973, 'colsample_bytree': 0.6180397711584514, 'reg_alpha': 2.5714135855018205, 'reg_lambda': 2.1511131265679593}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  71%|█████████████████████████████████████████████████████████████████████████████▍                               | 711/1000 [54:39<14:13,  2.95s/it]

[I 2026-05-19 14:49:31,818] Trial 707 finished with value: 0.9498627077313883 and parameters: {'n_estimators': 268, 'learning_rate': 0.04543854237008925, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 98, 'subsample': 0.9754879349734201, 'colsample_bytree': 0.7117652053681763, 'reg_alpha': 2.4336964054919803, 'reg_lambda': 2.5682983576602636}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  71%|█████████████████████████████████████████████████████████████████████████████▌                               | 712/1000 [54:42<14:03,  2.93s/it]

[I 2026-05-19 14:49:34,699] Trial 711 finished with value: 0.9498576101814905 and parameters: {'n_estimators': 234, 'learning_rate': 0.045779445709530305, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 96, 'subsample': 0.638512627636272, 'colsample_bytree': 0.625147497874278, 'reg_alpha': 0.09268868229977381, 'reg_lambda': 2.6827863699000036}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  71%|█████████████████████████████████████████████████████████████████████████████▋                               | 713/1000 [54:51<21:52,  4.57s/it]

[I 2026-05-19 14:49:43,088] Trial 710 finished with value: 0.9498705897014383 and parameters: {'n_estimators': 268, 'learning_rate': 0.0452906402744846, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 97, 'subsample': 0.6570933445813715, 'colsample_bytree': 0.6274418092622195, 'reg_alpha': 2.435347397910464, 'reg_lambda': 2.905703685478953}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  71%|█████████████████████████████████████████████████████████████████████████████▊                               | 714/1000 [54:56<22:17,  4.68s/it]

[I 2026-05-19 14:49:48,028] Trial 712 finished with value: 0.9498518415662645 and parameters: {'n_estimators': 267, 'learning_rate': 0.040752879627308364, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 97, 'subsample': 0.8654851713654194, 'colsample_bytree': 0.6274542674369906, 'reg_alpha': 3.5447231304137974e-05, 'reg_lambda': 2.841995541177924}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  72%|█████████████████████████████████████████████████████████████████████████████▉                               | 715/1000 [54:56<16:21,  3.44s/it]

[I 2026-05-19 14:49:48,602] Trial 718 finished with value: 0.9497768212378146 and parameters: {'n_estimators': 281, 'learning_rate': 0.04108029380443311, 'max_depth': 1, 'num_leaves': 12, 'min_child_samples': 132, 'subsample': 0.6407241493608531, 'colsample_bytree': 0.6274457129792447, 'reg_alpha': 4.243862933646359, 'reg_lambda': 2.8942267487626725}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  72%|██████████████████████████████████████████████████████████████████████████████                               | 716/1000 [55:00<16:43,  3.54s/it]

[I 2026-05-19 14:49:52,353] Trial 713 finished with value: 0.9498718962429373 and parameters: {'n_estimators': 276, 'learning_rate': 0.04107951723482848, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 96, 'subsample': 0.6511245703126338, 'colsample_bytree': 0.6247856065396861, 'reg_alpha': 2.541846900053695, 'reg_lambda': 2.853839882577871}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  72%|██████████████████████████████████████████████████████████████████████████████▏                              | 717/1000 [55:08<23:06,  4.90s/it]

[I 2026-05-19 14:50:00,423] Trial 714 finished with value: 0.9498076898924406 and parameters: {'n_estimators': 276, 'learning_rate': 0.015235487419076063, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 97, 'subsample': 0.6476770817415726, 'colsample_bytree': 0.6240371942085087, 'reg_alpha': 2.67018548544602, 'reg_lambda': 0.00022062195255362626}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  72%|██████████████████████████████████████████████████████████████████████████████▎                              | 718/1000 [55:11<20:41,  4.40s/it]

[I 2026-05-19 14:50:03,660] Trial 716 finished with value: 0.9498665833153572 and parameters: {'n_estimators': 276, 'learning_rate': 0.04141216937518564, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 96, 'subsample': 0.6498830027460004, 'colsample_bytree': 0.7795564397888668, 'reg_alpha': 2.564974954895689, 'reg_lambda': 2.865005768669887}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  72%|██████████████████████████████████████████████████████████████████████████████▎                              | 719/1000 [55:14<18:32,  3.96s/it]

[I 2026-05-19 14:50:06,582] Trial 723 finished with value: 0.9498227735815842 and parameters: {'n_estimators': 135, 'learning_rate': 0.041105629368627626, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 78, 'subsample': 0.9906676508968529, 'colsample_bytree': 0.6400451913985493, 'reg_alpha': 12.376721693792406, 'reg_lambda': 4.324919872946628}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  72%|██████████████████████████████████████████████████████████████████████████████▍                              | 720/1000 [55:14<13:26,  2.88s/it]

[I 2026-05-19 14:50:06,939] Trial 717 finished with value: 0.9498633440692148 and parameters: {'n_estimators': 276, 'learning_rate': 0.040961237679433354, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 91, 'subsample': 0.6472997511198992, 'colsample_bytree': 0.6270702954115, 'reg_alpha': 2.759073115266849, 'reg_lambda': 3.016516404759933}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  72%|██████████████████████████████████████████████████████████████████████████████▌                              | 721/1000 [55:32<34:23,  7.40s/it]

[I 2026-05-19 14:50:24,883] Trial 719 finished with value: 0.949873257919198 and parameters: {'n_estimators': 282, 'learning_rate': 0.04146820937928521, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 89, 'subsample': 0.6462389066610734, 'colsample_bytree': 0.6278998887125226, 'reg_alpha': 4.284654638601539, 'reg_lambda': 4.4557500820655624}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  72%|██████████████████████████████████████████████████████████████████████████████▋                              | 722/1000 [55:36<28:19,  6.12s/it]

[I 2026-05-19 14:50:28,008] Trial 720 finished with value: 0.949871828170344 and parameters: {'n_estimators': 282, 'learning_rate': 0.0407470359865599, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 97, 'subsample': 0.9098093068857446, 'colsample_bytree': 0.6423931455134878, 'reg_alpha': 4.067009339947023, 'reg_lambda': 4.192952827585113}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  72%|██████████████████████████████████████████████████████████████████████████████▊                              | 723/1000 [55:37<21:27,  4.65s/it]

[I 2026-05-19 14:50:29,227] Trial 722 finished with value: 0.9498708868011875 and parameters: {'n_estimators': 282, 'learning_rate': 0.04098977005634124, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 91, 'subsample': 0.643222736881789, 'colsample_bytree': 0.6293337708146046, 'reg_alpha': 4.11811069572785, 'reg_lambda': 4.330950464892356}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  72%|██████████████████████████████████████████████████████████████████████████████▉                              | 724/1000 [55:41<20:55,  4.55s/it]

[I 2026-05-19 14:50:33,554] Trial 721 finished with value: 0.9498710585180266 and parameters: {'n_estimators': 282, 'learning_rate': 0.040557636419706375, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 92, 'subsample': 0.9948073399357158, 'colsample_bytree': 0.6403934821312763, 'reg_alpha': 4.0886932282002135, 'reg_lambda': 4.6590149978025766}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  72%|███████████████████████████████████████████████████████████████████████████████                              | 725/1000 [55:44<18:33,  4.05s/it]

[I 2026-05-19 14:50:36,418] Trial 731 finished with value: 0.9498272856427313 and parameters: {'n_estimators': 126, 'learning_rate': 0.04281296873279015, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 70, 'subsample': 0.6177931572514525, 'colsample_bytree': 0.6431947687814717, 'reg_alpha': 4.407659177058843, 'reg_lambda': 5.304183981388559}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  73%|███████████████████████████████████████████████████████████████████████████████▏                             | 726/1000 [55:49<20:09,  4.42s/it]

[I 2026-05-19 14:50:41,693] Trial 724 finished with value: 0.9498708269073612 and parameters: {'n_estimators': 282, 'learning_rate': 0.041043093269819864, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 89, 'subsample': 0.6158376833852819, 'colsample_bytree': 0.6400795548781523, 'reg_alpha': 4.1174427528341955, 'reg_lambda': 4.1757436847094}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  73%|███████████████████████████████████████████████████████████████████████████████▎                             | 728/1000 [55:55<15:22,  3.39s/it]

[I 2026-05-19 14:50:47,351] Trial 726 finished with value: 0.9498675857908742 and parameters: {'n_estimators': 282, 'learning_rate': 0.041418558562870175, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 90, 'subsample': 0.6184712086069426, 'colsample_bytree': 0.6429129282253989, 'reg_alpha': 4.3445504416764615, 'reg_lambda': 0.004764640034368365}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:50:47,487] Trial 725 finished with value: 0.9498746775532545 and parameters: {'n_estimators': 282, 'learning_rate': 0.04223203044661596, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 90, 'subsample': 0.6468856861637905, 'colsample_bytree': 0.6362302646883692, 'reg_alpha': 4.206538528286881, 'reg_lambda': 4.488424862295725}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  73%|███████████████████████████████████████████████████████████████████████████████▍                             | 729/1000 [56:03<21:12,  4.70s/it]

[I 2026-05-19 14:50:55,245] Trial 727 finished with value: 0.9498721405471313 and parameters: {'n_estimators': 284, 'learning_rate': 0.04215215581843428, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 78, 'subsample': 0.9928262429944735, 'colsample_bytree': 0.6442213711409005, 'reg_alpha': 4.263990521645785, 'reg_lambda': 4.174482488231731}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  73%|███████████████████████████████████████████████████████████████████████████████▌                             | 730/1000 [56:09<23:01,  5.12s/it]

[I 2026-05-19 14:51:01,337] Trial 728 finished with value: 0.9498590030146465 and parameters: {'n_estimators': 283, 'learning_rate': 0.04275007247143058, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 89, 'subsample': 0.6157897659021263, 'colsample_bytree': 0.6424157994422606, 'reg_alpha': 11.583391748839205, 'reg_lambda': 4.152795498738289}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  73%|███████████████████████████████████████████████████████████████████████████████▋                             | 731/1000 [56:10<17:55,  4.00s/it]

[I 2026-05-19 14:51:02,717] Trial 729 finished with value: 0.9498591821455253 and parameters: {'n_estimators': 283, 'learning_rate': 0.042701969538178806, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 228, 'subsample': 0.9924378621549801, 'colsample_bytree': 0.6386658331761583, 'reg_alpha': 12.69821829841649, 'reg_lambda': 4.423493274062496}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  73%|███████████████████████████████████████████████████████████████████████████████▊                             | 732/1000 [56:16<20:22,  4.56s/it]

[I 2026-05-19 14:51:08,587] Trial 730 finished with value: 0.9498727190418068 and parameters: {'n_estimators': 283, 'learning_rate': 0.0422810059850294, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 78, 'subsample': 0.6154363742321042, 'colsample_bytree': 0.6407292721320054, 'reg_alpha': 4.031254010439817, 'reg_lambda': 4.612669166947452}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  73%|███████████████████████████████████████████████████████████████████████████████▉                             | 733/1000 [56:30<32:51,  7.38s/it]

[I 2026-05-19 14:51:22,561] Trial 732 finished with value: 0.9498677994291004 and parameters: {'n_estimators': 284, 'learning_rate': 0.042595042014371795, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 79, 'subsample': 0.6169097652741624, 'colsample_bytree': 0.6402455062848097, 'reg_alpha': 4.146842558135599, 'reg_lambda': 4.417555558050823}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  73%|████████████████████████████████████████████████████████████████████████████████                             | 734/1000 [56:35<28:49,  6.50s/it]

[I 2026-05-19 14:51:27,012] Trial 733 finished with value: 0.9498751687619105 and parameters: {'n_estimators': 283, 'learning_rate': 0.04405128601585743, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 156, 'subsample': 0.6154283922865308, 'colsample_bytree': 0.6421999638737482, 'reg_alpha': 7.011434605851326, 'reg_lambda': 4.686852581616494}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  74%|████████████████████████████████████████████████████████████████████████████████                             | 735/1000 [56:40<27:21,  6.20s/it]

[I 2026-05-19 14:51:32,484] Trial 734 finished with value: 0.9498709859574263 and parameters: {'n_estimators': 284, 'learning_rate': 0.043409347545254, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 70, 'subsample': 0.6157400586842684, 'colsample_bytree': 0.6422065651213792, 'reg_alpha': 7.084876531257505, 'reg_lambda': 1.5767933539012213}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  74%|████████████████████████████████████████████████████████████████████████████████▏                            | 736/1000 [56:41<20:48,  4.73s/it]

[I 2026-05-19 14:51:33,791] Trial 735 finished with value: 0.9498659116402791 and parameters: {'n_estimators': 293, 'learning_rate': 0.04331396584898903, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 78, 'subsample': 0.6172985292815244, 'colsample_bytree': 0.6413585397387971, 'reg_alpha': 8.137711238684956, 'reg_lambda': 1.6576287520999011}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  74%|████████████████████████████████████████████████████████████████████████████████▎                            | 737/1000 [56:44<18:18,  4.18s/it]

[I 2026-05-19 14:51:36,674] Trial 736 finished with value: 0.9498700930124813 and parameters: {'n_estimators': 284, 'learning_rate': 0.043487723355099324, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 80, 'subsample': 0.6144451400753312, 'colsample_bytree': 0.6407447683572868, 'reg_alpha': 7.316092600116568, 'reg_lambda': 1.8926410874032953}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  74%|████████████████████████████████████████████████████████████████████████████████▍                            | 738/1000 [56:51<21:40,  4.96s/it]

[I 2026-05-19 14:51:43,476] Trial 737 finished with value: 0.9498737524831732 and parameters: {'n_estimators': 284, 'learning_rate': 0.043538072484414096, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 76, 'subsample': 0.6147959509742367, 'colsample_bytree': 0.6164222107343239, 'reg_alpha': 7.633102491951925, 'reg_lambda': 5.567851173600439}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  74%|████████████████████████████████████████████████████████████████████████████████▌                            | 739/1000 [56:53<17:19,  3.98s/it]

[I 2026-05-19 14:51:45,178] Trial 738 finished with value: 0.9498668019694666 and parameters: {'n_estimators': 285, 'learning_rate': 0.043716817675302534, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 69, 'subsample': 0.8884358335107024, 'colsample_bytree': 0.6166836292682991, 'reg_alpha': 7.758809489014312, 'reg_lambda': 1.8581681470420597}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  74%|████████████████████████████████████████████████████████████████████████████████▋                            | 740/1000 [56:59<19:47,  4.57s/it]

[I 2026-05-19 14:51:51,110] Trial 739 finished with value: 0.9498571721786746 and parameters: {'n_estimators': 293, 'learning_rate': 0.03606272804381888, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 86, 'subsample': 0.6355588277699947, 'colsample_bytree': 0.614367629705722, 'reg_alpha': 0.29078435574834693, 'reg_lambda': 1.4840555651469154}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  74%|████████████████████████████████████████████████████████████████████████████████▊                            | 741/1000 [57:08<26:06,  6.05s/it]

[I 2026-05-19 14:52:00,604] Trial 740 finished with value: 0.9498674402010854 and parameters: {'n_estimators': 292, 'learning_rate': 0.03608791647135124, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 87, 'subsample': 0.6389595891738695, 'colsample_bytree': 0.6147400348871189, 'reg_alpha': 7.423329563649388, 'reg_lambda': 1.4750114287047023}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  74%|████████████████████████████████████████████████████████████████████████████████▉                            | 742/1000 [57:11<22:17,  5.19s/it]

[I 2026-05-19 14:52:03,778] Trial 741 finished with value: 0.9498661515277146 and parameters: {'n_estimators': 292, 'learning_rate': 0.03714653321705591, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 85, 'subsample': 0.6410486760075608, 'colsample_bytree': 0.6141309979346908, 'reg_alpha': 8.145827749936199, 'reg_lambda': 1.762949676283087}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  74%|████████████████████████████████████████████████████████████████████████████████▉                            | 743/1000 [57:16<20:58,  4.90s/it]

[I 2026-05-19 14:52:07,990] Trial 742 finished with value: 0.9498547685738534 and parameters: {'n_estimators': 293, 'learning_rate': 0.036137087981003436, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 85, 'subsample': 0.6381782741778098, 'colsample_bytree': 0.7247269145383473, 'reg_alpha': 7.520079144606319, 'reg_lambda': 1.613704178974474}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  74%|█████████████████████████████████████████████████████████████████████████████████                            | 744/1000 [57:19<18:30,  4.34s/it]

[I 2026-05-19 14:52:11,038] Trial 743 finished with value: 0.949861918195551 and parameters: {'n_estimators': 300, 'learning_rate': 0.0377106340784956, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 86, 'subsample': 0.6662703239255612, 'colsample_bytree': 0.6162360525342931, 'reg_alpha': 7.390524308936535, 'reg_lambda': 1.8187659491441788}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  74%|█████████████████████████████████████████████████████████████████████████████████▏                           | 745/1000 [57:31<29:11,  6.87s/it]

[I 2026-05-19 14:52:23,805] Trial 744 finished with value: 0.9498602028132375 and parameters: {'n_estimators': 292, 'learning_rate': 0.03744395920879761, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 159, 'subsample': 0.6399976366953282, 'colsample_bytree': 0.6147052421489292, 'reg_alpha': 7.6498057952305585, 'reg_lambda': 1.7272360332535937}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  75%|█████████████████████████████████████████████████████████████████████████████████▎                           | 746/1000 [57:38<28:19,  6.69s/it]

[I 2026-05-19 14:52:30,090] Trial 745 finished with value: 0.9498646460032057 and parameters: {'n_estimators': 300, 'learning_rate': 0.044439517896882774, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 133, 'subsample': 0.6336805562847146, 'colsample_bytree': 0.6534338786846109, 'reg_alpha': 7.857024600423625, 'reg_lambda': 6.48539726193629}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  75%|█████████████████████████████████████████████████████████████████████████████████▍                           | 747/1000 [57:40<22:23,  5.31s/it]

[I 2026-05-19 14:52:32,186] Trial 747 finished with value: 0.9498546483823471 and parameters: {'n_estimators': 275, 'learning_rate': 0.035866784451985836, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 147, 'subsample': 0.63641344606589, 'colsample_bytree': 0.6175174193599096, 'reg_alpha': 7.324929606036832, 'reg_lambda': 6.410821327554453}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  75%|█████████████████████████████████████████████████████████████████████████████████▌                           | 748/1000 [57:42<18:45,  4.47s/it]

[I 2026-05-19 14:52:34,682] Trial 748 finished with value: 0.949872618719718 and parameters: {'n_estimators': 275, 'learning_rate': 0.04500508657640739, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 155, 'subsample': 0.6376889757603568, 'colsample_bytree': 0.6147119019886862, 'reg_alpha': 7.361252971568503, 'reg_lambda': 6.593576601492952}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  75%|█████████████████████████████████████████████████████████████████████████████████▋                           | 749/1000 [57:44<15:38,  3.74s/it]

[I 2026-05-19 14:52:36,731] Trial 746 finished with value: 0.9495212110865099 and parameters: {'n_estimators': 292, 'learning_rate': 0.004895183281267261, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 143, 'subsample': 0.6359286409952967, 'colsample_bytree': 0.6157697929816509, 'reg_alpha': 7.8547316867631265, 'reg_lambda': 6.578589524269642}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  75%|█████████████████████████████████████████████████████████████████████████████████▊                           | 750/1000 [57:56<25:01,  6.01s/it]

[I 2026-05-19 14:52:48,021] Trial 750 finished with value: 0.9498623800240464 and parameters: {'n_estimators': 275, 'learning_rate': 0.03643010951309573, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 128, 'subsample': 0.633998222516288, 'colsample_bytree': 0.6339436756762051, 'reg_alpha': 9.073644650850325, 'reg_lambda': 7.053889311024407}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  75%|█████████████████████████████████████████████████████████████████████████████████▊                           | 751/1000 [57:56<18:34,  4.48s/it]

[I 2026-05-19 14:52:48,925] Trial 751 finished with value: 0.9498470701947159 and parameters: {'n_estimators': 275, 'learning_rate': 0.037838538569495046, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 64, 'subsample': 0.6342332698856965, 'colsample_bytree': 0.632828550406494, 'reg_alpha': 0.0005642046783630537, 'reg_lambda': 3.4715053300673176e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  75%|██████████████████████████████████████████████████████████████████████████████████                           | 753/1000 [58:05<16:35,  4.03s/it]

[I 2026-05-19 14:52:57,422] Trial 749 finished with value: 0.9494292238719716 and parameters: {'n_estimators': 300, 'learning_rate': 0.0039863691313362405, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 248, 'subsample': 0.6314393607291832, 'colsample_bytree': 0.8411389004919205, 'reg_alpha': 6.223957550937071, 'reg_lambda': 6.783934561938824}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:52:57,563] Trial 754 finished with value: 0.9498439044947536 and parameters: {'n_estimators': 275, 'learning_rate': 0.039006808521019405, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 179, 'subsample': 0.6001661713453684, 'colsample_bytree': 0.9333024226918503, 'reg_alpha': 5.8858786002679, 'reg_lambda': 6.6415138410037695}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  75%|██████████████████████████████████████████████████████████████████████████████████▏                          | 754/1000 [58:09<16:08,  3.94s/it]

[I 2026-05-19 14:53:01,331] Trial 753 finished with value: 0.9498681151934292 and parameters: {'n_estimators': 274, 'learning_rate': 0.03901137509306921, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 64, 'subsample': 0.6292216413227278, 'colsample_bytree': 0.6332358143719515, 'reg_alpha': 6.098426959026443, 'reg_lambda': 6.419895892469154}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  76%|██████████████████████████████████████████████████████████████████████████████████▎                          | 755/1000 [58:17<20:51,  5.11s/it]

[I 2026-05-19 14:53:09,145] Trial 752 finished with value: 0.9498513329351173 and parameters: {'n_estimators': 300, 'learning_rate': 0.03839793749934212, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 133, 'subsample': 0.6367895853844701, 'colsample_bytree': 0.9287370786639166, 'reg_alpha': 10.547220290194863, 'reg_lambda': 7.007648807677094}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  76%|██████████████████████████████████████████████████████████████████████████████████▍                          | 756/1000 [58:18<16:30,  4.06s/it]

[I 2026-05-19 14:53:10,762] Trial 756 finished with value: 0.9498389694770906 and parameters: {'n_estimators': 275, 'learning_rate': 0.04522542435332261, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 139, 'subsample': 0.626754551565379, 'colsample_bytree': 0.6525579814681195, 'reg_alpha': 35.55993180228221, 'reg_lambda': 6.6862242830323595}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  76%|██████████████████████████████████████████████████████████████████████████████████▌                          | 757/1000 [58:21<14:31,  3.59s/it]

[I 2026-05-19 14:53:13,220] Trial 755 finished with value: 0.9498536818614799 and parameters: {'n_estimators': 276, 'learning_rate': 0.04503865623464674, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 156, 'subsample': 0.6245263655513066, 'colsample_bytree': 0.9320526458990035, 'reg_alpha': 11.258746271115216, 'reg_lambda': 6.698716251929723}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  76%|██████████████████████████████████████████████████████████████████████████████████▌                          | 758/1000 [58:23<12:22,  3.07s/it]

[I 2026-05-19 14:53:15,107] Trial 757 finished with value: 0.9498510313459956 and parameters: {'n_estimators': 274, 'learning_rate': 0.046036049107923804, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 203, 'subsample': 0.6009478037011357, 'colsample_bytree': 0.6329282790514615, 'reg_alpha': 11.379728245454858, 'reg_lambda': 8.671752166468588}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  76%|██████████████████████████████████████████████████████████████████████████████████▋                          | 759/1000 [58:28<15:05,  3.76s/it]

[I 2026-05-19 14:53:20,475] Trial 758 finished with value: 0.9498404149035281 and parameters: {'n_estimators': 275, 'learning_rate': 0.039153043914767385, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 152, 'subsample': 0.6257924288183725, 'colsample_bytree': 0.6346268349101237, 'reg_alpha': 12.081512195662198, 'reg_lambda': 8.89313521796727}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  76%|██████████████████████████████████████████████████████████████████████████████████▊                          | 760/1000 [58:28<10:54,  2.73s/it]

[I 2026-05-19 14:53:20,789] Trial 759 finished with value: 0.9493555402332593 and parameters: {'n_estimators': 273, 'learning_rate': 0.004865006393762132, 'max_depth': 3, 'num_leaves': 16, 'min_child_samples': 62, 'subsample': 0.6001403654176691, 'colsample_bytree': 0.6331066411144964, 'reg_alpha': 11.516723150860658, 'reg_lambda': 10.595170468328378}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  76%|██████████████████████████████████████████████████████████████████████████████████▉                          | 761/1000 [58:41<22:52,  5.74s/it]

[I 2026-05-19 14:53:33,589] Trial 760 finished with value: 0.9498632116585917 and parameters: {'n_estimators': 273, 'learning_rate': 0.03882304037382017, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 109, 'subsample': 0.6275486839250705, 'colsample_bytree': 0.6315953948282138, 'reg_alpha': 11.60746416273479, 'reg_lambda': 3.294799004631197e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  76%|███████████████████████████████████████████████████████████████████████████████████                          | 762/1000 [58:51<27:54,  7.04s/it]

[I 2026-05-19 14:53:43,626] Trial 761 finished with value: 0.9498687301022752 and parameters: {'n_estimators': 273, 'learning_rate': 0.04709681816415855, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 109, 'subsample': 0.6079992447738984, 'colsample_bytree': 0.6337367708762045, 'reg_alpha': 14.774411066260111, 'reg_lambda': 0.0001582584818064522}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  76%|███████████████████████████████████████████████████████████████████████████████████▏                         | 763/1000 [58:53<21:59,  5.57s/it]

[I 2026-05-19 14:53:45,763] Trial 763 finished with value: 0.949840784512223 and parameters: {'n_estimators': 272, 'learning_rate': 0.04682833752670885, 'max_depth': 3, 'num_leaves': 9, 'min_child_samples': 170, 'subsample': 0.607666158859828, 'colsample_bytree': 0.6538161210112704, 'reg_alpha': 31.200032019962144, 'reg_lambda': 10.766222056698307}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  76%|███████████████████████████████████████████████████████████████████████████████████▎                         | 764/1000 [59:01<23:48,  6.05s/it]

[I 2026-05-19 14:53:52,947] Trial 762 finished with value: 0.9498525836650454 and parameters: {'n_estimators': 273, 'learning_rate': 0.03934256201758918, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 62, 'subsample': 0.6250329234825457, 'colsample_bytree': 0.6517765461511389, 'reg_alpha': 16.87700225197856, 'reg_lambda': 3.3765660767317236}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  76%|███████████████████████████████████████████████████████████████████████████████████▍                         | 765/1000 [59:02<18:31,  4.73s/it]

[I 2026-05-19 14:53:54,606] Trial 767 finished with value: 0.9498515218332093 and parameters: {'n_estimators': 198, 'learning_rate': 0.04745610927967331, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 109, 'subsample': 0.6089235912807579, 'colsample_bytree': 0.6329179995153233, 'reg_alpha': 0.00034023436627426875, 'reg_lambda': 3.4882621212724563}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  77%|███████████████████████████████████████████████████████████████████████████████████▍                         | 766/1000 [59:05<16:24,  4.21s/it]

[I 2026-05-19 14:53:57,597] Trial 764 finished with value: 0.949859343391285 and parameters: {'n_estimators': 277, 'learning_rate': 0.04589441570259541, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 103, 'subsample': 0.622819228933734, 'colsample_bytree': 0.6534322754267077, 'reg_alpha': 12.433082358871312, 'reg_lambda': 10.338932315419253}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  77%|███████████████████████████████████████████████████████████████████████████████████▌                         | 767/1000 [59:10<17:01,  4.38s/it]

[I 2026-05-19 14:54:02,379] Trial 765 finished with value: 0.9497598917598801 and parameters: {'n_estimators': 272, 'learning_rate': 0.013391072026282072, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 173, 'subsample': 0.6228434333869368, 'colsample_bytree': 0.6539795791526595, 'reg_alpha': 14.036292172770848, 'reg_lambda': 10.104396548232906}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  77%|███████████████████████████████████████████████████████████████████████████████████▋                         | 768/1000 [59:15<18:09,  4.70s/it]

[I 2026-05-19 14:54:07,816] Trial 766 finished with value: 0.9498567855194215 and parameters: {'n_estimators': 272, 'learning_rate': 0.04701035055683739, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 170, 'subsample': 0.6004522214947766, 'colsample_bytree': 0.6549370351209044, 'reg_alpha': 12.824394479649516, 'reg_lambda': 9.810605090422102}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  77%|███████████████████████████████████████████████████████████████████████████████████▊                         | 769/1000 [59:20<18:13,  4.73s/it]

[I 2026-05-19 14:54:12,627] Trial 773 finished with value: 0.9496073970472432 and parameters: {'n_estimators': 113, 'learning_rate': 0.013727655213374173, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 101, 'subsample': 0.6145638517719527, 'colsample_bytree': 0.6545321220788417, 'reg_alpha': 5.005149667227579, 'reg_lambda': 3.378956207884268}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  77%|███████████████████████████████████████████████████████████████████████████████████▉                         | 770/1000 [59:22<14:31,  3.79s/it]

[I 2026-05-19 14:54:14,211] Trial 768 finished with value: 0.9498523379790755 and parameters: {'n_estimators': 280, 'learning_rate': 0.0469104646885062, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 103, 'subsample': 0.6077282147546498, 'colsample_bytree': 0.6320116672831086, 'reg_alpha': 16.270513778108644, 'reg_lambda': 3.46106484374611}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  77%|████████████████████████████████████████████████████████████████████████████████████                         | 771/1000 [59:25<13:28,  3.53s/it]

[I 2026-05-19 14:54:17,121] Trial 770 finished with value: 0.9498568727251359 and parameters: {'n_estimators': 279, 'learning_rate': 0.047376280362444706, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 110, 'subsample': 0.6073899961670999, 'colsample_bytree': 0.6490068533282818, 'reg_alpha': 17.050583423382122, 'reg_lambda': 3.266214232973138}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:54:17,321] Trial 769 finished with value: 0.9498592753181594 and parameters: {'n_estimators': 280, 'learning_rate': 0.047142586272277055, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 110, 'subsample': 0.6236279388790407, 'colsample_bytree': 0.6541548914239762, 'reg_alpha': 4.926764947786529, 'reg_lambda': 3.482905239245735}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  77%|████████████████████████████████████████████████████████████████████████████████████▎                        | 773/1000 [59:27<09:32,  2.52s/it]

[I 2026-05-19 14:54:19,839] Trial 771 finished with value: 0.9498594816404424 and parameters: {'n_estimators': 279, 'learning_rate': 0.04726153204727148, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 191, 'subsample': 0.6084251332150613, 'colsample_bytree': 0.65358156268743, 'reg_alpha': 16.74109910593089, 'reg_lambda': 0.00015670464171385704}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  77%|████████████████████████████████████████████████████████████████████████████████████▎                        | 774/1000 [59:44<25:44,  6.84s/it]

[I 2026-05-19 14:54:36,732] Trial 772 finished with value: 0.949867512868599 and parameters: {'n_estimators': 288, 'learning_rate': 0.047292408055279886, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 102, 'subsample': 0.6082972565664995, 'colsample_bytree': 0.6548113897847111, 'reg_alpha': 4.848494810975082, 'reg_lambda': 4.06857726879731}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  78%|████████████████████████████████████████████████████████████████████████████████████▍                        | 775/1000 [59:52<26:50,  7.16s/it]

[I 2026-05-19 14:54:44,650] Trial 774 finished with value: 0.9498712038939872 and parameters: {'n_estimators': 288, 'learning_rate': 0.04383710453652911, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 162, 'subsample': 0.6121800749287839, 'colsample_bytree': 0.6479782344131556, 'reg_alpha': 3.3179400406938093, 'reg_lambda': 3.4700799118018972}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  78%|████████████████████████████████████████████████████████████████████████████████████▌                        | 776/1000 [59:57<23:45,  6.36s/it]

[I 2026-05-19 14:54:49,160] Trial 775 finished with value: 0.9498613432798265 and parameters: {'n_estimators': 280, 'learning_rate': 0.044274405530094284, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 218, 'subsample': 0.6120240216644711, 'colsample_bytree': 0.6515543424696943, 'reg_alpha': 0.6900470899416858, 'reg_lambda': 3.9722482456501806}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  78%|████████████████████████████████████████████████████████████████████████████████████▋                        | 777/1000 [59:57<16:48,  4.52s/it]

[I 2026-05-19 14:54:49,378] Trial 776 finished with value: 0.949866322727203 and parameters: {'n_estimators': 279, 'learning_rate': 0.04989067875404121, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 103, 'subsample': 0.6105064458901217, 'colsample_bytree': 0.6495898852428087, 'reg_alpha': 3.245388473179123, 'reg_lambda': 3.353857993637908}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  78%|███████████████████████████████████████████████████████████████████████████████████▏                       | 778/1000 [1:00:01<15:41,  4.24s/it]

[I 2026-05-19 14:54:52,966] Trial 777 finished with value: 0.9498735146291946 and parameters: {'n_estimators': 288, 'learning_rate': 0.0429529412803559, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 93, 'subsample': 0.6122958474526915, 'colsample_bytree': 0.6451011666469734, 'reg_alpha': 3.2878605485025054, 'reg_lambda': 3.5016630113795917}. Best is trial 603 with value: 0.9498815886860695.

[I 2026-05-19 14:55:04,316] Trial 778 finished with value: 0.9498736745504959 and parameters: {'n_estimators': 287, 'learning_rate': 0.043851531065711914, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 93, 'subsample': 0.6073406986539213, 'colsample_bytree': 0.6453540392764521, 'reg_alpha': 4.9292134834363575, 'reg_lambda': 3.088940798055905}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  78%|███████████████████████████████████████████████████████████████████████████████████▍                       | 780/1000 [1:00:12<16:35,  4.52s/it]

[I 2026-05-19 14:55:04,501] Trial 780 finished with value: 0.9498604977029192 and parameters: {'n_estimators': 241, 'learning_rate': 0.04367636481040465, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 93, 'subsample': 0.6081078954436602, 'colsample_bytree': 0.8159180639740993, 'reg_alpha': 3.2893195299527553, 'reg_lambda': 4.228029947544845}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  78%|███████████████████████████████████████████████████████████████████████████████████▌                       | 781/1000 [1:00:15<15:15,  4.18s/it]

[I 2026-05-19 14:55:07,907] Trial 779 finished with value: 0.9498729074462187 and parameters: {'n_estimators': 286, 'learning_rate': 0.043932115145464565, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 217, 'subsample': 0.9225236185680562, 'colsample_bytree': 0.6454572934452117, 'reg_alpha': 3.635161458841929, 'reg_lambda': 3.252498045618095}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  78%|███████████████████████████████████████████████████████████████████████████████████▋                       | 782/1000 [1:00:19<14:15,  3.92s/it]

[I 2026-05-19 14:55:11,235] Trial 781 finished with value: 0.9498678027745502 and parameters: {'n_estimators': 288, 'learning_rate': 0.04366258658883948, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 93, 'subsample': 0.6098638438617254, 'colsample_bytree': 0.6238391644696132, 'reg_alpha': 3.2988125965564152, 'reg_lambda': 4.738813071731591}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  78%|███████████████████████████████████████████████████████████████████████████████████▊                       | 783/1000 [1:00:23<14:14,  3.94s/it]

[I 2026-05-19 14:55:15,208] Trial 783 finished with value: 0.9498713123399417 and parameters: {'n_estimators': 287, 'learning_rate': 0.043552468440660214, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 216, 'subsample': 0.9224924291769582, 'colsample_bytree': 0.6228965726671346, 'reg_alpha': 0.7159897959937648, 'reg_lambda': 4.625524671757991}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  78%|███████████████████████████████████████████████████████████████████████████████████▉                       | 784/1000 [1:00:28<16:07,  4.48s/it]

[I 2026-05-19 14:55:20,928] Trial 784 finished with value: 0.9498677295824584 and parameters: {'n_estimators': 287, 'learning_rate': 0.0438431546103045, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 217, 'subsample': 0.6612433817735455, 'colsample_bytree': 0.6452167791519404, 'reg_alpha': 3.0575704271835966, 'reg_lambda': 0.0003555103774984253}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  78%|███████████████████████████████████████████████████████████████████████████████████▉                       | 785/1000 [1:00:32<14:43,  4.11s/it]

[I 2026-05-19 14:55:24,179] Trial 782 finished with value: 0.949861298932517 and parameters: {'n_estimators': 287, 'learning_rate': 0.04324215462572197, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 96, 'subsample': 0.6606848408815401, 'colsample_bytree': 0.9007605589438918, 'reg_alpha': 3.116254804497915, 'reg_lambda': 5.027179609027446}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  79%|████████████████████████████████████████████████████████████████████████████████████                       | 786/1000 [1:00:40<19:02,  5.34s/it]

[I 2026-05-19 14:55:32,385] Trial 793 finished with value: 0.9497712670692098 and parameters: {'n_estimators': 75, 'learning_rate': 0.040664225477889455, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 69, 'subsample': 0.6474926310481361, 'colsample_bytree': 0.6222019031692967, 'reg_alpha': 1.3441208829798423, 'reg_lambda': 5.286935385245727}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  79%|████████████████████████████████████████████████████████████████████████████████████▏                      | 787/1000 [1:00:46<19:26,  5.48s/it]

[I 2026-05-19 14:55:38,184] Trial 785 finished with value: 0.9498746471421649 and parameters: {'n_estimators': 288, 'learning_rate': 0.04286987229518705, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 92, 'subsample': 0.921253410500803, 'colsample_bytree': 0.6003179425402644, 'reg_alpha': 3.2826745745658306, 'reg_lambda': 4.718741988367959}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  79%|████████████████████████████████████████████████████████████████████████████████████▎                      | 788/1000 [1:00:54<22:25,  6.34s/it]

[I 2026-05-19 14:55:46,574] Trial 786 finished with value: 0.9498744565609613 and parameters: {'n_estimators': 291, 'learning_rate': 0.04992428390458929, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 92, 'subsample': 0.6462105807812571, 'colsample_bytree': 0.6283683860696742, 'reg_alpha': 3.132237027621945, 'reg_lambda': 4.126233842637658}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  79%|████████████████████████████████████████████████████████████████████████████████████▍                      | 789/1000 [1:00:58<19:45,  5.62s/it]

[I 2026-05-19 14:55:50,503] Trial 788 finished with value: 0.9498682208229248 and parameters: {'n_estimators': 287, 'learning_rate': 0.04326888763901703, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 92, 'subsample': 0.6500299768735043, 'colsample_bytree': 0.6238524200850709, 'reg_alpha': 1.3622737545743397, 'reg_lambda': 4.986783720836679}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  79%|████████████████████████████████████████████████████████████████████████████████████▌                      | 790/1000 [1:00:59<15:09,  4.33s/it]

[I 2026-05-19 14:55:51,815] Trial 787 finished with value: 0.9498677707146854 and parameters: {'n_estimators': 288, 'learning_rate': 0.0399590009693472, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 94, 'subsample': 0.657658317826773, 'colsample_bytree': 0.6248072442798652, 'reg_alpha': 3.307658975708218, 'reg_lambda': 0.00035026380461055686}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  79%|████████████████████████████████████████████████████████████████████████████████████▋                      | 791/1000 [1:01:04<15:01,  4.31s/it]

[I 2026-05-19 14:55:56,081] Trial 789 finished with value: 0.9498659565259416 and parameters: {'n_estimators': 286, 'learning_rate': 0.03979085321943403, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 91, 'subsample': 0.7939823551373315, 'colsample_bytree': 0.814134209808893, 'reg_alpha': 3.2074064143022225, 'reg_lambda': 5.248488262963837}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  79%|████████████████████████████████████████████████████████████████████████████████████▋                      | 792/1000 [1:01:09<15:45,  4.55s/it]

[I 2026-05-19 14:56:01,170] Trial 792 finished with value: 0.9498235955784835 and parameters: {'n_estimators': 266, 'learning_rate': 0.040270373153600936, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 69, 'subsample': 0.9410703145725349, 'colsample_bytree': 0.6224790503059646, 'reg_alpha': 71.59882033362057, 'reg_lambda': 5.430475095214201}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  79%|████████████████████████████████████████████████████████████████████████████████████▊                      | 793/1000 [1:01:13<15:00,  4.35s/it]

[I 2026-05-19 14:56:05,070] Trial 790 finished with value: 0.9498641988496832 and parameters: {'n_estimators': 287, 'learning_rate': 0.03978588916364869, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 69, 'subsample': 0.6478745331046659, 'colsample_bytree': 0.6232264042498874, 'reg_alpha': 3.3138059855833015, 'reg_lambda': 4.887310117462274}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  79%|████████████████████████████████████████████████████████████████████████████████████▉                      | 794/1000 [1:01:13<11:06,  3.24s/it]

[I 2026-05-19 14:56:05,683] Trial 791 finished with value: 0.9498632650316324 and parameters: {'n_estimators': 286, 'learning_rate': 0.04053622134897005, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 70, 'subsample': 0.6489722192532784, 'colsample_bytree': 0.6257534075104234, 'reg_alpha': 1.3595046387679306, 'reg_lambda': 5.027017950346537}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  80%|█████████████████████████████████████████████████████████████████████████████████████                      | 795/1000 [1:01:21<15:18,  4.48s/it]

[I 2026-05-19 14:56:13,085] Trial 794 finished with value: 0.9498656393631375 and parameters: {'n_estimators': 269, 'learning_rate': 0.040210928920707996, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 69, 'subsample': 0.8400307240804203, 'colsample_bytree': 0.6228912375881513, 'reg_alpha': 1.2395591960278602, 'reg_lambda': 4.868123320370517}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  80%|█████████████████████████████████████████████████████████████████████████████████████▏                     | 796/1000 [1:01:27<17:07,  5.04s/it]

[I 2026-05-19 14:56:19,433] Trial 795 finished with value: 0.9498664444857321 and parameters: {'n_estimators': 266, 'learning_rate': 0.04075476991204969, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 68, 'subsample': 0.6474066829455439, 'colsample_bytree': 0.6246058831305108, 'reg_alpha': 1.3815090387154345, 'reg_lambda': 5.501951317829958}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  80%|█████████████████████████████████████████████████████████████████████████████████████▎                     | 797/1000 [1:01:36<20:49,  6.15s/it]

[I 2026-05-19 14:56:28,200] Trial 796 finished with value: 0.9497334461961948 and parameters: {'n_estimators': 280, 'learning_rate': 0.007945159196054302, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 68, 'subsample': 0.6460493188373132, 'colsample_bytree': 0.6002412627349667, 'reg_alpha': 5.09085443714657, 'reg_lambda': 5.176586484856696}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  80%|█████████████████████████████████████████████████████████████████████████████████████▍                     | 798/1000 [1:01:39<17:29,  5.19s/it]

[I 2026-05-19 14:56:31,139] Trial 797 finished with value: 0.9498658830049562 and parameters: {'n_estimators': 266, 'learning_rate': 0.040105937258003765, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 68, 'subsample': 0.9410555466842359, 'colsample_bytree': 0.6272083049457526, 'reg_alpha': 5.163570444922057, 'reg_lambda': 2.207794050814146}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  80%|█████████████████████████████████████████████████████████████████████████████████████▍                     | 799/1000 [1:01:52<25:58,  7.75s/it]

[I 2026-05-19 14:56:44,879] Trial 798 finished with value: 0.9498596777577637 and parameters: {'n_estimators': 295, 'learning_rate': 0.04003431100898138, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 98, 'subsample': 0.9025407435270671, 'colsample_bytree': 0.600008538243007, 'reg_alpha': 1.40226326579837, 'reg_lambda': 5.306519598395185}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  80%|█████████████████████████████████████████████████████████████████████████████████████▋                     | 801/1000 [1:02:00<17:58,  5.42s/it]

[I 2026-05-19 14:56:52,358] Trial 799 finished with value: 0.9498650083885611 and parameters: {'n_estimators': 295, 'learning_rate': 0.04015317201799694, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 98, 'subsample': 0.8634881946187675, 'colsample_bytree': 0.6036620478169715, 'reg_alpha': 1.941498730446019, 'reg_lambda': 2.222244979584479}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:56:52,502] Trial 800 finished with value: 0.9498617391799309 and parameters: {'n_estimators': 293, 'learning_rate': 0.039749425579454184, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 98, 'subsample': 0.9014187095534469, 'colsample_bytree': 0.602709976401536, 'reg_alpha': 1.7283257843908242, 'reg_lambda': 2.2419527804185084}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  80%|█████████████████████████████████████████████████████████████████████████████████████▊                     | 802/1000 [1:02:02<14:46,  4.48s/it]

[I 2026-05-19 14:56:54,785] Trial 801 finished with value: 0.9498654240245724 and parameters: {'n_estimators': 295, 'learning_rate': 0.03972634623965474, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 99, 'subsample': 0.9450870350956309, 'colsample_bytree': 0.6032135546945401, 'reg_alpha': 2.2127453248178366, 'reg_lambda': 2.397585702157717}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  80%|█████████████████████████████████████████████████████████████████████████████████████▉                     | 803/1000 [1:02:04<12:14,  3.73s/it]

[I 2026-05-19 14:56:56,785] Trial 802 finished with value: 0.9498628516682037 and parameters: {'n_estimators': 293, 'learning_rate': 0.04010866731368727, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 243, 'subsample': 0.6658748308814044, 'colsample_bytree': 0.6005489716804588, 'reg_alpha': 2.2619496314253396, 'reg_lambda': 2.632641437126585}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  80%|██████████████████████████████████████████████████████████████████████████████████████                     | 804/1000 [1:02:10<13:36,  4.17s/it]

[I 2026-05-19 14:57:01,969] Trial 803 finished with value: 0.949867254411766 and parameters: {'n_estimators': 294, 'learning_rate': 0.03988861491486196, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 86, 'subsample': 0.9497820293078377, 'colsample_bytree': 0.6007086805370198, 'reg_alpha': 1.947676284276377, 'reg_lambda': 2.206451099430986}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  80%|██████████████████████████████████████████████████████████████████████████████████████▏                    | 805/1000 [1:02:14<13:47,  4.24s/it]

[I 2026-05-19 14:57:06,381] Trial 805 finished with value: 0.9498689121530086 and parameters: {'n_estimators': 294, 'learning_rate': 0.04092307700283162, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 101, 'subsample': 0.89217393877783, 'colsample_bytree': 0.6017738219246875, 'reg_alpha': 1.8334306039894743, 'reg_lambda': 2.2397329613348758}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  81%|██████████████████████████████████████████████████████████████████████████████████████▏                    | 806/1000 [1:02:16<11:13,  3.47s/it]

[I 2026-05-19 14:57:08,056] Trial 804 finished with value: 0.949864701896964 and parameters: {'n_estimators': 294, 'learning_rate': 0.033954913280494395, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 100, 'subsample': 0.9284096178406073, 'colsample_bytree': 0.6007083294256501, 'reg_alpha': 1.9170363999377915, 'reg_lambda': 2.1744053135431343}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  81%|██████████████████████████████████████████████████████████████████████████████████████▎                    | 807/1000 [1:02:34<26:01,  8.09s/it]

[I 2026-05-19 14:57:26,917] Trial 806 finished with value: 0.9497478733181193 and parameters: {'n_estimators': 295, 'learning_rate': 0.006243348081948005, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 241, 'subsample': 0.9144724603305322, 'colsample_bytree': 0.6082407542957813, 'reg_alpha': 1.8729636845253284, 'reg_lambda': 2.1677967589324805}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  81%|██████████████████████████████████████████████████████████████████████████████████████▍                    | 808/1000 [1:02:37<20:22,  6.37s/it]

[I 2026-05-19 14:57:29,264] Trial 808 finished with value: 0.9498713977268455 and parameters: {'n_estimators': 292, 'learning_rate': 0.04187834668779821, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 100, 'subsample': 0.8918175537612958, 'colsample_bytree': 0.6034232034753124, 'reg_alpha': 2.255009482169735, 'reg_lambda': 2.1260251959140013}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  81%|██████████████████████████████████████████████████████████████████████████████████████▌                    | 809/1000 [1:02:38<15:19,  4.81s/it]

[I 2026-05-19 14:57:30,453] Trial 813 finished with value: 0.9498167752188952 and parameters: {'n_estimators': 280, 'learning_rate': 0.04548648502659685, 'max_depth': 4, 'num_leaves': 3, 'min_child_samples': 86, 'subsample': 0.9270332081579529, 'colsample_bytree': 0.6089074434955042, 'reg_alpha': 2.4437904144514704, 'reg_lambda': 8.70720995904107}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  81%|██████████████████████████████████████████████████████████████████████████████████████▋                    | 810/1000 [1:02:39<11:57,  3.78s/it]

[I 2026-05-19 14:57:31,806] Trial 807 finished with value: 0.9497556857177367 and parameters: {'n_estimators': 294, 'learning_rate': 0.00758907719522097, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 100, 'subsample': 0.8929101390213159, 'colsample_bytree': 0.604051330029191, 'reg_alpha': 1.9887934134697924, 'reg_lambda': 1.9807852391603213}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  81%|██████████████████████████████████████████████████████████████████████████████████████▊                    | 811/1000 [1:02:43<11:23,  3.62s/it]

[I 2026-05-19 14:57:35,058] Trial 809 finished with value: 0.9498758399639362 and parameters: {'n_estimators': 295, 'learning_rate': 0.045949400815816575, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 99, 'subsample': 0.8882561310420836, 'colsample_bytree': 0.600728858326141, 'reg_alpha': 2.0189366280677365, 'reg_lambda': 8.578380643486271}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  81%|██████████████████████████████████████████████████████████████████████████████████████▉                    | 812/1000 [1:02:54<19:03,  6.08s/it]

[I 2026-05-19 14:57:46,893] Trial 810 finished with value: 0.9498602179743717 and parameters: {'n_estimators': 293, 'learning_rate': 0.03357034904490236, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 99, 'subsample': 0.8522111765164997, 'colsample_bytree': 0.6031849911330517, 'reg_alpha': 2.248156136940601, 'reg_lambda': 2.3786399233723934}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  81%|██████████████████████████████████████████████████████████████████████████████████████▉                    | 813/1000 [1:03:01<19:35,  6.29s/it]

[I 2026-05-19 14:57:53,631] Trial 812 finished with value: 0.9497040641961728 and parameters: {'n_estimators': 280, 'learning_rate': 0.006236881075035, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 88, 'subsample': 0.6189214354417698, 'colsample_bytree': 0.6045885568787343, 'reg_alpha': 2.1553665263086943, 'reg_lambda': 7.7655311358568575}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  82%|███████████████████████████████████████████████████████████████████████████████████████▏                   | 815/1000 [1:03:02<10:12,  3.31s/it]

[I 2026-05-19 14:57:54,569] Trial 814 finished with value: 0.9498710144256899 and parameters: {'n_estimators': 280, 'learning_rate': 0.049807971444152326, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 85, 'subsample': 0.6207883022708269, 'colsample_bytree': 0.6083928650900443, 'reg_alpha': 4.685208006672764, 'reg_lambda': 0.38357120118654814}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:57:54,701] Trial 811 finished with value: 0.9498744290536394 and parameters: {'n_estimators': 294, 'learning_rate': 0.04518208134370153, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 88, 'subsample': 0.6663222112161173, 'colsample_bytree': 0.6096840599534581, 'reg_alpha': 2.0823489637059427, 'reg_lambda': 13.315026832124229}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  82%|███████████████████████████████████████████████████████████████████████████████████████▎                   | 816/1000 [1:03:11<15:23,  5.02s/it]

[I 2026-05-19 14:58:03,688] Trial 815 finished with value: 0.9498718368563261 and parameters: {'n_estimators': 280, 'learning_rate': 0.049961276398717336, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 116, 'subsample': 0.6204722930212128, 'colsample_bytree': 0.6132866510697804, 'reg_alpha': 4.670890840499292, 'reg_lambda': 0.0005798347114298132}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  82%|███████████████████████████████████████████████████████████████████████████████████████▍                   | 817/1000 [1:03:13<12:44,  4.18s/it]

[I 2026-05-19 14:58:05,903] Trial 816 finished with value: 0.9498640305150072 and parameters: {'n_estimators': 280, 'learning_rate': 0.033945068372699734, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 87, 'subsample': 0.8873698303401351, 'colsample_bytree': 0.61083629489381, 'reg_alpha': 5.060074116899672, 'reg_lambda': 7.981002537575005}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  82%|███████████████████████████████████████████████████████████████████████████████████████▌                   | 818/1000 [1:03:14<09:14,  3.04s/it]

[I 2026-05-19 14:58:06,315] Trial 817 finished with value: 0.9498765411971535 and parameters: {'n_estimators': 280, 'learning_rate': 0.045029890330792764, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 89, 'subsample': 0.9362908304828402, 'colsample_bytree': 0.6128103889556404, 'reg_alpha': 4.575293990321011, 'reg_lambda': 8.65234419234996e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  82%|███████████████████████████████████████████████████████████████████████████████████████▋                   | 819/1000 [1:03:32<23:16,  7.72s/it]

[I 2026-05-19 14:58:24,935] Trial 818 finished with value: 0.9498703261997699 and parameters: {'n_estimators': 280, 'learning_rate': 0.045380936661233065, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 86, 'subsample': 0.9546308213031055, 'colsample_bytree': 0.6104226781724716, 'reg_alpha': 4.7298049055621565, 'reg_lambda': 8.43300131537011}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  82%|███████████████████████████████████████████████████████████████████████████████████████▋                   | 820/1000 [1:03:33<16:30,  5.50s/it]

[I 2026-05-19 14:58:25,241] Trial 819 finished with value: 0.9498661164112031 and parameters: {'n_estimators': 281, 'learning_rate': 0.049964259620998215, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 91, 'subsample': 0.9374851813837047, 'colsample_bytree': 0.6099793309145397, 'reg_alpha': 4.517199406623638, 'reg_lambda': 63.16802971467573}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  82%|███████████████████████████████████████████████████████████████████████████████████████▊                   | 821/1000 [1:03:37<15:19,  5.14s/it]

[I 2026-05-19 14:58:29,531] Trial 821 finished with value: 0.9498608162533542 and parameters: {'n_estimators': 281, 'learning_rate': 0.049878128007538006, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 89, 'subsample': 0.8557223743663028, 'colsample_bytree': 0.6118653366753992, 'reg_alpha': 0.005287597600750288, 'reg_lambda': 8.044764997271468}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  82%|███████████████████████████████████████████████████████████████████████████████████████▉                   | 822/1000 [1:03:38<11:49,  3.99s/it]

[I 2026-05-19 14:58:30,847] Trial 820 finished with value: 0.9498672793709568 and parameters: {'n_estimators': 280, 'learning_rate': 0.04974539851440073, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 84, 'subsample': 0.9069828877057187, 'colsample_bytree': 0.6097178969947447, 'reg_alpha': 4.598694182657968, 'reg_lambda': 13.197794227025458}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  82%|████████████████████████████████████████████████████████████████████████████████████████                   | 823/1000 [1:03:45<13:46,  4.67s/it]

[I 2026-05-19 14:58:37,124] Trial 822 finished with value: 0.9498688117549354 and parameters: {'n_estimators': 299, 'learning_rate': 0.049570069939435954, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 114, 'subsample': 0.9345227034895085, 'colsample_bytree': 0.6097703649300987, 'reg_alpha': 4.602791800030621, 'reg_lambda': 8.847773296364727}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  82%|████████████████████████████████████████████████████████████████████████████████████████▏                  | 824/1000 [1:03:57<20:20,  6.94s/it]

[I 2026-05-19 14:58:49,325] Trial 823 finished with value: 0.9498674631617703 and parameters: {'n_estimators': 297, 'learning_rate': 0.046594457410993655, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 114, 'subsample': 0.620754988215775, 'colsample_bytree': 0.6126950089283842, 'reg_alpha': 0.9104730863316991, 'reg_lambda': 11.208283882823853}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  82%|████████████████████████████████████████████████████████████████████████████████████████▎                  | 825/1000 [1:04:02<18:12,  6.25s/it]

[I 2026-05-19 14:58:53,962] Trial 824 finished with value: 0.9498728807134886 and parameters: {'n_estimators': 300, 'learning_rate': 0.04721459762166379, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 107, 'subsample': 0.9572739352207507, 'colsample_bytree': 0.6141660890066896, 'reg_alpha': 4.6969324983715115, 'reg_lambda': 11.06881791556907}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:58:54,061] Trial 829 finished with value: 0.9498580041971602 and parameters: {'n_estimators': 299, 'learning_rate': 0.047397397388868126, 'max_depth': 4, 'num_leaves': 6, 'min_child_samples': 107, 'subsample': 0.9542050166340433, 'colsample_bytree': 0.6117875393901081, 'reg_alpha': 4.342065329594567, 'reg_lambda': 7.790128346328821e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  83%|████████████████████████████████████████████████████████████████████████████████████████▍                  | 827/1000 [1:04:02<10:18,  3.57s/it]

[I 2026-05-19 14:58:54,874] Trial 828 finished with value: 0.9498548111193174 and parameters: {'n_estimators': 298, 'learning_rate': 0.04723728316267453, 'max_depth': 4, 'num_leaves': 6, 'min_child_samples': 107, 'subsample': 0.9602447584829535, 'colsample_bytree': 0.6135175179201162, 'reg_alpha': 3.8233574388712803, 'reg_lambda': 15.191022049879438}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  83%|████████████████████████████████████████████████████████████████████████████████████████▌                  | 828/1000 [1:04:03<08:15,  2.88s/it]

[I 2026-05-19 14:58:55,669] Trial 825 finished with value: 0.949863567240954 and parameters: {'n_estimators': 300, 'learning_rate': 0.04713514729581883, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 107, 'subsample': 0.9165408928706001, 'colsample_bytree': 0.6114537298791849, 'reg_alpha': 4.310683831805461, 'reg_lambda': 13.590267400372179}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  83%|████████████████████████████████████████████████████████████████████████████████████████▋                  | 829/1000 [1:04:04<06:17,  2.21s/it]

[I 2026-05-19 14:58:55,964] Trial 826 finished with value: 0.9498634262750242 and parameters: {'n_estimators': 284, 'learning_rate': 0.04759285201891052, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 114, 'subsample': 0.9059290469692971, 'colsample_bytree': 0.607747284149039, 'reg_alpha': 4.2539092779959375, 'reg_lambda': 64.1192357537907}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  83%|████████████████████████████████████████████████████████████████████████████████████████▊                  | 830/1000 [1:04:15<13:16,  4.68s/it]

[I 2026-05-19 14:59:07,287] Trial 827 finished with value: 0.9498721532321446 and parameters: {'n_estimators': 299, 'learning_rate': 0.046297581506024324, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 108, 'subsample': 0.9559278662946404, 'colsample_bytree': 0.6122865906225623, 'reg_alpha': 4.218812711129311, 'reg_lambda': 8.487455928175198}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  83%|████████████████████████████████████████████████████████████████████████████████████████▉                  | 831/1000 [1:04:32<23:13,  8.24s/it]

[I 2026-05-19 14:59:24,706] Trial 831 finished with value: 0.9498662471488657 and parameters: {'n_estimators': 287, 'learning_rate': 0.04722910115811117, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 93, 'subsample': 0.9161460909126351, 'colsample_bytree': 0.6151295529981587, 'reg_alpha': 5.817328255153193, 'reg_lambda': 14.286967731953588}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  83%|█████████████████████████████████████████████████████████████████████████████████████████                  | 832/1000 [1:04:34<17:45,  6.34s/it]

[I 2026-05-19 14:59:26,250] Trial 830 finished with value: 0.9498713240043752 and parameters: {'n_estimators': 299, 'learning_rate': 0.04669949281520894, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 93, 'subsample': 0.6223642550544595, 'colsample_bytree': 0.612841088167406, 'reg_alpha': 5.895002232985717, 'reg_lambda': 7.5042217478347e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  83%|█████████████████████████████████████████████████████████████████████████████████████████▏                 | 833/1000 [1:04:39<16:47,  6.04s/it]

[I 2026-05-19 14:59:31,565] Trial 832 finished with value: 0.9498665379927627 and parameters: {'n_estimators': 298, 'learning_rate': 0.047152964324479726, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 256, 'subsample': 0.9098604855072393, 'colsample_bytree': 0.6138149182764748, 'reg_alpha': 6.04112045426011, 'reg_lambda': 11.559697618791903}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  83%|█████████████████████████████████████████████████████████████████████████████████████████▏                 | 834/1000 [1:04:42<14:18,  5.17s/it]

[I 2026-05-19 14:59:34,643] Trial 833 finished with value: 0.9498764006440975 and parameters: {'n_estimators': 299, 'learning_rate': 0.04653160723869816, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 114, 'subsample': 0.9614380308425545, 'colsample_bytree': 0.6167177467800495, 'reg_alpha': 3.7933377493761298, 'reg_lambda': 6.512716547938386e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  84%|█████████████████████████████████████████████████████████████████████████████████████████▎                 | 835/1000 [1:04:48<14:56,  5.44s/it]

[I 2026-05-19 14:59:40,712] Trial 834 finished with value: 0.9498691967189975 and parameters: {'n_estimators': 299, 'learning_rate': 0.04590031662044231, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 110, 'subsample': 0.9581447446244209, 'colsample_bytree': 0.6153806423463639, 'reg_alpha': 6.046209236764284, 'reg_lambda': 0.00010787953412017761}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  84%|█████████████████████████████████████████████████████████████████████████████████████████▍                 | 836/1000 [1:04:55<16:14,  5.94s/it]

[I 2026-05-19 14:59:47,836] Trial 835 finished with value: 0.9498657650448805 and parameters: {'n_estimators': 289, 'learning_rate': 0.04689748891680674, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 105, 'subsample': 0.9176073760145899, 'colsample_bytree': 0.6164352628421333, 'reg_alpha': 6.324829446955953, 'reg_lambda': 4.1850517178779214e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  84%|█████████████████████████████████████████████████████████████████████████████████████████▋                 | 838/1000 [1:05:02<11:36,  4.30s/it]

[I 2026-05-19 14:59:54,139] Trial 837 finished with value: 0.9498731008299671 and parameters: {'n_estimators': 289, 'learning_rate': 0.04520745844978649, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 105, 'subsample': 0.9127799025229534, 'colsample_bytree': 0.6181830987174167, 'reg_alpha': 5.79268203036047, 'reg_lambda': 6.566664117100768e-05}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 14:59:54,321] Trial 838 finished with value: 0.9498580389729188 and parameters: {'n_estimators': 287, 'learning_rate': 0.04495895178607587, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 93, 'subsample': 0.9181214610036375, 'colsample_bytree': 0.6193567163850267, 'reg_alpha': 0.0012184610559898316, 'reg_lambda': 8.168400500087932}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  84%|█████████████████████████████████████████████████████████████████████████████████████████▊                 | 839/1000 [1:05:02<08:10,  3.04s/it]

[I 2026-05-19 14:59:54,412] Trial 839 finished with value: 0.94987190568866 and parameters: {'n_estimators': 290, 'learning_rate': 0.044734094875034235, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 93, 'subsample': 0.910716044218273, 'colsample_bytree': 0.6175451627047752, 'reg_alpha': 2.7761217276632415, 'reg_lambda': 1.1158472070882053e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  84%|█████████████████████████████████████████████████████████████████████████████████████████▉                 | 840/1000 [1:05:02<05:58,  2.24s/it]

[I 2026-05-19 14:59:54,790] Trial 841 finished with value: 0.949854708023248 and parameters: {'n_estimators': 287, 'learning_rate': 0.045063663979880715, 'max_depth': 4, 'num_leaves': 7, 'min_child_samples': 95, 'subsample': 0.9472250662585489, 'colsample_bytree': 0.6164722991293645, 'reg_alpha': 6.666385265319854, 'reg_lambda': 5.845336974145583e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  84%|█████████████████████████████████████████████████████████████████████████████████████████▉                 | 841/1000 [1:05:04<05:06,  1.93s/it]

[I 2026-05-19 14:59:55,977] Trial 836 finished with value: 0.949869570837371 and parameters: {'n_estimators': 300, 'learning_rate': 0.045173356275336404, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 94, 'subsample': 0.9553390838261208, 'colsample_bytree': 0.6160721852262578, 'reg_alpha': 6.2580755030544735, 'reg_lambda': 7.211016609836404e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  84%|██████████████████████████████████████████████████████████████████████████████████████████                 | 842/1000 [1:05:04<04:09,  1.58s/it]

[I 2026-05-19 14:59:56,728] Trial 840 finished with value: 0.9498385117408195 and parameters: {'n_estimators': 291, 'learning_rate': 0.044978513565435196, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 93, 'subsample': 0.9427212674905899, 'colsample_bytree': 0.6161478765313151, 'reg_alpha': 0.0011082506170090355, 'reg_lambda': 1.7692624734452334e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  84%|██████████████████████████████████████████████████████████████████████████████████████████▏                | 843/1000 [1:05:36<27:36, 10.55s/it]

[I 2026-05-19 15:00:28,254] Trial 842 finished with value: 0.9498718255549532 and parameters: {'n_estimators': 290, 'learning_rate': 0.044526005806858955, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 82, 'subsample': 0.627355837719215, 'colsample_bytree': 0.6180821922197807, 'reg_alpha': 6.211496719292586, 'reg_lambda': 4.1245114805702755e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  84%|██████████████████████████████████████████████████████████████████████████████████████████▎                | 844/1000 [1:05:36<19:29,  7.50s/it]

[I 2026-05-19 15:00:28,629] Trial 843 finished with value: 0.949856652333291 and parameters: {'n_estimators': 289, 'learning_rate': 0.04404466678213068, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 82, 'subsample': 0.9318663414593602, 'colsample_bytree': 0.7907234459214139, 'reg_alpha': 2.998577046900757, 'reg_lambda': 24.873896294024732}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  84%|██████████████████████████████████████████████████████████████████████████████████████████▍                | 845/1000 [1:05:41<16:59,  6.57s/it]

[I 2026-05-19 15:00:33,015] Trial 844 finished with value: 0.9498744012781486 and parameters: {'n_estimators': 290, 'learning_rate': 0.0444072182672124, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 96, 'subsample': 0.9490868128981272, 'colsample_bytree': 0.6191791182554643, 'reg_alpha': 3.0686098079194677, 'reg_lambda': 1.4934878232376364e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  85%|██████████████████████████████████████████████████████████████████████████████████████████▌                | 846/1000 [1:05:48<17:51,  6.96s/it]

[I 2026-05-19 15:00:40,901] Trial 845 finished with value: 0.9498220786667148 and parameters: {'n_estimators': 289, 'learning_rate': 0.01718971335206177, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 127, 'subsample': 0.9630930283691731, 'colsample_bytree': 0.6199095323412915, 'reg_alpha': 2.754462634663839, 'reg_lambda': 0.00012210462689378335}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  85%|██████████████████████████████████████████████████████████████████████████████████████████▋                | 847/1000 [1:05:50<13:20,  5.23s/it]

[I 2026-05-19 15:00:42,098] Trial 846 finished with value: 0.9498692503898452 and parameters: {'n_estimators': 288, 'learning_rate': 0.0445905764824346, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 122, 'subsample': 0.9810245315163387, 'colsample_bytree': 0.6192944506579621, 'reg_alpha': 2.8464337284762116, 'reg_lambda': 2.0994344169114844e-05}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 15:00:42,147] Trial 853 finished with value: 0.9498521282594542 and parameters: {'n_estimators': 187, 'learning_rate': 0.042938042127213964, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 82, 'subsample': 0.9727848958984507, 'colsample_bytree': 0.6328266536015668, 'reg_alpha': 3.0016541224662796, 'reg_lambda': 0.0002089071178906541}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  85%|██████████████████████████████████████████████████████████████████████████████████████████▊                | 849/1000 [1:05:56<10:42,  4.26s/it]

[I 2026-05-19 15:00:48,354] Trial 847 finished with value: 0.9498743103245524 and parameters: {'n_estimators': 292, 'learning_rate': 0.04495320571277892, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 112, 'subsample': 0.9683822314636874, 'colsample_bytree': 0.6204424994407944, 'reg_alpha': 2.8830026768074615, 'reg_lambda': 0.00010807220088246483}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  85%|██████████████████████████████████████████████████████████████████████████████████████████▉                | 850/1000 [1:06:01<11:12,  4.49s/it]

[I 2026-05-19 15:00:53,530] Trial 849 finished with value: 0.9498683448937092 and parameters: {'n_estimators': 292, 'learning_rate': 0.04400192504860571, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 122, 'subsample': 0.9664231527918055, 'colsample_bytree': 0.6201859746539325, 'reg_alpha': 2.945523332015825, 'reg_lambda': 7.5829625404664e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  85%|███████████████████████████████████████████████████████████████████████████████████████████                | 851/1000 [1:06:02<08:53,  3.58s/it]

[I 2026-05-19 15:00:54,525] Trial 852 finished with value: 0.9498714564093925 and parameters: {'n_estimators': 292, 'learning_rate': 0.04307818380305896, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 119, 'subsample': 0.963101468703967, 'colsample_bytree': 0.6328701720432045, 'reg_alpha': 2.7855305794858616, 'reg_lambda': 3.746563486841138e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  85%|███████████████████████████████████████████████████████████████████████████████████████████▏               | 852/1000 [1:06:02<06:39,  2.70s/it]

[I 2026-05-19 15:00:54,873] Trial 851 finished with value: 0.949863448064308 and parameters: {'n_estimators': 291, 'learning_rate': 0.04325646219989959, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 115, 'subsample': 0.9733213092774943, 'colsample_bytree': 0.6333848055810707, 'reg_alpha': 2.761493566934426, 'reg_lambda': 4.093013284404581e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  85%|███████████████████████████████████████████████████████████████████████████████████████████▎               | 853/1000 [1:06:04<05:30,  2.25s/it]

[I 2026-05-19 15:00:55,975] Trial 848 finished with value: 0.9498715478306329 and parameters: {'n_estimators': 291, 'learning_rate': 0.04378905052330217, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 127, 'subsample': 0.9873775052479496, 'colsample_bytree': 0.620727531125617, 'reg_alpha': 2.8640360718637052, 'reg_lambda': 7.091701759310926e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  85%|███████████████████████████████████████████████████████████████████████████████████████████▍               | 854/1000 [1:06:06<05:24,  2.22s/it]

[I 2026-05-19 15:00:58,137] Trial 850 finished with value: 0.9498711483377766 and parameters: {'n_estimators': 291, 'learning_rate': 0.04301352056443402, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 116, 'subsample': 0.9875352856253176, 'colsample_bytree': 0.633405612229219, 'reg_alpha': 2.83654538007444, 'reg_lambda': 6.209800136568468}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  86%|███████████████████████████████████████████████████████████████████████████████████████████▍               | 855/1000 [1:06:30<20:29,  8.48s/it]

[I 2026-05-19 15:01:21,967] Trial 864 finished with value: 0.949799858949261 and parameters: {'n_estimators': 107, 'learning_rate': 0.042279951253447474, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 102, 'subsample': 0.970289682297798, 'colsample_bytree': 0.6358632558235863, 'reg_alpha': 9.592089821259274, 'reg_lambda': 2.5319004166547725e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  86%|███████████████████████████████████████████████████████████████████████████████████████████▌               | 856/1000 [1:06:35<17:56,  7.47s/it]

[I 2026-05-19 15:01:26,991] Trial 854 finished with value: 0.9498631270846032 and parameters: {'n_estimators': 269, 'learning_rate': 0.04265551403694208, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 126, 'subsample': 0.9617771320535495, 'colsample_bytree': 0.633048159753095, 'reg_alpha': 2.85562031389561, 'reg_lambda': 2.32033671858049e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  86%|███████████████████████████████████████████████████████████████████████████████████████████▋               | 857/1000 [1:06:37<14:05,  5.91s/it]

[I 2026-05-19 15:01:29,167] Trial 855 finished with value: 0.9498515580972828 and parameters: {'n_estimators': 270, 'learning_rate': 0.0268046103120043, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 115, 'subsample': 0.9668089322012184, 'colsample_bytree': 0.6313151460276468, 'reg_alpha': 2.8185191325219168, 'reg_lambda': 9.943670304426744e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  86%|███████████████████████████████████████████████████████████████████████████████████████████▊               | 858/1000 [1:06:39<11:14,  4.75s/it]

[I 2026-05-19 15:01:31,169] Trial 856 finished with value: 0.9498633517921228 and parameters: {'n_estimators': 271, 'learning_rate': 0.04299692941168538, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 112, 'subsample': 0.9703372870615418, 'colsample_bytree': 0.6327278843262292, 'reg_alpha': 3.4549446680879137, 'reg_lambda': 0.00010583473982373601}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  86%|███████████████████████████████████████████████████████████████████████████████████████████▉               | 859/1000 [1:06:42<09:59,  4.25s/it]

[I 2026-05-19 15:01:34,249] Trial 857 finished with value: 0.9498637215174265 and parameters: {'n_estimators': 270, 'learning_rate': 0.04238207472738643, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 123, 'subsample': 0.8714921673033013, 'colsample_bytree': 0.632360745284196, 'reg_alpha': 9.80227656961618, 'reg_lambda': 0.00018190745208632408}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  86%|████████████████████████████████████████████████████████████████████████████████████████████               | 860/1000 [1:06:46<10:08,  4.34s/it]

[I 2026-05-19 15:01:38,819] Trial 858 finished with value: 0.9498705321438876 and parameters: {'n_estimators': 269, 'learning_rate': 0.04222818529333282, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 121, 'subsample': 0.9667250365800256, 'colsample_bytree': 0.6342232973815448, 'reg_alpha': 3.505401837199313, 'reg_lambda': 0.00013057831155621617}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  86%|████████████████████████████████████████████████████████████████████████████████████████████▏              | 861/1000 [1:06:50<09:39,  4.17s/it]

[I 2026-05-19 15:01:42,544] Trial 859 finished with value: 0.9498472475154209 and parameters: {'n_estimators': 270, 'learning_rate': 0.0433918350818374, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 104, 'subsample': 0.9814142625805928, 'colsample_bytree': 0.6329770333484436, 'reg_alpha': 0.034277359598758446, 'reg_lambda': 8.021744585710404e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  86%|████████████████████████████████████████████████████████████████████████████████████████████▏              | 862/1000 [1:07:00<13:48,  6.00s/it]

[I 2026-05-19 15:01:52,849] Trial 861 finished with value: 0.9498548606760016 and parameters: {'n_estimators': 271, 'learning_rate': 0.027120739636002724, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 112, 'subsample': 0.9733668770815457, 'colsample_bytree': 0.6340318895051751, 'reg_alpha': 3.8208372774495025, 'reg_lambda': 2.344730678886709e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  86%|████████████████████████████████████████████████████████████████████████████████████████████▎              | 863/1000 [1:07:01<09:50,  4.31s/it]

[I 2026-05-19 15:01:53,219] Trial 860 finished with value: 0.9498535998497107 and parameters: {'n_estimators': 268, 'learning_rate': 0.042462437619495016, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 124, 'subsample': 0.9690659226220085, 'colsample_bytree': 0.8859828186318909, 'reg_alpha': 9.499981884545246, 'reg_lambda': 4.4043749331751784e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  86%|████████████████████████████████████████████████████████████████████████████████████████████▍              | 864/1000 [1:07:02<07:51,  3.47s/it]

[I 2026-05-19 15:01:54,716] Trial 863 finished with value: 0.9498686509134042 and parameters: {'n_estimators': 271, 'learning_rate': 0.042097845210453524, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 104, 'subsample': 0.9862165518924388, 'colsample_bytree': 0.636623462256613, 'reg_alpha': 8.683978692769768, 'reg_lambda': 2.50680090724838e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  86%|████████████████████████████████████████████████████████████████████████████████████████████▌              | 865/1000 [1:07:03<05:43,  2.55s/it]

[I 2026-05-19 15:01:55,107] Trial 865 finished with value: 0.9498728720775734 and parameters: {'n_estimators': 270, 'learning_rate': 0.04826252291880635, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 105, 'subsample': 0.9691603049414856, 'colsample_bytree': 0.6373683499617724, 'reg_alpha': 8.825932994716062, 'reg_lambda': 6.122148112323208}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  87%|████████████████████████████████████████████████████████████████████████████████████████████▋              | 866/1000 [1:07:04<04:47,  2.15s/it]

[I 2026-05-19 15:01:56,315] Trial 862 finished with value: 0.9498683082609298 and parameters: {'n_estimators': 270, 'learning_rate': 0.041831958842848634, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 114, 'subsample': 0.9824480446483372, 'colsample_bytree': 0.6365099529452448, 'reg_alpha': 3.9660793124739424, 'reg_lambda': 9.592760494326657e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  87%|████████████████████████████████████████████████████████████████████████████████████████████▊              | 867/1000 [1:07:12<09:00,  4.06s/it]

[I 2026-05-19 15:02:04,845] Trial 869 finished with value: 0.9498306404625534 and parameters: {'n_estimators': 262, 'learning_rate': 0.0479345550781618, 'max_depth': 2, 'num_leaves': 16, 'min_child_samples': 103, 'subsample': 0.9789709385583731, 'colsample_bytree': 0.627939220493498, 'reg_alpha': 9.134915067521906, 'reg_lambda': 6.3126217267112725}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  87%|████████████████████████████████████████████████████████████████████████████████████████████▉              | 868/1000 [1:07:19<10:23,  4.73s/it]

[I 2026-05-19 15:02:11,123] Trial 870 finished with value: 0.9498328990619045 and parameters: {'n_estimators': 263, 'learning_rate': 0.04789096041936496, 'max_depth': 2, 'num_leaves': 16, 'min_child_samples': 103, 'subsample': 0.6305497813146258, 'colsample_bytree': 0.6384887094419796, 'reg_alpha': 4.035653966622881, 'reg_lambda': 0.00026200453912729455}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  87%|████████████████████████████████████████████████████████████████████████████████████████████▉              | 869/1000 [1:07:28<13:14,  6.07s/it]

[I 2026-05-19 15:02:20,322] Trial 868 finished with value: 0.9498627522080885 and parameters: {'n_estimators': 262, 'learning_rate': 0.04805642135829585, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 104, 'subsample': 0.9816779428334602, 'colsample_bytree': 0.6257846115205826, 'reg_alpha': 8.898406251493805, 'reg_lambda': 4.3667440116295236e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  87%|█████████████████████████████████████████████████████████████████████████████████████████████              | 870/1000 [1:07:31<11:11,  5.16s/it]

[I 2026-05-19 15:02:23,385] Trial 866 finished with value: 0.9498580836549106 and parameters: {'n_estimators': 267, 'learning_rate': 0.049730732411296136, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 78, 'subsample': 0.6001387890474009, 'colsample_bytree': 0.8801739454524908, 'reg_alpha': 8.893028961934467, 'reg_lambda': 4.653243570650409e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▏             | 871/1000 [1:07:34<09:54,  4.61s/it]

[I 2026-05-19 15:02:26,698] Trial 867 finished with value: 0.9498714127050242 and parameters: {'n_estimators': 270, 'learning_rate': 0.04790836953050591, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 111, 'subsample': 0.6291020233362951, 'colsample_bytree': 0.6293248277615989, 'reg_alpha': 3.95363212196902, 'reg_lambda': 0.0002215636228090389}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▎             | 872/1000 [1:07:37<08:27,  3.96s/it]

[I 2026-05-19 15:02:29,143] Trial 875 finished with value: 0.9498337551984314 and parameters: {'n_estimators': 261, 'learning_rate': 0.04970815220722463, 'max_depth': 2, 'num_leaves': 10, 'min_child_samples': 78, 'subsample': 0.6005830609515431, 'colsample_bytree': 0.6255442857185067, 'reg_alpha': 0.06838355050312343, 'reg_lambda': 0.00027624845808090084}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▍             | 873/1000 [1:07:38<06:40,  3.16s/it]

[I 2026-05-19 15:02:30,409] Trial 876 finished with value: 0.949848427175778 and parameters: {'n_estimators': 144, 'learning_rate': 0.04984321291668452, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 78, 'subsample': 0.6168267449180366, 'colsample_bytree': 0.6258765143880406, 'reg_alpha': 4.650475774142063, 'reg_lambda': 5.1136612385830996e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▌             | 874/1000 [1:07:38<04:54,  2.34s/it]

[I 2026-05-19 15:02:30,848] Trial 874 finished with value: 0.9498381704388397 and parameters: {'n_estimators': 283, 'learning_rate': 0.04960625005741046, 'max_depth': 2, 'num_leaves': 15, 'min_child_samples': 78, 'subsample': 0.6002111990467062, 'colsample_bytree': 0.6071210651214631, 'reg_alpha': 7.387138248841348, 'reg_lambda': 6.192739935414741}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  88%|█████████████████████████████████████████████████████████████████████████████████████████████▋             | 875/1000 [1:07:40<04:34,  2.20s/it]

[I 2026-05-19 15:02:32,746] Trial 873 finished with value: 0.9498324071599242 and parameters: {'n_estimators': 284, 'learning_rate': 0.04818528981412712, 'max_depth': 2, 'num_leaves': 15, 'min_child_samples': 271, 'subsample': 0.6005793322561293, 'colsample_bytree': 0.6072448431284088, 'reg_alpha': 9.3380578944502, 'reg_lambda': 3.2574433989359184}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  88%|█████████████████████████████████████████████████████████████████████████████████████████████▋             | 876/1000 [1:07:44<05:17,  2.56s/it]

[I 2026-05-19 15:02:36,141] Trial 871 finished with value: 0.9498665530308008 and parameters: {'n_estimators': 277, 'learning_rate': 0.04776550024949855, 'max_depth': 4, 'num_leaves': 16, 'min_child_samples': 104, 'subsample': 0.9990434055415006, 'colsample_bytree': 0.6252471500284912, 'reg_alpha': 6.318220827904451, 'reg_lambda': 6.127663663103699}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  88%|█████████████████████████████████████████████████████████████████████████████████████████████▊             | 877/1000 [1:07:44<03:59,  1.94s/it]

[I 2026-05-19 15:02:36,630] Trial 877 finished with value: 0.9498405068881741 and parameters: {'n_estimators': 284, 'learning_rate': 0.04967112391314033, 'max_depth': 2, 'num_leaves': 15, 'min_child_samples': 208, 'subsample': 0.6151296022944016, 'colsample_bytree': 0.6260863546463098, 'reg_alpha': 5.9526997190289945, 'reg_lambda': 3.248699153805146}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  88%|█████████████████████████████████████████████████████████████████████████████████████████████▉             | 878/1000 [1:07:50<06:01,  2.96s/it]

[I 2026-05-19 15:02:41,992] Trial 872 finished with value: 0.9498656917243758 and parameters: {'n_estimators': 283, 'learning_rate': 0.047995899400839565, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 78, 'subsample': 0.6285544564669876, 'colsample_bytree': 0.6266604347817736, 'reg_alpha': 3.9756985470061124, 'reg_lambda': 3.3525925399668037}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  88%|██████████████████████████████████████████████████████████████████████████████████████████████             | 879/1000 [1:07:51<04:57,  2.46s/it]

[I 2026-05-19 15:02:43,259] Trial 882 finished with value: 0.9493972928233916 and parameters: {'n_estimators': 143, 'learning_rate': 0.03707734398314357, 'max_depth': 1, 'num_leaves': 15, 'min_child_samples': 81, 'subsample': 0.6171613851709447, 'colsample_bytree': 0.608608578924433, 'reg_alpha': 1.4636913920809862, 'reg_lambda': 3.4142680639732244}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▏            | 880/1000 [1:08:07<12:55,  6.46s/it]

[I 2026-05-19 15:02:59,063] Trial 885 finished with value: 0.9497503469486407 and parameters: {'n_estimators': 277, 'learning_rate': 0.03852422389059762, 'max_depth': 1, 'num_leaves': 15, 'min_child_samples': 85, 'subsample': 0.6558611203866593, 'colsample_bytree': 0.6036940186061145, 'reg_alpha': 1.3726566805938234, 'reg_lambda': 30.91212330545138}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▎            | 881/1000 [1:08:08<09:55,  5.00s/it]

[I 2026-05-19 15:03:00,658] Trial 886 finished with value: 0.9497680919759366 and parameters: {'n_estimators': 278, 'learning_rate': 0.04559928050764348, 'max_depth': 1, 'num_leaves': 15, 'min_child_samples': 83, 'subsample': 0.6135083480623016, 'colsample_bytree': 0.6061242510927279, 'reg_alpha': 1.523055105228343, 'reg_lambda': 3.555385838893675}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▎            | 882/1000 [1:08:09<07:24,  3.77s/it]

[I 2026-05-19 15:03:01,558] Trial 879 finished with value: 0.9498506474115086 and parameters: {'n_estimators': 224, 'learning_rate': 0.037462929690651084, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 207, 'subsample': 0.6189942469108324, 'colsample_bytree': 0.6063006992098453, 'reg_alpha': 4.978367256026819, 'reg_lambda': 3.492124905564943}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▍            | 883/1000 [1:08:11<06:23,  3.28s/it]

[I 2026-05-19 15:03:03,667] Trial 887 finished with value: 0.9497704569702348 and parameters: {'n_estimators': 278, 'learning_rate': 0.04645438931867724, 'max_depth': 1, 'num_leaves': 13, 'min_child_samples': 60, 'subsample': 0.6185885395791372, 'colsample_bytree': 0.6010918400950526, 'reg_alpha': 1.3203810124706663, 'reg_lambda': 3.2869250595997688}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▌            | 884/1000 [1:08:13<05:25,  2.80s/it]

[I 2026-05-19 15:03:05,373] Trial 878 finished with value: 0.9498733771369444 and parameters: {'n_estimators': 283, 'learning_rate': 0.047658742521385355, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 234, 'subsample': 0.6159085977789631, 'colsample_bytree': 0.6001934922954539, 'reg_alpha': 5.383850532170103, 'reg_lambda': 3.3329861915565497}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▋            | 885/1000 [1:08:25<10:28,  5.47s/it]

[I 2026-05-19 15:03:17,066] Trial 881 finished with value: 0.9498675508556957 and parameters: {'n_estimators': 284, 'learning_rate': 0.049680881482553736, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 83, 'subsample': 0.6159609787041536, 'colsample_bytree': 0.6070065527311572, 'reg_alpha': 1.363232947005231, 'reg_lambda': 3.195505629394641}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  89%|██████████████████████████████████████████████████████████████████████████████████████████████▊            | 886/1000 [1:08:27<08:53,  4.68s/it]

[I 2026-05-19 15:03:19,908] Trial 880 finished with value: 0.94986413838164 and parameters: {'n_estimators': 283, 'learning_rate': 0.03739435373922376, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 79, 'subsample': 0.6211046434596837, 'colsample_bytree': 0.6070893907892762, 'reg_alpha': 5.6085447008457345, 'reg_lambda': 3.9944357568911166}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  89%|██████████████████████████████████████████████████████████████████████████████████████████████▉            | 887/1000 [1:08:35<10:31,  5.59s/it]

[I 2026-05-19 15:03:27,618] Trial 883 finished with value: 0.9498674903789712 and parameters: {'n_estimators': 283, 'learning_rate': 0.037922571236547874, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 61, 'subsample': 0.8049583394946987, 'colsample_bytree': 0.608257675412145, 'reg_alpha': 5.51626777307643, 'reg_lambda': 3.4589714155313707}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  89%|███████████████████████████████████████████████████████████████████████████████████████████████            | 888/1000 [1:08:38<08:44,  4.68s/it]

[I 2026-05-19 15:03:30,171] Trial 884 finished with value: 0.9498635466399727 and parameters: {'n_estimators': 283, 'learning_rate': 0.03791426751125019, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 85, 'subsample': 0.8053685879175106, 'colsample_bytree': 0.6002894766149595, 'reg_alpha': 5.793204435057847, 'reg_lambda': 3.249142954762743}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  89%|███████████████████████████████████████████████████████████████████████████████████████████████            | 889/1000 [1:08:42<08:22,  4.53s/it]

[I 2026-05-19 15:03:34,340] Trial 889 finished with value: 0.9498521685037989 and parameters: {'n_estimators': 226, 'learning_rate': 0.03783556535161575, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 60, 'subsample': 0.8050091672508545, 'colsample_bytree': 0.6001602767065697, 'reg_alpha': 1.478586463725114, 'reg_lambda': 4.176325950895563}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▏           | 890/1000 [1:08:47<08:24,  4.59s/it]

[I 2026-05-19 15:03:39,059] Trial 888 finished with value: 0.9498621869215267 and parameters: {'n_estimators': 277, 'learning_rate': 0.036713491792838004, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 234, 'subsample': 0.6148639249607459, 'colsample_bytree': 0.642795830550922, 'reg_alpha': 1.5207469444708426, 'reg_lambda': 4.0273505175277}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▎           | 891/1000 [1:08:47<06:01,  3.31s/it]

[I 2026-05-19 15:03:39,392] Trial 890 finished with value: 0.9498634717029304 and parameters: {'n_estimators': 277, 'learning_rate': 0.03766209145193766, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 144, 'subsample': 0.6141870303778328, 'colsample_bytree': 0.600344806074247, 'reg_alpha': 1.604234763186405, 'reg_lambda': 1.2747199311663882}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▍           | 892/1000 [1:09:08<15:22,  8.54s/it]

[I 2026-05-19 15:04:00,165] Trial 891 finished with value: 0.9498631423666909 and parameters: {'n_estimators': 277, 'learning_rate': 0.03772398558153251, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 89, 'subsample': 0.617446946299298, 'colsample_bytree': 0.7464865104931032, 'reg_alpha': 5.511614241346827, 'reg_lambda': 1.3402444061956993}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▌           | 893/1000 [1:09:08<11:03,  6.20s/it]

[I 2026-05-19 15:04:00,893] Trial 892 finished with value: 0.9498587846333983 and parameters: {'n_estimators': 276, 'learning_rate': 0.03723736796131414, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 89, 'subsample': 0.6215876177133413, 'colsample_bytree': 0.6419104247769418, 'reg_alpha': 5.86917891041664, 'reg_lambda': 8.387781476580601}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▋           | 894/1000 [1:09:11<09:13,  5.23s/it]

[I 2026-05-19 15:04:03,845] Trial 893 finished with value: 0.9498585235601549 and parameters: {'n_estimators': 296, 'learning_rate': 0.04514471355882236, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 89, 'subsample': 0.820446264275797, 'colsample_bytree': 0.6936177242709328, 'reg_alpha': 5.398210333136722, 'reg_lambda': 0.0009878137690178504}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  90%|███████████████████████████████████████████████████████████████████████████████████████████████▊           | 895/1000 [1:09:15<08:19,  4.76s/it]

[I 2026-05-19 15:04:07,507] Trial 894 finished with value: 0.949858101830842 and parameters: {'n_estimators': 300, 'learning_rate': 0.037932754623006874, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 193, 'subsample': 0.8238340381105833, 'colsample_bytree': 0.6426841700683994, 'reg_alpha': 5.541906627579715, 'reg_lambda': 8.457869057102528}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  90%|███████████████████████████████████████████████████████████████████████████████████████████████▊           | 896/1000 [1:09:15<05:53,  3.40s/it]

[I 2026-05-19 15:04:07,746] Trial 895 finished with value: 0.9498634818775763 and parameters: {'n_estimators': 295, 'learning_rate': 0.03802538552596475, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 97, 'subsample': 0.6405487180140502, 'colsample_bytree': 0.7496050573120456, 'reg_alpha': 2.1142221660957263, 'reg_lambda': 10.423691419130009}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  90%|███████████████████████████████████████████████████████████████████████████████████████████████▉           | 897/1000 [1:09:22<07:36,  4.43s/it]

[I 2026-05-19 15:04:14,576] Trial 897 finished with value: 0.949865357886674 and parameters: {'n_estimators': 276, 'learning_rate': 0.045311154097784655, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 97, 'subsample': 0.6424521583500475, 'colsample_bytree': 0.6406368471343395, 'reg_alpha': 2.3106274816058283, 'reg_lambda': 8.487479724852966}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  90%|████████████████████████████████████████████████████████████████████████████████████████████████           | 898/1000 [1:09:28<08:26,  4.97s/it]

[I 2026-05-19 15:04:20,803] Trial 896 finished with value: 0.9498613857419175 and parameters: {'n_estimators': 295, 'learning_rate': 0.03739983004902866, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 143, 'subsample': 0.6386056782237771, 'colsample_bytree': 0.6452007716291257, 'reg_alpha': 2.1252969744387666, 'reg_lambda': 8.772216883630897}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▏          | 899/1000 [1:09:41<12:17,  7.30s/it]

[I 2026-05-19 15:04:33,546] Trial 899 finished with value: 0.9498622264810657 and parameters: {'n_estimators': 300, 'learning_rate': 0.04514001074744428, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 143, 'subsample': 0.6587186687303749, 'colsample_bytree': 0.6427766355348737, 'reg_alpha': 2.1561039961964923, 'reg_lambda': 1.2469980328571377}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▎          | 900/1000 [1:09:42<08:49,  5.29s/it]

[I 2026-05-19 15:04:34,126] Trial 898 finished with value: 0.949854434485516 and parameters: {'n_estimators': 300, 'learning_rate': 0.04083495777663334, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 90, 'subsample': 0.6401090278846101, 'colsample_bytree': 0.6680461604951238, 'reg_alpha': 2.145420052892237, 'reg_lambda': 1.4191088064570088}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▍          | 901/1000 [1:09:45<07:49,  4.75s/it]

[I 2026-05-19 15:04:37,619] Trial 900 finished with value: 0.9498536234226626 and parameters: {'n_estimators': 300, 'learning_rate': 0.0409401165116614, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 146, 'subsample': 0.6583580201836919, 'colsample_bytree': 0.6438394363117678, 'reg_alpha': 23.10358071550965, 'reg_lambda': 1.3434110458790531}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▌          | 902/1000 [1:09:49<07:25,  4.54s/it]

[I 2026-05-19 15:04:41,697] Trial 901 finished with value: 0.9498699874831932 and parameters: {'n_estimators': 296, 'learning_rate': 0.04151504727299823, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 145, 'subsample': 0.8245739139186559, 'colsample_bytree': 0.6434614483689127, 'reg_alpha': 2.2230469601671135, 'reg_lambda': 9.503274472240621}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▌          | 903/1000 [1:09:52<06:28,  4.00s/it]

[I 2026-05-19 15:04:44,437] Trial 902 finished with value: 0.9498763137483243 and parameters: {'n_estimators': 300, 'learning_rate': 0.041654855058152675, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 98, 'subsample': 0.6421635931718964, 'colsample_bytree': 0.6421490818169482, 'reg_alpha': 2.2445603699670515, 'reg_lambda': 8.388207654731916}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▋          | 904/1000 [1:10:12<13:54,  8.70s/it]

[I 2026-05-19 15:05:04,063] Trial 904 finished with value: 0.9498714018114441 and parameters: {'n_estimators': 294, 'learning_rate': 0.04145792092291002, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 99, 'subsample': 0.6563181994035309, 'colsample_bytree': 0.6652266560888468, 'reg_alpha': 2.3049263500211774, 'reg_lambda': 9.224851158575479}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▊          | 905/1000 [1:10:13<10:14,  6.47s/it]

[I 2026-05-19 15:05:05,322] Trial 905 finished with value: 0.9498725197716318 and parameters: {'n_estimators': 299, 'learning_rate': 0.04157579202624982, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 96, 'subsample': 0.607305120909093, 'colsample_bytree': 0.6207402785218613, 'reg_alpha': 2.250496492818525, 'reg_lambda': 9.956283971160916}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████          | 907/1000 [1:10:17<06:13,  4.01s/it]

[I 2026-05-19 15:05:09,159] Trial 907 finished with value: 0.9498674920850474 and parameters: {'n_estimators': 295, 'learning_rate': 0.04525304531768729, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 138, 'subsample': 0.6077236953100742, 'colsample_bytree': 0.6206445123340487, 'reg_alpha': 2.1780122523494527, 'reg_lambda': 5.44103838321464}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 15:05:09,285] Trial 903 finished with value: 0.949868875856154 and parameters: {'n_estimators': 300, 'learning_rate': 0.04127520128967004, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 98, 'subsample': 0.8279691337771109, 'colsample_bytree': 0.6672403792691056, 'reg_alpha': 3.782975332652752, 'reg_lambda': 8.039276415391615}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▏         | 908/1000 [1:10:20<05:36,  3.65s/it]

[I 2026-05-19 15:05:12,117] Trial 906 finished with value: 0.9498595947769136 and parameters: {'n_estimators': 295, 'learning_rate': 0.04121956440280198, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 98, 'subsample': 0.6428523671137011, 'colsample_bytree': 0.6682117002437251, 'reg_alpha': 2.220633441532971, 'reg_lambda': 6.074316145221647}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▎         | 909/1000 [1:10:24<06:01,  3.97s/it]

[I 2026-05-19 15:05:16,826] Trial 913 finished with value: 0.9498373285517078 and parameters: {'n_estimators': 158, 'learning_rate': 0.04161329445414365, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 261, 'subsample': 0.6066711264318917, 'colsample_bytree': 0.6195520884168421, 'reg_alpha': 3.4817220796084083, 'reg_lambda': 5.850636529503775}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▎         | 910/1000 [1:10:26<05:00,  3.34s/it]

[I 2026-05-19 15:05:18,703] Trial 908 finished with value: 0.9498667372894698 and parameters: {'n_estimators': 294, 'learning_rate': 0.041845277647988066, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 74, 'subsample': 0.6583255426874447, 'colsample_bytree': 0.6642725464594601, 'reg_alpha': 3.776213491927294, 'reg_lambda': 6.069805986037129}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▍         | 911/1000 [1:10:34<06:56,  4.69s/it]

[I 2026-05-19 15:05:26,521] Trial 909 finished with value: 0.9498755158241903 and parameters: {'n_estimators': 300, 'learning_rate': 0.04143136328144182, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 137, 'subsample': 0.6553163101564974, 'colsample_bytree': 0.6203306470187581, 'reg_alpha': 3.452568868725487, 'reg_lambda': 5.712122598852213}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▌         | 912/1000 [1:10:43<08:35,  5.86s/it]

[I 2026-05-19 15:05:35,139] Trial 911 finished with value: 0.9498692473306665 and parameters: {'n_estimators': 284, 'learning_rate': 0.04155420574136327, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 294, 'subsample': 0.6091666335739191, 'colsample_bytree': 0.6195966554993395, 'reg_alpha': 3.6853291146518425, 'reg_lambda': 5.58759152900917}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▋         | 913/1000 [1:10:45<07:05,  4.90s/it]

[I 2026-05-19 15:05:37,763] Trial 910 finished with value: 0.9498626337028426 and parameters: {'n_estimators': 286, 'learning_rate': 0.041304288716700235, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 182, 'subsample': 0.6071995127168165, 'colsample_bytree': 0.6654476428822116, 'reg_alpha': 3.8234974836905185, 'reg_lambda': 6.0701417496650465e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▊         | 914/1000 [1:10:46<05:13,  3.64s/it]

[I 2026-05-19 15:05:38,491] Trial 912 finished with value: 0.9498640237496284 and parameters: {'n_estimators': 285, 'learning_rate': 0.0424331115426724, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 296, 'subsample': 0.6300999612508577, 'colsample_bytree': 0.6223508545222942, 'reg_alpha': 3.84320131925694, 'reg_lambda': 5.7773581001518425e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████▉         | 915/1000 [1:10:55<07:20,  5.18s/it]

[I 2026-05-19 15:05:47,212] Trial 921 pruned.

Best trial: 603. Best value: 0.949882:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████         | 916/1000 [1:11:04<08:49,  6.30s/it]

[I 2026-05-19 15:05:56,170] Trial 914 finished with value: 0.9494368598180578 and parameters: {'n_estimators': 296, 'learning_rate': 0.0038661953246120918, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 98, 'subsample': 0.6475501895508806, 'colsample_bytree': 0.7725009322331398, 'reg_alpha': 0.9467437514265976, 'reg_lambda': 14.396596294041686}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████         | 917/1000 [1:11:14<10:18,  7.45s/it]

[I 2026-05-19 15:06:06,280] Trial 915 finished with value: 0.9498649082186817 and parameters: {'n_estimators': 295, 'learning_rate': 0.041657549433608464, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 99, 'subsample': 0.6528755071014389, 'colsample_bytree': 0.6206398578174741, 'reg_alpha': 3.7602047305824318, 'reg_lambda': 15.68331690868433}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▎        | 919/1000 [1:11:21<06:57,  5.16s/it]

[I 2026-05-19 15:06:13,215] Trial 916 finished with value: 0.9498603388229461 and parameters: {'n_estimators': 296, 'learning_rate': 0.0416711418728363, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 101, 'subsample': 0.6492435460780337, 'colsample_bytree': 0.8647357091438617, 'reg_alpha': 3.552742793912389, 'reg_lambda': 15.132268854441007}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 15:06:13,374] Trial 919 finished with value: 0.949870028840531 and parameters: {'n_estimators': 295, 'learning_rate': 0.042851474923419126, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 108, 'subsample': 0.6478380244585437, 'colsample_bytree': 0.6190008885155094, 'reg_alpha': 0.880137963165938, 'reg_lambda': 14.49217427426501}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▍        | 920/1000 [1:11:24<05:52,  4.41s/it]

[I 2026-05-19 15:06:16,068] Trial 917 finished with value: 0.949275214098616 and parameters: {'n_estimators': 295, 'learning_rate': 0.003753615549800152, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 98, 'subsample': 0.6341494271749591, 'colsample_bytree': 0.6192765643903014, 'reg_alpha': 0.8104920054870488, 'reg_lambda': 15.416743784831944}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▌        | 921/1000 [1:11:25<04:38,  3.52s/it]

[I 2026-05-19 15:06:17,511] Trial 918 finished with value: 0.9498605135984854 and parameters: {'n_estimators': 293, 'learning_rate': 0.042384789884199775, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 106, 'subsample': 0.6501371282718081, 'colsample_bytree': 0.6195549215667217, 'reg_alpha': 1.1235029379750718, 'reg_lambda': 14.302644596700018}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▋        | 922/1000 [1:11:29<04:32,  3.50s/it]

[I 2026-05-19 15:06:20,955] Trial 920 finished with value: 0.949868012773997 and parameters: {'n_estimators': 293, 'learning_rate': 0.04345440518466101, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 109, 'subsample': 0.6541964045528964, 'colsample_bytree': 0.6596934362955242, 'reg_alpha': 1.111607688490595, 'reg_lambda': 15.709540716632514}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▊        | 923/1000 [1:11:37<06:17,  4.90s/it]

[I 2026-05-19 15:06:29,136] Trial 922 finished with value: 0.949864252344325 and parameters: {'n_estimators': 300, 'learning_rate': 0.03956074875179139, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 174, 'subsample': 0.6627201247495764, 'colsample_bytree': 0.6162265137339741, 'reg_alpha': 1.047727405874338, 'reg_lambda': 10.705746215287956}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▊        | 924/1000 [1:11:46<08:01,  6.34s/it]

[I 2026-05-19 15:06:38,838] Trial 923 finished with value: 0.9498598526452444 and parameters: {'n_estimators': 296, 'learning_rate': 0.035162897327416884, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 133, 'subsample': 0.6675626769501707, 'colsample_bytree': 0.6169298585981126, 'reg_alpha': 0.3903394635890502, 'reg_lambda': 15.199582729081632}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▉        | 925/1000 [1:11:51<07:07,  5.70s/it]

[I 2026-05-19 15:06:43,056] Trial 925 finished with value: 0.9498593876620924 and parameters: {'n_estimators': 300, 'learning_rate': 0.0350478147911325, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 108, 'subsample': 0.6366124596372139, 'colsample_bytree': 0.6135464309461474, 'reg_alpha': 2.6837422816228176, 'reg_lambda': 15.693345442757638}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████        | 926/1000 [1:11:51<05:14,  4.25s/it]

[I 2026-05-19 15:06:43,893] Trial 924 finished with value: 0.9498606257600752 and parameters: {'n_estimators': 300, 'learning_rate': 0.035598989028105, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 137, 'subsample': 0.6662253226830485, 'colsample_bytree': 0.6156899451559039, 'reg_alpha': 1.2313473170135836, 'reg_lambda': 13.622316533686627}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▏       | 927/1000 [1:11:58<05:50,  4.80s/it]

[I 2026-05-19 15:06:49,994] Trial 926 finished with value: 0.9498661554997702 and parameters: {'n_estimators': 300, 'learning_rate': 0.039479682841574215, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 164, 'subsample': 0.6663506952514017, 'colsample_bytree': 0.6131295691102864, 'reg_alpha': 0.8429731202846767, 'reg_lambda': 17.0250288856795}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▎       | 928/1000 [1:12:07<07:29,  6.24s/it]

[I 2026-05-19 15:06:59,606] Trial 927 finished with value: 0.9498651361518282 and parameters: {'n_estimators': 300, 'learning_rate': 0.045121804338197055, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 165, 'subsample': 0.6745106145577507, 'colsample_bytree': 0.6115679537844018, 'reg_alpha': 0.7549001846541468, 'reg_lambda': 18.780901030187298}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▍       | 929/1000 [1:12:20<09:35,  8.11s/it]

[I 2026-05-19 15:07:12,066] Trial 928 finished with value: 0.9498540972147584 and parameters: {'n_estimators': 300, 'learning_rate': 0.045030585488274856, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 136, 'subsample': 0.6657579223138783, 'colsample_bytree': 0.8016574414549739, 'reg_alpha': 1.1128136221454534, 'reg_lambda': 21.37058820759119}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▌       | 930/1000 [1:12:23<07:55,  6.79s/it]

[I 2026-05-19 15:07:15,792] Trial 930 finished with value: 0.949871471082911 and parameters: {'n_estimators': 292, 'learning_rate': 0.04540864000148276, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 132, 'subsample': 0.654161647656083, 'colsample_bytree': 0.6131781685218514, 'reg_alpha': 0.0001205694798675602, 'reg_lambda': 24.337298713655624}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▌       | 931/1000 [1:12:25<06:04,  5.28s/it]

[I 2026-05-19 15:07:17,545] Trial 929 finished with value: 0.949859687474509 and parameters: {'n_estimators': 299, 'learning_rate': 0.03489006209240932, 'max_depth': 4, 'num_leaves': 12, 'min_child_samples': 116, 'subsample': 0.667695479995015, 'colsample_bytree': 0.6141859915335185, 'reg_alpha': 0.5032415906978971, 'reg_lambda': 10.928105619190056}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▋       | 932/1000 [1:12:27<04:42,  4.15s/it]

[I 2026-05-19 15:07:19,038] Trial 931 finished with value: 0.949866592059157 and parameters: {'n_estimators': 291, 'learning_rate': 0.0448992285555169, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 166, 'subsample': 0.6680775008700095, 'colsample_bytree': 0.612532392798894, 'reg_alpha': 0.3870932871729519, 'reg_lambda': 11.003698795045404}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▊       | 933/1000 [1:12:30<04:31,  4.05s/it]

[I 2026-05-19 15:07:22,879] Trial 933 finished with value: 0.949859579919277 and parameters: {'n_estimators': 299, 'learning_rate': 0.035471393583711014, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 153, 'subsample': 0.6265406773458975, 'colsample_bytree': 0.6123859167124557, 'reg_alpha': 0.00021158784538944747, 'reg_lambda': 7.394475648610089}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████▉       | 934/1000 [1:12:33<03:53,  3.54s/it]

[I 2026-05-19 15:07:25,220] Trial 932 finished with value: 0.9498568566256193 and parameters: {'n_estimators': 292, 'learning_rate': 0.03478447398195128, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 164, 'subsample': 0.6650589209361729, 'colsample_bytree': 0.7619422384491317, 'reg_alpha': 1.6445614050121928, 'reg_lambda': 7.009315963262607}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████       | 935/1000 [1:12:40<04:52,  4.51s/it]

[I 2026-05-19 15:07:31,976] Trial 934 finished with value: 0.9498630202818727 and parameters: {'n_estimators': 290, 'learning_rate': 0.03497784611372791, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 120, 'subsample': 0.669209007541706, 'colsample_bytree': 0.6136038130176852, 'reg_alpha': 1.6884250627171797, 'reg_lambda': 6.772728627777372}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 936/1000 [1:12:50<06:40,  6.26s/it]

[I 2026-05-19 15:07:42,335] Trial 935 finished with value: 0.9498644155462774 and parameters: {'n_estimators': 300, 'learning_rate': 0.04567735804288387, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 159, 'subsample': 0.6762207637027063, 'colsample_bytree': 0.6268843675813985, 'reg_alpha': 1.7633873421981479, 'reg_lambda': 0.5831998299913406}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 937/1000 [1:12:52<05:18,  5.06s/it]

[I 2026-05-19 15:07:44,608] Trial 936 finished with value: 0.9498631160270101 and parameters: {'n_estimators': 291, 'learning_rate': 0.045451482897385126, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 158, 'subsample': 0.6711828642273335, 'colsample_bytree': 0.6111387885133223, 'reg_alpha': 1.7705849675959908, 'reg_lambda': 28.16422510965672}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 938/1000 [1:12:57<05:15,  5.08s/it]

[I 2026-05-19 15:07:49,723] Trial 937 finished with value: 0.9498299849724475 and parameters: {'n_estimators': 289, 'learning_rate': 0.021334161244878004, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 129, 'subsample': 0.6651970460883397, 'colsample_bytree': 0.6089998062801206, 'reg_alpha': 1.8261113386364687, 'reg_lambda': 22.12126129948188}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▍      | 939/1000 [1:12:58<03:55,  3.86s/it]

[I 2026-05-19 15:07:50,704] Trial 938 finished with value: 0.9498739394021867 and parameters: {'n_estimators': 291, 'learning_rate': 0.04598718044090275, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 132, 'subsample': 0.6764938880185698, 'colsample_bytree': 0.6287373111235753, 'reg_alpha': 2.659330051788052, 'reg_lambda': 6.926191301524871}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 940/1000 [1:13:11<06:31,  6.52s/it]

[I 2026-05-19 15:08:03,457] Trial 939 finished with value: 0.9498591172224702 and parameters: {'n_estimators': 290, 'learning_rate': 0.04594460556214226, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 118, 'subsample': 0.671572547064849, 'colsample_bytree': 0.7595757985596653, 'reg_alpha': 1.814346587727495, 'reg_lambda': 0.5799831172263915}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 941/1000 [1:13:17<06:08,  6.24s/it]

[I 2026-05-19 15:08:09,049] Trial 940 finished with value: 0.949862106661256 and parameters: {'n_estimators': 290, 'learning_rate': 0.046145233533712596, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 152, 'subsample': 0.9995718114036298, 'colsample_bytree': 0.6281518995186157, 'reg_alpha': 0.00015789890357429637, 'reg_lambda': 7.5140871111452165}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 942/1000 [1:13:27<07:08,  7.39s/it]

[I 2026-05-19 15:08:19,123] Trial 941 finished with value: 0.949871708967701 and parameters: {'n_estimators': 290, 'learning_rate': 0.045736280085033, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 126, 'subsample': 0.6756567326924457, 'colsample_bytree': 0.6272976993750355, 'reg_alpha': 1.8970784542136534, 'reg_lambda': 7.80912586264755}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████▉      | 943/1000 [1:13:28<05:25,  5.72s/it]

[I 2026-05-19 15:08:20,930] Trial 943 finished with value: 0.9498678677802594 and parameters: {'n_estimators': 287, 'learning_rate': 0.03962181403686283, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 113, 'subsample': 0.8470718279665505, 'colsample_bytree': 0.6280548338470407, 'reg_alpha': 2.6718118437124363, 'reg_lambda': 7.250871943337895}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████      | 944/1000 [1:13:30<04:08,  4.44s/it]

[I 2026-05-19 15:08:22,383] Trial 942 finished with value: 0.9498644055217198 and parameters: {'n_estimators': 290, 'learning_rate': 0.03922110825426282, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 115, 'subsample': 0.6750665440577981, 'colsample_bytree': 0.6303137279485053, 'reg_alpha': 1.724368309170199, 'reg_lambda': 6.974760534778681}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████      | 945/1000 [1:13:32<03:17,  3.59s/it]

[I 2026-05-19 15:08:24,003] Trial 945 finished with value: 0.9498358377361018 and parameters: {'n_estimators': 253, 'learning_rate': 0.023227299382617382, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 157, 'subsample': 0.6292545327102816, 'colsample_bytree': 0.6276807021239259, 'reg_alpha': 2.722147953468817, 'reg_lambda': 5.148539532913845}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 946/1000 [1:13:33<02:45,  3.06s/it]

[I 2026-05-19 15:08:25,823] Trial 944 finished with value: 0.9498610083940788 and parameters: {'n_estimators': 290, 'learning_rate': 0.03923881801840828, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 116, 'subsample': 0.8436279222957153, 'colsample_bytree': 0.6270534001795729, 'reg_alpha': 1.7960350501960853, 'reg_lambda': 6.477696188985221}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎     | 947/1000 [1:13:46<05:07,  5.80s/it]

[I 2026-05-19 15:08:38,014] Trial 946 finished with value: 0.949834463227524 and parameters: {'n_estimators': 288, 'learning_rate': 0.02139545650870159, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 117, 'subsample': 0.678564870709141, 'colsample_bytree': 0.628642232849229, 'reg_alpha': 2.589847823722592, 'reg_lambda': 4.68549867717639}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 948/1000 [1:13:51<04:56,  5.70s/it]

[I 2026-05-19 15:08:43,491] Trial 947 finished with value: 0.9498633009334577 and parameters: {'n_estimators': 288, 'learning_rate': 0.03964254304794109, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 152, 'subsample': 0.9934425328231068, 'colsample_bytree': 0.6307742940842961, 'reg_alpha': 2.81084169990173, 'reg_lambda': 5.2927609444875925}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 949/1000 [1:13:58<05:05,  6.00s/it]

[I 2026-05-19 15:08:50,177] Trial 949 finished with value: 0.9498693165295762 and parameters: {'n_estimators': 288, 'learning_rate': 0.038763671568529626, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 152, 'subsample': 0.9924078265362665, 'colsample_bytree': 0.6279160063939273, 'reg_alpha': 2.6202632420781025, 'reg_lambda': 4.598899333071506}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 950/1000 [1:14:00<03:59,  4.78s/it]

[I 2026-05-19 15:08:52,095] Trial 948 finished with value: 0.9496267291912417 and parameters: {'n_estimators': 288, 'learning_rate': 0.004299065626815522, 'max_depth': 4, 'num_leaves': 13, 'min_child_samples': 252, 'subsample': 0.9943933421284463, 'colsample_bytree': 0.6297974101388181, 'reg_alpha': 2.6700542415019113, 'reg_lambda': 4.69529247770287}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 951/1000 [1:14:06<04:10,  5.10s/it]

[I 2026-05-19 15:08:57,931] Trial 950 finished with value: 0.9497219105627043 and parameters: {'n_estimators': 287, 'learning_rate': 0.0054098440929551996, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 117, 'subsample': 0.8506477625726813, 'colsample_bytree': 0.6283499807511056, 'reg_alpha': 2.6747034446458366, 'reg_lambda': 4.416284452666835}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 952/1000 [1:14:07<03:16,  4.09s/it]

[I 2026-05-19 15:08:59,698] Trial 951 finished with value: 0.9498597498721013 and parameters: {'n_estimators': 255, 'learning_rate': 0.038455782882923964, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 108, 'subsample': 0.9994155196134533, 'colsample_bytree': 0.627740258696586, 'reg_alpha': 2.690821759092376, 'reg_lambda': 2.642946784375095}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 953/1000 [1:14:18<04:51,  6.20s/it]

[I 2026-05-19 15:09:10,828] Trial 952 finished with value: 0.9498671979957413 and parameters: {'n_estimators': 286, 'learning_rate': 0.039345462742888485, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 113, 'subsample': 0.6306335403018917, 'colsample_bytree': 0.6374372271581051, 'reg_alpha': 2.6664760909076404, 'reg_lambda': 4.788829528869633}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████     | 954/1000 [1:14:26<04:59,  6.52s/it]

[I 2026-05-19 15:09:18,070] Trial 955 finished with value: 0.9498632718851656 and parameters: {'n_estimators': 255, 'learning_rate': 0.03975558036185253, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 102, 'subsample': 0.62978919975423, 'colsample_bytree': 0.6411231323395263, 'reg_alpha': 2.735895632350421, 'reg_lambda': 4.807789349156045}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 955/1000 [1:14:29<04:16,  5.70s/it]

[I 2026-05-19 15:09:21,874] Trial 953 finished with value: 0.9498685785502538 and parameters: {'n_estimators': 286, 'learning_rate': 0.0399725126219756, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 114, 'subsample': 0.8395449107192546, 'colsample_bytree': 0.6388756267690715, 'reg_alpha': 2.6746040938990157, 'reg_lambda': 4.839275413321105}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 956/1000 [1:14:38<04:45,  6.49s/it]

[I 2026-05-19 15:09:30,182] Trial 954 finished with value: 0.949803223659418 and parameters: {'n_estimators': 285, 'learning_rate': 0.015414936203106073, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 116, 'subsample': 0.6272768238068438, 'colsample_bytree': 0.6353501663400603, 'reg_alpha': 2.819510383845956, 'reg_lambda': 4.749687948414437}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 957/1000 [1:14:38<03:21,  4.69s/it]

[I 2026-05-19 15:09:30,666] Trial 957 finished with value: 0.9497855402599958 and parameters: {'n_estimators': 285, 'learning_rate': 0.012055782300488038, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 101, 'subsample': 0.6332972314450814, 'colsample_bytree': 0.63707380632907, 'reg_alpha': 2.725546056623735, 'reg_lambda': 1.8071675403620542}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 958/1000 [1:14:44<03:29,  4.99s/it]

[I 2026-05-19 15:09:36,375] Trial 956 finished with value: 0.9497701589080421 and parameters: {'n_estimators': 286, 'learning_rate': 0.00896129339467147, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 151, 'subsample': 0.6264900921579437, 'colsample_bytree': 0.6419195724073649, 'reg_alpha': 2.8259891401848876, 'reg_lambda': 0.0005510617851718892}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 959/1000 [1:14:49<03:20,  4.90s/it]

[I 2026-05-19 15:09:41,032] Trial 958 finished with value: 0.9498628845434631 and parameters: {'n_estimators': 284, 'learning_rate': 0.04350941774760473, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 250, 'subsample': 0.6364252917486375, 'colsample_bytree': 0.6501263004503648, 'reg_alpha': 4.138675282105905, 'reg_lambda': 3.0771204666274136e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 960/1000 [1:14:55<03:33,  5.34s/it]

[I 2026-05-19 15:09:47,398] Trial 959 finished with value: 0.9498680604476647 and parameters: {'n_estimators': 284, 'learning_rate': 0.043384079673229096, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 300, 'subsample': 0.7801159198229639, 'colsample_bytree': 0.6411548178590839, 'reg_alpha': 4.0883124109599756, 'reg_lambda': 1.850876893056067}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 961/1000 [1:14:58<02:57,  4.56s/it]

[I 2026-05-19 15:09:50,160] Trial 968 finished with value: 0.949772320313173 and parameters: {'n_estimators': 80, 'learning_rate': 0.04993096072358221, 'max_depth': 4, 'num_leaves': 9, 'min_child_samples': 93, 'subsample': 0.640720177701059, 'colsample_bytree': 0.650575367588007, 'reg_alpha': 4.334966290470154, 'reg_lambda': 2.7040301361828503}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 962/1000 [1:14:59<02:18,  3.65s/it]

[I 2026-05-19 15:09:51,676] Trial 961 finished with value: 0.9498727576193928 and parameters: {'n_estimators': 282, 'learning_rate': 0.04377866037839097, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 105, 'subsample': 0.626987019862893, 'colsample_bytree': 0.6494134014559296, 'reg_alpha': 3.8342085245669626, 'reg_lambda': 1.6590125822940294}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████    | 963/1000 [1:15:02<02:10,  3.52s/it]

[I 2026-05-19 15:09:54,902] Trial 960 finished with value: 0.9498670542811795 and parameters: {'n_estimators': 283, 'learning_rate': 0.04357120828539942, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 103, 'subsample': 0.9548042233270202, 'colsample_bytree': 0.8330196979863329, 'reg_alpha': 3.561659248395536, 'reg_lambda': 0.0006635438189125147}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏   | 964/1000 [1:15:04<01:49,  3.03s/it]

[I 2026-05-19 15:09:56,804] Trial 962 finished with value: 0.9498711615054024 and parameters: {'n_estimators': 283, 'learning_rate': 0.044149862034505875, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 102, 'subsample': 0.6351448054331477, 'colsample_bytree': 0.6414688571210753, 'reg_alpha': 4.277123884161567, 'reg_lambda': 3.123997605470417e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 965/1000 [1:15:06<01:35,  2.72s/it]

[I 2026-05-19 15:09:58,769] Trial 963 finished with value: 0.9498683165133706 and parameters: {'n_estimators': 282, 'learning_rate': 0.04343263750614784, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 271, 'subsample': 0.6247952743873253, 'colsample_bytree': 0.6400823674772081, 'reg_alpha': 4.777432319137561, 'reg_lambda': 1.7844391968953277}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 966/1000 [1:15:19<03:17,  5.82s/it]

[I 2026-05-19 15:10:11,842] Trial 964 finished with value: 0.9498760522330436 and parameters: {'n_estimators': 280, 'learning_rate': 0.043552245058678454, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 103, 'subsample': 0.6417679005251183, 'colsample_bytree': 0.6497159119455426, 'reg_alpha': 4.521041552918255, 'reg_lambda': 2.15518344804763}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 967/1000 [1:15:31<04:12,  7.66s/it]

[I 2026-05-19 15:10:23,794] Trial 965 finished with value: 0.9497826645503136 and parameters: {'n_estimators': 280, 'learning_rate': 0.011883691399243914, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 90, 'subsample': 0.7768769393698421, 'colsample_bytree': 0.6460969458138266, 'reg_alpha': 4.276536991525434, 'reg_lambda': 1.7122732705759034}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 968/1000 [1:15:32<02:54,  5.44s/it]

[I 2026-05-19 15:10:24,036] Trial 966 finished with value: 0.9498648447736618 and parameters: {'n_estimators': 280, 'learning_rate': 0.04404770199610391, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 91, 'subsample': 0.9384694721377657, 'colsample_bytree': 0.6000888047733548, 'reg_alpha': 4.364178729680234, 'reg_lambda': 2.96673820967492e-05}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 969/1000 [1:15:37<02:47,  5.39s/it]

[I 2026-05-19 15:10:29,327] Trial 967 finished with value: 0.949867921958424 and parameters: {'n_estimators': 275, 'learning_rate': 0.04998073269150655, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 91, 'subsample': 0.9501960836111768, 'colsample_bytree': 0.646871028493995, 'reg_alpha': 5.011208997333453, 'reg_lambda': 1.7120089292928402}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 970/1000 [1:15:44<02:56,  5.89s/it]

[I 2026-05-19 15:10:36,386] Trial 969 finished with value: 0.9498720369945886 and parameters: {'n_estimators': 277, 'learning_rate': 0.043123726974938256, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 94, 'subsample': 0.6386845245541632, 'colsample_bytree': 0.6499872859882585, 'reg_alpha': 4.3626361150125055, 'reg_lambda': 0.00014959235246144993}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 971/1000 [1:15:49<02:46,  5.74s/it]

[I 2026-05-19 15:10:41,756] Trial 970 finished with value: 0.9498611638596277 and parameters: {'n_estimators': 278, 'learning_rate': 0.04321811596734581, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 272, 'subsample': 0.9375442773194202, 'colsample_bytree': 0.658121199211313, 'reg_alpha': 3.89143228566668, 'reg_lambda': 0.00014809551891176043}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████   | 972/1000 [1:15:53<02:25,  5.19s/it]

[I 2026-05-19 15:10:45,652] Trial 975 finished with value: 0.9498572921159326 and parameters: {'n_estimators': 274, 'learning_rate': 0.047867783068848035, 'max_depth': 4, 'num_leaves': 8, 'min_child_samples': 273, 'subsample': 0.9781453200081481, 'colsample_bytree': 0.6079416502926539, 'reg_alpha': 7.2744549148013355, 'reg_lambda': 0.0033984090156135792}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████   | 973/1000 [1:15:59<02:24,  5.35s/it]

[I 2026-05-19 15:10:51,398] Trial 972 finished with value: 0.9498624982121244 and parameters: {'n_estimators': 275, 'learning_rate': 0.04739176883114997, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 86, 'subsample': 0.9553436412886797, 'colsample_bytree': 0.6585322517486553, 'reg_alpha': 7.089838673800132, 'reg_lambda': 2.594418560518104}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 974/1000 [1:15:59<01:40,  3.86s/it]

[I 2026-05-19 15:10:51,781] Trial 973 finished with value: 0.9498706328980688 and parameters: {'n_estimators': 275, 'learning_rate': 0.047354104219109405, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 91, 'subsample': 0.6565946025123026, 'colsample_bytree': 0.6060465524355702, 'reg_alpha': 6.063737300623844, 'reg_lambda': 0.00014884043881716004}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 975/1000 [1:16:04<01:41,  4.08s/it]

[I 2026-05-19 15:10:56,366] Trial 971 finished with value: 0.9497608157652155 and parameters: {'n_estimators': 275, 'learning_rate': 0.010350117388484728, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 90, 'subsample': 0.9525443899837863, 'colsample_bytree': 0.6595552017071061, 'reg_alpha': 6.9303613599372005, 'reg_lambda': 2.65320876144228}. Best is trial 603 with value: 0.9498815886860695.
[I 2026-05-19 15:10:56,406] Trial 974 finished with value: 0.9498631915516288 and parameters: {'n_estimators': 276, 'learning_rate': 0.0476953052270516, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 88, 'subsample': 0.9420518974488891, 'colsample_bytree': 0.6575732451910331, 'reg_alpha': 7.15586971045433, 'reg_lambda': 0.9222281464760105}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 977/1000 [1:16:05<00:58,  2.52s/it]

[I 2026-05-19 15:10:57,791] Trial 976 finished with value: 0.9498760807662958 and parameters: {'n_estimators': 275, 'learning_rate': 0.04682899726753748, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 89, 'subsample': 0.9528326984322046, 'colsample_bytree': 0.6061236886905893, 'reg_alpha': 4.547661527431025, 'reg_lambda': 2.53360606196489}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▋  | 978/1000 [1:16:20<02:02,  5.57s/it]

[I 2026-05-19 15:11:12,571] Trial 977 finished with value: 0.949863921820753 and parameters: {'n_estimators': 275, 'learning_rate': 0.04597166866637228, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 109, 'subsample': 0.6437456038014355, 'colsample_bytree': 0.6563390619505315, 'reg_alpha': 7.677060951099453, 'reg_lambda': 2.7465062891507332}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 979/1000 [1:16:25<01:54,  5.46s/it]

[I 2026-05-19 15:11:17,733] Trial 978 finished with value: 0.9498603167478246 and parameters: {'n_estimators': 275, 'learning_rate': 0.04747054005135474, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 110, 'subsample': 0.6611758620122568, 'colsample_bytree': 0.6570338360038842, 'reg_alpha': 7.188880159212321, 'reg_lambda': 2.5769063008382873}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 980/1000 [1:16:28<01:36,  4.83s/it]

[I 2026-05-19 15:11:20,886] Trial 979 finished with value: 0.9498569822118 and parameters: {'n_estimators': 264, 'learning_rate': 0.04723197688131526, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 96, 'subsample': 0.6438771208416177, 'colsample_bytree': 0.658887673173175, 'reg_alpha': 7.295565845642414, 'reg_lambda': 2.522778102646143}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉  | 981/1000 [1:16:35<01:38,  5.18s/it]

[I 2026-05-19 15:11:26,943] Trial 980 finished with value: 0.9498674667888103 and parameters: {'n_estimators': 264, 'learning_rate': 0.04725027286308259, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 107, 'subsample': 0.6513969687861307, 'colsample_bytree': 0.6753842579396983, 'reg_alpha': 5.595762343217963, 'reg_lambda': 2.627796543140648}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████  | 982/1000 [1:16:45<01:58,  6.58s/it]

[I 2026-05-19 15:11:37,031] Trial 981 finished with value: 0.9498660467089277 and parameters: {'n_estimators': 266, 'learning_rate': 0.04659407577194255, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 84, 'subsample': 0.6443643635927297, 'colsample_bytree': 0.6595725380505675, 'reg_alpha': 6.1070075622055615, 'reg_lambda': 2.5583091893362404}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 983/1000 [1:16:47<01:28,  5.23s/it]

[I 2026-05-19 15:11:38,976] Trial 982 finished with value: 0.9498672350429654 and parameters: {'n_estimators': 273, 'learning_rate': 0.047151827581803654, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 108, 'subsample': 0.6429237559161837, 'colsample_bytree': 0.6553986404323937, 'reg_alpha': 6.447290490636928, 'reg_lambda': 2.7000111074988977}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 984/1000 [1:16:53<01:31,  5.74s/it]

[I 2026-05-19 15:11:45,928] Trial 983 finished with value: 0.9498727512588522 and parameters: {'n_estimators': 273, 'learning_rate': 0.04768310579313186, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 290, 'subsample': 0.645917858987245, 'colsample_bytree': 0.7196621719213318, 'reg_alpha': 6.734623827317733, 'reg_lambda': 2.672640018838809}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 985/1000 [1:16:55<01:09,  4.64s/it]

[I 2026-05-19 15:11:47,931] Trial 985 finished with value: 0.9498646629981169 and parameters: {'n_estimators': 263, 'learning_rate': 0.04720647945929708, 'max_depth': 4, 'num_leaves': 11, 'min_child_samples': 109, 'subsample': 0.6474446796065988, 'colsample_bytree': 0.6552481928688517, 'reg_alpha': 8.249533530269192, 'reg_lambda': 2.766110077363079}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 986/1000 [1:16:58<00:54,  3.90s/it]

[I 2026-05-19 15:11:50,096] Trial 984 finished with value: 0.9498571676346964 and parameters: {'n_estimators': 273, 'learning_rate': 0.04704303738981385, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 288, 'subsample': 0.638274693267192, 'colsample_bytree': 0.6751149054454701, 'reg_alpha': 6.452268148999668, 'reg_lambda': 10.307900437680647}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▌ | 987/1000 [1:17:03<00:57,  4.39s/it]

[I 2026-05-19 15:11:55,622] Trial 988 finished with value: 0.9498568293079263 and parameters: {'n_estimators': 265, 'learning_rate': 0.04749398007196448, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 110, 'subsample': 0.883580761299983, 'colsample_bytree': 0.6581194659179622, 'reg_alpha': 7.561542977797461, 'reg_lambda': 2.6592837937771496}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 988/1000 [1:17:04<00:41,  3.46s/it]

[I 2026-05-19 15:11:56,895] Trial 987 finished with value: 0.9498548700124696 and parameters: {'n_estimators': 265, 'learning_rate': 0.04671202285085056, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 289, 'subsample': 0.6519338449363726, 'colsample_bytree': 0.6760116281509893, 'reg_alpha': 4.387907545014259e-05, 'reg_lambda': 2.760036262440175}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊ | 989/1000 [1:17:08<00:37,  3.40s/it]

[I 2026-05-19 15:12:00,170] Trial 986 finished with value: 0.9498567044769304 and parameters: {'n_estimators': 269, 'learning_rate': 0.04708363937220336, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 288, 'subsample': 0.6424976284640558, 'colsample_bytree': 0.6555867975484084, 'reg_alpha': 7.63683181386632, 'reg_lambda': 3.0882252691532677}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 990/1000 [1:17:15<00:45,  4.57s/it]

[I 2026-05-19 15:12:07,482] Trial 999 finished with value: 0.949735004424021 and parameters: {'n_estimators': 56, 'learning_rate': 0.049615388540974185, 'max_depth': 3, 'num_leaves': 14, 'min_child_samples': 82, 'subsample': 0.8672969094302959, 'colsample_bytree': 0.6049447379734099, 'reg_alpha': 11.019389558443004, 'reg_lambda': 3.5772729506964462}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████ | 991/1000 [1:17:17<00:34,  3.86s/it]

[I 2026-05-19 15:12:09,669] Trial 989 finished with value: 0.9498672102992348 and parameters: {'n_estimators': 263, 'learning_rate': 0.04998262753000573, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 80, 'subsample': 0.6564612086865963, 'colsample_bytree': 0.6541526354221703, 'reg_alpha': 6.756546805505881, 'reg_lambda': 2.724159322339262}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 992/1000 [1:17:22<00:32,  4.11s/it]

[I 2026-05-19 15:12:14,369] Trial 997 finished with value: 0.9497672854348916 and parameters: {'n_estimators': 267, 'learning_rate': 0.04460282019421641, 'max_depth': 3, 'num_leaves': 2, 'min_child_samples': 86, 'subsample': 0.9521558192260493, 'colsample_bytree': 0.6077551693356201, 'reg_alpha': 10.520291071357775, 'reg_lambda': 3.899983528478559}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 993/1000 [1:17:23<00:21,  3.09s/it]

[I 2026-05-19 15:12:15,071] Trial 990 finished with value: 0.949866728596523 and parameters: {'n_estimators': 260, 'learning_rate': 0.0476676012209304, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 84, 'subsample': 0.9516878730910023, 'colsample_bytree': 0.6007293068680164, 'reg_alpha': 10.355236455963036, 'reg_lambda': 2.7736391892017456}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 994/1000 [1:17:24<00:14,  2.48s/it]

[I 2026-05-19 15:12:16,147] Trial 991 finished with value: 0.949867527858167 and parameters: {'n_estimators': 268, 'learning_rate': 0.04763639830103544, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 82, 'subsample': 0.9468871635057079, 'colsample_bytree': 0.609405455284093, 'reg_alpha': 10.072937503728111, 'reg_lambda': 3.060108415669345}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍| 995/1000 [1:17:25<00:10,  2.06s/it]

[I 2026-05-19 15:12:17,205] Trial 992 finished with value: 0.9498664133555014 and parameters: {'n_estimators': 264, 'learning_rate': 0.047474632409984674, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 85, 'subsample': 0.9422035209934386, 'colsample_bytree': 0.6074267166888262, 'reg_alpha': 10.0374991497235, 'reg_lambda': 3.8489931180540773}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 996/1000 [1:17:26<00:06,  1.73s/it]

[I 2026-05-19 15:12:18,163] Trial 994 finished with value: 0.949849175198807 and parameters: {'n_estimators': 266, 'learning_rate': 0.04532149562733815, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 83, 'subsample': 0.9454966681425071, 'colsample_bytree': 0.6085211869354625, 'reg_alpha': 9.332294332818163, 'reg_lambda': 3.7492461759072127}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋| 997/1000 [1:17:28<00:05,  1.97s/it]

[I 2026-05-19 15:12:20,702] Trial 995 finished with value: 0.949847600530758 and parameters: {'n_estimators': 264, 'learning_rate': 0.04537743240602237, 'max_depth': 3, 'num_leaves': 15, 'min_child_samples': 84, 'subsample': 0.9625092831856182, 'colsample_bytree': 0.600233428778365, 'reg_alpha': 0.048852599276432984, 'reg_lambda': 4.077059494382502}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 998/1000 [1:17:29<00:02,  1.48s/it]

[I 2026-05-19 15:12:21,032] Trial 993 finished with value: 0.949860172877894 and parameters: {'n_estimators': 266, 'learning_rate': 0.04745744459495787, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 83, 'subsample': 0.9438322682182348, 'colsample_bytree': 0.6087132158974463, 'reg_alpha': 11.287507755552829, 'reg_lambda': 3.9339117390831917}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉| 999/1000 [1:17:30<00:01,  1.56s/it]

[I 2026-05-19 15:12:22,774] Trial 996 finished with value: 0.9498672334572846 and parameters: {'n_estimators': 267, 'learning_rate': 0.04467063415385003, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 98, 'subsample': 0.9607066727762179, 'colsample_bytree': 0.6057484805869686, 'reg_alpha': 9.899037788061916, 'reg_lambda': 3.6583320284042014}. Best is trial 603 with value: 0.9498815886860695.

Best trial: 603. Best value: 0.949882: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [1:17:31<00:00,  4.65s/it]

[I 2026-05-19 15:12:23,564] Trial 998 finished with value: 0.9498627418333221 and parameters: {'n_estimators': 268, 'learning_rate': 0.04456733190424611, 'max_depth': 4, 'num_leaves': 14, 'min_child_samples': 82, 'subsample': 0.9622271026771319, 'colsample_bytree': 0.6060328611590549, 'reg_alpha': 10.476951256022138, 'reg_lambda': 4.113478614845083}. Best is trial 603 with value: 0.9498815886860695.
Best trial score:
0.9498815886860695

Best params:
{'n_estimators': 272, 'learning_rate': 0.04331743813378749, 'max_depth': 4, 'num_leaves': 15, 'min_child_samples': 79, 'subsample': 0.849554199458748, 'colsample_bytree': 0.6452730806890068, 'reg_alpha': 3.4284318632046933, 'reg_lambda': 6.744375246788695}

In [9]:
stacking_lgbm = LGBMClassifier(**study.best_params).fit(X_train, y_train.PitNextLap)

[LightGBM] [Info] Number of positive: 87381, number of negative: 351759
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007971 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 2550
[LightGBM] [Info] Number of data points in the train set: 439140, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.198982 -> initscore=-1.392668
[LightGBM] [Info] Start training from score -1.392668
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

# Submission

In [10]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [11]:
submission['PitNextLap'] = stacking_lgbm.predict_proba(X_test)[:, 1]

In [12]:
submission.to_csv('../data/submission/submission.csv', index=False)

In [13]:
X_train.columns

Index(['lgbm_logit', 'cat_logit', 'xgb_logit', 'hist_logit', 'lg_logit',
       'knn_logit', 'ridge_logit', 'voting_lgbm_cat_xgb_hist_logit',
       'voting_lg_ridge_logit',
       'stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_logit'],
      dtype='str')