# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from lightgbm import LGBMClassifier

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import StackingClassifier, VotingClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

# Loading Dataset

In [3]:
X_train = pd.read_parquet('../data/processed/X_train_logit.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_logit.parquet')

In [4]:
X_train.head()

,lgbm_logit,cat_logit,xgb_logit,hist_logit,lg_logit,knn_logit,ridge_logit,voting_lgbm_cat_xgb_hist_logit,voting_lg_ridge_logit,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_logit
0,1.402666,2.109990,2.149899,2.030346,1.440273,2.064999,0.500714,1.887848,0.925326,1.226844
1,0.616425,1.595299,1.584592,1.262993,0.799597,0.079907,0.335105,1.222563,0.561368,0.371762
2,0.023615,1.748857,1.106745,1.146720,0.235157,-1.325798,0.136991,0.929687,0.186260,0.066618
3,-6.367775,-5.125195,-4.946636,-4.912857,-6.083520,-34.538776,-1.247050,-5.198584,-2.069743,-6.799934
4,-0.438053,0.263538,-0.043875,-0.068158,-0.346862,-0.861416,-0.094611,-0.070366,-0.220629,-0.878595

In [5]:
X_test.head()

,lgbm_logit,cat_logit,xgb_logit,hist_logit,lg_logit,knn_logit,ridge_logit,voting_lgbm_cat_xgb_hist_logit,voting_lg_ridge_logit,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_logit
0,-5.379032,-3.409957,-3.759100,-3.888929,-5.042109,-34.538776,-1.272709,-3.899528,-34.538776,-5.055490
1,-5.795381,-4.426299,-4.187473,-3.950213,-2.684867,-2.019087,-0.626960,-4.396275,-34.538776,-5.602505
2,-5.574937,-4.441487,-4.232580,-4.454119,-5.395432,-34.538776,-1.335019,-4.564839,-34.538776,-5.656104
3,-1.635113,0.176618,0.347033,-0.058463,0.644945,-2.198160,0.190133,-0.222683,-0.304675,-1.163384
4,1.920299,3.398116,3.163860,3.161400,1.661579,34.539576,0.535153,2.745303,0.794179,2.146481

# Machine Learning

In [6]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "C": trial.suggest_float("C", 1e-5, 100, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
        "max_iter": trial.suggest_int("max_iter", 1000, 5000)
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LogisticRegression(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train, y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-19 15:36:52,023] A new study created in memory with name: no-name-e28d4f89-23ff-45a0-ad5e-6fa68c9499e5
Best trial: 9. Best value: 0.944693:   0%|▏                                                                                                               | 1/500 [00:10<1:30:55, 10.93s/it]

[I 2026-05-19 15:37:02,933] Trial 9 finished with value: 0.9446932299701961 and parameters: {'solver': 'saga', 'C': 2.06198041382091e-05, 'l1_ratio': 0.9817538850496152, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0007496390764380842, 'max_iter': 3982}. Best is trial 9 with value: 0.9446932299701961.

Best trial: 1. Best value: 0.949534:   0%|▍                                                                                                               | 2/500 [00:16<1:05:01,  7.83s/it]

[I 2026-05-19 15:37:08,617] Trial 1 finished with value: 0.9495342489125745 and parameters: {'solver': 'saga', 'C': 0.00032532931605422073, 'l1_ratio': 0.894567137202324, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 9.520621465954567e-05, 'max_iter': 3304}. Best is trial 1 with value: 0.9495342489125745.

Best trial: 4. Best value: 0.949628:   1%|▋                                                                                                                 | 3/500 [00:17<39:14,  4.74s/it]

[I 2026-05-19 15:37:09,666] Trial 11 finished with value: 0.9495386668403649 and parameters: {'solver': 'saga', 'C': 9.56192901249424e-05, 'l1_ratio': 0.10501213107261564, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00013737744350566928, 'max_iter': 2438}. Best is trial 11 with value: 0.9495386668403649.
[I 2026-05-19 15:37:09,695] Trial 4 finished with value: 0.94962822435673 and parameters: {'solver': 'saga', 'C': 6.826032938797313e-05, 'l1_ratio': 0.5745471138109697, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00014100914617849392, 'max_iter': 2214}. Best is trial 4 with value: 0.94962822435673.

Best trial: 6. Best value: 0.949761:   1%|█▏                                                                                                                | 5/500 [00:21<27:02,  3.28s/it]

[I 2026-05-19 15:37:13,991] Trial 6 finished with value: 0.9497610242992065 and parameters: {'solver': 'saga', 'C': 0.00010096117377630029, 'l1_ratio': 0.05624519132869199, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.6234355567177434e-05, 'max_iter': 1627}. Best is trial 6 with value: 0.9497610242992065.

Best trial: 6. Best value: 0.949761:   1%|█▎                                                                                                                | 6/500 [00:25<26:59,  3.28s/it]

[I 2026-05-19 15:37:17,266] Trial 12 pruned.

Best trial: 6. Best value: 0.949761:   1%|█▌                                                                                                              | 7/500 [00:42<1:00:47,  7.40s/it]

[I 2026-05-19 15:37:34,662] Trial 7 finished with value: 0.9497449841426343 and parameters: {'solver': 'saga', 'C': 65.19180315271119, 'l1_ratio': 0.7547562777815349, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.009211486867832614, 'max_iter': 3775}. Best is trial 6 with value: 0.9497610242992065.

Best trial: 6. Best value: 0.949761:   2%|█▊                                                                                                              | 8/500 [01:03<1:33:16, 11.37s/it]

[I 2026-05-19 15:37:55,605] Trial 8 finished with value: 0.9497436544463559 and parameters: {'solver': 'saga', 'C': 2.924959498880908, 'l1_ratio': 0.548186761191295, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003323067908010715, 'max_iter': 2060}. Best is trial 6 with value: 0.9497610242992065.

Best trial: 2. Best value: 0.949901:   2%|██                                                                                                              | 9/500 [01:07<1:15:09,  9.18s/it]

[I 2026-05-19 15:37:59,572] Trial 2 finished with value: 0.949900906188898 and parameters: {'solver': 'saga', 'C': 0.5609231030074171, 'l1_ratio': 0.758359707651102, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002062456510820194, 'max_iter': 2181}. Best is trial 2 with value: 0.949900906188898.

Best trial: 2. Best value: 0.949901:   2%|██▏                                                                                                            | 10/500 [01:20<1:23:34, 10.23s/it]

[I 2026-05-19 15:38:12,276] Trial 10 finished with value: 0.9497426231080907 and parameters: {'solver': 'saga', 'C': 9.184957006532546, 'l1_ratio': 0.541346579803575, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001765641145415203, 'max_iter': 1365}. Best is trial 2 with value: 0.949900906188898.

Best trial: 17. Best value: 0.949901:   2%|██▍                                                                                                           | 11/500 [01:26<1:14:30,  9.14s/it]

[I 2026-05-19 15:38:18,858] Trial 17 finished with value: 0.9499011367701513 and parameters: {'solver': 'saga', 'C': 2.9985889011250704, 'l1_ratio': 0.734299995280379, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00186717714605378, 'max_iter': 2652}. Best is trial 17 with value: 0.9499011367701513.

Best trial: 17. Best value: 0.949901:   2%|██▋                                                                                                           | 12/500 [01:42<1:30:53, 11.18s/it]

[I 2026-05-19 15:38:34,813] Trial 19 finished with value: 0.9498987292539823 and parameters: {'solver': 'saga', 'C': 0.09448114051582665, 'l1_ratio': 0.8248699795170228, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0011133218692977401, 'max_iter': 2439}. Best is trial 17 with value: 0.9499011367701513.

Best trial: 20. Best value: 0.949909:   3%|██▊                                                                                                           | 13/500 [01:58<1:41:07, 12.46s/it]

[I 2026-05-19 15:38:50,286] Trial 20 finished with value: 0.9499094325025099 and parameters: {'solver': 'saga', 'C': 0.8519318155313447, 'l1_ratio': 0.4969144143352646, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002316486410209002, 'max_iter': 2933}. Best is trial 20 with value: 0.9499094325025099.

Best trial: 20. Best value: 0.949909:   3%|███                                                                                                           | 14/500 [02:30<2:28:35, 18.34s/it]

[I 2026-05-19 15:39:22,409] Trial 5 finished with value: 0.9497410640634513 and parameters: {'solver': 'saga', 'C': 49.697698128816775, 'l1_ratio': 0.33865047837339923, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 8.442947154455903e-05, 'max_iter': 1802}. Best is trial 20 with value: 0.9499094325025099.

Best trial: 21. Best value: 0.949912:   3%|███▎                                                                                                          | 15/500 [02:44<2:18:07, 17.09s/it]

[I 2026-05-19 15:39:36,560] Trial 21 finished with value: 0.9499115283779235 and parameters: {'solver': 'saga', 'C': 0.03976403083131597, 'l1_ratio': 0.786116313239117, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5222462717761545e-06, 'max_iter': 2704}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   3%|███▌                                                                                                          | 16/500 [02:50<1:51:13, 13.79s/it]

[I 2026-05-19 15:39:42,632] Trial 18 finished with value: 0.9497422305835856 and parameters: {'solver': 'saga', 'C': 0.4574553446367943, 'l1_ratio': 0.7513211288757883, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0001760644892129178, 'max_iter': 1014}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   3%|███▋                                                                                                          | 17/500 [02:59<1:39:44, 12.39s/it]

[I 2026-05-19 15:39:51,756] Trial 25 finished with value: 0.949896276653666 and parameters: {'solver': 'saga', 'C': 0.004690146324967312, 'l1_ratio': 0.38100629584961254, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00038533886966216806, 'max_iter': 4719}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   4%|███▉                                                                                                          | 18/500 [03:10<1:36:36, 12.03s/it]

[I 2026-05-19 15:40:02,936] Trial 24 finished with value: 0.9498910552768521 and parameters: {'solver': 'saga', 'C': 0.0037855071609561026, 'l1_ratio': 0.3562597765654001, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1268346683388586e-06, 'max_iter': 4601}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   4%|████▏                                                                                                         | 19/500 [03:12<1:10:41,  8.82s/it]

[I 2026-05-19 15:40:04,259] Trial 0 finished with value: 0.9499011558855743 and parameters: {'solver': 'saga', 'C': 1.3074189879550568, 'l1_ratio': 0.6634772889068292, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.282961590306595e-05, 'max_iter': 1339}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   4%|████▍                                                                                                           | 20/500 [03:13<51:46,  6.47s/it]

[I 2026-05-19 15:40:05,251] Trial 15 finished with value: 0.9499010356731784 and parameters: {'solver': 'saga', 'C': 31.77433065834539, 'l1_ratio': 0.003411608991624626, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.069663700473126e-05, 'max_iter': 3724}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   4%|████▋                                                                                                           | 21/500 [03:19<52:02,  6.52s/it]

[I 2026-05-19 15:40:11,877] Trial 16 finished with value: 0.9499090739730569 and parameters: {'solver': 'saga', 'C': 29.42602230636796, 'l1_ratio': 0.9197450747799728, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014764392042169384, 'max_iter': 2163}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   4%|████▊                                                                                                         | 22/500 [03:33<1:08:36,  8.61s/it]

[I 2026-05-19 15:40:25,385] Trial 3 finished with value: 0.9499010568194821 and parameters: {'solver': 'saga', 'C': 32.557596680511054, 'l1_ratio': 0.7909177327729402, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.0385494065963073e-05, 'max_iter': 2260}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   5%|█████                                                                                                         | 23/500 [03:54<1:38:17, 12.36s/it]

[I 2026-05-19 15:40:46,504] Trial 22 finished with value: 0.9499112518129407 and parameters: {'solver': 'saga', 'C': 0.09182992231782569, 'l1_ratio': 0.7488883331374311, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0964264983769671e-06, 'max_iter': 4955}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   5%|█████▎                                                                                                        | 24/500 [03:59<1:19:28, 10.02s/it]

[I 2026-05-19 15:40:51,043] Trial 27 finished with value: 0.9498890043388549 and parameters: {'solver': 'saga', 'C': 0.003693801193248781, 'l1_ratio': 0.37319057589280596, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0277703754277607e-06, 'max_iter': 4836}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   5%|█████▌                                                                                                        | 25/500 [04:01<1:01:21,  7.75s/it]

[I 2026-05-19 15:40:53,502] Trial 26 finished with value: 0.9499016800553373 and parameters: {'solver': 'saga', 'C': 0.005935147402583632, 'l1_ratio': 0.3778038406585165, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8020060467295903e-06, 'max_iter': 4720}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   5%|█████▋                                                                                                        | 26/500 [04:18<1:23:57, 10.63s/it]

[I 2026-05-19 15:41:10,845] Trial 23 finished with value: 0.9499105262915478 and parameters: {'solver': 'saga', 'C': 0.1520439123441996, 'l1_ratio': 0.7422732975068728, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5348091851886597e-06, 'max_iter': 4681}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   5%|█████▉                                                                                                        | 27/500 [04:22<1:06:31,  8.44s/it]

[I 2026-05-19 15:41:14,172] Trial 14 finished with value: 0.9499013104998383 and parameters: {'solver': 'saga', 'C': 0.41917178375213754, 'l1_ratio': 0.08464536844098636, 'class_weight': None, 'fit_intercept': False, 'tol': 2.4732992432028487e-06, 'max_iter': 2334}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   6%|██████▏                                                                                                       | 28/500 [04:33<1:13:48,  9.38s/it]

[I 2026-05-19 15:41:25,755] Trial 28 finished with value: 0.9499007439011047 and parameters: {'solver': 'saga', 'C': 0.00887297581073678, 'l1_ratio': 0.6291440104037113, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3916552184788404e-06, 'max_iter': 3025}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   6%|██████▍                                                                                                       | 29/500 [04:38<1:03:19,  8.07s/it]

[I 2026-05-19 15:41:30,756] Trial 32 finished with value: 0.949910156763392 and parameters: {'solver': 'saga', 'C': 0.03523688386016714, 'l1_ratio': 0.9890232557357446, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3555394962297932e-06, 'max_iter': 2895}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   6%|██████▋                                                                                                         | 30/500 [04:41<50:39,  6.47s/it]

[I 2026-05-19 15:41:33,494] Trial 29 finished with value: 0.9499113653962388 and parameters: {'solver': 'saga', 'C': 0.02735143118735115, 'l1_ratio': 0.6484729622827385, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5904210291787356e-06, 'max_iter': 2940}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   6%|██████▉                                                                                                         | 31/500 [04:50<56:55,  7.28s/it]

[I 2026-05-19 15:41:42,671] Trial 33 finished with value: 0.9499111493569032 and parameters: {'solver': 'saga', 'C': 0.04975118774190828, 'l1_ratio': 0.9980382879938419, 'class_weight': None, 'fit_intercept': True, 'tol': 2.7972391639998012e-06, 'max_iter': 2857}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 21. Best value: 0.949912:   6%|███████                                                                                                       | 32/500 [05:18<1:44:11, 13.36s/it]

[I 2026-05-19 15:42:10,208] Trial 41 finished with value: 0.9498560709693707 and parameters: {'solver': 'saga', 'C': 0.0010757369055917107, 'l1_ratio': 0.6868111364362811, 'class_weight': None, 'fit_intercept': True, 'tol': 4.395376064445218e-06, 'max_iter': 4251}. Best is trial 21 with value: 0.9499115283779235.

Best trial: 36. Best value: 0.949912:   7%|███████▎                                                                                                      | 33/500 [05:29<1:39:45, 12.82s/it]

[I 2026-05-19 15:42:21,763] Trial 36 finished with value: 0.949911673955001 and parameters: {'solver': 'saga', 'C': 0.047297432118612405, 'l1_ratio': 0.6694902025911793, 'class_weight': None, 'fit_intercept': True, 'tol': 4.707490524370537e-06, 'max_iter': 2885}. Best is trial 36 with value: 0.949911673955001.

Best trial: 36. Best value: 0.949912:   7%|███████▍                                                                                                      | 34/500 [05:49<1:56:17, 14.97s/it]

[I 2026-05-19 15:42:41,772] Trial 39 finished with value: 0.9499114029511547 and parameters: {'solver': 'saga', 'C': 0.05280937574951465, 'l1_ratio': 0.8627096822615118, 'class_weight': None, 'fit_intercept': True, 'tol': 4.796968625384769e-06, 'max_iter': 4213}. Best is trial 36 with value: 0.949911673955001.

Best trial: 30. Best value: 0.949912:   7%|███████▋                                                                                                      | 35/500 [05:50<1:23:00, 10.71s/it]

[I 2026-05-19 15:42:42,537] Trial 30 finished with value: 0.9499118169308176 and parameters: {'solver': 'saga', 'C': 0.04200458280861669, 'l1_ratio': 0.41909910229591824, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2701346585928522e-06, 'max_iter': 2907}. Best is trial 30 with value: 0.9499118169308176.

Best trial: 30. Best value: 0.949912:   7%|███████▉                                                                                                      | 36/500 [06:07<1:38:03, 12.68s/it]

[I 2026-05-19 15:42:59,810] Trial 40 finished with value: 0.949911760498059 and parameters: {'solver': 'saga', 'C': 0.0445969527161404, 'l1_ratio': 0.6629937067192906, 'class_weight': None, 'fit_intercept': True, 'tol': 4.5839668815576536e-06, 'max_iter': 4331}. Best is trial 30 with value: 0.9499118169308176.

Best trial: 30. Best value: 0.949912:   7%|████████▏                                                                                                     | 37/500 [06:14<1:24:52, 11.00s/it]

[I 2026-05-19 15:43:06,883] Trial 42 finished with value: 0.9499100425764603 and parameters: {'solver': 'saga', 'C': 0.020761935050969908, 'l1_ratio': 0.6473854040141506, 'class_weight': None, 'fit_intercept': True, 'tol': 4.646222226581044e-06, 'max_iter': 3433}. Best is trial 30 with value: 0.9499118169308176.

Best trial: 35. Best value: 0.949912:   8%|████████▎                                                                                                     | 38/500 [06:26<1:26:00, 11.17s/it]

[I 2026-05-19 15:43:18,452] Trial 35 finished with value: 0.949911848816764 and parameters: {'solver': 'saga', 'C': 0.040253335528797604, 'l1_ratio': 0.43776486529372477, 'class_weight': None, 'fit_intercept': True, 'tol': 3.0537954117920904e-06, 'max_iter': 2921}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:   8%|████████▌                                                                                                     | 39/500 [06:29<1:07:13,  8.75s/it]

[I 2026-05-19 15:43:21,553] Trial 38 finished with value: 0.9499117938396753 and parameters: {'solver': 'saga', 'C': 0.051645635550037504, 'l1_ratio': 0.6320450126032299, 'class_weight': None, 'fit_intercept': True, 'tol': 4.702323562846464e-06, 'max_iter': 4321}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:   8%|████████▉                                                                                                       | 40/500 [06:31<51:45,  6.75s/it]

[I 2026-05-19 15:43:23,644] Trial 43 finished with value: 0.949910948303844 and parameters: {'solver': 'saga', 'C': 0.03847587518605297, 'l1_ratio': 0.8758928940328401, 'class_weight': None, 'fit_intercept': True, 'tol': 4.572882597886049e-06, 'max_iter': 3444}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:   8%|█████████▏                                                                                                      | 41/500 [06:34<43:24,  5.68s/it]

[I 2026-05-19 15:43:26,810] Trial 13 finished with value: 0.9499091209838376 and parameters: {'solver': 'saga', 'C': 8.491914733647567, 'l1_ratio': 0.07640613319853207, 'class_weight': None, 'fit_intercept': True, 'tol': 1.966085723861374e-06, 'max_iter': 4731}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:   8%|█████████▍                                                                                                      | 42/500 [06:36<34:09,  4.48s/it]

[I 2026-05-19 15:43:28,483] Trial 44 finished with value: 0.9499064872800087 and parameters: {'solver': 'saga', 'C': 0.01966933442073987, 'l1_ratio': 0.8571365734851895, 'class_weight': None, 'fit_intercept': True, 'tol': 6.199840446309564e-06, 'max_iter': 3280}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:   9%|█████████▋                                                                                                      | 43/500 [06:37<26:43,  3.51s/it]

[I 2026-05-19 15:43:29,738] Trial 34 finished with value: 0.9499117599972002 and parameters: {'solver': 'saga', 'C': 0.04437022286088994, 'l1_ratio': 0.44984755672349686, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0638257921461238e-06, 'max_iter': 2899}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:   9%|█████████▊                                                                                                      | 44/500 [06:39<22:44,  2.99s/it]

[I 2026-05-19 15:43:31,519] Trial 37 finished with value: 0.9499117181973367 and parameters: {'solver': 'saga', 'C': 0.05169599598024388, 'l1_ratio': 0.6163734805114218, 'class_weight': None, 'fit_intercept': True, 'tol': 3.5362323067619555e-06, 'max_iter': 4289}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:   9%|██████████                                                                                                      | 45/500 [06:54<49:24,  6.52s/it]

[I 2026-05-19 15:43:46,263] Trial 46 finished with value: 0.9499053951267594 and parameters: {'solver': 'saga', 'C': 0.01761381423964461, 'l1_ratio': 0.8741423686361862, 'class_weight': None, 'fit_intercept': True, 'tol': 8.600362422637476e-06, 'max_iter': 3386}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:   9%|██████████▎                                                                                                     | 46/500 [06:56<39:00,  5.15s/it]

[I 2026-05-19 15:43:48,238] Trial 48 finished with value: 0.9498652079854428 and parameters: {'solver': 'saga', 'C': 0.0009849640507213512, 'l1_ratio': 0.46972146541598003, 'class_weight': None, 'fit_intercept': True, 'tol': 9.261208556369843e-06, 'max_iter': 3214}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:   9%|██████████▌                                                                                                     | 47/500 [06:57<30:46,  4.08s/it]

[I 2026-05-19 15:43:49,791] Trial 31 finished with value: 0.9499116890668373 and parameters: {'solver': 'saga', 'C': 0.028783152950821435, 'l1_ratio': 0.19972239597560904, 'class_weight': None, 'fit_intercept': True, 'tol': 1.755729213507128e-06, 'max_iter': 2876}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  10%|██████████▊                                                                                                     | 48/500 [07:01<28:51,  3.83s/it]

[I 2026-05-19 15:43:53,057] Trial 45 finished with value: 0.9499054030984192 and parameters: {'solver': 'saga', 'C': 0.016780027009562576, 'l1_ratio': 0.8467572013206325, 'class_weight': None, 'fit_intercept': True, 'tol': 5.980760934162871e-06, 'max_iter': 3321}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  10%|██████████▉                                                                                                     | 49/500 [07:11<44:31,  5.92s/it]

[I 2026-05-19 15:44:03,864] Trial 51 finished with value: 0.9498627004112308 and parameters: {'solver': 'saga', 'C': 0.0009506839707579964, 'l1_ratio': 0.4984205417694429, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0089595218463599e-05, 'max_iter': 3223}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  10%|███████████▏                                                                                                    | 50/500 [07:15<40:06,  5.35s/it]

[I 2026-05-19 15:44:07,867] Trial 55 finished with value: 0.9498588745444797 and parameters: {'solver': 'saga', 'C': 0.0008187500672521822, 'l1_ratio': 0.46459155543973074, 'class_weight': None, 'fit_intercept': True, 'tol': 8.578636374396177e-06, 'max_iter': 3636}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  10%|███████████▏                                                                                                  | 51/500 [07:35<1:11:44,  9.59s/it]

[I 2026-05-19 15:44:27,347] Trial 56 finished with value: 0.9498732345121004 and parameters: {'solver': 'saga', 'C': 0.001388487892978469, 'l1_ratio': 0.47159500021695194, 'class_weight': None, 'fit_intercept': True, 'tol': 3.304595637306512e-05, 'max_iter': 3735}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  10%|███████████▍                                                                                                  | 52/500 [08:26<2:43:57, 21.96s/it]

[I 2026-05-19 15:45:18,172] Trial 47 finished with value: 0.9499098707298337 and parameters: {'solver': 'saga', 'C': 0.24995016930399486, 'l1_ratio': 0.5016009132776709, 'class_weight': None, 'fit_intercept': True, 'tol': 7.424032011604447e-06, 'max_iter': 3297}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  11%|███████████▋                                                                                                  | 53/500 [08:29<2:02:00, 16.38s/it]

[I 2026-05-19 15:45:21,526] Trial 53 finished with value: 0.9499098941534893 and parameters: {'solver': 'saga', 'C': 0.22908444065397143, 'l1_ratio': 0.46742186134434793, 'class_weight': None, 'fit_intercept': True, 'tol': 3.524227308566864e-05, 'max_iter': 4440}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  11%|███████████▉                                                                                                  | 54/500 [08:41<1:52:29, 15.13s/it]

[I 2026-05-19 15:45:33,759] Trial 49 finished with value: 0.9499098094028543 and parameters: {'solver': 'saga', 'C': 0.24835118302090037, 'l1_ratio': 0.4618242129079507, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0467021568625234e-05, 'max_iter': 3202}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  11%|████████████                                                                                                  | 55/500 [08:45<1:26:47, 11.70s/it]

[I 2026-05-19 15:45:37,449] Trial 52 finished with value: 0.9499099453950375 and parameters: {'solver': 'saga', 'C': 0.21557242528262935, 'l1_ratio': 0.44278874549668773, 'class_weight': None, 'fit_intercept': True, 'tol': 9.62672146014676e-06, 'max_iter': 3263}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  11%|████████████▎                                                                                                 | 56/500 [08:46<1:02:19,  8.42s/it]

[I 2026-05-19 15:45:38,227] Trial 50 finished with value: 0.9499099410028439 and parameters: {'solver': 'saga', 'C': 0.21892745741713646, 'l1_ratio': 0.45242118305698864, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0277858847812702e-05, 'max_iter': 3306}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  11%|████████████▊                                                                                                   | 57/500 [08:48<47:38,  6.45s/it]

[I 2026-05-19 15:45:40,074] Trial 54 finished with value: 0.9499100246146244 and parameters: {'solver': 'saga', 'C': 0.19192312707149425, 'l1_ratio': 0.445018026516742, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0703674174281189e-05, 'max_iter': 4200}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  12%|████████████▉                                                                                                   | 58/500 [08:53<45:09,  6.13s/it]

[I 2026-05-19 15:45:45,454] Trial 58 finished with value: 0.9499097965519656 and parameters: {'solver': 'saga', 'C': 0.2411141383271374, 'l1_ratio': 0.4388222235100539, 'class_weight': None, 'fit_intercept': True, 'tol': 3.680482105952516e-05, 'max_iter': 3670}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  12%|█████████████▏                                                                                                  | 59/500 [08:53<32:00,  4.36s/it]

[I 2026-05-19 15:45:45,668] Trial 57 finished with value: 0.9499097923223662 and parameters: {'solver': 'saga', 'C': 0.2581961931000432, 'l1_ratio': 0.46005036750103984, 'class_weight': None, 'fit_intercept': True, 'tol': 2.848434627864209e-05, 'max_iter': 3637}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  12%|█████████████▏                                                                                                | 60/500 [10:18<3:28:40, 28.46s/it]

[I 2026-05-19 15:47:10,362] Trial 64 finished with value: 0.949910933130887 and parameters: {'solver': 'saga', 'C': 0.10079335987393698, 'l1_ratio': 0.5586331525877045, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0034595160783404e-05, 'max_iter': 3982}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  12%|█████████████▍                                                                                                | 61/500 [10:23<2:37:50, 21.57s/it]

[I 2026-05-19 15:47:15,877] Trial 59 finished with value: 0.9499016146180782 and parameters: {'solver': 'saga', 'C': 0.23356523741621124, 'l1_ratio': 0.4543885946514812, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.6902434883844282e-05, 'max_iter': 1921}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  12%|█████████████▋                                                                                                | 62/500 [10:44<2:34:25, 21.15s/it]

[I 2026-05-19 15:47:36,050] Trial 68 finished with value: 0.9497227918440005 and parameters: {'solver': 'saga', 'C': 0.009904438651881816, 'l1_ratio': 0.5864640813016254, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.929562427974772e-05, 'max_iter': 3958}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  13%|█████████████▊                                                                                                | 63/500 [10:45<1:51:39, 15.33s/it]

[I 2026-05-19 15:47:37,791] Trial 61 finished with value: 0.9499015445070962 and parameters: {'solver': 'saga', 'C': 0.2914759237013112, 'l1_ratio': 0.5830814833754454, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.8008082610501705e-05, 'max_iter': 3916}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  13%|██████████████                                                                                                | 64/500 [10:47<1:21:23, 11.20s/it]

[I 2026-05-19 15:47:39,352] Trial 69 finished with value: 0.949718337783987 and parameters: {'solver': 'saga', 'C': 0.00884814973237852, 'l1_ratio': 0.5949487925575154, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.7067506437299402e-05, 'max_iter': 3980}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  13%|██████████████▎                                                                                               | 65/500 [10:51<1:05:19,  9.01s/it]

[I 2026-05-19 15:47:43,259] Trial 60 finished with value: 0.9499015368603946 and parameters: {'solver': 'saga', 'C': 0.26484021982727907, 'l1_ratio': 0.43260286628043426, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.6611257876893603e-05, 'max_iter': 3627}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  13%|██████████████▌                                                                                               | 66/500 [11:23<1:56:17, 16.08s/it]

[I 2026-05-19 15:48:15,813] Trial 62 finished with value: 0.9499016251922235 and parameters: {'solver': 'saga', 'C': 0.2556007664773856, 'l1_ratio': 0.5960103153920944, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.7474861968149905e-05, 'max_iter': 4357}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  13%|██████████████▋                                                                                               | 67/500 [11:36<1:48:21, 15.02s/it]

[I 2026-05-19 15:48:28,364] Trial 66 finished with value: 0.9497437229388149 and parameters: {'solver': 'saga', 'C': 0.12719513428744417, 'l1_ratio': 0.6031968236070885, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 2.2064444423231463e-05, 'max_iter': 4010}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  14%|██████████████▉                                                                                               | 68/500 [11:40<1:24:39, 11.76s/it]

[I 2026-05-19 15:48:32,520] Trial 67 finished with value: 0.9497441483373766 and parameters: {'solver': 'saga', 'C': 0.08336806322051175, 'l1_ratio': 0.5807739030604583, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.8830749602873125e-05, 'max_iter': 4103}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  14%|███████████████▏                                                                                              | 69/500 [11:47<1:13:32, 10.24s/it]

[I 2026-05-19 15:48:39,214] Trial 70 finished with value: 0.949744037709085 and parameters: {'solver': 'saga', 'C': 0.10610745998089827, 'l1_ratio': 0.5989894855092648, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.8908965643839043e-05, 'max_iter': 3965}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  14%|███████████████▍                                                                                              | 70/500 [12:03<1:26:54, 12.13s/it]

[I 2026-05-19 15:48:55,743] Trial 63 finished with value: 0.9499016282832061 and parameters: {'solver': 'saga', 'C': 0.24901854076784352, 'l1_ratio': 0.588170966291897, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.023022785882621e-05, 'max_iter': 4402}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  14%|███████████████▌                                                                                              | 71/500 [12:14<1:24:32, 11.82s/it]

[I 2026-05-19 15:49:06,861] Trial 65 finished with value: 0.9499020510726156 and parameters: {'solver': 'saga', 'C': 0.10059257664554283, 'l1_ratio': 0.6004331877248659, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.996328755897816e-05, 'max_iter': 4072}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  14%|███████████████▊                                                                                              | 72/500 [12:15<1:01:17,  8.59s/it]

[I 2026-05-19 15:49:07,914] Trial 72 finished with value: 0.9497186023079405 and parameters: {'solver': 'saga', 'C': 0.009364276367158256, 'l1_ratio': 0.26596285968045896, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 3.3132458215176646e-06, 'max_iter': 2692}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  15%|████████████████                                                                                              | 73/500 [13:40<3:42:50, 31.31s/it]

[I 2026-05-19 15:50:32,247] Trial 73 finished with value: 0.9499105793181384 and parameters: {'solver': 'saga', 'C': 0.08460705564766532, 'l1_ratio': 0.24459598393652945, 'class_weight': None, 'fit_intercept': True, 'tol': 3.3042229074105317e-06, 'max_iter': 2611}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  15%|████████████████▎                                                                                             | 74/500 [13:57<3:12:25, 27.10s/it]

[I 2026-05-19 15:50:49,520] Trial 74 finished with value: 0.9499005682238252 and parameters: {'solver': 'saga', 'C': 0.07278192470962923, 'l1_ratio': 0.2344331828009089, 'class_weight': None, 'fit_intercept': False, 'tol': 3.123041854468073e-06, 'max_iter': 2574}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  15%|████████████████▌                                                                                             | 75/500 [14:03<2:26:56, 20.75s/it]

[I 2026-05-19 15:50:55,434] Trial 71 finished with value: 0.9497412426788806 and parameters: {'solver': 'saga', 'C': 1.4286625397891604, 'l1_ratio': 0.5974534030793922, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 2.9889791655496962e-06, 'max_iter': 3950}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  15%|████████████████▋                                                                                             | 76/500 [14:22<2:24:05, 20.39s/it]

[I 2026-05-19 15:51:14,993] Trial 83 finished with value: 0.9499117500788969 and parameters: {'solver': 'saga', 'C': 0.06056555133689736, 'l1_ratio': 0.6828133053772412, 'class_weight': None, 'fit_intercept': True, 'tol': 1.997429040675558e-06, 'max_iter': 3075}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  15%|████████████████▉                                                                                             | 77/500 [14:40<2:18:00, 19.58s/it]

[I 2026-05-19 15:51:32,654] Trial 86 finished with value: 0.9498719548623873 and parameters: {'solver': 'saga', 'C': 0.0022331098666661703, 'l1_ratio': 0.6908979330231639, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9919173937504558e-06, 'max_iter': 3067}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  16%|█████████████████▏                                                                                            | 78/500 [15:14<2:48:16, 23.93s/it]

[I 2026-05-19 15:52:06,748] Trial 82 finished with value: 0.9499109759104245 and parameters: {'solver': 'saga', 'C': 0.06272126966537854, 'l1_ratio': 0.2601366576770892, 'class_weight': None, 'fit_intercept': True, 'tol': 3.043542371179904e-06, 'max_iter': 2617}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  16%|█████████████████▍                                                                                            | 79/500 [15:52<3:16:27, 28.00s/it]

[I 2026-05-19 15:52:44,246] Trial 87 finished with value: 0.9499103293588769 and parameters: {'solver': 'saga', 'C': 0.02421522549466798, 'l1_ratio': 0.7114796554549321, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0008180642121147e-06, 'max_iter': 3089}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  16%|█████████████████▌                                                                                            | 80/500 [15:55<2:24:45, 20.68s/it]

[I 2026-05-19 15:52:47,849] Trial 76 finished with value: 0.9499093274125909 and parameters: {'solver': 'saga', 'C': 0.8218208636087886, 'l1_ratio': 0.2601834821794356, 'class_weight': None, 'fit_intercept': True, 'tol': 3.2887775516268405e-06, 'max_iter': 2602}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  16%|█████████████████▊                                                                                            | 81/500 [16:06<2:03:48, 17.73s/it]

[I 2026-05-19 15:52:58,696] Trial 75 finished with value: 0.9499092696643008 and parameters: {'solver': 'saga', 'C': 0.8770091130877588, 'l1_ratio': 0.23377404143696465, 'class_weight': None, 'fit_intercept': True, 'tol': 3.0165169363631026e-06, 'max_iter': 2591}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  16%|██████████████████                                                                                            | 82/500 [16:35<2:25:51, 20.94s/it]

[I 2026-05-19 15:53:27,115] Trial 78 finished with value: 0.9499092075241741 and parameters: {'solver': 'saga', 'C': 1.288043053962556, 'l1_ratio': 0.25235173587961235, 'class_weight': None, 'fit_intercept': True, 'tol': 3.191733174590812e-06, 'max_iter': 2703}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  17%|██████████████████▎                                                                                           | 83/500 [16:38<1:49:49, 15.80s/it]

[I 2026-05-19 15:53:30,936] Trial 77 finished with value: 0.9499092166337858 and parameters: {'solver': 'saga', 'C': 1.2520634711280596, 'l1_ratio': 0.23993155893682194, 'class_weight': None, 'fit_intercept': True, 'tol': 3.279984878279396e-06, 'max_iter': 2638}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  17%|██████████████████▍                                                                                           | 84/500 [16:44<1:28:42, 12.79s/it]

[I 2026-05-19 15:53:36,704] Trial 79 finished with value: 0.9499092820270283 and parameters: {'solver': 'saga', 'C': 0.9626445585149828, 'l1_ratio': 0.22688648433196767, 'class_weight': None, 'fit_intercept': True, 'tol': 3.2995967481922424e-06, 'max_iter': 2548}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  17%|██████████████████▋                                                                                           | 85/500 [16:48<1:09:29, 10.05s/it]

[I 2026-05-19 15:53:40,351] Trial 80 finished with value: 0.9499092112657449 and parameters: {'solver': 'saga', 'C': 1.6894368847463404, 'l1_ratio': 0.3090587766675002, 'class_weight': None, 'fit_intercept': True, 'tol': 3.297430798260842e-06, 'max_iter': 2574}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  17%|██████████████████▉                                                                                           | 86/500 [16:54<1:01:34,  8.92s/it]

[I 2026-05-19 15:53:46,656] Trial 81 finished with value: 0.9499093269247443 and parameters: {'solver': 'saga', 'C': 0.8500670041833791, 'l1_ratio': 0.30135331398093895, 'class_weight': None, 'fit_intercept': True, 'tol': 3.4941313997507255e-06, 'max_iter': 2628}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  17%|███████████████████▏                                                                                          | 87/500 [18:04<3:07:04, 27.18s/it]

[I 2026-05-19 15:54:56,418] Trial 88 finished with value: 0.9499114772664052 and parameters: {'solver': 'saga', 'C': 0.028223295464224744, 'l1_ratio': 0.15435620819994078, 'class_weight': None, 'fit_intercept': True, 'tol': 2.091945354229224e-06, 'max_iter': 2435}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  18%|███████████████████▎                                                                                          | 88/500 [18:05<2:12:16, 19.26s/it]

[I 2026-05-19 15:54:57,212] Trial 84 finished with value: 0.9499094933375222 and parameters: {'solver': 'saga', 'C': 0.8357482538402649, 'l1_ratio': 0.710822835527585, 'class_weight': None, 'fit_intercept': True, 'tol': 2.065870950212167e-06, 'max_iter': 3108}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  18%|███████████████████▌                                                                                          | 89/500 [18:06<1:34:41, 13.82s/it]

[I 2026-05-19 15:54:58,340] Trial 95 finished with value: 0.9499105349706418 and parameters: {'solver': 'saga', 'C': 0.02810808066903275, 'l1_ratio': 0.7819639194373968, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2800986959738188e-06, 'max_iter': 2831}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  18%|███████████████████▊                                                                                          | 90/500 [18:17<1:29:04, 13.04s/it]

[I 2026-05-19 15:55:09,546] Trial 97 finished with value: 0.9499114742093301 and parameters: {'solver': 'saga', 'C': 0.03866582343565577, 'l1_ratio': 0.7893486661059821, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2701102922509068e-06, 'max_iter': 2800}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  18%|████████████████████                                                                                          | 91/500 [18:19<1:05:22,  9.59s/it]

[I 2026-05-19 15:55:11,103] Trial 85 finished with value: 0.9499094965905467 and parameters: {'solver': 'saga', 'C': 0.779477094345715, 'l1_ratio': 0.6946381806430968, 'class_weight': None, 'fit_intercept': True, 'tol': 2.104436286421284e-06, 'max_iter': 3068}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  18%|████████████████████▌                                                                                           | 92/500 [18:20<48:55,  7.19s/it]

[I 2026-05-19 15:55:12,705] Trial 91 finished with value: 0.9499112923474033 and parameters: {'solver': 'saga', 'C': 0.014111526779910922, 'l1_ratio': 0.31245285362817177, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6228581602966585e-06, 'max_iter': 2753}. Best is trial 35 with value: 0.949911848816764.

Best trial: 35. Best value: 0.949912:  19%|████████████████████▊                                                                                           | 93/500 [18:23<40:20,  5.95s/it]

[I 2026-05-19 15:55:15,746] Trial 94 finished with value: 0.9499042629429137 and parameters: {'solver': 'saga', 'C': 0.013786254785707051, 'l1_ratio': 0.7777933090155139, 'class_weight': None, 'fit_intercept': True, 'tol': 1.248805585286882e-06, 'max_iter': 2789}. Best is trial 35 with value: 0.949911848816764.

Best trial: 92. Best value: 0.949912:  19%|█████████████████████                                                                                           | 94/500 [18:26<33:30,  4.95s/it]

[I 2026-05-19 15:55:18,376] Trial 92 finished with value: 0.9499120900579981 and parameters: {'solver': 'saga', 'C': 0.013417574631375263, 'l1_ratio': 0.1689638967957728, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1797362653268647e-06, 'max_iter': 2745}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  19%|████████████████████▉                                                                                         | 95/500 [18:56<1:23:48, 12.42s/it]

[I 2026-05-19 15:55:48,203] Trial 89 finished with value: 0.9499114281398106 and parameters: {'solver': 'saga', 'C': 0.03317621243447349, 'l1_ratio': 0.18032829589256033, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0599608799076943e-06, 'max_iter': 2809}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  19%|█████████████████████                                                                                         | 96/500 [19:27<2:01:00, 17.97s/it]

[I 2026-05-19 15:56:19,136] Trial 93 finished with value: 0.9499116850004763 and parameters: {'solver': 'saga', 'C': 0.04005652472971832, 'l1_ratio': 0.31687276920795654, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2405544737971818e-06, 'max_iter': 2811}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  19%|█████████████████████▎                                                                                        | 97/500 [19:35<1:41:19, 15.09s/it]

[I 2026-05-19 15:56:27,491] Trial 99 finished with value: 0.9499089962882954 and parameters: {'solver': 'saga', 'C': 0.01460258224832515, 'l1_ratio': 0.5234305933383782, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2123814838582344e-06, 'max_iter': 4545}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  20%|█████████████████████▌                                                                                        | 98/500 [19:42<1:24:01, 12.54s/it]

[I 2026-05-19 15:56:34,096] Trial 98 finished with value: 0.9499116972174194 and parameters: {'solver': 'saga', 'C': 0.046003871384320036, 'l1_ratio': 0.6646016742325, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3127585275478253e-06, 'max_iter': 2809}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  20%|█████████████████████▊                                                                                        | 99/500 [20:16<2:08:39, 19.25s/it]

[I 2026-05-19 15:57:09,000] Trial 101 finished with value: 0.9499106403819726 and parameters: {'solver': 'saga', 'C': 0.014385607488417716, 'l1_ratio': 0.4155229819637151, 'class_weight': None, 'fit_intercept': True, 'tol': 1.620237181653698e-06, 'max_iter': 2958}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  20%|█████████████████████▊                                                                                       | 100/500 [20:24<1:45:50, 15.88s/it]

[I 2026-05-19 15:57:17,005] Trial 102 finished with value: 0.9499118551637024 and parameters: {'solver': 'saga', 'C': 0.04595753930542648, 'l1_ratio': 0.5298583583648568, 'class_weight': None, 'fit_intercept': True, 'tol': 5.693893189912913e-06, 'max_iter': 4600}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  20%|██████████████████████                                                                                       | 101/500 [20:35<1:34:23, 14.19s/it]

[I 2026-05-19 15:57:27,274] Trial 103 finished with value: 0.9499117689409227 and parameters: {'solver': 'saga', 'C': 0.04511140520196102, 'l1_ratio': 0.4113618875102901, 'class_weight': None, 'fit_intercept': True, 'tol': 5.506865660904888e-06, 'max_iter': 4573}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  20%|██████████████████████▏                                                                                      | 102/500 [20:36<1:08:46, 10.37s/it]

[I 2026-05-19 15:57:28,703] Trial 100 finished with value: 0.9499117505629451 and parameters: {'solver': 'saga', 'C': 0.05203228170166819, 'l1_ratio': 0.5275604499386577, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5937170040662358e-06, 'max_iter': 2778}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  21%|██████████████████████▊                                                                                        | 103/500 [20:37<49:26,  7.47s/it]

[I 2026-05-19 15:57:29,430] Trial 104 finished with value: 0.9499118367817931 and parameters: {'solver': 'saga', 'C': 0.0463936265488947, 'l1_ratio': 0.5316286932690023, 'class_weight': None, 'fit_intercept': True, 'tol': 5.255623333129635e-06, 'max_iter': 2982}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  21%|███████████████████████                                                                                        | 104/500 [20:42<44:07,  6.68s/it]

[I 2026-05-19 15:57:34,276] Trial 105 finished with value: 0.9499116140743735 and parameters: {'solver': 'saga', 'C': 0.05051806161880818, 'l1_ratio': 0.4060560066154053, 'class_weight': None, 'fit_intercept': True, 'tol': 6.755994828615684e-06, 'max_iter': 2939}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  21%|███████████████████████▎                                                                                       | 105/500 [20:54<54:02,  8.21s/it]

[I 2026-05-19 15:57:46,038] Trial 96 finished with value: 0.9499112511496204 and parameters: {'solver': 'saga', 'C': 0.04146813364346445, 'l1_ratio': 0.1810051878422806, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4210732284238967e-06, 'max_iter': 2803}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  21%|███████████████████████▌                                                                                       | 106/500 [20:54<38:15,  5.83s/it]

[I 2026-05-19 15:57:46,308] Trial 90 finished with value: 0.949909474792004 and parameters: {'solver': 'saga', 'C': 0.5646830646768294, 'l1_ratio': 0.31185010803488067, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2723526024778467e-06, 'max_iter': 2409}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  21%|███████████████████████▊                                                                                       | 107/500 [20:58<35:09,  5.37s/it]

[I 2026-05-19 15:57:50,603] Trial 106 finished with value: 0.9499118231207019 and parameters: {'solver': 'saga', 'C': 0.05045590300788924, 'l1_ratio': 0.6299228244885607, 'class_weight': None, 'fit_intercept': True, 'tol': 6.0325390595827356e-06, 'max_iter': 2919}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  22%|███████████████████████▌                                                                                     | 108/500 [21:30<1:27:39, 13.42s/it]

[I 2026-05-19 15:58:22,799] Trial 110 finished with value: 0.9498898217820428 and parameters: {'solver': 'saga', 'C': 0.005887548350370557, 'l1_ratio': 0.6329517279711501, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0168232774283202e-06, 'max_iter': 2343}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  22%|███████████████████████▊                                                                                     | 109/500 [21:36<1:13:21, 11.26s/it]

[I 2026-05-19 15:58:29,016] Trial 107 finished with value: 0.9499117447072394 and parameters: {'solver': 'saga', 'C': 0.05150965745763316, 'l1_ratio': 0.5240457714848819, 'class_weight': None, 'fit_intercept': True, 'tol': 5.692667506438773e-06, 'max_iter': 2976}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  22%|████████████████████████▍                                                                                      | 110/500 [21:40<57:33,  8.86s/it]

[I 2026-05-19 15:58:32,270] Trial 113 finished with value: 0.949895694627011 and parameters: {'solver': 'saga', 'C': 0.006443287509824888, 'l1_ratio': 0.5560173097277812, 'class_weight': None, 'fit_intercept': True, 'tol': 6.276220842331648e-06, 'max_iter': 4842}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  22%|████████████████████████▏                                                                                    | 111/500 [21:55<1:09:04, 10.65s/it]

[I 2026-05-19 15:58:47,120] Trial 108 finished with value: 0.9499103499535059 and parameters: {'solver': 'saga', 'C': 0.14159008329501588, 'l1_ratio': 0.4016056449278914, 'class_weight': None, 'fit_intercept': True, 'tol': 6.6358566537220215e-06, 'max_iter': 2955}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  22%|████████████████████████▊                                                                                      | 112/500 [21:56<50:59,  7.88s/it]

[I 2026-05-19 15:58:48,543] Trial 117 finished with value: 0.9498936427122361 and parameters: {'solver': 'saga', 'C': 0.005648756760745998, 'l1_ratio': 0.5262609520405842, 'class_weight': None, 'fit_intercept': True, 'tol': 5.853125102647622e-06, 'max_iter': 4996}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  23%|████████████████████████▋                                                                                    | 113/500 [22:34<1:48:30, 16.82s/it]

[I 2026-05-19 15:59:26,217] Trial 109 finished with value: 0.9499102219327934 and parameters: {'solver': 'saga', 'C': 0.1503773610448557, 'l1_ratio': 0.40660647936557304, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0003115680039332e-06, 'max_iter': 2316}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  23%|████████████████████████▊                                                                                    | 114/500 [22:42<1:32:18, 14.35s/it]

[I 2026-05-19 15:59:34,795] Trial 111 finished with value: 0.9499103948521872 and parameters: {'solver': 'saga', 'C': 0.1562896966924389, 'l1_ratio': 0.6303028448316503, 'class_weight': None, 'fit_intercept': True, 'tol': 6.060009419209199e-06, 'max_iter': 4895}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  23%|█████████████████████████                                                                                    | 115/500 [23:02<1:41:28, 15.82s/it]

[I 2026-05-19 15:59:54,031] Trial 114 finished with value: 0.949910308309675 and parameters: {'solver': 'saga', 'C': 0.1525088081385692, 'l1_ratio': 0.5263276279753243, 'class_weight': None, 'fit_intercept': True, 'tol': 5.96994178693476e-06, 'max_iter': 4944}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  23%|█████████████████████████▎                                                                                   | 116/500 [23:03<1:13:18, 11.46s/it]

[I 2026-05-19 15:59:55,314] Trial 112 finished with value: 0.949910208593806 and parameters: {'solver': 'saga', 'C': 0.1514848404016795, 'l1_ratio': 0.40865906406620334, 'class_weight': None, 'fit_intercept': True, 'tol': 4.2028502241419296e-06, 'max_iter': 4886}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  23%|█████████████████████████▉                                                                                     | 117/500 [23:06<57:02,  8.94s/it]

[I 2026-05-19 15:59:58,377] Trial 115 finished with value: 0.9499102801683634 and parameters: {'solver': 'saga', 'C': 0.155695672147108, 'l1_ratio': 0.5317693862355516, 'class_weight': None, 'fit_intercept': True, 'tol': 5.347912727583224e-06, 'max_iter': 4941}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  24%|█████████████████████████▋                                                                                   | 118/500 [23:17<1:01:06,  9.60s/it]

[I 2026-05-19 16:00:09,515] Trial 116 finished with value: 0.9499104212033286 and parameters: {'solver': 'saga', 'C': 0.1436841828629398, 'l1_ratio': 0.5222850602177007, 'class_weight': None, 'fit_intercept': True, 'tol': 4.244186869317201e-06, 'max_iter': 4788}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  24%|██████████████████████████▍                                                                                    | 119/500 [23:18<43:42,  6.88s/it]

[I 2026-05-19 16:00:10,065] Trial 118 finished with value: 0.9499105510158831 and parameters: {'solver': 'saga', 'C': 0.1308708103178202, 'l1_ratio': 0.5379452296972324, 'class_weight': None, 'fit_intercept': True, 'tol': 5.315298103406986e-06, 'max_iter': 4925}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  24%|██████████████████████████▏                                                                                  | 120/500 [23:37<1:07:50, 10.71s/it]

[I 2026-05-19 16:00:29,709] Trial 119 finished with value: 0.9499102401519192 and parameters: {'solver': 'saga', 'C': 0.16280580104299494, 'l1_ratio': 0.5287718058582817, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2691660530089344e-05, 'max_iter': 4532}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  24%|██████████████████████████▍                                                                                  | 121/500 [24:00<1:30:01, 14.25s/it]

[I 2026-05-19 16:00:52,223] Trial 120 finished with value: 0.9499104846456881 and parameters: {'solver': 'saga', 'C': 0.13856933072455344, 'l1_ratio': 0.552195803976615, 'class_weight': None, 'fit_intercept': True, 'tol': 4.0710559606047995e-06, 'max_iter': 4603}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  24%|██████████████████████████▌                                                                                  | 122/500 [24:06<1:14:56, 11.90s/it]

[I 2026-05-19 16:00:58,618] Trial 121 finished with value: 0.9499102233964454 and parameters: {'solver': 'saga', 'C': 0.14277542190531828, 'l1_ratio': 0.3467536390046843, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2483385872337174e-05, 'max_iter': 4946}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  25%|██████████████████████████▊                                                                                  | 123/500 [24:15<1:10:00, 11.14s/it]

[I 2026-05-19 16:01:08,003] Trial 122 finished with value: 0.9499112703518897 and parameters: {'solver': 'saga', 'C': 0.0682554555599485, 'l1_ratio': 0.48925617271501726, 'class_weight': None, 'fit_intercept': True, 'tol': 4.137595087488446e-06, 'max_iter': 4856}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  25%|███████████████████████████▌                                                                                   | 124/500 [24:16<49:48,  7.95s/it]

[I 2026-05-19 16:01:08,486] Trial 123 finished with value: 0.9499113398125288 and parameters: {'solver': 'saga', 'C': 0.0651280790077515, 'l1_ratio': 0.48342221210767733, 'class_weight': None, 'fit_intercept': True, 'tol': 4.165822966043488e-06, 'max_iter': 4607}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  25%|███████████████████████████▊                                                                                   | 125/500 [24:23<47:36,  7.62s/it]

[I 2026-05-19 16:01:15,346] Trial 125 finished with value: 0.9499117226166807 and parameters: {'solver': 'saga', 'C': 0.02169345743969859, 'l1_ratio': 0.49186474346018194, 'class_weight': None, 'fit_intercept': True, 'tol': 4.083180360960442e-06, 'max_iter': 4544}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  25%|███████████████████████████▍                                                                                 | 126/500 [24:44<1:13:01, 11.72s/it]

[I 2026-05-19 16:01:36,623] Trial 129 finished with value: 0.9499102539800333 and parameters: {'solver': 'saga', 'C': 0.06863888546335663, 'l1_ratio': 0.019944313935180646, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004192559996932333, 'max_iter': 4561}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  25%|███████████████████████████▋                                                                                 | 127/500 [25:00<1:20:44, 12.99s/it]

[I 2026-05-19 16:01:52,583] Trial 127 finished with value: 0.9499113269611641 and parameters: {'solver': 'saga', 'C': 0.06649762767475775, 'l1_ratio': 0.49190202804081773, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3841082006833707e-05, 'max_iter': 4556}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  26%|███████████████████████████▉                                                                                 | 128/500 [25:15<1:23:33, 13.48s/it]

[I 2026-05-19 16:02:07,141] Trial 134 finished with value: 0.9499113093740255 and parameters: {'solver': 'saga', 'C': 0.0215520080079523, 'l1_ratio': 0.002526476127674926, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002536166628102665, 'max_iter': 3007}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  26%|████████████████████████████                                                                                 | 129/500 [25:16<1:01:01,  9.87s/it]

[I 2026-05-19 16:02:08,646] Trial 130 finished with value: 0.949911348418477 and parameters: {'solver': 'saga', 'C': 0.02173281381829607, 'l1_ratio': 0.024800820386141398, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3727993078154414e-05, 'max_iter': 1623}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  26%|████████████████████████████▎                                                                                | 130/500 [25:39<1:25:02, 13.79s/it]

[I 2026-05-19 16:02:31,589] Trial 135 finished with value: 0.949909861525932 and parameters: {'solver': 'saga', 'C': 0.020056435309445307, 'l1_ratio': 0.6522113903444522, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5998499777546047e-06, 'max_iter': 3179}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  26%|████████████████████████████▌                                                                                | 131/500 [25:57<1:32:04, 14.97s/it]

[I 2026-05-19 16:02:49,309] Trial 124 finished with value: 0.9499101926523335 and parameters: {'solver': 'saga', 'C': 0.07286690114174249, 'l1_ratio': 0.0028969614267426724, 'class_weight': None, 'fit_intercept': True, 'tol': 1.321922794029766e-05, 'max_iter': 1562}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  26%|████████████████████████████▊                                                                                | 132/500 [25:58<1:07:05, 10.94s/it]

[I 2026-05-19 16:02:50,847] Trial 131 finished with value: 0.9499113712078374 and parameters: {'solver': 'saga', 'C': 0.06459148493800757, 'l1_ratio': 0.4869781100849598, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5590438982955376e-06, 'max_iter': 3145}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  27%|█████████████████████████████▌                                                                                 | 133/500 [25:59<47:39,  7.79s/it]

[I 2026-05-19 16:02:51,293] Trial 126 finished with value: 0.9499110770938557 and parameters: {'solver': 'saga', 'C': 0.06848043891489433, 'l1_ratio': 0.34686747628564035, 'class_weight': None, 'fit_intercept': True, 'tol': 4.269285705102161e-06, 'max_iter': 4533}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  27%|█████████████████████████████▋                                                                                 | 134/500 [26:05<43:54,  7.20s/it]

[I 2026-05-19 16:02:57,105] Trial 132 finished with value: 0.9499112477410669 and parameters: {'solver': 'saga', 'C': 0.06969944313068249, 'l1_ratio': 0.5043441189042085, 'class_weight': None, 'fit_intercept': True, 'tol': 7.905720999890526e-06, 'max_iter': 3148}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  27%|█████████████████████████████▉                                                                                 | 135/500 [26:07<34:15,  5.63s/it]

[I 2026-05-19 16:02:59,086] Trial 137 finished with value: 0.9499098766541174 and parameters: {'solver': 'saga', 'C': 0.020098714308071367, 'l1_ratio': 0.6498233183941944, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5716103283167537e-06, 'max_iter': 3153}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  27%|██████████████████████████████▏                                                                                | 136/500 [26:16<40:57,  6.75s/it]

[I 2026-05-19 16:03:08,441] Trial 139 finished with value: 0.9499115015433144 and parameters: {'solver': 'saga', 'C': 0.030022244664268595, 'l1_ratio': 0.6558139415422499, 'class_weight': None, 'fit_intercept': True, 'tol': 6.628953376937919e-05, 'max_iter': 2149}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  27%|██████████████████████████████▍                                                                                | 137/500 [26:23<41:12,  6.81s/it]

[I 2026-05-19 16:03:15,398] Trial 136 finished with value: 0.9499120101963578 and parameters: {'solver': 'saga', 'C': 0.023286874189011094, 'l1_ratio': 0.3679142933828412, 'class_weight': None, 'fit_intercept': True, 'tol': 7.608011122306898e-06, 'max_iter': 3161}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  28%|██████████████████████████████▋                                                                                | 138/500 [26:29<39:17,  6.51s/it]

[I 2026-05-19 16:03:21,208] Trial 138 finished with value: 0.9499115402625977 and parameters: {'solver': 'saga', 'C': 0.02849735255653787, 'l1_ratio': 0.6448203597024011, 'class_weight': None, 'fit_intercept': True, 'tol': 2.483356249235359e-06, 'max_iter': 3014}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  28%|██████████████████████████████▊                                                                                | 139/500 [26:33<34:36,  5.75s/it]

[I 2026-05-19 16:03:25,188] Trial 133 finished with value: 0.9499113555916516 and parameters: {'solver': 'saga', 'C': 0.06524347601463565, 'l1_ratio': 0.49208113823594357, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5677931939248054e-06, 'max_iter': 3157}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  28%|██████████████████████████████▌                                                                              | 140/500 [27:03<1:19:36, 13.27s/it]

[I 2026-05-19 16:03:55,994] Trial 128 finished with value: 0.9499102090818837 and parameters: {'solver': 'saga', 'C': 0.07328480559634817, 'l1_ratio': 0.00426039552600771, 'class_weight': None, 'fit_intercept': True, 'tol': 4.2573209285188335e-06, 'max_iter': 4545}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  28%|██████████████████████████████▋                                                                              | 141/500 [27:08<1:03:34, 10.62s/it]

[I 2026-05-19 16:04:00,451] Trial 141 finished with value: 0.9499120655106543 and parameters: {'solver': 'saga', 'C': 0.03174584025051887, 'l1_ratio': 0.5660502321705143, 'class_weight': None, 'fit_intercept': True, 'tol': 7.293095073402507e-06, 'max_iter': 4444}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  28%|██████████████████████████████▉                                                                              | 142/500 [27:31<1:25:48, 14.38s/it]

[I 2026-05-19 16:04:23,596] Trial 143 finished with value: 0.9499119467580769 and parameters: {'solver': 'saga', 'C': 0.035404248923075, 'l1_ratio': 0.5683901126239852, 'class_weight': None, 'fit_intercept': True, 'tol': 8.289205967771855e-06, 'max_iter': 4309}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  29%|███████████████████████████████▏                                                                             | 143/500 [27:33<1:03:18, 10.64s/it]

[I 2026-05-19 16:04:25,506] Trial 145 finished with value: 0.9499120492333871 and parameters: {'solver': 'saga', 'C': 0.031077443553162457, 'l1_ratio': 0.4263416137988032, 'class_weight': None, 'fit_intercept': True, 'tol': 6.026389939994088e-05, 'max_iter': 4314}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  29%|███████████████████████████████▍                                                                             | 144/500 [27:45<1:05:02, 10.96s/it]

[I 2026-05-19 16:04:37,226] Trial 140 finished with value: 0.9499119556933835 and parameters: {'solver': 'saga', 'C': 0.03094607040026019, 'l1_ratio': 0.3680266715174655, 'class_weight': None, 'fit_intercept': True, 'tol': 2.543096492087499e-06, 'max_iter': 3164}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  29%|████████████████████████████████▏                                                                              | 145/500 [27:49<52:14,  8.83s/it]

[I 2026-05-19 16:04:41,073] Trial 153 finished with value: 0.9499055216660791 and parameters: {'solver': 'saga', 'C': 0.0122484691786602, 'l1_ratio': 0.5635319814311242, 'class_weight': None, 'fit_intercept': True, 'tol': 0.004559874338403435, 'max_iter': 4428}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  29%|████████████████████████████████▍                                                                              | 146/500 [27:50<38:38,  6.55s/it]

[I 2026-05-19 16:04:42,309] Trial 146 finished with value: 0.9499120160602207 and parameters: {'solver': 'saga', 'C': 0.030975685618287573, 'l1_ratio': 0.5658739471121641, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6319553483020052e-06, 'max_iter': 4431}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  29%|████████████████████████████████▋                                                                              | 147/500 [27:54<35:14,  5.99s/it]

[I 2026-05-19 16:04:46,991] Trial 148 finished with value: 0.9499086026160445 and parameters: {'solver': 'saga', 'C': 0.010597797637420341, 'l1_ratio': 0.3679880205526849, 'class_weight': None, 'fit_intercept': True, 'tol': 8.134872370186216e-06, 'max_iter': 4332}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  30%|████████████████████████████████▊                                                                              | 148/500 [28:02<38:20,  6.54s/it]

[I 2026-05-19 16:04:54,802] Trial 142 finished with value: 0.9499120728192807 and parameters: {'solver': 'saga', 'C': 0.028275450949842296, 'l1_ratio': 0.37523621913451727, 'class_weight': None, 'fit_intercept': True, 'tol': 7.784151801110026e-06, 'max_iter': 4216}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  30%|█████████████████████████████████                                                                              | 149/500 [28:03<27:47,  4.75s/it]

[I 2026-05-19 16:04:55,382] Trial 147 finished with value: 0.9499088612624732 and parameters: {'solver': 'saga', 'C': 0.011027856047405677, 'l1_ratio': 0.37551406570110263, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6325459075223104e-06, 'max_iter': 4325}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  30%|█████████████████████████████████▎                                                                             | 150/500 [28:09<30:00,  5.14s/it]

[I 2026-05-19 16:05:01,444] Trial 150 finished with value: 0.9499059460718364 and parameters: {'solver': 'saga', 'C': 0.009342399626512855, 'l1_ratio': 0.4276514082726053, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5866195511959836e-06, 'max_iter': 3480}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  30%|█████████████████████████████████▌                                                                             | 151/500 [28:23<45:27,  7.82s/it]

[I 2026-05-19 16:05:15,485] Trial 152 finished with value: 0.9499056671009194 and parameters: {'solver': 'saga', 'C': 0.011650024923757581, 'l1_ratio': 0.5692367937480314, 'class_weight': None, 'fit_intercept': True, 'tol': 8.456342320494223e-06, 'max_iter': 4334}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  30%|█████████████████████████████████▋                                                                             | 152/500 [28:26<36:56,  6.37s/it]

[I 2026-05-19 16:05:18,496] Trial 144 finished with value: 0.9499120352396424 and parameters: {'solver': 'saga', 'C': 0.02961528287950262, 'l1_ratio': 0.37054287968150634, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7214354221716503e-06, 'max_iter': 4329}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  31%|█████████████████████████████████▉                                                                             | 153/500 [28:28<29:44,  5.14s/it]

[I 2026-05-19 16:05:20,771] Trial 161 finished with value: 0.9494029327325688 and parameters: {'solver': 'saga', 'C': 4.297634831170697e-05, 'l1_ratio': 0.38958047950010294, 'class_weight': None, 'fit_intercept': True, 'tol': 7.293663909487687e-06, 'max_iter': 4155}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  31%|██████████████████████████████████▏                                                                            | 154/500 [28:50<59:11, 10.27s/it]

[I 2026-05-19 16:05:42,970] Trial 154 finished with value: 0.9499060200960991 and parameters: {'solver': 'saga', 'C': 0.012225357439178733, 'l1_ratio': 0.5698409660282768, 'class_weight': None, 'fit_intercept': True, 'tol': 7.842895143437124e-06, 'max_iter': 4412}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  31%|██████████████████████████████████▍                                                                            | 155/500 [28:55<48:23,  8.42s/it]

[I 2026-05-19 16:05:47,088] Trial 151 finished with value: 0.949909643539946 and parameters: {'solver': 'saga', 'C': 0.011964951024070414, 'l1_ratio': 0.3784168279948284, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7045414501738213e-06, 'max_iter': 3521}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  31%|██████████████████████████████████▋                                                                            | 156/500 [29:09<57:48, 10.08s/it]

[I 2026-05-19 16:06:01,046] Trial 149 finished with value: 0.9499116064279309 and parameters: {'solver': 'saga', 'C': 0.04842395090943515, 'l1_ratio': 0.3780047918899183, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6906967802352136e-06, 'max_iter': 4314}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  31%|██████████████████████████████████▊                                                                            | 157/500 [29:17<55:34,  9.72s/it]

[I 2026-05-19 16:06:09,932] Trial 155 finished with value: 0.949908764148747 and parameters: {'solver': 'saga', 'C': 0.011083587103613339, 'l1_ratio': 0.38503974004838654, 'class_weight': None, 'fit_intercept': True, 'tol': 7.655995353882383e-06, 'max_iter': 4357}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  32%|██████████████████████████████████▍                                                                          | 158/500 [29:44<1:25:03, 14.92s/it]

[I 2026-05-19 16:06:37,001] Trial 156 finished with value: 0.9499119278792127 and parameters: {'solver': 'saga', 'C': 0.033499600907406925, 'l1_ratio': 0.431165525545416, 'class_weight': None, 'fit_intercept': True, 'tol': 9.805927708411051e-06, 'max_iter': 4334}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  32%|██████████████████████████████████▋                                                                          | 159/500 [29:53<1:13:57, 13.01s/it]

[I 2026-05-19 16:06:45,545] Trial 158 finished with value: 0.9499119734276498 and parameters: {'solver': 'saga', 'C': 0.03298567016053576, 'l1_ratio': 0.42884017248430417, 'class_weight': None, 'fit_intercept': True, 'tol': 7.610632157596585e-06, 'max_iter': 4170}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  32%|███████████████████████████████████▌                                                                           | 160/500 [29:57<58:47, 10.37s/it]

[I 2026-05-19 16:06:49,739] Trial 157 finished with value: 0.9499118984334437 and parameters: {'solver': 'saga', 'C': 0.03250550242089539, 'l1_ratio': 0.39101148081274956, 'class_weight': None, 'fit_intercept': True, 'tol': 7.299211899403274e-06, 'max_iter': 4331}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  32%|███████████████████████████████████▋                                                                           | 161/500 [30:02<49:41,  8.79s/it]

[I 2026-05-19 16:06:54,876] Trial 160 finished with value: 0.9499118468664058 and parameters: {'solver': 'saga', 'C': 0.03576246666245891, 'l1_ratio': 0.428812751564805, 'class_weight': None, 'fit_intercept': True, 'tol': 7.995705837962428e-06, 'max_iter': 4249}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  32%|███████████████████████████████████▉                                                                           | 162/500 [30:06<41:13,  7.32s/it]

[I 2026-05-19 16:06:58,757] Trial 159 finished with value: 0.9499119140477198 and parameters: {'solver': 'saga', 'C': 0.03472405382225822, 'l1_ratio': 0.38514250379787907, 'class_weight': None, 'fit_intercept': True, 'tol': 7.436959569498758e-06, 'max_iter': 4172}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  33%|███████████████████████████████████▌                                                                         | 163/500 [30:30<1:08:45, 12.24s/it]

[I 2026-05-19 16:07:22,484] Trial 163 finished with value: 0.9499120681029751 and parameters: {'solver': 'saga', 'C': 0.02853176530977409, 'l1_ratio': 0.38549961912353325, 'class_weight': None, 'fit_intercept': True, 'tol': 7.3034370288422755e-06, 'max_iter': 4160}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  33%|████████████████████████████████████▍                                                                          | 164/500 [30:31<49:29,  8.84s/it]

[I 2026-05-19 16:07:23,380] Trial 167 finished with value: 0.9499111272470436 and parameters: {'solver': 'saga', 'C': 0.017238859384624904, 'l1_ratio': 0.4383876343690314, 'class_weight': None, 'fit_intercept': True, 'tol': 4.209054824168215e-05, 'max_iter': 4235}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  33%|████████████████████████████████████▋                                                                          | 165/500 [30:40<49:05,  8.79s/it]

[I 2026-05-19 16:07:32,063] Trial 164 finished with value: 0.9499118974524411 and parameters: {'solver': 'saga', 'C': 0.03613726335250639, 'l1_ratio': 0.3629704583073573, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1132271560321977e-05, 'max_iter': 4251}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  33%|████████████████████████████████████▊                                                                          | 166/500 [30:43<39:12,  7.04s/it]

[I 2026-05-19 16:07:35,028] Trial 165 finished with value: 0.9499118299417406 and parameters: {'solver': 'saga', 'C': 0.03675707169437321, 'l1_ratio': 0.3346115532196296, 'class_weight': None, 'fit_intercept': True, 'tol': 4.4186980782288386e-05, 'max_iter': 4201}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  33%|████████████████████████████████████▍                                                                        | 167/500 [31:05<1:04:41, 11.66s/it]

[I 2026-05-19 16:07:57,451] Trial 170 finished with value: 0.949900193418679 and parameters: {'solver': 'saga', 'C': 0.03179014847342218, 'l1_ratio': 0.11769640512926871, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0001823705708562009, 'max_iter': 4225}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  34%|█████████████████████████████████████▎                                                                         | 168/500 [31:07<48:54,  8.84s/it]

[I 2026-05-19 16:07:59,710] Trial 169 finished with value: 0.9499119070717116 and parameters: {'solver': 'saga', 'C': 0.032992211912711726, 'l1_ratio': 0.6125387935650907, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0110190267971722e-05, 'max_iter': 4210}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  34%|████████████████████████████████████▊                                                                        | 169/500 [31:24<1:01:28, 11.14s/it]

[I 2026-05-19 16:08:16,230] Trial 162 finished with value: 0.9499111504557778 and parameters: {'solver': 'saga', 'C': 0.0339127484910944, 'l1_ratio': 0.12922472793136275, 'class_weight': None, 'fit_intercept': True, 'tol': 7.0780884663884674e-06, 'max_iter': 4228}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  34%|█████████████████████████████████████                                                                        | 170/500 [31:40<1:09:12, 12.58s/it]

[I 2026-05-19 16:08:32,172] Trial 166 finished with value: 0.9499111106015785 and parameters: {'solver': 'saga', 'C': 0.0328913331292143, 'l1_ratio': 0.12078405777235318, 'class_weight': None, 'fit_intercept': True, 'tol': 9.771148091767682e-06, 'max_iter': 4219}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  34%|██████████████████████████████████████▏                                                                        | 172/500 [31:46<41:22,  7.57s/it]

[I 2026-05-19 16:08:38,645] Trial 177 finished with value: 0.9498978739347466 and parameters: {'solver': 'saga', 'C': 0.025726319879017554, 'l1_ratio': 0.3362376076944875, 'class_weight': None, 'fit_intercept': False, 'tol': 9.965763813149987e-06, 'max_iter': 3823}. Best is trial 92 with value: 0.9499120900579981.
[I 2026-05-19 16:08:38,793] Trial 168 finished with value: 0.9499117490944944 and parameters: {'solver': 'saga', 'C': 0.03826416051695924, 'l1_ratio': 0.3286120649639142, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0038496765842327e-05, 'max_iter': 4210}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  35%|██████████████████████████████████████▍                                                                        | 173/500 [31:49<33:37,  6.17s/it]

[I 2026-05-19 16:08:41,677] Trial 176 finished with value: 0.9498980971181344 and parameters: {'solver': 'saga', 'C': 0.029848653082581958, 'l1_ratio': 0.3323038401287275, 'class_weight': None, 'fit_intercept': False, 'tol': 1.1229025700569469e-05, 'max_iter': 4458}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  35%|██████████████████████████████████████▋                                                                        | 174/500 [31:57<36:12,  6.66s/it]

[I 2026-05-19 16:08:49,515] Trial 173 finished with value: 0.9499120559032062 and parameters: {'solver': 'saga', 'C': 0.03155156930843676, 'l1_ratio': 0.43256066894205153, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0922132536852092e-05, 'max_iter': 4212}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  35%|██████████████████████████████████████▊                                                                        | 175/500 [31:58<26:24,  4.88s/it]

[I 2026-05-19 16:08:50,219] Trial 172 finished with value: 0.9499118777755047 and parameters: {'solver': 'saga', 'C': 0.03455556946529034, 'l1_ratio': 0.4358835729739758, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0439101214169529e-05, 'max_iter': 4223}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  35%|███████████████████████████████████████                                                                        | 176/500 [32:19<52:41,  9.76s/it]

[I 2026-05-19 16:09:11,366] Trial 171 finished with value: 0.9499120775341734 and parameters: {'solver': 'saga', 'C': 0.028075689314996176, 'l1_ratio': 0.35839677393010927, 'class_weight': None, 'fit_intercept': True, 'tol': 9.715258639944801e-06, 'max_iter': 4205}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  35%|███████████████████████████████████████▎                                                                       | 177/500 [32:28<52:20,  9.72s/it]

[I 2026-05-19 16:09:21,016] Trial 174 finished with value: 0.9499120749351369 and parameters: {'solver': 'saga', 'C': 0.032024813659425576, 'l1_ratio': 0.4356336382697033, 'class_weight': None, 'fit_intercept': True, 'tol': 1.04652344521909e-05, 'max_iter': 4203}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  36%|██████████████████████████████████████▊                                                                      | 178/500 [32:49<1:10:20, 13.11s/it]

[I 2026-05-19 16:09:42,017] Trial 175 finished with value: 0.9499118938753466 and parameters: {'solver': 'saga', 'C': 0.031463778181620945, 'l1_ratio': 0.3415792516472068, 'class_weight': None, 'fit_intercept': True, 'tol': 9.917661696769087e-06, 'max_iter': 4108}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  36%|███████████████████████████████████████                                                                      | 179/500 [33:16<1:30:58, 17.00s/it]

[I 2026-05-19 16:10:08,112] Trial 179 finished with value: 0.9499120575266403 and parameters: {'solver': 'saga', 'C': 0.024461773858265815, 'l1_ratio': 0.3376063000059665, 'class_weight': None, 'fit_intercept': True, 'tol': 1.165196016422662e-05, 'max_iter': 4092}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  36%|███████████████████████████████████████▏                                                                     | 180/500 [33:20<1:10:07, 13.15s/it]

[I 2026-05-19 16:10:12,266] Trial 178 finished with value: 0.9499120840409778 and parameters: {'solver': 'saga', 'C': 0.028024544022329585, 'l1_ratio': 0.3593899040515913, 'class_weight': None, 'fit_intercept': True, 'tol': 9.816119223462719e-06, 'max_iter': 3855}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  36%|███████████████████████████████████████▍                                                                     | 181/500 [33:28<1:01:27, 11.56s/it]

[I 2026-05-19 16:10:20,112] Trial 180 finished with value: 0.9499119700190193 and parameters: {'solver': 'saga', 'C': 0.021333875857794272, 'l1_ratio': 0.3564312415713223, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0242178595011919e-05, 'max_iter': 4079}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  36%|████████████████████████████████████████▍                                                                      | 182/500 [33:37<57:28, 10.84s/it]

[I 2026-05-19 16:10:29,290] Trial 184 finished with value: 0.9499118746958619 and parameters: {'solver': 'saga', 'C': 0.019957341697282926, 'l1_ratio': 0.35986726403099556, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5407401584952195e-05, 'max_iter': 4078}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  37%|████████████████████████████████████████▋                                                                      | 183/500 [33:39<43:38,  8.26s/it]

[I 2026-05-19 16:10:31,520] Trial 182 finished with value: 0.9499117466793608 and parameters: {'solver': 'saga', 'C': 0.01803182289425209, 'l1_ratio': 0.3599255317024363, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0057307598246457e-05, 'max_iter': 4455}. Best is trial 92 with value: 0.9499120900579981.
[I 2026-05-19 16:10:31,533] Trial 181 finished with value: 0.9499120113307912 and parameters: {'solver': 'saga', 'C': 0.024713546807623644, 'l1_ratio': 0.36282762358069287, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0828659642047311e-05, 'max_iter': 3862}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  37%|█████████████████████████████████████████                                                                      | 185/500 [34:03<52:19,  9.97s/it]

[I 2026-05-19 16:10:55,443] Trial 187 finished with value: 0.9499118691662407 and parameters: {'solver': 'saga', 'C': 0.01975499577241419, 'l1_ratio': 0.36486361824424596, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6216709111769302e-05, 'max_iter': 4084}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  37%|█████████████████████████████████████████▎                                                                     | 186/500 [34:04<40:25,  7.72s/it]

[I 2026-05-19 16:10:56,346] Trial 186 finished with value: 0.9499119203943014 and parameters: {'solver': 'saga', 'C': 0.020881830657099636, 'l1_ratio': 0.28694260723806303, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6030720734844203e-05, 'max_iter': 4090}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  37%|█████████████████████████████████████████▌                                                                     | 187/500 [34:08<35:34,  6.82s/it]

[I 2026-05-19 16:11:00,621] Trial 183 finished with value: 0.949912025316722 and parameters: {'solver': 'saga', 'C': 0.024927124965797548, 'l1_ratio': 0.28839303206304395, 'class_weight': None, 'fit_intercept': True, 'tol': 9.956764363327536e-06, 'max_iter': 4041}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  38%|█████████████████████████████████████████▋                                                                     | 188/500 [34:16<36:37,  7.04s/it]

[I 2026-05-19 16:11:08,264] Trial 185 finished with value: 0.949911814339686 and parameters: {'solver': 'saga', 'C': 0.0181626971467103, 'l1_ratio': 0.2884774508395686, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1696700577123763e-05, 'max_iter': 4681}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  38%|█████████████████████████████████████████▉                                                                     | 189/500 [34:17<28:19,  5.47s/it]

[I 2026-05-19 16:11:09,670] Trial 188 finished with value: 0.9499115557057867 and parameters: {'solver': 'saga', 'C': 0.017499121228804548, 'l1_ratio': 0.35984487819287647, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5065374270827694e-05, 'max_iter': 4099}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  38%|██████████████████████████████████████████▏                                                                    | 190/500 [34:24<30:51,  5.97s/it]

[I 2026-05-19 16:11:16,912] Trial 189 finished with value: 0.9499118198735397 and parameters: {'solver': 'saga', 'C': 0.016483612020895568, 'l1_ratio': 0.2850298096600029, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010125876099188317, 'max_iter': 4056}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  38%|█████████████████████████████████████████▋                                                                   | 191/500 [35:05<1:22:58, 16.11s/it]

[I 2026-05-19 16:11:57,873] Trial 192 finished with value: 0.9499115313063184 and parameters: {'solver': 'saga', 'C': 0.017496251802746703, 'l1_ratio': 0.36766115955876605, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4683239308183988e-05, 'max_iter': 4086}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  38%|█████████████████████████████████████████▊                                                                   | 192/500 [35:08<1:03:12, 12.31s/it]

[I 2026-05-19 16:12:01,015] Trial 191 finished with value: 0.9499118841313343 and parameters: {'solver': 'saga', 'C': 0.019834575202357985, 'l1_ratio': 0.3623289650354591, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5308671702643234e-05, 'max_iter': 4051}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  39%|██████████████████████████████████████████▊                                                                    | 193/500 [35:17<56:44, 11.09s/it]

[I 2026-05-19 16:12:09,178] Trial 200 finished with value: 0.9499043579253238 and parameters: {'solver': 'saga', 'C': 0.007264565398171677, 'l1_ratio': 0.39984741195715723, 'class_weight': None, 'fit_intercept': True, 'tol': 2.2230670788676733e-05, 'max_iter': 3860}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  39%|███████████████████████████████████████████                                                                    | 194/500 [35:19<43:05,  8.45s/it]

[I 2026-05-19 16:12:11,356] Trial 201 finished with value: 0.9499044051004759 and parameters: {'solver': 'saga', 'C': 0.007434964965554992, 'l1_ratio': 0.40726242882930913, 'class_weight': None, 'fit_intercept': True, 'tol': 2.353613610357266e-05, 'max_iter': 3894}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  39%|███████████████████████████████████████████▎                                                                   | 195/500 [35:26<40:58,  8.06s/it]

[I 2026-05-19 16:12:18,499] Trial 190 finished with value: 0.9499117297558779 and parameters: {'solver': 'saga', 'C': 0.016474729637523475, 'l1_ratio': 0.29797228546687965, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4588619962905318e-05, 'max_iter': 4085}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  39%|███████████████████████████████████████████▌                                                                   | 196/500 [35:37<44:57,  8.87s/it]

[I 2026-05-19 16:12:29,285] Trial 198 finished with value: 0.9499075407052091 and parameters: {'solver': 'saga', 'C': 0.008306569913981458, 'l1_ratio': 0.2958039917325162, 'class_weight': None, 'fit_intercept': True, 'tol': 2.3823505029939576e-05, 'max_iter': 3876}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  39%|███████████████████████████████████████████▋                                                                   | 197/500 [35:38<33:56,  6.72s/it]

[I 2026-05-19 16:12:30,958] Trial 195 finished with value: 0.9499115682286249 and parameters: {'solver': 'saga', 'C': 0.015086089847873883, 'l1_ratio': 0.29358137688127334, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5171236588961787e-05, 'max_iter': 3857}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  40%|███████████████████████████████████████████▉                                                                   | 198/500 [35:42<28:32,  5.67s/it]

[I 2026-05-19 16:12:34,162] Trial 197 finished with value: 0.9499111412342895 and parameters: {'solver': 'saga', 'C': 0.016288467405598913, 'l1_ratio': 0.40224217055276595, 'class_weight': None, 'fit_intercept': True, 'tol': 1.252912606934236e-05, 'max_iter': 3888}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  40%|████████████████████████████████████████████▏                                                                  | 199/500 [35:45<25:36,  5.11s/it]

[I 2026-05-19 16:12:37,946] Trial 199 finished with value: 0.9499113520503887 and parameters: {'solver': 'saga', 'C': 0.016752810376140854, 'l1_ratio': 0.39514997787137074, 'class_weight': None, 'fit_intercept': True, 'tol': 2.371992837285468e-05, 'max_iter': 3830}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  40%|████████████████████████████████████████████▍                                                                  | 200/500 [35:48<21:30,  4.30s/it]

[I 2026-05-19 16:12:40,365] Trial 193 finished with value: 0.9499118171072144 and parameters: {'solver': 'saga', 'C': 0.01745705566413809, 'l1_ratio': 0.2947287327914117, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4743794268046173e-05, 'max_iter': 4069}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  40%|████████████████████████████████████████████▌                                                                  | 201/500 [35:53<22:07,  4.44s/it]

[I 2026-05-19 16:12:45,131] Trial 194 finished with value: 0.9499116515125159 and parameters: {'solver': 'saga', 'C': 0.015809283682628107, 'l1_ratio': 0.2937564710284205, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4676428842090775e-05, 'max_iter': 4081}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  40%|████████████████████████████████████████████▊                                                                  | 202/500 [36:11<42:58,  8.65s/it]

[I 2026-05-19 16:13:03,630] Trial 196 finished with value: 0.9499117705851688 and parameters: {'solver': 'saga', 'C': 0.016793329451323644, 'l1_ratio': 0.2990706592407072, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2510385631896603e-05, 'max_iter': 3867}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  41%|████████████████████████████████████████████▎                                                                | 203/500 [36:37<1:08:56, 13.93s/it]

[I 2026-05-19 16:13:29,862] Trial 207 finished with value: 0.9498945235556981 and parameters: {'solver': 'saga', 'C': 0.0038734065277703333, 'l1_ratio': 0.3187641175547563, 'class_weight': None, 'fit_intercept': True, 'tol': 1.228960701546341e-05, 'max_iter': 3988}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  41%|████████████████████████████████████████████▍                                                                | 204/500 [36:52<1:10:08, 14.22s/it]

[I 2026-05-19 16:13:44,758] Trial 203 finished with value: 0.949911979453883 and parameters: {'solver': 'saga', 'C': 0.024955345401221705, 'l1_ratio': 0.40988412619213077, 'class_weight': None, 'fit_intercept': True, 'tol': 2.462766560253474e-05, 'max_iter': 3969}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  41%|█████████████████████████████████████████████▌                                                                 | 205/500 [36:59<58:37, 11.92s/it]

[I 2026-05-19 16:13:51,329] Trial 202 finished with value: 0.9499120811222929 and parameters: {'solver': 'saga', 'C': 0.025410137542848363, 'l1_ratio': 0.411535331904919, 'class_weight': None, 'fit_intercept': True, 'tol': 8.3817800002575e-06, 'max_iter': 3861}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  41%|█████████████████████████████████████████████▋                                                                 | 206/500 [37:05<49:20, 10.07s/it]

[I 2026-05-19 16:13:57,075] Trial 204 finished with value: 0.9499120806329 and parameters: {'solver': 'saga', 'C': 0.026191855391495676, 'l1_ratio': 0.41575760691055397, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1659342528516779e-05, 'max_iter': 3861}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  41%|█████████████████████████████████████████████▉                                                                 | 207/500 [37:12<45:58,  9.41s/it]

[I 2026-05-19 16:14:04,955] Trial 205 finished with value: 0.949911921707104 and parameters: {'solver': 'saga', 'C': 0.024319096765081868, 'l1_ratio': 0.42063903923851664, 'class_weight': None, 'fit_intercept': True, 'tol': 8.275636814042477e-06, 'max_iter': 4005}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  42%|██████████████████████████████████████████████▏                                                                | 208/500 [37:27<53:49, 11.06s/it]

[I 2026-05-19 16:14:19,856] Trial 208 finished with value: 0.9499119594469165 and parameters: {'solver': 'saga', 'C': 0.024812449916202923, 'l1_ratio': 0.41816895156783157, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1889900871351256e-05, 'max_iter': 3764}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  42%|██████████████████████████████████████████████▍                                                                | 209/500 [37:33<45:33,  9.40s/it]

[I 2026-05-19 16:14:25,367] Trial 209 finished with value: 0.9499119272390061 and parameters: {'solver': 'saga', 'C': 0.02378426877506138, 'l1_ratio': 0.41897186461241337, 'class_weight': None, 'fit_intercept': True, 'tol': 8.857949739584417e-06, 'max_iter': 4164}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  42%|██████████████████████████████████████████████▌                                                                | 210/500 [37:35<34:20,  7.11s/it]

[I 2026-05-19 16:14:27,140] Trial 210 finished with value: 0.9499119435061786 and parameters: {'solver': 'saga', 'C': 0.024158469362898363, 'l1_ratio': 0.4243951647528627, 'class_weight': None, 'fit_intercept': True, 'tol': 9.314073995357424e-06, 'max_iter': 3990}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  42%|██████████████████████████████████████████████▊                                                                | 211/500 [37:45<39:28,  8.20s/it]

[I 2026-05-19 16:14:37,876] Trial 206 finished with value: 0.9499120409309277 and parameters: {'solver': 'saga', 'C': 0.02731727256414103, 'l1_ratio': 0.31935488456054284, 'class_weight': None, 'fit_intercept': True, 'tol': 8.29622213875172e-06, 'max_iter': 3792}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  42%|███████████████████████████████████████████████                                                                | 212/500 [37:59<47:32,  9.91s/it]

[I 2026-05-19 16:14:51,771] Trial 211 finished with value: 0.9499120674484764 and parameters: {'solver': 'saga', 'C': 0.024600179508208975, 'l1_ratio': 0.32082955339917096, 'class_weight': None, 'fit_intercept': True, 'tol': 8.728612476468192e-06, 'max_iter': 3983}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  43%|███████████████████████████████████████████████▎                                                               | 213/500 [38:00<34:34,  7.23s/it]

[I 2026-05-19 16:14:52,749] Trial 213 finished with value: 0.9499119436723549 and parameters: {'solver': 'saga', 'C': 0.02458203654555369, 'l1_ratio': 0.45953903940147006, 'class_weight': None, 'fit_intercept': True, 'tol': 8.699379508619398e-06, 'max_iter': 4407}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  43%|███████████████████████████████████████████████▌                                                               | 214/500 [38:05<30:21,  6.37s/it]

[I 2026-05-19 16:14:57,114] Trial 212 finished with value: 0.9499120601267682 and parameters: {'solver': 'saga', 'C': 0.02670956839780982, 'l1_ratio': 0.3217578270653864, 'class_weight': None, 'fit_intercept': True, 'tol': 9.089813553608205e-06, 'max_iter': 3970}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  43%|███████████████████████████████████████████████▋                                                               | 215/500 [38:27<52:42, 11.10s/it]

[I 2026-05-19 16:15:19,225] Trial 214 finished with value: 0.9499119208969857 and parameters: {'solver': 'saga', 'C': 0.025083370757222376, 'l1_ratio': 0.4583083516819157, 'class_weight': None, 'fit_intercept': True, 'tol': 8.275481176997223e-06, 'max_iter': 4398}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  43%|███████████████████████████████████████████████                                                              | 216/500 [38:48<1:06:40, 14.08s/it]

[I 2026-05-19 16:15:40,298] Trial 215 finished with value: 0.9499120869769003 and parameters: {'solver': 'saga', 'C': 0.026914578015410372, 'l1_ratio': 0.42400723866025186, 'class_weight': None, 'fit_intercept': True, 'tol': 9.162269794719353e-06, 'max_iter': 3758}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  43%|████████████████████████████████████████████████▏                                                              | 217/500 [38:52<52:17, 11.09s/it]

[I 2026-05-19 16:15:44,380] Trial 216 finished with value: 0.9499120583467906 and parameters: {'solver': 'saga', 'C': 0.026027573479465303, 'l1_ratio': 0.4125965626185794, 'class_weight': None, 'fit_intercept': True, 'tol': 8.269238012319075e-06, 'max_iter': 3728}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  44%|████████████████████████████████████████████████▍                                                              | 218/500 [38:54<39:49,  8.47s/it]

[I 2026-05-19 16:15:46,768] Trial 217 finished with value: 0.9499118756852594 and parameters: {'solver': 'saga', 'C': 0.02167987181907394, 'l1_ratio': 0.4570082497503288, 'class_weight': None, 'fit_intercept': True, 'tol': 6.832079490952673e-06, 'max_iter': 3790}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  44%|████████████████████████████████████████████████▌                                                              | 219/500 [38:54<28:07,  6.01s/it]

[I 2026-05-19 16:15:47,016] Trial 219 finished with value: 0.9499119233340501 and parameters: {'solver': 'saga', 'C': 0.024281864521617756, 'l1_ratio': 0.4206004529107854, 'class_weight': None, 'fit_intercept': True, 'tol': 5.7850534307776195e-05, 'max_iter': 3776}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  44%|████████████████████████████████████████████████▊                                                              | 220/500 [39:02<30:10,  6.46s/it]

[I 2026-05-19 16:15:54,550] Trial 218 finished with value: 0.9499120043421072 and parameters: {'solver': 'saga', 'C': 0.027503066878015157, 'l1_ratio': 0.45263263794596076, 'class_weight': None, 'fit_intercept': True, 'tol': 8.942109670186296e-06, 'max_iter': 3577}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  44%|█████████████████████████████████████████████████                                                              | 221/500 [39:27<56:30, 12.15s/it]

[I 2026-05-19 16:16:19,978] Trial 221 finished with value: 0.9499120526576037 and parameters: {'solver': 'saga', 'C': 0.025843786336850364, 'l1_ratio': 0.44260207366216586, 'class_weight': None, 'fit_intercept': True, 'tol': 6.4523645070515194e-06, 'max_iter': 3752}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  44%|█████████████████████████████████████████████████▎                                                             | 222/500 [39:42<59:08, 12.76s/it]

[I 2026-05-19 16:16:34,168] Trial 222 finished with value: 0.9499120311868318 and parameters: {'solver': 'saga', 'C': 0.025571877357539206, 'l1_ratio': 0.4559712623660675, 'class_weight': None, 'fit_intercept': True, 'tol': 6.987022759832046e-06, 'max_iter': 3749}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  45%|████████████████████████████████████████████████▌                                                            | 223/500 [40:15<1:27:05, 18.86s/it]

[I 2026-05-19 16:17:07,259] Trial 223 finished with value: 0.9499120581786975 and parameters: {'solver': 'saga', 'C': 0.024431385809174005, 'l1_ratio': 0.3466853547000199, 'class_weight': None, 'fit_intercept': True, 'tol': 6.791833157300011e-06, 'max_iter': 3925}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  45%|████████████████████████████████████████████████▊                                                            | 224/500 [40:38<1:32:31, 20.11s/it]

[I 2026-05-19 16:17:30,288] Trial 225 finished with value: 0.9499113526597099 and parameters: {'solver': 'saga', 'C': 0.04980452096533737, 'l1_ratio': 0.32593892137973335, 'class_weight': None, 'fit_intercept': True, 'tol': 7.4458723556668385e-06, 'max_iter': 3688}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  45%|█████████████████████████████████████████████████                                                            | 225/500 [40:59<1:34:13, 20.56s/it]

[I 2026-05-19 16:17:51,890] Trial 226 finished with value: 0.9499115696643994 and parameters: {'solver': 'saga', 'C': 0.04504265386788172, 'l1_ratio': 0.34541270802420954, 'class_weight': None, 'fit_intercept': True, 'tol': 6.970195184155676e-06, 'max_iter': 3708}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  45%|█████████████████████████████████████████████████▎                                                           | 226/500 [41:20<1:33:25, 20.46s/it]

[I 2026-05-19 16:18:12,117] Trial 224 finished with value: 0.9499107990862079 and parameters: {'solver': 'saga', 'C': 0.04939013481686703, 'l1_ratio': 0.07665217391140706, 'class_weight': None, 'fit_intercept': True, 'tol': 6.567605338803043e-06, 'max_iter': 3958}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  45%|█████████████████████████████████████████████████▍                                                           | 227/500 [41:28<1:17:00, 16.93s/it]

[I 2026-05-19 16:18:20,803] Trial 231 finished with value: 0.9499024973136425 and parameters: {'solver': 'saga', 'C': 0.04835516567416727, 'l1_ratio': 0.9358177608343285, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.4667195345005e-06, 'max_iter': 3702}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  46%|██████████████████████████████████████████████████▌                                                            | 228/500 [41:29<54:12, 11.96s/it]

[I 2026-05-19 16:18:21,160] Trial 229 finished with value: 0.9499114767787684 and parameters: {'solver': 'saga', 'C': 0.04741039726049095, 'l1_ratio': 0.33109195681201953, 'class_weight': None, 'fit_intercept': True, 'tol': 6.542601256756368e-06, 'max_iter': 3703}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  46%|██████████████████████████████████████████████████▊                                                            | 229/500 [41:34<44:37,  9.88s/it]

[I 2026-05-19 16:18:26,192] Trial 227 finished with value: 0.9499113287468154 and parameters: {'solver': 'saga', 'C': 0.05025169585149135, 'l1_ratio': 0.32509646299841793, 'class_weight': None, 'fit_intercept': True, 'tol': 6.221379420768236e-06, 'max_iter': 3696}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  46%|██████████████████████████████████████████████████▏                                                          | 230/500 [41:59<1:05:03, 14.46s/it]

[I 2026-05-19 16:18:51,332] Trial 232 finished with value: 0.9499115390813639 and parameters: {'solver': 'saga', 'C': 0.04497004450362925, 'l1_ratio': 0.32476480197253826, 'class_weight': None, 'fit_intercept': True, 'tol': 6.498029616398089e-06, 'max_iter': 3717}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  46%|██████████████████████████████████████████████████▎                                                          | 231/500 [42:10<1:00:58, 13.60s/it]

[I 2026-05-19 16:19:02,904] Trial 220 finished with value: 0.9499091255386469 and parameters: {'solver': 'saga', 'C': 10.093272108292563, 'l1_ratio': 0.4618975844775891, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1467366807479626e-05, 'max_iter': 3614}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  46%|███████████████████████████████████████████████████▌                                                           | 232/500 [42:20<55:00, 12.31s/it]

[I 2026-05-19 16:19:12,248] Trial 228 finished with value: 0.949902549986278 and parameters: {'solver': 'saga', 'C': 0.04944100179125757, 'l1_ratio': 0.32791637926947537, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.56431309606808e-06, 'max_iter': 3594}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  47%|███████████████████████████████████████████████████▋                                                           | 233/500 [42:20<39:10,  8.80s/it]

[I 2026-05-19 16:19:12,847] Trial 230 finished with value: 0.9499026440109943 and parameters: {'solver': 'saga', 'C': 0.04563131503496584, 'l1_ratio': 0.3313795112452726, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.677716728495695e-06, 'max_iter': 3931}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  47%|███████████████████████████████████████████████████▉                                                           | 234/500 [42:22<29:38,  6.69s/it]

[I 2026-05-19 16:19:14,601] Trial 233 finished with value: 0.9499113926769235 and parameters: {'solver': 'saga', 'C': 0.04879334551987868, 'l1_ratio': 0.3257295805089573, 'class_weight': None, 'fit_intercept': True, 'tol': 5.843240723064158e-06, 'max_iter': 3666}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  47%|████████████████████████████████████████████████████▏                                                          | 235/500 [42:32<34:10,  7.74s/it]

[I 2026-05-19 16:19:24,789] Trial 237 finished with value: 0.949889642064458 and parameters: {'solver': 'saga', 'C': 0.01162659081648147, 'l1_ratio': 0.943162851941419, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.2347530029524104e-06, 'max_iter': 3636}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  47%|███████████████████████████████████████████████████▍                                                         | 236/500 [43:03<1:04:10, 14.59s/it]

[I 2026-05-19 16:19:55,357] Trial 244 finished with value: 0.9499098151553932 and parameters: {'solver': 'saga', 'C': 0.012800170613719249, 'l1_ratio': 0.39114713111551525, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007245111706544348, 'max_iter': 3793}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  47%|████████████████████████████████████████████████████▌                                                          | 237/500 [43:04<46:15, 10.55s/it]

[I 2026-05-19 16:19:56,505] Trial 239 finished with value: 0.949908858822855 and parameters: {'solver': 'saga', 'C': 0.011242552205756031, 'l1_ratio': 0.38725746185177046, 'class_weight': None, 'fit_intercept': True, 'tol': 5.154984619186726e-06, 'max_iter': 3763}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  48%|████████████████████████████████████████████████████▊                                                          | 238/500 [43:07<35:50,  8.21s/it]

[I 2026-05-19 16:19:59,239] Trial 238 finished with value: 0.9499096890872707 and parameters: {'solver': 'saga', 'C': 0.012285424177253392, 'l1_ratio': 0.38531259521460776, 'class_weight': None, 'fit_intercept': True, 'tol': 4.994277226468344e-06, 'max_iter': 3579}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  48%|█████████████████████████████████████████████████████                                                          | 239/500 [43:12<32:25,  7.45s/it]

[I 2026-05-19 16:20:04,927] Trial 240 finished with value: 0.9499096755857238 and parameters: {'solver': 'saga', 'C': 0.012256845109308136, 'l1_ratio': 0.38629269953894924, 'class_weight': None, 'fit_intercept': True, 'tol': 5.1479484666034616e-06, 'max_iter': 3594}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  48%|█████████████████████████████████████████████████████▎                                                         | 240/500 [43:18<29:17,  6.76s/it]

[I 2026-05-19 16:20:10,064] Trial 241 finished with value: 0.9499088614302235 and parameters: {'solver': 'saga', 'C': 0.012590274322635818, 'l1_ratio': 0.44611501019667593, 'class_weight': None, 'fit_intercept': True, 'tol': 9.205968330887279e-06, 'max_iter': 3549}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  48%|█████████████████████████████████████████████████████▌                                                         | 241/500 [43:35<42:29,  9.84s/it]

[I 2026-05-19 16:20:27,110] Trial 234 finished with value: 0.9499108199076369 and parameters: {'solver': 'saga', 'C': 0.049034094658861854, 'l1_ratio': 0.07905916413584041, 'class_weight': None, 'fit_intercept': True, 'tol': 6.151567852083336e-06, 'max_iter': 3745}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  48%|█████████████████████████████████████████████████████▋                                                         | 242/500 [43:44<41:47,  9.72s/it]

[I 2026-05-19 16:20:36,542] Trial 242 finished with value: 0.9499103143894108 and parameters: {'solver': 'saga', 'C': 0.013262896222622014, 'l1_ratio': 0.3882263599836302, 'class_weight': None, 'fit_intercept': True, 'tol': 9.36776626029489e-06, 'max_iter': 3926}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  49%|█████████████████████████████████████████████████████▉                                                         | 243/500 [43:58<47:25, 11.07s/it]

[I 2026-05-19 16:20:50,767] Trial 245 finished with value: 0.9499105034097306 and parameters: {'solver': 'saga', 'C': 0.013613239399537179, 'l1_ratio': 0.38570206825902964, 'class_weight': None, 'fit_intercept': True, 'tol': 8.926809606275033e-06, 'max_iter': 3830}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  49%|██████████████████████████████████████████████████████▏                                                        | 244/500 [44:01<36:09,  8.47s/it]

[I 2026-05-19 16:20:53,181] Trial 243 finished with value: 0.9499104430607671 and parameters: {'solver': 'saga', 'C': 0.013558452678921503, 'l1_ratio': 0.38877358316070165, 'class_weight': None, 'fit_intercept': True, 'tol': 5.047378419681368e-06, 'max_iter': 3793}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  49%|██████████████████████████████████████████████████████▍                                                        | 245/500 [44:03<27:59,  6.58s/it]

[I 2026-05-19 16:20:55,358] Trial 246 finished with value: 0.9499100176811075 and parameters: {'solver': 'saga', 'C': 0.012747069175998915, 'l1_ratio': 0.38828496267968493, 'class_weight': None, 'fit_intercept': True, 'tol': 8.94179079589399e-06, 'max_iter': 3808}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  49%|██████████████████████████████████████████████████████▌                                                        | 246/500 [44:11<30:20,  7.17s/it]

[I 2026-05-19 16:21:03,881] Trial 235 finished with value: 0.9499025097992364 and parameters: {'solver': 'saga', 'C': 0.050879259279694826, 'l1_ratio': 0.21168495325407205, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.360279065034135e-06, 'max_iter': 3704}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  49%|██████████████████████████████████████████████████████▊                                                        | 247/500 [44:35<50:35, 12.00s/it]

[I 2026-05-19 16:21:27,151] Trial 236 finished with value: 0.9499025415316895 and parameters: {'solver': 'saga', 'C': 0.04652681906587386, 'l1_ratio': 0.38462073295358234, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.464326918221176e-06, 'max_iter': 3630}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  50%|██████████████████████████████████████████████████████                                                       | 248/500 [44:54<1:00:09, 14.32s/it]

[I 2026-05-19 16:21:46,901] Trial 258 finished with value: 0.9497964828455636 and parameters: {'solver': 'saga', 'C': 0.00027066288759179186, 'l1_ratio': 0.3463052122580866, 'class_weight': None, 'fit_intercept': True, 'tol': 1.132016505488643e-05, 'max_iter': 3905}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 92. Best value: 0.949912:  50%|███████████████████████████████████████████████████████▎                                                       | 249/500 [45:01<50:15, 12.01s/it]

[I 2026-05-19 16:21:53,523] Trial 248 finished with value: 0.9499120746097167 and parameters: {'solver': 'saga', 'C': 0.028128541649575838, 'l1_ratio': 0.3832157203250118, 'class_weight': None, 'fit_intercept': True, 'tol': 9.183761824211932e-06, 'max_iter': 3934}. Best is trial 92 with value: 0.9499120900579981.

Best trial: 250. Best value: 0.949912:  50%|███████████████████████████████████████████████████████                                                       | 250/500 [45:05<40:25,  9.70s/it]

[I 2026-05-19 16:21:57,838] Trial 250 finished with value: 0.9499121585509325 and parameters: {'solver': 'saga', 'C': 0.02914879956934508, 'l1_ratio': 0.43970786556822744, 'class_weight': None, 'fit_intercept': True, 'tol': 8.83661241539477e-06, 'max_iter': 3921}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  50%|███████████████████████████████████████████████████████▏                                                      | 251/500 [45:06<28:32,  6.88s/it]

[I 2026-05-19 16:21:58,114] Trial 247 finished with value: 0.9499119265760427 and parameters: {'solver': 'saga', 'C': 0.03169643786169457, 'l1_ratio': 0.3861032505336014, 'class_weight': None, 'fit_intercept': True, 'tol': 9.189314326179239e-06, 'max_iter': 3909}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  50%|███████████████████████████████████████████████████████▍                                                      | 252/500 [45:29<48:38, 11.77s/it]

[I 2026-05-19 16:22:21,299] Trial 251 finished with value: 0.9499121159249866 and parameters: {'solver': 'saga', 'C': 0.026834376620592907, 'l1_ratio': 0.34769494668375495, 'class_weight': None, 'fit_intercept': True, 'tol': 1.080659640939505e-05, 'max_iter': 3896}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  51%|███████████████████████████████████████████████████████▋                                                      | 253/500 [45:48<57:43, 14.02s/it]

[I 2026-05-19 16:22:40,587] Trial 252 finished with value: 0.9499119581319452 and parameters: {'solver': 'saga', 'C': 0.0313066598450932, 'l1_ratio': 0.34964196285344773, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1343615703438512e-05, 'max_iter': 3945}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  51%|███████████████████████████████████████████████████████▉                                                      | 254/500 [45:57<50:55, 12.42s/it]

[I 2026-05-19 16:22:49,259] Trial 253 finished with value: 0.9499120248278539 and parameters: {'solver': 'saga', 'C': 0.028197567516834, 'l1_ratio': 0.34732638159813223, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1165868933345096e-05, 'max_iter': 3830}. Best is trial 250 with value: 0.9499121585509325.
[I 2026-05-19 16:22:49,283] Trial 249 finished with value: 0.9499116254625479 and parameters: {'solver': 'saga', 'C': 0.029227652873681332, 'l1_ratio': 0.1995193110104332, 'class_weight': None, 'fit_intercept': True, 'tol': 9.049751812121438e-06, 'max_iter': 3924}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  51%|████████████████████████████████████████████████████████▎                                                     | 256/500 [46:10<39:24,  9.69s/it]

[I 2026-05-19 16:23:02,278] Trial 254 finished with value: 0.9499120664746089 and parameters: {'solver': 'saga', 'C': 0.02587053158487937, 'l1_ratio': 0.34899932290944513, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1904775767157918e-05, 'max_iter': 3903}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  51%|████████████████████████████████████████████████████████▌                                                     | 257/500 [46:16<35:34,  8.79s/it]

[I 2026-05-19 16:23:08,318] Trial 255 finished with value: 0.949912084042461 and parameters: {'solver': 'saga', 'C': 0.02656441748275185, 'l1_ratio': 0.3475008075154342, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1180980955767421e-05, 'max_iter': 3912}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  52%|████████████████████████████████████████████████████████▊                                                     | 258/500 [46:16<26:23,  6.54s/it]

[I 2026-05-19 16:23:08,525] Trial 256 finished with value: 0.9499120611061482 and parameters: {'solver': 'saga', 'C': 0.026540267963612335, 'l1_ratio': 0.3579040547395066, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0862529113848281e-05, 'max_iter': 3910}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  52%|████████████████████████████████████████████████████████▉                                                     | 259/500 [46:26<30:25,  7.58s/it]

[I 2026-05-19 16:23:18,871] Trial 257 finished with value: 0.9499120487404475 and parameters: {'solver': 'saga', 'C': 0.028266310640602685, 'l1_ratio': 0.34931288838353114, 'class_weight': None, 'fit_intercept': True, 'tol': 1.158700002070584e-05, 'max_iter': 3932}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  52%|█████████████████████████████████████████████████████████▏                                                    | 260/500 [46:53<52:10, 13.04s/it]

[I 2026-05-19 16:23:45,980] Trial 261 finished with value: 0.9499121458650521 and parameters: {'solver': 'saga', 'C': 0.02991874587501646, 'l1_ratio': 0.47877818660791943, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1758307090246968e-05, 'max_iter': 4004}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  52%|█████████████████████████████████████████████████████████▍                                                    | 261/500 [46:55<38:55,  9.77s/it]

[I 2026-05-19 16:23:47,566] Trial 265 finished with value: 0.949897302324721 and parameters: {'solver': 'saga', 'C': 0.02556681619558583, 'l1_ratio': 0.4767093330444175, 'class_weight': None, 'fit_intercept': False, 'tol': 8.142620449936772e-06, 'max_iter': 3985}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  52%|█████████████████████████████████████████████████████████▋                                                    | 262/500 [46:57<29:23,  7.41s/it]

[I 2026-05-19 16:23:49,142] Trial 262 finished with value: 0.9499121027555966 and parameters: {'solver': 'saga', 'C': 0.02834312613992386, 'l1_ratio': 0.44073947599573693, 'class_weight': None, 'fit_intercept': True, 'tol': 1.217741127637552e-05, 'max_iter': 3941}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  53%|█████████████████████████████████████████████████████████▊                                                    | 263/500 [47:05<29:50,  7.56s/it]

[I 2026-05-19 16:23:57,093] Trial 259 finished with value: 0.9499120744447158 and parameters: {'solver': 'saga', 'C': 0.024745532338473118, 'l1_ratio': 0.34762301118270433, 'class_weight': None, 'fit_intercept': True, 'tol': 1.145174292076965e-05, 'max_iter': 4157}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  53%|██████████████████████████████████████████████████████████                                                    | 264/500 [47:11<28:51,  7.34s/it]

[I 2026-05-19 16:24:03,918] Trial 260 finished with value: 0.9499120544348321 and parameters: {'solver': 'saga', 'C': 0.027729835925126685, 'l1_ratio': 0.34798007941948483, 'class_weight': None, 'fit_intercept': True, 'tol': 1.236372884873425e-05, 'max_iter': 3996}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  53%|██████████████████████████████████████████████████████████▎                                                   | 265/500 [47:12<20:50,  5.32s/it]

[I 2026-05-19 16:24:04,444] Trial 266 finished with value: 0.949897883035845 and parameters: {'solver': 'saga', 'C': 0.02109907366068446, 'l1_ratio': 0.26331483020274526, 'class_weight': None, 'fit_intercept': False, 'tol': 7.4180921793333454e-06, 'max_iter': 3992}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  53%|██████████████████████████████████████████████████████████▌                                                   | 266/500 [47:17<20:34,  5.27s/it]

[I 2026-05-19 16:24:09,616] Trial 263 finished with value: 0.9499120707102733 and parameters: {'solver': 'saga', 'C': 0.027635082104742727, 'l1_ratio': 0.4378996955354631, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1841925793275508e-05, 'max_iter': 3977}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  53%|██████████████████████████████████████████████████████████▋                                                   | 267/500 [47:32<32:04,  8.26s/it]

[I 2026-05-19 16:24:24,899] Trial 264 finished with value: 0.9499120843761357 and parameters: {'solver': 'saga', 'C': 0.026469419745276612, 'l1_ratio': 0.43602454516006667, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2789293756499432e-05, 'max_iter': 3995}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  54%|██████████████████████████████████████████████████████████▉                                                   | 268/500 [47:59<53:38, 13.87s/it]

[I 2026-05-19 16:24:51,953] Trial 269 finished with value: 0.9499119083792678 and parameters: {'solver': 'saga', 'C': 0.021276018010412796, 'l1_ratio': 0.43305883058669037, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3213984657133186e-05, 'max_iter': 3996}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  54%|███████████████████████████████████████████████████████████▏                                                  | 269/500 [48:13<53:08, 13.80s/it]

[I 2026-05-19 16:25:05,584] Trial 267 finished with value: 0.9499108911598244 and parameters: {'solver': 'saga', 'C': 0.09299923971093932, 'l1_ratio': 0.4396589034853034, 'class_weight': None, 'fit_intercept': True, 'tol': 1.351727151706914e-05, 'max_iter': 3976}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  54%|███████████████████████████████████████████████████████████▍                                                  | 270/500 [48:20<45:21, 11.83s/it]

[I 2026-05-19 16:25:12,800] Trial 270 finished with value: 0.9499118741958499 and parameters: {'solver': 'saga', 'C': 0.03690142371326363, 'l1_ratio': 0.4412825629438574, 'class_weight': None, 'fit_intercept': True, 'tol': 1.307584527953084e-05, 'max_iter': 4000}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  54%|███████████████████████████████████████████████████████████▌                                                  | 271/500 [48:34<47:11, 12.36s/it]

[I 2026-05-19 16:25:26,420] Trial 272 finished with value: 0.9499117608387433 and parameters: {'solver': 'saga', 'C': 0.020519749263939135, 'l1_ratio': 0.436377075252305, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7681639289407892e-05, 'max_iter': 4010}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  54%|███████████████████████████████████████████████████████████▊                                                  | 272/500 [48:39<38:38, 10.17s/it]

[I 2026-05-19 16:25:31,458] Trial 273 finished with value: 0.9499115700292675 and parameters: {'solver': 'saga', 'C': 0.019325991714319545, 'l1_ratio': 0.43999660136366864, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3529725735772798e-05, 'max_iter': 4002}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  55%|████████████████████████████████████████████████████████████                                                  | 273/500 [48:47<36:05,  9.54s/it]

[I 2026-05-19 16:25:39,530] Trial 274 finished with value: 0.9499117261877448 and parameters: {'solver': 'saga', 'C': 0.019480786229527702, 'l1_ratio': 0.4098504037968339, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3151364753282086e-05, 'max_iter': 4009}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  55%|████████████████████████████████████████████████████████████▎                                                 | 274/500 [48:53<31:45,  8.43s/it]

[I 2026-05-19 16:25:45,376] Trial 277 finished with value: 0.9499115244800332 and parameters: {'solver': 'saga', 'C': 0.018617649014665817, 'l1_ratio': 0.4166942500913936, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8002391619441216e-05, 'max_iter': 4125}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  55%|████████████████████████████████████████████████████████████▌                                                 | 275/500 [48:59<28:43,  7.66s/it]

[I 2026-05-19 16:25:51,237] Trial 268 finished with value: 0.9499000071770596 and parameters: {'solver': 'saga', 'C': 0.08717381967396305, 'l1_ratio': 0.4389304784243531, 'class_weight': None, 'fit_intercept': False, 'tol': 1.2063542931031645e-05, 'max_iter': 4001}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  55%|████████████████████████████████████████████████████████████▋                                                 | 276/500 [49:15<38:15, 10.25s/it]

[I 2026-05-19 16:26:07,524] Trial 275 finished with value: 0.9499109495588772 and parameters: {'solver': 'saga', 'C': 0.084378851269595, 'l1_ratio': 0.40871609908075746, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3366680109197579e-05, 'max_iter': 4012}. Best is trial 250 with value: 0.9499121585509325.
[I 2026-05-19 16:26:07,657] Trial 276 finished with value: 0.9499109142598581 and parameters: {'solver': 'saga', 'C': 0.08568786240599773, 'l1_ratio': 0.40404250571376543, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3152333068704136e-05, 'max_iter': 4120}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  56%|█████████████████████████████████████████████████████████████▏                                                | 278/500 [49:21<25:39,  6.94s/it]

[I 2026-05-19 16:26:13,967] Trial 278 finished with value: 0.9499118278344122 and parameters: {'solver': 'saga', 'C': 0.03669329433995886, 'l1_ratio': 0.4153441339689856, 'class_weight': None, 'fit_intercept': True, 'tol': 1.745597787343294e-05, 'max_iter': 4010}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  56%|█████████████████████████████████████████████████████████████▍                                                | 279/500 [49:26<22:26,  6.09s/it]

[I 2026-05-19 16:26:18,097] Trial 271 finished with value: 0.9498998568701535 and parameters: {'solver': 'saga', 'C': 0.0896052345018416, 'l1_ratio': 0.4755878940598124, 'class_weight': None, 'fit_intercept': False, 'tol': 1.8153927007260312e-05, 'max_iter': 4019}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  56%|█████████████████████████████████████████████████████████████▌                                                | 280/500 [49:49<41:43, 11.38s/it]

[I 2026-05-19 16:26:41,806] Trial 279 finished with value: 0.949911819538039 and parameters: {'solver': 'saga', 'C': 0.036322547766643995, 'l1_ratio': 0.4144132385700892, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7616380520654932e-05, 'max_iter': 4156}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  56%|█████████████████████████████████████████████████████████████▊                                                | 281/500 [49:58<38:16, 10.49s/it]

[I 2026-05-19 16:26:50,215] Trial 281 finished with value: 0.9499114182547501 and parameters: {'solver': 'saga', 'C': 0.017929138015349497, 'l1_ratio': 0.40464048386144813, 'class_weight': None, 'fit_intercept': True, 'tol': 1.690843490175998e-05, 'max_iter': 4129}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  56%|██████████████████████████████████████████████████████████████                                                | 282/500 [50:03<32:40,  8.99s/it]

[I 2026-05-19 16:26:55,726] Trial 280 finished with value: 0.9499118419857566 and parameters: {'solver': 'saga', 'C': 0.03650323375629266, 'l1_ratio': 0.4069433166887532, 'class_weight': None, 'fit_intercept': True, 'tol': 1.816123480160619e-05, 'max_iter': 4130}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  57%|██████████████████████████████████████████████████████████████▎                                               | 283/500 [50:24<45:12, 12.50s/it]

[I 2026-05-19 16:27:16,404] Trial 282 finished with value: 0.9499118561370942 and parameters: {'solver': 'saga', 'C': 0.03670648790485815, 'l1_ratio': 0.4025814127988955, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7217336293136884e-05, 'max_iter': 4154}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  57%|██████████████████████████████████████████████████████████████▍                                               | 284/500 [50:30<38:22, 10.66s/it]

[I 2026-05-19 16:27:22,775] Trial 283 finished with value: 0.9499118984355075 and parameters: {'solver': 'saga', 'C': 0.036783460543857234, 'l1_ratio': 0.4739769779948137, 'class_weight': None, 'fit_intercept': True, 'tol': 1.980786553162822e-05, 'max_iter': 4132}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  57%|██████████████████████████████████████████████████████████████▋                                               | 285/500 [50:41<37:57, 10.59s/it]

[I 2026-05-19 16:27:33,214] Trial 284 finished with value: 0.9499118885070186 and parameters: {'solver': 'saga', 'C': 0.03910031914601516, 'l1_ratio': 0.4080725338086953, 'class_weight': None, 'fit_intercept': True, 'tol': 1.792110573419018e-05, 'max_iter': 4141}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  57%|██████████████████████████████████████████████████████████████▉                                               | 286/500 [50:42<27:25,  7.69s/it]

[I 2026-05-19 16:27:34,122] Trial 285 finished with value: 0.9499118114058135 and parameters: {'solver': 'saga', 'C': 0.03968974232422881, 'l1_ratio': 0.4685318693845344, 'class_weight': None, 'fit_intercept': True, 'tol': 1.771363884224582e-05, 'max_iter': 3890}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  57%|███████████████████████████████████████████████████████████████▏                                              | 287/500 [50:49<27:12,  7.66s/it]

[I 2026-05-19 16:27:41,727] Trial 286 finished with value: 0.9499118735440935 and parameters: {'solver': 'saga', 'C': 0.03567573048810292, 'l1_ratio': 0.407988829529325, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7154266806999842e-05, 'max_iter': 3855}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  58%|███████████████████████████████████████████████████████████████▎                                              | 288/500 [51:08<39:19, 11.13s/it]

[I 2026-05-19 16:28:00,952] Trial 287 finished with value: 0.9499120677814445 and parameters: {'solver': 'saga', 'C': 0.032520275626935456, 'l1_ratio': 0.47569540964048385, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0058569789874616e-05, 'max_iter': 3859}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  58%|███████████████████████████████████████████████████████████████▌                                              | 289/500 [51:14<33:13,  9.45s/it]

[I 2026-05-19 16:28:06,471] Trial 288 finished with value: 0.949911817099974 and parameters: {'solver': 'saga', 'C': 0.040087759830709224, 'l1_ratio': 0.48070391103027665, 'class_weight': None, 'fit_intercept': True, 'tol': 9.973331989141286e-06, 'max_iter': 1061}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  58%|███████████████████████████████████████████████████████████████▊                                              | 290/500 [51:19<28:23,  8.11s/it]

[I 2026-05-19 16:28:11,459] Trial 289 finished with value: 0.9499118746846757 and parameters: {'solver': 'saga', 'C': 0.03849488397306957, 'l1_ratio': 0.4836628432394206, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0049376559647035e-05, 'max_iter': 3853}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  58%|████████████████████████████████████████████████████████████████                                              | 291/500 [51:30<31:01,  8.91s/it]

[I 2026-05-19 16:28:22,226] Trial 290 finished with value: 0.9499118865537504 and parameters: {'solver': 'saga', 'C': 0.036054740784276375, 'l1_ratio': 0.36684307082389817, 'class_weight': None, 'fit_intercept': True, 'tol': 9.937316091500183e-06, 'max_iter': 3872}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  58%|████████████████████████████████████████████████████████████████▏                                             | 292/500 [51:39<30:48,  8.89s/it]

[I 2026-05-19 16:28:31,062] Trial 295 finished with value: 0.9499040869233312 and parameters: {'solver': 'saga', 'C': 0.008806547265905337, 'l1_ratio': 0.5052556821894408, 'class_weight': None, 'fit_intercept': True, 'tol': 9.759148764503624e-06, 'max_iter': 3879}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  59%|████████████████████████████████████████████████████████████████▍                                             | 293/500 [51:45<28:32,  8.27s/it]

[I 2026-05-19 16:28:37,903] Trial 291 finished with value: 0.9499119127508807 and parameters: {'solver': 'saga', 'C': 0.03812407496688691, 'l1_ratio': 0.5045828919005277, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0050534352045385e-05, 'max_iter': 3864}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  59%|████████████████████████████████████████████████████████████████▋                                             | 294/500 [52:00<35:17, 10.28s/it]

[I 2026-05-19 16:28:52,860] Trial 297 finished with value: 0.9499060478950685 and parameters: {'solver': 'saga', 'C': 0.008478309764889018, 'l1_ratio': 0.3674720235416186, 'class_weight': None, 'fit_intercept': True, 'tol': 9.916920910181105e-06, 'max_iter': 3871}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  59%|████████████████████████████████████████████████████████████████▉                                             | 295/500 [52:01<25:24,  7.44s/it]

[I 2026-05-19 16:28:53,676] Trial 296 finished with value: 0.9499063354975235 and parameters: {'solver': 'saga', 'C': 0.008735044325747624, 'l1_ratio': 0.36711873064174455, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0072350957550943e-05, 'max_iter': 3867}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  59%|█████████████████████████████████████████████████████████████████                                             | 296/500 [52:02<18:47,  5.53s/it]

[I 2026-05-19 16:28:54,734] Trial 292 finished with value: 0.9499118585719201 and parameters: {'solver': 'saga', 'C': 0.039654196582922706, 'l1_ratio': 0.3707146653265132, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0115780946820443e-05, 'max_iter': 3875}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  59%|█████████████████████████████████████████████████████████████████▎                                            | 297/500 [52:10<21:10,  6.26s/it]

[I 2026-05-19 16:29:02,689] Trial 293 finished with value: 0.9499118815085128 and parameters: {'solver': 'saga', 'C': 0.038166870121766, 'l1_ratio': 0.36490311023853433, 'class_weight': None, 'fit_intercept': True, 'tol': 9.981075783717993e-06, 'max_iter': 3868}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  60%|█████████████████████████████████████████████████████████████████▌                                            | 298/500 [52:24<28:24,  8.44s/it]

[I 2026-05-19 16:29:16,228] Trial 299 finished with value: 0.9499054723700132 and parameters: {'solver': 'saga', 'C': 0.007838399004411896, 'l1_ratio': 0.3655785107498874, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0201721537156965e-05, 'max_iter': 3888}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  60%|█████████████████████████████████████████████████████████████████▊                                            | 299/500 [52:31<26:47,  8.00s/it]

[I 2026-05-19 16:29:23,198] Trial 298 finished with value: 0.9499113759619051 and parameters: {'solver': 'saga', 'C': 0.016358706215371104, 'l1_ratio': 0.370483673298072, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0124578790246484e-05, 'max_iter': 3895}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  60%|██████████████████████████████████████████████████████████████████                                            | 300/500 [52:36<23:42,  7.11s/it]

[I 2026-05-19 16:29:28,246] Trial 294 finished with value: 0.9499111459038087 and parameters: {'solver': 'saga', 'C': 0.0636251282069751, 'l1_ratio': 0.36812211509283926, 'class_weight': None, 'fit_intercept': True, 'tol': 9.924958569399763e-06, 'max_iter': 3890}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  60%|██████████████████████████████████████████████████████████████████▏                                           | 301/500 [52:47<27:27,  8.28s/it]

[I 2026-05-19 16:29:39,241] Trial 311 pruned.

Best trial: 250. Best value: 0.949912:  60%|██████████████████████████████████████████████████████████████████▍                                           | 302/500 [53:11<43:12, 13.09s/it]

[I 2026-05-19 16:30:03,566] Trial 300 finished with value: 0.9499114341622035 and parameters: {'solver': 'saga', 'C': 0.06399800956453304, 'l1_ratio': 0.49971147545444167, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0570788793471165e-05, 'max_iter': 3885}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  61%|██████████████████████████████████████████████████████████████████▋                                           | 303/500 [53:24<42:31, 12.95s/it]

[I 2026-05-19 16:30:16,197] Trial 303 finished with value: 0.9499113453807307 and parameters: {'solver': 'saga', 'C': 0.016261522225798564, 'l1_ratio': 0.3742400382387867, 'class_weight': None, 'fit_intercept': True, 'tol': 8.193329858570431e-06, 'max_iter': 3915}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  61%|██████████████████████████████████████████████████████████████████▉                                           | 304/500 [53:30<35:28, 10.86s/it]

[I 2026-05-19 16:30:22,171] Trial 302 finished with value: 0.9499114374159134 and parameters: {'solver': 'saga', 'C': 0.06474491679687543, 'l1_ratio': 0.5087929895263364, 'class_weight': None, 'fit_intercept': True, 'tol': 8.491860551903297e-06, 'max_iter': 3903}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  61%|███████████████████████████████████████████████████████████████████                                           | 305/500 [53:34<29:10,  8.98s/it]

[I 2026-05-19 16:30:26,751] Trial 301 finished with value: 0.9499112226851064 and parameters: {'solver': 'saga', 'C': 0.05881990016535012, 'l1_ratio': 0.370141763287626, 'class_weight': None, 'fit_intercept': True, 'tol': 1.058393562644302e-05, 'max_iter': 3874}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  61%|███████████████████████████████████████████████████████████████████▎                                          | 306/500 [53:36<22:21,  6.92s/it]

[I 2026-05-19 16:30:28,861] Trial 304 finished with value: 0.9499116726665779 and parameters: {'solver': 'saga', 'C': 0.018156317320948835, 'l1_ratio': 0.3699065986949706, 'class_weight': None, 'fit_intercept': True, 'tol': 8.392173543430215e-06, 'max_iter': 3898}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  61%|███████████████████████████████████████████████████████████████████▌                                          | 307/500 [53:47<26:06,  8.11s/it]

[I 2026-05-19 16:30:39,770] Trial 309 finished with value: 0.9499105727145677 and parameters: {'solver': 'saga', 'C': 0.01523983662180247, 'l1_ratio': 0.45328460042239915, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1848918268781308e-05, 'max_iter': 3790}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  62%|███████████████████████████████████████████████████████████████████▊                                          | 308/500 [53:59<29:41,  9.28s/it]

[I 2026-05-19 16:30:51,771] Trial 310 finished with value: 0.9499107448184073 and parameters: {'solver': 'saga', 'C': 0.015933935404979577, 'l1_ratio': 0.45881673397195494, 'class_weight': None, 'fit_intercept': True, 'tol': 8.10362552816763e-06, 'max_iter': 3939}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  62%|███████████████████████████████████████████████████████████████████▉                                          | 309/500 [53:59<20:54,  6.57s/it]

[I 2026-05-19 16:30:52,005] Trial 306 finished with value: 0.9499114450598656 and parameters: {'solver': 'saga', 'C': 0.059738625019915295, 'l1_ratio': 0.45969481172947685, 'class_weight': None, 'fit_intercept': True, 'tol': 1.164068827421211e-05, 'max_iter': 3945}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  62%|████████████████████████████████████████████████████████████████████▏                                         | 310/500 [54:13<27:27,  8.67s/it]

[I 2026-05-19 16:31:05,593] Trial 308 finished with value: 0.9499115337156873 and parameters: {'solver': 'saga', 'C': 0.057511273448689344, 'l1_ratio': 0.4589380441623387, 'class_weight': None, 'fit_intercept': True, 'tol': 8.24218028013782e-06, 'max_iter': 3786}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  62%|████████████████████████████████████████████████████████████████████▍                                         | 311/500 [54:18<23:58,  7.61s/it]

[I 2026-05-19 16:31:10,678] Trial 305 finished with value: 0.9499111489952039 and parameters: {'solver': 'saga', 'C': 0.06248603531314455, 'l1_ratio': 0.3753806401643016, 'class_weight': None, 'fit_intercept': True, 'tol': 8.096760153260028e-06, 'max_iter': 3925}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  62%|████████████████████████████████████████████████████████████████████▋                                         | 312/500 [54:39<36:40, 11.71s/it]

[I 2026-05-19 16:31:31,986] Trial 313 finished with value: 0.9499107012242183 and parameters: {'solver': 'saga', 'C': 0.015412679626511603, 'l1_ratio': 0.4549263073522392, 'class_weight': None, 'fit_intercept': True, 'tol': 7.714711314424763e-06, 'max_iter': 4267}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  63%|████████████████████████████████████████████████████████████████████▊                                         | 313/500 [54:47<32:59, 10.58s/it]

[I 2026-05-19 16:31:39,955] Trial 312 finished with value: 0.9499114461984892 and parameters: {'solver': 'saga', 'C': 0.05946944045124122, 'l1_ratio': 0.4576068050507755, 'class_weight': None, 'fit_intercept': True, 'tol': 7.992190921232316e-06, 'max_iter': 4058}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  63%|█████████████████████████████████████████████████████████████████████                                         | 314/500 [55:02<36:14, 11.69s/it]

[I 2026-05-19 16:31:54,227] Trial 307 finished with value: 0.9499107875384961 and parameters: {'solver': 'saga', 'C': 0.06181123947828094, 'l1_ratio': 0.15763836622391922, 'class_weight': None, 'fit_intercept': True, 'tol': 8.04279227366762e-06, 'max_iter': 3954}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  63%|█████████████████████████████████████████████████████████████████████▎                                        | 315/500 [55:10<32:45, 10.62s/it]

[I 2026-05-19 16:32:02,361] Trial 315 finished with value: 0.949911873403563 and parameters: {'solver': 'saga', 'C': 0.02244914658833426, 'l1_ratio': 0.44747136119648406, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3578008383415435e-05, 'max_iter': 4048}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  63%|█████████████████████████████████████████████████████████████████████▌                                        | 316/500 [55:14<26:20,  8.59s/it]

[I 2026-05-19 16:32:06,209] Trial 314 finished with value: 0.9499119254612742 and parameters: {'solver': 'saga', 'C': 0.021711895318493494, 'l1_ratio': 0.44918909394275797, 'class_weight': None, 'fit_intercept': True, 'tol': 7.902394016937323e-06, 'max_iter': 4057}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  63%|█████████████████████████████████████████████████████████████████████▋                                        | 317/500 [55:14<18:39,  6.12s/it]

[I 2026-05-19 16:32:06,547] Trial 316 finished with value: 0.9499118830015532 and parameters: {'solver': 'saga', 'C': 0.022353156983936754, 'l1_ratio': 0.44903813729863873, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4124349567906094e-05, 'max_iter': 4051}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  64%|█████████████████████████████████████████████████████████████████████▉                                        | 318/500 [55:17<16:08,  5.32s/it]

[I 2026-05-19 16:32:10,012] Trial 325 finished with value: 0.94991074981087 and parameters: {'solver': 'saga', 'C': 0.025099505296264677, 'l1_ratio': 0.313007491741618, 'class_weight': None, 'fit_intercept': True, 'tol': 0.009811830567561618, 'max_iter': 4064}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  64%|██████████████████████████████████████████████████████████████████████▏                                       | 319/500 [55:19<12:10,  4.04s/it]

[I 2026-05-19 16:32:11,056] Trial 317 finished with value: 0.9499119378175094 and parameters: {'solver': 'saga', 'C': 0.02353214578492833, 'l1_ratio': 0.4543576031517811, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4217945674366102e-05, 'max_iter': 4064}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  64%|██████████████████████████████████████████████████████████████████████▍                                       | 320/500 [55:58<44:00, 14.67s/it]

[I 2026-05-19 16:32:50,501] Trial 318 finished with value: 0.9499120326384931 and parameters: {'solver': 'saga', 'C': 0.022204186713447687, 'l1_ratio': 0.31496301476852573, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3740136877308506e-05, 'max_iter': 4248}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  64%|██████████████████████████████████████████████████████████████████████▌                                       | 321/500 [56:06<37:56, 12.72s/it]

[I 2026-05-19 16:32:58,666] Trial 319 finished with value: 0.949912046463816 and parameters: {'solver': 'saga', 'C': 0.023604333786189834, 'l1_ratio': 0.3156426594680879, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4248410921889995e-05, 'max_iter': 4049}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  64%|██████████████████████████████████████████████████████████████████████▊                                       | 322/500 [56:10<29:55, 10.09s/it]

[I 2026-05-19 16:33:02,646] Trial 320 finished with value: 0.9499120189728337 and parameters: {'solver': 'saga', 'C': 0.02342890599700699, 'l1_ratio': 0.3109051658147014, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5114502123038374e-05, 'max_iter': 4062}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  65%|███████████████████████████████████████████████████████████████████████                                       | 323/500 [56:25<33:53, 11.49s/it]

[I 2026-05-19 16:33:17,403] Trial 321 finished with value: 0.9499120339390608 and parameters: {'solver': 'saga', 'C': 0.022791034645300693, 'l1_ratio': 0.3111239627456106, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4001732668818112e-05, 'max_iter': 4260}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  65%|███████████████████████████████████████████████████████████████████████▎                                      | 324/500 [56:26<24:37,  8.40s/it]

[I 2026-05-19 16:33:18,586] Trial 322 finished with value: 0.9499120365422107 and parameters: {'solver': 'saga', 'C': 0.024467697395698436, 'l1_ratio': 0.34182597643546064, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3632318416132067e-05, 'max_iter': 4066}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  65%|███████████████████████████████████████████████████████████████████████▌                                      | 325/500 [56:48<35:56, 12.32s/it]

[I 2026-05-19 16:33:40,062] Trial 323 finished with value: 0.9499113925058712 and parameters: {'solver': 'saga', 'C': 0.024398266131200837, 'l1_ratio': 0.05295473643414024, 'class_weight': None, 'fit_intercept': True, 'tol': 1.391594541394563e-05, 'max_iter': 4064}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  65%|███████████████████████████████████████████████████████████████████████▋                                      | 326/500 [56:52<28:39,  9.88s/it]

[I 2026-05-19 16:33:44,253] Trial 326 finished with value: 0.9499119503379065 and parameters: {'solver': 'saga', 'C': 0.024761464753703173, 'l1_ratio': 0.4248204178963307, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5197167778134387e-05, 'max_iter': 4061}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  65%|███████████████████████████████████████████████████████████████████████▉                                      | 327/500 [57:00<26:40,  9.25s/it]

[I 2026-05-19 16:33:52,040] Trial 324 finished with value: 0.9499121087660898 and parameters: {'solver': 'saga', 'C': 0.024226265481265177, 'l1_ratio': 0.3057154462238374, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3994396276420287e-05, 'max_iter': 4068}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  66%|████████████████████████████████████████████████████████████████████████▏                                     | 328/500 [57:09<26:27,  9.23s/it]

[I 2026-05-19 16:34:01,222] Trial 329 finished with value: 0.9499120702214544 and parameters: {'solver': 'saga', 'C': 0.02787133446704992, 'l1_ratio': 0.42754954270979073, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1612385775085411e-05, 'max_iter': 4278}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  66%|████████████████████████████████████████████████████████████████████████▍                                     | 329/500 [57:20<28:26,  9.98s/it]

[I 2026-05-19 16:34:12,955] Trial 328 finished with value: 0.9499121447155293 and parameters: {'solver': 'saga', 'C': 0.026206489272820273, 'l1_ratio': 0.32490443042673106, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2650473207094402e-05, 'max_iter': 3760}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  66%|████████████████████████████████████████████████████████████████████████▌                                     | 330/500 [57:22<21:31,  7.60s/it]

[I 2026-05-19 16:34:14,990] Trial 327 finished with value: 0.949912114460845 and parameters: {'solver': 'saga', 'C': 0.02705816870623587, 'l1_ratio': 0.3452836391229271, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4393990358726297e-05, 'max_iter': 4233}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  66%|████████████████████████████████████████████████████████████████████████▊                                     | 331/500 [57:31<21:55,  7.78s/it]

[I 2026-05-19 16:34:23,198] Trial 330 finished with value: 0.9499120344247318 and parameters: {'solver': 'saga', 'C': 0.027777577185348932, 'l1_ratio': 0.33811990186221513, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2154225482631116e-05, 'max_iter': 4248}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  66%|█████████████████████████████████████████████████████████████████████████                                     | 332/500 [58:11<49:01, 17.51s/it]

[I 2026-05-19 16:35:03,404] Trial 340 finished with value: 0.9498941967908385 and parameters: {'solver': 'saga', 'C': 0.013259974299292461, 'l1_ratio': 0.42657479862603254, 'class_weight': None, 'fit_intercept': False, 'tol': 1.1820078084700334e-05, 'max_iter': 4165}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  67%|█████████████████████████████████████████████████████████████████████████▎                                    | 333/500 [58:11<34:31, 12.41s/it]

[I 2026-05-19 16:35:03,900] Trial 339 finished with value: 0.9498961615074206 and parameters: {'solver': 'saga', 'C': 0.014637724126475736, 'l1_ratio': 0.3439860883130272, 'class_weight': None, 'fit_intercept': False, 'tol': 1.183417579580788e-05, 'max_iter': 4176}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  67%|█████████████████████████████████████████████████████████████████████████▍                                    | 334/500 [58:12<24:29,  8.85s/it]

[I 2026-05-19 16:35:04,465] Trial 331 finished with value: 0.9499120001007902 and parameters: {'solver': 'saga', 'C': 0.028865251238164108, 'l1_ratio': 0.34302905195742495, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2768269142773723e-05, 'max_iter': 3756}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  67%|█████████████████████████████████████████████████████████████████████████▋                                    | 335/500 [58:12<17:17,  6.29s/it]

[I 2026-05-19 16:35:04,762] Trial 341 finished with value: 0.949893877956621 and parameters: {'solver': 'saga', 'C': 0.012843692244709146, 'l1_ratio': 0.42622696882829975, 'class_weight': None, 'fit_intercept': False, 'tol': 1.2260702059036251e-05, 'max_iter': 4258}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  67%|█████████████████████████████████████████████████████████████████████████▉                                    | 336/500 [58:18<17:01,  6.23s/it]

[I 2026-05-19 16:35:10,849] Trial 332 finished with value: 0.9499120241760975 and parameters: {'solver': 'saga', 'C': 0.028549826567318498, 'l1_ratio': 0.3459448094287952, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1334137223068358e-05, 'max_iter': 4186}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  67%|██████████████████████████████████████████████████████████████████████████▏                                   | 337/500 [58:23<15:23,  5.66s/it]

[I 2026-05-19 16:35:15,194] Trial 333 finished with value: 0.9499119852978503 and parameters: {'solver': 'saga', 'C': 0.028968777926345154, 'l1_ratio': 0.3455933697548005, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2035591106599722e-05, 'max_iter': 3758}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  68%|██████████████████████████████████████████████████████████████████████████▎                                   | 338/500 [58:35<20:59,  7.78s/it]

[I 2026-05-19 16:35:27,909] Trial 334 finished with value: 0.9499120220608012 and parameters: {'solver': 'saga', 'C': 0.028119226349619626, 'l1_ratio': 0.33633088652257104, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1611557948286239e-05, 'max_iter': 4178}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  68%|██████████████████████████████████████████████████████████████████████████▌                                   | 339/500 [58:36<14:48,  5.52s/it]

[I 2026-05-19 16:35:28,156] Trial 342 finished with value: 0.9498962654537071 and parameters: {'solver': 'saga', 'C': 0.014917233537887905, 'l1_ratio': 0.345780928199267, 'class_weight': None, 'fit_intercept': False, 'tol': 1.20065836095156e-05, 'max_iter': 4212}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  68%|██████████████████████████████████████████████████████████████████████████▊                                   | 340/500 [58:37<11:16,  4.23s/it]

[I 2026-05-19 16:35:29,384] Trial 337 finished with value: 0.9499111607531294 and parameters: {'solver': 'saga', 'C': 0.014095748923236465, 'l1_ratio': 0.34577749801450025, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0954641774840125e-05, 'max_iter': 3753}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  68%|███████████████████████████████████████████████████████████████████████████                                   | 341/500 [58:37<08:10,  3.08s/it]

[I 2026-05-19 16:35:29,792] Trial 336 finished with value: 0.9499120645266851 and parameters: {'solver': 'saga', 'C': 0.029925889127245725, 'l1_ratio': 0.4299275036780794, 'class_weight': None, 'fit_intercept': True, 'tol': 1.17034247586976e-05, 'max_iter': 3741}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  68%|███████████████████████████████████████████████████████████████████████████▏                                  | 342/500 [58:41<08:58,  3.41s/it]

[I 2026-05-19 16:35:33,945] Trial 344 finished with value: 0.949911077950649 and parameters: {'solver': 'saga', 'C': 0.01728167414006208, 'l1_ratio': 0.3991042608451984, 'class_weight': None, 'fit_intercept': True, 'tol': 0.003285141585596514, 'max_iter': 4170}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  69%|███████████████████████████████████████████████████████████████████████████▍                                  | 343/500 [58:44<08:00,  3.06s/it]

[I 2026-05-19 16:35:36,214] Trial 335 finished with value: 0.9499119472331564 and parameters: {'solver': 'saga', 'C': 0.030495729396052697, 'l1_ratio': 0.34333616771085435, 'class_weight': None, 'fit_intercept': True, 'tol': 1.211048117158084e-05, 'max_iter': 3739}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  69%|███████████████████████████████████████████████████████████████████████████▋                                  | 344/500 [58:47<07:49,  3.01s/it]

[I 2026-05-19 16:35:39,083] Trial 338 finished with value: 0.9499111934475295 and parameters: {'solver': 'saga', 'C': 0.014562925769845638, 'l1_ratio': 0.3450675353804292, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1808075451553631e-05, 'max_iter': 4192}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  69%|███████████████████████████████████████████████████████████████████████████▉                                  | 345/500 [58:58<14:25,  5.59s/it]

[I 2026-05-19 16:35:50,687] Trial 351 finished with value: 0.9499103959988837 and parameters: {'solver': 'saga', 'C': 0.04673532681820954, 'l1_ratio': 0.3918653987129363, 'class_weight': None, 'fit_intercept': True, 'tol': 0.006661790162697467, 'max_iter': 4362}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  69%|████████████████████████████████████████████████████████████████████████████                                  | 346/500 [59:34<37:41, 14.68s/it]

[I 2026-05-19 16:36:26,612] Trial 346 finished with value: 0.949910765150227 and parameters: {'solver': 'saga', 'C': 0.01684659211798795, 'l1_ratio': 0.47795615393098767, 'class_weight': None, 'fit_intercept': True, 'tol': 1.125091721789704e-05, 'max_iter': 4180}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  69%|████████████████████████████████████████████████████████████████████████████▎                                 | 347/500 [59:43<33:13, 13.03s/it]

[I 2026-05-19 16:36:35,779] Trial 345 finished with value: 0.9499113627861281 and parameters: {'solver': 'saga', 'C': 0.01692402340993266, 'l1_ratio': 0.38830297184977186, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0217773515223915e-05, 'max_iter': 4318}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  70%|████████████████████████████████████████████████████████████████████████████▌                                 | 348/500 [59:55<32:20, 12.76s/it]

[I 2026-05-19 16:36:47,922] Trial 348 finished with value: 0.9499110693353128 and parameters: {'solver': 'saga', 'C': 0.015650916023398187, 'l1_ratio': 0.3981592851511451, 'class_weight': None, 'fit_intercept': True, 'tol': 2.10247178450157e-05, 'max_iter': 3363}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  70%|███████████████████████████████████████████████████████████████████████████▍                                | 349/500 [1:00:00<26:11, 10.40s/it]

[I 2026-05-19 16:36:52,823] Trial 343 finished with value: 0.949911347818334 and parameters: {'solver': 'saga', 'C': 0.015646629764248233, 'l1_ratio': 0.3416133290353476, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2719464099120186e-05, 'max_iter': 4200}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  70%|███████████████████████████████████████████████████████████████████████████▌                                | 350/500 [1:00:09<24:27,  9.79s/it]

[I 2026-05-19 16:37:01,169] Trial 349 finished with value: 0.9499113076431709 and parameters: {'solver': 'saga', 'C': 0.01653337098926128, 'l1_ratio': 0.39456041194612446, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6099687157337128e-05, 'max_iter': 4312}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  70%|███████████████████████████████████████████████████████████████████████████▊                                | 351/500 [1:00:30<32:43, 13.18s/it]

[I 2026-05-19 16:37:22,247] Trial 354 finished with value: 0.9499117957857731 and parameters: {'solver': 'saga', 'C': 0.045861733161803996, 'l1_ratio': 0.47501290228108783, 'class_weight': None, 'fit_intercept': True, 'tol': 2.072543164622272e-05, 'max_iter': 4385}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  70%|██████████████████████████████████████████████████████████████████████████▌                               | 352/500 [1:01:21<1:00:57, 24.71s/it]

[I 2026-05-19 16:38:13,890] Trial 359 finished with value: 0.9498967272941693 and parameters: {'solver': 'saga', 'C': 0.0052150020090413265, 'l1_ratio': 0.27102622901916024, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.5830693512238623e-05, 'max_iter': 3961}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  71%|████████████████████████████████████████████████████████████████████████████▏                               | 353/500 [1:01:29<47:44, 19.48s/it]

[I 2026-05-19 16:38:21,171] Trial 361 finished with value: 0.9498961276921977 and parameters: {'solver': 'saga', 'C': 0.004911180663236383, 'l1_ratio': 0.26816764772795076, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.5144478114114866e-05, 'max_iter': 2474}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  71%|████████████████████████████████████████████████████████████████████████████▍                               | 354/500 [1:01:35<37:35, 15.45s/it]

[I 2026-05-19 16:38:27,214] Trial 352 finished with value: 0.9499025340527174 and parameters: {'solver': 'saga', 'C': 0.04063989830969466, 'l1_ratio': 0.4013920873489415, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.0043477776702154e-05, 'max_iter': 4363}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  71%|████████████████████████████████████████████████████████████████████████████▋                               | 355/500 [1:01:41<30:59, 12.82s/it]

[I 2026-05-19 16:38:33,902] Trial 353 finished with value: 0.9499025151793589 and parameters: {'solver': 'saga', 'C': 0.047123506420529634, 'l1_ratio': 0.39290475345121034, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.01437569079057e-05, 'max_iter': 4328}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  71%|████████████████████████████████████████████████████████████████████████████▉                               | 356/500 [1:01:44<23:47,  9.91s/it]

[I 2026-05-19 16:38:37,014] Trial 350 finished with value: 0.9499025138781196 and parameters: {'solver': 'saga', 'C': 0.047451136481315874, 'l1_ratio': 0.3936861288249423, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.526697498314039e-05, 'max_iter': 4313}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  71%|█████████████████████████████████████████████████████████████████████████████                               | 357/500 [1:01:49<20:01,  8.41s/it]

[I 2026-05-19 16:38:41,910] Trial 355 finished with value: 0.9499025506440717 and parameters: {'solver': 'saga', 'C': 0.04270288954198121, 'l1_ratio': 0.39323191286855347, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.6281741765986896e-05, 'max_iter': 4298}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  72%|█████████████████████████████████████████████████████████████████████████████▎                              | 358/500 [1:01:55<17:42,  7.48s/it]

[I 2026-05-19 16:38:47,248] Trial 356 finished with value: 0.9499026334352821 and parameters: {'solver': 'saga', 'C': 0.044574080180337074, 'l1_ratio': 0.27302751816141874, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.9860515114995394e-05, 'max_iter': 4316}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  72%|█████████████████████████████████████████████████████████████████████████████▌                              | 359/500 [1:01:56<13:01,  5.54s/it]

[I 2026-05-19 16:38:48,262] Trial 347 finished with value: 0.9499010449448111 and parameters: {'solver': 'saga', 'C': 98.40851316737242, 'l1_ratio': 0.38947650036334364, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.2311884202393032e-05, 'max_iter': 4364}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  72%|█████████████████████████████████████████████████████████████████████████████▊                              | 360/500 [1:02:22<27:13, 11.66s/it]

[I 2026-05-19 16:39:14,209] Trial 362 finished with value: 0.949898439882439 and parameters: {'solver': 'saga', 'C': 0.009741887024408749, 'l1_ratio': 0.4299625753557918, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.569805512431484e-05, 'max_iter': 2492}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  72%|█████████████████████████████████████████████████████████████████████████████▉                              | 361/500 [1:02:23<19:33,  8.44s/it]

[I 2026-05-19 16:39:15,131] Trial 370 finished with value: 0.9499058066607949 and parameters: {'solver': 'saga', 'C': 0.009419188194801597, 'l1_ratio': 0.42709528963947574, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0014480990385971658, 'max_iter': 3970}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  72%|██████████████████████████████████████████████████████████████████████████████▏                             | 362/500 [1:02:24<14:14,  6.20s/it]

[I 2026-05-19 16:39:16,083] Trial 363 finished with value: 0.9499065954477937 and parameters: {'solver': 'saga', 'C': 0.010000819041623909, 'l1_ratio': 0.4215983890849148, 'class_weight': None, 'fit_intercept': True, 'tol': 3.249770968215552e-05, 'max_iter': 3978}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  73%|██████████████████████████████████████████████████████████████████████████████▍                             | 363/500 [1:02:24<10:06,  4.43s/it]

[I 2026-05-19 16:39:16,383] Trial 358 finished with value: 0.9499025838212816 and parameters: {'solver': 'saga', 'C': 0.04297323347516578, 'l1_ratio': 0.2734212433732012, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.925513370894608e-05, 'max_iter': 3991}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  73%|██████████████████████████████████████████████████████████████████████████████▌                             | 364/500 [1:02:25<07:55,  3.50s/it]

[I 2026-05-19 16:39:17,692] Trial 357 finished with value: 0.9499026100112136 and parameters: {'solver': 'saga', 'C': 0.04243720055324603, 'l1_ratio': 0.2722846336565299, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.0502961109579223e-05, 'max_iter': 4295}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  73%|██████████████████████████████████████████████████████████████████████████████▊                             | 365/500 [1:02:41<16:13,  7.21s/it]

[I 2026-05-19 16:39:33,579] Trial 364 finished with value: 0.9499065728371037 and parameters: {'solver': 'saga', 'C': 0.010043656443262017, 'l1_ratio': 0.4246202375089111, 'class_weight': None, 'fit_intercept': True, 'tol': 8.856791336540329e-06, 'max_iter': 3974}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  73%|███████████████████████████████████████████████████████████████████████████████                             | 366/500 [1:02:47<14:56,  6.69s/it]

[I 2026-05-19 16:39:39,053] Trial 365 finished with value: 0.9499064171638496 and parameters: {'solver': 'saga', 'C': 0.009873839671735081, 'l1_ratio': 0.42763902947646937, 'class_weight': None, 'fit_intercept': True, 'tol': 9.359762864767031e-06, 'max_iter': 3963}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  73%|███████████████████████████████████████████████████████████████████████████████▎                            | 367/500 [1:02:56<16:22,  7.39s/it]

[I 2026-05-19 16:39:48,082] Trial 367 finished with value: 0.9499054862057175 and parameters: {'solver': 'saga', 'C': 0.008964245400798565, 'l1_ratio': 0.4299521733955308, 'class_weight': None, 'fit_intercept': True, 'tol': 9.203085270936042e-06, 'max_iter': 3963}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  74%|███████████████████████████████████████████████████████████████████████████████▍                            | 368/500 [1:03:30<34:25, 15.65s/it]

[I 2026-05-19 16:40:23,001] Trial 368 finished with value: 0.94991184198661 and parameters: {'solver': 'saga', 'C': 0.036259892180011764, 'l1_ratio': 0.43059188865790293, 'class_weight': None, 'fit_intercept': True, 'tol': 3.221246740069832e-05, 'max_iter': 3975}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  74%|███████████████████████████████████████████████████████████████████████████████▋                            | 369/500 [1:03:34<26:09, 11.98s/it]

[I 2026-05-19 16:40:26,414] Trial 369 finished with value: 0.9499118611831079 and parameters: {'solver': 'saga', 'C': 0.03440879187955794, 'l1_ratio': 0.4351361468113081, 'class_weight': None, 'fit_intercept': True, 'tol': 3.097506641790459e-05, 'max_iter': 2706}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  74%|███████████████████████████████████████████████████████████████████████████████▉                            | 370/500 [1:03:57<33:08, 15.29s/it]

[I 2026-05-19 16:40:49,444] Trial 360 finished with value: 0.9499010542166889 and parameters: {'solver': 'saga', 'C': 37.99225719285559, 'l1_ratio': 0.42366715318204723, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.463376971981785e-05, 'max_iter': 3981}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  74%|████████████████████████████████████████████████████████████████████████████████▏                           | 371/500 [1:04:13<33:17, 15.48s/it]

[I 2026-05-19 16:41:05,372] Trial 377 finished with value: 0.9499113418068752 and parameters: {'solver': 'saga', 'C': 0.019973984002149104, 'l1_ratio': 0.4899842674281815, 'class_weight': None, 'fit_intercept': True, 'tol': 7.165659274514594e-06, 'max_iter': 4134}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  74%|████████████████████████████████████████████████████████████████████████████████▎                           | 372/500 [1:04:18<26:26, 12.40s/it]

[I 2026-05-19 16:41:10,565] Trial 371 finished with value: 0.949912009215271 and parameters: {'solver': 'saga', 'C': 0.03207339969373367, 'l1_ratio': 0.423592828935846, 'class_weight': None, 'fit_intercept': True, 'tol': 8.70240494000883e-06, 'max_iter': 3982}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  75%|████████████████████████████████████████████████████████████████████████████████▌                           | 373/500 [1:04:30<26:01, 12.29s/it]

[I 2026-05-19 16:41:22,615] Trial 375 finished with value: 0.9499119415493563 and parameters: {'solver': 'saga', 'C': 0.020241494598933357, 'l1_ratio': 0.3243293979434285, 'class_weight': None, 'fit_intercept': True, 'tol': 9.121849413408845e-06, 'max_iter': 4120}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  75%|████████████████████████████████████████████████████████████████████████████████▊                           | 374/500 [1:04:41<24:49, 11.82s/it]

[I 2026-05-19 16:41:33,342] Trial 374 finished with value: 0.9499118680167458 and parameters: {'solver': 'saga', 'C': 0.020421273481391625, 'l1_ratio': 0.3016665713293462, 'class_weight': None, 'fit_intercept': True, 'tol': 6.991948190658439e-06, 'max_iter': 3816}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  75%|█████████████████████████████████████████████████████████████████████████████████                           | 375/500 [1:04:42<18:16,  8.77s/it]

[I 2026-05-19 16:41:34,980] Trial 372 finished with value: 0.9499118401901019 and parameters: {'solver': 'saga', 'C': 0.03400391316885527, 'l1_ratio': 0.304554050461263, 'class_weight': None, 'fit_intercept': True, 'tol': 9.04756065438372e-06, 'max_iter': 2695}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  75%|█████████████████████████████████████████████████████████████████████████████████▏                          | 376/500 [1:04:50<17:17,  8.37s/it]

[I 2026-05-19 16:41:42,407] Trial 373 finished with value: 0.9499118802078822 and parameters: {'solver': 'saga', 'C': 0.033663275019538356, 'l1_ratio': 0.31370250429863866, 'class_weight': None, 'fit_intercept': True, 'tol': 9.136427452151396e-06, 'max_iter': 3814}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  75%|█████████████████████████████████████████████████████████████████████████████████▍                          | 377/500 [1:05:03<20:14,  9.88s/it]

[I 2026-05-19 16:41:55,812] Trial 380 finished with value: 0.9499115248100702 and parameters: {'solver': 'saga', 'C': 0.020532058004035417, 'l1_ratio': 0.4863011863343694, 'class_weight': None, 'fit_intercept': True, 'tol': 7.015352729804958e-06, 'max_iter': 4124}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  76%|█████████████████████████████████████████████████████████████████████████████████▋                          | 378/500 [1:05:05<15:01,  7.39s/it]

[I 2026-05-19 16:41:57,396] Trial 376 finished with value: 0.949911878744846 and parameters: {'solver': 'saga', 'C': 0.03145448757723664, 'l1_ratio': 0.30030979895967796, 'class_weight': None, 'fit_intercept': True, 'tol': 9.199572656308765e-06, 'max_iter': 3811}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  76%|█████████████████████████████████████████████████████████████████████████████████▊                          | 379/500 [1:05:22<20:38, 10.24s/it]

[I 2026-05-19 16:42:14,281] Trial 378 finished with value: 0.9499118863910997 and parameters: {'solver': 'saga', 'C': 0.03093816664553016, 'l1_ratio': 0.3047765877608207, 'class_weight': None, 'fit_intercept': True, 'tol': 7.138546181057691e-06, 'max_iter': 3802}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  76%|██████████████████████████████████████████████████████████████████████████████████                          | 380/500 [1:05:52<32:29, 16.25s/it]

[I 2026-05-19 16:42:44,542] Trial 379 finished with value: 0.9499119613941687 and parameters: {'solver': 'saga', 'C': 0.019965393687317434, 'l1_ratio': 0.31560928163897495, 'class_weight': None, 'fit_intercept': True, 'tol': 7.436604122293403e-06, 'max_iter': 4136}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  76%|██████████████████████████████████████████████████████████████████████████████████▎                         | 381/500 [1:06:00<27:20, 13.78s/it]

[I 2026-05-19 16:42:52,582] Trial 384 finished with value: 0.9499113675086109 and parameters: {'solver': 'saga', 'C': 0.019322914247876553, 'l1_ratio': 0.47183827089788444, 'class_weight': None, 'fit_intercept': True, 'tol': 7.235057967708951e-06, 'max_iter': 3819}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  76%|██████████████████████████████████████████████████████████████████████████████████▌                         | 382/500 [1:06:06<22:17, 11.34s/it]

[I 2026-05-19 16:42:58,214] Trial 366 finished with value: 0.9499091287917485 and parameters: {'solver': 'saga', 'C': 4.047092409353739, 'l1_ratio': 0.429491765717377, 'class_weight': None, 'fit_intercept': True, 'tol': 9.19035938512709e-06, 'max_iter': 2040}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  77%|██████████████████████████████████████████████████████████████████████████████████▋                         | 383/500 [1:06:22<24:55, 12.78s/it]

[I 2026-05-19 16:43:14,365] Trial 381 finished with value: 0.9499118524004553 and parameters: {'solver': 'saga', 'C': 0.020702389326425014, 'l1_ratio': 0.3029110168015723, 'class_weight': None, 'fit_intercept': True, 'tol': 7.4234439959289186e-06, 'max_iter': 3814}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  77%|██████████████████████████████████████████████████████████████████████████████████▉                         | 384/500 [1:06:31<22:21, 11.56s/it]

[I 2026-05-19 16:43:23,088] Trial 385 finished with value: 0.9499121444017009 and parameters: {'solver': 'saga', 'C': 0.02907255918395455, 'l1_ratio': 0.47218339530415004, 'class_weight': None, 'fit_intercept': True, 'tol': 9.654989948151049e-06, 'max_iter': 3811}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  77%|███████████████████████████████████████████████████████████████████████████████████▏                        | 385/500 [1:06:35<18:05,  9.43s/it]

[I 2026-05-19 16:43:27,550] Trial 387 finished with value: 0.9499116367260927 and parameters: {'solver': 'saga', 'C': 0.02035787665640911, 'l1_ratio': 0.47304306729283246, 'class_weight': None, 'fit_intercept': True, 'tol': 7.097033652858198e-06, 'max_iter': 4107}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  77%|███████████████████████████████████████████████████████████████████████████████████▍                        | 386/500 [1:06:36<12:59,  6.83s/it]

[I 2026-05-19 16:43:28,325] Trial 383 finished with value: 0.9499118798948445 and parameters: {'solver': 'saga', 'C': 0.01945404624924868, 'l1_ratio': 0.3068220533210368, 'class_weight': None, 'fit_intercept': True, 'tol': 6.538484850054939e-06, 'max_iter': 3819}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  77%|███████████████████████████████████████████████████████████████████████████████████▌                        | 387/500 [1:06:38<10:20,  5.49s/it]

[I 2026-05-19 16:43:30,665] Trial 382 finished with value: 0.9499118564583726 and parameters: {'solver': 'saga', 'C': 0.03265830253275851, 'l1_ratio': 0.3066916403124263, 'class_weight': None, 'fit_intercept': True, 'tol': 7.0473387582596e-06, 'max_iter': 3824}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  78%|███████████████████████████████████████████████████████████████████████████████████▊                        | 388/500 [1:06:39<07:52,  4.22s/it]

[I 2026-05-19 16:43:31,914] Trial 389 finished with value: 0.949911857437284 and parameters: {'solver': 'saga', 'C': 0.02022441284986242, 'l1_ratio': 0.24123881902410815, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011164239302168312, 'max_iter': 1832}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  78%|████████████████████████████████████████████████████████████████████████████████████                        | 389/500 [1:06:42<07:09,  3.87s/it]

[I 2026-05-19 16:43:34,967] Trial 386 finished with value: 0.9499118548497412 and parameters: {'solver': 'saga', 'C': 0.020030071850993925, 'l1_ratio': 0.35968282336512514, 'class_weight': None, 'fit_intercept': True, 'tol': 7.02406311585653e-06, 'max_iter': 3824}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  78%|████████████████████████████████████████████████████████████████████████████████████▏                       | 390/500 [1:07:01<15:07,  8.25s/it]

[I 2026-05-19 16:43:53,458] Trial 388 finished with value: 0.949911910633346 and parameters: {'solver': 'saga', 'C': 0.03167021874819016, 'l1_ratio': 0.3749805680627997, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0630238011761748e-05, 'max_iter': 1868}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  78%|████████████████████████████████████████████████████████████████████████████████████▍                       | 391/500 [1:07:16<18:42, 10.30s/it]

[I 2026-05-19 16:44:08,519] Trial 390 finished with value: 0.9499118571266039 and parameters: {'solver': 'saga', 'C': 0.020100357262311387, 'l1_ratio': 0.36032524783265646, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0934213039057794e-05, 'max_iter': 4086}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  78%|████████████████████████████████████████████████████████████████████████████████████▋                       | 392/500 [1:07:43<27:18, 15.17s/it]

[I 2026-05-19 16:44:35,066] Trial 396 finished with value: 0.9499112958910588 and parameters: {'solver': 'saga', 'C': 0.06715021009696737, 'l1_ratio': 0.5024436652878558, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00035263515334781097, 'max_iter': 3688}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  79%|████████████████████████████████████████████████████████████████████████████████████▉                       | 393/500 [1:08:14<35:30, 19.91s/it]

[I 2026-05-19 16:45:06,036] Trial 392 finished with value: 0.9499110310567745 and parameters: {'solver': 'saga', 'C': 0.07568757156919015, 'l1_ratio': 0.3671352465636377, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0868790009812234e-05, 'max_iter': 3651}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  79%|█████████████████████████████████████████████████████████████████████████████████████                       | 394/500 [1:08:25<30:45, 17.41s/it]

[I 2026-05-19 16:45:17,615] Trial 393 finished with value: 0.9499109811169133 and parameters: {'solver': 'saga', 'C': 0.07916082041348783, 'l1_ratio': 0.3592478579436758, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0889242299522621e-05, 'max_iter': 4078}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  79%|█████████████████████████████████████████████████████████████████████████████████████▎                      | 395/500 [1:08:35<26:25, 15.10s/it]

[I 2026-05-19 16:45:27,316] Trial 395 finished with value: 0.9499115122443487 and parameters: {'solver': 'saga', 'C': 0.062046924904169076, 'l1_ratio': 0.5103830259750589, 'class_weight': None, 'fit_intercept': True, 'tol': 6.032367234657359e-06, 'max_iter': 3673}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  79%|█████████████████████████████████████████████████████████████████████████████████████▌                      | 396/500 [1:08:36<19:06, 11.02s/it]

[I 2026-05-19 16:45:28,833] Trial 397 finished with value: 0.9499112745804258 and parameters: {'solver': 'saga', 'C': 0.06591904503435839, 'l1_ratio': 0.4683485119797022, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0644032645449208e-05, 'max_iter': 3627}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  79%|█████████████████████████████████████████████████████████████████████████████████████▊                      | 397/500 [1:08:39<14:35,  8.50s/it]

[I 2026-05-19 16:45:31,441] Trial 398 finished with value: 0.9499111123964636 and parameters: {'solver': 'saga', 'C': 0.07491646502375812, 'l1_ratio': 0.465624778366542, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0588437069227877e-05, 'max_iter': 3440}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  80%|█████████████████████████████████████████████████████████████████████████████████████▉                      | 398/500 [1:08:40<10:38,  6.26s/it]

[I 2026-05-19 16:45:32,484] Trial 400 finished with value: 0.9499114008145497 and parameters: {'solver': 'saga', 'C': 0.06595357198511825, 'l1_ratio': 0.5043650169447261, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0589504809264705e-05, 'max_iter': 4062}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  80%|██████████████████████████████████████████████████████████████████████████████████████▏                     | 399/500 [1:08:40<07:33,  4.49s/it]

[I 2026-05-19 16:45:32,844] Trial 394 finished with value: 0.9499111852701473 and parameters: {'solver': 'saga', 'C': 0.060798812396854016, 'l1_ratio': 0.3616987324208081, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0674666997838849e-05, 'max_iter': 4085}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  80%|██████████████████████████████████████████████████████████████████████████████████████▍                     | 400/500 [1:08:41<05:39,  3.39s/it]

[I 2026-05-19 16:45:33,683] Trial 399 finished with value: 0.9499110079602667 and parameters: {'solver': 'saga', 'C': 0.0822276874465956, 'l1_ratio': 0.46741320888023796, 'class_weight': None, 'fit_intercept': True, 'tol': 1.079532314106552e-05, 'max_iter': 4041}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  80%|██████████████████████████████████████████████████████████████████████████████████████▌                     | 401/500 [1:08:53<09:37,  5.84s/it]

[I 2026-05-19 16:45:45,215] Trial 391 finished with value: 0.9499103673591481 and parameters: {'solver': 'saga', 'C': 0.074191060241595, 'l1_ratio': 0.09696633635400113, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0370188065066765e-05, 'max_iter': 4095}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  80%|██████████████████████████████████████████████████████████████████████████████████████▊                     | 402/500 [1:08:59<09:47,  5.99s/it]

[I 2026-05-19 16:45:51,564] Trial 401 finished with value: 0.9499114995552569 and parameters: {'solver': 'saga', 'C': 0.06086642979713619, 'l1_ratio': 0.4879796989884336, 'class_weight': None, 'fit_intercept': True, 'tol': 1.038312789116724e-05, 'max_iter': 3663}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  81%|███████████████████████████████████████████████████████████████████████████████████████                     | 403/500 [1:09:09<11:49,  7.32s/it]

[I 2026-05-19 16:46:01,973] Trial 402 finished with value: 0.9499110583894647 and parameters: {'solver': 'saga', 'C': 0.08544638913354902, 'l1_ratio': 0.5123337933397571, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3480812019810094e-05, 'max_iter': 3638}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  81%|███████████████████████████████████████████████████████████████████████████████████████▎                    | 404/500 [1:09:36<21:05, 13.18s/it]

[I 2026-05-19 16:46:28,844] Trial 403 finished with value: 0.9499117079410635 and parameters: {'solver': 'saga', 'C': 0.05053754714054387, 'l1_ratio': 0.46517775515624255, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3529808750511936e-05, 'max_iter': 4225}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  81%|███████████████████████████████████████████████████████████████████████████████████████▍                    | 405/500 [1:10:00<25:40, 16.22s/it]

[I 2026-05-19 16:46:52,136] Trial 413 finished with value: 0.949910302841573 and parameters: {'solver': 'saga', 'C': 0.028520623875356532, 'l1_ratio': 0.8177448528341241, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4337352903510383e-05, 'max_iter': 4222}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  81%|███████████████████████████████████████████████████████████████████████████████████████▋                    | 406/500 [1:10:09<22:17, 14.23s/it]

[I 2026-05-19 16:47:01,728] Trial 404 finished with value: 0.9499115361565297 and parameters: {'solver': 'saga', 'C': 0.057305535576135776, 'l1_ratio': 0.46660863947162834, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2957648837030795e-05, 'max_iter': 4060}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  81%|███████████████████████████████████████████████████████████████████████████████████████▉                    | 407/500 [1:10:18<19:36, 12.65s/it]

[I 2026-05-19 16:47:10,711] Trial 405 finished with value: 0.9499117980620551 and parameters: {'solver': 'saga', 'C': 0.0470763606073338, 'l1_ratio': 0.46710106296083787, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3338155957935948e-05, 'max_iter': 4473}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  82%|████████████████████████████████████████████████████████████████████████████████████████▏                   | 408/500 [1:10:22<15:10,  9.89s/it]

[I 2026-05-19 16:47:14,161] Trial 407 finished with value: 0.9499121086126104 and parameters: {'solver': 'saga', 'C': 0.028565987259019272, 'l1_ratio': 0.4505234279929929, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3398935988441861e-05, 'max_iter': 4213}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  82%|████████████████████████████████████████████████████████████████████████████████████████▎                   | 409/500 [1:10:34<16:10, 10.66s/it]

[I 2026-05-19 16:47:26,607] Trial 406 finished with value: 0.949911609033998 and parameters: {'solver': 'saga', 'C': 0.05318254282249817, 'l1_ratio': 0.45637887689987766, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3071309486640907e-05, 'max_iter': 4237}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  82%|████████████████████████████████████████████████████████████████████████████████████████▌                   | 410/500 [1:10:36<11:53,  7.92s/it]

[I 2026-05-19 16:47:28,150] Trial 408 finished with value: 0.9499117141220355 and parameters: {'solver': 'saga', 'C': 0.04963264095521688, 'l1_ratio': 0.45415558687076557, 'class_weight': None, 'fit_intercept': True, 'tol': 1.304504957835723e-05, 'max_iter': 4172}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  82%|████████████████████████████████████████████████████████████████████████████████████████▊                   | 411/500 [1:10:37<08:59,  6.07s/it]

[I 2026-05-19 16:47:29,881] Trial 410 finished with value: 0.949911771546892 and parameters: {'solver': 'saga', 'C': 0.04385545512223168, 'l1_ratio': 0.44806125152819404, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3397888034422634e-05, 'max_iter': 4209}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  82%|████████████████████████████████████████████████████████████████████████████████████████▉                   | 412/500 [1:10:38<06:23,  4.35s/it]

[I 2026-05-19 16:47:30,241] Trial 409 finished with value: 0.949911717698465 and parameters: {'solver': 'saga', 'C': 0.046659099351914826, 'l1_ratio': 0.403810775017637, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4140469399495419e-05, 'max_iter': 4038}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  83%|█████████████████████████████████████████████████████████████████████████████████████████▏                  | 413/500 [1:10:38<04:38,  3.20s/it]

[I 2026-05-19 16:47:30,759] Trial 411 finished with value: 0.9499117580456808 and parameters: {'solver': 'saga', 'C': 0.04514213207350158, 'l1_ratio': 0.45247130524353657, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3678228169404574e-05, 'max_iter': 3932}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  83%|█████████████████████████████████████████████████████████████████████████████████████████▍                  | 414/500 [1:10:51<08:35,  5.99s/it]

[I 2026-05-19 16:47:43,259] Trial 416 finished with value: 0.9498926860804723 and parameters: {'solver': 'saga', 'C': 0.012084784206162385, 'l1_ratio': 0.44631774458743245, 'class_weight': None, 'fit_intercept': False, 'tol': 5.582268098688032e-06, 'max_iter': 4478}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  83%|█████████████████████████████████████████████████████████████████████████████████████████▋                  | 415/500 [1:10:51<06:12,  4.39s/it]

[I 2026-05-19 16:47:43,897] Trial 417 finished with value: 0.9498937434320073 and parameters: {'solver': 'saga', 'C': 0.013154820284696313, 'l1_ratio': 0.4429603458296699, 'class_weight': None, 'fit_intercept': False, 'tol': 4.7861491667982025e-05, 'max_iter': 3914}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  83%|█████████████████████████████████████████████████████████████████████████████████████████▊                  | 416/500 [1:10:58<07:13,  5.16s/it]

[I 2026-05-19 16:47:50,849] Trial 418 finished with value: 0.9498933762786133 and parameters: {'solver': 'saga', 'C': 0.011875390458168829, 'l1_ratio': 0.4093580368005101, 'class_weight': None, 'fit_intercept': False, 'tol': 8.167674768400894e-05, 'max_iter': 3901}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  83%|██████████████████████████████████████████████████████████████████████████████████████████                  | 417/500 [1:11:06<08:14,  5.96s/it]

[I 2026-05-19 16:47:58,684] Trial 414 finished with value: 0.9499118706149359 and parameters: {'solver': 'saga', 'C': 0.040891913589724646, 'l1_ratio': 0.44687002356682726, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3768627962503983e-05, 'max_iter': 4473}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  84%|██████████████████████████████████████████████████████████████████████████████████████████▎                 | 418/500 [1:11:10<07:04,  5.18s/it]

[I 2026-05-19 16:48:02,041] Trial 424 finished with value: 0.949882624213154 and parameters: {'solver': 'saga', 'C': 0.0025553578026534774, 'l1_ratio': 0.40970954689636796, 'class_weight': None, 'fit_intercept': True, 'tol': 6.960838101076133e-05, 'max_iter': 4265}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  84%|██████████████████████████████████████████████████████████████████████████████████████████▌                 | 419/500 [1:11:17<08:01,  5.95s/it]

[I 2026-05-19 16:48:09,789] Trial 428 pruned.

Best trial: 250. Best value: 0.949912:  84%|██████████████████████████████████████████████████████████████████████████████████████████▋                 | 420/500 [1:11:23<07:42,  5.78s/it]

[I 2026-05-19 16:48:15,174] Trial 422 finished with value: 0.9498940980463608 and parameters: {'solver': 'saga', 'C': 0.012775046346355637, 'l1_ratio': 0.40734673766115576, 'class_weight': None, 'fit_intercept': False, 'tol': 4.923749671615864e-05, 'max_iter': 4258}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  84%|██████████████████████████████████████████████████████████████████████████████████████████▉                 | 421/500 [1:11:23<05:37,  4.27s/it]

[I 2026-05-19 16:48:15,928] Trial 420 finished with value: 0.9498934231355369 and parameters: {'solver': 'saga', 'C': 0.01283077141666155, 'l1_ratio': 0.44557789977765383, 'class_weight': None, 'fit_intercept': False, 'tol': 1.5101234257513476e-05, 'max_iter': 4167}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  84%|███████████████████████████████████████████████████████████████████████████████████████████▏                | 422/500 [1:11:25<04:18,  3.31s/it]

[I 2026-05-19 16:48:17,006] Trial 421 finished with value: 0.9498936477819679 and parameters: {'solver': 'saga', 'C': 0.01292218178683752, 'l1_ratio': 0.44128674911689436, 'class_weight': None, 'fit_intercept': False, 'tol': 1.6399628707918358e-05, 'max_iter': 4158}. Best is trial 250 with value: 0.9499121585509325.
[I 2026-05-19 16:48:17,081] Trial 415 finished with value: 0.9499121240652432 and parameters: {'solver': 'saga', 'C': 0.027534528661716982, 'l1_ratio': 0.41005206635810004, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3839960509046463e-05, 'max_iter': 4452}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  85%|███████████████████████████████████████████████████████████████████████████████████████████▌                | 424/500 [1:11:44<07:55,  6.25s/it]

[I 2026-05-19 16:48:36,355] Trial 433 finished with value: 0.9497779674483118 and parameters: {'solver': 'saga', 'C': 0.00020117191829150454, 'l1_ratio': 0.407655350625439, 'class_weight': None, 'fit_intercept': True, 'tol': 9.197661396230735e-06, 'max_iter': 3850}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  85%|███████████████████████████████████████████████████████████████████████████████████████████▊                | 425/500 [1:11:55<09:25,  7.54s/it]

[I 2026-05-19 16:48:47,795] Trial 412 finished with value: 0.9499111293083757 and parameters: {'solver': 'saga', 'C': 0.04541560802292438, 'l1_ratio': 0.17485306718408616, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3969652891557264e-05, 'max_iter': 4195}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  85%|████████████████████████████████████████████████████████████████████████████████████████████                | 426/500 [1:12:02<09:00,  7.31s/it]

[I 2026-05-19 16:48:54,449] Trial 423 finished with value: 0.9498980723321399 and parameters: {'solver': 'saga', 'C': 0.013029042770759319, 'l1_ratio': 0.0535232070377642, 'class_weight': None, 'fit_intercept': False, 'tol': 8.681445247460028e-06, 'max_iter': 4461}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  85%|████████████████████████████████████████████████████████████████████████████████████████████▏               | 427/500 [1:12:14<10:29,  8.63s/it]

[I 2026-05-19 16:49:06,619] Trial 419 finished with value: 0.9499119288529542 and parameters: {'solver': 'saga', 'C': 0.036679478467464964, 'l1_ratio': 0.4513791365455961, 'class_weight': None, 'fit_intercept': True, 'tol': 1.533477934483929e-05, 'max_iter': 4172}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  86%|████████████████████████████████████████████████████████████████████████████████████████████▍               | 428/500 [1:12:37<15:00, 12.50s/it]

[I 2026-05-19 16:49:29,089] Trial 426 finished with value: 0.9499120441920812 and parameters: {'solver': 'saga', 'C': 0.029240666125528725, 'l1_ratio': 0.412323988728007, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6393266075928807e-05, 'max_iter': 4275}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  86%|████████████████████████████████████████████████████████████████████████████████████████████▋               | 429/500 [1:12:37<10:46,  9.11s/it]

[I 2026-05-19 16:49:29,702] Trial 425 finished with value: 0.9499120573687048 and parameters: {'solver': 'saga', 'C': 0.029320572997950763, 'l1_ratio': 0.41009165029764616, 'class_weight': None, 'fit_intercept': True, 'tol': 1.658336183154548e-05, 'max_iter': 4292}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  86%|████████████████████████████████████████████████████████████████████████████████████████████▉               | 430/500 [1:12:47<10:52,  9.32s/it]

[I 2026-05-19 16:49:39,542] Trial 427 finished with value: 0.9499119649678004 and parameters: {'solver': 'saga', 'C': 0.03194854192504709, 'l1_ratio': 0.40958502379870687, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5960224109873467e-05, 'max_iter': 3522}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  86%|█████████████████████████████████████████████████████████████████████████████████████████████               | 431/500 [1:13:03<12:54, 11.22s/it]

[I 2026-05-19 16:49:55,362] Trial 429 finished with value: 0.9499120627346752 and parameters: {'solver': 'saga', 'C': 0.028115413251944037, 'l1_ratio': 0.38753448270294527, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6887667522093786e-05, 'max_iter': 4146}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  86%|█████████████████████████████████████████████████████████████████████████████████████████████▎              | 432/500 [1:13:10<11:23, 10.06s/it]

[I 2026-05-19 16:50:02,620] Trial 438 finished with value: 0.9499119156795697 and parameters: {'solver': 'saga', 'C': 0.027310389691769483, 'l1_ratio': 0.3808021570378226, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007504119860471166, 'max_iter': 4352}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▌              | 433/500 [1:13:12<08:39,  7.75s/it]

[I 2026-05-19 16:50:04,896] Trial 431 finished with value: 0.9499120653346 and parameters: {'solver': 'saga', 'C': 0.028977059476781933, 'l1_ratio': 0.37421817371577404, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6321396044162643e-05, 'max_iter': 1390}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▋              | 434/500 [1:13:20<08:34,  7.79s/it]

[I 2026-05-19 16:50:12,794] Trial 430 finished with value: 0.9499120650116006 and parameters: {'solver': 'saga', 'C': 0.027742582944868872, 'l1_ratio': 0.3810106343692765, 'class_weight': None, 'fit_intercept': True, 'tol': 8.936172947673302e-06, 'max_iter': 4147}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  87%|█████████████████████████████████████████████████████████████████████████████████████████████▉              | 435/500 [1:13:28<08:16,  7.64s/it]

[I 2026-05-19 16:50:20,081] Trial 432 finished with value: 0.9499120776990415 and parameters: {'solver': 'saga', 'C': 0.0285325451086127, 'l1_ratio': 0.3757218552959992, 'class_weight': None, 'fit_intercept': True, 'tol': 8.420928424858485e-06, 'max_iter': 3745}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  87%|██████████████████████████████████████████████████████████████████████████████████████████████▏             | 436/500 [1:13:38<08:57,  8.40s/it]

[I 2026-05-19 16:50:30,260] Trial 434 finished with value: 0.9499120332916415 and parameters: {'solver': 'saga', 'C': 0.02708198410633042, 'l1_ratio': 0.38185557488722605, 'class_weight': None, 'fit_intercept': True, 'tol': 3.7212609843502547e-06, 'max_iter': 4624}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  87%|██████████████████████████████████████████████████████████████████████████████████████████████▍             | 437/500 [1:13:42<07:33,  7.20s/it]

[I 2026-05-19 16:50:34,639] Trial 444 finished with value: 0.949848440986219 and parameters: {'solver': 'saga', 'C': 0.0005854077280960832, 'l1_ratio': 0.3889009378260779, 'class_weight': None, 'fit_intercept': True, 'tol': 3.832663392434815e-06, 'max_iter': 4016}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▌             | 438/500 [1:13:48<06:52,  6.66s/it]

[I 2026-05-19 16:50:40,033] Trial 437 finished with value: 0.9499120531394762 and parameters: {'solver': 'saga', 'C': 0.025047398654034905, 'l1_ratio': 0.38416799001880886, 'class_weight': None, 'fit_intercept': True, 'tol': 1.780305511760852e-05, 'max_iter': 4123}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  88%|██████████████████████████████████████████████████████████████████████████████████████████████▊             | 439/500 [1:13:51<05:52,  5.78s/it]

[I 2026-05-19 16:50:43,770] Trial 435 finished with value: 0.9499120601318889 and parameters: {'solver': 'saga', 'C': 0.028062387219634586, 'l1_ratio': 0.3867738287399234, 'class_weight': None, 'fit_intercept': True, 'tol': 3.6953440253246236e-06, 'max_iter': 4458}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  88%|███████████████████████████████████████████████████████████████████████████████████████████████             | 440/500 [1:13:53<04:25,  4.43s/it]

[I 2026-05-19 16:50:45,032] Trial 436 finished with value: 0.9499120583424533 and parameters: {'solver': 'saga', 'C': 0.02788252302377056, 'l1_ratio': 0.3853905616341677, 'class_weight': None, 'fit_intercept': True, 'tol': 8.48796064293944e-06, 'max_iter': 4379}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  88%|███████████████████████████████████████████████████████████████████████████████████████████████▎            | 441/500 [1:13:54<03:24,  3.47s/it]

[I 2026-05-19 16:50:46,270] Trial 439 finished with value: 0.9499119729407894 and parameters: {'solver': 'saga', 'C': 0.026039829400770313, 'l1_ratio': 0.3725058183355237, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001877748903134489, 'max_iter': 4386}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  88%|███████████████████████████████████████████████████████████████████████████████████████████████▍            | 442/500 [1:14:29<12:27, 12.89s/it]

[I 2026-05-19 16:51:21,159] Trial 441 finished with value: 0.9499120511877118 and parameters: {'solver': 'saga', 'C': 0.02506004265237972, 'l1_ratio': 0.38495532726350035, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5246153997591096e-05, 'max_iter': 3742}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▋            | 443/500 [1:14:44<13:03, 13.75s/it]

[I 2026-05-19 16:51:36,902] Trial 440 finished with value: 0.9499120173506865 and parameters: {'solver': 'saga', 'C': 0.026000947282948866, 'l1_ratio': 0.3821672879350099, 'class_weight': None, 'fit_intercept': True, 'tol': 4.48936234706145e-06, 'max_iter': 4646}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  89%|███████████████████████████████████████████████████████████████████████████████████████████████▉            | 444/500 [1:14:59<13:12, 14.15s/it]

[I 2026-05-19 16:51:51,987] Trial 446 finished with value: 0.9499115233375267 and parameters: {'solver': 'saga', 'C': 0.017919299888220733, 'l1_ratio': 0.38265061897608627, 'class_weight': None, 'fit_intercept': True, 'tol': 2.638924183105144e-05, 'max_iter': 3763}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  89%|████████████████████████████████████████████████████████████████████████████████████████████████            | 445/500 [1:15:01<09:35, 10.46s/it]

[I 2026-05-19 16:51:53,832] Trial 443 finished with value: 0.9499119626981714 and parameters: {'solver': 'saga', 'C': 0.023304678431505355, 'l1_ratio': 0.3816527564033219, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1786136253481386e-05, 'max_iter': 4401}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  89%|████████████████████████████████████████████████████████████████████████████████████████████████▎           | 446/500 [1:15:10<08:49,  9.81s/it]

[I 2026-05-19 16:52:02,130] Trial 442 finished with value: 0.9499119560287232 and parameters: {'solver': 'saga', 'C': 0.023094637491067615, 'l1_ratio': 0.3846646907556191, 'class_weight': None, 'fit_intercept': True, 'tol': 3.885766158201571e-06, 'max_iter': 4418}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  89%|████████████████████████████████████████████████████████████████████████████████████████████████▌           | 447/500 [1:15:11<06:29,  7.34s/it]

[I 2026-05-19 16:52:03,714] Trial 445 finished with value: 0.9499115936106559 and parameters: {'solver': 'saga', 'C': 0.018151898551876697, 'l1_ratio': 0.38200250651954437, 'class_weight': None, 'fit_intercept': True, 'tol': 8.266677085617593e-06, 'max_iter': 4700}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▊           | 448/500 [1:15:13<04:58,  5.74s/it]

[I 2026-05-19 16:52:05,711] Trial 448 finished with value: 0.9499115496944956 and parameters: {'solver': 'saga', 'C': 0.01872940366561322, 'l1_ratio': 0.42017909844982027, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6493413074259875e-05, 'max_iter': 4395}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  90%|████████████████████████████████████████████████████████████████████████████████████████████████▉           | 449/500 [1:15:33<08:24,  9.89s/it]

[I 2026-05-19 16:52:25,278] Trial 449 finished with value: 0.9499113673422249 and parameters: {'solver': 'saga', 'C': 0.01795207892179885, 'l1_ratio': 0.4230930966802197, 'class_weight': None, 'fit_intercept': True, 'tol': 8.798938146251196e-06, 'max_iter': 3726}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████▏          | 450/500 [1:15:34<05:59,  7.20s/it]

[I 2026-05-19 16:52:26,200] Trial 450 finished with value: 0.9499110750311243 and parameters: {'solver': 'saga', 'C': 0.016468623434596638, 'l1_ratio': 0.43092189108466294, 'class_weight': None, 'fit_intercept': True, 'tol': 8.433331857749855e-06, 'max_iter': 3778}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████▍          | 451/500 [1:15:34<04:10,  5.12s/it]

[I 2026-05-19 16:52:26,468] Trial 451 finished with value: 0.9499114353378687 and parameters: {'solver': 'saga', 'C': 0.018386083451894495, 'l1_ratio': 0.4288827355853906, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1598109699435982e-05, 'max_iter': 3713}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  90%|█████████████████████████████████████████████████████████████████████████████████████████████████▋          | 452/500 [1:15:35<03:10,  3.96s/it]

[I 2026-05-19 16:52:27,724] Trial 447 finished with value: 0.9499117886437076 and parameters: {'solver': 'saga', 'C': 0.017959143269701796, 'l1_ratio': 0.328230765922775, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1881661118527382e-05, 'max_iter': 3733}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████▊          | 453/500 [1:15:37<02:30,  3.21s/it]

[I 2026-05-19 16:52:29,192] Trial 452 finished with value: 0.9499114423316876 and parameters: {'solver': 'saga', 'C': 0.018558055447335388, 'l1_ratio': 0.42353683806201736, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1538444283334997e-05, 'max_iter': 3739}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████          | 454/500 [1:16:09<09:08, 11.92s/it]

[I 2026-05-19 16:53:01,448] Trial 453 finished with value: 0.9499113419665457 and parameters: {'solver': 'saga', 'C': 0.018061402611584128, 'l1_ratio': 0.4312160736650126, 'class_weight': None, 'fit_intercept': True, 'tol': 1.212706016367232e-05, 'max_iter': 3716}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████▎         | 455/500 [1:16:24<09:36, 12.80s/it]

[I 2026-05-19 16:53:16,293] Trial 456 finished with value: 0.9499044065550264 and parameters: {'solver': 'saga', 'C': 0.006518434244203283, 'l1_ratio': 0.331387595082243, 'class_weight': None, 'fit_intercept': True, 'tol': 9.14542489724042e-06, 'max_iter': 3722}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████▍         | 456/500 [1:16:35<09:01, 12.32s/it]

[I 2026-05-19 16:53:27,473] Trial 460 finished with value: 0.9499031035755202 and parameters: {'solver': 'saga', 'C': 0.006174398175888282, 'l1_ratio': 0.353754807132989, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1689610049282304e-05, 'max_iter': 3889}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  91%|██████████████████████████████████████████████████████████████████████████████████████████████████▋         | 457/500 [1:16:47<08:40, 12.10s/it]

[I 2026-05-19 16:53:39,024] Trial 455 finished with value: 0.9499117507530392 and parameters: {'solver': 'saga', 'C': 0.019891645283908684, 'l1_ratio': 0.4252093460409936, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1002586059139344e-05, 'max_iter': 3750}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████▉         | 458/500 [1:16:55<07:45, 11.09s/it]

[I 2026-05-19 16:53:47,775] Trial 463 finished with value: 0.9499045578378565 and parameters: {'solver': 'saga', 'C': 0.006729487481543014, 'l1_ratio': 0.3401228040998335, 'class_weight': None, 'fit_intercept': True, 'tol': 9.90150624792836e-06, 'max_iter': 3931}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████▏        | 459/500 [1:17:05<07:17, 10.68s/it]

[I 2026-05-19 16:53:57,529] Trial 454 finished with value: 0.9499119747226838 and parameters: {'solver': 'saga', 'C': 0.018871759659889506, 'l1_ratio': 0.22414829784426504, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1467630113617585e-05, 'max_iter': 3740}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████▎        | 460/500 [1:17:12<06:17,  9.44s/it]

[I 2026-05-19 16:54:04,042] Trial 458 finished with value: 0.9499117600160535 and parameters: {'solver': 'saga', 'C': 0.017221111415963636, 'l1_ratio': 0.3292167711351291, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2048764534216982e-05, 'max_iter': 3717}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████▌        | 461/500 [1:17:15<04:59,  7.68s/it]

[I 2026-05-19 16:54:07,639] Trial 457 finished with value: 0.9499113927139092 and parameters: {'solver': 'saga', 'C': 0.015613087689896233, 'l1_ratio': 0.32824250932527765, 'class_weight': None, 'fit_intercept': True, 'tol': 9.03261154370099e-06, 'max_iter': 3743}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  92%|███████████████████████████████████████████████████████████████████████████████████████████████████▊        | 462/500 [1:17:33<06:47, 10.73s/it]

[I 2026-05-19 16:54:25,495] Trial 459 finished with value: 0.9499117969200036 and parameters: {'solver': 'saga', 'C': 0.03687557706953094, 'l1_ratio': 0.3297189625835702, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1099867765186744e-05, 'max_iter': 3726}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████        | 463/500 [1:18:07<10:51, 17.62s/it]

[I 2026-05-19 16:54:59,194] Trial 462 finished with value: 0.9499117424244444 and parameters: {'solver': 'saga', 'C': 0.038541923997262084, 'l1_ratio': 0.32688478085693184, 'class_weight': None, 'fit_intercept': True, 'tol': 5.814861411155459e-06, 'max_iter': 3928}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 464/500 [1:18:09<07:46, 12.96s/it]

[I 2026-05-19 16:55:01,287] Trial 464 finished with value: 0.9499118810203093 and parameters: {'solver': 'saga', 'C': 0.03799104684918939, 'l1_ratio': 0.35365111494053564, 'class_weight': None, 'fit_intercept': True, 'tol': 5.85198425349911e-06, 'max_iter': 2858}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 465/500 [1:18:30<08:59, 15.42s/it]

[I 2026-05-19 16:55:22,438] Trial 466 finished with value: 0.9499118065261994 and parameters: {'solver': 'saga', 'C': 0.0403959235623773, 'l1_ratio': 0.48799221306484286, 'class_weight': None, 'fit_intercept': True, 'tol': 6.2221766288231464e-06, 'max_iter': 3922}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 466/500 [1:18:36<07:08, 12.61s/it]

[I 2026-05-19 16:55:28,487] Trial 465 finished with value: 0.9499117609672272 and parameters: {'solver': 'saga', 'C': 0.04162939467893468, 'l1_ratio': 0.3546641601339443, 'class_weight': None, 'fit_intercept': True, 'tol': 9.8649772476859e-06, 'max_iter': 2227}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  93%|████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 467/500 [1:19:05<09:34, 17.41s/it]

[I 2026-05-19 16:55:57,076] Trial 469 finished with value: 0.949911866876618 and parameters: {'solver': 'saga', 'C': 0.03860291922587323, 'l1_ratio': 0.4828671328994361, 'class_weight': None, 'fit_intercept': True, 'tol': 6.086753856426377e-06, 'max_iter': 2897}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████       | 468/500 [1:19:15<08:07, 15.22s/it]

[I 2026-05-19 16:56:07,213] Trial 470 finished with value: 0.9499119212094428 and parameters: {'solver': 'saga', 'C': 0.03728140559361281, 'l1_ratio': 0.49001765005141645, 'class_weight': None, 'fit_intercept': True, 'tol': 5.41372304075306e-06, 'max_iter': 2885}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 469/500 [1:19:21<06:24, 12.42s/it]

[I 2026-05-19 16:56:13,082] Trial 467 finished with value: 0.9499113933281412 and parameters: {'solver': 'saga', 'C': 0.037838141113370485, 'l1_ratio': 0.22297469726885494, 'class_weight': None, 'fit_intercept': True, 'tol': 9.739242855788435e-06, 'max_iter': 3989}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 470/500 [1:19:25<05:01, 10.04s/it]

[I 2026-05-19 16:56:17,573] Trial 468 finished with value: 0.9499118714220394 and parameters: {'solver': 'saga', 'C': 0.039018983305084014, 'l1_ratio': 0.35850664666885873, 'class_weight': None, 'fit_intercept': True, 'tol': 5.418689823491882e-06, 'max_iter': 3938}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  94%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 471/500 [1:19:27<03:36,  7.45s/it]

[I 2026-05-19 16:56:18,991] Trial 472 finished with value: 0.9499118310894165 and parameters: {'solver': 'saga', 'C': 0.03914967502482647, 'l1_ratio': 0.48189370788951635, 'class_weight': None, 'fit_intercept': True, 'tol': 5.31339004205036e-06, 'max_iter': 4012}. Best is trial 250 with value: 0.9499121585509325.
[I 2026-05-19 16:56:19,085] Trial 471 finished with value: 0.9499118453947227 and parameters: {'solver': 'saga', 'C': 0.03880824108515694, 'l1_ratio': 0.3559412084105337, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9591021397019294e-05, 'max_iter': 3937}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 473/500 [1:19:44<03:39,  8.14s/it]

[I 2026-05-19 16:56:36,861] Trial 473 finished with value: 0.9499118428016186 and parameters: {'solver': 'saga', 'C': 0.03915932711630828, 'l1_ratio': 0.48673886538716427, 'class_weight': None, 'fit_intercept': True, 'tol': 5.73689846665263e-06, 'max_iter': 3997}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 474/500 [1:20:16<06:01, 13.89s/it]

[I 2026-05-19 16:57:08,212] Trial 475 finished with value: 0.9499106417854064 and parameters: {'solver': 'saga', 'C': 0.1169224148006187, 'l1_ratio': 0.49127293770421276, 'class_weight': None, 'fit_intercept': True, 'tol': 7.566739981023435e-06, 'max_iter': 4016}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 475/500 [1:20:21<04:48, 11.55s/it]

[I 2026-05-19 16:57:13,136] Trial 474 finished with value: 0.9499118637764712 and parameters: {'solver': 'saga', 'C': 0.0390669988205859, 'l1_ratio': 0.35755594819069253, 'class_weight': None, 'fit_intercept': True, 'tol': 2.001130848238142e-05, 'max_iter': 4018}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊     | 476/500 [1:20:23<03:39,  9.13s/it]

[I 2026-05-19 16:57:15,785] Trial 478 finished with value: 0.9499076944368354 and parameters: {'solver': 'saga', 'C': 0.010656760367255765, 'l1_ratio': 0.4086670825746816, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8882177806281756e-05, 'max_iter': 4012}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  95%|███████████████████████████████████████████████████████████████████████████████████████████████████████     | 477/500 [1:20:24<02:38,  6.90s/it]

[I 2026-05-19 16:57:16,971] Trial 477 finished with value: 0.949911885581345 and parameters: {'solver': 'saga', 'C': 0.03425626003245789, 'l1_ratio': 0.4061831093465414, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9901425225322308e-05, 'max_iter': 4012}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏    | 478/500 [1:20:27<02:05,  5.69s/it]

[I 2026-05-19 16:57:19,617] Trial 461 finished with value: 0.9499091143141726 and parameters: {'solver': 'saga', 'C': 12.541181480060654, 'l1_ratio': 0.33544872909834716, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1933533758171363e-05, 'max_iter': 3933}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍    | 479/500 [1:20:37<02:22,  6.79s/it]

[I 2026-05-19 16:57:29,112] Trial 476 finished with value: 0.9499118011582425 and parameters: {'solver': 'saga', 'C': 0.040294051065658996, 'l1_ratio': 0.48656684070453415, 'class_weight': None, 'fit_intercept': True, 'tol': 7.883013039651745e-06, 'max_iter': 2334}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋    | 480/500 [1:20:40<01:54,  5.75s/it]

[I 2026-05-19 16:57:32,341] Trial 480 finished with value: 0.9499090494725557 and parameters: {'solver': 'saga', 'C': 0.011919097572199071, 'l1_ratio': 0.40387286907839126, 'class_weight': None, 'fit_intercept': True, 'tol': 2.194982892434807e-05, 'max_iter': 4028}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉    | 481/500 [1:20:47<01:58,  6.23s/it]

[I 2026-05-19 16:57:39,714] Trial 482 finished with value: 0.9499079156667237 and parameters: {'solver': 'saga', 'C': 0.01082665620111389, 'l1_ratio': 0.4072240170099297, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9328038112090115e-05, 'max_iter': 3856}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  96%|████████████████████████████████████████████████████████████████████████████████████████████████████████    | 482/500 [1:20:55<01:59,  6.63s/it]

[I 2026-05-19 16:57:47,305] Trial 483 finished with value: 0.9499096069416533 and parameters: {'solver': 'saga', 'C': 0.012684893592034265, 'l1_ratio': 0.4089510491933868, 'class_weight': None, 'fit_intercept': True, 'tol': 1.415582460410573e-05, 'max_iter': 4026}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎   | 483/500 [1:21:03<02:01,  7.17s/it]

[I 2026-05-19 16:57:55,735] Trial 479 finished with value: 0.9499119073827206 and parameters: {'solver': 'saga', 'C': 0.03395234756036163, 'l1_ratio': 0.437163108096768, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8011466386901122e-05, 'max_iter': 4021}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌   | 484/500 [1:21:07<01:36,  6.04s/it]

[I 2026-05-19 16:57:59,125] Trial 481 finished with value: 0.9499120331349932 and parameters: {'solver': 'saga', 'C': 0.02526384971139688, 'l1_ratio': 0.41332071808945114, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0824244584009413e-05, 'max_iter': 4035}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊   | 485/500 [1:21:17<01:52,  7.49s/it]

[I 2026-05-19 16:58:10,005] Trial 484 finished with value: 0.9499086532094042 and parameters: {'solver': 'saga', 'C': 0.011312050504452833, 'l1_ratio': 0.402894563219511, 'class_weight': None, 'fit_intercept': True, 'tol': 7.718457341789876e-06, 'max_iter': 4541}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 486/500 [1:21:37<02:35, 11.07s/it]

[I 2026-05-19 16:58:29,483] Trial 486 finished with value: 0.949906363318368 and parameters: {'solver': 'saga', 'C': 0.009332026753324991, 'l1_ratio': 0.4013584889422246, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4585961401857916e-05, 'max_iter': 3824}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏  | 487/500 [1:21:44<02:06,  9.72s/it]

[I 2026-05-19 16:58:36,029] Trial 485 finished with value: 0.9499093705828872 and parameters: {'solver': 'saga', 'C': 0.012391827802737102, 'l1_ratio': 0.4096972783415135, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4101071768191892e-05, 'max_iter': 3827}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍  | 488/500 [1:22:07<02:46, 13.91s/it]

[I 2026-05-19 16:58:59,723] Trial 488 finished with value: 0.9499119306585848 and parameters: {'solver': 'saga', 'C': 0.02366543991135453, 'l1_ratio': 0.4499034174527418, 'class_weight': None, 'fit_intercept': True, 'tol': 1.498699535271316e-05, 'max_iter': 3819}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▊  | 490/500 [1:22:11<01:16,  7.67s/it]

[I 2026-05-19 16:59:03,610] Trial 489 finished with value: 0.9499118699840053 and parameters: {'solver': 'saga', 'C': 0.0227311029235859, 'l1_ratio': 0.43542032487469434, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4369763284814816e-05, 'max_iter': 3566}. Best is trial 250 with value: 0.9499121585509325.
[I 2026-05-19 16:59:03,742] Trial 487 finished with value: 0.9499119353741277 and parameters: {'solver': 'saga', 'C': 0.024695117423168923, 'l1_ratio': 0.4465423732259676, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3731083351868438e-05, 'max_iter': 3546}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████  | 491/500 [1:22:18<01:07,  7.55s/it]

[I 2026-05-19 16:59:11,004] Trial 490 finished with value: 0.9499119285426516 and parameters: {'solver': 'saga', 'C': 0.024090249283655666, 'l1_ratio': 0.4407604820092055, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4656004136676345e-05, 'max_iter': 3838}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  98%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎ | 492/500 [1:22:22<00:50,  6.27s/it]

[I 2026-05-19 16:59:14,275] Trial 491 finished with value: 0.9499119745775921 and parameters: {'solver': 'saga', 'C': 0.024263093874363758, 'l1_ratio': 0.44028000087599306, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5078350400059237e-05, 'max_iter': 3842}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 493/500 [1:22:32<00:52,  7.51s/it]

[I 2026-05-19 16:59:24,702] Trial 492 finished with value: 0.9499119493639832 and parameters: {'solver': 'saga', 'C': 0.024356887265376, 'l1_ratio': 0.44393749256017034, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4384148919256998e-05, 'max_iter': 3830}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 494/500 [1:22:33<00:33,  5.63s/it]

[I 2026-05-19 16:59:25,939] Trial 493 finished with value: 0.9499119352138209 and parameters: {'solver': 'saga', 'C': 0.02327314753590133, 'l1_ratio': 0.44228826249588526, 'class_weight': None, 'fit_intercept': True, 'tol': 1.453370156017581e-05, 'max_iter': 3582}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 495/500 [1:22:41<00:31,  6.28s/it]

[I 2026-05-19 16:59:33,725] Trial 494 finished with value: 0.9499119326097404 and parameters: {'solver': 'saga', 'C': 0.02393692116384382, 'l1_ratio': 0.4460277755513996, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4508476375566976e-05, 'max_iter': 3836}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▏| 496/500 [1:22:42<00:18,  4.61s/it]

[I 2026-05-19 16:59:34,453] Trial 495 finished with value: 0.9499119034959815 and parameters: {'solver': 'saga', 'C': 0.022843364368249016, 'l1_ratio': 0.45013614802988916, 'class_weight': None, 'fit_intercept': True, 'tol': 1.464778437496531e-05, 'max_iter': 3536}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912:  99%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 497/500 [1:22:51<00:18,  6.09s/it]

[I 2026-05-19 16:59:43,966] Trial 496 finished with value: 0.9499118961748676 and parameters: {'solver': 'saga', 'C': 0.022875450211566038, 'l1_ratio': 0.4433794198107544, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4337180206641696e-05, 'max_iter': 3832}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 498/500 [1:23:09<00:19,  9.51s/it]

[I 2026-05-19 17:00:01,467] Trial 497 finished with value: 0.9499120594902412 and parameters: {'solver': 'saga', 'C': 0.025709150356692054, 'l1_ratio': 0.4404217231682701, 'class_weight': None, 'fit_intercept': True, 'tol': 9.57135554902691e-06, 'max_iter': 3846}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 499/500 [1:23:12<00:07,  7.71s/it]

[I 2026-05-19 17:00:04,967] Trial 498 finished with value: 0.949911934561561 and parameters: {'solver': 'saga', 'C': 0.024203978326368898, 'l1_ratio': 0.44399438486325166, 'class_weight': None, 'fit_intercept': True, 'tol': 8.88685687393311e-06, 'max_iter': 4246}. Best is trial 250 with value: 0.9499121585509325.

Best trial: 250. Best value: 0.949912: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [1:23:22<00:00, 10.01s/it]

[I 2026-05-19 17:00:14,912] Trial 499 finished with value: 0.9499118877162429 and parameters: {'solver': 'saga', 'C': 0.022772733984773322, 'l1_ratio': 0.44251844076905555, 'class_weight': None, 'fit_intercept': True, 'tol': 9.468615886648325e-06, 'max_iter': 4279}. Best is trial 250 with value: 0.9499121585509325.
Best trial score:
0.9499121585509325

Best params:
{'solver': 'saga', 'C': 0.02914879956934508, 'l1_ratio': 0.43970786556822744, 'class_weight': None, 'fit_intercept': True, 'tol': 8.83661241539477e-06, 'max_iter': 3921}

In [8]:
stacking_lg = LogisticRegression(**study.best_params).fit(X_train, y_train.PitNextLap)

# Submission

In [9]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [10]:
submission['PitNextLap'] = stacking_lg.predict_proba(X_test)[:, 1]

In [11]:
submission.to_csv('../data/submission/submission.csv', index=False)

In [12]:
X_train.columns

Index(['lgbm_logit', 'cat_logit', 'xgb_logit', 'hist_logit', 'lg_logit',
       'knn_logit', 'ridge_logit', 'voting_lgbm_cat_xgb_hist_logit',
       'voting_lg_ridge_logit',
       'stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_logit'],
      dtype='str')