# Imports

In [53]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config

from scipy.stats import entropy, rankdata

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import StackingClassifier
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.inspection import permutation_importance
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.model_selection import StratifiedKFold

from feature_engine.selection import DropFeatures

## Utils

In [2]:
set_config(enable_metadata_routing=True)

In [13]:
class StackingFeatureEngineer(BaseEstimator, TransformerMixin):

    def __init__(
        self,
        add_rank_features=True,
        add_statistical_features=True,
        add_interaction_features=True,
        add_difference_features=True,
        add_entropy_features=True,
        add_threshold_features=True,
        confidence_threshold=0.9,
        uncertainty_low=0.4,
        uncertainty_high=0.6,
    ):

        self.add_rank_features = add_rank_features
        self.add_statistical_features = add_statistical_features
        self.add_interaction_features = add_interaction_features
        self.add_difference_features = add_difference_features
        self.add_entropy_features = add_entropy_features
        self.add_threshold_features = add_threshold_features

        self.confidence_threshold = confidence_threshold
        self.uncertainty_low = uncertainty_low
        self.uncertainty_high = uncertainty_high

    def fit(self, X, y=None):

        X = self._to_dataframe(X)

        self.feature_names_in_ = X.columns.tolist()

        return self

    def transform(self, X):

        X = self._to_dataframe(
            X,
            columns=getattr(self, "feature_names_in_", None)
        )

        features = []

        # =====================================================
        # FEATURES ORIGINAIS
        # =====================================================

        base_probs = X.copy()

        features.append(base_probs)

        # =====================================================
        # FEATURES ESTATÍSTICAS
        # =====================================================

        if self.add_statistical_features:

            stat_df = pd.DataFrame(index=X.index)

            stat_df["prob_mean"] = X.mean(axis=1)
            stat_df["prob_std"] = X.std(axis=1)
            stat_df["prob_min"] = X.min(axis=1)
            stat_df["prob_max"] = X.max(axis=1)
            stat_df["prob_range"] = (
                stat_df["prob_max"] -
                stat_df["prob_min"]
            )

            stat_df["prob_median"] = X.median(axis=1)

            features.append(stat_df)

        # =====================================================
        # ENTROPIA
        # =====================================================

        if self.add_entropy_features:

            ent_df = pd.DataFrame(index=X.index)

            probs_norm = (
                X.div(X.sum(axis=1) + 1e-12, axis=0)
            )

            ent_df["prediction_entropy"] = probs_norm.apply(
                lambda row: entropy(row + 1e-12),
                axis=1
            )

            features.append(ent_df)

        # =====================================================
        # RANK FEATURES
        # =====================================================

        if self.add_rank_features:

            rank_df = pd.DataFrame(index=X.index)

            ranks = np.apply_along_axis(
                rankdata,
                axis=1,
                arr=X.values
            )

            for i, col in enumerate(X.columns):

                rank_df[f"{col}_rank"] = ranks[:, i]

            features.append(rank_df)

        # =====================================================
        # AGREEMENT FEATURES
        # =====================================================

        vote_df = pd.DataFrame(index=X.index)

        preds = (X > 0.5).astype(int)

        vote_df["vote_sum"] = preds.sum(axis=1)
        vote_df["vote_mean"] = preds.mean(axis=1)

        vote_df["all_agree"] = (
            preds.nunique(axis=1) == 1
        ).astype(int)

        vote_df["disagreement"] = (
            preds.nunique(axis=1) > 1
        ).astype(int)

        features.append(vote_df)

        # =====================================================
        # THRESHOLD FEATURES
        # =====================================================

        if self.add_threshold_features:

            thresh_df = pd.DataFrame(index=X.index)

            thresh_df["high_conf_models"] = (
                X > self.confidence_threshold
            ).sum(axis=1)

            thresh_df["uncertain_models"] = (
                (
                    X > self.uncertainty_low
                ) &
                (
                    X < self.uncertainty_high
                )
            ).sum(axis=1)

            features.append(thresh_df)

        # =====================================================
        # INTERAÇÕES
        # =====================================================

        if self.add_interaction_features:

            inter_df = pd.DataFrame(index=X.index)

            cols = X.columns.tolist()

            for i in range(len(cols)):
                for j in range(i + 1, len(cols)):

                    c1 = cols[i]
                    c2 = cols[j]

                    inter_df[f"{c1}_x_{c2}"] = (
                        X[c1] * X[c2]
                    )

            features.append(inter_df)

        # =====================================================
        # DIFERENÇAS
        # =====================================================

        if self.add_difference_features:

            diff_df = pd.DataFrame(index=X.index)

            cols = X.columns.tolist()

            for i in range(len(cols)):
                for j in range(i + 1, len(cols)):

                    c1 = cols[i]
                    c2 = cols[j]

                    diff_df[f"{c1}_minus_{c2}"] = (
                        X[c1] - X[c2]
                    )

            features.append(diff_df)

        # =====================================================
        # CONCAT FINAL
        # =====================================================

        X_meta = pd.concat(features, axis=1)

        return X_meta

    @staticmethod
    def _to_dataframe(X, columns=None):

        if isinstance(X, pd.DataFrame):
            return X.copy()

        X = np.asarray(X)

        if columns is None:
            columns = [
                f"feature_{i}"
                for i in range(X.shape[1])
            ]

        return pd.DataFrame(X, columns=columns)

# Loading Dataset

In [4]:
X_train = pd.read_parquet('../data/processed/X_train_stacking2.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking2.parquet')

In [5]:
X_train.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,voting_lgbm_cat_xgb_hist_proba,stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.868510,0.826590
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.772514,0.801335
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.717012,0.782757
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,0.005494,0.502476
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,0.482416,0.703165

In [6]:
X_test.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,voting_lgbm_cat_xgb_hist_proba,stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,0.019849,0.509303
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,0.012173,0.505573
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,0.010304,0.504827
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.444558,0.696136
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.939648,0.852833

# Feature Engineering

## Feature Creation

In [14]:
sfe = StackingFeatureEngineer(
    add_rank_features=True,
    add_statistical_features=True,
    add_entropy_features=True,
    add_threshold_features=True,
    add_interaction_features=False,
    add_difference_features=False,
)

X_train_enc = sfe.fit_transform(X_train)
X_test_enc = sfe.transform(X_test)

In [48]:
X_train_enc.to_parquet('../data/processed/X_train_stacking3.parquet')
X_test_enc.to_parquet('../data/processed/X_test_stacking3.parquet')

## Feature Scaling

In [51]:
column_transformer = ColumnTransformer([
    (
        'standard_scaler', 
        StandardScaler(), 
        [
            'lgbm_proba', 'cat_proba', 'xgb_proba', 'hist_proba', 'lg_proba', 'knn_proba', 'voting_lgbm_cat_xgb_hist_proba', 
            'stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba', 'prob_mean', 'prob_max', 'prob_median', 'prediction_entropy',
            'cat_proba_rank', 'xgb_proba_rank', 'hist_proba_rank', 'lg_proba_rank', 'knn_proba_rank', 'voting_lgbm_cat_xgb_hist_proba_rank',
            'vote_sum', 'vote_mean'
        ]
    ),
    (
        'robust_scaler', 
        RobustScaler(), 
        [
            'prob_std', 'prob_min', 'prob_range', 'lgbm_proba_rank', 'stacking_lg_knn_voting_lgbm_cat_xgb_hist_proba_rank', 
            'all_agree', 'disagreement', 'high_conf_models', 'uncertain_models'
        ]
    ),
], remainder="passthrough")

## Feature Selection

In [58]:
model = make_pipeline(
    column_transformer,
    LogisticRegression(random_state=42, verbose=0, class_weight='balanced', max_iter=500)
).fit(X_train_enc, y_train.PitNextLap)

perm_result = permutation_importance(
    estimator=model, 
    X=X_train_enc, 
    y=y_train.PitNextLap, 
    n_jobs=-1, 
    scoring='roc_auc'
)

importance_df = pd.DataFrame({
    "feature": X_train_enc.columns.tolist(),
    "importance_mean": perm_result.importances_mean,
    "importance_std": perm_result.importances_std
}).sort_values(by="importance_mean", ascending=False)

features_to_drop = importance_df.query("importance_mean <= 0").feature.tolist()

# Machine Learning

In [70]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "C": trial.suggest_float("C", 1e-5, 100, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
        "max_iter": trial.suggest_int("max_iter", 1000, 5000)
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = make_pipeline(
            column_transformer,
            LogisticRegression(**params)
        ).fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train_enc, y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-18 17:06:10,895] A new study created in memory with name: no-name-10b72739-9c03-4772-b0ab-295081f2ca89
Best trial: 11. Best value: 0.949527:   0%|          | 1/500 [00:26<3:41:22, 26.62s/it]

[I 2026-05-18 17:06:37,509] Trial 11 finished with value: 0.9495267260133892 and parameters: {'solver': 'saga', 'C': 0.01165368745794059, 'l1_ratio': 0.2504298365789678, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.007948327613774918, 'max_iter': 4364}. Best is trial 11 with value: 0.9495267260133892.

Best trial: 6. Best value: 0.949531:   0%|          | 2/500 [00:33<2:04:21, 14.98s/it]

[I 2026-05-18 17:06:44,342] Trial 6 finished with value: 0.949530914269172 and parameters: {'solver': 'saga', 'C': 0.000879553907442171, 'l1_ratio': 0.21547588979229515, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.0453882946161282e-05, 'max_iter': 1518}. Best is trial 6 with value: 0.949530914269172.

Best trial: 8. Best value: 0.949561:   1%|          | 3/500 [00:37<1:23:29, 10.08s/it]

[I 2026-05-18 17:06:48,595] Trial 8 finished with value: 0.949561066344357 and parameters: {'solver': 'saga', 'C': 0.0003506477483334558, 'l1_ratio': 0.12675731645216015, 'class_weight': None, 'fit_intercept': True, 'tol': 4.824766682693902e-06, 'max_iter': 4888}. Best is trial 8 with value: 0.949561066344357.

Best trial: 8. Best value: 0.949561:   1%|          | 4/500 [00:39<55:31,  6.72s/it]

[I 2026-05-18 17:06:50,155] Trial 3 finished with value: 0.9460545011989524 and parameters: {'solver': 'saga', 'C': 1.9583131673326128e-05, 'l1_ratio': 0.8558904473310487, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.157309441395269e-06, 'max_iter': 1584}. Best is trial 8 with value: 0.949561066344357.

Best trial: 8. Best value: 0.949561:   1%|          | 5/500 [00:42<46:13,  5.60s/it]

[I 2026-05-18 17:06:53,779] Trial 5 finished with value: 0.9494942747129196 and parameters: {'solver': 'saga', 'C': 4.3766298342661685, 'l1_ratio': 0.5511561910679469, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0019347354803643808, 'max_iter': 1364}. Best is trial 8 with value: 0.949561066344357.

Best trial: 8. Best value: 0.949561:   1%|          | 6/500 [01:05<1:34:19, 11.46s/it]

[I 2026-05-18 17:07:16,601] Trial 15 finished with value: 0.9494673877894517 and parameters: {'solver': 'saga', 'C': 9.649666159955003e-05, 'l1_ratio': 0.31000437673034276, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.627970223730587e-05, 'max_iter': 1954}. Best is trial 8 with value: 0.949561066344357.

Best trial: 8. Best value: 0.949561:   1%|▏         | 7/500 [01:09<1:12:49,  8.86s/it]

[I 2026-05-18 17:07:20,132] Trial 16 finished with value: 0.9493812794138436 and parameters: {'solver': 'saga', 'C': 0.00012393531393550093, 'l1_ratio': 0.9053243058233588, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 9.33535688894947e-05, 'max_iter': 2506}. Best is trial 8 with value: 0.949561066344357.

Best trial: 8. Best value: 0.949561:   2%|▏         | 8/500 [01:10<52:52,  6.45s/it]

[I 2026-05-18 17:07:21,403] Trial 4 finished with value: 0.9495388836807853 and parameters: {'solver': 'saga', 'C': 0.010661210283341247, 'l1_ratio': 0.6833582959110546, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003542478395289752, 'max_iter': 4717}. Best is trial 8 with value: 0.949561066344357.

Best trial: 8. Best value: 0.949561:   2%|▏         | 9/500 [01:24<1:11:02,  8.68s/it]

[I 2026-05-18 17:07:34,996] Trial 17 finished with value: 0.9494260425840094 and parameters: {'solver': 'saga', 'C': 0.00011929846648933355, 'l1_ratio': 0.5390875624702173, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0009026338536457148, 'max_iter': 1821}. Best is trial 8 with value: 0.949561066344357.

Best trial: 19. Best value: 0.949575:   2%|▏         | 10/500 [01:50<1:55:27, 14.14s/it]

[I 2026-05-18 17:08:01,352] Trial 19 finished with value: 0.9495750505265578 and parameters: {'solver': 'saga', 'C': 0.0015621843114868562, 'l1_ratio': 0.49947849744780015, 'class_weight': None, 'fit_intercept': True, 'tol': 3.0577967945846007e-06, 'max_iter': 1418}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 19. Best value: 0.949575:   2%|▏         | 11/500 [03:19<5:01:56, 37.05s/it]

[I 2026-05-18 17:09:30,340] Trial 0 finished with value: 0.9495199207983364 and parameters: {'solver': 'saga', 'C': 0.35026573408819445, 'l1_ratio': 0.21451335388261317, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00019755403848464845, 'max_iter': 4345}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 19. Best value: 0.949575:   2%|▏         | 12/500 [03:31<3:59:20, 29.43s/it]

[I 2026-05-18 17:09:42,342] Trial 9 finished with value: 0.9495150003378925 and parameters: {'solver': 'saga', 'C': 1.0761309090661912, 'l1_ratio': 0.08871776949904753, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00024099545593163132, 'max_iter': 3322}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 19. Best value: 0.949575:   3%|▎         | 13/500 [03:59<3:54:25, 28.88s/it]

[I 2026-05-18 17:10:09,966] Trial 22 finished with value: 0.9495608036116275 and parameters: {'solver': 'saga', 'C': 0.0015267818266046888, 'l1_ratio': 0.054949188636531476, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4668832506476142e-06, 'max_iter': 3561}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 19. Best value: 0.949575:   3%|▎         | 14/500 [04:17<3:28:35, 25.75s/it]

[I 2026-05-18 17:10:28,486] Trial 23 finished with value: 0.9495521694513933 and parameters: {'solver': 'saga', 'C': 0.0019043924389933286, 'l1_ratio': 0.019738622335053843, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2045339419876585e-06, 'max_iter': 3403}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 19. Best value: 0.949575:   3%|▎         | 15/500 [04:18<2:28:04, 18.32s/it]

[I 2026-05-18 17:10:29,582] Trial 18 finished with value: 0.9495091607252221 and parameters: {'solver': 'saga', 'C': 0.15671340543011963, 'l1_ratio': 0.9896700993013131, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0005393339919532686, 'max_iter': 2370}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 19. Best value: 0.949575:   3%|▎         | 16/500 [04:20<1:46:46, 13.24s/it]

[I 2026-05-18 17:10:31,011] Trial 2 finished with value: 0.949509845739106 and parameters: {'solver': 'saga', 'C': 0.09032840912280911, 'l1_ratio': 0.8596662535664402, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00013419957467584404, 'max_iter': 1037}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 19. Best value: 0.949575:   3%|▎         | 17/500 [04:29<1:36:03, 11.93s/it]

[I 2026-05-18 17:10:39,912] Trial 1 finished with value: 0.9495095456555062 and parameters: {'solver': 'saga', 'C': 10.80767507402734, 'l1_ratio': 0.9711742970953409, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007286979088490972, 'max_iter': 3754}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 19. Best value: 0.949575:   4%|▎         | 18/500 [04:34<1:21:28, 10.14s/it]

[I 2026-05-18 17:10:45,891] Trial 26 pruned.

Best trial: 19. Best value: 0.949575:   4%|▍         | 19/500 [04:46<1:23:35, 10.43s/it]

[I 2026-05-18 17:10:56,979] Trial 7 finished with value: 0.9495239500406342 and parameters: {'solver': 'saga', 'C': 77.73366319382218, 'l1_ratio': 0.09189185830946256, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002652110249695459, 'max_iter': 3615}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 19. Best value: 0.949575:   4%|▍         | 20/500 [06:58<6:16:41, 47.09s/it]

[I 2026-05-18 17:13:09,504] Trial 29 finished with value: 0.9495393111794421 and parameters: {'solver': 'saga', 'C': 0.010407567153747169, 'l1_ratio': 0.6653206807778612, 'class_weight': None, 'fit_intercept': True, 'tol': 4.128422105216028e-06, 'max_iter': 2885}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 19. Best value: 0.949575:   4%|▍         | 21/500 [07:10<4:50:57, 36.44s/it]

[I 2026-05-18 17:13:21,134] Trial 30 finished with value: 0.9495404588587194 and parameters: {'solver': 'saga', 'C': 0.008733028802473815, 'l1_ratio': 0.7102349269426953, 'class_weight': None, 'fit_intercept': True, 'tol': 3.3441359079496466e-06, 'max_iter': 2782}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 19. Best value: 0.949575:   4%|▍         | 22/500 [07:25<3:59:37, 30.08s/it]

[I 2026-05-18 17:13:36,369] Trial 31 finished with value: 0.9495717892251191 and parameters: {'solver': 'saga', 'C': 0.0006144248845723191, 'l1_ratio': 0.3979644563088385, 'class_weight': None, 'fit_intercept': True, 'tol': 3.146788275809936e-05, 'max_iter': 4170}. Best is trial 19 with value: 0.9495750505265578.

Best trial: 32. Best value: 0.949576:   5%|▍         | 23/500 [07:46<3:37:16, 27.33s/it]

[I 2026-05-18 17:13:57,280] Trial 13 finished with value: 0.949505340004318 and parameters: {'solver': 'saga', 'C': 0.15085951422453958, 'l1_ratio': 0.7452222374251986, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0002624556701942133, 'max_iter': 1790}. Best is trial 19 with value: 0.9495750505265578.
[I 2026-05-18 17:13:57,382] Trial 32 finished with value: 0.949576495463963 and parameters: {'solver': 'saga', 'C': 0.001041375763691221, 'l1_ratio': 0.44653099208131736, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1227786456019308e-06, 'max_iter': 4079}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   5%|▌         | 25/500 [07:52<2:07:49, 16.15s/it]

[I 2026-05-18 17:14:03,495] Trial 33 finished with value: 0.9495619981458437 and parameters: {'solver': 'saga', 'C': 0.0005529836044299298, 'l1_ratio': 0.4417023316164812, 'class_weight': None, 'fit_intercept': True, 'tol': 2.8187658274396038e-05, 'max_iter': 4007}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   5%|▌         | 26/500 [08:11<2:13:04, 16.85s/it]

[I 2026-05-18 17:14:22,461] Trial 35 finished with value: 0.9495446004708465 and parameters: {'solver': 'saga', 'C': 0.00042807125965019515, 'l1_ratio': 0.43985702220585654, 'class_weight': None, 'fit_intercept': True, 'tol': 3.602192489602812e-05, 'max_iter': 3963}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   5%|▌         | 27/500 [08:13<1:41:36, 12.89s/it]

[I 2026-05-18 17:14:24,183] Trial 34 finished with value: 0.9495378070325732 and parameters: {'solver': 'saga', 'C': 0.000333578413434888, 'l1_ratio': 0.4145217393359867, 'class_weight': None, 'fit_intercept': True, 'tol': 3.033790946452965e-05, 'max_iter': 4246}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   6%|▌         | 28/500 [08:50<2:32:41, 19.41s/it]

[I 2026-05-18 17:15:01,041] Trial 36 finished with value: 0.9495649309581925 and parameters: {'solver': 'saga', 'C': 0.00285509302971467, 'l1_ratio': 0.44837395860553286, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8859151071932523e-06, 'max_iter': 4096}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   6%|▌         | 29/500 [08:55<2:02:00, 15.54s/it]

[I 2026-05-18 17:15:06,634] Trial 24 finished with value: 0.9495301165695839 and parameters: {'solver': 'saga', 'C': 0.04231420251830561, 'l1_ratio': 0.37730664960464133, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6942399195632765e-05, 'max_iter': 2758}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   6%|▌         | 30/500 [09:13<2:07:46, 16.31s/it]

[I 2026-05-18 17:15:24,866] Trial 40 pruned.

Best trial: 32. Best value: 0.949576:   6%|▌         | 31/500 [09:26<1:59:31, 15.29s/it]

[I 2026-05-18 17:15:37,656] Trial 38 finished with value: 0.9495546798967835 and parameters: {'solver': 'saga', 'C': 0.003640980103513818, 'l1_ratio': 0.600370675434393, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0100954559114137e-05, 'max_iter': 3119}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   6%|▋         | 32/500 [10:02<2:46:43, 21.38s/it]

[I 2026-05-18 17:16:13,730] Trial 10 finished with value: 0.9495167595023959 and parameters: {'solver': 'saga', 'C': 63.99190671199797, 'l1_ratio': 0.1450723717369492, 'class_weight': None, 'fit_intercept': False, 'tol': 1.0914378500918844e-05, 'max_iter': 3421}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   7%|▋         | 33/500 [10:05<2:03:15, 15.84s/it]

[I 2026-05-18 17:16:16,316] Trial 42 finished with value: 0.9495757440018441 and parameters: {'solver': 'saga', 'C': 0.0015232498100826528, 'l1_ratio': 0.49102357850148726, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1917356815228928e-06, 'max_iter': 4045}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   7%|▋         | 34/500 [10:22<2:04:53, 16.08s/it]

[I 2026-05-18 17:16:32,973] Trial 41 finished with value: 0.949562361231257 and parameters: {'solver': 'saga', 'C': 0.004180919534559356, 'l1_ratio': 0.31641486647585726, 'class_weight': None, 'fit_intercept': True, 'tol': 2.375973132251479e-06, 'max_iter': 3274}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   7%|▋         | 35/500 [10:57<2:49:43, 21.90s/it]

[I 2026-05-18 17:17:08,627] Trial 37 finished with value: 0.9495307106607452 and parameters: {'solver': 'saga', 'C': 0.037389685951130965, 'l1_ratio': 0.6035563348592367, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0791324110526888e-05, 'max_iter': 4297}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   7%|▋         | 36/500 [11:20<2:50:13, 22.01s/it]

[I 2026-05-18 17:17:30,900] Trial 46 pruned.

Best trial: 32. Best value: 0.949576:   7%|▋         | 37/500 [11:26<2:13:10, 17.26s/it]

[I 2026-05-18 17:17:37,002] Trial 39 finished with value: 0.9495313351567611 and parameters: {'solver': 'saga', 'C': 0.03355584144517786, 'l1_ratio': 0.5897289477838304, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0798428950155685e-05, 'max_iter': 4651}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   8%|▊         | 38/500 [11:32<1:48:07, 14.04s/it]

[I 2026-05-18 17:17:43,500] Trial 43 finished with value: 0.9495552168309862 and parameters: {'solver': 'saga', 'C': 0.005644384954669996, 'l1_ratio': 0.31684490715342456, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8367845451089478e-06, 'max_iter': 3934}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   8%|▊         | 39/500 [11:56<2:11:02, 17.05s/it]

[I 2026-05-18 17:18:07,609] Trial 47 finished with value: 0.9495720617555456 and parameters: {'solver': 'saga', 'C': 0.0010006605635977431, 'l1_ratio': 0.5061180682519095, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0019255163452787e-06, 'max_iter': 4577}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   8%|▊         | 40/500 [12:03<1:47:57, 14.08s/it]

[I 2026-05-18 17:18:14,737] Trial 48 finished with value: 0.949573731684983 and parameters: {'solver': 'saga', 'C': 0.0010925573858644193, 'l1_ratio': 0.5057970391869201, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1319830326490007e-06, 'max_iter': 3693}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   8%|▊         | 41/500 [12:15<1:41:40, 13.29s/it]

[I 2026-05-18 17:18:26,186] Trial 49 finished with value: 0.9495758001661828 and parameters: {'solver': 'saga', 'C': 0.0014349149290386286, 'l1_ratio': 0.5100434486286853, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0264342406030986e-06, 'max_iter': 3733}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   8%|▊         | 42/500 [12:30<1:44:54, 13.74s/it]

[I 2026-05-18 17:18:40,985] Trial 50 finished with value: 0.9495753328823874 and parameters: {'solver': 'saga', 'C': 0.0013062239407339437, 'l1_ratio': 0.5260250171232921, 'class_weight': None, 'fit_intercept': True, 'tol': 6.564589571814926e-06, 'max_iter': 4650}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   9%|▊         | 43/500 [12:37<1:30:03, 11.82s/it]

[I 2026-05-18 17:18:48,323] Trial 51 finished with value: 0.9494677237313731 and parameters: {'solver': 'saga', 'C': 0.0002167880330262273, 'l1_ratio': 0.7928142564532947, 'class_weight': None, 'fit_intercept': True, 'tol': 3.302082600301732e-06, 'max_iter': 3727}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   9%|▉         | 44/500 [12:49<1:30:27, 11.90s/it]

[I 2026-05-18 17:19:00,414] Trial 52 finished with value: 0.9495002312391572 and parameters: {'solver': 'saga', 'C': 0.0002010252532501842, 'l1_ratio': 0.4994928866061464, 'class_weight': None, 'fit_intercept': True, 'tol': 3.2048214745426745e-06, 'max_iter': 3787}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   9%|▉         | 45/500 [13:03<1:35:56, 12.65s/it]

[I 2026-05-18 17:19:14,812] Trial 53 finished with value: 0.9494260356746373 and parameters: {'solver': 'saga', 'C': 0.00014715363447236155, 'l1_ratio': 0.6463469537288087, 'class_weight': None, 'fit_intercept': True, 'tol': 3.3906490778733293e-06, 'max_iter': 1141}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   9%|▉         | 46/500 [13:30<2:07:45, 16.88s/it]

[I 2026-05-18 17:19:41,573] Trial 54 finished with value: 0.9495656503330986 and parameters: {'solver': 'saga', 'C': 0.002031842691983925, 'l1_ratio': 0.63469600380036, 'class_weight': None, 'fit_intercept': True, 'tol': 6.484207998447724e-06, 'max_iter': 1234}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:   9%|▉         | 47/500 [13:33<1:34:38, 12.53s/it]

[I 2026-05-18 17:19:43,951] Trial 45 finished with value: 0.9495317685065346 and parameters: {'solver': 'saga', 'C': 0.03181712791777004, 'l1_ratio': 0.5068615192138224, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5774301714733546e-06, 'max_iter': 3815}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  10%|▉         | 48/500 [13:47<1:38:56, 13.13s/it]

[I 2026-05-18 17:19:58,495] Trial 27 finished with value: 0.9495223031401274 and parameters: {'solver': 'saga', 'C': 54.326366664394286, 'l1_ratio': 0.3950884491685497, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9279929040519563e-05, 'max_iter': 2730}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  10%|▉         | 49/500 [13:53<1:21:20, 10.82s/it]

[I 2026-05-18 17:20:03,918] Trial 25 finished with value: 0.9495273887433102 and parameters: {'solver': 'saga', 'C': 0.10743799038086449, 'l1_ratio': 0.3680023930235536, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4457955306997052e-05, 'max_iter': 2523}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  10%|█         | 50/500 [13:53<57:18,  7.64s/it]

[I 2026-05-18 17:20:04,131] Trial 28 finished with value: 0.9495237959805098 and parameters: {'solver': 'saga', 'C': 75.856174863934, 'l1_ratio': 0.39877854037835864, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1214071207223058e-05, 'max_iter': 2843}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  10%|█         | 51/500 [14:18<1:37:17, 13.00s/it]

[I 2026-05-18 17:20:29,643] Trial 59 finished with value: 0.9489264962423881 and parameters: {'solver': 'saga', 'C': 5.152655954975399e-05, 'l1_ratio': 0.5417948869207468, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.291130414389551e-06, 'max_iter': 4796}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  10%|█         | 52/500 [14:46<2:09:14, 17.31s/it]

[I 2026-05-18 17:20:57,006] Trial 62 pruned.

Best trial: 32. Best value: 0.949576:  11%|█         | 53/500 [15:20<2:47:39, 22.50s/it]

[I 2026-05-18 17:21:31,633] Trial 63 finished with value: 0.9495689593043002 and parameters: {'solver': 'saga', 'C': 0.0010115556256669268, 'l1_ratio': 0.5502815640288234, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0322978536700177e-06, 'max_iter': 3090}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  11%|█         | 54/500 [15:28<2:14:29, 18.09s/it]

[I 2026-05-18 17:21:39,434] Trial 55 finished with value: 0.9495337318174581 and parameters: {'solver': 'saga', 'C': 0.020758055272284904, 'l1_ratio': 0.6385883466931863, 'class_weight': None, 'fit_intercept': True, 'tol': 5.244845682612262e-06, 'max_iter': 1135}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  11%|█         | 55/500 [16:14<3:15:39, 26.38s/it]

[I 2026-05-18 17:22:25,151] Trial 58 finished with value: 0.9495170782000576 and parameters: {'solver': 'saga', 'C': 0.01345891528789506, 'l1_ratio': 0.5477917058714425, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.493604049737248e-06, 'max_iter': 4444}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  11%|█         | 56/500 [16:27<2:45:35, 22.38s/it]

[I 2026-05-18 17:22:38,191] Trial 61 finished with value: 0.9495193947608456 and parameters: {'solver': 'saga', 'C': 0.012009518982731995, 'l1_ratio': 0.5441731144355408, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.116976528286959e-06, 'max_iter': 4845}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  11%|█▏        | 57/500 [16:34<2:11:40, 17.83s/it]

[I 2026-05-18 17:22:45,412] Trial 60 finished with value: 0.9495117696194683 and parameters: {'solver': 'saga', 'C': 0.016456015555392063, 'l1_ratio': 0.26160004889807303, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.997793602477059e-06, 'max_iter': 4387}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  12%|█▏        | 58/500 [16:37<1:38:03, 13.31s/it]

[I 2026-05-18 17:22:48,181] Trial 44 finished with value: 0.9495307254470567 and parameters: {'solver': 'saga', 'C': 0.03790331393386475, 'l1_ratio': 0.32557299926523153, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1312956619530163e-06, 'max_iter': 3735}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  12%|█▏        | 59/500 [16:43<1:22:43, 11.26s/it]

[I 2026-05-18 17:22:54,635] Trial 56 finished with value: 0.9495270998420334 and parameters: {'solver': 'saga', 'C': 0.014698457172747719, 'l1_ratio': 0.5255389232543801, 'class_weight': None, 'fit_intercept': False, 'tol': 6.599446893146089e-06, 'max_iter': 4767}. Best is trial 32 with value: 0.949576495463963.

Best trial: 32. Best value: 0.949576:  12%|█▏        | 60/500 [16:51<1:14:44, 10.19s/it]

[I 2026-05-18 17:23:02,347] Trial 66 finished with value: 0.9495746251944513 and parameters: {'solver': 'saga', 'C': 0.0011462610954631196, 'l1_ratio': 0.5051725406007673, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3842558717231867e-06, 'max_iter': 4115}. Best is trial 32 with value: 0.949576495463963.

Best trial: 68. Best value: 0.949581:  12%|█▏        | 61/500 [17:11<1:36:54, 13.24s/it]

[I 2026-05-18 17:23:22,715] Trial 68 finished with value: 0.9495805783121195 and parameters: {'solver': 'saga', 'C': 0.0009556136862175725, 'l1_ratio': 0.35065342248014697, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3631225510587194e-06, 'max_iter': 2168}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  12%|█▏        | 62/500 [17:18<1:21:22, 11.15s/it]

[I 2026-05-18 17:23:28,970] Trial 69 finished with value: 0.9495422160504889 and parameters: {'solver': 'saga', 'C': 0.0008425805478638512, 'l1_ratio': 0.7062948504117431, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5976799648135088e-06, 'max_iter': 4113}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  13%|█▎        | 63/500 [17:27<1:18:14, 10.74s/it]

[I 2026-05-18 17:23:38,756] Trial 64 finished with value: 0.9495235506618348 and parameters: {'solver': 'saga', 'C': 0.01653078824332816, 'l1_ratio': 0.34219687585583525, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 1.4777974318325804e-06, 'max_iter': 4459}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  13%|█▎        | 64/500 [17:48<1:39:12, 13.65s/it]

[I 2026-05-18 17:23:59,208] Trial 72 finished with value: 0.9495652970485315 and parameters: {'solver': 'saga', 'C': 0.0006645318033387251, 'l1_ratio': 0.46897991260427535, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4478032838415955e-06, 'max_iter': 1653}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  13%|█▎        | 65/500 [18:21<2:22:06, 19.60s/it]

[I 2026-05-18 17:24:32,688] Trial 75 finished with value: 0.9495335504516793 and parameters: {'solver': 'saga', 'C': 0.00031860235570073305, 'l1_ratio': 0.4217855429511099, 'class_weight': None, 'fit_intercept': True, 'tol': 2.617986090480344e-06, 'max_iter': 2217}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  13%|█▎        | 66/500 [18:40<2:19:35, 19.30s/it]

[I 2026-05-18 17:24:51,285] Trial 57 finished with value: 0.9495251640647264 and parameters: {'solver': 'saga', 'C': 0.02040696334024983, 'l1_ratio': 0.5576840252827482, 'class_weight': None, 'fit_intercept': False, 'tol': 6.569652549605055e-06, 'max_iter': 4800}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  13%|█▎        | 67/500 [19:01<2:22:58, 19.81s/it]

[I 2026-05-18 17:25:12,297] Trial 73 finished with value: 0.9495537038877038 and parameters: {'solver': 'saga', 'C': 0.005274370392808485, 'l1_ratio': 0.4673460452175089, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2917554732751631e-06, 'max_iter': 1464}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  14%|█▎        | 68/500 [19:02<1:41:19, 14.07s/it]

[I 2026-05-18 17:25:12,967] Trial 74 finished with value: 0.9495531110310926 and parameters: {'solver': 'saga', 'C': 0.006135943819967206, 'l1_ratio': 0.2525325131943377, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3419380774189732e-06, 'max_iter': 2114}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  14%|█▍        | 69/500 [19:24<1:59:21, 16.62s/it]

[I 2026-05-18 17:25:35,522] Trial 77 finished with value: 0.9495703410220152 and parameters: {'solver': 'saga', 'C': 0.0026508240864886326, 'l1_ratio': 0.2780138669408667, 'class_weight': None, 'fit_intercept': True, 'tol': 4.180681361316081e-06, 'max_iter': 1415}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  14%|█▍        | 70/500 [19:27<1:29:38, 12.51s/it]

[I 2026-05-18 17:25:38,449] Trial 76 finished with value: 0.9495246984787032 and parameters: {'solver': 'saga', 'C': 1.0782747048737285, 'l1_ratio': 0.19529702372923471, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0020868032239632264, 'max_iter': 1434}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  14%|█▍        | 71/500 [19:36<1:21:55, 11.46s/it]

[I 2026-05-18 17:25:47,451] Trial 79 finished with value: 0.9495240032282874 and parameters: {'solver': 'saga', 'C': 1.0178897779132312, 'l1_ratio': 0.35274101099787736, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0042078032066609344, 'max_iter': 3487}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  14%|█▍        | 72/500 [19:40<1:05:48,  9.23s/it]

[I 2026-05-18 17:25:51,460] Trial 78 finished with value: 0.9495717686941015 and parameters: {'solver': 'saga', 'C': 0.002232291953765607, 'l1_ratio': 0.2749328651828459, 'class_weight': None, 'fit_intercept': True, 'tol': 4.034769290827523e-06, 'max_iter': 2088}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  15%|█▍        | 73/500 [19:45<55:39,  7.82s/it]

[I 2026-05-18 17:25:56,010] Trial 70 finished with value: 0.949543766038931 and parameters: {'solver': 'saga', 'C': 0.006054546406626436, 'l1_ratio': 0.724278171887869, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4074788212223436e-06, 'max_iter': 2268}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  15%|█▍        | 74/500 [19:53<57:14,  8.06s/it]

[I 2026-05-18 17:26:04,638] Trial 81 finished with value: 0.9495787734709922 and parameters: {'solver': 'saga', 'C': 0.0013334789533537286, 'l1_ratio': 0.42568587592369855, 'class_weight': None, 'fit_intercept': True, 'tol': 4.755751678567491e-05, 'max_iter': 4206}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  15%|█▌        | 75/500 [20:02<58:00,  8.19s/it]

[I 2026-05-18 17:26:13,117] Trial 80 finished with value: 0.9495223791163436 and parameters: {'solver': 'saga', 'C': 3.099986484239811, 'l1_ratio': 0.3499670494896552, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0036177081448063933, 'max_iter': 4240}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  15%|█▌        | 76/500 [20:14<1:06:39,  9.43s/it]

[I 2026-05-18 17:26:25,455] Trial 82 finished with value: 0.9495784530572516 and parameters: {'solver': 'saga', 'C': 0.0012476465501808694, 'l1_ratio': 0.42932687020211613, 'class_weight': None, 'fit_intercept': True, 'tol': 1.038367741565881e-06, 'max_iter': 4079}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  15%|█▌        | 77/500 [20:18<55:38,  7.89s/it]

[I 2026-05-18 17:26:29,749] Trial 85 finished with value: 0.9495786473872971 and parameters: {'solver': 'saga', 'C': 0.0013583121219308265, 'l1_ratio': 0.4257343036297381, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015001279137972508, 'max_iter': 4233}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  16%|█▌        | 78/500 [20:20<42:11,  6.00s/it]

[I 2026-05-18 17:26:31,340] Trial 83 finished with value: 0.9495783236044375 and parameters: {'solver': 'saga', 'C': 0.001190679006371646, 'l1_ratio': 0.4319305565975624, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1339655424534553e-06, 'max_iter': 4276}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  16%|█▌        | 79/500 [20:29<49:06,  7.00s/it]

[I 2026-05-18 17:26:40,670] Trial 86 finished with value: 0.9495776248127197 and parameters: {'solver': 'saga', 'C': 0.001437917359901746, 'l1_ratio': 0.4394825071169383, 'class_weight': None, 'fit_intercept': True, 'tol': 4.217099644991242e-05, 'max_iter': 4195}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  16%|█▌        | 80/500 [20:35<46:48,  6.69s/it]

[I 2026-05-18 17:26:46,632] Trial 84 finished with value: 0.9495721900073875 and parameters: {'solver': 'saga', 'C': 0.001515481270527758, 'l1_ratio': 0.577501467846226, 'class_weight': None, 'fit_intercept': True, 'tol': 1.01260851297171e-06, 'max_iter': 4024}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  16%|█▌        | 81/500 [20:37<36:15,  5.19s/it]

[I 2026-05-18 17:26:48,336] Trial 87 finished with value: 0.9495424932315124 and parameters: {'solver': 'saga', 'C': 0.00039191891831144956, 'l1_ratio': 0.4263410132498249, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004329508423586897, 'max_iter': 2602}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  16%|█▋        | 82/500 [20:44<40:08,  5.76s/it]

[I 2026-05-18 17:26:55,425] Trial 88 finished with value: 0.9495565973698417 and parameters: {'solver': 'saga', 'C': 0.0004603320555896367, 'l1_ratio': 0.4150493973929794, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015769816622073158, 'max_iter': 3971}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  17%|█▋        | 83/500 [20:46<31:52,  4.59s/it]

[I 2026-05-18 17:26:57,271] Trial 89 finished with value: 0.949559507206191 and parameters: {'solver': 'saga', 'C': 0.0004918497519823271, 'l1_ratio': 0.4217000090593425, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016299077755528777, 'max_iter': 4015}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  17%|█▋        | 84/500 [20:54<39:14,  5.66s/it]

[I 2026-05-18 17:27:05,437] Trial 90 finished with value: 0.9495643461225735 and parameters: {'solver': 'saga', 'C': 0.0005546121132725768, 'l1_ratio': 0.4282910243764131, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010887516196109839, 'max_iter': 4330}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  17%|█▋        | 85/500 [21:03<45:29,  6.58s/it]

[I 2026-05-18 17:27:14,154] Trial 91 finished with value: 0.9495397022957917 and parameters: {'solver': 'saga', 'C': 0.0003659495528321067, 'l1_ratio': 0.4225673408747259, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015465901311159173, 'max_iter': 4315}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  17%|█▋        | 86/500 [21:11<48:55,  7.09s/it]

[I 2026-05-18 17:27:22,441] Trial 92 finished with value: 0.949565089503485 and parameters: {'solver': 'saga', 'C': 0.0032047497638365654, 'l1_ratio': 0.3990759679395399, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016460268638820134, 'max_iter': 4307}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  17%|█▋        | 87/500 [21:25<1:02:42,  9.11s/it]

[I 2026-05-18 17:27:36,263] Trial 94 finished with value: 0.9495663012507777 and parameters: {'solver': 'saga', 'C': 0.0030476488103705094, 'l1_ratio': 0.38672688228571556, 'class_weight': None, 'fit_intercept': True, 'tol': 5.933971950601272e-05, 'max_iter': 4314}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  18%|█▊        | 88/500 [21:26<46:40,  6.80s/it]

[I 2026-05-18 17:27:37,659] Trial 93 finished with value: 0.9495640778279129 and parameters: {'solver': 'saga', 'C': 0.0034406424312674036, 'l1_ratio': 0.40068995941773883, 'class_weight': None, 'fit_intercept': True, 'tol': 5.859423612101502e-05, 'max_iter': 4227}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  18%|█▊        | 89/500 [21:40<1:01:25,  8.97s/it]

[I 2026-05-18 17:27:51,698] Trial 97 finished with value: 0.949578914108176 and parameters: {'solver': 'saga', 'C': 0.0008387196661702571, 'l1_ratio': 0.36769610518377904, 'class_weight': None, 'fit_intercept': True, 'tol': 3.725135765879681e-05, 'max_iter': 4188}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  18%|█▊        | 90/500 [21:41<44:08,  6.46s/it]

[I 2026-05-18 17:27:52,307] Trial 95 finished with value: 0.9495624138875762 and parameters: {'solver': 'saga', 'C': 0.003421921347183637, 'l1_ratio': 0.45133562896517504, 'class_weight': None, 'fit_intercept': True, 'tol': 5.341454202051262e-05, 'max_iter': 4195}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  18%|█▊        | 91/500 [21:51<51:18,  7.53s/it]

[I 2026-05-18 17:28:02,322] Trial 98 finished with value: 0.9495048979688623 and parameters: {'solver': 'saga', 'C': 0.00021658623143523632, 'l1_ratio': 0.452422815488467, 'class_weight': None, 'fit_intercept': True, 'tol': 7.526715672711564e-05, 'max_iter': 4194}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  18%|█▊        | 92/500 [21:54<41:13,  6.06s/it]

[I 2026-05-18 17:28:04,972] Trial 99 finished with value: 0.9495227759811365 and parameters: {'solver': 'saga', 'C': 0.0002102505997315917, 'l1_ratio': 0.36512695798966305, 'class_weight': None, 'fit_intercept': True, 'tol': 4.4837513807322885e-05, 'max_iter': 3893}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  19%|█▊        | 93/500 [21:54<30:01,  4.43s/it]

[I 2026-05-18 17:28:05,576] Trial 96 finished with value: 0.9495604199890003 and parameters: {'solver': 'saga', 'C': 0.0038754200476909684, 'l1_ratio': 0.4545815587249505, 'class_weight': None, 'fit_intercept': True, 'tol': 5.194712171004394e-05, 'max_iter': 4182}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  19%|█▉        | 94/500 [22:07<46:47,  6.91s/it]

[I 2026-05-18 17:28:18,297] Trial 100 finished with value: 0.9495799675619814 and parameters: {'solver': 'saga', 'C': 0.0007238265371778201, 'l1_ratio': 0.2943138984320953, 'class_weight': None, 'fit_intercept': True, 'tol': 8.140381785005025e-05, 'max_iter': 3878}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  19%|█▉        | 95/500 [22:10<39:55,  5.91s/it]

[I 2026-05-18 17:28:21,878] Trial 101 finished with value: 0.949365133152366 and parameters: {'solver': 'saga', 'C': 8.673713958389852e-05, 'l1_ratio': 0.3669263060094201, 'class_weight': None, 'fit_intercept': True, 'tol': 4.3114501279600024e-05, 'max_iter': 4494}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 68. Best value: 0.949581:  19%|█▉        | 96/500 [22:15<36:24,  5.41s/it]

[I 2026-05-18 17:28:26,098] Trial 102 finished with value: 0.9495782074809467 and parameters: {'solver': 'saga', 'C': 0.0007492327014254127, 'l1_ratio': 0.36607149510787174, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002298853522881816, 'max_iter': 3858}. Best is trial 68 with value: 0.9495805783121195.

Best trial: 104. Best value: 0.949581:  19%|█▉        | 97/500 [22:19<33:45,  5.03s/it]

[I 2026-05-18 17:28:30,239] Trial 104 finished with value: 0.9495809729670872 and parameters: {'solver': 'saga', 'C': 0.0008676896336807316, 'l1_ratio': 0.3065727735439315, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003017910434184575, 'max_iter': 4560}. Best is trial 104 with value: 0.9495809729670872.

Best trial: 103. Best value: 0.949581:  20%|█▉        | 98/500 [22:32<50:23,  7.52s/it]

[I 2026-05-18 17:28:43,577] Trial 103 finished with value: 0.9495814433775219 and parameters: {'solver': 'saga', 'C': 0.0008898965921467019, 'l1_ratio': 0.2991082819867581, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9136086601844667e-06, 'max_iter': 4626}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  20%|█▉        | 99/500 [22:33<37:11,  5.56s/it]

[I 2026-05-18 17:28:44,582] Trial 105 finished with value: 0.9495800025354619 and parameters: {'solver': 'saga', 'C': 0.0007208299149753827, 'l1_ratio': 0.29180631729773815, 'class_weight': None, 'fit_intercept': True, 'tol': 9.382327073844462e-05, 'max_iter': 4521}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  20%|██        | 100/500 [22:37<33:17,  4.99s/it]

[I 2026-05-18 17:28:48,239] Trial 106 finished with value: 0.9495808965175263 and parameters: {'solver': 'saga', 'C': 0.0008377140582759618, 'l1_ratio': 0.2943552061572518, 'class_weight': None, 'fit_intercept': True, 'tol': 9.38653653018244e-05, 'max_iter': 3646}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  20%|██        | 101/500 [22:38<25:45,  3.87s/it]

[I 2026-05-18 17:28:49,503] Trial 107 finished with value: 0.9495785607945159 and parameters: {'solver': 'saga', 'C': 0.000648802632094691, 'l1_ratio': 0.2159954982643837, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00021814224805744568, 'max_iter': 4582}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  20%|██        | 102/500 [22:44<30:39,  4.62s/it]

[I 2026-05-18 17:28:55,870] Trial 108 finished with value: 0.9495798722401743 and parameters: {'solver': 'saga', 'C': 0.0007306521583975934, 'l1_ratio': 0.30088525233810204, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024793422864387803, 'max_iter': 4620}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  21%|██        | 103/500 [22:54<40:22,  6.10s/it]

[I 2026-05-18 17:29:05,422] Trial 110 finished with value: 0.9495623545579861 and parameters: {'solver': 'saga', 'C': 0.00029687166279168225, 'l1_ratio': 0.19872894491521065, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007926953535395782, 'max_iter': 4977}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  21%|██        | 104/500 [22:56<31:12,  4.73s/it]

[I 2026-05-18 17:29:06,953] Trial 20 finished with value: 0.9495080604177378 and parameters: {'solver': 'saga', 'C': 0.13545377649633966, 'l1_ratio': 0.4639007356829944, 'class_weight': None, 'fit_intercept': False, 'tol': 2.860690167016552e-06, 'max_iter': 4281}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  21%|██        | 105/500 [22:57<24:32,  3.73s/it]

[I 2026-05-18 17:29:08,338] Trial 109 finished with value: 0.9495797441087497 and parameters: {'solver': 'saga', 'C': 0.0007861110147887535, 'l1_ratio': 0.21250256403518025, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00035975630464726664, 'max_iter': 4991}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  21%|██        | 106/500 [23:02<27:55,  4.25s/it]

[I 2026-05-18 17:29:13,819] Trial 112 finished with value: 0.949559784551435 and parameters: {'solver': 'saga', 'C': 0.00028252430960113535, 'l1_ratio': 0.2148960693533725, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003376981016646265, 'max_iter': 4670}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  21%|██▏       | 107/500 [23:04<21:47,  3.33s/it]

[I 2026-05-18 17:29:14,983] Trial 111 finished with value: 0.9494753867019805 and parameters: {'solver': 'saga', 'C': 8.144692426151813e-05, 'l1_ratio': 0.18933716452643934, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.819092990521612e-05, 'max_iter': 4610}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  22%|██▏       | 108/500 [23:09<24:59,  3.82s/it]

[I 2026-05-18 17:29:19,971] Trial 113 finished with value: 0.9495799221133258 and parameters: {'solver': 'saga', 'C': 0.0007385284443302879, 'l1_ratio': 0.2230649685744703, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000295116533262032, 'max_iter': 4662}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  22%|██▏       | 109/500 [23:20<39:17,  6.03s/it]

[I 2026-05-18 17:29:31,139] Trial 115 finished with value: 0.949579678111041 and parameters: {'solver': 'saga', 'C': 0.0007463661534339556, 'l1_ratio': 0.224605559437618, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003593248695852502, 'max_iter': 4622}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  22%|██▏       | 110/500 [23:20<27:50,  4.28s/it]

[I 2026-05-18 17:29:31,347] Trial 116 finished with value: 0.949509987528006 and parameters: {'solver': 'saga', 'C': 0.00015907492382856341, 'l1_ratio': 0.29154792851837463, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0003082196792671518, 'max_iter': 4717}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  22%|██▏       | 111/500 [23:21<20:45,  3.20s/it]

[I 2026-05-18 17:29:32,036] Trial 114 finished with value: 0.9495795943410451 and parameters: {'solver': 'saga', 'C': 0.0007318741555168035, 'l1_ratio': 0.22139415358560885, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00032305578847078296, 'max_iter': 4626}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  23%|██▎       | 113/500 [23:28<19:46,  3.07s/it]

[I 2026-05-18 17:29:38,889] Trial 118 finished with value: 0.9495810811420217 and parameters: {'solver': 'saga', 'C': 0.0008378274920361342, 'l1_ratio': 0.2884284155636125, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002947225983194337, 'max_iter': 4738}. Best is trial 103 with value: 0.9495814433775219.
[I 2026-05-18 17:29:39,071] Trial 117 finished with value: 0.9494984415091187 and parameters: {'solver': 'saga', 'C': 0.0001356039932691298, 'l1_ratio': 0.3016937726403815, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.743519640467642e-05, 'max_iter': 4911}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  23%|██▎       | 114/500 [23:32<21:58,  3.42s/it]

[I 2026-05-18 17:29:43,318] Trial 119 finished with value: 0.9495200563680095 and parameters: {'solver': 'saga', 'C': 0.00016430378496091346, 'l1_ratio': 0.15629364097134307, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000579184797710259, 'max_iter': 4913}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  23%|██▎       | 115/500 [23:43<35:56,  5.60s/it]

[I 2026-05-18 17:29:54,024] Trial 122 finished with value: 0.9495752065098244 and parameters: {'solver': 'saga', 'C': 0.000823885700820781, 'l1_ratio': 0.14721568083486306, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005110266821504467, 'max_iter': 4911}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  23%|██▎       | 116/500 [23:43<25:42,  4.02s/it]

[I 2026-05-18 17:29:54,339] Trial 121 finished with value: 0.9495728638278923 and parameters: {'solver': 'saga', 'C': 0.0008858086429192584, 'l1_ratio': 0.1293377990646236, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004837651926966778, 'max_iter': 4900}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  23%|██▎       | 117/500 [23:44<19:04,  2.99s/it]

[I 2026-05-18 17:29:54,924] Trial 120 finished with value: 0.9494955864022743 and parameters: {'solver': 'saga', 'C': 0.00013834710349240305, 'l1_ratio': 0.1365917067849422, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006087355511648783, 'max_iter': 4747}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  24%|██▎       | 118/500 [23:51<27:32,  4.33s/it]

[I 2026-05-18 17:30:02,378] Trial 124 finished with value: 0.9495671777657828 and parameters: {'solver': 'saga', 'C': 0.0021033384606043764, 'l1_ratio': 0.14384337880885142, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005084058459045865, 'max_iter': 4543}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  24%|██▍       | 119/500 [23:51<19:38,  3.09s/it]

[I 2026-05-18 17:30:02,595] Trial 123 finished with value: 0.9495756005280903 and parameters: {'solver': 'saga', 'C': 0.0007675346166743693, 'l1_ratio': 0.14765528295264338, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004504654013113307, 'max_iter': 4937}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  24%|██▍       | 120/500 [24:06<41:26,  6.54s/it]

[I 2026-05-18 17:30:17,180] Trial 127 finished with value: 0.9495721942656464 and parameters: {'solver': 'saga', 'C': 0.002015128137970338, 'l1_ratio': 0.22873504230286645, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002672928865301188, 'max_iter': 4543}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  24%|██▍       | 121/500 [24:07<30:25,  4.82s/it]

[I 2026-05-18 17:30:17,979] Trial 126 finished with value: 0.9495717063900159 and parameters: {'solver': 'saga', 'C': 0.0021242103617156566, 'l1_ratio': 0.22948112936132622, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002716315707932283, 'max_iter': 4723}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  24%|██▍       | 122/500 [24:07<22:20,  3.55s/it]

[I 2026-05-18 17:30:18,556] Trial 128 finished with value: 0.9495739600546115 and parameters: {'solver': 'saga', 'C': 0.0004534826267728583, 'l1_ratio': 0.23141669767665274, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002924031448888171, 'max_iter': 4556}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  25%|██▍       | 123/500 [24:11<22:37,  3.60s/it]

[I 2026-05-18 17:30:22,284] Trial 129 finished with value: 0.9495773028918718 and parameters: {'solver': 'saga', 'C': 0.0005362401534875552, 'l1_ratio': 0.24019888177682563, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001223788042263535, 'max_iter': 4432}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  25%|██▍       | 124/500 [24:14<20:54,  3.34s/it]

[I 2026-05-18 17:30:25,007] Trial 130 finished with value: 0.9495764988144433 and parameters: {'solver': 'saga', 'C': 0.0005279273260725175, 'l1_ratio': 0.23903552739776748, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00027944724841006807, 'max_iter': 4447}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  25%|██▌       | 125/500 [24:30<44:46,  7.16s/it]

[I 2026-05-18 17:30:41,098] Trial 132 finished with value: 0.9495759361622149 and parameters: {'solver': 'saga', 'C': 0.0005145685344722222, 'l1_ratio': 0.2689373543498144, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00040099808246700573, 'max_iter': 4388}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  25%|██▌       | 126/500 [24:33<37:02,  5.94s/it]

[I 2026-05-18 17:30:44,191] Trial 131 finished with value: 0.949575803891553 and parameters: {'solver': 'saga', 'C': 0.0005111606151966342, 'l1_ratio': 0.23326242305022118, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012309573493989192, 'max_iter': 4819}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  25%|██▌       | 127/500 [24:33<26:47,  4.31s/it]

[I 2026-05-18 17:30:44,697] Trial 133 finished with value: 0.9495762795714089 and parameters: {'solver': 'saga', 'C': 0.0005631975406469088, 'l1_ratio': 0.3312562949762255, 'class_weight': None, 'fit_intercept': True, 'tol': 8.067142177048263e-05, 'max_iter': 4383}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  26%|██▌       | 128/500 [24:36<23:15,  3.75s/it]

[I 2026-05-18 17:30:47,141] Trial 134 finished with value: 0.9495770053757866 and parameters: {'solver': 'saga', 'C': 0.0006056068218195445, 'l1_ratio': 0.31950649618537585, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012743637354587734, 'max_iter': 4401}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  26%|██▌       | 129/500 [24:41<26:25,  4.27s/it]

[I 2026-05-18 17:30:52,634] Trial 135 finished with value: 0.9495513808729077 and parameters: {'solver': 'saga', 'C': 0.0002710128482503602, 'l1_ratio': 0.327700103515529, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001949295081839724, 'max_iter': 4836}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  26%|██▌       | 130/500 [24:49<33:42,  5.47s/it]

[I 2026-05-18 17:31:00,872] Trial 139 pruned.

Best trial: 103. Best value: 0.949581:  26%|██▌       | 131/500 [24:52<29:01,  4.72s/it]

[I 2026-05-18 17:31:03,862] Trial 137 finished with value: 0.9495558542969527 and parameters: {'solver': 'saga', 'C': 0.0003182215246682603, 'l1_ratio': 0.3274232312455761, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010444020349450393, 'max_iter': 3294}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  26%|██▋       | 132/500 [24:58<29:59,  4.89s/it]

[I 2026-05-18 17:31:09,153] Trial 136 finished with value: 0.9495545809114476 and parameters: {'solver': 'saga', 'C': 0.0002836977167686163, 'l1_ratio': 0.31346954430187496, 'class_weight': None, 'fit_intercept': True, 'tol': 7.64147425931145e-05, 'max_iter': 4650}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 103. Best value: 0.949581:  27%|██▋       | 133/500 [24:58<21:36,  3.53s/it]

[I 2026-05-18 17:31:09,514] Trial 138 finished with value: 0.9495610054207566 and parameters: {'solver': 'saga', 'C': 0.00033009706977299484, 'l1_ratio': 0.2902140900198429, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018615397709707598, 'max_iter': 4660}. Best is trial 103 with value: 0.9495814433775219.

Best trial: 142. Best value: 0.949582:  27%|██▋       | 134/500 [25:16<47:59,  7.87s/it]

[I 2026-05-18 17:31:27,495] Trial 142 finished with value: 0.9495819635507845 and parameters: {'solver': 'saga', 'C': 0.0009545675019697038, 'l1_ratio': 0.2960393568103569, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00033219804270706403, 'max_iter': 4663}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  27%|██▋       | 135/500 [25:17<34:31,  5.68s/it]

[I 2026-05-18 17:31:28,051] Trial 143 finished with value: 0.949581624559619 and parameters: {'solver': 'saga', 'C': 0.0009308853871313152, 'l1_ratio': 0.2877275401669547, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006720053698555799, 'max_iter': 4620}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  27%|██▋       | 136/500 [25:21<31:25,  5.18s/it]

[I 2026-05-18 17:31:32,083] Trial 144 finished with value: 0.9495812000999045 and parameters: {'solver': 'saga', 'C': 0.0009538077261831469, 'l1_ratio': 0.25476269330918794, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003554499107944186, 'max_iter': 4759}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  27%|██▋       | 137/500 [25:37<51:53,  8.58s/it]

[I 2026-05-18 17:31:48,589] Trial 141 finished with value: 0.9495473256109458 and parameters: {'solver': 'saga', 'C': 0.008321531490004997, 'l1_ratio': 0.2902560559658691, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007238899735434969, 'max_iter': 4628}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  28%|██▊       | 139/500 [25:39<27:01,  4.49s/it]

[I 2026-05-18 17:31:49,801] Trial 145 finished with value: 0.9495771432162581 and parameters: {'solver': 'saga', 'C': 0.0009222682994341004, 'l1_ratio': 0.1732039266105147, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000657533741167192, 'max_iter': 4998}. Best is trial 142 with value: 0.9495819635507845.
[I 2026-05-18 17:31:49,914] Trial 146 finished with value: 0.9495762723995901 and parameters: {'solver': 'saga', 'C': 0.0010109368518917655, 'l1_ratio': 0.1750585769306992, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003731953198698931, 'max_iter': 2945}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  28%|██▊       | 140/500 [25:42<24:45,  4.13s/it]

[I 2026-05-18 17:31:53,192] Trial 147 finished with value: 0.9495812338576419 and parameters: {'solver': 'saga', 'C': 0.0010978256048746323, 'l1_ratio': 0.26549265250922, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00037616758139500083, 'max_iter': 4819}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  28%|██▊       | 141/500 [25:59<48:14,  8.06s/it]

[I 2026-05-18 17:32:10,436] Trial 151 finished with value: 0.9495725684635422 and parameters: {'solver': 'saga', 'C': 0.0018704283374877352, 'l1_ratio': 0.26746969409015464, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0012979963839735843, 'max_iter': 4804}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  28%|██▊       | 142/500 [25:59<34:14,  5.74s/it]

[I 2026-05-18 17:32:10,750] Trial 148 finished with value: 0.9495763992687511 and parameters: {'solver': 'saga', 'C': 0.0010527032795598786, 'l1_ratio': 0.18165247726673528, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00041436391451604764, 'max_iter': 4807}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  29%|██▊       | 143/500 [26:01<26:22,  4.43s/it]

[I 2026-05-18 17:32:12,140] Trial 149 finished with value: 0.9495748371021767 and parameters: {'solver': 'saga', 'C': 0.001684709604313596, 'l1_ratio': 0.26226570806490984, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003774835161386261, 'max_iter': 4802}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  29%|██▉       | 144/500 [26:20<52:09,  8.79s/it]

[I 2026-05-18 17:32:31,096] Trial 153 finished with value: 0.9495748502961003 and parameters: {'solver': 'saga', 'C': 0.0016147709416903032, 'l1_ratio': 0.2515714067326975, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00036245205872126193, 'max_iter': 4724}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  29%|██▉       | 145/500 [26:21<37:57,  6.42s/it]

[I 2026-05-18 17:32:31,973] Trial 152 finished with value: 0.9495752898417462 and parameters: {'solver': 'saga', 'C': 0.0016046076132765843, 'l1_ratio': 0.2547625523975369, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00040059444559476177, 'max_iter': 4758}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  29%|██▉       | 146/500 [26:23<30:58,  5.25s/it]

[I 2026-05-18 17:32:34,504] Trial 21 finished with value: 0.9495220202278775 and parameters: {'solver': 'saga', 'C': 0.1612774043359393, 'l1_ratio': 0.40056836348422886, 'class_weight': None, 'fit_intercept': False, 'tol': 1.4425321300269135e-06, 'max_iter': 3740}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  29%|██▉       | 147/500 [26:30<33:00,  5.61s/it]

[I 2026-05-18 17:32:40,955] Trial 154 finished with value: 0.9495697249633015 and parameters: {'solver': 'saga', 'C': 0.0027123877172423416, 'l1_ratio': 0.2529500897947127, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00023587586139935728, 'max_iter': 4510}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  30%|██▉       | 148/500 [26:40<41:08,  7.01s/it]

[I 2026-05-18 17:32:51,236] Trial 140 finished with value: 0.9495250046404926 and parameters: {'solver': 'saga', 'C': 0.06711261312390615, 'l1_ratio': 0.2963391211569028, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00038495276377341125, 'max_iter': 4656}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  30%|██▉       | 149/500 [26:42<32:49,  5.61s/it]

[I 2026-05-18 17:32:53,581] Trial 125 finished with value: 0.9495291275271365 and parameters: {'solver': 'saga', 'C': 0.06371113079226186, 'l1_ratio': 0.23211658487087133, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004341989960848323, 'max_iter': 4731}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  30%|███       | 150/500 [26:44<25:26,  4.36s/it]

[I 2026-05-18 17:32:55,009] Trial 155 finished with value: 0.949579743568874 and parameters: {'solver': 'saga', 'C': 0.0006801424114462962, 'l1_ratio': 0.2722232496539103, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002344207959290371, 'max_iter': 4533}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  30%|███       | 151/500 [26:46<21:05,  3.63s/it]

[I 2026-05-18 17:32:56,927] Trial 157 finished with value: 0.9495797118561973 and parameters: {'solver': 'saga', 'C': 0.0007084731322661924, 'l1_ratio': 0.3005285590858254, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00023823377816173573, 'max_iter': 4520}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  30%|███       | 152/500 [26:49<20:29,  3.53s/it]

[I 2026-05-18 17:33:00,243] Trial 156 finished with value: 0.9495701702251512 and parameters: {'solver': 'saga', 'C': 0.0026494056044204916, 'l1_ratio': 0.28839116967177253, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024376603123537106, 'max_iter': 4472}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  31%|███       | 153/500 [26:54<23:32,  4.07s/it]

[I 2026-05-18 17:33:05,565] Trial 158 finished with value: 0.9495795395861955 and parameters: {'solver': 'saga', 'C': 0.0006949338058718411, 'l1_ratio': 0.29560090024766456, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00023650385966656265, 'max_iter': 4868}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  31%|███       | 154/500 [26:55<18:25,  3.19s/it]

[I 2026-05-18 17:33:06,720] Trial 159 pruned.

Best trial: 142. Best value: 0.949582:  31%|███       | 155/500 [27:03<26:31,  4.61s/it]

[I 2026-05-18 17:33:14,643] Trial 160 finished with value: 0.9495705734813583 and parameters: {'solver': 'saga', 'C': 0.0004021369742239338, 'l1_ratio': 0.27760391747449065, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008451252572612037, 'max_iter': 4505}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  31%|███       | 156/500 [27:06<23:54,  4.17s/it]

[I 2026-05-18 17:33:17,784] Trial 161 finished with value: 0.9495696539134851 and parameters: {'solver': 'saga', 'C': 0.0003899048475988445, 'l1_ratio': 0.2789064558225201, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008774917326928845, 'max_iter': 4510}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  31%|███▏      | 157/500 [27:09<21:05,  3.69s/it]

[I 2026-05-18 17:33:20,351] Trial 164 finished with value: 0.9495646613722671 and parameters: {'solver': 'saga', 'C': 0.00039172785314273324, 'l1_ratio': 0.3407015483170623, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00981734824655276, 'max_iter': 4555}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  32%|███▏      | 158/500 [27:11<17:34,  3.08s/it]

[I 2026-05-18 17:33:22,017] Trial 162 finished with value: 0.9495808772607781 and parameters: {'solver': 'saga', 'C': 0.0011622628681904434, 'l1_ratio': 0.27955006344677935, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002572919477549473, 'max_iter': 4559}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  32%|███▏      | 159/500 [27:16<21:27,  3.78s/it]

[I 2026-05-18 17:33:27,408] Trial 165 finished with value: 0.9495628017895928 and parameters: {'solver': 'saga', 'C': 0.0003925841028091968, 'l1_ratio': 0.3449172624495806, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009255015230921705, 'max_iter': 3391}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  32%|███▏      | 160/500 [27:18<17:38,  3.11s/it]

[I 2026-05-18 17:33:28,978] Trial 163 finished with value: 0.9495693572012784 and parameters: {'solver': 'saga', 'C': 0.00038252307458596545, 'l1_ratio': 0.27429910505557065, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011855887163450817, 'max_iter': 4556}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  32%|███▏      | 161/500 [27:29<30:59,  5.48s/it]

[I 2026-05-18 17:33:39,983] Trial 166 finished with value: 0.9495817421990467 and parameters: {'solver': 'saga', 'C': 0.0011653982267137103, 'l1_ratio': 0.3138777090897059, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013313097498457, 'max_iter': 4577}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  32%|███▏      | 162/500 [27:31<25:48,  4.58s/it]

[I 2026-05-18 17:33:42,472] Trial 167 finished with value: 0.9495815157515812 and parameters: {'solver': 'saga', 'C': 0.0011837373429609427, 'l1_ratio': 0.31124345345930465, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003025650364540195, 'max_iter': 4553}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 142. Best value: 0.949582:  33%|███▎      | 163/500 [27:34<23:35,  4.20s/it]

[I 2026-05-18 17:33:45,776] Trial 169 finished with value: 0.949581786553263 and parameters: {'solver': 'saga', 'C': 0.001011619683722291, 'l1_ratio': 0.31989739041900783, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002956436871032372, 'max_iter': 3504}. Best is trial 142 with value: 0.9495819635507845.

Best trial: 168. Best value: 0.949582:  33%|███▎      | 164/500 [27:35<17:45,  3.17s/it]

[I 2026-05-18 17:33:46,541] Trial 168 finished with value: 0.9495820845736207 and parameters: {'solver': 'saga', 'C': 0.0009845295413053827, 'l1_ratio': 0.31017816316668917, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012553430965138497, 'max_iter': 3483}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  33%|███▎      | 165/500 [27:42<23:55,  4.28s/it]

[I 2026-05-18 17:33:53,435] Trial 170 finished with value: 0.9495818173807793 and parameters: {'solver': 'saga', 'C': 0.0011165043764660109, 'l1_ratio': 0.31111631216372754, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012009084610361183, 'max_iter': 4877}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  33%|███▎      | 166/500 [27:54<36:30,  6.56s/it]

[I 2026-05-18 17:34:05,293] Trial 172 finished with value: 0.9495810607490494 and parameters: {'solver': 'saga', 'C': 0.0012048089654114558, 'l1_ratio': 0.3035994426671625, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018023044952013216, 'max_iter': 4714}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  33%|███▎      | 167/500 [27:56<29:18,  5.28s/it]

[I 2026-05-18 17:34:07,596] Trial 173 finished with value: 0.949579998441005 and parameters: {'solver': 'saga', 'C': 0.001360383709474021, 'l1_ratio': 0.3081323928669158, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003042643116810678, 'max_iter': 4998}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  34%|███▎      | 168/500 [27:58<23:28,  4.24s/it]

[I 2026-05-18 17:34:09,415] Trial 174 finished with value: 0.9495805570835506 and parameters: {'solver': 'saga', 'C': 0.0012879075640946213, 'l1_ratio': 0.3058373241770486, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003073296769836823, 'max_iter': 4687}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  34%|███▍      | 169/500 [27:59<18:23,  3.33s/it]

[I 2026-05-18 17:34:10,621] Trial 175 finished with value: 0.949581636122633 and parameters: {'solver': 'saga', 'C': 0.0012142738458597734, 'l1_ratio': 0.3200087843368928, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000174060782826048, 'max_iter': 3488}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  34%|███▍      | 170/500 [28:07<26:20,  4.79s/it]

[I 2026-05-18 17:34:18,809] Trial 176 finished with value: 0.949581628476974 and parameters: {'solver': 'saga', 'C': 0.0012057117775977114, 'l1_ratio': 0.31942354276548784, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001352075669653659, 'max_iter': 3509}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  34%|███▍      | 171/500 [28:19<37:04,  6.76s/it]

[I 2026-05-18 17:34:30,156] Trial 177 finished with value: 0.9495820099898342 and parameters: {'solver': 'saga', 'C': 0.001094995913500389, 'l1_ratio': 0.30843267393115953, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015910431928346813, 'max_iter': 3572}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  34%|███▍      | 172/500 [28:22<31:32,  5.77s/it]

[I 2026-05-18 17:34:33,635] Trial 179 finished with value: 0.9495428771771971 and parameters: {'solver': 'saga', 'C': 0.001200926949904984, 'l1_ratio': 0.3447577543766518, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0001859027864410949, 'max_iter': 3472}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  35%|███▍      | 173/500 [28:36<44:31,  8.17s/it]

[I 2026-05-18 17:34:47,402] Trial 180 finished with value: 0.9495370180342843 and parameters: {'solver': 'saga', 'C': 0.004322937024554456, 'l1_ratio': 0.3440914482990096, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00014261253551438763, 'max_iter': 3396}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  35%|███▍      | 174/500 [28:40<38:15,  7.04s/it]

[I 2026-05-18 17:34:51,812] Trial 182 finished with value: 0.9495814398285176 and parameters: {'solver': 'saga', 'C': 0.0011612556602977747, 'l1_ratio': 0.344187403325001, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016297174929173712, 'max_iter': 3585}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  35%|███▌      | 175/500 [28:47<37:38,  6.95s/it]

[I 2026-05-18 17:34:58,534] Trial 181 finished with value: 0.9495354898743293 and parameters: {'solver': 'saga', 'C': 0.0049093772581591645, 'l1_ratio': 0.32757456325861445, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00014632089409758026, 'max_iter': 3516}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  35%|███▌      | 176/500 [29:01<49:09,  9.10s/it]

[I 2026-05-18 17:35:12,677] Trial 184 finished with value: 0.9495709675442215 and parameters: {'solver': 'saga', 'C': 0.0023145635900486275, 'l1_ratio': 0.32529685570770994, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001706118758215316, 'max_iter': 3634}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  35%|███▌      | 177/500 [29:07<43:15,  8.03s/it]

[I 2026-05-18 17:35:18,214] Trial 183 finished with value: 0.9495600865885937 and parameters: {'solver': 'saga', 'C': 0.0045701004038986885, 'l1_ratio': 0.3232950285513274, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013587783556500324, 'max_iter': 3598}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  36%|███▌      | 178/500 [29:15<43:18,  8.07s/it]

[I 2026-05-18 17:35:26,354] Trial 186 finished with value: 0.9495709356515594 and parameters: {'solver': 'saga', 'C': 0.0023654985049794248, 'l1_ratio': 0.316247107930836, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010647602870150736, 'max_iter': 3655}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  36%|███▌      | 179/500 [29:19<37:22,  6.99s/it]

[I 2026-05-18 17:35:30,824] Trial 150 finished with value: 0.9495286679850945 and parameters: {'solver': 'saga', 'C': 0.0724228305957819, 'l1_ratio': 0.2590369456591824, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002286841390061747, 'max_iter': 4795}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  36%|███▌      | 180/500 [29:27<38:53,  7.29s/it]

[I 2026-05-18 17:35:38,832] Trial 187 finished with value: 0.9495750653112423 and parameters: {'solver': 'saga', 'C': 0.0019326712439632398, 'l1_ratio': 0.3854938874614895, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011138123165001706, 'max_iter': 3713}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  36%|███▌      | 181/500 [29:33<35:33,  6.69s/it]

[I 2026-05-18 17:35:44,111] Trial 188 finished with value: 0.9495760594090216 and parameters: {'solver': 'saga', 'C': 0.0018530030919828929, 'l1_ratio': 0.3788397805881394, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010570266838354884, 'max_iter': 3637}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  36%|███▋      | 182/500 [29:39<35:27,  6.69s/it]

[I 2026-05-18 17:35:50,807] Trial 189 finished with value: 0.9495766744832064 and parameters: {'solver': 'saga', 'C': 0.0017725378228973115, 'l1_ratio': 0.36939239361160675, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001940042534391938, 'max_iter': 3557}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  37%|███▋      | 183/500 [29:40<25:06,  4.75s/it]

[I 2026-05-18 17:35:51,034] Trial 191 pruned.

Best trial: 168. Best value: 0.949582:  37%|███▋      | 184/500 [29:45<25:29,  4.84s/it]

[I 2026-05-18 17:35:56,079] Trial 190 finished with value: 0.9495774398699638 and parameters: {'solver': 'saga', 'C': 0.001717003297810231, 'l1_ratio': 0.3764695850413554, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017988766334247643, 'max_iter': 3196}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  37%|███▋      | 185/500 [29:57<37:13,  7.09s/it]

[I 2026-05-18 17:36:08,419] Trial 192 finished with value: 0.9495812031346708 and parameters: {'solver': 'saga', 'C': 0.001197190561404446, 'l1_ratio': 0.35591590199794937, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019453086507153561, 'max_iter': 3351}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  37%|███▋      | 186/500 [30:04<36:16,  6.93s/it]

[I 2026-05-18 17:36:14,981] Trial 193 finished with value: 0.9495819092797337 and parameters: {'solver': 'saga', 'C': 0.0011312001062372058, 'l1_ratio': 0.3101040008627551, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016648736121162386, 'max_iter': 3244}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  37%|███▋      | 187/500 [30:20<51:09,  9.81s/it]

[I 2026-05-18 17:36:31,500] Trial 196 finished with value: 0.9495818917361006 and parameters: {'solver': 'saga', 'C': 0.001099903771412374, 'l1_ratio': 0.3145895795740188, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013153748142539853, 'max_iter': 3341}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  38%|███▊      | 188/500 [30:26<44:28,  8.55s/it]

[I 2026-05-18 17:36:37,131] Trial 197 finished with value: 0.9495817679195515 and parameters: {'solver': 'saga', 'C': 0.0011256046722823672, 'l1_ratio': 0.3070692340208005, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001314676893520474, 'max_iter': 3366}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  38%|███▊      | 189/500 [30:37<48:35,  9.37s/it]

[I 2026-05-18 17:36:48,417] Trial 194 finished with value: 0.9495158758054689 and parameters: {'solver': 'saga', 'C': 0.0010472766219911435, 'l1_ratio': 0.9456444777366106, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016251621045885453, 'max_iter': 3325}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  38%|███▊      | 190/500 [30:44<44:34,  8.63s/it]

[I 2026-05-18 17:36:55,306] Trial 198 finished with value: 0.949581915633444 and parameters: {'solver': 'saga', 'C': 0.0011244864342698899, 'l1_ratio': 0.3140812307506277, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014375812923121347, 'max_iter': 3359}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  38%|███▊      | 191/500 [30:49<39:11,  7.61s/it]

[I 2026-05-18 17:37:00,543] Trial 199 finished with value: 0.949581123988216 and parameters: {'solver': 'saga', 'C': 0.0010866602130704661, 'l1_ratio': 0.3575752208244136, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012792656464348325, 'max_iter': 3343}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  38%|███▊      | 192/500 [31:01<44:55,  8.75s/it]

[I 2026-05-18 17:37:11,957] Trial 200 finished with value: 0.9495816571972148 and parameters: {'solver': 'saga', 'C': 0.001079638754245414, 'l1_ratio': 0.33520107133027227, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001310621977107125, 'max_iter': 3424}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  39%|███▊      | 193/500 [31:13<49:57,  9.76s/it]

[I 2026-05-18 17:37:24,077] Trial 202 finished with value: 0.9495811810005996 and parameters: {'solver': 'saga', 'C': 0.0012126780686011944, 'l1_ratio': 0.3550198189946379, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001339310193317098, 'max_iter': 3074}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  39%|███▉      | 194/500 [31:15<38:55,  7.63s/it]

[I 2026-05-18 17:37:26,737] Trial 201 finished with value: 0.949568691231603 and parameters: {'solver': 'saga', 'C': 0.0027850067451269324, 'l1_ratio': 0.35561039509618514, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012995828359555647, 'max_iter': 3458}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  39%|███▉      | 195/500 [31:23<39:32,  7.78s/it]

[I 2026-05-18 17:37:34,858] Trial 203 finished with value: 0.949579961824804 and parameters: {'solver': 'saga', 'C': 0.0014331072604909856, 'l1_ratio': 0.3334959363742802, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001432713567798571, 'max_iter': 3457}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  39%|███▉      | 196/500 [31:38<49:58,  9.86s/it]

[I 2026-05-18 17:37:49,588] Trial 205 finished with value: 0.9495801446819417 and parameters: {'solver': 'saga', 'C': 0.0013843337465795, 'l1_ratio': 0.3256306273974209, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015168433638937091, 'max_iter': 3184}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  39%|███▉      | 197/500 [31:41<39:48,  7.88s/it]

[I 2026-05-18 17:37:52,850] Trial 171 finished with value: 0.9495233959796492 and parameters: {'solver': 'saga', 'C': 41.87234373965265, 'l1_ratio': 0.31173753683348315, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003045534317117526, 'max_iter': 4987}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  40%|███▉      | 198/500 [31:49<39:33,  7.86s/it]

[I 2026-05-18 17:38:00,651] Trial 206 finished with value: 0.9495769546416586 and parameters: {'solver': 'saga', 'C': 0.0005661098625350546, 'l1_ratio': 0.31311524739325153, 'class_weight': None, 'fit_intercept': True, 'tol': 8.73365559596567e-05, 'max_iter': 3206}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  40%|███▉      | 199/500 [32:05<51:46, 10.32s/it]

[I 2026-05-18 17:38:16,718] Trial 207 finished with value: 0.9495819326070855 and parameters: {'solver': 'saga', 'C': 0.0010329231894599371, 'l1_ratio': 0.3146961953809235, 'class_weight': None, 'fit_intercept': True, 'tol': 6.488763238249585e-05, 'max_iter': 3270}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  40%|████      | 200/500 [32:07<38:20,  7.67s/it]

[I 2026-05-18 17:38:18,198] Trial 208 finished with value: 0.9495816933657455 and parameters: {'solver': 'saga', 'C': 0.0009765462459372989, 'l1_ratio': 0.31771620591858063, 'class_weight': None, 'fit_intercept': True, 'tol': 8.623533043140082e-05, 'max_iter': 3247}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  40%|████      | 201/500 [32:17<41:23,  8.31s/it]

[I 2026-05-18 17:38:27,991] Trial 209 finished with value: 0.9495816702759953 and parameters: {'solver': 'saga', 'C': 0.0009880862430111052, 'l1_ratio': 0.3344605019206063, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011493481710221875, 'max_iter': 3367}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  40%|████      | 202/500 [32:26<42:53,  8.64s/it]

[I 2026-05-18 17:38:37,395] Trial 71 finished with value: 0.9495256216500932 and parameters: {'solver': 'saga', 'C': 0.3188756579460356, 'l1_ratio': 0.7203005328471278, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6848018568291194e-06, 'max_iter': 4055}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  41%|████      | 203/500 [32:31<36:57,  7.47s/it]

[I 2026-05-18 17:38:42,133] Trial 210 finished with value: 0.9495757420313764 and parameters: {'solver': 'saga', 'C': 0.0017961796340961265, 'l1_ratio': 0.32386685655433134, 'class_weight': None, 'fit_intercept': True, 'tol': 7.294717732860906e-05, 'max_iter': 3380}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  41%|████      | 204/500 [32:37<34:54,  7.08s/it]

[I 2026-05-18 17:38:48,300] Trial 211 finished with value: 0.9495718611160348 and parameters: {'solver': 'saga', 'C': 0.0021997659833595056, 'l1_ratio': 0.3363067682726689, 'class_weight': None, 'fit_intercept': True, 'tol': 6.455783247489612e-05, 'max_iter': 3249}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  41%|████      | 205/500 [32:47<39:18,  8.00s/it]

[I 2026-05-18 17:38:58,431] Trial 212 finished with value: 0.949580871465896 and parameters: {'solver': 'saga', 'C': 0.0008978885740561956, 'l1_ratio': 0.33009981252515863, 'class_weight': None, 'fit_intercept': True, 'tol': 7.694385920242953e-05, 'max_iter': 3260}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  41%|████      | 206/500 [32:52<34:03,  6.95s/it]

[I 2026-05-18 17:39:02,954] Trial 213 finished with value: 0.9495818773512512 and parameters: {'solver': 'saga', 'C': 0.0009740599987418075, 'l1_ratio': 0.3228581776299334, 'class_weight': None, 'fit_intercept': True, 'tol': 6.954640261130302e-05, 'max_iter': 3019}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  41%|████▏     | 207/500 [32:58<33:23,  6.84s/it]

[I 2026-05-18 17:39:09,530] Trial 214 finished with value: 0.949580053754645 and parameters: {'solver': 'saga', 'C': 0.0008589941824717882, 'l1_ratio': 0.33461577883700677, 'class_weight': None, 'fit_intercept': True, 'tol': 6.583006195228243e-05, 'max_iter': 3076}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  42%|████▏     | 208/500 [33:01<27:59,  5.75s/it]

[I 2026-05-18 17:39:12,752] Trial 215 finished with value: 0.9495816153101693 and parameters: {'solver': 'saga', 'C': 0.0009151129471170108, 'l1_ratio': 0.308216903370698, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010757316208438271, 'max_iter': 3263}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  42%|████▏     | 209/500 [33:16<40:26,  8.34s/it]

[I 2026-05-18 17:39:27,117] Trial 216 finished with value: 0.9495818361943785 and parameters: {'solver': 'saga', 'C': 0.0009536330618757404, 'l1_ratio': 0.3088865447398633, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010799264132545207, 'max_iter': 3079}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  42%|████▏     | 210/500 [33:19<32:16,  6.68s/it]

[I 2026-05-18 17:39:29,928] Trial 217 finished with value: 0.9495768646727051 and parameters: {'solver': 'saga', 'C': 0.0005832389962813211, 'l1_ratio': 0.31061652160664655, 'class_weight': None, 'fit_intercept': True, 'tol': 9.342424541620483e-05, 'max_iter': 3049}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  42%|████▏     | 211/500 [33:25<31:46,  6.60s/it]

[I 2026-05-18 17:39:36,331] Trial 218 finished with value: 0.9495769139679104 and parameters: {'solver': 'saga', 'C': 0.0005771164776237105, 'l1_ratio': 0.3163737651174039, 'class_weight': None, 'fit_intercept': True, 'tol': 9.539184496268051e-05, 'max_iter': 3424}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  42%|████▏     | 212/500 [33:27<25:44,  5.36s/it]

[I 2026-05-18 17:39:38,812] Trial 219 finished with value: 0.9495762483405908 and parameters: {'solver': 'saga', 'C': 0.0005371705308906069, 'l1_ratio': 0.3076972285636943, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010151611217965175, 'max_iter': 2973}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  43%|████▎     | 213/500 [33:41<37:38,  7.87s/it]

[I 2026-05-18 17:39:52,528] Trial 220 finished with value: 0.9495753618038496 and parameters: {'solver': 'saga', 'C': 0.0005138281282583407, 'l1_ratio': 0.31539201669476463, 'class_weight': None, 'fit_intercept': True, 'tol': 9.376848787607354e-05, 'max_iter': 3137}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  43%|████▎     | 214/500 [33:44<29:40,  6.23s/it]

[I 2026-05-18 17:39:54,921] Trial 221 finished with value: 0.9495768620691145 and parameters: {'solver': 'saga', 'C': 0.000580512902627307, 'l1_ratio': 0.30856114116298705, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010968142887762158, 'max_iter': 3141}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  43%|████▎     | 215/500 [33:51<30:38,  6.45s/it]

[I 2026-05-18 17:40:01,898] Trial 222 finished with value: 0.9495776381737109 and parameters: {'solver': 'saga', 'C': 0.0015753482359488777, 'l1_ratio': 0.3005690871543482, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011089875602966333, 'max_iter': 2993}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  43%|████▎     | 216/500 [33:53<25:18,  5.35s/it]

[I 2026-05-18 17:40:04,671] Trial 223 finished with value: 0.9495772438680461 and parameters: {'solver': 'saga', 'C': 0.0015417909126793047, 'l1_ratio': 0.29013818147174514, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011962769968006119, 'max_iter': 3292}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  43%|████▎     | 217/500 [34:08<38:52,  8.24s/it]

[I 2026-05-18 17:40:19,646] Trial 224 finished with value: 0.9495817491745692 and parameters: {'solver': 'saga', 'C': 0.0009079450296733661, 'l1_ratio': 0.2883035390996114, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001105580923308495, 'max_iter': 3287}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  44%|████▎     | 218/500 [34:09<28:13,  6.00s/it]

[I 2026-05-18 17:40:20,451] Trial 225 finished with value: 0.9495767229891893 and parameters: {'solver': 'saga', 'C': 0.0015641024987685394, 'l1_ratio': 0.286195557284468, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011980965686807101, 'max_iter': 3295}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  44%|████▍     | 219/500 [34:16<28:52,  6.16s/it]

[I 2026-05-18 17:40:26,990] Trial 226 finished with value: 0.9495815946468363 and parameters: {'solver': 'saga', 'C': 0.0008841994827942674, 'l1_ratio': 0.2815266616713781, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011907888120236951, 'max_iter': 3317}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  44%|████▍     | 220/500 [34:19<24:30,  5.25s/it]

[I 2026-05-18 17:40:30,087] Trial 227 finished with value: 0.9495817019893573 and parameters: {'solver': 'saga', 'C': 0.0009130885166831528, 'l1_ratio': 0.2815823438815797, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013305226711092841, 'max_iter': 3317}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  44%|████▍     | 221/500 [34:22<21:48,  4.69s/it]

[I 2026-05-18 17:40:33,493] Trial 228 pruned.

Best trial: 168. Best value: 0.949582:  44%|████▍     | 222/500 [34:23<16:51,  3.64s/it]

[I 2026-05-18 17:40:34,681] Trial 229 pruned.

Best trial: 168. Best value: 0.949582:  45%|████▍     | 223/500 [34:29<20:04,  4.35s/it]

[I 2026-05-18 17:40:40,684] Trial 230 pruned.

Best trial: 168. Best value: 0.949582:  45%|████▍     | 224/500 [34:43<32:47,  7.13s/it]

[I 2026-05-18 17:40:54,293] Trial 185 finished with value: 0.9495233803521728 and parameters: {'solver': 'saga', 'C': 22.839038926622173, 'l1_ratio': 0.32054069396243773, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013695094507293275, 'max_iter': 3643}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  45%|████▌     | 225/500 [34:46<27:40,  6.04s/it]

[I 2026-05-18 17:40:57,797] Trial 232 finished with value: 0.9495805102043752 and parameters: {'solver': 'saga', 'C': 0.0007738450727649188, 'l1_ratio': 0.2738478386483907, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013766958719406351, 'max_iter': 3500}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  45%|████▌     | 226/500 [34:48<22:08,  4.85s/it]

[I 2026-05-18 17:40:59,870] Trial 233 finished with value: 0.9495801453523145 and parameters: {'solver': 'saga', 'C': 0.0007139448267495135, 'l1_ratio': 0.2737697939642875, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000135811759479595, 'max_iter': 3406}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  45%|████▌     | 227/500 [34:55<24:17,  5.34s/it]

[I 2026-05-18 17:41:06,349] Trial 234 finished with value: 0.9495801619544698 and parameters: {'solver': 'saga', 'C': 0.0007069891385911884, 'l1_ratio': 0.2837435615882069, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013576497461065953, 'max_iter': 3490}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  46%|████▌     | 228/500 [35:00<24:23,  5.38s/it]

[I 2026-05-18 17:41:11,817] Trial 231 finished with value: 0.9495116482422679 and parameters: {'solver': 'saga', 'C': 0.0007879328227707531, 'l1_ratio': 0.8439235561402387, 'class_weight': None, 'fit_intercept': True, 'tol': 7.674472257028084e-05, 'max_iter': 2833}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  46%|████▌     | 229/500 [35:11<31:43,  7.02s/it]

[I 2026-05-18 17:41:22,685] Trial 235 finished with value: 0.9495793534841619 and parameters: {'solver': 'saga', 'C': 0.000760869352226412, 'l1_ratio': 0.34141566811712176, 'class_weight': None, 'fit_intercept': True, 'tol': 6.27038391179575e-05, 'max_iter': 3501}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  46%|████▌     | 230/500 [35:15<27:21,  6.08s/it]

[I 2026-05-18 17:41:26,553] Trial 236 finished with value: 0.9495794654159246 and parameters: {'solver': 'saga', 'C': 0.0006696282378251922, 'l1_ratio': 0.2915232729764629, 'class_weight': None, 'fit_intercept': True, 'tol': 5.425796075503478e-05, 'max_iter': 3204}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  46%|████▌     | 231/500 [35:17<21:04,  4.70s/it]

[I 2026-05-18 17:41:28,049] Trial 237 finished with value: 0.9495815792792172 and parameters: {'solver': 'saga', 'C': 0.0010895140349912271, 'l1_ratio': 0.3388839493044217, 'class_weight': None, 'fit_intercept': True, 'tol': 5.246814441842432e-05, 'max_iter': 3216}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  46%|████▋     | 232/500 [35:19<18:17,  4.09s/it]

[I 2026-05-18 17:41:30,722] Trial 178 finished with value: 0.9495094602619082 and parameters: {'solver': 'saga', 'C': 37.495907386934604, 'l1_ratio': 0.32010309039600576, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00014668273517411953, 'max_iter': 3545}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  47%|████▋     | 233/500 [35:31<28:43,  6.45s/it]

[I 2026-05-18 17:41:42,686] Trial 239 finished with value: 0.9495733912200729 and parameters: {'solver': 'saga', 'C': 0.0020742018515333047, 'l1_ratio': 0.34025526391746164, 'class_weight': None, 'fit_intercept': True, 'tol': 6.388505320166406e-05, 'max_iter': 3232}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  47%|████▋     | 234/500 [35:32<21:26,  4.84s/it]

[I 2026-05-18 17:41:43,744] Trial 238 finished with value: 0.949569714115091 and parameters: {'solver': 'saga', 'C': 0.0026479040257685557, 'l1_ratio': 0.3394852671393034, 'class_weight': None, 'fit_intercept': True, 'tol': 5.609349547679312e-05, 'max_iter': 3249}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  47%|████▋     | 235/500 [35:43<28:31,  6.46s/it]

[I 2026-05-18 17:41:53,971] Trial 242 finished with value: 0.949581365261059 and parameters: {'solver': 'saga', 'C': 0.0012580753123665688, 'l1_ratio': 0.33480647200454466, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011295325013212534, 'max_iter': 3328}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  47%|████▋     | 236/500 [35:43<20:30,  4.66s/it]

[I 2026-05-18 17:41:54,445] Trial 240 finished with value: 0.9495705330004753 and parameters: {'solver': 'saga', 'C': 0.0025621843941862604, 'l1_ratio': 0.3017111244779638, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001104889328498792, 'max_iter': 3248}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  47%|████▋     | 237/500 [35:45<16:12,  3.70s/it]

[I 2026-05-18 17:41:55,889] Trial 243 finished with value: 0.9495805847398768 and parameters: {'solver': 'saga', 'C': 0.0012758817611471282, 'l1_ratio': 0.296719632606058, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010241233729866865, 'max_iter': 3345}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  48%|████▊     | 238/500 [35:49<17:22,  3.98s/it]

[I 2026-05-18 17:42:00,539] Trial 241 finished with value: 0.9495699797643627 and parameters: {'solver': 'saga', 'C': 0.002584005979143262, 'l1_ratio': 0.3346924726904717, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011364456560879817, 'max_iter': 3356}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  48%|████▊     | 239/500 [35:56<20:27,  4.70s/it]

[I 2026-05-18 17:42:06,936] Trial 244 finished with value: 0.9495817854910623 and parameters: {'solver': 'saga', 'C': 0.001165118498748722, 'l1_ratio': 0.33194392129477335, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010722320391978702, 'max_iter': 3349}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  48%|████▊     | 240/500 [36:01<20:55,  4.83s/it]

[I 2026-05-18 17:42:12,047] Trial 195 finished with value: 0.9495204089942311 and parameters: {'solver': 'saga', 'C': 42.858038198545465, 'l1_ratio': 0.3139973532581944, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001326552283178242, 'max_iter': 3529}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  48%|████▊     | 241/500 [36:01<15:11,  3.52s/it]

[I 2026-05-18 17:42:12,517] Trial 245 finished with value: 0.9495812283190663 and parameters: {'solver': 'saga', 'C': 0.001164918951083659, 'l1_ratio': 0.29879880819369997, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001071987241786915, 'max_iter': 3332}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  48%|████▊     | 242/500 [36:08<19:54,  4.63s/it]

[I 2026-05-18 17:42:19,737] Trial 247 finished with value: 0.949580849739607 and parameters: {'solver': 'saga', 'C': 0.0010835181612453726, 'l1_ratio': 0.367330386367853, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016229326592255897, 'max_iter': 3147}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  49%|████▊     | 243/500 [36:10<15:33,  3.63s/it]

[I 2026-05-18 17:42:21,041] Trial 248 finished with value: 0.9495803859860283 and parameters: {'solver': 'saga', 'C': 0.0010540474773701176, 'l1_ratio': 0.3667824367306838, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015664827379680663, 'max_iter': 3104}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  49%|████▉     | 244/500 [36:10<11:24,  2.67s/it]

[I 2026-05-18 17:42:21,481] Trial 246 finished with value: 0.9495819329009413 and parameters: {'solver': 'saga', 'C': 0.001052946258782578, 'l1_ratio': 0.29516868996266266, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010354029081822921, 'max_iter': 3365}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  49%|████▉     | 245/500 [36:16<15:10,  3.57s/it]

[I 2026-05-18 17:42:27,145] Trial 249 finished with value: 0.9495805091430908 and parameters: {'solver': 'saga', 'C': 0.001038313026658724, 'l1_ratio': 0.3681871525555838, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016542802532334055, 'max_iter': 3122}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  49%|████▉     | 246/500 [36:22<18:41,  4.41s/it]

[I 2026-05-18 17:42:33,527] Trial 250 finished with value: 0.9495801201317506 and parameters: {'solver': 'saga', 'C': 0.0014095405207863844, 'l1_ratio': 0.3584050425070348, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001692564555926804, 'max_iter': 3429}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  49%|████▉     | 247/500 [36:27<18:47,  4.46s/it]

[I 2026-05-18 17:42:38,077] Trial 251 finished with value: 0.9495750377067184 and parameters: {'solver': 'saga', 'C': 0.001579296461811745, 'l1_ratio': 0.24689776720037482, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001705116423840317, 'max_iter': 3423}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  50%|████▉     | 248/500 [36:28<14:24,  3.43s/it]

[I 2026-05-18 17:42:39,111] Trial 252 finished with value: 0.9495807648909326 and parameters: {'solver': 'saga', 'C': 0.0009740602661015693, 'l1_ratio': 0.3541328800974571, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016226568415189926, 'max_iter': 3092}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  50%|████▉     | 249/500 [36:35<18:51,  4.51s/it]

[I 2026-05-18 17:42:46,138] Trial 253 finished with value: 0.9495759088210338 and parameters: {'solver': 'saga', 'C': 0.0015286742980965692, 'l1_ratio': 0.25134322208646087, 'class_weight': None, 'fit_intercept': True, 'tol': 8.951192885686847e-05, 'max_iter': 3442}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  50%|█████     | 250/500 [36:37<15:31,  3.72s/it]

[I 2026-05-18 17:42:48,036] Trial 254 finished with value: 0.9495788190268332 and parameters: {'solver': 'saga', 'C': 0.001518613540544321, 'l1_ratio': 0.3216954324221126, 'class_weight': None, 'fit_intercept': True, 'tol': 8.779323386326337e-05, 'max_iter': 3426}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  50%|█████     | 251/500 [36:39<13:43,  3.31s/it]

[I 2026-05-18 17:42:50,361] Trial 255 finished with value: 0.9495745047789903 and parameters: {'solver': 'saga', 'C': 0.0016462222354645998, 'l1_ratio': 0.2511197915490436, 'class_weight': None, 'fit_intercept': True, 'tol': 9.041458653641937e-05, 'max_iter': 3437}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  50%|█████     | 252/500 [36:43<14:54,  3.61s/it]

[I 2026-05-18 17:42:54,666] Trial 256 finished with value: 0.9495756703091953 and parameters: {'solver': 'saga', 'C': 0.0016986264500265672, 'l1_ratio': 0.2866946098251816, 'class_weight': None, 'fit_intercept': True, 'tol': 9.098952978490684e-05, 'max_iter': 3421}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  51%|█████     | 253/500 [36:48<16:40,  4.05s/it]

[I 2026-05-18 17:42:59,760] Trial 257 finished with value: 0.9495753859562528 and parameters: {'solver': 'saga', 'C': 0.0017012243374705546, 'l1_ratio': 0.2841057937158321, 'class_weight': None, 'fit_intercept': True, 'tol': 9.371821267212466e-05, 'max_iter': 3418}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  51%|█████     | 254/500 [36:53<17:18,  4.22s/it]

[I 2026-05-18 17:43:04,386] Trial 258 finished with value: 0.9495752307644165 and parameters: {'solver': 'saga', 'C': 0.0017308320794234876, 'l1_ratio': 0.28651147296001156, 'class_weight': None, 'fit_intercept': True, 'tol': 9.142341017907561e-05, 'max_iter': 3363}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  51%|█████     | 255/500 [36:56<15:09,  3.71s/it]

[I 2026-05-18 17:43:06,895] Trial 259 finished with value: 0.9495752392206352 and parameters: {'solver': 'saga', 'C': 0.0017455216773132876, 'l1_ratio': 0.29131007256694885, 'class_weight': None, 'fit_intercept': True, 'tol': 9.30465829305076e-05, 'max_iter': 3369}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  51%|█████     | 256/500 [37:02<18:41,  4.60s/it]

[I 2026-05-18 17:43:13,561] Trial 260 finished with value: 0.9495764817596498 and parameters: {'solver': 'saga', 'C': 0.0005354895995374382, 'l1_ratio': 0.28563370543664035, 'class_weight': None, 'fit_intercept': True, 'tol': 9.603922130798503e-05, 'max_iter': 3357}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  51%|█████▏    | 257/500 [37:03<13:48,  3.41s/it]

[I 2026-05-18 17:43:14,197] Trial 261 finished with value: 0.9495753608261834 and parameters: {'solver': 'saga', 'C': 0.0004905765055387316, 'l1_ratio': 0.28479643411774846, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012009828818228996, 'max_iter': 3310}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  52%|█████▏    | 258/500 [37:06<13:12,  3.28s/it]

[I 2026-05-18 17:43:17,166] Trial 262 finished with value: 0.9495782584103806 and parameters: {'solver': 'saga', 'C': 0.0006211909306636239, 'l1_ratio': 0.2846978041841374, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012119970137831346, 'max_iter': 3316}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  52%|█████▏    | 259/500 [37:10<14:22,  3.58s/it]

[I 2026-05-18 17:43:21,451] Trial 263 finished with value: 0.9495769804889755 and parameters: {'solver': 'saga', 'C': 0.0005842917513558446, 'l1_ratio': 0.28335824962411327, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012608492205105825, 'max_iter': 3310}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  52%|█████▏    | 260/500 [37:16<17:27,  4.36s/it]

[I 2026-05-18 17:43:27,651] Trial 264 finished with value: 0.9495778603637047 and parameters: {'solver': 'saga', 'C': 0.000631499478144393, 'l1_ratio': 0.3082087227033866, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012341541245430783, 'max_iter': 3284}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  52%|█████▏    | 261/500 [37:20<17:04,  4.29s/it]

[I 2026-05-18 17:43:31,746] Trial 265 finished with value: 0.94957592739887 and parameters: {'solver': 'saga', 'C': 0.000524083162571684, 'l1_ratio': 0.3065262431649568, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012606093982515132, 'max_iter': 3304}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  52%|█████▏    | 262/500 [37:21<12:32,  3.16s/it]

[I 2026-05-18 17:43:32,291] Trial 266 finished with value: 0.9495794894867897 and parameters: {'solver': 'saga', 'C': 0.0007209125826045957, 'l1_ratio': 0.31679064665931383, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012359183350034065, 'max_iter': 3268}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  53%|█████▎    | 263/500 [37:29<18:01,  4.56s/it]

[I 2026-05-18 17:43:40,122] Trial 204 finished with value: 0.949523986144721 and parameters: {'solver': 'saga', 'C': 31.423842091598157, 'l1_ratio': 0.3275494681981588, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013688496388499733, 'max_iter': 3470}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  53%|█████▎    | 264/500 [37:29<13:12,  3.36s/it]

[I 2026-05-18 17:43:40,665] Trial 267 finished with value: 0.9495800065912526 and parameters: {'solver': 'saga', 'C': 0.0007943465326068135, 'l1_ratio': 0.31168626867800847, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012405236222173284, 'max_iter': 3274}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  53%|█████▎    | 265/500 [37:30<09:44,  2.49s/it]

[I 2026-05-18 17:43:41,114] Trial 268 finished with value: 0.9495806643955789 and parameters: {'solver': 'saga', 'C': 0.0008568480047320507, 'l1_ratio': 0.3111307819873954, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013220262782308624, 'max_iter': 3275}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  53%|█████▎    | 266/500 [37:33<10:10,  2.61s/it]

[I 2026-05-18 17:43:44,013] Trial 270 finished with value: 0.9495804968695152 and parameters: {'solver': 'saga', 'C': 0.0008484742318510561, 'l1_ratio': 0.3177053031647575, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020347041712110765, 'max_iter': 2941}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  53%|█████▎    | 267/500 [37:34<08:17,  2.14s/it]

[I 2026-05-18 17:43:45,050] Trial 269 finished with value: 0.9495816478455076 and parameters: {'solver': 'saga', 'C': 0.0009247870223841731, 'l1_ratio': 0.3110591001410891, 'class_weight': None, 'fit_intercept': True, 'tol': 7.193744164357317e-05, 'max_iter': 3001}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  54%|█████▎    | 268/500 [37:43<16:46,  4.34s/it]

[I 2026-05-18 17:43:54,521] Trial 271 finished with value: 0.9495813195902564 and parameters: {'solver': 'saga', 'C': 0.0009155187178428602, 'l1_ratio': 0.3193630469548918, 'class_weight': None, 'fit_intercept': True, 'tol': 6.826015087048097e-05, 'max_iter': 2903}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  54%|█████▍    | 269/500 [37:45<13:51,  3.60s/it]

[I 2026-05-18 17:43:56,398] Trial 272 finished with value: 0.9495806048643451 and parameters: {'solver': 'saga', 'C': 0.0008695915236089707, 'l1_ratio': 0.32177833031049813, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020179279605230953, 'max_iter': 3020}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  54%|█████▍    | 270/500 [37:46<11:09,  2.91s/it]

[I 2026-05-18 17:43:57,698] Trial 273 finished with value: 0.9495814323207629 and parameters: {'solver': 'saga', 'C': 0.0009272910833287889, 'l1_ratio': 0.32233227177797974, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019171704033061582, 'max_iter': 3540}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  54%|█████▍    | 271/500 [37:55<17:37,  4.62s/it]

[I 2026-05-18 17:44:06,309] Trial 274 finished with value: 0.949581352778911 and parameters: {'solver': 'saga', 'C': 0.0009242449944344023, 'l1_ratio': 0.32536443526770636, 'class_weight': None, 'fit_intercept': True, 'tol': 7.070702924965654e-05, 'max_iter': 2686}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  54%|█████▍    | 272/500 [37:56<14:00,  3.69s/it]

[I 2026-05-18 17:44:07,818] Trial 275 finished with value: 0.9495815087494138 and parameters: {'solver': 'saga', 'C': 0.0009691095400249923, 'l1_ratio': 0.32742853999957433, 'class_weight': None, 'fit_intercept': True, 'tol': 6.92198689303103e-05, 'max_iter': 3000}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  55%|█████▍    | 273/500 [37:58<11:04,  2.93s/it]

[I 2026-05-18 17:44:08,976] Trial 276 finished with value: 0.9495811302815191 and parameters: {'solver': 'saga', 'C': 0.0010156636105795765, 'l1_ratio': 0.2612838226275061, 'class_weight': None, 'fit_intercept': True, 'tol': 7.291250829055537e-05, 'max_iter': 2956}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  55%|█████▍    | 274/500 [38:01<11:26,  3.04s/it]

[I 2026-05-18 17:44:12,269] Trial 277 finished with value: 0.9495810146217082 and parameters: {'solver': 'saga', 'C': 0.0010116459050507618, 'l1_ratio': 0.256533146218345, 'class_weight': None, 'fit_intercept': True, 'tol': 7.615463125911394e-05, 'max_iter': 3033}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  55%|█████▌    | 275/500 [38:12<20:03,  5.35s/it]

[I 2026-05-18 17:44:23,013] Trial 279 finished with value: 0.9495816109542854 and parameters: {'solver': 'saga', 'C': 0.0011570507697896964, 'l1_ratio': 0.3375338253624714, 'class_weight': None, 'fit_intercept': True, 'tol': 6.738861424482459e-05, 'max_iter': 3186}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  55%|█████▌    | 276/500 [38:12<14:42,  3.94s/it]

[I 2026-05-18 17:44:23,662] Trial 281 finished with value: 0.9495796877738133 and parameters: {'solver': 'saga', 'C': 0.0011328247340236144, 'l1_ratio': 0.39565660380281054, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000104179429788962, 'max_iter': 3136}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  55%|█████▌    | 277/500 [38:13<10:48,  2.91s/it]

[I 2026-05-18 17:44:24,154] Trial 280 finished with value: 0.949581445365764 and parameters: {'solver': 'saga', 'C': 0.0011611467873201761, 'l1_ratio': 0.3490677448503276, 'class_weight': None, 'fit_intercept': True, 'tol': 7.518129410648108e-05, 'max_iter': 3572}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  56%|█████▌    | 278/500 [38:21<17:06,  4.63s/it]

[I 2026-05-18 17:44:32,799] Trial 283 finished with value: 0.9495800793798587 and parameters: {'solver': 'saga', 'C': 0.001296005088205506, 'l1_ratio': 0.390884356968338, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015122656812939435, 'max_iter': 3182}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  56%|█████▌    | 280/500 [38:22<08:43,  2.38s/it]

[I 2026-05-18 17:44:33,079] Trial 282 finished with value: 0.9495437861300429 and parameters: {'solver': 'saga', 'C': 0.0012836989589488812, 'l1_ratio': 0.3968356332682804, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 7.293926930020222e-05, 'max_iter': 3025}. Best is trial 168 with value: 0.9495820845736207.
[I 2026-05-18 17:44:33,235] Trial 284 finished with value: 0.9495426599362075 and parameters: {'solver': 'saga', 'C': 0.001361968832931027, 'l1_ratio': 0.3429747372602391, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00015060543290342388, 'max_iter': 3159}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  56%|█████▌    | 281/500 [38:27<11:47,  3.23s/it]

[I 2026-05-18 17:44:38,487] Trial 285 finished with value: 0.9495429319765598 and parameters: {'solver': 'saga', 'C': 0.0012396717573061472, 'l1_ratio': 0.34903066931277815, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00010440937185655734, 'max_iter': 3177}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  56%|█████▋    | 282/500 [38:38<19:40,  5.41s/it]

[I 2026-05-18 17:44:49,003] Trial 286 finished with value: 0.9495324532558371 and parameters: {'solver': 'saga', 'C': 0.0004059362223619213, 'l1_ratio': 0.34667655797613395, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00014927401080956952, 'max_iter': 3141}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  57%|█████▋    | 283/500 [38:38<14:14,  3.94s/it]

[I 2026-05-18 17:44:49,490] Trial 288 finished with value: 0.9495305780384455 and parameters: {'solver': 'saga', 'C': 0.0003959284497144397, 'l1_ratio': 0.30122072214967693, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00015530744717017216, 'max_iter': 2376}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  57%|█████▋    | 284/500 [38:39<11:16,  3.13s/it]

[I 2026-05-18 17:44:50,747] Trial 287 finished with value: 0.9495743739351553 and parameters: {'solver': 'saga', 'C': 0.0019711008375553384, 'l1_ratio': 0.34548609453414864, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001522500891654125, 'max_iter': 3577}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  57%|█████▋    | 285/500 [38:49<17:51,  4.98s/it]

[I 2026-05-18 17:45:00,044] Trial 290 finished with value: 0.9495724057477173 and parameters: {'solver': 'saga', 'C': 0.0021226511043286565, 'l1_ratio': 0.3007052608694006, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015237288326694302, 'max_iter': 3504}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  57%|█████▋    | 286/500 [38:52<15:56,  4.47s/it]

[I 2026-05-18 17:45:03,316] Trial 291 finished with value: 0.9495718985861984 and parameters: {'solver': 'saga', 'C': 0.00043448389080682224, 'l1_ratio': 0.30047868874801476, 'class_weight': None, 'fit_intercept': True, 'tol': 4.537710467673804e-05, 'max_iter': 3510}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  57%|█████▋    | 287/500 [38:53<12:00,  3.38s/it]

[I 2026-05-18 17:45:04,172] Trial 289 finished with value: 0.9495431312769652 and parameters: {'solver': 'saga', 'C': 0.0022372942928646448, 'l1_ratio': 0.3017822762389893, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 3.651989421692974e-05, 'max_iter': 3734}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  58%|█████▊    | 288/500 [38:55<10:36,  3.00s/it]

[I 2026-05-18 17:45:06,276] Trial 292 finished with value: 0.9495713995884045 and parameters: {'solver': 'saga', 'C': 0.0023367669563416587, 'l1_ratio': 0.3002919772670299, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015460650186463321, 'max_iter': 3509}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  58%|█████▊    | 289/500 [39:07<19:50,  5.64s/it]

[I 2026-05-18 17:45:18,066] Trial 294 finished with value: 0.9495740225781006 and parameters: {'solver': 'saga', 'C': 0.001883454089320087, 'l1_ratio': 0.2983633631201607, 'class_weight': None, 'fit_intercept': True, 'tol': 4.9502870022581845e-05, 'max_iter': 3525}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  58%|█████▊    | 290/500 [39:07<14:14,  4.07s/it]

[I 2026-05-18 17:45:18,472] Trial 295 finished with value: 0.9495719862149627 and parameters: {'solver': 'saga', 'C': 0.0021603357164010333, 'l1_ratio': 0.30328438409446024, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010327834975421234, 'max_iter': 3514}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  58%|█████▊    | 291/500 [39:09<12:21,  3.55s/it]

[I 2026-05-18 17:45:20,808] Trial 299 pruned.

Best trial: 168. Best value: 0.949582:  58%|█████▊    | 292/500 [39:17<16:09,  4.66s/it]

[I 2026-05-18 17:45:28,073] Trial 296 finished with value: 0.9495800443415863 and parameters: {'solver': 'saga', 'C': 0.0006866570302394461, 'l1_ratio': 0.27256480774506975, 'class_weight': None, 'fit_intercept': True, 'tol': 4.4232157204767276e-05, 'max_iter': 3717}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  59%|█████▊    | 293/500 [39:21<15:19,  4.44s/it]

[I 2026-05-18 17:45:32,000] Trial 301 pruned.

Best trial: 168. Best value: 0.949582:  59%|█████▉    | 294/500 [39:22<11:42,  3.41s/it]

[I 2026-05-18 17:45:32,995] Trial 300 pruned.

Best trial: 168. Best value: 0.949582:  59%|█████▉    | 295/500 [39:29<15:58,  4.67s/it]

[I 2026-05-18 17:45:40,631] Trial 297 finished with value: 0.9492031334168471 and parameters: {'solver': 'saga', 'C': 0.003486727585535516, 'l1_ratio': 0.2658501582859178, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00010552327747924363, 'max_iter': 3407}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  59%|█████▉    | 296/500 [39:32<13:30,  3.97s/it]

[I 2026-05-18 17:45:42,967] Trial 302 finished with value: 0.9495791501562689 and parameters: {'solver': 'saga', 'C': 0.0006386588825035034, 'l1_ratio': 0.2662906479953493, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018132630230510553, 'max_iter': 3227}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  59%|█████▉    | 297/500 [39:42<19:33,  5.78s/it]

[I 2026-05-18 17:45:52,973] Trial 303 finished with value: 0.9495769354370107 and parameters: {'solver': 'saga', 'C': 0.0006007868512260173, 'l1_ratio': 0.33089920003182766, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018644488801910472, 'max_iter': 3378}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  60%|█████▉    | 298/500 [39:53<25:39,  7.62s/it]

[I 2026-05-18 17:46:04,883] Trial 306 finished with value: 0.9495797155722119 and parameters: {'solver': 'saga', 'C': 0.0014183069028481465, 'l1_ratio': 0.36938516135831123, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020535424184420513, 'max_iter': 3218}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  60%|█████▉    | 299/500 [39:54<18:43,  5.59s/it]

[I 2026-05-18 17:46:05,734] Trial 307 finished with value: 0.9495797051641521 and parameters: {'solver': 'saga', 'C': 0.0014266962277307577, 'l1_ratio': 0.3729396571209509, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00021170557179929335, 'max_iter': 3357}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  60%|██████    | 300/500 [39:58<17:00,  5.10s/it]

[I 2026-05-18 17:46:09,707] Trial 305 finished with value: 0.9495679245187022 and parameters: {'solver': 'saga', 'C': 0.0030440263286232666, 'l1_ratio': 0.331745272864585, 'class_weight': None, 'fit_intercept': True, 'tol': 8.209722556301942e-05, 'max_iter': 3380}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  60%|██████    | 301/500 [39:59<12:19,  3.72s/it]

[I 2026-05-18 17:46:10,176] Trial 304 finished with value: 0.9495540325244377 and parameters: {'solver': 'saga', 'C': 0.0031305122749888475, 'l1_ratio': 0.06461118569802515, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020235242234764591, 'max_iter': 3226}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  60%|██████    | 302/500 [40:05<14:47,  4.48s/it]

[I 2026-05-18 17:46:16,451] Trial 308 finished with value: 0.9495798185580415 and parameters: {'solver': 'saga', 'C': 0.0013962583332575913, 'l1_ratio': 0.37706490651579383, 'class_weight': None, 'fit_intercept': True, 'tol': 8.445748179474357e-05, 'max_iter': 3249}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  61%|██████    | 303/500 [40:20<24:29,  7.46s/it]

[I 2026-05-18 17:46:30,852] Trial 310 finished with value: 0.9495808197363264 and parameters: {'solver': 'saga', 'C': 0.000874142363803786, 'l1_ratio': 0.3155564226274729, 'class_weight': None, 'fit_intercept': True, 'tol': 7.926994327494787e-05, 'max_iter': 3457}. Best is trial 168 with value: 0.9495820845736207.
[I 2026-05-18 17:46:30,910] Trial 309 finished with value: 0.9495805551188164 and parameters: {'solver': 'saga', 'C': 0.0013316274241221427, 'l1_ratio': 0.31952953698892483, 'class_weight': None, 'fit_intercept': True, 'tol': 8.402070069661867e-05, 'max_iter': 2767}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  61%|██████    | 305/500 [40:23<15:20,  4.72s/it]

[I 2026-05-18 17:46:33,910] Trial 311 finished with value: 0.9495819095019797 and parameters: {'solver': 'saga', 'C': 0.0010558289675791045, 'l1_ratio': 0.32061996348524846, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012965100795827415, 'max_iter': 3259}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  61%|██████    | 306/500 [40:26<13:54,  4.30s/it]

[I 2026-05-18 17:46:36,949] Trial 312 finished with value: 0.9495813234957717 and parameters: {'solver': 'saga', 'C': 0.0009210053939390387, 'l1_ratio': 0.320597660137805, 'class_weight': None, 'fit_intercept': True, 'tol': 5.907192953397049e-05, 'max_iter': 3444}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  61%|██████▏   | 307/500 [40:41<23:22,  7.27s/it]

[I 2026-05-18 17:46:52,577] Trial 317 finished with value: 0.9495655302197449 and parameters: {'solver': 'saga', 'C': 0.00044476215197113616, 'l1_ratio': 0.357135968707437, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002630913506351417, 'max_iter': 3074}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  62%|██████▏   | 308/500 [40:45<19:49,  6.19s/it]

[I 2026-05-18 17:46:55,904] Trial 314 finished with value: 0.9495730201844961 and parameters: {'solver': 'saga', 'C': 0.0004799031368042481, 'l1_ratio': 0.32826359646755593, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011580384632438624, 'max_iter': 3052}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  62%|██████▏   | 309/500 [40:45<15:02,  4.72s/it]

[I 2026-05-18 17:46:56,825] Trial 316 finished with value: 0.9495717598259971 and parameters: {'solver': 'saga', 'C': 0.0004655209137018732, 'l1_ratio': 0.33473064222102533, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013567336874815378, 'max_iter': 3081}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  62%|██████▏   | 310/500 [40:46<11:01,  3.48s/it]

[I 2026-05-18 17:46:57,216] Trial 315 finished with value: 0.9495803867019482 and parameters: {'solver': 'saga', 'C': 0.0009456530159189895, 'l1_ratio': 0.3547805407472228, 'class_weight': None, 'fit_intercept': True, 'tol': 6.0510443259197666e-05, 'max_iter': 2884}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  62%|██████▏   | 311/500 [40:57<18:23,  5.84s/it]

[I 2026-05-18 17:47:08,838] Trial 319 pruned.

Best trial: 168. Best value: 0.949582:  62%|██████▏   | 312/500 [41:01<16:32,  5.28s/it]

[I 2026-05-18 17:47:12,762] Trial 321 pruned.

Best trial: 168. Best value: 0.949582:  63%|██████▎   | 313/500 [41:09<18:09,  5.83s/it]

[I 2026-05-18 17:47:19,897] Trial 320 finished with value: 0.9495547842462875 and parameters: {'solver': 'saga', 'C': 0.00027203729125653054, 'l1_ratio': 0.2965539848336364, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013259141636390117, 'max_iter': 3603}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  63%|██████▎   | 314/500 [41:18<21:23,  6.90s/it]

[I 2026-05-18 17:47:29,342] Trial 322 finished with value: 0.9495757700257637 and parameters: {'solver': 'saga', 'C': 0.0016933057314419638, 'l1_ratio': 0.29397340241301784, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005732588127499752, 'max_iter': 3603}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  63%|██████▎   | 315/500 [41:26<22:27,  7.29s/it]

[I 2026-05-18 17:47:37,523] Trial 323 finished with value: 0.9495725578698652 and parameters: {'solver': 'saga', 'C': 0.001893279450520037, 'l1_ratio': 0.23950955181758088, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013151467283487544, 'max_iter': 3804}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  63%|██████▎   | 316/500 [41:31<20:33,  6.70s/it]

[I 2026-05-18 17:47:42,871] Trial 324 finished with value: 0.9495766848856487 and parameters: {'solver': 'saga', 'C': 0.0017459085706331503, 'l1_ratio': 0.3368980398700287, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001714883161654718, 'max_iter': 3346}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  63%|██████▎   | 317/500 [41:49<30:22,  9.96s/it]

[I 2026-05-18 17:48:00,474] Trial 326 finished with value: 0.949581479976748 and parameters: {'solver': 'saga', 'C': 0.0012082356153642277, 'l1_ratio': 0.3421336043661755, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016252056773888662, 'max_iter': 3357}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  64%|██████▎   | 318/500 [42:14<43:38, 14.39s/it]

[I 2026-05-18 17:48:25,235] Trial 328 finished with value: 0.9495798174150257 and parameters: {'solver': 'saga', 'C': 0.0007627992148021084, 'l1_ratio': 0.3126125938684886, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011345350374564185, 'max_iter': 3441}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  64%|██████▍   | 319/500 [42:40<53:37, 17.78s/it]

[I 2026-05-18 17:48:50,938] Trial 329 finished with value: 0.9495809129053157 and parameters: {'solver': 'saga', 'C': 0.001115673033994183, 'l1_ratio': 0.2747476621399303, 'class_weight': None, 'fit_intercept': True, 'tol': 9.762902968347308e-05, 'max_iter': 3162}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  64%|██████▍   | 320/500 [44:00<1:49:22, 36.46s/it]

[I 2026-05-18 17:50:11,079] Trial 14 finished with value: 0.9495239894034612 and parameters: {'solver': 'saga', 'C': 5.142375326468863, 'l1_ratio': 0.6636255807713836, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016517925098969027, 'max_iter': 3116}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  64%|██████▍   | 321/500 [44:25<1:38:52, 33.14s/it]

[I 2026-05-18 17:50:36,471] Trial 331 finished with value: 0.9495791952176778 and parameters: {'solver': 'saga', 'C': 0.0007096216748640321, 'l1_ratio': 0.31499561278839305, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011877300877279382, 'max_iter': 3271}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  64%|██████▍   | 322/500 [44:46<1:27:52, 29.62s/it]

[I 2026-05-18 17:50:57,859] Trial 332 finished with value: 0.9495810274116092 and parameters: {'solver': 'saga', 'C': 0.001263534896657307, 'l1_ratio': 0.35903483674656406, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00022147454804237967, 'max_iter': 3475}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  65%|██████▍   | 323/500 [45:09<1:21:03, 27.48s/it]

[I 2026-05-18 17:51:20,344] Trial 298 finished with value: 0.9495067977663492 and parameters: {'solver': 'saga', 'C': 0.30886700731354194, 'l1_ratio': 0.27115291567186295, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00010427749422462109, 'max_iter': 3365}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  65%|██████▍   | 324/500 [45:10<57:13, 19.51s/it]

[I 2026-05-18 17:51:21,255] Trial 333 finished with value: 0.9495796296942454 and parameters: {'solver': 'saga', 'C': 0.0007807832272448053, 'l1_ratio': 0.32911994156124685, 'class_weight': None, 'fit_intercept': True, 'tol': 8.972353359056874e-05, 'max_iter': 3350}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  65%|██████▌   | 326/500 [45:33<41:55, 14.46s/it]

[I 2026-05-18 17:51:44,384] Trial 335 finished with value: 0.9495820095079269 and parameters: {'solver': 'saga', 'C': 0.001083053854044262, 'l1_ratio': 0.30557773559538637, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014190687860891706, 'max_iter': 3210}. Best is trial 168 with value: 0.9495820845736207.
[I 2026-05-18 17:51:44,516] Trial 334 finished with value: 0.9495795603961309 and parameters: {'solver': 'saga', 'C': 0.0007775190741344608, 'l1_ratio': 0.3317908050030818, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014078022623764935, 'max_iter': 3298}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  65%|██████▌   | 327/500 [45:55<47:45, 16.56s/it]

[I 2026-05-18 17:52:05,997] Trial 336 finished with value: 0.9495796242894132 and parameters: {'solver': 'saga', 'C': 0.0013906457286337259, 'l1_ratio': 0.3119693046791239, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017246819920663546, 'max_iter': 3187}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  66%|██████▌   | 328/500 [46:22<57:06, 19.92s/it]

[I 2026-05-18 17:52:33,756] Trial 338 finished with value: 0.9495715949779928 and parameters: {'solver': 'saga', 'C': 0.0022557058366349946, 'l1_ratio': 0.35231871260529113, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001314535456833893, 'max_iter': 3096}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  66%|██████▌   | 329/500 [46:41<55:53, 19.61s/it]

[I 2026-05-18 17:52:52,651] Trial 325 finished with value: 0.9495232149195443 and parameters: {'solver': 'saga', 'C': 6.306299847892765, 'l1_ratio': 0.3424001032660024, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016880328401300482, 'max_iter': 3339}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  66%|██████▌   | 330/500 [46:43<40:25, 14.27s/it]

[I 2026-05-18 17:52:54,441] Trial 339 finished with value: 0.9495816898500402 and parameters: {'solver': 'saga', 'C': 0.001094786007258809, 'l1_ratio': 0.30316190252029573, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024519044895176455, 'max_iter': 3229}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  66%|██████▌   | 331/500 [47:04<45:31, 16.17s/it]

[I 2026-05-18 17:53:15,035] Trial 340 finished with value: 0.9495817570163065 and parameters: {'solver': 'saga', 'C': 0.0011289146100480383, 'l1_ratio': 0.3016342799152838, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000238678264255478, 'max_iter': 3205}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  66%|██████▋   | 332/500 [47:12<38:29, 13.75s/it]

[I 2026-05-18 17:53:23,140] Trial 341 finished with value: 0.9495414392441752 and parameters: {'solver': 'saga', 'C': 0.001011143188839699, 'l1_ratio': 0.7730445527257681, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002465263740043584, 'max_iter': 3232}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  67%|██████▋   | 333/500 [47:16<30:38, 11.01s/it]

[I 2026-05-18 17:53:27,764] Trial 342 pruned.

Best trial: 168. Best value: 0.949582:  67%|██████▋   | 334/500 [47:27<30:02, 10.86s/it]

[I 2026-05-18 17:53:38,268] Trial 327 finished with value: 0.949524205913819 and parameters: {'solver': 'saga', 'C': 8.166540599766464, 'l1_ratio': 0.3142997363200899, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011615781103941108, 'max_iter': 3456}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  67%|██████▋   | 335/500 [47:30<23:26,  8.53s/it]

[I 2026-05-18 17:53:41,357] Trial 330 finished with value: 0.9495226838040715 and parameters: {'solver': 'saga', 'C': 7.148548207183083, 'l1_ratio': 0.31424913457837206, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00023779874353762798, 'max_iter': 3279}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  67%|██████▋   | 336/500 [47:34<19:24,  7.10s/it]

[I 2026-05-18 17:53:45,122] Trial 343 finished with value: 0.9495779132252314 and parameters: {'solver': 'saga', 'C': 0.0005641703112354534, 'l1_ratio': 0.24807248944237537, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00028328607190536073, 'max_iter': 3187}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  67%|██████▋   | 337/500 [47:39<17:37,  6.49s/it]

[I 2026-05-18 17:53:50,193] Trial 344 finished with value: 0.9495764061104628 and parameters: {'solver': 'saga', 'C': 0.000544058739532818, 'l1_ratio': 0.2827759100855478, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00022304536208838025, 'max_iter': 3201}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  68%|██████▊   | 338/500 [47:50<21:02,  7.80s/it]

[I 2026-05-18 17:54:01,036] Trial 345 finished with value: 0.9495769767441867 and parameters: {'solver': 'saga', 'C': 0.0005939297362158777, 'l1_ratio': 0.28773441138379074, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00026057020516057403, 'max_iter': 3105}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  68%|██████▊   | 339/500 [47:57<20:45,  7.74s/it]

[I 2026-05-18 17:54:08,633] Trial 347 finished with value: 0.9495767527416717 and parameters: {'solver': 'saga', 'C': 0.0016196887825411757, 'l1_ratio': 0.2931712326192189, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00021132701210287434, 'max_iter': 2973}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  68%|██████▊   | 340/500 [48:02<18:02,  6.76s/it]

[I 2026-05-18 17:54:13,126] Trial 278 finished with value: 0.9495260911139785 and parameters: {'solver': 'saga', 'C': 0.23754530428036258, 'l1_ratio': 0.3381677712733408, 'class_weight': None, 'fit_intercept': True, 'tol': 6.504879232146472e-05, 'max_iter': 3016}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  68%|██████▊   | 341/500 [48:02<13:04,  4.94s/it]

[I 2026-05-18 17:54:13,801] Trial 348 finished with value: 0.9495764558515433 and parameters: {'solver': 'saga', 'C': 0.001672745510753196, 'l1_ratio': 0.2942442763721723, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019427217393925395, 'max_iter': 2975}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  68%|██████▊   | 342/500 [48:12<16:47,  6.38s/it]

[I 2026-05-18 17:54:23,539] Trial 349 finished with value: 0.9495776136156149 and parameters: {'solver': 'saga', 'C': 0.001558798324594925, 'l1_ratio': 0.30056449912229277, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020044231375657544, 'max_iter': 3002}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  69%|██████▊   | 343/500 [48:18<16:13,  6.20s/it]

[I 2026-05-18 17:54:29,321] Trial 293 finished with value: 0.949526267123872 and parameters: {'solver': 'saga', 'C': 0.22836357745872563, 'l1_ratio': 0.30432878864618873, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010861205134382521, 'max_iter': 3781}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  69%|██████▉   | 344/500 [48:26<17:13,  6.62s/it]

[I 2026-05-18 17:54:36,944] Trial 350 finished with value: 0.9495818461851663 and parameters: {'solver': 'saga', 'C': 0.0010822793435487851, 'l1_ratio': 0.301782380245337, 'class_weight': None, 'fit_intercept': True, 'tol': 8.433739763985246e-05, 'max_iter': 3036}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  69%|██████▉   | 345/500 [48:30<15:47,  6.12s/it]

[I 2026-05-18 17:54:41,873] Trial 352 finished with value: 0.9495813593373533 and parameters: {'solver': 'saga', 'C': 0.0009960990743687718, 'l1_ratio': 0.2652203381131025, 'class_weight': None, 'fit_intercept': True, 'tol': 2.830001065883092e-05, 'max_iter': 3254}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  69%|██████▉   | 346/500 [48:42<19:46,  7.70s/it]

[I 2026-05-18 17:54:53,282] Trial 353 finished with value: 0.9495814605106337 and parameters: {'solver': 'saga', 'C': 0.0010059762958917334, 'l1_ratio': 0.2678513926622981, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4947113117415169e-05, 'max_iter': 3230}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  69%|██████▉   | 347/500 [49:01<28:05, 11.01s/it]

[I 2026-05-18 17:55:12,016] Trial 356 finished with value: 0.9495712629144887 and parameters: {'solver': 'saga', 'C': 0.002414585179459581, 'l1_ratio': 0.27872114451493646, 'class_weight': None, 'fit_intercept': True, 'tol': 9.047905178379e-05, 'max_iter': 3119}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  70%|██████▉   | 348/500 [49:09<25:31, 10.08s/it]

[I 2026-05-18 17:55:19,908] Trial 357 finished with value: 0.9495728966959179 and parameters: {'solver': 'saga', 'C': 0.0021360142293772202, 'l1_ratio': 0.3621419902795059, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001532787963885572, 'max_iter': 3172}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  70%|██████▉   | 349/500 [49:23<28:25, 11.30s/it]

[I 2026-05-18 17:55:34,055] Trial 358 finished with value: 0.9495789173759194 and parameters: {'solver': 'saga', 'C': 0.0007267938848455718, 'l1_ratio': 0.3318794822331922, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003379521769896694, 'max_iter': 3157}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  70%|███████   | 350/500 [49:33<27:48, 11.12s/it]

[I 2026-05-18 17:55:44,760] Trial 359 finished with value: 0.9495790182277115 and parameters: {'solver': 'saga', 'C': 0.0007290568265847728, 'l1_ratio': 0.3288287497779471, 'class_weight': None, 'fit_intercept': True, 'tol': 8.682849689792845e-05, 'max_iter': 3299}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  70%|███████   | 351/500 [49:57<37:15, 15.01s/it]

[I 2026-05-18 17:56:08,836] Trial 361 finished with value: 0.9495570746417638 and parameters: {'solver': 'saga', 'C': 0.0003024885932936111, 'l1_ratio': 0.29915652335042264, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014190642383178336, 'max_iter': 3303}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  70%|███████   | 352/500 [50:21<43:17, 17.55s/it]

[I 2026-05-18 17:56:32,326] Trial 362 finished with value: 0.94957886283132 and parameters: {'solver': 'saga', 'C': 0.0013396223069046223, 'l1_ratio': 0.2747938004104172, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011592743619355525, 'max_iter': 3081}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  71%|███████   | 353/500 [50:38<42:47, 17.46s/it]

[I 2026-05-18 17:56:49,587] Trial 355 finished with value: 0.9495328541649419 and parameters: {'solver': 'saga', 'C': 0.02619931737115781, 'l1_ratio': 0.2744338238108093, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001503387374489607, 'max_iter': 3124}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  71%|███████   | 354/500 [50:55<42:18, 17.38s/it]

[I 2026-05-18 17:57:06,783] Trial 363 finished with value: 0.9495660928451107 and parameters: {'solver': 'saga', 'C': 0.003187682725920549, 'l1_ratio': 0.37752125698792305, 'class_weight': None, 'fit_intercept': True, 'tol': 9.878818511729263e-05, 'max_iter': 3384}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  71%|███████   | 355/500 [51:14<42:38, 17.64s/it]

[I 2026-05-18 17:57:25,034] Trial 364 finished with value: 0.9495664467626004 and parameters: {'solver': 'saga', 'C': 0.0033779402896792965, 'l1_ratio': 0.30687998327769134, 'class_weight': None, 'fit_intercept': True, 'tol': 9.886380422727571e-05, 'max_iter': 3260}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  71%|███████   | 356/500 [51:37<46:41, 19.45s/it]

[I 2026-05-18 17:57:48,711] Trial 366 finished with value: 0.9495795282381607 and parameters: {'solver': 'saga', 'C': 0.0011136389534306304, 'l1_ratio': 0.24189716873269895, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012983976754081173, 'max_iter': 2904}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  71%|███████▏  | 357/500 [52:00<48:31, 20.36s/it]

[I 2026-05-18 17:58:11,176] Trial 367 finished with value: 0.949580623146829 and parameters: {'solver': 'saga', 'C': 0.001313721896130759, 'l1_ratio': 0.3538339951596618, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001764301582611108, 'max_iter': 3385}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  72%|███████▏  | 358/500 [54:29<2:19:56, 59.13s/it]

[I 2026-05-18 18:00:40,779] Trial 313 finished with value: 0.9495254731284746 and parameters: {'solver': 'saga', 'C': 0.4075680688897611, 'l1_ratio': 0.3198238705463695, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013132764991041047, 'max_iter': 3471}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  72%|███████▏  | 359/500 [54:56<1:55:58, 49.35s/it]

[I 2026-05-18 18:01:07,319] Trial 369 finished with value: 0.949581168322432 and parameters: {'solver': 'saga', 'C': 0.0008592062922864776, 'l1_ratio': 0.2966016012225257, 'class_weight': None, 'fit_intercept': True, 'tol': 8.173112417690858e-05, 'max_iter': 3243}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  72%|███████▏  | 360/500 [55:19<1:36:47, 41.49s/it]

[I 2026-05-18 18:01:30,444] Trial 370 finished with value: 0.949568633647621 and parameters: {'solver': 'saga', 'C': 0.00042668344191605526, 'l1_ratio': 0.3333916457006268, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002547050615618414, 'max_iter': 3312}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  72%|███████▏  | 361/500 [55:42<1:23:15, 35.94s/it]

[I 2026-05-18 18:01:53,434] Trial 371 finished with value: 0.9495727402106006 and parameters: {'solver': 'saga', 'C': 0.0020131164457280835, 'l1_ratio': 0.2878656821738322, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011595823356831148, 'max_iter': 3202}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  72%|███████▏  | 362/500 [56:07<1:14:50, 32.54s/it]

[I 2026-05-18 18:02:18,061] Trial 372 finished with value: 0.9495810516329876 and parameters: {'solver': 'saga', 'C': 0.0012243929666926228, 'l1_ratio': 0.3102324960852884, 'class_weight': None, 'fit_intercept': True, 'tol': 6.027269463976475e-05, 'max_iter': 3383}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  73%|███████▎  | 363/500 [56:30<1:07:47, 29.69s/it]

[I 2026-05-18 18:02:41,084] Trial 373 finished with value: 0.9495796516523674 and parameters: {'solver': 'saga', 'C': 0.0006711974497962177, 'l1_ratio': 0.26073004034088015, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017654139947487568, 'max_iter': 3072}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  73%|███████▎  | 364/500 [56:53<1:03:00, 27.80s/it]

[I 2026-05-18 18:03:04,479] Trial 374 finished with value: 0.9495810041311044 and parameters: {'solver': 'saga', 'C': 0.001024454573599246, 'l1_ratio': 0.3501177461115725, 'class_weight': None, 'fit_intercept': True, 'tol': 8.206309888878196e-05, 'max_iter': 3314}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  73%|███████▎  | 365/500 [57:14<57:34, 25.59s/it]

[I 2026-05-18 18:03:24,909] Trial 375 finished with value: 0.9495756886768895 and parameters: {'solver': 'saga', 'C': 0.0017809735066389445, 'l1_ratio': 0.3199059624822684, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00033514886024449934, 'max_iter': 3219}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  73%|███████▎  | 366/500 [57:37<55:48, 24.99s/it]

[I 2026-05-18 18:03:48,508] Trial 376 finished with value: 0.9495801282662649 and parameters: {'solver': 'saga', 'C': 0.0007417827001876396, 'l1_ratio': 0.2829906139690657, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001417624647063472, 'max_iter': 3427}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  73%|███████▎  | 367/500 [58:00<53:45, 24.25s/it]

[I 2026-05-18 18:04:11,021] Trial 377 finished with value: 0.9495792094571055 and parameters: {'solver': 'saga', 'C': 0.0014319701619755914, 'l1_ratio': 0.3057897175376207, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011619140726774497, 'max_iter': 3284}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  74%|███████▎  | 368/500 [58:24<53:31, 24.33s/it]

[I 2026-05-18 18:04:35,541] Trial 378 finished with value: 0.9495810641966985 and parameters: {'solver': 'saga', 'C': 0.0009469630203783776, 'l1_ratio': 0.33576152760908484, 'class_weight': None, 'fit_intercept': True, 'tol': 9.039674491202739e-05, 'max_iter': 4884}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  74%|███████▍  | 369/500 [58:54<56:53, 26.05s/it]

[I 2026-05-18 18:05:05,616] Trial 379 finished with value: 0.949576472331243 and parameters: {'solver': 'saga', 'C': 0.0005376359923337715, 'l1_ratio': 0.29819031915178085, 'class_weight': None, 'fit_intercept': True, 'tol': 8.40465514672964e-06, 'max_iter': 3137}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  74%|███████▍  | 370/500 [59:15<52:55, 24.43s/it]

[I 2026-05-18 18:05:26,257] Trial 380 finished with value: 0.9495532579379031 and parameters: {'solver': 'saga', 'C': 0.0003889749690151135, 'l1_ratio': 0.380072449199447, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00045691576761098667, 'max_iter': 3389}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  74%|███████▍  | 371/500 [59:37<51:16, 23.85s/it]

[I 2026-05-18 18:05:48,753] Trial 381 finished with value: 0.949579721467086 and parameters: {'solver': 'saga', 'C': 0.001175023775238843, 'l1_ratio': 0.258650143689907, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017764706636969383, 'max_iter': 3316}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  74%|███████▍  | 372/500 [59:58<49:05, 23.01s/it]

[I 2026-05-18 18:06:09,807] Trial 382 finished with value: 0.949551321373556 and parameters: {'solver': 'saga', 'C': 0.0007726087825674778, 'l1_ratio': 0.6200190061602147, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00022176211952799874, 'max_iter': 2851}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  75%|███████▍  | 373/500 [1:00:26<51:51, 24.50s/it]

[I 2026-05-18 18:06:37,786] Trial 383 finished with value: 0.9495705475189335 and parameters: {'solver': 'saga', 'C': 0.0023837597219362448, 'l1_ratio': 0.3275032786351227, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014853758762659885, 'max_iter': 3176}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  75%|███████▍  | 374/500 [1:00:51<51:26, 24.50s/it]

[I 2026-05-18 18:07:02,284] Trial 384 finished with value: 0.9495781367668362 and parameters: {'solver': 'saga', 'C': 0.0016194373629477082, 'l1_ratio': 0.355907910697354, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010218396245118214, 'max_iter': 3548}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  75%|███████▌  | 375/500 [1:01:15<51:03, 24.51s/it]

[I 2026-05-18 18:07:26,825] Trial 385 finished with value: 0.9495806290055568 and parameters: {'solver': 'saga', 'C': 0.0012205942450261985, 'l1_ratio': 0.28783530729318385, 'class_weight': None, 'fit_intercept': True, 'tol': 5.182643827755265e-05, 'max_iter': 3228}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  75%|███████▌  | 376/500 [1:01:42<51:46, 25.05s/it]

[I 2026-05-18 18:07:53,147] Trial 386 finished with value: 0.9495779140419959 and parameters: {'solver': 'saga', 'C': 0.0006385644796214814, 'l1_ratio': 0.3140002775941351, 'class_weight': None, 'fit_intercept': True, 'tol': 7.409500260629215e-05, 'max_iter': 3049}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  75%|███████▌  | 377/500 [1:07:52<4:23:50, 128.70s/it]

[I 2026-05-18 18:14:03,700] Trial 354 finished with value: 0.9495254057822295 and parameters: {'solver': 'saga', 'C': 0.5480369168781868, 'l1_ratio': 0.26724698787773477, 'class_weight': None, 'fit_intercept': True, 'tol': 8.694422285898199e-05, 'max_iter': 3244}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  76%|███████▌  | 378/500 [1:08:14<3:16:24, 96.59s/it]

[I 2026-05-18 18:14:25,360] Trial 388 finished with value: 0.9494751761815238 and parameters: {'solver': 'saga', 'C': 0.0008851733062172463, 'l1_ratio': 0.6879873105347697, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00012606750679978549, 'max_iter': 3435}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  76%|███████▌  | 379/500 [1:09:10<2:50:11, 84.40s/it]

[I 2026-05-18 18:15:21,298] Trial 389 finished with value: 0.9495487494853428 and parameters: {'solver': 'saga', 'C': 0.00769398625706663, 'l1_ratio': 0.3267215340583489, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016433079110554494, 'max_iter': 2631}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  76%|███████▌  | 380/500 [1:10:37<2:50:15, 85.13s/it]

[I 2026-05-18 18:16:48,128] Trial 337 finished with value: 0.9495250941011586 and parameters: {'solver': 'saga', 'C': 4.57814982073435, 'l1_ratio': 0.3082907538542112, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015927083185885476, 'max_iter': 3269}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  76%|███████▌  | 381/500 [1:11:01<2:12:19, 66.72s/it]

[I 2026-05-18 18:17:11,902] Trial 391 finished with value: 0.9495743700973571 and parameters: {'solver': 'saga', 'C': 0.0015990245095574473, 'l1_ratio': 0.2350074013956273, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010982275007780589, 'max_iter': 3361}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  76%|███████▋  | 382/500 [1:11:21<1:43:46, 52.76s/it]

[I 2026-05-18 18:17:32,102] Trial 392 finished with value: 0.9495814738632694 and parameters: {'solver': 'saga', 'C': 0.0011004913409802801, 'l1_ratio': 0.3443349353014071, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000275529893164159, 'max_iter': 3137}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  77%|███████▋  | 383/500 [1:12:08<1:39:43, 51.14s/it]

[I 2026-05-18 18:18:19,464] Trial 368 finished with value: 0.9495254295318369 and parameters: {'solver': 'saga', 'C': 0.5683221406089946, 'l1_ratio': 0.3202621174220544, 'class_weight': None, 'fit_intercept': True, 'tol': 8.225606560529601e-05, 'max_iter': 3220}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  77%|███████▋  | 384/500 [1:12:35<1:24:53, 43.91s/it]

[I 2026-05-18 18:18:46,484] Trial 394 finished with value: 0.9495766549737599 and parameters: {'solver': 'saga', 'C': 0.0005350498939723047, 'l1_ratio': 0.21555656096117048, 'class_weight': None, 'fit_intercept': True, 'tol': 6.244724393574422e-05, 'max_iter': 3420}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  77%|███████▋  | 385/500 [1:12:57<1:11:29, 37.30s/it]

[I 2026-05-18 18:19:08,356] Trial 395 finished with value: 0.9495723226311705 and parameters: {'solver': 'saga', 'C': 0.0020559152982475718, 'l1_ratio': 0.282741349563024, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020509099489869663, 'max_iter': 3504}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  77%|███████▋  | 386/500 [1:12:59<50:55, 26.80s/it]

[I 2026-05-18 18:19:10,672] Trial 393 finished with value: 0.9494602648325692 and parameters: {'solver': 'saga', 'C': 0.0006117557709725805, 'l1_ratio': 0.998105435274294, 'class_weight': None, 'fit_intercept': True, 'tol': 6.401029087807085e-05, 'max_iter': 3468}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  77%|███████▋  | 387/500 [1:13:22<47:56, 25.46s/it]

[I 2026-05-18 18:19:32,987] Trial 396 finished with value: 0.9495802224495253 and parameters: {'solver': 'saga', 'C': 0.000789085493730382, 'l1_ratio': 0.29826783500301296, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001292932387674719, 'max_iter': 3063}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  78%|███████▊  | 388/500 [1:13:23<33:48, 18.12s/it]

[I 2026-05-18 18:19:33,977] Trial 397 finished with value: 0.9495816883416625 and parameters: {'solver': 'saga', 'C': 0.0009138491722079116, 'l1_ratio': 0.29815411676680886, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012297549307528112, 'max_iter': 3335}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  78%|███████▊  | 389/500 [1:13:45<35:39, 19.28s/it]

[I 2026-05-18 18:19:55,963] Trial 398 finished with value: 0.9495798874892032 and parameters: {'solver': 'saga', 'C': 0.0014326422203476048, 'l1_ratio': 0.34182189170364463, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010335703023965864, 'max_iter': 1060}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  78%|███████▊  | 390/500 [1:13:48<26:44, 14.59s/it]

[I 2026-05-18 18:19:59,600] Trial 399 finished with value: 0.949566782636931 and parameters: {'solver': 'saga', 'C': 0.00036241978926942624, 'l1_ratio': 0.280859387638982, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010040983261595347, 'max_iter': 3317}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  78%|███████▊  | 391/500 [1:14:09<29:38, 16.31s/it]

[I 2026-05-18 18:20:19,946] Trial 400 finished with value: 0.9495711145035639 and parameters: {'solver': 'saga', 'C': 0.0003880888818054095, 'l1_ratio': 0.2522369124509956, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011721776096760693, 'max_iter': 3328}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  78%|███████▊  | 392/500 [1:14:11<22:04, 12.26s/it]

[I 2026-05-18 18:20:22,750] Trial 401 finished with value: 0.9495812038464845 and parameters: {'solver': 'saga', 'C': 0.0009431707676432101, 'l1_ratio': 0.25430065029797394, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001449689064247824, 'max_iter': 2919}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  79%|███████▊  | 393/500 [1:14:31<25:33, 14.33s/it]

[I 2026-05-18 18:20:41,914] Trial 402 finished with value: 0.9495708429347223 and parameters: {'solver': 'saga', 'C': 0.0009151943967080567, 'l1_ratio': 0.10342414695620566, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00022885378479469903, 'max_iter': 3145}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  79%|███████▉  | 394/500 [1:14:34<19:39, 11.13s/it]

[I 2026-05-18 18:20:45,562] Trial 403 finished with value: 0.9495471341988024 and parameters: {'solver': 'saga', 'C': 0.0002231166994649291, 'l1_ratio': 0.3013556729734605, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019401238751090387, 'max_iter': 3167}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  79%|███████▉  | 395/500 [1:14:51<22:43, 12.98s/it]

[I 2026-05-18 18:21:02,875] Trial 404 finished with value: 0.949579240376082 and parameters: {'solver': 'saga', 'C': 0.0014010043950514908, 'l1_ratio': 0.2997568666943225, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001839402159668655, 'max_iter': 3200}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  79%|███████▉  | 396/500 [1:14:55<17:30, 10.10s/it]

[I 2026-05-18 18:21:06,235] Trial 365 finished with value: 0.9495250697050202 and parameters: {'solver': 'saga', 'C': 0.9441737200628542, 'l1_ratio': 0.30110184167706877, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012351916225328283, 'max_iter': 3278}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  79%|███████▉  | 397/500 [1:15:06<17:47, 10.36s/it]

[I 2026-05-18 18:21:17,227] Trial 405 finished with value: 0.9495702115251987 and parameters: {'solver': 'saga', 'C': 0.0027118894586374625, 'l1_ratio': 0.2785924903600072, 'class_weight': None, 'fit_intercept': True, 'tol': 7.263448183636567e-05, 'max_iter': 2421}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  80%|███████▉  | 398/500 [1:15:17<17:54, 10.53s/it]

[I 2026-05-18 18:21:28,156] Trial 407 finished with value: 0.9495324179257574 and parameters: {'solver': 'saga', 'C': 0.0007355861286934982, 'l1_ratio': 0.2758324196144201, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00032669415445466877, 'max_iter': 3359}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  80%|███████▉  | 399/500 [1:15:18<12:56,  7.69s/it]

[I 2026-05-18 18:21:29,199] Trial 406 finished with value: 0.9495780464575535 and parameters: {'solver': 'saga', 'C': 0.0006149757567643741, 'l1_ratio': 0.28529157529139304, 'class_weight': None, 'fit_intercept': True, 'tol': 7.479341511925683e-05, 'max_iter': 3349}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  80%|████████  | 400/500 [1:15:19<09:27,  5.67s/it]

[I 2026-05-18 18:21:30,169] Trial 408 pruned.

Best trial: 168. Best value: 0.949582:  80%|████████  | 401/500 [1:15:32<13:03,  7.92s/it]

[I 2026-05-18 18:21:43,326] Trial 409 pruned.

Best trial: 168. Best value: 0.949582:  80%|████████  | 402/500 [1:15:33<09:29,  5.81s/it]

[I 2026-05-18 18:21:44,216] Trial 410 pruned.

Best trial: 168. Best value: 0.949582:  81%|████████  | 403/500 [1:15:44<12:04,  7.47s/it]

[I 2026-05-18 18:21:55,548] Trial 411 finished with value: 0.9495756907851829 and parameters: {'solver': 'saga', 'C': 0.0018749258406947499, 'l1_ratio': 0.3622220428806133, 'class_weight': None, 'fit_intercept': True, 'tol': 9.416058774855926e-05, 'max_iter': 3080}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  81%|████████  | 404/500 [1:15:55<13:26,  8.40s/it]

[I 2026-05-18 18:22:06,129] Trial 413 finished with value: 0.9495813134860291 and parameters: {'solver': 'saga', 'C': 0.0011045286617345437, 'l1_ratio': 0.3570330044572813, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015097036281660486, 'max_iter': 3251}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  81%|████████  | 405/500 [1:16:05<14:06,  8.91s/it]

[I 2026-05-18 18:22:16,241] Trial 414 finished with value: 0.9495802696898401 and parameters: {'solver': 'saga', 'C': 0.0011379759978764014, 'l1_ratio': 0.2603257947956583, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014801382059125072, 'max_iter': 3246}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  81%|████████  | 406/500 [1:16:16<14:47,  9.44s/it]

[I 2026-05-18 18:22:26,903] Trial 415 finished with value: 0.9495753219433052 and parameters: {'solver': 'saga', 'C': 0.00047691029680953375, 'l1_ratio': 0.2660133424642462, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002585855121324037, 'max_iter': 2787}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  81%|████████▏ | 407/500 [1:16:38<20:47, 13.42s/it]

[I 2026-05-18 18:22:49,601] Trial 417 finished with value: 0.9495812867290713 and parameters: {'solver': 'saga', 'C': 0.0009013438521387982, 'l1_ratio': 0.3093786993029201, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011813277630386402, 'max_iter': 2961}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  82%|████████▏ | 408/500 [1:16:39<14:46,  9.63s/it]

[I 2026-05-18 18:22:50,403] Trial 416 finished with value: 0.9495626833189892 and parameters: {'solver': 'saga', 'C': 0.0040958088876784215, 'l1_ratio': 0.301917127400561, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00024725895059691134, 'max_iter': 3545}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  82%|████████▏ | 409/500 [1:17:02<20:51, 13.76s/it]

[I 2026-05-18 18:23:13,752] Trial 419 finished with value: 0.9495801043476538 and parameters: {'solver': 'saga', 'C': 0.0013778685579267495, 'l1_ratio': 0.3368652463179424, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018394784371139966, 'max_iter': 3959}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  82%|████████▏ | 410/500 [1:17:03<14:51,  9.90s/it]

[I 2026-05-18 18:23:14,694] Trial 418 finished with value: 0.9491714075047415 and parameters: {'solver': 'saga', 'C': 5.869096200530635e-05, 'l1_ratio': 0.33824327761715406, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001745883512881524, 'max_iter': 3568}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  82%|████████▏ | 411/500 [1:17:27<20:53, 14.08s/it]

[I 2026-05-18 18:23:38,523] Trial 421 finished with value: 0.9495819255642693 and parameters: {'solver': 'saga', 'C': 0.0010644238510881768, 'l1_ratio': 0.289370603773106, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001180417239188613, 'max_iter': 1561}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  82%|████████▏ | 412/500 [1:17:39<19:28, 13.27s/it]

[I 2026-05-18 18:23:49,913] Trial 420 finished with value: 0.9495030686666956 and parameters: {'solver': 'saga', 'C': 0.0004762586248889769, 'l1_ratio': 0.8866346603727708, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012070859293060437, 'max_iter': 3435}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  83%|████████▎ | 413/500 [1:17:51<18:54, 13.04s/it]

[I 2026-05-18 18:24:02,400] Trial 422 finished with value: 0.9495795828223009 and parameters: {'solver': 'saga', 'C': 0.0013283054792216965, 'l1_ratio': 0.2854497514401261, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013644635983915145, 'max_iter': 1529}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  83%|████████▎ | 414/500 [1:18:16<23:52, 16.66s/it]

[I 2026-05-18 18:24:27,515] Trial 424 finished with value: 0.9495805614375357 and parameters: {'solver': 'saga', 'C': 0.0007818530579257754, 'l1_ratio': 0.27398269857212393, 'class_weight': None, 'fit_intercept': True, 'tol': 8.177668365915453e-05, 'max_iter': 3018}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  83%|████████▎ | 415/500 [1:24:21<2:51:43, 121.21s/it]

[I 2026-05-18 18:30:32,684] Trial 12 finished with value: 0.9495033569908975 and parameters: {'solver': 'saga', 'C': 4.053340172272188, 'l1_ratio': 0.9277131799035272, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.902454170317396e-05, 'max_iter': 4777}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  83%|████████▎ | 416/500 [1:24:46<2:09:03, 92.18s/it]

[I 2026-05-18 18:30:57,131] Trial 426 finished with value: 0.9495703242675557 and parameters: {'solver': 'saga', 'C': 0.00254100665234219, 'l1_ratio': 0.24354361291051274, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00042329134247050357, 'max_iter': 2219}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  83%|████████▎ | 417/500 [1:25:09<1:38:45, 71.39s/it]

[I 2026-05-18 18:31:20,017] Trial 427 finished with value: 0.9495817335996743 and parameters: {'solver': 'saga', 'C': 0.0010913519793954486, 'l1_ratio': 0.2906830867809307, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015521640429842684, 'max_iter': 3156}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  84%|████████▎ | 418/500 [1:25:32<1:18:00, 57.08s/it]

[I 2026-05-18 18:31:43,691] Trial 428 finished with value: 0.9495764048420418 and parameters: {'solver': 'saga', 'C': 0.0013938325870020208, 'l1_ratio': 0.23509564877981787, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019287676011505827, 'max_iter': 3124}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  84%|████████▍ | 419/500 [1:25:36<55:38, 41.21s/it]

[I 2026-05-18 18:31:47,884] Trial 346 finished with value: 0.9495248170776195 and parameters: {'solver': 'saga', 'C': 1.4502684862484103, 'l1_ratio': 0.2797115610896581, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002157673886496805, 'max_iter': 2989}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  84%|████████▍ | 420/500 [1:26:06<50:17, 37.72s/it]

[I 2026-05-18 18:32:17,442] Trial 430 finished with value: 0.9495712917603875 and parameters: {'solver': 'saga', 'C': 0.002246970007581813, 'l1_ratio': 0.30990106942694484, 'class_weight': None, 'fit_intercept': True, 'tol': 5.0749547419046147e-05, 'max_iter': 3176}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  84%|████████▍ | 421/500 [1:26:09<35:51, 27.23s/it]

[I 2026-05-18 18:32:20,218] Trial 429 finished with value: 0.9495682163218898 and parameters: {'solver': 'saga', 'C': 0.002428516373258602, 'l1_ratio': 0.4818892698223933, 'class_weight': None, 'fit_intercept': True, 'tol': 5.315520112792701e-05, 'max_iter': 3180}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  84%|████████▍ | 422/500 [1:26:31<33:33, 25.81s/it]

[I 2026-05-18 18:32:42,703] Trial 431 finished with value: 0.9495796209270445 and parameters: {'solver': 'saga', 'C': 0.00121019144283748, 'l1_ratio': 0.2657151618096206, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001570201959583093, 'max_iter': 1385}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  85%|████████▍ | 423/500 [1:26:32<23:27, 18.28s/it]

[I 2026-05-18 18:32:43,424] Trial 432 finished with value: 0.9495801070102173 and parameters: {'solver': 'saga', 'C': 0.0011575073315006617, 'l1_ratio': 0.26095109559198093, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016464855501788065, 'max_iter': 1164}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  85%|████████▍ | 424/500 [1:26:56<25:10, 19.87s/it]

[I 2026-05-18 18:33:07,013] Trial 433 finished with value: 0.9495779817109536 and parameters: {'solver': 'saga', 'C': 0.0006351123315205777, 'l1_ratio': 0.30331392616950825, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015798405168849068, 'max_iter': 2489}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  85%|████████▌ | 425/500 [1:27:20<26:42, 21.37s/it]

[I 2026-05-18 18:33:31,865] Trial 435 finished with value: 0.9495764098308805 and parameters: {'solver': 'saga', 'C': 0.001613356754303322, 'l1_ratio': 0.2861930519103483, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010597154068970052, 'max_iter': 3255}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  85%|████████▌ | 426/500 [1:27:44<27:10, 22.03s/it]

[I 2026-05-18 18:33:55,447] Trial 436 finished with value: 0.9495800812564635 and parameters: {'solver': 'saga', 'C': 0.0007892907328283789, 'l1_ratio': 0.3130279388317265, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013666540946930724, 'max_iter': 4905}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  85%|████████▌ | 427/500 [1:27:58<23:58, 19.71s/it]

[I 2026-05-18 18:34:09,729] Trial 437 finished with value: 0.9495781091340753 and parameters: {'solver': 'saga', 'C': 0.0010172341024054172, 'l1_ratio': 0.21480429059677275, 'class_weight': None, 'fit_intercept': True, 'tol': 0.004470088468807716, 'max_iter': 2075}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  86%|████████▌ | 428/500 [1:28:21<24:49, 20.69s/it]

[I 2026-05-18 18:34:32,717] Trial 438 finished with value: 0.9495752559035668 and parameters: {'solver': 'saga', 'C': 0.0005224725441049526, 'l1_ratio': 0.3237314273361472, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00026567095187887577, 'max_iter': 2929}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  86%|████████▌ | 429/500 [1:28:43<24:50, 20.99s/it]

[I 2026-05-18 18:34:54,394] Trial 439 finished with value: 0.9495757091756968 and parameters: {'solver': 'saga', 'C': 0.0017294342931437707, 'l1_ratio': 0.29468613631692153, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00021827808381617996, 'max_iter': 3048}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  86%|████████▌ | 430/500 [1:29:08<25:59, 22.28s/it]

[I 2026-05-18 18:35:19,699] Trial 440 finished with value: 0.9495796464582327 and parameters: {'solver': 'saga', 'C': 0.0006885678077758091, 'l1_ratio': 0.28761168920495367, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010453915101959937, 'max_iter': 3127}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  86%|████████▌ | 431/500 [1:29:24<23:12, 20.19s/it]

[I 2026-05-18 18:35:34,999] Trial 387 finished with value: 0.949524854649052 and parameters: {'solver': 'saga', 'C': 3.4230410408119583, 'l1_ratio': 0.27872598855541453, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012637392233249756, 'max_iter': 1003}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  86%|████████▋ | 432/500 [1:29:35<19:46, 17.44s/it]

[I 2026-05-18 18:35:46,038] Trial 441 finished with value: 0.9495819096317583 and parameters: {'solver': 'saga', 'C': 0.0010938265675004726, 'l1_ratio': 0.3162508503886294, 'class_weight': None, 'fit_intercept': True, 'tol': 6.789254131304137e-05, 'max_iter': 3208}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  87%|████████▋ | 433/500 [1:29:51<18:57, 16.98s/it]

[I 2026-05-18 18:36:01,924] Trial 442 finished with value: 0.9495806394865948 and parameters: {'solver': 'saga', 'C': 0.001027430769716982, 'l1_ratio': 0.2478429287514521, 'class_weight': None, 'fit_intercept': True, 'tol': 6.665085379210888e-05, 'max_iter': 1237}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  87%|████████▋ | 434/500 [1:30:01<16:24, 14.92s/it]

[I 2026-05-18 18:36:12,040] Trial 443 finished with value: 0.9495793143708656 and parameters: {'solver': 'saga', 'C': 0.0014977590646500444, 'l1_ratio': 0.33445789213762317, 'class_weight': None, 'fit_intercept': True, 'tol': 6.369673476159561e-05, 'max_iter': 3165}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  87%|████████▋ | 435/500 [1:30:17<16:46, 15.49s/it]

[I 2026-05-18 18:36:28,858] Trial 444 finished with value: 0.949578805691267 and parameters: {'solver': 'saga', 'C': 0.0015419198305382915, 'l1_ratio': 0.34530793078229693, 'class_weight': None, 'fit_intercept': True, 'tol': 3.944200278694812e-05, 'max_iter': 1661}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  87%|████████▋ | 436/500 [1:30:38<18:12, 17.08s/it]

[I 2026-05-18 18:36:49,637] Trial 445 finished with value: 0.9495671505483759 and parameters: {'solver': 'saga', 'C': 0.003028398312649704, 'l1_ratio': 0.36637642592140346, 'class_weight': None, 'fit_intercept': True, 'tol': 7.61126140290231e-05, 'max_iter': 1691}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  87%|████████▋ | 437/500 [1:30:58<18:38, 17.76s/it]

[I 2026-05-18 18:37:08,987] Trial 446 finished with value: 0.9495658493178778 and parameters: {'solver': 'saga', 'C': 0.00327598579345718, 'l1_ratio': 0.3748360169563218, 'class_weight': None, 'fit_intercept': True, 'tol': 7.723415485506701e-05, 'max_iter': 3036}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  88%|████████▊ | 438/500 [1:31:04<14:47, 14.32s/it]

[I 2026-05-18 18:37:15,272] Trial 447 finished with value: 0.9495572664400915 and parameters: {'solver': 'saga', 'C': 0.00032500003599629496, 'l1_ratio': 0.3211626100960427, 'class_weight': None, 'fit_intercept': True, 'tol': 8.376285464714898e-05, 'max_iter': 3675}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  88%|████████▊ | 439/500 [1:31:24<16:18, 16.05s/it]

[I 2026-05-18 18:37:35,344] Trial 448 finished with value: 0.9495547876677899 and parameters: {'solver': 'saga', 'C': 0.0002901870524777635, 'l1_ratio': 0.3163506289341317, 'class_weight': None, 'fit_intercept': True, 'tol': 9.205157459385306e-05, 'max_iter': 3266}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  88%|████████▊ | 440/500 [1:31:30<13:04, 13.08s/it]

[I 2026-05-18 18:37:41,524] Trial 449 finished with value: 0.9495356174478531 and parameters: {'solver': 'saga', 'C': 0.0007612843567426324, 'l1_ratio': 0.31295699055655335, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.64909568960741e-05, 'max_iter': 1920}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  88%|████████▊ | 441/500 [1:31:51<15:10, 15.43s/it]

[I 2026-05-18 18:38:02,443] Trial 450 finished with value: 0.9495805437064035 and parameters: {'solver': 'saga', 'C': 0.0008154848298232483, 'l1_ratio': 0.29295929284873706, 'class_weight': None, 'fit_intercept': True, 'tol': 5.771776384979512e-05, 'max_iter': 2002}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  88%|████████▊ | 442/500 [1:31:57<12:15, 12.68s/it]

[I 2026-05-18 18:38:08,703] Trial 451 finished with value: 0.9495753248795982 and parameters: {'solver': 'saga', 'C': 0.0004886561238022871, 'l1_ratio': 0.2902423058185313, 'class_weight': None, 'fit_intercept': True, 'tol': 5.862695502894059e-05, 'max_iter': 3286}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  89%|████████▊ | 443/500 [1:32:25<16:20, 17.19s/it]

[I 2026-05-18 18:38:36,411] Trial 453 finished with value: 0.9495735695096343 and parameters: {'solver': 'saga', 'C': 0.0020586613364281256, 'l1_ratio': 0.35116708144157777, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011060635624932662, 'max_iter': 2853}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  89%|████████▉ | 444/500 [1:32:31<12:57, 13.89s/it]

[I 2026-05-18 18:38:42,592] Trial 434 finished with value: 0.9495232368795692 and parameters: {'solver': 'saga', 'C': 83.68857924985528, 'l1_ratio': 0.29021286477315034, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014457200921320278, 'max_iter': 3033}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  89%|████████▉ | 445/500 [1:32:49<13:55, 15.19s/it]

[I 2026-05-18 18:39:00,832] Trial 454 finished with value: 0.9495804948331352 and parameters: {'solver': 'saga', 'C': 0.0011223995264610564, 'l1_ratio': 0.26292968881494394, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014270008450707587, 'max_iter': 4842}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  89%|████████▉ | 446/500 [1:32:55<10:56, 12.16s/it]

[I 2026-05-18 18:39:05,915] Trial 455 finished with value: 0.949580327119097 and parameters: {'solver': 'saga', 'C': 0.0011250630051385451, 'l1_ratio': 0.2615228302876955, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012088162457907372, 'max_iter': 3420}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  89%|████████▉ | 447/500 [1:33:16<13:10, 14.91s/it]

[I 2026-05-18 18:39:27,245] Trial 456 finished with value: 0.9495766979373054 and parameters: {'solver': 'saga', 'C': 0.0006003256829099333, 'l1_ratio': 0.33161621077754033, 'class_weight': None, 'fit_intercept': True, 'tol': 7.035732949154646e-05, 'max_iter': 3198}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  90%|████████▉ | 448/500 [1:33:21<10:16, 11.85s/it]

[I 2026-05-18 18:39:31,946] Trial 457 finished with value: 0.9495767067249321 and parameters: {'solver': 'saga', 'C': 0.0005977374577288619, 'l1_ratio': 0.33164877354332223, 'class_weight': None, 'fit_intercept': True, 'tol': 7.201474798109333e-05, 'max_iter': 3201}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  90%|████████▉ | 449/500 [1:33:45<13:21, 15.71s/it]

[I 2026-05-18 18:39:56,662] Trial 459 finished with value: 0.949578425188679 and parameters: {'solver': 'saga', 'C': 0.001527358942076085, 'l1_ratio': 0.30872131172489975, 'class_weight': None, 'fit_intercept': True, 'tol': 8.9344755089694e-05, 'max_iter': 3124}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  90%|█████████ | 450/500 [1:34:13<16:02, 19.25s/it]

[I 2026-05-18 18:40:24,189] Trial 460 finished with value: 0.9495796635099618 and parameters: {'solver': 'saga', 'C': 0.0008857913514864937, 'l1_ratio': 0.35059689481888273, 'class_weight': None, 'fit_intercept': True, 'tol': 4.527320749832664e-05, 'max_iter': 3295}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  90%|█████████ | 451/500 [1:34:40<17:40, 21.65s/it]

[I 2026-05-18 18:40:51,431] Trial 461 finished with value: 0.9495739444979631 and parameters: {'solver': 'saga', 'C': 0.0020156668584707335, 'l1_ratio': 0.4045748637437927, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011273490579899184, 'max_iter': 3481}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  90%|█████████ | 452/500 [1:35:06<18:18, 22.88s/it]

[I 2026-05-18 18:41:17,192] Trial 462 finished with value: 0.9495765523923954 and parameters: {'solver': 'saga', 'C': 0.0013631093090307736, 'l1_ratio': 0.2327667809271427, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017029884727891932, 'max_iter': 3384}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  91%|█████████ | 453/500 [1:35:29<18:01, 23.02s/it]

[I 2026-05-18 18:41:40,521] Trial 463 finished with value: 0.9495645029672211 and parameters: {'solver': 'saga', 'C': 0.0009301276725533397, 'l1_ratio': 0.573459875880702, 'class_weight': None, 'fit_intercept': True, 'tol': 9.74479222560708e-05, 'max_iter': 2956}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  91%|█████████ | 454/500 [1:35:53<17:47, 23.21s/it]

[I 2026-05-18 18:42:04,169] Trial 464 finished with value: 0.9495732508516198 and parameters: {'solver': 'saga', 'C': 0.0004335030961746, 'l1_ratio': 0.2748988320000044, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013889296193187684, 'max_iter': 3117}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  91%|█████████ | 455/500 [1:36:16<17:21, 23.14s/it]

[I 2026-05-18 18:42:27,147] Trial 465 finished with value: 0.9495794946858631 and parameters: {'solver': 'saga', 'C': 0.0007386467659334903, 'l1_ratio': 0.3171680191301964, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001129601554249542, 'max_iter': 3305}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  91%|█████████ | 456/500 [1:36:38<16:49, 22.95s/it]

[I 2026-05-18 18:42:49,665] Trial 466 finished with value: 0.9495806659228476 and parameters: {'solver': 'saga', 'C': 0.0012596064347806257, 'l1_ratio': 0.3018615576765668, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018398005935249512, 'max_iter': 3388}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  91%|█████████▏| 457/500 [1:36:54<14:59, 20.92s/it]

[I 2026-05-18 18:43:05,839] Trial 467 pruned.

Best trial: 168. Best value: 0.949582:  92%|█████████▏| 458/500 [1:37:01<11:41, 16.71s/it]

[I 2026-05-18 18:43:12,722] Trial 458 finished with value: 0.949529776912412 and parameters: {'solver': 'saga', 'C': 0.04963861635276545, 'l1_ratio': 0.3080076680727963, 'class_weight': None, 'fit_intercept': True, 'tol': 8.684235587763927e-05, 'max_iter': 3118}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  92%|█████████▏| 459/500 [1:37:20<11:43, 17.17s/it]

[I 2026-05-18 18:43:30,968] Trial 468 finished with value: 0.9495390863190343 and parameters: {'solver': 'saga', 'C': 0.0009062535312205929, 'l1_ratio': 0.33222455931398276, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00013146675964509472, 'max_iter': 4355}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  92%|█████████▏| 460/500 [1:37:26<09:13, 13.83s/it]

[I 2026-05-18 18:43:37,001] Trial 469 finished with value: 0.9495412557676426 and parameters: {'solver': 'saga', 'C': 0.0010242448896676491, 'l1_ratio': 0.3319632562571545, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00013922021498143368, 'max_iter': 2685}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  92%|█████████▏| 461/500 [1:37:44<09:49, 15.12s/it]

[I 2026-05-18 18:43:55,127] Trial 470 finished with value: 0.94957682333868 and parameters: {'solver': 'saga', 'C': 0.0006635777051346597, 'l1_ratio': 0.3499217981750605, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016020618367985968, 'max_iter': 3491}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  92%|█████████▏| 462/500 [1:37:52<08:18, 13.12s/it]

[I 2026-05-18 18:44:03,560] Trial 471 finished with value: 0.9495783939175364 and parameters: {'solver': 'saga', 'C': 0.0006376916848460141, 'l1_ratio': 0.29427961746684844, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010486032077351255, 'max_iter': 3471}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  93%|█████████▎| 463/500 [1:38:11<09:05, 14.75s/it]

[I 2026-05-18 18:44:22,142] Trial 472 finished with value: 0.9495806543852654 and parameters: {'solver': 'saga', 'C': 0.0012230670085651273, 'l1_ratio': 0.2894574127288433, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010603771978433752, 'max_iter': 4759}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  93%|█████████▎| 464/500 [1:38:11<06:18, 10.52s/it]

[I 2026-05-18 18:44:22,780] Trial 452 finished with value: 0.9495266692505503 and parameters: {'solver': 'saga', 'C': 0.12259179647802017, 'l1_ratio': 0.5724858785588214, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011081672456752255, 'max_iter': 3289}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  93%|█████████▎| 465/500 [1:38:37<08:51, 15.18s/it]

[I 2026-05-18 18:44:48,835] Trial 473 finished with value: 0.9495571350467543 and parameters: {'solver': 'saga', 'C': 0.0051281718271253395, 'l1_ratio': 0.2516178378533331, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000187370146321654, 'max_iter': 4749}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  93%|█████████▎| 466/500 [1:38:38<06:05, 10.74s/it]

[I 2026-05-18 18:44:49,201] Trial 474 finished with value: 0.949577717549946 and parameters: {'solver': 'saga', 'C': 0.0016075731841495515, 'l1_ratio': 0.3142251424774411, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018569435079137482, 'max_iter': 3306}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  93%|█████████▎| 467/500 [1:38:39<04:22,  7.95s/it]

[I 2026-05-18 18:44:50,648] Trial 475 finished with value: 0.949573701162927 and parameters: {'solver': 'saga', 'C': 0.0016305889151737964, 'l1_ratio': 0.5241323450967275, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002027600787975608, 'max_iter': 3182}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  94%|█████████▍| 469/500 [1:39:05<04:45,  9.21s/it]

[I 2026-05-18 18:45:15,709] Trial 476 finished with value: 0.9495774767910042 and parameters: {'solver': 'saga', 'C': 0.0016327618540161988, 'l1_ratio': 0.316986744076532, 'class_weight': None, 'fit_intercept': True, 'tol': 5.57814025334069e-05, 'max_iter': 4107}. Best is trial 168 with value: 0.9495820845736207.
[I 2026-05-18 18:45:15,898] Trial 478 finished with value: 0.9495672650932215 and parameters: {'solver': 'saga', 'C': 0.0004869302177170099, 'l1_ratio': 0.3769544690207802, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00036244174644351255, 'max_iter': 4091}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  94%|█████████▍| 470/500 [1:39:10<04:06,  8.23s/it]

[I 2026-05-18 18:45:21,822] Trial 477 finished with value: 0.9495679237034768 and parameters: {'solver': 'saga', 'C': 0.002642366838121259, 'l1_ratio': 0.19857710435480774, 'class_weight': None, 'fit_intercept': True, 'tol': 7.372870737301513e-05, 'max_iter': 3214}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  94%|█████████▍| 471/500 [1:39:26<04:58, 10.31s/it]

[I 2026-05-18 18:45:36,984] Trial 318 finished with value: 0.9495242809111589 and parameters: {'solver': 'saga', 'C': 4.367576593240255, 'l1_ratio': 0.3381867707855822, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013799918719209, 'max_iter': 3600}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  94%|█████████▍| 472/500 [1:39:31<04:07,  8.84s/it]

[I 2026-05-18 18:45:42,386] Trial 480 finished with value: 0.949581267185572 and parameters: {'solver': 'saga', 'C': 0.0008741930188495533, 'l1_ratio': 0.26941644483708205, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013182657944177048, 'max_iter': 3018}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  95%|█████████▍| 473/500 [1:39:35<03:17,  7.32s/it]

[I 2026-05-18 18:45:46,172] Trial 481 finished with value: 0.9495814194282574 and parameters: {'solver': 'saga', 'C': 0.0009073900831837106, 'l1_ratio': 0.2722840944367032, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013149405827205066, 'max_iter': 3408}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  95%|█████████▍| 474/500 [1:39:40<02:51,  6.59s/it]

[I 2026-05-18 18:45:51,046] Trial 479 finished with value: 0.9495683410361243 and parameters: {'solver': 'saga', 'C': 0.002639933473511489, 'l1_ratio': 0.3871744918443637, 'class_weight': None, 'fit_intercept': True, 'tol': 7.054362034912974e-05, 'max_iter': 3055}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  95%|█████████▌| 475/500 [1:39:52<03:27,  8.29s/it]

[I 2026-05-18 18:46:03,328] Trial 485 pruned.

Best trial: 168. Best value: 0.949582:  95%|█████████▌| 476/500 [1:39:54<02:34,  6.44s/it]

[I 2026-05-18 18:46:05,449] Trial 482 finished with value: 0.9495813143598075 and parameters: {'solver': 'saga', 'C': 0.0008740189898896493, 'l1_ratio': 0.2704943507102272, 'class_weight': None, 'fit_intercept': True, 'tol': 2.3959099326867615e-05, 'max_iter': 3054}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  95%|█████████▌| 477/500 [1:39:55<01:50,  4.81s/it]

[I 2026-05-18 18:46:06,442] Trial 483 finished with value: 0.9495806226616267 and parameters: {'solver': 'saga', 'C': 0.0012062814707877957, 'l1_ratio': 0.2810523520115488, 'class_weight': None, 'fit_intercept': True, 'tol': 8.898826655843923e-05, 'max_iter': 3394}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  96%|█████████▌| 478/500 [1:40:03<02:07,  5.80s/it]

[I 2026-05-18 18:46:14,560] Trial 484 finished with value: 0.9495808403176879 and parameters: {'solver': 'saga', 'C': 0.001226760127870592, 'l1_ratio': 0.298840264413178, 'class_weight': None, 'fit_intercept': True, 'tol': 8.944749118090927e-05, 'max_iter': 3089}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  96%|█████████▌| 479/500 [1:40:17<02:51,  8.16s/it]

[I 2026-05-18 18:46:28,225] Trial 486 finished with value: 0.9495757215940023 and parameters: {'solver': 'saga', 'C': 0.0006300330541406431, 'l1_ratio': 0.35780749335152967, 'class_weight': None, 'fit_intercept': True, 'tol': 9.20357006697088e-05, 'max_iter': 3150}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  96%|█████████▌| 480/500 [1:40:19<02:04,  6.25s/it]

[I 2026-05-18 18:46:30,001] Trial 487 finished with value: 0.9495758587281392 and parameters: {'solver': 'saga', 'C': 0.0006238320164662461, 'l1_ratio': 0.3558504416918711, 'class_weight': None, 'fit_intercept': True, 'tol': 9.053423866820271e-05, 'max_iter': 3555}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  96%|█████████▌| 481/500 [1:40:20<01:29,  4.72s/it]

[I 2026-05-18 18:46:31,178] Trial 488 finished with value: 0.9495770621472358 and parameters: {'solver': 'saga', 'C': 0.0006150223793553063, 'l1_ratio': 0.32235607758627843, 'class_weight': None, 'fit_intercept': True, 'tol': 9.678561934292498e-05, 'max_iter': 2900}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  96%|█████████▋| 482/500 [1:40:23<01:14,  4.16s/it]

[I 2026-05-18 18:46:33,994] Trial 67 finished with value: 0.9495252083006193 and parameters: {'solver': 'saga', 'C': 1.1267006384403757, 'l1_ratio': 0.2421570990793345, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5281778663487095e-06, 'max_iter': 3473}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  97%|█████████▋| 483/500 [1:40:29<01:19,  4.69s/it]

[I 2026-05-18 18:46:39,929] Trial 489 finished with value: 0.9495751620296998 and parameters: {'solver': 'saga', 'C': 0.0005944163875766082, 'l1_ratio': 0.3599653719557259, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011686303753305946, 'max_iter': 3234}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  97%|█████████▋| 484/500 [1:40:39<01:44,  6.52s/it]

[I 2026-05-18 18:46:50,713] Trial 491 finished with value: 0.9495665485573849 and parameters: {'solver': 'saga', 'C': 0.0003941127367673555, 'l1_ratio': 0.3202646979227186, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00048527617751491274, 'max_iter': 2923}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  97%|█████████▋| 485/500 [1:40:44<01:29,  5.99s/it]

[I 2026-05-18 18:46:55,472] Trial 490 finished with value: 0.9495672532432173 and parameters: {'solver': 'saga', 'C': 0.0004018676053238877, 'l1_ratio': 0.32186341251975376, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011037294401477571, 'max_iter': 3239}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  97%|█████████▋| 486/500 [1:40:45<01:03,  4.50s/it]

[I 2026-05-18 18:46:56,500] Trial 492 finished with value: 0.9495494727701642 and parameters: {'solver': 'saga', 'C': 0.00039830931068194627, 'l1_ratio': 0.04892029146956178, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011845670375180726, 'max_iter': 3241}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  97%|█████████▋| 487/500 [1:40:51<01:03,  4.85s/it]

[I 2026-05-18 18:47:02,154] Trial 493 finished with value: 0.9495734133461131 and parameters: {'solver': 'saga', 'C': 0.002050311889449032, 'l1_ratio': 0.33364238175424504, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011910832863287115, 'max_iter': 4935}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  98%|█████████▊| 488/500 [1:40:52<00:44,  3.74s/it]

[I 2026-05-18 18:47:03,326] Trial 494 finished with value: 0.949562014142386 and parameters: {'solver': 'saga', 'C': 0.0003686691025973154, 'l1_ratio': 0.32855910647425357, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016331922584671127, 'max_iter': 3327}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  98%|█████████▊| 489/500 [1:41:03<01:05,  5.92s/it]

[I 2026-05-18 18:47:14,312] Trial 495 finished with value: 0.9495718663025372 and parameters: {'solver': 'saga', 'C': 0.0021221008079947536, 'l1_ratio': 0.2434324289993082, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00016239292112472573, 'max_iter': 3336}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  98%|█████████▊| 490/500 [1:41:07<00:54,  5.42s/it]

[I 2026-05-18 18:47:18,590] Trial 496 finished with value: 0.9495734665553895 and parameters: {'solver': 'saga', 'C': 0.001958333295223436, 'l1_ratio': 0.29977593726478236, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015755251632036194, 'max_iter': 3865}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  98%|█████████▊| 491/500 [1:41:08<00:35,  3.89s/it]

[I 2026-05-18 18:47:18,900] Trial 497 finished with value: 0.9495719463538238 and parameters: {'solver': 'saga', 'C': 0.0020619494729641613, 'l1_ratio': 0.2465446788520771, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001620733574440695, 'max_iter': 3317}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  98%|█████████▊| 492/500 [1:41:13<00:34,  4.33s/it]

[I 2026-05-18 18:47:24,246] Trial 499 finished with value: 0.9495816138427398 and parameters: {'solver': 'saga', 'C': 0.0009141305312417677, 'l1_ratio': 0.30217255955316413, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015332526115608615, 'max_iter': 3682}. Best is trial 168 with value: 0.9495820845736207.

Best trial: 168. Best value: 0.949582:  99%|█████████▊| 493/500 [1:41:13<00:21,  3.11s/it]

[I 2026-05-18 18:47:24,510] Trial 498 finished with value: 0.9495770225145985 and parameters: {'solver': 'saga', 'C': 0.0013651608231249844, 'l1_ratio': 0.24240658726993086, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015058059707508286, 'max_iter': 3323}. Best is trial 168 with value: 0.9495820845736207.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 168. Best value: 0.949582:  99%|█████████▊| 493/500 [1:42:35<01:27, 12.49s/it]

KeyboardInterrupt:

In [ ]:
stacking_lg = LogisticRegression(**study.best_params).fit(X_train_enc, y_train.PitNextLap)

# Submission

In [ ]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [ ]:
submission['PitNextLap'] = stacking_lg.predict_proba(X_test)[:, 1]

In [ ]:
submission.to_csv('../data/submission/submission.csv', index=False)