# Imports

In [10]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config

from scipy.stats import entropy, rankdata
from scipy.special import logit, expit

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import StackingClassifier
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.inspection import permutation_importance
from sklearn.preprocessing import StandardScaler, RobustScaler
from sklearn.model_selection import StratifiedKFold

from feature_engine.selection import DropFeatures

## Utils

In [11]:
set_config(enable_metadata_routing=True)

In [12]:
class StackingFeatureEngineer(BaseEstimator, TransformerMixin):

    def __init__(
        self,
        add_rank_features=True,
        add_statistical_features=True,
        add_interaction_features=True,
        add_difference_features=True,
        add_entropy_features=True,
        add_threshold_features=True,
        confidence_threshold=0.9,
        uncertainty_low=0.4,
        uncertainty_high=0.6,
    ):

        self.add_rank_features = add_rank_features
        self.add_statistical_features = add_statistical_features
        self.add_interaction_features = add_interaction_features
        self.add_difference_features = add_difference_features
        self.add_entropy_features = add_entropy_features
        self.add_threshold_features = add_threshold_features

        self.confidence_threshold = confidence_threshold
        self.uncertainty_low = uncertainty_low
        self.uncertainty_high = uncertainty_high

    def fit(self, X, y=None):

        X = self._to_dataframe(X)

        self.feature_names_in_ = X.columns.tolist()

        return self

    def transform(self, X):

        X = self._to_dataframe(
            X,
            columns=getattr(self, "feature_names_in_", None)
        )

        features = []

        # =====================================================
        # FEATURES ORIGINAIS
        # =====================================================

        base_probs = X.copy()

        features.append(base_probs)

        # =====================================================
        # FEATURES ESTATÍSTICAS
        # =====================================================

        if self.add_statistical_features:

            stat_df = pd.DataFrame(index=X.index)

            stat_df["prob_mean"] = X.mean(axis=1)
            stat_df["prob_std"] = X.std(axis=1)
            stat_df["prob_min"] = X.min(axis=1)
            stat_df["prob_max"] = X.max(axis=1)
            stat_df["prob_range"] = (
                stat_df["prob_max"] -
                stat_df["prob_min"]
            )

            stat_df["prob_median"] = X.median(axis=1)

            features.append(stat_df)

        # =====================================================
        # ENTROPIA
        # =====================================================

        if self.add_entropy_features:

            ent_df = pd.DataFrame(index=X.index)

            probs_norm = (
                X.div(X.sum(axis=1) + 1e-12, axis=0)
            )

            ent_df["prediction_entropy"] = probs_norm.apply(
                lambda row: entropy(row + 1e-12),
                axis=1
            )

            features.append(ent_df)

        # =====================================================
        # RANK FEATURES
        # =====================================================

        if self.add_rank_features:

            rank_df = pd.DataFrame(index=X.index)

            ranks = np.apply_along_axis(
                rankdata,
                axis=1,
                arr=X.values
            )

            for i, col in enumerate(X.columns):

                rank_df[f"{col}_rank"] = ranks[:, i]

            features.append(rank_df)

        # =====================================================
        # AGREEMENT FEATURES
        # =====================================================

        vote_df = pd.DataFrame(index=X.index)

        preds = (X > 0.5).astype(int)

        vote_df["vote_sum"] = preds.sum(axis=1)
        vote_df["vote_mean"] = preds.mean(axis=1)

        vote_df["all_agree"] = (
            preds.nunique(axis=1) == 1
        ).astype(int)

        vote_df["disagreement"] = (
            preds.nunique(axis=1) > 1
        ).astype(int)

        features.append(vote_df)

        # =====================================================
        # THRESHOLD FEATURES
        # =====================================================

        if self.add_threshold_features:

            thresh_df = pd.DataFrame(index=X.index)

            thresh_df["high_conf_models"] = (
                X > self.confidence_threshold
            ).sum(axis=1)

            thresh_df["uncertain_models"] = (
                (
                    X > self.uncertainty_low
                ) &
                (
                    X < self.uncertainty_high
                )
            ).sum(axis=1)

            features.append(thresh_df)

        # =====================================================
        # INTERAÇÕES
        # =====================================================

        if self.add_interaction_features:

            inter_df = pd.DataFrame(index=X.index)

            cols = X.columns.tolist()

            for i in range(len(cols)):
                for j in range(i + 1, len(cols)):

                    c1 = cols[i]
                    c2 = cols[j]

                    inter_df[f"{c1}_x_{c2}"] = (
                        X[c1] * X[c2]
                    )

            features.append(inter_df)

        # =====================================================
        # DIFERENÇAS
        # =====================================================

        if self.add_difference_features:

            diff_df = pd.DataFrame(index=X.index)

            cols = X.columns.tolist()

            for i in range(len(cols)):
                for j in range(i + 1, len(cols)):

                    c1 = cols[i]
                    c2 = cols[j]

                    diff_df[f"{c1}_minus_{c2}"] = (
                        X[c1] - X[c2]
                    )

            features.append(diff_df)

        # =====================================================
        # CONCAT FINAL
        # =====================================================

        X_meta = pd.concat(features, axis=1)

        return X_meta

    @staticmethod
    def _to_dataframe(X, columns=None):

        if isinstance(X, pd.DataFrame):
            return X.copy()

        X = np.asarray(X)

        if columns is None:
            columns = [
                f"feature_{i}"
                for i in range(X.shape[1])
            ]

        return pd.DataFrame(X, columns=columns)

In [13]:
def get_logit(proba, eps=1e-15):
    proba = np.clip(proba, eps, 1 - eps)
    return logit(proba)

# Loading Dataset

In [14]:
X_train = pd.read_parquet('../data/processed/X_train_stacking2.parquet')
y_train = pd.read_parquet('../data/processed/y_train.parquet')

X_test = pd.read_parquet('../data/processed/X_test_stacking2.parquet')

In [15]:
X_train.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,ridge_logit,voting_lgbm_cat_xgb_hist_proba,voting_lg_ridge_proba,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba
0,0.802607,0.891870,0.895659,0.883947,0.808497,0.887454,0.500714,0.868510,0.716126,0.773266
1,0.649405,0.831360,0.829854,0.779541,0.689888,0.519966,0.335105,0.772514,0.636769,0.591885
2,0.505904,0.851809,0.751522,0.758911,0.558520,0.209855,0.136991,0.717012,0.546431,0.516648
3,0.001713,0.005910,0.007057,0.007298,0.002275,0.000000,-1.247050,0.005494,0.112073,0.001113
4,0.392205,0.565506,0.489033,0.482967,0.414144,0.297043,-0.094611,0.482416,0.445065,0.293469

In [16]:
X_test.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,ridge_logit,voting_lgbm_cat_xgb_hist_proba,voting_lg_ridge_proba,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,-1.272709,0.019849,-0.629264,0.006334
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,-0.626960,0.012173,-0.279447,0.003675
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,-1.335019,0.010304,-0.661186,0.003484
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.190133,0.444558,0.424415,0.238053
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.535153,0.939648,0.688728,0.895339

# Feature Engineering

## Feature Creation

In [21]:
X_train['ridge_proba'] = X_train['ridge_logit'].apply(expit)
X_test['ridge_proba'] = X_test['ridge_logit'].apply(expit)

X_train = X_train.drop(columns='ridge_logit')
X_test = X_test.drop(columns='ridge_logit')

In [22]:
sfe = StackingFeatureEngineer(
    add_rank_features=True,
    add_statistical_features=True,
    add_entropy_features=True,
    add_threshold_features=True,
    add_interaction_features=False,
    add_difference_features=False,
)

X_train_enc = sfe.fit_transform(X_train)
X_test_enc = sfe.transform(X_test)

In [23]:
# X_train_enc.to_parquet('../data/processed/X_train_stacking3.parquet')
# X_test_enc.to_parquet('../data/processed/X_test_stacking3.parquet')

In [59]:
X_test_enc.head()

,lgbm_proba,cat_proba,xgb_proba,hist_proba,lg_proba,knn_proba,voting_lgbm_cat_xgb_hist_proba,voting_lg_ridge_proba,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba,ridge_proba,...,voting_lgbm_cat_xgb_hist_proba_rank,voting_lg_ridge_proba_rank,stacking_lgbm_with_knn_and_voting_lg_ridge_and_voting_lgbm_cat_xgb_hist_proba_rank,ridge_proba_rank,vote_sum,vote_mean,all_agree,disagreement,high_conf_models,uncertain_models
0,0.004591,0.031986,0.022774,0.020057,0.006419,0.000000,0.019849,-0.629264,0.006334,0.218794,...,6.0,1.0,4.0,10.0,0,0.0,1,0,0,0
1,0.003032,0.011817,0.014957,0.018887,0.063872,0.117213,0.012173,-0.279447,0.003675,0.348200,...,5.0,1.0,3.0,10.0,0,0.0,1,0,0,0
2,0.003777,0.011641,0.014307,0.011497,0.004517,0.000000,0.010304,-0.661186,0.003484,0.208330,...,6.0,1.0,3.0,10.0,0,0.0,1,0,0,0
3,0.163131,0.544040,0.585898,0.485388,0.655870,0.099916,0.444558,0.424415,0.238053,0.547391,...,5.0,4.0,3.0,8.0,4,0.4,0,1,0,6
4,0.872172,0.967646,0.959451,0.959356,0.840450,1.000000,0.939648,0.688728,0.895339,0.630684,...,6.0,2.0,5.0,1.0,10,1.0,1,0,5,0

## Feature Scaling

## Feature Selection

In [47]:
model = make_pipeline(
    StandardScaler(),
    LogisticRegression(random_state=42, verbose=0, class_weight='balanced', max_iter=500)
).fit(X_train_enc, y_train.PitNextLap)

perm_result = permutation_importance(
    estimator=model, 
    X=X_train_enc, 
    y=y_train.PitNextLap, 
    n_jobs=-1, 
    scoring='roc_auc'
)

importance_df = pd.DataFrame({
    "feature": X_train_enc.columns.tolist(),
    "importance_mean": perm_result.importances_mean,
    "importance_std": perm_result.importances_std
}).sort_values(by="importance_mean", ascending=False)

features_to_drop = importance_df.query("importance_mean <= 0").feature.tolist()

In [48]:
features_to_drop

['vote_sum', 'vote_mean', 'prob_range', 'xgb_proba_rank']

# Machine Learning

In [49]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "C": trial.suggest_float("C", 1e-5, 100, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
        "max_iter": trial.suggest_int("max_iter", 1000, 5000)
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = make_pipeline(
            DropFeatures(features_to_drop),
            StandardScaler(),
            LogisticRegression(**params)
        ).fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)

study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_train_enc, y_train), n_trials=500, n_jobs=-1, show_progress_bar=True)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-19 17:37:39,293] A new study created in memory with name: no-name-2c1063e5-8438-4203-adb0-eef79065bf12
Best trial: 0. Best value: 0.949635:   0%|▏                                                                                                               | 1/500 [00:22<3:04:57, 22.24s/it]

[I 2026-05-19 17:38:01,530] Trial 0 finished with value: 0.9496345199692486 and parameters: {'solver': 'saga', 'C': 0.0438006845727291, 'l1_ratio': 0.30330229660956076, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002881125637601851, 'max_iter': 3247}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   0%|▍                                                                                                               | 2/500 [00:25<1:32:53, 11.19s/it]

[I 2026-05-19 17:38:04,989] Trial 11 finished with value: 0.9469541610253842 and parameters: {'solver': 'saga', 'C': 0.00027748082718853445, 'l1_ratio': 0.2563817309451887, 'class_weight': None, 'fit_intercept': False, 'tol': 0.000500742163251842, 'max_iter': 4510}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   1%|▋                                                                                                                 | 3/500 [00:27<55:44,  6.73s/it]

[I 2026-05-19 17:38:06,406] Trial 3 finished with value: 0.9491689094083888 and parameters: {'solver': 'saga', 'C': 0.0038358454657609945, 'l1_ratio': 0.6720869351020908, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0003912543939468418, 'max_iter': 3875}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   1%|▉                                                                                                                 | 4/500 [00:28<38:28,  4.65s/it]

[I 2026-05-19 17:38:07,874] Trial 10 finished with value: 0.9494936513876271 and parameters: {'solver': 'saga', 'C': 2.0676336089237143e-05, 'l1_ratio': 0.8772233690635736, 'class_weight': None, 'fit_intercept': False, 'tol': 4.429723533597965e-05, 'max_iter': 3270}. Best is trial 0 with value: 0.9496345199692486.
[I 2026-05-19 17:38:07,965] Trial 8 finished with value: 0.9496291473369955 and parameters: {'solver': 'saga', 'C': 0.003664163720931034, 'l1_ratio': 0.5777190529560372, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003141831228792828, 'max_iter': 2390}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   1%|█▎                                                                                                                | 6/500 [00:40<44:18,  5.38s/it]

[I 2026-05-19 17:38:19,933] Trial 15 pruned.

Best trial: 0. Best value: 0.949635:   1%|█▌                                                                                                                | 7/500 [00:49<51:46,  6.30s/it]

[I 2026-05-19 17:38:28,661] Trial 13 finished with value: 0.9496140829546708 and parameters: {'solver': 'saga', 'C': 9.244263065866935, 'l1_ratio': 0.3877178209070148, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.001253282671271311, 'max_iter': 3904}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   2%|█▊                                                                                                                | 8/500 [00:51<42:07,  5.14s/it]

[I 2026-05-19 17:38:30,834] Trial 6 finished with value: 0.9491228436839385 and parameters: {'solver': 'saga', 'C': 0.21313967972935693, 'l1_ratio': 0.38944626613375344, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.993274725554152e-06, 'max_iter': 2354}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   2%|██                                                                                                                | 9/500 [00:53<35:38,  4.36s/it]

[I 2026-05-19 17:38:33,236] Trial 14 finished with value: 0.9496174945327145 and parameters: {'solver': 'saga', 'C': 0.015890583735180343, 'l1_ratio': 0.943378210635399, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00028087986818444815, 'max_iter': 1664}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   2%|██▎                                                                                                              | 10/500 [00:55<29:17,  3.59s/it]

[I 2026-05-19 17:38:34,961] Trial 12 finished with value: 0.9491608546148187 and parameters: {'solver': 'saga', 'C': 3.25779392716787e-05, 'l1_ratio': 0.16979446949483556, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.347708911346596e-05, 'max_iter': 2105}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   2%|██▍                                                                                                              | 11/500 [00:56<22:47,  2.80s/it]

[I 2026-05-19 17:38:35,848] Trial 2 finished with value: 0.9491223730821922 and parameters: {'solver': 'saga', 'C': 0.30489361615457894, 'l1_ratio': 0.3979176778143584, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0014487112301478978, 'max_iter': 1089}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   2%|██▋                                                                                                              | 12/500 [01:12<53:14,  6.55s/it]

[I 2026-05-19 17:38:51,334] Trial 21 finished with value: 0.9496329613257778 and parameters: {'solver': 'saga', 'C': 1.2909546437104946, 'l1_ratio': 0.011184918410412137, 'class_weight': None, 'fit_intercept': True, 'tol': 0.009473136883033318, 'max_iter': 4708}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   3%|██▉                                                                                                              | 13/500 [01:14<44:10,  5.44s/it]

[I 2026-05-19 17:38:54,169] Trial 22 finished with value: 0.9496320618661283 and parameters: {'solver': 'saga', 'C': 0.13176545189076105, 'l1_ratio': 0.00524482831337536, 'class_weight': None, 'fit_intercept': True, 'tol': 0.005849248199696329, 'max_iter': 2672}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   3%|███▏                                                                                                             | 14/500 [01:15<33:11,  4.10s/it]

[I 2026-05-19 17:38:55,064] Trial 18 finished with value: 0.9491982241536837 and parameters: {'solver': 'saga', 'C': 0.002466137542729087, 'l1_ratio': 0.7176099793423255, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0002898612721320258, 'max_iter': 1272}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   3%|███▍                                                                                                             | 15/500 [01:17<27:20,  3.38s/it]

[I 2026-05-19 17:38:56,791] Trial 19 finished with value: 0.9496138691922397 and parameters: {'solver': 'saga', 'C': 6.9126524461618555, 'l1_ratio': 0.8326109343630392, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0008790020875574193, 'max_iter': 2656}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   3%|███▌                                                                                                             | 16/500 [01:22<30:31,  3.78s/it]

[I 2026-05-19 17:39:01,514] Trial 17 finished with value: 0.9495554406054652 and parameters: {'solver': 'saga', 'C': 0.00024227974251403656, 'l1_ratio': 0.6625051697037938, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.3524646785577177e-06, 'max_iter': 1006}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   3%|███▊                                                                                                             | 17/500 [01:29<38:22,  4.77s/it]

[I 2026-05-19 17:39:08,589] Trial 23 finished with value: 0.9496289511188175 and parameters: {'solver': 'saga', 'C': 41.9888415333103, 'l1_ratio': 0.01785653759759856, 'class_weight': None, 'fit_intercept': True, 'tol': 0.009239125677424421, 'max_iter': 4986}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   4%|████                                                                                                             | 18/500 [01:32<33:27,  4.16s/it]

[I 2026-05-19 17:39:11,322] Trial 24 finished with value: 0.9496304428994868 and parameters: {'solver': 'saga', 'C': 10.890721448936583, 'l1_ratio': 0.011001658406423372, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00930912679503645, 'max_iter': 4858}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   4%|████▎                                                                                                            | 19/500 [01:33<25:56,  3.24s/it]

[I 2026-05-19 17:39:12,411] Trial 25 finished with value: 0.9496285492560578 and parameters: {'solver': 'saga', 'C': 10.026481029680221, 'l1_ratio': 0.014986769567426363, 'class_weight': None, 'fit_intercept': True, 'tol': 0.006969163201777663, 'max_iter': 4961}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   4%|████▌                                                                                                            | 20/500 [01:35<23:43,  2.96s/it]

[I 2026-05-19 17:39:14,739] Trial 26 finished with value: 0.9496312975808383 and parameters: {'solver': 'saga', 'C': 89.06328291203099, 'l1_ratio': 0.0634126901260173, 'class_weight': None, 'fit_intercept': True, 'tol': 0.007256721988021393, 'max_iter': 4964}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   4%|████▋                                                                                                            | 21/500 [01:35<17:28,  2.19s/it]

[I 2026-05-19 17:39:15,104] Trial 20 finished with value: 0.9496329778542656 and parameters: {'solver': 'saga', 'C': 0.004980847001124956, 'l1_ratio': 0.34730061024025904, 'class_weight': None, 'fit_intercept': True, 'tol': 6.495490121262312e-06, 'max_iter': 4384}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   4%|████▉                                                                                                            | 22/500 [01:38<17:50,  2.24s/it]

[I 2026-05-19 17:39:17,470] Trial 27 finished with value: 0.9496265611472164 and parameters: {'solver': 'saga', 'C': 1.5209643092187524, 'l1_ratio': 0.023290923556392566, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00967298491073405, 'max_iter': 4752}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   5%|█████▏                                                                                                           | 23/500 [01:49<38:22,  4.83s/it]

[I 2026-05-19 17:39:28,340] Trial 28 finished with value: 0.9496314146707642 and parameters: {'solver': 'saga', 'C': 1.7462158076760337, 'l1_ratio': 0.1277110117532846, 'class_weight': None, 'fit_intercept': True, 'tol': 0.003667851895116014, 'max_iter': 4437}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   5%|█████▍                                                                                                           | 24/500 [01:50<29:31,  3.72s/it]

[I 2026-05-19 17:39:29,479] Trial 29 finished with value: 0.949630535595541 and parameters: {'solver': 'saga', 'C': 1.496852129688564, 'l1_ratio': 0.19533021979877147, 'class_weight': None, 'fit_intercept': True, 'tol': 0.003719842397909577, 'max_iter': 4398}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   5%|█████▋                                                                                                           | 25/500 [01:50<22:18,  2.82s/it]

[I 2026-05-19 17:39:30,193] Trial 7 pruned.

Best trial: 0. Best value: 0.949635:   5%|█████▉                                                                                                           | 26/500 [01:52<18:38,  2.36s/it]

[I 2026-05-19 17:39:31,484] Trial 30 finished with value: 0.9496297909145731 and parameters: {'solver': 'saga', 'C': 1.1289103466740555, 'l1_ratio': 0.1660688633722685, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0031052742134005116, 'max_iter': 4396}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 0. Best value: 0.949635:   5%|██████                                                                                                           | 27/500 [01:55<21:02,  2.67s/it]

[I 2026-05-19 17:39:34,875] Trial 31 finished with value: 0.9496314073496365 and parameters: {'solver': 'saga', 'C': 1.0130546619065652, 'l1_ratio': 0.22424127791981063, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00266987005301633, 'max_iter': 4219}. Best is trial 0 with value: 0.9496345199692486.

Best trial: 33. Best value: 0.949635:   6%|██████▎                                                                                                         | 28/500 [02:12<54:24,  6.92s/it]

[I 2026-05-19 17:39:51,703] Trial 33 finished with value: 0.9496349562375673 and parameters: {'solver': 'saga', 'C': 0.026622393040788984, 'l1_ratio': 0.2707993573371409, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8218515956205516e-05, 'max_iter': 4238}. Best is trial 33 with value: 0.9496349562375673.

Best trial: 33. Best value: 0.949635:   6%|██████▍                                                                                                       | 29/500 [02:23<1:04:17,  8.19s/it]

[I 2026-05-19 17:40:02,858] Trial 34 finished with value: 0.9496346592071181 and parameters: {'solver': 'saga', 'C': 0.03136977888282334, 'l1_ratio': 0.2853629516288252, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3155600400640489e-05, 'max_iter': 4202}. Best is trial 33 with value: 0.9496349562375673.

Best trial: 33. Best value: 0.949635:   6%|██████▋                                                                                                         | 30/500 [02:25<48:56,  6.25s/it]

[I 2026-05-19 17:40:04,578] Trial 35 finished with value: 0.9496347086630224 and parameters: {'solver': 'saga', 'C': 0.03477009520629691, 'l1_ratio': 0.2908865471671874, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1740365619765338e-05, 'max_iter': 3987}. Best is trial 33 with value: 0.9496349562375673.

Best trial: 36. Best value: 0.949635:   6%|██████▉                                                                                                         | 31/500 [02:26<35:59,  4.60s/it]

[I 2026-05-19 17:40:05,347] Trial 36 finished with value: 0.9496349845319525 and parameters: {'solver': 'saga', 'C': 0.022897685947476744, 'l1_ratio': 0.2812870732173657, 'class_weight': None, 'fit_intercept': True, 'tol': 1.079649820277571e-05, 'max_iter': 4191}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   6%|███████▏                                                                                                        | 32/500 [02:31<37:02,  4.75s/it]

[I 2026-05-19 17:40:10,432] Trial 38 finished with value: 0.94963459413556 and parameters: {'solver': 'saga', 'C': 0.030446484282960432, 'l1_ratio': 0.3073551494208504, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2111127069427405e-05, 'max_iter': 3467}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   7%|███████▍                                                                                                        | 33/500 [02:35<35:56,  4.62s/it]

[I 2026-05-19 17:40:14,742] Trial 37 finished with value: 0.9496346349404924 and parameters: {'solver': 'saga', 'C': 0.019921892309675636, 'l1_ratio': 0.2955662464973869, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1128880428687627e-06, 'max_iter': 3966}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   7%|███████▌                                                                                                        | 34/500 [02:48<55:41,  7.17s/it]

[I 2026-05-19 17:40:27,867] Trial 39 finished with value: 0.9496346123579176 and parameters: {'solver': 'saga', 'C': 0.03237072426223645, 'l1_ratio': 0.29869928741500745, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1066501457250532e-05, 'max_iter': 3350}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   7%|███████▋                                                                                                      | 35/500 [02:58<1:02:08,  8.02s/it]

[I 2026-05-19 17:40:37,864] Trial 40 finished with value: 0.9496326291085427 and parameters: {'solver': 'saga', 'C': 0.06687022873990636, 'l1_ratio': 0.31073425186810555, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4972741206174188e-05, 'max_iter': 3481}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   7%|████████                                                                                                        | 36/500 [03:01<49:20,  6.38s/it]

[I 2026-05-19 17:40:40,431] Trial 41 finished with value: 0.949633998291368 and parameters: {'solver': 'saga', 'C': 0.04450741861680106, 'l1_ratio': 0.3012891700089141, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7234414269530472e-05, 'max_iter': 3429}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   7%|████████▎                                                                                                       | 37/500 [03:01<36:12,  4.69s/it]

[I 2026-05-19 17:40:41,174] Trial 42 finished with value: 0.9496345178433959 and parameters: {'solver': 'saga', 'C': 0.030871885121570474, 'l1_ratio': 0.3186724496823686, 'class_weight': None, 'fit_intercept': True, 'tol': 1.55553629300411e-05, 'max_iter': 4083}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   8%|████████▌                                                                                                       | 38/500 [03:08<40:32,  5.27s/it]

[I 2026-05-19 17:40:47,784] Trial 44 finished with value: 0.9496334860242376 and parameters: {'solver': 'saga', 'C': 0.03787348931653704, 'l1_ratio': 0.4624995513958666, 'class_weight': None, 'fit_intercept': True, 'tol': 2.215530233888905e-05, 'max_iter': 4076}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   8%|████████▋                                                                                                       | 39/500 [03:14<41:07,  5.35s/it]

[I 2026-05-19 17:40:53,336] Trial 43 finished with value: 0.9496278565706548 and parameters: {'solver': 'saga', 'C': 0.01629381967762395, 'l1_ratio': 0.4795890073458168, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5850487680497358e-06, 'max_iter': 4014}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   8%|████████▉                                                                                                       | 40/500 [03:19<42:17,  5.52s/it]

[I 2026-05-19 17:40:59,234] Trial 48 pruned.

Best trial: 36. Best value: 0.949635:   8%|█████████▏                                                                                                      | 41/500 [03:23<38:48,  5.07s/it]

[I 2026-05-19 17:41:03,273] Trial 45 finished with value: 0.9496323423202497 and parameters: {'solver': 'saga', 'C': 0.07784554605272512, 'l1_ratio': 0.40969512439355027, 'class_weight': None, 'fit_intercept': True, 'tol': 2.7421653833212192e-05, 'max_iter': 4126}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   8%|█████████▍                                                                                                      | 42/500 [03:26<32:20,  4.24s/it]

[I 2026-05-19 17:41:05,559] Trial 49 pruned.

Best trial: 36. Best value: 0.949635:   9%|█████████▋                                                                                                      | 43/500 [03:31<35:33,  4.67s/it]

[I 2026-05-19 17:41:11,217] Trial 46 finished with value: 0.9496281254141742 and parameters: {'solver': 'saga', 'C': 0.01113485046581552, 'l1_ratio': 0.43679568743005626, 'class_weight': None, 'fit_intercept': True, 'tol': 2.86849260956678e-05, 'max_iter': 4117}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   9%|█████████▊                                                                                                      | 44/500 [03:38<40:52,  5.38s/it]

[I 2026-05-19 17:41:18,269] Trial 47 finished with value: 0.9496273475152259 and parameters: {'solver': 'saga', 'C': 0.011297347869884266, 'l1_ratio': 0.4616060546501002, 'class_weight': None, 'fit_intercept': True, 'tol': 4.160409897382592e-06, 'max_iter': 4122}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   9%|██████████                                                                                                      | 45/500 [03:40<32:22,  4.27s/it]

[I 2026-05-19 17:41:19,953] Trial 4 finished with value: 0.9496301347729492 and parameters: {'solver': 'saga', 'C': 1.361711145976424, 'l1_ratio': 0.2934882058972521, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00027043838044705343, 'max_iter': 4296}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   9%|██████████                                                                                                    | 46/500 [04:27<2:08:41, 17.01s/it]

[I 2026-05-19 17:42:06,687] Trial 50 finished with value: 0.9491220389599654 and parameters: {'solver': 'saga', 'C': 0.44504589891400037, 'l1_ratio': 0.40025696549617296, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 3.701074428747347e-05, 'max_iter': 3771}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:   9%|██████████▎                                                                                                   | 47/500 [04:52<2:26:28, 19.40s/it]

[I 2026-05-19 17:42:31,662] Trial 57 finished with value: 0.9496345770206396 and parameters: {'solver': 'saga', 'C': 0.0008715754331343867, 'l1_ratio': 0.24732023320196972, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000146957183651473, 'max_iter': 3158}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 36. Best value: 0.949635:  10%|██████████▌                                                                                                   | 48/500 [05:23<2:52:23, 22.88s/it]

[I 2026-05-19 17:43:02,679] Trial 58 finished with value: 0.949614767931695 and parameters: {'solver': 'saga', 'C': 0.29265019272329157, 'l1_ratio': 0.5358988521715764, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 9.534195665299099e-05, 'max_iter': 4584}. Best is trial 36 with value: 0.9496349845319525.

Best trial: 59. Best value: 0.949635:  10%|██████████▊                                                                                                   | 49/500 [05:59<3:22:11, 26.90s/it]

[I 2026-05-19 17:43:38,950] Trial 59 finished with value: 0.949634990877135 and parameters: {'solver': 'saga', 'C': 0.0021733152546806007, 'l1_ratio': 0.11480220564599453, 'class_weight': None, 'fit_intercept': True, 'tol': 3.928961506515511e-06, 'max_iter': 3885}. Best is trial 59 with value: 0.949634990877135.

Best trial: 59. Best value: 0.949635:  10%|███████████                                                                                                   | 50/500 [06:00<2:22:22, 18.98s/it]

[I 2026-05-19 17:43:39,452] Trial 54 finished with value: 0.9496144056749 and parameters: {'solver': 'saga', 'C': 0.4044808738875746, 'l1_ratio': 0.26008872897966884, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.892492029161258e-06, 'max_iter': 4584}. Best is trial 59 with value: 0.949634990877135.

Best trial: 59. Best value: 0.949635:  10%|███████████▏                                                                                                  | 51/500 [06:36<3:00:58, 24.18s/it]

[I 2026-05-19 17:44:15,775] Trial 61 finished with value: 0.9495833176642087 and parameters: {'solver': 'saga', 'C': 0.0004211608379691949, 'l1_ratio': 0.11009773721682929, 'class_weight': None, 'fit_intercept': True, 'tol': 7.95767197756707e-06, 'max_iter': 2963}. Best is trial 59 with value: 0.949634990877135.

Best trial: 59. Best value: 0.949635:  10%|███████████▍                                                                                                  | 52/500 [06:38<2:10:01, 17.41s/it]

[I 2026-05-19 17:44:17,392] Trial 60 finished with value: 0.9495477775609913 and parameters: {'solver': 'saga', 'C': 0.0003053797276959236, 'l1_ratio': 0.10425417677233964, 'class_weight': None, 'fit_intercept': True, 'tol': 5.725116186678677e-06, 'max_iter': 4602}. Best is trial 59 with value: 0.949634990877135.

Best trial: 59. Best value: 0.949635:  11%|███████████▋                                                                                                  | 53/500 [06:45<1:46:19, 14.27s/it]

[I 2026-05-19 17:44:24,341] Trial 56 finished with value: 0.949614381437558 and parameters: {'solver': 'saga', 'C': 0.41117165894847346, 'l1_ratio': 0.24243249079928036, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00013903099514594989, 'max_iter': 3076}. Best is trial 59 with value: 0.949634990877135.

Best trial: 62. Best value: 0.949636:  11%|███████████▉                                                                                                  | 54/500 [07:12<2:15:56, 18.29s/it]

[I 2026-05-19 17:44:52,001] Trial 62 finished with value: 0.949635511218127 and parameters: {'solver': 'saga', 'C': 0.0019101647051077495, 'l1_ratio': 0.35749066208652547, 'class_weight': None, 'fit_intercept': True, 'tol': 2.7207133900447497e-06, 'max_iter': 3975}. Best is trial 62 with value: 0.949635511218127.

Best trial: 62. Best value: 0.949636:  11%|████████████                                                                                                  | 55/500 [07:15<1:41:47, 13.73s/it]

[I 2026-05-19 17:44:55,060] Trial 63 finished with value: 0.9496344374144462 and parameters: {'solver': 'saga', 'C': 0.0024445716194729547, 'l1_ratio': 0.3576328475059304, 'class_weight': None, 'fit_intercept': True, 'tol': 2.822185622512262e-06, 'max_iter': 3908}. Best is trial 62 with value: 0.949635511218127.

Best trial: 62. Best value: 0.949636:  11%|████████████▎                                                                                                 | 56/500 [07:26<1:35:00, 12.84s/it]

[I 2026-05-19 17:45:05,851] Trial 64 finished with value: 0.9496344261905033 and parameters: {'solver': 'saga', 'C': 0.00244177767291648, 'l1_ratio': 0.3581255915284125, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0657784844693936e-06, 'max_iter': 3893}. Best is trial 62 with value: 0.949635511218127.

Best trial: 62. Best value: 0.949636:  11%|████████████▌                                                                                                 | 57/500 [07:32<1:20:06, 10.85s/it]

[I 2026-05-19 17:45:12,054] Trial 55 finished with value: 0.949614437882692 and parameters: {'solver': 'saga', 'C': 0.3735391636850595, 'l1_ratio': 0.2420666733703402, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.810869916539954e-06, 'max_iter': 3112}. Best is trial 62 with value: 0.949635511218127.

Best trial: 62. Best value: 0.949636:  12%|████████████▊                                                                                                 | 58/500 [07:45<1:23:39, 11.36s/it]

[I 2026-05-19 17:45:24,592] Trial 67 pruned.

Best trial: 62. Best value: 0.949636:  12%|████████████▉                                                                                                 | 59/500 [07:53<1:16:41, 10.43s/it]

[I 2026-05-19 17:45:32,873] Trial 65 finished with value: 0.9496349560170003 and parameters: {'solver': 'saga', 'C': 0.002136917745044063, 'l1_ratio': 0.34523759483212596, 'class_weight': None, 'fit_intercept': True, 'tol': 2.6691921645742906e-06, 'max_iter': 3856}. Best is trial 62 with value: 0.949635511218127.

Best trial: 62. Best value: 0.949636:  12%|█████████████▍                                                                                                  | 60/500 [07:55<56:50,  7.75s/it]

[I 2026-05-19 17:45:34,361] Trial 68 pruned.

Best trial: 62. Best value: 0.949636:  12%|█████████████▋                                                                                                  | 61/500 [07:56<41:51,  5.72s/it]

[I 2026-05-19 17:45:35,352] Trial 66 finished with value: 0.9495952761523989 and parameters: {'solver': 'saga', 'C': 8.990217341892258e-05, 'l1_ratio': 0.3532288076483185, 'class_weight': None, 'fit_intercept': True, 'tol': 3.379117756866228e-06, 'max_iter': 4284}. Best is trial 62 with value: 0.949635511218127.

Best trial: 62. Best value: 0.949636:  12%|█████████████▉                                                                                                  | 62/500 [08:05<49:20,  6.76s/it]

[I 2026-05-19 17:45:44,523] Trial 53 finished with value: 0.9496305843850331 and parameters: {'solver': 'saga', 'C': 0.34928418385074655, 'l1_ratio': 0.23783728179101196, 'class_weight': None, 'fit_intercept': True, 'tol': 4.5902708937807595e-06, 'max_iter': 3137}. Best is trial 62 with value: 0.949635511218127.

Best trial: 70. Best value: 0.949638:  13%|█████████████▊                                                                                                | 63/500 [08:31<1:31:44, 12.60s/it]

[I 2026-05-19 17:46:10,740] Trial 70 finished with value: 0.9496379673274298 and parameters: {'solver': 'saga', 'C': 0.0009022776729452396, 'l1_ratio': 0.5674486002179352, 'class_weight': None, 'fit_intercept': True, 'tol': 2.7678888251867223e-06, 'max_iter': 3588}. Best is trial 70 with value: 0.9496379673274298.

Best trial: 70. Best value: 0.949638:  13%|██████████████                                                                                                | 64/500 [08:34<1:10:40,  9.73s/it]

[I 2026-05-19 17:46:13,773] Trial 71 finished with value: 0.94963063735846 and parameters: {'solver': 'saga', 'C': 0.004965234510448156, 'l1_ratio': 0.5188793060268305, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8941035560603693e-06, 'max_iter': 3803}. Best is trial 70 with value: 0.9496379673274298.

Best trial: 70. Best value: 0.949638:  13%|██████████████▌                                                                                                 | 65/500 [08:34<50:24,  6.95s/it]

[I 2026-05-19 17:46:14,255] Trial 72 finished with value: 0.9496359039065065 and parameters: {'solver': 'saga', 'C': 0.004860153664632641, 'l1_ratio': 0.1475549791553647, 'class_weight': None, 'fit_intercept': True, 'tol': 2.079144899013642e-06, 'max_iter': 3812}. Best is trial 70 with value: 0.9496379673274298.

Best trial: 70. Best value: 0.949638:  13%|██████████████▊                                                                                                 | 66/500 [08:44<55:31,  7.68s/it]

[I 2026-05-19 17:46:23,625] Trial 51 finished with value: 0.94912165961058 and parameters: {'solver': 'saga', 'C': 0.3987647379654602, 'l1_ratio': 0.10575102073483714, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 4.0255954218662405e-06, 'max_iter': 3095}. Best is trial 70 with value: 0.9496379673274298.

Best trial: 70. Best value: 0.949638:  13%|███████████████                                                                                                 | 67/500 [08:46<42:50,  5.94s/it]

[I 2026-05-19 17:46:25,498] Trial 73 finished with value: 0.9496353778363481 and parameters: {'solver': 'saga', 'C': 0.005885962530466029, 'l1_ratio': 0.14678389720992538, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7759179728829607e-06, 'max_iter': 3744}. Best is trial 70 with value: 0.9496379673274298.

Best trial: 70. Best value: 0.949638:  14%|███████████████▏                                                                                                | 68/500 [08:53<44:51,  6.23s/it]

[I 2026-05-19 17:46:32,414] Trial 52 finished with value: 0.9496304383100143 and parameters: {'solver': 'saga', 'C': 0.42057689927627734, 'l1_ratio': 0.24616417172411106, 'class_weight': None, 'fit_intercept': True, 'tol': 3.4725625925684047e-06, 'max_iter': 3783}. Best is trial 70 with value: 0.9496379673274298.

Best trial: 74. Best value: 0.949642:  14%|███████████████▏                                                                                              | 69/500 [09:11<1:11:21,  9.93s/it]

[I 2026-05-19 17:46:50,992] Trial 74 finished with value: 0.9496418237060705 and parameters: {'solver': 'saga', 'C': 0.0011645315107332503, 'l1_ratio': 0.536463546766197, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7505236362547811e-06, 'max_iter': 3573}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  14%|███████████████▋                                                                                                | 70/500 [09:12<51:34,  7.20s/it]

[I 2026-05-19 17:46:51,801] Trial 75 finished with value: 0.9496273884013323 and parameters: {'solver': 'saga', 'C': 0.0009059602963641503, 'l1_ratio': 0.6863171425368838, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0625426684820146e-06, 'max_iter': 3566}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  14%|███████████████▉                                                                                                | 71/500 [09:14<40:58,  5.73s/it]

[I 2026-05-19 17:46:54,096] Trial 76 finished with value: 0.9496378945624393 and parameters: {'solver': 'saga', 'C': 0.0012203256976454563, 'l1_ratio': 0.6122713603159062, 'class_weight': None, 'fit_intercept': True, 'tol': 1.903330867281896e-06, 'max_iter': 3637}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  14%|████████████████▏                                                                                               | 72/500 [09:25<50:40,  7.10s/it]

[I 2026-05-19 17:47:04,417] Trial 77 finished with value: 0.9496404833234278 and parameters: {'solver': 'saga', 'C': 0.0010434207078409503, 'l1_ratio': 0.5673012996461035, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7284801935096996e-06, 'max_iter': 3584}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  15%|████████████████▎                                                                                               | 73/500 [09:27<41:04,  5.77s/it]

[I 2026-05-19 17:47:07,085] Trial 78 finished with value: 0.9496221001956094 and parameters: {'solver': 'saga', 'C': 0.0009021201856538893, 'l1_ratio': 0.15089681002054509, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0891170873810897e-06, 'max_iter': 3638}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  15%|████████████████▌                                                                                               | 74/500 [09:33<39:58,  5.63s/it]

[I 2026-05-19 17:47:12,390] Trial 79 finished with value: 0.9496292498579983 and parameters: {'solver': 'saga', 'C': 0.0007963420223347662, 'l1_ratio': 0.6261418762006311, 'class_weight': None, 'fit_intercept': True, 'tol': 2.104518826314292e-06, 'max_iter': 3581}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  15%|████████████████▌                                                                                             | 75/500 [09:51<1:08:04,  9.61s/it]

[I 2026-05-19 17:47:31,284] Trial 81 finished with value: 0.9496411928833755 and parameters: {'solver': 'saga', 'C': 0.0011079390593658582, 'l1_ratio': 0.5635336141418938, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5599235420069897e-06, 'max_iter': 3278}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  15%|█████████████████                                                                                               | 76/500 [09:52<49:16,  6.97s/it]

[I 2026-05-19 17:47:32,099] Trial 80 finished with value: 0.9496223244806672 and parameters: {'solver': 'saga', 'C': 0.0009380425609038161, 'l1_ratio': 0.7288331725829952, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5391268914095894e-06, 'max_iter': 3572}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  16%|█████████████████▍                                                                                              | 78/500 [09:55<28:36,  4.07s/it]

[I 2026-05-19 17:47:34,994] Trial 9 finished with value: 0.9491215133741976 and parameters: {'solver': 'saga', 'C': 0.7671642416533436, 'l1_ratio': 0.20106517918232303, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 9.335254535989579e-06, 'max_iter': 1762}. Best is trial 74 with value: 0.9496418237060705.
[I 2026-05-19 17:47:35,134] Trial 82 finished with value: 0.9496366940417689 and parameters: {'solver': 'saga', 'C': 0.0014074099762949339, 'l1_ratio': 0.6176662654582317, 'class_weight': None, 'fit_intercept': True, 'tol': 1.442340361591117e-06, 'max_iter': 3304}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  16%|█████████████████▋                                                                                              | 79/500 [10:07<43:50,  6.25s/it]

[I 2026-05-19 17:47:46,464] Trial 83 finished with value: 0.9496248367813637 and parameters: {'solver': 'saga', 'C': 0.0005569610167498058, 'l1_ratio': 0.5954259059268182, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4534633315101688e-06, 'max_iter': 3350}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  16%|█████████████████▉                                                                                              | 80/500 [10:09<36:06,  5.16s/it]

[I 2026-05-19 17:47:49,089] Trial 84 finished with value: 0.9496233571190457 and parameters: {'solver': 'saga', 'C': 0.0005024060692889062, 'l1_ratio': 0.6066531292548073, 'class_weight': None, 'fit_intercept': True, 'tol': 1.575699274612723e-06, 'max_iter': 3284}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  16%|██████████████████▏                                                                                             | 81/500 [10:10<26:59,  3.87s/it]

[I 2026-05-19 17:47:49,933] Trial 32 finished with value: 0.9496302099258669 and parameters: {'solver': 'saga', 'C': 1.110366989604568, 'l1_ratio': 0.25929519045848687, 'class_weight': None, 'fit_intercept': True, 'tol': 2.024562463268896e-05, 'max_iter': 4408}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  16%|██████████████████▎                                                                                             | 82/500 [10:14<26:41,  3.83s/it]

[I 2026-05-19 17:47:53,675] Trial 85 finished with value: 0.9496263730190764 and parameters: {'solver': 'saga', 'C': 0.0004997668522643783, 'l1_ratio': 0.5859690072159736, 'class_weight': None, 'fit_intercept': True, 'tol': 1.5681902812300896e-06, 'max_iter': 3337}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  17%|██████████████████▌                                                                                             | 83/500 [10:22<35:49,  5.16s/it]

[I 2026-05-19 17:48:01,936] Trial 1 finished with value: 0.9496299891850425 and parameters: {'solver': 'saga', 'C': 8.64093603092229, 'l1_ratio': 0.6236378587388985, 'class_weight': None, 'fit_intercept': True, 'tol': 9.348628878189177e-05, 'max_iter': 1837}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  17%|██████████████████▊                                                                                             | 84/500 [10:29<39:32,  5.70s/it]

[I 2026-05-19 17:48:08,914] Trial 69 finished with value: 0.9496315006945231 and parameters: {'solver': 'saga', 'C': 0.13013525246717553, 'l1_ratio': 0.14719384433890675, 'class_weight': None, 'fit_intercept': True, 'tol': 2.9171374656145477e-06, 'max_iter': 3627}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  17%|███████████████████                                                                                             | 85/500 [10:33<35:35,  5.15s/it]

[I 2026-05-19 17:48:12,762] Trial 87 finished with value: 0.949636977718645 and parameters: {'solver': 'saga', 'C': 0.001589186006023887, 'l1_ratio': 0.5687707407313642, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3824146898263367e-06, 'max_iter': 3291}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  17%|███████████████████▎                                                                                            | 86/500 [10:35<28:57,  4.20s/it]

[I 2026-05-19 17:48:14,743] Trial 86 finished with value: 0.949626184612191 and parameters: {'solver': 'saga', 'C': 0.00042107067555912, 'l1_ratio': 0.5830439121239289, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4440770819232816e-06, 'max_iter': 2802}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  17%|███████████████████▍                                                                                            | 87/500 [10:37<24:36,  3.57s/it]

[I 2026-05-19 17:48:16,866] Trial 88 finished with value: 0.9496248155646215 and parameters: {'solver': 'saga', 'C': 0.00040129928918911995, 'l1_ratio': 0.5866090198571893, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3406199407337e-06, 'max_iter': 3268}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  18%|███████████████████▋                                                                                            | 88/500 [10:38<19:19,  2.81s/it]

[I 2026-05-19 17:48:17,895] Trial 89 finished with value: 0.9496271601928404 and parameters: {'solver': 'saga', 'C': 0.0005433497625035039, 'l1_ratio': 0.5769267467634914, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3472878988965362e-06, 'max_iter': 3292}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  18%|███████████████████▉                                                                                            | 89/500 [10:48<32:54,  4.80s/it]

[I 2026-05-19 17:48:27,344] Trial 90 finished with value: 0.949635803071259 and parameters: {'solver': 'saga', 'C': 0.0016936680393177647, 'l1_ratio': 0.580061707804528, 'class_weight': None, 'fit_intercept': True, 'tol': 2.546205006559767e-06, 'max_iter': 2852}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  18%|████████████████████▏                                                                                           | 90/500 [10:54<35:22,  5.18s/it]

[I 2026-05-19 17:48:33,399] Trial 91 finished with value: 0.9496373025710231 and parameters: {'solver': 'saga', 'C': 0.0015728645909223484, 'l1_ratio': 0.5582153841972874, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2407275456975565e-06, 'max_iter': 2860}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  18%|████████████████████▍                                                                                           | 91/500 [10:55<27:50,  4.08s/it]

[I 2026-05-19 17:48:34,937] Trial 92 finished with value: 0.9496205104766803 and parameters: {'solver': 'saga', 'C': 0.0001769099037034436, 'l1_ratio': 0.5817167239359226, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2013898949949383e-06, 'max_iter': 2806}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  18%|████████████████████▌                                                                                           | 92/500 [10:58<25:25,  3.74s/it]

[I 2026-05-19 17:48:37,860] Trial 93 finished with value: 0.9496382073427562 and parameters: {'solver': 'saga', 'C': 0.001532354162334222, 'l1_ratio': 0.537403689412282, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1224025804337978e-06, 'max_iter': 2906}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  19%|████████████████████▊                                                                                           | 93/500 [11:08<37:06,  5.47s/it]

[I 2026-05-19 17:48:47,386] Trial 94 finished with value: 0.9496394865983705 and parameters: {'solver': 'saga', 'C': 0.0013479084637841648, 'l1_ratio': 0.5513048985249492, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1258938542090598e-06, 'max_iter': 2762}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  19%|█████████████████████                                                                                           | 94/500 [11:15<40:25,  5.97s/it]

[I 2026-05-19 17:48:54,528] Trial 95 finished with value: 0.9496388020763906 and parameters: {'solver': 'saga', 'C': 0.0014146985488692591, 'l1_ratio': 0.5558276177389112, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0092444032696598e-06, 'max_iter': 2884}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  19%|█████████████████████▎                                                                                          | 95/500 [11:15<29:01,  4.30s/it]

[I 2026-05-19 17:48:54,928] Trial 96 finished with value: 0.9496386852740105 and parameters: {'solver': 'saga', 'C': 0.0014567050428280044, 'l1_ratio': 0.5439520812562433, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2141613277041245e-06, 'max_iter': 2922}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  19%|█████████████████████▌                                                                                          | 96/500 [11:19<28:56,  4.30s/it]

[I 2026-05-19 17:48:59,214] Trial 97 finished with value: 0.9496402114629701 and parameters: {'solver': 'saga', 'C': 0.0012652168715502421, 'l1_ratio': 0.5532911315647915, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0152451316019706e-06, 'max_iter': 3409}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  19%|█████████████████████▋                                                                                          | 97/500 [11:21<22:53,  3.41s/it]

[I 2026-05-19 17:49:00,551] Trial 99 finished with value: 0.9496380814392149 and parameters: {'solver': 'saga', 'C': 0.001514731200613271, 'l1_ratio': 0.5481287903531342, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0579884309526715e-06, 'max_iter': 3414}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  20%|█████████████████████▉                                                                                          | 98/500 [11:22<18:11,  2.71s/it]

[I 2026-05-19 17:49:01,635] Trial 98 finished with value: 0.9496390498255348 and parameters: {'solver': 'saga', 'C': 0.001391669984306591, 'l1_ratio': 0.5515028987970982, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0261049097962204e-06, 'max_iter': 2876}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  20%|██████████████████████▏                                                                                         | 99/500 [11:30<28:50,  4.31s/it]

[I 2026-05-19 17:49:09,696] Trial 100 finished with value: 0.949638469898163 and parameters: {'solver': 'saga', 'C': 0.0014773901741104158, 'l1_ratio': 0.5472813073956591, 'class_weight': None, 'fit_intercept': True, 'tol': 1.024389321007667e-06, 'max_iter': 2913}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  20%|██████████████████████▍                                                                                        | 101/500 [11:38<25:00,  3.76s/it]

[I 2026-05-19 17:49:17,377] Trial 102 finished with value: 0.9496393387304742 and parameters: {'solver': 'saga', 'C': 0.0013605894780097233, 'l1_ratio': 0.5533824281799291, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0333498506139842e-06, 'max_iter': 2469}. Best is trial 74 with value: 0.9496418237060705.
[I 2026-05-19 17:49:17,487] Trial 101 finished with value: 0.9496201426214694 and parameters: {'solver': 'saga', 'C': 0.0001701393216046763, 'l1_ratio': 0.5479223135954452, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1461122861983158e-06, 'max_iter': 2298}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  20%|██████████████████████▋                                                                                        | 102/500 [11:42<25:48,  3.89s/it]

[I 2026-05-19 17:49:21,679] Trial 103 finished with value: 0.9496293069336179 and parameters: {'solver': 'saga', 'C': 0.00325014029198558, 'l1_ratio': 0.547119248054698, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1833644385850394e-06, 'max_iter': 2519}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  21%|██████████████████████▊                                                                                        | 103/500 [11:51<35:57,  5.43s/it]

[I 2026-05-19 17:49:30,716] Trial 104 finished with value: 0.9496397239318857 and parameters: {'solver': 'saga', 'C': 0.0013504630974088027, 'l1_ratio': 0.5378950835714831, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0364543645588573e-06, 'max_iter': 2560}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  21%|███████████████████████                                                                                        | 104/500 [11:58<39:17,  5.95s/it]

[I 2026-05-19 17:49:37,879] Trial 105 finished with value: 0.9496385754724308 and parameters: {'solver': 'saga', 'C': 0.0014640197178941924, 'l1_ratio': 0.5464013292941677, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1202226288578108e-06, 'max_iter': 2630}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  21%|███████████████████████▎                                                                                       | 105/500 [12:00<30:45,  4.67s/it]

[I 2026-05-19 17:49:39,565] Trial 106 finished with value: 0.9496358335101529 and parameters: {'solver': 'saga', 'C': 0.00019967776519454102, 'l1_ratio': 0.495061203953223, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0712067837600625e-06, 'max_iter': 2542}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  21%|███████████████████████▊                                                                                       | 107/500 [12:04<20:28,  3.13s/it]

[I 2026-05-19 17:49:43,339] Trial 107 finished with value: 0.9496258516294009 and parameters: {'solver': 'saga', 'C': 0.0001555297130704638, 'l1_ratio': 0.49599579845646274, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0079042178034237e-06, 'max_iter': 2391}. Best is trial 74 with value: 0.9496418237060705.
[I 2026-05-19 17:49:43,492] Trial 108 finished with value: 0.9496263045497617 and parameters: {'solver': 'saga', 'C': 0.0031127932943895045, 'l1_ratio': 0.6491680829208971, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0601421181985101e-06, 'max_iter': 2951}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  22%|███████████████████████▉                                                                                       | 108/500 [12:06<18:38,  2.85s/it]

[I 2026-05-19 17:49:45,705] Trial 109 finished with value: 0.9496310609851173 and parameters: {'solver': 'saga', 'C': 0.0036585405263923443, 'l1_ratio': 0.49568139066014505, 'class_weight': None, 'fit_intercept': True, 'tol': 1.022422572425735e-06, 'max_iter': 2547}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  22%|████████████████████████▏                                                                                      | 109/500 [12:14<28:08,  4.32s/it]

[I 2026-05-19 17:49:53,442] Trial 110 finished with value: 0.9496305902365796 and parameters: {'solver': 'saga', 'C': 0.003293037171675706, 'l1_ratio': 0.5019042428309892, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0305076462760871e-06, 'max_iter': 2457}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  22%|████████████████████████▍                                                                                      | 110/500 [12:22<36:06,  5.56s/it]

[I 2026-05-19 17:50:01,883] Trial 112 finished with value: 0.949631135626795 and parameters: {'solver': 'saga', 'C': 0.004425661959668173, 'l1_ratio': 0.496955993341975, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0204934735766115e-06, 'max_iter': 2563}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  22%|████████████████████████▋                                                                                      | 111/500 [12:23<27:04,  4.18s/it]

[I 2026-05-19 17:50:02,844] Trial 111 finished with value: 0.9496305407943867 and parameters: {'solver': 'saga', 'C': 0.003062065896344261, 'l1_ratio': 0.49946662934643926, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0334612973813802e-06, 'max_iter': 2534}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  22%|████████████████████████▊                                                                                      | 112/500 [12:25<23:16,  3.60s/it]

[I 2026-05-19 17:50:05,100] Trial 113 finished with value: 0.9496304537627266 and parameters: {'solver': 'saga', 'C': 0.003114810090355292, 'l1_ratio': 0.5007565397157688, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1054402949872956e-06, 'max_iter': 2619}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  23%|█████████████████████████                                                                                      | 113/500 [12:30<25:42,  3.99s/it]

[I 2026-05-19 17:50:09,985] Trial 119 pruned.

Best trial: 74. Best value: 0.949642:  23%|█████████████████████████▎                                                                                     | 114/500 [12:34<26:09,  4.07s/it]

[I 2026-05-19 17:50:14,232] Trial 114 finished with value: 0.9496307976418867 and parameters: {'solver': 'saga', 'C': 0.003243523665021933, 'l1_ratio': 0.49314170201500324, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0579987406962782e-06, 'max_iter': 2679}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  23%|█████████████████████████▌                                                                                     | 115/500 [12:41<31:06,  4.85s/it]

[I 2026-05-19 17:50:20,911] Trial 116 finished with value: 0.9496308434806396 and parameters: {'solver': 'saga', 'C': 0.004059448261248399, 'l1_ratio': 0.51309081310771, 'class_weight': None, 'fit_intercept': True, 'tol': 1.753745027097399e-06, 'max_iter': 2681}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  23%|█████████████████████████▊                                                                                     | 116/500 [12:42<23:27,  3.67s/it]

[I 2026-05-19 17:50:21,819] Trial 115 finished with value: 0.9496311395438604 and parameters: {'solver': 'saga', 'C': 0.0038980889357618583, 'l1_ratio': 0.49408033082388364, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7162818554619666e-06, 'max_iter': 2656}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  23%|█████████████████████████▉                                                                                     | 117/500 [12:45<21:30,  3.37s/it]

[I 2026-05-19 17:50:24,492] Trial 118 finished with value: 0.9496359342980035 and parameters: {'solver': 'saga', 'C': 0.0006837196023557683, 'l1_ratio': 0.5089297623962178, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7599940449161988e-06, 'max_iter': 2681}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  24%|██████████████████████████▏                                                                                    | 118/500 [12:46<16:38,  2.62s/it]

[I 2026-05-19 17:50:25,343] Trial 117 finished with value: 0.9496261644783035 and parameters: {'solver': 'saga', 'C': 0.0033056131674654154, 'l1_ratio': 0.6531636138306621, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8260711919681097e-06, 'max_iter': 2715}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  24%|██████████████████████████▍                                                                                    | 119/500 [12:52<24:38,  3.88s/it]

[I 2026-05-19 17:50:32,174] Trial 120 finished with value: 0.9494476126305766 and parameters: {'solver': 'saga', 'C': 0.00028861644640719463, 'l1_ratio': 0.5209414898547113, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.769980773615638e-06, 'max_iter': 2681}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  24%|██████████████████████████▊                                                                                    | 121/500 [13:06<29:32,  4.68s/it]

[I 2026-05-19 17:50:45,197] Trial 122 finished with value: 0.9496335853010919 and parameters: {'solver': 'saga', 'C': 0.00029664186353861284, 'l1_ratio': 0.5274574785873242, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8194852258947745e-06, 'max_iter': 2690}. Best is trial 74 with value: 0.9496418237060705.
[I 2026-05-19 17:50:45,340] Trial 121 finished with value: 0.9491470730945023 and parameters: {'solver': 'saga', 'C': 0.007295017978620037, 'l1_ratio': 0.6482259447236387, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 1.725363160845392e-06, 'max_iter': 2193}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  24%|███████████████████████████                                                                                    | 122/500 [13:09<27:00,  4.29s/it]

[I 2026-05-19 17:50:48,721] Trial 123 finished with value: 0.9496356862256292 and parameters: {'solver': 'saga', 'C': 0.0007106480684282399, 'l1_ratio': 0.5223322000346629, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6549628885124718e-06, 'max_iter': 2196}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  25%|███████████████████████████▎                                                                                   | 123/500 [13:11<23:20,  3.72s/it]

[I 2026-05-19 17:50:51,103] Trial 124 finished with value: 0.9496289658957717 and parameters: {'solver': 'saga', 'C': 0.006873359877396329, 'l1_ratio': 0.520325540837662, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1813052946156703e-06, 'max_iter': 3018}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  25%|███████████████████████████▌                                                                                   | 124/500 [13:13<20:12,  3.23s/it]

[I 2026-05-19 17:50:53,176] Trial 127 finished with value: 0.9496093927923612 and parameters: {'solver': 'saga', 'C': 0.0071394764526495095, 'l1_ratio': 0.6429982973056688, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 6.0467825046175804e-05, 'max_iter': 3175}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  25%|███████████████████████████▊                                                                                   | 125/500 [13:16<19:24,  3.11s/it]

[I 2026-05-19 17:50:56,010] Trial 125 finished with value: 0.949606825754669 and parameters: {'solver': 'saga', 'C': 0.0006188990599085346, 'l1_ratio': 0.5214632187781678, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.1124758674440802e-06, 'max_iter': 2730}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  25%|███████████████████████████▉                                                                                   | 126/500 [13:23<26:36,  4.27s/it]

[I 2026-05-19 17:51:02,989] Trial 126 finished with value: 0.9496109176881697 and parameters: {'solver': 'saga', 'C': 0.0007245440333476523, 'l1_ratio': 0.5282843607863217, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.31214481552009e-06, 'max_iter': 2735}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  25%|████████████████████████████▏                                                                                  | 127/500 [13:26<23:44,  3.82s/it]

[I 2026-05-19 17:51:05,762] Trial 128 finished with value: 0.9496143224440944 and parameters: {'solver': 'saga', 'C': 0.0010608844651831448, 'l1_ratio': 0.6440309357790944, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.40920376387633e-06, 'max_iter': 3188}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  26%|████████████████████████████▍                                                                                  | 128/500 [13:27<19:21,  3.12s/it]

[I 2026-05-19 17:51:07,255] Trial 129 finished with value: 0.9496133682089651 and parameters: {'solver': 'saga', 'C': 0.0011264982909304268, 'l1_ratio': 0.6772062900891733, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.2720533767431284e-06, 'max_iter': 2113}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 74. Best value: 0.949642:  26%|████████████████████████████▋                                                                                  | 129/500 [13:33<23:10,  3.75s/it]

[I 2026-05-19 17:51:12,450] Trial 130 finished with value: 0.9496256646718975 and parameters: {'solver': 'saga', 'C': 0.006900204283880188, 'l1_ratio': 0.6877011655606591, 'class_weight': None, 'fit_intercept': True, 'tol': 2.319479182032064e-06, 'max_iter': 3024}. Best is trial 74 with value: 0.9496418237060705.

Best trial: 134. Best value: 0.949642:  26%|████████████████████████████▌                                                                                 | 130/500 [13:42<33:44,  5.47s/it]

[I 2026-05-19 17:51:21,943] Trial 134 finished with value: 0.9496420828292089 and parameters: {'solver': 'saga', 'C': 0.001153041495570838, 'l1_ratio': 0.47378151254958245, 'class_weight': None, 'fit_intercept': True, 'tol': 6.0911783460510125e-05, 'max_iter': 3163}. Best is trial 134 with value: 0.9496420828292089.

Best trial: 134. Best value: 0.949642:  26%|█████████████████████████████                                                                                 | 132/500 [13:46<21:55,  3.57s/it]

[I 2026-05-19 17:51:25,947] Trial 131 finished with value: 0.9496358301274702 and parameters: {'solver': 'saga', 'C': 0.0011042363343647804, 'l1_ratio': 0.6419063897628564, 'class_weight': None, 'fit_intercept': True, 'tol': 3.323605953354596e-06, 'max_iter': 3070}. Best is trial 134 with value: 0.9496420828292089.
[I 2026-05-19 17:51:26,130] Trial 132 finished with value: 0.9496417939097326 and parameters: {'solver': 'saga', 'C': 0.0013038325295023883, 'l1_ratio': 0.4646709888887642, 'class_weight': None, 'fit_intercept': True, 'tol': 2.305821423353735e-06, 'max_iter': 3195}. Best is trial 134 with value: 0.9496420828292089.

Best trial: 134. Best value: 0.949642:  27%|█████████████████████████████▎                                                                                | 133/500 [13:48<18:10,  2.97s/it]

[I 2026-05-19 17:51:27,692] Trial 133 finished with value: 0.9496322894495239 and parameters: {'solver': 'saga', 'C': 0.0011644953497841688, 'l1_ratio': 0.6847728610851586, 'class_weight': None, 'fit_intercept': True, 'tol': 2.3038510997111945e-06, 'max_iter': 3000}. Best is trial 134 with value: 0.9496420828292089.

Best trial: 134. Best value: 0.949642:  27%|█████████████████████████████▍                                                                                | 134/500 [13:57<29:20,  4.81s/it]

[I 2026-05-19 17:51:36,802] Trial 135 finished with value: 0.9496324794493638 and parameters: {'solver': 'saga', 'C': 0.0011368680890134167, 'l1_ratio': 0.680259971765039, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2992785682222487e-06, 'max_iter': 2908}. Best is trial 134 with value: 0.9496420828292089.

Best trial: 134. Best value: 0.949642:  27%|█████████████████████████████▋                                                                                | 135/500 [14:01<27:25,  4.51s/it]

[I 2026-05-19 17:51:40,600] Trial 136 finished with value: 0.9496329394788117 and parameters: {'solver': 'saga', 'C': 0.0011479901142021618, 'l1_ratio': 0.675669633384314, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3061441372430006e-06, 'max_iter': 2932}. Best is trial 134 with value: 0.9496420828292089.

Best trial: 134. Best value: 0.949642:  27%|█████████████████████████████▉                                                                                | 136/500 [14:08<31:30,  5.19s/it]

[I 2026-05-19 17:51:47,398] Trial 139 finished with value: 0.9496338000891299 and parameters: {'solver': 'saga', 'C': 0.002063781822779361, 'l1_ratio': 0.4635248815175868, 'class_weight': None, 'fit_intercept': True, 'tol': 3.3562571119881727e-06, 'max_iter': 2914}. Best is trial 134 with value: 0.9496420828292089.

Best trial: 134. Best value: 0.949642:  27%|██████████████████████████████▏                                                                               | 137/500 [14:09<24:38,  4.07s/it]

[I 2026-05-19 17:51:48,849] Trial 137 finished with value: 0.9496387840483805 and parameters: {'solver': 'saga', 'C': 0.0011537223453579736, 'l1_ratio': 0.604350416292613, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2896256419288013e-06, 'max_iter': 2890}. Best is trial 134 with value: 0.9496420828292089.

Best trial: 138. Best value: 0.949642:  28%|██████████████████████████████▎                                                                               | 138/500 [14:09<17:42,  2.93s/it]

[I 2026-05-19 17:51:49,125] Trial 138 finished with value: 0.9496421122647571 and parameters: {'solver': 'saga', 'C': 0.0012157000427812697, 'l1_ratio': 0.4721993887306227, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3156088029414616e-06, 'max_iter': 1982}. Best is trial 138 with value: 0.9496421122647571.

Best trial: 138. Best value: 0.949642:  28%|██████████████████████████████▌                                                                               | 139/500 [14:16<23:47,  3.95s/it]

[I 2026-05-19 17:51:55,458] Trial 140 finished with value: 0.9496419099020432 and parameters: {'solver': 'saga', 'C': 0.001214067349549464, 'l1_ratio': 0.4552209063881547, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2992776869812546e-06, 'max_iter': 2909}. Best is trial 138 with value: 0.9496421122647571.

Best trial: 138. Best value: 0.949642:  28%|██████████████████████████████▊                                                                               | 140/500 [14:22<28:18,  4.72s/it]

[I 2026-05-19 17:52:01,968] Trial 146 finished with value: 0.9496335212671729 and parameters: {'solver': 'saga', 'C': 0.0020359430192837, 'l1_ratio': 0.45664326798219323, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001532158509755319, 'max_iter': 3211}. Best is trial 138 with value: 0.9496421122647571.

Best trial: 138. Best value: 0.949642:  28%|███████████████████████████████                                                                               | 141/500 [14:25<24:22,  4.08s/it]

[I 2026-05-19 17:52:04,538] Trial 145 finished with value: 0.9490672395545289 and parameters: {'solver': 'saga', 'C': 1.384436501043547e-05, 'l1_ratio': 0.4595132025864325, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004693935622952738, 'max_iter': 3445}. Best is trial 138 with value: 0.9496421122647571.

Best trial: 138. Best value: 0.949642:  28%|███████████████████████████████▏                                                                              | 142/500 [14:26<18:46,  3.15s/it]

[I 2026-05-19 17:52:05,521] Trial 141 finished with value: 0.9496323809495559 and parameters: {'solver': 'saga', 'C': 0.0022750349031232923, 'l1_ratio': 0.45659497062556853, 'class_weight': None, 'fit_intercept': True, 'tol': 3.4614103858859015e-06, 'max_iter': 3453}. Best is trial 138 with value: 0.9496421122647571.

Best trial: 138. Best value: 0.949642:  29%|███████████████████████████████▍                                                                              | 143/500 [14:32<24:02,  4.04s/it]

[I 2026-05-19 17:52:11,648] Trial 142 finished with value: 0.9496325966501098 and parameters: {'solver': 'saga', 'C': 0.002212081961825992, 'l1_ratio': 0.4641865856714926, 'class_weight': None, 'fit_intercept': True, 'tol': 1.31575895553834e-06, 'max_iter': 2909}. Best is trial 138 with value: 0.9496421122647571.

Best trial: 138. Best value: 0.949642:  29%|███████████████████████████████▋                                                                              | 144/500 [14:33<18:05,  3.05s/it]

[I 2026-05-19 17:52:12,386] Trial 143 finished with value: 0.9496319251461255 and parameters: {'solver': 'saga', 'C': 0.0023486321837937435, 'l1_ratio': 0.46612687359279525, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3294619348672786e-06, 'max_iter': 3417}. Best is trial 138 with value: 0.9496421122647571.

Best trial: 138. Best value: 0.949642:  29%|███████████████████████████████▉                                                                              | 145/500 [14:33<13:22,  2.26s/it]

[I 2026-05-19 17:52:12,792] Trial 144 finished with value: 0.9496345447987797 and parameters: {'solver': 'saga', 'C': 0.0019833001532778994, 'l1_ratio': 0.4687072682112562, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3361685592758134e-06, 'max_iter': 3494}. Best is trial 138 with value: 0.9496421122647571.

Best trial: 148. Best value: 0.949645:  29%|████████████████████████████████                                                                              | 146/500 [14:35<12:39,  2.15s/it]

[I 2026-05-19 17:52:14,682] Trial 148 finished with value: 0.9496449674479684 and parameters: {'solver': 'saga', 'C': 0.0004112374713037938, 'l1_ratio': 0.42639802333719307, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009055437115406952, 'max_iter': 3205}. Best is trial 148 with value: 0.9496449674479684.

Best trial: 148. Best value: 0.949645:  29%|████████████████████████████████▎                                                                             | 147/500 [14:39<15:30,  2.64s/it]

[I 2026-05-19 17:52:18,464] Trial 150 finished with value: 0.9496339362477203 and parameters: {'solver': 'saga', 'C': 0.002063279458984343, 'l1_ratio': 0.4331728029995044, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009618206589015004, 'max_iter': 3499}. Best is trial 148 with value: 0.9496449674479684.

Best trial: 148. Best value: 0.949645:  30%|████████████████████████████████▌                                                                             | 148/500 [14:53<36:39,  6.25s/it]

[I 2026-05-19 17:52:33,142] Trial 147 finished with value: 0.9496337203803954 and parameters: {'solver': 'saga', 'C': 0.002081892696871926, 'l1_ratio': 0.4241163696699223, 'class_weight': None, 'fit_intercept': True, 'tol': 1.376297691988831e-06, 'max_iter': 3465}. Best is trial 148 with value: 0.9496449674479684.

Best trial: 148. Best value: 0.949645:  30%|████████████████████████████████▊                                                                             | 149/500 [14:54<27:24,  4.69s/it]

[I 2026-05-19 17:52:34,172] Trial 153 finished with value: 0.9496411397129807 and parameters: {'solver': 'saga', 'C': 0.00070258011797871, 'l1_ratio': 0.42871467153394655, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00023382956221011157, 'max_iter': 1651}. Best is trial 148 with value: 0.9496449674479684.

Best trial: 148. Best value: 0.949645:  30%|█████████████████████████████████                                                                             | 150/500 [14:55<20:22,  3.49s/it]

[I 2026-05-19 17:52:34,888] Trial 149 finished with value: 0.9496333018276925 and parameters: {'solver': 'saga', 'C': 0.0021171520531809104, 'l1_ratio': 0.4506525243215658, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3880046302998312e-06, 'max_iter': 1396}. Best is trial 148 with value: 0.9496449674479684.

Best trial: 152. Best value: 0.949646:  30%|█████████████████████████████████▏                                                                            | 151/500 [14:56<15:21,  2.64s/it]

[I 2026-05-19 17:52:35,536] Trial 152 finished with value: 0.9496464295141092 and parameters: {'solver': 'saga', 'C': 0.00039879919406494584, 'l1_ratio': 0.41022005319766175, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00020768960232571298, 'max_iter': 2794}. Best is trial 152 with value: 0.9496464295141092.

Best trial: 152. Best value: 0.949646:  30%|█████████████████████████████████▍                                                                            | 152/500 [14:57<12:34,  2.17s/it]

[I 2026-05-19 17:52:36,594] Trial 156 finished with value: 0.9496462009575595 and parameters: {'solver': 'saga', 'C': 0.00040355450554275846, 'l1_ratio': 0.39223640455757947, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007940901951972153, 'max_iter': 1888}. Best is trial 152 with value: 0.9496464295141092.

Best trial: 158. Best value: 0.949647:  31%|█████████████████████████████████▋                                                                            | 153/500 [15:01<15:33,  2.69s/it]

[I 2026-05-19 17:52:40,503] Trial 158 finished with value: 0.9496472856390141 and parameters: {'solver': 'saga', 'C': 0.0003893409130136492, 'l1_ratio': 0.4152412255596723, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00231011400335484, 'max_iter': 2780}. Best is trial 158 with value: 0.9496472856390141.
[I 2026-05-19 17:52:40,540] Trial 154 finished with value: 0.9496419775972484 and parameters: {'solver': 'saga', 'C': 0.00045628479287376604, 'l1_ratio': 0.42502904042415357, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017716667901183922, 'max_iter': 1801}. Best is trial 158 with value: 0.9496472856390141.

Best trial: 158. Best value: 0.949647:  31%|██████████████████████████████████                                                                            | 155/500 [15:08<17:38,  3.07s/it]

[I 2026-05-19 17:52:47,531] Trial 151 finished with value: 0.9496444475625454 and parameters: {'solver': 'saga', 'C': 0.0004148056422598757, 'l1_ratio': 0.44045259324289365, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4175187692359586e-06, 'max_iter': 1609}. Best is trial 158 with value: 0.9496472856390141.

Best trial: 158. Best value: 0.949647:  31%|██████████████████████████████████▎                                                                           | 156/500 [15:16<24:50,  4.33s/it]

[I 2026-05-19 17:52:55,703] Trial 159 finished with value: 0.9496463600451035 and parameters: {'solver': 'saga', 'C': 0.00040124702618640225, 'l1_ratio': 0.3815782321137586, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0016398172071321981, 'max_iter': 1514}. Best is trial 158 with value: 0.9496472856390141.

Best trial: 158. Best value: 0.949647:  31%|██████████████████████████████████▌                                                                           | 157/500 [15:19<23:30,  4.11s/it]

[I 2026-05-19 17:52:59,178] Trial 155 finished with value: 0.9496429100154578 and parameters: {'solver': 'saga', 'C': 0.0004381259227012357, 'l1_ratio': 0.4371031151016761, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4012838059981562e-06, 'max_iter': 1737}. Best is trial 158 with value: 0.9496472856390141.

Best trial: 157. Best value: 0.949649:  32%|██████████████████████████████████▊                                                                           | 158/500 [15:23<22:18,  3.91s/it]

[I 2026-05-19 17:53:02,550] Trial 157 finished with value: 0.9496489648640862 and parameters: {'solver': 'saga', 'C': 0.00036288645855161837, 'l1_ratio': 0.42093401968878585, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4960594295492598e-06, 'max_iter': 1197}. Best is trial 157 with value: 0.9496489648640862.

[I 2026-05-19 17:53:04,759] Trial 162 finished with value: 0.9496413858007322 and parameters: {'solver': 'saga', 'C': 0.00046722526793130555, 'l1_ratio': 0.3982799672243441, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00018087937816164019, 'max_iter': 2028}. Best is trial 157 with value: 0.9496489648640862.

Best trial: 157. Best value: 0.949649:  32%|███████████████████████████████████▏                                                                          | 160/500 [15:25<14:15,  2.52s/it]

[I 2026-05-19 17:53:04,958] Trial 160 finished with value: 0.9496450951301021 and parameters: {'solver': 'saga', 'C': 0.0004122584298263122, 'l1_ratio': 0.38453267804494223, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001460198577828745, 'max_iter': 1466}. Best is trial 157 with value: 0.9496489648640862.

Best trial: 163. Best value: 0.949652:  32%|███████████████████████████████████▍                                                                          | 161/500 [15:28<14:56,  2.64s/it]

[I 2026-05-19 17:53:07,939] Trial 163 finished with value: 0.9496524028503034 and parameters: {'solver': 'saga', 'C': 0.00032969981491148175, 'l1_ratio': 0.3882826349942755, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002292938329461887, 'max_iter': 1880}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  32%|███████████████████████████████████▋                                                                          | 162/500 [15:29<11:14,  1.99s/it]

[I 2026-05-19 17:53:08,367] Trial 161 finished with value: 0.9496492413932796 and parameters: {'solver': 'saga', 'C': 0.0003653465393452472, 'l1_ratio': 0.3815145840958776, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001234525910103585, 'max_iter': 1432}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  33%|███████████████████████████████████▊                                                                          | 163/500 [15:32<12:57,  2.31s/it]

[I 2026-05-19 17:53:11,412] Trial 164 finished with value: 0.9496439312288439 and parameters: {'solver': 'saga', 'C': 0.0004238921410167973, 'l1_ratio': 0.3713456074356258, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00014281998777100036, 'max_iter': 1929}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  33%|████████████████████████████████████                                                                          | 164/500 [15:34<13:24,  2.39s/it]

[I 2026-05-19 17:53:14,016] Trial 165 finished with value: 0.9496469570397416 and parameters: {'solver': 'saga', 'C': 0.0003907723821855559, 'l1_ratio': 0.38987519638993806, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00021178623016995408, 'max_iter': 1877}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  33%|████████████████████████████████████▎                                                                         | 165/500 [15:40<19:22,  3.47s/it]

[I 2026-05-19 17:53:20,041] Trial 166 finished with value: 0.9496463236090206 and parameters: {'solver': 'saga', 'C': 0.00039994581146942965, 'l1_ratio': 0.3954595916507337, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001491249793470668, 'max_iter': 1809}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  33%|████████████████████████████████████▌                                                                         | 166/500 [15:49<28:35,  5.14s/it]

[I 2026-05-19 17:53:29,087] Trial 167 finished with value: 0.9496395003058428 and parameters: {'solver': 'saga', 'C': 0.0004919530102616234, 'l1_ratio': 0.39511804531583095, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017074680501247917, 'max_iter': 1875}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  33%|████████████████████████████████████▋                                                                         | 167/500 [15:50<21:12,  3.82s/it]

[I 2026-05-19 17:53:29,831] Trial 171 finished with value: 0.9496483473659744 and parameters: {'solver': 'saga', 'C': 0.00037348326988157756, 'l1_ratio': 0.38228453838859167, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0020439357705703287, 'max_iter': 1918}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  34%|████████████████████████████████████▉                                                                         | 168/500 [15:51<16:31,  2.99s/it]

[I 2026-05-19 17:53:30,818] Trial 170 finished with value: 0.9496235166156565 and parameters: {'solver': 'saga', 'C': 0.0001082076912396154, 'l1_ratio': 0.3806936990776222, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0018180765898519555, 'max_iter': 1926}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  34%|█████████████████████████████████████▏                                                                        | 169/500 [15:53<15:17,  2.77s/it]

[I 2026-05-19 17:53:33,127] Trial 173 finished with value: 0.9496331558321132 and parameters: {'solver': 'saga', 'C': 0.00011691388818386159, 'l1_ratio': 0.37917127389014715, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0019197220501932556, 'max_iter': 1512}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  34%|█████████████████████████████████████▍                                                                        | 170/500 [15:54<11:36,  2.11s/it]

[I 2026-05-19 17:53:33,691] Trial 168 finished with value: 0.949616278101032 and parameters: {'solver': 'saga', 'C': 0.0001055840624508693, 'l1_ratio': 0.3918260042525842, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00023775412917107449, 'max_iter': 1868}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  34%|█████████████████████████████████████▌                                                                        | 171/500 [15:55<10:11,  1.86s/it]

[I 2026-05-19 17:53:34,966] Trial 169 finished with value: 0.9496429601012991 and parameters: {'solver': 'saga', 'C': 0.00044183870023457167, 'l1_ratio': 0.382557664445636, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00019338384839314476, 'max_iter': 1873}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  34%|█████████████████████████████████████▊                                                                        | 172/500 [15:57<10:43,  1.96s/it]

[I 2026-05-19 17:53:37,160] Trial 174 finished with value: 0.9496271199241997 and parameters: {'solver': 'saga', 'C': 0.00010967449744811176, 'l1_ratio': 0.37183138857291737, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0020109716924251535, 'max_iter': 1858}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  35%|██████████████████████████████████████                                                                        | 173/500 [16:05<19:32,  3.59s/it]

[I 2026-05-19 17:53:44,542] Trial 172 finished with value: 0.9496291515329549 and parameters: {'solver': 'saga', 'C': 0.00011428826826787074, 'l1_ratio': 0.3850973337521399, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0002062071020966416, 'max_iter': 1887}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  35%|██████████████████████████████████████▎                                                                       | 174/500 [16:12<26:03,  4.79s/it]

[I 2026-05-19 17:53:52,163] Trial 175 finished with value: 0.9496338626323955 and parameters: {'solver': 'saga', 'C': 0.00011638614472130949, 'l1_ratio': 0.37356007471414654, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011692596066839177, 'max_iter': 1831}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  35%|██████████████████████████████████████▌                                                                       | 175/500 [16:14<21:11,  3.91s/it]

[I 2026-05-19 17:53:54,011] Trial 178 finished with value: 0.94962702801755 and parameters: {'solver': 'saga', 'C': 0.00011022301151023778, 'l1_ratio': 0.3758694605273792, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002016709314264561, 'max_iter': 1601}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 163. Best value: 0.949652:  35%|██████████████████████████████████████▋                                                                       | 176/500 [16:15<16:47,  3.11s/it]

[I 2026-05-19 17:53:55,250] Trial 176 finished with value: 0.9496359052938871 and parameters: {'solver': 'saga', 'C': 0.0001188707229967852, 'l1_ratio': 0.3761398572799586, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00013350171490182067, 'max_iter': 1792}. Best is trial 163 with value: 0.9496524028503034.

Best trial: 180. Best value: 0.949656:  35%|██████████████████████████████████████▉                                                                       | 177/500 [16:21<21:03,  3.91s/it]

[I 2026-05-19 17:54:01,035] Trial 180 finished with value: 0.9496562284868084 and parameters: {'solver': 'saga', 'C': 0.00023201044954937862, 'l1_ratio': 0.33312996049990695, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003531645302038337, 'max_iter': 1708}. Best is trial 180 with value: 0.9496562284868084.

Best trial: 180. Best value: 0.949656:  36%|███████████████████████████████████████▏                                                                      | 178/500 [16:24<18:38,  3.47s/it]

[I 2026-05-19 17:54:03,480] Trial 177 finished with value: 0.949609875048399 and parameters: {'solver': 'saga', 'C': 9.913415945722155e-05, 'l1_ratio': 0.38067474513009947, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011452789264052334, 'max_iter': 1576}. Best is trial 180 with value: 0.9496562284868084.

Best trial: 180. Best value: 0.949656:  36%|███████████████████████████████████████▍                                                                      | 179/500 [16:27<18:49,  3.52s/it]

[I 2026-05-19 17:54:07,096] Trial 179 finished with value: 0.9496487607895625 and parameters: {'solver': 'saga', 'C': 0.0003246369919843764, 'l1_ratio': 0.3301156341843984, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010928813490232981, 'max_iter': 1667}. Best is trial 180 with value: 0.9496562284868084.

Best trial: 180. Best value: 0.949656:  36%|███████████████████████████████████████▌                                                                      | 180/500 [16:28<14:08,  2.65s/it]

[I 2026-05-19 17:54:07,730] Trial 181 finished with value: 0.949654679092864 and parameters: {'solver': 'saga', 'C': 0.0002488953213963249, 'l1_ratio': 0.33209598117841177, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00010674750054668724, 'max_iter': 1188}. Best is trial 180 with value: 0.9496562284868084.

Best trial: 180. Best value: 0.949656:  36%|███████████████████████████████████████▊                                                                      | 181/500 [16:33<17:37,  3.31s/it]

[I 2026-05-19 17:54:12,595] Trial 182 finished with value: 0.9496525658013641 and parameters: {'solver': 'saga', 'C': 0.00023418836945006375, 'l1_ratio': 0.31929315080109844, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011902125838820281, 'max_iter': 1163}. Best is trial 180 with value: 0.9496562284868084.

Best trial: 180. Best value: 0.949656:  36%|████████████████████████████████████████                                                                      | 182/500 [16:34<14:34,  2.75s/it]

[I 2026-05-19 17:54:14,021] Trial 183 finished with value: 0.9496555115784153 and parameters: {'solver': 'saga', 'C': 0.00022546468293787296, 'l1_ratio': 0.32925848621439946, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00011582051887494567, 'max_iter': 1706}. Best is trial 180 with value: 0.9496562284868084.

Best trial: 180. Best value: 0.949656:  37%|████████████████████████████████████████▎                                                                     | 183/500 [16:39<17:56,  3.39s/it]

[I 2026-05-19 17:54:18,927] Trial 189 pruned.

Best trial: 185. Best value: 0.949657:  37%|████████████████████████████████████████▍                                                                     | 184/500 [16:41<16:03,  3.05s/it]

[I 2026-05-19 17:54:21,150] Trial 185 finished with value: 0.9496574433476305 and parameters: {'solver': 'saga', 'C': 0.0002383978071131754, 'l1_ratio': 0.4117822354276281, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00034805272297231305, 'max_iter': 1204}. Best is trial 185 with value: 0.9496574433476305.
[I 2026-05-19 17:54:21,173] Trial 184 finished with value: 0.9496546829147544 and parameters: {'solver': 'saga', 'C': 0.00021910258089389572, 'l1_ratio': 0.3251045876379872, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00012149826631298271, 'max_iter': 1698}. Best is trial 185 with value: 0.9496574433476305.

Best trial: 185. Best value: 0.949657:  37%|████████████████████████████████████████▉                                                                     | 186/500 [16:45<12:54,  2.47s/it]

[I 2026-05-19 17:54:24,750] Trial 191 pruned.

Best trial: 185. Best value: 0.949657:  37%|█████████████████████████████████████████▏                                                                    | 187/500 [16:46<10:27,  2.01s/it]

[I 2026-05-19 17:54:25,341] Trial 187 finished with value: 0.9496570809988574 and parameters: {'solver': 'saga', 'C': 0.00020846578848518984, 'l1_ratio': 0.41132650476964433, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003403501414440411, 'max_iter': 1179}. Best is trial 185 with value: 0.9496574433476305.
[I 2026-05-19 17:54:25,373] Trial 186 finished with value: 0.9496570940663048 and parameters: {'solver': 'saga', 'C': 0.00023659354284070192, 'l1_ratio': 0.3389521870402179, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00034221661596100345, 'max_iter': 1178}. Best is trial 185 with value: 0.9496574433476305.

Best trial: 188. Best value: 0.949658:  38%|█████████████████████████████████████████▌                                                                    | 189/500 [16:52<12:33,  2.42s/it]

[I 2026-05-19 17:54:31,381] Trial 188 finished with value: 0.9496578971395401 and parameters: {'solver': 'saga', 'C': 0.00022561539839812078, 'l1_ratio': 0.3391720179805163, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003258528149622593, 'max_iter': 1207}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  38%|█████████████████████████████████████████▊                                                                    | 190/500 [17:00<19:40,  3.81s/it]

[I 2026-05-19 17:54:39,868] Trial 190 finished with value: 0.9496468211530198 and parameters: {'solver': 'saga', 'C': 0.0003606597887692118, 'l1_ratio': 0.33722785047551435, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003200730806016026, 'max_iter': 1182}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  38%|██████████████████████████████████████████                                                                    | 191/500 [17:10<27:11,  5.28s/it]

[I 2026-05-19 17:54:49,645] Trial 192 finished with value: 0.9496536173605664 and parameters: {'solver': 'saga', 'C': 0.0002562383044312617, 'l1_ratio': 0.33007297639930966, 'class_weight': None, 'fit_intercept': True, 'tol': 7.49432709377057e-05, 'max_iter': 1100}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  38%|██████████████████████████████████████████▏                                                                   | 192/500 [17:10<20:45,  4.04s/it]

[I 2026-05-19 17:54:50,175] Trial 193 finished with value: 0.9496515565977758 and parameters: {'solver': 'saga', 'C': 0.000314446968841008, 'l1_ratio': 0.3446477646432086, 'class_weight': None, 'fit_intercept': True, 'tol': 8.159503004709848e-05, 'max_iter': 1142}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  39%|██████████████████████████████████████████▍                                                                   | 193/500 [17:11<16:12,  3.17s/it]

[I 2026-05-19 17:54:50,985] Trial 197 finished with value: 0.9495039768955742 and parameters: {'solver': 'saga', 'C': 6.801772085757045e-05, 'l1_ratio': 0.31137142503573195, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007483651919519095, 'max_iter': 1033}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  39%|██████████████████████████████████████████▋                                                                   | 194/500 [17:12<12:24,  2.43s/it]

[I 2026-05-19 17:54:51,526] Trial 194 finished with value: 0.9496494631609732 and parameters: {'solver': 'saga', 'C': 0.00030255146890154733, 'l1_ratio': 0.3243497132568842, 'class_weight': None, 'fit_intercept': True, 'tol': 7.67176308712762e-05, 'max_iter': 1391}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  39%|███████████████████████████████████████████                                                                   | 196/500 [17:13<07:12,  1.42s/it]

[I 2026-05-19 17:54:52,206] Trial 199 finished with value: 0.9496508061104096 and parameters: {'solver': 'saga', 'C': 0.00026944825724969495, 'l1_ratio': 0.3187112572912558, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00035187079409368355, 'max_iter': 1005}. Best is trial 188 with value: 0.9496578971395401.
[I 2026-05-19 17:54:52,375] Trial 198 finished with value: 0.949647512101523 and parameters: {'solver': 'saga', 'C': 0.00030909005950670987, 'l1_ratio': 0.31468913209175253, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003473952660337205, 'max_iter': 1030}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  39%|███████████████████████████████████████████▎                                                                  | 197/500 [17:15<08:38,  1.71s/it]

[I 2026-05-19 17:54:54,782] Trial 196 finished with value: 0.9496542065168768 and parameters: {'solver': 'saga', 'C': 0.00024187582450079285, 'l1_ratio': 0.32702022986168433, 'class_weight': None, 'fit_intercept': True, 'tol': 7.315343567181992e-05, 'max_iter': 1086}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  40%|███████████████████████████████████████████▌                                                                  | 198/500 [17:15<06:27,  1.28s/it]

[I 2026-05-19 17:54:54,998] Trial 195 finished with value: 0.9496547612222797 and parameters: {'solver': 'saga', 'C': 0.00024223574339376475, 'l1_ratio': 0.3297643363880213, 'class_weight': None, 'fit_intercept': True, 'tol': 8.212351390550943e-05, 'max_iter': 1046}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  40%|███████████████████████████████████████████▊                                                                  | 199/500 [17:21<12:37,  2.52s/it]

[I 2026-05-19 17:55:00,496] Trial 200 finished with value: 0.9496499064184725 and parameters: {'solver': 'saga', 'C': 0.00029073158473152987, 'l1_ratio': 0.3216181442104185, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00032373040686247643, 'max_iter': 1003}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  40%|████████████████████████████████████████████                                                                  | 200/500 [17:29<21:44,  4.35s/it]

[I 2026-05-19 17:55:09,163] Trial 201 finished with value: 0.9496510972263273 and parameters: {'solver': 'saga', 'C': 0.00024004848134159378, 'l1_ratio': 0.31461742107030116, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003136293580185692, 'max_iter': 1313}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  40%|████████████████████████████████████████████▏                                                                 | 201/500 [17:40<31:18,  6.28s/it]

[I 2026-05-19 17:55:20,003] Trial 204 finished with value: 0.9496529386975101 and parameters: {'solver': 'saga', 'C': 0.0002561324867600754, 'l1_ratio': 0.3255856869076024, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00034973114965479874, 'max_iter': 1296}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  40%|████████████████████████████████████████████▍                                                                 | 202/500 [17:41<23:40,  4.77s/it]

[I 2026-05-19 17:55:21,189] Trial 203 finished with value: 0.9493314892300363 and parameters: {'solver': 'saga', 'C': 4.400602719756115e-05, 'l1_ratio': 0.3102435608622493, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00034554899381137574, 'max_iter': 1305}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  41%|████████████████████████████████████████████▋                                                                 | 203/500 [17:44<20:22,  4.12s/it]

[I 2026-05-19 17:55:23,799] Trial 202 finished with value: 0.9494554295363983 and parameters: {'solver': 'saga', 'C': 5.748159782737117e-05, 'l1_ratio': 0.3247101594848988, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00033654692572262216, 'max_iter': 1020}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  41%|█████████████████████████████████████████████                                                                 | 205/500 [17:45<11:23,  2.32s/it]

[I 2026-05-19 17:55:25,057] Trial 207 finished with value: 0.9496527760042109 and parameters: {'solver': 'saga', 'C': 0.00024698546360314103, 'l1_ratio': 0.3227065209433668, 'class_weight': None, 'fit_intercept': True, 'tol': 7.717154489095366e-05, 'max_iter': 1318}. Best is trial 188 with value: 0.9496578971395401.
[I 2026-05-19 17:55:25,170] Trial 205 finished with value: 0.9496522170994226 and parameters: {'solver': 'saga', 'C': 0.00026160042944482184, 'l1_ratio': 0.3243967817842644, 'class_weight': None, 'fit_intercept': True, 'tol': 7.959662086445295e-05, 'max_iter': 1288}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  41%|█████████████████████████████████████████████▎                                                                | 206/500 [17:47<11:02,  2.25s/it]

[I 2026-05-19 17:55:27,274] Trial 206 finished with value: 0.9496364998042657 and parameters: {'solver': 'saga', 'C': 0.00016753971260996265, 'l1_ratio': 0.2862140535624615, 'class_weight': None, 'fit_intercept': True, 'tol': 7.432818386031282e-05, 'max_iter': 1322}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  41%|█████████████████████████████████████████████▌                                                                | 207/500 [17:48<08:44,  1.79s/it]

[I 2026-05-19 17:55:27,975] Trial 209 finished with value: 0.9496411626583194 and parameters: {'solver': 'saga', 'C': 0.00019353915798022057, 'l1_ratio': 0.2871675293020954, 'class_weight': None, 'fit_intercept': True, 'tol': 8.220829273152779e-05, 'max_iter': 1358}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  42%|█████████████████████████████████████████████▊                                                                | 208/500 [17:49<07:23,  1.52s/it]

[I 2026-05-19 17:55:28,873] Trial 208 finished with value: 0.9496324392070588 and parameters: {'solver': 'saga', 'C': 0.00016143995143582323, 'l1_ratio': 0.2818204546289735, 'class_weight': None, 'fit_intercept': True, 'tol': 8.133376144737709e-05, 'max_iter': 1304}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  42%|█████████████████████████████████████████████▉                                                                | 209/500 [17:55<13:52,  2.86s/it]

[I 2026-05-19 17:55:34,866] Trial 210 finished with value: 0.9496263758402448 and parameters: {'solver': 'saga', 'C': 0.0001640186943907076, 'l1_ratio': 0.2706626407362705, 'class_weight': None, 'fit_intercept': True, 'tol': 7.554903976237731e-05, 'max_iter': 1316}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  42%|██████████████████████████████████████████████▏                                                               | 210/500 [17:58<13:57,  2.89s/it]

[I 2026-05-19 17:55:37,812] Trial 211 finished with value: 0.9496365812107486 and parameters: {'solver': 'saga', 'C': 0.00019299328366175674, 'l1_ratio': 0.27727174948802524, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00041477028531138266, 'max_iter': 1322}. Best is trial 188 with value: 0.9496578971395401.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 188. Best value: 0.949658:  42%|██████████████████████████████████████████████▍                                                               | 211/500 [18:09<25:37,  5.32s/it]

[I 2026-05-19 17:55:48,818] Trial 213 finished with value: 0.9496344025046206 and parameters: {'solver': 'saga', 'C': 0.00017209293703860385, 'l1_ratio': 0.28037757173476247, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004543983487598312, 'max_iter': 1317}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  42%|██████████████████████████████████████████████▋                                                               | 212/500 [18:10<19:17,  4.02s/it]

[I 2026-05-19 17:55:49,791] Trial 212 finished with value: 0.9496369560644752 and parameters: {'solver': 'saga', 'C': 0.0001600771183446671, 'l1_ratio': 0.29151947501533376, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004202376892066333, 'max_iter': 1303}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  43%|██████████████████████████████████████████████▊                                                               | 213/500 [18:15<20:06,  4.20s/it]

[I 2026-05-19 17:55:54,429] Trial 217 finished with value: 0.9496396538170895 and parameters: {'solver': 'saga', 'C': 0.00022617835300568713, 'l1_ratio': 0.27914810911734933, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004503560208681297, 'max_iter': 1115}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  43%|███████████████████████████████████████████████                                                               | 214/500 [18:17<17:56,  3.77s/it]

[I 2026-05-19 17:55:57,168] Trial 218 finished with value: 0.9496369879764563 and parameters: {'solver': 'saga', 'C': 0.0002283982138552054, 'l1_ratio': 0.27265261190308254, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004412415264094361, 'max_iter': 1141}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  43%|███████████████████████████████████████████████▎                                                              | 215/500 [18:19<14:19,  3.02s/it]

[I 2026-05-19 17:55:58,444] Trial 214 finished with value: 0.9496315316802285 and parameters: {'solver': 'saga', 'C': 0.0001639701903929834, 'l1_ratio': 0.2787634110135021, 'class_weight': None, 'fit_intercept': True, 'tol': 7.610921317309896e-05, 'max_iter': 1291}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  43%|███████████████████████████████████████████████▌                                                              | 216/500 [18:20<12:17,  2.60s/it]

[I 2026-05-19 17:56:00,044] Trial 215 finished with value: 0.9496321667456676 and parameters: {'solver': 'saga', 'C': 0.0001642559166554879, 'l1_ratio': 0.27980037312880524, 'class_weight': None, 'fit_intercept': True, 'tol': 8.060600962617579e-05, 'max_iter': 1318}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 188. Best value: 0.949658:  43%|███████████████████████████████████████████████▋                                                              | 217/500 [18:20<08:51,  1.88s/it]

[I 2026-05-19 17:56:00,257] Trial 216 finished with value: 0.9496355788069349 and parameters: {'solver': 'saga', 'C': 0.0001825496046710389, 'l1_ratio': 0.27843209249421014, 'class_weight': None, 'fit_intercept': True, 'tol': 7.685997364808925e-05, 'max_iter': 1314}. Best is trial 188 with value: 0.9496578971395401.

Best trial: 220. Best value: 0.949659:  44%|███████████████████████████████████████████████▉                                                              | 218/500 [18:23<09:03,  1.93s/it]

[I 2026-05-19 17:56:02,286] Trial 220 finished with value: 0.9496589060403153 and parameters: {'solver': 'saga', 'C': 0.00023159681349152323, 'l1_ratio': 0.3479193493462983, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004483022104971438, 'max_iter': 1096}. Best is trial 220 with value: 0.9496589060403153.

Best trial: 220. Best value: 0.949659:  44%|████████████████████████████████████████████████▏                                                             | 219/500 [18:25<09:55,  2.12s/it]

[I 2026-05-19 17:56:04,867] Trial 221 finished with value: 0.949656579758465 and parameters: {'solver': 'saga', 'C': 0.00025630236903029273, 'l1_ratio': 0.34771573212870976, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006041472429070749, 'max_iter': 1097}. Best is trial 220 with value: 0.9496589060403153.

Best trial: 219. Best value: 0.94966:  44%|████████████████████████████████████████████████▊                                                              | 220/500 [18:26<07:43,  1.66s/it]

[I 2026-05-19 17:56:05,448] Trial 219 finished with value: 0.9496602091935532 and parameters: {'solver': 'saga', 'C': 0.00022990166871802325, 'l1_ratio': 0.35577193648644956, 'class_weight': None, 'fit_intercept': True, 'tol': 5.1302902158447696e-05, 'max_iter': 1159}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  44%|█████████████████████████████████████████████████                                                              | 221/500 [18:44<30:23,  6.53s/it]

[I 2026-05-19 17:56:23,366] Trial 222 finished with value: 0.9496580701106172 and parameters: {'solver': 'saga', 'C': 0.00024388070475742988, 'l1_ratio': 0.3476710602676947, 'class_weight': None, 'fit_intercept': True, 'tol': 5.3884166062344934e-05, 'max_iter': 1108}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  44%|█████████████████████████████████████████████████▎                                                             | 222/500 [18:45<22:53,  4.94s/it]

[I 2026-05-19 17:56:24,573] Trial 223 finished with value: 0.9496577501530894 and parameters: {'solver': 'saga', 'C': 0.000248967259597924, 'l1_ratio': 0.3496217171048823, 'class_weight': None, 'fit_intercept': True, 'tol': 5.12000921968114e-05, 'max_iter': 1094}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  45%|█████████████████████████████████████████████████▌                                                             | 223/500 [18:46<17:55,  3.88s/it]

[I 2026-05-19 17:56:25,998] Trial 228 finished with value: 0.9496581792698144 and parameters: {'solver': 'saga', 'C': 0.0002463950808179332, 'l1_ratio': 0.35021073259511104, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005667152133097277, 'max_iter': 1094}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  45%|█████████████████████████████████████████████████▋                                                             | 224/500 [18:50<17:40,  3.84s/it]

[I 2026-05-19 17:56:29,751] Trial 225 finished with value: 0.9496578178275106 and parameters: {'solver': 'saga', 'C': 0.00025002805138593567, 'l1_ratio': 0.3511767698918777, 'class_weight': None, 'fit_intercept': True, 'tol': 4.652627017499324e-05, 'max_iter': 1103}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  45%|█████████████████████████████████████████████████▉                                                             | 225/500 [18:51<13:41,  2.99s/it]

[I 2026-05-19 17:56:30,741] Trial 224 finished with value: 0.9496563564135879 and parameters: {'solver': 'saga', 'C': 0.0002575123023078704, 'l1_ratio': 0.34585996840457156, 'class_weight': None, 'fit_intercept': True, 'tol': 5.354192551964126e-05, 'max_iter': 1119}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  45%|██████████████████████████████████████████████████▏                                                            | 226/500 [18:53<12:42,  2.78s/it]

[I 2026-05-19 17:56:33,026] Trial 226 finished with value: 0.9496589631495039 and parameters: {'solver': 'saga', 'C': 0.0002353969310427571, 'l1_ratio': 0.35033463554452376, 'class_weight': None, 'fit_intercept': True, 'tol': 5.216898480864366e-05, 'max_iter': 1097}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  45%|██████████████████████████████████████████████████▍                                                            | 227/500 [18:56<12:18,  2.70s/it]

[I 2026-05-19 17:56:35,566] Trial 227 finished with value: 0.9496567671626961 and parameters: {'solver': 'saga', 'C': 0.0002594623056571482, 'l1_ratio': 0.3503248640159707, 'class_weight': None, 'fit_intercept': True, 'tol': 5.255140681819602e-05, 'max_iter': 1223}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  46%|██████████████████████████████████████████████████▌                                                            | 228/500 [18:56<09:16,  2.05s/it]

[I 2026-05-19 17:56:36,076] Trial 229 finished with value: 0.9496567484514703 and parameters: {'solver': 'saga', 'C': 0.0002575127634044805, 'l1_ratio': 0.3483197735653847, 'class_weight': None, 'fit_intercept': True, 'tol': 5.41868862369412e-05, 'max_iter': 1222}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  46%|██████████████████████████████████████████████████▊                                                            | 229/500 [18:59<09:35,  2.12s/it]

[I 2026-05-19 17:56:38,392] Trial 230 finished with value: 0.9496560026266809 and parameters: {'solver': 'saga', 'C': 0.0002667290102286341, 'l1_ratio': 0.3486482698403378, 'class_weight': None, 'fit_intercept': True, 'tol': 4.979185371221127e-05, 'max_iter': 1094}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  46%|███████████████████████████████████████████████████                                                            | 230/500 [19:00<08:52,  1.97s/it]

[I 2026-05-19 17:56:40,009] Trial 231 finished with value: 0.9496596146364134 and parameters: {'solver': 'saga', 'C': 0.00023201354032341417, 'l1_ratio': 0.35296603007564736, 'class_weight': None, 'fit_intercept': True, 'tol': 5.690790806784023e-05, 'max_iter': 1079}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  46%|███████████████████████████████████████████████████▎                                                           | 231/500 [19:17<28:38,  6.39s/it]

[I 2026-05-19 17:56:56,695] Trial 232 finished with value: 0.9496584502973061 and parameters: {'solver': 'saga', 'C': 0.0002516470916385946, 'l1_ratio': 0.35982171501547555, 'class_weight': None, 'fit_intercept': True, 'tol': 5.57264789434108e-05, 'max_iter': 1093}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  46%|███████████████████████████████████████████████████▌                                                           | 232/500 [19:20<23:40,  5.30s/it]

[I 2026-05-19 17:56:59,464] Trial 233 finished with value: 0.9496574038303027 and parameters: {'solver': 'saga', 'C': 0.0002498136011432456, 'l1_ratio': 0.34775537232072823, 'class_weight': None, 'fit_intercept': True, 'tol': 4.969779431029275e-05, 'max_iter': 1214}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  47%|███████████████████████████████████████████████████▋                                                           | 233/500 [19:22<19:29,  4.38s/it]

[I 2026-05-19 17:57:01,700] Trial 234 finished with value: 0.9496570017151811 and parameters: {'solver': 'saga', 'C': 0.00025230672396829617, 'l1_ratio': 0.346220967596608, 'class_weight': None, 'fit_intercept': True, 'tol': 4.766031215368171e-05, 'max_iter': 1106}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  47%|███████████████████████████████████████████████████▉                                                           | 234/500 [19:24<16:43,  3.77s/it]

[I 2026-05-19 17:57:04,045] Trial 235 finished with value: 0.9496594682622218 and parameters: {'solver': 'saga', 'C': 0.00024077615231958191, 'l1_ratio': 0.35799984359105846, 'class_weight': None, 'fit_intercept': True, 'tol': 4.763435783921702e-05, 'max_iter': 1221}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  47%|████████████████████████████████████████████████████▏                                                          | 235/500 [19:26<13:20,  3.02s/it]

[I 2026-05-19 17:57:05,309] Trial 236 finished with value: 0.9495677129490229 and parameters: {'solver': 'saga', 'C': 7.978010869593823e-05, 'l1_ratio': 0.3550526727619516, 'class_weight': None, 'fit_intercept': True, 'tol': 5.052626618614363e-05, 'max_iter': 1100}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  47%|████████████████████████████████████████████████████▍                                                          | 236/500 [19:28<12:01,  2.73s/it]

[I 2026-05-19 17:57:07,363] Trial 237 finished with value: 0.9496592657177872 and parameters: {'solver': 'saga', 'C': 0.00023539562437471093, 'l1_ratio': 0.35214831263536145, 'class_weight': None, 'fit_intercept': True, 'tol': 4.30555770297351e-05, 'max_iter': 1098}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  47%|████████████████████████████████████████████████████▌                                                          | 237/500 [19:32<13:39,  3.12s/it]

[I 2026-05-19 17:57:11,384] Trial 238 finished with value: 0.9495702667152223 and parameters: {'solver': 'saga', 'C': 8.05962410821602e-05, 'l1_ratio': 0.35560816943117507, 'class_weight': None, 'fit_intercept': True, 'tol': 4.561520685846212e-05, 'max_iter': 1091}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  48%|████████████████████████████████████████████████████▊                                                          | 238/500 [19:32<10:01,  2.30s/it]

[I 2026-05-19 17:57:11,754] Trial 239 finished with value: 0.949532543612125 and parameters: {'solver': 'saga', 'C': 7.042737025990579e-05, 'l1_ratio': 0.35291701360648525, 'class_weight': None, 'fit_intercept': True, 'tol': 4.7399837016451536e-05, 'max_iter': 1095}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  48%|█████████████████████████████████████████████████████                                                          | 239/500 [19:35<10:58,  2.52s/it]

[I 2026-05-19 17:57:14,816] Trial 241 finished with value: 0.949563866280864 and parameters: {'solver': 'saga', 'C': 7.860405763571704e-05, 'l1_ratio': 0.35433789216401856, 'class_weight': None, 'fit_intercept': True, 'tol': 4.909156721706203e-05, 'max_iter': 1090}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  48%|█████████████████████████████████████████████████████▎                                                         | 240/500 [19:35<07:55,  1.83s/it]

[I 2026-05-19 17:57:15,004] Trial 240 finished with value: 0.9495341055750576 and parameters: {'solver': 'saga', 'C': 7.092702038783355e-05, 'l1_ratio': 0.3550176479898778, 'class_weight': None, 'fit_intercept': True, 'tol': 4.6999489397277805e-05, 'max_iter': 1075}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  48%|█████████████████████████████████████████████████████▌                                                         | 241/500 [19:52<26:53,  6.23s/it]

[I 2026-05-19 17:57:31,474] Trial 242 finished with value: 0.9496522706178533 and parameters: {'solver': 'saga', 'C': 0.000146162708334122, 'l1_ratio': 0.3560710070253822, 'class_weight': None, 'fit_intercept': True, 'tol': 4.7636195906501514e-05, 'max_iter': 1098}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  48%|█████████████████████████████████████████████████████▋                                                         | 242/500 [19:59<27:52,  6.48s/it]

[I 2026-05-19 17:57:38,569] Trial 243 finished with value: 0.9496487133136515 and parameters: {'solver': 'saga', 'C': 0.00013811043338238265, 'l1_ratio': 0.35203445054246046, 'class_weight': None, 'fit_intercept': True, 'tol': 4.8478722767842415e-05, 'max_iter': 1199}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  49%|█████████████████████████████████████████████████████▉                                                         | 243/500 [20:02<23:20,  5.45s/it]

[I 2026-05-19 17:57:41,624] Trial 245 finished with value: 0.94965010822446 and parameters: {'solver': 'saga', 'C': 0.00014123562110943794, 'l1_ratio': 0.35531477272031226, 'class_weight': None, 'fit_intercept': True, 'tol': 4.7948815899539475e-05, 'max_iter': 1223}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  49%|██████████████████████████████████████████████████████▏                                                        | 244/500 [20:04<19:31,  4.58s/it]

[I 2026-05-19 17:57:44,171] Trial 246 finished with value: 0.9496506476488772 and parameters: {'solver': 'saga', 'C': 0.00014303548620437135, 'l1_ratio': 0.35978810719820287, 'class_weight': None, 'fit_intercept': True, 'tol': 3.6474071093111755e-05, 'max_iter': 1227}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  49%|██████████████████████████████████████████████████████▍                                                        | 245/500 [20:07<16:27,  3.87s/it]

[I 2026-05-19 17:57:46,399] Trial 247 finished with value: 0.949649301702174 and parameters: {'solver': 'saga', 'C': 0.00013906432095934826, 'l1_ratio': 0.35720275058564344, 'class_weight': None, 'fit_intercept': True, 'tol': 4.576731809052744e-05, 'max_iter': 1200}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  49%|██████████████████████████████████████████████████████▌                                                        | 246/500 [20:10<15:13,  3.59s/it]

[I 2026-05-19 17:57:49,357] Trial 248 finished with value: 0.9496535410837564 and parameters: {'solver': 'saga', 'C': 0.00015095975817656855, 'l1_ratio': 0.3483928048534742, 'class_weight': None, 'fit_intercept': True, 'tol': 3.399924698317578e-05, 'max_iter': 1215}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  49%|██████████████████████████████████████████████████████▊                                                        | 247/500 [20:10<11:36,  2.75s/it]

[I 2026-05-19 17:57:50,141] Trial 249 finished with value: 0.9496485029864763 and parameters: {'solver': 'saga', 'C': 0.00013694318555217532, 'l1_ratio': 0.35780391293190184, 'class_weight': None, 'fit_intercept': True, 'tol': 3.290622586086365e-05, 'max_iter': 1226}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  50%|███████████████████████████████████████████████████████                                                        | 248/500 [20:13<11:15,  2.68s/it]

[I 2026-05-19 17:57:52,652] Trial 251 finished with value: 0.9496460103650108 and parameters: {'solver': 'saga', 'C': 0.00013313813187424832, 'l1_ratio': 0.34866132590062526, 'class_weight': None, 'fit_intercept': True, 'tol': 3.6891617504151426e-05, 'max_iter': 1216}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  50%|███████████████████████████████████████████████████████▎                                                       | 249/500 [20:15<10:18,  2.47s/it]

[I 2026-05-19 17:57:54,614] Trial 250 finished with value: 0.9496507794073829 and parameters: {'solver': 'saga', 'C': 0.00014400270836588427, 'l1_ratio': 0.34886732876369225, 'class_weight': None, 'fit_intercept': True, 'tol': 3.577765336912484e-05, 'max_iter': 1231}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  50%|███████████████████████████████████████████████████████▌                                                       | 250/500 [20:26<20:49,  5.00s/it]

[I 2026-05-19 17:58:05,529] Trial 259 pruned.

Best trial: 219. Best value: 0.94966:  50%|███████████████████████████████████████████████████████▋                                                       | 251/500 [20:27<15:49,  3.81s/it]

[I 2026-05-19 17:58:06,580] Trial 252 finished with value: 0.9496527072287032 and parameters: {'solver': 'saga', 'C': 0.0001486199832736536, 'l1_ratio': 0.3482807607452723, 'class_weight': None, 'fit_intercept': True, 'tol': 3.63747397343234e-05, 'max_iter': 1220}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  50%|███████████████████████████████████████████████████████▉                                                       | 252/500 [20:29<13:17,  3.22s/it]

[I 2026-05-19 17:58:08,376] Trial 260 pruned.

Best trial: 219. Best value: 0.94966:  51%|████████████████████████████████████████████████████████▏                                                      | 253/500 [20:30<10:29,  2.55s/it]

[I 2026-05-19 17:58:09,383] Trial 255 finished with value: 0.949640791720533 and parameters: {'solver': 'saga', 'C': 0.0005874501962006619, 'l1_ratio': 0.3458010778119442, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005739643564899872, 'max_iter': 1219}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  51%|████████████████████████████████████████████████████████▍                                                      | 254/500 [20:35<13:51,  3.38s/it]

[I 2026-05-19 17:58:14,711] Trial 253 finished with value: 0.9496486638656035 and parameters: {'solver': 'saga', 'C': 0.0001403353699980376, 'l1_ratio': 0.3454611626215874, 'class_weight': None, 'fit_intercept': True, 'tol': 3.4765135706830996e-05, 'max_iter': 1218}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  51%|████████████████████████████████████████████████████████▌                                                      | 255/500 [20:35<10:10,  2.49s/it]

[I 2026-05-19 17:58:15,121] Trial 257 finished with value: 0.949658933625839 and parameters: {'solver': 'saga', 'C': 0.0002077156003663377, 'l1_ratio': 0.34132555755612565, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005845066949849476, 'max_iter': 1002}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  51%|████████████████████████████████████████████████████████▊                                                      | 256/500 [20:36<07:55,  1.95s/it]

[I 2026-05-19 17:58:15,800] Trial 258 finished with value: 0.9496586678383665 and parameters: {'solver': 'saga', 'C': 0.0002126836260394504, 'l1_ratio': 0.34079670602819945, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007084080801513127, 'max_iter': 1010}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  51%|█████████████████████████████████████████████████████████                                                      | 257/500 [20:39<08:41,  2.15s/it]

[I 2026-05-19 17:58:18,416] Trial 254 finished with value: 0.9496597726717043 and parameters: {'solver': 'saga', 'C': 0.0002046804614385418, 'l1_ratio': 0.3466916014634126, 'class_weight': None, 'fit_intercept': True, 'tol': 2.941871117964168e-05, 'max_iter': 1218}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  52%|█████████████████████████████████████████████████████████▎                                                     | 258/500 [20:44<12:25,  3.08s/it]

[I 2026-05-19 17:58:23,669] Trial 256 finished with value: 0.9496587380855139 and parameters: {'solver': 'saga', 'C': 0.00020505705911256426, 'l1_ratio': 0.340478984933505, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5971514598208266e-05, 'max_iter': 1227}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  52%|█████████████████████████████████████████████████████████▍                                                     | 259/500 [20:57<24:32,  6.11s/it]

[I 2026-05-19 17:58:36,852] Trial 261 finished with value: 0.9496387043068018 and parameters: {'solver': 'saga', 'C': 0.0005978517704995625, 'l1_ratio': 0.3048386397872559, 'class_weight': None, 'fit_intercept': True, 'tol': 5.962216248123767e-05, 'max_iter': 1127}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  52%|█████████████████████████████████████████████████████████▋                                                     | 260/500 [20:59<19:20,  4.83s/it]

[I 2026-05-19 17:58:38,709] Trial 262 finished with value: 0.9496411762900973 and parameters: {'solver': 'saga', 'C': 0.0006115476725765412, 'l1_ratio': 0.3698492937692669, 'class_weight': None, 'fit_intercept': True, 'tol': 5.9949768997572914e-05, 'max_iter': 1141}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  52%|█████████████████████████████████████████████████████████▉                                                     | 261/500 [21:01<15:59,  4.02s/it]

[I 2026-05-19 17:58:40,814] Trial 263 finished with value: 0.9496472426340438 and parameters: {'solver': 'saga', 'C': 0.00026393216177465176, 'l1_ratio': 0.3026871378089571, 'class_weight': None, 'fit_intercept': True, 'tol': 6.284466495777145e-05, 'max_iter': 1000}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  52%|██████████████████████████████████████████████████████████▏                                                    | 262/500 [21:03<13:01,  3.28s/it]

[I 2026-05-19 17:58:42,386] Trial 264 finished with value: 0.9496471829396768 and parameters: {'solver': 'saga', 'C': 0.0002673963329082513, 'l1_ratio': 0.3030850638082183, 'class_weight': None, 'fit_intercept': True, 'tol': 5.659851392221925e-05, 'max_iter': 1140}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  53%|██████████████████████████████████████████████████████████▍                                                    | 263/500 [21:08<15:34,  3.94s/it]

[I 2026-05-19 17:58:47,869] Trial 266 finished with value: 0.9496459305836533 and parameters: {'solver': 'saga', 'C': 0.00029111424114568977, 'l1_ratio': 0.3025735564184731, 'class_weight': None, 'fit_intercept': True, 'tol': 6.017070681807057e-05, 'max_iter': 1133}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  53%|██████████████████████████████████████████████████████████▌                                                    | 264/500 [21:09<11:39,  2.97s/it]

[I 2026-05-19 17:58:48,543] Trial 265 finished with value: 0.9496461488757237 and parameters: {'solver': 'saga', 'C': 0.0002851158053027171, 'l1_ratio': 0.302117993632552, 'class_weight': None, 'fit_intercept': True, 'tol': 5.9849453052643784e-05, 'max_iter': 1004}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  53%|██████████████████████████████████████████████████████████▊                                                    | 265/500 [21:10<09:23,  2.40s/it]

[I 2026-05-19 17:58:49,632] Trial 267 finished with value: 0.9496548670871198 and parameters: {'solver': 'saga', 'C': 0.00029526037375434593, 'l1_ratio': 0.36981223184123024, 'class_weight': None, 'fit_intercept': True, 'tol': 5.5451841154004605e-05, 'max_iter': 1129}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  53%|███████████████████████████████████████████████████████████                                                    | 266/500 [21:13<10:12,  2.62s/it]

[I 2026-05-19 17:58:52,759] Trial 268 finished with value: 0.94965421674329 and parameters: {'solver': 'saga', 'C': 0.00030474410619349206, 'l1_ratio': 0.36987935695669877, 'class_weight': None, 'fit_intercept': True, 'tol': 5.989986674702037e-05, 'max_iter': 1003}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  53%|███████████████████████████████████████████████████████████▎                                                   | 267/500 [21:33<30:10,  7.77s/it]

[I 2026-05-19 17:59:12,556] Trial 270 finished with value: 0.9496531029673212 and parameters: {'solver': 'saga', 'C': 0.0003112886501196644, 'l1_ratio': 0.4057341259191598, 'class_weight': None, 'fit_intercept': True, 'tol': 2.671368424234311e-05, 'max_iter': 1140}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  54%|███████████████████████████████████████████████████████████▍                                                   | 268/500 [21:33<21:44,  5.62s/it]

[I 2026-05-19 17:59:13,166] Trial 271 finished with value: 0.949653207238552 and parameters: {'solver': 'saga', 'C': 0.0003129066126613531, 'l1_ratio': 0.40151364452863453, 'class_weight': None, 'fit_intercept': True, 'tol': 2.747729807232942e-05, 'max_iter': 1037}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  54%|███████████████████████████████████████████████████████████▋                                                   | 269/500 [21:38<20:26,  5.31s/it]

[I 2026-05-19 17:59:17,743] Trial 272 finished with value: 0.9496513076069739 and parameters: {'solver': 'saga', 'C': 0.0003356594741271825, 'l1_ratio': 0.41023109325798657, 'class_weight': None, 'fit_intercept': True, 'tol': 2.3558221282662503e-05, 'max_iter': 1137}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 219. Best value: 0.94966:  54%|███████████████████████████████████████████████████████████▉                                                   | 270/500 [21:39<14:53,  3.88s/it]

[I 2026-05-19 17:59:18,297] Trial 273 finished with value: 0.9496092650559989 and parameters: {'solver': 'saga', 'C': 0.0001969256422034966, 'l1_ratio': 0.4122784864803993, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.8680221384182375e-05, 'max_iter': 1002}. Best is trial 219 with value: 0.9496602091935532.

Best trial: 274. Best value: 0.949662:  54%|███████████████████████████████████████████████████████████▌                                                  | 271/500 [21:44<16:08,  4.23s/it]

[I 2026-05-19 17:59:23,314] Trial 275 finished with value: 0.949609489689677 and parameters: {'solver': 'saga', 'C': 0.00019698410920375008, 'l1_ratio': 0.3670386862453708, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.5199886656657716e-05, 'max_iter': 1081}. Best is trial 219 with value: 0.9496602091935532.
[I 2026-05-19 17:59:23,359] Trial 274 finished with value: 0.9496616536313859 and parameters: {'solver': 'saga', 'C': 0.00020408872596850848, 'l1_ratio': 0.3651169574174175, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9151725247292587e-05, 'max_iter': 1054}. Best is trial 274 with value: 0.9496616536313859.

Best trial: 274. Best value: 0.949662:  55%|████████████████████████████████████████████████████████████                                                  | 273/500 [21:44<09:19,  2.47s/it]

[I 2026-05-19 17:59:24,158] Trial 276 finished with value: 0.9496079375167035 and parameters: {'solver': 'saga', 'C': 0.0002039155868495804, 'l1_ratio': 0.41097655556704193, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.3492402913529385e-05, 'max_iter': 1065}. Best is trial 274 with value: 0.9496616536313859.

Best trial: 274. Best value: 0.949662:  55%|████████████████████████████████████████████████████████████▎                                                 | 274/500 [21:48<10:34,  2.81s/it]

[I 2026-05-19 17:59:27,995] Trial 277 finished with value: 0.9496106700283065 and parameters: {'solver': 'saga', 'C': 0.00019047171679268865, 'l1_ratio': 0.4124256106808609, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.799938389074269e-05, 'max_iter': 1071}. Best is trial 274 with value: 0.9496616536313859.

Best trial: 274. Best value: 0.949662:  55%|████████████████████████████████████████████████████████████▌                                                 | 275/500 [21:59<17:58,  4.79s/it]

[I 2026-05-19 17:59:38,395] Trial 278 finished with value: 0.949609605852662 and parameters: {'solver': 'saga', 'C': 0.00019771802545338616, 'l1_ratio': 0.4079549054710283, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.000639058057103476, 'max_iter': 1413}. Best is trial 274 with value: 0.9496616536313859.

Best trial: 274. Best value: 0.949662:  55%|████████████████████████████████████████████████████████████▋                                                 | 276/500 [22:01<15:32,  4.16s/it]

[I 2026-05-19 17:59:40,878] Trial 279 finished with value: 0.9496140739935294 and parameters: {'solver': 'saga', 'C': 4.97769659950825, 'l1_ratio': 0.3714047930686595, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0006934285226396488, 'max_iter': 1065}. Best is trial 274 with value: 0.9496616536313859.

Best trial: 274. Best value: 0.949662:  55%|████████████████████████████████████████████████████████████▉                                                 | 277/500 [22:02<12:19,  3.32s/it]

[I 2026-05-19 17:59:42,009] Trial 280 finished with value: 0.9496084206302562 and parameters: {'solver': 'saga', 'C': 0.00020083133306978337, 'l1_ratio': 0.3696387360382332, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0006844430617410891, 'max_iter': 1398}. Best is trial 274 with value: 0.9496616536313859.

Best trial: 281. Best value: 0.949662:  56%|█████████████████████████████████████████████████████████████▏                                                | 278/500 [22:04<10:55,  2.95s/it]

[I 2026-05-19 17:59:44,051] Trial 281 finished with value: 0.9496617014459682 and parameters: {'solver': 'saga', 'C': 0.0002008790662843274, 'l1_ratio': 0.3670705188737767, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000689628586150852, 'max_iter': 1428}. Best is trial 281 with value: 0.9496617014459682.

Best trial: 281. Best value: 0.949662:  56%|█████████████████████████████████████████████████████████████▍                                                | 279/500 [22:09<12:59,  3.53s/it]

[I 2026-05-19 17:59:48,998] Trial 282 finished with value: 0.9496579214586497 and parameters: {'solver': 'saga', 'C': 0.00019800968912230427, 'l1_ratio': 0.33648172171035556, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006581135207466759, 'max_iter': 1414}. Best is trial 281 with value: 0.9496617014459682.

Best trial: 281. Best value: 0.949662:  56%|█████████████████████████████████████████████████████████████▌                                                | 280/500 [22:10<09:31,  2.60s/it]

[I 2026-05-19 17:59:49,340] Trial 284 finished with value: 0.9496598771847087 and parameters: {'solver': 'saga', 'C': 0.00017705162674916045, 'l1_ratio': 0.3675644098301525, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007394625425125478, 'max_iter': 1204}. Best is trial 281 with value: 0.9496617014459682.

Best trial: 285. Best value: 0.949662:  56%|█████████████████████████████████████████████████████████████▊                                                | 281/500 [22:13<10:30,  2.88s/it]

[I 2026-05-19 17:59:52,893] Trial 285 finished with value: 0.9496617416270915 and parameters: {'solver': 'saga', 'C': 0.00020125600856227033, 'l1_ratio': 0.3685219510175683, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007325115937962414, 'max_iter': 1404}. Best is trial 285 with value: 0.9496617416270915.

Best trial: 285. Best value: 0.949662:  56%|██████████████████████████████████████████████████████████████                                                | 282/500 [22:20<14:54,  4.10s/it]

[I 2026-05-19 17:59:59,897] Trial 283 finished with value: 0.9496616736088098 and parameters: {'solver': 'saga', 'C': 0.0001935666609536709, 'l1_ratio': 0.3676222057553429, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9529193573489478e-05, 'max_iter': 1413}. Best is trial 285 with value: 0.9496617416270915.

Best trial: 285. Best value: 0.949662:  57%|██████████████████████████████████████████████████████████████▎                                               | 283/500 [22:29<19:31,  5.40s/it]

[I 2026-05-19 18:00:08,360] Trial 288 finished with value: 0.949622835949936 and parameters: {'solver': 'saga', 'C': 0.00010772681642900356, 'l1_ratio': 0.3364470878150203, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0004937799312186292, 'max_iter': 1255}. Best is trial 285 with value: 0.9496617416270915.

Best trial: 285. Best value: 0.949662:  57%|██████████████████████████████████████████████████████████████▍                                               | 284/500 [22:33<17:53,  4.97s/it]

[I 2026-05-19 18:00:12,318] Trial 290 finished with value: 0.9495952914273476 and parameters: {'solver': 'saga', 'C': 9.244007929125546e-05, 'l1_ratio': 0.33232883377456623, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009607323868602392, 'max_iter': 1479}. Best is trial 285 with value: 0.9496617416270915.

Best trial: 285. Best value: 0.949662:  57%|██████████████████████████████████████████████████████████████▋                                               | 285/500 [22:35<15:32,  4.34s/it]

[I 2026-05-19 18:00:15,183] Trial 287 finished with value: 0.9496299634842302 and parameters: {'solver': 'saga', 'C': 74.15014237049812, 'l1_ratio': 0.3658264666408835, 'class_weight': None, 'fit_intercept': True, 'tol': 4.084124460373853e-05, 'max_iter': 1252}. Best is trial 285 with value: 0.9496617416270915.

Best trial: 285. Best value: 0.949662:  57%|██████████████████████████████████████████████████████████████▉                                               | 286/500 [22:36<12:01,  3.37s/it]

[I 2026-05-19 18:00:16,285] Trial 286 finished with value: 0.9496095532737957 and parameters: {'solver': 'saga', 'C': 9.710081261726509e-05, 'l1_ratio': 0.3667585095271445, 'class_weight': None, 'fit_intercept': True, 'tol': 1.883074956562754e-05, 'max_iter': 1247}. Best is trial 285 with value: 0.9496617416270915.

Best trial: 289. Best value: 0.949724:  57%|███████████████████████████████████████████████████████████████▏                                              | 287/500 [22:39<11:12,  3.16s/it]

[I 2026-05-19 18:00:18,941] Trial 292 finished with value: 0.9496103544466562 and parameters: {'solver': 'saga', 'C': 0.00010116759255896647, 'l1_ratio': 0.3894521730828471, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0005307228386980096, 'max_iter': 1471}. Best is trial 285 with value: 0.9496617416270915.
[I 2026-05-19 18:00:18,944] Trial 289 finished with value: 0.9497237717175612 and parameters: {'solver': 'saga', 'C': 8.90658714927694e-05, 'l1_ratio': 0.9213411778078824, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7149287235241646e-05, 'max_iter': 1264}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 289. Best value: 0.949724:  58%|███████████████████████████████████████████████████████████████▌                                              | 289/500 [22:44<09:44,  2.77s/it]

[I 2026-05-19 18:00:23,568] Trial 291 finished with value: 0.9496585548281242 and parameters: {'solver': 'saga', 'C': 0.0001720117068861565, 'l1_ratio': 0.37226466118796825, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8318981690297686e-05, 'max_iter': 1466}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 289. Best value: 0.949724:  58%|███████████████████████████████████████████████████████████████▊                                              | 290/500 [22:53<15:08,  4.33s/it]

[I 2026-05-19 18:00:32,626] Trial 294 finished with value: 0.9496125397470788 and parameters: {'solver': 'saga', 'C': 9.895489026827041e-05, 'l1_ratio': 0.3707371828588911, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010105328719170238, 'max_iter': 1364}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 289. Best value: 0.949724:  58%|████████████████████████████████████████████████████████████████                                              | 291/500 [22:55<12:39,  3.63s/it]

[I 2026-05-19 18:00:34,292] Trial 293 finished with value: 0.9496152838422948 and parameters: {'solver': 'saga', 'C': 0.00010103754840984704, 'l1_ratio': 0.37351804585183523, 'class_weight': None, 'fit_intercept': True, 'tol': 1.7895798725714675e-05, 'max_iter': 1392}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 289. Best value: 0.949724:  58%|████████████████████████████████████████████████████████████████▏                                             | 292/500 [22:56<11:01,  3.18s/it]

[I 2026-05-19 18:00:36,259] Trial 299 pruned.

Best trial: 289. Best value: 0.949724:  59%|████████████████████████████████████████████████████████████████▍                                             | 293/500 [22:58<09:26,  2.74s/it]

[I 2026-05-19 18:00:37,857] Trial 298 pruned.

Best trial: 289. Best value: 0.949724:  59%|████████████████████████████████████████████████████████████████▋                                             | 294/500 [23:08<16:03,  4.68s/it]

[I 2026-05-19 18:00:47,382] Trial 295 finished with value: 0.949599273800095 and parameters: {'solver': 'saga', 'C': 9.271920369449425e-05, 'l1_ratio': 0.3720532708791234, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8347395405943538e-05, 'max_iter': 1438}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 289. Best value: 0.949724:  59%|████████████████████████████████████████████████████████████████▉                                             | 295/500 [23:10<13:21,  3.91s/it]

[I 2026-05-19 18:00:49,417] Trial 296 finished with value: 0.9496669866188014 and parameters: {'solver': 'saga', 'C': 0.00010358724819264877, 'l1_ratio': 0.8656022467005543, 'class_weight': None, 'fit_intercept': True, 'tol': 1.8721375983917685e-05, 'max_iter': 1477}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 289. Best value: 0.949724:  59%|█████████████████████████████████████████████████████████████████▎                                            | 297/500 [23:12<08:34,  2.54s/it]

[I 2026-05-19 18:00:52,044] Trial 300 finished with value: 0.9494492865506103 and parameters: {'solver': 'saga', 'C': 4.580703451575498e-05, 'l1_ratio': 0.9021101414238026, 'class_weight': None, 'fit_intercept': False, 'tol': 1.4250613532930824e-05, 'max_iter': 1383}. Best is trial 289 with value: 0.9497237717175612.
[I 2026-05-19 18:00:52,203] Trial 297 finished with value: 0.9496553861720276 and parameters: {'solver': 'saga', 'C': 0.0001700020873288564, 'l1_ratio': 0.3899852479226312, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3654911318167698e-05, 'max_iter': 1519}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 289. Best value: 0.949724:  60%|█████████████████████████████████████████████████████████████████▌                                            | 298/500 [23:13<06:33,  1.95s/it]

[I 2026-05-19 18:00:52,762] Trial 302 pruned.

Best trial: 289. Best value: 0.949724:  60%|█████████████████████████████████████████████████████████████████▊                                            | 299/500 [23:21<12:14,  3.65s/it]

[I 2026-05-19 18:01:00,428] Trial 304 finished with value: 0.9489767097156694 and parameters: {'solver': 'saga', 'C': 2.6284727580092638e-05, 'l1_ratio': 0.38325950204190296, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001295060752997833, 'max_iter': 1449}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 289. Best value: 0.949724:  60%|██████████████████████████████████████████████████████████████████                                            | 300/500 [23:25<12:29,  3.75s/it]

[I 2026-05-19 18:01:04,405] Trial 301 finished with value: 0.9493756281692749 and parameters: {'solver': 'saga', 'C': 4.8929306285125936e-05, 'l1_ratio': 0.8627470049742908, 'class_weight': None, 'fit_intercept': False, 'tol': 1.3084232681853308e-05, 'max_iter': 1531}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 289. Best value: 0.949724:  60%|██████████████████████████████████████████████████████████████████▏                                           | 301/500 [23:33<16:55,  5.10s/it]

[I 2026-05-19 18:01:12,677] Trial 303 finished with value: 0.9494274885172516 and parameters: {'solver': 'saga', 'C': 5.605791213044382e-05, 'l1_ratio': 0.3854500223207419, 'class_weight': None, 'fit_intercept': True, 'tol': 1.2310245857347423e-05, 'max_iter': 1530}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 289. Best value: 0.949724:  60%|██████████████████████████████████████████████████████████████████▍                                           | 302/500 [23:35<13:37,  4.13s/it]

[I 2026-05-19 18:01:14,527] Trial 309 finished with value: 0.9497220664648987 and parameters: {'solver': 'saga', 'C': 5.3011561610117045e-05, 'l1_ratio': 0.9310525183962644, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0012425787795488107, 'max_iter': 1581}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 289. Best value: 0.949724:  61%|██████████████████████████████████████████████████████████████████▋                                           | 303/500 [23:35<09:57,  3.03s/it]

[I 2026-05-19 18:01:14,994] Trial 307 finished with value: 0.9496611626873266 and parameters: {'solver': 'saga', 'C': 0.0001647537645277291, 'l1_ratio': 0.8513365635272605, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001116193766809584, 'max_iter': 1572}. Best is trial 289 with value: 0.9497237717175612.

Best trial: 308. Best value: 0.949732:  61%|██████████████████████████████████████████████████████████████████▉                                           | 304/500 [23:36<07:38,  2.34s/it]

[I 2026-05-19 18:01:15,716] Trial 308 finished with value: 0.949731650416623 and parameters: {'solver': 'saga', 'C': 5.9066121279773937e-05, 'l1_ratio': 0.9333427104953516, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000804879166604654, 'max_iter': 1552}. Best is trial 308 with value: 0.949731650416623.

Best trial: 308. Best value: 0.949732:  61%|███████████████████████████████████████████████████████████████████                                           | 305/500 [23:44<12:50,  3.95s/it]

[I 2026-05-19 18:01:23,425] Trial 306 finished with value: 0.9495728497161826 and parameters: {'solver': 'saga', 'C': 4.38568566457094e-05, 'l1_ratio': 0.8206424425862936, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0434160132887016e-05, 'max_iter': 1535}. Best is trial 308 with value: 0.949731650416623.

Best trial: 308. Best value: 0.949732:  61%|███████████████████████████████████████████████████████████████████▎                                          | 306/500 [23:44<09:30,  2.94s/it]

[I 2026-05-19 18:01:24,011] Trial 305 finished with value: 0.9496306396229853 and parameters: {'solver': 'saga', 'C': 0.00016785233357985614, 'l1_ratio': 0.7178537680614421, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1198938524042999e-05, 'max_iter': 1481}. Best is trial 308 with value: 0.949731650416623.

Best trial: 310. Best value: 0.949762:  61%|███████████████████████████████████████████████████████████████████▌                                          | 307/500 [23:53<14:41,  4.57s/it]

[I 2026-05-19 18:01:32,377] Trial 310 finished with value: 0.9497616997762798 and parameters: {'solver': 'saga', 'C': 5.053326874642945e-05, 'l1_ratio': 0.9645803251378251, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1058154783603676e-05, 'max_iter': 1552}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 310. Best value: 0.949762:  62%|███████████████████████████████████████████████████████████████████▊                                          | 308/500 [23:58<15:00,  4.69s/it]

[I 2026-05-19 18:01:37,365] Trial 313 finished with value: 0.9497140428628009 and parameters: {'solver': 'saga', 'C': 0.00012934334067730567, 'l1_ratio': 0.915915546033066, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001075556802835781, 'max_iter': 1573}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 310. Best value: 0.949762:  62%|███████████████████████████████████████████████████████████████████▉                                          | 309/500 [23:59<11:25,  3.59s/it]

[I 2026-05-19 18:01:38,371] Trial 315 finished with value: 0.9495862542709979 and parameters: {'solver': 'saga', 'C': 7.137481271990906e-05, 'l1_ratio': 0.7805223729641771, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0012716401049731737, 'max_iter': 1619}. Best is trial 310 with value: 0.9497616997762798.
[I 2026-05-19 18:01:38,574] Trial 314 finished with value: 0.9496209147604754 and parameters: {'solver': 'saga', 'C': 4.164021703635343e-05, 'l1_ratio': 0.8712506362028121, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011831725838946253, 'max_iter': 1564}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 310. Best value: 0.949762:  62%|████████████████████████████████████████████████████████████████████▍                                         | 311/500 [24:03<09:50,  3.12s/it]

[I 2026-05-19 18:01:42,992] Trial 311 finished with value: 0.9496985916659557 and parameters: {'solver': 'saga', 'C': 0.00017806149455571003, 'l1_ratio': 0.9686869253709256, 'class_weight': None, 'fit_intercept': True, 'tol': 1.060322350736982e-05, 'max_iter': 1297}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 310. Best value: 0.949762:  63%|████████████████████████████████████████████████████████████████████▊                                         | 313/500 [24:07<07:17,  2.34s/it]

[I 2026-05-19 18:01:46,610] Trial 316 finished with value: 0.9495722123851777 and parameters: {'solver': 'saga', 'C': 3.083786562532892e-05, 'l1_ratio': 0.881375030970037, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0007723691409813057, 'max_iter': 1453}. Best is trial 310 with value: 0.9497616997762798.
[I 2026-05-19 18:01:46,774] Trial 317 finished with value: 0.9496197382559881 and parameters: {'solver': 'saga', 'C': 2.450552807839252e-05, 'l1_ratio': 0.9033641693055228, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001138516718552792, 'max_iter': 1606}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 310. Best value: 0.949762:  63%|█████████████████████████████████████████████████████████████████████                                         | 314/500 [24:09<06:31,  2.11s/it]

[I 2026-05-19 18:01:48,328] Trial 312 finished with value: 0.9497008016300198 and parameters: {'solver': 'saga', 'C': 0.00015781486484032887, 'l1_ratio': 0.9288143693837806, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1183657528783645e-05, 'max_iter': 1285}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 310. Best value: 0.949762:  63%|█████████████████████████████████████████████████████████████████████▎                                        | 315/500 [24:16<11:46,  3.82s/it]

[I 2026-05-19 18:01:56,152] Trial 318 finished with value: 0.9497099284751933 and parameters: {'solver': 'saga', 'C': 2.6784581850977585e-05, 'l1_ratio': 0.9323733452054146, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010875565245316307, 'max_iter': 1629}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 310. Best value: 0.949762:  63%|█████████████████████████████████████████████████████████████████████▌                                        | 316/500 [24:20<11:35,  3.78s/it]

[I 2026-05-19 18:01:59,843] Trial 319 finished with value: 0.9496751384709053 and parameters: {'solver': 'saga', 'C': 1.7695110770391295e-05, 'l1_ratio': 0.9249155830439725, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011713006693434606, 'max_iter': 1627}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 310. Best value: 0.949762:  63%|█████████████████████████████████████████████████████████████████████▋                                        | 317/500 [24:21<09:12,  3.02s/it]

[I 2026-05-19 18:02:01,077] Trial 320 finished with value: 0.9497554049206567 and parameters: {'solver': 'saga', 'C': 3.89421234078322e-05, 'l1_ratio': 0.9938946004322544, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008699938762512521, 'max_iter': 1618}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 310. Best value: 0.949762:  64%|█████████████████████████████████████████████████████████████████████▉                                        | 318/500 [24:23<07:37,  2.52s/it]

[I 2026-05-19 18:02:02,411] Trial 321 finished with value: 0.9496781229485964 and parameters: {'solver': 'saga', 'C': 1.9256545571281043e-05, 'l1_ratio': 0.921891921401665, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00087942315451492, 'max_iter': 1667}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 310. Best value: 0.949762:  64%|██████████████████████████████████████████████████████████████████████▏                                       | 319/500 [24:27<09:27,  3.14s/it]

[I 2026-05-19 18:02:07,010] Trial 322 finished with value: 0.9497210707076548 and parameters: {'solver': 'saga', 'C': 6.208775540881234e-05, 'l1_ratio': 0.924150603239474, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008125987929067761, 'max_iter': 1359}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 310. Best value: 0.949762:  64%|██████████████████████████████████████████████████████████████████████▍                                       | 320/500 [24:29<07:49,  2.61s/it]

[I 2026-05-19 18:02:08,385] Trial 324 finished with value: 0.9497361248924395 and parameters: {'solver': 'saga', 'C': 1.239624358343685e-05, 'l1_ratio': 0.9838782146655383, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000831484231258819, 'max_iter': 1636}. Best is trial 310 with value: 0.9497616997762798.

Best trial: 326. Best value: 0.949767:  64%|██████████████████████████████████████████████████████████████████████▌                                       | 321/500 [24:38<14:03,  4.71s/it]

[I 2026-05-19 18:02:18,002] Trial 326 finished with value: 0.9497667555641287 and parameters: {'solver': 'saga', 'C': 3.227550763145778e-05, 'l1_ratio': 0.9871112280844829, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009196328517125791, 'max_iter': 1614}. Best is trial 326 with value: 0.9497667555641287.

Best trial: 326. Best value: 0.949767:  64%|██████████████████████████████████████████████████████████████████████▊                                       | 322/500 [24:40<11:08,  3.75s/it]

[I 2026-05-19 18:02:19,525] Trial 327 finished with value: 0.9497538620674988 and parameters: {'solver': 'saga', 'C': 1.9785023952956146e-05, 'l1_ratio': 0.9891770697338755, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009682339564899122, 'max_iter': 1692}. Best is trial 326 with value: 0.9497667555641287.

Best trial: 326. Best value: 0.949767:  65%|███████████████████████████████████████████████████████████████████████                                       | 323/500 [24:40<08:03,  2.73s/it]

[I 2026-05-19 18:02:19,862] Trial 323 finished with value: 0.9497657738136583 and parameters: {'solver': 'saga', 'C': 6.181345787590456e-05, 'l1_ratio': 0.9949664535744368, 'class_weight': None, 'fit_intercept': True, 'tol': 2.0244804856642757e-05, 'max_iter': 1576}. Best is trial 326 with value: 0.9497667555641287.

Best trial: 325. Best value: 0.949778:  65%|███████████████████████████████████████████████████████████████████████▎                                      | 324/500 [24:42<07:00,  2.39s/it]

[I 2026-05-19 18:02:21,459] Trial 325 finished with value: 0.9497784591892581 and parameters: {'solver': 'saga', 'C': 5.9909668307149846e-05, 'l1_ratio': 0.9897439042136817, 'class_weight': None, 'fit_intercept': True, 'tol': 2.126309301074045e-05, 'max_iter': 1609}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  65%|███████████████████████████████████████████████████████████████████████▌                                      | 325/500 [24:43<05:39,  1.94s/it]

[I 2026-05-19 18:02:22,350] Trial 329 finished with value: 0.9497477040091796 and parameters: {'solver': 'saga', 'C': 1.3892185508495552e-05, 'l1_ratio': 0.9939578380112144, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008596490006100903, 'max_iter': 1703}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  65%|███████████████████████████████████████████████████████████████████████▋                                      | 326/500 [24:43<04:43,  1.63s/it]

[I 2026-05-19 18:02:23,261] Trial 328 finished with value: 0.9496935466536571 and parameters: {'solver': 'saga', 'C': 1.453157683773558e-05, 'l1_ratio': 0.9826592935391707, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008904167920509055, 'max_iter': 1656}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  65%|███████████████████████████████████████████████████████████████████████▉                                      | 327/500 [24:50<08:41,  3.01s/it]

[I 2026-05-19 18:02:29,501] Trial 330 finished with value: 0.9497763784061215 and parameters: {'solver': 'saga', 'C': 3.6207672998375704e-05, 'l1_ratio': 0.9836129637657505, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009263610178236103, 'max_iter': 1682}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  66%|████████████████████████████████████████████████████████████████████████▏                                     | 328/500 [24:52<07:46,  2.71s/it]

[I 2026-05-19 18:02:31,513] Trial 331 finished with value: 0.9497174387555324 and parameters: {'solver': 'saga', 'C': 1.5594570212613248e-05, 'l1_ratio': 0.9853191039448965, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010451514074138104, 'max_iter': 1673}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  66%|████████████████████████████████████████████████████████████████████████▍                                     | 329/500 [24:59<11:14,  3.95s/it]

[I 2026-05-19 18:02:38,340] Trial 332 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.401280147814835e-05, 'l1_ratio': 0.9964001610843394, 'class_weight': None, 'fit_intercept': True, 'tol': 0.000889201780852457, 'max_iter': 1677}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  66%|████████████████████████████████████████████████████████████████████████▊                                     | 331/500 [25:01<07:02,  2.50s/it]

[I 2026-05-19 18:02:40,804] Trial 334 finished with value: 0.9497324374280385 and parameters: {'solver': 'saga', 'C': 1.5344192891257343e-05, 'l1_ratio': 0.9879726805280759, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009285975554159442, 'max_iter': 1675}. Best is trial 325 with value: 0.9497784591892581.
[I 2026-05-19 18:02:40,962] Trial 336 finished with value: 0.9497476174676681 and parameters: {'solver': 'saga', 'C': 1.5031348949332966e-05, 'l1_ratio': 0.9948055639735545, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008796253050991567, 'max_iter': 1730}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  66%|█████████████████████████████████████████████████████████████████████████                                     | 332/500 [25:02<05:23,  1.92s/it]

[I 2026-05-19 18:02:41,540] Trial 333 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.5297088355331148e-05, 'l1_ratio': 0.9972554992873797, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008731647213659639, 'max_iter': 1650}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  67%|█████████████████████████████████████████████████████████████████████████▎                                    | 333/500 [25:03<05:01,  1.80s/it]

[I 2026-05-19 18:02:43,062] Trial 335 finished with value: 0.9497527204008944 and parameters: {'solver': 'saga', 'C': 1.6890375382617913e-05, 'l1_ratio': 0.9902346146110288, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008664758717030495, 'max_iter': 1660}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  67%|█████████████████████████████████████████████████████████████████████████▍                                    | 334/500 [25:08<07:26,  2.69s/it]

[I 2026-05-19 18:02:47,824] Trial 337 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.1206383406643923e-05, 'l1_ratio': 0.99769638188496, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009295784935797816, 'max_iter': 1676}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  67%|█████████████████████████████████████████████████████████████████████████▋                                    | 335/500 [25:12<08:12,  2.99s/it]

[I 2026-05-19 18:02:51,512] Trial 338 finished with value: 0.9497451012675283 and parameters: {'solver': 'saga', 'C': 1.4358959696303487e-05, 'l1_ratio': 0.9906548844779898, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008627042238286535, 'max_iter': 1716}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  67%|█████████████████████████████████████████████████████████████████████████▉                                    | 336/500 [25:14<07:28,  2.73s/it]

[I 2026-05-19 18:02:53,647] Trial 339 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.4676953084218656e-05, 'l1_ratio': 0.9998240806246631, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008616735050309786, 'max_iter': 1716}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  67%|██████████████████████████████████████████████████████████████████████████▏                                   | 337/500 [25:19<09:05,  3.35s/it]

[I 2026-05-19 18:02:58,423] Trial 340 finished with value: 0.9497477800607014 and parameters: {'solver': 'saga', 'C': 1.59061823065917e-05, 'l1_ratio': 0.9957498836536793, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009000730092458492, 'max_iter': 1745}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  68%|██████████████████████████████████████████████████████████████████████████▎                                   | 338/500 [25:22<09:04,  3.36s/it]

[I 2026-05-19 18:03:01,814] Trial 342 finished with value: 0.9497477301174613 and parameters: {'solver': 'saga', 'C': 1.2177471589279463e-05, 'l1_ratio': 0.9948234004371034, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009274622981518151, 'max_iter': 1744}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  68%|██████████████████████████████████████████████████████████████████████████▊                                   | 340/500 [25:26<06:29,  2.43s/it]

[I 2026-05-19 18:03:05,355] Trial 344 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.2683838695978098e-05, 'l1_ratio': 0.9982380545951575, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008857023477573358, 'max_iter': 1734}. Best is trial 325 with value: 0.9497784591892581.
[I 2026-05-19 18:03:05,491] Trial 343 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.0854073950190835e-05, 'l1_ratio': 0.9998247490593273, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009118594402199408, 'max_iter': 1709}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  68%|███████████████████████████████████████████████████████████████████████████                                   | 341/500 [25:29<07:03,  2.66s/it]

[I 2026-05-19 18:03:08,715] Trial 341 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.0028808768466826e-05, 'l1_ratio': 0.9996484785074222, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0008829490521895863, 'max_iter': 1743}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  68%|███████████████████████████████████████████████████████████████████████████▏                                  | 342/500 [25:31<06:31,  2.48s/it]

[I 2026-05-19 18:03:10,752] Trial 345 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.0940958072735698e-05, 'l1_ratio': 0.9980749253997079, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009028129740685485, 'max_iter': 1751}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  69%|███████████████████████████████████████████████████████████████████████████▍                                  | 343/500 [25:35<07:45,  2.97s/it]

[I 2026-05-19 18:03:14,851] Trial 346 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.0218112801241066e-05, 'l1_ratio': 0.9973728664483243, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0014841560075293501, 'max_iter': 1731}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  69%|███████████████████████████████████████████████████████████████████████████▋                                  | 344/500 [25:37<06:51,  2.64s/it]

[I 2026-05-19 18:03:16,722] Trial 347 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.0509420934647455e-05, 'l1_ratio': 0.9995278371120095, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0014770771247548918, 'max_iter': 1746}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  69%|███████████████████████████████████████████████████████████████████████████▉                                  | 345/500 [25:42<08:46,  3.39s/it]

[I 2026-05-19 18:03:21,890] Trial 348 finished with value: 0.9497477548466164 and parameters: {'solver': 'saga', 'C': 1.0240790121931317e-05, 'l1_ratio': 0.9973712561008903, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001398964213247637, 'max_iter': 1745}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  69%|████████████████████████████████████████████████████████████████████████████                                  | 346/500 [25:45<08:17,  3.23s/it]

[I 2026-05-19 18:03:24,740] Trial 349 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.000931131746225e-05, 'l1_ratio': 0.999605271974714, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0014703740651810862, 'max_iter': 1773}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  69%|████████████████████████████████████████████████████████████████████████████▎                                 | 347/500 [25:47<07:04,  2.77s/it]

[I 2026-05-19 18:03:26,444] Trial 350 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.0985997777249956e-05, 'l1_ratio': 0.9893525080903, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0015060382214597766, 'max_iter': 1727}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  70%|████████████████████████████████████████████████████████████████████████████▌                                 | 348/500 [25:50<07:34,  2.99s/it]

[I 2026-05-19 18:03:29,951] Trial 351 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.017184669818561e-05, 'l1_ratio': 0.9978291714346792, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0015109271867514657, 'max_iter': 1760}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  70%|████████████████████████████████████████████████████████████████████████████▊                                 | 349/500 [25:52<06:48,  2.70s/it]

[I 2026-05-19 18:03:31,979] Trial 352 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.0639285837069806e-05, 'l1_ratio': 0.9981192344342302, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0015713887711850606, 'max_iter': 1778}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  70%|█████████████████████████████████████████████████████████████████████████████                                 | 350/500 [25:56<07:17,  2.91s/it]

[I 2026-05-19 18:03:35,382] Trial 353 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.0051553926236483e-05, 'l1_ratio': 0.9999256889559367, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0014812602051753596, 'max_iter': 1750}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  70%|█████████████████████████████████████████████████████████████████████████████▏                                | 351/500 [25:58<06:42,  2.70s/it]

[I 2026-05-19 18:03:37,593] Trial 355 finished with value: 0.9497482798689312 and parameters: {'solver': 'saga', 'C': 1.038069142710751e-05, 'l1_ratio': 0.9997771425130133, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0014744957634623822, 'max_iter': 1756}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  70%|█████████████████████████████████████████████████████████████████████████████▍                                | 352/500 [25:59<05:52,  2.38s/it]

[I 2026-05-19 18:03:39,225] Trial 354 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.0130916729942601e-05, 'l1_ratio': 0.9992148338438039, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0014882015679283215, 'max_iter': 1795}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  71%|█████████████████████████████████████████████████████████████████████████████▋                                | 353/500 [26:07<09:43,  3.97s/it]

[I 2026-05-19 18:03:46,904] Trial 357 finished with value: 0.9496819545569114 and parameters: {'solver': 'saga', 'C': 1.025626542653622e-05, 'l1_ratio': 0.9543153629060702, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0013284780894914482, 'max_iter': 1740}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  71%|█████████████████████████████████████████████████████████████████████████████▉                                | 354/500 [26:09<07:49,  3.22s/it]

[I 2026-05-19 18:03:48,354] Trial 356 finished with value: 0.9497476583824082 and parameters: {'solver': 'saga', 'C': 1.0128000539846097e-05, 'l1_ratio': 0.9964262481729402, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0014492988854070484, 'max_iter': 1746}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  71%|██████████████████████████████████████████████████████████████████████████████                                | 355/500 [26:09<06:04,  2.51s/it]

[I 2026-05-19 18:03:49,231] Trial 358 finished with value: 0.9496840289359557 and parameters: {'solver': 'saga', 'C': 1.049825715148476e-05, 'l1_ratio': 0.9597203522605184, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0015207560221132319, 'max_iter': 1791}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  71%|██████████████████████████████████████████████████████████████████████████████▎                               | 356/500 [26:13<07:01,  2.93s/it]

[I 2026-05-19 18:03:53,116] Trial 359 finished with value: 0.949619404434376 and parameters: {'solver': 'saga', 'C': 1.1655347889685375e-05, 'l1_ratio': 0.9597860209903271, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0015123026351831171, 'max_iter': 1792}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  71%|██████████████████████████████████████████████████████████████████████████████▌                               | 357/500 [26:16<06:53,  2.89s/it]

[I 2026-05-19 18:03:55,911] Trial 360 finished with value: 0.9496876669051794 and parameters: {'solver': 'saga', 'C': 1.0293394169160236e-05, 'l1_ratio': 0.9562977796996306, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0015738530172837361, 'max_iter': 1768}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  72%|██████████████████████████████████████████████████████████████████████████████▊                               | 358/500 [26:18<06:01,  2.55s/it]

[I 2026-05-19 18:03:57,649] Trial 363 finished with value: 0.9497125372536415 and parameters: {'solver': 'saga', 'C': 2.1214355606309553e-05, 'l1_ratio': 0.9581446412063428, 'class_weight': None, 'fit_intercept': True, 'tol': 0.004974063418371965, 'max_iter': 1763}. Best is trial 325 with value: 0.9497784591892581.
[I 2026-05-19 18:03:57,756] Trial 361 finished with value: 0.9497106237613145 and parameters: {'solver': 'saga', 'C': 2.0919779070692477e-05, 'l1_ratio': 0.9572726359125177, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0014369189115845272, 'max_iter': 1806}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  72%|███████████████████████████████████████████████████████████████████████████████▏                              | 360/500 [26:21<05:04,  2.17s/it]

[I 2026-05-19 18:04:01,141] Trial 362 finished with value: 0.949709721100156 and parameters: {'solver': 'saga', 'C': 2.085781590232322e-05, 'l1_ratio': 0.9562554738836269, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0013779964669200606, 'max_iter': 1796}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  72%|███████████████████████████████████████████████████████████████████████████████▍                              | 361/500 [26:26<06:42,  2.90s/it]

[I 2026-05-19 18:04:06,237] Trial 364 finished with value: 0.9497089019352778 and parameters: {'solver': 'saga', 'C': 2.0122717087374152e-05, 'l1_ratio': 0.966620201427399, 'class_weight': None, 'fit_intercept': True, 'tol': 0.003623845013920575, 'max_iter': 2011}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  72%|███████████████████████████████████████████████████████████████████████████████▋                              | 362/500 [26:30<06:47,  2.95s/it]

[I 2026-05-19 18:04:09,346] Trial 365 finished with value: 0.9497160187378905 and parameters: {'solver': 'saga', 'C': 2.13525685909987e-05, 'l1_ratio': 0.9625188826740769, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002629632883444802, 'max_iter': 1817}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  73%|███████████████████████████████████████████████████████████████████████████████▊                              | 363/500 [26:32<06:28,  2.83s/it]

[I 2026-05-19 18:04:11,868] Trial 366 finished with value: 0.9497077160869993 and parameters: {'solver': 'saga', 'C': 1.9909268185777912e-05, 'l1_ratio': 0.9686417302595717, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0017481850366460345, 'max_iter': 1997}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  73%|████████████████████████████████████████████████████████████████████████████████                              | 364/500 [26:36<07:00,  3.09s/it]

[I 2026-05-19 18:04:15,610] Trial 367 finished with value: 0.9497149972000356 and parameters: {'solver': 'saga', 'C': 2.065863258722054e-05, 'l1_ratio': 0.9680968994395441, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0018825516205654058, 'max_iter': 1941}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  73%|████████████████████████████████████████████████████████████████████████████████▎                             | 365/500 [26:38<06:15,  2.78s/it]

[I 2026-05-19 18:04:17,581] Trial 368 finished with value: 0.9497221239714879 and parameters: {'solver': 'saga', 'C': 2.1195505331944397e-05, 'l1_ratio': 0.9719094099292223, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0018955374328784643, 'max_iter': 2024}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  73%|████████████████████████████████████████████████████████████████████████████████▌                             | 366/500 [26:39<05:12,  2.33s/it]

[I 2026-05-19 18:04:18,805] Trial 370 finished with value: 0.9497706223475586 and parameters: {'solver': 'saga', 'C': 3.214437269532771e-05, 'l1_ratio': 0.973829641705717, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002483178509438644, 'max_iter': 1960}. Best is trial 325 with value: 0.9497784591892581.
[I 2026-05-19 18:04:18,944] Trial 369 finished with value: 0.9497222824440723 and parameters: {'solver': 'saga', 'C': 2.0990658717640693e-05, 'l1_ratio': 0.9747051232506895, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002276339191365055, 'max_iter': 1987}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  74%|████████████████████████████████████████████████████████████████████████████████▉                             | 368/500 [26:44<05:29,  2.50s/it]

[I 2026-05-19 18:04:24,244] Trial 371 finished with value: 0.9497775547278866 and parameters: {'solver': 'saga', 'C': 3.5289560352917496e-05, 'l1_ratio': 0.9747681581599382, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001028683291728975, 'max_iter': 1986}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  74%|█████████████████████████████████████████████████████████████████████████████████▏                            | 369/500 [26:49<06:30,  2.98s/it]

[I 2026-05-19 18:04:28,714] Trial 372 finished with value: 0.9497726121331127 and parameters: {'solver': 'saga', 'C': 3.3040401657370506e-05, 'l1_ratio': 0.9728420757334971, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001852199650038216, 'max_iter': 1967}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  74%|█████████████████████████████████████████████████████████████████████████████████▍                            | 370/500 [26:53<06:47,  3.14s/it]

[I 2026-05-19 18:04:32,291] Trial 373 finished with value: 0.9497707476318868 and parameters: {'solver': 'saga', 'C': 3.2242766974582546e-05, 'l1_ratio': 0.9769386498758471, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009776780172744651, 'max_iter': 1959}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 325. Best value: 0.949778:  74%|█████████████████████████████████████████████████████████████████████████████████▌                            | 371/500 [26:55<06:18,  2.93s/it]

[I 2026-05-19 18:04:34,681] Trial 374 finished with value: 0.9497733072408716 and parameters: {'solver': 'saga', 'C': 3.316150530624464e-05, 'l1_ratio': 0.9754145061888913, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010500643246720298, 'max_iter': 1671}. Best is trial 325 with value: 0.9497784591892581.

Best trial: 375. Best value: 0.949779:  74%|█████████████████████████████████████████████████████████████████████████████████▊                            | 372/500 [27:01<07:56,  3.72s/it]

[I 2026-05-19 18:04:40,453] Trial 375 finished with value: 0.9497786228357418 and parameters: {'solver': 'saga', 'C': 3.589260614496148e-05, 'l1_ratio': 0.9762895726243728, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010077913691764536, 'max_iter': 1677}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  75%|██████████████████████████████████████████████████████████████████████████████████                            | 373/500 [27:01<06:01,  2.85s/it]

[I 2026-05-19 18:04:41,096] Trial 378 finished with value: 0.9497681353369402 and parameters: {'solver': 'saga', 'C': 3.16647018859949e-05, 'l1_ratio': 0.9794645146352929, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009424037631226215, 'max_iter': 1670}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  75%|██████████████████████████████████████████████████████████████████████████████████▌                           | 375/500 [27:02<03:21,  1.61s/it]

[I 2026-05-19 18:04:41,681] Trial 376 finished with value: 0.9497709585069101 and parameters: {'solver': 'saga', 'C': 3.288162892864425e-05, 'l1_ratio': 0.9812383857969256, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009262597015668338, 'max_iter': 1690}. Best is trial 375 with value: 0.9497786228357418.
[I 2026-05-19 18:04:41,878] Trial 377 finished with value: 0.9497729152577644 and parameters: {'solver': 'saga', 'C': 3.343587358076176e-05, 'l1_ratio': 0.9803230946966293, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010440206762179266, 'max_iter': 1662}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  75%|██████████████████████████████████████████████████████████████████████████████████▋                           | 376/500 [27:08<06:04,  2.94s/it]

[I 2026-05-19 18:04:48,004] Trial 379 finished with value: 0.949770100867698 and parameters: {'solver': 'saga', 'C': 3.211897613314562e-05, 'l1_ratio': 0.9780976678831723, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010009234167208585, 'max_iter': 1685}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  75%|██████████████████████████████████████████████████████████████████████████████████▉                           | 377/500 [27:11<06:07,  2.99s/it]

[I 2026-05-19 18:04:51,098] Trial 380 finished with value: 0.9497613023450322 and parameters: {'solver': 'saga', 'C': 2.9777597226784438e-05, 'l1_ratio': 0.9778021790213424, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009190306007630575, 'max_iter': 1647}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  76%|███████████████████████████████████████████████████████████████████████████████████▏                          | 378/500 [27:15<06:29,  3.20s/it]

[I 2026-05-19 18:04:54,783] Trial 381 finished with value: 0.9497662424553182 and parameters: {'solver': 'saga', 'C': 3.07620710248804e-05, 'l1_ratio': 0.974983092770507, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010365382793624583, 'max_iter': 1916}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  76%|███████████████████████████████████████████████████████████████████████████████████▍                          | 379/500 [27:16<05:20,  2.65s/it]

[I 2026-05-19 18:04:56,148] Trial 244 finished with value: 0.9496300337560368 and parameters: {'solver': 'saga', 'C': 2.489607180223975, 'l1_ratio': 0.3571494226458107, 'class_weight': None, 'fit_intercept': True, 'tol': 4.889021779135681e-05, 'max_iter': 1098}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  76%|███████████████████████████████████████████████████████████████████████████████████▌                          | 380/500 [27:18<04:35,  2.29s/it]

[I 2026-05-19 18:04:57,606] Trial 382 finished with value: 0.9497624665729207 and parameters: {'solver': 'saga', 'C': 3.0002809727150726e-05, 'l1_ratio': 0.9775282829916176, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010214043441071385, 'max_iter': 2076}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  76%|███████████████████████████████████████████████████████████████████████████████████▊                          | 381/500 [27:25<07:42,  3.88s/it]

[I 2026-05-19 18:05:05,220] Trial 386 finished with value: 0.949740948275098 and parameters: {'solver': 'saga', 'C': 2.8750502006184202e-05, 'l1_ratio': 0.949645187030177, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010878567259960655, 'max_iter': 2083}. Best is trial 375 with value: 0.9497786228357418.
[I 2026-05-19 18:05:05,272] Trial 383 finished with value: 0.9497421561312303 and parameters: {'solver': 'saga', 'C': 3.464300627315825e-05, 'l1_ratio': 0.9480850130350499, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001074511354217014, 'max_iter': 1647}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  77%|████████████████████████████████████████████████████████████████████████████████████▍                         | 384/500 [27:26<03:14,  1.68s/it]

[I 2026-05-19 18:05:05,631] Trial 384 finished with value: 0.9497336642489662 and parameters: {'solver': 'saga', 'C': 3.3582226886140577e-05, 'l1_ratio': 0.9430046706174113, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011187202153514948, 'max_iter': 2073}. Best is trial 375 with value: 0.9497786228357418.
[I 2026-05-19 18:05:05,735] Trial 385 finished with value: 0.9497729830364301 and parameters: {'solver': 'saga', 'C': 3.3033428423962485e-05, 'l1_ratio': 0.9752073456848205, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0010199885885894648, 'max_iter': 2121}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  77%|████████████████████████████████████████████████████████████████████████████████████▋                         | 385/500 [27:32<05:24,  2.82s/it]

[I 2026-05-19 18:05:11,780] Trial 387 finished with value: 0.9497435189876005 and parameters: {'solver': 'saga', 'C': 3.540386285802248e-05, 'l1_ratio': 0.9488443793036363, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011266973887979171, 'max_iter': 2106}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  77%|████████████████████████████████████████████████████████████████████████████████████▉                         | 386/500 [27:37<06:20,  3.34s/it]

[I 2026-05-19 18:05:16,549] Trial 388 finished with value: 0.949729672320748 and parameters: {'solver': 'saga', 'C': 3.4166382403995315e-05, 'l1_ratio': 0.9410141102218741, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011253369301277188, 'max_iter': 2099}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  77%|█████████████████████████████████████████████████████████████████████████████████████▏                        | 387/500 [27:38<05:24,  2.88s/it]

[I 2026-05-19 18:05:18,221] Trial 389 finished with value: 0.9497319773694276 and parameters: {'solver': 'saga', 'C': 3.5985860204663964e-05, 'l1_ratio': 0.9423281516285692, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011012617961074912, 'max_iter': 2102}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  78%|█████████████████████████████████████████████████████████████████████████████████████▎                        | 388/500 [27:42<05:54,  3.17s/it]

[I 2026-05-19 18:05:22,127] Trial 391 finished with value: 0.9497403182741833 and parameters: {'solver': 'saga', 'C': 3.2870411601214614e-05, 'l1_ratio': 0.9471082165483495, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011175199281277003, 'max_iter': 2089}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 375. Best value: 0.949779:  78%|█████████████████████████████████████████████████████████████████████████████████████▌                        | 389/500 [27:43<04:32,  2.46s/it]

[I 2026-05-19 18:05:22,826] Trial 390 finished with value: 0.9497327310300264 and parameters: {'solver': 'saga', 'C': 3.7177537879446624e-05, 'l1_ratio': 0.9427612001406702, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001230934165596411, 'max_iter': 1907}. Best is trial 375 with value: 0.9497786228357418.

Best trial: 395. Best value: 0.94978:  78%|██████████████████████████████████████████████████████████████████████████████████████▌                        | 390/500 [27:46<04:52,  2.66s/it]

[I 2026-05-19 18:05:25,989] Trial 395 finished with value: 0.9497802392797107 and parameters: {'solver': 'saga', 'C': 3.755150279560464e-05, 'l1_ratio': 0.9743095530323451, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0032137033556347465, 'max_iter': 2175}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  78%|██████████████████████████████████████████████████████████████████████████████████████▊                        | 391/500 [27:49<04:57,  2.73s/it]

[I 2026-05-19 18:05:28,896] Trial 394 finished with value: 0.9497760056231602 and parameters: {'solver': 'saga', 'C': 3.43295187815775e-05, 'l1_ratio': 0.9760323784267243, 'class_weight': None, 'fit_intercept': True, 'tol': 0.001197455303788641, 'max_iter': 1900}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  78%|███████████████████████████████████████████████████████████████████████████████████████                        | 392/500 [27:50<04:09,  2.31s/it]

[I 2026-05-19 18:05:30,186] Trial 392 finished with value: 0.9497408149249462 and parameters: {'solver': 'saga', 'C': 3.631393621612517e-05, 'l1_ratio': 0.9471291733513395, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011889558200475123, 'max_iter': 2081}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  79%|███████████████████████████████████████████████████████████████████████████████████████▏                       | 393/500 [27:52<03:39,  2.06s/it]

[I 2026-05-19 18:05:31,651] Trial 393 finished with value: 0.9497777939925989 and parameters: {'solver': 'saga', 'C': 3.719691579786721e-05, 'l1_ratio': 0.9710582454494556, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0011559209093695007, 'max_iter': 2135}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  79%|███████████████████████████████████████████████████████████████████████████████████████▍                       | 394/500 [27:53<03:04,  1.74s/it]

[I 2026-05-19 18:05:32,665] Trial 396 finished with value: 0.9496218028293903 and parameters: {'solver': 'saga', 'C': 3.527716347094255e-05, 'l1_ratio': 0.9718856873091135, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0011960905285097365, 'max_iter': 1964}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  79%|███████████████████████████████████████████████████████████████████████████████████████▋                       | 395/500 [27:56<03:55,  2.24s/it]

[I 2026-05-19 18:05:36,058] Trial 397 finished with value: 0.9496184413807974 and parameters: {'solver': 'saga', 'C': 3.623949656199948e-05, 'l1_ratio': 0.9699993927356142, 'class_weight': None, 'fit_intercept': False, 'tol': 0.002432870938351158, 'max_iter': 2164}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  79%|███████████████████████████████████████████████████████████████████████████████████████▉                       | 396/500 [27:59<04:20,  2.51s/it]

[I 2026-05-19 18:05:39,198] Trial 398 finished with value: 0.9496207277310462 and parameters: {'solver': 'saga', 'C': 4.0860037202286314e-05, 'l1_ratio': 0.9748549950993337, 'class_weight': None, 'fit_intercept': False, 'tol': 0.00282108046918929, 'max_iter': 1926}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  79%|████████████████████████████████████████████████████████████████████████████████████████▏                      | 397/500 [28:02<04:29,  2.61s/it]

[I 2026-05-19 18:05:42,017] Trial 399 finished with value: 0.9495681475526849 and parameters: {'solver': 'saga', 'C': 4.434407062631508e-05, 'l1_ratio': 0.9718821018745069, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0031010752590473955, 'max_iter': 1965}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  80%|████████████████████████████████████████████████████████████████████████████████████████▎                      | 398/500 [28:06<05:11,  3.05s/it]

[I 2026-05-19 18:05:46,133] Trial 400 finished with value: 0.9496687204090979 and parameters: {'solver': 'saga', 'C': 2.806657969948972e-05, 'l1_ratio': 0.9752896127287708, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.002593789355350365, 'max_iter': 1864}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  80%|████████████████████████████████████████████████████████████████████████████████████████▌                      | 399/500 [28:08<04:25,  2.63s/it]

[I 2026-05-19 18:05:47,792] Trial 401 finished with value: 0.9497680543474006 and parameters: {'solver': 'saga', 'C': 4.579979973862356e-05, 'l1_ratio': 0.975292365683141, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0027091967873111122, 'max_iter': 2281}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  80%|████████████████████████████████████████████████████████████████████████████████████████▊                      | 400/500 [28:09<03:41,  2.21s/it]

[I 2026-05-19 18:05:49,020] Trial 402 finished with value: 0.9497685321057912 and parameters: {'solver': 'saga', 'C': 4.463167179337869e-05, 'l1_ratio': 0.9752911222634254, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0027955576430999394, 'max_iter': 1929}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  80%|█████████████████████████████████████████████████████████████████████████████████████████                      | 401/500 [28:14<04:46,  2.89s/it]

[I 2026-05-19 18:05:53,512] Trial 403 finished with value: 0.9497628479104543 and parameters: {'solver': 'saga', 'C': 4.9306610999217196e-05, 'l1_ratio': 0.9731433197130692, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0027687441988190685, 'max_iter': 2171}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  80%|█████████████████████████████████████████████████████████████████████████████████████████▏                     | 402/500 [28:17<04:43,  2.89s/it]

[I 2026-05-19 18:05:56,387] Trial 404 finished with value: 0.9495101679927425 and parameters: {'solver': 'saga', 'C': 4.8906930438126064e-05, 'l1_ratio': 0.9721043610817697, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0007054187256756256, 'max_iter': 2175}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  81%|█████████████████████████████████████████████████████████████████████████████████████████▍                     | 403/500 [28:17<03:25,  2.12s/it]

[I 2026-05-19 18:05:56,711] Trial 405 finished with value: 0.9497725371980058 and parameters: {'solver': 'saga', 'C': 4.712942113302322e-05, 'l1_ratio': 0.9700519687691062, 'class_weight': None, 'fit_intercept': True, 'tol': 0.002898247990735662, 'max_iter': 1927}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  81%|█████████████████████████████████████████████████████████████████████████████████████████▋                     | 404/500 [28:19<03:33,  2.23s/it]

[I 2026-05-19 18:05:59,189] Trial 406 finished with value: 0.949612456246587 and parameters: {'solver': 'saga', 'C': 4.983896293622077e-05, 'l1_ratio': 0.9740101457732411, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.003169899293157406, 'max_iter': 2202}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  81%|█████████████████████████████████████████████████████████████████████████████████████████▉                     | 405/500 [28:23<04:14,  2.68s/it]

[I 2026-05-19 18:06:02,924] Trial 407 finished with value: 0.9496158152882945 and parameters: {'solver': 'saga', 'C': 5.4623858810478064e-05, 'l1_ratio': 0.9735759398339764, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0029483983923306043, 'max_iter': 2256}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  81%|██████████████████████████████████████████████████████████████████████████████████████████▏                    | 406/500 [28:27<04:57,  3.16s/it]

[I 2026-05-19 18:06:07,224] Trial 409 finished with value: 0.9497732118154916 and parameters: {'solver': 'saga', 'C': 5.00369470983316e-05, 'l1_ratio': 0.9724041824723659, 'class_weight': None, 'fit_intercept': True, 'tol': 0.004027939495651375, 'max_iter': 1869}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  81%|██████████████████████████████████████████████████████████████████████████████████████████▎                    | 407/500 [28:29<04:00,  2.59s/it]

[I 2026-05-19 18:06:08,471] Trial 408 finished with value: 0.9496539882155108 and parameters: {'solver': 'saga', 'C': 2.7380966933774337e-05, 'l1_ratio': 0.9691129704640458, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0007224155255233732, 'max_iter': 1868}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  82%|██████████████████████████████████████████████████████████████████████████████████████████▌                    | 408/500 [28:30<03:30,  2.29s/it]

[I 2026-05-19 18:06:10,055] Trial 411 finished with value: 0.9497630688354202 and parameters: {'solver': 'saga', 'C': 5.247146563957336e-05, 'l1_ratio': 0.9742471108350994, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004383725215954988, 'max_iter': 2137}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  82%|██████████████████████████████████████████████████████████████████████████████████████████▊                    | 409/500 [28:31<02:48,  1.85s/it]

[I 2026-05-19 18:06:10,878] Trial 410 finished with value: 0.9496154658756097 and parameters: {'solver': 'saga', 'C': 5.421974063104733e-05, 'l1_ratio': 0.9730811087825022, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0030618315291986893, 'max_iter': 2147}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  82%|███████████████████████████████████████████████████████████████████████████████████████████▏                   | 411/500 [28:38<03:23,  2.28s/it]

[I 2026-05-19 18:06:17,230] Trial 412 finished with value: 0.94968740140883 and parameters: {'solver': 'saga', 'C': 5.2929640527561425e-05, 'l1_ratio': 0.9015723925556227, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0027173596621784695, 'max_iter': 2243}. Best is trial 395 with value: 0.9497802392797107.
[I 2026-05-19 18:06:17,374] Trial 414 finished with value: 0.9497063451941734 and parameters: {'solver': 'saga', 'C': 5.733677301690047e-05, 'l1_ratio': 0.9132754616956322, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004819758673310296, 'max_iter': 2270}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  82%|███████████████████████████████████████████████████████████████████████████████████████████▍                   | 412/500 [28:39<02:44,  1.87s/it]

[I 2026-05-19 18:06:18,290] Trial 413 finished with value: 0.9496908137371601 and parameters: {'solver': 'saga', 'C': 5.211011173592579e-05, 'l1_ratio': 0.9044632317215111, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0030952233536080207, 'max_iter': 2343}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  83%|███████████████████████████████████████████████████████████████████████████████████████████▋                   | 413/500 [28:40<02:29,  1.72s/it]

[I 2026-05-19 18:06:19,652] Trial 415 finished with value: 0.9497515475177758 and parameters: {'solver': 'saga', 'C': 6.190837451732844e-05, 'l1_ratio': 0.9687559632236424, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004385428444025156, 'max_iter': 2385}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  83%|███████████████████████████████████████████████████████████████████████████████████████████▉                   | 414/500 [28:45<04:06,  2.86s/it]

[I 2026-05-19 18:06:25,173] Trial 269 finished with value: 0.9496299786122823 and parameters: {'solver': 'saga', 'C': 14.910802989391502, 'l1_ratio': 0.37026456005963304, 'class_weight': None, 'fit_intercept': True, 'tol': 6.072433688808012e-05, 'max_iter': 1136}. Best is trial 395 with value: 0.9497802392797107.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 395. Best value: 0.94978:  83%|████████████████████████████████████████████████████████████████████████████████████████████▏                  | 415/500 [28:48<04:02,  2.86s/it]

[I 2026-05-19 18:06:28,022] Trial 416 finished with value: 0.9496880163394135 and parameters: {'solver': 'saga', 'C': 5.9884149048095234e-05, 'l1_ratio': 0.8994355287270555, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0033778407939070738, 'max_iter': 2288}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  83%|████████████████████████████████████████████████████████████████████████████████████████████▎                  | 416/500 [28:49<02:58,  2.12s/it]

[I 2026-05-19 18:06:28,429] Trial 419 finished with value: 0.9496924818032506 and parameters: {'solver': 'saga', 'C': 5.687023435953785e-05, 'l1_ratio': 0.9020339924026108, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.007077836277877905, 'max_iter': 2340}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  83%|████████████████████████████████████████████████████████████████████████████████████████████▌                  | 417/500 [28:49<02:20,  1.69s/it]

[I 2026-05-19 18:06:29,101] Trial 418 finished with value: 0.9497384275601328 and parameters: {'solver': 'saga', 'C': 6.170029315540046e-05, 'l1_ratio': 0.9355871441059358, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004666211886162689, 'max_iter': 2302}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  84%|████████████████████████████████████████████████████████████████████████████████████████████▊                  | 418/500 [28:50<01:52,  1.37s/it]

[I 2026-05-19 18:06:29,713] Trial 417 finished with value: 0.9496241529796784 and parameters: {'solver': 'saga', 'C': 2.683414279677294e-05, 'l1_ratio': 0.9022522646533092, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0048793750298973485, 'max_iter': 2016}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  84%|█████████████████████████████████████████████████████████████████████████████████████████████                  | 419/500 [28:53<02:27,  1.82s/it]

[I 2026-05-19 18:06:32,609] Trial 420 finished with value: 0.9496822963641997 and parameters: {'solver': 'saga', 'C': 5.929188912748135e-05, 'l1_ratio': 0.8949083717889087, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004435190573263012, 'max_iter': 2431}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  84%|█████████████████████████████████████████████████████████████████████████████████████████████▏                 | 420/500 [28:57<03:22,  2.53s/it]

[I 2026-05-19 18:06:36,789] Trial 421 finished with value: 0.9497402548368086 and parameters: {'solver': 'saga', 'C': 6.321683549853967e-05, 'l1_ratio': 0.9385772258481002, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006057307747231436, 'max_iter': 2397}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  84%|█████████████████████████████████████████████████████████████████████████████████████████████▍                 | 421/500 [29:00<03:29,  2.65s/it]

[I 2026-05-19 18:06:39,719] Trial 423 finished with value: 0.949741483701743 and parameters: {'solver': 'saga', 'C': 6.820277253351404e-05, 'l1_ratio': 0.9381302673140255, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004967640226419098, 'max_iter': 2331}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  84%|█████████████████████████████████████████████████████████████████████████████████████████████▋                 | 422/500 [29:00<02:34,  1.98s/it]

[I 2026-05-19 18:06:40,129] Trial 422 finished with value: 0.9497183585210539 and parameters: {'solver': 'saga', 'C': 2.596732782329647e-05, 'l1_ratio': 0.9431083711385388, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0040678973370954635, 'max_iter': 2375}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  85%|█████████████████████████████████████████████████████████████████████████████████████████████▉                 | 423/500 [29:03<02:54,  2.27s/it]

[I 2026-05-19 18:06:43,085] Trial 424 finished with value: 0.9497093617024269 and parameters: {'solver': 'saga', 'C': 2.871567622157428e-05, 'l1_ratio': 0.9376902891814914, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004289473459059547, 'max_iter': 2001}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  85%|██████████████████████████████████████████████████████████████████████████████████████████████▎                | 425/500 [29:11<03:31,  2.82s/it]

[I 2026-05-19 18:06:50,911] Trial 429 finished with value: 0.949725556956351 and parameters: {'solver': 'saga', 'C': 3.985329406199435e-05, 'l1_ratio': 0.945765376584337, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003931039747762238, 'max_iter': 1951}. Best is trial 395 with value: 0.9497802392797107.
[I 2026-05-19 18:06:51,111] Trial 425 finished with value: 0.9497171682625682 and parameters: {'solver': 'saga', 'C': 2.715012197801662e-05, 'l1_ratio': 0.942356704682091, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002292832397303055, 'max_iter': 2006}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  85%|██████████████████████████████████████████████████████████████████████████████████████████████▌                | 426/500 [29:12<02:31,  2.05s/it]

[I 2026-05-19 18:06:51,378] Trial 426 finished with value: 0.9497084601843552 and parameters: {'solver': 'saga', 'C': 2.8787894889197776e-05, 'l1_ratio': 0.9370618795845167, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0040848934631203615, 'max_iter': 2010}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  85%|██████████████████████████████████████████████████████████████████████████████████████████████▊                | 427/500 [29:12<01:59,  1.63s/it]

[I 2026-05-19 18:06:52,018] Trial 428 finished with value: 0.9497208699760662 and parameters: {'solver': 'saga', 'C': 2.9175808694211142e-05, 'l1_ratio': 0.9443963494449271, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0023077156706535003, 'max_iter': 2027}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  86%|███████████████████████████████████████████████████████████████████████████████████████████████                | 428/500 [29:13<01:41,  1.41s/it]

[I 2026-05-19 18:06:52,918] Trial 427 finished with value: 0.9497112693416503 and parameters: {'solver': 'saga', 'C': 2.8263398172025828e-05, 'l1_ratio': 0.9387423228121818, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004456253818316466, 'max_iter': 1999}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  86%|███████████████████████████████████████████████████████████████████████████████████████████████▏               | 429/500 [29:14<01:31,  1.29s/it]

[I 2026-05-19 18:06:53,945] Trial 430 finished with value: 0.9497152087356436 and parameters: {'solver': 'saga', 'C': 2.6878804957893495e-05, 'l1_ratio': 0.9412535967121886, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004018540253180106, 'max_iter': 1996}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  86%|███████████████████████████████████████████████████████████████████████████████████████████████▍               | 430/500 [29:20<03:01,  2.59s/it]

[I 2026-05-19 18:06:59,563] Trial 431 finished with value: 0.9497310902312563 and parameters: {'solver': 'saga', 'C': 2.74977666173466e-05, 'l1_ratio': 0.9504968513878135, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.004014101971070399, 'max_iter': 1983}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  86%|███████████████████████████████████████████████████████████████████████████████████████████████▋               | 431/500 [29:23<03:19,  2.88s/it]

[I 2026-05-19 18:07:03,128] Trial 432 finished with value: 0.9497347403883214 and parameters: {'solver': 'saga', 'C': 2.733829063530721e-05, 'l1_ratio': 0.9526221605111271, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0022298981014824766, 'max_iter': 1955}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  86%|███████████████████████████████████████████████████████████████████████████████████████████████▉               | 432/500 [29:24<02:36,  2.30s/it]

[I 2026-05-19 18:07:04,083] Trial 434 finished with value: 0.9495769685093114 and parameters: {'solver': 'saga', 'C': 3.967081683283078e-05, 'l1_ratio': 0.961552316004241, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0022461497610896087, 'max_iter': 1956}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  87%|████████████████████████████████████████████████████████████████████████████████████████████████▏              | 433/500 [29:25<01:57,  1.75s/it]

[I 2026-05-19 18:07:04,523] Trial 433 finished with value: 0.9497408302534673 and parameters: {'solver': 'saga', 'C': 4.0088793625754855e-05, 'l1_ratio': 0.9562408082068626, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0038134419119259058, 'max_iter': 1991}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  87%|████████████████████████████████████████████████████████████████████████████████████████████████▌              | 435/500 [29:34<03:08,  2.90s/it]

[I 2026-05-19 18:07:14,061] Trial 438 finished with value: 0.9497572884675763 and parameters: {'solver': 'saga', 'C': 4.6710034687110895e-05, 'l1_ratio': 0.9683304744556578, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0035230565529066225, 'max_iter': 2162}. Best is trial 395 with value: 0.9497802392797107.
[I 2026-05-19 18:07:14,189] Trial 437 finished with value: 0.9497438274596144 and parameters: {'solver': 'saga', 'C': 4.173227181692685e-05, 'l1_ratio': 0.9586017644620098, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0023106703472336584, 'max_iter': 2174}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  87%|████████████████████████████████████████████████████████████████████████████████████████████████▊              | 436/500 [29:36<02:36,  2.45s/it]

[I 2026-05-19 18:07:15,588] Trial 439 finished with value: 0.9497494434965654 and parameters: {'solver': 'saga', 'C': 4.1174167381820856e-05, 'l1_ratio': 0.9623762076740016, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0020810292643155016, 'max_iter': 1876}. Best is trial 395 with value: 0.9497802392797107.
[I 2026-05-19 18:07:15,644] Trial 440 finished with value: 0.9497532142078929 and parameters: {'solver': 'saga', 'C': 4.174480701234393e-05, 'l1_ratio': 0.9647390595211484, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003501367757886482, 'max_iter': 1887}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████▏             | 438/500 [29:36<01:25,  1.37s/it]

[I 2026-05-19 18:07:15,839] Trial 436 finished with value: 0.949744754029491 and parameters: {'solver': 'saga', 'C': 3.465388625435344e-05, 'l1_ratio': 0.9581378234043164, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.002260741587352372, 'max_iter': 1901}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████▍             | 439/500 [29:39<01:50,  1.81s/it]

[I 2026-05-19 18:07:18,962] Trial 435 finished with value: 0.9497464328062974 and parameters: {'solver': 'saga', 'C': 2.7820215943531907e-05, 'l1_ratio': 0.9587523168566461, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0022184933061581502, 'max_iter': 1884}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████▋             | 440/500 [29:45<02:45,  2.76s/it]

[I 2026-05-19 18:07:24,398] Trial 441 finished with value: 0.9497673288197257 and parameters: {'solver': 'saga', 'C': 4.046701279734238e-05, 'l1_ratio': 0.9732009694840981, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0020178592266823793, 'max_iter': 1890}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  88%|█████████████████████████████████████████████████████████████████████████████████████████████████▉             | 441/500 [29:46<02:21,  2.39s/it]

[I 2026-05-19 18:07:25,821] Trial 442 finished with value: 0.9497676930431996 and parameters: {'solver': 'saga', 'C': 4.239566150592634e-05, 'l1_ratio': 0.9739287820185958, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0034032609765452964, 'max_iter': 2143}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  88%|██████████████████████████████████████████████████████████████████████████████████████████████████             | 442/500 [29:48<02:08,  2.22s/it]

[I 2026-05-19 18:07:27,573] Trial 444 finished with value: 0.9497698183421356 and parameters: {'solver': 'saga', 'C': 4.195195541408157e-05, 'l1_ratio': 0.9753127591432579, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0026112908258732834, 'max_iter': 2175}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████▎            | 443/500 [29:49<01:49,  1.93s/it]

[I 2026-05-19 18:07:28,781] Trial 443 finished with value: 0.9497696566495879 and parameters: {'solver': 'saga', 'C': 4.284513146766339e-05, 'l1_ratio': 0.9754572383407827, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0033519268285011365, 'max_iter': 2151}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████▌            | 444/500 [29:52<02:00,  2.16s/it]

[I 2026-05-19 18:07:31,508] Trial 446 pruned.

Best trial: 395. Best value: 0.94978:  89%|██████████████████████████████████████████████████████████████████████████████████████████████████▊            | 445/500 [29:55<02:20,  2.55s/it]

[I 2026-05-19 18:07:35,017] Trial 448 finished with value: 0.9497647636743063 and parameters: {'solver': 'saga', 'C': 4.315230727056529e-05, 'l1_ratio': 0.9723264465203824, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.008812795586778912, 'max_iter': 1866}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████            | 446/500 [29:56<01:50,  2.05s/it]

[I 2026-05-19 18:07:35,869] Trial 447 finished with value: 0.9497716731210776 and parameters: {'solver': 'saga', 'C': 4.2915060622601975e-05, 'l1_ratio': 0.9772504389677739, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005638576132294606, 'max_iter': 2138}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████▏           | 447/500 [29:57<01:33,  1.77s/it]

[I 2026-05-19 18:07:36,979] Trial 445 finished with value: 0.9497703066866687 and parameters: {'solver': 'saga', 'C': 4.1907457083117514e-05, 'l1_ratio': 0.9758130696026773, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0026986552231615993, 'max_iter': 1869}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████▍           | 448/500 [29:59<01:33,  1.79s/it]

[I 2026-05-19 18:07:38,815] Trial 449 finished with value: 0.9497527042603722 and parameters: {'solver': 'saga', 'C': 7.73282954761148e-05, 'l1_ratio': 0.9760085676616561, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0018656862111627497, 'max_iter': 2146}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████▋           | 449/500 [30:00<01:15,  1.47s/it]

[I 2026-05-19 18:07:39,539] Trial 450 finished with value: 0.9497717341234555 and parameters: {'solver': 'saga', 'C': 4.301897474105481e-05, 'l1_ratio': 0.9772288543461627, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005988370819765133, 'max_iter': 2155}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  90%|███████████████████████████████████████████████████████████████████████████████████████████████████▉           | 450/500 [30:05<02:11,  2.64s/it]

[I 2026-05-19 18:07:44,908] Trial 451 finished with value: 0.9496168728403631 and parameters: {'solver': 'saga', 'C': 0.1046021506914958, 'l1_ratio': 0.977308020292795, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.005794742180039941, 'max_iter': 1870}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████           | 451/500 [30:09<02:27,  3.01s/it]

[I 2026-05-19 18:07:48,797] Trial 452 finished with value: 0.9497362142580968 and parameters: {'solver': 'saga', 'C': 2.202282279080453e-05, 'l1_ratio': 0.9799410557374623, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0019579401105188675, 'max_iter': 1847}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  90%|████████████████████████████████████████████████████████████████████████████████████████████████████▎          | 452/500 [30:12<02:17,  2.87s/it]

[I 2026-05-19 18:07:51,338] Trial 460 pruned.

Best trial: 395. Best value: 0.94978:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████▌          | 453/500 [30:12<01:37,  2.07s/it]

[I 2026-05-19 18:07:51,550] Trial 454 finished with value: 0.9497536508614409 and parameters: {'solver': 'saga', 'C': 7.70727667895193e-05, 'l1_ratio': 0.9789698347670328, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001826088645312168, 'max_iter': 2082}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  91%|████████████████████████████████████████████████████████████████████████████████████████████████████▊          | 454/500 [30:12<01:10,  1.54s/it]

[I 2026-05-19 18:07:51,828] Trial 453 finished with value: 0.9497740010971926 and parameters: {'solver': 'saga', 'C': 2.102576462615025e-05, 'l1_ratio': 0.9735660898536069, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0017456926584682466, 'max_iter': 2080}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████          | 455/500 [30:18<02:02,  2.72s/it]

[I 2026-05-19 18:07:57,308] Trial 456 finished with value: 0.9497567316484552 and parameters: {'solver': 'saga', 'C': 7.186398976304381e-05, 'l1_ratio': 0.9805635909759793, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00273026284515726, 'max_iter': 2212}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 456/500 [30:18<01:27,  1.99s/it]

[I 2026-05-19 18:07:57,569] Trial 455 finished with value: 0.9496660648710685 and parameters: {'solver': 'saga', 'C': 2.10890019805094e-05, 'l1_ratio': 0.9193798604135277, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0029074293938923606, 'max_iter': 2075}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  91%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍         | 457/500 [30:19<01:09,  1.62s/it]

[I 2026-05-19 18:07:58,318] Trial 457 finished with value: 0.9497238595241759 and parameters: {'solver': 'saga', 'C': 7.362565710019582e-05, 'l1_ratio': 0.9235939849600606, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0027792561976150414, 'max_iter': 2237}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▋         | 458/500 [30:20<01:04,  1.53s/it]

[I 2026-05-19 18:07:59,654] Trial 458 finished with value: 0.9496853071569419 and parameters: {'solver': 'saga', 'C': 1.9489471578837174e-05, 'l1_ratio': 0.9258143049099559, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006069771369858043, 'max_iter': 2093}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  92%|█████████████████████████████████████████████████████████████████████████████████████████████████████▉         | 459/500 [30:21<01:01,  1.50s/it]

[I 2026-05-19 18:08:01,077] Trial 459 finished with value: 0.9496573171115832 and parameters: {'solver': 'saga', 'C': 1.8900854028592144e-05, 'l1_ratio': 0.914784359845194, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005757018838686322, 'max_iter': 2227}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████         | 460/500 [30:23<01:04,  1.62s/it]

[I 2026-05-19 18:08:02,988] Trial 462 pruned.

Best trial: 395. Best value: 0.94978:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎        | 461/500 [30:26<01:18,  2.02s/it]

[I 2026-05-19 18:08:05,951] Trial 461 finished with value: 0.9497286304799063 and parameters: {'solver': 'saga', 'C': 7.261333174075415e-05, 'l1_ratio': 0.9268516284970747, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006661334669738321, 'max_iter': 2269}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████▌        | 462/500 [30:28<01:18,  2.05s/it]

[I 2026-05-19 18:08:08,084] Trial 465 pruned.

Best trial: 395. Best value: 0.94978:  93%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊        | 463/500 [30:33<01:41,  2.75s/it]

[I 2026-05-19 18:08:12,463] Trial 463 finished with value: 0.9497273143499472 and parameters: {'solver': 'saga', 'C': 8.333474617255639e-05, 'l1_ratio': 0.9239982085615347, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.005885013338888363, 'max_iter': 2079}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████        | 464/500 [30:35<01:29,  2.49s/it]

[I 2026-05-19 18:08:14,353] Trial 464 finished with value: 0.949727238683257 and parameters: {'solver': 'saga', 'C': 7.628438196472214e-05, 'l1_ratio': 0.9269477265441762, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0028012422678754603, 'max_iter': 2264}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏       | 465/500 [30:38<01:41,  2.90s/it]

[I 2026-05-19 18:08:18,210] Trial 466 finished with value: 0.9496855428520382 and parameters: {'solver': 'saga', 'C': 2.1026217505842545e-05, 'l1_ratio': 0.9263847020226602, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006106107372817449, 'max_iter': 2060}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████▍       | 466/500 [30:39<01:19,  2.33s/it]

[I 2026-05-19 18:08:19,222] Trial 467 finished with value: 0.9497398417402245 and parameters: {'solver': 'saga', 'C': 2.1404853784768714e-05, 'l1_ratio': 0.9541182417495239, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.006065048518670261, 'max_iter': 2054}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  93%|███████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 467/500 [30:40<01:04,  1.95s/it]

[I 2026-05-19 18:08:20,277] Trial 468 finished with value: 0.94973359796481 and parameters: {'solver': 'saga', 'C': 1.8737758756522693e-05, 'l1_ratio': 0.9494331075097907, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0067518638938824024, 'max_iter': 2078}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  94%|███████████████████████████████████████████████████████████████████████████████████████████████████████▉       | 468/500 [30:45<01:23,  2.62s/it]

[I 2026-05-19 18:08:24,467] Trial 470 finished with value: 0.9497375933104033 and parameters: {'solver': 'saga', 'C': 2.4379654402083878e-05, 'l1_ratio': 0.9538197309111297, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.003078884005134684, 'max_iter': 2047}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████       | 469/500 [30:45<01:02,  2.02s/it]

[I 2026-05-19 18:08:25,072] Trial 472 finished with value: 0.9497453925281082 and parameters: {'solver': 'saga', 'C': 2.3433013530551656e-05, 'l1_ratio': 0.9573413280733926, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.00867287268267336, 'max_iter': 2042}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████▎      | 470/500 [30:54<01:59,  3.98s/it]

[I 2026-05-19 18:08:33,639] Trial 474 finished with value: 0.9497415910966709 and parameters: {'solver': 'saga', 'C': 2.39242256474853e-05, 'l1_ratio': 0.9558061141830019, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0034318185170923044, 'max_iter': 2048}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████▌      | 471/500 [30:55<01:26,  2.99s/it]

[I 2026-05-19 18:08:34,317] Trial 473 pruned.

Best trial: 395. Best value: 0.94978:  94%|████████████████████████████████████████████████████████████████████████████████████████████████████████▊      | 472/500 [30:59<01:34,  3.38s/it]

[I 2026-05-19 18:08:38,620] Trial 478 finished with value: 0.9497421358603981 and parameters: {'solver': 'saga', 'C': 3.493974080297963e-05, 'l1_ratio': 0.9565804491744034, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.008001315058967725, 'max_iter': 1933}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████      | 473/500 [31:00<01:12,  2.70s/it]

[I 2026-05-19 18:08:39,710] Trial 476 finished with value: 0.949739442513392 and parameters: {'solver': 'saga', 'C': 3.6394998165480105e-05, 'l1_ratio': 0.9548671222906973, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0017516257691528746, 'max_iter': 2050}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▏     | 474/500 [31:03<01:11,  2.74s/it]

[I 2026-05-19 18:08:42,574] Trial 469 finished with value: 0.9490390030643796 and parameters: {'solver': 'saga', 'C': 2.2570114343282302e-05, 'l1_ratio': 0.2104724077780158, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.614107999481196e-06, 'max_iter': 4861}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▍     | 475/500 [31:04<00:56,  2.28s/it]

[I 2026-05-19 18:08:43,753] Trial 471 finished with value: 0.9497373441021404 and parameters: {'solver': 'saga', 'C': 2.2882317018790317e-05, 'l1_ratio': 0.9533410585716444, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.2789268815404344e-06, 'max_iter': 2034}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▋     | 476/500 [31:05<00:45,  1.91s/it]

[I 2026-05-19 18:08:44,810] Trial 477 pruned.

Best trial: 395. Best value: 0.94978:  95%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉     | 477/500 [31:15<01:36,  4.20s/it]

[I 2026-05-19 18:08:54,346] Trial 475 finished with value: 0.9497406568824502 and parameters: {'solver': 'saga', 'C': 2.283225816373197e-05, 'l1_ratio': 0.9550182756053596, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.731057439493189e-06, 'max_iter': 4808}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████     | 478/500 [31:18<01:30,  4.10s/it]

[I 2026-05-19 18:08:58,222] Trial 481 finished with value: 0.949778854873732 and parameters: {'solver': 'saga', 'C': 3.5397291598607375e-05, 'l1_ratio': 0.9804749256293901, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0012352976884378653, 'max_iter': 1820}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▎    | 479/500 [31:19<01:04,  3.08s/it]

[I 2026-05-19 18:08:58,878] Trial 482 finished with value: 0.9497795064135282 and parameters: {'solver': 'saga', 'C': 3.796753251487434e-05, 'l1_ratio': 0.9832700143376892, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0017808141711416967, 'max_iter': 1832}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 480/500 [31:22<01:01,  3.08s/it]

[I 2026-05-19 18:09:01,995] Trial 483 finished with value: 0.949772705616617 and parameters: {'solver': 'saga', 'C': 4.573781054675609e-05, 'l1_ratio': 0.979073386097937, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0012604820856291499, 'max_iter': 1822}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊    | 481/500 [31:23<00:45,  2.39s/it]

[I 2026-05-19 18:09:02,780] Trial 480 finished with value: 0.9497787616627372 and parameters: {'solver': 'saga', 'C': 3.5399234861970466e-05, 'l1_ratio': 0.9803203817250628, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 6.773325995663991e-06, 'max_iter': 1971}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████    | 482/500 [31:24<00:37,  2.08s/it]

[I 2026-05-19 18:09:04,122] Trial 479 finished with value: 0.9497794802215813 and parameters: {'solver': 'saga', 'C': 3.466052099517365e-05, 'l1_ratio': 0.9823636391780217, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.304106341023734e-06, 'max_iter': 1825}. Best is trial 395 with value: 0.9497802392797107.
[I 2026-05-19 18:09:04,128] Trial 484 finished with value: 0.9497742557332669 and parameters: {'solver': 'saga', 'C': 4.716579247882445e-05, 'l1_ratio': 0.9814379786656402, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0012709598673371477, 'max_iter': 1823}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 484/500 [31:27<00:26,  1.63s/it]

[I 2026-05-19 18:09:06,343] Trial 485 finished with value: 0.9497748247638718 and parameters: {'solver': 'saga', 'C': 4.6938490509521865e-05, 'l1_ratio': 0.9821516323850733, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0013014857441897602, 'max_iter': 2175}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋   | 485/500 [31:29<00:25,  1.72s/it]

[I 2026-05-19 18:09:08,328] Trial 487 finished with value: 0.9495466912998294 and parameters: {'solver': 'saga', 'C': 4.6433199717100436e-05, 'l1_ratio': 0.748408136781364, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001336376913016604, 'max_iter': 2165}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▉   | 486/500 [31:30<00:22,  1.59s/it]

[I 2026-05-19 18:09:09,576] Trial 486 finished with value: 0.9497794333719891 and parameters: {'solver': 'saga', 'C': 3.512528835427813e-05, 'l1_ratio': 0.9823893497948251, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0013181492928578333, 'max_iter': 1840}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  97%|████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 487/500 [31:35<00:32,  2.52s/it]

[I 2026-05-19 18:09:14,566] Trial 488 finished with value: 0.949563457950342 and parameters: {'solver': 'saga', 'C': 4.873287445193275e-05, 'l1_ratio': 0.9819319781318586, 'class_weight': None, 'fit_intercept': False, 'tol': 0.0012411057411764509, 'max_iter': 1859}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 488/500 [31:41<00:41,  3.45s/it]

[I 2026-05-19 18:09:20,417] Trial 494 pruned.

Best trial: 395. Best value: 0.94978:  98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌  | 489/500 [31:43<00:35,  3.27s/it]

[I 2026-05-19 18:09:23,213] Trial 489 finished with value: 0.9497733475787943 and parameters: {'solver': 'saga', 'C': 4.992006234949661e-05, 'l1_ratio': 0.98311005728494, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0012402561831558914, 'max_iter': 1940}. Best is trial 395 with value: 0.9497802392797107.
[I 2026-05-19 18:09:23,280] Trial 490 finished with value: 0.9497741191310279 and parameters: {'solver': 'saga', 'C': 4.920384712154159e-05, 'l1_ratio': 0.9836394115901548, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0012795013550533317, 'max_iter': 1820}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████  | 491/500 [31:44<00:17,  1.97s/it]

[I 2026-05-19 18:09:23,985] Trial 496 pruned.

Best trial: 395. Best value: 0.94978:  98%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 492/500 [31:47<00:17,  2.14s/it]

[I 2026-05-19 18:09:26,651] Trial 491 finished with value: 0.9497752942696115 and parameters: {'solver': 'saga', 'C': 4.959025544116688e-05, 'l1_ratio': 0.9871029936303114, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0012845785692137037, 'max_iter': 1810}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍ | 493/500 [31:48<00:12,  1.78s/it]

[I 2026-05-19 18:09:27,414] Trial 492 finished with value: 0.9497725797735386 and parameters: {'solver': 'saga', 'C': 5.103607847785962e-05, 'l1_ratio': 0.9828540787734594, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.0012570628161158047, 'max_iter': 1833}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋ | 494/500 [31:48<00:08,  1.42s/it]

[I 2026-05-19 18:09:27,840] Trial 493 finished with value: 0.9497730720373057 and parameters: {'solver': 'saga', 'C': 5.0826983721191403e-05, 'l1_ratio': 0.9843619713481119, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 0.001313883158652249, 'max_iter': 1811}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 495/500 [31:57<00:18,  3.62s/it]

[I 2026-05-19 18:09:37,186] Trial 495 finished with value: 0.9497677244363645 and parameters: {'solver': 'saga', 'C': 5.8115171313279286e-05, 'l1_ratio': 0.98459968308412, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 9.11077975522003e-06, 'max_iter': 1885}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 496/500 [32:00<00:13,  3.27s/it]

[I 2026-05-19 18:09:39,582] Trial 497 finished with value: 0.9497548176896181 and parameters: {'solver': 'saga', 'C': 5.912310369517483e-05, 'l1_ratio': 0.9986183389011533, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 5.191581939898335e-06, 'max_iter': 1828}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978:  99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 497/500 [32:01<00:08,  2.70s/it]

[I 2026-05-19 18:09:40,870] Trial 498 finished with value: 0.9497500970481662 and parameters: {'solver': 'saga', 'C': 5.847937286156731e-05, 'l1_ratio': 0.9997596863487951, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 9.21753251116308e-06, 'max_iter': 1818}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▌| 498/500 [32:04<00:05,  2.69s/it]

[I 2026-05-19 18:09:43,546] Trial 499 finished with value: 0.9497544764364909 and parameters: {'solver': 'saga', 'C': 6.279473632323208e-05, 'l1_ratio': 0.9997721505379096, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 8.624430803090059e-06, 'max_iter': 1815}. Best is trial 395 with value: 0.9497802392797107.

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/sklearn/linear_model/_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
Best trial: 395. Best value: 0.94978: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 499/500 [40:14<02:26, 146.11s/it]

[I 2026-05-19 18:17:53,524] Trial 16 finished with value: 0.9496137572794842 and parameters: {'solver': 'saga', 'C': 80.64109187859468, 'l1_ratio': 0.7119692413549155, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.0914959047153115e-05, 'max_iter': 1667}. Best is trial 395 with value: 0.9497802392797107.

Best trial: 395. Best value: 0.94978: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [50:33<00:00,  6.07s/it]

[I 2026-05-19 18:28:12,446] Trial 5 finished with value: 0.949613760370292 and parameters: {'solver': 'saga', 'C': 19.08665494910593, 'l1_ratio': 0.3143302677307699, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 2.748723624958948e-06, 'max_iter': 3821}. Best is trial 395 with value: 0.9497802392797107.
Best trial score:
0.9497802392797107

Best params:
{'solver': 'saga', 'C': 3.755150279560464e-05, 'l1_ratio': 0.9743095530323451, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0032137033556347465, 'max_iter': 2175}

In [50]:
stacking_lg = make_pipeline(
    DropFeatures(features_to_drop),
    StandardScaler(),
    LogisticRegression(**study.best_params)
).fit(X_train_enc, y_train.PitNextLap)

# Submission

In [53]:
submission = pd.read_csv('../data/raw/sample_submission.csv')

In [54]:
submission['PitNextLap'] = stacking_lg.predict_proba(X_test_enc)[:, 1]

ValueError: Input X contains infinity or a value too large for dtype('float64').

In [ ]:
submission.to_csv('../data/submission/submission.csv', index=False)